### ISSUE TITLE
[Usage]: Request for vllm project to support OpenAI's /v1/models endpoint

### ISSUE THREAD

**Issue by xddun** [vllm-project/vllm#10029]
### Your current environment

I would like to request that the vllm project support OpenAI’s /v1/models endpoint. When using the Open WebUI framework, this endpoint is required to view the available models, but the vllm project currently does not provide support for it.

### How would you like to use vllm

I would like to request that the vllm project support OpenAI’s /v1/models endpoint. When using the Open WebUI framework, this endpoint is required to view the available models, but the vllm project currently does not provide support for it.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
We do have a `/v1/models/` endpoint here: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py#L316

**Comment by xddun** [comment]
Thank you for the response. It seems I made a mistake in my operations yesterday, which caused the interface not to display. I retried it, and now it works.

![image](https://github.com/user-attachments/assets/879bd50c-cfa2-4b78-a544-69ab4bdbb19d)
