### ISSUE TITLE
[Misc]: HW Configuration for A100 CI Benchmark

### ISSUE THREAD

**Issue by dtoya** [vllm-project/vllm#10026]
### Anything you want to discuss about vllm.

Is it possible to share HW configuration of A100 used in CI Benchmark result https://perf.vllm.ai/ ?  Especially, it is helpful to know which of A100-40GB or A100-80GB is used.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
A100-SXM4-80GB

**Comment by dtoya** [comment]
Thank you for your answer.
