### ISSUE TITLE
question with llm engine settings using api_server.

### ISSUE THREAD

**Issue by RavenLeeANU** [vllm-project/vllm#1003]
Hi,

I am using OpenAI API 

python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen-7B --host 0.0.0.0 --port 8001 --trust-remote-code

to post a quest like:

{
"model":"Qwen/Qwen-7B",
"messages":[{"role":"user","content":"Tell me a story"}],
"stream":false,
"temperature":0.7,
"max_tokens":500
}

the server side stats shows:

Received request cmpl-bd26ae24cc03420994e9cf497e3b4530: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\nTell me a story<|im_end|>\n<|im_start|>assistant\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.7, top_p=1.0, top_k=-1, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], ignore_eos=False, max_tokens=500, logprobs=None), prompt token ids: [151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 40451, 752, 264, 3364, 151645, 198, 151644, 77091, 198].
INFO 09-10 12:13:24 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 09-10 12:13:29 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.6%, CPU KV cache usage: 0.0%
INFO 09-10 12:13:34 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.8%, CPU KV cache usage: 0.0%
INFO 09-10 12:13:39 llm_engine.py:613] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.9%, CPU KV cache usage: 0.0%
INFO 09-10 12:13:41 async_llm_engine.py:100] Finished request cmpl-bd26ae24cc03420994e9cf497e3b4530.

which indicates generation is slow(0-20tokens/s), taking response more than 17+s. any hints about what am I doing wrong? thanks.

gpu params are: 

 NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10          On   | 00000000:00:09.0 Off |                    0 |
|  0%   40C    P0    55W / 150W |  19207MiB / 23028MiB |      0%      Default |
|                               |                      |                  N/A |

**Comment by lonngxiang** [comment]
prompt格式写的有问题

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
