### ISSUE TITLE
[Bug]: math-shepherd-mistral-7b-prm does not support the 'embedding' task. Supported tasks: {'generate'}

### ISSUE THREAD

**Issue by KADCA21** [vllm-project/vllm#10035]
### Your current environment

I thought math-shepherd-mistral-7b-prm has already supported 'embedding' task according to this [PR](https://github.com/vllm-project/vllm/pull/9697)

### 🐛 Describe the bug

Any way to use math-shepherd-mistral-7b-prm in embedding mode?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Which version of vLLM are you using? This is not in the latest release, so you have to use vLLM from main branch.
