### ISSUE TITLE
[Doc]: Does vllm support function call

### ISSUE THREAD

**Issue by leoneyar** [vllm-project/vllm#10066]
### 📚 The doc issue

For custom LLM, use vllm for whether or not to support function call

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Yes, please read the [docs](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#tool-calling-in-the-chat-completion-api).
