### ISSUE TITLE
[Doc]: openai_chat_completion_client_for_multimodal.py error

### ISSUE THREAD

**Issue by johnson7788** [vllm-project/vllm#10078]
### 📚 The doc issue

  vllm serve microsoft/Phi-3.5-vision-instruct --dtype auto --trust-remote-code --max_model_len 8192 --limit-mm-per-prompt image=2
   
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'extra_forbidden', 'loc': ('body', 'max_completion_tokens'), 'msg': 'Extra inputs are not permitted', 'input': 64}]", 'type': 'BadRequestError', 'param': None, 'code': 400}

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should update your `openai` version to support `max_completion_tokens`.

**Comment by gcalmettes** [comment]
@johnson7788 the new `max_completion_tokens` field ([#9837](https://github.com/vllm-project/vllm/pull/9837)) is supported in the latest vllm release. Using `>v0.6.4` should fix your issue.
