### ISSUE TITLE
invalid dtype for bias

### ISSUE THREAD

**Issue by zxyever** [vllm-project/vllm#1007]
RuntimeError: invalid dtype for bias - should match query's dtype

**Comment by raihan0824** [comment]
same problem when loading bloom model

**Comment by WoosukKwon** [comment]
Hi @zxyever @raihan0824, the bug is fixed in vLLM v0.1.7. Please upgrade vLLM with
```bash
pip install vllm --upgrade
```
and try again. Sorry for the inconvenience.
