### ISSUE TITLE
error when running bloom model

### ISSUE THREAD

**Issue by raihan0824** [vllm-project/vllm#1008]
```
RuntimeError: invalid dtype for bias - should match query's dtype
```

it works well when I load llama model, but I get that error when I tried to run bloom

**Comment by WoosukKwon** [comment]
Hi @raihan0824, this was recently fixed by #996. We will release a new version with the fix soon. For now, please [install vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source).
