### ISSUE TITLE
baichuan's alibi bias in vllm is different from the huggingface's source code，doesn't it matter？

### ISSUE THREAD

**Issue by janelu9** [vllm-project/vllm#1009]
here is:
[-n,-n+1,......,0] * alibi_slopes
huggingface's  is:
[0,1,.....,n] * alibi_slopes
During inferring，the former need updates all cached value‘s alibi，but the latter need only updates the last one's.  Doesn't it matter？Do the cached prompts' alibi keep being updated now?
Need I do the following modifications, if I want to keep the same with baichuan's source code ？
https://github.com/vllm-project/vllm/issues/985#issuecomment-1711061942

**Comment by mpdpey043** [comment]
i found comment in vllm src code（/vllm/model_executor/layers/attention.py line355）, it says it's the same of those two biases:
![图片](https://github.com/vllm-project/vllm/assets/134110143/da595b29-a2e8-4d43-9280-74074965d255)

**Comment by janelu9** [comment]
> i found comment in vllm src code（/vllm/model_executor/layers/attention.py line355）, it says it's the same of those two biases: ![图片](https://user-images.githubusercontent.com/134110143/266943024-da595b29-a2e8-4d43-9280-74074965d255.png)

No , they're different. I think inferrence's should be the same as train's

**Comment by mpdpey043** [comment]
> > i found comment in vllm src code（/vllm/model_executor/layers/attention.py line355）, it says it's the same of those two biases: ![图片](https://user-images.githubusercontent.com/134110143/266943024-da595b29-a2e8-4d43-9280-74074965d255.png)
> 
> No, they're different strictly speaking. I think inferrence's should be the same as train's

so, if it dose  misaligned with huggingface's result, you can change it back in the HF ways as this comment said.

**Comment by janelu9** [comment]
qk adds bias before softmax , so it gets the same attention weight
