### ISSUE TITLE
about conversation template

### ISSUE THREAD

**Issue by allenhaozi** [vllm-project/vllm#1012]
Will vllm consider adding this feature?

In production, business applications often ignore `stop` field, but this can be problematic when the model is different

e.g.:
[fastchat conversation template](https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py#L283)

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
