### ISSUE TITLE
codellama AttributeError: module 'vllm.pos_encoding_ops' has no attribute 'rotary_embedding'

### ISSUE THREAD

**Issue by godsakurapeng** [vllm-project/vllm#1015]
vllm version: 90eb3f43ca5228647c834243d98881d53c7745d0
model: https://huggingface.co/codellama/CodeLlama-7b-Python-hf
error: ![image](https://github.com/vllm-project/vllm/assets/138603914/35c042d2-b452-430f-acc1-11ef643366ca)

Only error in codellama, it's good when i use another model

**Comment by WoosukKwon** [comment]
Hi @godsakurapeng, could you re-install vLLM?
```bash
pip install vllm --upgrade
```

**Comment by godsakurapeng** [comment]
> Hi @godsakurapeng, could you re-install vLLM?
> 
> ```shell
> pip install vllm --upgrade
> ```

Thank you, it work well
