### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by xuancaiqisehua** [vllm-project/vllm#1016]
vllm ： 0.1.7
torch  ：2.0.1+cu118
xformers ： 0.0.21
transformers  ：4.33.1

When I ran the example the following error occurred
RuntimeError: CUDA error: invalid device ordinal

**Comment by WoosukKwon** [comment]
Hi @xuancaiqisehua, just to double check: Can you run pytorch on your machine?

**Comment by xuancaiqisehua** [comment]
> 



> Hi @xuancaiqisehua, just to double check: Can you run pytorch on your machine?

Yes, I remove the line of code (torch.cuda.set_device(self.device) in vllm/worker/worker.py and it's works.

**Comment by WoosukKwon** [comment]
@xuancaiqisehua Happy to hear that you solved the problem. However, it sounds a bit weird. Did you specify `LOCAL_RANK` in you env variables?

**Comment by xuancaiqisehua** [comment]
> @xuancaiqisehua Happy to hear that you solved the problem. However, it sounds a bit weird. Did you specify `LOCAL_RANK` in you env variables?

I set the following in the terminal：

1、ray start --head --port=6379
2、ray start --address='**.**.**.**:6379'
3、export CUDA_VISIBLE_DEVICES=3,6 

then run the code:

```
from vllm import LLM,SamplingParams

prompts = [
   "<reserved_102>世界上第二高的山峰是哪座<reserved_103>"
]
sampling_params = SamplingParams(temperature=1, top_p=0.95,top_k=5,max_tokens=1024)

llm = LLM(model='Baichuan-13B-Chat',trust_remote_code=True,tensor_parallel_size=2)
outputs = llm.generate(prompts, sampling_params)
for output in outputs:
    print(output)
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

The following error is triggered：
![image](https://github.com/vllm-project/vllm/assets/38554867/7afade6a-4f43-4736-80fd-fc33bab3128c)

So, I remove the line of code (torch.cuda.set_device(self.device) in vllm/worker/worker.py.
Then it's works,I don't know the reason either.

**Comment by M-Chris** [comment]
FYI The issue is in how Ray is being assigned the devices.. or lack of rank more specifically. I actually have patches for this in a PR waiting on https://github.com/vllm-project/vllm/issues/1010 to push

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
