### ISSUE TITLE
[Feature]: ValueError: Model Qwen2VLForConditionalGeneration does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

### ISSUE THREAD

**Issue by cv-nlp** [vllm-project/vllm#10178]
### Your current environment

<details>
Will Qwen2-VL support LoRA reasoning in the future? I want to try multiple LoRA reasoning experiments.
</details>

### 🐛 Describe the bug

Will Qwen2-VL support LoRA reasoning in the future? I want to try multiple LoRA reasoning experiments.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
LoRA support for the language backbone of Qwen2-VL has already been added in #10022.

**Comment by cv-nlp** [comment]
> LoRA support for the language backbone of Qwen2-VL has already been added in #10022. It will be in the next release (or you can build vLLM from source to use it now).

Thanks bro,I'll try it

**Comment by DarkLight1337** [comment]
Feel free to re-open if your issue persists!
