### ISSUE TITLE
[help wanted]: why cmake 3.31 breaks vllm and how to fix it 

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#10189]
### Anything you want to discuss about vllm.

we need to figure it out and revert https://github.com/vllm-project/vllm/pull/10188 in the end.

the recent cmake 3.31 release breaks the release pipeline.
this successful release https://buildkite.com/vllm/release/builds/1745#019311b9-49d5-4f13-8064-df14308bd9ae uses cmake 3.30
and this failed release https://buildkite.com/vllm/release/builds/1746#01931327-c49b-4e52-8c0b-95fb95140ea4 uses cmake 3.31, and we get `CMake Error: Could not find CMAKE_ROOT !!! .`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
This might be the issue of `cmake-python-distributions`: https://github.com/scikit-build/cmake-python-distributions/issues/557. 

I can run the building pipeline with `cmake==3.31.0.1` successfully. We might need to exclude `cmake-3.31.0` and use `cmake-3.31.0.1` for building instead.

**Comment by youkaichao** [comment]
@Isotr0py thanks for investigating this!
