### ISSUE TITLE
Set the default `gpu-memory-utilzation` as 0.95

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#1018]
The `gpu-memory-utilization` argument was originally set to 0.95 by default but changed to 0.9, mainly because the memory profiling at the initialization time can be inaccurate. However, oftentimes the wasted 5% of GPU memory considerably affects the performance; For 13B LLMs, this leads to 20% difference (10GB vs. 12GB) in the KV cache size. For the best performance, we should make the memory profiling more accurate and set `gpu-memory-utilization` back to 0.95.

**Comment by irasin** [comment]
LGTM
BTW, can you set the `max_num_batched_tokens` argument default value to 4096 or 8192 since many LLMs have supported 4096/8192 prompt now.

**Comment by esmeetu** [comment]
But this might trigger OOM when batch size or prompt is large. 0.9 is safe for me.

**Comment by cason0126** [comment]
In my test on A800 - 80GB .  setting  gpu-memory-utilzation  =  0.95 or 0.5，  request/s didn't change much。May I ask why?  Did I set it up somewhere?

**Comment by irasin** [comment]
> In my test on A800 - 80GB . setting gpu-memory-utilzation = 0.95 or 0.5， request/s didn't change much。May I ask why? Did I set it up something wrong？

Hi @cason0126 , I wonder what model do you test on A800 - 80 GB. If you test llama7B/13B level model, the number of kv cache blocks is redundant for them.

**Comment by bohea** [comment]
what if someone wants to deploy two 13B models on A100 - 80 GB
will the first one still uses  26G(weights) + 46G(kv cache) = 72G = 80G * 0.9?

**Comment by bohea** [comment]
> LGTM BTW, can you set the `max_num_batched_tokens` argument default value to 4096 or 8192 since many LLMs have supported 4096/8192 prompt now.

may max_num_batched_tokens = max_model_len * p

0 < p < 1

BTW， What is limiting max_num_batched_tokens？ The larger max_num_batched_tokens, the more cache we need?

**Comment by cason0126** [comment]
> > In my test on A800 - 80GB . setting gpu-memory-utilzation = 0.95 or 0.5， request/s didn't change much。May I ask why? Did I set it up something wrong？
> 
> Hi @cason0126 , I wonder what model do you test on A800 - 80 GB. If you test llama7B/13B level model, the number of kv cache blocks is redundant for them.

oh！！，my test is 13B level ；  thank for answering 。 but why？ Do you have any references? and，what level model would be necessary？

**Comment by cason0126** [comment]
> what if someone wants to deploy two 13B models on A100 - 80 GB如果有人想在 A100 - 80 GB 上部署两个 13B 型号怎么办 will the first one still uses 26G(weights) + 46G(kv cache) = 72G = 80G * 0.9? 第一个仍然使用 26G(权重) + 46G(kv 缓存) = 72G = 80G * 0.9 吗？

why do u have to do that way ？you can try 0.45 * 2 。that will be 0.9  total

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
