### ISSUE TITLE
[Feature]: Request LoRA support for Aria

### ISSUE THREAD

**Issue by thanhnguyentung95** [vllm-project/vllm#10194]
### 🚀 The feature, motivation and pitch

Model AriaForConditionalGeneration does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
This model isn't managed by vLLM repo. Please open an issue at [rhymes-ai/Aria](https://github.com/rhymes-ai/Aria/tree/main) instead.
