### ISSUE TITLE
Can vLLM support medusa head?

### ISSUE THREAD

**Issue by MichaelJayW** [vllm-project/vllm#1023]
https://sites.google.com/view/medusa-llm

**Comment by hmellor** [comment]
@simon-mo is this a feature you'd like to see implemented?

**Comment by chizhang118** [comment]
Is there any plan for implementing this feature? Will it occur in Q2 roadmap?

**Comment by simon-mo** [comment]
Yes this is planned to happen. After the speculative decoding framework is in.
