### ISSUE TITLE
[Bug]: qwen cannot be quantized in vllm

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#10263]
### Your current environment

gpu A10
vllm version: 0.6.3.post1

### 🐛 Describe the bug

for qwen series, such as `Qwen/Qwen2.5-7B-Instruct`, it seems that vllm cannot apply quantization to it.
no matther for `bitsandbytes` or `awq` . 
even for `unsloth` version, `unsloth/Qwen2.5-7B-Instruct-bnb-4bit` it does not work either.

error message:
`AttributeError: Model Qwen2ForCausalLM does not support BitsAndBytes quantization yet.`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
The current release version indeed doesn't support this. It should be supported in the upcoming release version, see: #8941. You can try building from the `main` branch

**Comment by yananchen1989** [comment]
thanks. 

could you also take a look at phi series such as `microsoft/Phi-3.5-mini-instruct` ?
same issue with qwen : bnb quantization error

**Comment by yananchen1989** [comment]
@jeejeelee

**Comment by mgoin** [comment]
Hi @yananchen1989, phi is also supports with bitsandbytes on vLLM main, so please wait for the next release

I have tested with
```
vllm serve unsloth/Phi-3.5-mini-instruct-bnb-4bit --quantization bitsandbytes --load-format bitsandbytes
```

**Comment by SHAI-varun-upadhyay** [comment]
same issue i am also facing with :` unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit`

https://huggingface.co/unsloth/Qwen2.5-VL-7B-Instruct-unsloth-bnb-4bit/discussions/9
