### ISSUE TITLE
Long prompt will block all running generation.

### ISSUE THREAD

**Issue by esmeetu** [vllm-project/vllm#1026]
When i request using long prompt(larger than 4096), engine need 10s to process. At the moment, the running generation will be blocked until long prompt process task finished. When doing batch prompt, this phenomenon is more obvious. And may trigger abort onto new requests.

vLLM: 0.1.7

@Yard1 Do you have any ideas?
cc @zhuohan123 @WoosukKwon

**Comment by Yard1** [comment]
I would imagine this is due to the tokenization blocking the asyncio event loop. I am looking into ways of making encoding non-blocking to fix that.

**Comment by esmeetu** [comment]
> I would imagine this is due to the tokenization blocking the asyncio event loop. I am looking into ways of making encoding non-blocking to fix that. I am surprised it takes 10s though - how big are the prompts exactly?

8000-16k.
and my GPU is poor🤖

**Comment by Yard1** [comment]
Tokenization is done on CPU. Actually, you can test if that is the cause if you go to the LLMEngine class and replace the `tokenizer.encode` call with simply returning a constant list of n integers. If everything works smoothly after that, then it confirms the hypothesis that the tokenizer is the issue

**Comment by esmeetu** [comment]
@Yard1 I think it shouldn't be tokenizer issue. When long prompt received, engine log prompt ids in add_request method of async_llm_engine class. And then stucks until llm_engine log output.

4, 139, 187, 234, 139, 187, 30392, 31352, 30682, 233, 158, 194, 30690, 30210, 30214, 30392, 30672, 31381, 30486, 31704, 30275, 30878, 31647, 235, 183, 184, 30210, 235, 183, 165, 31730, 30267, 2277, 29937, 13291, 29901].

<stuck here.... wait about 10s>

INFO 09-13 11:57:58 llm_engine.py:613] Avg prompt throughput: 600.1 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.7%, CPU KV cache usage: 0.0%

**Comment by Yard1** [comment]
Is it possible it's simply taking that long to run the forward pass on GPU? What happens if you run the LLMEngine directly, without async? (See examples folder)

**Comment by esmeetu** [comment]
@Yard1 I test on 'llm_engine_example' by adding long prompt. It seems no delay.

So the issue is related with async_llm_engine when using openai api server?

**Comment by Yard1** [comment]
It would certainly suggest that. Would it be possible for you to share some of the prompts and the model you are using? I can try to reproduce.

**Comment by yanxiyue** [comment]
I read vllm's scheduling code a few days ago. My understanding is that although it seems to take a long time, it is indeed in line with the current implementation. It should be because each iteration is divided into two categories, one is prompt processing and the other is generation processing. Each iteration will only process one of them. If the prompt is too long and happens to be scheduled first, then naturally Will block subsequent added requests.

**Comment by esmeetu** [comment]
@Yard1 I use codellama-7b model. Prompt you can use 'vllm/entrypoints/openai/api_server.py'  whole source code. I am not conveniently share my code. 😶‍🌫️
Template here is '[INST] {code} [/INST]'

**Comment by Yard1** [comment]
@esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?

**Comment by esmeetu** [comment]
> @esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?

No, I have set max batched length args to 10000.

**Comment by wejoncy** [comment]
It may have a block-wise prompt encoding strategy.
To split a long prompt into multiple blocks to ensure each model forward is returning fast.

**Comment by yungangwu** [comment]
> > @esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?
> 
> No, I have set --max-num-batched-tokens args to 10000.

How did you implement batch processing when streaming output? Do you use openai api sever？

**Comment by esmeetu** [comment]
> > > @esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?
> 
> > 
> 
> > No, I have set --max-num-batched-tokens args to 10000.
> 
> 
> 
> How did you implement batch processing when streaming output? Do you use openai api sever？

Yes.

**Comment by yungangwu** [comment]
> > > > @esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?
> > 
> > 
> > > 
> > 
> > 
> > > No, I have set --max-num-batched-tokens args to 10000.
> > 
> > 
> > How did you implement batch processing when streaming output? Do you use openai api sever？
> 
> Yes.

Thanks. I'll try.

**Comment by yungangwu** [comment]
> > > > @esmeetu Do you get `Input prompt (n tokens) is too long and exceeds limit` in the logs?
> > 
> > 
> > > 
> > 
> > 
> > > No, I have set --max-num-batched-tokens args to 10000.
> > 
> > 
> > How did you implement batch processing when streaming output? Do you use openai api sever？
> 
> Yes.

Hello, I see the source code of vllm api sever. It's not support multiple prompts in a batch.
`elif isinstance(first_element, (str, list)):
            # TODO: handles multiple prompt case in list[list[int]]
            if len(request.prompt) > 1:
                return create_error_response(
                    HTTPStatus.BAD_REQUEST,
                    "multiple prompts in a batch is not currently supported")
            use_token_ids = not isinstance(first_element, str)
            prompt = request.prompt[0]`

**Comment by esmeetu** [comment]
@yungangwu I requested server concurrently which starting many requests at the same time.

**Comment by yungangwu** [comment]
@esmeetu ok，thank you.
