### ISSUE TITLE
[Feature]: 2:4 sparsity + w4a16 support

### ISSUE THREAD

**Issue by arunpatala** [vllm-project/vllm#10260]
### 🚀 The feature, motivation and pitch

Here in llm compressor, they say this mode is supported with 2:4 sparsity along with w4a16 quantization.

https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_2of4_sparse_w4a16

I just want to confirm this is supported in official vllm (not nm-vllm). Is there any existing model on huggingface (for llama 3.1 8B preferably) that I can test the speedup with?

Thanks

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by mgoin** [comment]
Hi @arunpatala we have support in vLLM for 2:4 sparse w4a16 (and w8a16) through the Marlin 2:4 kernel. You can see the models we use for testing [here](https://github.com/vllm-project/vllm/blob/7c65527918cd16286961a2a779e15743ca41ab0e/tests/models/decoder_only/language/test_gptq_marlin_24.py).

We are currently working on expanding this to more usable 2:4 sparse w8a8 compression.

Here is a quick proof-of-life benchmark I ran on a single H100 with two 1B models:

## Dense w4a16
```
python benchmarks/benchmark_latency.py --model alexm-nm/tinyllama-24-gptq-4bit-g128 --batch-size 1 --input-len 1024 --output-len 128
...
Avg latency: 0.3207843996429195 seconds
10% percentile latency: 0.32040550544625146 seconds
25% percentile latency: 0.3205501704942435 seconds
50% percentile latency: 0.3206998590612784 seconds
75% percentile latency: 0.3209406057721935 seconds
90% percentile latency: 0.3210684997495264 seconds
99% percentile latency: 0.3224447054718621 seconds
```

## Sparse 2:4 w4a16
```
python benchmarks/benchmark_latency.py --model alexm-nm/tinyllama-24-marlin24-4bit-g128 --batch-size 1 --input-len 1024 --output-len 128
...
Avg latency: 0.2847968160368813 seconds
10% percentile latency: 0.2830693102441728 seconds
25% percentile latency: 0.2848531081690453 seconds
50% percentile latency: 0.2849869194906205 seconds
75% percentile latency: 0.2854982622375246 seconds
90% percentile latency: 0.2855735011049546 seconds
99% percentile latency: 0.2860022523289081 seconds
```

In this latency benchmark I see a small but measurable 1.15x improvement

**Comment by arunpatala** [comment]
thanks for your reply.

do u expect more improvements in future or for bigger models?

**Comment by jvonrad** [comment]
hi is there a possibility to just test a 2:4 sparse model without gptq quantization
