### ISSUE TITLE
[Doc]: OpenAI Chat Completion Client For Multimodal missing using video as input for qwen2-vl

### ISSUE THREAD

**Issue by jxgu1016** [vllm-project/vllm#10316]
### 📚 The doc issue

the [doc](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_for_multimodal.html) only shows using multiple images, but how to use video as input?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ywang96** [comment]
In my knowledge our API server does not support video as input yet, but you can use the offline interface to run inference with video as input.

**Comment by jxgu1016** [comment]
according to [qwen2-vl doc](https://github.com/QwenLM/Qwen2-VL#notes), video input for openai chat is not supported for now.
