### ISSUE TITLE
【PLS！】A question about the paper experiments.

### ISSUE THREAD

**Issue by KylinC** [vllm-project/vllm#1038]
Hello, I read your awesome vLLM paper, but I wonder how you get the ORCA baseline.
is it Orca still close source? I can't find its source code. Or you use the other continuous batching implementation?
Thx.

**Comment by yanxiyue** [comment]
As mentioned in Section 6.1 of the paper, vllm team implemented 3 different version themselves.

**Comment by KylinC** [comment]
got it, thx

**Comment by WoosukKwon** [comment]
@yanxiyue Thanks!
