### ISSUE TITLE
[Doc]: Migrate to Markdown

### ISSUE THREAD

**Issue by rafvasq** [vllm-project/vllm#10427]
### 📚 The doc issue

Currently, documentation is written in ReStructuredText which is feature-rich but not as simple and popular as Markdown. This could be a barrier for people who are new to rST but want to contribute documentation. 

### Suggest a potential alternative/fix

Migrate the current docs to use [MyST](https://myst-parser.readthedocs.io/en/latest/index.html), a flavour of Markdown extended for use with Sphinx. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
Totally agree. If we migrate to markdown, we can also get a preview of documentation from previewer during writing without any re-building.

**Comment by simon-mo** [comment]
I support this!

**Comment by DarkLight1337** [comment]
+1!
