### ISSUE TITLE
[Doc]: Pages were moved without a redirect

### ISSUE THREAD

**Issue by shannonxtreme** [vllm-project/vllm#10428]
### 📚 The doc issue

In #9924, some pages were moved from the `/dev/` directory to the `/design/` directory. However, there's no redirect configured for the moved pages so the old URLs are returning 404 errors (for example: https://docs.vllm.ai/en/latest/dev/kernel/paged_attention.html). 

### Suggest a potential alternative/fix

For readthedocs, the way to add redirects seems to be https://docs.readthedocs.io/en/stable/guides/redirects.html

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @russellb

**Comment by russellb** [comment]
> cc @russellb

Thanks. 

I don't mind creating some redirects, but it looks like you have to be an admin of the docs site to do it. I'm not sure who is. @simon-mo ?

**Comment by DarkLight1337** [comment]
I have created redirects for the files moved in that PR. Thanks for reporting this issue!
