### ISSUE TITLE
[Misc]: `pip-compile requirements-test.in` fails with conflict from "decord"

### ISSUE THREAD

**Issue by lk-chen** [vllm-project/vllm#10466]
### Anything you want to discuss about vllm.

TL;DR: don't pip-compile on arm-chip macbook as of 2024Q4

----------------------original post-------------------

`decord` was introduced in #10020, now `pip-compile` is failing for both python3.9 and python3.12 with error
```
  ERROR: Cannot install decord because these package versions have conflicting dependencies.
Discarding decord==0.6.0 (from -r requirements-test.txt (line 96)) to proceed the resolution
  ERROR: Could not find a version that satisfies the requirement decord (from versions: none)
```

test python3.12 using mac (m3 pro)
```
conda create --name py312 -c conda-forge python=3.12
conda activate py312
pip install pip-tools
pip-compile --output-file=requirements-test.txt requirements-test.in
```

cc @litianjian

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by lk-chen** [comment]
turns out it's mac-specific issue, according to dmlc/decord#213

tried s/decord/eva-decord, and it seems working with 3.9 and 3.11, not 3.12. Tested on macbook (m3 pro)

![image](https://github.com/user-attachments/assets/c9b92cdc-d78d-4ec6-92af-d4bb8bb8a2f5)

**Comment by comaniac** [comment]
Also cc @khluu

**Comment by lk-chen** [comment]
not only "decord" package, "bitsandbytes" has similar issue.

Many python packages publish "manylinux-x86_64" wheels, which does not work for arm-chip macbook.

I'm going to close this issue for now.
