### ISSUE TITLE
Intel PVC GPU + vLLM

### ISSUE THREAD

**Issue by atanikan** [vllm-project/vllm#1046]
I currently see a prerequisite of CUDA for vLLM models. We currently have a cluster with Intel PVC GPUs. I would like to know if there are plans on abstracting vllm to use our pre-trained models so that it can run without CUDA.

**Comment by WoosukKwon** [comment]
Hi @atanikan, thanks for your interest in vLLM. We are definitely interested in supporting more diverse hardware backends. However, currently we don't have expertise on Intel PVC GPUs and don't even have access to them. Therefore, we won't be able to do it by ourselves, while we'd love to help if someone works on integration.

**Comment by jikunshang** [comment]
hi @atanikan, I open a PR(#3814 ) to support Intel PVC + vLLM, Please take a try.
