### ISSUE TITLE
[Bug]: LLaMA3.2-1B finetuned w/ Sentence Transformer. --> ValueError: Model architectures ['LlamaModel'] are not supported for now.

### ISSUE THREAD

**Issue by thusinh1969** [vllm-project/vllm#10481]
### Your current environment

!pip install vllm==0.5.4
!pip install git+https://github.com/huggingface/transformers
!pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121

### 🐛 Describe the bug

We finetune **LlaMA-3.2-1B** with **Sentence Transformers** latest version, it works well after finetuning and benchmark.
However, once we tried to load it with vLLM, the error occured:

!pip install vllm==0.5.4
!pip install git+https://github.com/huggingface/transformers
!pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121

model_path = "path to LlaMA-3.2-1B Sentence Transformer checkpoint model saved" - works without vLLM.

llm = LLM(model=model_path, 
tokenizer=model_path,
#gpu_memory_utilization=0.5,
dtype="auto",
kv_cache_dtype="auto",
tensor_parallel_size=1,
max_seq_len_to_capture=2048,
max_num_batched_tokens=2048,
max_num_seqs=2048,
use_v2_block_manager=True,
enforce_eager=True,
trust_remote_code=True)

==> ERROR below:

ValueError                                Traceback (most recent call last)
Cell In[17], line 2
      1 # Create an LLM.
----> 2 llm = LLM(model=model_path, 
      3           tokenizer=model_path,
      4           #gpu_memory_utilization=0.5,
      5           dtype="auto",
      6           kv_cache_dtype="auto",
      7           tensor_parallel_size=1,
      8           max_seq_len_to_capture=2048,
      9           max_num_batched_tokens=2048,
     10           max_num_seqs=2048,
     11           use_v2_block_manager=True,
     12           enforce_eager=True,
     13           trust_remote_code=True) # 16384

File ~/env/lib/python3.10/site-packages/vllm/entrypoints/llm.py:158, in LLM.__init__(self, model, tokenizer, tokenizer_mode, skip_tokenizer_init, trust_remote_code, tensor_parallel_size, dtype, quantization, revision, tokenizer_revision, seed, gpu_memory_utilization, swap_space, cpu_offload_gb, enforce_eager, max_context_len_to_capture, max_seq_len_to_capture, disable_custom_all_reduce, **kwargs)
    135     raise TypeError(
    136         "There is no need to pass vision-related arguments anymore.")
    137 engine_args = EngineArgs(
    138     model=model,
    139     tokenizer=tokenizer,
   (...)
    156     **kwargs,
    157 )
--> 158 self.llm_engine = LLMEngine.from_engine_args(
    159     engine_args, usage_context=UsageContext.LLM_CLASS)
    160 self.request_counter = Counter()

File ~/env/lib/python3.10/site-packages/vllm/engine/llm_engine.py:445, in LLMEngine.from_engine_args(cls, engine_args, usage_context, stat_loggers)
    443 executor_class = cls._get_executor_cls(engine_config)
    444 # Create the LLM engine.
--> 445 engine = cls(
    446     **engine_config.to_dict(),
    447     executor_class=executor_class,
    448     log_stats=not engine_args.disable_log_stats,
    449     usage_context=usage_context,
    450     stat_loggers=stat_loggers,
    451 )
    453 return engine

File ~/env/lib/python3.10/site-packages/vllm/engine/llm_engine.py:249, in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, device_config, load_config, lora_config, multimodal_config, speculative_config, decoding_config, observability_config, prompt_adapter_config, executor_class, log_stats, usage_context, stat_loggers)
    243 self.generation_config_fields = _load_generation_config_dict(
    244     model_config)
    246 self.input_processor = INPUT_REGISTRY.create_input_processor(
    247     self.model_config)
--> 249 self.model_executor = executor_class(
    250     model_config=model_config,
    251     cache_config=cache_config,
    252     parallel_config=parallel_config,
    253     scheduler_config=scheduler_config,
    254     device_config=device_config,
    255     lora_config=lora_config,
    256     multimodal_config=multimodal_config,
    257     speculative_config=speculative_config,
    258     load_config=load_config,
    259     prompt_adapter_config=prompt_adapter_config,
    260 )
    262 if not self.model_config.embedding_mode:
    263     self._initialize_kv_caches()

File ~/env/lib/python3.10/site-packages/vllm/executor/executor_base.py:47, in ExecutorBase.__init__(self, model_config, cache_config, parallel_config, scheduler_config, device_config, load_config, lora_config, multimodal_config, speculative_config, prompt_adapter_config)
     44 self.speculative_config = speculative_config
     45 self.prompt_adapter_config = prompt_adapter_config
---> 47 self._init_executor()

File ~/env/lib/python3.10/site-packages/vllm/executor/gpu_executor.py:36, in GPUExecutor._init_executor(self)
     34 self.driver_worker = self._create_worker()
     35 self.driver_worker.init_device()
---> 36 self.driver_worker.load_model()

File ~/env/lib/python3.10/site-packages/vllm/worker/worker.py:139, in Worker.load_model(self)
    138 def load_model(self):
--> 139     self.model_runner.load_model()

File ~/env/lib/python3.10/site-packages/vllm/worker/model_runner.py:722, in GPUModelRunnerBase.load_model(self)
    720 logger.info("Starting to load model %s...", self.model_config.model)
    721 with CudaMemoryProfiler() as m:
--> 722     self.model = get_model(model_config=self.model_config,
    723                            device_config=self.device_config,
    724                            load_config=self.load_config,
    725                            lora_config=self.lora_config,
    726                            multimodal_config=self.multimodal_config,
    727                            parallel_config=self.parallel_config,
    728                            scheduler_config=self.scheduler_config,
    729                            cache_config=self.cache_config)
    731 self.model_memory_usage = m.consumed_memory
    732 logger.info("Loading model weights took %.4f GB",
    733             self.model_memory_usage / float(2**30))

File ~/env/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py:21, in get_model(model_config, load_config, device_config, parallel_config, scheduler_config, lora_config, multimodal_config, cache_config)
     14 def get_model(*, model_config: ModelConfig, load_config: LoadConfig,
     15               device_config: DeviceConfig, parallel_config: ParallelConfig,
     16               scheduler_config: SchedulerConfig,
     17               lora_config: Optional[LoRAConfig],
     18               multimodal_config: Optional[MultiModalConfig],
     19               cache_config: CacheConfig) -> nn.Module:
     20     loader = get_model_loader(load_config)
---> 21     return loader.load_model(model_config=model_config,
     22                              device_config=device_config,
     23                              lora_config=lora_config,
     24                              multimodal_config=multimodal_config,
     25                              parallel_config=parallel_config,
     26                              scheduler_config=scheduler_config,
     27                              cache_config=cache_config)

File ~/env/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py:324, in DefaultModelLoader.load_model(self, model_config, device_config, lora_config, multimodal_config, parallel_config, scheduler_config, cache_config)
    322 with set_default_torch_dtype(model_config.dtype):
    323     with target_device:
--> 324         model = _initialize_model(model_config, self.load_config,
    325                                   lora_config, multimodal_config,
    326                                   cache_config, scheduler_config)
    327     model.load_weights(
    328         self._get_weights_iterator(model_config.model,
    329                                    model_config.revision,
   (...)
    332                                        "fall_back_to_pt_during_load",
    333                                        True)), )
    335     for _, module in model.named_modules():

File ~/env/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py:151, in _initialize_model(model_config, load_config, lora_config, multimodal_config, cache_config, scheduler_config)
    143 def _initialize_model(
    144         model_config: ModelConfig,
    145         load_config: LoadConfig,
   (...)
    148         cache_config: CacheConfig,
    149         scheduler_config: Optional[SchedulerConfig] = None) -> nn.Module:
    150     """Initialize a model with the given configurations."""
--> 151     model_class = get_model_architecture(model_config)[0]
    152     quant_config = _get_quantization_config(model_config, load_config)
    154     return model_class(config=model_config.hf_config,
    155                        cache_config=cache_config,
    156                        quant_config=quant_config,
    157                        **_get_model_initialization_kwargs(
    158                            model_class, lora_config, multimodal_config,
    159                            scheduler_config))

File ~/env/lib/python3.10/site-packages/vllm/model_executor/model_loader/utils.py:35, in get_model_architecture(model_config)
     33     if model_cls is not None:
     34         return (model_cls, arch)
---> 35 raise ValueError(
     36     f"Model architectures {architectures} are not supported for now. "
     37     f"Supported architectures: {ModelRegistry.get_supported_archs()}")

ValueError: Model architectures ['LlamaModel'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'FalconForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'InternVLChatModel', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPMV', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PaliGemmaForConditionalGeneration', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3VForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MedusaModel', 'MLPSpeculatorPreTrainedModel', 'JambaForCausalLM', 'MistralModel']

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
It's only supported in v0.6.4 or above. Please update your vLLM version.

**Comment by thusinh1969** [comment]
It works, thanks.
