### ISSUE TITLE
why prompt token ids is None?

### ISSUE THREAD

**Issue by cgq0816** [vllm-project/vllm#1049]
Received request 6f70b6651dbd4df19d25d8c1f4486ad4: prompt: 'San Francisco is a', sampling params: SamplingParams(n=2, best_of=2, presence_penalty=0.0, frequency_penalty=0.0, temperature=0.0, top_p=1.0, top_k=-1, use_beam_search=True, length_penalty=1.0, early_stopping=False, stop=['<|im_end|>'], ignore_eos=False, max_tokens=512, logprobs=None), prompt token ids: None.

**Comment by robertsw22** [comment]
same

**Comment by 202030481266** [comment]
me too

**Comment by itsmeashutosh43** [comment]
same

**Comment by 202030481266** [comment]
I met this issue when I using fastchat.vllm_worker to deploy the chatglm3-6B model. And I fixed this by updating the code in sampling_params:
`stop=list(stop)` -> `stop=[i for i in stop if i != ""]`

**Comment by sheiy** [comment]
same
