### ISSUE TITLE
When baichuan2 is deployed, the output is always 2。 or two? or two! end, the comparison affects the user experience

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#1050]
![image](https://github.com/vllm-project/vllm/assets/25812074/ff306599-0a84-47df-b6a8-fc6915e8e02f)
![image](https://github.com/vllm-project/vllm/assets/25812074/4281bb1e-6861-439b-8d8a-7d75d5be1ce4)

**Comment by Zhang-star-master** [comment]
how  can  i   rollback to 3272d7a ?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
