### ISSUE TITLE
[Feature]: Multimodel prefix-caching features

### ISSUE THREAD

**Issue by justzhanghong** [vllm-project/vllm#10510]
### 🚀 The feature, motivation and pitch

v0.6.4.post1, "--enable-prefix-caching is currently not supported for multimodal models and has been disabled." When will multimodal models be supported?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by robertgshaw2-neuralmagic** [comment]
This is being actively worked on as part of the VLLM V1 project. Not definite timeline but I would expect within a month

**Comment by justzhanghong** [comment]
Thanks.
