### ISSUE TITLE
How specify decoding strategy?

### ISSUE THREAD

**Issue by jiacheng-ye** [vllm-project/vllm#1055]
Hi, thanks for the good work. I'm wondering how to specify decoding strategy? For example, in transformers generate function, I can specify logits_processor. However, it seems not supported in vllm as shown in https://github.com/vllm-project/vllm/blob/main/vllm/sampling_params.py.

Thanks in advance for your help.

**Comment by hmellor** [comment]
This is now supported https://github.com/vllm-project/vllm/blob/1ece1ae829dcbc4b1b19b3e2d3042457615e862f/vllm/sampling_params.py#L92-L93
