### ISSUE TITLE
[Usage]: Why `use_beam_search` is eliminated in `vllm.SamplingParams` from v0.6.3?

### ISSUE THREAD

**Issue by BAI-Yeqi** [vllm-project/vllm#10605]
### Your current environment

I am asking a general API question regarding `vllm`, therefore, env info is not needed.

### How would you like to use vllm

I want to ask why `use_beam_search` is eliminated in `vllm.SamplingParams` from v0.6.3 (https://docs.vllm.ai/en/v0.6.3/dev/sampling_params.html)?

How can we control the usage of beam search from v0.6.3 onwards?

To the best of my knowledge, `use_beam_search` is supported in all versions from [v0.4.0.post1](https://docs.vllm.ai/en/v0.4.0.post1/dev/sampling_params.html) to [v0.6.2](https://docs.vllm.ai/en/v0.6.2/dev/sampling_params.html).

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by noooop** [comment]
PTAL  

- https://github.com/vllm-project/vllm/issues/6226

- https://github.com/vllm-project/vllm/issues/8306

- https://github.com/vllm-project/vllm/pull/9296
