### ISSUE TITLE
[Usage]: How to make model response information appear in the vllm backend logs

### ISSUE THREAD

**Issue by nora647** [vllm-project/vllm#10602]
### Your current environment

I am deploying a qwen2.5-7b model via vllm serve Qwen/Qwen2.5-7B-Instruct with api calls using the langchain framework.

```text
vllm serve Qwen/Qwen2.5-7B-Instruct
```
But in the process of using it, I found that the vllm background log only records the log of requests to llm, and does not record the log of llm replies, which is very inconvenient in program debugging. 
<img width="854" alt="1db554ad959899f82124ab9cd80d923" src="https://github.com/user-attachments/assets/96e75a24-f63d-4c52-aedb-8d751bf4d531">

I would like to know how to make vllm background log can record model reply information in real time.For example, as shown in the following figure
<img width="853" alt="af26d8187b66d9c6eac2abba5cccf81" src="https://github.com/user-attachments/assets/dc855218-bd91-4275-8fcc-f5cfa7d5947d">

### How would you like to use vllm

I would like to know how to make vllm background log can record model reply information in real time.For example, as shown in the following figure.Thank you!

<img width="853" alt="af26d8187b66d9c6eac2abba5cccf81" src="https://github.com/user-attachments/assets/7eb3d5c3-d076-4065-94c9-555736c1fc4e">

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
The output isn't logged in our code, you'll have to edit `chat_completion_stream_generator` and/or `chat_completion_stream_generator` inside `vllm/entrypoints/openai/serving_chat.py` to log this information.

**Comment by nora647** [comment]
> The output isn't logged in our code, you'll have to edit `chat_completion_full_generator` and/or `chat_completion_stream_generator` inside `vllm/entrypoints/openai/serving_chat.py` to log this information.

Thank you！

**Comment by mizadri** [comment]
Hey @DarkLight1337 , I implemented and created a PR for this https://github.com/vllm-project/vllm/pull/20707
