### ISSUE TITLE
[Doc]: docker+lmdeploy deploys multimodal large model and reports an error：AssertionError: failed to match chat template, please explicit set chat_template_config（docker+lmdeploy部署多模态大模型）

### ISSUE THREAD

**Issue by Aanlifire** [vllm-project/vllm#10625]
### 📚 The doc issue

The deployment process is as follows：

pip install qwen_vl_utils

git clone https://github.com/InternLM/lmdeploy.git
cd lmdeploy
docker build --build-arg CUDA_VERSION=cu12 -t openmmlab/lmdeploy:qwen2vl . -f ./docker/Qwen2VL_Dockerfile

docker run --runtime nvidia --gpus all \
    -v ~/Qwen2-VL-7B-Instruct:/lmdeploy/models \
    -p 8000:8000 \
    --ipc=host \
    openmmlab/lmdeploy:latest \
    lmdeploy serve api_server /lmdeploy/models

(base) root@lxing:~/lmdeploy# docker run --runtime nvidia --gpus all \
    -v ~/Qwen2-VL-7B-Instruct:/lmdeploy/models \
    -v ~/Qwen2-VL-7B-Instruct/chat_template.json:/opt/lmdeploy/config/chat_template.json \
    -p 8000:8000 \
    --ipc=host \
    openmmlab/lmdeploy:qwen2vl-v0.5.1 \
    lmdeploy serve api_server /lmdeploy/models

==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

2024-11-25 03:36:47,633 - lmdeploy - WARNING - archs.py:53 - Fallback to pytorch engine because /lmdeploy/models not supported by turbomind engine.
Qwen2VLRotaryEmbedding can now be fully parameterized by passing the model config through the config argument. All other arguments will be removed in v4.46
Traceback (most recent call last):
  File "/opt/py3/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 338, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1073, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 32, in __init__
    self.vl_prompt_template = get_vl_prompt_template(
  File "/opt/lmdeploy/lmdeploy/vl/templates.py", line 512, in get_vl_prompt_template
    assert type(chat_template) != type(BaseModel()), 'failed to match ' \
AssertionError: failed to match chat template, please explicit set chat_template_config

### Suggest a potential alternative/fix

Please tell me how to solve this problem

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
According to the stack trace, this seems to be a problem with lmdeploy rather than vllm. Please open an issue on their repo instead.
