### ISSUE TITLE
GPU consumption

### ISSUE THREAD

**Issue by yilihtien** [vllm-project/vllm#1062]
My environment involves creating a virtual machine (VM) on a Hyper Converge Infrastructure machine, and within the VM, setting up a Conda environment. And using an A100 80g GPU. Executing the following commands:
python -m vllm.entrypoints.api_server  --model  'LinkSoul/Chinese-Llama-2-7b' --swap-space 16  --disable-log-requests --host 172.22.119.190 --port 10860 --max-num-seqs 256 --trust-remote-code --tensor-parallel-size 1
![image](https://github.com/vllm-project/vllm/assets/39508634/de565359-80ec-4262-96fe-2a158cf1a865)

GPU mem used 73GB! Can someone please tell me what cause it. Thanks

**Comment by viv92** [comment]
I'm facing the same issue. 
Llama2_7b_chat model consumes ~14 GB of GPU RAM immediately after load, but a couple of seconds later, the same model is consuming > 90% of available GPU RAM (46GB on A6000 in my case)

**Comment by viv92** [comment]
Ok. 
EngineArgs.gpu_memory_utilization = 0.9 by default

**Comment by yilihtien** [comment]
Thanks🤪
