### ISSUE TITLE
[Feature]: Qwen2-VL

### ISSUE THREAD

**Issue by Chin-Vic** [vllm-project/vllm#10654]
### 🚀 The feature, motivation and pitch

Is Qwen2-VL supported for running on AWS Inf2?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
vLLM does support [Qwen2-VL](https://docs.vllm.ai/en/latest/models/supported_models.html#supported-vlms). As for specific machines, it depends on their hardware (e.g. whether they have enough memory to load the model).
