### ISSUE TITLE
 How to deploy api server as https

### ISSUE THREAD

**Issue by yilihtien** [vllm-project/vllm#1066]
My app is opend as https, and can not request api by http. Any solutions besides modify api_server.py. thanks for help.

**Comment by Allinwang0528** [comment]
你是怎么解决的 我也遇到了同样的问题

**Comment by cchung85** [comment]
You can put a light-weight server like nginx in front of the vllm server. This nginx provides the https termination for inbound https calls, and relays the request to vllm using http. This pattern is very  popular, and the role of nginx is called a reverse proxy. You can put multiple ngix servers in front of multiple vllm server, and act as a load balancer. (For best security, the nginx and vllm server should be 'close' together).
