### ISSUE TITLE
[Feature]: Integrate with XGrammar for zero-overhead structured generation in LLM inference.

### ISSUE THREAD

**Issue by choisioo** [vllm-project/vllm#10660]
### 🚀 The feature, motivation and pitch

Enables zero-overhead structured generation in LLM inference.

https://github.com/mlc-ai/xgrammar

### Additional context

https://blog.mlc.ai/2024/11/22/achieving-efficient-flexible-portable-structured-generation-with-xgrammar
https://xgrammar.mlc.ai/docs/how_to/engine_integration.html

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by dongxiaolong** [comment]
#10785

**Comment by mgoin** [comment]
Support has landed as of https://github.com/vllm-project/vllm/pull/10785 and performance is much better!
