### ISSUE TITLE
[Bug]: CPU Docker build fail.

### ISSUE THREAD

**Issue by Zhenzhong1** [vllm-project/vllm#10689]
### Your current environment

![image](https://github.com/user-attachments/assets/4c4809e4-7983-4205-a747-05f3e037575c)

### 🐛 Describe the bug

docker build -f Dockerfile.cpu -t vllm-cpu-env --shm-size=4g .

![image](https://github.com/user-attachments/assets/4f3dac9d-1c05-40d8-89a1-1d52f9e78705)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ZePan110** [comment]
I triggered this issue as well and backtracked many versions with the same reported error. 
![image](https://github.com/user-attachments/assets/c4b5bed4-9ac5-4385-87b8-35ba60ac0712)

**Comment by bigPYJ1151** [comment]
should be fixed by #10700

**Comment by ZePan110** [comment]
> should be fixed by #10700

Thanks for fixing!

**Comment by Zhenzhong1** [comment]
Thank you all.

**Comment by Bunny15738** [comment]
Still i am facing same issue

**Comment by Bunny15738** [comment]
Hi @bigPYJ1151 , Any update on above?
I am using same Dockerfile.cpu.

**Comment by bigPYJ1151** [comment]
@Bunny15738 Also coredump problem in your building?

**Comment by Bunny15738** [comment]
Yes, it is still faling at this point.
`RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/ccache \
    --mount=type=bind,source=.git,target=.git \
    VLLM_TARGET_DEVICE=cpu \
    python3 setup.py bdist_wheel && \
    pip install dist/*.whl && \
    rm -rf dist`

**Comment by bigPYJ1151** [comment]
Hmmm, the latest main branch should be normal. You can try to remove ```/usr/local/lib/libiomp5.so``` from ```ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:/usr/local/lib/libiomp5.so"``` in the dockerfile.

**Comment by Bunny15738** [comment]
@bigPYJ1151 ,Still issue persist...!!

**Comment by bigPYJ1151** [comment]
Are you using the latest main branch? I can't reproduce this coredump problem on the latest main🤔

**Comment by Bunny15738** [comment]
Yes for sure I am using the main branch.
Will this help?

`27.05 Had to git clone more than once: 3 times.
27.05 CMake Error at onednn-subbuild/onednn-populate-prefix/tmp/onednn-populate-gitclone.cmake:50 (message):
27.05   Failed to clone repository: 'https://github.com/oneapi-src/oneDNN.git'
27.05
27.05
27.05 FAILED: onednn-populate-prefix/src/onednn-populate-stamp/onednn-populate-download /workspace/vllm/.deps/onednn-subbuild/onednn-populate-prefix/src/onednn-populate-stamp/onednn-populate-download
27.05 cd /workspace/vllm/.deps && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -DCMAKE_MESSAGE_LOG_LEVEL=VERBOSE -P 
/workspace/vllm/.deps/onednn-subbuild/onednn-populate-prefix/tmp/onednn-populate-gitclone.cmake && /usr/local/lib/python3.10/dist-packages/cmake/data/bin/cmake -E touch /workspace/vllm/.deps/onednn-subbuild/onednn-populate-prefix/src/onednn-populate-stamp/onednn-populate-download
27.05 ninja: build stopped: subcommand failed.
27.05
27.05 CMake Error at /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:1918 (message): 
27.05   Build step for onednn failed: 1
27.05 Call Stack (most recent call first):
27.05   /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)
27.05   /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
27.05   /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:2145 (cmake_language)        
27.05   /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.31/Modules/FetchContent.cmake:2384 (__FetchContent_Populate)
27.05   cmake/cpu_extension.cmake:170 (FetchContent_MakeAvailable)
27.05   CMakeLists.txt:89 (include)
27.05
27.05
27.05 -- Configuring incomplete, errors occurred!
27.07 Traceback (most recent call last):
27.07   File "/workspace/vllm/setup.py", line 682, in <module>
27.07     setup(
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 117, in setup
27.07     return distutils.core.setup(**attrs)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 186, in setup
27.07     return run_commands(dist)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 202, in run_commands
27.07     dist.run_commands()
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
27.07     self.run_command(cmd)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 999, in run_command
27.07     super().run_command(command)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 1021, in run_command
27.07     cmd_obj.run()
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/bdist_wheel.py", line 369, in run
27.07     self.run_command("build")
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 357, in run_command
27.07     self.distribution.run_command(command)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 999, in run_command
27.07     super().run_command(command)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 1021, in run_command
27.07     cmd_obj.run()
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 140, in run
27.07     self.run_command(cmd_name)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 357, in run_command
27.07     self.distribution.run_command(command)
27.07   File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 999, in run_command
27.08     super().run_command(command)
27.08   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 1021, in run_command
27.08     cmd_obj.run()
27.08   File "/workspace/vllm/setup.py", line 267, in run
27.08     super().run()
27.08   File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 99, in run
27.09     _build_ext.run(self)
27.09   File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 375, in run
27.09     self.build_extensions()
27.09   File "/workspace/vllm/setup.py", line 226, in build_extensions
27.09     self.configure(ext)
27.09   File "/workspace/vllm/setup.py", line 204, in configure
27.09     subprocess.check_call(
27.09   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
27.09     raise CalledProcessError(retcode, cmd)
27.09 subprocess.CalledProcessError: Command '['cmake', '/workspace/vllm', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DVLLM_TARGET_DEVICE=cpu', '-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache', '-DCMAKE_CUDA_COMPILER_LAUNCHER=ccache', '-DCMAKE_HIP_COMPILER_LAUNCHER=ccache', '-DVLLM_PYTHON_EXECUTABLE=/usr/bin/python3', '-DVLLM_PYTHON_PATH=/workspace/vllm:/usr/lib/python310.zip:/usr/lib/python3.10:/usr/lib/python3.10/lib-dynload:/usr/local/lib/python3.10/dist-packages:/usr/lib/python3/dist-packages:/usr/local/lib/python3.10/dist-packages/setuptools/_vendor', '-DFETCHCONTENT_BASE_DIR=/workspace/vllm/.deps', '-DCMAKE_JOB_POOL_COMPILE:STRING=compile', '-DCMAKE_JOB_POOLS:STRING=compile=8']' returned non-zero exit status 1.
------
Dockerfile:55
--------------------
  54 |
  55 | >>> RUN --mount=type=cache,target=/root/.cache/pip \
  56 | >>>     --mount=type=cache,target=/root/.cache/ccache \
  57 | >>>     --mount=type=bind,source=.git,target=.git \
  58 | >>>     VLLM_TARGET_DEVICE=cpu \
  59 | >>>     python3 setup.py bdist_wheel && \
  60 | >>>     pip install dist/*.whl && \
  61 | >>>     rm -rf dist
  62 |
--------------------
ERROR: failed to solve: process "/bin/sh -c VLLM_TARGET_DEVICE=cpu     python3 setup.py bdist_wheel &&     pip install dist/*.whl &&     rm -rf dist" did not complete successfully: exit code: 1`

**Comment by bigPYJ1151** [comment]
Looks like it is not the coredump problem. There are some errors in fetching oneDNN repository. Maybe you can try ```git clone https://github.com/oneapi-src/oneDNN.git``` to check detailed error.
