### ISSUE TITLE
Provision for `diversity_penalty` in vLLM generation?

### ISSUE THREAD

**Issue by Bhuvanesh09** [vllm-project/vllm#1076]
Is there a way to reproduce results to huggingface's generation with the parameter `diversity_penalty` present [here](https://huggingface.co/docs/transformers/v4.33.2/en/main_classes/text_generation#transformers.GenerationConfig.diversity_penalty). 

`diversity_penalty` helps to generate diversity in the output when using `beam_search`. The current implementation of vLLM doesn't allow for this and returns similar outputs across all of its beams. Is there a method to replicate something similar with vLLM?

**Comment by hmellor** [comment]
This is achieved using `repetition_penalty` in the `SamplingParams`
