### ISSUE TITLE
[New Model]: Qwen/QwQ-32B-Preview

### ISSUE THREAD

**Issue by SongXiaoMao** [vllm-project/vllm#10786]
### The model to consider.

Qwen/QwQ-32B-Preview

### What's your difficulty of supporting the model you want?

Currently, the latest version of vllm can start this model, but the answers are all symbols. I hope to support this model as soon as possible, thank you!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
See #10737

**Comment by SongXiaoMao** [comment]
Updated vllm to version 0.6.5, and downloaded the model on HF again, and it can be used normally. Thanks!
