### ISSUE TITLE
[Issue]Recompute mode affects the latency of the request

### ISSUE THREAD

**Issue by wjj19950828** [vllm-project/vllm#1079]
## Issue
In high concurrency situations, the latency of some requests is too long.

## describe
Hello, thank you vllm for your contribution in large model deployment

Currently I have encountered a problem: when the bs/concurrency is high, the recompute mode will be triggered. This situation is not friendly to the latency of some requests because it needs to be recalculated.

Is there any good solution to this situation? Thanks ~
![image](https://github.com/vllm-project/vllm/assets/19977378/9f989376-1240-4f8c-a0de-03dd8d97c48c)

**Comment by wjj19950828** [comment]
@viktor-ferenczi  @Woosuk Kwon
Do you have any suggestions over there?

Thanks~

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
