### ISSUE TITLE
[Feature]: Adding Support for Custom CORS setup

### ISSUE THREAD

**Issue by Cognitus-Stuti** [vllm-project/vllm#10832]
### 🚀 The feature, motivation and pitch

vllm is endpoints are fastapi based and it supports CORS already, I believe we can expose setting up cors middleware into these for additional security, is there a feature like this already ?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by cjackal** [comment]
vllm provides `--middleware <import path to middleware>` argument which accepts arbitrary ASGI middleware. cf) [here](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html#command-line-arguments-for-the-server)
