### ISSUE TITLE
Feature request: add prometheus exporter

### ISSUE THREAD

**Issue by itaybar** [vllm-project/vllm#1083]
I think it would be great to add `/metrics` route for api using prometheus client. This will help vllm be more “end to end” product
Some metrics I think will be great:

- Total request count
- Total failure count with error type as label
- buckets of latency
- Total generated tokens
- Total input tokens

Those are the main I can think of right now. Pleased to get some more

**Comment by joestein** [comment]
This looks like it is already implemented https://docs.vllm.ai/en/latest/serving/metrics.html
