### ISSUE TITLE
WSL performance issue with pin_memory=False

### ISSUE THREAD

**Issue by ryanshrott** [vllm-project/vllm#1084]
Has anyone benchmarked performance of WSL ubuntu and VLLM? I seem to be getting lower performance, but there are too many variables to say for sure. Any optimized settings to use/consider?

I get this warning as well. Any idea what to do? 
WARNING 09-18 10:59:09 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by dliting** [comment]
> Has anyone benchmarked performance of WSL ubuntu and VLLM? I seem to be getting lower performance, but there are too many variables to say for sure. Any optimized settings to use/consider?
> 
> I get this warning as well. Any idea what to do? WARNING 09-18 10:59:09 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.

same issue

**Comment by hmellor** [comment]
This is an issue with WSL that is unavoidable in vLLM.

https://github.com/vllm-project/vllm/blob/14ccd94c89d0ffd9da283545d93ab1dfea5da340/vllm/utils.py#L354-L365

See this extract from https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-applications:

> Pinned system memory (example: System memory that an application makes resident for GPU accesses) availability for applications is limited.

**Comment by TomLucidor** [comment]
@hmellor When will this be fixed so vLLM can have UVA / pinned memory for CPU offloading?
