### ISSUE TITLE
[New Model]: OLMo 2 13B

### ISSUE THREAD

**Issue by gaardhus** [vllm-project/vllm#10869]
### The model to consider.

https://huggingface.co/allenai/OLMo-2-1124-13B

### What's your difficulty of supporting the model you want?

The model will be supported in the next version of the transformers library, but I guess it still needs to be added here as well somewhere, as I'm getting an error saying `Model architectures ['Olmo2ForCausalLM'] are not supported for now` when trying to run `vllm serve "allenai/OLMo-2-1124-7B-Instruct"`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jikunshang** [comment]
https://github.com/vllm-project/vllm/pull/10503 this model should be supported last week. Please install latest vllm and try again.

**Comment by gaardhus** [comment]
Thank you, that worked!
