### ISSUE TITLE
vLLM Discord Server

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#1088]
As the vLLM's user and developer community keeps growing, the current communication model (Github Issues/PRs + random emails) turns out to be not efficient enough. Especially, this prevents communication across different developers without getting through @WoosukKwon and me. Therefore, we finally created the [vLLM Discord server](https://discord.gg/jz7wjKhh6g) to enable more efficient communication. Please join and participate in the discussion! Your issues can get more speedy feedback over there.

We are relatively new to Discord. Please let us know if you have any suggestions.

**Comment by niansong1996** [comment]
@zhuohan123 It seems that the link has expired, can you update the link? Thanks!

**Comment by zhuohan123** [comment]
> @zhuohan123 It seems that the link has expired, can you update the link? Thanks!

Can you try again? Discord is giving me the original link. It doesn't have an expiration date.

**Comment by niansong1996** [comment]
Ah yes, turns out I needed to do some verification for discord and it's showing that the link is valid now. Sorry!

**Comment by carterkrichard** [comment]
Hi all - I am having difficulty joining the discord server. Accepting the server invite just redirects me to my Discord home, and I'm not able to find the server through Discovery. Is anyone else having this issue?

**Comment by hmellor** [comment]
@WoosukKwon shall we close this?
