### ISSUE TITLE
[Misc]: FP8/INT8 for AQLM ？

### ISSUE THREAD

**Issue by Duncan1115** [vllm-project/vllm#10894]
### Anything you want to discuss about vllm.

Using AQLM to inference large scale models (e.g., LLaMA 3 70B) is a bit slow. Does AQLM support matrix vector multiplication of FP8/INT8 ?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by robertgshaw2-neuralmagic** [comment]
No it does not. AQLM is a good method for compression, but the codebooks mean that performance will be slow, especially for high QPS serving.
