### ISSUE TITLE
[Misc]: About example output from processor in Mllama

### ISSUE THREAD

**Issue by QuanHoangDanh** [vllm-project/vllm#10910]
### Anything you want to discuss about vllm.

Hello guys, I have read the code of mllama and this [example ](https://github.com/vllm-project/vllm/blob/127c07480ecea15e4c2990820c457807ff78a057/vllm/model_executor/models/mllama.py#L168) make me confused, it started with prompt ids `128000, 128256, 128000` and below is prompt `<|image|><|begin_of_text|>` I know `<|image|>`'s index is `128256` and `<|begin_of_text|>`'s index is `128000`, therefore I guess this sequence must translate to `<|begin_of_text|><|image|><|begin_of_text|>`. Could anyone please help me clarify this?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
There is an extra `<|begin_of_text|>` token in the `prompt_ids` because the tokenizer automatically adds one. The `prompt` that is shown here is the original prompt that is passed to the tokenizer, rather than the detokenized token ids.

**Comment by QuanHoangDanh** [comment]
@DarkLight1337, I understand, thank you very much.
