### ISSUE TITLE
Is there any ready docker for vllm?

### ISSUE THREAD

**Issue by teraktor2006** [vllm-project/vllm#1091]
If docker file is available, please put Dockerfile and requirements to save some time.
Thanks.

**Comment by williamjeong2** [comment]
vllm can be installed as a python pip package, so you don't need a dockerfile. However, if you want to configure vllm with docker, you can use an image based on NVIDIA's CUDA image.

ex. image tag: `ncidia/cuda:{cuda-version}-devel-ubuntu{ubuntu-version}`
> [!NOTE]
> CUDA version must be within the package's support range.

Of course, the next step is to install vlllm with pip, just like installing any other package in a dockerfile based on this image.

In my case, the final built image was about 25 GB. (The nvidia image is about 10 GB in size because it's a devel image).


Here is my dockerfile:
> [!WARNING]
> This may not work in latest versions.
```dockerfile
ARG CUDA_VERSION=11.8.0
ARG CUDNN_VERSION=8
ARG UBUNTU_VERSION=22.04

# Target the CUDA build image
ARG BASE_CUDA_DEV_CONTAINER=nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}

FROM ${BASE_CUDA_DEV_CONTAINER} as base

ARG APTPKGS="zsh sudo wget tmux nvtop vim neovim curl less"
RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get install -y --no-install-recommends openssh-server openssh-client git git-lfs && \
    python3 -m pip install --upgrade pip && \
    apt-get install -y --no-install-recommends $APTPKGS && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TORCH_CUDA_ARCH_LIST="8.0;8.6+PTX;8.9;9.0"

RUN git clone https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    pip3 install -e . && \
    # TODO: Remove this once error is fixed
    # If ray is not installed version 2.5.1, it could be cause of the following error: AttributeError: 'NoneType' object has no attribute 'fs'
    pip3 install ray==2.5.1 && \
    pip3 cache purge

```

**Comment by teraktor2006** [comment]
Thanks @williamjeong2 . It works for 1 gpu:
ENTRYPOINT [ "python3", "-m", "vllm.entrypoints.openai.api_server", "--tensor-parallel-size", "1", "--host", "0.0.0.0", "--port", "8000" ]

but with --tensor-parallel-size 2 I got this error (when install vllm locally it works fine):

(RayWorker pid=1451) *** SIGBUS received at time=1695144916 on cpu 3 ***
(RayWorker pid=1451) PC: @     0x7f7984381bba  (unknown)  (unknown)
(RayWorker pid=1451)     @     0x7f7984214520       3392  (unknown)
(RayWorker pid=1451)     @ 0x6e312d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1451) [2023-09-19 17:35:16,659 E 1451 3290] logging.cc:361: *** SIGBUS received at time=1695144916 on cpu 3 ***
(RayWorker pid=1451) [2023-09-19 17:35:16,660 E 1451 3290] logging.cc:361: PC: @     0x7f7984381bba  (unknown)  (unknown)
(RayWorker pid=1451) [2023-09-19 17:35:16,661 E 1451 3290] logging.cc:361:     @     0x7f7984214520       3392  (unknown)
(RayWorker pid=1451) [2023-09-19 17:35:16,662 E 1451 3290] logging.cc:361:     @ 0x6e312d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1451) Fatal Python error: Bus error
(RayWorker pid=1451)
(RayWorker pid=1451)
(RayWorker pid=1451) Extension modules: msgpack._cmsgpack, setproctitle, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, yaml._yaml, grpc._cython.cygrpc, ray._raylet, charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, sentencepiece._sentencepiece, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pandas._[libs.tslibs.np](http://libs.tslibs.np/)_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, pyarrow._json (total: 100)
2023-09-19 17:35:16,760 WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff01f951f3f430b15c99f1b62701000000 Worker ID: 08e7f3c808507e2973536c7f7b85ecbea3aff3e97c5e2e038f503392 Node ID: 2c859424bf484833fd98f6c7676e2621c6f5ca1b0991245b6b861c5f Worker IP address: 172.17.0.2 Worker port: 44645 Worker PID: 1451 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 624, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 442, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 250, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 279, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 105, in __init__
    self._init_cache()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 185, in _init_cache
    num_blocks = self._run_workers(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 682, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2542, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
        class_name: RayWorker
        actor_id: 01f951f3f430b15c99f1b62701000000
        pid: 1451
        namespace: f2087012-1034-4470-ac17-97c08d5b0c62
        ip: 172.17.0.2
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(RayWorker pid=1450) *** SIGBUS received at time=1695144916 on cpu 2 ***
(RayWorker pid=1450) PC: @     0x7fbb10670bba  (unknown)  (unknown)
(RayWorker pid=1450)     @     0x7fbb10503520       3392  (unknown)
(RayWorker pid=1450)     @ 0x70372d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1450) [2023-09-19 17:35:16,659 E 1450 3289] logging.cc:361: *** SIGBUS received at time=1695144916 on cpu 2 ***
(RayWorker pid=1450) [2023-09-19 17:35:16,660 E 1450 3289] logging.cc:361: PC: @     0x7fbb10670bba  (unknown)  (unknown)
(RayWorker pid=1450) [2023-09-19 17:35:16,661 E 1450 3289] logging.cc:361:     @     0x7fbb10503520       3392  (unknown)
(RayWorker pid=1450) [2023-09-19 17:35:16,662 E 1450 3289] logging.cc:361:     @ 0x70372d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=1450) Fatal Python error: Bus error
(RayWorker pid=1450)  [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorker pid=1450) Extension modules: msgpack._cmsgpack, setproctitle, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, yaml._yaml, grpc._cython.cygrpc, ray._raylet, charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, sentencepiece._sentencepiece, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pandas._[libs.tslibs.np](http://libs.tslibs.np/)_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, pyarrow._json (total: 100)

**Comment by michaelact** [comment]
Hi, please check my pull request: https://github.com/vllm-project/vllm/pull/1135

**Comment by hmellor** [comment]
Closing as resovled, Dockerfile is now provided.
