### ISSUE TITLE
[Usage]: when i learn quickstart，python vllm/examples /offline_inference.py

### ISSUE THREAD

**Issue by jingAH03** [vllm-project/vllm#10926]
### Your current environment

```text
ImportError: cannot import name 'LLM' from partially initialized module 'vllm' (most likely due to a circular import)
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
I think you just need to cd to your vllm folder and run `python examples/offline_inference.py`.
