### ISSUE TITLE
[Bug]: Different default value for temperature in SamplingParams and ChatCompletionRequest

### ISSUE THREAD

**Issue by yansh97** [vllm-project/vllm#10930]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

The default value for `temperature` in `SamplingParams` is `1.0`. https://github.com/vllm-project/vllm/blob/571da8fc431ec36427ee1034a7779b23229b015e/vllm/sampling_params.py#L176

The default value for `temperature` in `ChatCompletionRequest` is `0.7`. https://github.com/vllm-project/vllm/blob/571da8fc431ec36427ee1034a7779b23229b015e/vllm/entrypoints/openai/protocol.py#L173

This can lead to inconsistencies between online and offline inference results.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
@njhill do you know why this is the case?

**Comment by simon-mo** [comment]
Hmmm it should be 1.0 to align with OpenAI's parameter, please help fix? 

https://platform.openai.com/docs/api-reference/chat

**Comment by yansh97** [comment]
> Hmmm it should be 1.0 to align with OpenAI's parameter, please help fix?[ 重试    错误原因 ](javascript:void(0))
> 
> https://platform.openai.com/docs/api-reference/chat

Yep, I’ll submit a PR.
