### ISSUE TITLE
can we add streaming to llm.generate

### ISSUE THREAD

**Issue by Qinneys** [vllm-project/vllm#1093]
I want to use llm.generate with other api like vector store and stable diffusion api. If it's convenient for you, I really hope to add such an interface

**Comment by jveronvialard** [comment]
Isn't there already a `stream` argument? https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py#L31

**Comment by hmellor** [comment]
Closing as this feature has been implemented.
