### ISSUE TITLE
improve detokenize_incrementally performance

### ISSUE THREAD

**Issue by lynnleelhl** [vllm-project/vllm#1099]
I tried to benchmark the latency of sequence calculation, and I found that the `detokenize_incrementally` function took a significant time. 
more specific, it's the calling to `tokenizer.convert_tokens_to_string` takes the most of time. 

however the input argument of `convert_tokens_to_string` is previous output tokens plus the new one, 
```
output_tokens = prev_output_tokens + [new_token]
```
since the outer function called after each token calculated, the previous output tokens will do `convert_tokens_to_string` multiple times. 

I've measured in my environment, `convert_tokens_to_string` took around 2ms when convert the last token in my sequence (around 300 tokens, model is baichuan 13b), and it got called 300 times, so it cost around 0.3s for the total one sequence, that would be more time if the token number is bigger or batching number increasing. 

I was thinking if `convert_tokens_to_string` could only convert the newly calculated token instead of all the output tokens, so every token only convert once. 
I tried to change the code a little bit, like 
```
output_tokens = [prev_output_text, new_token]
```
and it's 10 times faster for baichuan 13b

so, do we have any special consideration here that can't change like above? If not, I'd like to pull a PR to improve it.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
