### ISSUE TITLE
POTENTIAL ERROR: When doing beam_search, parent sequences are not prefix of child sequences

### ISSUE THREAD

**Issue by Bhuvanesh09** [vllm-project/vllm#1101]
Steps to reproduce:
Using the code 
```python
from vllm import LLM, SamplingParams
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(n=3, use_beam_search=True, temperature=0, early_stopping=True, )
llm = LLM(model="gpt2", gpu_memory_utilization=0.1)

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    for o in output.outputs:
        generated_text = o.text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

When placing a breakpoint at L458 of the file llm_engine.py in the function `_process_sequence_group_samples`, in the first iteration itself the following is observed when one runs the following in the debug console:

```python
p = running_child_seqs[0][1] #parent
c = running_child_seqs[0][0] #child 
print(p.output_logprobs, p.output_tokens)
[OUTPUT]: [{3700: -5.050571918487549}] ['ĠJames']
print(c.output_logprobs, c.output_tokens)
[OUTPUT]: [{1757: -4.613071918487549}] ['ĠJohn']
```

**Comment by Bhuvanesh09** [comment]
Is this because the parent sequence itself is used for the last child_sample instead of forking the parent? This is found at the L384 of the same file. It may make sense to not do this because (child, parent) sequence is used throughout the function and we have mutated the parent itself to be one of the children.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
