### ISSUE TITLE
[Usage]: How to specify the local storage path for vllm download models？

### ISSUE THREAD

**Issue by MiDonkey** [vllm-project/vllm#11049]
### Your current environment

How to specify the local storage path for vllm download models? I have made the following attempts but none of them are effective. VLLM always stores the model in the directory “~/. cache/hug”.
﻿
1. Set the environment variable VLLM_CACHE_ROOT.
2. Set the environment variable HF_HUB_CACHE.
3. When using the function LLM to load models, set its argument "hf_overrides" as {"cache_dir": "xxx"}.
﻿
I would be greatly grateful if someone could help me with this issue.

### Before submitting a new issue...

- [ ] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should set the `HF_HOME` environment variable.
