### ISSUE TITLE
[Feature]: logging request_id instead of random uuid

### ISSUE THREAD

**Issue by cynial** [vllm-project/vllm#11050]
### 🚀 The feature, motivation and pitch

vLLM now supports the x-request-id header, as discussed in this issue: https://github.com/vllm-project/vllm/issues/9593.

However, during the completion process, a random ID is still being used. Could we consider using the x-request-id instead? This change would enhance our ability to trace requests more effectively.

For reference, see the current implementation here: 
https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_completion.py#L89

`request_id = f"cmpl-{random_uuid()}" : `

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
This should be implemented by #10968 already.
