### ISSUE TITLE
API-Server inference becomes very slow after running overnight

### ISSUE THREAD

**Issue by yilihtien** [vllm-project/vllm#1105]
My api-server becomes very slow after running overnight, even if I restart the api-server. It only returns to normal after restarting the VM. However, it becomes slow again after a while. Is there any expert who can help? Thank you very much.
My environment involves creating a virtual machine (VM) on a Hyper Converge Infrastructure machine, and within the VM, setting up a Conda environment. And using an A100 80g GPU.

**Comment by flexchar** [comment]
I'm shooting blindly but have you thought about checking out RAM/SWAP usage? Maybe some kind of caching builds up and goes into using disk which would be significantly slower.

**Comment by yilihtien** [comment]
Thanks for your comment, I will keep watching

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
