### ISSUE TITLE
[Misc]: Brand guidelines around vLLM logo; is there a media kit that can be downloaded with brand assets?

### ISSUE THREAD

**Issue by jessicachitas** [vllm-project/vllm#11066]
### Anything you want to discuss about vllm.

Hi there,

I am working on a website about an AI model that uses vLLM as a runtime and wanted to use the logo in a diagram.

I also was looking for an svg of this logo with a transparent background in both light and dark variants and could not find anything.

What are the guidelines regarding the logo and can it be used in this scenario?

Thanks

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
Just created one https://github.com/vllm-project/media-kit
