### ISSUE TITLE
No support for longer context lengths.

### ISSUE THREAD

**Issue by bhumik1310** [vllm-project/vllm#1108]
Model: Llama-2-chat-hf
The current implementation of vLLM gives the finish_reason as 'length' whilst the native model supports context length of 4024(And works well with the context we've tested it with) , Is the option available to change the native context length supported by the vLLM instance?

I've retried the experiments with the latest release and the issue still persists.

**Comment by sandeepgsc** [comment]
same issue here. Can someone address this?

**Comment by viktor-ferenczi** [comment]
YaRN model support was merged into 0.2.1 already. There have been recently merged PRs like #1510 about longer context length support. It is just not well documented yet.

Try to use YaRN models from https://huggingface.co/NousResearch
