### ISSUE TITLE
[Usage]: Why is QWen VL's dynamic loading of LoRA so slow in execution?

### ISSUE THREAD

**Issue by xxzhang0927** [vllm-project/vllm#11092]
### Your current environment

Environment：
vllm==0.6.4.post1
A800
Performance：
Without loading LoRA, it averages 1 second; with LoRA loading, it averages 3 seconds

### How would you like to use vllm

request_id = str(uuid.uuid4().hex)
sampling_params = SamplingParams(max_tokens=1024)
lora_request = LoRARequest("1234567", int("1234567"), "/qwenvl/sft/output/qwen2-vl-7b-instruct/v2-20241202-150642/checkpoint-280")
result_generator = engine_vllm.generate(
            prompt=llm_inputs,  
            sampling_params=sampling_params,  
            request_id=request_id,
            lora_request=lora_request
        ) 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
How did you test this time?  Did you perform any warmup?

**Comment by xxzhang0927** [comment]
lora_request = LoRARequest("1234567", int("1234567"), "/qwenvl/llamafactory/saves/qwen2_vl-7b/alpaca/sft")

# # result_generator = engine_vllm.generate(prompt=llm_inputs, sampling_params=sampling_params, request_id=request_id)

    async def process_generation():  
        result_generator = engine_vllm.generate(
            prompt=llm_inputs,  
            sampling_params=sampling_params,  
            request_id=request_id,
            lora_request=lora_request
        )

**Comment by xxzhang0927** [comment]
I only added lora_request
