### ISSUE TITLE
Qwen-7B-Chat,use long text(3k以上) without answer？What should I do

### ISSUE THREAD

**Issue by cgq0816** [vllm-project/vllm#1110]
![image](https://github.com/vllm-project/vllm/assets/42534237/581d3fb8-762a-4468-be85-7cba55e969b8)

![image](https://github.com/vllm-project/vllm/assets/42534237/5115dc23-638f-45a0-847e-c41b46ea1ba8)

**Comment by allenhaozi** [comment]
have you set this parameter `--max-num-batched-tokens`

**Comment by cgq0816** [comment]
> have you set this parameter `--max-num-batched-tokens`

CUDA_VISIBLE_DEVICES=2 python openai/api_server.py  --host 0.0.0.0 --port 35300 --model  /data/model/Qwen-7B-Chat  --trust-remote-code --gpu-memory-utilization 0.8 --served-model-name qwen --max-num-batched-tokens 8192 --max-model-len 8192

the same issue

**Comment by allenhaozi** [comment]
> > have you set this parameter `--max-num-batched-tokens`
> 
> CUDA_VISIBLE_DEVICES=2 python openai/api_server.py --host 0.0.0.0 --port 35300 --model /data/model/Qwen-7B-Chat --trust-remote-code --gpu-memory-utilization 0.8 --served-model-name qwen --max-num-batched-tokens 8192 --max-model-len 8192
> 
> the same issue

the latest main branch ?

**Comment by cgq0816** [comment]
> > > have you set this parameter `--max-num-batched-tokens`
> > 
> > 
> > CUDA_VISIBLE_DEVICES=2 python openai/api_server.py --host 0.0.0.0 --port 35300 --model /data/model/Qwen-7B-Chat --trust-remote-code --gpu-memory-utilization 0.8 --served-model-name qwen --max-num-batched-tokens 8192 --max-model-len 8192
> > the same issue
> 
> the latest main branch ?

yes，vllm 0.2.0

**Comment by yxl** [comment]
> > > have you set this parameter `--max-num-batched-tokens`
> > 
> > 
> > CUDA_VISIBLE_DEVICES=2 python openai/api_server.py --host 0.0.0.0 --port 35300 --model /data/model/Qwen-7B-Chat --trust-remote-code --gpu-memory-utilization 0.8 --served-model-name qwen --max-num-batched-tokens 8192 --max-model-len 8192
> > the same issue
> 
> the latest main branch ?

I could reproduce this issue on latest main branch of ee92b58b3ae28a52c2500674de721e7a718432d8

**Comment by chenxu2048** [comment]
Same issue occurred with a long prompt in 0.2.0. The output could be generated correctly using the hf model and weights.

**Comment by cgq0816** [comment]
config.json文件里添加如下配置，解决超长文本输出为空的问题  
"rope_scaling": {
              "type": "dynamic",
                  "factor": 2.0
                    }
