### ISSUE TITLE
[Bug]: grammar_is_likely_lark doesn't work correctly

### ISSUE THREAD

**Issue by comaniac** [vllm-project/vllm#11118]
### Your current environment

`grammar_is_likely_lark` identifies valid EBNF grammars as lark like.

### 🐛 Describe the bug

The `grammar_is_likely_lark` is likely too loose, so even valid EBNF grammar is identified as "Lark like" grammar. For example:

```
root ::= (expr "=" term)+
expr  ::= term ([-+*/] term)*
term  ::= num | "(" expr ")"
num   ::= [0-9]+
```

This is a valid EBNF grammar, but since it has `|`, it is identified as lark like grammar.

cc @mgoin 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by AlbertoCastelo** [comment]
I'm impacted by the same issue. I understand this behavior might be related to trying to add some backward compatibility to previous users (seamlessly migrating them to Xgrammars from outlines). However, it's penalising the new users of XGrammars and potentially leading to silent errors for Lark users.

My take is that if the user wants use Lark with XGrammars they should handle the conversion on their side and vLLM should avoid this "magic" that introduces potential silent errors.

My proposal would be to remove that block entirely (at least until its properly tested):
Current code:
```python
if grammar_is_likely_lark(guided_params.grammar):
    try:
        grammar_str = convert_lark_to_gbnf(guided_params.grammar)
    except ValueError as e:
        raise ValueError(
            "Failed to convert the grammar from Lark to GBNF. "
            "Please either use GBNF grammar directly or specify"
            " --guided-decoding-backend=outlines.\n"
            f"Conversion error: {str(e)}") from e
else:
    grammar_str = guided_params.grammar
```

Proposal:
```python
grammar_str = guided_params.grammar
```

**Comment by AlbertoCastelo** [comment]
The solution proposed by @comaniac in [this PR](https://github.com/vllm-project/vllm/pull/11119) also works for me! Hope that is shipped soon
