### ISSUE TITLE
[Bug]: InternVL2-Llama3-76B-AWQ RUN ERROR KeyError: 'layers.39.mlp.gate_up_proj.qweight'

### ISSUE THREAD

**Issue by Oldpan** [vllm-project/vllm#11122]
### Your current environment

Neuron SDK Version: N/A
vLLM Version: 0.6.4.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PXB     PXB     SYS     SYS     SYS     SYS     0-95            N/A             N/A
GPU1    PIX      X      PXB     PXB     SYS     SYS     SYS     SYS     0-95            N/A             N/A
GPU2    PXB     PXB      X      PXB     SYS     SYS     SYS     SYS     0-95            N/A             N/A
GPU3    PXB     PXB     PXB      X      SYS     SYS     SYS     SYS     0-95            N/A             N/A
GPU4    SYS     SYS     SYS     SYS      X      PIX     PXB     PXB     0-95            N/A             N/A
GPU5    SYS     SYS     SYS     SYS     PIX      X      PXB     PXB     0-95            N/A             N/A
GPU6    SYS     SYS     SYS     SYS     PXB     PXB      X      PXB     0-95            N/A             N/A
GPU7    SYS     SYS     SYS     SYS     PXB     PXB     PXB      X      0-95            N/A             N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NVIDIA_VISIBLE_DEVICES=all
CUBLAS_VERSION=12.2.5.6
NVIDIA_REQUIRE_CUDA=cuda>=9.0
CUDA_CACHE_DISABLE=1
NCCL_VERSION=2.19.3
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
NVIDIA_PRODUCT_NAME=Triton Server
CUDA_VERSION=12.2.2.009
CUDA_VISIBLE_DEVICES=0,1,2,3
CUDA_VISIBLE_DEVICES=0,1,2,3
CUDNN_VERSION=8.9.5.29
NVIDIA_TRITON_SERVER_VERSION=23.10

### Model Input Dumps

None

### 🐛 Describe the bug

Does the **InternVL2-Llama3-76B-AWQ** model support this configuration?  
I am running **vllm version 0.6.4.post1+cu122** with the following command:

```bash
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 OMP_NUM_THREADS=64 vllm serve /InternVL2-Llama3-76B-AWQ \
  --limit-mm-per-prompt image=6 \
  --tensor-parallel-size 8 \
  --gpu-memory-utilization 0.9 \
  --enforce_eager \
  --max_model_len 8192
```

However, I encountered an error. Could you confirm if this model is currently supported or if there are known bugs?

```
ERROR 12-12 03:24:49 engine.py:366] 'layers.39.mlp.gate_up_proj.qweight'
ERROR 12-12 03:24:49 engine.py:366] Traceback (most recent call last):
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 12-12 03:24:49 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 12-12 03:24:49 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 12-12 03:24:49 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 12-12 03:24:49 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
ERROR 12-12 03:24:49 engine.py:366]     super().__init__(*args, **kwargs)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/executor/executor_base.py", line 36, in __init__
ERROR 12-12 03:24:49 engine.py:366]     self._init_executor()
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/executor/multiproc_gpu_executor.py", line 114, in _init_executor
ERROR 12-12 03:24:49 engine.py:366]     self._run_workers("load_model",
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/executor/multiproc_gpu_executor.py", line 195, in _run_workers
ERROR 12-12 03:24:49 engine.py:366]     driver_worker_output = driver_worker_method(*args, **kwargs)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/worker/worker.py", line 152, in load_model
ERROR 12-12 03:24:49 engine.py:366]     self.model_runner.load_model()
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/worker/model_runner.py", line 1074, in load_model
ERROR 12-12 03:24:49 engine.py:366]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
ERROR 12-12 03:24:49 engine.py:366]     return loader.load_model(vllm_config=vllm_config)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/model_loader/loader.py", line 334, in load_model
ERROR 12-12 03:24:49 engine.py:366]     model.load_weights(self._get_all_weights(model_config, model))
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/internvl.py", line 668, in load_weights
ERROR 12-12 03:24:49 engine.py:366]     loader.load_weights(weights)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 229, in load_weights
ERROR 12-12 03:24:49 engine.py:366]     autoloaded_weights = list(self._load_module("", self.module, weights))
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 190, in _load_module
ERROR 12-12 03:24:49 engine.py:366]     yield from self._load_module(prefix,
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 175, in _load_module
ERROR 12-12 03:24:49 engine.py:366]     module_load_weights(weights)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/llama.py", line 586, in load_weights
ERROR 12-12 03:24:49 engine.py:366]     loader.load_weights(
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 229, in load_weights
ERROR 12-12 03:24:49 engine.py:366]     autoloaded_weights = list(self._load_module("", self.module, weights))
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 190, in _load_module
ERROR 12-12 03:24:49 engine.py:366]     yield from self._load_module(prefix,
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/utils.py", line 175, in _load_module
ERROR 12-12 03:24:49 engine.py:366]     module_load_weights(weights)
ERROR 12-12 03:24:49 engine.py:366]   File "/code/lab/projects/vllm/vllm/model_executor/models/llama.py", line 390, in load_weights
ERROR 12-12 03:24:49 engine.py:366]     param = params_dict[name]
ERROR 12-12 03:24:49 engine.py:366] KeyError: 'layers.39.mlp.gate_up_proj.qweight'
INFO 12-12 03:24:50 multiproc_worker_utils.py:120] Killing local vLLM worker processes
```

 Thanks!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
ping @Isotr0py  @mgoin

**Comment by Isotr0py** [comment]
@Oldpan Are you using the [OpenGVLab/InternVL2-Llama3-76B-AWQ](https://huggingface.co/OpenGVLab/InternVL2-Llama3-76B-AWQ)? 

If so, you need to specify `--quantization=awq`, because its quant_config is put in `text_config` and vLLM can't automatically detect it.

**Comment by Isotr0py** [comment]
AWQ only supports float16, you can add `--dtype=half` to use float16.

**Comment by Oldpan** [comment]
> AWQ only supports float16, you can add `--dtype=half` to use float16.

Thanks. It works
