### ISSUE TITLE
Doesn't vllm support GPU H100 serving equipment?

### ISSUE THREAD

**Issue by yuri-son** [vllm-project/vllm#1113]
Hello developers, 
I am leaving an issue because I am getting an unresolved error while serving using the H100 device. 

I checked that the server is up and running and the input queries are communicated, but I am getting a 500 Internal Server Error.
The container image I'm using is **thebloke/cuda11.8.0-ubuntu22.04-pytorch**

First of all, the machine I am using is "NVIDIA H100" and the error I am facing is **RuntimeError: CUDA error: no kernel image is available for execution on the device 
Compile with 'TORCH_USE_CUDA_DSA' to enable device-side assertions.** 
This is where the error occurred: vllm/model_executor/paraller_utils/tensor_parallel/layers.py, line 361, in forward output = output_ + self.bias if self.bias is not None else output_

If you have a workaround for this error, I would really appreciate your advice... plz..

**Comment by ngoanpv** [comment]
Try to upgrade the torch and xformers version, the above issue should be fixed:

pip install --pre torch==2.1.0.dev20230902+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118 
pip install -U xformers

**Comment by CrazyBrick** [comment]
> Try to upgrade the torch and xformers version, the above issue should be fixed:
> 
> pip install --pre torch==2.1.0.dev20230902+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118 pip install -U xformers

could you explain it in detail？

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
