### ISSUE TITLE
Cannot use LLama-70b with multiple GPUs

### ISSUE THREAD

**Issue by zdchu** [vllm-project/vllm#1116]
Hi there,

I failed to use LLama-70b on an 8-A100 machine. The script I use is 

`model = LLM(model=script_args.model_name, tensor_parallel_size=2)`

The error is 

```
2023-09-20 18:06:25,855 WARNING services.py:1889 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67108864 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2023-09-20 18:06:26,013 INFO worker.py:1642 -- Started a local Ray instance.
Traceback (most recent call last):
  File "vllm_rank_model_id.py", line 124, in <module>
    model = LLM(model=script_args.model_name, tensor_parallel_size=1)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 66, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 220, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
  File "/opt/conda/envs/vllm/lib/python3.8/site-packages/vllm/engine/ray_utils.py", line 102, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```

It seems it did not detect the GPUs. Can you take a look at this issue?

**Comment by davedgd** [comment]
Not ideal, but for the moment, try adding the following in your code prior to calling the `model = LLM(...)` line:

```
import ray, torch

ray.shutdown()

ray.init(num_gpus=torch.cuda.device_count())
```

**Comment by epolewski** [comment]
Any way to workaround this when loading from console?

**Comment by HelloCard** [comment]
if change as:
ray.shutdown()
ray.init(num_gpus=2, address=ray_address, ignore_reinit_error=True)
then:
```
(llm) root@DESKTOP-1CSPSTT:~# CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.api_server --model /mnt/e/Code/text-generation-webui/models/orca-2-13B-AWQ --trust-remote-code --quantization awq --max-model-len 4096 --tensor-parallel-size 2
WARNING 12-04 22:44:49 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2023-12-04 22:44:51,897 INFO worker.py:1673 -- Started a local Ray instance.
INFO 12-04 22:44:52 llm_engine.py:73] Initializing an LLM engine with config: model='/mnt/e/Code/text-generation-webui/models/orca-2-13B-AWQ', tokenizer='/mnt/e/Code/text-generation-webui/models/orca-2-13B-AWQ', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=awq, seed=0)
INFO 12-04 22:47:07 llm_engine.py:218] # GPU blocks: 2513, # CPU blocks: 655
Traceback (most recent call last):
  File "/root/miniconda3/envs/llm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/llm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/vllm-main/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/root/vllm-main/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/root/vllm-main/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/root/vllm-main/vllm/engine/async_llm_engine.py", line 305, in _init_engine
    return engine_class(*args, **kwargs)
  File "/root/vllm-main/vllm/engine/llm_engine.py", line 112, in __init__
    self._init_cache()
  File "/root/vllm-main/vllm/engine/llm_engine.py", line 230, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/root/vllm-main/vllm/engine/llm_engine.py", line 746, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/root/vllm-main/vllm/engine/llm_engine.py", line 723, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/root/miniconda3/envs/llm/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/llm/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/llm/lib/python3.10/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorkerVllm.execute_method() (pid=741, ip=172.28.17.124, actor_id=a96d8f05ce6434b4ffea633a01000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f9b6dc0cf40>)
  File "/root/vllm-main/vllm/engine/ray_utils.py", line 31, in execute_method
    return executor(*args, **kwargs)
  File "/root/vllm-main/vllm/worker/worker.py", line 112, in init_cache_engine
    self.cache_engine = CacheEngine(self.cache_config, self.model_config,
  File "/root/vllm-main/vllm/worker/cache_engine.py", line 44, in __init__
    self.gpu_cache = self.allocate_gpu_cache()
  File "/root/vllm-main/vllm/worker/cache_engine.py", line 75, in allocate_gpu_cache
    key_blocks = torch.empty(
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```

**Comment by HelloCard** [comment]
@epolewski 
I solve this problam, edit vllm\engine\ray_utils.py
change
ray.init(address=ray_address, ignore_reinit_error=True)
as
ray.shutdown()
ray.init(num_gpus=2, address=ray_address, ignore_reinit_error=True)

num_gpus=2 because I have 2 gpu.
--max-model-len set as 2048, then no "RuntimeError: handle_0 INTERNAL ASSERT FAILED" ERR, and all will be ok.
But this is still wrong, because my v-memory, there is obviously no problem in supporting a context of 4096 length: 10G of the 44G video memory is used for model loading, and the remaining space is 30G!

**Comment by epolewski** [comment]
> @epolewski I solve this problam, edit vllm\engine\ray_utils.py change ray.init(address=ray_address, ignore_reinit_error=True) as ray.shutdown() ray.init(num_gpus=2, address=ray_address, ignore_reinit_error=True)
> 
> num_gpus=2 because I have 2 gpu. --max-model-len set as 2048, then no "RuntimeError: handle_0 INTERNAL ASSERT FAILED" ERR, and all will be ok. But this is still wrong, because my v-memory, there is obviously no problem in supporting a context of 4096 length: 10G of the 44G video memory is used for model loading, and the remaining space is 30G!

Tried this and @HelloCard 's suggestion and got this:

torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.

**Comment by double-vin** [comment]
> > @epolewski I solve this problam, edit vllm\engine\ray_utils.py change ray.init(address=ray_address, ignore_reinit_error=True) as ray.shutdown() ray.init(num_gpus=2, address=ray_address, ignore_reinit_error=True)
> > num_gpus=2 because I have 2 gpu. --max-model-len set as 2048, then no "RuntimeError: handle_0 INTERNAL ASSERT FAILED" ERR, and all will be ok. But this is still wrong, because my v-memory, there is obviously no problem in supporting a context of 4096 length: 10G of the 44G video memory is used for model loading, and the remaining space is 30G!
> 
> Tried this and @HelloCard 's suggestion and got this:
> 
> torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1 ncclUnhandledCudaError: Call to CUDA function failed.
> 
> Note that I'm pretty sure VLLM can see both cards. When I send only the second GPU via cuda_visible_devices, it only uses the second GPU. I've also tried "export NCCL_IB_DISABLE=1" as suggested elsewhere on the internet for this error. When I set the NCCL Debug to 1, I get:
> 
> Last error: Cuda failure 'invalid argument' (RayWorkerVllm pid=16696) Desktop:16696:16696 [1] misc/cudawrap.cc:179 NCCL WARN Failed to find CUDA library libcuda.so (NCCL_CUDA_PATH='') : _Z42ncclKernel_SendRecv_RING_SIMPLE_Sum_int8_tP11ncclDevCommmP8ncclWork (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO NET/Socket : Using [0]eth0:172.19.106.70<0> (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Using network Socket (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=6000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 0(=7000) and dev 1(=6000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P Chunksize set to 131072 (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Channel 00 : 1[6000] -> 0[7000] via SHM/direct/direct (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1. (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Could not enable P2P between dev 1(=6000) and dev 0(=7000) (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO Channel 01 : 1[6000] -> 0[7000] via SHM/direct/direct (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] transport.cc:154 NCCL WARN Cuda failure 'invalid argument' (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO (RayWorkerVllm pid=16696) Desktop:16696:16803 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^lo,docker,veth [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.) (RayWorkerVllm pid=16696) Desktop:16696:16696 [1] NCCL INFO Bootstrap : Using eth0:172.19.106.70<0> (RayWorkerVllm pid=16696) Desktop:16696:16696 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory (RayWorkerVllm pid=16696) Desktop:16696:16696 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
> 
> so then I re-enabled it
> 
> (RayWorkerVllm pid=17757) Desktop:17757:17864 [1] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ^lo,docker,veth [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.) (RayWorkerVllm pid=17757) Desktop:17757:17757 [1] NCCL INFO Bootstrap : Using eth0:172.19.106.70<0> (RayWorkerVllm pid=17757) Desktop:17757:17757 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory (RayWorkerVllm pid=17757) Desktop:17757:17757 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation (RayWorkerVllm pid=17757) [repeated 2x across cluster]
> 
> It looks like libnccl-net maybe isn't installed? I tried setting NCCL_SOCKET_IFNAME=lo and NCCL_HOME=/usr/local/cuda and changing NCCL_SOCKET_IFNAME to no avail.

I also have this question

**Comment by wanghh2000** [comment]
Why ray `Placement group` can not have 2 GPUs?  

(ServeController pid=2645112)   File "/data/miniconda3_envs/z2/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 101, in initialize_cluster
(ServeController pid=2645112)     raise ValueError(
(ServeController pid=2645112) ValueError: Placement group bundle cannot have more than 1 GPU.

https://github.com/vllm-project/vllm/blob/79d64c495463665cf80937a05226806785cfa583/vllm/engine/ray_utils.py#L100

**Comment by francescov1** [comment]
Also seeing this error when using the vllm Docker image with Mixtral and CUDA 12.1.1
