### ISSUE TITLE
[Bug]: ARM vLLM container build failing due to outlines v0.1.9

### ISSUE THREAD

**Issue by sidharthrajaram** [vllm-project/vllm#11178]
### Your current environment

M2 Mac with Docker Desktop

### 🐛 Describe the bug

Building ARM vLLM Docker image with `docker build -f Dockerfile.arm -t vllm-cpu-env --shm-size=4g .` leads to the following error:
```
24.95   copying python/outlines_core/fsm/regex.py -> build/lib.linux-aarch64-cpython-310/outlines_core/fsm
24.95   running build_ext
24.95   running build_rust
24.95   error: can't find Rust compiler
24.95 
24.95   If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
24.95 
24.95   To update pip, run:
24.95 
24.95       pip install --upgrade pip
24.95 
24.95   and then retry package installation.
24.95 
24.95   If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
24.97   error: subprocess-exited-with-error
24.97   
24.97   × Building wheel for outlines_core (pyproject.toml) did not run successfully.
24.97   │ exit code: 1
24.97   ╰─> See above for output.
24.97   
24.97   note: This error originates from a subprocess, and is likely not a problem with pip.
24.97   full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmp9inm24ey
24.97   cwd: /tmp/pip-install-k98qbmgt/outlines-core_52043b4e88924bfeb2524aaea4a95439
24.97   Building wheel for outlines_core (pyproject.toml): finished with status 'error'
24.97   ERROR: Failed building wheel for outlines_core
24.97 Failed to build outlines_core
25.00 ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (outlines_core)
------
Dockerfile.arm:37
--------------------
  36 |     
  37 | >>> RUN --mount=type=cache,target=/root/.cache/pip \
  38 | >>>     --mount=type=bind,src=requirements-common.txt,target=requirements-common.txt \
  39 | >>>     --mount=type=bind,src=requirements-cpu.txt,target=requirements-cpu.txt \
  40 | >>>     pip install -v -r requirements-cpu.txt
  41 |     
```

This was because of missing arm64 support for `outlines-core` (https://github.com/dottxt-ai/outlines-core/issues/122) which was causing install for `outlines` v0.1.9 to break. This was recently fixed in both `outlines-core` and `outlines` (https://github.com/dottxt-ai/outlines/pull/1336).

Accordingly, the `outlines` dependency in requirements-common.txt should be bumped to v0.1.11.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by RachelShalom** [comment]
thanks @sidharthrajaram , had the same issue and upgrading outlines to 0.1.11 solved the build issue

**Comment by sidharthrajaram** [comment]
@RachelShalom yep exactly, that's what I had to do locally once they pushed the new release. Glad to hear it was the same fix. There's an (updated) PR open to address that on `main` #11180

**Comment by russellb** [comment]
yep, #11180 should solve this

**Comment by russellb** [comment]
> yep, #11180 should solve this

Oops, I thought you had linked to #11140 which is an older PR for the same thing.
