### ISSUE TITLE
Support custom models

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#112]
We need to provide clean abstractions and interfaces so that users can easily plug in their custom models.

**Comment by hmellor** [comment]
Can this be considered done now that there is a documentation page detailing how to do it https://docs.vllm.ai/en/latest/models/adding_model.html?

**Comment by DarkLight1337** [comment]
We now support automatic detection of generation/embedding task (`vllm/models/interfaces_base.py`) as well as additional features such as multimodal input (`vllm/models/interfaces.py`) for both built-in and OOT models. It's safe to say that this issue has been resolved.
