### ISSUE TITLE
--download-dir is not strictly obeyed

### ISSUE THREAD

**Issue by drunlade** [vllm-project/vllm#1120]
## Issue

When using the `--download_dir` argument, the server modules (I only tested with them) still download and use files in the `~/.cache/` path. Note that the actual model file is not downloaded there, but the surrounding config files are.

## Expected Behaviour

All file are downloaded to and used from the path provided by `--download_dir`

## STR

```bash
rm -rf ~/.cache/huggingface/hub/models--facebook--opt-125m/

root@425b8da2809f:/# python -m vllm.entrypoints.api_server --host 0.0.0.0 --port 10102 --download-dir /models/

Downloading (…)lve/main/config.json: 100%|███████████████████████████| 651/651 [00:00<00:00, 463kB/s]
INFO 09-21 04:58:19 llm_engine.py:72] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, download_dir='/models/', load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
Downloading (…)okenizer_config.json: 100%|███████████████████████████| 685/685 [00:00<00:00, 419kB/s]
Downloading (…)olve/main/vocab.json: 100%|████████████████████████| 899k/899k [00:00<00:00, 4.80MB/s]
Downloading (…)olve/main/merges.txt: 100%|████████████████████████| 456k/456k [00:00<00:00, 8.08MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████| 441/441 [00:00<00:00, 2.01MB/s]
INFO 09-21 04:58:25 llm_engine.py:202] # GPU blocks: 17928, # CPU blocks: 7281
WARNING 09-21 04:58:25 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO:     Started server process [914]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:10102 (Press CTRL+C to quit)
```

```bash
root@425b8da2809f:/# ls -latr /models/models--facebook--opt-125m/snapshots/27dcfa74d334bc871f3234de431e71c6eeba5dd6/
total 0
drwxr-xr-x 1 root root 4096 Sep 20 15:38 ..
lrwxrwxrwx 1 root root   76 Sep 21 04:55 pytorch_model.bin -> ../../blobs/2d74da6615135c58cf3cf9ad4cb11e7c613ff9e55fe658a47ab83b6c8d1174a9
```

```bash
root@425b8da2809f:/# ls -latr ~/.cache/huggingface/hub/models--facebook--opt-125m/snapshots/27dcfa74d334bc871f3234de431e71c6eeba5dd6/
total 8
drwxr-xr-x 3 root root 4096 Sep 21 04:58 ..
lrwxrwxrwx 1 root root   52 Sep 21 04:58 config.json -> ../../blobs/b3fb716a3024261980becb2382e31a3780985130
lrwxrwxrwx 1 root root   52 Sep 21 04:58 tokenizer_config.json -> ../../blobs/27c24ca9d908d0b678b20c698aeb9e950c44d865
lrwxrwxrwx 1 root root   52 Sep 21 04:58 vocab.json -> ../../blobs/0a39732b2d8be8e493cab3da68b68cc3e28221de
lrwxrwxrwx 1 root root   52 Sep 21 04:58 merges.txt -> ../../blobs/226b0752cac7789c48f0cb3ec53eda48b7be36cc
lrwxrwxrwx 1 root root   52 Sep 21 04:58 special_tokens_map.json -> ../../blobs/5dfa36546b8eddce0e04df3133c30df43fcc3828
```

**Comment by viktor-ferenczi** [comment]
This is a problem with HuggingFace libraries even without vLLM. I tried to talk it down from caching, but I could not. Just accept the fact and make sure the `~/.cache` folder is on a partition with enough space. The only advantage of this is that if a model is downloaded multiple times it still consumes 1x the same. But yeah, deleting the `~/.cache` folder can accidentally delete all your downloaded models, which is bad.

**Comment by drunlade** [comment]
Hmm, so in fact it might be better to mount my host system `models` dir to `~/.cache/huggingface/hub/` and just drop the `--download-dir`

Not a nice solution, but sounds like you're saying there's no fix here unless HF files it?

**Comment by viktor-ferenczi** [comment]
Yes. Please let us know whether it fixed your issue, so we can close this ticket.

**Comment by viktor-ferenczi** [comment]
See also `TRANSFORMERS_CACHE` here: https://huggingface.co/docs/transformers/installation?highlight=transformers_cache#caching-models

**Comment by drunlade** [comment]
Thanks, that works. Is it possible to export the ENV based on the input argument so `TRANSFORMERS_CACHE` is set to the path given at runtime? I imagine the input params are parsed long before `TRANSFORMERS_CACHE` is read?

**Comment by drunlade** [comment]
I'll close this for now, do consider though finding a way to make the argument work as intended.

**Comment by SuperBruceJia** [comment]
> ## Issue
> When using the `--download_dir` argument, the server modules (I only tested with them) still download and use files in the `~/.cache/` path. Note that the actual model file is not downloaded there, but the surrounding config files are.
> 
> ## Expected Behaviour
> All file are downloaded to and used from the path provided by `--download_dir`
> 
> ## STR
> ```shell
> rm -rf ~/.cache/huggingface/hub/models--facebook--opt-125m/
> 
> root@425b8da2809f:/# python -m vllm.entrypoints.api_server --host 0.0.0.0 --port 10102 --download-dir /models/
> 
> Downloading (…)lve/main/config.json: 100%|███████████████████████████| 651/651 [00:00<00:00, 463kB/s]
> INFO 09-21 04:58:19 llm_engine.py:72] Initializing an LLM engine with config: model='facebook/opt-125m', tokenizer='facebook/opt-125m', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, download_dir='/models/', load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
> Downloading (…)okenizer_config.json: 100%|███████████████████████████| 685/685 [00:00<00:00, 419kB/s]
> Downloading (…)olve/main/vocab.json: 100%|████████████████████████| 899k/899k [00:00<00:00, 4.80MB/s]
> Downloading (…)olve/main/merges.txt: 100%|████████████████████████| 456k/456k [00:00<00:00, 8.08MB/s]
> Downloading (…)cial_tokens_map.json: 100%|██████████████████████████| 441/441 [00:00<00:00, 2.01MB/s]
> INFO 09-21 04:58:25 llm_engine.py:202] # GPU blocks: 17928, # CPU blocks: 7281
> WARNING 09-21 04:58:25 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
> INFO:     Started server process [914]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:10102 (Press CTRL+C to quit)
> ```
> 
> ```shell
> root@425b8da2809f:/# ls -latr /models/models--facebook--opt-125m/snapshots/27dcfa74d334bc871f3234de431e71c6eeba5dd6/
> total 0
> drwxr-xr-x 1 root root 4096 Sep 20 15:38 ..
> lrwxrwxrwx 1 root root   76 Sep 21 04:55 pytorch_model.bin -> ../../blobs/2d74da6615135c58cf3cf9ad4cb11e7c613ff9e55fe658a47ab83b6c8d1174a9
> ```
> 
> ```shell
> root@425b8da2809f:/# ls -latr ~/.cache/huggingface/hub/models--facebook--opt-125m/snapshots/27dcfa74d334bc871f3234de431e71c6eeba5dd6/
> total 8
> drwxr-xr-x 3 root root 4096 Sep 21 04:58 ..
> lrwxrwxrwx 1 root root   52 Sep 21 04:58 config.json -> ../../blobs/b3fb716a3024261980becb2382e31a3780985130
> lrwxrwxrwx 1 root root   52 Sep 21 04:58 tokenizer_config.json -> ../../blobs/27c24ca9d908d0b678b20c698aeb9e950c44d865
> lrwxrwxrwx 1 root root   52 Sep 21 04:58 vocab.json -> ../../blobs/0a39732b2d8be8e493cab3da68b68cc3e28221de
> lrwxrwxrwx 1 root root   52 Sep 21 04:58 merges.txt -> ../../blobs/226b0752cac7789c48f0cb3ec53eda48b7be36cc
> lrwxrwxrwx 1 root root   52 Sep 21 04:58 special_tokens_map.json -> ../../blobs/5dfa36546b8eddce0e04df3133c30df43fcc3828
> ```

You may use one of the following ways to change the Transformers cache directory:
```shell
export TRANSFORMERS_CACHE=/projectnb/pnn/.cache
export HF_HOME=/projectnb/pnn/.cache
export HF_DATASETS_CACHE=/projectnb/pnn/.cache
```

or 

```python
import os 

os.environ['TRANSFORMERS_CACHE'] = "/projectnb/pnn/.cache"
os.environ['HF_HOME'] = "/projectnb/pnn/.cache"
os.environ['HF_DATASETS_CACHE'] = "/projectnb/pnn/.cache"
```

Best regards,

Shuyue
Dec. 17th, 2023

**Comment by adivekar-utexas** [comment]
Can we reopen this issue? I believe it is bug, as I shall explain below:

In `vllm==0.6.4.post1`, I have traced this issue to `download_weights_from_hf` in `vllm/model_executor/model_loader.weight_utils.py`. Code is reproduced below.

The issue is that this checks HF_HUB_OFFLINE, which is by default False. The purpose of setting HF_HUB_OFFLINE is to **only** load from disk. From the HF docs:
>  HF_HUB_OFFLINE
> If set, no HTTP calls will be made to the Hugging Face Hub. If you try to download files, only the cached files will be accessed. If no cache file is detected, an error is raised This is useful in case your network is slow and you don’t care about having the latest version of a file.

For this reason, by default HF_HUB_OFFLINE is False. Thus, the if-else gets triggered and `allow_patterns` can be set. This can prevent using the downloaded file in the later call to `snapshot_download`.

Code for `vllm/model_executor/model_loader.weight_utils.py#download_weights_from_hf`: 
```
def download_weights_from_hf(
    model_name_or_path: str,
    cache_dir: Optional[str],
    allow_patterns: List[str],
    revision: Optional[str] = None,
    ignore_patterns: Optional[Union[str, List[str]]] = None,
) -> str:
    """Download model weights from Hugging Face Hub.

    Args:
        model_name_or_path (str): The model name or path.
        cache_dir (Optional[str]): The cache directory to store the model
            weights. If None, will use HF defaults.
        allow_patterns (List[str]): The allowed patterns for the
            weight files. Files matched by any of the patterns will be
            downloaded.
        revision (Optional[str]): The revision of the model.
        ignore_patterns (Optional[Union[str, List[str]]]): The patterns to
            filter out the weight files. Files matched by any of the patterns
            will be ignored.

    Returns:
        str: The path to the downloaded model weights.
    """
    if not huggingface_hub.constants.HF_HUB_OFFLINE:
        # Before we download we look at that is available:
        fs = HfFileSystem()
        file_list = fs.ls(model_name_or_path, detail=False, revision=revision)

        # depending on what is available we download different things
        for pattern in allow_patterns:
            matching = fnmatch.filter(file_list, pattern)
            if len(matching) > 0:
                allow_patterns = [pattern]
                break

    logger.info("Using model weights format %s", allow_patterns)
    # Use file lock to prevent multiple processes from
    # downloading the same model weights at the same time.
    with get_lock(model_name_or_path, cache_dir):
        hf_folder = snapshot_download(
            model_name_or_path,
            allow_patterns=allow_patterns,
            ignore_patterns=ignore_patterns,
            cache_dir=cache_dir,
            tqdm_class=DisabledTqdm,
            revision=revision,
            local_files_only=huggingface_hub.constants.HF_HUB_OFFLINE,
        )
    return hf_folder
```

**Comment by adivekar-utexas** [comment]
FYI using `download_dir` from the LLM class works as expected.

**Comment by malte-j** [comment]
Just ran into this again, expecting the `download_dir` parameter to work. Can this issue stay open until the parameter behaves as expected?
