### ISSUE TITLE
AssertionError: Prompt input should have only one seq.

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#1121]
- OS: **Ubuntu 22.04**
- GPUs: **2x 4090** (2x 24GB)
- CUDA: **11.8**
- CPU: **Ryzen 3800X**
- RAM: **64GB**
- vLLM build: **main** `400b8289`

Started the API server with this command:
```sh
python -O -u -m vllm.entrypoints.api_server \
    --host=0.0.0.0 \
    --port=8000 \
    --model=$HOME/models/WizardLM/WizardCoder-Python-13B-V1.0 \
    --tokenizer=hf-internal-testing/llama-tokenizer \
    --tensor-parallel-size=2 \
    --block-size=16 \
    --swap-space=8
```

After running for a few minutes it crashes with `500 Internal server error`.

Error in the log:
```
AssertionError: Prompt input should have only one seq.
```

Please find the full log attached:
[vllm-server-error.log.gz](https://github.com/vllm-project/vllm/files/12680614/vllm-server-error.log.gz)

I've removed the part with all the successful requests to redact the prompts, but kept the failed request in full.

Tested with the latest official version (0.1.7), it worked perfectly for the first attempt with the exact same prompts. However the order may have been different due to running up to 32 generations in parallel. The above error with the custom build happened 3 times in a row, so it does not seem to depend on the order of prompts, however.

**UPDATE:** The same error has just happened to vLLM 0.1.7 with a different set of prompts.

**Comment by WoosukKwon** [comment]
@zhuohan123 Could you take a look?

**Comment by viktor-ferenczi** [comment]
In case you cannot reproduce I can try to log the `input_metadata` or the `seq_group` here. Just let me know if you need it.

**Comment by viktor-ferenczi** [comment]
The same error has just happened to vLLM 0.1.7, so this is not a newly introduced issue. It just happens with a different set of prompts.

**Comment by viktor-ferenczi** [comment]
Added logging of `seq_group` in the `assert` statement, then reproduced the issue:
```
AssertionError: Prompt input should have only one seq: seq_group = ([339, 411, 412], SamplingParams(n=3, best_of=3, presence_penalty=0.0, frequency_penalty=0.2, temperature=0.5, top_p=1.0, top_k=-1, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], ignore_eos=False, max_tokens=2522, logprobs=None))
```

**Comment by viktor-ferenczi** [comment]
This is currently a blocker. The server does not stop when it happens, but ends up in a loop of `500 Internal Server Error` responses as the client retries. It is possible to detect the problem and restart the server, then it eventually completes, but since the problem happens very soon (after only a few hundred requests or even sooner) it is not a good workaround.

I can reproduce the problem here and can try to debug this myself if you wish.

**Comment by hmellor** [comment]
@zhuohan123 was this issue resolved?
