### ISSUE TITLE
The quality of the generated answers is degraded

### ISSUE THREAD

**Issue by yangzhj53** [vllm-project/vllm#1126]
I use baichuan2 as llm. When inputting long text, although the speed is improved, the quality of the generated answers has declined. Some people say that it is caused by different sampling during generation. How can I modify it?

**Comment by zjuzhfbloodz** [comment]
same situation

**Comment by viktor-ferenczi** [comment]
Please see whether there have been any changes to the settings in `SamplingParams`. Does reverting to the old settings help? If yes, then which setting caused the issue?

**Comment by viktor-ferenczi** [comment]
Maybe related: #1128

**Comment by akaihaoshuai** [comment]
可以参考文档 https://zhuanlan.zhihu.com/p/658780653

**Comment by Sanster** [comment]
You can try the modifications mentioned here.
https://github.com/vllm-project/vllm/issues/712#issuecomment-1707928868

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
