### ISSUE TITLE
[Bug]: gpt2 输出只有！

### ISSUE THREAD

**Issue by G1017** [vllm-project/vllm#11316]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

python3 -m vllm.entrypoints.openai.api_server --mo
del /models/openai/gpt2 --host 127.0.0.1 --port 12345

curl 127.0.0.1:12345/v1/completions \
    -H "Content-Type: application/json" \
    -d '{"model":"/share/fshare/common/models/openai/gpt2",
        "prompt":"hello. ",
        "temperature":0.7,
        "max_tokens":128}'

output's text only "!",not correct answer.
![image](https://github.com/user-attachments/assets/567aa2bb-b676-44d8-a1fd-dc8d4c4bb3b3)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by G1017** [comment]
Latest version，and model ：https://huggingface.co/openai-community/gpt2/tree/main

**Comment by G1017** [comment]
> Which version of vLLM are you using? Can you show the output of `collect_env.py`? Please also link the HF repo you downloaded the model from.

Which version of vLLM are you using? Can you show the output of collect_env.py? Please also link the HF repo you downloaded the model from.

**Comment by G1017** [comment]
> Which version of vLLM are you using? Can you show the output of `collect_env.py`? Please also link the HF repo you downloaded the model from.

Latest version vllm；and  model：https://huggingface.co/openai-community/gpt2/tree/main

**Comment by DarkLight1337** [comment]
Did you solve it?
