### ISSUE TITLE
A callback in vLLM engine that expose the running stats

### ISSUE THREAD

**Issue by tanmayv25** [vllm-project/vllm#1132]
While working on adding vLLM support in [Triton Inference Server](https://github.com/triton-inference-server/tutorials/blob/main/Quick_Deploy/vLLM/README.md), we found that it would be beneficial for us to track certain stats like the following:

        - infligtht count
        - max infligtht capacity
        - kv cache blocks in use
        - total kv cache blocks
        
It would be great if vllm engine can take an optional callback function as input which will expose these stats. These stats can then be exported to Prometheus metrics. In a production environment, this information would be useful in routing requests to different instances of vLLM engines running on different machines.

Let me know if there is any alternative way of reliably obtaining this information from a vLLM engine.

**Comment by hmellor** [comment]
Metrics are now provided in Prometheus format at `/metrics`
