### ISSUE TITLE
[New Model]: Add Cohere2 Model

### ISSUE THREAD

**Issue by CXIAAAAA** [vllm-project/vllm#11357]
### 🚀 The feature, motivation and pitch

Recently cohere released a [CommandR7B](https://github.com/huggingface/transformers/tree/main/src/transformers/models/cohere2) model in huggingface and I would like to contribute the vllm implementation version of it. @simon-mo 

The model also uses the interleave attention like gemma2 and mistral, so kv cache optimization is needed. I saw it is also on the roadmap. https://github.com/vllm-project/vllm/issues/9464

### Additional context

I have integrated and tested it work with all the benchmark scripts and would like to add a feature branch for review.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
This has already been added in https://github.com/vllm-project/vllm/pull/11203, and is in the latest released version of vLLM.

**Comment by CXIAAAAA** [comment]
@DarkLight1337 i think there is some issues for the impl:
1. the attention is sssf, so when passing the sliding_window as None(global attention layer) and at the same time pass in the cache_config, it will go to this branch https://github.com/vllm-project/vllm/blob/b880ffb87e0bcde5e3693203b480df49e46d67bc/vllm/attention/layer.py#L51, which makes the sliding window back to 4096. So instead of [4096, 4096, 4096, None]. You current implementation will become [4096, 4096, 4096, 4096]. You could print here to double check: https://github.com/vllm-project/vllm/blob/b880ffb87e0bcde5e3693203b480df49e46d67bc/vllm/attention/backends/flash_attn.py#L616
2. i did this to fix: https://github.com/vllm-project/vllm/pull/11358

**Comment by DarkLight1337** [comment]
Thanks! I'll ask @simon-mo to take a look since he added this.

**Comment by simon-mo** [comment]
actually i think @youkaichao added this

**Comment by youkaichao** [comment]
@CXIAAAAA thanks for the report! The sliding window support for cohere2 is indeed broken, and I added a pr https://github.com/vllm-project/vllm/pull/11583 to fix it.

gemma2 works fine, because `cache_config.sliding_window` is `None` for models with interleaved sliding window.
