### ISSUE TITLE
Use multi-turn prompts for benchmark_throughput.py

### ISSUE THREAD

**Issue by imoneoi** [vllm-project/vllm#1139]
Do we consider using multi-turn prompts instead of the first turn for throughput benchmarking? It would be more realistic.

**Comment by hmellor** [comment]
@simon-mo is this something you'd be interested in seeing implemented?

**Comment by pliops-daniels** [comment]
Please see the following RFC and PR:
https://github.com/vllm-project/vllm/issues/20265
https://github.com/vllm-project/vllm/pull/20267

This is possibly what you are looking for.
