### ISSUE TITLE
IP bind error

### ISSUE THREAD

**Issue by qyhdt** [vllm-project/vllm#1141]
Hi, vllm team
   I hit an error when I start a service according to your documentation, gives me below error.
Anyone can help me to take a look.

Documentation:
![image](https://github.com/vllm-project/vllm/assets/7843730/ebb65f37-429c-49ce-9e92-45b411e00a56)
Error
![image](https://github.com/vllm-project/vllm/assets/7843730/78bf99ee-beb2-42ca-94e1-29f8998a7f8e)

**Comment by qyhdt** [comment]
It needs to add two arguments -- host  xxxx --port 8000, and also if anyone want to let this service can be access from other machine, host need to be set as 0.0.0.0

**Comment by viktor-ferenczi** [comment]
You have some other process running on port `8000` or your previous instance still keep that port blocked for a few more seconds (TCP/IP stack (mis)feature).

How to find the existing process running on port `8000`:
```sh
netstat -nlp | grep 8000
```

Then just kill it and try starting vLLM again.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
