### ISSUE TITLE
源码openai api_server.py报错

### ISSUE THREAD

**Issue by sunbeibei-hub** [vllm-project/vllm#1142]
AttributeError: 'ChatCompletionRequest' object has no attribute 'stop_token_ids'

**Comment by sunbeibei-hub** [comment]
pip install 不报错

**Comment by viktor-ferenczi** [comment]
Support has been added in #1097, but not released yet. Please build vLLM from its `main` branch if you need it right now. How to build is described in https://github.com/vllm-project/vllm/blob/main/CONTRIBUTING.md

**Comment by hmellor** [comment]
Closing as resolved.
