### ISSUE TITLE
H800 support

### ISSUE THREAD

**Issue by cobraheleah** [vllm-project/vllm#1143]
does vllm compatible with the gpu of H800

**Comment by viktor-ferenczi** [comment]
In theory yes, but H800 is pretty new so I'm not sure whether it has been tested yet. 

Can we kindly ask to test vLLM on the H800 and see whether it works for your use case?

Please share you results here or on the Discord (invite is in the README).

@WoosukKwon I suggest adding a short list of the most popular hardware supported to the README to avoid creating question type issues.

**Comment by hmellor** [comment]
Closing as stale.
