### ISSUE TITLE
[Usage]: missing openai templates

### ISSUE THREAD

**Issue by JohnConnor123** [vllm-project/vllm#11474]
### Your current environment

Is there a way to fix this errorr? All guides start with a line with the llm serve command, but it doesn’t work for me (even with tokenizer option) + I prefer a docker container?
![image](https://github.com/user-attachments/assets/66124ce1-7a75-4b45-bc21-ecc874493d1e)

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Which model are you using? Chat Completions API is only supported for models with a chat template.

**Comment by JohnConnor123** [comment]
> Chat Completions API is only supported for models with a chat template.

facebook/opt-125m, IlyaGusev/saiga_nemo_12b and etc

**Comment by DarkLight1337** [comment]
Those models don't define a chat template. In that case, you can provide your own chat template: some examples can be found [here](https://github.com/vllm-project/vllm/tree/main/examples).

**Comment by JohnConnor123** [comment]
> Those models don't define a chat template. In that case, you can provide your own chat template: some examples can be found [here](https://github.com/vllm-project/vllm/tree/main/examples).

I run llm from docker, not from venv python environment. How do I pass my chat template to the vllm engine? I didn't find any similar arguments here: https://docs.vllm.ai/en/latest/usage/engine_args.html

**Comment by DarkLight1337** [comment]
There is a `--chat-template` parameter that's specific to `[vllm serve](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#cli-reference)`.

**Comment by JohnConnor123** [comment]
Got it, thanks!
