### ISSUE TITLE
The First vLLM SF Bay Area Meetup

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#1149]
We are excited to announce that we will hold the first vLLM SF bay area meetup at 6pm on 10/5 (Thu). The vLLM team will give a deep dive on vLLM and share the future plans and roadmaps of the project. We will also have our users and contributors come and share their experiences. You can find the event details and RSVP [here](https://lu.ma/first-vllm-meetup). Please join us if you are around the bay area. Let's come together, share our stories, and envision the future of vLLM.

**Comment by yanxiyue** [comment]
is there any way to attend the meeting online, such as zoom?

**Comment by LiuXiaoxuanPKU** [comment]
> is there any way to attend the meeting online, such as zoom?

Sorry we don't have the online option, but we will share the talk slides from vLLM team after the meetup.

**Comment by gandalf012** [comment]
Can you share the slides please

**Comment by zhuohan123** [comment]
Please find the meetup slides [here](https://docs.google.com/presentation/d/1QL-XPFXiFpDBh86DbEegFXBXFXjix4v032GhShbKf3s/edit?usp=sharing)!

**Comment by Aya-ZIbra** [comment]
Are there any future planned events? I wish to join the upcoming events

**Comment by zhuohan123** [comment]
> Are there any future planned events? I wish to join the upcoming events

Will update in the repo if there is any future events!

**Comment by tp-nan** [comment]
Hi, is there any more ppt or video?
