### ISSUE TITLE
Is vllm willing to support models based on other AI frameworks, such as mindspore?

### ISSUE THREAD

**Issue by wxsIcey** [vllm-project/vllm#11507]
Hello,

we are MindSpore eco-developers! MindSpore is a new open source deep learning training/inference framework that could be used for mobile, edge and cloud scenarios.(You can get a more detailed introduction to MindSpore at: https://www.mindspore.cn/en)

We want to add a MindSpore backend to vllm to expand the MindSpore ecosystem, and at the same time, also make the vllm ecosystem better.

Our team has several software engineers with years of development experience, and we are supported by the team of MindSpore framework developers.

We would like to know if your community accepts models based on MindSpore? and if it is possible, we can discuss the technical details further.

**Comment by WangErXiao** [comment]
如果支持这些框架，那vllm就走不远了。

**Comment by wxsIcey** [comment]
> 如果支持这些框架，那vllm就走不远了。
https://github.com/vllm-project/vllm/issues/3620
Google后续都有将JAX集成到vLLM的想法，为什么我们国内的框架不可以这样做呢？
https://github.com/vllm-project/vllm/issues/7692
现在已经有人提出npu支持vllm，那么将Mindspore集成到vLLM，我理解也是可以的

**Comment by wxsIcey** [comment]
> 如果支持这些框架，那vllm就走不远了。

https://github.com/vllm-project/vllm/issues/3620
Google后续都有将JAX集成到vLLM的想法，为什么我们国内的框架不可以这样做呢？
https://github.com/vllm-project/vllm/issues/7692
现在已经有人提出npu支持vllm，那么将Mindspore集成到vLLM，我理解也是可以的

**Comment by ywang96** [comment]
Personally I think it makes more sense for the support for alternative frameworks to stay as a fork of vLLM. For now the scope of vLLM is still limited to PyTorch and we don't have plan to expand to other frameworks.

#3620 as you mentioned is adding support for TPUs with PyTorch XLA rather than supporting JAX directly, and general speaking supporting different hardware is a much different story than supporting other DL frameworks.

**Comment by wxsIcey** [comment]
> Personally I think it makes more sense for the support for alternative frameworks to stay as a fork of vLLM. For now the scope of vLLM is still limited to PyTorch and we don't have plan to expand to other frameworks.
> 
> #3620 as you mentioned is adding support for TPUs with PyTorch XLA rather than supporting JAX directly, and general speaking supporting different hardware is a much different story than supporting other DL frameworks.

Thank you very much for your patient reply. We will continue to pay attention to the technical development of vllm and think about the possibility of connecting mindpore with vllm technology.
