### ISSUE TITLE
[Feature]: ValueError: Model architectures ['DeepseekV3ForCausalLM'] are not supported for now.

### ISSUE THREAD

**Issue by ybdesire** [vllm-project/vllm#11520]
### 🚀 The feature, motivation and pitch

The DeepseekV3 is a very powerful model. Would you help support the model deployment?

https://huggingface.co/deepseek-ai/DeepSeek-V3

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
See: https://github.com/vllm-project/vllm/pull/11502
