### ISSUE TITLE
support whisper?

### ISSUE THREAD

**Issue by silvacarl2** [vllm-project/vllm#1152]
this is a question, not an issue.

Any ideas if this could be used to support whisper?

**Comment by viktor-ferenczi** [comment]
There is no support yet, but it is on the [Development Roadmap](https://github.com/vllm-project/vllm/issues/244)

If you want to help adding it, then please see [Adding a New Model](https://vllm.readthedocs.io/en/latest/models/adding_model.html).

**Comment by viktor-ferenczi** [comment]
Duplicate of #180

**Comment by silvacarl2** [comment]
excellent thx.  vllm is amazing.
