### ISSUE TITLE
AWS EC2 T4 g4dn.xlarge error

### ISSUE THREAD

**Issue by silvacarl2** [vllm-project/vllm#1153]
I am getting this error on an AWS EC2 T4 g4dn.xlarge:

ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5.

is there a modifier that would allow me to run it on T4?

**Comment by viktor-ferenczi** [comment]
Duplicate of #1157

**Comment by silvacarl2** [comment]
sorry got it, thx.
