### ISSUE TITLE
Hello, which vllm version support DeepSeek-V3?

### ISSUE THREAD

**Issue by 13416157913** [vllm-project/vllm#11559]
### Your current environment

Hello, which vllm version support DeepSeek-V3?

### Model Input Dumps

Hello, which vllm version support DeepSeek-V3?

### 🐛 Describe the bug

Hello, which vllm version support DeepSeek-V3?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by chenchunhui97** [comment]
how much GPU memory do u have?

**Comment by 13416157913** [comment]
> how much GPU memory do u have?

8*A800 80GB

**Comment by DarkLight1337** [comment]
It is supported since [v0.6.6](https://github.com/vllm-project/vllm/releases/tag/v0.6.6)
