### ISSUE TITLE
ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5.

### ISSUE THREAD

**Issue by lonngxiang** [vllm-project/vllm#1157]
when run Baichuan2-13B-Chat

**Comment by viktor-ferenczi** [comment]
Try to build vLLM from sources (`main` branch) and use the `--dtype float` parameter.

See also https://github.com/vllm-project/vllm/commit/1ac4ccf73c91370f1fcb4f60c1117646cd7a7502
