### ISSUE TITLE
[Usage]: VLLM version question

### ISSUE THREAD

**Issue by OliverLeeXZ** [vllm-project/vllm#11597]
### Your current environment

My current vllm version is Version: 0.6.5, and I guessing the problem I faced results from vllm version mismatched.

### How would you like to use vllm

I using hack method to run the custom decoding strategy in llama2, using such codes:
1.if HAS_TRITON:
    from vllm.model_executor.layers.ops.sample import sample as sample_triton
2.from vllm.sequence import (
    CompletionSequenceGroupOutput,
    Logprob,
    PromptLogprobs,
    SampleLogprobs,
    SamplerOutput,
    SequenceOutput,
)
3.if envs.VLLM_USE_FLASHINFER_SAMPLER and find_spec("flashinfer"):
    import flashinfer.sampling

    # yapf: disable
    from flashinfer.sampling import (
        top_k_top_p_sampling_from_probs as flashinfer_top_k_top_p_sampling)

    # yapf: enable
else:
    flashinfer_top_k_top_p_sampling = None

and facing such problems:

1.Traceback (most recent call last):
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/test.py", line 3, in <module>
    from sampler import FacadeSampler
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/sampler.py", line 16, in <module>
    from vllm.model_executor.layers.ops.sample import sample as sample_triton
ModuleNotFoundError: No module named 'vllm.model_executor.layers.ops'
2.Traceback (most recent call last):
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/test.py", line 3, in <module>
    from sampler import FacadeSampler
  File "/home/lxz/CODE/hallucination/top_nsigma/src/vllm/sampler.py", line 21, in <module>
    from vllm.sequence import (
ImportError: cannot import name 'SamplerOutput' from 'vllm.sequence' (/home/lxz/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/sequence.py)

I guess these problem maybe result from vllm version, so which is the proper version?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You can view the history of `sequence.py` for each version on GitHub. It shouldn't take long to figure out the version you need.

**Comment by OliverLeeXZ** [comment]
Thanks for your timely reply!
