### ISSUE TITLE
Transfer vllm-client repository into vllm-project

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#1159]
Hi @WoosukKwon ,

I've developed a standalone Python client for the vLLM API:
- https://github.com/viktor-ferenczi/vllm-client
- https://pypi.org/project/vllm-client/

It has tests and example and documented. I already started to use this package in my projects.

The reason for a separate Python API client is to allow vLLM user to have minimal dependencies in their Python projects. I am aware that it is possible by just using `requests` directly, but that's more verbose and less convenient, especially for newbies. Delivering a separate HTTP library would also allow for seamless upgrade to a newer vLLM API version should we need one without the clients to do anything than updating the Python package.

I think this repository should belong into the `vllm-project` GitHub organization instead of my private GitHub.

Could you please consider transferring the above repository or allowing me to do that? Thank you.

I've attempted to request a transfer, but it does not work like that:
![image](https://github.com/vllm-project/vllm/assets/1848514/112d31e0-4be7-4006-8887-9aef2f1abf02)

**Comment by viktor-ferenczi** [comment]
@casper-hansen What is your opinion on this one?

The `/stats` endpoint is not implemented in the client yet. I'm not entirely sure if it needs to be added at all for generic use.

**Comment by casper-hansen** [comment]
For serving vLLM models, I use [runpod python](https://github.com/runpod/runpod-python) myself. One thing to consider is that vLLM is already a big job to maintain. Adding a client to maintain and develop may be too big of a task for the authors to take care of.

There are also other frameworks like [ray](https://github.com/ray-project/ray/blob/eeaf0ae063c62ca12abfb9d056758603dc36dc1b/doc/source/serve/doc_code/vllm_example.py#L16) that supports vLLM for deployments.
