### ISSUE TITLE
killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node

### ISSUE THREAD

**Issue by starlitsky2010** [vllm-project/vllm#1160]
#033[2m#033[33m(raylet)#033[0m [DATE] (raylet) node_manager.cc:3007: 2 Workers (tasks /
 actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: abd406d415bd2b74a5
e281968fd76aa200d56e4529fd1c1cd4373840, IP: 10.0.167.26) over the last time period. To see more information about th
e Workers killed on this node, use `ray logs raylet.out -ip 10.0.167.26`
#033[2m#033[33m(raylet)#033[0m
#033[2m#033[33m(raylet)#033[0m Refer to the documentation on how to address the out of memory issue: https://docs.ra
y.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reduci
ng task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RA
Y_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_mon
itor_refresh_ms` to zero.

I met this problem. How many memory with tensor_parallel_size=4 when infernce with a 1.3B model?

**Comment by viktor-ferenczi** [comment]
Please provide the OS, CUDA version, CPU, CPU RAM, GPU(s), GPU VRAM sizes. If you have a way to reproduce please share that as well. Thanks.

**Comment by starlitsky2010** [comment]
My mistake, I just exported all logits to calculate the PPL with a big batch. Then it causes OOM.
