### ISSUE TITLE
[Installation]: no image for vllm/vllm-openai:v0.6.6.post1 on docker hub

### ISSUE THREAD

**Issue by ktrapeznikov** [vllm-project/vllm#11633]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
pip install -vvv vllm
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ktrapeznikov** [comment]
latest one is for v0.6.6.post1 https://hub.docker.com/r/vllm/vllm-openai/tags

**Comment by simon-mo** [comment]
Thank you for letting us know! I have just uploaded it.
