### ISSUE TITLE
I am using vllm to start a video processing service for qwen2vl-7b, but there is an error message when passing in video_url. The error message is Unknown part type video_url, and the vllm version is 0.6.3.post1[Usage]: 

### ISSUE THREAD

**Issue by hyyuananran** [vllm-project/vllm#11640]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Please show the command that you used to serve the model, and also how you sent the request to the server.

**Comment by hyyuananran** [comment]
python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8088 --model /app/qwen2vl-7b/ --dtype auto --tensor-parallel-size 1 --gpu-memory-utilization 0.95 -max-model-len 8096 --served-model-name qwen2vl-7b --trust-remote-code


query = {"model":"qwen2vl-7b",
"messages":[
{"role":"user",
"content":[
{"type":"text","text":"xxxxxxxxx"},
{"type":"video_url","video_url":{"url":xxxxxxxxx}
}]
}]
}

**Comment by DarkLight1337** [comment]
What type of URL are you passing in? In v0.6.3, only `data:video/jpeg` URLs are supported. v0.6.6.post1 supports more types of video URLs.

**Comment by hyyuananran** [comment]
It is a URL for an S3 repository, and the file format is mp4
