### ISSUE TITLE
Phi 1.5 support

### ISSUE THREAD

**Issue by axel578** [vllm-project/vllm#1167]
Phi 1.5 is a new model from Microsoft, supporting this model would be extremely usefull.

A detailed list of info of phi 1.5 can be found here : [https://huggingface.co/microsoft/phi-1_5](url)

Its basically supporting MixFormerSequentialConfig .
The phi 1.5 has weird features, also 4 bit support would be great !! (and not only on gpu, but cpu also please, this model size should work ok on cpu)

**Comment by viktor-ferenczi** [comment]
Please consider adding this to the [Roadmap](https://github.com/vllm-project/vllm/issues/244).

It is also a low hanging fruit for new contributors learning into vLLM's code base.

**Comment by adivoj** [comment]
We neeed it

**Comment by Bojun-Feng** [comment]
Hi, I am interested in integrating phi 1.5. However, I am new to the codebase and am a bit overwhelmed by the large code base. Are there any recommended resources to get started?

**Comment by adivoj** [comment]
Hi Bojum,

Good to hear that you're interested. I found the models being defined here: /vllm/model_executor/models and are registered here: /vllm/model_executor/model_loader.py. 

Here are some phi1.5 sources you can use:
https://huggingface.co/microsoft/phi-1_5/tree/main
PR: https://huggingface.co/microsoft/phi-1_5/discussions/22/files
https://github.com/OpenAccess-AI-Collective/axolotl/tree/2d60ba3a6ea4def14e6ab974299322a0bf90d5bb/src/axolotl/models/phi

I was thinking of pushing all models to GPT4 and make it come up with the new one based on modeling_mixformer_sequential.py :)

**Comment by Bojun-Feng** [comment]
Hi adivoj, thank you so much for the quick response! Unfortunately, I found out that my machine is not compatible with vLLM and therefore can not locally test the code. As a result, other people might be a better fit...

**Comment by Linzecong** [comment]
I tried to adapt it and successfully aligned the model weights. The output results were correct before passing through the attention layer, but they were incorrect after passing through the attention layer. Later I found that he used CrossAttention [https://huggingface.co/microsoft/phi-1_5/blob/main/modeling_mixformer_sequential.py#L518](https://huggingface.co/microsoft/phi-1_5/blob/main/modeling_mixformer_sequential.py#L518) I am not sure if this problem is caused.

**Comment by andersonbcdefg** [comment]
I was looking into this. I believe the "cross-attention" used in Phi-1.5 is not true cross-attention, it's just used for current token to attend to past KV-cache during autoregressive generation. From what I can see, the Phi-1.5 architecture is basically the same as a GPT-NeoX with attention/FFN in parallel, except:

1) In each transformer block the pre-FFN and pre-Attention layernorms are the same (GPT-NeoX doesn't share these params, as noted in their paper).
2) Phi-1.5 has a bias on the output linear layer, and GPT-NeoX does not.

Alternatively, Phi-1.5 has the same architecture as GPT-J, except:
1) GPT-J has separate q, k, v projections and Phi-1.5 has W_qkv
2) GPT-J does not have bias on the q, k, v layers, and Phi-1.5 does have bias on W_qkv

It shouldn't be too crazy to adapt these, given that vLLM already supports GPT-NeoX and GPT-J. The MixFormer modelling file on Hugging Face is unnecessarily complicated relative to how small the architecture changes they made are relative to GPT-NeoX/GPT-J.

**Comment by check39** [comment]
Any update on this? Can anyone make change accordingly if you are familiar with code base?

**Comment by adivoj** [comment]
Wow, thanks a lot man! All the best to you :)

**Comment by Linzecong** [comment]
> Hey guys, just opened the PR integrating phi-1.5 into the codebase. Even though the model works, the output on some sequences does not exactly match the HF implementation, so if anyone could have a look, it could fasten the merge progress a lot.
> 
> Thanks! @andersonbcdefg @Linzecong @adivoj @Bojun-Feng

Thank you very much for your support! I did a quick verification, I set top_k to 1 and the output aligned in most cases. I think it is caused by accuracy issues, because when I use float32 to load the model, the hf output is very stable when top_k is 1. But when using half to load, even if top_k is 1, the output is still unstable.

**Comment by adivoj** [comment]
Man, they just announced phi v 2.0 https://youtu.be/S2gn_EoSWac?feature=shared

**Comment by maximzubkov** [comment]
I almost envisioned it when @sytelus reacted on the PR 😅

**Comment by olsaarik** [comment]
Just a heads up, the microsoft/phi-1_5 model has been updated: https://huggingface.co/microsoft/phi-1_5/commit/271c3397ab4e1f8f4e49868b1e8ba0be95363c88 The relevant changes for vLLM are only in naming. The architecture is now called "PhiForCausalLM" and names of model weights have also changed.

**Comment by WoosukKwon** [comment]
Hi @olsaarik, thanks for the heads up! We noticed the change and adapted it in #1664. I've checked that vLLM works with the new Phi model naming and weights.
