### ISSUE TITLE
The Prompt is not right when i was using vllm.entrypoints.openai.api_server

### ISSUE THREAD

**Issue by meichangsu1** [vllm-project/vllm#1169]
My local model is CodeLlama2-13b-hf ，when i use vllm by  "python -m vllm.entrypoints.openai.api_server   xxx" ，why the full prompt is : prompt: "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.\n### Human: Got any creative ideas for a 10 year old’s birthday?\n### Assistant: Of course! Here are some creative ideas for a 10-year-old's birthday party:\n1. Treasure Hunt: Organize a treasure hunt in your backyard or nearby park. Create clues and riddles for the kids to solve, leading them to hidden treasures and surprises.\n2. Science Party: Plan a science-themed party where kids can engage in fun and interactive experiments. You can set up different stations with activities like making slime, erupting volcanoes, or creating simple chemical reactions.\n3. Outdoor Movie Night: Set up a backyard movie night with a projector and a large screen or white sheet. Create a cozy seating area with blankets and pillows, and serve popcorn and snacks while the kids enjoy a favorite movie under the stars.\n4. DIY Crafts Party: Arrange a craft party where kids can unleash their creativity. Provide a variety of craft supplies like beads, paints, and fabrics, and let them create their own unique masterpieces to take home as party favors.\n5. Sports Olympics: Host a mini Olympics event with various sports and games. Set up different stations for activities like sack races, relay races, basketball shooting, and obstacle courses. Give out medals or certificates to the participants.\n6. Cooking Party: Have a cooking-themed party where the kids can prepare their own mini pizzas, cupcakes, or cookies. Provide toppings, frosting, and decorating supplies, and let them get hands-on in the kitchen.\n7. Superhero Training Camp: Create a superhero-themed party where the kids can engage in fun training activities. Set up an obstacle course, have them design their own superhero capes or masks, and organize superhero-themed games and challenges.\n8. Outdoor Adventure: Plan an outdoor adventure party at a local park or nature reserve. Arrange activities like hiking, nature scavenger hunts, or a picnic with games. Encourage exploration and appreciation for the outdoors.\nRemember to tailor the activities to the birthday child's interests and preferences.

**Comment by viktor-ferenczi** [comment]
_The ticket description is unreadable, so I asked GPT-4 to reformat it while keeping all the text the same by the letter:_

**Local Model:** CodeLlama2-13b-hf

**Command:** `python -m vllm.entrypoints.openai.api_server xxx`

**Full Prompt:**
```
A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.

### Human: Got any creative ideas for a 10 year old’s birthday?
### Assistant: Of course! Here are some creative ideas for a 10-year-old's birthday party:

1. Treasure Hunt:
   - Organize a treasure hunt in your backyard or nearby park.
   - Create clues and riddles for the kids to solve, leading them to hidden treasures and surprises.

2. Science Party:
   - Plan a science-themed party where kids can engage in fun and interactive experiments.
   - Set up different stations with activities like making slime, erupting volcanoes, or creating simple chemical reactions.

3. Outdoor Movie Night:
   - Set up a backyard movie night with a projector and a large screen or white sheet.
   - Create a cozy seating area with blankets and pillows.
   - Serve popcorn and snacks while the kids enjoy a favorite movie under the stars.

4. DIY Crafts Party:
   - Arrange a craft party where kids can unleash their creativity.
   - Provide a variety of craft supplies like beads, paints, and fabrics.
   - Let them create their own unique masterpieces to take home as party favors.

5. Sports Olympics:
   - Host a mini Olympics event with various sports and games.
   - Set up different stations for activities like sack races, relay races, basketball shooting, and obstacle courses.
   - Give out medals or certificates to the participants.

6. Cooking Party:
   - Have a cooking-themed party where the kids can prepare their own mini pizzas, cupcakes, or cookies.
   - Provide toppings, frosting, and decorating supplies.
   - Let them get hands-on in the kitchen.

7. Superhero Training Camp:
   - Create a superhero-themed party where the kids can engage in fun training activities.
   - Set up an obstacle course.
   - Have them design their own superhero capes or masks.
   - Organize superhero-themed games and challenges.

8. Outdoor Adventure:
   - Plan an outdoor adventure party at a local park or nature reserve.
   - Arrange activities like hiking, nature scavenger hunts, or a picnic with games.
   - Encourage exploration and appreciation for the outdoors.

Remember to tailor the activities to the birthday child's interests and preferences.
```

**Comment by viktor-ferenczi** [comment]
I see two issues here:

1. The `ConversationTemplate` is provided by a `get_conversation_template` call, which comes from the `fastchat` package.

```py
from fastchat.model.model_adapter import get_conversation_template
```

Please read the code of the `get_gen_prompt` function in [vllm/entrypoints/openai/api_server.py](vllm/entrypoints/openai/api_server.py) to how the returned template is used together with the messages sent in the API request.

Workaround: You can send an `str` in `messages` to ignore the template returned by `fastchat`. You must format with the right prompt template on your (client) side for this to work.

2. [CodeLlama2-13b-hf](https://huggingface.co/codellama/CodeLlama-13b-hf) is a base model, not an instruction or chat fine-tuned one. It means that it does not have a prompt template, just completes the prompt you provide. Consider using [codellama/CodeLlama-13b-Instruct-hf](https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf) instead.

**Comment by agrogov** [comment]
When inferencing `mistralai/Mistral-7B-Instruct-v0.1` or `mistralai/Mistral-7B-v0.1` models vLLM using [this template](https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py#L312) instead of [this one](https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py#L845)

**Comment by meichangsu1** [comment]
i have solved this problem by using python -m vllm.entrypoints.openai.api_server xxx --served-model llama2/CodeLlama2-13b-hf

**Comment by agrogov** [comment]
`--served-model mistralai/Mistral-7B-Instruct-v0.1` not helped at all, still see in logs:
`### Human: Got any creative ideas for a 10 year old’s birthday?\n### Assistant: Of course! Here are some creative ideas for a 10-year-old's birthday party:\n`

**Comment by cheperuiz** [comment]
Im having the same issue, is there a way to pass the template from the command line? I'm running the docker image...
