### ISSUE TITLE
Do not initialize process group when using a single GPU

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#117]
Currently we call `torch.distributed.init_process_group` even for a single GPU. This is redundant and causes errors when the LLM object is created multiple times.

**Comment by neubig** [comment]
Just commenting to upvote this. I'm encountering the same issue when I run two experiments in a row within the same program (even if the old LLM object is out of scope by the time the second one is initialized).

**Comment by gburachas** [comment]
I get this problem after a single call to LLM, and even if only one GPU is visible.

**Comment by hmellor** [comment]
Closing because a single worker will now only use way Ray if the user specifies `--worker-use-ray`
