### ISSUE TITLE
[Discussion] Any other libraries/techniques that can be combined with vllm to further speed up inference?

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#1175]
My current setup is this, and it takes around 2 seconds to generate a response from a prompt, was wondering if there are additional libraries/packages that can be used on top of vllm to achieve subsecond performance?
`
llm = LLM(model="mosaicml/mpt-7b-instruct", trust_remote_code=True,dtype="float16",tensor_parallel_size=2)
`

**Comment by hmellor** [comment]
Quantization is something you could try.

Also, discussions such as this are best had in https://github.com/vllm-project/vllm/discussions.
