### ISSUE TITLE
Parallel Requests in AsyncLLMEngine giving different results even when using argmax

### ISSUE THREAD

**Issue by louisowen6yellow** [vllm-project/vllm#1182]
Hi, I was experimenting with the [vllm server](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py), and found an interesting issue. 

I checked the issues and couldn't find raised issues that are related to this. Other issues are comparing the difference in output between vLLM and HuggingFace, while this issue is about comparing the difference in outputs generated by vLLM itself at different times even when setting `temperature=0`, `top_p=1`, and `top_k=-1`.

---------------------------------------------

TL;DR: 

Why vLLM give different responses when we're sending the same input data and the same input prompt when we're sending **parallel requests/batch requests** multiple times? While it's always giving the same response when sending a **single request** multiple times?

---------------------------------------------

Experiment setup:

- Model: fine-tuned llama-2 7B and 13B

- We’re testing with a QnA task using ~700 query & knowledge pairs.

- For parallel requests testing, we’re sampling 3 pairs randomly in each iteration.
   - Thus, each query may have been sampled more than once and we’re interested in examining whether multiple answers from the same query are the exact same or not.
   - Hence, we’re testing deterministic behavior.
- For single requests testing, we’re sending only the same sample one after another (not in parallel)
   - We’re also interested to examine whether the responses coming are the same or not.

---------------------------------------------

 Experiment results:

- vLLM 13B model (QLoRA fine-tuning)
   - When sending parallel requests for 500 iterations: `5/557` (0.9%) queries are inconsistent -> we’re not getting the same answers multiple times from the same query
   - When sending single request using the same sample for 150 iterations, we only get `1` unique answer, no variation
- vLLM 7B model (regular fine-tuning, without QLoRA)
    - When sending parallel requests  for 500 iterations: `2/585` (0.3%) queries are inconsistent -> we’re not getting the same answers multiple times from the same query
    - When sending single request using the same sample for 150 iterations, we only get `1` unique answer, no variation

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by ehuaa** [comment]
@hmellor I still encountered this issue in 0.3.3

**Comment by hmellor** [comment]
@ehuaa please try with the latest version 0.4.0

If you're still having problems, please open an issue using the new template so we have all the details.
