### ISSUE TITLE
Automatically configure `max_num_batched_tokens` based on model length

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#1189]
BTW, can you set the `max_num_batched_tokens` argument default value to 4096 or 8192 since many LLMs have supported 4096/8192 prompt now.

_Originally posted by @irasin in https://github.com/vllm-project/vllm/issues/1018#issuecomment-1714852004_

**Comment by WoosukKwon** [comment]
@esmeetu I think this will fix your issue on shared memory. Basically, if you do not want to fully utilize the model's context length, you can simply overwrite `max_model_len` (and avoid the shared memory error). Then, `max_num_batched_tokens` will be automatically set according to the specified model length. Does this make sense to you?

**Comment by esmeetu** [comment]
@WoosukKwon Setting maximum model length is good for me. 
But i have to always set this parameter when using model which has 16384 length. Because my Turing GPU can only afford 65536 bytes with extra padding(reach 67644). So it cannot pass the check in worker.

**Comment by WoosukKwon** [comment]
@esmeetu Now that #1198 is merged, you can simply set `max_model_len` as 16000. You don't have to care about `max_num_batched_tokens`.

**Comment by esmeetu** [comment]
@WoosukKwon Thanks.
