### ISSUE TITLE
How can I convert a large model with vllm from fp16 to int8

### ISSUE THREAD

**Issue by piaosa** [vllm-project/vllm#1190]
such as llama2-13b

**Comment by viktor-ferenczi** [comment]
It is not a vLLM question. 

If you're interested in using vLLM with 8-bit quantized models, then follow the [PR on adding AWQ W8A8 support](https://github.com/vllm-project/vllm/pull/1112).

Please close this ticket if you found your answer.

**Comment by AniZpZ** [comment]
Quantization is not a vLLM question. But you can inference in w8a8 with this [pr](https://github.com/vllm-project/vllm/pull/1112)
We impelement int8 llama 13b with smoothquant [here](https://github.com/AniZpZ/smoothquant/tree/llama-dev), it might help you.

**Comment by hmellor** [comment]
Quantization is supported via AWQ, GPTQ and SqueezeLM
