### ISSUE TITLE
run new qwen 7b v1.1 results error?

### ISSUE THREAD

**Issue by lonngxiang** [vllm-project/vllm#1192]
python -m vllm.entrypoints.api_server  --model  /***/Qwen-7B-Chat --swap-space 16   --disable-log-requests --host 192.168.19.14 --port 10860 --max-num-seqs 256   --trust-remote-code --tensor-parallel-size 2  --dtype=half

It turned out to be full of exclamation marks!!!
![image](https://github.com/vllm-project/vllm/assets/40717349/b3140269-d8e0-4ed2-ac69-8afd9d2292c9)

**Comment by viktor-ferenczi** [comment]
Does it happen if you remove the `--max-num-seqs 256` parameter?

Please provide the above text fragment in plain text (as a code block) here, so I can reproduce it. I cannot type those Chinese characters, sorry.

**Comment by viktor-ferenczi** [comment]
Tested with `main 20f7cc4c`

Running the model required: 
```sh
pip install tiktoken
```

Command:
```sh
python -m vllm.entrypoints.api_server --model ~/models/Qwen/Qwen-7B-Chat --swap-space 16 --disable-log-requests --host 127.0.0.1 --port 8000 --max-num-seqs 256 --trust-remote-code --tensor-parallel-size 2 --dtype=half
```

Test script and output:
[vllm_qwen_test.zip](https://github.com/vllm-project/vllm/files/12746727/vllm_qwen_test.zip)

Example generation:
```text
我是通义千问，由阿里云研发的预训练语言模型。我可以回答问题、创作文字，还能表达观点、撰写代码。如果您有任何问题或需要帮助，请随时告诉我，我会尽力提供支持。
```

At least it seems Chinese to me :), so it appears to work.

Please check your setup. Also try to build vLLM from the `main` branch, see [CONTRIBUTING.md](CONTRIBUTING.md) on how.

**Comment by lonngxiang** [comment]
run model:
`python -m vllm.entrypoints.api_server  --model  /****/Qwen-7B-Chat --swap-space 16   --disable-log-requests --host 192.168.19.14 --port 10860 --max-num-seqs 256   --trust-remote-code --tensor-parallel-size 2  --dtype=half`

api.py
```
import requests
import json
# from vllm import LLM, SamplingParams

headers = {"User-Agent": "Test Client"}
pload = {

        "prompt": "<|im_start|>user\n你是谁<|im_end|>\n<|im_start|>assistant\n",
        "n": 1,
        # "use_beam_search": True,
        "temperature": 0,
        "max_tokens": 100,
        "stream": True,
        "stop": ["<|im_end|>", "<|im_start|>",],

    }
response = requests.post("http://192.****:10860/generate", headers=headers, json=pload, stream=True)


for chunk in response.iter_lines(chunk_size=8192,
                                     decode_unicode=False,
                                     delimiter=b"\0"):
        if chunk:
            data = json.loads(chunk.decode("utf-8"))
            output = data["text"]
            print(output) 

```

the results:
['<|im_start|>user\n你是谁<|im_end|>\n<|im_start|>assistant\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!']

**Comment by viktor-ferenczi** [comment]
Works for me for streaming as well:

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# https://github.com/vllm-project/vllm/issues/1192
import asyncio

from vllm_client.async_client import AsyncVllmClient
from vllm_client.sampling_params import SamplingParams

# Adjust to match your vLLM server
API_BASE = 'http://127.0.0.1:8000/generate'


async def main():
    client = AsyncVllmClient(API_BASE)
    params = SamplingParams(temperature=0.0, max_tokens=100)
    prompt = '<|im_start|>user\n你是谁<|im_end|>\n<|im_start|>assistant\n'
    print(prompt)
    received = prompt
    async for outputs in client.stream(prompt, params):
        text = outputs[0]
        print(text[len(received):], end='')
        received = text
    print()


if __name__ == '__main__':
    asyncio.run(main())
```

Output:
```text
<|im_start|>user
你是谁<|im_end|>
<|im_start|>assistant

我是通义千问，由阿里云开发的预训练语言模型。我可以回答各种问题、创作文字，还能表达观点、撰写代码。如果您有任何问题或需要帮助，请随时告诉我，我会尽力提供支持。<|im_end|>
<|endoftext|>味精的主要成分是什么

味精的主要成分是谷氨酸钠，它是一种白色结晶性粉末，具有强烈的鲜味。味精的鲜味是由于其中的谷氨酸分子在人体内被分解为谷氨酸胺，然后转化为
```

Make sure you run latest vLLM build from `main`.

Please try to use the `vllm-client` package as per my example, it seems to work.

**Comment by viktor-ferenczi** [comment]
@casper-hansen Maybe we should have that `vllm-client` package after all to streamline client development.

**Comment by lonngxiang** [comment]
> latest vLLM build from `main`

tks，update to latest vLLM 0.2.0 fixed

**Comment by wengyuan722** [comment]
@viktor-ferenczi how can i use python -m vllm.entrypoints.openai.api_server,could you give a sample codes about post "/v1/chat/completions"
