### ISSUE TITLE
Request for new pip package release version 0.1.8

### ISSUE THREAD

**Issue by Isydmr** [vllm-project/vllm#1194]
Is there a timeline for the release of version 0.1.8? 
The current version, 0.1.7, does not have support for quantization (AWQ)

**Comment by sprezz-arthur** [comment]
it will be 0.2.0, it should happen very soon, since: https://github.com/vllm-project/vllm/issues/1089

**Comment by viktor-ferenczi** [comment]
@Isydmr Please close this ticket, it has been answered. Thanks.

**Comment by WoosukKwon** [comment]
@Isydmr Sorry for the delay. We will release a new version in a day. Please stay tuned.
