### ISSUE TITLE
Keep getting CUDA out of memory but I have memory available!

### ISSUE THREAD

**Issue by naticio** [vllm-project/vllm#1201]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 47.54 GiB total capacity; 31.64 GiB already allocated; 1.03 GiB free; 31.66 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:4F:00.0 Off |                  Off |
| 30%   25C    P8    22W / 300W |  13936MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by djmaze** [comment]
Same here (4,5 GB model / 24 GB VRAM).

**Comment by parthiv-crest** [comment]
Any update on this? I am facing the same issue.

**Comment by gordicaleksa** [comment]
Same here, have 48GBs of VRAM and OPT-125M is failing, what's up here?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
