### ISSUE TITLE
MLC

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [vllm-project/vllm#1204]
Hello,

Thanks for the great framework for deploying LLM.

Would it be possible to use a LLM model compiled with the MLC-AI library?

**Comment by viktor-ferenczi** [comment]
How do you plan to use vLLM for that?

**Comment by Matthieu-Tinycoaching** [comment]
Wouldn't it be possible to use a MLC compiled model as a specific quantized model, like vLLM already does with AWQ models?

**Comment by hmellor** [comment]
@simon-mo @WoosukKwon is this a feature you'd want to see implemented?
