### ISSUE TITLE
vllm loading baichuan2-13b-chat quantized model error, using the official provided after the quantized 4bits also reported error

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#1207]
![image](https://github.com/vllm-project/vllm/assets/25812074/40760ed5-b829-46f4-977e-074972231c37)

**Comment by viktor-ferenczi** [comment]
Please provide the OS, CUDA version, CPU, CPU RAM, GPU(s), GPU VRAM sizes, command line you started the vLLM with, model used and the full vLLM log output for diagnosis.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
