### ISSUE TITLE
3 gpu's not supported?

### ISSUE THREAD

**Issue by ye7love7** [vllm-project/vllm#1208]
I'm using 3 gpu's and launching vllm using fastchat and reporting an error, cutoff error.

**Comment by viktor-ferenczi** [comment]
Please provide the OS, CUDA version, CPU, CPU RAM, GPU(s), GPU VRAM sizes, command line you started the vLLM with, model used and the full vLLM log output for diagnosis.

**Comment by irasin** [comment]
Generally speaking, using tensor parallel requires an even number of gpu, because hidden_size/head_num, etc. are usually even numbers, like 4096/32，5120/40

**Comment by viktor-ferenczi** [comment]
It could be solved by splitting the tensors in a non-uniform way between the GPUs. 
For example: `4096 = 1280 + 1280 + 1536`

It would complicate the code, but would allow for GPU numbers which are not power of two.

Until they your workaround is to use only two GPUs: `--tensor-parallel=2`

Question is how much demand is there for this feature.

@WoosukKwon Feature request: Support odd number of GPUs (non-uniform split)

**Comment by irasin** [comment]
If all GPU device are the same, such as 4 Nvidia A10 gpu cards, non-uniform splitting of tensor parallelism is inefficient because it means workload imbalance, so when doing all reduce, the device with lower workload will be in invalid waiting time.

BTW, if you guys want to support odd number of GPUs, I think the best practice should be pipeline parallel.

**Comment by viktor-ferenczi** [comment]
Inefficiency would depend on what's the common denominator we need to hold between tensor sizes. In my example I used 256, which is quite large. Maybe it can be 32 or even 16, depending on hardware. So in practice the imbalance would not be that bad.

Pipeline parallel would work, but result in higher latency. I guess that's acceptable, since the goal here is high throughput (therefore optimal utilization).

**Comment by ye7love7** [comment]
How should I set up the command line so that 3 Gpus can work, please



---Original---
From: "Viktor ***@***.***&gt;
Date: Thu, Sep 28, 2023 22:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] 3 gpu's not supported? (Issue #1208)




 
Inefficiency would depend on what's the common denominator we need to hold between tensor sizes. In my example I used 256, which is quite large. Maybe it can be 32 or even 16, depending on hardware. So in practice the imbalance would not be that bad.
 
Pipeline parallel would work, but result in higher latency. I guess that's acceptable, since the goal here is high throughput (therefore optimal utilization).

**Comment by viktor-ferenczi** [comment]
Try `--pipeline-parallel-size=3`, but it will be efficient only if you run multiple generations at the same time.

**Comment by ye7love7** [comment]
Thank you. I just want to get it up and running. Efficiency is secondary.


---Original---
From: "Viktor ***@***.***&gt;
Date: Fri, Sep 29, 2023 16:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] 3 gpu's not supported? (Issue #1208)




 
Try --pipeline-parallel-size=3, but it will be efficient only if you run multiple generations at the same time.

**Comment by ye7love7** [comment]
[vllm/config.py]
def _verify_args(self) -> None:
256 | if self.pipeline_parallel_size > 1:
257 | raise NotImplementedError(
258 | "Pipeline parallelism is not supported yet.")

OMG!not support pipeline parallel









> Try `--pipeline-parallel-size=3`, but it will be efficient only if you run multiple generations at the same time.

**Comment by irasin** [comment]
yes, pipeline parallel is not supported yet. 
So I wonder when will it be supported? @viktor-ferenczi , Hope to use pipeline parallel as soon as possible.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by cduk** [comment]
A further question on this, is the recommendation an even number or does it need to be a power of 2? For example, would having 6 GPUs work well? I saw some reports that with 6 GPUs vLLM would use only 4 of them.

**Comment by puppetm4st3r** [comment]
any news with this? is there a plan to support --pipeline-parallel-size or odd gpu number (even when it could be less efective)

**Comment by TienDungHUST** [comment]
I faced with this issue too. How can I serve vLLM with odd GPU number while the  --pipeline-parallel-size  is not implemented yet and total number of attention heads ( like 40, 64,...) must be divisible by --tensor-parallel-size

**Comment by eigen2017** [comment]
same error
32 heads on 3 gpus
total number of attention heads must be divisible by tensor parallel size

**Comment by groxaxo** [comment]
any updates on this ? any workaround ??
