### ISSUE TITLE
Does this library support the official META based LLama2 model(s), or just the huggingface flavor? 

### ISSUE THREAD

**Issue by vgoklani** [vllm-project/vllm#1216]
Hey there,

Thanks for releasing this! Does this library support the official implementations directly from META, or is the just the huggingface variety? Thanks!

**Comment by viktor-ferenczi** [comment]
Hi, As far as I'm aware only the HF model is supported.

[List of supported models](https://vllm.readthedocs.io/en/latest/models/supported_models.html)

Why do you need support for Meta's model format?

**Comment by vgoklani** [comment]
We don't want the transformers library to be a dependency for prod; the META implementation is both minimal and clean, and much easier to work with. A lots of other companies feel the same way :)

**Comment by vgoklani** [comment]
Is there an implementation that connects to nanoGPT? Just something minimal that we can work from? thanks!
