### ISSUE TITLE
Support for Contrastive Search

### ISSUE THREAD

**Issue by abdulvirta** [vllm-project/vllm#1219]
Does vllm supports contrastive search? If not, would be great to add that support as soon as possible? [Research](https://arxiv.org/pdf/2210.14140.pdf) shows that this improves model quality significantly and it is currently supported in transformers HF library. Would be great to get parity for this in vllm.

**Comment by viktor-ferenczi** [comment]
Related to #535

**Comment by abdulvirta** [comment]
so would the implementation of that ticket enable the end user to be able to implement contrastive search on their side? or do you mean that the contrastive search support work needs that work to happen first?

**Comment by Peter-Devine** [comment]
I may be mistaken, but implementing contrastive search would require more than just enabling logit processing.

Contrastive search, from my understanding, requires access to the last hidden state of each previous token. From the [paper linked above](https://arxiv.org/pdf/2210.14140.pdf), we can see
![image](https://github.com/vllm-project/vllm/assets/49399312/7564bdc5-740b-495d-879a-0d1804d07dfb)
where h is the last hidden state.

Looking at Huggingface's implementation of [Contrastive Search](https://github.com/huggingface/transformers/blob/75a33d60f25d99ff8cdd657d6ba685dc4336a0d1/src/transformers/generation/utils.py#L1843), particularly the [_ranking_fast function](https://github.com/huggingface/transformers/blob/75a33d60f25d99ff8cdd657d6ba685dc4336a0d1/src/transformers/generation/utils.py#L4741), we can see that you need the hidden states to calculate the output.
Is access to the last hidden states of each previous token even possible using paged attention? If not, I would guess that even having access to sum of the hidden states would still result in generation similar to contrastive search (this is just a hypothesis though).

Anyway, thanks for the great package :)

**Comment by YecanLee** [comment]
Any update on adding this feature?👀
