### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dannyxiaocn** [vllm-project/vllm#1225]
When I install vLLM, I have pull the docker as the tutorial and install from source. But there are an error encountered, how can I fix this:
`ValueError: Unsupported CUDA arch (5.2). Valid CUDA arch strings are: ['7.0', '7.5', '8.0', '8.6', '8.9', '9.0', '7.0+PTX', '7.5+PTX', '8.0+PTX', '8.6+PTX', '8.9+PTX', '9.0+PTX'].`

**Comment by MarcCote** [comment]
I managed to get it working by setting `ENV TORCH_CUDA_ARCH_LIST="8.0;8.6;8.9"` (depends on your GPU) but I think an `ENV TORCH_CUDA_ARCH_LIST=""` could also work.

I believe the check [here](https://github.com/vllm-project/vllm/blob/v0.2.0/setup.py#L59-L63) should be a
> if none of the architectures in `arch_list` are in `valid_arch_strs`, then raise an error

instead of

>if **one** of the architectures in `arch_list` is not in `valid_arch_strs`, then raise an error
