### ISSUE TITLE
Chinese and emojis not supported via OpenAI API

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#1231]
Top-left is vLLM.  I don't see any way with OpenAI API version of vLLM to get actual tokens.  TGI (top-middle) handles this already on its own end.    OpenAI itself has no issues for same exact code.

![image](https://github.com/vllm-project/vllm/assets/2249614/404be205-f5ac-4e1a-b9f2-2d042397b7e6)

In h2oGPT for native torch we do this: https://github.com/h2oai/h2ogpt/blob/549340ce78f1ecfeaec16b9f1e3b1428bec3776b/src/gen.py#L3079-L3097

vLLM could do similar.

**Comment by esmeetu** [comment]
Hi, @pseudotensor Could you test openai api directly without `gen.py`. It natively support Chinese and emojis. 
Go to #984 to refer to more comments and hope that can solve this.

**Comment by pseudotensor** [comment]
Ok thanks.
