### ISSUE TITLE
Disable detailed request logging by default

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#1240]
vLLM 0.2.0 logs all requests in detail by default, which produces excessive log output.

While it is useful for bug investigation (if a full log is provided) this is a pain for regular use.

Currently the way to turn this off is to pass the `--disable-log-requests` command line argument.

I would suggest the following:
- Disable logging of detailed request information by default
- Deprecate the `--disable-log-requests` flag and change it to do nothing
- Introduce a `--log-requests` flag to enable this feature on demand

**Comment by hmellor** [comment]
@WoosukKwon @simon-mo @zhuohan123 what do you think of this suggestion?

**Comment by ParisNeo** [comment]
I think this is a great suggestion. Also it would be a good idea to control what gets logged. For example I don't want to log the tokens nor the load. I just want to log the prompt with the ip address of the source for control purposes.

**Comment by shyringo** [comment]
Met the same issue. But I somehow think it is a better idea to keep logging as the default choice. In remedy, just hope that documents could be more organized, accurate and of guidance, to help solve this issue easy and quick.

**Comment by hmellor** [comment]
@shyringo PRs that improve the documentation are always welcome.

I'm going to close this as not planned because in general it is better for vLLM to be loud while you're figuring out how it works, and then you can tell it to be quiet with `--disable-log-requests` when you're ready to use it in anger.
