### ISSUE TITLE
Huge latency increase with AWQ models at medium context lengths

### ISSUE THREAD

**Issue by CooperBrownUMD** [vllm-project/vllm#1242]
Using an awq quantized model from thebloke (TheBloke/manticore-13b-chat-pyg-AWQ), generation is fine and starts after a few seconds with only a few sentences in the context window, but anything more than three or four makes it take ~30 seconds to start generation. Tried different awq models, and the issue doesn't happen with unquantized models. Is this normal/something to do with the way it handles awq models?

**Comment by casper-hansen** [comment]
This is not normal behavior. You can go to AutoAWQ and try to generate using Huggingface methods to see how it normally works.
