### ISSUE TITLE
livez and readyz are missing from the api_server

### ISSUE THREAD

**Issue by petrosbaltzis** [vllm-project/vllm#1245]
Hello,

I am trying to deploy an LLM model using vLLM on Kubernetes. However, for K8, the `readinessProbe` and `livenessProbe` are needed to indicate [the health of the api-server](https://kubernetes.io/docs/reference/using-api/health-checks/)  and these endpoints are missing from the [api_server.py](https://github.com/vllm-project/vllm/blob/ebe4d1db3a42096cebcc2b2d289143bc0ef02d3d/vllm/entrypoints/api_server.py)

For that reason I have raised a simple PR to include the needed endpoints: https://github.com/vllm-project/vllm/pull/1244

Regards,
Petros Baltzis

**Comment by jc-louis** [comment]
one health endpoint was added https://github.com/vllm-project/vllm/pull/1540

**Comment by petrosbaltzis** [comment]
Thanks for that! We already started using it!
