### ISSUE TITLE
Jetson agx orin 

### ISSUE THREAD

**Issue by MrBrabus75** [vllm-project/vllm#1248]
Hello,

Its possible to install on Jetson agx orin nvidia device ? its a TPU Ubuntu 20.04 in ARM64 (aarch64), with a specific version of pytorch " https://developer.download.nvidia.cn/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl "

if yes, can you explain what i need to change ? 

Thanks you in advance

**Comment by MrBrabus75** [comment]
I apologize if I wasn't clear earlier. To summarize:

    I'm trying to install vllm-project on an NVIDIA Jetson AGX Orin.
    This device operates on Ubuntu 20.04 (tegra 5.10.120), which is an ARM64 version.
    The Jetson runs on Python 3.8, and I cannot upgrade to a newer version like Python 3.10 due to specific dependencies on this platform.
    It uses a specific version of PyTorch that requires Python 3.8 and is optimized for CUDA on this platform. You can find this version of PyTorch here: [PyTorch link](https://developer.download.nvidia.cn/compute/redist/jp/v511/pytorch/torch-2.0.0+nv23.05-cp38-cp38-linux_aarch64.whl).
    I aim to get guidance on making vllm-project work with this particular PyTorch version and the Jetson.

Is it possible to add support for this configuration? If not, could you guide me through the necessary steps to extend the support on my own, such as creating a PR?

Thank you for your understanding.

**Comment by AlpinDale** [comment]
You can use [conda](https://docs.conda.io/projects/miniconda/en/latest/) to install the latest python + CUDA versions. Set up a conda environment with `conda create -n vllm python=3.11`, activate it with `conda activate vllm` and install CUDA 11.8 with `conda install -c "nvidia/label/cuda-11.8.0" cuda`. After that, you can simply do a `pip install vllm` to get started.

If you don't like conda, you can try a python version management software like [pyenv](https://github.com/pyenv/pyenv) or [asdf](https://asdf-vm.com). Regardless, it's never recommended to pollute your system-wide packages with pip installs; always operate within a virtual environment.

**Comment by vvsotnikov** [comment]
>After that, you can simply do a pip install vllm to get started

It's not that simple - you will also need a CUDA-enabled PyTorch built for aarch64, which is not available via pip or conda.

**Comment by AdiKhedkar38** [comment]
Is it possible to install vllm on TPUv5. I want to deploy inference of llm model using vllm on TPU. 
TPU-vm configuration:
`Operating System: Ubuntu 22.04.2 LTS              
          Kernel: Linux 5.19.0-1030-gcp
    Architecture: x86-64`

**Comment by WangFengtu1996** [comment]
anythings update?

**Comment by Acc1143** [comment]
怎么解决呢？
