### ISSUE TITLE
StreamingLLM support?

### ISSUE THREAD

**Issue by nivibilla** [vllm-project/vllm#1253]
Hey,

This was a really interesting solution to the KV cache for long context. 
https://github.com/mit-han-lab/streaming-llm

I was wondering it could be implemented here. From the looks of things it doesn't change anything about the model itself, its more about how the KV cache is implemented.

They show that they can have coherent inference over millions of tokens

Thanks!

**Comment by Guangxuan-Xiao** [comment]
Hello vLLM Team,

I'd like to start by expressing my appreciation for your dedication in developing the vLLM framework. Tracking the project's evolution has been nothing short of exhilarating. I believe that integrating [StreamingLLM](https://github.com/mit-han-lab/streaming-llm) would be an enhancement that would be of great value to many users.

To streamline this possible integration, I've curated a suggested approach based on the StreamingLLM's structure:

1. **Sliding Window KV Cache:** Integrate the sliding window KV cache tailored for extensive generation tasks. 
   - [Reference - KV Cache](https://github.com/mit-han-lab/streaming-llm/blob/main/streaming_llm/kv_cache.py)
   - [Reference - Example Implementation](https://github.com/mit-han-lab/streaming-llm/blob/main/examples/run_streaming_llama.py#L71)

2. **Initial Token Persistence:** Ensure that starting tokens' KV (like the first page of tokens) are consistently maintained within the current context window.

3. **Rotary Embedding Caching:** It's crucial to cache the key states before applying the rotary embedding.
   - [Reference - Caching](https://github.com/mit-han-lab/streaming-llm/blob/main/streaming_llm/pos_shift/modify_llama.py#L96)
   
   Subsequently, the rotary positional embedding should be reapplied within this cache during the generation stage.
   - [Reference - Reapplication](https://github.com/mit-han-lab/streaming-llm/blob/main/streaming_llm/pos_shift/modify_llama.py#L102)

Adhering to this approach, I'm confident that StreamingLLM can be integrated into the vLLM framework. The entire community, myself included, is enthusiastic about the potential of this feature!

Best,
Guangxuan

**Comment by MichaelZhouwang** [comment]
Is there any update on this feature update?

**Comment by Kaiyang-Chen** [comment]
Hi @Guangxuan-Xiao, I believe this feature is quite meaningful and I'm interested in helping to implement it. However, after some initial research, I feel that there isn't a straightforward and efficient method. This is because the values in the kvcache already include the `pos_embedding` calculated with the absolute position, combined with the query's embedding to perform the linear computation to obtain the kv cache. However, in the streamingllm, the relative positions of the tokens need to change.

The most naive solution would be only store kv value from `QKVLinear` before applying any position info, and then add position info to the whole `context_window` before the attention computation. This approach would require new CUDA kernels to handle such inputs and introduce recomputation for the current key cache, and also need extra memory for the intermediate `key_state`. I think the throughput would decrease significantly. Also, such a change is completely different from the original memory management logic and would be a significant modification. I'm not sure if the team would accept making the codebase especially complex for this feature. 

Hi Team @WoosukKwon @zhuohan123, do you guys have any thoughts/hints about how to gracefully integrate this feature?

**Comment by halixness** [comment]
+1

**Comment by soacker** [comment]
> Hi @Guangxuan-Xiao, I believe this feature is quite meaningful and I'm interested in helping to implement it. However, after some initial research, I feel that there isn't a straightforward and efficient method. This is because the values in the kvcache already include the `pos_embedding` calculated with the absolute position, combined with the query's embedding to perform the linear computation to obtain the kv cache. However, in the streamingllm, the relative positions of the tokens need to change.
> 
> The most naive solution would be only store kv value from `QKVLinear` before applying any position info, and then add position info to the whole `context_window` before the attention computation. This approach would require new CUDA kernels to handle such inputs and introduce recomputation for the current key cache, and also need extra memory for the intermediate `key_state`. And also, if we try to leverage paged kv cache, when token eviction or replacement happens, we need extra data copying or extra space to store the index in order to keep the token in fixed blocks and maintain their relative sequence. I think the throughput would decrease significantly. Also, such a change is completely different from the original memory management logic and would be a significant modification. I'm not sure if the team would accept making the codebase especially complex for this feature.
> 
> Hi Team @WoosukKwon @zhuohan123, do you guys have any thoughts/hints about how to gracefully integrate this feature?

Hi [Kaiyang-Chen](https://github.com/Kaiyang-Chen), I noticed your naive solution. To avoid conflicts with the original page block, would it be possible to handle the pos_embed via post-processing? For example, if the saved k_m (kv cached) is located at position m, we could apply ROPE again, rotating position m in k_m to 0. Then, based on the new position  defined in the StreamingLLM, we could use ROPE to assign the pos_embed to the key accordingly. I have also proposed a method called "mesa-extrapolation" (https://github.com/soacker/Mesa-Extrapolation) for handling extrapolation of longer inputs. If we could integrate these methods for handling longer texts with minimal changes to the original page memory management logic, that would be excellent.

**Comment by soacker** [comment]
We might not need to provide a new CUDA kernel.

## Post-processing:

Assume that we get the key cached located on m, like below:

<img width="542" alt="image" src="https://github.com/user-attachments/assets/86e7cb64-2498-44ec-b3b0-1b01ecd9798f">

We only need to rotate it with -m, like below:

<img width="867" alt="image" src="https://github.com/user-attachments/assets/1315c3d3-04c7-4dd2-9da7-95d402f87641">

Then, we can get the key without pos_embed.

Next, we only need to apply new position to it.

**Comment by maobaolong** [comment]
Glad to find this issue. As years past, is it possible to introduce the streaming llm for the current vllm or integrate to lmcache?
@KuntaiDu @ApostaC ?

**Comment by ApostaC** [comment]
Yeah, we have tried to introduce those KV cache eviction / KV cache sink technique into LMCache before. @YaoJiayi did something early this year. Would love to revisit it sometime soon!

**Comment by astro-utora** [comment]
Hi

**Comment by Andrew-Zhang** [comment]
> We might not need to provide a new CUDA kernel.
> 
> ## Post-processing:
> Assume that we get the key cached located on m, like below:
> 
> <img alt="image" width="542" src="https://private-user-images.githubusercontent.com/34324856/391316154-86e7cb64-2498-44ec-b3b0-1b01ecd9798f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ0NjIzNzAsIm5iZiI6MTc1NDQ2MjA3MCwicGF0aCI6Ii8zNDMyNDg1Ni8zOTEzMTYxNTQtODZlN2NiNjQtMjQ5OC00NGVjLWIzYjAtMWIwMWVjZDk3OThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA2VDA2MzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YWM4MjZkMTRjZjRmNmI0Njk2MjVhMjQwOGFjNjFjOWQ3NTVkZDc1ZjU1OWU5NDE3ZjY4ZGFjZGZjMjRiYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WwEt8yAA988QFjvtsLK4lnJOEmMQbP8YMf4W-qsQiIE">
> We only need to rotate it with -m, like below:
> 
> <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/34324856/391316361-1315c3d3-04c7-4dd2-9da7-95d402f87641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ0NjIzNzAsIm5iZiI6MTc1NDQ2MjA3MCwicGF0aCI6Ii8zNDMyNDg1Ni8zOTEzMTYzNjEtMTMxNWMzZDMtMDRjNy00ZGQyLTlkYTctOTVkNDAyZjg3NjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA2VDA2MzQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTNhNjZlNDAyMDZiZGViZjc0ODlhNDhlZDU1ODdmMzVjMDY1MWJmMWUwMTgyZThhMjAxNmJlYmJlYTJjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E4W8b4cTz3tcKBYNWMiseUNhsJ6noLhEJL7LXYAbGiU">
> Then, we can get the key without pos_embed.
> 
> Next, we only need to apply new position to it.


@soacker Did you encounter any issues when implementing this postprocessing methodology? I had the same idea.
