### ISSUE TITLE
Installing for Intel ARC

### ISSUE THREAD

**Issue by ElliottDyson** [vllm-project/vllm#1256]
Hello,

Is there any chance for Intel ARC support being added to the roadmap? Thank you

**Comment by WoosukKwon** [comment]
Hi @ElliottDyson, unfortunately it's not on our roadmap at the moment because there are only few users. Instead, maybe we will consider adding support for Intel CPUs and Gaudi 2 in the future.

**Comment by ElliottDyson** [comment]
> Hi @ElliottDyson, unfortunately it's not on our roadmap at the moment because there are only few users. Instead, maybe we will consider adding support for Intel CPUs and Gaudi 2 in the future.

Well if you do end up supporting intel CPUs it should also then inherently support intel ARC GPUs because they both rely on the same implementation, oneAPI. So that would be great. As for the small userbase, I totally understand where you are coming from

**Comment by itlackey** [comment]
+1 for Intel GPU support

**Comment by zhouyuan** [comment]
@ElliottDyson @itlackey 
Hi, just in case you are still looking for, here's the initial patch to support for Intel GPU(ARC & PVC)
https://github.com/vllm-project/vllm/pull/2378

thanks, -yuan
