### ISSUE TITLE
Option to not apply the frequency penalty to some tokens or strings.

### ISSUE THREAD

**Issue by abhigoyal2210** [vllm-project/vllm#1257]
I couldn't find any option to not apply the frequency penalty to some tokens or strings. One instance where this can be useful is when you want to use a frequency penalty to avoid repetitive output but this causes some output formats to break, e.g. when you need a list of dictionaries (a JSON output) where the keys of the dictionaries are the same. In such a scenario, a higher frequency penalty causes the format to break but a low penalty is not desirable as it causes repetitive language in the output. Can we add this feature? I'll be happy to work on it.

**Comment by abhigoyal2210** [comment]
This is a global frequency penalty that is applied to every repeated token, right? Consider a scenario where we want a JSON output (or an XML type):

```
[
    { 'key1': {{value}}, 'key2': {{value}} },
    { 'key1': {{value}}, 'key2': {{value}} }
]
```

Here the model has to repeat `key1` and `key2` to generate a valid output. So it makes sense not to penalize the model for doing so. The frequency penalty which we can currently will penalize the model if it repeats these keys as well. This causes the generated output to have an invalid format (and sometimes it changes the names of the keys which is not intended). However, allowing the model to generate such keys without any repetition penalty will solve this problem.

There can be other use cases as well where you may want to allow repetition of certain words or tokens but not all. This kind of JSON style output format is just one example which comes to my mind.

**Comment by hmellor** [comment]
Closing because JSON schemas can now be specified using guided generation. So using the frequency penalty wouldn't harm the JSON syntax.
