### ISSUE TITLE
Some models with `awq` quantization cannot using 4 tensor parallism

### ISSUE THREAD

**Issue by esmeetu** [vllm-project/vllm#1258]
When i use this https://huggingface.co/TheBloke/WizardCoder-Python-7B-V1.0-AWQ model with TP4, it will raise `Group size should be a multiple of 32` in `gemm_kernels.cu` file. https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/csrc/quantization/awq/gemm_kernels.cu#L465
 
And i digged it into more, I find that `intermediate_size` of `WizardCoder-Python-7B-V1.0-AWQ` is 11008. So when using TP4, `reshaped_x`'s shape in `apply_weights` of `AWQRowParallelLinear` class will be `11008/4=2752`. https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/vllm/model_executor/layers/quantized_linear/awq.py#L100

Then in line `int group_size = num_in_channels / _scaling_factors.size(0);` will equal to `int group_size = 2752 / 8`, so the group_size will be `344`. And we know `344 % 32 = 24` that doesn'e equal to 0.
https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/csrc/quantization/awq/gemm_kernels.cu#L458

I have no idea to solve this.

**Comment by casper-hansen** [comment]
The CUDA kernel needs to be generalized a bit more before this use-case is enables. I am hoping a community member that has experience can improve and make it more widely usable.

**Comment by esmeetu** [comment]
I think the same as you, looking forward to that day to come soon, but for now, I’m already satisfied enough with current awq implementation.
