### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SatoshiReport** [vllm-project/vllm#1262]
This is my setup:

Ubuntu 20.04.6 LTS
Build cuda_11.8.r11.8/compiler.31833905_0
A10 NVIDIA
python -m vllm.entrypoints.openai.api_server --model TheBloke/Wizard-Vicuna-13B-Uncensored-AWQ --quantization awq --host 0.0.0.0 --gpu-memory-utilization 0.50

Memory utilization starts at 50% but within a day it goes to 75%.  Let me know if you need any other data from me.  Thanks.

**Comment by junior-zsy** [comment]
Both gptq and awq will encounter the same problem

**Comment by chqiwang** [comment]
I also encountered it when use the mistral 8x7b model

**Comment by gautam-fairpe** [comment]
I am facing the same issue using with awq quantized model. How to fix the memory leak ?

**Comment by hmellor** [comment]
Closing as vLLM has changed a lot since this was opened. If anyone is still experiencing this problem, please open a new issue using the new templates and provide all the information that a community member will need to assist you.

**Comment by xueyedamo521** [comment]
> I also encountered it,Both gptq and awq will encounter the same problem

Have you solved this problem? I also encountered it，too.  When using AWQ model，A10 gpu memory utilization starts at 50% but within a day it goes to 99% and crash finally.

**Comment by xueyedamo521** [comment]
> Closing as vLLM has changed a lot since this was opened. If anyone is still experiencing this problem, please open a new issue using the new templates and provide all the information that a community member will need to assist you.

Have you solved this problem? I also encountered it，too.  When using AWQ model，A10 gpu memory utilization starts at 50% but within a day it goes to 99% and crash finally.

**Comment by RobertLiu0905** [comment]
Have you solved this problem? I also encountered it，too. When using gptq model
