### ISSUE TITLE
multiple prompts in a batch is not currently supported

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#1270]
Is this planned?  Seems like good idea to support full OpenAI behavior and any batching is already handled well by vLLM, so should be relatively easy I would guess?

https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/vllm/entrypoints/openai/api_server.py#L396-L401

**Comment by simon-mo** [comment]
This has been addressed.
