### ISSUE TITLE
Can't load fine-tuned LLama2 model stored in local

### ISSUE THREAD

**Issue by fr-ashikaumagiliya** [vllm-project/vllm#1271]
I have a fine-tuned LLama2 model (LoRA Layers merged). Model folder contains following files:

- config.json
- generation_config.json
- model-00001-of-00002.safetensors 
- model-00002-of-00002.safetensors
- model.safetensors.index.json 
- special_tokens_map.json
- tokenizer_config.json 
- tokenizer.json

When I try to load the model it throws following error. Any idea on how to resolve this?

`llm = LLM(model="./llama-ft/merged_model")`

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> Cell In[16], line 11
>       3 prompts = [
>       4     "Hello, my name is",
>       5     "The president of the United States is",
>       6     "The capital of France is",
>       7     "The future of AI is",
>       8 ]
>       9 sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
> ---> 11 llm = LLM(model="./llama-ft/merged_model")
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py:89, in LLM.__init__(self, model, tokenizer, tokenizer_mode, trust_remote_code, tensor_parallel_size, dtype, quantization, revision, seed, gpu_memory_utilization, swap_space, **kwargs)
>      74     kwargs["disable_log_stats"] = True
>      75 engine_args = EngineArgs(
>      76     model=model,
>      77     tokenizer=tokenizer,
>    (...)
>      87     **kwargs,
>      88 )
> ---> 89 self.llm_engine = LLMEngine.from_engine_args(engine_args)
>      90 self.request_counter = Counter()
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:229, in LLMEngine.from_engine_args(cls, engine_args)
>     226 distributed_init_method, placement_group = initialize_cluster(
>     227     parallel_config)
>     228 # Create the LLM engine.
> --> 229 engine = cls(*engine_configs,
>     230              distributed_init_method,
>     231              placement_group,
>     232              log_stats=not engine_args.disable_log_stats)
>     233 return engine
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:108, in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, distributed_init_method, placement_group, log_stats)
>     106     self._init_workers_ray(placement_group)
>     107 else:
> --> 108     self._init_workers(distributed_init_method)
>     110 # Profile the memory usage and initialize the cache.
>     111 self._init_cache()
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:140, in LLMEngine._init_workers(self, distributed_init_method)
>     132 worker = Worker(
>     133     self.model_config,
>     134     self.parallel_config,
>    (...)
>     137     distributed_init_method,
>     138 )
>     139 self.workers.append(worker)
> --> 140 self._run_workers(
>     141     "init_model",
>     142     get_all_outputs=True,
>     143 )
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py:692, in LLMEngine._run_workers(self, method, get_all_outputs, *args, **kwargs)
>     689     else:
>     690         executor = getattr(worker, method)
> --> 692     output = executor(*args, **kwargs)
>     693     all_outputs.append(output)
>     695 if self.parallel_config.worker_use_ray:
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py:63, in Worker.init_model(self)
>      60 torch.cuda.set_device(self.device)
>      62 # Initialize the distributed environment.
> ---> 63 _init_distributed_environment(self.parallel_config, self.rank,
>      64                               self.distributed_init_method)
>      66 # Initialize the model.
>      67 set_random_seed(self.model_config.seed)
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py:358, in _init_distributed_environment(parallel_config, rank, distributed_init_method)
>     356 # A small all_reduce for warmup.
>     357 torch.distributed.all_reduce(torch.zeros(1).cuda())
> --> 358 initialize_model_parallel(parallel_config.tensor_parallel_size,
>     359                           parallel_config.pipeline_parallel_size)
> 
> File /opt/conda/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/parallel_state.py:116, in initialize_model_parallel(tensor_model_parallel_size, pipeline_model_parallel_size, virtual_pipeline_model_parallel_size, pipeline_model_parallel_split_rank)
>     114 global _DATA_PARALLEL_GROUP
>     115 global _DATA_PARALLEL_GLOBAL_RANKS
> --> 116 assert _DATA_PARALLEL_GROUP is None, 'data parallel group is already initialized'
>     117 all_data_parallel_group_ranks = []
>     118 for i in range(pipeline_model_parallel_size):
> 
> AssertionError: data parallel group is already initialized
> 
> 
>

**Comment by WangShaner** [comment]
The model should be provided in pickle files, e.g., pytorch_model-00001-of-00002.bin.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
