### ISSUE TITLE
Slow model loading

### ISSUE THREAD

**Issue by mckbrchill** [vllm-project/vllm#1276]
Hi!

My setup is:

- NVIDIA A100 (CUDA 12.2)
- AMD EPYC 7702
- Ubuntu 20.04

I'm running an API server like this:
`python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8000 --model TheBloke/WizardCoder-Python-34B-V1.0-AWQ --quantization awq --trust-remote-code --max-num-batched-tokens 4096 --max-model-len 4096`

What's an adequate time for executing API server with AWQ model that size? I have to wait around 50 minutes and I can't estimate if it's okay or not. Also if I interrupt the server after it has already loaded and then run it again, the execution takes around 5 min.

I had Tesla V100 previously, and I tried it with non quantized models, and it seemed much faster. So I'm trying to figure it out if there's somthing wrong with my new setup, or AWQ format loading is slow.

I also did some quick test: running simple "torch.cuda.is_available()" takes around 3 minutes to execute on the first run, and done almost immediately after

**Comment by mckbrchill** [comment]
Did some additional tests, seems that running models through vllm somehow messes up my GPU.
The test was:
1. New cloud with V100 -> start oobabooga/text-generation-webui, load GPTQ 15B model -> it takes 9 sec to load.
2. Create new env installing via pip vllm==0.2.0 -> run `python -m vllm.entrypoints.openai.api_server` -> it takes around 10 sec to load
3. Reboot my clound VM -> run `python -m vllm.entrypoints.openai.api_server` -> it takes around 9 minutes to load
4. start oobabooga/text-generation-webui, load GPTQ 15B model -> it takes around 19 minutes to load
Did `sudo nvidia-smi --gpu-reset -i 0, no difference`

**Comment by xujinlai** [comment]
Is there any conclusion on this model loading slow down?

**Comment by mckbrchill** [comment]
> Is there any conclusion on this model loading slow down? 
> 
> I just met a similar condition that when vllm loading model checkpoint from some hdfs-like distributed object store

3-min lag was due to some wrong gpu setup on the cloud provider side.
But the main slowdown was caused by the fact that virtual machine had HDD. I switched to SSD and the problem was solved
