### ISSUE TITLE
Question about the design of attention

### ISSUE THREAD

**Issue by dannyxiaocn** [vllm-project/vllm#1277]
In the model_executor/layers/attention.py, line 207-209, how does vLLM can ensure that when `num_prompt_tokens > 0`, `num_generation_tokens == 0`? Does this mean the prompt will always be prioritised than generation? 
I have check the `_prepare_inputs()` in worker.py. However, I have not found any clue why this can happen. 
I am really looking forward to any help.

**Comment by masahi** [comment]
Since https://github.com/vllm-project/vllm/pull/658, vllm never mixes prompt and generation tokens in a batch.

**Comment by dannyxiaocn** [comment]
I see, the scheduler part prioritize the incoming prompt phase requests before running generation requests.
