### ISSUE TITLE
Feature request. Allow a few model instances in one GPU if they can feet in VRAM.

### ISSUE THREAD

**Issue by agrogov** [vllm-project/vllm#1287]
The idea in having more instances of the model in VRAM of single GPU, for example two 7B models can fit 24Gb easily, so on 2 24Gb GPUs we can have 4 instances for concurrent requests and wuth Ray help it should be possible if vLLM will support such kind of spreading.
Now when trying to run 4 instances on 2 GPUs I got:
```
2023-10-07 16:28:06,308	INFO worker.py:1642 -- Started a local Ray instance.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 616, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 483, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
                                               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vllm/engine/ray_utils.py", line 107, in initialize_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```

**Comment by leocnj** [comment]
Regarding "two 7B models can fit 24Gb easily,", I am not sure this will work. If we use float16 or bfloat16 precision, each 7B model will take 7x2 = 14 Gb. Then, two 7B model will use 14x2=28Gb. Will you please help on my reasoning?

**Comment by agrogov** [comment]
Your conclusions are absolutely correct. The 7B model occupies approximately 15.4GB of VRAM. However, I am referring to Ray instances, which means the model is divided between two GPUs (+ key:value cache), totaling around 9.2GB per GPU if we limit vLLM to 45% (--gpu-memory-utilization 0.45). 
My idea is to allow the creation of more Ray instances to distribute computations among them.

**Comment by hmellor** [comment]
@WoosukKwon @simon-mo @zhuohan123 is this a feature you'd like to see implemented?
