### ISSUE TITLE
ImportError: /opt/vllm/vllm/attention_ops.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl27throw_data_ptr_access_errorEv

### ISSUE THREAD

**Issue by jianhuaz** [vllm-project/vllm#1291]
Excuse me, why is this mistake?

![image](https://github.com/vllm-project/vllm/assets/22927505/d676ff76-2745-4a74-8cbd-b3ac248e9a38)

**Comment by LRY89757** [comment]
+1

**Comment by LRY89757** [comment]
https://github.com/vllm-project/vllm/pull/1290/files
https://github.com/vllm-project/vllm/issues/1283
Maybe this can be help to you, but I still want one official solution to this issue from the developer of vllm

**Comment by jianhuaz** [comment]
Thanks! @LRY89757

**Comment by zhiqiangzhongddu** [comment]
I have the same error now. So, what's the final solution? @jianhuaz

**Comment by ysl940114** [comment]
+1

**Comment by rinapch** [comment]
+ 1

**Comment by zhiqiangzhongddu** [comment]
I avoided this issue by installing using `pip install vllm` instead of `pip install -e .  # This may take 5-10 minutes.`. Probably it works for you too. @rinapch @ysl940114

**Comment by ahkarami** [comment]
I have the same issue. I have installed by following the below link (for CUDA 11.8):
https://docs.vllm.ai/en/latest/getting_started/installation.html#install-with-pip
