### ISSUE TITLE
Low VRAM batch processing mode

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#1297]
This is a research topic and idea to make low VRAM GPUs usable for running large models in batch processing setups, where latency don't matter that much.

For example running a 70B model on a 3080Ti with only 12GB of VRAM (ctransformers, 8-bit GGUF) is possible if only 12 layers are loaded on the GPU and the rest are running on the CPU. Doing so leaves the GPU largely underutilized, as the nvtop output clearly shows:

![image](https://github.com/vllm-project/vllm/assets/1848514/51e172bb-ae8f-4de3-8a6b-c4ee17bffa8c)

We could run the whole model on the GPU by loading only 10 layers at a time (to free up space for the KV cache and other overhead) and running a wide batch of sequences (like 4096) through the layers loaded. Repeat until all layers are processed. We could also think about this mode as time multiplexing the same GPU over multiple pipeline steps.

It would need loading all the weights into VRAM once for every batch of prompt tokens processed or every new token generated, but this cost would be amortized over all the sequences processed at the same time. Loading of the weights would ideally happen from CPU RAM, but may also happen from disk swap on fast NVMe should the CPU RAM would not be enough to store all the model weights.

Open questions:
- Would the above work at all with minimal code changes, considering vLLM's current architecture?
- What is the optimum batch size considering the VRAM requirements of running state and amortized weight loading times?
- What would be the realistic use cases for this mode? Obviously this mode is for the "GPU poor", not for mass cloud hosting.

**Comment by hmellor** [comment]
@WoosukKwon @simon-mo @zhuohan123 is this a feature you'd like to see implemented?

**Comment by hmellor** [comment]
Stale
