### ISSUE TITLE
[Dependency Issue] How to run at H100 about CUDA 12, Torch 2.1.0

### ISSUE THREAD

**Issue by LRY89757** [vllm-project/vllm#1301]
The pytorch 2.1.0 has been released. We can get the latest version for cuda12 now, so I can build the vllm on hopper architecture, but there exists some issues about torch version.

If we only run `pip intall -e .` in the cmd with cuda12 env, we could build it successfully but can't run, because it will throw one error during runtime:
`.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl27throw_data_ptr_access_errorEv`
and about why, you can refer to this issue: https://github.com/Dao-AILab/flash-attention/issues/451 ,
> due to pytorch interface changing between the version used in 23.06 and 23.07

If we only run `pip intall -e .` in the cmd with cuda11.x , it can't be built successfully, because of the unmatch of pytorch 12.1 and cuda 11.8(and lower cuda toolkit version)

![image](https://github.com/vllm-project/vllm/assets/77330637/76d2c4a6-8b01-45a8-884d-05556008a181)

refer to:
https://github.com/vllm-project/vllm/issues/385
https://github.com/vllm-project/vllm/issues/1283
https://github.com/vllm-project/vllm/issues/1291

**Hope it will be useful for users  : ), I've been confused by this for a very long time : (**

**Comment by LRY89757** [comment]
May be the only way we can apply is to compile the pytorch from scratch : (
@zhuohan123 @WoosukKwon

**Comment by LRY89757** [comment]
According to this [issue](https://github.com/pytorch/pytorch/issues/90761), the cu11.8+torch2.1_nightly is capable to support hopper architecture, so we can run vllm with the command:
```bash
pip install --pre torch==2.1.0.dev20230902+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118
python setup.py develop -v
```

**Comment by tysg** [comment]
@LRY89757 did you find a reason or have a theory why it's not working well on H100?

**Comment by galatolofederico** [comment]
The package `torch==2.1.0.dev20230902+cu118` seems not to exist anymore on `https://download.pytorch.org/whl/nightly/cu118`.
I still can't run vllm on a H100 cluster, I've tried to compile from scratch both pytorch and vllm with no luck.
I also tried with the provided container
```
$ docker run --gpus=all -it docker.io/library/vllm:lastest
root@d0fe99ea3fe7:/workspace# python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vllm
>>> import torch
>>> torch.tensor([1,2,3]).cuda()
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:173: UserWarning: 
NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75 sm_80 sm_86.
If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
tensor([1, 2, 3], device='cuda:0')
>>> 
```


I am running CUDA 12.0 on the host with driver 525 and it is a DGX with 8xH100 (80GB)

**Comment by tcapelle** [comment]
Have anyone figured this out? I am also running on H100 and I am unable to use flash_atten, this is my docker image:
```
# https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags
# 12/01/2023 -> https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-11.html
FROM nvcr.io/nvidia/pytorch:23.11-py3

## Flash Atten 2
RUN python -m pip install "flash-attn==2.3.6" --no-build-isolation
```

**Comment by enochlev** [comment]
any luck?

**Comment by jjziets** [comment]
Seems that H100 wants 12.3 but pytouch is not there yet.
