### ISSUE TITLE
How do you stream tokens with the Python API?

### ISSUE THREAD

**Issue by simonw** [vllm-project/vllm#1302]
I'd like to be able to do the equivalent of this:

```python
for token in llm.prompt("ten names for a pet pelican:"):
    print(token, end="")
```

I've not been able to figure out how to get back a stream of tokens that I can iterate over as they are produced.

I think it's possible because the API server does it - could we get a code example showing how to do this directly using Python?

**Comment by davewsmith** [comment]
sys.stdout.flush() might be what you're looking for

**Comment by nateraw** [comment]
Hey @simonw did @davewsmith's suggestion work? last time I tried this it was returning the full sequence, not streaming tokens IIRC

**Comment by monuminu** [comment]
did you manage to do this ?

**Comment by nateraw** [comment]
My solution was written a while ago, but still works, it seems. :)

<p>Here's a Colab: <a target="_blank" href="https://colab.research.google.com/gist/nateraw/bc31a821a24d2034a96617811c2e996f/vllm-python-api-streaming.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a></p>

Or, if you prefer, a [gist](https://gist.github.com/nateraw/bc31a821a24d2034a96617811c2e996f) of that notebook.

Feel free to give it a try @monuminu
