### ISSUE TITLE
The output of the qwen model is not as expected

### ISSUE THREAD

**Issue by aihaidong** [vllm-project/vllm#1305]

**Comment by aihaidong** [comment]
![e84ee2b9a31f77e915ef7afa9fc4a2c](https://github.com/vllm-project/vllm/assets/54533917/3a61f13a-aa3e-4f9c-a77b-2482d5ec3383)
The answer you were hoping for was not what you expected.

**Comment by Sanster** [comment]
For the qwen chat model, you need to use the input in `chatml` format, for example:
```bash
'<|im_start|>user\n你是谁?<|im_end|>\n<|im_start|>assistant\
```

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
