### ISSUE TITLE
to add qwen-int4 support

### ISSUE THREAD

**Issue by Cloopen-ReLiNK** [vllm-project/vllm#1307]

**Comment by wangschang** [comment]
I need qwen-int4 support too!

**Comment by wangschang** [comment]
when I run qwen-int . throw a error like this   

ValueError: Quantization is not supported for <class 'vllm.model_executor.models.qwen.QWenLMHeadModel'>.

**Comment by casper-hansen** [comment]
I have a draft PR open in AutoAWQ but the Qwen implementation is buggy compared to other models. Waiting for Qwen to be streamlined a bit more or for someone to help create a workaround.

https://github.com/casper-hansen/AutoAWQ/pull/78

**Comment by Minami-su** [comment]
+1

**Comment by raihan0824** [comment]
+1
