### ISSUE TITLE
vllm cutoff the output

### ISSUE THREAD

**Issue by piziliufeng** [vllm-project/vllm#1312]
We deployed the Baichuan2_13B model based on the VLLM framework. However, response truncation often occurs when an interface is invoked, see the following figure. The max_tokens of the request parameter is sent to 2500. According to the output tokens statistics, the maximum value is not reached either. Do you know what the problem is?
request:
![image](https://github.com/vllm-project/vllm/assets/27138295/11fbc08a-8c59-4754-86d4-df77d94cce63)
response:
![image](https://github.com/vllm-project/vllm/assets/27138295/9b5933a8-c392-4822-94c8-bbd44bcf86e7)

**Comment by Vincent-Li-9701** [comment]
I noticed a very similar issue with Mixtral as well. Do you have any insight on what the potential issue might be?

**Comment by chemrahul82** [comment]
I am seeing the same behavior with Mixtral. I am noticing that the output generation is abruptly stopping during writing numerical characters.

**Comment by Vincent-Li-9701** [comment]
I notice exactly the same issue. I found it's better to remove any trailing space. It helps this pre-mature termination.

**Comment by chemrahul82** [comment]
@Vincent-Li-9701 are you referring to trailing spaces at the end of prompt, i.e. after the [/INST] tag? Or something else? Thanks.

**Comment by Vincent-Li-9701** [comment]
The trailing space. But later I found it's more complicated than that. You need to remove a lot of the noise from the text and also few shot is very helpful.

**Comment by miguelalonsojr** [comment]
Seeing the same thing. Has there been any investigation into this?

**Comment by perretv** [comment]
We are observing this issue while serving the `mistralai/Mixtral-8x7b-Instruct-v0.1` model when using streaming with high concurrency; which prevents us from using vLLM in production. Any comments from the devs on this issue? @WoosukKwon @zhuohan123

**Comment by Vincent-Li-9701** [comment]
I was able to circumvent this problem with some few-shot prompting. But not sure if this is the root cause.

**Comment by miguelalonsojr** [comment]
> I was able to circumvent this problem with some few-shot prompting. But not sure if this is the root cause.

We already do few-shot prompting throughout our pipeline and the issue still occurs. In particular, we're seeing the streaming cutoff almost always when the models is in the middle of generating version numbers, and it does so pretty consistently. In our concurrency tests directly testing a deployed model, we've observed the same consistency is the cutoff, except it cuts off at commas instead of numbers.

**Comment by Vincent-Li-9701** [comment]
Have you checked if the huggingface model produces the same issue?

**Comment by miguelalonsojr** [comment]
We're using the HF model `mistralai/Mixtral-8x7b-Instruct-v0.1`.

**Comment by Vincent-Li-9701** [comment]
I mean loading the modeling using huggingface and run inference via torch

**Comment by Huohhhhy** [comment]
When I use version 0.3.1 or higher, this issue occurs

**Comment by Vincent-Li-9701** [comment]
``

> When I use version 0.3.1 or higher, this issue occurs

Does downgrading to older version help?
