### ISSUE TITLE
Question for continuous batching

### ISSUE THREAD

**Issue by xinhaoc** [vllm-project/vllm#1316]
Hi vllm team:

in the `attention.py` https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/attention.py#L209
looks like you split the prompt phase and generation phase. But in continuous batching, what may happen is There will be a mixture of prompt phase and generation phase.

For example, if one of the request in this batch is finished before others, so another new request will be inserted into this batch. In this case, there will be one request in prompt phase and other requests in generation phase. How do you handle this situation?

Thanks!

**Comment by masahi** [comment]
See my answer https://github.com/vllm-project/vllm/issues/1277#issuecomment-1751299666

**Comment by xinhaoc** [comment]
thanks!
