### ISSUE TITLE
Question regarding behavior of AsyncLLMEngine on single batch

### ISSUE THREAD

**Issue by shixianc** [vllm-project/vllm#1317]
We're planning to serve online traffic using AsyncLLMEngine based on example: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py 

But our traffic limits to 1x1 traffic, i.e. each HTTP request contains only 1 prompt. Will AsyncLLMEngine dynamically form a larger batch size for incoming requests? 

Thru reading the code, it seems it should have the same behavior as offline batch llm engine: on each decoding iteration, the scheduler will automatically create a large enough batch from the requests queue to max out GPU memory utilization. I want to confirm if this is true for online serving.

**Comment by hmellor** [comment]
Yes, if multiple requests come in at the same time, they will be batched
