### ISSUE TITLE
openbuddy-llama2 bug

### ISSUE THREAD

**Issue by xiaoyaolangzhi** [vllm-project/vllm#1319]
path = "./openbuddy-llama2-13b-v11.1-bf16"
prompts = ["hello"]
llm = LLM(model=path, tokenizer=path, trust_remote_code=True, tensor_parallel_size=2, dtype="auto", tokenizer_mode="slow", load_format="pt")
outputs = llm.generate(prompts)
text = outputs[0].outputs[0].text

text is : hd2022 Mohammed Ali Jinnah Democratic Republic Sudan (

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
