### ISSUE TITLE
Something is blocked where tensor_parallel_size > 1

### ISSUE THREAD

**Issue by Oubaaa** [vllm-project/vllm#1320]
Something is blocked where tensor_parallel_size > 1

The displayed content is：
Started a local Ray instance.
and nothing else

it is work where  tensor_parallel_size == 1

I set NCCL_IGNORE_DISABLED_P2P=1.

it is error before I set NCCL_IGNORE_DISABLED_P2P=1.

**Comment by miko7879** [comment]
I'm running into the same issue, is this related to Ray by any chance?

**Comment by miko7879** [comment]
We solved the issue on our end. If you're running in a container make sure --pid-limit is set to a high value, such as 60000. Same with ulimit -u. Also run the container in privileged mode.

**Comment by Oubaaa** [comment]
> We solved the issue on our end. If you're running in a container make sure --pid-limit is set to a high value, such as 60000. Same with ulimit -u. Also run the container in privileged mode.

Thank you for your reply. I did not run using a container. When I upgraded the Cuda version to 11.8, this issue was resolved
