### ISSUE TITLE
memory leak when running mistralai/Mistral-7B-Instruct-v0.1

### ISSUE THREAD

**Issue by captify-sivakhno** [vllm-project/vllm#1321]
I have an error suggesting memory leak when running 
```llm = LLM(model="mistralai/Mistral-7B-Instruct-v0.1", trust_remote_code=True, dtype="float16", tensor_parallel_size=1, gpu_memory_utilization=0.80, max_model_len=8000)
sampling_params = SamplingParams(best_of=3, temperature=0.8, top_p=0.95, max_tokens=450, presence_penalty = 1.0, frequency_penalty=1.)
outputs = llm.generate(prompts, sampling_params)
```

ValueError: Double free! PhysicalTokenBlock(device=Device.GPU, block_number=415, ref_count=0) is already freed.

Any suggestions on what to look into would be most appreciated!

**Comment by WoosukKwon** [comment]
Hi @captify-sivakhno, thanks for reporting the bug. Could you share your `prompts` so that we can reproduce the bug?

**Comment by frankiedrake** [comment]
I have the same issue running inference on multiple GPU

**Comment by chadlzx** [comment]
The issue seems to occur when the Prompt is too long; I estimate that this threshold of input_id length is above 2048.

**Comment by chujiezheng** [comment]
@WoosukKwon Hi, is there any progress on this issue?

**Comment by hmellor** [comment]
Closing in preference to #1556

**Comment by Raphaelzrf** [comment]
@manzke 'Mistral-7B-Instruct-v0.3' also has this problem, and editing  the config.json (set "sliding_window": null) doesn't work
