### ISSUE TITLE
Lightweight (C++ / Native) Runtime

### ISSUE THREAD

**Issue by wsxiaoys** [vllm-project/vllm#1336]
It appears that there is no tracking issue mentioned for the lightweight runtime in the [Roadmap](https://docs.google.com/presentation/d/1QL-XPFXiFpDBh86DbEegFXBXFXjix4v032GhShbKf3s/edit#slide=id.g24ab9eb18b6_1_7).

I create this issue so that interested individuals can subscribe for updates on it.

**Comment by wejoncy** [comment]
Hi
We are working on onnxruntime as a backend and we hope which can improve it at some extend.

**Comment by simon-mo** [comment]
We have decided on utilizing graph capture and torch compile, instead of native runtime.

**Comment by xushijie** [comment]
> We have decided on utilizing graph capture and torch compile, instead of native runtime.
Do you have documents for this part? Thanks
