### ISSUE TITLE
what is the recommended way to call function of model like transformers do?

### ISSUE THREAD

**Issue by lynnleelhl** [vllm-project/vllm#1342]
for example baichuan2-13b has a function `chat` in huggingface's example page using transformers
```
response = model.chat(tokenizer, messages)
```
how could I call this function using vllm like that?

**Comment by hmellor** [comment]
You would need to use your Huggingface tokenizer to turn `messages` into a prompt, and then you can follow this documentation https://docs.vllm.ai/en/latest/getting_started/quickstart.html#offline-batched-inference
