### ISSUE TITLE
about vllm healthy check on k8s

### ISSUE THREAD

**Issue by allenhaozi** [vllm-project/vllm#1343]
Deploying vllm on k8s For service stability, healthy check is configured

1. TCP check
2. real llm request
3. healthy check api

1. tcp is a little simple
2. real request relative resource consumption

Can we add a simple calculation to provide check as follows

```
@app.get("/healthz")
async def health_check():
    """Health check"""
    # a simple compute
```

if it works, I would like to contribute this pr

**Comment by nivibilla** [comment]
see #1244

**Comment by simon-mo** [comment]
health endpoint has been added in recent versions.
