### ISSUE TITLE
[Error] 400 Bad Request

### ISSUE THREAD

**Issue by Tostino** [vllm-project/vllm#1351]
Hey all, I am getting some errors when using the OpenAI api end point:
```
INFO:     ::1:51556 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
```

Getting that somewhat often (every 15 min or so).

And then on the client side:
```
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"max_tokens must be at least 1, got -53.","type":"invalid_request_error","param":null,"code":null}' (HTTP response code was 400)
```

Release 0.2.0

Running on 2x 3090 using: python -m vllm.entrypoints.openai.api_server --model Tostino/Inkbot-13B-8k-0.2 --tensor-parallel-size=2 --conversation-template inkbot.json

**Comment by Tostino** [comment]
Haven't continued getting this error so I will close this.

**Comment by viviable** [comment]
got the same problem here

**Comment by SafeyahShemali** [comment]
I solve it by checking the required number of max_token as in chat completion you have to consider input and output.

**Comment by yuting-shi** [comment]
I set the parameter "max-model-len" as 8192 and my input token length was 4988, but it still shows the same error "400 Bad Request"

**Comment by DarkLight1337** [comment]
> I set the parameter "max-model-len" as 8192 and my input token length was 4988, but it still shows the same error "400 Bad Request"

Can you repost your issue in #4667 so it can get more visibility?

**Comment by PRAVEENKUMAR2003** [comment]
how you guys solved? I am locally running its working, when I dockerize it its not working

**Comment by dondiegorivera** [comment]
I got the same issue, I can talk to the model from python but it does not work via vscode/cline.

**Comment by DarkLight1337** [comment]
> I got the same issue, I can talk to the model from python but it does not work via vscode/cline.

Can you create a new issue and explain it in more detail?
