### ISSUE TITLE
Failed to build xformers from wheel even though they are already present

### ISSUE THREAD

**Issue by DjWarmonger** [vllm-project/vllm#1353]
I tried to install vllm in a fresh Conda environment today. It depends on xformers, but fails to build them:

```
        File "C:\Users\tomas\miniconda3\envs\llm_server\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/__w/xformers/xformers/third_party/flash-attention/csrc/flash_attn/flash_api.cpp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.    
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects
```
Indeed, latest xformers release fails to work on Windows. So I tried to install minimum supported version xformers 0.0.22 via pip and it succedded:
```
filelock          3.9.0
fsspec            2023.4.0
Jinja2            3.1.2
MarkupSafe        2.1.2
mpmath            1.3.0
mypy-extensions   1.0.0
networkx          3.0
numpy             1.26.0
pip               23.2.1
pyre-extensions   0.0.29
setuptools        68.0.0
sympy             1.12
torch             2.0.1
typing_extensions 4.4.0
typing-inspect    0.9.0
wheel             0.41.2
xformers          0.0.22
```
However, vllm installer seems to ignore it and **still** tries to (re?)build the wheel, and as a result it fails the entire installation process.

More details: https://github.com/facebookresearch/xformers/issues/886#issuecomment-1762922926

**Comment by rer0dgers** [comment]
Exactly the same issue.

**Comment by uGuardian** [comment]
Also having the same issue. It's worth mentioning that I'm in a venv.

**Comment by DjWarmonger** [comment]
It seems that the xformers issue was fixed on their side. That error doesn't show up anymore, but there's still another during pip install.
Possibly on my side, will  investigate.

**Comment by WoosukKwon** [comment]
I believe this should be fixed now since we changed the xformers version from `>=0.0.22` to `==0.0.22`. Could you try again?

**Comment by Santiagowwi** [comment]
> I believe this should be fixed now since we changed the xformers version from `>=0.0.22` to `==0.0.22`. Could you try again?

Dont working

**Comment by zeke-john** [comment]
@DjWarmonger @uGuardian @Santiagowwi @WoosukKwon @rer0dgers Any updates? facing the same issue.

**Comment by Santiagowwi** [comment]
@zeke-john No
