### ISSUE TITLE
Pre-PR Feedback: Token Filtering API

### ISSUE THREAD

**Issue by noamgat** [vllm-project/vllm#1357]
Hello. I'm looking to contribute a prefix token filtering mechanism to vLLM, to allow functionality similar to huggingface's

```
prefix_allowed_tokens_fn: Callable[[int, torch.Tensor], List[int]]
```

parameter when calling generate(). 

Is this something that the team will be willing to consider accepting if I submit a PR?
I thought about adding an optional function field to SamplingParams and using it in the Sampler module if it was provided, but prefer feedback from the team before I dive inside.

For some context - I developed a library - [LM Format Enforcer](https://pypi.org/project/lm-format-enforcer) that uses this API (and nothing else, contrary to similar libraries) to allow forcing JSON / regular expression output from the LLM, and opening this API will allow easy integration of it into vLLM.

**Comment by noamgat** [comment]
I created a notebook that shows how to integrate the library with vLLM in its current form:

https://github.com/noamgat/lm-format-enforcer/blob/main/samples/colab_vllm_integration.ipynb

However, it makes use of monkey patching to bypass limitations.

There is one cell which contains 99% of the (non-unit-test) code that will be in the PR if I will submit it:

```
import vllm
import torch
from typing import List, Callable, Optional
from vllm.sampling_params import SamplingParams
from vllm.model_executor.input_metadata import InputMetadata

class SamplingParamsWithFilterFunction(SamplingParams):
    logits_allowed_tokens_filter_function: Optional[Callable[[int, torch.Tensor], List[int]]]

def _apply_allowed_token_filters(logits: torch.Tensor, 
                                 input_metadata: InputMetadata) -> torch.Tensor:
    num_seqs, vocab_size = logits.shape
    logits_row_idx = 0
    for seq_ids, sampling_params in input_metadata.seq_groups:
        if isinstance(sampling_params, SamplingParamsWithFilterFunction):
            filter_function = sampling_params.logits_allowed_tokens_filter_function
        else:
            filter_function = None
        for seq_id in seq_ids:
            if filter_function is not None:
                output_token_ids = input_metadata.seq_data[seq_id].output_token_ids
                output_token_tensor = torch.tensor(output_token_ids, dtype=torch.long)
                allowed_tokens = filter_function(logits_row_idx, output_token_tensor)
                logits_add_factor = torch.zeros(vocab_size, dtype=logits.dtype, device=logits.device)
                logits_add_factor[:] = float('-inf')
                logits_add_factor[allowed_tokens] = 0
                logits[logits_row_idx] += logits_add_factor
            logits_row_idx += 1
    assert logits_row_idx == num_seqs
    return logits 
```

And then a call to the function needs to happen in ```Sampler.forward()```:

```
logits = _apply_allowed_token_filters(logits, input_metadata)
```

And thats it. I think this is a positive step for vLLM in such integrations, and does not really have drawbacks. What do you think?

**Comment by noamgat** [comment]
Opened a PR here: https://github.com/vllm-project/vllm/pull/1469

**Comment by flexorRegev** [comment]
adding in an example code to use it in a batch setting when you want to generate each request with a different constraint (using the Regex constraint here):

```python
def vllm_batch_with_constraint(llm: vllm.LLM, prompts_and_constraint_regexes: list[(str,str)]) -> str:
        for prompt,regex in prompts_and_constraint_regexes:
            parser = RegexParser(regex)
            prefix_function = build_transformers_prefix_allowed_tokens_fn(llm.get_tokenizer(), parser) if parser else None
            sampling_params = SamplingParamsWithFilterFunction()
            sampling_params.temperature = 0.0
            sampling_params.top_p = 1
            sampling_params.stop_token_ids = [model.tokenizer.eos_token_id]
            sampling_params.max_tokens = DEFAULT_MAX_NEW_TOKENS
            sampling_params.logits_allowed_tokens_filter_function = prefix_function
            llm._add_request(prompt, sampling_params=sampling_params,prompt_token_ids=None)
        results = llm._run_engine(use_tqdm= True)
        return results
```
