### ISSUE TITLE
Qwen-7B-Chat  vllm failed

### ISSUE THREAD

**Issue by shujun1992** [vllm-project/vllm#1359]
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:121, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'

**Comment by Qinyong-Wang** [comment]
use cuda 11.8

**Comment by cipolee** [comment]
+1,cuda 11.8还是报这个错

**Comment by Zhi-lin** [comment]
这个问题有解决方案吗
