### ISSUE TITLE
Please release the latest code

### ISSUE THREAD

**Issue by immcossi** [vllm-project/vllm#1360]
Using the current release version, Mistral models cannot be used with VLLM, getting the error 'ValueError: Quantization is not supported for <class 'vllm.model_executor.models.mistral.MistralForCausalLM'>'.
After the last release, lots of changes were added for Mistral models, without good GPU support VLLM cannot be built from the source, please release the latest build to Pypi so that everyone can access the latest features.

**Comment by casper-hansen** [comment]
#1346 looks to be underway for release today.

**Comment by immcossi** [comment]
@casper-hansen Thanks for the update.
