### ISSUE TITLE
does vllm use Flash-Decoding?

### ISSUE THREAD

**Issue by 0x1997** [vllm-project/vllm#1362]
As vllm depends on xformers, is vllm already using this [Flash-Decoding](https://together.ai/blog/flash-decoding-for-long-context-inference) algorithm?

**Comment by WoosukKwon** [comment]
Hi @0x1997, yes. PagedAttention V2 (#1348) implements a similar idea to boost the performance when the batch size or the number of attention heads per GPU is small. We will announce more once all planned optimizations are merged.

**Comment by leocnj** [comment]
It looks that PR #1348 has been merged into 0.2.1 release. To use V2 version, do users need do anything when calling vllm? Thanks

**Comment by WoosukKwon** [comment]
@leocnj Nothing is required for users. vLLM uses both V1 and V2 based on a simple heuristic:
https://github.com/vllm-project/vllm/blob/d189170b6c5a143e493c3f5cb7e8c976e8da62c7/vllm/model_executor/layers/attention.py#L159

In a nutshell, currently we use V2 only when the batch size is small. Once we further optimize the performance, we will use V2 in more cases.

**Comment by hongqing1986** [comment]
> @leocnj Nothing is required for users. vLLM uses both V1 and V2 based on a simple heuristic:
> 
> https://github.com/vllm-project/vllm/blob/d189170b6c5a143e493c3f5cb7e8c976e8da62c7/vllm/model_executor/layers/attention.py#L159
> 
> In a nutshell, currently we use V2 only when the batch size is small. Once we further optimize the performance, we will use V2 in more cases.

In the above condition, if either of the following conditions is met, the code will follow the "v1" version. You mentioned that it only applies when the batch size is small. However, in practice, for a small batch size, the other condition as well:

max_num_partitions = (
(input_metadata.max_context_len + _PARTITION_SIZE - 1) //
_PARTITION_SIZE)

According to the calculation logic above, essentially, in this batch, most sequences with a maximum length of less than or equal to 512 will also follow the "v1" version. As a result, the impact will only be noticeable when the batch size is small and there is at least one sequence with a length greater than 512.

Is my understanding correct?

**Comment by WoosukKwon** [comment]
@hongqing1986 Yes, your analysis is correct. V2 is used when the batch size is small and at least one sequence has a context length over 512.
