### ISSUE TITLE
cannot import name 'activation_ops' from 'vllm'

### ISSUE THREAD

**Issue by Darrenzeng** [vllm-project/vllm#1367]
We discovered some issues while experimenting with the framework. Some packages are missing in the vllm directory：

1. ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm' (most likely due to a circular import)
2. ImportError: cannot import name 'activation_ops' from 'vllm'

Our run command is：python3 -m vllm.entrypoints.api_server

**Comment by WoosukKwon** [comment]
Could you run vLLM outside the root directory of the repo?

**Comment by Darrenzeng** [comment]
No, we did it in the vllm-main

**Comment by Darrenzeng** [comment]
Thank you for your reply. We successfully solved the problem using the method you mentioned.
