### ISSUE TITLE
single_query_cached_kv_attention  does not supported long sequence inference.

### ISSUE THREAD

**Issue by jameswu2014** [vllm-project/vllm#1370]
In 'test_attention.py': MAX_SEQ_LEN=get_max_shared_memory_bytes() // FLOAT32_BYTES - 512
In my A100 env, the MAX_SEQ_LEN = 41216. While, when my kv seq len is larger than the value, such as 65536, the kernel will failed.the error like this:
"
E               RuntimeError: CUDA error: invalid argument
E               CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
E               For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
E               Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
"
How can I fix it?

**Comment by jameswu2014** [comment]
I got it. In worker.py, there is a function "_check_if_can_support_max_seq_len":
"""
def _check_if_can_support_max_seq_len(max_seq_len: int,
                                      block_size: int) -> None:
    # Follows the logic in
    # attention_kernels.cu::single_query_cached_kv_attention_launcher
    max_shared_mem = get_max_shared_memory_bytes()
    float32_bytes = torch.finfo(torch.float).bits // 8
    padded_max_seq_len = (
        (max_seq_len + block_size - 1) / block_size) * block_size
    # padded_max_seq_len + extra buffer
    required_shared_mem = (padded_max_seq_len + 512) * float32_bytes
    if padded_max_seq_len * float32_bytes > max_shared_mem:
        raise RuntimeError(
            f"vLLM cannot currently support max_model_len={max_seq_len} "
            f"with block_size={block_size} on GPU with compute "
            f"capability {torch.cuda.get_device_capability()} "
            f"(required shared memory {required_shared_mem} > "
            f"available shared memory {max_shared_mem}). "
            "This will be fixed in a future release.")
"""
So when will it  be fixed? As we know, Long context is becoming very popular, so it is significant to support this feature.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
