### ISSUE TITLE
Does vllm support KV-cache between multi-turn conversation

### ISSUE THREAD

**Issue by leoozy** [vllm-project/vllm#1371]
Hello, in many cases, we need to take multi-turn conversation. That is, the output of the first step will be added to the input of the second step. Could you please tell me whether the common part of the multi-turn conversation will be cached?

**Comment by jameswu2014** [comment]
I have the same question.

**Comment by kongjiellx** [comment]
+1

**Comment by HouYueJie** [comment]
+1

**Comment by hmellor** [comment]
Yes, in the form of prefix caching https://github.com/vllm-project/vllm/pull/2762
