### ISSUE TITLE
Nvidia Tesla p40 24GB

### ISSUE THREAD

**Issue by LakoMoor** [vllm-project/vllm#1374]
Hello! Has anyone used GPU p40? I'm interested to know how many tokens it generates per second. Preferably on 7B models.

**Comment by WoosukKwon** [comment]
Hi @LakoMoor, unfortunately vLLM only supports Volta or later GPUs. P40 is not officially supported.

**Comment by LakoMoor** [comment]
Oh... it's very sad... I just bought 10 gpus...((

**Comment by yukimakura** [comment]
#963
