### ISSUE TITLE
Improving FLOPS utilization with smaller models

### ISSUE THREAD

**Issue by kevinhu** [vllm-project/vllm#1375]
Hello! We've been using VLLM to run some batch inference tasks and are huge fans of the experience so far.

However, some of the models we're using are on the smaller end (<3B parameters), and for these models we're only seeing about 50% GPU utilization. If we use larger models (>7B) we're able to consistently hit 90%+ utilization.

Do you have any tips for optimizing utilization for these smaller models? I've tried tweaking the max cached sequences/tokens and the block size, but those don't seem to make much of a difference.

**Comment by kevinhu** [comment]
I tested out an experimental CUDA graph PR that Yunfeng shared here: https://github.com/yunfeng-scale/vllm/pull/1. At large batch sizes, there isn't much of a difference. It seems the primary bottleneck is the logic that's executed in `engine.step()` rather than Pytorch dispatches.

**Comment by yunfeng-scale** [comment]
i think for large batch sizes CPU/GPU communication overhead is not significant any more. to increase GPU utilization on smaller models i think we should look at integrating the idea from https://pytorch.org/blog/flash-decoding/ into paged attention kernels

**Comment by MichaelJayW** [comment]
Same issue here with llama 1.4B. Small model can use larger batch which means more seqs for decoding, GPU is idle when decoding which cause GPU low util
Profiling it by using nvtx in llm_engine.py's step(). Steps are:
![image](https://github.com/vllm-project/vllm/assets/1152904/e2b4921c-97e0-4748-98b4-fcae93ec364b)
Decoding time incre with seqence size(from 1ms to 30ms!!!):
![image](https://github.com/vllm-project/vllm/assets/1152904/8cdf88f9-a33f-4de4-be10-0f1f06842386)
**Small model can use larger batch which means more seqs for decoding, GPU is idle when decoding which cause GPU low util**
NSight file, unzip it open it with NSight:
[vllm014-llama-1B4-30prompts-detail copy.nsys-rep.zip](https://github.com/vllm-project/vllm/files/13407690/vllm014-llama-1B4-30prompts-detail.copy.nsys-rep.zip)
