### ISSUE TITLE
What is best preactice to serve to multiple user?

### ISSUE THREAD

**Issue by bodybreaker** [vllm-project/vllm#1387]
I think i can deal with Btach inference with queue,
but is there any way to serve batch inference with streaming like chatGPT?

**Comment by bodybreaker** [comment]
@Cyberes Yes I did

**Comment by yungangwu** [comment]
same problem

**Comment by hmellor** [comment]
https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html
