### ISSUE TITLE
bump pydantic to v2

### ISSUE THREAD

**Issue by jens-create** [vllm-project/vllm#1396]
Would be it be possible to bump pydantic to v2 as ray [serve] is now compatible with pydantic v2? See [Ray PR](https://github.com/ray-project/ray/pull/40222).

Follow up on issue #423 and PR #429.

**Comment by WoosukKwon** [comment]
Hi @jens-create Thanks for bringing this up! We will definitely consider bumping up the version once they bump up the pydantic version in Ray.

**Comment by michaelfeil** [comment]
Is there a follow-up on this?

**Comment by dbuades** [comment]
Just an FYI, Ray just released their 2.9.0 version, which adds support for Pydantic >=2.5.0

https://github.com/ray-project/ray/releases/tag/ray-2.9.0

CC @WoosukKwon

**Comment by Lawouach** [comment]
Hi all,

That would be quite good to upgrade, less and less projects will expect pydantic 1.x so the pin on 1.10 on vllm is a becoming a headache.

**Comment by jvmncs** [comment]
bumping this! there is an open PR for it here: https://github.com/vllm-project/vllm/pull/2322
