### ISSUE TITLE
Different deployments of Baichuan2 yield very different answers

### ISSUE THREAD

**Issue by wuQi-666** [vllm-project/vllm#1407]
Using vllm mode to deploy Baichuan2, providing test interface, using postman test, and using page mode to deploy Baichuan2, two ways to ask the same question, why the use of postman interface mode to get the answer will be wrong, and after the error to ask other questions will also be wrong?

![image](https://github.com/vllm-project/vllm/assets/139730426/a5367a4e-bf6b-4dbf-8c9f-c2f5699dbf50)
![image](https://github.com/vllm-project/vllm/assets/139730426/69acc051-2785-4c4b-8b41-a6fbca4eedaa)

**Comment by zzzzzxw** [comment]
I encountered the same problem with baichuan2-7b-chat, but the baichuan2-13b-chat output was completely correct. In fact, my 7b-chat model outputs the first sentence correctly, and the second output of multiple rounds of dialogue starts to produce errors. Moreover, I clearly observed that 7b-chat uses rotery.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
