### ISSUE TITLE
Going to cancel this PR, and work on another which properly implements the HF chat templates within the tokenizer.

### ISSUE THREAD

**Issue by lamm-mit** [vllm-project/vllm#1425]
Going to cancel this PR, and work on another which properly implements the HF chat templates within the tokenizer.

_Originally posted by @Tostino in https://github.com/vllm-project/vllm/issues/1294#issuecomment-1763618404_

**Comment by lamm-mit** [comment]
I am curious to see if you had any updates on whether the HF chat templates have been implemented? Thank you for the great work.

**Comment by Tostino** [comment]
https://github.com/vllm-project/vllm/pull/1365

Just waiting on feedback / someone to merge. I've run 100 million tokens through this setup so far.

**Comment by darinkishore** [comment]
@Tostino Thank you so much!! How are they handling chat templates rn? like if you called mistral, would it actually use the proper templates if you called it through their openai thing?

**Comment by Tostino** [comment]
The base Mistral model doesn't include a chat template in the tokenizer: https://huggingface.co/mistralai/Mistral-7B-v0.1/blob/main/tokenizer_config.json

But you could specify it yourself in a file and use the --chat-template flag to get Mistral working with templates properly.

Or if someone else has implemented it in the tokenizer for Mistral you can use their tokenizer instead.

**Comment by Tostino** [comment]
Sorry... I spoke too soon. Mistral instruct does actually include a chat template: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/blob/main/tokenizer_config.json

So yes they should work with my fork out of the box with the OpenAI API.

**Comment by Stealthwriter** [comment]
![image](https://github.com/vllm-project/vllm/assets/126798556/397438fa-c148-456a-8a4d-844d65a971f6)
I'm using mistral , why vllm is using this format?

**Comment by Stealthwriter** [comment]
This needs to be fixed because using ### for mistral outputs weird stuff

**Comment by Stealthwriter** [comment]
anyone knows how to fix this?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
