### ISSUE TITLE
Mistral much slower than LLaMa-2-7B

### ISSUE THREAD

**Issue by ojus1** [vllm-project/vllm#1428]
I have finetuned both Mistral-7B and Llama2-7b on custom usecase and quantized them using AutoAWQ.
Below are the benchmark results (throughput here is tokens/sec).
From my understanding, shouldn't Mistral be faster or equivalent to Llama2? Can someone figure out why this is the case?

![image](https://github.com/vllm-project/vllm/assets/13467155/251b38a2-e741-4b9b-8c64-9a29c3a772e1)

**Comment by vishalsingha** [comment]
The result of autoAWQ quantized model after fine-tuning is different from different form loading finetuned model in huggingface.

**Comment by zihaolucky** [comment]
Same issue in my case, any updates? Thanks.
