### ISSUE TITLE
requests.exceptions.ConnectionError when using on an offline cluster 

### ISSUE THREAD

**Issue by HYZ17** [vllm-project/vllm#1432]
I try to use vllm to run llama-7b on my offline cluster. And I have set the environment variable `TRANSFORMERS_OFFLINE=1`. But I still got error as follows. 
`requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/huggyllama/llama-7b/revision/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b27fbfbe550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"), '(Request ID: 3b8686a3-75ca-4258-bebc-83ef391708a8)')`

### Environment info
```
python==3.8.18 
vllm ==0.1.7
transformers==4.33.0 
```
Is it possible for me to use Vllm on an offline cluster? And how to do so?

**Comment by HYZ17** [comment]
yes, please refer to https://github.com/vllm-project/vllm/discussions/1405#discussioncomment-7796433

**Comment by llmwesee** [comment]
It works but the generated responses are wrong most of the time.
