### ISSUE TITLE
vLLM docker image

### ISSUE THREAD

**Issue by RonanKMcGovern** [vllm-project/vllm#1438]
Has anyone built a docker image, or could an auto build be set up?

TGI has a docker image available and it makes inferencing much more turnkey on services like runpod.

**Comment by ehartford** [comment]
@winglian has this one
https://github.com/winglian/worker-vllm-new
https://hub.docker.com/r/winglian/runpod-worker-vllm/tags

**Comment by RonanKMcGovern** [comment]
@ehartford is there a docker version that runs the fastapi api?

As far as I understand, the main docker image on vllm runs an openai compatible api, and it's unclear whether that can batch async requests or not (while I believe fastapi can).

I had a look through @winglian 's docker image and it seems to be a custom api built, rather than using fastapi or openai style, correct?

**Comment by simon-mo** [comment]
The OpenAI server vLLM ship with have _exactly_ the same code path as the demo API server (FastAPI server you are mentioning). It support async requests batching.

**Comment by RonanKMcGovern** [comment]
ok that's great, probably don't need a fastapi docker image then. thanks
