### ISSUE TITLE
Plugin Pycharm compatible with vLLM ?

### ISSUE THREAD

**Issue by maxpln** [vllm-project/vllm#1439]
Hi !

I'm looking to use a an open source LLM as code assistant on my PyCharm IDE.
I use vLLM to create an API for the model, but do you know a Jetbrain Plugin compatible with vLLM ?
I would like a plugin which act like Copilot for example. 

I'm open to every sugestions. 

Thanks !

**Comment by kzawisto** [comment]
You could try Refact Assistant or Tabby ML for this (server + plugin). I doubt that coding autocomplete LLMs are a focus here (but it's interesting what comes out of this topic).

**Comment by hmellor** [comment]
vLLM provides an OpenAI compatible server. So if you find a plugin that can talk to OpenAI, then it can talk to vLLM.
