### ISSUE TITLE
Failed to load the Qwen-14b-chat tokenizer

### ISSUE THREAD

**Issue by xjDUAN184** [vllm-project/vllm#1445]
from vllm import LLM

llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1')  # Name or path of your model
output = llm.generate("Hello, my name is")
print(output)

The error message is as follows：

Exception has occurred: RuntimeError
Failed to load the tokenizer. If the tokenizer is a custom tokenizer not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
ValueError: Tokenizer class QWenTokenizer does not exist or is not currently imported.

The above exception was the direct cause of the following exception:

  File "/home/czp/vllm-main/vllm/test.py", line 3, in <module>
    llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1')  # Name or path of your model
RuntimeError: Failed to load the tokenizer. If the tokenizer is a custom tokenizer not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.

**Comment by Sanster** [comment]
You need to confirm that there are tokenize-related files under the directory `/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1` (if not, copy from other directories of snapshots), or directly use `Qwen/Qwen-14B-Chat`.

**Comment by xjDUAN184** [comment]
@Sanster 
hello, 
![image](https://github.com/vllm-project/vllm/assets/73686733/4f06f253-6444-4bc7-a49a-878525bb0c2f)
![image](https://github.com/vllm-project/vllm/assets/73686733/a91c74e5-2687-46b1-b313-ed0ed8f6847e)
The above picture is the file about tokenizer in the local folder, and the picture below is the picture about tokenizer in huggingface. Both are the same.

**Comment by Sanster** [comment]
```python
llm = LLM(model='/root/.cache/huggingface/hub/models--Qwen--Qwen-14B-Chat/snapshots/63faec65d9eb7d31b6a177e0680563eb4043a1a1', trust_remote_code=True)
```

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
