### ISSUE TITLE
How to set model quantization to int4 when calling the api interface?

### ISSUE THREAD

**Issue by xjDUAN184** [vllm-project/vllm#1446]
I am using the api    vllm/entrypoints/openai/api_server.py without setting the parameters for model quantification. I tried --quantition as "int4" but it didn't work. My model is llama2

**Comment by ehartford** [comment]
vllm doesn't support 4bit

**Comment by hmellor** [comment]
Quantization is supported via AWQ, GPTQ, SqueezeLLM
