### ISSUE TITLE
Use vLLM to load model that exceed the memory size of a single graphics card

### ISSUE THREAD

**Issue by LuckySevenTc** [vllm-project/vllm#1449]
Can increasing tensor_parallel_size parameter solve the problem that the single graphics card's memory is not enough to deploy the model? Apart from modifying this parameter, is there any way to solve this problem when loading the model using vLLM?

**Comment by hmellor** [comment]
To use tensor parallel you must have >1 GPU. You can reduce memory usage by:
- Using quantization
- Setting `--enforce-eager`
- Decreasing `--gpu-memory-utilization`
- Decreasing `--max-model-len`

https://docs.vllm.ai/en/latest/models/engine_args.html
