### ISSUE TITLE
vllm Infer blocking

### ISSUE THREAD

**Issue by ming-shy** [vllm-project/vllm#1450]
I use vllm 0.2.0 for model reasoning, the first request can return the result normally, the second request can see the request entered the vllm, but there is no result, and the subsequent request feels blocked. Can you help me? Analyze what the reason is.

However, this does not happen when I use vllm 0.1.4.

**Comment by ming-shy** [comment]
I did not use the api_server provided by the project, and used flask to deploy, I would encounter the above problems, but 0.1.4 is no problem at all, 0.1.7, 0.2.0 will have the above problems.

**Comment by ming-shy** [comment]
Dear author,
At the bottom I used the flask framework to build the web service, but there were some strange phenomena (below). Isn't vllm compatible with other web frameworks?

①The first request to enter can be reasoned normally;
②Second request, vllm directly calls abort_request;
③ After subsequent requests are Received, vllm prints a log saying Received request, but no more inference is performed.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
