### ISSUE TITLE
Benchmarking vs TGI

### ISSUE THREAD

**Issue by harryjulian** [vllm-project/vllm#1451]
I've been comparing the performance of TGI and vLLM recently; using `Mistral`, on my setup it seems like TGI now massively outperforms vLLM in this case.

I'm running on a g5.xlarge (1x NVIDIA A10G), both vLLM and TGI in respective docker containers.

Is this performance difference expected? 

I also noticed the TGI launch script in the benchmarks uses v0.8, this should probably be updated to the newest version (or the newest pre-license change version, at least).

**Comment by amir-in-a-cynch** [comment]
Yes, I've been seeing Mistral is slower than I expected on vLLM too.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
