### ISSUE TITLE
Questions on High Throughput Support and Parameter Tuning

### ISSUE THREAD

**Issue by williamjeong2** [vllm-project/vllm#1452]
Hey vllm Team,

I’ve been diving into vllm and saw that it’s designed to support high throughput, which is awesome! Got a few questions and was hoping to get some guidance to make the most out of it.

1.	**Parameter Settings for High User Load**: I was wondering if you guys have any recommended settings or a formula for determining the best parameters when dealing with a lot of users. Any tips or best practices on this?
2.	**Example with a Specific Model**: If you could provide an example, especially using a specific model, on how to set this up for optimal performance, that would be super helpful.
3.	**Handling More Concurrent Requests**: Also, is there a way to reduce the token/s but still handle more concurrent requests? Looking for some strategies or tweaks here.

Thanks a ton for your help!

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
