### ISSUE TITLE
The detected CUDA version (11.8) mismatches the version that was used to compile       PyTorch (12.1). Please make sure to use the same CUDA versions

### ISSUE THREAD

**Issue by sujianwei1** [vllm-project/vllm#1453]
RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

**Comment by sujianwei1** [comment]
my torch version is 2.0.1

**Comment by Tan-YiFan** [comment]
If your cuda version is 11.8, this command might help:

```bash
pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
```

Ref: https://pytorch.org/get-started/previous-versions/

**Comment by 128Ghe980** [comment]
same problem,mark

**Comment by 128Ghe980** [comment]
> If your cuda version is 11.8, this command might help:
> 
> ```shell
> pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> Ref: https://pytorch.org/get-started/previous-versions/

I have a very similar problem:
The detected CUDA version (11.7) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
And I use this: 
pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 --index-url https://download.pytorch.org/whl/cu117

but still I recive the same error. Can you help me?

**Comment by Tan-YiFan** [comment]
@128Ghe980 Make sure that you run `pip install` in your conda env.
Try `python -c "import torch; print(torch.__version__)"`. The output should be `2.0.1+cu117`

**Comment by wangkuiyi** [comment]
@Tan-YiFan `pip install -e .` gave me the error as described in https://github.com/vllm-project/vllm/issues/1453#issue-1958405821

`pip list | grep torch` shows that I have `torch 2.1.0+default` installed. However, I couldn't import torch to check its version, because it gave me another error:

```
18:53 $ python
Python 3.9.0 (default, Nov 15 2020, 14:28:56)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yi_wang999747/miniconda3/envs/vllm/lib/python3.9/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/yi_wang999747/miniconda3/envs/vllm/lib/python3.9/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
```

**Comment by wangkuiyi** [comment]
I uninstalled PyTorch 2.1.0 and installed PyTorch 2.0.1. Then I do not longer suffer from the above error.

**Comment by wangkuiyi** [comment]
The error message in https://github.com/vllm-project/vllm/issues/1453#issue-1958405821 means

1. You have NVCC version 11.8 installed on your host / conda env.
1. You are using it to build vLLM's PyTorch extensions as listed in the setup.py file.
1. You have PyTorch installed on your host / conda env.
1. The version of NVCC used to build PyTorch is 12.1
1. You must use NVCC 12.1 to build vLLM's PyTorch extensions

So, you need to upgrade your CUDA / NVCC to version 12.1.

**Comment by sujianwei1** [comment]
modify torch version to 2.0，is ok

**Comment by Ikkyu321** [comment]
same question with cuda11.8，mark

**Comment by juanmf** [comment]
I'm getting this error in a Docker build, So I don't thick the problem is in my system. Am I wrong?
made this issue for tracking: https://github.com/mistralai/mistral-src/issues/76

**Comment by Tan-YiFan** [comment]
Starting from [vLLM v0.2.2](https://github.com/vllm-project/vllm/releases/tag/v0.2.2), PyTorch v2.1 + CUDA 12.1 is supported. If problems are not solved, it might help to use vLLM >= v0.2.2.

**Comment by BramVanroy** [comment]
Unfortunately I am still experiencing this issue. The script keeps telling me that 

```
The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
```

Even though I have only specifically installed cu118. Even more so, `nvcc- --version` yields 11.8 and `python -c "import torch; print(torch.version.cuda)"` also prints 11.8. So I have no idea where this 12.1 is coming from but it seems to have to do with the extensions that it is loading. So I wonder whether there is a mismatch between those that come with the library and PyTorch.

**Comment by hsekki** [comment]
Same problem with @BramVanroy , have you solved the issue? Thanks

**Comment by BramVanroy** [comment]
> Same problem with @BramVanroy , have you solved the issue? Thanks

Sadly, no.

**Comment by OneStepAndTwoSteps** [comment]
Same Problem.

**Comment by alik-git** [comment]
Hi guys, not sure this will help, but I was troubleshooting this myself for another repo (GroundingDINO) and managed to solve the issue so just sharing the solution.

I think this error occurs when the pip creates a temporary python environment to build some package, but that temporary environment may fetch a version of pytorch that's compiled with a different version of cuda than your system. To fix this, you can use the command pip install --no-build-isolation package_name, so for example for the GroundingDINO package it would be:

```bash
pip install --no-build-isolation -e GroundingDINO
```

**Comment by ibeltagy** [comment]
`pip install --no-build-isolation -e .` fixed the problem. Thank you, @alik-git

**Comment by Taited** [comment]
> Hi guys, not sure this will help, but I was troubleshooting this myself for another repo (GroundingDINO) and managed to solve the issue so just sharing the solution.
> 
> I think this error occurs when the pip creates a temporary python environment to build some package, but that temporary environment may fetch a version of pytorch that's compiled with a different version of cuda than your system. To fix this, you can use the command pip install --no-build-isolation package_name, so for example for the GroundingDINO package it would be:
> 
> ```shell
> pip install --no-build-isolation -e GroundingDINO
> ```

Thank you @alik-git ! You saved my day!

**Comment by ricardosanunes** [comment]
> ```shell
> pip install --no-build-isolation -e GroundingDINO
> ```

so do I replace 'GroundingDINO' with 'torch'?
sorry for the question, newbie here

**Comment by alik-git** [comment]
Yes that's right, whatever the name of your package that you want to install is

**Comment by bbbts** [comment]
> If your cuda version is 11.8, this command might help:
> 
> ```shell
> pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
> ```
> 
> Ref: https://pytorch.org/get-started/previous-versions/

In my case the error is - 
"The detected CUDA version (10.0) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions."

I can not seem to find any command that suits it. Kindly help.

**Comment by huangheLee** [comment]
The following command  can fix my same problom.
```
 pip install -U  torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu118
 ```
 code from pytorch website
 https://pytorch.org/get-started/previous-versions/

**Comment by laomao0** [comment]
> `pip install --no-build-isolation -e .` fixed the problem. Thank you, @alik-git

thanks, it helps.

**Comment by liao1fan** [comment]
@

> Hi guys, not sure this will help, but I was troubleshooting this myself for another repo (GroundingDINO) and managed to solve the issue so just sharing the solution.
> 
> I think this error occurs when the pip creates a temporary python environment to build some package, but that temporary environment may fetch a version of pytorch that's compiled with a different version of cuda than your system. To fix this, you can use the command pip install --no-build-isolation package_name, so for example for the GroundingDINO package it would be:
> 
> pip install --no-build-isolation -e GroundingDINO

Thanks!!! It works!!! You are my god.

**Comment by 15101051** [comment]
I think this issue arises because Conda automatically installs the corresponding version of CUDA when installing PyTorch but does not install `nvcc`. On the other hand, when using `pip` to install and build, it only relies on the locally available `nvcc` for compilation. In this case, the CUDA version of PyTorch is higher than the local `nvcc`, leading to a mismatch. The solution is to run:

`conda install cuda-nvcc=12.1.* -c nvidia`

Here, `12.1` corresponds to the CUDA version installed by PyTorch. After that, using:

`pip install --no-build-isolation -e .`

will allow it to use the matching `nvcc`.

**Comment by zerofen** [comment]
Under the Windows system, the Nvidia driver in the system is version 12.4. In order to reproduce the project, CUDA11.3 version is required. After configuring CUDA11.3 in the virtual environment, it is necessary to execute Python setup. py install, but the result is an error with a Runtime Error:The detected CUDA version (12.4) mismatches the version that was used to compilePyTorch (11.3). Please make sure to use the same CUDA versions. How can I solve this problem?
