### ISSUE TITLE
How to change the format of the default template?

### ISSUE THREAD

**Issue by Stealthwriter** [vllm-project/vllm#1460]
![image](https://github.com/vllm-project/vllm/assets/126798556/9e971da7-1c9c-4739-8092-28d33ad963c3)

How to change this format? ### user ### assistant

I'm using mistral model it doesn't use this format

**Comment by agrogov** [comment]
For Mistral model just use plain text requests without `<s>[INST] ... [/INST]</s>` special tokens, for me it works.

**Comment by jrsperry** [comment]
Why is there a giant writeup about a 10 year old birthday party on every template? How does that get populated? The actual prompt isn't till the very end.

**Comment by Stealthwriter** [comment]
> Why is there a giant writeup about a 10 year old birthday party on every template? How does that get populated? The actual prompt isn't till the very end.

I'm also facing the same problem

**Comment by hmellor** [comment]
If you're loading the model from HF then the chat template should be included in `generation_config.json`. Otherwise you can write your own and pass it to the `--chat-template` argument of the OpenAI compatible server.
