### ISSUE TITLE
cumulatve log_probs not available anymore

### ISSUE THREAD

**Issue by SebastianBodza** [vllm-project/vllm#1462]
Is this the prefered way to not calculate the cumulative_logprob? In [v0.2.0](https://github.com/vllm-project/vllm/releases/tag/v0.2.0) they were available in [v0.2.1](https://github.com/vllm-project/vllm/releases/tag/v0.2.1) removed. 

It is always returning 0.0 with awq quant

**Comment by guozhiyao** [comment]
have you solved the problem? I also get 0 with v0.2.0
