### ISSUE TITLE
Error when launching a FastAPI server with mistral AWQ model

### ISSUE THREAD

**Issue by amirabdullah19852020** [vllm-project/vllm#1463]
When I try to launch a mistral model server like the following:

python -m vllm.entrypoints.api_server --model TheBloke/Mistral-7B-OpenOrca-AWQ

I get this error:

```
File "/usr/local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 388, in load_weights
    param = state_dict[name]
KeyError: 'model.layers.0.mlp.down_proj.qweight'
```

I've gotten this same error with a few other AWQ mistral variants I've attempted.

**Comment by amirabdullah19852020** [comment]
I'm an idiot, I just had to specify the right arguments to the server. Closing.

**Comment by puyuanOT** [comment]
Got the same error, how did you solved it?

**Comment by amir-in-a-cynch** [comment]
> I'm an idiot, I just had to specify the right arguments to the server. Closing.

> Got the same error, how did you solved it?

You just have to make sure you pass the quantization argument.
