### ISSUE TITLE
Failed to connect to GCS within 60 seconds

### ISSUE THREAD

**Issue by mengban** [vllm-project/vllm#1465]
my env:
`vllm: 0.2.1-post`
`ray: 2.7.1`
and everything is ok when I run with `tensor_parallel_size=1`
but something goes wrong when I set  `tensor_parallel_size=2`
> gcs_rpc_client.h:552: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. 

And my hardware is a single machine with two A10 cards.
Can someone help me plz?

**Comment by smallmocha** [comment]
I meet the same issue before，finally i found it because of load model in child thread，maybe you can avoid this when load model in main thread

**Comment by smallmocha** [comment]
not the same way to run，maybe you can execute ps  to check whether gcs_server process runing

**Comment by tsvisab** [comment]
If for some reason you're loading your model from a thread other than the main one,
initialize ray beforehand *in the main thread*:



`        ray.init(num_gpus=model_config.tensor_parallel_size)`


worked for me
