### ISSUE TITLE
Proposal: Add model registration to support proprietary models

### ISSUE THREAD

**Issue by wangkuiyi** [vllm-project/vllm#1467]
So far, users have had to fork and maintain an internal version of vLLM in order to run a proprietary model with it.

Is it a good idea adding model registration, similar to `AutoModelForCausalLM.register(config_class, model_class)` in [Hugging Face Transformer](https://huggingface.co/docs/transformers/v4.34.1/en/quicktour#automodel)?

In this way, users could define their models in their private Git repos. For example, in https://github.com/my/private_model.git, I could have `mymodel.py`:

```python
import torch
import vllm

# Register MyModel to vllm.model_executor.model_loader._MODEL_REGISTRY
vllm.register(model_class=MyModel)

class MyModel(torch.nn.Module):
    def __init__(self, config: MyModelConfig) -> None:
        super().__init__()
        vocab_size = ((config.vocab_size + 63) // 64) * 64
        self.embed_tokens = vllm.parallel_utils.layers.VocabParallelEmbedding(
            vocab_size,
            config.hidden_size,
        )
        self.norm = vllm.layers.RMSNorm(config.hidden_size, eps=config.rms_norm_eps)
```

Then, I would run a vLLM service with the following command to serve a pre-trained `MyModel`:

```shell
pip install -e ~/w/mymodel
python -m vllm.entrypoints.api_server -m mymodel
```

Or,

```shell
python -m vllm.entrypoint.api_server -e ~/w/mymodel/mymodel.py
```

**Comment by hmellor** [comment]
@WoosukKwon @simon-mo @zhuohan123 is this a feature you'd like to see implemented?
