### ISSUE TITLE
Error gpu memory utilization with awq model when tp>1.

### ISSUE THREAD

**Issue by gesanqiu** [vllm-project/vllm#1472]
Right now vLLM will allocate 90% gpu memory for each accessible gpu card, but when launch server with awq model, it will became a unknow behavior. I run awq format codellama-13b(6.8GB) model on L4(24GB) and A40(48GB), and the gpu memory utilization is different, and `----gpu-memory-utilization` and `--swap-space` parameter is invalid in this situation.
On L4(24GB) it will pre-allocate ~10GB gpu memory:
![image](https://github.com/vllm-project/vllm/assets/37237570/75feecb3-c5fd-44da-8b3b-145c33e56932)
And when I send a request, it will increase ~2GB, the gpu memory usage come to ~12GB:
![image](https://github.com/vllm-project/vllm/assets/37237570/1792ef25-5498-4407-be7a-b201a7d5b92c)

On A40(48GB) it will pre-allocate ~31GB gpu memory:
![image](https://github.com/vllm-project/vllm/assets/37237570/7466b9ea-8bb9-4ef4-bac9-045259bbba60)
And when I send the same request that I sent to L4, it will also increase ~2GB, the gpu memory usage come to ~33GB:
![image](https://github.com/vllm-project/vllm/assets/37237570/61b39fbf-cb5c-4ced-ba56-6128d3c4acdc)

The only pattern I found in the phenomenon is they both allocate 1946MB gpu memory after I send a request to the server. In general, vLLM won't allocate memory after the engine launched, it's wired.
Due to lack of gpu memory, this will cause two problem:
1. Only can process limited sequences in each iteration, on L4 the `llm_engine` will only have one sequnce in the running queue.
![image](https://github.com/vllm-project/vllm/assets/37237570/b9c41a00-06ba-4c84-a24d-688453f9fa8a)
2. When the `max_new_token` is large, due to the full use of KV cache, `llm_engine` will run into stuck , also see #1206 
![image](https://github.com/vllm-project/vllm/assets/37237570/f299895c-82b3-4e11-bfa4-95df4f257f80)

But can't reproduce this on llama-2-13b-hf awq model.
@WoosukKwon @zhuohan123 Do you have any ideads about this issue?

**Comment by gesanqiu** [comment]
After tracing the whole gpu memory allocate flow, I found that vLLM will do a forward before init cache. Due to lack of truely INT4 kernel, vLLM will de-quantize the weight to FP16, so the peak gpu memory is large than it intend to be, which devided the cache size: `num_gpu_blocks = int((total_gpu_memory * gpu_memory_utilization - peak_memory) // cache_block_size)`.
Codellama-13b has 16K context length, awq format model will cost ~10GB extra gpu memory to executing one forward. So on L4(24GB), only 23*0.9 - 8 - 10 = ~2.7GB gpu memory can use for `CacheEngine`.
Right now it's better to calculate memory cost in FP16 format when deploy quantized mdel.
But vLLM will stuck when KVCache is full loaded, still need a solution.

**Comment by LovesportsMcDull** [comment]
How do you calculate that peak_memory is 8?

**Comment by roelschr** [comment]
Hi @gesanqiu, there seems to be a big difference between `vllm`'s quant cuda kernels and `llm-awq`'s [one](https://github.com/mit-han-lab/llm-awq/blob/153272e44818dc80c60604097162a219561106a1/awq/kernels/csrc/quantization/gemm_cuda_gen.cu#L158), especially around dequantization. Also, a few users reported that `FastChat` AWQ implementation works just fine (they use `tinychat`, which uses `llm-awq` to load the quantized models). I have no experience with kernels, but could this be fixed by using `llm-awq` kernels? Or even let `vllm` use `tinychat` to load quantized AWQ models?

**Comment by gesanqiu** [comment]
After more test, I found that awq model still has some error when using tp > 1. When I setup the tp=2, it will cause OOM error when concurrcy is big enough, it seems the `--max-num-batched-token` or `init_cache()` didn't work well in tp>1 situation.

**Comment by gesanqiu** [comment]
> Hi @gesanqiu, there seems to be a big difference between `vllm`'s quant cuda kernels and `llm-awq`'s [one](https://github.com/mit-han-lab/llm-awq/blob/153272e44818dc80c60604097162a219561106a1/awq/kernels/csrc/quantization/gemm_cuda_gen.cu#L158), especially around dequantization. Also, a few users reported that `FastChat` AWQ implementation works just fine (they use `tinychat`, which uses `llm-awq` to load the quantized models). I have no experience with kernels, but could this be fixed by using `llm-awq` kernels? Or even let `vllm` use `tinychat` to load quantized AWQ models?

Sorry I'm also not a CUDA expert, can't help with you idea.

**Comment by chi2liu** [comment]
At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.
