### ISSUE TITLE
OpenAI API model_check should be optional or removed

### ISSUE THREAD

**Issue by samos123** [vllm-project/vllm#1478]
There doesn't seem to be a good reason to check the model name since a single vLLM only serves one model. Instead I would prefer to either have the `check_model` function [1] removed or be able to turn the check off through configuration.

[1] https://github.com/vllm-project/vllm/blob/v0.2.1/vllm/entrypoints/openai/api_server.py#L62

**Comment by AaronFriel** [comment]
@hmellor Why was this closed as not planned - it looks like there's a commit that implements this on the fork above, it seems easy to pull in?

**Comment by samos123** [comment]
it really makes the usage of vLLM inside [Lingo](https://github.com/substratusai/lingo) a bit clunky. I now have to pass served model name to each vLLM instance even though it serves no purpose...

**Comment by hmellor** [comment]
It was closed as stale (which is only if the reasons that GitHub confusingly bundles under "not planned").

Based on your discussion on the PR, it sounds like being able to serve the same model under multiple names would help your situation. Does https://github.com/vllm-project/vllm/pull/2894 help at all?

**Comment by AaronFriel** [comment]
Yeah, it should - the description and use case in #2894 is accurate - we want to serve *a* model, and be able to upgrade it over time.

**Comment by hmellor** [comment]
Great, feel free to show your support for the PR over there so that we can get it merged sooner!
