### ISSUE TITLE
CUDA OOM when inference using python script but works fine when using online inference command

### ISSUE THREAD

**Issue by chaunceyliu30** [vllm-project/vllm#1480]
I bumped into a problem when using vllm to do llm generation. I use the same model Qwen-7B for offline inference and online inference, when using offline inference I followed the instruction in the documentation but I got cuda out of memory issue. However, when I use the same model to initialize a service and try using online inference to do the same generation task, it works fine. In my situation, I need to do batch offline inference, can you give me some advice on how to avoid the CUDA OOM problem? THANK YOU!

**Comment by yang-zhikai** [comment]
mark

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
