### ISSUE TITLE
Isn't vllm compatible with other web frameworks?

### ISSUE THREAD

**Issue by ming-shy** [vllm-project/vllm#1487]
**_Dear author,
At the bottom I used the flask framework to build the web service, but there were some strange phenomena (below). Isn't vllm compatible with other web frameworks?_**

**phenomena** :
①The first request to enter can be reasoned normally;
②Second request, vllm directly calls abort_request;
③ After subsequent requests are Received, vllm prints a log saying Received request, but no more inference is performed.

**MY ENV:
flask
rtx4090
vllm0.2.0
python3.8
cuda11.8**

**Comment by aixiaodewugege** [comment]
same question

**Comment by ming-shy** [comment]
> same question

flask is acceptable for vllm0.1.4, but not for later versions. The core code of vllm has changed significantly since 0.1.4, so later versions may not be compatible with other web synchronization frameworks.

**Comment by aixiaodewugege** [comment]
> > same question
> 
> flask is acceptable for vllm0.1.4, but not for later versions. The core code of vllm has changed significantly since 0.1.4, so later versions may not be compatible with other web synchronization frameworks.

Thank you! Do you think it's possible to use Flask to call the VLLM API?

**Comment by ming-shy** [comment]
> > > same question
> > 
> > 
> > flask is acceptable for vllm0.1.4, but not for later versions. The core code of vllm has changed significantly since 0.1.4, so later versions may not be compatible with other web synchronization frameworks.
> 
> Thank you! Do you think it's possible to use Flask to call the VLLM API?

vllm returns asynchronous iterators, and even if you call vllm's api, what you receive is still an asynchronous iterator, and you need flask to process it. So I personally don't think that's feasible.

**Comment by aixiaodewugege** [comment]
Understood. Beyond just using its API, is there another way to integrate vllm? I aim to deploy it on my server and provide services via an iOS app.

**Comment by mengban** [comment]
> Understood. Beyond just using its API, is there another way to integrate vllm? I aim to deploy it on my server and provide services via an iOS app.

of course you can.  you can refer:
`https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py`

**Comment by gesanqiu** [comment]
As far as I know, FastChat is compatible with OpenAI API.
