### ISSUE TITLE
vLLM hangs after 10 minutes without any error message

### ISSUE THREAD

**Issue by xingyaoww** [vllm-project/vllm#1492]
Hi vLLM team,

I started a vLLM server (OpenAI API) to serve LLaMA-7b and had multiple processes sending requests to it simultaneously to saturate the GPU (I tried both 1xA100 40G and 1xA40 40G).

However, after 5-10 minutes, the vLLM server will hang there (no more new requests get handled) forever without error messages. Most recent stats show that "INFO 10-27 20:44:35 llm_engine.py:624] Avg prompt throughput: 642.0 tokens/s, Avg generation throughput: 61.0 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 20 reqs, GPU KV cache u
sage: 98.7%, CPU KV cache usage: 0.0%".

After hanging happens, `v1/models` endpoint still works (give correct responses), but chat completion and completion requests will receive `openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500).` and there were NO error messages from the vLLM side.

Any idea what might cause this? Is it because there are too many requests to be handled?

Thanks!

**Comment by xingyaoww** [comment]
Looks like it might be a GPU compute issue -- I scale to 4xA100 40G to handle the same amount of requests, and there are no more errors after 30 minutes. Is there a way to add a warning/error messages in vLLM to notify the user when this happens (e.g., the queue for requests is full)?

**Comment by JGSweets** [comment]
@xingyaoww did you solve this issue? I'm seeing this resurfacing with my own tests. Thanks!

**Comment by ZeanNi** [comment]
> [@xingyaoww](https://github.com/xingyaoww) did you solve this issue? I'm seeing this resurfacing with my own tests. Thanks!

Hi did you solve this issue? my vLLM aslo hangs without any error message when I was using ChatOpenAI to parallel call

**Comment by ZeanNi** [comment]
> [@xingyaoww](https://github.com/xingyaoww) did you solve this issue? I'm seeing this resurfacing with my own tests. Thanks!

@JGSweets Hi did you solve this issue? my vLLM aslo hangs without any error message when I was using ChatOpenAI to parallel call

**Comment by shrijayan** [comment]
Same issue I am also facing. Not even able to cancel the process.

<img width="747" height="81" alt="Image" src="https://github.com/user-attachments/assets/5cf25c1d-242f-4cf1-add0-1fd9a025ba53" />

Memory utilization graph

<img width="459" height="141" alt="Image" src="https://github.com/user-attachments/assets/80d147c0-8898-4516-8366-609af48dfe8d" />

In between log was like

<img width="2486" height="647" alt="Image" src="https://github.com/user-attachments/assets/a9d59394-94f1-4983-82c2-3fe71cd0e397" />

**Comment by shrijayan** [comment]
I also saw this error message now

[rank1]:[W713 00:11:52.782973677 TCPStore.cpp:125] [c10d] recvValue failed on SocketImpl(fd=69, addr=[localhost]:37046, remote=[localhost]:54753): failed to recv, got 0 bytes
Exception raised from recvBytes at /pytorch/torch/csrc/distributed/c10d/Utils.hpp:678 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f3f62f1e5e8 in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x5ba8afe (0x7f3fb803cafe in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x5baae40 (0x7f3fb803ee40 in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x5bab74a (0x7f3fb803f74a in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)
frame #4: c10d::TCPStore::check(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) + 0x2a9 (0x7f3fb80391a9 in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libtorch_cpu.so)
frame #5: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x379 (0x7f3f63c99989 in /home/karrtik/projects/shrijayan/venv_vllm_uv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xdc253 (0x7f3f53fb3253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x94ac3 (0x7f3fd4e36ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0x126850 (0x7f3fd4ec8850 in /lib/x86_64-linux-gnu/libc.so.6)

[rank1]:[W713 00:11:52.787226570 ProcessGroupNCCL.cpp:1659] [PG ID 0 PG GUID 0 Rank 1] Failed to check the "should dump" flag on TCPStore, (maybe TCPStore server has shut down too early), with error: failed to recv, got 0 bytes

**Comment by shrijayan** [comment]
Is there any solution, I have tries till reinstalling the OS? Any solution
