### ISSUE TITLE
How to implement a disk cache? Or better ideas? 

### ISSUE THREAD

**Issue by benjamin-asdf** [vllm-project/vllm#1495]
I have a lot of large and similar prompt prefixes across requests.

As an optimization, I am toying with the idea to cache kv on disk and load the cache from disk depending on the prefix.

Any design inputs on how to go about doing this?

Open to any suggestions, maybe you have better ideas where to optimize.

**Comment by flexchar** [comment]
This feels beyond scope of the purpose of this server. I'd suggest looking in another Python packages for this. Personally I came across [Helicone](https://github.com/Helicone/helicone) which I'm trying right now, I use it to let my users rate suggestions. It also seems to offer caching and you can host yourself for complete control. [LLMonitor](https://llmonitor.com/helicone-vs-llmonitor) also seems promising. I'm also sure there's ton of packages out there. 

You could also host yourself an embedding model and cache based on the match. 
Hope that helps!

**Comment by benjamin-asdf** [comment]
Thanks for the input @flexchar

**Comment by hmellor** [comment]
Prefix caching has been added in #2614
