### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by SinclairCoder** [vllm-project/vllm#1498]
How to install in ubuntu 22.04, cuda 11.8, torch 2.1.0+cu118 python 3.10? 

I found that `pip install vllm` will re-install torch-2.01 and update cuda version. How to install vllm, but based on my cuda env? thanks in advance!!!

**Comment by shaily99** [comment]
Having similar issues with vllm; it says it fails with exit code -9 and I don't know what that means

**Comment by nigue3025** [comment]
same problem here

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
