### ISSUE TITLE
Run vllm, the server stopped automatically.

### ISSUE THREAD

**Issue by yixuantt** [vllm-project/vllm#1499]
Install vllm normally. After running, the server will be shut down and rebooted without any error message. Two servers have been replaced, and both have the same problem.

**Comment by yixuantt** [comment]
```
python3 -m vllm.entrypoints.openai.api_server \
    	--model "place hold"  \
	--swap-space 16 \
	--quantization awq \
	--tensor-parallel-size 4 \
	--max-model-len 8192 \
	--block-size  8 \
	--gpu-memory-utilization 0.6 \
	--dtype float16 \
	--max-num-batched-tokens 8192 
```

**Comment by mridulBanik112** [comment]
I am also getting this issue when --tensor-parallel-size 4 is given. Any leads?

**Comment by Thatwho** [comment]
I got the same problem，the server has rebooted without any message.
