### ISSUE TITLE
Switch the linter and formatter to `ruff`

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#1511]
This issue proposes switching the linter (pylint) and formatter (yapf) to ruff https://github.com/astral-sh/ruff.

The benefit of `ruff` are speed and wide adoption. `ruff` is 100x faster than both of them. `ruff` is used by almost every modern Python packages. This means contributors are more likely to use ruff than pylint + yapf combo.

The further downside of `yapf` includes the limited 80 characters formatting and non-deterministic formatting. 

Once the formatting PR gets merged, I will send the a message, including scripts and patch to help rebasing on-going PRs.

**Comment by simon-mo** [comment]
Related we should also use `clang-format` for C++ code

**Comment by zhuohan123** [comment]
BTW I do think the 80-character limit is good because this can make two-column code review look nice on a normal monitor.

Also, does ruff follow [Google Python style guide](https://google.github.io/styleguide/pyguide.html)?

**Comment by simon-mo** [comment]
Black style keep the code around 80 characters but it is not as strict
as yapf. 

ruff's style is a superset of all pylint's style, pylint styles cover
most of Google's style.
