### ISSUE TITLE
VLLM     two GPUs  Qwen-7B-Chat   consumes more VRAM

### ISSUE THREAD

**Issue by shujun1992** [vllm-project/vllm#1512]
I'm using the Qwen-7B-Chat  model on a single A10 GPU, and it's consuming 18506MB . 

When using two A10 GPUs, each GPU also consumes 18506MB. Is there something wrong ?

**Comment by sprezz-arthur** [comment]
Hello! I think this is one of the most common misconceptions in VLLM usage.
There's a parameter named `gpu_memory_utilization` on the VLLM on the LLM class that defaults to `0.9`, this means it will use 90% (and **not** up to 90%) of your available GPU memory, increasing the KV Cache as much as it can.

There are other issues dealing with this: https://github.com/vllm-project/vllm/issues/550

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
