### ISSUE TITLE
Does the API server automatically batch user requests together?

### ISSUE THREAD

**Issue by aixiaodewugege** [vllm-project/vllm#1515]
I noticed that the API server example does not provide a place to set the batch size, so I'm a bit confused.

**Comment by simon-mo** [comment]
Yes. The parameter is `--max-num-batched-tokens`. This is the effective max batch size. 

https://github.com/vllm-project/vllm/blob/7013a80170146ca4f7fd9539e4d7fd852d4718b6/vllm/engine/arg_utils.py#L151-L155

**Comment by liyucheng09** [comment]
@simon-mo May I ask for a bit clarificaiton about `--max-num-batched-tokens`. Does it mean the max_length of a single prompt cannot exceed `--max-num-batched-tokens`. Say if we have 2048 for `--max-num-batched-tokens`, does it mean we cannot send prompt longer than 2048?
