### ISSUE TITLE
Can vllm handle two prompts at the same time?

### ISSUE THREAD

**Issue by zozoteacher** [vllm-project/vllm#1516]
I have multiple problems, can they be dealt with at the same time?

**Comment by zozoteacher** [comment]
I have two gpu, preferably two gpu reasoning different problems

**Comment by simon-mo** [comment]
vLLM is an inference engine for LLMs. It can handle multiple request at the same time. Each request can be containing different prompt. Here's an example running four prompts at the same time:

https://github.com/vllm-project/vllm/blob/main/examples/offline_inference.py


It will also be able to run on multiple GPUs out of the box.

**Comment by Hamza-Chekireb** [comment]
Can vLLM handle overlapping requests? For example, if two requests each take 10 seconds to generate, and the first request arrives, followed by the second request 2 seconds later, will the second request be processed concurrently or wait until the first one finishes ?
