### ISSUE TITLE
Error:  When using OpenAI-Compatible Server, the server is available but cannot be accessed from the same terminal.

### ISSUE THREAD

**Issue by LuristheSun** [vllm-project/vllm#1519]
I'm using this perfect framework to build up an on-air api server for my local LLM. Specifically, I had run this command in my linux terminal:
`python -m vllm.entrypoints.openai.api_server    --model /home/XXX/baichuan2    --trust-remote-code    --tensor-parallel-size 1    --host 10.201.1.181    --port 8000`
Note that /baichuan2 is a directory containing the fine-tuned model derived from baichuan-inc/Baichuan2-13B-Base.

And I get:
`INFO:     Started server process [448902]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://10.201.1.181:8000 (Press CTRL+C to quit)`

To test whether the server is ready or not, I used `telnet 10.201.1.181 8000` in another shell, which returned 
`Trying 10.201.1.181...
Connected to 10.201.1.181.
Escape character is '^]'.`
So I suppose the server is running properly.

But when I attempt to call this server via python scripts as documented :
`import openai

openai.api_key = "0.0.0.0"

openai.api_base = 'http://10.201.1.181:8000/v1'

response = openai.Completion.create(model='/home/XXX/baichuan2', prompt=prompt, temperature = 0.8, do_sample = True, max_tokens = 512)
`

The program will report errors after a long-time pausing with a html code in the end indicating 502 error: 

`Traceback (most recent call last):
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/XXX/ChatTU/main.py", line 31, in <module>
    main(test_mode = test_mode, fixed_label = args.fixed_label, query = query, ip = ip)
  File "/home/XXX/ChatTU/main.py", line 17, in main
    Conversation_Chain(test_mode = test_mode, fixed_label = fixed_label,  query = query, ip = ip)
  File "/home/XXX/ChatTU/SourceCode/Customer_Service.py", line 164, in Conversation_Chain
    response = local_llm.chat(args = args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/ChatTU/LLM/Local_LLM.py", line 172, in chat
    response = openai.Completion.create(model='/home/XXX/baichuan2', prompt=prompt, temperature = 0.8, do_sample = True, max_tokens = 512)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/XXX/anaconda3/lib/python3.11/site-packages/openai/api_requestor.py", line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"`

(I didn't post that html code since it's way too long.)

Besides, my LLM is supported by this framework since 
`from vllm import LLM

llm = LLM(model='/home/luyiran/baichuan2', trust_remote_code = True)  # Name or path of your model
output = llm.generate("Hello, my name is")
print(output)`
works fine.

I'm quiet confused about this problem. But several days earlier I had successfully depolyed an api server for the same LLM on a different machine, using the exact same method like this one, with the only difference being the host. I'm wondering what's wrong with my code and will be extremely grateful if anyone would like to offer your invaluable assistance.

**Comment by simon-mo** [comment]
> openai.error.APIError: HTTP code 502 from API (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "[http://www.w3.org/TR/html4/strict.dtd"`](http://www.w3.org/TR/html4/strict.dtd%22%60)

This looks like you have something already running on port 8000. You can do it by checking `curl localhost:8000` without vLLM running. One common case is HTTP proxy running on port 8000. 

Feel free to re-open the issue if this is not resolved!

**Comment by LuristheSun** [comment]
> > openai.error.APIError: HTTP code 502 from API (<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "[http://www.w3.org/TR/html4/strict.dtd"`](http://www.w3.org/TR/html4/strict.dtd%22%60)
> 
> This looks like you have something already running on port 8000. You can do it by checking `curl localhost:8000` without vLLM running. One common case is HTTP proxy running on port 8000.
> 
> Feel free to re-open the issue if this is not resolved!

Thank you very much for your helpful response! Although there's nothing was running on port 8000, your reply really inspired me. I managed to solve this problem via closing the proxy in my terminal. Once again, thank you!

**Comment by fengshansi** [comment]
Same. I spend several hours to solve this problem. Why set os.environ["http_proxy"]  can cause 502. Even the port of http_proxy is not same with the vllm server.

**Comment by coranholmes** [comment]
Met the same issue, solved by turning off my proxy.

**Comment by fengshansi** [comment]
I want to know why this problem occurs.

**Comment by minhkids** [comment]
> Met the same issue, solved by unset "http_proxy"

work for me! 
add this and it should work
`os.environ['http_proxy'] = ''`
`os.environ['https_proxy'] = ''`

**Comment by halfrot** [comment]
Also curious why this would happen? Took me hours to debug...
