### ISSUE TITLE
How to use vllm to calculate the number of tokens

### ISSUE THREAD

**Issue by zozoteacher** [vllm-project/vllm#1521]
How to use vllm to calculate the number of tokens

**Comment by simon-mo** [comment]
Can you elaborate? It is the job of the tokenizer. You can use https://github.com/openai/tiktoken or the corresponding Huggingface tokenizer to compute it. vLLM doesn't expose public API to perform it. 

I hope this can solve the issue. Feel free to re-open the issue if this is not resolved!

**Comment by ravipudi** [comment]
Say we host Llama3 on vllm for inferencing and we have a need to check the number of tokens as computed by the Llama3 tokenizer for a given prompt (to indicate to the user on the ui) - is there a way in vllm to expose this functionality as an end point? 
@simon-mo

**Comment by edwardzjl** [comment]
@ravipudi I think the `/tokenize` endpoint meets your deed.

See https://github.com/vllm-project/vllm/blob/214efc2c3cb568e8eb3f7d234f3bd8f5bbe24795/vllm/entrypoints/openai/api_server.py#L305

**Comment by gaardhus** [comment]
> [@ravipudi](https://github.com/ravipudi) I think the `/tokenize` endpoint meets your deed.
> 
> See
> 
> [vllm/vllm/entrypoints/openai/api_server.py](https://github.com/vllm-project/vllm/blob/214efc2c3cb568e8eb3f7d234f3bd8f5bbe24795/vllm/entrypoints/openai/api_server.py#L305)
> 
> Line 305 in [214efc2](/vllm-project/vllm/commit/214efc2c3cb568e8eb3f7d234f3bd8f5bbe24795)
>  async def tokenize(request: TokenizeRequest, raw_request: Request):

i.e.

```bash
curl -X 'POST' "http://localhost:8000/tokenize" \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '{"prompt":"hello"}'
```

**Comment by zengqingfu1442** [comment]
How about using the token usage info to calculate the number of tokens? The usage info should be like:
```
"usage": {
    "prompt_tokens": 19,
    "completion_tokens": 10,
    "total_tokens": 29,
    "prompt_tokens_details": {
      "cached_tokens": 0,
      "audio_tokens": 0
    },
    "completion_tokens_details": {
      "reasoning_tokens": 0,
      "audio_tokens": 0,
      "accepted_prediction_tokens": 0,
      "rejected_prediction_tokens": 0
    }
  },
```
