### ISSUE TITLE
ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm'

### ISSUE THREAD

**Issue by Edisonwei54** [vllm-project/vllm#1522]
#    Here's my test code
'
from vllm import LLM, SamplingParams

prompts = [
    "Tell me about AI",
    "Write a story about llamas",
    "What is 291 - 150?",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
]
prompt_template=f'''System: A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.
Human: {prompt}
Assistant:
'''

prompts = [prompt_template.format(prompt=prompt) for prompt in prompts]

sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="TheBloke/AquilaChat2-34B-16K-AWQ", quantization="awq", dtype="auto")

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
'

#    I tried to run and it returned this error for me
ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm' (most likely due to a circular import) (/home/ps/app/edison/vllm/vllm/__init__.py)

#    environment
I followed the docs exactly

**Comment by simon-mo** [comment]
can you paste the full stacktrace? Additionally, does your current working directory contains files or folders named `vllm` or `cuda_utils`? This error is most likely that there are files with name conflict.

**Comment by Edisonwei54** [comment]
> can you paste the full stacktrace? Additionally, does your current working directory contains files or folders named `vllm` or `cuda_utils`? This error is most likely that there are files with name conflict.

Thank you very much for your answer. I can successfully run the code by placing it outside the file.

**Comment by Rahmat711** [comment]
can any please help @Edisonwei54 or @simon-mo i tired placing it outside the vllm folder and running but still no luck. need help.
