### ISSUE TITLE
[Bug] prompt_logprobs = 1  OOM problem

### ISSUE THREAD

**Issue by shunxing1234** [vllm-project/vllm#1532]
When I set prompt_logprobs = 1, if the input is excessively long (exceeding 900 tokens), it results in an out-of-memory (OOM) error.

Here are some details.
![image](https://github.com/vllm-project/vllm/assets/33774367/f967c115-bb79-43a6-a66a-309b3431990f)

model: BAAI/AquiilaChat2-34B
eva: 2* A100 40G

**Comment by Shuigs18** [comment]
gpu_memory_utilization 参数调低一点就行了

**Comment by shunxing1234** [comment]
> gpu_memory_utilization参数调低一点就行了

我调低了一些 还是会有oom的情况

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by DarkLight1337** [comment]
Re-opening this as it can be repro'd by #5067.
