### ISSUE TITLE
 Is there a way to avoid inference when enabling prompt_logprobs to save on runtime?

### ISSUE THREAD

**Issue by RanchiZhao** [vllm-project/vllm#1535]
as title

**Comment by RanchiZhao** [comment]
because we want to use vllm just doing some PPL eval tasks

**Comment by simon-mo** [comment]
To compute prompt_logprobs, vLLM still need to run one forward pass. I think you can just set the maximal generated token to be 1?

**Comment by RanchiZhao** [comment]
> To compute prompt_logprobs, vLLM still need to run one forward pass. I think you can just set the maximal generated token to be 1?

that is indeed what i do now, thanks for your answer!
