### ISSUE TITLE
Question: How does the Llama engine generate multiple choices?

### ISSUE THREAD

**Issue by EricLBuehler** [vllm-project/vllm#1537]
Hello everybody,

Inspired by this project, I am working on [`candle_vllm`](https://github.com/EricLBuehler/candle-vllm) for the [`candle`](https://github.com/huggingface/candle/tree/main) framework. I am working on adding a Llama engine first, but cannot seem to find where it is implemented in VLLM?

Specifically, I see below that only the final output will be returned from the model:
> https://github.com/vllm-project/vllm/blob/5687d584fe4825d59a6fd9ecc5840e1df04e380f/vllm/entrypoints/openai/api_server.py#L308

Am I mistaken? If so, how does the Llama engine generate multiple "choices"?

Thanks!

**Comment by viktor-ferenczi** [comment]
If you want to see multiple generations, then use an `n` value higher than 1 to generate multiple outputs.

Alternative is to use beam search, which provides a single result, but internally evaluates branches of possibilities.

**Comment by EricLBuehler** [comment]
Okay, thanks.

Candle does not provide these features as an API, so I would need to implement beam search, and run the model `n` times manually. 

Can you confirm that vllm internally either:
- Runs the model `n` times if the model is not using beam search.

or

- Uses beam search to find the best output.

During a chat completion API call?
