### ISSUE TITLE
ValueError: Quantization is not supported for <class 'vllm.model_executor.models.aquila.AquilaForCausalLM'>.

### ISSUE THREAD

**Issue by Edisonwei54** [vllm-project/vllm#1538]
# I tried using the following code to test the AquilaChat2-34B-16K-AWQ model launched by vllm, but it failed.
’‘’
from vllm import LLM, SamplingParams

prompts = [
    "Tell me about AI",
    "Write a story about llamas",
    "What is 291 - 150?",
    "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
]
prompt_template=f'''System: A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.
Human: {prompts}
Assistant:
'''

prompts = [prompt_template.format(prompt=prompt) for prompt in prompts]

sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="TheBloke/AquilaChat2-34B-16K-AWQ", quantization="awq", dtype="auto", trust_remote_code=True)

outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
‘’‘

# My system environment was built with reference to the official documentation of vllm.

**Comment by gesanqiu** [comment]
awq only support llama-2 model right now

**Comment by liyang79** [comment]
Encountered the same problem. Is there any plan to support AWQ for AquilaChat2 models?

**Comment by lonngxiang** [comment]
same error


run：AquilaChat2-7b
![image](https://github.com/vllm-project/vllm/assets/40717349/014f9179-f582-4a81-bbb6-ef77fcb9a3d7)

**Comment by WoosukKwon** [comment]
Hi @Edisonwei54 @liyang79 @lonngxiang, this iss fixed in the new version (v0.2.2), which was just released. Please try again with the new release and let us know if the error persists.

**Comment by lonngxiang** [comment]
> Hi @Edisonwei54 @liyang79 @lonngxiang, this iss fixed in the new version (v0.2.2), which was just released. Please try again with the new release and let us know if the error persists.
nice job！！！

**Comment by liyang79** [comment]
Cool! It worked on v0.2.2.

**Comment by lonngxiang** [comment]
> Cool! It worked on v0.2.2.

yes，but i ues api request not success

**Comment by liyang79** [comment]
> > Cool! It worked on v0.2.2.
> 
> yes，but i ues api request not success #1714 [https://github.com/vllm-project/vllm/pull/1714](url)
> 
> ![image](https://user-images.githubusercontent.com/40717349/284139479-e4a930c0-aa0f-4473-b1b8-3e0c9cfb2aa6.png)

I didn't test vllm openai-compatible server but was able to serve AquilaChat2-34B-16K-AWQ model with fastchat vllm_worker. I am using langchain on the client side.

**Comment by lonngxiang** [comment]
> > > Cool! It worked on v0.2.2.
> > 
> > 
> > yes，but i ues api request not success #1714 [https://github.com/vllm-project/vllm/pull/1714](url)
> > ![image](https://user-images.githubusercontent.com/40717349/284139479-e4a930c0-aa0f-4473-b1b8-3e0c9cfb2aa6.png)
> 
> I didn't test vllm openai-compatible server but was able to serve AquilaChat2-34B-16K-AWQ model with fastchat vllm_worker. I am using langchain on the client side.



Can you share how  fastchat vllm_worker commands use awq？

**Comment by liyang79** [comment]
> > > > Cool! It worked on v0.2.2.
> > > 
> > > 
> > > yes，but i ues api request not success #1714 [https://github.com/vllm-project/vllm/pull/1714](url)
> > > ![image](https://user-images.githubusercontent.com/40717349/284139479-e4a930c0-aa0f-4473-b1b8-3e0c9cfb2aa6.png)
> > 
> > 
> > I didn't test vllm openai-compatible server but was able to serve AquilaChat2-34B-16K-AWQ model with fastchat vllm_worker. I am using langchain on the client side.
> 
> Can you share how fastchat vllm_worker commands use awq？

```
python -m fastchat.serve.vllm_worker \
  --model-names "gpt-3.5-turbo,text-davinci-003,text-embedding-ada-002" \
  --model-path ./models/TheBloke/AquilaChat2-34B-16K-AWQ \
  --quantization awq \
  --num-gpus 2 \
  --trust-remote-code
```
