### ISSUE TITLE
Feature request: Controlling `config.json` of HF's models

### ISSUE THREAD

**Issue by keyboardAnt** [vllm-project/vllm#1542]
Thanks for this great project!

A quick feature request: [When loading models from the HuggingFace Hub](https://github.com/vllm-project/vllm/blob/7e90a2d11785b4cba5172f13178adb6d194a867f/vllm/config.py#L79), allow providing custom values to overwrite the default `config.json`. For example, change [the value of `max_position_embeddings` from `32768`](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1/blob/7ad5799710574ba1c1d953eba3077af582f3a773/config.json#L11) to `100000`, to allow longer prompts.

**Comment by Aakash-kaushik** [comment]
hey, any workarounds or development on this?

**Comment by AkshatGiri** [comment]
Also would be super useful for models that don't provide a config.json.

**Comment by Aakash-kaushik** [comment]
Being worked on in #2547
