### ISSUE TITLE
AWQ quantization does not quantize model weights during inference

### ISSUE THREAD

**Issue by DAIZHENWEI** [vllm-project/vllm#1544]
I am trying to use the AWQ quantization to load a quantized model. However, during inference time, the model weight is still mapped to float16 and int32. In `./vllm/engine/arg_utils.py`, we cannot set the `dtype` to int4. And in `awq.py`, `get_supported_act_dtypes() `only supports `torch.half`.

Any plan to fix this issue?

**Comment by gesanqiu** [comment]
Right now there aren't INT4 cuda kernels, and not every Nvidia GPU support INT4 computing.

**Comment by WoosukKwon** [comment]
Hi @DAIZHENWEI, AWQ (as well as GPTQ) is a weight-only quantization method, which dequantizes the weights to FP16/BF16 on the fly during matmul. You need to use a different quantization method to actually compute the operation in INT4. Unfortunately, none of the quantization method in vLLM supports this. And to the best of my knowledge, quantizing the activation beyond 8 bits significantly hurts the output quality for now.
