### ISSUE TITLE
how to use quantization squeezellm with vllm

### ISSUE THREAD

**Issue by dengzheng-cloud** [vllm-project/vllm#1547]
already use https://github.com/SqueezeAILab/SqueezeLLM/tree/main/quantization to quantize my sft model, and get a packed model.
try to run squeezellm quantized model in vllm 0.2.1 with script benchmarks/benchmark_latency.py
shell is 
CUDA_VISIBLE_DEVICES=0 python benchmark_latency.py --model [fold contain packd pt] --tokenizer [model path] --quantization squeezellm --batch-size 128
and get error log 
File "/vllm/vllm/model_executor/weight_utils.py", line 107, in get_quant_config
    raise ValueError(f"Cannot find the config file for {quantization}")  
ValueError: Cannot find the config file for squeezellm

after run with pdb vllm didn't find, while during quantization, squeezellm tutorial [https://github.com/SqueezeAILab/SqueezeLLM/tree/main/quantization] didn't output a quant_config.json.
my issue is how to get that quant_config.json file. thx!

**Comment by dengzheng-cloud** [comment]
for people who have met this issue, here is a backup solution
download quant_config.json from https://huggingface.co/squeeze-ai-lab/sq-llama-2-7b-w4-s0/blob/main/quant_config.json
if anyone know how to generate a config json, please comment, thank you.

**Comment by WoosukKwon** [comment]
Hi @dengzheng-cloud, thanks for letting us know the issue. Please add `quant_config.json` like [this](https://huggingface.co/squeeze-ai-lab/sq-llama-2-7b-w4-s0/blob/main/quant_config.json). I will ask the author of the repo to fix this.

**Comment by dengzheng-cloud** [comment]
> ~Hi @dengzheng-cloud, thanks for letting us know the issue. Please add `quant_config.json` like [this](https://huggingface.co/squeeze-ai-lab/sq-llama-2-7b-w4-s0/blob/main/quant_config.json). I will ask the author of the repo to fix this.~
> 
> Never mind, for some reason, your second reply wasn't visible in my browser.

thx anyway
after that, I tested squeezellm by using benchmark_latency.py, and there is a huge performance gap, squeezellm is extremely slow. There may be some issues with either my testing methodology or quantization.
