### ISSUE TITLE
[Benchmark] Bottleneck of vLLM as of 2023 11 02

### ISSUE THREAD

**Issue by tjtanaa** [vllm-project/vllm#1550]
I use ```py-spy``` to profile the pid of process when running the `benchmark/benchmark_throughput.py` on 4 GPUs with llama-2-70b-chat model.

The first most time spent on ```torch.repeat_interleave``` which lies in the ```multi_query_kv_attention``` as discuss in issue  https://github.com/pytorch/pytorch/issues/31980.

The following 4 graphs shows the function call duration on 4 GPUs.

![profile_70b_0](https://github.com/vllm-project/vllm/assets/29171856/7c7b4101-d10d-43d6-8f7a-e6937eb8029b)
![profile_70b_1](https://github.com/vllm-project/vllm/assets/29171856/824c8515-a9a6-427c-ab64-87fb328af293)
![profile_70b_2](https://github.com/vllm-project/vllm/assets/29171856/cd0d8c57-acac-457f-a7d6-d0cfe0141871)
![profile_70b_3](https://github.com/vllm-project/vllm/assets/29171856/2e336059-a690-4595-a947-a3ba4c5fba8c)

The second bottleneck is the ```_prune_hidden_state``` function.

Hope that this could provide some insights to move forward in optimizing the framework.

[Update]
There seems to have some PR going on in pytorch (https://github.com/pytorch/pytorch/pull/51869) but it seems that it was not merged.

**Comment by simon-mo** [comment]
Great work! Thank you

**Comment by zhuohan123** [comment]
The GPU and CPU execution are asynchronous and I believe `_prune_hidden_state` is the synchronization point (as discussed in https://github.com/vllm-project/vllm/pull/707). Can you try to profile with `CUDA_LAUNCH_BLOCKING=1` and see whether these two functions are still the bottleneck?
