### ISSUE TITLE
Call for Contribution: Support ChatGLM3

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#1552]
Hi vLLM community,

We are aware of the enthusiasm ([https://github.com/vllm-project/vllm/issues/247](https://github.com/vllm-project/vllm/issues/247) [https://github.com/vllm-project/vllm/issues/231](https://github.com/vllm-project/vllm/issues/231)) to add support for ChatGLM model. However, the team is currently overwhelmed by other higher priorities work like improving latency and enhance quantization.

Currently, there are total of five stale PRs, each in different states, none of them are mergable.
[https://github.com/vllm-project/vllm/pull/1477](https://github.com/vllm-project/vllm/pull/1477)
[https://github.com/vllm-project/vllm/pull/1261](https://github.com/vllm-project/vllm/pull/1261)
[https://github.com/vllm-project/vllm/pull/1109](https://github.com/vllm-project/vllm/pull/1109)
[https://github.com/vllm-project/vllm/pull/649](https://github.com/vllm-project/vllm/pull/649)
[https://github.com/vllm-project/vllm/pull/625](https://github.com/vllm-project/vllm/pull/625)

I believe we can directly support [https://github.com/THUDM/ChatGLM3](https://github.com/THUDM/ChatGLM3). We are looking for people who can help us take the model to completion. We will do our best in reviewing your PRs and support your contribution.

Contribution guide here: [https://vllm.readthedocs.io/en/latest/models/adding_model.html](https://vllm.readthedocs.io/en/latest/models/adding_model.html)

**Comment by felixdae** [comment]
now we have one more, could you please review it @simon-mo 
https://github.com/vllm-project/vllm/pull/1558

**Comment by simon-mo** [comment]
@felixdae thank you for that. The teams is taking a look at both https://github.com/vllm-project/vllm/pull/1558
and https://github.com/vllm-project/vllm/pull/1261

**Comment by simon-mo** [comment]
It is now supported via #1261
