### ISSUE TITLE
Guidance on how many requests can be processed at a time?

### ISSUE THREAD

**Issue by dvfabbri** [vllm-project/vllm#1555]
Hello - 

I am trying to understand how many requests can be processed in parallel with the llm_engine, and what keeps requests WAITING. I see various variables like "max_num_batched_tokens" and "max_num_seqs", but more details or documentation describing how this process occurs would be helpful. Moreover, how can we tune our system to do process more requests in parallel (e.g. use more GPUs if available, use smaller models, use smaller context windows, etc.)

**Comment by Sirri69** [comment]
Any updates on this?

We also need these numbers.

**Comment by Stealthwriter** [comment]
any updates? I want to know also. How many requests can be handled and if we can control it
