### ISSUE TITLE
Add support for LongLora

### ISSUE THREAD

**Issue by coranholmes** [vllm-project/vllm#1557]
I am using [LongLora](https://github.com/dvlab-research/LongLoRA) for inference. The model uses [short shift attention](https://github.com/dvlab-research/LongLoRA/blob/main/llama_attn_replace_sft.py). I am not sure whether vllm supports it? If no, is it possible to support it?

**Comment by tjtanaa** [comment]
![image](https://github.com/vllm-project/vllm/assets/29171856/17ac9c3d-fc21-4953-9dce-2e3006a07a50)
From
https://huggingface.co/Yukang/Llama-2-70b-chat-longlora-32k

It says that short shift attention is not needed during inference. Maybe you can try to load the model with vllm and test out directly?

**Comment by hmellor** [comment]
Closing because it appears LongLoRA isn't needed for inference.
