### ISSUE TITLE
Yarn-Mistral-7b-128k  set max_seq_len, CUDA OUT OF MEMORY....

### ISSUE THREAD

**Issue by NickyDark1** [vllm-project/vllm#1559]
Does it take up more than 40GB memory to be able to modify the length of the tokens before loading the model?

```Python
from vllm import LLM, SamplingParams#, set_tokenizer, get_tokenizer
import torch
import time

import gc
# max_seq_len=2028,
model= "NousResearch/Yarn-Mistral-7b-128k" 
llm = LLM(model=model,dtype="bfloat16", gpu_memory_utilization=.5,  tensor_parallel_size=1, quantization=None, seed=0,)

```

set max_seq_len how?

```
INFO 11-04 06:25:50 llm_engine.py:72] Initializing an LLM engine with config: model='NousResearch/Yarn-Mistral-7b-128k', tokenizer='NousResearch/Yarn-Mistral-7b-128k', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=524288, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
```

![image](https://github.com/vllm-project/vllm/assets/123802672/41b8b386-14b0-4a97-9b87-77351f2274b6)

**Comment by WoosukKwon** [comment]
Hi @NickyDark1, thanks for the question. You can set the maximum model length through `max_model_len` parameter.

**Comment by bonuschild** [comment]
> Hi @NickyDark1, thanks for the question. You can set the maximum model length through `max_model_len` parameter.

Why `--max_seq_len=524288` affects the memory usage? Which performance will this change affects on?

**Comment by bonuschild** [comment]
> Hi @NickyDark1, thanks for the question. You can set the maximum model length through `max_model_len` parameter.

And Why nobody calculate or tell the actual VRAM usage in advance if this `--max_seq_len` can greatly affect VRAM usage? I also occur serveral OOM maybe due to the same reason.

**Comment by WoosukKwon** [comment]
@bonuschild It's because vLLM pre-allocates the memory space of 1) intermediate activations, ephemeral tensors created and deleted during model forward pass (and depend on `max_model_len`), and 2) KV cache. If you set `max_model_len` small, vLLM will pre-allocate smaller space for intermediate activations and larger space for KV cache. This generally leads to higher throughput. However, vLLM will reject any request whose `prompt_len` + `max_tokens` is larger than `max_model_len`, so you need to consider the actual maximum length you need for your application.

If `max_model_len` is too large, as in the Mistral-128K model, it might cause OOM at initialization time. This is because vLLM memory profiler initially runs the model with a dummy input sequence of length `max_model_len`. If your GPU does not have enough memory to process the input sequence, it will cause OOM.

**Comment by bonuschild** [comment]
@WoosukKwon I also check https://github.com/vllm-project/vllm/issues/1267#issuecomment-1797144791, Thanks for explaining. Looking forward to the new version.

BTW, so how should I correctly use the AWQ quantized model published by @TheBloke? In his huggingface model homepage the recommend is the normal vllm usage like in this 33B model [deepseek-coder-33B-instruct-AWQ](https://huggingface.co/TheBloke/deepseek-coder-33B-instruct-AWQ):
```bash
python3 python -m vllm.entrypoints.api_server --model TheBloke/deepseek-coder-33B-instruct-AWQ --quantization awq
```
> maybe with handwriting mistake that appears repeated `python` calling.

So to calculate the exactly VRAM usage, I need at least:
- model filesize in GB unit
- model maximum sequence length in count unit

Is there other required variable, such as RAM, Disk? And how to calculate it? If I want the full capability of Mistral 7B 128K :)

**Comment by TheBloke** [comment]
Oops, that's a typo in my README! should say:
```
python3 -m vllm.entrypoints.api_server --model TheBloke/deepseek-coder-33B-instruct-AWQ --quantization awq
```

I'll fix that in my READMEs shortly.

**Comment by bonuschild** [comment]
@TheBloke Ah you're welcome~

**Comment by aemonge** [comment]
How can we change the max_model_len throught the langchain python include?

```
from langchain_community.llms import VLLM

VLLM(
            model=model,
            download_dir=VLLM_DOWNLOAD_PATH,
            gpu_memory_utilization=0.95,
            max_seq_len=64,  # No changes reflected,
            max_model_len=64,  # No changes reflected,
            trust_remote_code=True,  # mandatory for hf models
            max_new_tokens=32,  # No changes reflected,
        )
        
```

**Comment by Jasonsey** [comment]
> How can we change the max_model_len throught the langchain python include?
> 
> ```
> from langchain_community.llms import VLLM
> 
> VLLM(
>             model=model,
>             download_dir=VLLM_DOWNLOAD_PATH,
>             gpu_memory_utilization=0.95,
>             max_seq_len=64,  # No changes reflected,
>             max_model_len=64,  # No changes reflected,
>             trust_remote_code=True,  # mandatory for hf models
>             max_new_tokens=32,  # No changes reflected,
>         )
>         
> ```

I have the same question

**Comment by ryj0902** [comment]
It works to me

```
from langchain_community.llms import VLLM

llm = VLLM(model=model,
           ...
           vllm_kwargs={
               "max_model_len":64,
               "gpu_memory_utilization":0.95,
           }
)
```

**Comment by Jasonsey** [comment]
> @aemonge @Jasonsey  It works to me
> 
> ```
> from langchain_community.llms import VLLM
> 
> llm = VLLM(model=model,
>            ...
>            vllm_kwargs={
>                "max_model_len":64,
>                "gpu_memory_utilization":0.95,
>            }
> )
> ```

awesome，I will have a try.

**Comment by aemonge** [comment]
That works indeed! :rocket:
