### ISSUE TITLE
[FEATURE] Implement Dynamic SplitFuse

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#1562]
Dear vLLM maintainers @WoosukKwon and @zhuohan123 (@Yard1),

DeepSpeed has released its serving framework which claims to be faster than vLLM. The main speedup comes from [Dynamic SplitFuse](https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen#b-dynamic-splitfuse-) which is a technique that does the following:

- Long prompts are decomposed into much smaller chunks and scheduled across multiple forward passes (iterations) with only the final pass performing any generation.

- Short prompts will be composed to exactly fill a target token budget. Even short prompts may be decomposed to ensure the budget is precisely met and the forward sizes are well-aligned.

Code: https://github.com/microsoft/DeepSpeed-MII
Background: https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fastgen

Llama 13B (1x A100-80GB):
![image](https://github.com/vllm-project/vllm/assets/27340033/cc7842b8-e234-482d-8550-d38d39d94473)

Llama 70B (4x A100x80GB with TP):
![image](https://github.com/vllm-project/vllm/assets/27340033/e035e094-0f10-463c-abf0-aafd67a61fed)

**Comment by irasin** [comment]
LGTM

**Comment by thesues** [comment]
Hi, is there any progress right now?

**Comment by shixianc** [comment]
Do we have an ETA? 😊

**Comment by tdene** [comment]
Hi @WoosukKwon @zhuohan123

The absence of a chunked prefill implementation in vllm is a major blocker. Any kind of timeline or regular communication on progress towards a chunked prefill implementation would be immensely helpful.

**Comment by sh1ng** [comment]
Keeping a batch with aligned length definitely helps https://github.com/vllm-project/vllm/pull/2357

**Comment by njhill** [comment]
Looks like someone has started working on this: https://github.com/vllm-project/vllm/pull/3106

**Comment by hmellor** [comment]
Chunked prefill is now supported
