### ISSUE TITLE
Issue when trying to run inference on this model EleutherAI/gpt-j-6b

### ISSUE THREAD

**Issue by sudhir2016** [vllm-project/vllm#1563]
EleutherAI/gpt-j-6b is mentioned as supported in the docs. Trying to run inference on Google Colab with free tier GPU. Getting this error. AssertionError: tensor model parallel group is already initialized.

**Comment by chaizhongming** [comment]
Perhaps  you _init distributed environment for second time, I come across the same question and  fix it  by adding  a initial_env_flag, first let initial_env_flag = True, when you have inited distributed environment, let initial_env_flag = False.

**Comment by sudhir2016** [comment]
Thanks for the response @chaizhongming. Yes the problem was because I was initializing for second time. It works fine when I restart. However EleutherAI/gpt-j-6b is too big for colab free tier causes a memory crash. But you can run larger models like Llama 13 B based on AWQ quantization.
