### ISSUE TITLE
Adding support for switch-transformer / NLLB-MoE

### ISSUE THREAD

**Issue by yl3469** [vllm-project/vllm#1565]
Hi vLLM Team,

Thanks again for the great work!

Recently my collaborator and I have been working on MoE and like to try to integrate vLLM with SwitchTransformer / FairSeq. I was wondering if you mind sharing if there is any effort already going on and what would be the major challenges?

https://huggingface.co/docs/transformers/main/model_doc/nllb-moe
https://github.dev/huggingface/transformers/blob/main/src/transformers/models/switch_transformers/modeling_switch_transformers.py

Thanks,
Lisa

**Comment by hmellor** [comment]
@yl3469 do you still intend to add support for this model archutecture?

**Comment by thangld201** [comment]
Hi @hmellor, if I want to add support for [NLLB ](https://huggingface.co/facebook/nllb-200-3.3B) in vllm, what should I do ?

**Comment by hmellor** [comment]
You can follow the steps at https://docs.vllm.ai/en/latest/models/adding_model.html

**Comment by thangld201** [comment]
> You can follow the steps at https://docs.vllm.ai/en/latest/models/adding_model.html

This is for CausalLM, where as NLLB is encoder-decoder. I suppose that it would be very different from what's written here ?

**Comment by hmellor** [comment]
Ah I see, in that case you'll want to head over to #187 to discuss Encoder-Decoder model support.
