### ISSUE TITLE
a possible improvement for gpu memory cache in llama

### ISSUE THREAD

**Issue by Eva20150932** [vllm-project/vllm#1571]
in short:
add "` torch.cuda.empty_cache()`" at last of `LlamaDecoderLayer.forward()` may help lessen the temporary gpu cache when model forwarding.
___
i'm using llama of vllm for inferencing and i was confused by the large memory usage shown in nvidia-smi. it always happened in `worker.profile_num_available_blocks()` when initializing, which may use out 35+gb memory, but not didnt bother too much on runtime.
after checking cuda memory status(using `torch.cuda.max_memory_reserved()`) step by step, i found there is an increasing cuda cache each time after  `LlamaDecoderLayer.forward()`. in my opinion this part of increased cache may be caused by the mlp in layer, and if true, this cache won't be used again and ` torch.cuda.empty_cache()` here can help lessen the memory while not slow down the forward process.

change( vllm/model_executor/models/llama.py line 217 started)

    # Fully Connected
    residual = hidden_states
    hidden_states = self.post_attention_layernorm(hidden_states)
    hidden_states = self.mlp(hidden_states)
    hidden_states = residual + hidden_states
    return hidden_states
to

    # Fully Connected
    residual = hidden_states
    hidden_states = self.post_attention_layernorm(hidden_states)
    hidden_states = self.mlp(hidden_states)
    hidden_states = residual + hidden_states

    # Release Cache
    torch.cuda.empty_cache()
    return hidden_states

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
