### ISSUE TITLE
OpenAI API incompatiable with some GPT Frontend

### ISSUE THREAD

**Issue by bonuschild** [vllm-project/vllm#1572]
- The API that used by https://github.com/Yidadaa/ChatGPT-Next-Web is `/v1/chat/completions?xxx`
- The API Server created by vllm offerring api like `/v1/completions?xxx`

Why is that? Can't VLLM load model for chatting purpose?

**Comment by simon-mo** [comment]
Hmmm we do support chat completion in the OpenAI compatible API server as well

See

https://github.com/vllm-project/vllm/blob/8516999495114926c9838c2d6e0feb580d4d983f/vllm/entrypoints/openai/api_server.py#L189-L191

**Comment by bonuschild** [comment]
> Hmmm we do support chat completion in the OpenAI compatible API server as well
> 
> See
> 
> https://github.com/vllm-project/vllm/blob/8516999495114926c9838c2d6e0feb580d4d983f/vllm/entrypoints/openai/api_server.py#L189-L191

However in the documentation [here](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server) it just decleares the `v1/completions` interface, which is same as what happen when used: When I send via `v1/chat/completions` interfaces the VLLM logs says `NOT FOUND` error...

Is the version problem?

**Comment by simon-mo** [comment]
That's possible. Can you try the latest version?

**Comment by bonuschild** [comment]
@simon-mo I am using the latest https://github.com/vllm-project/vllm/releases/tag/v0.2.1.post1 version.

**Comment by simon-mo** [comment]
Ah you might be hitting the model name check issue

https://github.com/vllm-project/vllm/blob/8516999495114926c9838c2d6e0feb580d4d983f/vllm/entrypoints/openai/api_server.py#L62-L69

You might want to start with server with parameter `--served-model-name gpt-3.5-turbo` or something else that your client is expecting.

**Comment by bonuschild** [comment]
@simon-mo Ah...you might spot the real reason! Thank you very much! Maybe can be merged into the documentation for better experience for other developer?

**Comment by simon-mo** [comment]
Definitely! Contribution welcomed here.
