### ISSUE TITLE
llama2 70b,  Tesla V100s, the output is always been cut off,could you help to check it?

### ISSUE THREAD

**Issue by ChristineSeven** [vllm-project/vllm#1578]
configuration:
 Tesla V100S GPU memory: 32768MiB*8
params:
      "n": 1,
      "top_k": 30,
      "top_p": 0.85,
      "use_beam_search": False,
      "max_tokens": 8192,
      "length_penalty":1.0,
      "ignore_eos":True,

the output is always been cut off.

use the stream mode, partof code as follows.
    if stream_flag is True:
        # Streaming case
        async def stream_results() -> AsyncGenerator[bytes, None]:
            completion_output = ''
            previous_length = 0
            async for request_output in results_generator:
                # print('request_output:', request_output)
                # print('vars(request_output):', vars(request_output))
                text_outputs = [
                    output.text for output in request_output.outputs
                ]
                completion_output = ''.join(text_outputs)
                logger.info(f'completion_output: {completion_output}')
                new_string = completion_output[previous_length:]
                previous_length = len(completion_output)
                yield new_string.encode("utf-8")
            end_time = get_datetime_now_obj()
            duration = (end_time - start_time).seconds

**Comment by simon-mo** [comment]
Can you put in the full script for reproducibility, currently this snippet doesn't help us diagnose the issue. Additionally, since `"max_tokens": 8192`, are you sure the output is below the limit?

**Comment by ChristineSeven** [comment]
the server code:
@app.post("/api/v1/gpt")
async def generate(request: Request) -> Response:
    resp_dict = {}
    code = 200
    content = await request.body()
    content = content.decode(errors='ignore')
    # prompt = request_dict.pop("inputs")
    # sample_params_dict = request_dict["parameters"]
    sampling_params = SamplingParams(**default_params)
    #sampling_params.verify()

    request_id = uuid.uuid4().hex
    prompt = "请根据指令，严谨的编写适当的回复。\n\n### 指令：\n{}\n\n### 回复：\n".format(content)
    results_generator = model.generate(prompt, sampling_params, request_id)

    #start_time = get_datetime_now_obj()
    # Non-streaming case
    final_output = None
    async for request_output in results_generator:
        if await request.is_disconnected():
            # Abort the request if the client disconnects.
            await model.abort(request_id)
            return Response(status_code=499)
        final_output = request_output

    assert final_output is not None
    prompt = final_output.prompt
    print('prompt:', prompt)
    text_outputs = [prompt + output.text for output in final_output.outputs]
    print('text_outputs:', text_outputs)

    insert_log(content, text_outputs, start_time.strftime('%Y-%m-%d %H:%M:%S'), duration, json.dumps(default_params,ensure_ascii=False))
    resp_dict['result'] = {
        'code': code,
        'content': text_outputs
    }
    return JSONResponse(content=resp_dict)
	
if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=19222)
    parser.add_argument("--n", type=int, default=1)
    parser.add_argument("--top_k", type=int, default=50)
    parser.add_argument("--top_p", type=float, default=0.4)
    parser.add_argument("--use_beam_search", type=bool, default=False)
    parser.add_argument("--max_tokens", type=int, default=8192)
    parser.add_argument("--temperature", type=float, default=0.5)
    parser.add_argument("--max_req_input_len", type=int, default=5000)
    parser.add_argument("--ignore_eos", type=bool, default=False)
    #parser.add_argument("--tensor-parallel-size", type=int, default=1)
    #parser.add_argument("--dtype", type=str, default='auto', choices=['float16', 'bfloat16'])
    parser = AsyncEngineArgs.add_cli_args(parser)
    args = parser.parse_args()
	    device = torch.device('cuda')
    print(f'Device: {device}')

    model_dir = args.model
    if not os.path.exists(model_dir):
        print('Model Not Found:', model_dir)
        exit(1)
    else:
        print(f'[{get_datetime_now_obj().strftime("%m-%d %H:%M")}] Model Dir: {model_dir}')

    model_name = os.path.basename(model_dir.rstrip('/')) + '_fp16_vllm'
    print(f'Model Name: {model_name}')

    log_date = get_datetime_now_obj().strftime('%Y%m%d_%H%M')
    log_file_path = os.path.realpath(f'logs/vllm_{model_name}_{log_date}.log')
    print('log_file_path:', log_file_path)

    use_preset_answer = True
    preset_chats_dict = get_preset_chats()
	    logging.basicConfig(filename=log_file_path,
                        filemode='a',
                        format='%(asctime)s: %(message)s',
                        datefmt='%m-%d %H:%M:%S',
                        level=logging.INFO)

    logger = logging.getLogger()

    history_tokens_length = 51
    no_input_tokens_length = 37
    print('history_tokens_length:', history_tokens_length)
    print('no_input_tokens_length:', no_input_tokens_length)

    print('Load Model Finished!')
    print('ignore eos',args.ignore_eos)
    default_params = {
        "n": args.n,
        "top_k": args.top_k,
        "top_p": args.top_p,
        "use_beam_search": args.use_beam_search,
        "max_tokens": args.max_tokens,
        "temperature":args.temperature,
        "ignore_eos":args.ignore_eos,
    }
    uvicorn.run(app,
                host=args.host,
                port=args.port,
                log_level="debug",
                timeout_keep_alive=TIMEOUT_KEEP_ALIVE)

**Comment by ChristineSeven** [comment]
`@app.post("/api/v1/gpt")
async def generate(request: Request) -> Response:
    resp_dict = {}
    code = 200
    content = await request.body()
    content = content.decode(errors='ignore')
    # prompt = request_dict.pop("inputs")
    # sample_params_dict = request_dict["parameters"]
    sampling_params = SamplingParams(**default_params)
    #sampling_params.verify()

    request_id = uuid.uuid4().hex
    prompt = "请根据指令，严谨的编写适当的回复。\n\n### 指令：\n{}\n\n### 回复：\n".format(content)
    results_generator = model.generate(prompt, sampling_params, request_id)

    #start_time = get_datetime_now_obj()
    # Non-streaming case
    final_output = None
    async for request_output in results_generator:
        if await request.is_disconnected():
            # Abort the request if the client disconnects.
            await model.abort(request_id)
            return Response(status_code=499)
        final_output = request_output

    assert final_output is not None
    prompt = final_output.prompt
    print('prompt:', prompt)
    text_outputs = [prompt + output.text for output in final_output.outputs]
    print('text_outputs:', text_outputs)

    insert_log(content, text_outputs, start_time.strftime('%Y-%m-%d %H:%M:%S'), duration, json.dumps(default_params,ensure_ascii=False))
    resp_dict['result'] = {
        'code': code,
        'content': text_outputs
    }
    return JSONResponse(content=resp_dict)
	
if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=19222)
    parser.add_argument("--n", type=int, default=1)
    parser.add_argument("--top_k", type=int, default=50)
    parser.add_argument("--top_p", type=float, default=0.4)
    parser.add_argument("--use_beam_search", type=bool, default=False)
    parser.add_argument("--max_tokens", type=int, default=8192)
    parser.add_argument("--temperature", type=float, default=0.5)
    parser.add_argument("--max_req_input_len", type=int, default=5000)
    parser.add_argument("--ignore_eos", type=bool, default=False)
    #parser.add_argument("--tensor-parallel-size", type=int, default=1)
    #parser.add_argument("--dtype", type=str, default='auto', choices=['float16', 'bfloat16'])
    parser = AsyncEngineArgs.add_cli_args(parser)
    args = parser.parse_args()
	    device = torch.device('cuda')
    print(f'Device: {device}')

    model_dir = args.model
    if not os.path.exists(model_dir):
        print('Model Not Found:', model_dir)
        exit(1)
    else:
        print(f'[{get_datetime_now_obj().strftime("%m-%d %H:%M")}] Model Dir: {model_dir}')

    model_name = os.path.basename(model_dir.rstrip('/')) + '_fp16_vllm'
    print(f'Model Name: {model_name}')

    log_date = get_datetime_now_obj().strftime('%Y%m%d_%H%M')
    log_file_path = os.path.realpath(f'logs/vllm_{model_name}_{log_date}.log')
    print('log_file_path:', log_file_path)

    use_preset_answer = True
    preset_chats_dict = get_preset_chats()
	    logging.basicConfig(filename=log_file_path,
                        filemode='a',
                        format='%(asctime)s: %(message)s',
                        datefmt='%m-%d %H:%M:%S',
                        level=logging.INFO)

    logger = logging.getLogger()

    history_tokens_length = 51
    no_input_tokens_length = 37
    print('history_tokens_length:', history_tokens_length)
    print('no_input_tokens_length:', no_input_tokens_length)

    print('Load Model Finished!')
    print('ignore eos',args.ignore_eos)
    default_params = {
        "n": args.n,
        "top_k": args.top_k,
        "top_p": args.top_p,
        "use_beam_search": args.use_beam_search,
        "max_tokens": args.max_tokens,
        "temperature":args.temperature,
        "ignore_eos":args.ignore_eos,
    }
    uvicorn.run(app,
                host=args.host,
                port=args.port,
                log_level="debug",
                timeout_keep_alive=TIMEOUT_KEEP_ALIVE)



	
`

**Comment by ChristineSeven** [comment]
`@app.post("/api/v1/gpt")
async def generate(request: Request) -> Response:
    resp_dict = {}
    code = 200
    content = await request.body()
    content = content.decode(errors='ignore')
    # prompt = request_dict.pop("inputs")
    # sample_params_dict = request_dict["parameters"]
    sampling_params = SamplingParams(**default_params)
    #sampling_params.verify()

    request_id = uuid.uuid4().hex
    prompt = "### 指令：\n{}\n\n### 回复：\n".format(content)
    results_generator = model.generate(prompt, sampling_params, request_id)

    #start_time = get_datetime_now_obj()
    # Non-streaming case
    final_output = None
    async for request_output in results_generator:
        if await request.is_disconnected():
            # Abort the request if the client disconnects.
            await model.abort(request_id)
            return Response(status_code=499)
        final_output = request_output

    assert final_output is not None
    prompt = final_output.prompt
    print('prompt:', prompt)
    text_outputs = [prompt + output.text for output in final_output.outputs]
    print('text_outputs:', text_outputs)

    insert_log(content, text_outputs, start_time.strftime('%Y-%m-%d %H:%M:%S'), duration, json.dumps(default_params,ensure_ascii=False))
    resp_dict['result'] = {
        'code': code,
        'content': text_outputs
    }
    return JSONResponse(content=resp_dict)
	
if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=19222)
    parser.add_argument("--n", type=int, default=1)
    parser.add_argument("--top_k", type=int, default=50)
    parser.add_argument("--top_p", type=float, default=0.4)
    parser.add_argument("--use_beam_search", type=bool, default=False)
    parser.add_argument("--max_tokens", type=int, default=8192)
    parser.add_argument("--temperature", type=float, default=0.5)
    parser.add_argument("--max_req_input_len", type=int, default=5000)
    parser.add_argument("--ignore_eos", type=bool, default=False)
    #parser.add_argument("--tensor-parallel-size", type=int, default=1)
    #parser.add_argument("--dtype", type=str, default='auto', choices=['float16', 'bfloat16'])
    parser = AsyncEngineArgs.add_cli_args(parser)
    args = parser.parse_args()
	    device = torch.device('cuda')
    print(f'Device: {device}')

    model_dir = args.model
    if not os.path.exists(model_dir):
        print('Model Not Found:', model_dir)
        exit(1)
    else:
        print(f'[{get_datetime_now_obj().strftime("%m-%d %H:%M")}] Model Dir: {model_dir}')

    model_name = os.path.basename(model_dir.rstrip('/')) + '_fp16_vllm'
    print(f'Model Name: {model_name}')

    log_date = get_datetime_now_obj().strftime('%Y%m%d_%H%M')
    log_file_path = os.path.realpath(f'logs/vllm_{model_name}_{log_date}.log')
    print('log_file_path:', log_file_path)

    use_preset_answer = True
    preset_chats_dict = get_preset_chats()
	    logging.basicConfig(filename=log_file_path,
                        filemode='a',
                        format='%(asctime)s: %(message)s',
                        datefmt='%m-%d %H:%M:%S',
                        level=logging.INFO)

    logger = logging.getLogger()

    history_tokens_length = 51
    no_input_tokens_length = 37
    print('history_tokens_length:', history_tokens_length)
    print('no_input_tokens_length:', no_input_tokens_length)

    print('Load Model Finished!')
    print('ignore eos',args.ignore_eos)
    default_params = {
        "n": args.n,
        "top_k": args.top_k,
        "top_p": args.top_p,
        "use_beam_search": args.use_beam_search,
        "max_tokens": args.max_tokens,
        "temperature":args.temperature,
        "ignore_eos":args.ignore_eos,
    }
    uvicorn.run(app,
                host=args.host,
                port=args.port,
                log_level="debug",
                timeout_keep_alive=TIMEOUT_KEEP_ALIVE)



	
`

**Comment by ChristineSeven** [comment]
the server code is as belows. So would you help to check it?

**Comment by ChristineSeven** [comment]
`    # Non-streaming case
    final_output = None
    async for request_output in results_generator:
        if await request.is_disconnected():
            # Abort the request if the client disconnects.
            await engine.abort(request_id)
            return Response(status_code=499)
        final_output = request_output

    assert final_output is not None
    prompt = final_output.prompt
    text_outputs = [prompt + output.text for output in final_output.outputs]
    ret = {"text": text_outputs}
    return JSONResponse(ret)`
For this non streaming case, will there be the case the outputs are fetched enough?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
