### ISSUE TITLE
微调好的模型要怎么使用vllm呢

### ISSUE THREAD

**Issue by leaf-ygq** [vllm-project/vllm#1579]
用Qwen模型微调之后，发现LLM这个函数只支持用模型的名字初始化。那我模型改了其他名字，要怎么加载到LLM里呢？
![image](https://github.com/vllm-project/vllm/assets/75319189/e22d22bb-0b03-49ab-ba06-c80a628c280f)

**Comment by LiuXiaoxuanPKU** [comment]
You can also put the model location here: `llm = LLM(model=model_dir)`.

**Comment by leaf-ygq** [comment]
我用了文件目录的形式加载，如下图所示
![image](https://github.com/vllm-project/vllm/assets/75319189/011fad49-bcb0-44b4-8ba8-b8cb4cc15fa3)
但是依旧报错：
![image](https://github.com/vllm-project/vllm/assets/75319189/b4ae4e01-f26d-4d67-9b1d-2c32d1880e04)

**Comment by leaf-ygq** [comment]
另外，想咨询一下，哪个版本的VLLM，在初始化LLM时，有下面这个用法呢？(model这个参数是模型的名字，llm_model这个参数是已加载好的模型)
llm = LLM(
        model=model,
        tokenizer=model,
        tensor_parallel_size=1,
        seed=123,
        trust_remote_code=True,
        is_exist_model=True,
        llm_model=llm_model
    )

**Comment by cauyxy** [comment]
把千问模型原来的那个文件夹里面的 configuration_qwen.py, 那些 python 文件放到你微调完的模型文件夹

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
