### ISSUE TITLE
Dolly V2 : instruction following pipeline support in vLLM

### ISSUE THREAD

**Issue by copasseron** [vllm-project/vllm#1585]
Hello everyone, 

I'm deploying some models leveraging vLLM and triton, and have been successful with a lot of them. 

However today I have some issue deploying dolly-v2-12b https://huggingface.co/databricks/dolly-v2-12b.

Everything deploys but I get very rubbish response from the LLM.

It is because it is not using the custom instruction following pipeline here https://huggingface.co/databricks/dolly-v2-12b/blob/main/instruct_pipeline.py.

I've tried setting trust-remote-code (https://github.com/vllm-project/vllm/blob/1a2bbc930135cd3b94fbff2aafbdf5c568acc8bd/vllm/engine/arg_utils.py#L76), but it hasn't changed anything. 

My guess would be that I'm stuck with transformers.pipeline() to use this custom instruction pipeline. 

Is there a way to use vLLM and use this instruct pipeline ?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
