### ISSUE TITLE
Help in code: Shape of Key cache vs shape of value cache:

### ISSUE THREAD

**Issue by Bhuvanesh09** [vllm-project/vllm#1586]
Our team is trying to implement BART and similar Encoder-Decoder Architecture for vllm. While exploring the code, we have ran into a curious question:

The shape of cache while using GPT2 is as follows for key and value:
key_cache : `[34652, 12, 8, 16, 8]`
value_cache: `[34652, 12, 64, 16]`

Here, the last 4 dims for key_cache are : [num_heads, head_size/x, num_tokens_per_block, x]

The question is:
1. Role of x?
2. Why is the shape different for key and value
3. What is 34652 in the above shape?

Kindly point us in the right direction on where we could learn more about this. Thanks.

**Comment by chu-tianxiang** [comment]
afaik, the key cache shape is from FasterTransformer to use vectorized memory access for better performance (128-bit per instruction = 8 float16). See [the comment](https://github.com/NVIDIA/FasterTransformer/blob/d21dc02bc5f70bc7dc0d18ba5801ae263565e68e/src/fastertransformer/kernels/decoder_masked_multihead_attention/decoder_masked_multihead_attention_template.hpp#L62) in FT:

> // The layout of the cache buffer for the keys is [B, H, Dh/x, L, x] where x == 8 for FP16 and
> // x == 4 for FP32 where the fastest moving dimension (contiguous data) is the rightmost one. The
> // values for x are chosen to create chunks of 16 bytes.

It's perfectly OK to use same shape for key and value cache without such optimization. 30652 is the number of blocks pre-allocated by vLLM.
