### ISSUE TITLE
Mistral 7B with AWQ - bfloat16 error

### ISSUE THREAD

**Issue by gordicaleksa** [vllm-project/vllm#1592]
I saw @WoosukKwon's msg [here](https://github.com/vllm-project/vllm/issues/1433#issuecomment-1772995719) on how to setup AWQ.

I downloaded the weights from the bloke [here](https://huggingface.co/TheBloke/Mistral-7B-v0.1-AWQ) but I'm having issues with Mistral as it's bfloat16 and currently for quantization it seems you have some assumptions that the model should be float16 only?

What's the state with Mistral has anyone run a quantized version?

Thanks!

**Comment by BharatSingla12** [comment]
facing the same issue, I am trying to run it in colab gpu and getting below error
` ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5.
`

**Comment by phuonglekhac** [comment]
You could specify `dtype='half'` or if you use API server: `--dtype half`
example: `python -m vllm.entrypoints.openai.api_server --model TheBloke/openchat_3.5-AWQ --quantization awq --host 0.0.0.0 --port 8686 --dtype half --served-model-name openchat/openchat_3.5`

> facing the same issue, I am trying to run it in colab gpu and getting below error `ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5.`

**Comment by Kelang-Tian** [comment]
> You could specify `dtype='half'` or if you use API server: `--dtype half` example: `python -m vllm.entrypoints.openai.api_server --model TheBloke/openchat_3.5-AWQ --quantization awq --host 0.0.0.0 --port 8686 --dtype half --served-model-name openchat/openchat_3.5`
> 
> > facing the same issue, I am trying to run it in colab gpu and getting below error `ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla T4 GPU has compute capability 7.5.`

https://github.com/vllm-project/vllm/issues/1941
set `dtype='half'` can start `vllm.entrypoints.openai.api_server`. Sometimes my model has NaN issues at half precision( because the model is sft in bfloat16).
It seems that I need to implement a bf16 version of the kernel myself
