### ISSUE TITLE
No CUDA GPUs are available Error with vLLM in JupyterLab 

### ISSUE THREAD

**Issue by SafeyahShemali** [vllm-project/vllm#1594]
Hello, 

I have been facing a various errors regarding running the vLLM  on GCP with JupyterLab. The set of errors as as follow:

- No CUDA GPUs are available
- CUDA out of memory. Tried to allocate 150.00 MiB (GPU 0; 14.58 GiB total capacity; 13.94 GiB already allocated; 17.31 MiB free; 13.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Please, I need help!

**Comment by NavinKumarMNK** [comment]
- `No CUDA GPUs are available` , This error occurs if the `worker_use_ray`=False. Try setting up `worker_use_ray`=True 
- `CUDA out of memory` errors arise when you are trying to load model of memory size greater then GPU VRAM. This should be solved by increasing GPU VRAM or decreasing the model size which might decrease the memory footprint of the model
