### ISSUE TITLE
How to set seed before generation?

### ISSUE THREAD

**Issue by baleksey** [vllm-project/vllm#1595]
I know, you can set any seed during model loading, but how specific seed can be set before each generation (without reloading model every time) or even better for every N prompt you feed to generator?

Thank you in advance!

**Comment by simon-mo** [comment]
You are correct this is not supported at the moment. We welcome contributions!

**Comment by avirlrma** [comment]
Hi @simon-mo,
I've created a draft PR, could you please have a look?

**Comment by brando90** [comment]
answer:

```
I'll research how vLLM handles seeding for determinism and whether there are any official methods or workarounds for ensuring reproducibility. I'll get back to you with the details soon.

# Handling Random Seeds in vLLM for Deterministic Results

## Seeding Support in vLLM 
**Built-in Seeding Mechanism:** vLLM allows you to set a random seed for text generation through its `SamplingParams`. The `SamplingParams` class includes a `seed` parameter that you can specify when generating text ([[Sampling Parameters — vLLM](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation)](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation)). For example, you might do: 

```python
from vllm import LLM, SamplingParams
model = LLM(model="your-model-name")
params = SamplingParams(seed=42, temperature=0.7, max_tokens=100)
output = model.generate(["Your prompt here"], sampling_params=params)
``` 

In this case, using the same seed (42) with identical prompts and parameters should *ideally* produce the same output each run. This per-request seed feature was introduced in vLLM around version 0.3.2 ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)), making reproducibility easier by controlling randomness on each generation call. There isn't a separate `vllm.set_seed()` function; instead, you pass the seed as part of the generation request (or via the OpenAI-compatible API’s extra parameters if using vLLM’s server). vLLM’s OpenAI-style server accepts extra parameters like `"seed": 42` in the JSON payload even though the real OpenAI API doesn’t support seed, providing a convenient way to seed requests for deterministic outputs ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)).

**Global vs. Request-Level Seeding:** vLLM also has a global seed option in its CLI (`--seed`) which sets the initial random seed for the server/engine ([[OpenAI-Compatible Server — vLLM](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#:~:text=%60)](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#:~:text=%60)). However, be aware of how this behaves. In older versions, if you *didn’t* specify any seed, vLLM would default to `0` and internally call `torch.manual_seed(0)` (and seed other libraries) on model initialization, effectively fixing the random state for *all* operations ([[[Bug]: The random seed behavior when loading a model in vLLM is confusing. · Issue #11953 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)). This meant that even code outside vLLM (e.g. Python’s `random` or NumPy) could produce the same “random” values every run because the global RNG was inadvertently reset ([[[Bug]: The random seed behavior when loading a model in vLLM is confusing. · Issue #11953 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)). This was identified as confusing behavior and treated as a bug – the expected behavior is that if no seed is provided, vLLM should not alter global randomness ([[[Bug]: The random seed behavior when loading a model in vLLM is confusing. · Issue #11953 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11953#:~:text=,users%20can%20control%20this%20behavior)](https://github.com/vllm-project/vllm/issues/11953#:~:text=,users%20can%20control%20this%20behavior)). Recent fixes have addressed this by changing the default seed to `None` (so it won’t override global RNG unless you explicitly set a seed) ([[[Bug]: The random seed behavior when loading a model in vLLM is confusing. · Issue #11953 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)). In summary, if you want deterministic outputs, **you should explicitly set a seed** (either via `SamplingParams` or `--seed`), and if you don’t, vLLM will now leave randomness to its default (rather than silently seeding everything to 0 as before).

## Underlying Dependencies and Reproducibility 
**PyTorch and CUDA Influence:** vLLM is built on PyTorch, and its randomness behavior is subject to PyTorch’s and CUDA’s characteristics. In theory, if all random influences are controlled (same model, prompt, seed, and sampling settings), the generation process is a “mathematical” function that should be deterministic. **In practice, small numerical variations in low-level operations can break determinism**. The vLLM team notes that it *“does not guarantee stable log probabilities”* across runs ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)). This is mainly because of two factors:  

- **Floating-Point Precision & Numerical Instability:** Large language model inference involves floating-point computations that may yield slightly different results depending on precision and operation order. vLLM’s FAQ explains that *“variations in logprobs may occur due to numerical instability in Torch operations”* ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)). If you run the same model with different precision (e.g. FP16 vs. BF16) or even just different batch configurations, you might get tiny differences in computed probabilities that can snowball into different token choices. One of vLLM’s contributors observed that with insufficient precision, *even using the same seed, different batch sizes can lead to different tokens being sampled* ([[Support per-request seed by njhill · Pull Request #2514 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)). In other words, if the model’s forward pass is done in a slightly different way (due to how batching or parallelism works), the sequence of random draws could diverge because the underlying probabilities changed at the 5th or 6th decimal place.

- **Non-deterministic GPU Ops:** By default, some GPU operations are non-deterministic (for example, certain parallel algorithms may produce results in an unpredictable order). Different hardware or libraries might execute operations differently. A vLLM user reported that generating text with the same seed on an **NVIDIA A100 vs. H100 GPU** produced different completions ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=When%20running%20on%20different%20type,I%20would%20obtain%20different%20results)](https://github.com/vllm-project/vllm/issues/11526#:~:text=When%20running%20on%20different%20type,I%20would%20obtain%20different%20results)) ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)). The maintainers confirmed this is expected: *“the kernel implementation may be different based on the GPU, resulting in minor numerical differences.”* ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)). Similarly, if you run on different CUDA or PyTorch versions, you might hit slight variations. Even multi-threading or asynchronous scheduling can introduce variability – one discussion noted that runtime micro-optimizations in the scheduler can cause different outcomes on the **same** machine in different runs ([[How deterministic the result of inference is for the local LLMs? : r/LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/comments/17197k1/how_deterministic_the_result_of_inference_is_for/#:~:text=Even%20with%20the%20same%20seed%2C,according%20to%20a%20new%20study)](https://www.reddit.com/r/LocalLLaMA/comments/17197k1/how_deterministic_the_result_of_inference_is_for/#:~:text=Even%20with%20the%20same%20seed%2C,according%20to%20a%20new%20study)). 

**Seed Scope:** The `seed` in vLLM specifically targets the model’s token sampling. Internally, vLLM uses the seed to initialize the RNG for generating tokens (likely via PyTorch’s RNG) in a **per-request scope**. If you provide a seed in `SamplingParams`, vLLM will set the necessary random state so that the sequence of random numbers (for token selection) is repeatable for that request. However, **other sources of randomness** in the environment (like data loading, shuffling outside vLLM, or other parallel processes) are not controlled by that. For truly identical results, you may still need to set seeds in those domains as well (e.g., call `random.seed()`, `np.random.seed()`, or `torch.manual_seed()` in your script) if they affect your workflow. vLLM’s seed primarily ensures the *model’s generation* is seeded. (Notably, the user forum discussion you referenced about calling `torch.manual_seed`, `np.random.seed`, etc., was essentially trying to cover all bases. The vLLM team responded that simply using the vLLM sampling params seed is sufficient for the model generation part ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)).)

**PyTorch Deterministic Modes:** Because vLLM leans on PyTorch, you can also leverage PyTorch’s deterministic settings if needed. Setting `torch.backends.cudnn.deterministic = True` and `torch.use_deterministic_algorithms(True)` can force certain operations to use deterministic algorithms (at some performance cost). In the context of vLLM, this might reduce variability in layer computations. One user explicitly mentioned using `torch.use_deterministic_algorithms(True)` alongside seeding all libraries to try to guarantee identical outputs ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=Does%20it%20enough%20to%20get,factors%20will%20violate%20the%20determinism)](https://github.com/vllm-project/vllm/issues/2910#:~:text=Does%20it%20enough%20to%20get,factors%20will%20violate%20the%20determinism)). While the vLLM docs don’t explicitly require this, it’s a viable step if you are encountering non-determinism. Just be aware that even with these flags, **floating-point rounding differences can still occur** if anything (hardware, library, order of ops) changes – these flags mainly prevent nondeterministic threading or hashing behaviors.

## Reproducibility: Issues and Limitations 
Despite providing a seeding mechanism, **vLLM does not promise bit-for-bit reproducibility in all cases**. The seed feature should give you consistent results for the same prompt **when all conditions are identical**, but there are known limitations:

- **Batching & Concurrency Effects:** vLLM is optimized for high throughput and will dynamically batch requests together. If you send one request in isolation vs. the same request alongside others, the internal batching can differ, which might slightly change the generation timing or sequence. The team explains that *“the same requests might be batched differently due to factors such as other concurrent requests, changes in batch size, or batch expansion in speculative decoding”*. These batching variations, combined with numerical instability, *“can lead to slightly different logit/logprob values at each step”* and eventually different sampled tokens ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=In%20vLLM%2C%20the%20same%20requests,sampled%2C%20further%20divergence%20is%20likely)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=In%20vLLM%2C%20the%20same%20requests,sampled%2C%20further%20divergence%20is%20likely)). Once a single token diverges, the rest of the output will likely diverge as well. This means that **running vLLM in a multi-user server scenario can make results non-reproducible** even with a fixed seed, because the presence or absence of other requests influences the outcome. 

- **Precision and Model Variants:** As noted, using lower precision modes (like **bfloat16 or int8 quantization**) can increase the chance of divergent results. vLLM developers observed that *float16 yields more stable results than bfloat16, and quantized models are likely even less stable* in terms of reproducibility ([[Support per-request seed by njhill · Pull Request #2514 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/pull/2514#:~:text=Thanks%20%40Yard1%21%20Yes%20I%27m%20aware,so%20will%20do%20some%20tests)](https://github.com/vllm-project/vllm/pull/2514#:~:text=Thanks%20%40Yard1%21%20Yes%20I%27m%20aware,so%20will%20do%20some%20tests)). The FAQ specifically suggests using **float32** for improved stability if exact reproducibility is important, albeit with a memory and speed cost ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)). In practice, if you absolutely need the same outputs, consider disabling any compression/quantization and using the highest precision you can.

- **Hardware and Library Differences:** As mentioned, running on different GPUs or different BLAS libraries might give different results with the same seed. Minor differences in floating-point implementations (e.g., due to TensorCore vs. non-TensorCore math) can cause cumulative divergence ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)). Even on CPU, differences in compiler optimizations have been shown to produce different text generations under the exact same seeds ([[How deterministic the result of inference is for the local LLMs? : r/LocalLLaMA](https://www.reddit.com/r/LocalLLaMA/comments/17197k1/how_deterministic_the_result_of_inference_is_for/#:~:text=Even%20with%20the%20same%20seed%2C,according%20to%20a%20new%20study)](https://www.reddit.com/r/LocalLLaMA/comments/17197k1/how_deterministic_the_result_of_inference_is_for/#:~:text=Even%20with%20the%20same%20seed%2C,according%20to%20a%20new%20study)). **Reproducibility is thus “fragile”** – seemingly innocuous changes like upgrading PyTorch or moving to a newer GPU driver could affect it. 

- **Known Bugs (Historical):** Earlier versions of vLLM had a few reproducibility glitches that are worth noting if you use those versions:
  - *Pipeline Parallel Seed Bug:* In vLLM’s multi-GPU (pipeline parallel) mode, there was a bug where the per-request seed was not correctly handled across model shards, leading to non-deterministic outputs even if you set a seed. This was tracked and fixed in mid-2024 ([[[Bug]: Seed issue with Pipeline Parallel · Issue #6449 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/6449#:~:text=Closed)](https://github.com/vllm-project/vllm/issues/6449#:~:text=Closed)) ([[[Bug]: Seed issue with Pipeline Parallel · Issue #6449 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/6449#:~:text=Image%3A%20%40simon,6698%20%20%20%2089)](https://github.com/vllm-project/vllm/issues/6449#:~:text=Image%3A%20%40simon,6698%20%20%20%2089)), so if you’re on vLLM ≥0.5.3 you should have the fix. On modern versions, seeding should work consistently whether you run on one GPU or partition the model on several.  
  - *Default Seed Behavior:* As discussed, vLLM used to default to `seed=0` if not specified, unintentionally freezing global randomness ([[[Bug]: The random seed behavior when loading a model in vLLM is confusing. · Issue #11953 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)](https://github.com/vllm-project/vllm/issues/11953#:~:text=1,which%20can%20cause%20subtle%20bugs)). This has been addressed so that not specifying a seed will let each run differ (which is the intuitive behavior). If you *want* identical runs, you must explicitly set a seed now. This change avoids surprising situations where unrelated random code kept repeating results.

- **Reproducibility vs. Performance:** It’s worth noting that vLLM’s design prioritizes speed and efficiency. One consequence is that it may sacrifice *exact* reproducibility for performance optimizations ([[AIMO vLLM Accelerated ToT+SC DeepSeekMath - Kaggle](https://www.kaggle.com/code/bsmit1659/aimo-vllm-accelerated-tot-sc-deepseekmath#:~:text=Generation%20Speed%3A%20vLLM%20is%20designed,)](https://www.kaggle.com/code/bsmit1659/aimo-vllm-accelerated-tot-sc-deepseekmath#:~:text=Generation%20Speed%3A%20vLLM%20is%20designed,)). For example, the dynamic batching and parallelism are great for throughput but introduce nondeterminism. The **Kaggle** user guide for vLLM highlights this trade-off: *“vLLM is designed to be high-speed, potentially sacrificing some deterministic behaviors (like exact reproducibility of results) for performance.”* ([[AIMO vLLM Accelerated ToT+SC DeepSeekMath - Kaggle](https://www.kaggle.com/code/bsmit1659/aimo-vllm-accelerated-tot-sc-deepseekmath#:~:text=Generation%20Speed%3A%20vLLM%20is%20designed,)](https://www.kaggle.com/code/bsmit1659/aimo-vllm-accelerated-tot-sc-deepseekmath#:~:text=Generation%20Speed%3A%20vLLM%20is%20designed,)). In critical applications, you should be aware of this compromise.

## Best Practices for Deterministic Behavior 
While you cannot guarantee 100% identical outputs in every scenario, you can **maximize reproducibility** with a few strategies:

- **Set the Seed for Every Generation:** Always provide a `seed` in `SamplingParams` (or via the API payload) when you need reproducible outputs. This ensures the model’s sampling uses a fixed random sequence ([[Sampling Parameters — vLLM](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation)](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation)). If you’re calling the OpenAI-compatible HTTP server, include the seed in the `extra` parameters of your request. This is the primary mechanism to control vLLM’s randomness.

- **Use Deterministic Sampling Settings:** If exact repeatability is crucial, consider turning *off* as much randomness as possible. For instance, set `temperature=0` (greedy decoding) or a very low temperature, use `top_p=1.0` and `top_k=-1` (no sampling cutoff), and avoid nucleus or top-k sampling. Greedy decoding (temperature 0) will always pick the highest-probability token, making the process deterministic *given the same logits*. Do note that even greedy can diverge if floating-point math diverges (as some users observed), but it removes the additional layer of random choice, greatly stabilizing outputs. In one bug report, using `temperature=0.0` made outputs consistent across GPUs when a higher temperature did not ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=CUDA_VISIBLE_DEVICES%3D%24GPU%20python%20,port%20%24PORT)](https://github.com/vllm-project/vllm/issues/11526#:~:text=CUDA_VISIBLE_DEVICES%3D%24GPU%20python%20,port%20%24PORT)).

- **Keep Environment Consistent:** Try to run your deterministic tests under the same conditions each time. That means using the same hardware type, same number of requests in parallel, same model version, and same vLLM version. Even the sequence in which you feed prompts might matter if you’re using the server (because it affects batching). For true apples-to-apples comparisons, run the prompts one at a time in isolation. If you use the vLLM server in production, be aware that a prompt’s output might not be reproducible later when the system is under different load. In such cases, you might opt to use vLLM in a single-threaded or offline mode for your deterministic runs.

- **Increase Numerical Stability:** Run the model in higher precision if possible. Using `--dtype float32` (if vLLM provides such an option) or ensuring the model is loaded in FP32 will reduce the chance of tiny numeric differences ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)). If you must use FP16 or BF16 for speed, know that you’re inherently allowing more variability. Also, disable any non-essential optimizations that could introduce randomness – for example, speculative decoding or certain flash-attention kernels might have non-deterministic behaviors (speculative decoding in particular changes the generation procedure, though vLLM should handle its randomness with the seed as well).

- **Leverage PyTorch Controls:** As a safeguard, set `torch.manual_seed(seed)` along with vLLM’s own seed, and if using numpy or Python’s random in your data pipeline, seed those as well. This way, **all** sources of randomness in your script are controlled. Moreover, enabling deterministic algorithms in PyTorch (`torch.use_deterministic_algorithms(True)`) can prevent nondeterministic operations at the cost of speed. The combination of these settings was suggested by a user and, while vLLM’s team emphasized their built-in support, it’s a reasonable best practice for critical reproducibility needs ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=I%27m%20wondering%20is%20there%20a,factors%20will%20violate%20the%20determinism)](https://github.com/vllm-project/vllm/issues/2910#:~:text=I%27m%20wondering%20is%20there%20a,factors%20will%20violate%20the%20determinism)). Remember to also set the environment variable `CUBLAS_WORKSPACE_CONFIG=:16:8` (or `:4096:8`) if you’re using CUDA, to enforce deterministic CuBLAS operations (a PyTorch recommendation for full determinism).

- **Monitor vLLM Updates:** Keep an eye on vLLM’s release notes or GitHub issues regarding reproducibility. The team is aware of determinism issues and often provides guidance or fixes. For example, the FAQ explicitly acknowledges that *using request seeds makes generation more stable* but still “discrepancies due to precision differences may still occur” ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)). Such transparency means they might offer new flags or improvements in future. Staying updated will ensure you know the current limitations.

**Conclusion:** vLLM does provide a way to control randomness (the `seed` parameter), and using it will give you deterministic behavior in many cases (especially for sampling-based generation). However, the reproducibility is ultimately *best-effort*. Underlying factors like PyTorch’s numerical determinism, GPU hardware differences, and vLLM’s performance-oriented batching can all introduce slight unpredictability ([[Support per-request seed by njhill · Pull Request #2514 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)) ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)). For most practical purposes, if you fix the seed and run under the same conditions, you’ll get the same result. But if exact repeatability is mission-critical, implement the above best practices and test thoroughly. Consider vLLM’s outputs deterministic only to the extent that the entire execution environment is identical – any drift there, and the results may diverge despite identical seeds ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=In%20vLLM%2C%20the%20same%20requests,sampled%2C%20further%20divergence%20is%20likely)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=In%20vLLM%2C%20the%20same%20requests,sampled%2C%20further%20divergence%20is%20likely)) ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)). Always treat seeded generation as a way to *increase* stability, not as an iron-clad guarantee of identical output in all scenarios. 

**References:**

- vLLM Documentation – *SamplingParams* class (seed parameter) ([[Sampling Parameters — vLLM](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation)](https://docs.vllm.ai/en/v0.5.1/dev/sampling_params.html#:~:text=,to%20use%20for%20the%20generation))  
- vLLM Documentation – *Inference FAQ on variability across runs* ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=A%3A%20Yes%2C%20it%20can,see%20the%20Numerical%20Accuracy%20section)) ([[Frequently Asked Questions — vLLM](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory)](https://docs.vllm.ai/en/latest/getting_started/faq.html#:~:text=,this%20will%20require%20more%20memory))  
- vLLM GitHub Issue – Confirmation of deterministic generation support via seed ([[[feat] vLLM generation deterministic option/flag · Issue #2910 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71)](https://github.com/vllm-project/vllm/issues/2910#:~:text=simon,71))  
- vLLM GitHub Issue – Developer notes on seed determinism and precision limits ([[Support per-request seed by njhill · Pull Request #2514 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)](https://github.com/vllm-project/vllm/pull/2514#:~:text=One%20issue%20I%20have%20encountered,to%20keep%20in%20mind%20here)) ([[Support per-request seed by njhill · Pull Request #2514 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/pull/2514#:~:text=Thanks%20%40Yard1%21%20Yes%20I%27m%20aware,so%20will%20do%20some%20tests)](https://github.com/vllm-project/vllm/pull/2514#:~:text=Thanks%20%40Yard1%21%20Yes%20I%27m%20aware,so%20will%20do%20some%20tests))  
- vLLM GitHub Issue – User report of different outputs on different GPUs (numeric differences) ([[[Bug]: Different sampled output when running on different GPUs · Issue #11526 · vllm-project/vllm · GitHub](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences)](https://github.com/vllm-project/vllm/issues/11526#:~:text=This%20is%20normal%20behaviour%2C%20since,resulting%20in%20minor%20numerical%20differences))  
- vLLM GitHub Issue – Discussion of default seed=0 behavior and fix
```

**Comment by brando90** [comment]
https://stackoverflow.com/questions/79467847/how-can-i-ensure-deterministic-text-generation-with-vllm-and-does-it-support-a/79467848#79467848
