### ISSUE TITLE
Transformers version issue causes chatglm  to fail to start

### ISSUE THREAD

**Issue by ak646260187** [vllm-project/vllm#1601]
when the transformers>=4.33.2:

  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2017, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2249, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 108, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 104, in vocab_size
    return self.tokenizer.n_words
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer

when the transfomers==4.33.2 or 4.33.0:

from transformers import MistralConfig
ImportError: cannot import name 'MistralConfig' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/__init__.py)

**Comment by ak646260187** [comment]
python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --tensor-parallel-size 1 --model $MODEL_NAME --trust-remote-code --port xx

**Comment by Jeffwan** [comment]
it's a version issue. I had the issue last week as well. Bump to latest version helps

**Comment by CurisZhou** [comment]
> when the transformers>=4.33.2:
> 
> File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2017, in from_pretrained return cls._from_pretrained( File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils_base.py", line 2249, in _from_pretrained tokenizer = cls(*init_inputs, **init_kwargs) File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 69, in **init** super().**init**(padding_side=padding_side, **kwargs) File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py", line 367, in **init** self._add_tokens( File "/usr/local/lib/python3.8/dist-packages/transformers/tokenization_utils.py", line 467, in _add_tokens current_vocab = self.get_vocab().copy() File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 108, in get_vocab vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)} File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-tarotdice-v2/tokenization_chatglm.py", line 104, in vocab_size return self.tokenizer.n_words AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer
> 
> when the transfomers==4.33.2 or 4.33.0:
> 
> from transformers import MistralConfig ImportError: cannot import name 'MistralConfig' from 'transformers' (/usr/local/lib/python3.8/dist-packages/transformers/**init**.py)

Hi, have you successfully solved this problem？
I also meet this issue. After updating the version of my transformers, this issue also exits.
