### ISSUE TITLE
LLMEngine.step() missing 1 required positional argument: 'request_arrival_time'

### ISSUE THREAD

**Issue by yuye2133** [vllm-project/vllm#1602]
vllm==0.1.3
ray==2.8.0

`
from vllm import LLM, SamplingParams
prompts = [
    "Funniest joke ever:",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.95, top_p=0.95, max_tokens=200)
llm = LLM(model="xxx", tensor_parallel_size=2)
**outputs = llm.generate(prompts, sampling_params)**
print(outputs)
`
error message
`
(pid=27540) INFO: Init log file success, log_file=/apps/logs/log_receiver/rec-pred-2-mlp-pytorch-1029026.ai.vip.com/vllm.log
(RayWorker pid=27540) [W socket.cpp:436] [c10d] The server socket cannot be initialized on [::]:49363 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=27540) [W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [pytorch-rec-pred-2-mlp-1029026-worker-0.pytorch-rec-pred-2-mlp-1029026.mlp.svc.gd17-ai-001.vip.com]:49363 (errno: 97 - Address family not supported by protocol).
(RayWorker pid=27540) /opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py:231: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(RayWorker pid=27540)   tokens_tensor = torch.cuda.LongTensor(input_tokens)
(RayWorker pid=27541) [W socket.cpp:663] [c10d] The client socket cannot be initialized to connect to [pytorch-rec-pred-2-mlp-1029026-worker-0.pytorch-rec-pred-2-mlp-1029026.mlp.svc.gd17-ai-001.vip.com]:49363 (errno: 97 - Address family not supported by protocol).
Processed prompts:   0% 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/llm_models/test.py", line 12, in <module>
    outputs = llm.generate(prompts, sampling_params)
  File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 130, in generate
    return self._run_engine(use_tqdm)
  File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 150, in _run_engine
    step_outputs = self.llm_engine.step()
**TypeError: LLMEngine.step() missing 1 required positional argument: 'request_arrival_time'**
(pid=27541) INFO: Init log file success, log_file=/apps/logs/log_receiver/rec-pred-2-mlp-pytorch-1029026.ai.vip.com/vllm.log
(RayWorker pid=27541) /opt/conda/lib/python3.10/site-packages/vllm/worker/worker.py:231: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
(RayWorker pid=27541)   tokens_tensor = torch.cuda.LongTensor(input_tokens)
Processed prompts:   0% 0/3 [00:01<?, ?it/s]
`

**Comment by yeshenyong** [comment]
the same issue
