### ISSUE TITLE
can you support YiForCausalLM? model Yi-34B

### ISSUE THREAD

**Issue by wujingbo-web** [vllm-project/vllm#1603]
when i try to run 
python -m vllm.entrypoints.openai.api_server --model Yi-34B-200K --port 18081 --trust-remote-code
error occurs:
Model architectures ['YiForCausalLM'] are not supported for now

it's web site address:
https://github.com/01-ai/Yi

**Comment by WoosukKwon** [comment]
Hi @wujingbo-web, which version of vLLM are you using? We recently added the support, so it's not available in the stable release version yet. We will make a new release soon. Please [install vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source) until then.

**Comment by anlongfei** [comment]
we installed vllm-0.3.2 from source, but found Model architectures ['YiForCausalLM'] are not supported.

$ pip list | grep vllm
vllm                      0.3.2+cu118

ValueError: Model architectures ['YiForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OLMoForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM']

**Comment by esmeetu** [comment]
@wujingbo-web @anlongfei Please update your model file, Yi has change their model architecture name from `YiForCausalLM` to `LlamaForCausalLM `. And vLLM already support Llama.
