### ISSUE TITLE
qwen-14b-chat in vllm when the num of input tokens more than 3000 ,generation is so bad and repetitive

### ISSUE THREAD

**Issue by BWZhang-NLP** [vllm-project/vllm#1604]
qwen-14b-chat when the num of input tokens more than 3000 ,generation is so bad and repetitive,but HF's result is good.

The generation result:
`
依据，其，3 依据，22003 依据，3 29 依据，3、3 依据，3 10004848848 依据，其 依据，33888 依据，888888888，判决，84848 08，依据，88880028222000，888

��8 依据，8 依据，8 依据，848 依据 依据，人民法院，0888888 依据，8 依据，3 依据，8 依据，8 依据8 33 依据，3 依据848 依据88 依据，0 、48 12 2 依据，8 依据88 依据，8 依据，8 依据88 88 领848 依据88 玠288 依据，8 依据，8 人民法院，8 人民法院，其 依据，其3 88 3 人民法院，8 依据8 依据，2 依据8 8 依据8 依据8 依据8 8 88 8 8 依据8 8 额8 8 8 依据8 依据 8 依据8 依据 8 8 8 、88 人民法院 人民法院，8 8 依据，人民法院，4 人民法院，88 8 人民法院， 8 8 8 8 人民法院，人民法院，对8 颠 人民法院 人民法院8 人民法院 人民法院，人民法院88 人民法院 人民法院，人民法院88 人民法院，8 人民法院 人民法院，88 人民法院 人民法院，48 人民法院，48 人民法院 人民法院，人民法院，人民法院 人民法院 人民法院 人民法院 人民法院 人民法院，人民法院 人民法院，人民法院 依据8 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 依据 人民法院 人民法院 人民法院 依据 人民法院 人民法院，人民法院，人民法院 人民法院 人民法院 人民法院8 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院，人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院888 人民法院 人民法院8 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民法院 人民......
`

**Comment by zhangzai666** [comment]
you can try 
prompts = [
    f"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n{instruct}<|im_end|>\n<|im_start|>assistant\n"
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95,max_tokens = 2000,stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"])

**Comment by BWZhang-NLP** [comment]
> you can try prompts = [ f"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n{instruct}<|im_end|>\n<|im_start|>assistant\n" ]
> 
> # Create a sampling params object.
> sampling_params = SamplingParams(temperature=0.8, top_p=0.95,max_tokens = 2000,stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"])

It not work,the template and stop_word_list have used.The main problem is there are some differences in the implementation of qwen ntk and vllm ntk.

**Comment by BWZhang-NLP** [comment]
> > you can try prompts = [ f"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n{instruct}<|im_end|>\n<|im_start|>assistant\n" ]
> > # Create a sampling params object.
> > sampling_params = SamplingParams(temperature=0.8, top_p=0.95,max_tokens = 2000,stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"])
> 
> It not work,the template and stop_word_list have used.The main problem is there are some differences between the implementation of qwen ntk and vllm ntk. ps:The problem only occurs when the input tokens exceeds 2048

It works by adding follow param in config.json
"rope_scaling": {
"type": "dynamic",
"factor": 2.0
}

**Comment by ye7love7** [comment]
> > > you can try prompts = [ f"<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n{instruct}<|im_end|>\n<|im_start|>assistant\n" ]
> > > # Create a sampling params object.
> > > sampling_params = SamplingParams(temperature=0.8, top_p=0.95,max_tokens = 2000,stop=["<|im_end|>", "<|endoftext|>", "<|im_start|>"])
> > 
> > 
> > It not work,the template and stop_word_list have used.The main problem is there are some differences between the implementation of qwen ntk and vllm ntk. ps:The problem only occurs when the input tokens exceeds 2048
> 
> It works by adding follow param in config.json "rope_scaling": { "type": "dynamic", "factor": 2.0 }

success,thaks a lot!
