### ISSUE TITLE
Request for Support for Ascend Series Graphics Cards

### ISSUE THREAD

**Issue by junior-zsy** [vllm-project/vllm#1606]
Hello,

I hope this message finds you well. I am writing to kindly request your support for the Ascend series of graphics cards in your project.

As you may be aware, recent geopolitical circumstances have resulted in the inability for developers in China to access NVIDIA graphics cards due to export restrictions from the United States. As a result, many of us have turned to domestically produced alternatives, such as the Ascend series graphics cards, which have proven to be highly capable and efficient.

However, the lack of support for the Ascend series in many projects, including this one, has presented a significant challenge. It would be greatly appreciated if you could consider extending your support to include these graphics cards, thereby enabling us to continue contributing to and benefiting from your project.

I understand that this may require additional resources and effort on your part. To assist you in this endeavor, I have included the link to the official Ascend development resources on GitHub and their official website:

GitHub: https://github.com/Ascend
Official Website: https://www.hiascend.com/en/
These resources provide comprehensive documentation and development tools that should hopefully make the process of integrating support for the Ascend series more straightforward.

I sincerely appreciate your consideration of this request. The support for Ascend series graphics cards would not only benefit developers in China, but also those across the globe who may choose or need to use these cards.

Thank you for your time and understanding. I look forward to your positive response.

**Comment by junior-zsy** [comment]
I am currently learning Ascend C programming to modify the page attention implementation based on NPU in VLLM. However, this will take some time. If you are an official representative of Huawei, I hope you can facilitate the involvement of internal experts to develop logic similar to VLLM page attention based on NPU, as a replacement for the CUDA page attention. Additionally, you could consider providing machine resources to the official VLLM team for debugging and development purposes, if needed. This would allow them to contribute to the development process. Thank you. @Superskyyy  @WoosukKwon

**Comment by xs1997zju** [comment]
Any Update?

**Comment by cason0126** [comment]
@junior-zsy  any Update？
