### ISSUE TITLE
Can S-Lora be integrated into vLLM?

### ISSUE THREAD

**Issue by nivibilla** [vllm-project/vllm#1610]
https://github.com/S-LoRA/S-LoRA

They call it 'unified paging' and don't require the model to be merged before doing inference. This would be really useful for serving Mixture of Expert models for example or a service that requires multiple different fine-tuned lora adapters based on the same base model.

And needless to say there has been a lot of request for lora deployments

**Comment by matankley** [comment]
+1

**Comment by farouqaldori** [comment]
+1

**Comment by BharatSingla12** [comment]
+1

**Comment by GayHub1010** [comment]
+1

**Comment by AmoghM** [comment]
+1

**Comment by DavidPeleg6** [comment]
+1

**Comment by jpeig** [comment]
+2

**Comment by draplater** [comment]
+1

**Comment by wDevil** [comment]
+1

**Comment by dongzhiwen1218** [comment]
+9

**Comment by yuiant** [comment]
+10086

**Comment by nmhjklnm** [comment]
+23333

**Comment by Ted8000** [comment]
+120

**Comment by nivibilla** [comment]
This could possibly be the solution
#1804

**Comment by codybum** [comment]
No API, but an allows for serving of multi-lora: https://github.com/punica-ai/punica

**Comment by hahazei** [comment]
+1

**Comment by simon-mo** [comment]
The integration is complete. https://docs.vllm.ai/en/latest/models/lora.html

**Comment by ashutoshbhushan21** [comment]
Does this handle multiple loras simultaneously for concurrent calls to different lora adaptors like slora ?

**Comment by simon-mo** [comment]
It is exactly S-LoRA with Punica batched gemm kernels. This means concurrent calls of different lora adaptors can be executed in one batch.

**Comment by CodingYuanLiu** [comment]
Hi, how does vLLM manage the weight of LoRA adapters? Does it use unified paging (with KV Cache) like S-LoRA? Thanks!
