### ISSUE TITLE
Why model parallelism doesn't improve performance

### ISSUE THREAD

**Issue by pgarec** [vllm-project/vllm#1611]
If I parallelize an OPT-13b model into two A100 GPUs, the throughput of the serving is worse than using a single A100, eventhough you are doubling the number of GPU blocks available for the KV cache.

**Comment by datascience279** [comment]
facing the same issue with zephyr-7b

**Comment by hmellor** [comment]
Model parallel only improves performance if the cost of running the model sharded across multiple GPUs and the inter-GPU collectives between shards is less than the cost of running the model on a single GPU
