### ISSUE TITLE
2x speedup with IBM foundation stack

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#1615]
They rewrite Llama model definition to be compatible with torch.compile. Completely open source. 

https://github.com/foundation-model-stack/foundation-model-stack

**Comment by WoosukKwon** [comment]
Hi @casper-hansen, thanks for bringing it up. Indeed, we are actively investigating `torch.compile` support.

**Comment by hmellor** [comment]
Closing because `torch.compile` is on the roadmap #2681
