### ISSUE TITLE
Paged attention v2 is slower than v1 on T4 GPU.

### ISSUE THREAD

**Issue by esmeetu** [vllm-project/vllm#1618]
Running 

python benchmarks/kernels/benchmark_paged_attention.py --verion v1

vs

python benchmarks/kernels/benchmark_paged_attention.py --verion v2

v1 output: 1531.001us
v2 output: 1875.677us

And i tested real model scenarios that reflects that v2 is slower than v1 when batch size up to 4(16k ctx len).
@WoosukKwon Could you have T4 gpu to test these?

**Comment by SupreethRao99** [comment]
FlashAttention2 is currently not supported on Turing Class GPU's, which is why it'll be slower that FlashAttention1. Here's the excerpt from the flash attention git repo

> FlashAttention-2 currently supports:
> 
> 1. Ampere, Ada, or Hopper GPUs (e.g., A100, RTX 3090, RTX 4090, H100). Support for Turing GPUs (T4, RTX 2080) is coming soon, please use FlashAttention 1.x for Turing GPUs for now.
> 2. Datatype fp16 and bf16 (bf16 requires Ampere, Ada, or Hopper GPUs).
> 3. All head dimensions up to 256. Head dim > 192 backward requires A100/A800 or H100/H800.

**Comment by esmeetu** [comment]
@SupreethRao99 Thanks for your kindly reply. But i meant Paged attention instead of Flash attention. And i use flashattenv1 default as you said when i benchmarking pagedatten v1 and v2.
