### ISSUE TITLE
Why does this "logits_processors" parameter appear to be missing during operation?(v0.2.1.post1)

### ISSUE THREAD

**Issue by incrementallearning** [vllm-project/vllm#1619]
![image](https://github.com/vllm-project/vllm/assets/56470984/529d8576-3d5f-4d7c-9cd3-4ef1a6506319)

**Comment by simon-mo** [comment]
It has not be released yet. It will be part of v0.2.2. Please feel free to install from source. We are working on release it as soon as we can: https://github.com/vllm-project/vllm/issues/1551
