### ISSUE TITLE
Where is the part related to system prompt?

### ISSUE THREAD

**Issue by rayleizhu** [vllm-project/vllm#1627]
Section 4.4 in the [paper](https://arxiv.org/pdf/2309.06180.pdf) mentioned that you reserved some physic blocks to cope with system prompts; where are the codes for this part?

**Comment by simon-mo** [comment]
We had the code in the original experimental prototype. However, in order to simplify the open source project code, we didn't not ship it in the first iteration. There's recent in progress work on this: #1669, stay tuned!
