### ISSUE TITLE
CPU heavy code in async function _AsyncLLMEngine._run_workers_async blocks the event loop

### ISSUE THREAD

**Issue by dominik-schwabe** [vllm-project/vllm#1629]
The function _AsyncLLMEngine._run_workers_async executes a function on the workers via `getattr(worker, method)` which is cpu bound and blocks the event loop and requests with fastapi for example can not be optimally served.
More specifically, the `_queue` in the created stream object in the following line accumulates a lot of tokens even when reading them as soon as possible leading to the first half of the tokens appearing on the screen one by one and the last half of tokens appearing all almost at the same time once vllm is done handling the request and the event loop is unblocked.
https://github.com/vllm-project/vllm/blob/0d578228ca220c120bb73316c1d35d078a5bd7b1/vllm/engine/async_llm_engine.py#L386

I created a [pull request](https://github.com/vllm-project/vllm/pull/1628) to fix this issue by executing the worker functions in a ThreadPoolExecutor.

**Comment by simon-mo** [comment]
Merged. Thank you for your contribution!

**Comment by dominik-schwabe** [comment]
You're welcome!
Also note that `asyncio.get_event_loop().run_in_executor(None, partial(executor, *args, **kwargs))` can be replaced with `asyncio.to_thread(executor, *args, **kwargs)` once you drop support for Python 3.8.
