### ISSUE TITLE
Why is data stored in 16-byte chunks?

### ISSUE THREAD

**Issue by vedantroy** [vllm-project/vllm#1630]
From reading the test code:
```
        x = 16 // torch.tensor([], dtype=dtype).element_size()
        key_cache_shape = (num_blocks, num_heads, head_size // x, block_size, x)
```
It looks like the purpose of `x` is to partition the innermost data, into chunks of 16 bytes. I'm curious why this is the case.

Is it something to do with the cuda kernels?

**Comment by vedantroy** [comment]
Answer = yes.
```
  // A vector type to store a part of a key or a query.
  // The vector size is configured in such a way that the threads in a thread group
  // fetch or compute 16 bytes at a time.
```

**Comment by Luke20000429** [comment]
So why we load 16 byte at a time? NV cache line size is 128-byte, if we want coalescing within a thread group, we can load 128 byte at a time, if we want coalescing within a warp, we should load 4 byte at a time, why it is 16 bytes?
