### ISSUE TITLE
Support 01-ai/Yi-34B-200K

### ISSUE THREAD

**Issue by ekolawole** [vllm-project/vllm#1632]
Hello vLLM team. When are you adding 01-ai/Yi-34B-200K model support by default?

I know I can add it myself locally, but it will be nice to have it added by default.

**Comment by simon-mo** [comment]
Contribution welcomed!

**Comment by esmeetu** [comment]
@ekolawole refs: #1603. Build main branch which has supported Yi model but new version hasn't been released.
