### ISSUE TITLE
Prompt caching

### ISSUE THREAD

**Issue by AIApprentice101** [vllm-project/vllm#1635]
I saw other folks proposed the feature of caching overlapping prompts for reuse. For example, when the system prompt includes few-shot examples (long), encoding it every request is not efficient.

This newly released paper maybe useful: https://huggingface.co/papers/2311.04934.

**Comment by irasin** [comment]
This paper maybe helpful, https://arxiv.org/pdf/2311.04934.pdf

**Comment by AIApprentice101** [comment]
@irasin we are sharing the same paper lol~

**Comment by irasin** [comment]
@AIApprentice101 Sorry, didn't notice that

**Comment by rayleizhu** [comment]
I think the vLLM authors are aware of this problem because they mentioned it in their [paper] (begin from the end of page 7, and Figure 10)(https://arxiv.org/pdf/2309.06180.pdf). 

However, I need help finding the implementation in their released code.

Related issue: https://github.com/vllm-project/vllm/issues/1627

@WoosukKwon

**Comment by simon-mo** [comment]
We are aware of this new approach and actively evaluating it.

**Comment by linchen111** [comment]
> We are aware of this new approach and actively evaluating it.我们意识到这种新方法并积极评估它。

I also used feed shots in prompt, but it's really slow now

**Comment by bryanhpchiang** [comment]
Any updates here?

**Comment by rayleizhu** [comment]
> > We are aware of this new approach and actively evaluating it.我们意识到这种新方法并积极评估它。
> 
> I also used few shots in prompt, but it's really slow now

This makes sense, as Prompt Cache only helps the **prompt phase**, which prefills the KV Cache and generates the first response token. It cannot help the **autoregressive generation phase**, which is the hot spot of the response generation.

**Comment by hmellor** [comment]
`--enable-prefix-caching`

**Comment by AnaRhisT94** [comment]
> > > We are aware of this new approach and actively evaluating it.我们意识到这种新方法并积极评估它。
> > 
> > 
> > I also used few shots in prompt, but it's really slow now
> 
> This makes sense, as Prompt Cache only helps the **prompt phase**, which prefills the KV Cache and generates the first response token. It cannot help the **autoregressive generation phase**, which is the hot spot of the response generation.
> 
> See how to further improve the efficiency of LLM serving with a long shared system prompt here: [RelayAttention for Efficient Large Language Model Serving with Long System Prompts](https://openreview.net/forum?id=G1hjFDre0NF)
> 
> @simon-mo Do you consider integrating RelayAttention into vLLM? If yes, I will be glad to participate.

How is this better than just hashing the prefixes which is the simplest approach?

**Comment by rayleizhu** [comment]
> > > > We are aware of this new approach and actively evaluating it.我们意识到这种新方法并积极评估它。
> > > 
> > > 
> > > I also used few shots in prompt, but it's really slow now
> > 
> > 
> > This makes sense, as Prompt Cache only helps the **prompt phase**, which prefills the KV Cache and generates the first response token. It cannot help the **autoregressive generation phase**, which is the hot spot of the response generation.
> > See how to further improve the efficiency of LLM serving with a long shared system prompt here: [RelayAttention for Efficient Large Language Model Serving with Long System Prompts](https://openreview.net/forum?id=G1hjFDre0NF)
> > @simon-mo Do you consider integrating RelayAttention into vLLM? If yes, I will be glad to participate.
> 
> How is this better than just hashing the prefixes which is the simplest approach?
> 
> What's the difference in performance when enable-prefix-caching is used vs your approach?

Prefix caching avoids the redundant **re-computations and storage** of system KVs. However, the system KVs **are still read multiple times during computation**, which is exactly the problem that RelayAttention aims to solve.

**Comment by AlbertoCastelo** [comment]
Is there any work planned here? Prompt caching would be super useful for my use-case

**Comment by zengqingfu1442** [comment]
How to enable prompt caching when using vllm to serve models? Thanks.

**Comment by zengqingfu1442** [comment]
> [@zengqingfu1442](https://github.com/zengqingfu1442) Kindly check the option mentioned below:
> 
> https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html
> 
> ![Image](https://github.com/user-attachments/assets/584b48c9-c387-4c8f-90b9-abe2911b32b2)

Does "--enable-prefix-caching" would only cache system prompt(not incuding user prompt)?
