### ISSUE TITLE
Add support to core42/jais-13b-chat

### ISSUE THREAD

**Issue by almersawi** [vllm-project/vllm#1638]
Can vLLM support jais model?

**Comment by SamujjwalSam** [comment]
Here's a fork of the original repo with Jais support: https://github.com/SamujjwalSam/vllm-jais/tree/jais
I could not create a pull request as I could make it work only with `vLLM-v0.2.1-post1`.

**Comment by esmeetu** [comment]
Close this as https://github.com/vllm-project/vllm/pull/3183 has supported. And will release in v0.3.4.
