### ISSUE TITLE
SSL Certificate Verification Error Openai 1.2.3 client with vllm openai compatible api

### ISSUE THREAD

**Issue by zekrismh** [vllm-project/vllm#1644]
**Description**:

I am encountering an issue when attempting to use the official OpenAI client with the VLLM OpenAI-compatible API. Specifically, when trying to connect to the API using the official OpenAI client with versions greater than 1.0.0, I consistently receive the following error:
`
httpcore.connection:starttls.failed exception=ConnectError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))`
**Details**:

Issue Type: Bug
API Client: Official OpenAI client
Error Version: OpenAI > 1.0.0
Error Message: httpcore.connection:starttls.failed exception=ConnectError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)'))
**Additional Information:**

- The error does not occur with OpenAI versions <= 0.28.1, and the connection works perfectly in those cases.
- The issue seems to be related to SSL certificate verification.

**Steps to Reproduce:**

- Use the official OpenAI client > 1.0.0.
- Connect to the VLLM OpenAI-compatible API.

**Expected Behavior:**

I expect the OpenAI API connection to work without SSL certificate verification errors, even with versions greater than 1.0.0.

**Environment:**

Operating System: MACOS
Python Version:3.8.6
OpenAI Client Version: 1.2.3

**Note:** If you have any insights or solutions to this issue, please feel free to share. I appreciate your assistance in resolving this problem.

**Comment by simon-mo** [comment]
Can you share your openai client configuration snippet? Did you add use http instead of https? The vLLM OpenAI compatible server is running on http without certificate. `openai.api_base = "http://localhost:8000/v1"`

**Comment by zekrismh** [comment]
The latest version of openai work like below : 

`api_key = "EMPTY"
api_base = "https://genai-llm-inference-job-llama70b.maxikube.ca.cib/v1/"
model = "/data/volume/.cache/huggingface/hub/models--meta-llama--Llama-2-70b-chat-hf/snapshots/36d9a7388cc80e5f4b3e9701ca2f250d21a96c30"


from openai import OpenAI


client = OpenAI(api_key=api_key, base_url=api_base)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model=model,
)`

I'll try with HTTP instead of HTTPS

**Comment by simon-mo** [comment]
Yeah it definitely looks like the https being the issue here.
