### ISSUE TITLE
Triton Server Example does not work

### ISSUE THREAD

**Issue by rguo123** [vllm-project/vllm#1647]
Hi,
I run into this issue when following the triton inference tutorial with vllm here:
https://github.com/triton-inference-server/tutorials/tree/main/Quick_Deploy/vLLM

I'm running on a AWS Ubuntu machine with this default [image](https://aws.amazon.com/releasenotes/aws-deep-learning-ami-gpu-pytorch-2-0-amazon-linux-2/) on an A10 GPU. 

`UNAVAILABLE: Internal: AssertionError: vLLM Triton backend must be configured to use decoupled model transaction policy`

Thank you

**Comment by rguo123** [comment]
Ah on further digging:
https://github.com/triton-inference-server/vllm_backend/pull/20

It's because this autocomplete isn't actually being called so `config.pbtxt` is not set up correctly.
So using the old `config.pbtxt` seems to have fixed this

**Comment by tanmayv25** [comment]
The auto-complete feature is currently available only on triton's main branch that tracks development to a future release. The auto-complete functionality will be available with 23.11 release which is scheduled to be released by end of the month.
Thanks for your patience.

**Comment by guialfaro053** [comment]
> The auto-complete feature is currently available only on triton's main branch that tracks development to a future release. The auto-complete functionality will be available with 23.11 release which is scheduled to be released by end of the month. Thanks for your patience.

Thanks @tanmayv25 for your work. It is truly amazing and blazingly fast! Is it normal that all Mistral-based models when ran on Trinton-AWQ server, run out of memory? It has happened in all my experiments but not for any Llama-based models.

**Comment by tanmayv25** [comment]
@guialfaro053 Which GPU are you using? What is `gpu_memory_utilization` setting in your `model.json`?
We have been able to run Mistral models within Triton + vLLM backend.

**Comment by guialfaro053** [comment]
@tanmayv25 I am using an RTX4090 24gb and my `gpu_memory_utilization` is 0.5. But even if i change that parameter to 0.9 or 0.1, the same allocation error occurs so maybe my installation process is wrong? I am using the 23.10 image and then I update I `pip install vllm==0.2.2` for Mistral support.

**Comment by guialfaro053** [comment]
@tanmayv25 Yes, outside Triton, I have no issues. 

> That is directly in a python script?

I basically just run the server in the entrypoints/openai directory and everything is okay, but when I follow the Triton-vLLM backend tutorial I get OOM.
