### ISSUE TITLE
usage of vllm for extracting embeddings

### ISSUE THREAD

**Issue by ra-MANUJ-an** [vllm-project/vllm#1654]
Following is a little piece of code to extract embeddings from a certain layer of LLM:
```
def process_row(prompt: str, model, tokenizer, layers_to_use: list, remove_period: bool):
    """
    Processes a row of data and returns the embeddings.
    """
    if remove_period:
        prompt = prompt.rstrip(". ")
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        outputs = model.generate(inputs.input_ids, output_hidden_states=True, return_dict_in_generate=True, max_new_tokens=1, min_new_tokens=1)
    embeddings = {}
    for layer in layers_to_use:
        last_hidden_state = outputs.hidden_states[0][layer][0][-1]
        embeddings[layer] = [last_hidden_state.numpy().tolist()]
    return embeddings
```
It's pretty standard way, but it's pretty slow. Is there any way to use vllm to make it faster without needing to call generate function everytime? I've tried batching, but it's slow too. Any help is appreciated!

**Comment by WuNein** [comment]
Similarly, for me, I need to extract the last hidden state of the model. But it seems difficult to do, especially i need to modify the worker.py to get better performance. (KVcache ,etc)
```
class OPTModel(nn.Module):

    def __init__(self, config: OPTConfig):
        super().__init__()
        self.decoder = OPTDecoder(config)

    def forward(
        self,
        input_ids: torch.Tensor,
        positions: torch.Tensor,
        kv_caches: List[KVCache],
        input_metadata: InputMetadata,
        cache_events: Optional[List[torch.cuda.Event]],
    ) -> torch.Tensor:
        return self.decoder(input_ids, positions, kv_caches, input_metadata,
                            cache_events) # i need this
```

**Comment by ra-MANUJ-an** [comment]
> Similarly, for me, I need to extract the last hidden state of the model. But it seems difficult to do, especially i need to modify the worker.py to get better performance. (KVcache ,etc)
> 
> ```
> class OPTModel(nn.Module):
> 
>     def __init__(self, config: OPTConfig):
>         super().__init__()
>         self.decoder = OPTDecoder(config)
> 
>     def forward(
>         self,
>         input_ids: torch.Tensor,
>         positions: torch.Tensor,
>         kv_caches: List[KVCache],
>         input_metadata: InputMetadata,
>         cache_events: Optional[List[torch.cuda.Event]],
>     ) -> torch.Tensor:
>         return self.decoder(input_ids, positions, kv_caches, input_metadata,
>                             cache_events) # i need this
> ```

So, does that work? Are you able to make it faster?

**Comment by WuNein** [comment]
> > Similarly, for me, I need to extract the last hidden state of the model. But it seems difficult to do, especially i need to modify the worker.py to get better performance. (KVcache ,etc)
> > ```
> > class OPTModel(nn.Module):
> > 
> >     def __init__(self, config: OPTConfig):
> >         super().__init__()
> >         self.decoder = OPTDecoder(config)
> > 
> >     def forward(
> >         self,
> >         input_ids: torch.Tensor,
> >         positions: torch.Tensor,
> >         kv_caches: List[KVCache],
> >         input_metadata: InputMetadata,
> >         cache_events: Optional[List[torch.cuda.Event]],
> >     ) -> torch.Tensor:
> >         return self.decoder(input_ids, positions, kv_caches, input_metadata,
> >                             cache_events) # i need this
> > ```
> 
> So, does that work? Are you able to make it faster?

No! It has error or not init worker! the worker is too complex

**Comment by ra-MANUJ-an** [comment]
> > > Similarly, for me, I need to extract the last hidden state of the model. But it seems difficult to do, especially i need to modify the worker.py to get better performance. (KVcache ,etc)
> > > ```
> > > class OPTModel(nn.Module):
> > > 
> > >     def __init__(self, config: OPTConfig):
> > >         super().__init__()
> > >         self.decoder = OPTDecoder(config)
> > > 
> > >     def forward(
> > >         self,
> > >         input_ids: torch.Tensor,
> > >         positions: torch.Tensor,
> > >         kv_caches: List[KVCache],
> > >         input_metadata: InputMetadata,
> > >         cache_events: Optional[List[torch.cuda.Event]],
> > >     ) -> torch.Tensor:
> > >         return self.decoder(input_ids, positions, kv_caches, input_metadata,
> > >                             cache_events) # i need this
> > > ```
> > 
> > 
> > So, does that work? Are you able to make it faster?
> 
> No! It has error of not init worker! the worker is too complex

well, ok! let's see if someone has solved the problem

**Comment by WuNein** [comment]
I made a solution, without changing the library, i can run. But i cannot certain it can accerate.
```
from vllm import LLM, SamplingParams
llm = LLM(model="/root/hdd/llm/opt-1.3b")
from vllm.sequence import (SamplerOutput, Sequence, SequenceGroup,
                           SequenceGroupMetadata, SequenceGroupOutputs,
                           SequenceOutputs, SequenceStatus)

prompt = 'I am a'

prompt_token_ids = llm.llm_engine.tokenizer.encode(prompt)
block_size = llm.llm_engine.cache_config.block_size
seq_id = next(llm.llm_engine.seq_counter)
seq = Sequence(seq_id, prompt, prompt_token_ids, block_size)
request_id = str(next(llm.request_counter))
# Create the sequence group.
seq_group = SequenceGroup(request_id, [seq], sampling_params,
                            None)
from vllm.sequence import SamplerOutput, SequenceData, SequenceGroupMetadata
import torch
torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

# Profile memory usage with max_num_sequences sequences and the total
# number of tokens equal to max_num_batched_tokens.

# Enable top-k sampling to reflect the accurate memory usage.
vocab_size = llm.llm_engine.workers[0].model.config.vocab_size
sampling_params = SamplingParams(top_p=0.99, top_k=vocab_size - 1)
max_num_batched_tokens = llm.llm_engine.workers[0].scheduler_config.max_num_batched_tokens
max_num_seqs = llm.llm_engine.workers[0].scheduler_config.max_num_seqs

prompt = 'I am a'

prompt_token_ids = llm.llm_engine.tokenizer.encode(prompt) #[2, 100, 524, 10]

seqs = []
# for group_id in range(max_num_seqs):
#     seq_len = (max_num_batched_tokens // max_num_seqs +
#                 (group_id < max_num_batched_tokens % max_num_seqs))
#     print(seq_len)
group_id = 1
seq_data = SequenceData(prompt_token_ids)
seq = SequenceGroupMetadata(
    request_id=str(group_id),
    is_prompt=True,
    seq_data={group_id: seq_data},
    sampling_params=sampling_params,
    block_tables=None,
)
seqs.append(seq)

input_tokens, input_positions, input_metadata = llm.llm_engine.workers[0]._prepare_inputs(
    seqs)
# Execute the model.
num_layers = llm.llm_engine.workers[0].model_config.get_num_layers(llm.llm_engine.workers[0].parallel_config)
tempOut = llm.llm_engine.workers[0].model.model(
    input_ids=input_tokens,
    positions=input_positions,
    kv_caches=[(None, None)] * num_layers,
    input_metadata=input_metadata,
    cache_events=None,
)
tempOut.size() #torch.Size([1, 4, 2048])
```

![image](https://github.com/vllm-project/vllm/assets/84025979/287a7dbf-2028-4808-a6a0-f5f98259f5cd)

If you improve this code, share with me !

**Comment by bondoo-winston** [comment]
@WuNein using your code, is there any way I can also extract the output tokens along with the embeddings?  With vllm, I'm running model.generate(...) and getting different number of output tokens. For an example prompt, I'm getting 125 output tokens, with vllm's model.generate(...). However, with your approach, the dimensions of my output embedding are 108, 5120, which does not make sense

**Comment by PoohTheWinnie** [comment]
@WuNein using your code, is there any way I can also extract the output tokens along with the embeddings? With vllm, I'm running model.generate(...) and getting different number of output tokens. For an example prompt, I'm getting 125 output tokens, with vllm's model.generate(...). However, with your approach, the dimensions of my output embedding are 108, 5120, which does not make sense

**Comment by WuNein** [comment]
> @WuNein using your code, is there any way I can also extract the output tokens along with the embeddings? With vllm, I'm running model.generate(...) and getting different number of output tokens. For an example prompt, I'm getting 125 output tokens, with vllm's model.generate(...). However, with your approach, the dimensions of my output embedding are 108, 5120, which does not make sense

I made a demo, check it out.
https://github.com/WuNein/vllm4mteb

**Comment by ra-MANUJ-an** [comment]
> I made a solution, without changing the library, i can run. But i cannot certain it can accerate.
> 
> ```
> from vllm import LLM, SamplingParams
> llm = LLM(model="/root/hdd/llm/opt-1.3b")
> from vllm.sequence import (SamplerOutput, Sequence, SequenceGroup,
>                            SequenceGroupMetadata, SequenceGroupOutputs,
>                            SequenceOutputs, SequenceStatus)
> 
> prompt = 'I am a'
> 
> prompt_token_ids = llm.llm_engine.tokenizer.encode(prompt)
> block_size = llm.llm_engine.cache_config.block_size
> seq_id = next(llm.llm_engine.seq_counter)
> seq = Sequence(seq_id, prompt, prompt_token_ids, block_size)
> request_id = str(next(llm.request_counter))
> # Create the sequence group.
> seq_group = SequenceGroup(request_id, [seq], sampling_params,
>                             None)
> from vllm.sequence import SamplerOutput, SequenceData, SequenceGroupMetadata
> import torch
> torch.cuda.empty_cache()
> torch.cuda.reset_peak_memory_stats()
> 
> # Profile memory usage with max_num_sequences sequences and the total
> # number of tokens equal to max_num_batched_tokens.
> 
> # Enable top-k sampling to reflect the accurate memory usage.
> vocab_size = llm.llm_engine.workers[0].model.config.vocab_size
> sampling_params = SamplingParams(top_p=0.99, top_k=vocab_size - 1)
> max_num_batched_tokens = llm.llm_engine.workers[0].scheduler_config.max_num_batched_tokens
> max_num_seqs = llm.llm_engine.workers[0].scheduler_config.max_num_seqs
> 
> prompt = 'I am a'
> 
> prompt_token_ids = llm.llm_engine.tokenizer.encode(prompt) #[2, 100, 524, 10]
> 
> seqs = []
> # for group_id in range(max_num_seqs):
> #     seq_len = (max_num_batched_tokens // max_num_seqs +
> #                 (group_id < max_num_batched_tokens % max_num_seqs))
> #     print(seq_len)
> group_id = 1
> seq_data = SequenceData(prompt_token_ids)
> seq = SequenceGroupMetadata(
>     request_id=str(group_id),
>     is_prompt=True,
>     seq_data={group_id: seq_data},
>     sampling_params=sampling_params,
>     block_tables=None,
> )
> seqs.append(seq)
> 
> input_tokens, input_positions, input_metadata = llm.llm_engine.workers[0]._prepare_inputs(
>     seqs)
> # Execute the model.
> num_layers = llm.llm_engine.workers[0].model_config.get_num_layers(llm.llm_engine.workers[0].parallel_config)
> tempOut = llm.llm_engine.workers[0].model.model(
>     input_ids=input_tokens,
>     positions=input_positions,
>     kv_caches=[(None, None)] * num_layers,
>     input_metadata=input_metadata,
>     cache_events=None,
> )
> tempOut.size() #torch.Size([1, 4, 2048])
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/84025979/283500632-287a7dbf-2028-4808-a6a0-f5f98259f5cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NjcwMjMsIm5iZiI6MTcxMDY2NjcyMywicGF0aCI6Ii84NDAyNTk3OS8yODM1MDA2MzItMjg3YTdkYmYtMjAyOC00ODA4LWE2YTAtZjVmOTgyNTlmNWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5MTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZDA4YjBmZWI4OTAyNWUzY2UzZmI5ZDA0YzgzYWEwMDE5Y2MxYTVlMjgxNjQxZDhjNWExNWZiMWI4YmYxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yqQhTXkJpdJcbUG_eMTdxikIxWz-Nd3slWkqCaO3dIc)
> 
> I check the answer ![image](https://private-user-images.githubusercontent.com/84025979/283667733-a67de89b-7780-4da9-bd31-50d1559ad3b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NjcwMjMsIm5iZiI6MTcxMDY2NjcyMywicGF0aCI6Ii84NDAyNTk3OS8yODM2Njc3MzMtYTY3ZGU4OWItNzc4MC00ZGE5LWJkMzEtNTBkMTU1OWFkM2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA5MTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjN2Q2ZTFhYTBlZWM5YWE5ODQ5Njk1YzdkMDk0YzBiYzY5YmU5NzAyZGQ3NDI4Y2I0OTE0MmUxYmMxYzFjYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Kh4FPY3AWSUV4GqtDFLh5UP6gEwuFssjFhlBZm89EY) the cos sim showed, they are the same.
> 
> If you improve this code, share with me !

Hi @WuNein, this code will probably provide the last hidden state, is there any way to get values of intermediate hidden states?

**Comment by WuNein** [comment]
@ra-MANUJ-an  https://github.com/vllm-project/vllm/blob/abfc4f3387c436d46d6701e9ba916de8f9ed9329/vllm/model_executor/models/llama.py#L274

May have, you should try, https://github.com/WuNein/vllm4mteb/blob/main/vllm-new.py

My code for newer version is here.

Maybe star for me.

**Comment by ra-MANUJ-an** [comment]
@WuNein Thanks for taking time to write the code properly, but how are you implementing hidden_states with your following code:

[outputs = engine.driver_worker.model_runner.model(input_ids=input_tokens,
        positions=input_positions,
        kv_caches=[(None, None)] * num_layers,
        input_metadata=input_metadata)](https://github.com/WuNein/vllm4mteb/blob/28f56ba833ccbf9b782a06b64716a8c7e39f6537/vllm-new.py#L29)

**Comment by ra-MANUJ-an** [comment]
@WuNein Hi, if you have time, could you please answer the above question?

**Comment by WuNein** [comment]
> @WuNein Hi, if you have time, could you please answer the above question?

There may not any solution if the hidden state do not have intermediate states.

I don't have the requirement to get the intermediate states.
