### ISSUE TITLE
Stuck loading model

### ISSUE THREAD

**Issue by jpeig** [vllm-project/vllm#1660]
When I boot the API server:

`python3 -m vllm.entrypoints.openai.api_server --port 9999 --dtype half --trust-remote-code --host 127.0.0.1
`
The API spins up in 10 seconds.

However when I download a model or load one locally:

`python3 -m vllm.entrypoints.openai.api_server --port 9999 --model TheBloke/Mistral-7B-Instruct-v0.1-AWQ -q awq --dtype half --trust-remote-code --host 127.0.0.1
`
My PC slows down and loading takes forever.

I'm using a 3090 and WSL. What could be the issue here?

**Comment by jpeig** [comment]
As I am loading the model, my WSL client consumes 72gig of RAM, some kind of memory leak is going on.

Name: torch
Version: 2.1.0+cu118

Name: xformers
Version: 0.0.22.post7+cu118

**Comment by siyuyuan** [comment]
i have the same issue

**Comment by simon-mo** [comment]
Thanks for opening. Sorry that we do not have the hardware to reproduce and debug this issue (WSL + 3090). We can load the model on A100 and L4 so it's going to be difficult to debug. 

Does any have clues about this? Can you try `py-spy` to profile the processes to see whether it is stuck or just loading very slowly.

**Comment by marianbastiUNRN** [comment]
I'm spinning up unquantized models no problem on WSL+3090
```python3 -m vllm.entrypoints.openai.api_server --model openchat/openchat_3.5 --dtype half```

But when I try to load quantized AWQ models, my WSL crashes with no error message. I can see the model loading into the GPU

System info:

- OS: Windows 10
- Installed and running on WSL2
- CPU: AMD Ryzen 9 5900X
- GPU: EVGA RTX3090 24g
- RAM: 32gb
