### ISSUE TITLE
API Server Performance

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#1677]
During benchmarking, we discovered there are performance gaps in both the API server and AsyncLLM engine where the request latency and throughput do not match a hand written gRPC server. 

I'm planning to investigate this. The clues are:
* Slowdown in the asyncio loop due to implementation to support streaming
* Blocking call in the asyncio loop, which have trouble offloading requests, this should be resolved by the threading PR. #1628 but we should benchmark it. 
* The FastAPI + uvicorn is single threaded. 

cc @WoosukKwon @zhuohan123

**Comment by simon-mo** [comment]
A simple py-spy profile didn't review anything too suspicious 
<img width="1716" alt="image" src="https://github.com/vllm-project/vllm/assets/21118851/84f37887-a582-43c4-809a-29085b5b8772">

One hypothesis is the time it takes to `_schedule` and sampling, which is on the main thread blocking networking. I think it is pretty significant overhead, about 0.5ms is spent per decode and blocking the network thread. 
```
schedule_time_us: 118, execute_time: 7664, postprocess_time_us: 409
```

**Comment by vishal09vns** [comment]
Hi ,
`AsyncLLMEngine.generate` is not producing the output in streaming way as done with transformer's `model.generate`. On using "AsyncLLMEngine.generate" the arrival of first token is taking so much time after that all tokens are coming very fast. Can anyone explain why is this happening.

Here is my code.

```python

    engine = AsyncLLMEngine.from_engine_args(engine_args)
    results_generator = engine.generate(prompt, sampling_params, request_id)

    # Streaming case
    async def stream_results() -> AsyncGenerator[bytes, None]:
        previous_text = [""]*n
        async for request_output in results_generator:
            text_outputs = [output.text for output in request_output.outputs]

            # returning only single output
            extra_text = text_outputs[0][len(previous_text[0]):]
            previous_text = text_outputs
            yield extra_text.encode("utf-8")

    if stream:
        return StreamingResponse(stream_results(), media_type='text/event-stream')

```
`async for request_output in results_generator:` loop is delaying the first token by large amount (Around 8 to 10 sec).

**Comment by knagrecha** [comment]
This may explain discrepancy in results of benchmarks between vLLM and DS-FastGen? their benchmarks use the persistent client mode; as far as I know, the vLLM benchmarks use llm.generate() instead.

**Comment by REIGN12** [comment]
Is there any updates for this issue:-)

**Comment by mgoin** [comment]
This has been resolved by https://github.com/vllm-project/vllm/pull/6883, RFC that tracked this https://github.com/vllm-project/vllm/issues/6797
