### ISSUE TITLE
vllm support torch==2.1.0 version cu11.8?

### ISSUE THREAD

**Issue by zzflybird** [vllm-project/vllm#1680]
I don't see a vllm package in torch cu118 in the [URL](https://download.pytorch.org/whl/cu118)

**Comment by yanxiyue** [comment]
torch 2.10 dost not support suda 11.8, shoud be 12+

**Comment by zzflybird** [comment]
> torch 2.10 dost not support suda 11.8, shoud be 12+

ok. : )

**Comment by esmeetu** [comment]
I successfully installed `vllm` with `torch==2.1.1+cu118` from source.

System info:
- Ubuntu 20.04
- cuda driver version: 535(support cuda 12.2)
- cuda toolkit: 11.8

Here is the guideline:
```shell
# 1. install torch
pip install torch --index-url https://download.pytorch.org/whl/cu118
# 2. install requirements
pip install -r requirements.txt
# 3. install packaging in pyproject.toml which not presented in requirements.txt
pip install packaging
# 4. install vllm from source with --no-build-isolation
pip install -e . --no-build-isolation
```
Finnaly you will get vllm==0.2.1+cu118.
@WoosukKwon @zhuohan123 Should we add this in document page or README? If so, i will submit a PR.

**Comment by xiaoduozhou** [comment]
> I successfully installed `vllm` with `torch==2.1.2+cu118` from source.
> 
> System info:
> 
> * Ubuntu 20.04
> * cuda driver version: 535(support cuda 12.2)
> * cuda toolkit: 11.8
> 
> I cannt install `vllm` using `pip install -e .` directly.
> 
> Here is the guideline to install bypass cuda error:
> 
> ```shell
> # 1. install torch xformers(confirm version is the same as defined in requirement.txt)
> pip install torch==2.1.2 xformers==0.0.23.post1 --index-url https://download.pytorch.org/whl/cu118
> # 2. install vllm requirements
> pip install -r requirements.txt
> # 3. install vllm from source with --no-build-isolation
> pip install -e . --no-build-isolation
> ```
> 
> Finnaly you will get vllm==0.2.6+cu118. @WoosukKwon @zhuohan123 Should we add this in document page or README? If so, i will submit a PR.

good ,  I successfully installed it this way.
