### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by UncleFB** [vllm-project/vllm#1681]
1. docker run --gpus all -it --rm --ipc=host nvcr.io/nvidia/pytorch:22.12-py3
2. pip install vllm
![image](https://github.com/vllm-project/vllm/assets/38581531/eb61d60f-d7bc-4ae9-af8e-5d514ae6b529)
When i start a server, there is an error.
![image](https://github.com/vllm-project/vllm/assets/38581531/f90cecec-5c6b-47f1-ba52-0a667e363c82)

**Comment by rbao2018** [comment]
Please try to install vllm in nvcr.io/nvidia/pytorch:22.05-py3, that image works for me.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
