### ISSUE TITLE
In Qwen-14B, using vllm for reasoning with long prompts yields poor results | 在Qwen-14B中，使用vllm对long prompt进行推理，效果很差

### ISSUE THREAD

**Issue by Klein73** [vllm-project/vllm#1683]
Hello, I have modified qwen-14B using PI to support long text inference.
The validation of the HF model has been completed and the results are okay.
However, when using vllm inference, the answers for long prompts are far from the answers generated by the HF model, and they are not coherent (the answers for short prompts are normal).
For example, when I ask a summarization question, the HF model can provide a proper summary, but the vllm answer looks something like this:
"Reasonable use. And, the plaintiff, and the defendant (Caesar, reconciliatory)."
(It is basically gibberish)
I have checked other issues and tried adjusting parameters like max_tokens, top_k, and top_p (keeping them consistent with HF's settings), but the conclusion remains the same.
I would like to know if vllm currently does not support long text inference, or if it does not support the modified qwen-14B with linear interpolation, or if there is an issue with my usage.

-------------------------------------

你好，我使用PI对qwen-14B进行了改造，使其可以支持长文本推理。
HF模型的验证已经完成，效果是ok的。
但是使用vllm推理时，长prompt回答与HF模型的回答相差甚远，基本不说人话了（短prompt的回答是正常的）。

例如我询问一个总结性的问题，HF模型可以正常总结，vllm回答类似这样：
“合理使用。并且，起诉人，以及原告（凯撒，和解性，被告。”
（基本是在胡言乱语）

我查看了其他的issue，对max_tokens，top_k，top_p等参数进行了设置（与HF的设置保持了一致），结论依然同上。

请问是vllm目前确实不支持长文本推理，还是说不支持线性插值改造后的qwen-14B，还是说我使用的有问题呢

**Comment by JustinYuu** [comment]
可能要确认一下Qwen这些中文LLM和vicuna这些英文LLM的prompt格式和eos token是否一致

**Comment by Klein73** [comment]
> 可能要确认一下Qwen这些中文LLM和vicuna这些英文LLM的prompt格式和eos token是否一致

短文本prompt效果是ok的，所以我理解这些设定都没问题。目前就是不确定是vllm本身不支持长文本，还是由于我对qwen进行了PI的改造，导致vllm不支持改造后的qwen。

**Comment by yanxiyue** [comment]
> > 可能要确认一下Qwen这些中文LLM和vicuna这些英文LLM的prompt格式和eos token是否一致
> 
> 短文本prompt效果是ok的，所以我理解这些设定都没问题。目前就是不确定是vllm本身不支持长文本，还是由于我对qwen进行了PI的改造，导致vllm不支持改造后的qwen。

大概率是的，你可以对比一下模型适配层的实现

**Comment by MRKINKI** [comment]
多长的文本？

**Comment by Klein73** [comment]
> 多长的文本？

2000多token效果就很不好了，6000多，9000多token也都测过，都不好

**Comment by ericzhou571** [comment]
> > 多长的文本？
> 
> 2000多token效果就很不好了，6000多，9000多token也都测过，都不好

同样的问题，蹲一个，导致qwen一直没办法替代百川

**Comment by zjupeter** [comment]
请问题主，问题解决了吗？我遇到了相同的问题。我是直接使用原qwen-14B，没做任何改造，对长prompt（3500+token）的回答也不对，直接输出结束符了。不使用vllm，或对短的prompt，或qwen-7B + vllm + 长prompt，都没问题。

> > 可能要确认一下Qwen这些中文LLM和vicuna这些英文LLM的prompt格式和eos token是否一致
> 
> 短文本prompt效果是ok的，所以我理解这些设定都没问题。目前就是不确定是vllm本身不支持长文本，还是由于我对qwen进行了PI的改造，导致vllm不支持改造后的qwen。

**Comment by heyblackC** [comment]
我提交了vllm支持Qwen-14b长上下文的bug fix代码，请看这个pull request：[https://github.com/vllm-project/vllm/pull/1746](url)
