### ISSUE TITLE
using vllm to answer in Qwen-7B-Chat, there is a recurring issue of answers being repeated multiple times,

### ISSUE THREAD

**Issue by shujun1992** [vllm-project/vllm#1694]
When using vllm to answer in Qwen-7B-Chat, there is a recurring issue of answers being repeated multiple times, which is not present when not using vllm.

GPU: 2  T4
MODEL: Qwen-7B-Chat
PROMPT:  <指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 \n\"根据已知信息无法回答该问题，请使用随手拍进行提问，随手拍使用路径：手机移动办公-工作台-数字直通车\"。不允许在答案中添加编造成分，答案请使用中文，结果以markdown的形式输出。</指令>\n\n<已知信息>问题：是否可以先开户、后面再补上门核实和法人开户意愿核实工作？ 答案：上门核实可以后补，法人开户意愿核实需要提前或同步完成。\n问题：客户签约财资需要哪几个步骤（大步骤，具体的步骤可以参考操作文档） 答案：1、客户确认签约财资的方案；\n2、上级单位与下级单位完成账户使用授权（如无下级单位或关联单位，则跳过这一步）；\n3、在前台签署相关协议，录入系统；\n4、经办行引导客户登录财资，并协助客户配置相关设置及参数；\n问题：营业执照刚刚注册好，工商系统还查不到，能开户吗？ 答案：在风险可控的情况下，确定客户开户信息真实，可以开户。</已知信息>\n\n<问题>企业开户流程</问题>

**Comment by shujun1992** [comment]
INFO 11-20 08:54:05 async_llm_engine.py:370] Received request 8b2eab1b928747abb9d544a6b2a5a37a: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 \n"根据已知信息
无法回答该问题，请使用随手拍进行提问，随手拍使用路径：手机移动办公-工作台-数字直通车"。不允许在答案中添加编造成分，答案请使用中文，结果以markdown的形式输出。</指令>\n\n<已知信息>问题：是否可以先开户、后面再补上门核实和法人开户意愿核实工作？ 答案：上门核实可以后补，法人开户意愿核实需要提前或同步完成。\n问题：客户签约财资需要哪几个步骤（大步骤，具体的步骤可以参考操作文档） 答案：1、客户确认签约财资的方案；\n2、上级单位与下级单位完成账户使用授权（如无下级单位或关联单位，则跳过这一步）；\n3、在前台签署相关协议，录入系统；\n4、经办行引导客户登录财资，并协助客户配置相关设置及参数；\n问题：营业执照刚刚注册好，工商系统还查不到，能开户吗？ 答案：在风险可控的情况下，确定客户开户信息真实，可以开户。</已知信息>\n\n<问题>企业开户流程</问题><|im_end|>\n<|im_start|>assistant\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|im_start|>', '<|endoftext|>', '<|im_end|>'], ignore_eos=False, max_tokens=7908, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.2023-11-20 08:54:05 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
INFO 11-20 08:54:05 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 9.4%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:10 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 13.6%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:15 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 18.3%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:20 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 22.5%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:25 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 27.2%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:30 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 31.4%, CPU KV cache usage: 0.0%
2023-11-20 08:54:31 | INFO | model_worker | Send heart beat. Models: ['Qwen-7B-Chat']. Semaphore: Semaphore(value=4, locked=False). call_ct: 1. worker_id: bc0bc8a3. 
2023-11-20 08:54:31 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-11-20 08:54:31 | INFO | stdout | INFO:     127.0.0.1:57204 - "POST /receive_heart_beat HTTP/1.1" 200 OK
INFO 11-20 08:54:36 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 35.6%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:41 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 40.3%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:46 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 44.5%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:51 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 48.7%, CPU KV cache usage: 0.0%
INFO 11-20 08:54:56 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 26.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 53.4%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:01 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 57.6%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:06 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 61.8%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:11 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 66.0%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:16 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 70.2%, CPU KV cache usage: 0.0%
2023-11-20 08:55:16 | INFO | model_worker | Send heart beat. Models: ['Qwen-7B-Chat']. Semaphore: Semaphore(value=4, locked=False). call_ct: 1. worker_id: bc0bc8a3. 
2023-11-20 08:55:16 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-11-20 08:55:16 | INFO | stdout | INFO:     127.0.0.1:57220 - "POST /receive_heart_beat HTTP/1.1" 200 OK
INFO 11-20 08:55:21 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 74.3%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:26 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 78.5%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:31 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 82.7%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:36 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 86.9%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:41 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 91.1%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:46 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 95.3%, CPU KV cache usage: 0.0%
INFO 11-20 08:55:51 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 25.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 99.5%, CPU KV cache usage: 0.0%

**Comment by zhanpengjie** [comment]
same problem

**Comment by stannum2** [comment]
Same problem, have you solved it?
