### ISSUE TITLE
pip install vllm vs pip install -e .

### ISSUE THREAD

**Issue by qy1026** [vllm-project/vllm#1697]
I've noticed that the way of installing vllm will lead to different codes.

With  "pip install vllm", the vllm version will be vllm-0.2.1.post1 and there is no parameter named "repetition_penalty" in sampling_params.py;  

while actually there is "repetition _penalty" parameter in the lateset repo.

**Comment by simon-mo** [comment]
`pip install -e .` install from the main branch, which is ahead of the latest release `vllm-0.2.1.post1`. We are release 0.2.2 here #1551
