### ISSUE TITLE
baichuan2-13b A10 deploy

### ISSUE THREAD

**Issue by 77h2l** [vllm-project/vllm#1698]
hi there, I wonder how can users deploy a baichuan2-13b model on a single A10 gpu server, due to the limited gpu memory, we have to use quantization method, but it seems vllm now not support quantization method to deploy such models, 
If directly use the auto-awq method, seem not support baichuan as follows:

File ~/miniconda3/envs/vllm/lib/python3.8/site-packages/awq/models/auto.py:24, in check_and_get_model_type(model_dir, trust_remote_code)
     22 config = AutoConfig.from_pretrained(model_dir, trust_remote_code=trust_remote_code)
     23 if config.model_type not in AWQ_CAUSAL_LM_MODEL_MAP.keys():
---> 24     raise TypeError(f"{config.model_type} isn't supported yet.")
     25 model_type = config.model_type
     26 return model_type

TypeError: baichuan isn't supported yet.

does anyone have any solutions, thx ahead of time.

**Comment by WoosukKwon** [comment]
Closing this issue as all models support AWQ since #1622.

**Comment by 77h2l** [comment]
@WoosukKwon FYI
I tried to run baichuan2-13b awq as the official code:

from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

model_path = './Baichuan2-13B-Base'
quant_path = './baichuan2_awq_int4'
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }

# Load model
model = AutoAWQForCausalLM.from_pretrained(model_path, **{"low_cpu_mem_usage": True})
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# Quantize
model.quantize(tokenizer, quant_config=quant_config)

# Save quantized model
model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)


still returns not supported yet

    raise TypeError(f"{config.model_type} isn't supported yet.")
TypeError: baichuan isn't supported yet.

**Comment by David-Lee-1990** [comment]
me too
