### ISSUE TITLE
Support for Starcoder

### ISSUE THREAD

**Issue by andreapiso** [vllm-project/vllm#170]
Does this work with Starcoder? The readme lists gpt-2 which is starcoder base architecture, has anyone tried it yet?

**Comment by WoosukKwon** [comment]
Thanks for your request! To my knowledge, StarCoder is based on the GPTBigCode architecture which is a bit different from GPT-2. We are planning to support it soon. Please stay tuned!

**Comment by andreapiso** [comment]
This is awesome to know. Code completion and coding assistant in general are a use case where throughput and latency can make a huge difference. Today we use Ray and text-generation-inference to serve starcoder to our vscode and intellij extensions. I see that there's already a PR for using vllm with Ray Serve so I'm quite excited to try it.

**Comment by michaelfeil** [comment]
Might be able to work on it.

Should be straightforward from GPT-2, HF GPT Bigcode model uses linear instead of GPT-2-Conv1D.
Also MQA can be just duplicated (see e.g. starcoder.cpp), to MHA. Once a „native“ MQA is available, could move also to MQA.

**Comment by michaelfeil** [comment]
[[Added a PR](https://github.com/vllm-project/vllm/pull/209)](https://github.com/vllm-project/vllm/pull/209)

**Comment by gesanqiu** [comment]
It seems not support WizardCoder yet, I got following output when I load WizardCoder:

```shell
(vllm) root@k8s-node-master-38:/workdir# CUDA_VISIBLE_DEVICES=4,5 python -m vllm.entrypoints.api_server --model ./WizardCoder --tensor-parallel-size 2 --port 8013 --host 10.0.76.38
2023-06-29 02:07:47,436 INFO worker.py:1636 -- Started a local Ray instance.
INFO 06-29 02:07:48 llm_engine.py:59] Initializing an LLM engine with config: model='./WizardCoder', dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=2, seed=0)
(Worker pid=144328) 2023-06-29 02:08:15,710     ERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::Worker.__init__() (pid=144328, ip=10.0.76.38, actor_id=83b486cb2c87ced4d099c99601000000, repr=<vllm.worker.worker.Worker object at 0x7eebec58db10>)
(Worker pid=144328)   File "/workdir/vllm/vllm/worker/worker.py", line 45, in __init__
(Worker pid=144328)     self.model = get_model(model_config)
(Worker pid=144328)   File "/workdir/vllm/vllm/model_executor/model_loader.py", line 49, in get_model
(Worker pid=144328)     model.load_weights(
(Worker pid=144328)   File "/workdir/vllm/vllm/model_executor/models/gpt_bigcode.py", line 288, in load_weights
(Worker pid=144328)     load_tensor_parallel_weights(param, loaded_weight, name,
(Worker pid=144328)   File "/workdir/vllm/vllm/model_executor/weight_utils.py", line 101, in load_tensor_parallel_weights
(Worker pid=144328)     assert param.shape == loaded_weight.shape
```

I checked log and found that is `transformer.wte.weight` cause the assert, the param.shape of it is [24608， 6144], while loaded_weight.shape is [24545, 6144], any ideas about this issue?
