### ISSUE TITLE
Distributed inference using multiple machines

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#1702]
Is this supported? For example, I have two machines each with only one GPU. 
Does vllm support 1 instance using the two machines?

**Comment by simon-mo** [comment]
Yes. You need to use the `ray` runtime according to our docs here: https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html

**Comment by sleepwalker2017** [comment]
> Yes. You need to use the `ray` runtime according to our docs here: https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html

Thank you! I'll try that.

**Comment by sleepwalker2017** [comment]
> Yes. You need to use the `ray` runtime according to our docs here: https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html

Hello, seems vllm only supports tp, no support for PP, right?

**Comment by zhuohan123** [comment]
> > Yes. You need to use the `ray` runtime according to our docs here: https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html
> 
> Hello, seems vllm only supports tp, no support for PP, right?

Yes, you are right. We don't see a lot of asks for PP for now. This is in our long-term road map.
