### ISSUE TITLE
bug of opt awq model

### ISSUE THREAD

**Issue by irasin** [vllm-project/vllm#1703]
Hi @zhuohan123, I found two bugs of opt awq model in the latest code because of the code refactor. 
1. in https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/opt.py#L215, some opt model may not use quantized linear in project_in/project_out, 
2. in https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/opt.py#L254, project_in/project_out have two return value

**Comment by irasin** [comment]
And for bloom awq model, I got the following error
```bash
    param = params_dict[name]
KeyError: 'transformer.h.0.mlp.gelu_impl.scales'
```

**Comment by WoosukKwon** [comment]
Hi @irasin, thanks for reporting the issue.

Regarding
> in https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/opt.py#L215, some opt model may not use quantized linear in project_in/project_out,

Could you let us know which OPT model does not use quantized linears for these layers?
