### ISSUE TITLE
Load from HF format models doesn't work

### ISSUE THREAD

**Issue by jerryMeng100** [vllm-project/vllm#171]
Running it on HF transformers models on the hub seems to break on :

    else:
        for bin_file in hf_bin_files:
            state = torch.load(bin_file, map_location="cpu")
            for name, param in state.items():
                yield name, param
                
Probably because it needs to call model.load_state_dict(torch.load(bin_file, map_location="cpu")) from huggingface model. The exact error is: AttributeError: 'TrainingArguments' object has no attribute 'items'

Is this an error on my end or does this apply to all HF-format models on the hub?

**Comment by WoosukKwon** [comment]
Which model did you try? Also, can you say more about your environment?

**Comment by jerryMeng100** [comment]
I tried for testing this one: https://huggingface.co/ehartford/Wizard-Vicuna-7B-Uncensored/tree/main

For testing I put download_dir to be '.' so it downloaded everything in the dir that I was testing things. Cuda 11.8, pytorch 2.0.1 i think. 

Small thing in addition: I ran into "could not find fastchat" and I had to do pip install fschat to fix that. Is that a dependency error or something on my side?

**Comment by WoosukKwon** [comment]
vLLM does not have fastchat as its dependency. It seems it's because the model weights were not properly saved.

**Comment by jerryMeng100** [comment]
It definitely works with HF format from other tests, but seems to be something with robustness with translating that here. I tried Vicuna 7b and it worked. I think the wizard-vicuna I was using was in float 32? It's double the size of other 7b models in float 16.

Also - wonder if there's a way to have custom stopping tokens like in transformers pipelines, such as '\n'?

**Comment by WoosukKwon** [comment]
Yes, please check the `SamplingParams` class in https://github.com/vllm-project/vllm/blob/67d96c29fba9b72cb4c4edbc26211c208a00ebdd/vllm/sampling_params.py#L5

For example, if you are using the `LLM` class, then you can initialize the `SamplingParams` class with `stop` and pass it to the `llm.generate` method.

**Comment by jerryMeng100** [comment]
Ok, one last thing (related to the HF thing). I did a direct comparison of HF pipelines and vLLM generate, and ended up getting about 200 char/s on vLLM and 140 char/s on Transformers on my RTX 4090. It's a sizable difference of 1.4x but not quite 20x+. What conditions were the 20x+ improvements from? I ran it on 1 input prompt sequence to generate a long poem about some topic.

The comparison was done with ehartford/WizardLM-7B-V1.0-Uncensored which is a llama derivative.

**Comment by WoosukKwon** [comment]
Thanks for trying out vLLM! The majority of the vLLM's speedup comes from batching more sequences together (hence we are high-throughput system). If you test with a larger number of prompts, then you will see a larger gap.

**Comment by jerryMeng100** [comment]
Gotcha, makes sense. Noticed you had a live async server for serving a model over an API, do you see a bigger speedup there or is it the 1.4/1.5x base speed that I had gotten here?

**Comment by WoosukKwon** [comment]
Closing the issue as we found that the saved model format is causing the error. But please reopen the issue if you need further help.
