### ISSUE TITLE
ImportError: libcudart.so.12

### ISSUE THREAD

**Issue by tranhoangnguyen03** [vllm-project/vllm#1718]
Was working yesterday.
Today it gives the following error:
```
from vllm import cuda_utils
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

I've tried turning it off and on again multiple times.

**Comment by WoosukKwon** [comment]
Hi @tranhoangnguyen03 , we just released a new version (v0.2.2) which depends on PyTorch 2.1 and CUDA 12.1. This might cause error if you environment does not have CUDA 12.1.
1. Please upgrade PyTorch using `pip install --upgrade torch`
2. If it does not work, please install vLLM + CUDA 11.8 following the instructions [here](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#install-with-pip).

**Comment by tranhoangnguyen03** [comment]
1. doesn't work
2. takes a long time
--> I'm reverting back to vllm==0.2.1.post1

**Comment by tranhoangnguyen03** [comment]
In case anyone else runs into the same trouble as I did. Here's how to make it work on Google Colab:

```
!pip -q install --upgrade fschat accelerate autoawq vllm
!pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121
```

**Comment by Tanio253** [comment]
> In case anyone else runs into the same trouble as I did. Here's how to make it work on Google Colab:
> 
> ```
> !pip -q install --upgrade fschat accelerate autoawq vllm
> !pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121
> ```

Thank you! Super useful.

**Comment by Hukongtao** [comment]
> Hi @tranhoangnguyen03 , we just released a new version (v0.2.2) which depends on PyTorch 2.1 and CUDA 12.1. This might cause error if you environment does not have CUDA 12.1.
> 
> 1. Please upgrade PyTorch using `pip install --upgrade torch` and see if the error persists.
> 2. If it does not work, please install vLLM + CUDA 11.8 following the instructions [here](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#install-with-pip).

Is there a cuda11.7 version?

**Comment by zhaozhaoxia** [comment]
> > Hi @tranhoangnguyen03 , we just released a new version (v0.2.2) which depends on PyTorch 2.1 and CUDA 12.1. This might cause error if you environment does not have CUDA 12.1.
> > 
> > 1. Please upgrade PyTorch using `pip install --upgrade torch` and see if the error persists.
> > 2. If it does not work, please install vLLM + CUDA 11.8 following the instructions [here](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#install-with-pip).
> 
> Is there a cuda11.7 version?

 Is there a cuda11.1 version?

**Comment by datalee** [comment]
> CUDA 12.1.

Is there a cuda11.7 version?

**Comment by AWangji** [comment]
> > Hi @tranhoangnguyen03 , we just released a new version (v0.2.2) which depends on PyTorch 2.1 and CUDA 12.1. This might cause error if you environment does not have CUDA 12.1.
> > 
> > 1. Please upgrade PyTorch using `pip install --upgrade torch` and see if the error persists.
> > 2. If it does not work, please install vLLM + CUDA 11.8 following the instructions [here](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#install-with-pip).
> 
> Is there a cuda11.7 version?

same question, is there anyone solve it?

**Comment by qinhuangdaoStation** [comment]
> In case anyone else runs into the same trouble as I did. Here's how to make it work on Google Colab:
> 
> ```
> !pip -q install --upgrade fschat accelerate autoawq vllm
> !pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121
> ```

Excuse me, what is the version of vllm?

**Comment by DarkLight1337** [comment]
> > In case anyone else runs into the same trouble as I did. Here's how to make it work on Google Colab:
> > ```
> > !pip -q install --upgrade fschat accelerate autoawq vllm
> > !pip install torch==2.1.0+cu121 torchvision==0.16.0+cu121 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu121
> > ```
> 
> Excuse me, what is the version of vllm?

That is a very old version. I recommend you install the latest vLLM on a clean environment.

**Comment by stefanradev93** [comment]
Wraps Mamba State Space Model (SSM) as a highly performant summary network for `torch` backend:

https://github.com/state-spaces/mamba/tree/main

Usage for us:

`
summary_net = MambaSSM()
`

Caveat: Only works for PyTorch backend due to hardware-aware optimization of the algo.
