### ISSUE TITLE
/usr/bin/python: Error while finding module specification for 'vllm.entrypoints.api_server' (ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm' (most likely due to a circular import) (/workspace/vllm/vllm/__init__.py))

### ISSUE THREAD

**Issue by Rahmat711** [vllm-project/vllm#1719]
Can anyone please help i am getting error 
root@2a87f372d0a8:/workspace# cd vllm
root@2a87f372d0a8:/workspace/vllm# python -m vllm.entrypoints.api_server
/usr/bin/python: Error while finding module specification for 'vllm.entrypoints.api_server' (ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm' (most likely due to a circular import) (/workspace/vllm/vllm/__init__.py))

Even i tried running command python -m vllm.entrypoints.api_server outside vllm directory still the same issue.

**Comment by simon-mo** [comment]
Consider reinstall vllm from source, there are some new binary introduced.

**Comment by Rahmat711** [comment]
Even after reinstalling again the issue is still there?

**Comment by WoosukKwon** [comment]
@Rahmat711 Could you run vllm in a totally empty directory?

**Comment by simon-mo** [comment]
I did the following:
```bash
find . | grep \.so # confirm it finds all built shared objects
find . | grep \.so | xargs rm # remove them
pip install -e . --verbose # build again
```

**Comment by freedave** [comment]
Also getting this error with a fresh install

**Comment by simon-mo** [comment]
Can you check that your CUDA version is 12 instead of 11? I had to upgrade my CUDA version as well.

**Comment by freedave** [comment]
Yes:
torch                     2.1.1+cu121
torchaudio                2.1.1+cu121
torchvision               0.16.1+cu121

**Comment by WoosukKwon** [comment]
@freedave Could you try running vllm in a new empty directory?

**Comment by freedave** [comment]
Maybe I should specify that I am running this from the cloned git repo, not a "pip install vllm", and kicking off the api server like this:

    python -m vllm.entrypoints.api_server \
    --model "some_model_path" \
    --tensor-parallel-size 4

**Comment by SS4G** [comment]
Can this problem only be solved by upgrading to cuda 12? I also got this error without pip installing vllm when my cuda is 11.7.

**Comment by CSWellesSun** [comment]
I also encounter the problem. I find that after I install vllm, I shouldn't run `python -m vllm.entrypoints.api_server` in the the vllm source code directory. Instead, I can use any other directories to run the command.

**Comment by Rahmat711** [comment]
As i am trying with cuda 11.8 still is it necessary to use cuda 12.1 and even the docker image that shared in docs get 11.8 cuda insatlled. if there is issue with cuda let me know as i am still facing the errors

**Comment by WoosukKwon** [comment]
@Rahmat711, from what I can gather, this error isn't related to the version of CUDA you're using, be it 11.8 or 12.1. The only confirmed and reproducible cause of this issue we've seen is when someone installs vLLM using `pip install vllm` and then tries to run vLLM in the root directory of the vLLM repository.

For the other cases, I've never successfully reproduced them. Thus, we are guessing that this error can be related to misconfigured user environment.

**Comment by WoosukKwon** [comment]
@freedave Thanks for letting us know. Could you share the output of `pip list` in your environment?

**Comment by Rahmat711** [comment]
@WoosukKwon can you please share the code snippet for installing the same in new env in cuda 11.8 as i have insatlled vllm from cloning the repo and not with pip. but still if you can reshare the right installtion step will be very helpfull.
thanks🙌

**Comment by Rahmat711** [comment]
@WoosukKwon please help i tried all possible ways but unable to run can you please provide the step to resolve or guide me why the issue might me coming for circular import.

**Comment by tjtanaa** [comment]
I have found out that the circular import is most likely caused by the flat layout of the repository. converting the vllm repo into [src layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) should solve the problem.

Many of us would `pip install vllm` and would try to run `python -m vllm.entrypoints.api_server` at the root of the repository. Since there are two different paths that python can import `vllm`, from `python/site-packages` or from the `vllm` module (a folder with __init__.py). This ambigous case could be the cause of circular import. That's why if user changed to other directory, they could run the `python -m vllm.entrypoints.api_server`.

**Comment by Rahmat711** [comment]
Got it! Thanks
