### ISSUE TITLE
Download model from GCP storage bucket instead of huggingface

### ISSUE THREAD

**Issue by jajj50386** [vllm-project/vllm#1729]
Is there any way to specify model location from gcp storage bucket instead of huggingface repo? (--model)

**Comment by simon-mo** [comment]
I believe you can download the model using gsutil in command line first, and point vLLM to the directory using the model weights by setting `model` parameter to the path of the weights.

**Comment by jajj50386** [comment]
Thanks. can you give me example of how path point works? So should i use something like --model path/to/model/weights in vllm?

**Comment by simon-mo** [comment]
Yes exactly. The weights directory need to be in a format that huggingface transformers can understand. Do you have a specific model in mind?

**Comment by jajj50386** [comment]
Thanks again. yeah I'm using llama-2-13b
