### ISSUE TITLE
anyone test chatglm3-6b? set tensor_parallel_size=4, get wrong response

### ISSUE THREAD

**Issue by Coder-nlper** [vllm-project/vllm#1735]
Set tensor_parallel_size=1 or  tensor_parallel_size=2.  the response is OK.

my env info:

vllm==0.2.2
ray==2.8.0
transformers==4.34.0
torch==2.1.0

**Comment by zyt1024** [comment]
hello, how to run multi card in single machine?  when I set tensor_parallel_size=2,The following error occurred：
```  
File "/home/xxx/offline_inference_chatglm.py", line 7, in <module>
    llm = LLM(model=model_path, trust_remote_code=True, tensor_parallel_size=2)
  File "/home/xxx/vllm/vllm/entrypoints/llm.py", line 93, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/home/xxx/vllm/vllm/engine/llm_engine.py", line 228, in from_engine_args
    distributed_init_method, placement_group = initialize_cluster(
  File "/home/xxx/vllm/vllm/engine/ray_utils.py", line 77, in initialize_cluster
    ray.init(address=ray_address, ignore_reinit_error=True)
  File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/worker.py", line 1486, in init
    bootstrap_address = services.canonicalize_bootstrap_address(address, _temp_dir)
  File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/services.py", line 530, in canonicalize_bootstrap_address
    addr = get_ray_address_from_environment(addr, temp_dir
File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/psutil/_common.py", line 772, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/152830/stat'
````

**Comment by Coder-nlper** [comment]
maybe this ?
<img width="459" alt="image" src="https://github.com/vllm-project/vllm/assets/7296788/be9e092c-53b4-43cf-97e9-6ea77116163c">

**Comment by Coder-nlper** [comment]
> hello, how to run multi card in single machine? when I set tensor_parallel_size=2,The following error occurred：
> 
> ```
> File "/home/xxx/offline_inference_chatglm.py", line 7, in <module>
>     llm = LLM(model=model_path, trust_remote_code=True, tensor_parallel_size=2)
>   File "/home/xxx/vllm/vllm/entrypoints/llm.py", line 93, in __init__
>     self.llm_engine = LLMEngine.from_engine_args(engine_args)
>   File "/home/xxx/vllm/vllm/engine/llm_engine.py", line 228, in from_engine_args
>     distributed_init_method, placement_group = initialize_cluster(
>   File "/home/xxx/vllm/vllm/engine/ray_utils.py", line 77, in initialize_cluster
>     ray.init(address=ray_address, ignore_reinit_error=True)
>   File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>   File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/worker.py", line 1486, in init
>     bootstrap_address = services.canonicalize_bootstrap_address(address, _temp_dir)
>   File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/ray/_private/services.py", line 530, in canonicalize_bootstrap_address
>     addr = get_ray_address_from_environment(addr, temp_dir
> File "/home/xxx/miniforge3/envs/vllm/lib/python3.10/site-packages/psutil/_common.py", line 772, in open_binary
>     return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
> FileNotFoundError: [Errno 2] No such file or directory: '/proc/152830/stat'
> ```

reinstall vllm in a new  conda   env?

**Comment by Coder-nlper** [comment]
@gameofdimension  any suggestion? (;´༎ຶД༎ຶ`)

**Comment by tanguofu** [comment]
> maybe this ? <img alt="image" width="459" src="https://private-user-images.githubusercontent.com/7296788/286101392-be9e092c-53b4-43cf-97e9-6ea77116163c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDA4MzQsIm5iZiI6MTcwMjU0MDUzNCwicGF0aCI6Ii83Mjk2Nzg4LzI4NjEwMTM5Mi1iZTllMDkyYy01M2I0LTQzY2YtOTdlOS02ZWE3NzExNjE2M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTRUMDc1NTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQwNmRlODAxNGJkNGU2OGNmNDFlM2E2NTk4MzBkOGU1ODYwZWUzZDFkMTFiMTdmYjQzMTZjZGNmYzlhMzY1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4QlriEiijEb322WP1tciyK1Ky-NjMb9S52A-1LXddFU">
> 
> multi_query_group_num = 2
> 
> only support tensor_parallel_size=2?

where is the code？ i didnot find in vllm main branch~
