### ISSUE TITLE
chatglm3 will generate 'assistant' tokens

### ISSUE THREAD

**Issue by Nisoka** [vllm-project/vllm#1743]
when i use the api_openai to serve chatglm3, the response will generate 'assistant' first, then return the corrent response. 
anyone get same error？

example:
你好啊
assistant 你好👋！我是人工智能助手 ChatGLM3-6B，很高兴见到你，欢迎问我任何问题。

hello
assistant Hello! How can I help you today?

**Comment by Nisoka** [comment]
vllm: main branch (and modify the openai api_server.py to enable the tokenizer support chatglm3 encode)
    if 'chatglm3' in engine_model_config.tokenizer.lower():
        tokenizer = get_tokenizer(
            engine_model_config.tokenizer,
            **encode_special_tokens=True,**
            tokenizer_mode=engine_model_config.tokenizer_mode,
            trust_remote_code=engine_model_config.trust_remote_code)

fschat: main branch (for support chatglm3)

**Comment by sinopec** [comment]
fix my probelm thx~~

> vllm: main branch (and modify the openai api_server.py to enable the tokenizer support chatglm3 encode) if 'chatglm3' in engine_model_config.tokenizer.lower(): tokenizer = get_tokenizer( engine_model_config.tokenizer, **encode_special_tokens=True,** tokenizer_mode=engine_model_config.tokenizer_mode, trust_remote_code=engine_model_config.trust_remote_code)
> 
> fschat: main branch (for support chatglm3)

**Comment by sinopec** [comment]
A better way is to change the chatglm3-6b tokernizer init function's default value for encode_special_tokens
