### ISSUE TITLE
vllm是否支持推理可复现（seed）

### ISSUE THREAD

**Issue by chk4991** [vllm-project/vllm#1744]
请问vllm是否支持设置随机种子，使每次请求的推理都可复现。目前在SamplingParams中没有发现与seed有关的参数。

**Comment by DouHappy** [comment]
想要可复现的话可以尝试设置SamplingParams里的temperature=0
sampling_params = SamplingParams(temperature=0)

**Comment by DouHappy** [comment]
> 请问vllm是否支持设置随机种子，使每次请求的推理都可复现。目前在SamplingParams中没有发现与seed有关的参数。

#1637 Maybe This can be helpful.
