### ISSUE TITLE
Does it support multi-modal LLM like LLaVa?

### ISSUE THREAD

**Issue by Privilger** [vllm-project/vllm#1751]
The given example shows how to use for LLM like llama.
But how can I use it to accelerate Visual Language Model like LLaVa?

**Comment by simon-mo** [comment]
LLaVa needs to be added with our lightweight model addition process. Contribution welcomed!

**Comment by l4b4r4b4b4** [comment]
> LLaVa needs to be added with our lightweight model addition process. Contribution welcomed! https://docs.vllm.ai/en/latest/models/adding_model.html

You dont generally see an issue in using the lighweight model adidtion for the composed llava model with CLIP, vision encoder and LLM?

**Comment by simon-mo** [comment]
It does turns out to be more complex. A working PR is here #3042

**Comment by ywang96** [comment]
Closing as https://github.com/vllm-project/vllm/pull/3042 adds support for LLaVA1.5

**Comment by iamsaurabhgupt** [comment]
is LLaVA-Next supported? 
couldn't find a working example

**Comment by ywang96** [comment]
@iamsaurabhgupt Feel free to take a look at the example here! https://github.com/vllm-project/vllm/issues/4194#issuecomment-2187565657. One limitation we have now is that we don't support dynamic shape of input image, so the results might be slightly different from huggingface implementation, but we're on track to support this very soon!
