### ISSUE TITLE
--tensor-parallel-size vs device_map?

### ISSUE THREAD

**Issue by garyyang85** [vllm-project/vllm#1752]
I have two 32G V100 gpus, and need to run a 13B float16 model. I have tried below paths:
1.  python -m vllm.entrypoints.openai.api_server --dtype float16 --trust-remote-code --model /app/model --port 8000 --host 0.0.0.0 **--tensor-parallel-size 1**,  OOM
2. python -m vllm.entrypoints.openai.api_server --dtype float16 --trust-remote-code --model /app/model --port 8000 --host 0.0.0.0 **--tensor-parallel-size 2**,  both GPU usage is about 27G and can inference very fast with long tokens
3. use fastchat to start with 1 GPU,the GPU usage is about 27G, **The inference speed is fast but will stuck on long tokens.**
4. use fastchat to start with 2 GPUs, both GPU usage is about 14G, it use the device_map. **The inference speed is too slow with long tokens but won't stuck.**

Questions:
1. Why --tensor-parallel-size 1 will cause OOM, the 1 GPU resource should be enough.
2. Does vllm support device_map? If there are only two 24G GPUs，how can I run such model with vllm?  
3. How to speed up the inference when use device_map? (Maybe not specific with vllm, for discussion)

**Comment by yuxx0218** [comment]
hi, could you please share me how to set device_map?
