### ISSUE TITLE
Batching inference outputs are not the same with single inference

### ISSUE THREAD

**Issue by gesanqiu** [vllm-project/vllm#1761]
If I call the llm.generate with a batch prompts and greedy search, the output of batch inference is different to single batch inference. Is this right? A minimum reprodece script looks like this:
```python
from vllm import LLM, SamplingParams

# Sample prompts.
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0)

# Create an LLM.
llm = LLM(model="/workdir/hf_models/llama-2-7b-chat-hf/", trust_remote_code=True)
# Generate texts from the prompts. The output is a list of RequestOutput objects
# that contain the prompt, generated text, and other information.
outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
    
    
for prompt in prompts:
    print(prompt)
    outputs = llm.generate(prompt, sampling_params)
    for output in outputs:
        generated_text = output.outputs[0].text
        print(f"Generated text: {generated_text!r}")

```
![image](https://github.com/vllm-project/vllm/assets/37237570/1e852648-7d53-4928-89b6-cb4071e37879)

**Comment by WoosukKwon** [comment]
Hi @gesanqiu, I believe this should not be the case. Could you share a reproducible example?

**Comment by gesanqiu** [comment]
@WoosukKwon Sorry for made a mistake, this issue is tested on #1508, vLLM main branch doesn't have this issue. Need to check the dev branch.

**Comment by gesanqiu** [comment]
#1546 fixed this issue.

**Comment by microhu** [comment]
I use the latest 0.5.4 version and found this problem is still existed. The decoding results of using batchsize=10 and 1 is different for some sentences.(Not all)

I guess it may be caused by the left padding. Some short sentences will be padded at the left. I wonder whether the vllm model will add special mask to remove the left-pading when perform self-attention? These should cause some differences if not
