### ISSUE TITLE
Bug in fastchat API when setting served-model-name

### ISSUE THREAD

**Issue by dred0n** [vllm-project/vllm#1768]
I need my model name to match chatGPT's in order to integrate with an existing product.

To accomplish this by setting the 'served-model-name' option show below::

python -m vllm.entrypoints.openai.api_server \
--served-model-name gpt-3.5-turbo \
--model Intel/neural-chat-7b-v3-1

This causes the following error when making an API call

POST http://192.168.254.161:8000/v1/chat/completions
{
  "model": "chatgpt-3.5-turbo",
  "messages": [...]
}

Error:
  File "/home/dredon/miniconda3/envs/vllm/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: None is not a valid SeparatorStyle

**Comment by liwenju0** [comment]
i faced the same error, how did you solved this problem finally, please give me a help
