### ISSUE TITLE
Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].Isn’t gptq already supported?

### ISSUE THREAD

**Issue by tms2003** [vllm-project/vllm#1769]
My code like this:
```
llm = LLM(model="/home/llm/QWenData/Qwen-14B-Chat-Int4", revision="v1.1.8", trust_remote_code=True,quantization="gptq")
```

I notice this url :https://github.com/vllm-project/vllm/pull/916 showing  qptq already merge in master.
I already install git source code for the newest code.but I got this:
```
Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm']
```
So what should I do to use the gptq model?

**Comment by shatealaboxiaowang** [comment]
> quantization="gptq"

Has the problem been solved? Why is it closed?

**Comment by Peter-Devine** [comment]
Same +1

**Comment by Kelang-Tian** [comment]
Same +1

**Comment by schauppi** [comment]
Same +1

**Comment by lunalulu** [comment]
请问你们解决了吗？vllm0.2.2

**Comment by enymfc25173** [comment]
Same +1

**Comment by srimanth-duggineni** [comment]
Same +1
