### ISSUE TITLE
Container Build Fail - Cannot find CUDA at CUDA_HOME

### ISSUE THREAD

**Issue by karlbernard2** [vllm-project/vllm#177]
Whatever I try, I get:

```
RuntimeError: Cannot find CUDA at CUDA_HOME: /usr/local/cuda. CUDA must be available in order to build the package.
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/39/a1/42e126432a166dcca8d93c430a5c733b1734f4e0f7ffbaf7cbbdb22662a1/vllm-0.1.0.tar.gz#sha256=14425335ac80b17d60a1633f03c5d05d2c6b46a06b196eccab900e2150d96c79 (from https://pypi.org/simple/vllm/) (requires-python:>=3.8). Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp6ex7hkl2 Check the logs for full command output.
```

**Dockerfile:**
```
FROM nvcr.io/nvidia/pytorch:22.12-py3
WORKDIR /app

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get install unzip
RUN apt-get -y install python3 wget
RUN apt-get -y install python3-pip

RUN pip uninstall -y torch
RUN pip install vllm
```

I also tried with 
FROM nvcr.io/nvidia/cuda:11.8.0-runtime-ubuntu20.04

**Comment by WoosukKwon** [comment]
Thanks for reporting the issue. I'm currently investigating it. I'll get back to you once I figure it out.

**Comment by gottlike** [comment]
You can't just use the standard Docker setup for CUDA work. Your host needs some libraries/drivers: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html

**Comment by HaishuoFang** [comment]
I have the same problem when i install it on Slurm

**Comment by HaishuoFang** [comment]
I found the resolution. The main reason is it needs to use torch.cuda.is_available() to verify if the cuda is available in `setup.py`. For slurm, you only get gpus when you submit the jobs. So when you install it, just comment it out.  Besides, you also need to check compute_capabilities with your cuda version

**Comment by karlbernard2** [comment]
@HaishuoFang will you commit changes to setup.py?

**Comment by HaishuoFang** [comment]
if they would like, I can create a pr. Otherwise, just wait for them to fix it

**Comment by karlbernard2** [comment]
I was looking forward to test in production and measure the performance gain, but I can wait for a fix.

However, I'm not sure I understand your proposed solution, looking at the setup.py, it's already using torch.cuda.is_available()

**Comment by nicolasf** [comment]
I was able to work around this using `DOCKER_BUILDKIT=0`.

Example:
`DOCKER_BUILDKIT=0 docker-compose up`
