### ISSUE TITLE
GPU consumption is way higher than expected for quantized model

### ISSUE THREAD

**Issue by eswarthammana** [vllm-project/vllm#1770]
Hi Team,

Python 3.10.x
vLLM 0.2.2
autoawq 0.1.7

Firstly thanks for the blazing speed tool for LLM's.
I have explored Llama2-7b-chat-hf, by using autoawq and created 4bit quantized model.

Which is of around 3.6GB, but the GPU usage on T4 is way higher around 19GB. is there any configurations do i need to further setup.

Following is my Langchain vLLM class instance
```
VLLM(
            model=model,
            callback_manager=callback_manager,
        )
```
where model is the quantized model folder path.

> attaching the GPU consumption

![image](https://github.com/vllm-project/vllm/assets/23114153/8d997627-caa1-4c30-ae73-e1013c23fe22)

python3 is the only process running fastapi application which consumes the vLLM quantized Llama2-7b

please share your suggestions

**Comment by SebastianBodza** [comment]
https://github.com/vllm-project/vllm/issues/550
https://github.com/vllm-project/vllm/issues/1512
