### ISSUE TITLE
Fatal python error:Bus error

### ISSUE THREAD

**Issue by hanzhenlei767** [vllm-project/vllm#1771]
![WechatIMG1287](https://github.com/vllm-project/vllm/assets/42851990/06ad0512-d1da-466d-8689-b0cad348e76a)

I deployed vllm on  RTX4090 * 2 and encountered an error. Can anyone help me?

**Comment by nkwangleiGIT** [comment]
I met with the same issue, can you solve this? @hanzhenlei767

**Comment by linzm1007** [comment]
I met with the same issue. Has this problem been solved?

**Comment by gree2** [comment]
add --shm-size=32g to you docker run command may fix your problem.

`docker run --gpus all --shm-size=32g --name chatglm4-9b -v /data/sdb/models:/root/models -p 8020:8000 -e --ipc=host vllm/vllm-openai:v0.4.2 --model /root/models/glm-4-9b-chat --tokenizer /root/models/glm-4-9b-chat --max-model-len 8192 --tensor-parallel-size 4 --enable-prefix-caching --trust-remote-code --disable-log-stats --enforce-eager --gpu-memory-utilization=0.7 --served-model-name=chatglm4-9b
`
