### ISSUE TITLE
Error from "Build from source"

### ISSUE THREAD

**Issue by Hukongtao** [vllm-project/vllm#1772]
I tried to build vllm from the source code, but encountered the following error:
RuntimeError: The NVIDIA driver on your system is too old
![image](https://github.com/vllm-project/vllm/assets/16505966/c9c37a72-09e8-4715-80f0-c5b7d0a6b204)
![image](https://github.com/vllm-project/vllm/assets/16505966/a4dbcfdb-69e1-44c7-b9b0-0394ffd797b9)

**Comment by WoosukKwon** [comment]
Hi @Hukongtao, as shown in the error message, your driver version is too old. The driver only covers up to CUDA 11.4. Please upgrade the NVIDIA driver.
