### ISSUE TITLE
chatglm isn't supported.

### ISSUE THREAD

**Issue by tms2003** [vllm-project/vllm#1775]
Trying to use AutoAWQ to quantize the chatglm pattern, the result is:
chatglm isn't supported yet. Is there a solution?

my code just like this:
```
model_path = '/home/incar/newdata2/tms/llm/chatglm3-6b-32k'
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
model = AutoAWQForCausalLM.from_pretrained(model_path, **{"low_cpu_mem_usage": True})

```

**Comment by hmellor** [comment]
This seems like an issue that should be raised on https://github.com/casper-hansen/AutoAWQ
