### ISSUE TITLE
Load model into multiple GPU's

### ISSUE THREAD

**Issue by andrey-genpracc** [vllm-project/vllm#1778]
Hi!
Can load model into multiple GPU's . For example half of layers in GPU0 , and half to GPU1 . Like in obabooga

**Comment by omer-dayan** [comment]
I am not sure what obabooga is. But what you describe is pipeline parallelism and its supported by vLLM via Ray. 
Mind though that pipeline parallelism is not the only way to run one model in multiple GPUs. There is also tensor parallelism.
And obviously there is data parallelism, which means few replicas of the whole model on different GPUs
