### ISSUE TITLE
Proposal: force type hint check with mypy

### ISSUE THREAD

**Issue by wangkuiyi** [vllm-project/vllm#1780]
## Why

While I am learning the source code, I found it challenging to understand asyncio. Taking this codebase as an example, I spend quite some time with the following method signature:

https://github.com/vllm-project/vllm/blob/7c600440f7560348e571f021f2b2d1469de5264d/vllm/engine/async_llm_engine.py#L394-L399

I realized there was a discrepancy in the return type hint. The original hint was:

```python
-> RequestOutput:
```

However, the correct hint should be:

```python
-> typing.AsyncIterator[RequestOutput]:
```

For a detailed demonstration of this issue, please see the appendix below.

## Proposal

To enhance type checking with mypy, it's advisable to include the following options in mypy.ini, as suggested in [this StackOverflow answer](https://stackoverflow.com/a/70913528):

```
disallow_untyped_defs
disallow_incomplete_defs
disallow_untyped_calls
```

## Appendix

Below is a complete example that illustrates the correct use of type hints for async iterators:

```python
"""
For a full check including type hints, run the following command

mypy \
  --disallow-untyped-defs \
  --disallow-incomplete-defs \
  --disallow-untyped-calls \
  /tmp/a.py
"""
import asyncio
import typing


async def foo() -> typing.AsyncIterable[int]:
    for i in range(3):
        yield (i)


async def bar() -> typing.AsyncIterable[int]:
    f = foo()
    print(f"The type of foo is {type(foo)}")  # <class 'function'>
    print(f"The return type of foo is {type(f)}")  # <class 'async_generator'>
    async for i in f:
        yield i


async def main() -> None:
    b = bar()
    print(f"The type of bar is {type(bar)}")  # <class 'function'>
    print(f"The return type of bar is {type(b)}")  # <class 'async_generator'>
    async for i in b:
        print(i)


c = main()
print(f"The return type of main is {type(c)}")  #  <class 'coroutine'>
asyncio.run(c)
```

**Comment by simon-mo** [comment]
we would definitely love to fully enable type checking, however, we understand it is fairly involved and time consuming so we are focusing on more pressing issue. if you can help contribute that would be amazing!

**Comment by DarkLight1337** [comment]
@rkooo567 you may close this once you've completed the PR for cross-directory type checking with `mypy`.

**Comment by rkooo567** [comment]
Yeah I will need to create 1 more PR to finish this

**Comment by DarkLight1337** [comment]
Closing this as mypy has been enabled to some extent - please refer to #3680 for further developments.
