### ISSUE TITLE
Repeated generation and ValueError: max() arg is an empty sequence error

### ISSUE THREAD

**Issue by ZEROYXY** [vllm-project/vllm#1783]
vllm    0.2.2
xformers    0.0.22.post7
python 3.10
transformer  4.35.1
LLM  ChatGLM2-6B-32K

I am facing the error as below when I use vllm to speed up the chatglm2-6b-32k:
It repeated the same word after several rounds and aborted with the error: max() arg is an empty sequence.
The deiatls are as below:

<img width="1271" alt="vllm_bug_1" src="https://github.com/vllm-project/vllm/assets/49576528/62eb0e3e-c62b-4bd2-a4b1-3cae226d1ec6">
<img width="1267" alt="vllm_bug_2" src="https://github.com/vllm-project/vllm/assets/49576528/92332fba-d48d-4e44-9d61-f4267ca1be9e">
<img width="1241" alt="vllm_bug_3" src="https://github.com/vllm-project/vllm/assets/49576528/14e31bce-a500-4ddc-8855-843f974ed01d">
<img width="1275" alt="vllm_bug_4" src="https://github.com/vllm-project/vllm/assets/49576528/15dfd664-c4b9-4adb-98ff-e821e6b9ec5d">

**Comment by ZEROYXY** [comment]
vllm于加速ChatGLM2-6B-32K进行长文本生成时，出现无意义重复生成问题，并会导致上述问题引起崩溃。该问题应如何应对

**Comment by RetormLi** [comment]
I met this problem, too. It will happen when the input is very long (still less than max length)
