### ISSUE TITLE
Is SequenceOutputs indeed SequenceOutput (removing the s suffix)?

### ISSUE THREAD

**Issue by wangkuiyi** [vllm-project/vllm#1787]
Based on the implementation, it appears that each `SequenceOutputs` object represents [a single token rather than multiple tokens generated from a sequence](https://github.com/vllm-project/vllm/blob/7c600440f7560348e571f021f2b2d1469de5264d/vllm/sequence.py#L373). In light of this, should the class be renamed to `SequenceOutput` by removing the 's' suffix to more accurately reflect its functionality?

In the same way, `SequenceGroupOutputs` should be `SequenceGroupOutput` and `SamplerOutput` could be `SequenceGroupOutputs`?

**Comment by zhuohan123** [comment]
Thanks for pointing this out! Fixed the naming in #1803

We will keep the `SamplerOutput` naming since this type is used for sampler's output.
