### ISSUE TITLE
openai client failed

### ISSUE THREAD

**Issue by frankxyy** [vllm-project/vllm#1789]
hi，I use the  https://github.com/vllm-project/vllm/blob/main/examples/openai_completion_client.py file to infer streamingly. However, this error occurs:

AttributeError: module 'openai' has no attribute 'Completion'

**Comment by whitelok** [comment]
Completion is deprecated in openai-python

**Comment by 0-hero** [comment]
With the current vllm implementation downgrade openai==0.28 in your env
