### ISSUE TITLE
How to compile the `csrc` into an object file with `nvcc`?

### ISSUE THREAD

**Issue by EricLBuehler** [vllm-project/vllm#1793]
Hello everybody,

I am trying to compile the `csrc` part of `vllm` into an object file (excluding the Python bindings). However, I cannot find a way to do this. This is the command I was using:
```
"nvcc" "-ccbin=c++" "-Xcompiler" "-O0" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-G" "-Xcompiler" "-gdwarf-4" "-Xcompiler" "-fno-omit-frame-pointer" "-m64" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-I /home/ericbuehler/.local/lib/python3.10/site-packages/torch/include" "-I /home/ericbuehler/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include" "-I /usr/include/python3.10" "-gencode" "arch=compute_62,code=sm_62" "-o" "/home/ericbuehler/candle-vllm/target/debug/build/candle-vllm-40c333732b7323b5/out/csrc/attention/attention_kernels.o" "-c" "csrc/attention/attention_kernels.cu"
```
It simply attempts to compile all `*.cu` files for a Jetson TX2 GPU (compute 6.2) as a test case, and provides paths to my libraries. However, it fails with an error code 1 and an error message that I could not find in the log.

I have read the `setup.py` and see [this](https://github.com/vllm-project/vllm/blob/7c600440f7560348e571f021f2b2d1469de5264d/setup.py#L145) line which seems to be loading the CUDA kernel, but I cannot understand how the files do not appear to be compiled before use? How can I compile the `csrc` CUDA kernel using `ops.h` as the API binding? Where can I find some pointers for how to do this, perhaps an example? 

Thanks for any help!

**Comment by whitelok** [comment]
Seems not support sm_62. Refer to: https://github.com/vllm-project/vllm/blob/main/setup.py#L18

**Comment by EricLBuehler** [comment]
@whitelok, do you know one that would work (for development purposes)?

**Comment by whitelok** [comment]
> @whitelok, do you know one that would work (for development purposes)?

Can you provide your jetpack version/ OS version ?

**Comment by EricLBuehler** [comment]
I am on WSL2 (ubuntu).

**Comment by EricLBuehler** [comment]
@whitelok, could you provide an example `nvcc` invocation using any supported GPU architecture? Thanks!

**Comment by EricLBuehler** [comment]
Running the `setup.py` and extracting the NVCC flags gives:
`['-O2', '-std=c++17', '-D_GLIBCXX_USE_CXX11_ABI=1', '-gencode', 'arch=compute_86,code=sm_86']`

**Comment by EricLBuehler** [comment]
I will use the `setup.py` file to automate the process based on a known working system. Thanks for the help!
