### ISSUE TITLE
can you support XverseForCausalLM? model XVERSE-65B

### ISSUE THREAD

**Issue by baiyuelanshan** [vllm-project/vllm#1794]
when i try to run
python -m vllm.entrypoints.openai.api_server --model XVERSE-65B --port 17861 --trust-remote-code
error occurs:
Model architectures ['XverseForCausalLM'] are not supported for now

vllm version: 0.2.1

it's web site address:
https://github.com/xverse-ai/XVERSE-65B

**Comment by whitelok** [comment]
seems XVERSE-13B is in pr https://github.com/vllm-project/vllm/pull/950
