### ISSUE TITLE
Tiny GPT-2 model downloaded from HuggingFace servers during initialisation

### ISSUE THREAD

**Issue by michel-m** [vllm-project/vllm#1799]
Hi,

(I use vLLM via LangChain, so I hope I'm looking for answers in the right place.)

During initialisation of vLLM when running various models, such as Mistral 7B, vLLM downloads some kind of fake tiny GPT-2 model (about 3MB size on disk) from HuggingFace's servers. This is not a problem in development environment, but our production environment doesn't have access to HF servers (and we cannot change this behaviour, the data we work with being too sensitive to tolerate access to internet) and so it hangs during init, and just restarts the process forever after timeouts.

What is this GPT-2 model? What can I do to prevent vLLM from trying to download it?

Thanks in advance for your help!

**Comment by 777ki** [comment]
when vLLM starup, there is a param to set which and where model to be load. 
why don't you to configure that param to solve your problem
like this:
```
python -m vllm.entrypoints.openai.api_server --model
or
llm = LLM(model=xxxx)
```

**Comment by michel-m** [comment]
Hi, thank you for your answer.
As I mentioned, I use vLLM via LangChain integration (implementation example here: https://python.langchain.com/docs/integrations/llms/vllm).
In my code I do exactly how you suggest:
```python
from langchain.llms import VLLM
llm = VLLM(model="<path_to_mistral_model_directory>")
```
But during startup vLLM still downloads that tiny GPT-2 model (what is it for by the way?).
Thanks for your help.
