### ISSUE TITLE
request a vllm.whl for cuda11.8_torch2.0.1_py39

### ISSUE THREAD

**Issue by ChenShuwei1001** [vllm-project/vllm#1807]
hi the authors.

Since the latest vllm (0.2.2) for cuda11.8 is built with torch 2.1.0 (which is incompatible with cuda 11.8)， could you please release a vllm.whl that is built with torch 2.0.1 and py39 ?

best wishes~

**Comment by ChenShuwei1001** [comment]
something wired happened when I tried to build vllm for cuda11.8, torch2.0.1 and py39 from the source code.

**Comment by ChenShuwei1001** [comment]
I also tried reinstall torch2.0.1 after installing vllm, but meet this error:

from vllm import quantization_ops
/usr/local/lib/python3.9/site-packages/vllm/quantization_ops.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by ChenShuwei1001** [comment]
Undefined symbol is caused by the incompatibility between vllm-0.2.2 and torch 2.0.1. Since vllm-0.2.2 is built with torch 2.1.0，when I tried to run vllm with torch 0.2.1, the undefined symbol comes. I have checked that torch 2.1.0 has a cuda 11.8 version, so use the right version torch will easily solve the problem.

**Comment by WoosukKwon** [comment]
Hi @ChenShuwei1001, as you found out, we provide [CUDA 11.8 version of vLLM](https://docs.vllm.ai/en/latest/getting_started/installation.html#install-with-pip), which requires manually installing the right version of PyTorch. Thanks for sharing your experience!
