### ISSUE TITLE
vllm-master（0.2.2）多卡并行推理乱码，单卡推理正常，使用了llama的Muilti-Query推理，请问是什么问题？

### ISSUE THREAD

**Issue by Chenyangzh** [vllm-project/vllm#1809]
vllm：0.2.2
pytorch：2.1.0
cuda：12.1
driver: 525.85.12

使用llama，muilti-query（num_key_value_heads=1）推理，发现单卡推理结果正常，多卡推理结果会有乱码和重复。请问怎么解决？

**Comment by FrankWhh** [comment]
我也碰到乱码，请问咋解决的

**Comment by pprp** [comment]
I encountered a similar issue when using 4 GPUs, as they were unable to function properly.

<img width="366" alt="image" src="https://github.com/vllm-project/vllm/assets/29230784/bd7c23b5-5d2c-4dff-b8ab-ef262c50b7f2">
