### ISSUE TITLE
fine tune model

### ISSUE THREAD

**Issue by deepanshu3061999** [vllm-project/vllm#1811]
Is Vllm compatible for inference of a custom fine tune model??

**Comment by WoosukKwon** [comment]
Hi @deepanshu3061999, yes. As long as the model architecture is supported ([supported list](https://docs.vllm.ai/en/latest/models/supported_models.html)), you can run your local model with vLLM by just providing the path to the model directory as the `model` argument.

**Comment by deepanshu3061999** [comment]
i have a peft model , i am merging and uploading the weights of that model with base model and the loading it, want to make this time faster 
# Reload model in FP16 and merge it with LoRA weights
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map=device_map,
)
model = PeftModel.from_pretrained(base_model,"/content/gdrive/MyDrive/28nov2023")
model = model.merge_and_unload()

# Reload tokenizer to save it
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

can we use vllm instead of this ?

**Comment by NEU-CS** [comment]
Hello~I have the same question. How did you solve this problem? Thanks so much!
