### ISSUE TITLE
Profile and optimize list operations in scheduling

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#1850]
BTW, we are considering using Numpy to reduce the list operations. I believe this can be done in another PR.

_Originally posted by @WoosukKwon in https://github.com/vllm-project/vllm/pull/1843#discussion_r1410054638_

**Comment by Yard1** [comment]
Highly recommend using pytorch profiler with CPU stack trace for profiling this!

**Comment by hmellor** [comment]
@WoosukKwon has this work been done now?

**Comment by youkaichao** [comment]
It seems not 👀
