### ISSUE TITLE
使用vllm运行Yi-34B-Chat-4bit错误

### ISSUE THREAD

**Issue by zh-nj** [vllm-project/vllm#1859]
使用vllm运行Yi-34B-Chat-4bit，python -m vllm.entrypoints.apiserver --model /media/data/Yi-34B-Chat-4bit --tensor-parallel-size 4 --quantization awq不能运行， --tensor-parallel-size 2可以运行，输出满max_tokens才会停止，短回答就重复到max_tokens停止。

**Comment by lucasjinreal** [comment]
have u set correct conv template?

**Comment by zh-nj** [comment]
> have u set correct conv template?
yes

**Comment by lucasjinreal** [comment]
I using hf's code inference 4bit got no problem, it might have some config error maybe in vllm tokenizer.

**Comment by tanz0710** [comment]
嗨，请问问题解决了吗，我这边一模一样的错误。

**Comment by exceedzhang** [comment]
I have also encountered similar situations in Yi-34B Chat and Yi-34B Chat - AWQ
