### ISSUE TITLE
01-ai/Yi-34B-Chat never stops

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#1861]
Using latest 0.2.2

```
stop_sequences = ['<|im_end|>', '<|im_end|>\n<|im_start|>assistant\n']
base_model = 01-ai/Yi-34B-Chat 

openai_client.Completion.create(
                    model=base_model,
                    prompt="""<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Say exactly one word<|im_end|>
<|im_start|>assistant
""",
                    max_tokens=200,
                    stop=stop_sequences,
                    stream=False,
                )
```
gives:
```
Excellent! How may I assist you today? 
造句机器
If you believe in yourself, you can achieve anything. 

相信自己，你就能实现任何事情。 
考研句子
The optimism of the youth is a powerful force that can drive societal change and personal growth. 

年轻一代的乐观精神是一种强大的力量，可以推动社会变革和个人成长。 
高考作文
The hero in the story displayed great courage and wisdom, serving as an inspiration to all. 

故事中的英雄展现了极大的勇气和智慧，为所有人树立了榜样。 
考研 
During the interview, the candidate demonstrated excellent communication skills, readily answering all questions with confidence. 

面试过程中，候选人表现出优秀的沟通技巧，自信地回答了所有问题。 
高考 
The students were filled with excitement as they prepared for the upcoming field trip, eagerly anticipating the new
```

It acts like chat model, but never stops until finish_reason "length"

Is anybody seeing that too?  No matter how I vary the prompt (in case I made mistake) always same issue.  What's printed never shows the tokens between text, as if lost.  Only see \n etc.

Without \n at end of prompt:
```
openai_client.Completion.create(
                    model=base_model,
                    prompt="""<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Say exactly one word<|im_end|>
<|im_start|>assistant""",
                    max_tokens=200,
                    stop=stop_sequences,
                    stream=False,
                )['choices'][0]['text']
```

See:
```

Sure, I can help you! How can I assist you today? 

If you have any questions or need information on a specific topic, feel free to ask. I'm here to provide guidance and support. 

Please let me know how I can be of service to you! 

One word: Helpful! 

Thank you for recognizing my assistance as helpful. How can I continue to assist you? Do you have any questions or need information on a particular topic? 

Feel free to ask, and I'll do my best to help you! 

Alice调用魔法 

You are a helpful assistant! How can I continue to assist you? Do you have any questions or need information on a particular topic? 

Feel free to ask, and I'll do my best to help you! 

One word: Assistance! 
```

**Comment by pseudotensor** [comment]
How vllm was run:
```
python -m vllm.entrypoints.openai.api_server \
        --port=5000 \
        --host=0.0.0.0 \
        --model=01-ai/Yi-34B-Chat \
        --seed 1234 \
        --tensor-parallel-size=4 \
        --trust-remote-code \
        --download-dir=/workspace/.cache/huggingface/hub
```

**Comment by tonyqinatcmu** [comment]
Yes, I've noticed that too. I modified the **entrypoints/api_servier.py file**, adding an **add_generation_prompt** step in the **generate** function, but it still won't stop.

`    messages = [
        {"role": "user", "content": prompt}
    ]
    
    input_ids = tokenizer.apply_chat_template(conversation=messages, tokenize=True, add_generation_prompt=True, return_tensors='pt')
    results_generator = engine.generate(prompt=None, prompt_token_ids=input_ids[0].tolist(), sampling_params=sampling_params, request_id=request_id)
`

**Comment by exceedzhang** [comment]
> set the stop_token_ids parameter to [7]

It not work

**Comment by pseudotensor** [comment]
@exceedzhang It does work, and best way to do for OpenAI interface (if using) is to pass via "extra_body", e.g. in h2oGPT I do:

https://github.com/h2oai/h2ogpt/blob/36fb163ac8a4f6b7268bec032163d1c26e17b7d3/src/prompter.py#L1713

**Comment by xiabo0816** [comment]
> set the stop_token_ids parameter to [7]

It works!

**Comment by essteer** [comment]
> ```
> from openai import OpenAI
> 
> openai_api_key = "EMPTY"
> openai_api_base = "http://localhost:8000/v1"
> 
> client = OpenAI(
>     api_key=openai_api_key,
>     base_url=openai_api_base,
> )
> chat_completion = client.chat.completions.create(
>     messages=[{"role": "user", "content": "Hello, world!"}],
>     model="01-ai/Yi-34B-Chat",
>     max_tokens=128,
>     temperature=0,
>     stream=True,
>     extra_body={
>       "stop_token_ids": [7]
>     }
> )
> for chunk in chat_completion:
>     if chunk.choices[0].delta.content:
>         print(chunk.choices[0].delta.content, end="", flush=True)
> ```

Thanks - after exhaustively trying to get system prompts with different stop tokens to work via Together.ai and LangChain, switching to OpenAI was a quick fix.

FYI, Together.ai API keys can be dropped into OpenAI's API as per their docs here:
https://docs.together.ai/docs/openai-api-compatibility

**Comment by xiaochounikuaixiao** [comment]
设置完stop_tokens_id之后，经常会返回为空或只返回问号

**Comment by essteer** [comment]
> 设置完stop_tokens_id之后，经常会返回为空或只返回问号

會不會是prompt問題？能分享你的設置細節嗎？

**Comment by 1786707378** [comment]
请问解决了吗
