### ISSUE TITLE
integration with langchain and streaming

### ISSUE THREAD

**Issue by RachelShalom** [vllm-project/vllm#1862]
HI 
I'm loading llama2 chat  Vllm with langchain and streamlit
the problem isI can't manage to stream the data. I get the response as one "chunk". I aslo check if there is "stream" argument that I can use in vllm_kwargs but couldn't find one
any idea how to solve this and make it work in a streaming fashion with langchain?
` llm = VLLM(
            model=model_path,
            trust_remote_code=True,  
            max_new_tokens=3000,
            top_k=10,
            top_p=0.95,
            temperature=0.8,
            callback_manager=callback_manager,
            verbose=True, token=hf_auth)
`
        

        for resp in llm.stream(some_prompt):
               print(resp)`

**Comment by Sajalj98** [comment]
Hi @RachelShalom Did you find any solution to above problem.

**Comment by phatjkk** [comment]
I have the same problem too.

**Comment by aarnphm** [comment]
Shouldn't this be opened upstream on LangChain instead of here?

**Comment by aemonge** [comment]
Same issues:

```
from langchain_community.llms.vllm import VLLM
       self.llm = VLLM(
            verbose=False,
            client=None,
            model=model,
            download_dir=VLLM_DOWNLOAD_PATH,
            trust_remote_code=True,  # mandatory for hf models
            vllm_kwargs={
                "gpu_memory_utilization": 0.95,
                "max_model_len": 4096,  # 8192,
                "enforce_eager": True,
            },
        )
        
            stream = self.llm.ainvoke(
                self._convert_base_message(cast(List[BaseMessage], event.contents))
            )
            print(await stream)
            for chunk in await stream:
                print(chunk)
```

**Comment by Shengguang-Zhou** [comment]
Any solution yet？

**Comment by DarkLight1337** [comment]
Please open an issue on LangChain's repo since the issue lies on their side.
