### ISSUE TITLE
Support Int8-quantified llama ?

### ISSUE THREAD

**Issue by shatealaboxiaowang** [vllm-project/vllm#1863]
Hi, dear:

Are there any INT8-quantified llama model available for testing ?
I want to use smoothquant and torch-int to quantify the model and then use vllm to reason, but smoothquant and torch-in are only suitable for cuda11.3.  so, there are existing quantified int8 models that can be inferred directly with vllm ??

Thank you!

**Comment by andrey-genpracc** [comment]
Hi in doc example of AWQ they use llama and i quantized llama and used it with vllm

**Comment by shatealaboxiaowang** [comment]
> Hi In doc example of AWQ they use llama and i also quantized llama and used it with vllm . but not sure if awq supports int8
awq does not support int8
