### ISSUE TITLE
[BUG] vllm will hang when using torchrun to start

### ISSUE THREAD

**Issue by PeterSH6** [vllm-project/vllm#1865]
Hi vllm maintainers,

Thanks for the awesome project!

I'm using vllm with other distributed training frameworks in the same Python file and I need to launch the Python file with `torchrun` to set up the distributed environment. However, when I test the vllm example (the code from the quickstart) with `torchrun --rdzv-backend=c10d --rdzv-endpoint=localhost:0 --nnodes=1 --nproc-per-node=2 vllm.py` . I found that it would hang after initializing the model and printing the log:
<img width="1494" alt="截屏2023-11-30 下午9 08 13" src="https://github.com/vllm-project/vllm/assets/43173188/97f4c729-271e-444f-97cf-94321d9a60a9">
I use tensor_parallel = 2 in this case and it works fine when I use `Python3 vllm.py`. I wonder if it supports launching the vllm with torchrun?

CC: @WoosukKwon @zhuohan123 @Yard1

**Comment by SONG-WONHO** [comment]
Hello, @PeterSH6

I encountered the same issue and resolved it by using the command `os.environ["TORCH_GEOMETRY_USE_AGENT_STORE"] = "False"`.

**Comment by xTayEx** [comment]
> TORCH_GEOMETRY_USE_AGENT_STORE

Hi! Thank you for your solution! I encountered the same issue and have tried this environment variable, but it still doesn't work. Could you please tell the version of PyTorch you are using?

**Comment by youkaichao** [comment]
`vllm` uses `ray` internally for multi-node setup.

If you want to do inference during training, you can set up a inference entrypoint, and let training jobs send requests to the inference entrypoint.
