### ISSUE TITLE
 I can not improve throughput with tensor-parallel on multi-gpus.

### ISSUE THREAD

**Issue by shatealaboxiaowang** [vllm-project/vllm#1873]
Hi dear：

I have tested the tensor parallelism of vllm on multiple gpus, but the effect is not as good as running on a single card, even if the batch size is relatively large (such as 16, 32, 64) will not be good, what is the reason ?

My service startup command is: CUDA_VISIBLE_DEVICES=0,1,2,3 python3 -m vllm.entrypoints.openai.api_server --dtype bfloat16 --max-model-len 7000 --tokenizer-mode auto --max-num-batched-tokens 30000 --block-size 16 --swap-space 16 --served-model-name codellama-13b-hf --model /home/models/CodeLlama-13b-hf/ --host 0.0.0.0 --port 8000 --tensor-parallel-size=4 --max-num-seqs 1024

thanks！

**Comment by sleepwalker2017** [comment]
The same problem.

**Comment by hmellor** [comment]
Tensor parallel does not improve the throughput of small models as the cost inter-GPU communication dominates
