### ISSUE TITLE
Yi-34B-Chat-4bit got CUDA out of memory

### ISSUE THREAD

**Issue by weiminw** [vllm-project/vllm#1877]
when I run the 4bit model in vllm. I got following error. I am using rtx4090 (24G GPU memory).

![Screenshot from 2023-12-01 12-28-40](https://github.com/vllm-project/vllm/assets/3841400/0c8c6c02-5365-436a-83a9-86e1dd1c6043)
![Screenshot from 2023-12-01 12-28-09](https://github.com/vllm-project/vllm/assets/3841400/0714a0f8-4652-45bc-8a09-b952a7390b83)

**Comment by John-Ge** [comment]
you may restrict the context length to 4096.

**Comment by weiminw** [comment]
> you may restrict the context length to 4096.
You mean:

set max_position_embeddings: 4096 in config.json ?

**Comment by thiner** [comment]
To run an AWQ model, you'd better try set arguments
```
--max-model-len 4096 (or lower)
--dtype half
```
Check https://docs.vllm.ai/en/latest/models/engine_args.html for more details.
