### ISSUE TITLE
Could you help to provide a solution for Qwen-14B-Chat-Int4(gptq) using vllm? Many Thanks!

### ISSUE THREAD

**Issue by micronetboy** [vllm-project/vllm#1881]
Could you help to provide a solution for Qwen-14B-Chat-Int4(gptq) using vllm? Many Thanks!

**Comment by chenxu2048** [comment]
You can try this PR  #1580, which contains the basic GPTQ support.

Or quantize Qwen-14B-Chat to int4 in AutoAWQ, with the script in [this pr](https://github.com/casper-hansen/AutoAWQ/pull/182#issuecomment-1811748733).
