### ISSUE TITLE
Throughput issues with Tensor Parallelism (Mistral 7B + FP16)

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#1888]
Today, I was testing on a node with 8x A100. I used a fine-tuned Mistral 7B, no quantization and just running FP16. The specific use-case is to summarize long documents and eventually chatting with them.

Settings:

```bash
python benchmark_throughput.py \
    --backend vllm \
    --model mistralai/Mistral-7B-Instruct-v0.1 \
    --tensor-parallel-size 8 \
    --dtype float16 \
    --input-len 10240 \
    --output-len 1024 \
    --num-prompts 100
```

Setup: Python 3.10, PyTorch 2.1.0, CUDA 12.1.

Throughput:

- 1x A100 (TP=1): 0.575 requests/second, 6464 tokens/second
- 8x A100 (TP=8): 0.27 requests/second, 2957 tokens/second
- Note: I did not get to try 2x, 3x, 4x, etc. as these tests were taking a long time to finish because I started out with 1000 prompts.

Questions:

- Is this the expected performance?
- Why does TP not scale well, is there a bug?
- Is the expected way to scale to more requests/second to use Ray/KubeRay to create replicas of vLLM with TP=1?

I found similar problems described in #1838 #1707 #1435 but unsure if it has been determined there is a bug.

**Comment by casper-hansen** [comment]
> I'm not a maintainer, but I think with small models, the way to scale more would be to use ray. 

That is what I suspected. I will experiment with this next week and try to come back with new results.

**Comment by minlik** [comment]
similar result

**Comment by matrixssy** [comment]
How did you get "6464 tokens/second" information? In default log such as:
```
llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 23.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
```?
