### ISSUE TITLE
How to load local llm and refit the weights of LLM Engine?

### ISSUE THREAD

**Issue by hijkzzz** [vllm-project/vllm#1897]
Hi, we are https://github.com/OpenLLMAI/OpenRLHF

We want to integrate vLLM with OpenRLHF to support large models
In RLHF we need to re-fit the weight of LLM models during the training
We even need to free the vLLM GPU memory to leave more memory for training, but not destroy the vLLM object
And then we can refit the LLM model weights from the training framework.

thx for your reply!

**Comment by ruihan0495** [comment]
I am also facing this issue, have you solved them already?
