### ISSUE TITLE
Remove Yi

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#1899]
On Nov. 21st, the Yi authors changed their code/config files to be compatible with LLaMA ([ref](https://huggingface.co/01-ai/Yi-34B-200K/commit/00313b6183023bd3a3da86fecb36d966bfc14132)). Therefore, we can _slowly_ remove the model and config code for Yi. While this breaks the compatibility for the users who downloaded the model before Nov. 21st, I think this is acceptable.

**Comment by WoosukKwon** [comment]
Closed by #2854

**Comment by vacant2011** [comment]
for yi model before Nov. 21st, how to user newer version of vllm to inference?
