### ISSUE TITLE
Maybe a bug about the swap_out

### ISSUE THREAD

**Issue by lambda7xx** [vllm-project/vllm#190]
-  [preempt](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L369) use the _```preempt_by_swap ``` to swap CPU and GPU block

- The ```preempt_by_swap ```  will call [swap_out](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L407)

-  I see the [swap_out](https://github.com/vllm-project/vllm/blob/main/vllm/core/block_manager.py#L199), it will swap all seq in the seq_group even its status is RUNNING.

But I think you want to achieve to swap the seq whose status is [SequenceStatus.SWAPPED](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L393)

**Comment by zhuohan123** [comment]
`swap_out` moves blocks from GPU block to CPU block, which is designed to move current RUNNING sequences to a SWAPPED state.

**Comment by lambda7xx** [comment]
> `swap_out` moves blocks from GPU block to CPU block, which is designed to move current RUNNING sequences to a SWAPPED state.

You mean when we use _[preempt_by_swap](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L386).
- First, we change the status to [SWAPPED](https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L393) if its status is RUNNING
- Then, we move its blocks from GPU to CPU? [swap_out](https://github.com/vllm-project/vllm/blob/main/vllm/core/block_manager.py#L199).

Thanks. BTW, I found the pytest test/ fails.

**Comment by zhuohan123** [comment]
Yes, your understanding is correct. Feel free to re-open the issue if you have any further questions.
