### ISSUE TITLE
Please help me! I do not know how to solve this problem

### ISSUE THREAD

**Issue by Kawai1Ace** [vllm-project/vllm#1906]
![图片](https://github.com/vllm-project/vllm/assets/77878387/03afa525-1363-4292-9a06-ccd2d5731bb3)
![图片](https://github.com/vllm-project/vllm/assets/77878387/5d168e05-6ad8-4f9b-b463-d4b757369dd3)

**Comment by sleepcoo** [comment]
Does your machine not have a cuda environment... do you want to try it with linux?

**Comment by Kawai1Ace** [comment]
> Does your machine not have a cuda environment... do you want to try it with linux?

I have a nvidia 3080 and cuda version is 12.3 run on windows 11. I do not know what happens in my installation.

**Comment by phineas-pta** [comment]
windows not supported

**Comment by hmellor** [comment]
You can use vLLM on Windows via WSL

**Comment by Zephyr69** [comment]
> You can use vLLM on Windows via WSL

Doesn't wsl2 not support nccl? I tried it on windows10, but it always reports errors related to nccl, even with libnccl installed.
