### ISSUE TITLE
Can cuda version 11.6 run this project? It is not convenient for me to update the cuda version of computers in the laboratory

### ISSUE THREAD

**Issue by Kawai1Ace** [vllm-project/vllm#1907]

**Comment by SuperBruceJia** [comment]
First git clone the project

then

```shell
cd vllm
pip install -e . --user
```

**Comment by Kawai1Ace** [comment]
> First git clone the project
> 
> then
> 
> ```shell
> cd vllm
> pip install -e . --user
> ```

![图片](https://github.com/vllm-project/vllm/assets/77878387/509d0df8-6abf-4387-8281-5b4c4afc4994)
It shows that the NVIDIA driver is too old. It is not convenient for me to update the driver and I do not know how to solve it

**Comment by Hukongtao** [comment]
> > First git clone the project
> > then
> > ```shell
> > cd vllm
> > pip install -e . --user
> > ```
> 
> ![图片](https://private-user-images.githubusercontent.com/77878387/287585088-509d0df8-6abf-4387-8281-5b4c4afc4994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTg1NTIsIm5iZiI6MTcwMjQ1ODI1MiwicGF0aCI6Ii83Nzg3ODM4Ny8yODc1ODUwODgtNTA5ZDBkZjgtNmFiZi00Mzg3LTgyODEtNWI0YzRhZmM0OTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMGMyYmIxOTI3YTMwMTFkMTg2OTE4NGViYmY4OWFhYTRmNDc0MmQ0ODAxMmY2NzVhZDc1NTFjMWYwMjY4MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLXNrk8O7Qixm4gdX6vpD1Rvdzz0nKOsmZVe_KmzeEg) It shows that the NVIDIA driver is too old. It is not convenient for me to update the driver and I do not know how to solve it

I met the same problem. Have you solved it?

**Comment by Hukongtao** [comment]
> > > First git clone the project
> > > then
> > > ```shell
> > > cd vllm
> > > pip install -e . --user
> > > ```
> > 
> > 
> > ![图片](https://private-user-images.githubusercontent.com/77878387/287585088-509d0df8-6abf-4387-8281-5b4c4afc4994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjMxNzksIm5iZiI6MTcwMTY2Mjg3OSwicGF0aCI6Ii83Nzg3ODM4Ny8yODc1ODUwODgtNTA5ZDBkZjgtNmFiZi00Mzg3LTgyODEtNWI0YzRhZmM0OTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA0MDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDJmNWJhMTM2YTE0OWUwYTlkZjI5NjE2M2U4M2FhNmM3YzFkZWY4ZWRjNzcyZGFjODJlYmY2YjY0MTVkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iueox485piAZmZLL-wcvo846FRbfy_WZ-ZBibgIRTQQ) It shows that the NVIDIA driver is too old. It is not convenient for me to update the driver and I do not know how to solve it
> 
> I think downloading and installing the latest NVIDIA GPU driver (not CUDA) should solve the problem.



> > > First git clone the project
> > > then
> > > ```shell
> > > cd vllm
> > > pip install -e . --user
> > > ```
> > 
> > 
> > ![图片](https://private-user-images.githubusercontent.com/77878387/287585088-509d0df8-6abf-4387-8281-5b4c4afc4994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NjMxNzksIm5iZiI6MTcwMTY2Mjg3OSwicGF0aCI6Ii83Nzg3ODM4Ny8yODc1ODUwODgtNTA5ZDBkZjgtNmFiZi00Mzg3LTgyODEtNWI0YzRhZmM0OTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA0MDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMDJmNWJhMTM2YTE0OWUwYTlkZjI5NjE2M2U4M2FhNmM3YzFkZWY4ZWRjNzcyZGFjODJlYmY2YjY0MTVkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iueox485piAZmZLL-wcvo846FRbfy_WZ-ZBibgIRTQQ) It shows that the NVIDIA driver is too old. It is not convenient for me to update the driver and I do not know how to solve it
> 
> I think downloading and installing the latest NVIDIA GPU driver (not CUDA) should solve the problem.

It is not a personal computer and does not have permission to upgrade the driver.

**Comment by Kawai1Ace** [comment]
> > > First git clone the project
> > > then
> > > ```shell
> > > cd vllm
> > > pip install -e . --user
> > > ```
> > 
> > 
> > ![图片](https://private-user-images.githubusercontent.com/77878387/287585088-509d0df8-6abf-4387-8281-5b4c4afc4994.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTg1NTIsIm5iZiI6MTcwMjQ1ODI1MiwicGF0aCI6Ii83Nzg3ODM4Ny8yODc1ODUwODgtNTA5ZDBkZjgtNmFiZi00Mzg3LTgyODEtNWI0YzRhZmM0OTk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMGMyYmIxOTI3YTMwMTFkMTg2OTE4NGViYmY4OWFhYTRmNDc0MmQ0ODAxMmY2NzVhZDc1NTFjMWYwMjY4MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLXNrk8O7Qixm4gdX6vpD1Rvdzz0nKOsmZVe_KmzeEg) It shows that the NVIDIA driver is too old. It is not convenient for me to update the driver and I do not know how to solve it
> 
> I met the same problem. Have you solved it?

No. So I use colab

**Comment by ybdesire** [comment]
same issue, still no solution

**Comment by youkaichao** [comment]
Sorry but we cannot do anything in this situation. vllm requires proper cuda version and driver version to function correctly.
