### ISSUE TITLE
How can I run VLLM serving without an internet connection?

### ISSUE THREAD

**Issue by ZPerling** [vllm-project/vllm#1910]
### Discussed in https://github.com/vllm-project/vllm/discussions/1405

<div type='discussions-op-text'>

<sup>Originally posted by **ZPerling** October 18, 2023</sup>
I cloned the model repository on Hugging Face to my local machine and used the `--download-dir` parameter to specify the directory. However, when running VLLM, it still tries to connect to Hugging Face, which doesn't work without an internet connection. Even after setting `export HF_HUB_OFFLINE=1`, offline mode doesn't seem to be working. Is it possible to run VLLM offline and if so, how can I achieve this?
</div>

**Comment by simon-mo** [comment]
I think this is possible with one small addition of flag `local_files_only` in the huggingface loader, see more in #1824 and contribution welcomed!

**Comment by HYZ17** [comment]
Using absolute path to load the model, rather than the name of huggingface, works for me. For example, 
```
import os 
os.environ["CUDA_VISIBLE_DEVICES"] = "5"
from vllm import LLM

prompts = ["Hello, my name is", "The capital of France is"]  # Sample prompts.
#llm = LLM(model="/home/.cache/huggingface/hub/models--huggyllama--llama-13b/snapshots/bf57045473f207bb1de1ed035ace226f4d9f9bba",)
outputs = llm.generate(prompts)  # Generate texts from the prompts.
print(outputs)
```

**Comment by clxyder** [comment]
`HT_HUB_OFFLINE=1` should now be fixed with `huggingface_hub>=0.20.0`, which includes: https://github.com/huggingface/huggingface_hub/pull/1899

**Comment by ZPerling** [comment]
@clxyder `HF_HUB_OFFLINE=1` work for me，thanks

**Comment by AIApprentice101** [comment]
@ZPerling 

with `os.environ['HF_HUB_OFFLINE'] = "1"`, I received the following error: `OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/TheBloke/Mistral-7B-Instruct-v0.2-AWQ: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.`

I'm using `huggingface_hub==0.20.3` and `vllm==0.3.2`

How did you mange to make it work? Thanks.

**Comment by juud79** [comment]
> @ZPerling
> 
> with `os.environ['HF_HUB_OFFLINE'] = "1"`, I received the following error: `OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/TheBloke/Mistral-7B-Instruct-v0.2-AWQ: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.`
> 
> I'm using `huggingface_hub==0.20.3` and `vllm==0.3.2`
> 
> How did you mange to make it work? Thanks.

you solve that problem? i faced that problem
