### ISSUE TITLE
Is tensor core the default for computation ？

### ISSUE THREAD

**Issue by shatealaboxiaowang** [vllm-project/vllm#1915]
Hi Dear:
I have two questions:
(1) If compiling and reasoning on the A100, the default is to use tensor core for reasoning, Not cuda core, right ?
(2) If using the int4 quantized model for inference,  need to de-quantize the inference calculation?
thank you!

**Comment by tonystz** [comment]
I use 2 T4 for inference, but the tensor core Utilization is low, it's normal?
![image](https://github.com/vllm-project/vllm/assets/8477911/004d0cec-3202-4750-8328-1cb4cee2c005)
