### ISSUE TITLE
When to support  Yi-34B-Chat-8bits （gptq）？

### ISSUE THREAD

**Issue by cgq0816** [vllm-project/vllm#1916]
![image](https://github.com/vllm-project/vllm/assets/42534237/8341b4d8-fc98-4c05-9c68-20d377dae834)

**Comment by a1164714** [comment]
https://github.com/chu-tianxiang/vllm-gptq/

**Comment by esmeetu** [comment]
Hi @cgq0816 ,  [v0.3.3](https://github.com/vllm-project/vllm/releases/tag/v0.3.3) has support 8bit GPTQ which can meet you needs.
