### ISSUE TITLE
Can it support macos ?  M2 chip.

### ISSUE THREAD

**Issue by znsoftm** [vllm-project/vllm#1921]
Asas

**Comment by simon-mo** [comment]
Currently vLLM doesn't support macOS or windows native. It is currently designed to support NVIDIA with AMD GPU support in progress. 

If you want to use m2 chip right now, I would recommend using llama.cpp for now. 

But we are definitely open for ideas and contributions here! AFIAK, PyTorch's macOS support is pretty behind?

**Comment by pathorn** [comment]
Dupe of #1397 

I just made a PR #2244 - feel free to test and give feedback, but this issue should probably be closed as duplicate.

**Comment by bluenevus** [comment]
+1

**Comment by hmellor** [comment]
Closing in favour of #2081
