### ISSUE TITLE
Question regarding vllm's lack of KV cache clearing?

### ISSUE THREAD

**Issue by EricLBuehler** [vllm-project/vllm#1925]
Hello everybody,

During my development of candle-vllm and before my recent work developing PagedAttention, I added some methods to clear the KV cache (deallocating the old tensors) of the models between requests. This is because I noticed a shape error occurs if the same model was run with a KV cache from an old inference cycle (even with the same prompt). Is this a recognized error, or perhaps a bug with the old KV cache implementation for the Llama-2 model?

I have not run my implementation (although it is based on the vllm implementation), and am not sure if this cache-clearing is still necessary. I use the vllm CUDA kernels as well as basing my implementation on vllm as closely as the language and framework difference allows.

I cannot seem to find any explicit cache clearing happening between inference request, but deallocating the cache would induce a dramatic performance overhead and defeat the point of PagedAttention, so I think that this is probably not being done?

@WoosukKwon, could you please clarify why vllm does not need to clear the cache - is it a bug with my old KV cache implementation, or does it have to do with vllm's batching or something else?

Thanks!

**Comment by EricLBuehler** [comment]
I see the following code in both the non-beam search and beam search cases, which looks like freeing parts of the KV cache? Please correct me if I am wrong.

> https://github.com/vllm-project/vllm/blob/60dc62dc9e53428912953276e0d12a034b353fb6/vllm/engine/llm_engine.py#L429-L435

**Comment by fungaren** [comment]
https://docs.vllm.ai/en/stable/serving/online_serving/#cache-management-apis

Now vllm supported `/reset_prefix_cache` to clear kv cache when `VLLM_SERVER_DEV_MODE=1`
