### ISSUE TITLE
Why we need head_mapping as param pass to paged_attention kernel?

### ISSUE THREAD

**Issue by wbn03** [vllm-project/vllm#1928]
I think this mapping is used to support MQA/GQA. But kv_head_num is fully to express the relation between q's head and kv's head, which can also avoid loading the map into register. is It better? 
Or is there have models must use the mapping to express the relation between q and kv?

**Comment by WoosukKwon** [comment]
Hi @wbn03 thanks for the suggestion. I think your point is valid. Could you submit a PR to fix this?

**Comment by wbn03** [comment]
> Hi @wbn03 thanks for the suggestion. I think your point is valid. Could you submit a PR to fix this?

I submit this PR to fix this. Please review.
[https://github.com/vllm-project/vllm/pull/1997](url)
