### ISSUE TITLE
使用vllm推理gptj模型，相比较HF推理结果缺少一部分

### ISSUE THREAD

**Issue by xixicocorsy** [vllm-project/vllm#1933]
SamplingParams采样设置：(max_tokens=1024, use_beam_search=True, best_of=4, early_stopping=True, temperature=0, top_p=1, top_k=-1) repetition_penalties为1.2
vllm结果：up by Mark Noble led to a first-half goal for Diafra Sakho which was blocked by Courtois. Later in the 15th minute, a through pass from Hazard set Ramires clear on goal, but his delicate side-footed finish struck the inside of the far post and rebounded into the hands of Adrian .
HF结果：up by Mark Noble led to a first-half goal for Diafra Sakho which was blocked by Courtois.\nLater in the 15th minute, a through pass from Hazard set Ramires clear on goal, but his delicate side-footed finish struck the inside of the far post and rebounded into the hands of Adrian.\nEden Hazard scored the only goal of the game in the 22nd minute to give Chelsea a hard-fought win at Upton Park.\nChelsea maintained their five-point lead at the top of the Premier League table.\nWest Ham failed to score in six of their last seven Premier League'
两结果相比较前半句一致，但vllm没有HF结果的后半句，max_tokens也已设为1024

**Comment by xin-li-67** [comment]
hi, there is a [zhihu post](https://zhuanlan.zhihu.com/p/658780653) talking about this. You can check it and see if it works for you.
