### ISSUE TITLE
How to enable data parallelism with multiple gpus for inference?

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#1940]
I know you can achieve tensor parallelism with tensor_parallel_size=2 when using multi-gpus, was wondering if its possible to enable data parallelism as well. I tried making concurrent requests using multi-threading but that came with a host of runtime issues.

**Comment by simon-mo** [comment]
For now, vLLM is designed to host a single copy of the model. To run vLLM on multiple GPUs scaling data parallel, you can try https://github.com/ray-project/ray-llm
