### ISSUE TITLE
AssertionError assert output == other_output when temperature >= 1.6 and top_p >= 0.9

### ISSUE THREAD

**Issue by LokiLiu** [vllm-project/vllm#1942]
Hi,

I recently attempted to apply two models to run on vllm. 

At first, everything went smoothly, but after a while, it was discovered that vllm would encounter TP issues that could not be recovered.

In the end, I found that this issue is easy to  happened in a multi GPU accelerators runtime environment when temperature>=1.6  and top_p >= 0.9.
Especially in an environment with 8 GPU accelerators, it basically appears 100%. 

I tried using the latest  0.2.3 version, but it still appears.

The models I tested is as follows:
1、Qwen/Qwen-72B-Chat:  https://huggingface.co/Qwen/Qwen-72B-Chat 
2、Qwen/Qwen-7B-Chat:    https://huggingface.co/Qwen/Qwen-7B-Chat

The problem is as follows:
File "/usr/local/python-3.8/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 562, in step
    output = self._run_workers(
  File "/usr/local/python-3.8/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 718, in _run_workers
    assert output == other_output

**Comment by jianwenzh** [comment]
+1. Thanks @LokiLiu open this issue! I met this same issue on Llama-2-7B, both A100 and V100. My part observation is it apears when sequence longer to above 2500. It also depends on model (I fine-tuned different versions from the same base model, some of them trigger this while some not). I noticed there were previous issue opened about this https://github.com/vllm-project/vllm/issues/1684 as well.

**Comment by LokiLiu** [comment]
@jianwenzh This issue may caused by some options such as unstable sorting and different GPU accelerators have chosen different IDs. Shall we consider removing this assert judgment or using the results of the first GPU accelerators(id=0) to overwrite the results of GPU accelerators(id=1~N)?

**Comment by uryuk** [comment]
@WoosukKwon @jianwenzh  I met the same issue with the model (GPTQ quantization): https://huggingface.co/TheBloke/Llama-2-70B-GPTQ
Vllm version 0.2.6. It runs on 2 V100 GPUs.  Prompt: fails on any long prompt, a couple of sentences would do.

Every other request fails, and a new parallel request whilst the previous one works, fails the first one.
I added a couple of debug prints here: https://github.com/vllm-project/vllm/blob/main/vllm/engine/async_llm_engine.py#L225 and found this:

```
Output: [SequenceGroupOutput(samples=[SequenceOutput(parent_seq_id=1, output_token=0, logprobs={0: nan})], prompt_logprobs=None)]
Other output: [SequenceGroupOutput(samples=[SequenceOutput(parent_seq_id=1, output_token=0, logprobs={0: nan})], prompt_logprobs=None)]

```
So, the logprobs are NaN and it fails the assert as it should. Any particular place up the code invocation I could check ?

**Comment by jianwenzh** [comment]
@uryuk : Have you tried this recent fix/mitigation: https://github.com/vllm-project/vllm/pull/2209 ?

**Comment by uryuk** [comment]
Wonderful, you already took care of it @jianwenzh ! Yes, I can confirm it solved the issue in my case. Tested on 2, 4 and 8 V100 GPUs. It's a pity streams caused this instability.
