### ISSUE TITLE
Streaming support in VLLM

### ISSUE THREAD

**Issue by Sajalj98** [vllm-project/vllm#1946]
Hi Team, 
I tried using llama 7b for streaming using following code on Jupyter Notebook- 

llm = VLLM(model="meta-llama/Llama-2-7b-chat-hf", use_auth_token=token, max_new_tokens=128,temperature=0.1, top_p=1,
             num_beams=1,top_k=50, trust_remote_code=True, load_in_4bit=True,  streaming=True, callbacks=[StreamingStdOutCallbackHandler()])

For getting tokens i tried - 
1. llm("tell me a long story")
2. for chunk in llm.stream("Write me a song about sparkling water."):
    print(chunk, end="", flush=True)
3. llm.generate(["Write me a song about rain."])

I am getting the response but in one shot and not token wise.
![image](https://github.com/vllm-project/vllm/assets/35100919/e91ca21d-c183-44cb-a217-6d8ba4add2b2)
![image](https://github.com/vllm-project/vllm/assets/35100919/5aba3437-5788-4211-bba0-4ef1d4908fc4)

![image](https://github.com/vllm-project/vllm/assets/35100919/aeeb0e68-2d96-4259-9479-00ed5bd52b8b)

How to i get proper streaming on Jupyter Notebook.

**Comment by chris-aeviator** [comment]
@simon-mo @Sajalj98 could it be we still need https://github.com/vllm-project/vllm/pull/1052 merged?

**Comment by chris-aeviator** [comment]
@Sajalj98 you can just copy over the changes from https://github.com/vllm-project/vllm/pull/1052/files to your vllm to have it work. it should work with llama

**Comment by Sajalj98** [comment]
Thanks @chris-aeviator the changes you suggested is working, I hope the request gets merges to the main branch soon.
I have one more query, how can i use this custom function to send response back to an api call.
Can you provide a reference code snippet.

**Comment by gilljon** [comment]
Are there any plans to get this merged down?

**Comment by chris-aeviator** [comment]
Use asyncVllmEngine for streaming

**Comment by ASC8384** [comment]
> Use asyncVllmEngine for streaming
> […](#)
> Am 24.01.2024 um 22:46 schrieb Jon Gill ***@***.***>: ﻿ Are there any plans to get this merged down? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Excuse me, can you provide a short example of how to run it on the command line

**Comment by malikfaiq555** [comment]
@chris-aeviator changing the source code definately helped thanks for the solution.

**Comment by zhang-boyu** [comment]
> confirm with the changes merged I'm able to stream in a n

I tried your example but it raise an error: " TypeError: generate() got an unexpected keyword argument 'stream'". How does this happen?

**Comment by sancelot** [comment]
@chris-aeviator  small typo error in your link => https://docs.vllm.ai/en/latest/api/engine/async_llm_engine.html
