### ISSUE TITLE
Remove "cuda" and use xpu abstraction

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#1948]
Currently, vLLM has many `cuda`s throughout its codebase. This is only compatible with NVIDAI/AMD/Intel GPUs, and not with other accelerators. A more general abstraction (like xpu in DeepSpeed) is required to support more diverse hardware.

**Comment by Superskyyy** [comment]
Agreed, the abstraction layer would allow the ease of integration of non-cuda accelerators, I'm pretty sure this needs to be sorted out before the ascend NPU support can be integrated into upstream @junior-zsy. I can work on this while adding support for Ascend NPU accelerators. #1606

**Comment by jikunshang** [comment]
hi @WoosukKwon I am trying to resolve this issue in PR #2503, please take a review at your convenience:)
