### ISSUE TITLE
Support for Falcon-7B / 40B models

### ISSUE THREAD

**Issue by sujithjoseph** [vllm-project/vllm#195]
It would be great, if you can add support for Falcon models as well!  Does it support onnx models today?

**Comment by MotzWanted** [comment]
@WoosukKwon When do you anticipate adding support for Falcon to vLLM?

**Comment by WoosukKwon** [comment]
@MotzWanted I'm working on it now. I think we can add less-optimized version of Falcon (MQA replaced by MHA) quickly (within a few days) and then develop kernels to make the model actually use MQA.

**Comment by emphasis10** [comment]
I'm waiting for supporting Falcon families, too. Thanks a lot for your works.

**Comment by HSQ79815** [comment]
great, thanks

**Comment by teopapad92** [comment]
thanks, looking forward to it
