### ISSUE TITLE
Optimum-NVIDIA 28x throughput

### ISSUE THREAD

**Issue by SinanAkkoyun** [vllm-project/vllm#1951]
https://huggingface.co/blog/optimum-nvidia

Hi! It would be awesome if this had latency and throughput implications for this project.

**Comment by zhaoyang-star** [comment]
optimum-nvidia is dependent on trtllm. so I guess the runtime of optimum-nvidia is trtllm.

**Comment by SinanAkkoyun** [comment]
I guess that means that vLLM can not benefit from the transformer-engine FP8 implementation of optimum?
