### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by SingJumpRapp** [vllm-project/vllm#1952]
when I use LLama2-70B(AWQ quantized) and the input more than 4096 tokens, I get the error 'RuntimeError: probability tensor contains either `inf`, `nan` or element < 0', by debugging， I found that the output of the single_query_cached_kv_attention have Nan value.
    I use four A6000 to deploy my service. And here are some informations for initialization：

LlamaTokenizerFast(name_or_path='/home/services/AWQ_model', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
        0: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
        1: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
        2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
AsyncEngineArgs(model='/home/services/AWQ_model', tokenizer='/home/services/AWQ_model', tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', seed=0, max_model_len=10000, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, block_size=16, swap_space=4, gpu_memory_utilization=0.8, max_num_batched_tokens=10000, max_num_seqs=64, max_paddings=256, disable_log_stats=False, revision=None, tokenizer_revision=None, quantization='awq', engine_use_ray=False, disable_log_requests=False, max_log_len=None)

**Comment by 777ki** [comment]
which version of vllm do you use?
could you give us more information about you vllm version, os version

**Comment by SingJumpRapp** [comment]
> which version of vllm do you use? could you give us more information about you vllm version, os version

hello, I use vllm v0.2.1.

**Comment by ayrnb** [comment]
I also encountered the same problem, how can I solve it?
