### ISSUE TITLE
Why does the 8-GPUs experience a longer concurrent delay compared to the 2-GPUs?

### ISSUE THREAD

**Issue by sherry085** [vllm-project/vllm#1954]
I conducted concurrent processing tests on an RTX 3090 and the results showed that it takes longer for the 8-GPUs to process the same concurrent requests than 2-GPUs, and the performance of 4 Gpus is similar to that of 2 Gpus. Reducing max-num-seqs on the 2-GPUs system can accelerate inference, but adjusting max-num-seqs and max-num-batched-tokens on the 8-GPU has little effect, and the speed is still slower than that of the 2-GPUs system. What could be the reason for this? Is it that the scheduling takes more time than the computation? Are there any methods that I can try?

**Comment by hmellor** [comment]
If the overhead of inter-GPU communication is greater than the compute required for the model, then increasing the tensor parallel size will decrease performance.
