### ISSUE TITLE
v100 显卡

### ISSUE THREAD

**Issue by mayu123mayu** [vllm-project/vllm#1955]
什么时候支持v100显卡啊，不支持啊

**Comment by leocnj** [comment]
From my experience, no issue for running vLLM on V100 cards. However, when using AWQ, it looks V100 (GPU level 70) cannot handle (at least 75). 

一般FP6的模型，V100 可以使用，但是AWQ好像就不行了。

**Comment by aliencaocao** [comment]
GPTQ 8bit doesnt run on v100 for me...4bit works fine

**Comment by 1SingleFeng** [comment]
同样急切的需要，please
