### ISSUE TITLE
Repeated answer: When I use vllm with opt-13b, the generated text is not end until the max length, with the repeated answer

### ISSUE THREAD

**Issue by duihuhu** [vllm-project/vllm#1958]
hi, I use vllm in greedy SamplingType, I meet  the repeated answer: 
`sampling_params = SamplingParams(temperature=0, top_p=1, max_tokens=2048)`

`from vllm import LLM, SamplingParams

# Sample prompts.
prompts = [
    "Give three tips for staying healthy.",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0, top_p=1, max_tokens=2048)

# Create an LLM.
llm = LLM(model="/workspace/opt-13b/", tensor_parallel_size=4)
outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}", len(output.out
puts[0].token_ids))`

The answer is follow, the same text is repreated, also to other prompts.
![截屏2023-12-07 下午3 59 51](https://github.com/vllm-project/vllm/assets/8213143/dd316200-1c6b-420e-abbf-2fd07dbd8283)

So is there any way to solve this problem?
Thanks.

**Comment by ChengShuting** [comment]
did you find the solution?

**Comment by joaograndotto** [comment]
Same issue

**Comment by kbwzy** [comment]
any one hase idea?

**Comment by atharvajk98** [comment]
Facing the same issue! Any possible solutions?

**Comment by edwardh5** [comment]
<img width="1585" alt="Screenshot 2024-11-19 at 11 11 12 PM" src="https://github.com/user-attachments/assets/a6ceb714-f5cb-4a76-8ba5-e2db2e776ba5">
I'm getting the same

**Comment by dkkb** [comment]
Is this a bug of vllm?

**Comment by zzy7517** [comment]
why this issus is closed

**Comment by auto-Dog** [comment]
similiar issuse, on kaggle environment. I tried and found update vllm can relieve it.

**Comment by Gzzz2022** [comment]
Same issue
