### ISSUE TITLE
Proposal: pre-commit instead of format.sh

### ISSUE THREAD

**Issue by explainerauthors** [vllm-project/vllm#1969]
It seems that tools called in `./format.sh` could be easily configured to be call by pre-commit by adding them to the file `/.pre-commit-config.yaml`.

Once we do this, every time, contributors run `git commit`, they could run these tool with the **new content**, which shouldn't take much time.

Also, we could create a GitHub action to run `pre-commit run --all-files` to check the consistent project style.

Is this a good idea? Thanks!

**Comment by yunfeng-scale** [comment]
there's https://github.com/vllm-project/vllm/pull/1442. will go back to this
