### ISSUE TITLE
KeyError on Loading LLaMA Parameters in vLLM due to Unhandled Cached Rotary Embeddings

### ISSUE THREAD

**Issue by imgaojun** [vllm-project/vllm#1977]
While integrating the LLaMA model with vLLM, I encountered a KeyError related to the rotary embeddings' cached cosine and sine values (`cos_cached` and `sin_cached`). These parameters, while present in LLaMA, are not directly handled or required by vLLM. This results in a conflict when loading the model with these cached values.

<img width="445" alt="1bd6757a5380e4c463c57168845edcf7" src="https://github.com/vllm-project/vllm/assets/9442170/e59bd379-92ab-433d-852b-a904cbac8568">

**Comment by imgaojun** [comment]
Hi @WoosukKwon. Thank you for your prompt response. I encountered this issue while working with the LLaMA 2-7b model. Specifically, the scenario arose after fine-tuning the LLaMa2-7b model using the ColossalAI framework. It appears that ColossalAI saved all the parameters of the LLaMa2-7b model, including `inv_freq`, `cos_cached`, and `sin_cached`.

This preservation of all parameters, including those related to rotary embeddings, led to the KeyError when integrating with vLLM. I believe these extra parameters (`cos_cached` and `sin_cached`), which are not directly utilized by vLLM, are creating the conflict.

```
class LlamaRotaryEmbedding(nn.Module):
    def __init__(self, dim, max_position_embeddings=2048, base=10000, device=None):
        super().__init__()

        self.dim = dim
        self.max_position_embeddings = max_position_embeddings
        self.base = base
        inv_freq = 1.0 / (self.base ** (torch.arange(0, self.dim, 2).float().to(device) / self.dim))
        self.register_buffer("inv_freq", inv_freq, persistent=False)

        # Build here to make `torch.jit.trace` work.
        self._set_cos_sin_cache(
            seq_len=max_position_embeddings, device=self.inv_freq.device, dtype=torch.get_default_dtype()
        )

    def _set_cos_sin_cache(self, seq_len, device, dtype):
        self.max_seq_len_cached = seq_len
        t = torch.arange(self.max_seq_len_cached, device=device, dtype=self.inv_freq.dtype)

        freqs = torch.outer(t, self.inv_freq)
        # Different from paper, but it uses a different permutation in order to obtain the same calculation
        emb = torch.cat((freqs, freqs), dim=-1)
        self.register_buffer("cos_cached", emb.cos().to(dtype), persistent=False)
        self.register_buffer("sin_cached", emb.sin().to(dtype), persistent=False)

    def forward(self, x, seq_len=None):
        # x: [bs, num_attention_heads, seq_len, head_size]
        if seq_len > self.max_seq_len_cached:
            self._set_cos_sin_cache(seq_len=seq_len, device=x.device, dtype=x.dtype)

        return (
            self.cos_cached[:seq_len].to(dtype=x.dtype),
            self.sin_cached[:seq_len].to(dtype=x.dtype),
        )
```

**Comment by Yard1** [comment]
Closed by https://github.com/vllm-project/vllm/pull/1978
