### ISSUE TITLE
Add support for GPTJ

### ISSUE THREAD

**Issue by ri938** [vllm-project/vllm#198]
Will it be possible to add support for GPTJ please? Any plans for this?

**Comment by zhuohan123** [comment]
Supporting GPTJ is in our plan! Please stay tuned and let us know if you are interested in contribute the model!

**Comment by beratcmn** [comment]
GPT-J and GPT-NeoX have similar architectures. Maybe a hacky solution is possible as of now.

**Comment by Vineetls** [comment]
For what it's worth I'd also be very interested in this feature

**Comment by zhuohan123** [comment]
Fixed by #226
