### ISSUE TITLE
latest version requires cuda >= 12.1?

### ISSUE THREAD

**Issue by lkluo** [vllm-project/vllm#1980]
I have a problem getting the garbage outputs with version >= 0.2.2, but works fine with lower version e.g. 0.2.1.post1.
Could it be related to cuda version? mine is 11.8.
I also have a try with cu118 version, or build from source, but didn't work.

**Comment by lkluo** [comment]
same issue #1929

**Comment by miko7879** [comment]
Install the CUDA 11.8 version as per instructions here: https://docs.vllm.ai/en/latest/getting_started/installation.html

For VLLM_VERSION use 0.2.5

```
# Install vLLM with CUDA 11.8.
export VLLM_VERSION=0.2.4
export PYTHON_VERSION=39
pip install https://github.com/vllm-project/vllm/releases/download/v${VLLM_VERSION}/vllm-${VLLM_VERSION}+cu118-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux1_x86_64.whl

# Re-install PyTorch with CUDA 11.8.
pip uninstall torch -y
pip install torch --upgrade --index-url https://download.pytorch.org/whl/cu118
```

**Comment by lkluo** [comment]
@miko7879 thanks, very helpful.
