### ISSUE TITLE
vllm inference server without internet: vLLM: raise ConnectionError(e, request=request)

### ISSUE THREAD

**Issue by llmwesee** [vllm-project/vllm#1986]
When I ran vllm inference server without internet connection then it throws the following error

`File "/home/miniconda3/envs/vllm/lib/python3.10/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/meta-llama/Llama-2-13b-chat-hf/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb471e53400>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 180aa8f1-bd8d-4f1e-bc19-2ba285227928)')`

When i power on the server, it ask for internet connection to run vllm. However, I want to use h2ogpt with vllm inferencing on my private server without internet connection.

Please help me regarding this!

****Command I hit:
`python -m vllm.entrypoints.openai.api_server --port=5000 --host=0.0.0.0 --model meta-llam
a/Llama-2-13b-chat-hf --tokenizer=hf-internal-testing/llama-tokenizer --tensor-parallel-size=1 --seed 1234 --max-num-batched-tokens=4096`
`

**Comment by hmellor** [comment]
If you don't have internet then `--model` must have already been cached. Right now vLLM is trying to download a model checkpoint because it doesn't exist locally.

**Comment by youkaichao** [comment]
There is a flag `local_files_only`from huggingface.

https://huggingface.co/docs/transformers/v4.39.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained.local_files_only(bool,

By default, it asks for internet connection because it will try to check for the latest model. Yes, models can be updated by the authors...

**Comment by njhill** [comment]
I think this is actually a problem currently in vLLM. See discussion in https://github.com/vllm-project/vllm/pull/3125

**Comment by hmellor** [comment]
Good point, you can get around it using `HF_HUB_OFFLINE=1` too.

So I'd consider this resolved and the PR you linked a UX improvement.

**Comment by prashantgupta24** [comment]
@hmellor but even having the model in my local cache, if I set `HF_HUB_OFFLINE=1`, vllm still fails to start, which is what @njhill tagged above. See below

```
$ ls cache

models--facebook--opt-125m  version.txt
```

```
export TRANSFORMERS_CACHE=cache
export HF_HUB_CACHE=cache
export HF_HUB_OFFLINE=1
```

and
```
LLM(model="facebook/opt-125m")
``` 
gives me
```
huggingface_hub.utils._http.OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/facebook/opt-125m: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.
```
even though the model exists in my cache

**Comment by a823883735** [comment]
Deploying in Kubernetes using vllm/vllm openai: latest is also a connectionError exception. After setting HF_SUB_SFFLINE to 1, the problem occurred again:
ValueError: Invalid repository ID or local directory specified: 'mistralai/Mistral-7B-Instruct-v0.3'.
Please verify the following requirements:
1. Provide a valid Hugging Face repository ID.
2. Specify a local directory that contains a recognized configuration file.
- For Hugging Face models: ensure the presence of a 'config.json'.
- For Mistral models: ensure the presence of a 'params.json'.

**Comment by a823883735** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/main.py", line 53, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/serve.py", line 27, in cmd
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1078, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 146, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 166, in build_async_engine_client_from_engine_args
    vllm_config = engine_args.create_engine_config(usage_context=usage_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/arg_utils.py", line 1098, in create_engine_config
    device_config = DeviceConfig(device=self.device)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.12/dist-packages/vllm/config.py", line 2119, in __post_init__
    raise RuntimeError(
RuntimeError: Failed to infer device type, please set the environment variable `VLLM_LOGGING_LEVEL=DEBUG` to turn on verbose logging to help debug the issue.
