### ISSUE TITLE
Ignore `model` key in the vLLM OpenAI server mode

### ISSUE THREAD

**Issue by flexchar** [vllm-project/vllm#1988]
I use vLLM to serve private AI model on dedicate instance that is consumed by existing infra across many languages. If I retrain model and deploy, I need to also update other databases to request the right model. 

I feel like it'd be great if `model` in the request would actually be ignored. I find this reasonable expectation because vLLM supports serving only one model at a time. That model's name is always shown in the response and thus it's still visible. This way my backend could accept any model that is currently active.

Does this sound reasonable? :)

**Comment by flexchar** [comment]
That helps but causes issue in the tracking. I use model value on the response object to log requests that are rated by people (thumbs up or down). If I use same dummy name, then I cannot scope ratings. :(

**Comment by SMAntony** [comment]
> I use vLLM to serve private AI model on dedicate instance that is consumed by existing infra across many languages. If I retrain model and deploy, I need to also update other databases to request the right model.
> 
> I feel like it'd be great if `model` in the request would actually be ignored. I find this reasonable expectation because vLLM supports serving only one model at a time. That model's name is always shown in the response and thus it's still visible. This way my backend could accept any model that is currently active.
> 
> Does this sound reasonable? :)

Any reason why this is not supported?

**Comment by hmellor** [comment]
You can achieve the same effect by profiding multiple model names to the `--served-model-name` argument.

i.e. `--served-model-name long-specific-name default` would allow your backend to always call the model called `default` and the `model` field in the response will be `long-specific-name`.

From the docs:
> `--served-model-name`
>    The model name(s) used in the API. If multiple names are provided, the server will respond to any of the provided names. The model name in the model field of a response will be the first name in this list. If not specified, the model name will be the same as the –model argument. Noted that this name(s) will also be used in model_name tag content of prometheus metrics, if multiple names provided, metrics tag will take the first one.
