### ISSUE TITLE
How can I deploy vllm model with multi-replicas

### ISSUE THREAD

**Issue by youthbupt** [vllm-project/vllm#1995]
I want to deploy a LLM model on 8 A100 gpus. 
To support the higher concurrency, I want to deploy 8 replicas (one replica on one gpu), and I want to expose one service to handle user requests, how can I do it?

**Comment by lambda7xx** [comment]
you mean each gpu has one vllm?  and it serve. small model like 13b

**Comment by youthbupt** [comment]
> you mean each A100 gpu has one vllm? and it serves small model like `13b`

yes, how can I manage these model replicas in one service ?

**Comment by lambda7xx** [comment]
> > you mean each A100 gpu has one vllm? and it serves small model like `13b`
> 
> yes, how can I manage these model replicas in one service ?

maybe you can do like below.
1)first, use 8 ports to launch  8 vllm on each gpu
2)set a frontend and receive the request from user,  then router the requests to one vllm based on load balance.

**Comment by linchen111** [comment]
> > > you mean each A100 gpu has one vllm? and it serves small model like `13b`
> > 
> > 
> > yes, how can I manage these model replicas in one service ?
> 
> maybe you can do like below. 1)first, use 8 ports to launch 8 vllm on each gpu 2)set a frontend and receive the request from user, then router the requests to one vllm based on load balance.

If I want to do inference offline,how should I do this

**Comment by Drzhivago264** [comment]
CUDA_VISIBLE_DEVICES= 0 python -m vllm.entrypoints.api_server --model [your model] --port 8080
Cuda visible devices are from 0 to 7 if your machine have 8 of them. You need to choose multiple port (e.g., from 8001 to 8007)
Then you can send request to 127.0.0.1:[your port] to inference your server locally.

**Comment by hmellor** [comment]
This can be acheived using https://github.com/lm-sys/FastChat and their vLLM integration by running a single controller and multiple vLLM model workers.
