### ISSUE TITLE
Fail to install the old version with the provided command, report error

### ISSUE THREAD

**Issue by xyingZHANG** [vllm-project/vllm#1999]
fail to install the old version: 
pip install https://github.com/vllm-project/vllm/releases/download/v0.2.2/vllm-0.2.2+cu118-cp310-cp310-manylinu**x1_x86_64.whl
### ERROR: vllm-0.2.2+cu118-cp310-cp310-manylinux1_x86_64.whl is not a supported wheel on this platform.**

**Comment by chasezcz** [comment]
The same issue occurred while I was working on Docker.

**Comment by griff4692** [comment]
Is there a resolution to this? I'm having the same issue

**Comment by cbettero** [comment]
same issue:
pip install https://github.com/vllm-project/vllm/releases/download/v0.2.4/vllm-0.2.4+cu118-cp311-cp311-manylinux1_x86_64.whl4

fails with same error;
Env:
Windows 11
Conda
Python 3.11
Cuda 18
RTX 4090

**Comment by youkaichao** [comment]
Please install the latest version, and use a supported operating system.

Windows is not supported natively, but you can use WSL.
