### ISSUE TITLE
I want to add mamba_chat (2.8b) model 

### ISSUE THREAD

**Issue by SafeyahShemali** [vllm-project/vllm#2001]
Hello vllm Team, 

havenhq/mamba-chat seems not supported with vllm. Will you be able to help me out to add it?

Sincerely,

**Comment by DarkLight1337** [comment]
FYI Jamba is now supported in vLLM (#4115), so it should be easier to implement this model now.

**Comment by DarkLight1337** [comment]
I think this should be solved by #6484

**Comment by tlrmchlsmth** [comment]
Mamba support just landed (still TODO to support Mamba2, so Codestral Mamba is not yet supported)
