### ISSUE TITLE
Does vllm-0.2.1 support Baichuan2?

### ISSUE THREAD

**Issue by rualars** [vllm-project/vllm#2010]
For some reasons, I have to use the vllm-0.2.1, and I'm not sure if the version supports Baichuan2.

**Comment by firebook** [comment]
> For some reasons, I have to use the vllm-0.2.1, and I'm not sure if the version supports Baichuan2.

The version did not support Baichuan2，but you can merge the fix (#1876 ) to 0.2.1，and compile for yourself.

**Comment by rualars** [comment]
> > For some reasons, I have to use the vllm-0.2.1, and I'm not sure if the version supports Baichuan2.
> 
> The version did not support Baichuan2，but you can merge the fix (#1876 ) to 0.2.1，and compile for yourself.

Thank you!
