### ISSUE TITLE
Specify `--load-format pt` for Mixtral

### ISSUE THREAD

**Issue by pierrestock** [vllm-project/vllm#2018]
As explained [here](https://huggingface.co/mistralai/Mixtral-8x7B-v0.1/discussions/3), HF pushed some changes to the official repo to make it compatible with `transformers==4.36.0.dev0`. Need to double check that this does not break vLLM integration (in particular, we don't want to load weights twice, and model name changed from `mistral` to `mixtral`).

https://github.com/vllm-project/vllm/blob/b5f882cc98e2c9c6dde7357dbac2ec0c2c57d8cd/requirements.txt#L10C20-L10C20

**Comment by void-b583x2-NULL** [comment]
That's pretty urgent. I've tried the updated vLLM version for mixtral/mistral, but the following error could not be avoided:
```
File ~/anaconda3/envs/vllm/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py:792, in _LazyConfigMapping.__getitem__(self, key)
    790     return self._extra_content[key]
    791 if key not in self._mapping:
--> 792     raise KeyError(key)
    793 value = self._mapping[key]
    794 module_name = model_type_to_module_name(key)

KeyError: 'mixtral'
```
 I've tried lots of kinds of modifications to the code but failed. Any ideas or updates on this?

**Comment by pierrestock** [comment]
Adding `--load-format pt` seems do to the trick. I'll let you guys advertise it (maybe an assert in the code)?

**Comment by xiechengmude** [comment]
> Adding `--load-format pt` seems do to the trick. I'll let you guys (@WoosukKwon @zhuohan123) advertise it (maybe an assert in the code)?

I met this problem too. How to add this param ?
