### ISSUE TITLE
Implement Retrieval QA support

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#2037]
I am using a Retriever with a question answer chain and wanted to use vllm for my llm:

`
from langchain.llms import VLLM
from langchain.chains import RetrievalQA
from langchain.vectorstores import FAISS
from langchain_core.vectorstores import VectorStoreRetriever

vllm = VLLM(
    model="mosaicml/mpt-7b",
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=128,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
)
retriever = VectorStoreRetriever(vectorstore=FAISS(...))
retrievalQA = RetrievalQA.from_llm(llm=vllm,, retriever=retriever)
`

**Comment by simon-mo** [comment]
Which feature is missing from vLLM to support this?
