### ISSUE TITLE
Support Mixtral's safetensors weights

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2041]
Currently, we only support Mistral's pt format weights. Let's support safetensors weights as the pt weight files might also be changed by HF in the future.

**Comment by nidhishs** [comment]
How can I convert the safe tensors weights for a Mixtral fine-tune to pt in the meantime?

**Comment by codybum** [comment]
I also can't seem to find any information about converting safe tensors or merged python_model.bin to pt.

**Comment by WoosukKwon** [comment]
This will be fixed by #2090
