### ISSUE TITLE
The returned results using prompt_logprobs=1

### ISSUE THREAD

**Issue by getao** [vllm-project/vllm#2043]
It seems that setting prompt_logprobs=1 will return the scoring of the context (i.e., prompt). However, the returned results are a little confusing:

When I used a Llama-2-7b to score a sequece, the returned results look as follow:

[None, {15043: -7.584228515625, 917: -2.512939214706421}, {29892: -1.4937736988067627}, {590: -1.8308428525924683, 306: -1.3464678525924683}, {1024: -0.11963547021150589}, {338: -0.01794273406267166}]

The first and third positions have two keys while the other positions have only 1 key. Is that because the position's word is not the word with the highest prob?

**Comment by jiangllan** [comment]
same question

**Comment by answer-Li** [comment]
我也遇到了同样的问题

**Comment by iseesaw** [comment]
same question
