### ISSUE TITLE
Vllm RayWoker  process hangs when use llm engine

### ISSUE THREAD

**Issue by SuoSiFire** [vllm-project/vllm#2050]
When I use vllm's https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/llm.py to load the Qwen-14b model。 all requests will get stuck and can be reproduced repeatedly

**Code**

`
self.vllm_model = LLM(model=os.path.join(dir_path, config['model_path']),
                               tensor_parallel_size=2,
                               trust_remote_code=True,
                               gpu_memory_utilization=0.9)
`

**GPU**

Use 2 V100 gpu to load the qwen14b model

**VLLM Version**

vllm version 0.2.1

**Problem**

After a certain request, all requests will be stuck and there will be no error log, but the main process will not hang up. Through nvidia-smi, observe that one of the two rayworker processes remains alive.

I would like to ask if this is a problem caused by llm engine, or a problem caused by using rayworker. Is it possible to solve using async llm engine?

**Comment by SuoSiFire** [comment]
error message：

WARNING worker.py:2074 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff0894b66f4e27693713fa99ae01000000 Worker ID: 79ef46dc1931ca50726a4dfae1c1695d9f0d67279e0e27544aa431d0 Node ID: 134a026a4d55de851b3d23099108d4a3d4b27ca8fb63a73177f89ec9 Worker IP address: 10.104.42.179 Worker port: 39411 Worker PID: 1098 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors

**Comment by shyringo** [comment]
could refer to issue #1908, https://github.com/vllm-project/vllm/issues/1908#issuecomment-2074543512, which solves the hanging of ray by the following code:
        #llm is a vllm.LLM object
        import gc
        import torch
        from vllm.model_executor.parallel_utils.parallel_state import destroy_model_parallel
        import os

        #avoid huggingface/tokenizers process dead lock
        os.environ["TOKENIZERS_PARALLELISM"] = "false"
        destroy_model_parallel()
        #del a vllm.executor.ray_gpu_executor.RayGPUExecutor object
        del llm.llm_engine.model_executor
        del llm
        gc.collect()
        torch.cuda.empty_cache()
        import ray
        ray.shutdown()
