### ISSUE TITLE
Support VLM model and GPT4V API

### ISSUE THREAD

**Issue by xunfeng1980** [vllm-project/vllm#2058]
VLM model: Qwen-VL/LLaVA etc
VLM API: GPT-4V API https://platform.openai.com/docs/guides/vision

**Comment by l4b4r4b4b4** [comment]
I strongly second this. However Llava 1.6 models are very peculiar :D

**Comment by Reichenbachian** [comment]
It's fine if it's peculiar. We can just error (BadRequest) anything that doesn't have image first or multiple images for instance, but still keep the same format. We shouldn't design the endpoint around the model. The model should fit into the endpoint.

**Comment by ywang96** [comment]
Closing this as we merged #5237
