### ISSUE TITLE
mixtral-8x7B-Instruct-v0.1 giving garbage output on long prompts

### ISSUE THREAD

**Issue by vibhuagrawal14** [vllm-project/vllm#2059]
Having some trouble pinpointing if its my prompts that is causing this, but often on long-ish prompts (5k+ tokens), the output is either completely unrelated (as in the attached image), or just a word/pair-of-words/phrase being repeated endlessly.

<img width="909" alt="image" src="https://github.com/vllm-project/vllm/assets/35597204/3e1f31b3-6f64-497d-beb3-2ae3b4dd9a30">

Is anybody else facing the same issue?

**Comment by arshadshk7** [comment]
same issue here

**Comment by WoosukKwon** [comment]
Hi @vibhuagrawal14 Thanks for reporting the bug. We just fixed it in #2088. Please [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source) until we publish a new release.

**Comment by vibhuagrawal14** [comment]
Thank you!
