### ISSUE TITLE
[BUG] Mistral/Mixtral generate nonsense past 4096 tokens in prompt

### ISSUE THREAD

**Issue by AlpinDale** [vllm-project/vllm#2064]
If the prompt contains more than 4k tokens, the model will begin generating nonsense. This seems to be true for both Mistral and Mixtral. I launched the engine at both 32k and 8k max model lengths for testing. Tested with the latest vllm release.

**Comment by AlpinDale** [comment]
![image](https://github.com/vllm-project/vllm/assets/52078762/298db9fb-2e01-4837-93f0-b0d99664d6ee)
Tested using [SillyTavern](https://github.com/SillyTavern/SillyTavern). No issues with the prompt (I manually inspected, and it works perfectly fine with other models). 

CC @WoosukKwon @zhuohan123 because this seems like an important bug.

**Comment by AlpinDale** [comment]
![image](https://github.com/vllm-project/vllm/assets/52078762/db54943d-a1de-4458-a946-486b01ba96e8)

**Comment by stefanobranco** [comment]
I have noticed the same thing. I'm running from docker, and tried with both the latest and built from source, with no difference.

`docker run -it --gpus all -e HUGGING_FACE_HUB_TOKEN=$token --ipc=host -p 8080:8080 -v $volume:/root/.cache/huggingface docker.io/vllm/vllm-openai --model $model --tensor-parallel-size 8 --port 8080 --load-format pt`

As far as I can tell I'm not doing anything special, and the same setup works with hf tgi, so it doesn't appear to be a model issue.

**Comment by arshadshk7** [comment]
I am having the same issue with Mistral 7b.

**Comment by dev-mush** [comment]
I am having the same issue, was wondering if it has something to do with the sliding_window config, I'm running it using vLLM

**Comment by vibhuagrawal14** [comment]
@dev-mush what value did you update it to?

**Comment by dev-mush** [comment]
> @dev-mush what value did you update it to?

32k, mistral team says that it should theoretically support up to 128k context, but the problem went away as soon as I got it to 8k...I'm having troubles understanding how the sliding_window affects the quality of the output to be honest, so any hint is well appreciated ☺️

**Comment by vibhuagrawal14** [comment]
with 32k, I am getting `rpc error: code = DeadlineExceeded desc = context deadline exceeded%`
8k is working though, but the garbage is still there for me :/ 

full traceback here:

```
Traceback (most recent call last):▉| 12.1G/12.1G [05:32<00:00, 40.6MB/s]
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main]
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 729, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 107, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 194, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 727, in _run_workers_in_batch
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ChunkedEncodingError): ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 833, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(4963331015 bytes read, 7171139841 more expected)

The above exception was the direct cause of the following exception:

ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 934, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 905, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 811, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 729, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(4963331015 bytes read, 7171139841 more expected)', IncompleteRead(4963331015 bytes read, 7171139841 more expected))

During handling of the above exception, another exception occurred:

ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 32, in execute_method
    return executor(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 72, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 36, in load_model
    self.model = get_model(self.model_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 124, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 519, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 201, in hf_model_weights_iterator
    hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 141, in prepare_hf_model_weights
    hf_folder = snapshot_download(model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 238, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 213, in _inner_hf_hub_download
    return hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1461, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 541, in http_get
    for chunk in r.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(4963331015 bytes read, 7171139841 more expected)', IncompleteRead(4963331015 bytes read, 7171139841 more expected))
consolidated.01.pt: 100%|██████████| 12.1G/12.1G [05:32<00:00, 36.5MB/s]
rpc error: code = DeadlineExceeded desc = context deadline exceeded%
```

**Comment by arshadshk** [comment]
@dev-mush wouldn't it affect it if we increase the sliding window to 8k? Since it's trained with windows of 4k, the overall scales of attention output would change.

I wonder why using a 4k sliding window would be a problem since it is a "sliding window." Even if the context size is 8k, it would still only attend to the previous 4k tokens, hence having the same effect as with 4k.

**Comment by WoosukKwon** [comment]
Hi @AlpinDale Thanks for reporting the bug. We just fixed it in #2088. Please [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source) until we publish a new release.

**Comment by AlpinDale** [comment]
@WoosukKwon that seems to have fixed the issue, but not *quite*. Now, the model completely ignores any tokens past the 4096 context window. Perhaps it'd be best if the sliding window value was aligned with the max model length? As in, the `max_model_len` arg would also change the sliding window value. Manually setting it to 32k in the config.json fixes this issue.

**Comment by WoosukKwon** [comment]
@AlpinDale Could you provide a reproducible example?

**Comment by exceedzhang** [comment]
I ran Mixtral Model using vLLM! I found Error!
<img width="1512" alt="image" src="https://github.com/vllm-project/vllm/assets/4583537/5a866e57-4c6b-42bb-a8b5-75f6514bba49">

<img width="1512" alt="image" src="https://github.com/vllm-project/vllm/assets/4583537/062b8fcd-d741-4e43-9a5f-0d4658005f7f">

Can anyone know why?

**Comment by rakesgi2022** [comment]
> with 32k, I am getting `rpc error: code = DeadlineExceeded desc = context deadline exceeded%` 8k is working though, but the garbage is still there for me :/
> 
> full traceback here:
> 
> ```
> Traceback (most recent call last):▉| 12.1G/12.1G [05:32<00:00, 40.6MB/s]
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main]
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 729, in <module>
>     engine = AsyncLLMEngine.from_engine_args(engine_args)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 495, in from_engine_args
>     engine = cls(parallel_config.worker_use_ray,
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
>     self.engine = self._init_engine(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
>     return engine_class(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 107, in __init__
>     self._init_workers_ray(placement_group)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 194, in _init_workers_ray
>     self._run_workers(
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 750, in _run_workers
>     self._run_workers_in_batch(workers, method, *args, **kwargs))
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 727, in _run_workers_in_batch
>     all_outputs = ray.get(all_outputs)
>   File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2563, in get
>     raise value.as_instanceof_cause()
> ray.exceptions.RayTaskError(ChunkedEncodingError): ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
>   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 833, in _raw_read
>     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
> urllib3.exceptions.IncompleteRead: IncompleteRead(4963331015 bytes read, 7171139841 more expected)
> 
> The above exception was the direct cause of the following exception:
> 
> ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
>   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
>     yield from self.raw.stream(chunk_size, decode_content=True)
>   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 934, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 905, in read
>     data = self._raw_read(amt)
>   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 811, in _raw_read
>     with self._error_catcher():
>   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 729, in _error_catcher
>     raise ProtocolError(f"Connection broken: {e!r}", e) from e
> urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(4963331015 bytes read, 7171139841 more expected)', IncompleteRead(4963331015 bytes read, 7171139841 more expected))
> 
> During handling of the above exception, another exception occurred:
> 
> ray::RayWorkerVllm.execute_method() (pid=7598, ip=192.168.25.172, actor_id=9a702c3d2722e46a47e1444101000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f1781fa3d90>)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 32, in execute_method
>     return executor(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 72, in load_model
>     self.model_runner.load_model()
>   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 36, in load_model
>     self.model = get_model(self.model_config)
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 124, in get_model
>     model.load_weights(model_config.model, model_config.download_dir,
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 519, in load_weights
>     for name, loaded_weight in hf_model_weights_iterator(
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 201, in hf_model_weights_iterator
>     hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights(
>   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 141, in prepare_hf_model_weights
>     hf_folder = snapshot_download(model_name_or_path,
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 238, in snapshot_download
>     thread_map(
>   File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
>     return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
>     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
>   File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1170, in __iter__
>     for obj in iterable:
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
>     yield _result_or_cancel(fs.pop())
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
>     return fut.result(timeout)
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
>     return self.__get_result()
>   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
>     raise self._exception
>   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 213, in _inner_hf_hub_download
>     return hf_hub_download(
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1461, in hf_hub_download
>     http_get(
>   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 541, in http_get
>     for chunk in r.iter_content(chunk_size=DOWNLOAD_CHUNK_SIZE):
>   File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 818, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(4963331015 bytes read, 7171139841 more expected)', IncompleteRead(4963331015 bytes read, 7171139841 more expected))
> consolidated.01.pt: 100%|██████████| 12.1G/12.1G [05:32<00:00, 36.5MB/s]
> rpc error: code = DeadlineExceeded desc = context deadline exceeded%
> ```

Hello !
I have the same error and I still don't know how to solve the problem. I'm using 2 A100 GPUs...
