### ISSUE TITLE
Any options to increase vLLM performance?

### ISSUE THREAD

**Issue by Archmilio** [vllm-project/vllm#2073]
I am testing on A100 and H100, but the performance is significantly lower compared to TGI. 
TGI and vLLM have many similar features such as paged attention and continuous batch.
I tested both serving solutions with the latest version using the LLaMA 2 70B model.
I ran it with the default options, are there any options that need to be added or changed in order to improve vLLM performance?

vLLM Setting

Client Settings 
sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], ignore_eos=True, max_tokens=500, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True),

Server Settings
args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, model='/mnt/models/Llama-2-70b', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)

**Comment by AlpinDale** [comment]
Tensor parallelism is a bit slow due to Ray core pinning. After launching your server, run this command:

```sh
cpuid=0 ; for pid in $(ps xo '%p %c' | grep ray:: | awk '{print $1;}') ; do taskset -cp $cpuid $pid ; cpuid=$(($cpuid + 1)) ; done
```

That should increase throughput.

**Comment by nivibilla** [comment]
I'm working on a model parallel implementation instead of tensor parallel. Using tensor parallel for models that fit inside a single GPU in my experience don't provide boost of n gpus. Whereas if you use model parallel. A simple way is to have 8 instances of vllm and have a router like litellm to route the requests between them

**Comment by hewr1993** [comment]
> a model parallel implementation 

That's awesome! @nivibilla  Do you have a branch already?

**Comment by Lvjinhong** [comment]
> 由于 Ray 核心固定，张量并行性有点慢。启动服务器后，运行以下命令：
> 
> ```shell
> cpuid=0 ; for pid in $(ps xo '%p %c' | grep ray:: | awk '{print $1;}') ; do taskset -cp $cpuid $pid ; cpuid=$(($cpuid + 1)) ; done
> ```
> 
> 这应该会增加吞吐量。

What if we switch the implementation from ray to torchrun? Would that lead to better results?

**Comment by nivibilla** [comment]
> > a model parallel implementation 
> 
> That's awesome! @nivibilla  Do you have a branch already?

I was going to, then I found this pr which is exactly what I was going to do.

https://github.com/vllm-project/vllm/pull/1230
