### ISSUE TITLE
can vllm use autogptq compressed model like llama-2-70b-chat-gptq

### ISSUE THREAD

**Issue by fancyerii** [vllm-project/vllm#2077]
I want to use [llama-2-70b-chat-gptq](https://huggingface.co/TheBloke/Llama-2-70B-Chat-GPTQ). Can it be used in vllm?

**Comment by Tostino** [comment]
No, you can use awq quantized models though. GPTQ is not supported at this point in time.

**Comment by aarnphm** [comment]
There is a running PR https://github.com/vllm-project/vllm/pull/916

**Comment by fancyerii** [comment]
@aarnphm is this pr ready to use?
