### ISSUE TITLE
System prompt not working with Mistral-7B-Instruct-v0.1

### ISSUE THREAD

**Issue by naveenkazeta** [vllm-project/vllm#2080]
Following the example https://docs.vllm.ai/en/latest/getting_started/quickstart.html#using-openai-chat-api-with-vllm
I tried

```
curl http://$BASE_URL/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "mistralai/Mistral-7B-Instruct-v0.1",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Who won the world series in 2020?"}
        ]
    }'
```

gives error

`BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Conversation roles must alternate user/assistant/user/assistant/...', 'type': 'invalid_request_error', 'param': None, 'code': None}
`
Without system prompt it works fine.

I also tried with OpenHermes-2.5-Mistral-7B
```
curl http://$BASE_URL/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "teknium/OpenHermes-2.5-Mistral-7B",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Who won the world series in 2020?"}
        ]
    }'
```
and it works fine with system prompt.

**Comment by simon-mo** [comment]
Mixtral's instruction tuned model has chat template that doesn't support system messages. See https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/blob/main/tokenizer_config.json#L42

**Comment by pandadom** [comment]
@simon-mo  how would the curl command then look like for mistral/mixtral if it doesnt support system messages?

**Comment by simon-mo** [comment]
I believe you just need to remove system block. 

```diff
curl http://$BASE_URL/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "teknium/OpenHermes-2.5-Mistral-7B",
        "messages": [
-           {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Who won the world series in 2020?"}
        ]
    }'
```
