### ISSUE TITLE
Models of AMD GPUs supported

### ISSUE THREAD

**Issue by yunbaohe2022** [vllm-project/vllm#2082]
May I ask which models of AMD GPUs are currently supported by vLLM?

**Comment by tanpinsiang** [comment]
vLLM currently supports AMD Instinct MI210, MI250, MI250X, and MI300.

**Comment by yunbaohe2022** [comment]
> vLLM currently supports AMD Instinct MI210, MI250, MI250X, and MI300.

Thanks！

**Comment by wizd** [comment]
how about 7900 XTX?

**Comment by hmellor** [comment]
t
