### ISSUE TITLE
Is vllm support stream chat in offline inference?

### ISSUE THREAD

**Issue by chenyunlin00** [vllm-project/vllm#2083]
I found vllm support streaming in api server. But I want to know is  vllm support stream chat in offline inference. I didn't found it in example.

**Comment by Archmilio** [comment]
What is offline inference?

There is an example of chat stream token at the following link
https://docs.vllm.ai/en/latest/getting_started/quickstart.html#using-openai-chat-api-with-vllm

**Comment by chenyunlin00** [comment]
> What is offline inference?
> 
> There is an example of chat stream token at the following link https://docs.vllm.ai/en/latest/getting_started/quickstart.html#using-openai-chat-api-with-vllm

Thank you for your reply.
Is there any simple streaming API (like stream_chat or stream_generate) can use. For example:
```python
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

# Create an LLM.
llm = LLM(model="/path/my_local_model")
# Get streaming output
outputs = llm.stream_generate(prompts, sampling_params)
# Print the outputs.
for chunk in outputs:
    print(f"{chunk}")
```
