### ISSUE TITLE
Timeline on supporting Mixtral on ROCm?

### ISSUE THREAD

**Issue by jamestwhedbee** [vllm-project/vllm#2089]
Ran into this https://github.com/vllm-project/vllm/blob/096827c2846e7a769cf20e34c46b8eada444cc1e/vllm/model_executor/models/__init__.py#L42

**Comment by nivibilla** [comment]
This [pr](https://github.com/vllm-project/vllm/pull/2090) seems to remove the requirement for mega blocks. And hence the requirement for Nvidia gpus. Might be worth watching

**Comment by WoosukKwon** [comment]
As @nivibilla explained, now that #2090 is merged I think ROCm support should be feasible. Please stay tuned!

**Comment by jamestwhedbee** [comment]
Amazing, I am happy to test this out whenever you give me the go-ahead

**Comment by WoosukKwon** [comment]
Hi @jamestwhedbee, this should be fixed by #2180. Please try out the main branch again. Thanks.
