### ISSUE TITLE
How to infer the model running on Docker.

### ISSUE THREAD

**Issue by gireesh30** [vllm-project/vllm#2091]
Hi,

I am running mistral-7B model on vllm docker image by using the following command:
docker run --runtime nvidia --gpus all \
    -v /model_data:/model_files \
    --env "HUGGING_FACE_HUB_TOKEN=" \
    -p 8000:8000 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model mistralai/Mistral-7B-v0.1 
    
    and the model is successfully running. Now i want to use Gradio to build a chat interface to infer the mistral model.Can anyone help me on this how to do ?

**Comment by adarshxs** [comment]
You must have an endpoint now thats activated

you can refer here: https://docs.vllm.ai/en/latest/getting_started/quickstart.html

```
curl http://localhost:8000/generate \
    -d '{
        "prompt": "San Francisco is a",
        "use_beam_search": true,
        "n": 4,
        "temperature": 0
    }'
```

**Comment by gireesh30** [comment]
I want to know how to use gradio to build an interface and how to infer the model what function should be used for inferring
