### ISSUE TITLE
vllm推理如何指定某块gpu

### ISSUE THREAD

**Issue by roundXin** [vllm-project/vllm#2092]

**Comment by xxm1668** [comment]
CUDA_VISIBLE_DEVICES=0

**Comment by roundXin** [comment]
> CUDA_VISIBLE_DEVICES=0
<img width="1407" alt="1702519958887" src="https://github.com/vllm-project/vllm/assets/70061450/50971640-f9b5-455d-9243-b6ffadddc865">

在jupyter中应该怎么指定呢，我现在每次制定了卡2，他总是跑卡0上运行

**Comment by xTayEx** [comment]
Maybe using English is better

**Comment by Halflifefa** [comment]
Maybe this method can solve your problem

import os
import torch
os.environ["CUDA_VISIBLE_DEVICES"] = "4"

print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.device_count())
for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name(i))
    torch.cuda.get_device_properties(i)

**Comment by vergilus** [comment]
vllm只能从入口调用部分用CUDA_VISIBLE_DEVICES控制使用的gpu。

**Comment by meijunfeng2019** [comment]
这不太科学，应该有在代码里指定的功能

**Comment by sunwufan13** [comment]
> > CUDA_VISIBLE_DEVICES=0
> 
> <img alt="1702519958887" width="1407" src="https://private-user-images.githubusercontent.com/70061450/290378349-50971640-f9b5-455d-9243-b6ffadddc865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTAxMDgsIm5iZiI6MTczMDE4OTgwOCwicGF0aCI6Ii83MDA2MTQ1MC8yOTAzNzgzNDktNTA5NzE2NDAtZjliNS00NTVkLTkyNDMtYjZmZmFkZGRjODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMjg2MmViNjE1YTE2ZWUxYjU3OGUwMDQ3NzEzYWM0NzYzZDU5NWViOTA2MjY5ODc0ZjVmNGU5ZWZmYzEyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ox8wyWxHGLEBQo0sWiyaZl7sKGINYk5hyK1IM4byyQY">
> 在jupyter中应该怎么指定呢，我现在每次制定了卡2，他总是跑卡0上运行

给大家提供一点经验，希望可以节省大家一会儿时间。
vllm指定GPU的方法，就是CUDA_VISIBLE_DEVICES参数。以下图片为官方文档中的描述
![WechatIMG2074](https://github.com/user-attachments/assets/6d677451-7f3f-4ea2-bf21-de09cf08da7f)
但是，这里有一个小问题需要注意，就是
CUDA_VISIBLE_DEVICES=4,7
和
vllm serve Qwen/Qwen2.5-1.5B-Instruct
gpu指定命令和vllm启动命令，不能分开两行执行。必须在同一行执行，like this:
CUDA_VISIBLE_DEVICES=4,7 vllm serve Qwen/Qwen2.5-1.5B-Instruct
原因是分开的话会启动两个shell进程。
希望对大家有用

**Comment by LasRuinasCirculares** [comment]
我在尝试MCTS的时候，需要设置一个policy model和一个reward model，那这样我应该如何使用vllm将它们部署到不同的GPU上呢。
我尝试在policy model.py和reward model.py中分别设置了CUDA_VISIBLE_DEVICES，但是并不管用。在import的时候，会使用后设置的CUDA_VISIBLE_DEVICES

**Comment by LasRuinasCirculares** [comment]
这样实在是非常不方便！我不能够将在同一个程序中在不同的GPU上加载不同的模型

**Comment by ant-ob-hengtang** [comment]
> > > CUDA_VISIBLE_DEVICES=0
> > 
> > 
> > <img alt="1702519958887" width="1407" src="https://private-user-images.githubusercontent.com/70061450/290378349-50971640-f9b5-455d-9243-b6ffadddc865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTAxMDgsIm5iZiI6MTczMDE4OTgwOCwicGF0aCI6Ii83MDA2MTQ1MC8yOTAzNzgzNDktNTA5NzE2NDAtZjliNS00NTVkLTkyNDMtYjZmZmFkZGRjODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA4MTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkMjg2MmViNjE1YTE2ZWUxYjU3OGUwMDQ3NzEzYWM0NzYzZDU5NWViOTA2MjY5ODc0ZjVmNGU5ZWZmYzEyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ox8wyWxHGLEBQo0sWiyaZl7sKGINYk5hyK1IM4byyQY">
> > 在jupyter中应该怎么指定呢，我现在每次制定了卡2，他总是跑卡0上运行
> 
> 给大家提供一点经验，希望可以节省大家一会儿时间。 vllm指定GPU的方法，就是CUDA_VISIBLE_DEVICES参数。以下图片为官方文档中的描述 ![WechatIMG2074](https://github.com/user-attachments/assets/6d677451-7f3f-4ea2-bf21-de09cf08da7f) 但是，这里有一个小问题需要注意，就是 CUDA_VISIBLE_DEVICES=4,7 和 vllm serve Qwen/Qwen2.5-1.5B-Instruct gpu指定命令和vllm启动命令，不能分开两行执行。必须在同一行执行，like this: CUDA_VISIBLE_DEVICES=4,7 vllm serve Qwen/Qwen2.5-1.5B-Instruct 原因是分开的话会启动两个shell进程。 希望对大家有用

Amazing! it works , thanks bro :)

**Comment by dragoneptech** [comment]
如果用nohup在后台运行程序，即nohup CUDA_VISIBLE_DEVICES=0,1 vllm serve Qwen/Qwen2.5-1.5B-Instruct >vllm.log 2>&1 &提示报错！

**Comment by CooperLee996** [comment]
> 如果用nohup在后台运行程序，即nohup CUDA_VISIBLE_DEVICES=0,1 vllm serve Qwen/Qwen2.5-1.5B-Instruct >vllm.log 2>&1 &提示报错！

请问解决了吗 我进程直接没了
