### ISSUE TITLE
support for variable experts in Mixtral

### ISSUE THREAD

**Issue by nivibilla** [vllm-project/vllm#2096]
Some early benchmarks show up a 1 point drop in perplexity when using 3 experts instead of the default 2 in Mixtral.

https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1855151885

Please could we have support to specify the number of experts active?

**Comment by USBhost** [comment]
https://github.com/ggerganov/llama.cpp/pull/4406#issuecomment-1853793988

**Comment by pcmoritz** [comment]
I believe you can do this by just cloning https://huggingface.co/mistralai/Mixtral-8x7B-v0.1/tree/main, changing the `num_experts_per_tok` in config.json and pointing vLLM to the changed config. No need to change anything in vLLM :)

**Comment by nivibilla** [comment]
> I believe you can do this by just cloning https://huggingface.co/mistralai/Mixtral-8x7B-v0.1/tree/main, changing the `num_experts_per_tok` in config.json and pointing vLLM to the changed model. No need to change anything in vLLM :)

I see, I was looking fir if it's possible to vary the experts per prompt.
