### ISSUE TITLE
performance of Mixtral-8x7B inference

### ISSUE THREAD

**Issue by TexasRangers86** [vllm-project/vllm#2098]
I am a loyal user of vllm !

I tested Mixtral-8x7B-inference last day with vllm 0.2.4 and transformers 4.36.0 on 2 x A100 80G, and I got about 15 tokens per second. But I got about 100 tokens / s with this (https://www.together.ai/blog/together-inference-engine-v1), they don't open source, just web.
So will vllm team follow up on this work, that seems a bit faster.
They mentioned
 “Over the past several months, our team and collaborators have released a number of techniques that optimize inference performance including [FlashAttention-2](https://together.ai/blog/tri-dao-flash-attention), [Flash-Decoding](https://together.ai/blog/flash-decoding-for-long-context-inference), and [Medusa](https://together.ai/blog/medusa), available in the open source and incorporated into many [libraries](https://github.com/Dao-AILab/flash-attention/blob/main/usage.md). Our team has combined these techniques with our own optimizations and today we are excited to announce the Together Inference Engine.”
 
![image](https://github.com/vllm-project/vllm/assets/10004234/27fac133-e833-46c7-b5a2-4996f363c28e)

 
As a loyal user, I hope vllm can follow up on relevant work. I wish vllm better and better.

**Comment by TexasRangers86** [comment]
The biggest technical difference is probably [Medusa](https://together.ai/blog/medusa).

**Comment by WoosukKwon** [comment]
Hi @TexasRangers86, thanks for reporting this. We've just merged #2090 and release a new version. Could you benchmark again with the new release? It should be much faster now.

**Comment by TexasRangers86** [comment]
Thanks a lot for reply，I will test as soon ASAP！

**Comment by TexasRangers86** [comment]
> Hi @TexasRangers86, thanks for reporting this. We've just merged #2090 and release a new version. Could you benchmark again with the new release? It should be much faster now.

I got 23 tokens/s with vllm 0.2.5 (05bdf4e) on 2 x A100 (80G). It does seem to be 50% faster！

**Comment by martinshkreli** [comment]
> The biggest technical difference is probably [Medusa](https://together.ai/blog/medusa).

dont you need original training data for medusa?

**Comment by TexasRangers86** [comment]
> > The biggest technical difference is probably [Medusa](https://together.ai/blog/medusa).
> 
> dont you need original training data for medusa?

I will continue pretrain Mixtral-8x7B with my dataset if I follow up medusa. I don't start this work right now.

**Comment by Ethan-yt** [comment]
Hi @WoosukKwon 
I find a little bit confusing:

https://github.com/vllm-project/vllm/blob/1db83e31a2468cae37f326a642c0a4c4edbb5e4f/vllm/model_executor/models/mixtral.py#L146
In the inference code, all tokens are computed by all experts. Can we just compute the corresponding tokens?

In the transformers code, there is a slice of `hidden_states`

https://github.com/huggingface/transformers/blob/fa21ead73db473d88f8eca1ec244aba776fd9047/src/transformers/models/mixtral/modeling_mixtral.py#L837

Thanks

**Comment by Ethan-yt** [comment]
> Hi @WoosukKwon I find a little bit confusing:
> 
> https://github.com/vllm-project/vllm/blob/1db83e31a2468cae37f326a642c0a4c4edbb5e4f/vllm/model_executor/models/mixtral.py#L146
> 
> 
> In the inference code, all tokens are computed by all experts. Can we just compute the corresponding tokens?
> In the transformers code, there is a slice of `hidden_states`
> 
> https://github.com/huggingface/transformers/blob/fa21ead73db473d88f8eca1ec244aba776fd9047/src/transformers/models/mixtral/modeling_mixtral.py#L837
> 
> Thanks

Never mind, I find the answer in https://github.com/vllm-project/vllm/pull/2090

**Comment by harvinyou** [comment]
How fast is the inference speed of deepseek v2 under the current vllm framework, using the a100 series as an example
