### ISSUE TITLE
Any optimization options for H100?

### ISSUE THREAD

**Issue by Archmilio** [vllm-project/vllm#2107]
Thank you for your hard work.

The performance difference between A100 and H100 is not significant. I used the official VLLM image 0.2.4 on Docker Hub.

I set the prompt and completion to 500, and both A100 and H100 take 19 seconds.

Are there any settings to optimize performance on H100?

**Comment by Tan-YiFan** [comment]
Are you using H100-PCIe or H100-SXM? The memory bandwidth of A100-SXM and H100-PCIe are both 2TB/s, so their performance in LLM inference is similar (LLM inference is sensitive to memory bandwidth).
