### ISSUE TITLE
CTranslate2

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [vllm-project/vllm#211]
Hello,

Thanks for the great framework for deploying LLM.

Would it be possible to use a LLM model compiled with the CTranslate2 library?

**Comment by zhuohan123** [comment]
Thanks for bringing this up. We will investigate the CTranslate2 library and evaluate the difficulty and the potential benefit of adding it into vLLM.

**Comment by anujnayyar1** [comment]
Would love to see this! Thank you for the library so far!!

**Comment by Matthieu-Tinycoaching** [comment]
Hi,

Any news regarding this integration? Ctranslate2 has already proven its speed within the TitanML framework for local LLM serving.

**Comment by manishiitg** [comment]
hi,

any news on this?

**Comment by Matthieu-Tinycoaching** [comment]
+1

**Comment by shixianc** [comment]
+11

**Comment by hmellor** [comment]
@zhuohan123 do you see any benefit of adding this to vLLM?

**Comment by hmellor** [comment]
Closing because if there was significant benefit, it would have been discussed more or even implemented by now.
