### ISSUE TITLE
How to configure which GPU to use

### ISSUE THREAD

**Issue by wenku1992abc** [vllm-project/vllm#2118]
there is no config parameter to configure which GPU to use,it always to find GPU:0 I want to change the GPU number,what should i do ? PS : i used os.environ["CUDA_VISIBLE_DEVICES"] = "3" but it also to run on GPU:0

**Comment by Archmilio** [comment]
Try using NVIDIA_VISIBLE_DEVICES.

**Comment by kk3dmax** [comment]
I also need a "device_map" argv to config this like HF.
Not sure why there is no such argv...

**Comment by hmellor** [comment]
You must set `CUDA_VISIBLE_DEVICES=3` outside your script, setting it inside might be too late.
