### ISSUE TITLE
Unable to build docker image on machines without GPU

### ISSUE THREAD

**Issue by shangshng** [vllm-project/vllm#2127]
Hello all, I tried to build the ROCM docker image on a machine without GPU, but I met the problem:

> Traceback (most recent call last):
    File "/var/lib/jenkins/vllm/setup.py", line 207, in <module>
        amd_arch = get_amdgpu_offload_arch()
   File "/var/lib/jenkins/vllm/setup.py", line 59, in get_amdgpu_offload_arch
        raise RuntimeError(error_message) from e
   RuntimeError: Error: Command '['/opt/rocm/llvm/bin/amdgpu-offload-arch']' returned non-zero exit status 1.

It looks like it's unable to pip install vllm on a machine without GPU now, but I remember that vllm 0.2.1 on branch https://github.com/EmbeddedLLM/vllm-rocm/tree/v0.2.1.post1-rocm can be installed without GPUs. 

BTW, this problem also exists on CUDA platform. Hope you give some advice!

**Comment by alpayariyak** [comment]
+1

**Comment by simon-mo** [comment]
Fixed in #2581, Please try out the latest main branch and let us know!
