### ISSUE TITLE
Explain chattemplate using example?

### ISSUE THREAD

**Issue by premgadwal** [vllm-project/vllm#2130]
I am building a chatbot using deepseek models can someone explain me with example how to provide chat template with example

**Comment by satyajitghana** [comment]
Here's an example chat template of Alpaca Format: https://github.com/satyajitghana/tsai-chat/blob/master/chat_templates/template_alpaca.jinja

You use it like, 

```
python -m vllm.entrypoints.openai.api_server \
    --model "satyajitghana/mistral-7b-v0.1-alpaca-chat" \
    --chat-template ./chat_templates/template_alpaca.jinja
```

**Comment by premgadwal** [comment]
Thanks
