### ISSUE TITLE
Unable to run ehartford/dolphin-2.5-mixtral-8x7b

### ISSUE THREAD

**Issue by w013nad** [vllm-project/vllm#2132]
Model: https://huggingface.co/ehartford/dolphin-2.5-mixtral-8x7b
VLLM version: 0.2.5
Run method: API server endpoint inside a custom docker container (RHEL)
Hardware: 4x A100 40GB
Cuda version: 12.0

When I try to run it, it states it cannot find any weights.
```
RuntimeError: Cannot find any model weights with `/home/ndurkee/dolphin-2.5-mixtral-8x7b`
(RayWorkerVllm pid=2530) /usr/local/lib/python3.8/dist-packages/torch/nn/init.py:412: UserWarning: Initializing zero-element tensors is a no-op [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=2530)   warnings.warn("Initializing zero-element tensors is a no-op") [repeated 3x across cluster]
```

**What I've tested**
I did test mistralai/Mixtral-8x7B-Instruct-v0.1 and that does work on my system. It seems to have something to do with the model. Note that I did still get a warning "_Initializing zero-element tensors is a no-op_" but the model still seems to work fine.

Other people have stated that this model works with their setups which indicates that the issue is related to this model's interaction with VLLM. Possibly due to .safetensors for mistralai/mixtral and .bin for dolphin? My other model (wizardcoder 34B) utilizes .bin files and that does work. Overall, it likely has something to do with mixtral.

Let me know if I've missed anything.

**Comment by PsychoBoy11** [comment]
Is it working as of 0.2.6 version? 
Docker image: nvidia/cuda:12.1.0-base-ubuntu22.04
Python: 3.10
2xA100 80GB
Latest vllm, huggingface packages
I am getting the same output:

> 2023-12-28 07:27:28,806 INFO worker.py:1724 -- Started a local Ray instance.
> 2023-12-28 07:27:33,724 INFO worker.py:1558 -- Calling ray.init() again after it has already been called.
> INFO 12-28 07:27:34 llm_engine.py:73] Initializing an LLM engine with config: model='/model', tokenizer='/model', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, enforce_eager=False, seed=0)
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> (RayWorkerVllm pid=285) /usr/local/lib/python3.10/site-packages/torch/nn/init.py:412: UserWarning: Initializing zero-element tensors is a no-op
> (RayWorkerVllm pid=285)   warnings.warn("Initializing zero-element tensors is a no-op")
