### ISSUE TITLE
Serving Mixtral 8x7B with vllm OpenAI Server

### ISSUE THREAD

**Issue by JoshuaFurman** [vllm-project/vllm#2134]
I want to serve Mixtral with the openai compatible server but its not obvious to me reading the documentation how to set: `tensor_parallel_size = 2` 

I have 2xA100s so i can split Mixtral across both GPUs but I dont see how to configure that anywhere...

Is this even possible?

**Comment by miko7879** [comment]
When you start the server, pass the tensor_parallel_size flag as follows: `--tensor-parallel-size 2`

It'll automatically split the model across both GPUs and serve the model as expected.

**Comment by JoshuaFurman** [comment]
Terrific! Just confirmed this worked, thank you @miko7879 !

**Comment by WoosukKwon** [comment]
@miko7879 Thanks for answering the question!
