### ISSUE TITLE
KV cache is low, memory profiling does not see the remaining VRAM

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#2136]
GPUs: 2x 4090 (2x24GB)

Regarding my long context issue with CodeLlama above:
- vLLM 0.2.3: `# GPU blocks: 1464, # CPU blocks: 1310`
- vLLM 0.2.4: `# GPU blocks: 1464, # CPU blocks: 1310`
- vLLM 0.2.5 and `main`: `# GPU blocks: 112, # CPU blocks: 1310`

Something broke in VRAM profiling or before that, which prevents vLLM from using all remaining VRAM for the KV cache. Profiling already gives too low values and there is no way to manually override it from the command line. Both GPUs had ~8GB free VRAM after loading the model, so vLLM just fails to allocate it as cache.

Command:
```sh
python -O -u -m vllm.entrypoints.openai.api_server \
  --model=TheBloke/CodeLlama-13B-Instruct-fp16 \
  --chat-template=$HOME/bin/templates/llama-2-chat.jinja \
  --served-model-name=model \
  --host=0.0.0.0 \
  --port=8000 \
  --max-model-len=16384 \
  --max-num-seqs=16 \
  --tensor-parallel-size=2 \
  --swap-space=8 \
  --gpu-memory-utilization=0.95 \
  --disable-log-requests
```

Tested OK up to the full 16k context window on vLLM 0.2.3 and 0.2.4. The test fails on 0.2.5 if the sequence is longer than about 1700 tokens. (I think the exact limit is 112 * 16 due to block manager allocation and the block size of 16.)

vLLM 0.2.5 (and `main`) works fine with `TheBloke/deepseek-coder-33B-instruct-AWQ`, the problem does not happen with that model.

The use of `--chat-template` does not affect the problem, that's only to get the chat template right (same as Llama-2).

I've tried to change all the meaningful command line options in many ways, none of them helped.

**Comment by WoosukKwon** [comment]
Hi @viktor-ferenczi, thanks for reprint the issue. I believe this was fixed by #2151. Please try out v0.2.6!

**Comment by viktor-ferenczi** [comment]
Thanks for the fix. However, testing vLLM 0.2.6 with the same command failed right away.

To get it even doing any inference I had to add the `--enforce-eager` parameter.

It could load and run inference, however about ~34% lower total throughput than before (~500t/s => ~330t/s).

It then crashed without any meaningful error in the log at **~63% KV cache load**:
```
INFO 12-18 10:49:47 llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 315.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 68.9%, CPU KV cache usage: 0.0%
```

What is the best way to provide you with more details?

Had to revert to vLLM 0.2.4 and restarting it whenever it freezes (keepalive).

**Comment by WoosukKwon** [comment]
Hi @viktor-ferenczi, could you provide a reproducible script?

**Comment by viktor-ferenczi** [comment]
Sure. I will attempt to crash it with 16 parallel long context (near 16k) completions.

**Comment by viktor-ferenczi** [comment]
Should I test `0.2.6` or `main` branch version?

**Comment by Rahmat711** [comment]
@Woosuk Kwon the vllm model run into infinity it keeps running that 2 request for ever when tried with mistral 7b instruct and not responding to new request. Is this a known issue as we need to restart it back to start responding.
(Note the request prompt was large)

```20/12/2023, 12:10:11 AM    INFO 12-19 18:40:11 llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 28.7 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 98.7%, CPU KV cache usage: 0.0%

**Comment by viktor-ferenczi** [comment]
@Rahmat711 Which vLLM version are you using?

**Comment by Rahmat711** [comment]
@viktor-ferenczi i am using version 0.2.6

**Comment by viktor-ferenczi** [comment]
@WoosukKwon Tested `main` branch `a1b9cb2a` version:

GPUs: 2x4090 (2x24GB)
Model: `TheBloke/CodeLlama-34B-Instruct-AWQ`

```sh
python -O -u -m vllm.entrypoints.openai.api_server \
  --model=TheBloke/CodeLlama-34B-Instruct-AWQ \
  --chat-template=chat-templates/llama-2-chat.jinja \
  --quantization=awq \
  --dtype=float16 \
  --served-model-name=model \
  --host=0.0.0.0 \
  --port=8000 \
  --max-model-len=16384 \
  --max-num-seqs=1 \
  --tensor-parallel-size=2 \
  --swap-space=8 \
  --disable-log-requests
```

The model fails to load with CUDA OOM, log attached:
[CodeLlama-34B-Instruct-AWQ.main-a1b9cb2a.2x4090.log](https://github.com/vllm-project/vllm/files/13757172/CodeLlama-34B-Instruct-AWQ.main-a1b9cb2a.2x4090.log)

Using `--enforce-eager` does not help, it fails with CUDA OOM.

Using `--gpu-memory-utilization=0.95` does not fix the issue either.

- 0.2.4 could load this model even with `--max-num-seqs=16`.
- 0.2.5 could load this model with `--gpu-memory-utilization=0.95`, but ended up with minimal GPU KV cache (see up in the description), so contexts longer than 1700 tokens failed.
- 0.2.6 cannot even load this model anymore.

Something went broken in 0.2.5 and got worse in 0.2.6.

**Comment by chi2liu** [comment]
At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.

**Comment by adogwangwang** [comment]
> GPU KV cache

hello, can you show me how to increase GPU KV cache?  here is my log , when I run gemma7b,it will take 30s once, soooo slow,  how can I  make it faster?
INFO 05-22 02:20:59 async_llm_engine.py:524] Received request 10390bd4d2dc4936bd1a62e5793a4fd8: prompt: '<bos><start_of_turn>user\nplease tell me something about python<end_of_turn>\n<start_of_turn>model\n', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.8, top_p=0.8, top_k=1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[1], include_stop_str_in_output=False, ignore_eos=False, max_tokens=4096, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: None, lora_request: None.
INFO 05-22 02:20:59 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:04 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 12.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:09 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:14 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:19 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg 
generation throughput: 13.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:24 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 13.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.5%, CPU KV cache usage: 0.0%
INFO 05-22 02:21:29 async_llm_engine.py:120] Finished request 10390bd4d2dc4936bd1a62e5793a4fd8.

**Comment by YushuYan064** [comment]
@adogwangwang
Hi, I am encountering the same issue. Could you please share how you solved this issue?
Thank you.
