### ISSUE TITLE
Use LRU cache for CUDA Graphs

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2143]
another way to save memory is to use LRUcache for this map, and capture it on demand.

_Originally posted by @scv119 in https://github.com/vllm-project/vllm/pull/1926#discussion_r1427594126_

**Comment by hmellor** [comment]
@WoosukKwon has this work been done?

**Comment by SnzFor16Min** [comment]
Any update on caching the CUDA graphs?
