### ISSUE TITLE
GPTQ models don't support CUDA graph

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2147]
Got the following error while running `python examples/llm_engine_example.py --model TheBloke/Mixtral-8x7B-v0.1-GPTQ --dtype half`:
```
  File "/home/wskwon/workspace/vllm/vllm/model_executor/layers/sampler.py", line 396, in _random_sample
    random_samples = torch.multinomial(probs,
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```
The error didn't appear when the `--enforce-eager` flag was set.

*AWQ models did not raise errors.

I guess this is somehow related to exllama v2 kernels.

**Comment by r000bin** [comment]
@WoosukKwon thx for your work!

You mentioned "*AWQ models did not raise errors.". Does that mean mixtral AWQ is working now or in general AWQ (not mixtral)?

I saw in https://github.com/vllm-project/vllm/issues/2074 that mixtral AWQ is not yet working, right?

**Comment by WoosukKwon** [comment]
Hi @r000bin, Mixtral AWQ (e.g., `ybelkada/Mixtral-8x7B-Instruct-v0.1-AWQ`) is supported.

**Comment by teopapad92** [comment]
I am still facing the KeyError issue
![image](https://github.com/vllm-project/vllm/assets/32456947/2332d641-e93e-4895-938c-4c4cb5cce97d)

**Comment by chu-tianxiang** [comment]
I did a few tests today and found that I have to get current cuda stream and launch kernels with `kernel<<<blocks, threads, 0, stream>>>` instead of using default `kernel<<<blocks, threads>>>` to make cuda graph stream capture to work.
