### ISSUE TITLE
GPTQ does not support bfloat16

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2149]
Currently, our GPTQ kernels only support the float16 precision.

**Comment by Kelang-Tian** [comment]
> Currently, our GPTQ kernels only support the float16 precision.

Is there any plan to support bf16? If so, when is the estimated time?

**Comment by chu-tianxiang** [comment]
The exllama kernel is tailored for float16, e.g. it uses magic numbers for int4 to float16 conversion and heavily rely on half2 math operators. The PageAttention implementation provides a good example for dealing with different precisions with a common abstract interface, but it needs lots of work to implement. Another choice is to discard these precision-specific tricks and use universal template functions that apply to all data precision, in which case the performance would decline. 

Another thing is, AutoGPTQ by default load models in float16 precision, so the tensors in GPTQ checkpoints may actually be float16 even though `config.json` says bf16.

**Comment by zcnrex** [comment]
I would vote for precision specific optimizations to ensure the optimal speed, as this project's goal is large scale and low latency.

**Comment by TopIdiot** [comment]
@WoosukKwon  Is there any plan to support bf16? 
Maybe we can use triton to support it, and optimize cuda kernels later.
Or if there is a roadmap, I can see what I can do to help it.
