### ISSUE TITLE
when use gptq  using v100   CUDA 12.2, RuntimeError: CUDA error: no kernel image is available for execution on the device 

### ISSUE THREAD

**Issue by meichangsu1** [vllm-project/vllm#2165]
File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/quantization/gptq.py", line 209, in apply_weights
    output = ops.gptq_gemm(reshaped_x, weights["qweight"],
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
@chu-tianxiang

**Comment by chu-tianxiang** [comment]
I don't have exact environment but I tested with V100 CUDA 12.1 and found no problem. I'm not sure where the problem lies, does it still exist if you install from source?

**Comment by meichangsu1** [comment]
well,I sovled by using the docker image  vllm/vllm-openai:latest
