### ISSUE TITLE
May I ask whether vllm supports Baichuan2-7B-Chat-4bits

### ISSUE THREAD

**Issue by lijiawen-LJW** [vllm-project/vllm#2170]
When I execute this line of instruction：
VLLM_USE_MODELSCOPE=True python -m vllm.entrypoints.openai.api_server --model="baichuan-inc/Baichuan2-13B-Chat" --download-dir="/root/autodl-tmp/model/"  --revision='v1.0.3' --trust-remote-code 
When I execute this line of instruction
ValueError: Unknown quantization method: gptq. Must be one of ['awq', 'squeezellm'].

**Comment by yhyu13** [comment]
Gptq should be supported now https://github.com/vllm-project/vllm/issues/2147
