### ISSUE TITLE
AsyncLLMEgnine with mistralai/Mixtral-8x7B-Instruct-v0.1 - AsyncLLMEngine dead and Invalid config blocking attribute value -2147483648

### ISSUE THREAD

**Issue by aswain571** [vllm-project/vllm#2173]
I am trying to stream the output from Mixtral-8x7B-Instruct-v0.1 using the AsyncLLM engine and running into some problems. My code has been working perfectly for Mistral7B model. The error trace is given below:

xception raised in creation task: The actor died because of an error raised in its creation task, ray::_AsyncLLMEngine.__init__() (pid=641091, ip=10.146.0.2, actor_id=12feec12736fa57cc721e47901000000, repr=<vllm.engine.async_llm_engine._AsyncLLMEngine object at 0x7fd41820a670>)
(_AsyncLLMEngine pid=641091)   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
(_AsyncLLMEngine pid=641091)     return self.__get_result()
(_AsyncLLMEngine pid=641091)   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
(_AsyncLLMEngine pid=641091)     raise self._exception
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 108, in __init__
(_AsyncLLMEngine pid=641091)     self._init_workers_ray(placement_group)
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 191, in _init_workers_ray
(_AsyncLLMEngine pid=641091)     self._run_workers(
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 755, in _run_workers
(_AsyncLLMEngine pid=641091)     self._run_workers_in_batch(workers, method, *args, **kwargs))
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 732, in _run_workers_in_batch
(_AsyncLLMEngine pid=641091)     all_outputs = ray.get(all_outputs)
(_AsyncLLMEngine pid=641091) ray.exceptions.RayTaskError(DistBackendError): ray::RayWorkerVllm.execute_method() (pid=641194, ip=10.146.0.2, actor_id=d6d45db57fe6b04b1ec82ae801000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7edf085ed820>)
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/engine/ray_utils.py", line 31, in execute_method
(_AsyncLLMEngine pid=641091)     return executor(*args, **kwargs)
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/worker/worker.py", line 72, in init_model
(_AsyncLLMEngine pid=641091)     _init_distributed_environment(self.parallel_config, self.rank,
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/vllm/worker/worker.py", line 190, in _init_distributed_environment
(_AsyncLLMEngine pid=641091)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
(_AsyncLLMEngine pid=641091)     return func(*args, **kwargs)
(_AsyncLLMEngine pid=641091)   File "/home/abhisek.swain/code/derai-continuous-deployment/venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2050, in all_reduce
(_AsyncLLMEngine pid=641091)     work = group.allreduce([tensor], opts)
(_AsyncLLMEngine pid=641091) torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:219, invalid argument, NCCL version 2.14.3
(_AsyncLLMEngine pid=641091) ncclInvalidArgument: Invalid value for an argument.
(_AsyncLLMEngine pid=641091) Last error:
(_AsyncLLMEngine pid=641091) Invalid config blocking attribute value -2147483648
INFO 12-18 11:05:16 async_llm_engine.py:134] Aborted request bc5edbd4aa344719b01faee69b485aa7.

There are lot more errors following this most notably:

raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
(_AsyncLLMEngine pid=641091) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorkerVllm.execute_method() (pid=641195, ip=10.146.0.2, actor_id=572ddc81eab16f68d8eab04301000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7f655c4ec850>)

This happens during the generation of the streaming response. 

  async def stream_results() -> AsyncGenerator[str, None]:
        async for request_output in results_generator:

Has anyone seen this error before? Please advise. Thanks.

**Comment by chenxiangzhen** [comment]
Have you solved this problem?

**Comment by aswain571** [comment]
Yes. The error was due to wrong version of nvidia-nccl-cu12. Please use 2.18.1.

**Comment by lasseedfast** [comment]
I get the exact same error even when using nvidia-nccl-cu12 2.18.1 and vLLM 0.2.7

**Comment by aswain571** [comment]
Please checkin you have multiple versions of Nvidia-nccl-cu installed and your pytorch+triton versions
