### ISSUE TITLE
Quantizing 'lmsys/vicuna-7b-v1.5' model (vllm  AutoAWQ example code)  giving cuda error

### ISSUE THREAD

**Issue by SaloniHenecha24** [vllm-project/vllm#2176]
The example code for Quantizing on vllm documentation was working before few days, but now same code on same machine giving cuda error.

## CODE :
```
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

model_path = 'lmsys/vicuna-7b-v1.5'
quant_path = 'vicuna-7b-v1.5-awq'
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }

# Load model
model = AutoAWQForCausalLM.from_pretrained(model_path, **{"low_cpu_mem_usage": True})
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# Quantize
model.quantize(tokenizer, quant_config=quant_config)

# Save quantized model
model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)
```

## MACHINE CONFIG(GPU) : 
AWS sagemaker ml.g5.8xlarge
NVIDIA A10G

## ERROR OUTPUT:

---> 1 model.quantize(tokenizer, quant_config=quant_config)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/awq/models/base.py:49, in BaseAWQForCausalLM.quantize(self, tokenizer, quant_config, calib_data, split, text_column)
     43 self.quant_config: AwqConfig = AwqConfig.from_dict(quant_config)
     45 quantizer = AwqQuantizer(
     46     self, self.model, tokenizer, self.quant_config.w_bit, self.quant_config.q_group_size,
     47     self.quant_config.version, calib_data, split, text_column
     48 )
---> 49 quantizer.quantize()
     50 self.is_quantized = True

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/awq/quantize/quantizer.py:82, in AwqQuantizer.quantize(self)
     78 # [STEP 2]: Compute and apply scale list
     79 module_config: List[Dict] = self.awq_model.get_layers_for_scaling(
     80     self.modules[i], input_feat, self.module_kwargs
     81 )
---> 82 scales_list = [self._search_best_scale(self.modules[i], **layer) for layer in module_config]
     83 apply_scale(self.modules[i], scales_list, input_feat_dict=input_feat)
     84 scales_list = append_str_prefix(scales_list, get_op_name(self.model, self.modules[i]) + ".")

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/awq/quantize/quantizer.py:82, in <listcomp>(.0)
     78 # [STEP 2]: Compute and apply scale list
     79 module_config: List[Dict] = self.awq_model.get_layers_for_scaling(
     80     self.modules[i], input_feat, self.module_kwargs
     81 )
---> 82 scales_list = [self._search_best_scale(self.modules[i], **layer) for layer in module_config]
     83 apply_scale(self.modules[i], scales_list, input_feat_dict=input_feat)
     84 scales_list = append_str_prefix(scales_list, get_op_name(self.model, self.modules[i]) + ".")

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/utils/_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/awq/quantize/quantizer.py:158, in AwqQuantizer._search_best_scale(self, module, prev_op, layers, inp, module2inspect, kwargs)
    155         fp16_output = fp16_output[0]
    157 # [STEP 4]: Compute loss
--> 158 best_scales = self._compute_best_scale(
    159     inp, w_max, x_max, module2inspect,
    160     layers, fp16_output, kwargs
    161 )
    163 return (get_op_name(module, prev_op), tuple([get_op_name(module, m) for m in layers]), best_scales)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/awq/quantize/quantizer.py:203, in AwqQuantizer._compute_best_scale(self, x, w_max, x_max, module2inspect, linears2scale, fp16_output, kwargs)
    200     fc.weight.data = self.pseudo_quantize_tensor(fc.weight.data) / scales_view
    202 # W * X
--> 203 int_w_output = module2inspect(x, **kwargs)
    204 if isinstance(int_w_output, tuple):
    205     int_w_output = int_w_output[0]

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py:708, in LlamaSdpaAttention.forward(self, hidden_states, attention_mask, position_ids, past_key_value, output_attentions, use_cache)
    706 if past_key_value is not None:
    707     cache_kwargs = {"sin": sin, "cos": cos}  # Specific to RoPE models
--> 708     key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)
    710 key_states = repeat_kv(key_states, self.num_key_value_groups)
    711 value_states = repeat_kv(value_states, self.num_key_value_groups)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/cache_utils.py:127, in DynamicCache.update(self, key_states, value_states, layer_idx, cache_kwargs)
    125     self.value_cache.append(value_states)
    126 else:
--> 127     self.key_cache[layer_idx] = torch.cat([self.key_cache[layer_idx], key_states], dim=-2)
    128     self.value_cache[layer_idx] = torch.cat([self.value_cache[layer_idx], value_states], dim=-2)
    130 return self.key_cache[layer_idx], self.value_cache[layer_idx]

> OutOfMemoryError: CUDA out of memory. Tried to allocate 3.05 GiB. GPU 0 has a total capacty of 22.19 GiB of which 2.75 GiB is free. Including non-PyTorch memory, this process has 19.44 GiB memory in use. Of the allocated memory 19.12 GiB is allocated by PyTorch, and 18.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by WoosukKwon** [comment]
@casper-hansen Could you take a look?

**Comment by ArthurZucker** [comment]
@casper-hansen if you have any insight when debugging we'll open a fix asap in transformers

**Comment by younesbelkada** [comment]
I think the reason is that previously we were using tuples of tuples where past key values were populated along the way without extra memory allocation, whereas now we create new torch tensors, `torch.cat([self.value_cache[layer_idx], value_states], dim=-2)` creates copies of past kv tensors. We indeed need to investigate and see

**Comment by casper-hansen** [comment]
> @casper-hansen if you have any insight when debugging we'll open a fix asap in transformers

@ArthurZucker Thanks for the support! My compute is locked up in trying to quantize Mixtral to a low enough perplexity at the moment, happy to investigate deeper when we solve quantizing Mixtral

> I think the reason is that previously we were using tuples of tuples where past key values were populated along the way without extra memory allocation, whereas now we create new torch tensors, `torch.cat([self.value_cache[layer_idx], value_states], dim=-2)` creates copies of past kv tensors. We indeed need to investigate and see. Not sure though if the reason is what I have just stated

A quick investigation may just be to run a maximum memory profiling of 4.35.2 versus 4.36.0 during inference. A more advanced one would be during quantization. I use this script for speed+memory benchmarks on FP16 and INT4 models:
https://github.com/casper-hansen/AutoAWQ/blob/main/examples/benchmark.py

**Comment by ArthurZucker** [comment]
Maybe the garbage cleaner does not clear the previous references ? Yes will check for sure as I'm implementing the static cache!

**Comment by SaloniHenecha24** [comment]
> This should not be going OOM for a 7B. I have quantized so many 7B models with 24GB VRAM that I lost count. This may be due to the caching update in 4.36.0 of transformers, perhaps that uses additional memory - something to investigate.
> 
> You could also try to remove the `{"low_cpu_mem_usage": True}`, although I never experienced issues with it. I also wonder if it would work if you passed `{"use_cache": False}`.
> 
> If issues persist, you can use AutoAWQ 0.1.7 with transformers 4.35.2.


versions : **AutoAWQ 0.1.7 ,  transformers 4.36.2**

1. Tried removing {"low_cpu_mem_usage": True}`, : didnt worked , same error
2. **Adding  `{"use_cache": False}`. : yes this worked!** 

3.  transformers 4.35.2.   :  RuntimeError: Failed to import transformers.models.mixtral.configuration_mixtral because of the following error (look up to see its traceback):
No module named 'transformers.models.mixtral.configuration_mixtral'


Though, The saved quantized model , when I am loading for inference are taking incosistent gpu memory usage
BEFORE:
quant_path = "Mistral-7B-OpenOrca-AWQ-quantized"
llm1 = LLM(model=quant_path,
          quantization="AWQ",
          dtype="half",
          max_model_len=4096,
          gpu_memory_utilization = 0.3 )
GPU blocks: 364, # CPU blocks: 2048
GPU usage : 4452MiB


same  gpu_memory_utilization = 0.3 gives gpu_memory_utilization
NOW: 
(working code)
quant_path = "Mistral-7B-OpenOrca-AWQ-quantized_new"
llm = LLM(model=quant_path,
          quantization="AWQ",
          dtype="half",
          max_model_len=4096,
          gpu_memory_utilization = 0.4 )
GPU blocks: 1500, # CPU blocks: 2048
7574MiB / 23028MiB 

NOTE : I  have also seen inconsistency in this as well sometimes it also doesnt works for gpu_memory_utilization = 0.4 and needs gpu_memory_utilization = 0.5
