### ISSUE TITLE
Support for MPT-7B and MPT-30B

### ISSUE THREAD

**Issue by mspronesti** [vllm-project/vllm#218]
It would be great if you could support MPT-7B and MPT-30B

**Comment by WoosukKwon** [comment]
Hi @mspronesti, thanks for brining it up. I believe MPT's architecture is pretty similar to BLOOM. We will add support for both models very soon!

**Comment by rossbucky** [comment]
+1. I think both bloom and mpt just need alibi implementation and then vllm could support both.

**Comment by rossbucky** [comment]
@WoosukKwon can I ask about the timeline for it when you mention it very soon? is it like in 2 weeks or 4 weeks roadmap? thanks
