### ISSUE TITLE
Running vLLM in docker in CPU only

### ISSUE THREAD

**Issue by delta-whiplash** [vllm-project/vllm#2185]
Hello how can I run vLLM in CPU mode only with docker ?

Thanks for the help

**Comment by WoosukKwon** [comment]
Hi @delta-whiplash, NVIDIA or AMD GPUs are required to run vLLM. If you want to try vLLM, you use google colab with a T4 GPU for free.

**Comment by delta-whiplash** [comment]
> Hi @delta-whiplash, NVIDIA or AMD GPUs are required to run vLLM. If you want to try vLLM, you use google colab with a T4 GPU for free.

Ok I understand do you know great inference software with CPU only to use I don't have big GPU to run Mistral 8x7b
