### ISSUE TITLE
Error: max retries exceeded: unexpected EOF

### ISSUE THREAD

**Issue by SAKSoomro** [vllm-project/vllm#2187]
pulling manifest 
pulling bdb11b0699e0...  38% ▕██████████████████████████████████████████████████                                                                                   ▏  10 GB/ 26 GB  2.1 MB/s   2h11m
Error: max retries exceeded: unexpected EOF

**Comment by ckcodes907** [comment]
run the same command again, download will resume.

**Comment by SAKSoomro** [comment]
It works, Thanks.

**Comment by saravanans1204** [comment]
Thank you it works

**Comment by GreedyAllay** [comment]
I retried the download for at least 10 times but it keeps saying it for me without actually making more progress than 20%

**Comment by 535803710** [comment]
thanks   ,you are a goodman
