### ISSUE TITLE
The inference results of vllm and HF are inconsistent

### ISSUE THREAD

**Issue by lemonit-eric-mao** [vllm-project/vllm#2189]
# vllm和HF推理结果不一致

## Config Info

- vllm                      0.2.5
- transformers        4.36.0
- LLM                      chatglm3-6b-32k
- Python                 3.10.12
- OS                       ubuntu
- GPU                     NVIDIA A100  80G
- CUDA                  12.1
- NVIDIA Driver      525.125.06

###  vLLM
``` python
from vllm import LLM, SamplingParams

llm = LLM(model="/mnt/data/NewLLM/THUDM/chatglm3-6b-32k", trust_remote_code=True)

sampling_params = SamplingParams(
   top_p=0.9, 
   top_k=3, 
   best_of=6,
   repetition_penalty=1.2, 
   temperature=0.7,
   max_tokens=500
)

prompts = [
   "你好",
]

outputs = llm.generate(prompts, sampling_params)

for output in outputs:
   prompt = output.prompt
   generated_text = output.outputs[0].text
   print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

# Output
Prompt: '你好', Generated text: '！请问有什么问题我可以帮您解答吗？'





prompts = [
   "晚上睡不着应该怎么办",
]

outputs = llm.generate(prompts, sampling_params)

for output in outputs:
   prompt = output.prompt
   generated_text = output.outputs[0].text
   print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")


# Output
Prompt: '晚上睡不着应该怎么办', Generated text: '？\n 根据问题，我们需要解决的是晚上睡不着的问题。首先，我们可以尝试改变自己的睡眠环境，比如保持床铺整洁、安静、温暖等，这些都有助于提高入睡质量。其次，我们也可以通过一些放松的方式来缓解压力和焦虑，例如冥想、深呼吸、瑜伽等等。此外，避免在睡前过度使用电子设备也是非常重要的，因为蓝光会抑制褪黑素的分泌，影响我们的睡眠质量。最后，如果以上方法都无法解决问题，建议咨询医生或专业机构寻求帮助。'

```

### HF
``` python

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("/mnt/data/NewLLM/THUDM/chatglm3-6b-32k", trust_remote_code=True)
model = AutoModel.from_pretrained("/mnt/data/NewLLM/THUDM/chatglm3-6b-32k", trust_remote_code=True).half().cuda()

model = model.eval()

response, history = model.chat(tokenizer, "你好", history=[])
print(response)

# Output
你好！我是 ChatGLM3-6B，很高兴见到你，欢迎问我任何问题。



response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)

# Output
晚上睡不着可能会让人感到焦虑和沮丧，但以下方法可能会帮助你改善睡眠：

1. 建立规律的睡眠时间表：每天尽量在相同的时间上床和起床，包括周末。
2. 创建舒适的睡眠环境：确保你的睡眠环境安静、黑暗、凉爽且舒适，床垫和枕头也应该舒适。
3. 避免刺激性物质：避免在睡前饮用咖啡、茶或其他含咖啡因的饮料，以及避免食用过多的糖分和脂肪。
4. 放松技巧：尝试使用一些放松技巧，如深呼吸、冥想、渐进性肌肉松弛或瑜伽，这些方法可以帮助你放松身心并入睡。
5. 避免在床上看电视或使用电脑：在床上看电视或使用电脑可能会影响睡眠质量，因此最好在床上看书或听一些柔和的音乐。

如果以上方法都无法帮助你改善睡眠，建议你咨询医生或专业心理医生的意见。
```

## Question
What adjustments should I make to make the reasoning results closer to HF

**Comment by pvtoan** [comment]
Hi,

I also got this problem but my case is even worse.

Actually, I used Llama2-7B-Chat-Hf with 

**Config info:**
vllm 0.2.6
transformers 4.36.2
LLM Llama2-7B-Chat-Hf 
Python 3.10.12
Ubuntu 22.04
GPU NVIDIA 4090 24gb

**Code**
llm = VLLM(model="meta-llama/Llama-2-7b-chat-hf", tensor_parallel_size=1, trust_remote_code=True, temperature=0.6, top_k=5, top_p=0.9, torch_dtype=torch.bfloat16, max_new_tokens=500) 
llm("hello")

**Answer**
@matthew-mitchell.com
www.matthew-mitchell.com
Matthew Mitchell is a composer and sound artist based in London. He creates music that spans a range of genres, from electronic and acoustic sounds to sound installations and live performances. His work often explores the relationship between sound and space, and he has a particular interest in the way that sound can be used to create immersive and transformative experiences.
Matthew has worked with a wide range of artists and organizations, including the BBC, the Guardian, and the Tate Modern. He has also been commissioned to create music for a number of festivals and events, including the London 2012 Olympics and the Edinburgh Festival Fringe.
In addition to his work as a composer, Matthew is also a skilled teacher and has given workshops and masterclasses at a number of institutions, including the Royal College of Music and the University of Edinburgh. He is passionate about sharing his knowledge and skills with others and helping to inspire the next generation of musicians and sound artists.
Matthew is also a prolific recording artist and has released a number of albums, including "The Light That Fills the World" and "The Space Between". His music has been praised for its beauty, depth, and emotional resonance, and he has been described as a "master of his craft".
Overall, Matthew Mitchell is a highly respected and innovative composer and sound artist who is pushing the boundaries of his craft and creating truly unique and transformative experiences for audiences around the world.



Also, I don't know Llama2-7b-Chat occupied around 21GB from VRAM. 
(In fact, I run exact the same code before but it takes only around 14GB VRAM)


Does anyone get weird answer and high-occupied GPU memory as me? If yes, can I know how you fixed that?

**Comment by KirisameR** [comment]
perhaps you should set temperature=0 on both test cases to eliminate the potential impact of randomness over your query results. 

When temperature set to above 0, even for the same model running in the same inference environment, when given the same query it may output completely different responses.
