### ISSUE TITLE
Have you considered sharing KV cache of a single GPU across multiple models?

### ISSUE THREAD

**Issue by tianliplus** [vllm-project/vllm#2193]
Sometimes it is more cost-effective to deploy multiple models on the same set of GPUs. But vLLM supports running one model only, and will occupy fixed-size GPU memory from beginning. That makes it hard to share GPU across multiple models.

**Comment by hewr1993** [comment]
you may find `--gpu-memory-utilization` helpful

**Comment by tianliplus** [comment]
> you may find `--gpu-memory-utilization` helpful

This config is fixed at vLLM starting stage. If there were two models running on the same GPU, each with 50% of memory, one cannot consume more than 50% even if the other one is idle.

**Comment by jowamedia** [comment]
I give a thumbs up for this feature. I do have a Nvidia A100 80 GB at work and I would like to load several models on it.
Like one for normal language and some for coding.

python -m vllm.entrypoints.openai.api_server \
--model="Open-Orca/Mistral-7B-OpenOrca"  \
--model="TheBloke/deepseek-coder-6.7B-instruct-AWQ" \
 --trust-remote-code

**Comment by HuangLianghong** [comment]
@tianliplus @hewr1993  Can you run two models on the GPU with `--gpu-memory-utilization`? I try to run two models by running `python -m vllm.entrypoints.api_server --model ./open_llama_7B --swap-space 16 --gpu-memory-utilization 0.4`  in two terminals, but only one model can be loaded successfully, the other one raises the error:
```
INFO 12-28 17:20:57 llm_engine.py:73] Initializing an LLM engine with config: model='./open_llama_7B', tokenizer='./open_llama_7B', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
INFO 12-28 17:21:17 llm_engine.py:223] # GPU blocks: 0, # CPU blocks: 2048
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/entrypoints/api_server.py", line 80, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 496, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 269, in __init__
    self.engine = self._init_engine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 314, in _init_engine
    return engine_class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 113, in __init__
    self._init_cache()
  File "/mnt/sda/2022-0526/home/hlh/python_venvs/vllm-py3.11.6/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 227, in _init_cache
    raise ValueError("No available memory for the cache blocks. "
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```
It cannot allocate memory blocks in the GPU.

**Comment by damienw34** [comment]
Hi,

I came to the same issue today. So far I tested if I give 0.9 to the second model it works (tested with codelama-7b and vicuna on A100). 

So I suspect that the factor may take only FREE memory for the calculation. It would make the parameter pretty unusable but I did not found it in source code.

Regards


regards

**Comment by hmellor** [comment]
Closing as stale.

**Comment by hmellor** [comment]
vLLM can be used to serve multiple models on a single GPU, simply lower `--gpu-memory-utilization` on each instance so that they sum to <1

**Comment by cyk-gaudi** [comment]
Gotcha! I didn't realize that this is possible today! Thank you!
