### ISSUE TITLE
AWQ Cuda OOM

### ISSUE THREAD

**Issue by carlosandrea** [vllm-project/vllm#2199]
Hello, 

I'm having issue making inference with AWQ model which give me a CUDA OOM error at loading using VLLM:
llm = LLM(model="/root/Thot/llama_model_weights/quantized/Q4/Phind-CodeLlama-34B-v2-AWQ", quantization='awq', dtype='half', gpu_memory_utilization=0.95)

In the meantime I can make inference with the same model but using GPTQ version
I can also make inference using AWQ model within transformers.
Model :
https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-AWQ
https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GPTQ/tree/main

Any help would be appreciated !

**Comment by esmeetu** [comment]
Try adding `--enforce_eager` parameter. Related info: #2182

**Comment by carlosandrea** [comment]
Hello, 

Same using :
llm = LLM(model="/root/Thot/llama_model_weights/quantized/Q4/Phind-CodeLlama-34B-v2-AWQ", quantization='awq', dtype='half', gpu_memory_utilization=0.95,enforce_eager=True)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 10.75 GiB. GPU 0 has a total capacty of 23.65 GiB of which 5.10 GiB is free. Including non-PyTorch memory, this process has 18.54 GiB memory in use. Of the allocated memory 17.56 GiB is allocated by PyTorch, and 410.29 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by dachengai** [comment]
same question

**Comment by DaBossCoda** [comment]
also getting this OOM with awq

**Comment by wakk** [comment]
try to reduce `--max-model-len`. This may be helpful.
