### ISSUE TITLE
Feature request: add json formating via opanai entrypoint

### ISSUE THREAD

**Issue by itaybar** [vllm-project/vllm#2204]
Add option to 
https://github.com/vllm-project/vllm/blob/de60a3fb93957dce6b242299b5d163f02ef7f383/vllm/entrypoints/openai/protocol.py#L82
` json_format: Union[Boolean, string, None] = None` 
 which False or None says do not force json format, True says format to some json, and string should describe specific json (usind pydantic.schema())

using [lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer)

**Comment by itaybar** [comment]
And maybe support regex in the same way

**Comment by hmellor** [comment]
Structured output is now supported by #2819
