### ISSUE TITLE
Stopping an indefinitely running request

### ISSUE THREAD

**Issue by vibhuagrawal14** [vllm-project/vllm#2215]
I am using Mixtral-8x7B-Instruct-v0.1 to generate JSONs from some given text, but in some cases the generation does not follow the given JSON format, and starts generating a very large (5k+ tokens) output. This causes the server to slow down massively.

Is there a way to stop the generation of a particular request?

**Comment by WoosukKwon** [comment]
Hi @vibhuagrawal14, currently vLLM doesn't have a good way to handle such a case. I think we need to support structured decoding (or grammar?) to address your problem. For now, you can use `max_tokens` to prevent too-long outputs.

**Comment by vibhuagrawal14** [comment]
@WoosukKwon Any suggestion as to where I can start if we want to implement this functionality?
