### ISSUE TITLE
Is pipeline parallelism  not supported yet?

### ISSUE THREAD

**Issue by janelu9** [vllm-project/vllm#2226]
I think it is easy to support and faster than tensor parallelism .
for example:
`x.to("cuda:0").to("cuda:1")`

**Comment by Lvjinhong** [comment]
+1

**Comment by SungBalance** [comment]
+2

**Comment by Lvjinhong** [comment]
> I think it is easy to support and faster than tensor parallelism . for example: `x.to("cuda:0").to("cuda:1")`


#387 mentioned some obstacles to implementing pipeline parallelism, but I'm not sure if there have been any recent developments.
