### ISSUE TITLE
how to add history in /vllm/entrypoints/api_server.py？

### ISSUE THREAD

**Issue by hediyuan** [vllm-project/vllm#2228]
hi everyone, could you please help me take a look at this question?

how to add history in /vllm/entrypoints/api_server.py？
If the request includes prompt and histroy，such as :
{"prompt": "What floor do I live on？"，
 "history": [["Please remember, I live on the 10th floor","ok, I will remember that" ]]"}

How should I add history to the prompt? Is it using a template? Doesn't each model have a different template?

**Comment by doublegssc** [comment]
+1

**Comment by hmellor** [comment]
It is the application's job to manage conversation history, not the inference server's.
