### ISSUE TITLE
How long does it generally take to load a 70B open-source model?

### ISSUE THREAD

**Issue by cangyi071** [vllm-project/vllm#2233]
It took me over 120 minutes to load the 67B DeepSeek model. Is this normal?

**Comment by duguwanglong** [comment]
The vLLM seams like not support DeepSeek model.

**Comment by cangyi071** [comment]
> The vLLM seams like not support DeepSeek model.

problem resolved:https://github.com/vllm-project/vllm/issues/2253

vllm supports DeepSeek now,you can refer to it：https://github.com/deepseek-ai/DeepSeek-LLM

**Comment by pluiez** [comment]
> > The vLLM seams like not support DeepSeek model.
> 
> problem resolved:#2253
> 
> vllm supports DeepSeek now,you can refer to it：https://github.com/deepseek-ai/DeepSeek-LLM


@cangyi071   Hi, I'm wondering eventually how long does it take to load a 70B model from local filesystem? In my case it's taking around 40 minutes, that is a pain.

**Comment by cangyi071** [comment]
Now it takes me 3 mins to load 67B model 。
The slow speed is not related to the implementation of VLLM; it should be an issue with storage media。you can test the file transfer speed of your storage media.
