### ISSUE TITLE
Argument --pipeline-parallel-size/-pp: invalid int value: '8000:8000

### ISSUE THREAD

**Issue by Jesus-session** [vllm-project/vllm#2235]
I'm experiencing an issue with the docker image when try to run it on runpod.io. I get the following error:
`api_server.py: error: argument --pipeline-parallel-size/-pp: invalid int value: '8000:8000`

I've follow the [docs](https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html) . I'm not sure what's causing this issue, but it's preventing me from using the vllm container.
This is the runpod template configuration that i was using:
![Screenshot from 2023-12-21 14-28-54](https://github.com/vllm-project/vllm/assets/153531968/cd690e2c-afbc-4b0e-9583-1adbc260bfa6)

Any help or guidance would be greatly appreciated. Thank you!

**Comment by leedhn** [comment]
Hi, placing the `-p` argument before `--env` may resolve this issue!

I'm currently using the shell script below, and it works well!

```
sudo docker run --runtime Nvidia --gpus all \
-p 8000:8000 \
--ipc=host \
-v ~/.cache/huggingface:/root/.cache/huggingface \
--env "HUGGING_FACE_HUB_TOKEN=<token>" \
vllm/vllm-openai:latest \
--model mistralai/Mixtral-8x7B-Instruct-v0.1
```

**Comment by KamalUtla** [comment]
I am having the same issue,

I am using the container start command as:

`docker run --runtime nvidia --gpus all \
    -p 8000:8000 \
    --ipc=host \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=****************" \
    vllm/vllm-openai:latest \
    --model meta-llama/Llama-3.1-70B-Instruct \
    --dtype bfloat16 \
    --enable-lora \
    --lora-modules some_adater=some_model_name \
    --port 8000 \
    --max_model_len 4096 \
    --tensor-parallel-size 4`

**Comment by DarkLight1337** [comment]
> I am having the same issue,
> 
> I am using the container start command as:
> 
> ```
> docker run --runtime nvidia --gpus all \
>     -p 8000:8000 \
>     --ipc=host \
>     -v ~/.cache/huggingface:/root/.cache/huggingface \
>     --env "HUGGING_FACE_HUB_TOKEN=****************" \
>     vllm/vllm-openai:latest \
>     --model meta-llama/Llama-3.1-70B-Instruct \
>     --dtype bfloat16 \
>     --enable-lora \
>     --lora-modules some_adater=some_model_name \
>     --port 8000 \
>     --max_model_len 4096 \
>     --tensor-parallel-size 4```
> ```

You're passing two `-p/--port` arguments to the same command here. I think you can use `--` to separate the part of the command that is used for docker and the other part for the inner command to run.

**Comment by KamalUtla** [comment]
> > I am having the same issue,
> > I am using the container start command as:
> > ```
> > docker run --runtime nvidia --gpus all \
> >     -p 8000:8000 \
> >     --ipc=host \
> >     -v ~/.cache/huggingface:/root/.cache/huggingface \
> >     --env "HUGGING_FACE_HUB_TOKEN=****************" \
> >     vllm/vllm-openai:latest \
> >     --model meta-llama/Llama-3.1-70B-Instruct \
> >     --dtype bfloat16 \
> >     --enable-lora \
> >     --lora-modules some_adater=some_model_name \
> >     --port 8000 \
> >     --max_model_len 4096 \
> >     --tensor-parallel-size 4```
> > ```
> 
> You're passing two `-p/--port` arguments to the same command here. I think you can use `--` to separate the part of the command that is used for docker and the other part for the inner command to run.

Hey thanks for the quick reply but i really dont know about what you are saying, like using '--' to separate the docker and vllm commands, can you maybe give me an example? sorry for the trouble but your help will be greatly appreciated

**Comment by DarkLight1337** [comment]
I mean you can try

```
docker run --runtime nvidia --gpus all \
    -p 8000:8000 \
    --ipc=host \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=****************" \
    -- \  # Added this line
    vllm/vllm-openai:latest \
    --model meta-llama/Llama-3.1-70B-Instruct \
    --dtype bfloat16 \
    --enable-lora \
    --lora-modules some_adater=some_model_name \
    --port 8000 \
    --max_model_len 4096 \
    --tensor-parallel-size 4
```

That being said I haven't tested this.

**Comment by KamalUtla** [comment]
@DarkLight1337 no luck

I tried the command:

```
docker run --runtime nvidia --gpus all \
    -p 8000:8000 \
    --ipc=host \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=************************** " \
    -- \
    vllm/vllm-openai:latest \
    --model meta-llama/Llama-3.1-70B-Instruct \
    --dtype bfloat16 \
    --enable-lora \
    --lora-modules adapter=adapter_path \
    --max_model_len 4096 \
    --tensor-parallel-size 4
```
- removed the --port argument in vLLM commands
- added the separator 

and still no luck, same error: `api_server.py: error: argument --pipeline-parallel-size/-pp: invalid int value: '8000:8000'`
