### ISSUE TITLE
docker image error ModuleNotFoundError: No module named 'vllm'

### ISSUE THREAD

**Issue by ehartford** [vllm-project/vllm#2236]
using this procedure
https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html

I was deploying on runpod this image:
vllm/vllm-openai:latest
https://hub.docker.com/r/vllm/vllm-openai/tags

then I get an error

```
2023-12-21T15:25:16.536115444Z /usr/bin/python3: Error while finding module specification for 'vllm.entrypoints.openai.api_server' (ModuleNotFoundError: No module named 'vllm')
```

**Comment by simon-mo** [comment]
Do you have a folder in the container named vllm on the path that could override the installation by any chance?

**Comment by ehartford** [comment]
> Do you have a folder in the container named vllm on the path that could override the installation by any chance? 

No. This is on Runpod

**Comment by treezy254** [comment]
pip install vllm

**Comment by ehartford** [comment]
this is the literal vllm docker image, the official one.

https://hub.docker.com/r/vllm/vllm-openai/tags

Are you trying to tell me that vllm isn't installed on the vllm docker image?

**Comment by wwydmanski** [comment]
@ehartford, do you by any chance mount the container volume in the `/workspace` directory? If so, you overwrite the default workspace and remove the `vllm` module

**Comment by ehartford** [comment]
I bet that's the problem!

**Comment by rohitpaulk** [comment]
Ran into this too on Runpod. Changing the mount path from `/workspace` to something like `/root/.cache/huggingface` fixes it.

**Comment by RonanKMcGovern** [comment]
That's great, thanks @rohitpaulk
