### ISSUE TITLE
How to penalty repeating some parts of the answers?

### ISSUE THREAD

**Issue by SuperBruceJia** [vllm-project/vllm#2238]
I noticed some answers were incorrect due to repetition. **Is there a way to add some penalty to the repetition?** 

<img width="2168" alt="image" src="https://github.com/vllm-project/vllm/assets/31528604/db4d573d-1cb3-4799-ad3c-5085dc0f9e2e">

Thank you very much in advance!

Best regards,

Shuyue
Dec. 21st, 2023

**Comment by hmellor** [comment]
https://github.com/vllm-project/vllm/blob/925f3332cac488e5ad2dbc8f5c6d5f42d2556816/vllm/sampling_params.py#L47-L50
