### ISSUE TITLE
Get weird answer when loading Llama2-7b-chat-hf by using VLLM

### ISSUE THREAD

**Issue by pvtoan** [vllm-project/vllm#2240]
Hi,

I got a problem when I load Llama2-7B-Chat-Hf by using VLLM

**Config info:**
vllm 0.2.6
transformers 4.36.2
LLM Llama2-7B-Chat-Hf
Python 3.10.12
Ubuntu 22.04
GPU NVIDIA 4090 24gb

**Code**
llm = VLLM(model="meta-llama/Llama-2-7b-chat-hf", tensor_parallel_size=1, trust_remote_code=True, temperature=0.6, top_k=5, top_p=0.9, torch_dtype=torch.bfloat16, max_new_tokens=500)
llm("hello")

**Answer from llm("hello"):**
@matthew-mitchell.com
[www.matthew-mitchell.com](http://www.matthew-mitchell.com/)
Matthew Mitchell is a composer ...

I also try another question "explain to me the meaning of 'hi how are you today?' " and get weird answer too.

**My questions**
1. Can you please reproduce the answer to check if you get the same problem as me? If yes, please let me know how to fix this problem.

2. Also, Llama2-7b-Chat occupied around 21GB from VRAM. However, previously, I run exactly the same code before but it takes only around 14GB VRAM).

Moreover, when I use VLLM to load a LLM-13B model (model size is about 26GB) but it occupied around 23GB for each of my GPU-4090 24GB (I have two GPU-4090 24GB).

I think VLLM intends to take more memory from GPUs.

**Comment by DouHappy** [comment]
About VRAM：Because vLLM will try to occupy 90% of your VRAM for future cache. You can set gpu_memory_utilization when loading model to achieve lower VRAM  occupation.

**Comment by pvtoan** [comment]
Hi @DouHappy,

Thank you for your quick answer about VRAM issue. I did test and I can control VRAM occupation now.

If you have, please help me test my first question.
