### ISSUE TITLE
Running from Docker with Local Model Files Failed

### ISSUE THREAD

**Issue by thiner** [vllm-project/vllm#2247]
I tried to run vllm from Docker image follow the official tutorial https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html. My model files are stored at `/home/appuser/repo/models/Qwen-14b-Chat-AWQ`, I launched the docker image with command:
`docker run --gpus all -v /home/appuser/repo/models:/root/.cache/huggingface -p 8800:8000 --ipc=host vllm/vllm-openai:latest --model Qwen-14B-Chat-AWQ --quantization awq --tensor-parallel-size 2`, however, vllm reported it failed to load the model file:
```
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Qwen-14B-Chat-AWQ is not the path to a directory containing a file named config.json.
```
Then, I looked into the image, 
```
docker run --rm -it -v /home/appuser/repo/models:/root/.cache/huggingface --entrypoint bash  vllm/vllm-openai:latest
ls /root/.cache/huggingface/   
Qwen-14B-Chat-AWQ
```
Obviously, the model folder is right there.
Can anyone tell how to mount local model files into vllm docker image?

**Comment by jarekmor** [comment]
docker run --gpus all 
-v /home/appuser/repo/models/:/mnt/model/ \
-p 8800:8000 \
--env "TRANSFORMERS_OFFLINE=1" \
--env "HF_DATASET_OFFLINE=1" \
--ipc=host vllm/vllm-openai:latest \
--model="/mnt/model/" \
--quantization awq --tensor-parallel-size 2

**Comment by hmellor** [comment]
Closing as stale
