### ISSUE TITLE
Selective batching support

### ISSUE THREAD

**Issue by Lvjinhong** [vllm-project/vllm#2252]
Hello,

Does vLLM currently support Selective batching? In other words, if each sequence in a batch of inputs specifies a different max_new_tokens, can Selective batching be used to obtain varying output lengths within the same batch during generation? Typically, in the traditional batch processing approach, a uniform max value needs to be specified for generating within a batch.

Thank you.

**Comment by Alkaid-Friderich** [comment]
Does the continuous batching technology in the vLLM online service scenario contain the concept of batch size? @Lvjinhong

**Comment by Lvjinhong** [comment]
> Does the continuous batching technology in the vLLM online service scenario contain the concept of batch size? @Lvjinhong



I believe that batch size is indeed included in continuous batching because variable-length sequences are grouped together and, once the generated response is completed, new sequences replace the old ones. This method ensures that the GPU always decodes at the maximum batch size, and every generated token is utilized.

But, how is the output length of each sequence guaranteed?

**Comment by GongZhengLi** [comment]
I don't think vllm support selective batching, it deal the sequence group either in prefill stage or decoding stage. Maybe there is a hyper-parameter to control whether to prefill the  new request based a ratio of unsaturation.
