### ISSUE TITLE
How long does vllm take to load  your local model?

### ISSUE THREAD

**Issue by cangyi071** [vllm-project/vllm#2253]
for me ,baichuan2_7B，15minutes.

**Comment by yhyu13** [comment]
There shouldn't be anything to compile once you install the pip package. The model loading time should only limit by the storage media

You could attach a debugger in vscode to debug the model loading procedure.

**Comment by cangyi071** [comment]
> There shouldn't be anything to compile once you install the pip package. The model loading time should only limit by the storage media
> 
> You could attach a debugger in vscode to debug the model loading procedure.

Thank you,  a great inspiration to me. I feel like my model loading speed may be hanging by some configuration of my AI dedicated storage file system.

**Comment by cangyi071** [comment]
> There shouldn't be anything to compile once you install the pip package. The model loading time should only limit by the storage media
> 
> You could attach a debugger in vscode to debug the model loading procedure.

After investigation, it was found that the high-speed hard drive had a problem. After replacing the hard drive, the speed is very fast, only taking 2 minutes. Once again, thank you for your advice

**Comment by cangyi071** [comment]
Problem resolved, solution: replace the hard drive

**Comment by cangyi071** [comment]
Problem resolved, solution: replace the hard drive
