### ISSUE TITLE
Does the continuous batching technology in the vLLM online service scenario contain the concept of batch size?

### ISSUE THREAD

**Issue by Alkaid-Friderich** [vllm-project/vllm#2257]

**Comment by irasin** [comment]
The answer is YES, refer to https://github.com/vllm-project/vllm/blob/main/vllm/worker/model_runner.py#L187

In each iteration, the batch_size will change according to the scheduler outputs.

**Comment by Lvjinhong** [comment]
> The answer is YES, refer to https://github.com/vllm-project/vllm/blob/main/vllm/worker/model_runner.py#L187
> 
> In each iteration, the batch_size will change according to the scheduler outputs.


So, are you saying that I don't need to specify batch size before calling generate, and that I can pass in all inputs at once, and the scheduler will automatically adjust the batches?

**Comment by irasin** [comment]
> > The answer is YES, refer to https://github.com/vllm-project/vllm/blob/main/vllm/worker/model_runner.py#L187
> > In each iteration, the batch_size will change according to the scheduler outputs.
> 
> So, are you saying that I don't need to specify batch size before calling generate, and that I can pass in all inputs at once, and the scheduler will automatically adjust the batches?
> 

Yes, given a lot of request seq, scheduler will determine to run the prefill or decode stage by the seq status, and select the seqs to make up a batch to run (according to the max_num_batched_tokens/max_num_seqs/max_paddings defined in https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py)

> Can I dynamically specify the max_tokens for each sequence in the batch?
> 
> ```
>   sampling_params = SamplingParams(
>             n=1,
>             temperature=1.0,  
>             top_p=1.0,  
>             max_tokens=output_len 
>         )
> ```
> 
> For instance, by passing a list to max_tokens, with each item in the list corresponding to the length of each prompt

No, all promots in one request share the same sampling params. If you want to specify different output len for different prompt, you need to send multiple generate requests.

**Comment by Lvjinhong** [comment]
> > > The answer is YES, refer to https://github.com/vllm-project/vllm/blob/main/vllm/worker/model_runner.py#L187
> > > In each iteration, the batch_size will change according to the scheduler outputs.
> > 
> > 
> > So, are you saying that I don't need to specify batch size before calling generate, and that I can pass in all inputs at once, and the scheduler will automatically adjust the batches?
> 
> Yes, given a lot of request seq, scheduler will determine to run the prefill or decode stage by the seq status, and select the seqs to make up a batch to run (according to the max_num_batched_tokens/max_num_seqs/max_paddings defined in https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py)
> 
> > Can I dynamically specify the max_tokens for each sequence in the batch?
> > ```
> >   sampling_params = SamplingParams(
> >             n=1,
> >             temperature=1.0,  
> >             top_p=1.0,  
> >             max_tokens=output_len 
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For instance, by passing a list to max_tokens, with each item in the list corresponding to the length of each prompt
> 
> No, all promots in one request share the same sampling params. If you want to specify different output len for different prompt, you need to send multiple generate requests.



I understand your mean. However, in a scenario where there are numerous requests with varying output lengths, continuous batch processing may lose its effectiveness. 

I am curious if it is possible to adapt vLLM to suit my specific scenario with minimal changes, specifically to dynamically specify different output lengths within a single batch. 
This inquiry is just for my personal understanding. I would like to know if implementing such a feature would be significantly challenging. 

Thank you very much for your assistance.

**Comment by irasin** [comment]
@Lvjinhong
Forgive me for not explaining clearly, in each iteration, different seqs in one batch can have different sampling params. 
So in your scenario, you just need to asynchronously send multiple generate reqeusts with different prompts + sampling params, for example, https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py#L111

**Comment by irasin** [comment]
However, about the batch_size, as I mentioned in https://github.com/vllm-project/vllm/issues/1985, 
in the scheduler the number of pad token will be affected by the longest/shortest prompt, and in a common case, the batch_size will be relatively small（e.g 1/2/3...)
And the gpu computing utilization will not reach very high levels because of the fmha/gemm size is small

So just be careful that the throughput performance is strongly dependent on the prompt length distribution.

**Comment by Lvjinhong** [comment]
@irasin  Thank you for your answer. 
The asynchronous request example should also be applicable to offline scenarios, right? My understanding is that once I send the requests in the loop using async, the batching will be handled automatically, correct? 


```python
for i in tqdm(range(len(requests))):
  prompt, prompt_len, output_len = requests[i]
  sampling_params = SamplingParams(...)
  llm_outputs = llm.generate(...)
 ```

Also, regarding the issue you mentioned in #1985, if I sort the sequences by length before sending the requests, grouping together those of similar lengths, would this improve the utilization rate?

**Comment by irasin** [comment]
> @irasin Thank you for your answer. The asynchronous request example should also be applicable to offline scenarios, right? My understanding is that once I send the requests in the loop using async, the batching will be handled automatically, correct?
> 
> ```python
> for i in tqdm(range(len(requests))):
>   prompt, prompt_len, output_len = requests[i]
>   sampling_params = SamplingParams(...)
>   llm_outputs = llm.generate(...)
> ```
> 
No, in your code the `generate` call in the for loop  is a synchronous call, so the batch_size is always one, resulting in extremely low device utilization.
Only the asynchronous call can handle different prompt with different sampling params in one batch.

> Also, regarding the issue you mentioned in #1985, if I sort the sequences by length before sending the requests, grouping together those of similar lengths, would this improve the utilization rate?

Yes, But in the real-world online service scenario, we cannot perform real-time sort processing on user requests (They should be processed as FIFO). So sort ahead-of-time is just meaningless for testing.

**Comment by irasin** [comment]
Hi, @WoosukKwon, @zhuohan123, @simon-mo,
 I'd really like to know your thoughts on https://github.com/vllm-project/vllm/issues/1985

**Comment by Thewillman** [comment]
> > @irasin Thank you for your answer. The asynchronous request example should also be applicable to offline scenarios, right? My understanding is that once I send the requests in the loop using async, the batching will be handled automatically, correct?
> > ```python
> > for i in tqdm(range(len(requests))):
> >   prompt, prompt_len, output_len = requests[i]
> >   sampling_params = SamplingParams(...)
> >   llm_outputs = llm.generate(...)
> > ```
> 
> No, in your code the `generate` call in the for loop is a synchronous call, so the batch_size is always one, resulting in extremely low device utilization. Only the asynchronous call can handle different prompt with different sampling params in one batch.
> 
> > Also, regarding the issue you mentioned in #1985, if I sort the sequences by length before sending the requests, grouping together those of similar lengths, would this improve the utilization rate?
> 
> Yes, But in the real-world online service scenario, we cannot perform real-time sort processing on user requests (They should be processed as FIFO). So sort ahead-of-time is just meaningless for testing.

After checking the source code, it seems that args:max_output_len in one batch is chosen as the max one of the batch and then use padding to revise it for shorter examples? 
For benchmark code, offline vLLM for llama seems no need to use async operation. So can we regard the reason of the different length of generated tokens between vLLM and hf is the different calculation but not unfitable hyperparam setting?

**Comment by Lvjinhong** [comment]
> > > @irasin Thank you for your answer. The asynchronous request example should also be applicable to offline scenarios, right? My understanding is that once I send the requests in the loop using async, the batching will be handled automatically, correct?
> > > ```python
> > > for i in tqdm(range(len(requests))):
> > >   prompt, prompt_len, output_len = requests[i]
> > >   sampling_params = SamplingParams(...)
> > >   llm_outputs = llm.generate(...)
> > > ```
> > 
> > 
> > No, in your code the `generate` call in the for loop is a synchronous call, so the batch_size is always one, resulting in extremely low device utilization. Only the asynchronous call can handle different prompt with different sampling params in one batch.
> > > Also, regarding the issue you mentioned in #1985, if I sort the sequences by length before sending the requests, grouping together those of similar lengths, would this improve the utilization rate?
> > 
> > 
> > Yes, But in the real-world online service scenario, we cannot perform real-time sort processing on user requests (They should be processed as FIFO). So sort ahead-of-time is just meaningless for testing.
> 
> After checking the source code, it seems that args:max_output_len in one batch is chosen as the max one of the batch and then use padding to revise it for shorter examples? For benchmark code, offline vLLM for llama seems no need to use async operation. So can we regard the reason of the different length of generated tokens between vLLM and hf is the different calculation but not unfitable hyperparam setting?


In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.

**Comment by Lvjinhong** [comment]
@Thewillman   In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.

**Comment by Thewillman** [comment]
> @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.

It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?

**Comment by Lvjinhong** [comment]
> > @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.
> 
> It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?

sorry，I will retest later and confirm this again.

**Comment by Thewillman** [comment]
> > > @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.
> > 
> > 
> > It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?
> 
> sorry，I will retest later and confirm this again.

Thanks a lot, the different results between accelerate framework and hf transformer seems confuse a large amount of coders

**Comment by irasin** [comment]
> > > > @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.
> > > 
> > > 
> > > It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?
> > 
> > 
> > sorry，I will retest later and confirm this again.
> 
> Thanks a lot, the different results between accelerate framework and hf transformer seems confuse a large amount of coders

Hi, @Thewillman, I totally agree with you, but I was wondering if we only use greedy-search and the same prompt, the result of hf transfomers and vllm should be the same? If you have time, can you do some verfiy test?

**Comment by Thewillman** [comment]
> > > > > @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.
> > > > 
> > > > 
> > > > It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?
> > > 
> > > 
> > > sorry，I will retest later and confirm this again.
> > 
> > 
> > Thanks a lot, the different results between accelerate framework and hf transformer seems confuse a large amount of coders
> 
> Hi, @Thewillman, I totally agree with you, but I was wondering if we only use greedy-search and the same prompt, the result of hf transfomers and vllm should be the same? If you have time, can you do some verfiy test?

The test can be viewed on earlier issue,but nothing helpful advice [https://github.com/vllm-project/vllm/issues/2196](url)

**Comment by Thewillman** [comment]
> > > > > @Thewillman In my latest tests, I have noticed that the length of tokens generated using vLLM is consistent with those obtained from hf transformers.
> > > > 
> > > > 
> > > > It's not a bug of calculation? We just follow the benchmark code and find that it's hard to enforce examples sychronize hf transformer.Do you change the setting or use online version?
> > > 
> > > 
> > > sorry，I will retest later and confirm this again.
> > 
> > 
> > Thanks a lot, the different results between accelerate framework and hf transformer seems confuse a large amount of coders
> 
> Hi, @Thewillman, I totally agree with you, but I was wondering if we only use greedy-search and the same prompt, the result of hf transfomers and vllm should be the same? If you have time, can you do some verfiy test?

The test can be viewed on earlier issue,but nothing helpful advice [#2196 ](https://github.com/vllm-project/vllm/issues/2196)

**Comment by Lvjinhong** [comment]
@irasin In this asynchronous scenario, it is necessary to input prompt_token_ids based on pre-tokenization. So, can the tokenizer encode also be performed asynchronously to achieve higher performance?

**Comment by stupity110** [comment]
> @Lvjinhong Forgive me for not explaining clearly, in each iteration, different seqs in one batch can have different sampling params. So in your scenario, you just need to asynchronously send multiple generate reqeusts with different prompts + sampling params, for example, https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py#L111

So, By asynchronously sending multiple generate reqeusts, could we make continuous batching with different prompts and sampling params?
