### ISSUE TITLE
Could we support Fuyu-8B, a multimodel llm?

### ISSUE THREAD

**Issue by leiwen83** [vllm-project/vllm#2262]
Hi,

Fuyu 8B is a multimodel llm model, could we support it in vllm?
https://www.adept.ai/blog/fuyu-8b

It seems to me current vllm only could support pure text, so for this kind of multimodel mixing with image, how could we handle it?

Thx~

**Comment by simon-mo** [comment]
now we added supported for llava, this is welcomed!

**Comment by Isotr0py** [comment]
I would like to work on this model. But it seems that the `persimmon` used as language model in `Fuyu-8B` hasn't been supported.

Maybe we can support it first?
