### ISSUE TITLE
awq gemm 4bit kernal is slower than gemm fp16

### ISSUE THREAD

**Issue by shiqingzhangCSU** [vllm-project/vllm#2268]
![image](https://github.com/vllm-project/vllm/assets/44834482/184350b3-8181-4fbf-ae6b-812f2af995ca)
time cost for each ops
![image](https://github.com/vllm-project/vllm/assets/44834482/a7e29482-741d-4e80-a1c6-9468abec16cc)

When I was testing the llama-like model , I found that the model inference of awq int4 was slower than the fp16 version. The specific analysis was that the int4 gemm kernel was too slow. Is there any optimization plan for this part? Or are there any optimization ideas?

**Comment by Archmilio** [comment]
How many batches did you run? In AutoAWQ GIT, it is recommended to use up to 8 batches for AWQ.

https://github.com/casper-hansen/AutoAWQ
There are two versions of AWQ: GEMM and GEMV. Both names relate to how matrix multiplication runs under the hood. We suggest the following:

GEMV (quantized): 20% faster than GEMM, only batch size 1 (not good for large context).
GEMM (quantized): Much faster than FP16 at batch sizes below 8 (good with large contexts).
FP16 (non-quantized): Recommended for highest throughput: [vLLM](https://github.com/vllm-project/vllm).

**Comment by shiqingzhangCSU** [comment]
> How many batches did you run? In AutoAWQ GIT, it is recommended to use up to 8 batches for AWQ.
> 
> https://github.com/casper-hansen/AutoAWQ There are two versions of AWQ: GEMM and GEMV. Both names relate to how matrix multiplication runs under the hood. We suggest the following:
> 
> GEMV (quantized): 20% faster than GEMM, only batch size 1 (not good for large context). GEMM (quantized): Much faster than FP16 at batch sizes below 8 (good with large contexts). FP16 (non-quantized): Recommended for highest throughput: [vLLM](https://github.com/vllm-project/vllm).
I test  1, 2, 4, 8 batches, and fp16 faster than int4 in every batchsize. 😫

**Comment by shiqingzhangCSU** [comment]
> How many batches did you run? In AutoAWQ GIT, it is recommended to use up to 8 batches for AWQ.
> 
> https://github.com/casper-hansen/AutoAWQ There are two versions of AWQ: GEMM and GEMV. Both names relate to how matrix multiplication runs under the hood. We suggest the following:
> 
> GEMV (quantized): 20% faster than GEMM, only batch size 1 (not good for large context). GEMM (quantized): Much faster than FP16 at batch sizes below 8 (good with large contexts). FP16 (non-quantized): Recommended for highest throughput: [vLLM](https://github.com/vllm-project/vllm).

I test 1, 2, 4, 8 batches, and fp16 faster than int4 in every batchsize. 😫

**Comment by hmellor** [comment]
This is a known issue (hence the warning in the [documentation](https://docs.vllm.ai/en/latest/quantization/auto_awq.html)).

Contributions improving AWQ performance are welcome 😄
