### ISSUE TITLE
Awq quantized qwen-72b-chat input long text returns empty string

### ISSUE THREAD

**Issue by ly19970621** [vllm-project/vllm#2275]
In the config.json file of qwne-72b-chat, it says that it supports 32768 tokens. I changed max-model-len to 16384 for the awq-quantized model and tried inputting around 10000 tokens but it returned an empty string with the warning message
 `Input prompt (10854 tokens) is too long and exceeds the capacity of block_manager`. 
When I loaded the original gptq model quantized by VLLM with max-model-len set to 16384, it returned normally with 10000 tokens input. However, when I changed max-model-len to 32768, it also returned an empty string with the same warning message. Could you please help me figure out what could be causing this issue? 
My hardware environment includes a single _A800-80G GPU_ and my software environment includes _CUDA 12.1, Python 3.10.13, VLLM 0.2.6, Transformers 4.35.2, and AutoAWQ 0.1.7._
![Uploading 2023-12-27 09-39-05屏幕截图.png…]()

**Comment by prabuvnc** [comment]
The same issue happens with non-quantized model of qwen-72b-chat as well, even loading the model with max_seq_len with 32768 tokens cant handle longer prompt (> 10000 tokens) and returns empty string with above error message stating "exceeds the capacity of block manager".
This is not an issue with other longer context models like mixtral

**Comment by Wimeremce7** [comment]
我也遇到同样的问题，需要修改什么参数来解决吗？
