### ISSUE TITLE
Support `logprobs` for `ChatCompletionRequest` in openai api server?

### ISSUE THREAD

**Issue by beginlner** [vllm-project/vllm#2276]

**Comment by jlcmoore** [comment]
This would be great to have, if possible.

E.g. `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-7b-hf`  and
```
from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
completion = client.completions.create(model="meta-llama/Llama-2-7b-hf",
                                      prompt="Hello!",
                                      logprobs=5)
print("Completion result:", completion)
```
works but `python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-7b-chat-hf` 
```
from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
completion = client.completions.create(model="meta-llama/Llama-2-7b-chat-hf",
                                      messages= [{'role' : 'user', 'content': "Hello!"}],
                                      logprobs=5)
print("Completion result:", completion)
```
does not.

For some reason log probs are currently only set up for completions end points, not chat end points. I think the fix would simply entail changing `serving_chat.py` [link](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_chat.py) to incorporate log probs like `serving_completion.py` does [link](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_completion.py). 

Thanks!

**Comment by simon-mo** [comment]
Closed by https://github.com/vllm-project/vllm/pull/2918
