### ISSUE TITLE
how to set tensor-parallel-size and pipeline-parallel-size in llama structure?

### ISSUE THREAD

**Issue by CaoYiwei** [vllm-project/vllm#2280]
I want to deploy hf 70b model on 4 * A6000.   Which kind of hyper parameters is better  tp=2,pp=2 or tp=1,pp=4 or tp=4, pp=1?

**Comment by WoosukKwon** [comment]
Hi @CaoYiwei, vLLM currently does not support pipeline parallelism. However, you can use tensor parallelism very easily. Please check out our [docs](https://docs.vllm.ai/en/latest/serving/distributed_serving.html).
