### ISSUE TITLE
Retrieving a list of supported models

### ISSUE THREAD

**Issue by peer0** [vllm-project/vllm#2282]
is there a method of vllm that retrieves all the supported models?

**Comment by jessiewiswjc** [comment]
ctrl+f in [doc](https://docs.vllm.ai/en/latest/models/supported_models.html)?

**Comment by WoosukKwon** [comment]
Hi @peer0, you can either check out docs (as @jessiewiswjc answered) or find them in our code:

https://github.com/vllm-project/vllm/blob/9140561059904f133a3c146f04afe13d1cdd5a6c/vllm/model_executor/models/__init__.py#L12-L40
