### ISSUE TITLE
Try Chatglm2-6b-32k with openai api-server, get unexpected result

### ISSUE THREAD

**Issue by zrl4836** [vllm-project/vllm#2299]
1 When I use openai api-server with PyTorch  , I can get reasonable results。
https://github.com/THUDM/ChatGLM2-6B/blob/main/openai_api.py
Logs：
![image](https://github.com/vllm-project/vllm/assets/28527493/7c8e3bad-7fec-4943-85d5-605f20636b96)

2 When I use openai api-server with vllm , I get unexpected results. [vllm 0.2.6]
`python3 -m vllm.entrypoints.openai.api_server --model /data/ZhipuAI/chatglm2-6b-32k  --tokenizer /data/ZhipuAI/chatglm2-6b-32k  --trust-remote-code`
Logs:
![image](https://github.com/vllm-project/vllm/assets/28527493/a27fe71a-dc1f-43a1-8806-fe42cf1b3d91)
![image](https://github.com/vllm-project/vllm/assets/28527493/a5e87c27-a7a1-4ddd-b391-eed3bcd89fa1)

3 The request script is as follows：
`from openai import OpenAI
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
models = client.models.list()
model = models.data[0].id
contents = [
            "概括下这段文字：年轻女孩沦为乞丐，牙齿掉光呆坐路边，流浪2个月，警方救助被拒。近日，多名网友发文称，广东深圳龙岗区布吉街道有一名年轻女孩流浪近两三个月，这名女孩衣着单薄，牙齿全部脱落，手脚起皮，每当有人经过就会大喊大叫。曝光照片显示，女孩一头长发，长相清秀气质，皮肤白皙。目前，在各方帮助下，该女子已于12月20日晚安全返回家乡。综合媒体报道，近日，有网友反映在深圳市龙岗区布吉街道，有一名牙齿脱落、衣着单薄的女子提着行李箱，在街头流浪。网友发布的帖文显示，流浪女子手脚起皮、牙齿脱落坐在街头，身边放着一个行李箱和一些杂物。该女子精神疑似不正常，有时会大喊大叫。有网友表示，早在今年10月已经有人看到该女子在布吉街道流浪，此外，还有网友在阪田街道看到过她的身影。12月22日，布吉派出所工作人员表示，已经记录反映的情况，之后会有回复。该所还回应媒体称，警方已和这名流浪女子有过接触，但女子称自己不愿意接受社会救助。深圳龙岗区妇联工作人员表示，该会已对流浪女子介入救助，她前期比较拒绝我们提供的帮助，我们给她一些吃的喝的，也帮她安排住宿，但她都比较抵触。工作人员表示，该女子并非深圳人。针对贴文反映的问题，龙岗区民政局会同布吉街道第一时间对该女子进行了救助，向其提供了食物、饮水以及棉被、棉大衣等御寒物资。在各方帮助下，该女子已于12月20日晚安全返回原籍地。",
            ]

fn = open("vllm026.log", "w")
for content in contents:
    for i in range(100):
        chat_completion = client.chat.completions.create(
            messages=[{
                "role": "user",
                "content": content
            }],
            model=model,
            temperature=0.8,
            top_p=0.8,            
        )
        print(f"第{i}次测试：{chat_completion.choices[0].message}")
        print(f'----'*50)
        fn.write(f"第{i}次测试：{chat_completion.choices[0].message} \n") 
fn.close()`

[1-pt-nv.log](https://github.com/vllm-project/vllm/files/13790599/1-pt-nv.log)
[2-vllm026.log](https://github.com/vllm-project/vllm/files/13790600/2-vllm026.log)

**Comment by 0-hero** [comment]
Please try with this `python3 -m vllm.entrypoints.openai.api_server --model THUDM/chatglm3-6b-32k --trust-remote-code`

**Comment by huyuan-cn** [comment]
> Please try with this `python3 -m vllm.entrypoints.openai.api_server --model THUDM/chatglm3-6b-32k --trust-remote-code`

Does the model name must  be "THUDM/chatglm3-6b"? I customize it like ”chatglm3-6b-vllm“, vllm reply  will include duplicates and "|im_end|" information.

**Comment by huyuan-cn** [comment]
I tried adding these two parameters, and there was some improvement because they were originally defined in THUDM/ChatGLM3-6B/openai_api.py.
presence_penalty=0.0,
frequency_penalty=1.0,
