### ISSUE TITLE
python or rust for http server，which is better?

### ISSUE THREAD

**Issue by frankxyy** [vllm-project/vllm#2303]
Hi, in a python http_server，multiple coroutines or threads are scheduled by the interpreter.  And it seems not easy to add some user-defined scheduling logic. By the way, the rust language seems provide a more detailed interface for concurrency related developing. So will a rust http server provide better concurrency?

**Comment by EricLBuehler** [comment]
@frankxyy have you seen https://github.com/EricLBuehler/candle-vllm?
