### ISSUE TITLE
Mistral 7B takes up 69GB of vRAM on A100

### ISSUE THREAD

**Issue by WinsonSou** [vllm-project/vllm#2304]
I'm trying to run multiple instances of Mistral 7B on a A100 GPU. However it seems to be taking up 69GBs of vRAM on the A100.

Command i'm using to run
`@4xa100-node:~$ sudo docker run --runtime nvidia --gpus all     -v ~/.cache/huggingface:/root/.cache/huggingface     -p 8000:8000     --ipc=host     vllm/vllm-openai:latest     --model mistralai/Mistral-7B-v0.1`

Output
![image](https://github.com/vllm-project/vllm/assets/34645607/c3e69e40-ecd3-4b11-9c2b-85027daf6a51)

What seems to be the issue? Am i doing something wrong?

**Comment by rsnm2** [comment]
vLLM has an internal memory manager for the KV-cache and reserves the memory at the start to do so. So, seeing high RAM utilization is expected and will not fluctuate.


To use tensor parallelism (i.e. shard the model over multiple gpus), launch with `--tensor-parallel-size 4` 

https://docs.vllm.ai/en/latest/models/engine_args.html#cmdoption-tensor-parallel-size
