### ISSUE TITLE
Support for chatglm-6b

### ISSUE THREAD

**Issue by datalee** [vllm-project/vllm#231]
It would be great if you could support chatglm-6b，It's a popular chinese model。
https://huggingface.co/THUDM/chatglm-6b

**Comment by zhaoying9105** [comment]
mark

**Comment by HJT9328** [comment]
mark

**Comment by binarri** [comment]
mark

**Comment by Jeffwan** [comment]
If anyone is familiar with chatGLM model architecture, feel free to help on #625. I am new to transformer architecture and not sure if my changes is correct..

**Comment by cabbagetalk** [comment]
> If anyone is familiar with chatGLM model architecture, feel free to help on #625. I am new to transformer architecture and not sure if my changes is correct..

Vllm can support chatglm 6b now？

**Comment by simon-mo** [comment]
If anyone have bandwidth to help us implement ChatGLM3 support, please leave a comment and coordinate here: https://github.com/vllm-project/vllm/issues/1552

**Comment by hmellor** [comment]
ChatGLM supported in #1261
