### ISSUE TITLE
out of memory with mixtral AWQ

### ISSUE THREAD

**Issue by m0wer** [vllm-project/vllm#2312]
Error:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 24.56 MiB is free. Process 106008 has 23.66 GiB memory in use. Of the allocated memory 23.19 GiB is allocated by PyTorch, and 32.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Model: https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ

Command:

```
docker run --runtime nvidia --gpus all     \
-v [...]:/root/.cache/huggingface     --env "HUGGING_FACE_HUB_TOKEN=[...]"    \
 -p 10080:8000     --ipc=host     vllm/vllm-openai:latest   --trust-remote-code  \
--model TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ \
--dtype auto --gpu-memory-utilization 0.5 --max-model-len 4096 --quantization awq
```

Does not work without the extra parameters either.

HW: RTX 3090 (24GB).

Looks similar to https://github.com/vllm-project/vllm/issues/188 but https://github.com/vllm-project/vllm/issues/188#issuecomment-1785991729 didn't work here.

**Comment by WoosukKwon** [comment]
Hi @m0wer, the Mixtral model has ~47B parameters. Therefore, the model parameters take ~24GB of memory with the 4-bit AWQ quantization. Considering the space for intermediate activations and KV cache, your GPU memory is simply not big enough to hold the quantized model.

**Comment by m0wer** [comment]
Thanks for your reply @WoosukKwon .

The same happens with smaller models, such as Mistral 7B AWQ.

And I guess there is no multi-GPU support (I have also a RTX 2060 with 6GB) nor partial offloading (rest with CPU), right?

**Comment by tongyx361** [comment]
In my case (pure Linux with A100(80GB)),
decreasing `swap_space` (perhaps under the corresponding value of GPU memory * `gpu_memory_utilization`) helps.

**Comment by Haoping-Xiao** [comment]
same here. must be a bug. my GPU memory budget is even enough for the unquantized model but oom for the awq quantized one.

**Comment by YYXLN** [comment]
I have also run into this problem with amd radeon. If I launch the vllm as a pod and give the initial command as sleep, the graphics pipe is 100% occupied.
