### ISSUE TITLE
Outdated Pydantic Version

### ISSUE THREAD

**Issue by kmcleste** [vllm-project/vllm#2313]
OpenAI's Python library now allows for Pydantic versions >= 1.9.0, < 3 (see openai [requirements](https://github.com/openai/openai-python/blob/f1c7d714914e3321ca2e72839fe2d132a8646e7f/pyproject.toml#L12C27-L12C27)). Would it be possible to bump the pinned version for vLLM to match?

**Comment by kmcleste** [comment]
I can make a PR if there is no other reason for the version to be pinned to 1.10.13

**Comment by jvmncs** [comment]
https://github.com/vllm-project/vllm/pull/2322
