### ISSUE TITLE
Help with autogptq

### ISSUE THREAD

**Issue by jesulo** [vllm-project/vllm#2319]
Please help with autogptq, installing in  rhel8 ppc64le in podman, pip3 install auto-gptq --extra-index-url https://huggingface.github.io/autogptq-index/whl/cu118/

error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [19 lines of output]
python: can't open file '/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/./autogptq_extension/qigen/generate.py': [Errno 2] No such file or directory
Traceback (most recent call last):
File "/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/setup.py", line 109, in
subprocess.check_output(["python", "./autogptq_extension/qigen/generate.py", "--module", "--search", "--p", str(p)])
File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 424, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/opt/anaconda/envs/vicuna/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', './autogptq_extension/qigen/generate.py', '--module', '--search', '--p', '160']' returned non-zero exit status 2.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/tmp/pip-install-mq0hh9__/auto-gptq_ad9386319bae45eea27a8ef6f79b46f3/setup.py", line 111, in <module>
      raise Exception(f"Generating QiGen kernels failed with the error shown above.")
  Exception: Generating QiGen kernels failed with the error shown above.
  Generating qigen kernels...
  [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-89lnfo0w

**Comment by wejoncy** [comment]
Hi, It might be better to issue this on AutoGPTQ repo.

But you can have a try with [QLLM](https://github.com/wejoncy/QLLM), Which is also good to quantize model for vLLM serving.
```
COMPATIBLE_WITH_AUTOGPTQ=1 python -m qllm --model=meta-llama/Llama-2-7b-hf --method=gptq --save ./Llama-2-7b-4bit --pack_mode=GPTQ
```
