### ISSUE TITLE
When I use awq to quantify yi-34b-chat, then llm.generate: (RuntimeError: CUDA error: device-side assert triggered)

### ISSUE THREAD

**Issue by mingyangAbc** [vllm-project/vllm#2320]
I use the project(https://github.com/casper-hansen/AutoAWQ) quantification yi-34b-chat model, then i run vllm demo meet “RuntimeError: CUDA error: device-side assert triggered”.

> **code：**

    from vllm import LLM, SamplingParams
    prompts = [
        "Hello, my name is",
    ]
    sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
    llm = LLM(model="/Yi/quantized_model", tensor_parallel_size=1, trust_remote_code=True)
    outputs = llm.generate(prompts, sampling_params)
    # Print the outputs.
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

> **log：**

2024-01-02 20:21:56,878 - modelscope - INFO - PyTorch version 2.1.2+cu118 Found.
2024-01-02 20:21:56,879 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-01-02 20:21:56,918 - modelscope - INFO - Loading done! Current index file version is 1.9.5, with md5 6cc4bf9c033540e7f2386c0058d4f4b4 and a total number of 945 components indexed
[2024-01-02 20:21:59,535] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WARNING 01-02 20:21:59 config.py:179] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 01-02 20:21:59 llm_engine.py:73] Initializing an LLM engine with config: model='/Yi/quantized_model', tokenizer='/Yi/quantized_model', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, enforce_eager=False, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 01-02 20:22:21 llm_engine.py:223] # GPU blocks: 3168, # CPU blocks: 1092
INFO 01-02 20:22:25 model_runner.py:394] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-02 20:22:40 model_runner.py:437] Graph capturing finished in 15 secs.
Processed prompts:   0%|                                  | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/tmp/pycharm_project_314/test/test.py", line 32, in <module>
    outputs = llm.generate(prompts, sampling_params)
  File "/root/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 165, in generate
    return self._run_engine(use_tqdm)
  File "/root/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 185, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/root/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 581, in step
    output = self._run_workers(
  File "/root/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 755, in _run_workers
    self._run_workers_in_batch(workers, method, *args, **kwargs))
  File "/root/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 729, in _run_workers_in_batch
    output = executor(*args, **kwargs)
  File "/root/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/lib/python3.10/site-packages/vllm/worker/worker.py", line 159, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/root/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 354, in execute_model
    output = self.model.sample(
  File "/root/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 295, in sample
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/root/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py", line 58, in forward
    do_min_p) = SamplingTensors.from_sampling_metadata(
  File "/root/lib/python3.10/site-packages/vllm/model_executor/sampling_metadata.py", line 131, in from_sampling_metadata
    sampling_tensors = SamplingTensors.from_lists(
  File "/root/lib/python3.10/site-packages/vllm/model_executor/sampling_metadata.py", line 218, in from_lists
    temperatures=temperatures_t.to(device=device, non_blocking=True),
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Processed prompts:   0%|                                  | 0/1 [00:00<?, ?it/s]
../aten/src/ATen/native/cuda/Indexing.cu:1239: indexSelectSmallIndex: block: [34,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

> **nvcc -V：**

   nvcc: NVIDIA (R) Cuda compiler driver
   Copyright (c) 2005-2022 NVIDIA Corporation
   Built on Wed_Sep_21_10:33:58_PDT_2022
   Cuda compilation tools, release 11.8, V11.8.89
   Build cuda_11.8.r11.8/compiler.31833905_0

> **pip list：**

absl-py                       2.0.0
accelerate                    0.25.0
addict                        2.4.0
aiofiles                      23.2.1
aiohttp                       3.9.1
aioprometheus                 23.3.0
aiosignal                     1.3.1
aliyun-python-sdk-core        2.14.0
aliyun-python-sdk-kms         2.16.2
altair                        5.2.0
annotated-types               0.6.0
anyio                         3.7.1
async-timeout                 4.0.3
attributedict                 0.3.0
attrs                         23.1.0
auto-gptq                     0.5.1
autoawq                       0.1.7+cu118
bitsandbytes                  0.41.2.post2
blessings                     1.7
cachetools                    5.3.2
certifi                       2023.11.17
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cmake                         3.25.0
codecov                       2.1.13
colorama                      0.4.6
coloredlogs                   15.0.1
colour-runner                 0.1.1
contourpy                     1.2.0
coverage                      7.4.0
cpm-kernels                   1.0.11
crcmod                        1.7
cryptography                  41.0.7
cycler                        0.12.1
DataProperty                  1.0.1
datasets                      2.16.1
deepdiff                      6.7.1
deepspeed                     0.12.5
dill                          0.3.6
distlib                       0.3.8
docstring-parser              0.15
einops                        0.7.0
evaluate                      0.4.1
exceptiongroup                1.2.0
fastapi                       0.104.1
ffmpy                         0.3.1
filelock                      3.13.1
fire                          0.5.0
fonttools                     4.46.0
frozenlist                    1.4.0
fsspec                        2023.10.0
gast                          0.5.4
gekko                         1.0.6
gevent                        22.10.2
google-auth                   2.25.1
google-auth-oauthlib          1.1.0
gradio                        3.50.2
gradio_client                 0.6.1
greenlet                      3.0.1
grpcio                        1.59.3
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.2
httptools                     0.6.1
httpx                         0.25.2
huggingface-hub               0.19.4
humanfriendly                 10.0
idna                          3.6
importlib-metadata            7.0.0
importlib-resources           6.1.1
inspecta                      0.1.3
jieba                         0.42.1
Jinja2                        3.1.2
jmespath                      0.10.0
joblib                        1.3.2
jsonlines                     4.0.0
jsonschema                    4.20.0
jsonschema-specifications     2023.11.2
kiwisolver                    1.4.5
lit                           15.0.7
lm_eval                       0.4.0
lxml                          5.0.0
Markdown                      3.5.1
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.2
mbstrdecoder                  1.1.3
mdurl                         0.1.2
modelscope                    1.9.5
mpmath                        1.3.0
ms-swift                      1.6.0.dev0
msgpack                       1.0.7
multidict                     6.0.4
multiprocess                  0.70.14
networkx                      3.2.1
ninja                         1.11.1.1
nltk                          3.8.1
numexpr                       2.8.8
numpy                         1.26.2
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.101
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.2.2
optimum                       1.14.1
ordered-set                   4.1.0
orjson                        3.9.10
oss2                          2.18.3
packaging                     23.2
pandas                        2.1.3
pathvalidate                  3.2.0
peft                          0.7.1
Pillow                        10.1.0
pip                           23.3.2
platformdirs                  4.1.0
pluggy                        1.3.0
portalocker                   2.8.2
protobuf                      4.23.4
psutil                        5.9.6
py-cpuinfo                    9.0.0
pyarrow                       14.0.1
pyarrow-hotfix                0.6
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pybind11                      2.11.1
pycparser                     2.21
pycryptodome                  3.19.0
pydantic                      1.10.13
pydantic_core                 2.14.5
pydub                         0.25.1
Pygments                      2.17.2
pynvml                        11.5.0
pyparsing                     3.1.1
pyproject-api                 1.6.1
pytablewriter                 1.2.0
python-dateutil               2.8.2
python-dotenv                 1.0.0
python-multipart              0.0.6
pytz                          2023.3.post1
PyYAML                        6.0.1
quantile-python               1.1
ray                           2.9.0
referencing                   0.31.1
regex                         2023.10.3
requests                      2.31.0
requests-oauthlib             1.3.1
responses                     0.18.0
rich                          13.7.0
rootpath                      0.1.1
rouge                         1.0.1
rouge-chinese                 1.0.3
rouge-score                   0.1.2
rpds-py                       0.13.2
rsa                           4.9
sacrebleu                     2.4.0
safetensors                   0.4.1
scikit-learn                  1.3.2
scipy                         1.11.4
semantic-version              2.10.0
sentencepiece                 0.1.99
setuptools                    68.0.0
shtab                         1.6.5
simplejson                    3.19.2
six                           1.16.0
sniffio                       1.3.0
sortedcontainers              2.4.0
sqlitedict                    2.1.0
sse-starlette                 1.8.2
starlette                     0.27.0
sympy                         1.12
tabledata                     1.3.3
tabulate                      0.9.0
tcolorpy                      0.1.4
tensorboard                   2.15.1
tensorboard-data-server       0.7.2
termcolor                     2.4.0
texttable                     1.7.0
threadpoolctl                 3.2.0
tiktoken                      0.5.2
tokenizers                    0.15.0
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         2.1.2+cu118
torchaudio                    2.1.0+cu118
torchvision                   0.16.0+cu118
tox                           4.11.4
tqdm                          4.66.1
tqdm-multiprocess             0.0.11
transformers                  4.35.2
transformers-stream-generator 0.0.4
triton                        2.1.0
trl                           0.7.7
typepy                        1.3.2
typing_extensions             4.8.0
tyro                          0.6.0
tzdata                        2023.3
urllib3                       2.1.0
uvicorn                       0.24.0.post1
uvloop                        0.19.0
virtualenv                    20.25.0
vllm                          0.2.6+cu118
watchfiles                    0.21.0
websockets                    11.0.3
Werkzeug                      3.0.1
wheel                         0.41.2
xformers                      0.0.23.post1+cu118
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.3
zipp                          3.17.0
zope.event                    5.0
zope.interface                6.1
zstandard                     0.22.0

**Comment by janelu9** [comment]
Maybe you CPU has been damaged

**Comment by davelza95** [comment]
Hello, @mingyangAbc did you find a solution?
