### ISSUE TITLE
LangChain and LlamaIndex support

### ISSUE THREAD

**Issue by ktolias** [vllm-project/vllm#233]
Excellent job, it made my LLM blazing fast. I tried it on T4 (16GB vRAM) and it seems to lower inference time from 36 secs to just 9 secs.

I then tried to use it along with LangChain and LlamaIndex but I got the following error:

<img width="1088" alt="Screenshot 2023-06-25 at 9 42 23 AM" src="https://github.com/vllm-project/vllm/assets/26122127/60540dcc-f550-4005-835c-69847a9cef4e">

ValidationError: 1 validation error for LLMChain
llm
  value is not a valid dict (type=type_error.dict) 

Can you please provide any guidance?

**Comment by beratcmn** [comment]
Langchain integration is easier than it looks. You can add `vllm.LLM` as a custom LLM. [Doc link](https://python.langchain.com/docs/modules/model_io/models/llms/how_to/custom_llm)

**Comment by ktolias** [comment]
Thanks mate! Langchain works like a charm! 
On the other hand llamaIndex seems to fetch the context and then hangs.
<img width="1189" alt="Screenshot 2023-06-25 at 5 21 14 PM" src="https://github.com/vllm-project/vllm/assets/26122127/86dec3e2-3cc3-4be8-ad0a-c2cda13cd137">

<img width="1199" alt="Screenshot 2023-06-25 at 5 21 27 PM" src="https://github.com/vllm-project/vllm/assets/26122127/2b1c49f5-6473-4039-9171-9e0de0931a39">

**Comment by ktolias** [comment]
It seems that there is a problem with the specific chain (RetrievalQA).
When I revert to the simple LLMChain, everything worked fine with LangChain.
The problem with LlamaIndex still remains.

<img width="1271" alt="Screenshot 2023-06-26 at 4 58 00 PM" src="https://github.com/vllm-project/vllm/assets/26122127/15f01556-24c8-4bfe-8a70-71af1682b24b">

**Comment by zhuohan123** [comment]
Please refer to https://python.langchain.com/docs/integrations/llms/vllm for the latest langchain integration!
