### ISSUE TITLE
Does vllm support private model serving from huggingface?

### ISSUE THREAD

**Issue by wisechat-eng** [vllm-project/vllm#2334]

**Comment by NikolaBorisov** [comment]
I think so, if you pass the right hugging face token as environment variable

**Comment by Soumendraprasad** [comment]
@NikolaBorisov , could you share some reference for how to use vllm to make an end point of private hugging face models . [Here](https://docs.vllm.ai/en/latest/getting_started/quickstart.html) it only mentioned that how to serve a hf model , but if the model is gated/private then how to make it's end point .

**Comment by DarkLight1337** [comment]
Assuming that you're accessing a private/gated model via your HuggingFace account, you can set `HF_TOKEN` or `HF_TOKEN_PATH` (using the associated with your account) as described [here](https://huggingface.co/docs/huggingface_hub/en/package_reference/environment_variables).
