### ISSUE TITLE
awq compression of llama 2 70b chat got bad result

### ISSUE THREAD

**Issue by fancyerii** [vllm-project/vllm#2339]
I use awq to quantize llama 2 70b-chat by:
```
CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" python quantize_llama.py
```
the codes of quantize_llama.py：

```
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

model_path = '/nas/lili/models_hf/70B-chat'
quant_path = '/nas/lili/models_hf/70B-chat-awq'
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }

# Load model
model = AutoAWQForCausalLM.from_pretrained(model_path, **{
                    "low_cpu_mem_usage": True,
                    "device_map": "auto"
                    })
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

# Quantize
model.quantize(tokenizer, quant_config=quant_config)

# Save quantized model
model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)

```

And I serve it with:
```
CUDA_VISIBLE_DEVICES=0,1 python api_server.py --model /nas/lili/models_hf/70B-chat-awq/ --port 8005  --tensor-parallel-size=2
```

In my test data, orginal llama 2 70b-chat got 0.581 accuracy. But awq compressed model only got 0.094. What's wrong?
my system info:
autoawq                                0.1.8
transformers                           4.36.1
torch                                  2.1.2

**Comment by Rahmat711** [comment]
+1

**Comment by wyxscir** [comment]
> I use awq to quantize llama 2 70b-chat by:
> 
> ```
> CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" python quantize_llama.py
> ```
> 
> the codes of quantize_llama.py：
> 
> ```
> from awq import AutoAWQForCausalLM
> from transformers import AutoTokenizer
> 
> model_path = '/nas/lili/models_hf/70B-chat'
> quant_path = '/nas/lili/models_hf/70B-chat-awq'
> quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
> 
> # Load model
> model = AutoAWQForCausalLM.from_pretrained(model_path, **{
>                     "low_cpu_mem_usage": True,
>                     "device_map": "auto"
>                     })
> tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> 
> # Quantize
> model.quantize(tokenizer, quant_config=quant_config)
> 
> # Save quantized model
> model.save_quantized(quant_path)
> tokenizer.save_pretrained(quant_path)
> ```
> 
> And I serve it with:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 python api_server.py --model /nas/lili/models_hf/70B-chat-awq/ --port 8005  --tensor-parallel-size=2
> ```
> 
> In my test data, orginal llama 2 70b-chat got 0.581 accuracy. But awq compressed model only got 0.094. What's wrong? my system info: autoawq 0.1.8 transformers 4.36.1 torch 2.1.2

I have similar questions, have you solved it?

**Comment by fancyerii** [comment]
> > I use awq to quantize llama 2 70b-chat by:
> > ```
> > CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" python quantize_llama.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the codes of quantize_llama.py：
> > ```
> > from awq import AutoAWQForCausalLM
> > from transformers import AutoTokenizer
> > 
> > model_path = '/nas/lili/models_hf/70B-chat'
> > quant_path = '/nas/lili/models_hf/70B-chat-awq'
> > quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }
> > 
> > # Load model
> > model = AutoAWQForCausalLM.from_pretrained(model_path, **{
> >                     "low_cpu_mem_usage": True,
> >                     "device_map": "auto"
> >                     })
> > tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
> > 
> > # Quantize
> > model.quantize(tokenizer, quant_config=quant_config)
> > 
> > # Save quantized model
> > model.save_quantized(quant_path)
> > tokenizer.save_pretrained(quant_path)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And I serve it with:
> > ```
> > CUDA_VISIBLE_DEVICES=0,1 python api_server.py --model /nas/lili/models_hf/70B-chat-awq/ --port 8005  --tensor-parallel-size=2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In my test data, orginal llama 2 70b-chat got 0.581 accuracy. But awq compressed model only got 0.094. What's wrong? my system info: autoawq 0.1.8 transformers 4.36.1 torch 2.1.2
> 
> I have similar questions, have you solved it?

not yet.

**Comment by qinchuanhui** [comment]
I have similar issue with llama-3-8B
