### ISSUE TITLE
when --gpu-memory-utilization is set to 0.9, while actually  the fraction of  gpu memory utilization is more than 0.9

### ISSUE THREAD

**Issue by meichangsu1** [vllm-project/vllm#2342]
![微信图片_20240104164759](https://github.com/vllm-project/vllm/assets/22477246/971416ee-23b0-4142-b1d8-a872533c302d)

**Comment by FlorianJoncour** [comment]
I don't know the vLLM internals well, but if you don't set `worker-use-ray` or `engine-use-ray`, some parts are not sent to ray.remote, and so gpu_memory_utilization is not used in these cases.

Maybe the `gpu-memory-utilization` could be more explicit about that but I'm not sure it's an issue btw.

**Comment by sdw12138** [comment]
+1 ， same question
