### ISSUE TITLE
memory leak in v0.2.7

### ISSUE THREAD

**Issue by smallmocha** [vllm-project/vllm#2345]
it seem exist memory leak in v0.2.7

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        1071  0.4  0.0 28963612 417336 ?     SNl  17:36   0:02 ray::RayWorkerVllm
root        1166  6.2  0.5 68235476 5179612 ?    RNl  17:36   0:36 ray::RayWorkerVllm.execute_method

two hours later
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        1071  0.1  0.0 28963612 417336 ?     SNl  17:36   0:14 ray::RayWorkerVllm
root        1166  3.4  0.6 69346516 6284616 ?    SNl  17:36   4:57 ray::RayWorkerVllm

three hours later
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root        1071  0.1  0.0 28963612 417336 ?     SNl  17:36   0:20 ray::RayWorkerVllm
root        1166  3.4  0.6 69987220 6919976 ?    SNl  17:36   7:27 ray::RayWorkerVllm

**Comment by smallmocha** [comment]
seem due to CUDA graph，no memory leak when enforce-eager=True

**Comment by baisechundu** [comment]
> 6919976
Mark!
Same problem, but it also frequently occurs in vllm0.2.6.  I used a gptq quantified model to deploy services。

**Comment by junior-zsy** [comment]
Same problem ， I used a awq quantified model to deploy services

**Comment by scriptator** [comment]
I also have problems with a memory leak with vllm 0.2.7. For me it's not limited to Ray but also concerns the API server itself, no matter whether I use the CUDA graph or not. I am running Mixtral unquantized on two A100 GPUs.

**Comment by baisechundu** [comment]
> I also have problems with a memory leak with vllm 0.2.7. For me it's not limited to Ray but also concerns the API server itself, no matter whether I use the CUDA graph or not. I am running Mixtral unquantized on two A100 GPUs.

I have set the following parameters and have not encountered any memory leakage issues yet:  --swap-space 0 --enforce-eager

**Comment by ChristineSeven** [comment]
Whether I use the CUDA graph or not, there is memory issue.

**Comment by meichangsu1** [comment]
same issue

**Comment by Receiling** [comment]
same issue

**Comment by ChristineSeven** [comment]
> > I also have problems with a memory leak with vllm 0.2.7. For me it's not limited to Ray but also concerns the API server itself, no matter whether I use the CUDA graph or not. I am running Mixtral unquantized on two A100 GPUs.
> 
> I have set the following parameters and have not encountered any memory leakage issues yet: --swap-space 0 --enforce-eager

Have you tried to start the server and try to stay for serveral hours or more？ I have tried serveral times and every time i can reproduce this

**Comment by ChristineSeven** [comment]
Not only in version 0.2.7, I tested 0.2.6, 0.2.3 also has this issue. The reproduce step is start the server and stay for serveral hours, then the issue comes. @zhuohan123 @WoosukKwon @pcmoritz would you help to take a look at this issue? I am not able to solve it.
