### ISSUE TITLE
OOM with meta-llama/Llama-2-70b-chat-hf

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#2348]
I have 8 Tesla V100 32 GB GPUS, and set tensor_parallel_size tp 8, which should be enough to run meta-llama/Llama-2-70b-chat-hf but I am getting an
```
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 
<img width="602" alt="Screenshot 2024-01-04 at 11 35 14 AM" src="https://github.com/vllm-project/vllm/assets/131425383/5ebb4b00-cfda-4358-847c-ac68d10f2ca8">

This is my setup, I can't use quantization since my GPUs are version 7
```
llm = VLLM(
        model='meta-llama/Llama-2-70b-chat-hf,
        trust_remote_code=True, 
        max_new_tokens=512,
        top_k=10,
        top_p=0.95,
        temperature=0,
        dtype="float16",
        tensor_parallel_size=8,
        gpu_memory_utilization=1,
        disable_log_stats=True,
        enforce_eager=True,
        max_model_len=1024
)

```

**Comment by JianqiaoLu** [comment]
it is true you cannot even loading the 70b-llama chat into 8 * v100 （interestingly thought, you can run the 70b qianwen chat based on same config）;) I guess it is due to vllm acceleration technique.

**Comment by iarbel84** [comment]
Any update here? I'm having the same issue when trying to load Llama-2-70B on 8xL4 GPUs (GCP G2 instance, total 192GB vRAM). Also couldn't load Mixtral-8x7B. Both models loaded fine with Huggingface TGI

**Comment by HoustonJ2013** [comment]
I tested v0.3.3 with cuda 11.8 on a node with 8 V100 32G, it works without OOM.
