### ISSUE TITLE
snapshot download from HF not from modelscope

### ISSUE THREAD

**Issue by VpkPrasanna** [vllm-project/vllm#2353]
since VLLM uses snapshot download from modelscope will not allow us to download private models , if it is implemented with snapshot download from HF it would be highly appreciable

**Comment by simon-mo** [comment]
can you elaborate? vLLM download from huggingface by default and we uses corresponding function from huggingface hub to perform the download. modelscope is just another option that's not on the default path.

**Comment by simon-mo** [comment]
here's the usage of huggingface snapshot download https://github.com/vllm-project/vllm/blob/937e7b7d7c460c00805ac358a4873ec0653ab2f5/vllm/model_executor/weight_utils.py#L155

**Comment by VpkPrasanna** [comment]
thanks for the clarification , how to load the hf private models (llama-2 model) by passing token ?

**Comment by simon-mo** [comment]
You can `huggingface-cli login` in the terminal and put in your token so it's saved in home directory, or pass in env var `HF_TOKEN`

**Comment by VpkPrasanna** [comment]
Thanks @simon-mo
