### ISSUE TITLE
NaN in running quantized MoE model (TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ)

### ISSUE THREAD

**Issue by parasol-aser** [vllm-project/vllm#2359]
Hi vLLM team! 

I was testing vLLM 0.2.7 for serving Mixtral-8x7B-Instruct-v0.1-AWQ on an A100 40G. Here is my command:

`python examples/llm_engine_example.py --model TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ --quantization awq --dtype half --enforce-eager --max-model-len 16`

I observed that MixtralForCausalLM produces NaN: 

> MixtralForCausalLM sample hidden_states:tensor([[[nan, nan, nan, ..., nan, nan, nan],
>      [nan, nan, nan, ..., nan, nan, nan],
>      [nan, nan, nan, ..., nan, nan, nan],
>      ...,
>      [nan, nan, nan, ..., nan, nan, nan],
>      [nan, nan, nan, ..., nan, nan, nan],
>      [nan, nan, nan, ..., nan, nan, nan]]], device='cuda:0',
>     dtype=torch.float16)

The above is printed (I added a print statement) on the hidden_states tensor in the MixtralForCausalLM sample function:
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/mixtral.py#L360

```python
def sample(
        self,
        hidden_states: Optional[torch.Tensor],
        sampling_metadata: SamplingMetadata,
    ) -> Optional[SamplerOutput]:
        print(f"MixtralForCausalLM sample hidden_states:{hidden_states}")
        next_tokens = self.sampler(self.lm_head.weight, hidden_states,
                                   sampling_metadata)
        return next_tokens
```

Is there a bug?

**Comment by MileSquareDevelopers** [comment]
I saw this too with another AWQ model I was running

**Comment by PhaneendraGunda** [comment]
getting same null response from AWQ model. 

```
curl http://localhost:8000/v1/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ",
        "prompt": "San Francisco is a",
        "max_tokens": 20,
        "temperature": 0.7
    }'
```

**output**

```
{"id":"cmpl-4b4e8effbcf6411c908d5f5fc6dd463b","object":"text_completion","created":4941,"model":"TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ","choices":[{"index":0,"text":"","logprobs":null,"finish_reason":"length"}],"usage":{"p
rompt_tokens":5,"total_tokens":25,"completion_tokens":20}}
```

logs from vLLM engine

```
Received request cmpl-4b4e8effbcf6411c908d5f5fc6dd463b: prompt: 'San Francisco is a', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0,
repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_to
kens=20, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [1, 3652, 9686, 349, 264].
(_AsyncLLMEngine pid=10216) INFO 01-09 20:33:11 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CP
U KV cache usage: 0.0%
```

**Comment by CSEEduanyu** [comment]
Hello, can I ask if the 4bit version of awq quantized is faster than fp16 without error?

**Comment by jaywongs** [comment]
This problem still exist~

**Comment by tom-doerr** [comment]
Might be an issue with how TheBloke quantized it. This version of Mixtral AWQ might work: https://huggingface.co/casperhansen/mixtral-instruct-awq

**Comment by mridulBanik112** [comment]
I am also getting same issue. Theres's nothing in output. Working with 4 A10 gpu.
