### ISSUE TITLE
v2.0.7 becomed slower than v2.0.6

### ISSUE THREAD

**Issue by janelu9** [vllm-project/vllm#2367]
model: deepseek-llm-67b-chat -awq-int4
tp = 2
gpu: A100-40G x2
v2.0.7: 16tokens/s
v2.0.6: 21tokens/s

**Comment by yudian0504** [comment]
maybe caused by this commit:

https://github.com/vllm-project/vllm/pull/2221

**Comment by morning-hao** [comment]
+1， slower than before，slower too much
