### ISSUE TITLE
 [Bug] torch.distributed.DistBackendError: NCCL error ....  Address already in use

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#237]
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    llm = LLM(model=path)
  File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/llm.py", line 56, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 151, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 93, in __init__
    worker = worker_cls(
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 40, in __init__
    _init_distributed_environment(parallel_config, rank,
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 302, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Call to bind failed : Address already in use
```

Why is this?

**Comment by zhuohan123** [comment]
[This line](https://github.com/vllm-project/vllm/blob/0603379863cd98aac0b56a32eed49c6f0c8bff46/vllm/engine/ray_utils.py#L98) chooses a random port for initializing NCCL. Does this cause the issue you meet? Maybe you can try simply rerun the script.

**Comment by sleepwalker2017** [comment]
> [This line](https://github.com/vllm-project/vllm/blob/0603379863cd98aac0b56a32eed49c6f0c8bff46/vllm/engine/ray_utils.py#L98) chooses a random port for initializing NCCL. Does this cause the issue you meet? Maybe you can try simply rerun the script.

Thank you! I still have a question. 
If I run on only one device, why does it still init nccl. Maybe the port should be inited only when nccl is needed, and also the port should be assigned by users.

**Comment by zhuohan123** [comment]
> > [This line](https://github.com/vllm-project/vllm/blob/0603379863cd98aac0b56a32eed49c6f0c8bff46/vllm/engine/ray_utils.py#L98) chooses a random port for initializing NCCL. Does this cause the issue you meet? Maybe you can try simply rerun the script.
> 
> Thank you! I still have a question. If I run on only one device, why does it still init nccl. Maybe the port should be inited only when nccl is needed, and also the port should be assigned by users.

This is an implementation issue as mentioned in #117 and we'll fix it. For the port number, this is an internal port just used for initialization, so we use a random selection process.

**Comment by zhuohan123** [comment]
Please re-open this issue if you have any further questions.
