### ISSUE TITLE
How to use Splitwise(from microsoft) in vllm?

### ISSUE THREAD

**Issue by Lin-Qingyang-Alec** [vllm-project/vllm#2370]
Microsoft have claimed that ”Splitwise“ is supported in vLLM, see
https://www.microsoft.com/en-us/research/blog/splitwise-improves-gpu-usage-by-splitting-llm-inference-phases/
![image](https://github.com/vllm-project/vllm/assets/58217233/7835c241-f22c-4ffc-a510-1238f4a5d770)

So how to use it in vLLM? I could not find keyword about ”Splitwise“.

**Comment by monuminu** [comment]
same here

**Comment by Alec-Lin** [comment]
@monuminu From your homepage, it appears that you work at Microsoft. Don’t you know where this part of the code can be obtained?😂

**Comment by monuminu** [comment]
Let me get the info :)

**Comment by Alec-Lin** [comment]
@monuminu Ok, please keep me posted if there are any updates.

**Comment by monuminu** [comment]
Code will be released in some days

**Comment by Alec-Lin** [comment]
Thank you, I am looking forward to the day when the code is available.

**Comment by kd303** [comment]
As per the [blog](https://www.microsoft.com/en-us/research/blog/splitwise-improves-gpu-usage-by-splitting-llm-inference-phases/), this seems implemented or part of vLLM

> Our approach is now part of [vLLM(opens in new tab)](https://github.com/vllm-project/vllm) and can also be implemented with other frameworks.

**Comment by Alec-Lin** [comment]
@kd303 I have read this blog yet. But do you know how to use it in vllm? I can not find any keyword in vllm code.

**Comment by aashaka** [comment]
Thanks for the interest in Splitwise code. We have opened https://github.com/vllm-project/vllm/issues/2472 to track the open sourcing of our internal prototype.

**Comment by hmellor** [comment]
https://github.com/vllm-project/vllm/pull/2809
