### ISSUE TITLE
Mixtral-8x7B-Instruct-v0.1  Response content was truncated

### ISSUE THREAD

**Issue by ludovicmarecaux** [vllm-project/vllm#2376]
Hi,
I try to query in french but query get a truncated response. I try max_tokens=-1 in HuggingFaceHub(repo=...) or summary_chain.run(...) but it didn't work, any idea?

`from langchain.chains.summarize import load_summarize_chain`
`from langchain.text_splitter import RecursiveCharacterTextSplitter`

`text = 'travail.txt'`
`with open(text, 'r') as file:`
 `  essay = file.read()`
`from dotenv import load_dotenv`
`load_dotenv()`
`from langchain.llms import HuggingFaceHub`
`llm = HuggingFaceHub(repo_id="mistralai/Mixtral-8x7B-Instruct-v0.1", model_kwargs={"temperature":0.1})`
`text_splitter = RecursiveCharacterTextSplitter(separators=['\n\n', '\n', '(?=>. )', ' ', ''],chunk_size=3000,chunk_overlap=500)`
`docs = text_splitter.create_documents([essay])`
`from langchain.prompts import PromptTemplate`
`map_prompt = """
    Ecrit un résumé précis en francais en 1000 mots de :
    "{text}"
    Résumé précis:
     """`
`map_prompt_template = PromptTemplate(template=map_prompt, input_variables=["text"])`
`combine_prompt = """
 Ecrit un résumé précis en 200 mots en francais de :
 ```{text}```
 Résumé par points clés:
"""`
`combine_prompt_template = PromptTemplate(template=combine_prompt, input_variables=["text"])`
`summary_chain = load_summarize_chain(llm=llm, chain_type='map_reduce',                             map_prompt=map_prompt_template, combine_prompt=combine_prompt_template,  verbose=True)`
`output = summary_chain.run(input_documents=docs, max_tokens=-1)`
`print(output)`

answer (truncated):

    ```
Giuseppe Rensi, philosophe italien, a écrit en 1923 un essai intitulé "Contre le travail" dans lequel il critique la morale de la société capitaliste qui insiste sur une conception du travail comme phénomène éthico-religieux de grande importance.
    Selon Rensi, le travail est une activité aliénante et désagréable qui est souvent

```

**Comment by clemens-pala** [comment]
Same problem in German language.

**Comment by lhteillet** [comment]
Same problem !  And adding max_new_tokens = 2000 (for instance) doesn't change anything.

**Comment by DarkLight1337** [comment]
Please refer to #2464 for the solution.
