### ISSUE TITLE
Understanding about LLM class from vllm

### ISSUE THREAD

**Issue by VpkPrasanna** [vllm-project/vllm#2380]
is LLM class from vllm is asynchronous by nature ?
why am i asking this from the [slides](https://docs.google.com/presentation/d/1QL-XPFXiFpDBh86DbEegFXBXFXjix4v032GhShbKf3s/edit#slide=id.g24ad94a0065_0_84) on the first meetup  it has mentioned that llm is synchronous rather api_server and openai_server are asynchronous ?

if that is true ,how to call the llm model asynchronously ?

correct me if i am wrong !
TIA

**Comment by simon-mo** [comment]
You can use AsyncLLMEngine to call it asynchronously.
