### ISSUE TITLE
CUDA OOM for Mixtral 8x7B AWQ Tensor Parallelism 2

### ISSUE THREAD

**Issue by chiragjn** [vllm-project/vllm#2382]
I am trying to run TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ with 2 x A10 GPUs

```
docker run --shm-size 10gb -it --rm --gpus all -v /data/:/data/ vllm/vllm-openai:v0.2.7 --model  TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ --quantization awq  --dtype auto --enforce-eager --disable-log-requests --tensor-parallel-size 2 --download-dir /data/
```

and while theoretically, it should fit it runs into CUDA OOM

I already looked at this: https://github.com/vllm-project/vllm/issues/2312

Interestingly, if I try it on 2 x A100 80GB but with `--gpu-memory-utilization 0.5`, it fits fine and settles to

```
# GPU blocks: 6487, # CPU blocks: 4096
```

```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     86918      C   python3                         20238MiB |
|    1   N/A  N/A     89935      C   ray::RayWorkerVllm              20238MiB |
+-----------------------------------------------------------------------------+
```

It should be able to run fine with 2 x A10 GB too.

But even on 2 x A100 80 GB it cannot load with `--gpu-memory-utilization 0.3` or `--gpu-memory-utilization 0.4`
```
File "/workspace/vllm/engine/llm_engine.py", line 114, in __init__
    self._init_cache()
  File "/workspace/vllm/engine/llm_engine.py", line 279, in _init_cache
    raise ValueError("No available memory for the cache blocks. "
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
```

Maybe only the cache block calculation is incorrect?

**Comment by joazoa** [comment]
I can't run the mixtral unquantised on 2x 48GB cards, even with small --max-model-len. Could this be related ?

**Comment by Ashley0703** [comment]
Maybe you can try to increase the `gpu-memory-utilization` to 0.9 or 1 to see if it works.

**Comment by PhaneendraGunda** [comment]
even I got the same problem. enable the flag (--enforce-eager) to fix the issue, but it will degrade the performance compared to cuda graphs. 

I am planning raise new issue on the same.
