### ISSUE TITLE
getting error RuntimeError: unable to mmap 18329065000 bytes from file </home/.cache/huggingface/hub/models--TheBloke--CodeLlama-34B-Instruct-GPTQ/snapshots/0a2785d47fb7330388e0487e0526bbc53d87c156/model.safetensors>: Cannot allocate memory (12) 

### ISSUE THREAD

**Issue by Wizmak9** [vllm-project/vllm#2391]
i am getting error RuntimeError: unable to mmap 18329065000 bytes from file </home/.cache/huggingface/hub/models--TheBloke--CodeLlama-34B-Instruct-GPTQ/snapshots/0a2785d47fb7330388e0487e0526bbc53d87c156/model.safetensors>: Cannot allocate memory (12) 

When ran 
python3 -m vllm.entrypoints.openai.api_server --model TheBloke/CodeLlama-34B-Instruct-GPTQ --quantization gptq --gpu-memory-utilization 1 --enforce-eager

Can anyone please help?

**Comment by Nova-Mok** [comment]
it was due to a lack of CPU cores, increase your CPU cores, and it should work fine. 🙂
