### ISSUE TITLE
batching and streaming

### ISSUE THREAD

**Issue by andrey-genpracc** [vllm-project/vllm#2396]
Hi!
If i correctly understood code . Any type of entrypoints api with stream doesn't support batching . But LLMEngine has step() method for processing batch of requests and i can implement streaming with batch using step() or  there any pitfalls here? For example how handle these multiple response streams

**Comment by xinzaifeixiang1992** [comment]
I have the same question, and strongly expecting someone can help me.

**Comment by andrey-genpracc** [comment]
> I have the same question, and strongly expecting someone can help me.

u can use engine.step() method to synchronous executing batch of requests but probably without streaming
