### ISSUE TITLE
Need more metrics: Average First Token Latency

### ISSUE THREAD

**Issue by zhaoyang-star** [vllm-project/vllm#2399]
@simon-mo  I found we could get more metrics from the `/metrics` endpoint. Average First Token Latency is an important metric on server. So Could the `/metrics` endpoint support Average First Token Latency?

**Comment by simon-mo** [comment]
We can do a histogram so you get median and percentiles. Average without a time bound is not useful for observability.

**Comment by zhaoyang-star** [comment]
> istogram so you get median and percentile

Yes. It is better to use median and percentiles based on a histogram. Will you consider to add this feature?

**Comment by simon-mo** [comment]
see #2316

**Comment by simon-mo** [comment]
`histogram_time_to_first_token` has been added by @robertgshaw2-neuralmagic
