### ISSUE TITLE
Yi-34B-200K have empty output under default config (max_position_embedding=20000)

### ISSUE THREAD

**Issue by CaesarWWK** [vllm-project/vllm#2402]
In Samsum benchmark, the Yi-34B-200K with max_position_embedding=20000 only output empty token (eos token) or 2-3 "\n" even when the context length is really small (around 1k). 

However, if I change the max_position_embedding from default to 32000 in model's config.json, the model output the summarization correctly.

There is definitely something wrong, the setting of max_position_embedding should not effect the performance of short-context samples greatly.

**Comment by Time-Limit** [comment]
@CaesarWWK Hello, did you slove this problem?

**Comment by CaesarWWK** [comment]
> @CaesarWWK Hello, did you slove this problem?

Nope. Recently I'm focusing on DPO,  I did not use vllm since then.
