### ISSUE TITLE
Openai接口能否添加主流大模型的chat template

### ISSUE THREAD

**Issue by mini-tiger** [vllm-project/vllm#2403]
Chatglm 百川等常见模型，以openai方式启动需要写jinja模板chat-template，是否可以自动适配，或者指定模型类型

**Comment by QwertyJack** [comment]
百川就没有chat_template，你可以联系百川团队。

**Comment by simon-mo** [comment]
见#2390

**Comment by simon-mo** [comment]
Contribution welcomed to automatically load the template given model type.

**Comment by nullxjx** [comment]
同问，有没有starchat的chat template jinja文件
