### ISSUE TITLE
out of memory running mixtral gptq model in vllm 0.2.7

### ISSUE THREAD

**Issue by arkohut** [vllm-project/vllm#2413]
https://github.com/vllm-project/vllm/assets/39525455/c6787334-8a22-4dd4-838a-9fff1a1e0a38

The model downloaded from https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ and it works well in vllm 0.2.6 but run out of memory using 0.2.7.

**Comment by matankley** [comment]
Thanks for the detailed video. Same thong here. Can't upgrade vllm due to this error

**Comment by chu-tianxiang** [comment]
v0.2.7 enables CUDA graph for GPTQ by default which leads to increased memory usage. This rise in memory consumption can be particularly pronounced for Mixtral, given that MOE has larger activation sizes.  Could you please try setting `enforce_eager =True` or reduce `gpu_memory_utilization`?

**Comment by matankley** [comment]
@chu-tianxiang `enforce_eager=True` fixed the issue.

**Comment by francescov1** [comment]
Is there a way to fix this if using the vllm docker image? I dont see an enforce_eager flag

**Comment by Abhishekghosh1998** [comment]
@arkohut Could you please let me know the memory utilization statistics of running the model on your A40 GPU backed with 48 GiBs of  GPU memory with `enforce_eager=True`?

vLLM 0.2.7 has CUDA Graphs enabled by default (i.e., `enforce_eager=False` by default), and using CUDA Graph would add 1 -3 GiBs of memory overhead.
Just wanted to confirm if your model (with `enforce_eager=True`) does not leave memory for CUDA Graphs to work. (less than 3 GiBs are left on the device)
