### ISSUE TITLE
top_k = 50 will make vllm prediction align with transformers

### ISSUE THREAD

**Issue by sfyumi** [vllm-project/vllm#2415]
There is a lot of issues about the different results between vllm and transformers. Some of them is caused by vllm sample implementation like repetition, or caused by kernel implementation bug. These bugs are fixed in the latest vllm release.

When I test the latest version of vllm, I still get different results from transformers. After some investigation, I find that the default value of top_k is different between vllm and transformers. **Transformer's default top_k is 50, vllm's default top_k is -1**.

I test vllm with top_k = 50, the result is same with transformers.

Hope this will help.

**Comment by hmellor** [comment]
@simon-mo what do you think about the suggested change?

**Comment by hmellor** [comment]
vLLM is using the default OpenAI values of parameters rather than the default transformers values.
