### ISSUE TITLE
chat template jinja file for starchat model?

### ISSUE THREAD

**Issue by nullxjx** [vllm-project/vllm#2420]
I want to run [starchat](https://huggingface.co/HuggingFaceH4/starchat-beta) model using vLLM, what is the chat template jinja file for starchat model? Can anyone provide me with that?

**Comment by nullxjx** [comment]
"{% for message in messages %}{{ '<|' + message['role'] + '|>' + '\n' + message['content'] + '<|end|>' + '\n'}}{% endfor %}{{ '<|assistant|>' + '\n' }}"

is this ok?

**Comment by s-natsubori** [comment]
my template
(remove spaces)
```
{% for message in messages %}
    {% if message['role'] == 'user' %}
        {{ '<|user|>\n' + message['content'] + '<|end|>\n' }}
    {% elif message['role'] == 'system' %}
        {{ '<|system|>\n' + message['content'] + '<|end|>\n' }}
    {% elif message['role'] == 'assistant' %}
        {{ '<|assistant|>\n' + message['content'] + '<|end|>\n' }}
    {% endif %}
{% endfor %}
{% if add_generation_prompt %}
  {{ '<|assistant|>\n' }}
{% endif %}
```

**Comment by nullxjx** [comment]
> my template (remove spaces)
> 
> ```
> {% for message in messages %}
>     {% if message['role'] == 'user' %}
>         {{ '<|user|>\n' + message['content'] + '<|end|>\n' }}
>     {% elif message['role'] == 'system' %}
>         {{ '<|system|>\n' + message['content'] + '<|end|>\n' }}
>     {% elif message['role'] == 'assistant' %}
>         {{ '<|assistant|>\n' + message['content'] + '<|end|>\n' }}
>     {% endif %}
> {% endfor %}
> {% if add_generation_prompt %}
>   {{ '<|assistant|>\n' }}
> {% endif %}
> ```

I use yours for testing, but the result is nonsense, see the result below
<img width="1705" alt="image" src="https://github.com/vllm-project/vllm/assets/21221616/a33acd1c-0d93-4ec6-ae92-253d7eb99289">

but the prompt seems to be ok
```txt
<|system|>\nYou are a helpful assistant.<|end|>\n<|user|>\nHow to use nginx for load balancing?<|end|>\n<|assistant|>\n
```

Did you test it, is the result ok?

**Comment by s-natsubori** [comment]
my code output
```
[2024-01-12 04:23:46,683] [DEBU] /usr/local/api/chat_models/chat_local.py(140):_request2prompt: <|user|>
How to use nginx for load balancing?<|end|>
<|assistant|>

INFO 01-12 04:23:46 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 01-12 04:23:51 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
[2024-01-12 04:23:52,640] [DEBU] /usr/local/api/chat_models/chat_local_vllm.py(183):agenerate: Nginx can be used as a load balancer in front of a set of web servers. To configure Nginx as a load balancer, follow these steps:

1. Install and configure Nginx as a reverse proxy server. In your Nginx configuration file (usually located at /etc/nginx/nginx.conf), add an " upstream " block that defines the set of web servers that will be load balanced. For example:

```
http {
    ...

    upstream backend_servers {
        server 192.168.0.100:80;
        server 192.168.0.101:80;
        server 192.168.0.102:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}
```

2. Restart Nginx to apply the configuration changes.

3. Test the configuration by visiting the server's IP address or hostname in a web browser, and verifying that it serves content from one of the backend servers defined in the upstream block .
```

**Comment by nullxjx** [comment]
> my code output
> 
> > [2024-01-12 04:23:46,683] [DEBU] /usr/local/api/chat_models/chat_local.py(140):_request2prompt: <|user|>
> > How to use nginx for load balancing?<|end|>
> > <|assistant|>
> > INFO 01-12 04:23:46 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
> > INFO 01-12 04:23:51 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
> > [2024-01-12 04:23:52,640] [DEBU] /usr/local/api/chat_models/chat_local_vllm.py(183):agenerate: Nginx can be used as a load balancer in front of a set of web servers. To configure Nginx as a load balancer, follow these steps:
> > 
> > 1. Install and configure Nginx as a reverse proxy server. In your Nginx configuration file (usually located at /etc/nginx/nginx.conf), add an " upstream " block that defines the set of web servers that will be load balanced. For example:
> > 
> > ```
> > http {
> >     ...
> > 
> >     upstream backend_servers {
> >         server 192.168.0.100:80;
> >         server 192.168.0.101:80;
> >         server 192.168.0.102:80;
> >     }
> > 
> >     server {
> >         listen 80;
> > 
> >         location / {
> >             proxy_pass http://backend_servers;
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Restart Nginx to apply the configuration changes.
> > 3. Test the configuration by visiting the server's IP address or hostname in a web browser, and verifying that it serves content from one of the backend servers defined in the upstream block .

Can you provide the vllm version you are using and the prompt content output in the vllm log? Currently I'm using the vllm/vllm-openai:v0.2.7 image to run vllm.

my client curl command is
```bash
(base)  ~/ curl http://localhost:8008/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "starchat",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "How to use nginx for load balancing?"}
    ],
    "max_tokens": 64,
    "stop": ["<|end|>"],
    "temperature": 0.2,
    "skip_special_tokens": true,
    "stream": false
  }'
{"id":"cmpl-5d1142cf13ce4c95ae8f640034000f42","object":"chat.completion","created":5172707,"model":"starchat","choices":[{"index":0,"message":{"role":"assistant","content":"\n¿\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n¿\n\n"},"finish_reason":"length"}],"usage":{"prompt_tokens":25,"total_tokens":89,"completion_tokens":64}}
```

as you can see, the output is nonsense.

the vllm logs are as follows:
```bash
INFO:     169.254.32.1:39924 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 01-22 03:16:05 async_llm_engine.py:383] Received request cmpl-5d1142cf13ce4c95ae8f640034000f42: prompt: '<|system|>\nYou are a helpful assistant.<|end|>\n<|user|>\nHow to use nginx for load balancing?<|end|>\n<|assistant|>\n', sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.2, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|end|>'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=64, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [49152, 203, 4282, 884, 312, 17247, 47330, 32, 49155, 203, 49153, 203, 8257, 372, 793, 21505, 436, 2454, 14699, 18522, 49, 49155, 203, 49154, 203].
INFO 01-22 03:16:06 llm_engine.py:706] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 01-22 03:16:08 async_llm_engine.py:111] Finished request cmpl-5d1142cf13ce4c95ae8f640034000f42.
INFO:     169.254.32.1:41162 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

Thank you~

**Comment by s-natsubori** [comment]
maybe, this...

[GPTBigCodeForCausalLM, TP >= 2, output is bloken\. Is this BUG? · Issue \#2417 · vllm\-project/vllm](https://github.com/vllm-project/vllm/issues/2417)

Try
- set tensor_parallel_size=1
- or build vllm in Dockerfile
```
RUN git clone https://github.com/vllm-project/vllm
WORKDIR /usr/local/setup/vllm
RUN pip install -e .
```

**Comment by nullxjx** [comment]
I'm sure it's indeed the problem you mentioned. I tested using the main branch of vllm, the result the ok when using 2 gpu, the vllm/vllm-openai:v0.2.7 image has bugs on tensor-parallel. Thank you for reply~

**Comment by nullxjx** [comment]
> maybe, this...
> 
> [GPTBigCodeForCausalLM, TP >= 2, output is bloken. Is this BUG? · Issue #2417 · vllm-project/vllm](https://github.com/vllm-project/vllm/issues/2417)
> 
> Try
> 
> * set tensor_parallel_size=1
> * or build latest vllm in Dockerfile
> 
> ```
> RUN git clone https://github.com/vllm-project/vllm
> WORKDIR /usr/local/setup/vllm
> RUN pip install -e .
> ```

I'm sure it's indeed the problem you mentioned. I tested using the main branch of vllm, the result the ok when using 2 gpu, the vllm/vllm-openai:v0.2.7 image has bugs on tensor-parallel. Thank you for reply~
