### ISSUE TITLE
Is vllm continuous batching by default turned on?

### ISSUE THREAD

**Issue by Slyne** [vllm-project/vllm#2423]
Hi,
I'm quite newbee to vllm. I've checked the engine arguments [here](https://github.com/vllm-project/vllm/blob/4b61c6b669e368c6850531815940d9a542b9f223/vllm/engine/arg_utils.py#L11).
Not sure if I'm testing correctly.
I got the below testing result (benchmark_serving.py) and am not quite sure if the continuous batching is working:

|Num GPU | Requet Rate | Model | Throughput | Avg Latency(s) | Latency Per token (s) | Latency Per output token (s)| Total Time(s)|
|------------|--------------|---------|--------------|------------------|------------------------|-------------------------------|---------------|
|1 | 10 | 7B-float16-TP1 | 5.91 | 37.62 | 0.22 | 2.57 | 169.19|
|1 | 6 | 7B-float16-TP1 | 5.76 | 6.13 | 0.04 | 0.32 | 173.7|
|1 | 5 | 7B-float16-TP1 | 4.93 | 3.1 | 0.02 | 0.15 | 202.93|
|1 | 2 | 7B-float16-TP1 | 1.99 | 1.18 | 0.01 | 0.06 | 503.03|
|2 | 10 | 7B-float16-TP2 | 6.37 | 42.84 | 0.25 | 2.62 | 157.1|
|2 | 6 | 7B-float16-TP2 | 5.9 | 7.57 | 0.04 | 0.39 | 169.47|
|2 | 5 | 7B-float16-TP2 | 4.94 | 2.82 | 0.01 | 0.15 | 202.49|
|1 | 6 | 7B-gptq4bit-TP1 | 5.29 | 20.73 | 0.12 | 1.15 | 189.09|
|1 | 5 | 7B-gptq4bit-TP1 | 4.94 | 6.26 | 0.03 | 0.31 | 202.38|
|2 | 5 | 13B-float16-TP2 | 3.74 | 41.02 | 0.24 | 2.67 | 267.06|
|2 | 3 | 13B-float16-TP2 | 2.97 | 4.42 | 0.02 | 0.23 | 337.02|
|4 | 5 | 13B-float16-TP4 | 2.98 | 37.05 | 0.22 | 1.86 | 221.77|
|4 | 4 | 13B-float16-TP4 | 3.95 | 6.17 | 0.03 | 0.33 | 253.1|
|2 | 4 | 13B-gptq4bit-TP2 | 3.95 | 8.99 | 0.05 | 0.48 | 252.91|
|4 | 4 | 13B-gptq4bit-TP4 | 3.95 | 9.24 | 0.05 | 0.49 | 252.96|

**Comment by AlpinDale** [comment]
Continuous batching is handled by the scheduler, which automatically handles the batching of requests based on the current load and the configured maximum number of batched tokens. It should continuously groups incoming requests.

**Comment by Slyne** [comment]
> Continuous batching is handled by the scheduler, which automatically handles the batching of requests based on the current load and the configured maximum number of batched tokens. It should continuously groups incoming requests.

Got it. Perhaps I should adjust maximum number of batched tokens.

**Comment by ywang96** [comment]
Closing as @AlpinDale provided a good answer!
