### ISSUE TITLE
examples/offline_inference.py。推理baichuan-13b，1*A100（80G），会OOM？

### ISSUE THREAD

**Issue by lvjianxin** [vllm-project/vllm#2430]
采用代码examples/offline_inference.py，vllm也这么吃显存吗？

**Comment by seanxcwang** [comment]
控制下gpu memory usage看下

**Comment by qiezikuangge** [comment]
vllm会将载入模型后剩余显存全拿来分配kv cache block，默认的gpu memory usage为0.9，越大就分配的越多

**Comment by tongjingqi** [comment]
https://github.com/vllm-project/vllm/blob/0e163fce18594c7e29dc5a143dd6b33d213fcbf3/vllm/entrypoints/llm.py#L82
把链接中文件init的函数默认参数gpu_memory_utilization: float = 0.9, 
比如改成0.5，相当于一开始占用你90%的显存，现在就只占用50%的显存了
