### ISSUE TITLE
cuda11.8 use gptq for Qwen

### ISSUE THREAD

**Issue by skyantao** [vllm-project/vllm#2435]
Hi , my env is cuda 118 , and my model is qwen  int4.
my vllm  install   https://github.com/vllm-project/vllm/releases/download/v0.2.7/vllm-0.2.7+cu118-cp310-cp310-manylinux1_x86_64.whl

my code is :
model_path = "/mnt/e/weight/MODELSCOPE/qwen/gptq0113"  llm = LLM(model=model_path, tensor_parallel_size=1,trust_remote_code=True) sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

prompts = [query] 
outputs = llm.generate(prompts, sampling_params) 
response = outputs[0].outputs[0].text

but the result is error!!!
for example: 
input is :hello
output is :username_0: Hello again! I have a problem using your API. I

input:tell me all about bejing 
output:The answer to the question is not provided in the given text. Therefore, I

can you help me ? thanks

**Comment by skyantao** [comment]
![image](https://github.com/vllm-project/vllm/assets/6165974/0d924f70-3bd7-49e7-bc15-5e2fd94ccc4d)


WARNING 01-13 22:06:32 config.py:175] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 01-13 22:06:32 llm_engine.py:70] Initializing an LLM engine with config: model='/mnt/e/weight/MODELSCOPE/qwen/gptq0113', tokenizer='/mnt/e/weight/MODELSCOPE/qwen/gptq0113', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=gptq, enforce_eager=False, seed=0)
WARNING 01-13 22:06:33 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 01-13 22:08:35 llm_engine.py:275] # GPU blocks: 1670, # CPU blocks: 512
WARNING 01-13 22:08:35 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 01-13 22:08:35 model_runner.py:501] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-13 22:08:35 model_runner.py:505] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
INFO 01-13 22:08:43 model_runner.py:547] Graph capturing finished in 8 secs.
Running on local URL:  http://0.0.0.0:7861

To create a public link, set `share=True` in `launch()`.
Processed prompts: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.38it/s]

**Comment by skyantao** [comment]
find a sample issuse. 
use  issuse   https://github.com/vllm-project/vllm/issues/901   to  resolve the problem

**Comment by dliting** [comment]
> Hi , my env is cuda 118 , and my model is qwen int4. my vllm install https://github.com/vllm-project/vllm/releases/download/v0.2.7/vllm-0.2.7+cu118-cp310-cp310-manylinux1_x86_64.whl
> 
> my code is : model_path = "/mnt/e/weight/MODELSCOPE/qwen/gptq0113"  llm = LLM(model=model_path, tensor_parallel_size=1,trust_remote_code=True) sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
> 
> prompts = [query]  outputs = llm.generate(prompts, sampling_params)  response = outputs[0].outputs[0].text
> 
> but the result is error!!! for example: input is :hello output is :username_0: Hello again! I have a problem using your API. I
> 
> input:tell me all about bejing output:The answer to the question is not provided in the given text. Therefore, I
> 
> can you help me ? thanks

same question
