### ISSUE TITLE
Is it possible for the asynchronous generate method to support only passing the prompt_token_ids parameter without requiring the prompt parameter? This would be advantageous for customizing the input of tokens.

### ISSUE THREAD

**Issue by shell-nlp** [vllm-project/vllm#2436]
Is it possible for the asynchronous generate method to support only passing the prompt_token_ids parameter without requiring the prompt parameter? This would be advantageous for customizing the input of tokens.

We have observed that using the tokenizer.encode method directly to generate tokens can lead to certain issues. Customizing the input by passing prompt_token_ids can resolve these problems.

https://github.com/vllm-project/vllm/blob/35c4bc20d9d454f58506b561b6770d3ae4752bf9/vllm/engine/async_llm_engine.py#L408C10-L408C10
```
 async def generate(
        self,
        prompt: Optional[str],
        sampling_params: SamplingParams,
        request_id: str,
        prompt_token_ids: Optional[List[int]] = None
    ) -> AsyncI
```terator[RequestOutput]:

**Comment by simon-mo** [comment]
I don't see any major issue with. Contribution welcomed!

**Comment by shell-nlp** [comment]
#2122 

I encountered an issue while testing the ChatGPT-LM3 model. There is a significant discrepancy between the decoding results of VLLM and the implementation by Hugging Face (HF). This discrepancy negatively affects the quality of the generated responses and hampers the normal functioning of the system. Interestingly, regardless of the decoding parameters used, the HF implementation does not exhibit such problems. I fells this issue is a common problem for Chinese language models. However, using custom prompt_token_ids can alleviate this problem.

https://github.com/vllm-project/vllm/issues/2122#issue-2042826543

**Comment by shell-nlp** [comment]
> I encountered an issue while testing the ChatGPT-LM3 model. There is a significant discrepancy between the decoding results of VLLM and the implementation by Hugging Face (HF). This discrepancy negatively affects the quality of the generated responses and hampers the normal functioning of the system. Interestingly, regardless of the decoding parameters used, the HF implementation does not exhibit such problems. I fells this issue is a common problem for Chinese language models. However, using custom prompt_token_ids can alleviate this problem.

#2122 
I encountered an issue while testing the ChatGPT-LM3 model. There is a significant discrepancy between the decoding results of VLLM and the implementation by Hugging Face (HF). This discrepancy negatively affects the quality of the generated responses and hampers the normal functioning of the system. Interestingly, regardless of the decoding parameters used, the HF implementation does not exhibit such problems. I fells this issue is a common problem for Chinese language models. However, using custom prompt_token_ids can alleviate this problem.

**Comment by shell-nlp** [comment]
> I don't see any major issue with. Contribution welcomed!

#2122 

I encountered an issue while testing the ChatGPT-LM3 model. There is a significant discrepancy between the decoding results of VLLM and the implementation by Hugging Face (HF). This discrepancy negatively affects the quality of the generated responses and hampers the normal functioning of the system. Interestingly, regardless of the decoding parameters used, the HF implementation does not exhibit such problems. I fells this issue is a common problem for Chinese language models. However, using custom prompt_token_ids can alleviate this problem.

**Comment by shell-nlp** [comment]
> I don't see any major issue with. Contribution welcomed!我没有看到任何重大问题。欢迎贡献！

vllm : 
prompt: 你是谁            
output:  你有什么目的？我为什么要回答你？
--------------  translate-------------------------
Prompt: who are you? 
output: what is your purpose? Why should I answer you?

**Comment by shell-nlp** [comment]
> I don't see any major issue with. Contribution welcomed!

vllm :
prompt: 你是谁
output: 你有什么目的？我为什么要回答你？
-------------- translate-------------------------
Prompt: who are you?
output: what is your purpose? Why should I answer you?
