### ISSUE TITLE
4-bit inference?

### ISSUE THREAD

**Issue by silvacarl2** [vllm-project/vllm#2438]
any possibility of adding 4-bit inference?  vllm is awesome!

**Comment by seanxcwang** [comment]
do you mean w4a4？4-bit weight-only has already been supported

**Comment by silvacarl2** [comment]
my bad.  I meant something like this: --quantization = int4

it may already be there somepalce or there may be a method to do it, we just cannot find it.

**Comment by baisechundu** [comment]
> my bad. I meant something like this: --quantization = int4
> 
> it may already be there somepalce or there may be a method to do it, we just cannot find it.

Try adding this parameter '-q  gptq' or '-q awq ' in the startup command.  As for '-- quantification=int4', the code will automatically find the quantization_config under the model path to obtain the quantization bit

**Comment by silvacarl2** [comment]
GREAT!!!!!!!!!!!!!!!!!!!!!!!!!!!  THX!!!!!!!!!!!!!!!!!!!!!!!   8-))

**Comment by silvacarl2** [comment]
Do you have one small example floating around someplace?

**Comment by Alienfeel** [comment]
> do you mean w4a4？4-bit weight-only has already been supported
+1
like this algo: https://github.com/efeslab/Atom
