### ISSUE TITLE
API Server batch request issue

### ISSUE THREAD

**Issue by nlpkiddo-2001** [vllm-project/vllm#2441]
Hi, I am new to vLLM usage and i want to load and serve mistral 7b model using vLLM. Here is my brief understanding about vLLM. 
1. LLM Engine => could handle offline batching (i.e list of prompts)
2. Async LLM Engine => wrapped with LLM Engine and could server async calls individually but only through online serving (api_server.py)

Now I need to process batch calls (i..e list of prompts)  through API server batch request.
prompts = ["Give me a haiku poem"] * 10
How can I achieve this through api request. Kindly help me with this. Thanks in advance.

**Comment by nlpkiddo-2001** [comment]
Any comments on this???

**Comment by HuichiZhou** [comment]
+1

**Comment by whitepapercg** [comment]
+

**Comment by simon-mo** [comment]
PR here: https://github.com/vllm-project/vllm/pull/2529

**Comment by nlpkiddo-2001** [comment]
Hey @simon-mo , thanks for the update
but what if i need to do this API batch request via entrypopints.api_server.py

**Comment by simon-mo** [comment]
entrypopints.api_server is not going to receive much attention as compare to the OpenAI server, which have strictly more features. We do not recommend using the entrypopints.api_server as your production server.

**Comment by nlpkiddo-2001** [comment]
thanks for the update @simon-mo

**Comment by certara-pchunduru** [comment]
What are the alternatives to using api_server for production server?

**Comment by pchunduru10** [comment]
What are the alternative to using api_server for production ?

**Comment by simon-mo** [comment]
OpenAI compatible server https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-server
