### ISSUE TITLE
The Second vLLM SF Bay Area Meetup (Jan 31st 5-7:30pm)

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#2445]
## Welcome to the second vLLM Meetup @ The AI Alliance!

​​We are absolutely thrilled to invite you to the second vLLM meetup. This event is for the growing community of vLLM users and developers to connect, share, and learn together. The vLLM team will share the recent updates on the project. We will also have vLLM collaborators from IBM coming up to the stage to discuss their insights on LLM optimizations.

## (Tentative) ​Agenda

​**5:00pm - 6:00pm:** Doors open and check-in. Mingles and discussions. Food and refreshments will be available.

​**6:00pm - 6:40pm:** Talks
* ​Introduction: AI Alliance - Alexy Khrabrov, IBM Research
* vLLM Project Update - Zhuohan Li, Woosuk Kwon, UC Berkeley
* torch.compile and vLLM - Nick Hill, IBM Research

​​**6:40pm - 7:30pm:** Q&A and Social Hour - This is your chance to mingle, share your experiences, ask questions, and get to know the vLLM team on a personal level.

### Note from the vLLM Team:

​​We, the vLLM team, are incredibly excited to meet each and every one of you. This meetup is not just about sharing updates but also about celebrating the community that makes vLLM what it is today. Let's come together, share our stories, and envision the future of vLLM.

## ​​Special Thanks:

​​A heartfelt thank you to IBM for generously providing us with the venue for this event. Their continuous support has been invaluable to the vLLM's open-source community.

**Comment by vecorro** [comment]
Hi, are there any public slides from this event? I'd be great to take a look if possible.

Thanks!

**Comment by LiuXiaoxuanPKU** [comment]
> Hi, are there any public slides from this event? I'd be great to take a look if possible.
> 
> Thanks!

Yes, please check it [here](https://docs.google.com/presentation/d/12mI2sKABnUw5RBWXDYY-HtHth4iMSNcEoQ10jDQbxgA/edit?usp=sharing)!

**Comment by vecorro** [comment]
Many thanks @LiuXiaoxuanPKU!
