### ISSUE TITLE
Can Falcon-40B run at single A100 80gb? 

### ISSUE THREAD

**Issue by chenglimin** [vllm-project/vllm#2447]
Can Falcon-40B run at single A100 80gb?  I encountered error "ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine." Did I set something wrong?
I run with the following command "python benchmark_throughput.py --input-len=1 --output-len=128 --model=/models/falcon-40B/ --tokenizer=/models/falcon-40B/ --n 1 --num-prompts=1 --enforce-eager"

**Comment by ymwangg** [comment]
Yes, but you need to quantize the model. So try AWQ or GPTQ? Fp16 40B model takes ~80GB memory.

**Comment by chenglimin** [comment]
> Yes, but you need to quantize the model. So try AWQ or GPTQ? Fp16 40B model takes ~80GB memory.

If I directly use the Fp16 Falcon-40B model, vLLM will can not support it? I have already meet the problem of "GPU block:0", in fact, there are no other processes running on GPU at all.

**Comment by ymwangg** [comment]
40B fp16 model takes ~80GB memory already, so you need to either quantize it or use tensor parallelism.
