### ISSUE TITLE
Mixtral issue

### ISSUE THREAD

**Issue by UncleFB** [vllm-project/vllm#2448]
vllm version 0.2.7
python -u -m vllm.entrypoints.openai.api_server \
       --host 0.0.0.0 \
       --port 8008 \
       --model /data2/public_file2/LLM_model/Mixtral-8x7B-Instruct-v0.1 \
       --tensor-parallel-size 8 \
       --load-format pt

ValueError: Currently, the 'pt' format is not supported for Mixtral. Please use the 'safetensors' format instead.

**Comment by esmeetu** [comment]
hi, @UncleFB. Currently vLLM only support .bin and .safetensors format Mixtral model. Please download the latest model from huggingface.
