### ISSUE TITLE
no longer support encoder(prompt) + decoder computation(like ORCA)?

### ISSUE THREAD

**Issue by 92hyungjun** [vllm-project/vllm#2450]
Hi vllm team.

In v0.1.0, There is an implementation of the functionality that when a new prompt comes during decoding, operations except attention are processed in a same batch.
https://github.com/vllm-project/vllm/blob/67d96c29fba9b72cb4c4edbc26211c208a00ebdd/vllm/model_executor/layers/attention.py#L121

in v0.2.7, It seems like the prompt and decoing computation are separated.
https://github.com/vllm-project/vllm/blob/2e0b6e775756345aa1d39f772c186e00f8c29e92/vllm/model_executor/layers/attention.py#L101

Is this feature no longer supported?
Thanks!

**Comment by SingJumpRapp** [comment]
I have the same query, it means I need to pause my generation when I get a new request. The longer the prompt, the longer the pause time.
