### ISSUE TITLE
int8 supported?

### ISSUE THREAD

**Issue by charliedream1** [vllm-project/vllm#2455]
int8 supported?

**Comment by s-natsubori** [comment]
maybe no.

supported Quantization
> Quantization: [GPTQ](https://arxiv.org/abs/2210.17323), [AWQ](https://arxiv.org/abs/2306.00978), [SqueezeLLM](https://arxiv.org/abs/2306.07629)

these use int4

**Comment by charliedream1** [comment]
Will in8 support in the future?



---Original---
From: ***@***.***&gt;
Date: Thu, Jan 18, 2024 10:23 AM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] int8 supported? (Issue #2455)




 
maybe no.
 
supported Quantization
  
Quantization: GPTQ, AWQ, SqueezeLLM
  
these use int4

**Comment by wuchaooooo** [comment]
mark

**Comment by leocnj** [comment]
This PR #1508 shows how to use smoothquant INT8

**Comment by charliedream1** [comment]
Thx



---Original---
From: "Lei ***@***.***&gt;
Date: Sat, Jan 20, 2024 05:21 AM
To: ***@***.***&gt;;
Cc: "Optimus ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] int8 supported? (Issue #2455)




 
This PR #1508 shows how to use smoothquant INT8
