### ISSUE TITLE
Why vllm does not support Chinese input

### ISSUE THREAD

**Issue by 929359291** [vllm-project/vllm#246]
There is a decode error in Chinese input，is token.decode

**Comment by 929359291** [comment]
> 
thinks, i try  again

**Comment by 929359291** [comment]
> If you use chinese-alpaca/llama, remember their tokenizers are different with the original ones. However in vllm/engine/tokenizer_utils.py it force to use the original llama tokenizer hf-internal-testing/llama-tokenizer. this produce the error. They should allow you to pass a use_fast=False to avoid this behavior, but currently it's not possible. Before they fix this issue, as a temporary workaround, you can simply replace the tokenizer by llm.llm_engine.tokenizer = AutoTokenizer.from_pretrained('YOUR CHINESE ALPACA/LLAMA TOKENIZER', use_fast=False)

thinks, i try again

**Comment by luoyangen** [comment]
> > If you use chinese-alpaca/llama, remember their tokenizers are different with the original ones. However in vllm/engine/tokenizer_utils.py it force to use the original llama tokenizer hf-internal-testing/llama-tokenizer. this produce the error. They should allow you to pass a use_fast=False to avoid this behavior, but currently it's not possible. Before they fix this issue, as a temporary workaround, you can simply replace the tokenizer by llm.llm_engine.tokenizer = AutoTokenizer.from_pretrained('YOUR CHINESE ALPACA/LLAMA TOKENIZER', use_fast=False)
> 
> thinks, i try again

Hi, Did you successed by passing use_fast=False?
I tried but get "RuntimeError: CUDA error: device-side assert triggered".

**Comment by shifan3** [comment]
> 

don't know how to do that, in the source code use_fast never reach the from_pretrained code

**Comment by shifan3** [comment]
> Hi, Did you successed by passing use_fast=False? I tried but get "RuntimeError: CUDA error: device-side assert triggered".
In current build, use_fast never reach the get_tokenizer code

**Comment by 929359291** [comment]
> > > If you use chinese-alpaca/llama, remember their tokenizers are different with the original ones. However in vllm/engine/tokenizer_utils.py it force to use the original llama tokenizer hf-internal-testing/llama-tokenizer. this produce the error. They should allow you to pass a use_fast=False to avoid this behavior, but currently it's not possible. Before they fix this issue, as a temporary workaround, you can simply replace the tokenizer by llm.llm_engine.tokenizer = AutoTokenizer.from_pretrained('YOUR CHINESE ALPACA/LLAMA TOKENIZER', use_fast=False)
> > 
> > 
> > thinks, i try again
> 
> Hi, Did you successed by passing use_fast=False? I tried but get "RuntimeError: CUDA error: device-side assert triggered".

hi boy, i not try, wait vLLM Development Roadmap #244
