### ISSUE TITLE
Run local llm qwen-72b failed

### ISSUE THREAD

**Issue by thugbobby** [vllm-project/vllm#2460]
When I run local llm qwen-72b-chat, it can`t work normal, it will be stuck like this:
![image](https://github.com/vllm-project/vllm/assets/68416779/dee72595-700a-4085-9a6f-a1527b8f5362)
**Command**
```
python -m vllm.entrypoints.openai.api_server --model /mnt/bynas/llms_store/Qwen-72B-Chat --trust-remote-code --tensor-parallel-size 4 --host 0.0.0.0 --port 5000 \
--served-model-name Qwen/Qwen-72B-Chat --gpu-memory-utilization 0.5
```
**Environment**
4 *  Nvidia A6000 48G
cuda 12.3
python 3.11

**Comment by qiezikuangge** [comment]
Don't see any error information from the picture

**Comment by yuanphoenix** [comment]
Yes,I meet this problem too.

**Comment by yuanphoenix** [comment]
> Don't see any error information from the picture

no error. but do not work。
程序没出错，cpu百分百运行，但是不往下推进。

**Comment by qiezikuangge** [comment]
显存有正确占用吗，模型加载完应该在160G左右，然后会进行预计算达到峰值显存(观察GPU使用率查看是否100%)，可能会OOM

**Comment by YingchaoX** [comment]
显存不够呀，我使用4*A100 80G加 --gpu-memory-utilization 0.5配置显存都不够的，，，
实验了一下，使用--gpu-memory-utilization 0.6 也就是192G显存是可以启动的。。。

可以先试一下[int4版本](https://huggingface.co/Qwen/Qwen-72B-Chat-Int4)，目前vllm支持gptq量化

**Comment by yuanphoenix** [comment]
> 显存不够呀，我使用4*A100 80G加 --gpu-memory-utilization 0.5配置显存都不够的，，， 实验了一下，使用--gpu-memory-utilization 0.6 也就是192G显存是可以启动的。。。
> 
> 可以先试一下[int4版本](https://huggingface.co/Qwen/Qwen-72B-Chat-Int4)，目前vllm支持gptq量化

int4的也这个问题。4张3090，每张卡占用10G 然后就不动了。

vllm的最新版
输入  
```
CUDA_VISIBLE_DEVICES=1,2,4,5   python -m vllm.entrypoints.openai.api_server \
>     --model /data/lilili/Qwen-72B-Chat-Int4  --port 7412    --trust-remote-code  --tensor-parallel-size 4
```
输出,就不动了。
```
INFO 01-18 15:25:36 api_server.py:727] args: Namespace(host=None, port=7412, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, model='/data/lilili/Qwen-72B-Chat-Int4', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 01-18 15:25:36 config.py:175] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2024-01-18 15:25:39,718 INFO worker.py:1724 -- Started a local Ray instance.
INFO 01-18 15:25:40 llm_engine.py:70] Initializing an LLM engine with config: model='/data/lilili/Qwen-72B-Chat-Int4', tokenizer='/data/lilili/Qwen-72B-Chat-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, quantization=gptq, enforce_eager=False, seed=0)
WARNING 01-18 15:25:41 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
```
![image](https://github.com/vllm-project/vllm/assets/32676100/b83bfa4e-3cd2-4cd2-8e10-6f37673ca235)
1，2，4，5卡

**Comment by YingchaoX** [comment]
我用4卡--gpu-memory-utilization 0.3 也就是(4*80*0.3=96G)显存是会报错的
ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (11424). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
还是显存不够的问题。

我这边实验下来--gpu-memory-utilization 0.5 也就是(4*80*0.5=160G)才能正常启动。

你可以用8卡试试😓

**Comment by PeterXiaTian** [comment]
> > 显存不够呀，我使用4*A100 80G加 --gpu-memory-utilization 0.5配置显存都不够的，，， 实验了一下，使用--gpu-memory-utilization 0.6 也就是192G显存是可以启动的。。。
> > 可以先试一下[int4版本](https://huggingface.co/Qwen/Qwen-72B-Chat-Int4)，目前vllm支持gptq量化
> 
> int4的也这个问题。4张3090，每张卡占用10G 然后就不动了。
> 
> vllm的最新版 输入
> 
> ```
> CUDA_VISIBLE_DEVICES=1,2,4,5   python -m vllm.entrypoints.openai.api_server \
> >     --model /data/lilili/Qwen-72B-Chat-Int4  --port 7412    --trust-remote-code  --tensor-parallel-size 4
> ```
> 
> 输出,就不动了。
> 
> ```
> INFO 01-18 15:25:36 api_server.py:727] args: Namespace(host=None, port=7412, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, model='/data/lilili/Qwen-72B-Chat-Int4', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
> WARNING 01-18 15:25:36 config.py:175] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
> 2024-01-18 15:25:39,718 INFO worker.py:1724 -- Started a local Ray instance.
> INFO 01-18 15:25:40 llm_engine.py:70] Initializing an LLM engine with config: model='/data/lilili/Qwen-72B-Chat-Int4', tokenizer='/data/lilili/Qwen-72B-Chat-Int4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, quantization=gptq, enforce_eager=False, seed=0)
> WARNING 01-18 15:25:41 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/32676100/297658297-b83bfa4e-3cd2-4cd2-8e10-6f37673ca235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTU3MDUsIm5iZiI6MTcwNTY1NTQwNSwicGF0aCI6Ii8zMjY3NjEwMC8yOTc2NTgyOTctYjgzYmZhNGUtM2NkMi00Y2QyLThlMTAtNmYzNzY3M2NhMjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA5MTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMDE3NjU5OWE4MzE1YWRmMzI5NmY5NDU3YjU2NTE0ZTcyNmQ5ZGViM2QzZjA2NmU5OGNlYzE0YjQwZmU4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96dSdJrUlbx2dkTBPWWHzPu966iOu3OMsFEFiSIfQjA) 1，2，4，5卡

启动了怎么找不到端口？这是怎么回事

**Comment by qiezikuangge** [comment]
> CUDA_VISIBLE_DEVICES=7 python -m vllm.entrypoints.openai.api_server --model /home/work/chatglm3-6b --port 8989 --trust-remote-code --gpu-memory-utilization 0.98 --tensor-parallel-size=2 --dtype bfloat16 启动后无法访问，找不到端口是怎么回事？？

试试 --host 0.0.0.0

**Comment by ehuaa** [comment]
> When I run local llm qwen-72b-chat, it can`t work normal, it will be stuck like this: ![image](https://private-user-images.githubusercontent.com/68416779/297253066-dee72595-700a-4085-9a6f-a1527b8f5362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzI4MzQsIm5iZiI6MTcwNzIzMjUzNCwicGF0aCI6Ii82ODQxNjc3OS8yOTcyNTMwNjYtZGVlNzI1OTUtNzAwYS00MDg1LTlhNmYtYTE1MjdiOGY1MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1MTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmM1NDM3ZGE1ZDJiNDJhYWE3ZDI2ZjZjMGQ3ZWQ2MTNhY2M0MDVjNWFhMDZjZDJlNzA5NjZhM2ZmMzg4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QQkeMtsNWgpdOl7GPRmm5V4eHzHHY2Qcpsk1NQrgqJ8) **Command**
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model /mnt/bynas/llms_store/Qwen-72B-Chat --trust-remote-code --tensor-parallel-size 4 --host 0.0.0.0 --port 5000 \
> --served-model-name Qwen/Qwen-72B-Chat --gpu-memory-utilization 0.5
> ```
> 
> **Environment** 4 * Nvidia A6000 48G cuda 12.3 python 3.11

Have you fixed this problem? I have same problem on 8*A100 80G after initializing llm engine and it stucks. @thugbobby

**Comment by yuanphoenix** [comment]
直接使用A800解决了。

**Comment by thelongestusernameofall** [comment]
> > When I run local llm qwen-72b-chat, it can`t work normal, it will be stuck like this: ![image](https://private-user-images.githubusercontent.com/68416779/297253066-dee72595-700a-4085-9a6f-a1527b8f5362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzI4MzQsIm5iZiI6MTcwNzIzMjUzNCwicGF0aCI6Ii82ODQxNjc3OS8yOTcyNTMwNjYtZGVlNzI1OTUtNzAwYS00MDg1LTlhNmYtYTE1MjdiOGY1MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1MTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZmM1NDM3ZGE1ZDJiNDJhYWE3ZDI2ZjZjMGQ3ZWQ2MTNhY2M0MDVjNWFhMDZjZDJlNzA5NjZhM2ZmMzg4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QQkeMtsNWgpdOl7GPRmm5V4eHzHHY2Qcpsk1NQrgqJ8) **Command**
> > ```
> > python -m vllm.entrypoints.openai.api_server --model /mnt/bynas/llms_store/Qwen-72B-Chat --trust-remote-code --tensor-parallel-size 4 --host 0.0.0.0 --port 5000 \
> > --served-model-name Qwen/Qwen-72B-Chat --gpu-memory-utilization 0.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Environment** 4 * Nvidia A6000 48G cuda 12.3 python 3.11
> 
> Have you fixed this problem? I have same problem on 8*A100 80G after initializing llm engine and it stucks. @thugbobby


Same Problem . 有人解决了么？

**Comment by DarkLight1337** [comment]
We have added [documentation](https://docs.vllm.ai/en/stable/getting_started/debugging.html) for this situation in #5430. Please take a look.
