### ISSUE TITLE
when to support chatglm2-6b? 

### ISSUE THREAD

**Issue by liukaiyueyuo** [vllm-project/vllm#247]
chatglm-6b(chatglm2-6b) is a very popular Chinese LLM. Do you have a plan？

**Comment by zhaoying9105** [comment]
mark

**Comment by bb2103** [comment]
+1, wanted too

**Comment by foxxxx001** [comment]
mark

**Comment by irasin** [comment]
mark

**Comment by zhuqn** [comment]
mark

**Comment by BrightXiaoHan** [comment]
+1

**Comment by wuxiy** [comment]
+1

**Comment by wuxiy** [comment]
+1

**Comment by binarri** [comment]
Mark

**Comment by Oliver-ss** [comment]
mark

**Comment by felixstander** [comment]
mark

**Comment by akxxsb** [comment]
mark

**Comment by jinchihe** [comment]
+1

**Comment by wang-benqiang** [comment]
mark

**Comment by iDonal** [comment]
+1

**Comment by youthbupt** [comment]
+1

**Comment by Jeffwan** [comment]
If anyone is familiar with chatGLM model architecture, feel free to help on #625. I am new to transformer architecture and not sure if my changes is correct..

**Comment by jinghai** [comment]
+1

**Comment by x22x22** [comment]
mark

**Comment by datalee** [comment]
mark

**Comment by callanwu** [comment]
mark

**Comment by simon-mo** [comment]
If anyone have bandwidth to help us implement ChatGLM support, please leave a comment and coordinate here: https://github.com/vllm-project/vllm/issues/1552

**Comment by chenyangjun45** [comment]
When I use vllm to load ChatGLM2 model that trained with "quantization_bit 8", it seems to be not supported. The code below is the original code in ChatGLM2 "modeling_chatglm.py".  If anyone can add this feature into vllm? thanks. 

`class ChatGLMForConditionalGeneration(ChatGLMPreTrainedModel):
    def __init__(self, config: ChatGLMConfig, empty_init=True, device=None):
        super().__init__(config)

        self.max_sequence_length = config.max_length
        self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
        self.config = config
        self.quantized = False

        if self.config.quantization_bit:
            self.quantize(self.config.quantization_bit, empty_init=True)`


`    def quantize(self, bits: int, empty_init=False, device=None, **kwargs):
        if bits == 0:
            return

        from .quantization import quantize

        if self.quantized:
            logger.info("Already quantized.")
            return self

        self.quantized = True

        self.config.quantization_bit = bits

        self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
                                            **kwargs)
        return self`

**Comment by hmellor** [comment]
ChatGLM supported in https://github.com/vllm-project/vllm/pull/1261
