### ISSUE TITLE
Add Splitwise: prompt and token phase separation

### ISSUE THREAD

**Issue by goiri** [vllm-project/vllm#2472]
We have built the system described in [http://aka.ms/splitwise](http://aka.ms/splitwise)
Splitwise splits the prompt and token phases to run in different servers.
This leverages the differences between these two phases to improve throughput.
We have an internal prototype on top of an internal vLLM branch.
This issue tracks the effort to open source this prototype and make it part of the official vLLM.
 
This includes:
* Add MSCCL++ support [https://github.com/microsoft/mscclpp](https://github.com/microsoft/mscclpp)
* Add per-layer KV-cache transfer
* Coordination across prompt and token servers
* Documentation

**Comment by goiri** [comment]
This was asked in [https://github.com/vllm-project/vllm/issues/2370](https://github.com/vllm-project/vllm/issues/2370).

**Comment by irasin** [comment]
LGTM,  I was wondering when can we use it in vllm?

**Comment by goiri** [comment]
@irasin, @aashaka is doing some cleanup and refactoring and will be posting the PRs in the next few weeks.
We will be updating this issue (and linking the PRs) with the progress.

**Comment by adney11** [comment]
Hi All, 

Just wanted to check in and see if there is any update on Splitwise's implementation in vLLM, and if this internal prototype codebase can be released?

Thank you!

**Comment by aashaka** [comment]
This has now been released in PR https://github.com/vllm-project/vllm/pull/2809. @adney11, @irasin
