### ISSUE TITLE
Support JSON mode.

### ISSUE THREAD

**Issue by MiyazonoKaori** [vllm-project/vllm#2483]
Any plan to integrate modules such as lm-format-enforcer. Support JSON mode.

**Comment by simon-mo** [comment]
Yes! This is our top priorities.

**Comment by hadsed** [comment]
Is there currently any work happening here? I could look into it if not.

**Comment by fullstackwebdev** [comment]
context-free grammar
![FwDTXcNaYAIafOg](https://github.com/vllm-project/vllm/assets/10137946/08b5f918-768b-4b08-9170-0a9fb2b6a2c3)


it would be cool if the llama cpp GBNF grammars could be standardize so we can do stuff like the image , between different LLM frameworks.

**Comment by simon-mo** [comment]
In our roadmap, anything https://github.com/outlines-dev/outlines supports can be part of vLLM, as long as any other frameworks that support LogitsProcessors API.

**Comment by Kaotic3** [comment]
This looks good, just read through outlines - seems super useful.

When do we get it :D

**Comment by findalexli** [comment]
Have someone done benchmark on latency introduced by outlines?

**Comment by solesensei** [comment]
Is this already supported as described here https://github.com/vllm-project/vllm/issues/1191?

**Comment by ChuckHend** [comment]
I would also love to see this feature make it into vllm!

**Comment by wxgeorge** [comment]
> Is this already supported as described here #1191?

I suspect the same ...

e.g. https://github.com/vllm-project/vllm/pull/3211

**Comment by ChuckHend** [comment]
`"request_format": { "type": "json_object" }` seems to work for me. Also requires a prompt specifically asking for json response.

**Comment by DarkLight1337** [comment]
> > Is this already supported as described here #1191?
> 
> I suspect the same.
> 
> Specifically https://github.com/vllm-project/vllm/pull/3211 implements handling for `"request_format": { "type": "json_object" }` in the completion request body, which is what I'm familiar with when we say "JSON mode".

Yep, that should do it.
