### ISSUE TITLE
`max_num_batched_tokens` and `max_num_seqs values`

### ISSUE THREAD

**Issue by isRambler** [vllm-project/vllm#2492]
Hello, because I am new to vllm, I want to know how to set the `max_num_batched_tokens` and `max_num_seqs values` in order to achieve maximum inference performance. What is the relationship between `max_num_batched_tokens` and `max_num_seqs`? Why do the output tokens appear when I set different max_num_batched_tokens and max_num_seqs? The totals may be inconsistent

**Comment by JasonZhu1313** [comment]
`max_num_batched_tokens` and `max_num_seqs` essentially determines the batch size at prefill stage - the first time when the model performs inference to predict the next token in a sequence. vLLM utilizes continuous batching to achieve high throughput. The underlying scheduler determines, at a certain step, the batched samples for inference based on the state of GPU memory and the availability of KV Cache blocks. The scheduler separates queries into three categories: Waiting Queue (sequences at prefill stage), Running Queue (sequences at decoding stage), Swapping Queue (if cpu / gpu swapping is enabled).

I have drawn a diagram to better illustrate the scheduling workflow and you can see `max_num_batched_tokens` and `max_num_seqs` determines the batch size of waiting queue:

![Flowchart (3)](https://github.com/vllm-project/vllm/assets/28351896/9bdc17bc-e517-44e7-a9a8-eb7485d86043)

If you set the `max_num_batched_tokens` or `max_num_seqs` with low value then the prefill batch size will be small (e.g., 1) which might not hurt performance, there is no one size fit all suggestion I guess, I think you can tweak the prefill batch size through these two knobs and use benchmark_serving.py in vLLM to determine what size leads to best performance.

**Comment by isRambler** [comment]
> `max_num_batched_tokens` and `max_num_seqs` essentially determines the batch size at prefill stage - the first time when the model performs inference to predict the next token in a sequence. vLLM utilizes continuous batching to achieve high throughput. The underlying scheduler determines, at a certain step, the batched samples for inference based on the state of GPU memory and the availability of KV Cache blocks. The scheduler separates queries into three categories: Waiting Queue (sequences at prefill stage), Running Queue (sequences at decoding stage), Swapping Queue (if cpu / gpu swapping is enabled).
> 
> I have drawn a diagram to better illustrate the scheduling workflow and you can see `max_num_batched_tokens` and `max_num_seqs` determines the batch size of waiting queue:
> 
> ![Flowchart (3)](https://private-user-images.githubusercontent.com/28351896/297814161-9bdc17bc-e517-44e7-a9a8-eb7485d86043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTYxOTUsIm5iZiI6MTcwNTkxNTg5NSwicGF0aCI6Ii8yODM1MTg5Ni8yOTc4MTQxNjEtOWJkYzE3YmMtZTUxNy00NGU3LWE5YTgtZWI3NDg1ZDg2MDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNjNjOTcwZjFiMTI3Yjc3ZTc2YzYxZjdhYTI0NTFhNWZhNGFmY2VkNDlkYmQwN2VhODU5ZDZlYTlmNjRmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEiPbOXGH84jSlV-GM_5U95ekvr1Omjo0Cs-nvjgiU4)
> 
> If you set the `max_num_batched_tokens` or `max_num_seqs` with low value then the prefill batch size will be small (e.g., 1) which might not hurt performance, there is no one size fit all suggestion I guess, I think you can tweak the prefill batch size through these two knobs and use benchmark_serving.py in vLLM to determine what size leads to best performance.

OK, thanks for the explanation

**Comment by banyip** [comment]
> Hello, because I am new to vllm, I want to know how to set the `max_num_batched_tokens` and `max_num_seqs values` in order to achieve maximum inference performance. What is the relationship between `max_num_batched_tokens` and `max_num_seqs`? Why do the output tokens appear when I set different max_num_batched_tokens and max_num_seqs? The totals may be inconsistent

Is there a final answer to set this variable?

**Comment by realJaydenCheng** [comment]
> > Hello, because I am new to vllm, I want to know how to set the `max_num_batched_tokens` and `max_num_seqs values` in order to achieve maximum inference performance. What is the relationship between `max_num_batched_tokens` and `max_num_seqs`? Why do the output tokens appear when I set different max_num_batched_tokens and max_num_seqs? The totals may be inconsistent
> 
> Is there a final answer to set this variable?

You can set these variables when initializing the LLM object:

```python
from vllm import LLM
llm = LLM(
    model=LLM_PATH,
    max_num_batched_tokens=512*50,
    max_model_len=512*50,
    gpu_memory_utilization=0.3,
)
```

**Comment by ehartford** [comment]
can we have some kind of guidance or rule of thumb?  How do we decide, practically speaking, what values to set in order to maximize performance?

**Comment by zengqingfu1442** [comment]
> You can set these variables when initializing the LLM object:
> 
> from vllm import LLM
> llm = LLM(
>     model=LLM_PATH,
>     max_num_batched_tokens=512*50,
>     max_model_len=512*50,
>     gpu_memory_utilization=0.3,
> )

What if i set a larger value of max_num_batched_tokens than max_model_len? i think that the max_model_len should be less than or equal the context length of the llm.

**Comment by mrtpk** [comment]
Please check out `autotune.sh` https://github.com/vllm-project/vllm/blob/ba7ba35cdaeacb59860bad2691de190bd77ccd05/benchmarks/auto_tune.sh#L20 to get the best params for a model for different conditions.

**Comment by mrtpk** [comment]
> `max_num_batched_tokens` and `max_num_seqs` essentially determines the batch size at prefill stage - the first time when the model performs inference to predict the next token in a sequence. vLLM utilizes continuous batching to achieve high throughput. The underlying scheduler determines, at a certain step, the batched samples for inference based on the state of GPU memory and the availability of KV Cache blocks. The scheduler separates queries into three categories: Waiting Queue (sequences at prefill stage), Running Queue (sequences at decoding stage), Swapping Queue (if cpu / gpu swapping is enabled).
> 
> I have drawn a diagram to better illustrate the scheduling workflow and you can see `max_num_batched_tokens` and `max_num_seqs` determines the batch size of waiting queue:
> 
> ![Flowchart (3)](https://github.com/vllm-project/vllm/assets/28351896/9bdc17bc-e517-44e7-a9a8-eb7485d86043)
> 
> If you set the `max_num_batched_tokens` or `max_num_seqs` with low value then the prefill batch size will be small (e.g., 1) which might not hurt performance, there is no one size fit all suggestion I guess, I think you can tweak the prefill batch size through these two knobs and use benchmark_serving.py in vLLM to determine what size leads to best performance.

@JasonZhu1313, Thank you for the diagram. It helps us understand what is happening inside. But I still could not understand the mathematical relationship between `batch_sz`,  `max_num_batched_tokens`, and `max_num_seqs`. Is there a math formula that helps calculate `batch_sz` from these values?
