### ISSUE TITLE
How to add my model to vllm finetuned from a huggingface model which has an existing model in vLLM?

### ISSUE THREAD

**Issue by xincanfeng** [vllm-project/vllm#2504]
Are the vllm models have the exact same structures as those in HuggingFace? Since the vllm load model from huggingface, I think their structures are the same, right?

**Comment by ikalista** [comment]
Yes, it's all the same except it's not adapted for peft or lora yet.

**Comment by xincanfeng** [comment]
Thank you so much for answering!
