### ISSUE TITLE
Are you ready to support InternLM2?

### ISSUE THREAD

**Issue by canglangzhishuiz** [vllm-project/vllm#2506]
ValueError: Model architectures ['InternLM2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'DeciLMForCausalLM', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM', 'YiForCausalLM']

**Comment by YCG09** [comment]
@canglangzhishuiz 问题解决了吗？

**Comment by Panda-ka** [comment]
我也遇到了同样的问题，不知道怎样解决
