### ISSUE TITLE
lookahead faster than vllm?

### ISSUE THREAD

**Issue by janelu9** [vllm-project/vllm#2508]
can vllm apply its decoding method?
https://github.com/alipay/PainlessInferenceAcceleration/tree/main

**Comment by MeJerry215** [comment]
这个真的有应用场景嘛？数据刷的很好看，一到sampling 生成就歇逼，因为gready 生成容易大量重复，在大量重复之前没性能加速。

**Comment by janelu9** [comment]
> 这个真的有应用场景嘛？数据刷的很好看，一到sampling 生成就歇逼，因为gready 生成容易大量重复，在大量重复之前没性能加速。

just try it

**Comment by huangtingwei9988** [comment]
@janelu9 I'm working for it
