### ISSUE TITLE
openapi running but "POST /v1/chat/completions HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by Nero10578** [vllm-project/vllm#2520]
I managed to install and get vllm working in windows wsl ubuntu, but I can't seem to get it to respond to any openapi requests. I keep getting the error message: "POST /v1/chat/completions HTTP/1.1" 404 Not Found

I have forwarded ports in windows to wsl and textgen webui running in wsl works just fine with its openai api.

```
python -m vllm.entrypoints.api_server --model text-generation-webui/models/cognitivecomputations_dolphin-2.6-mistral-7b --tensor-parallel-size 2
2024-01-21 01:28:29,635 INFO worker.py:1724 -- Started a local Ray instance.
INFO 01-21 01:28:30 llm_engine.py:70] Initializing an LLM engine with config: model='text-generation-webui/models/cognitivecomputations_dolphin-2.6-mistral-7b', tokenizer='text-generation-webui/models/cognitivecomputations_dolphin-2.6-mistral-7b', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, quantization=None, enforce_eager=False, seed=0)
INFO 01-21 01:28:57 llm_engine.py:275] # GPU blocks: 10974, # CPU blocks: 4096
WARNING 01-21 01:28:57 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 01-21 01:28:57 model_runner.py:501] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 01-21 01:28:57 model_runner.py:505] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
(RayWorkerVllm pid=2897) WARNING 01-21 01:28:57 cache_engine.py:96] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(RayWorkerVllm pid=2897) INFO 01-21 01:28:57 model_runner.py:501] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(RayWorkerVllm pid=2897) INFO 01-21 01:28:57 model_runner.py:505] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
[W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
(RayWorkerVllm pid=2897) [W CUDAGraph.cpp:145] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
INFO 01-21 01:29:32 model_runner.py:547] Graph capturing finished in 36 secs.
(RayWorkerVllm pid=2897) INFO 01-21 01:29:32 model_runner.py:547] Graph capturing finished in 36 secs.
INFO:     Started server process [449]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.24.16.1:56006 - "POST /v1/chat/completions HTTP/1.1" 404 Not Found
```

**Comment by Avinash-Raj** [comment]
@Nero10578 You need to invoke `openai` server, ie. `vllm.entrypoints.openai.api_server`

**Comment by benaurelschill** [comment]
I am having the same problem - 
/health works fine but every other api call gets 404 Not found - even v1/models is returning a 404
even though the server is invoked, and the model is loaded correctly
@Nero10578 have you found any fixes?
@WoosukKwon is this a known issue?

**Comment by hmellor** [comment]
Closing this as it due to user error, @Avinash-Raj provided the correct answer.

**Comment by Andy1018** [comment]
@Nero10578 how to resove this issue?

**Comment by iFe1er** [comment]
That's SUPER EASY to confuse ... Thanks @Avinash-Raj

**Comment by shinthor** [comment]
For others who might get this issue another thing to check for is to make sure to include the /v1/ after the base url/ip address+port combo. Llama.cpp handles the request with just the base url without v1 but vllm gives a 404 error without it

**Comment by cryptowooser** [comment]
I'm having this issue now as well: 

Docker code is: 
docker run --shm-size 10g --rm --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --mount type=bind,src="${PWD}",target=/workspace/vllm --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface --env "HUGGING_FACE_HUB_TOKEN=(Redacted)" -p 8000:8000 vllm/vllm-openai:latest --model microsoft/Phi-3-medium-4k-instruct --tensor-parallel-size 2 --trust-remote-code

Function to communicate with LLM is:

    def communicate_with_llm(self, input):
        openai_api_key = "EMPTY"
        openai_api_base = "http://localhost:8000/v1/"

        client = OpenAI(
            api_key=openai_api_key,
            base_url=openai_api_base,
        )

        model_name = "modemicrosoft/Phi-3-medium-4k-instructv1"
        chat_response = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": "You are an expert evaluator and instructor in the Japanese language."},
                {"role": "user", "content": input},]
        )
        return chat_response.choices[0].message.content

Can anyone provide guidance?
