### ISSUE TITLE
DeepSeek MoE support

### ISSUE THREAD

**Issue by SinanAkkoyun** [vllm-project/vllm#2534]
Hey, it would be awesome if we could see https://github.com/deepseek-ai/DeepSeek-MoE support

**Comment by simon-mo** [comment]
Active works in #2467 and #2453

**Comment by esmeetu** [comment]
@SinanAkkoyun Close this since [v0.3.0](https://github.com/vllm-project/vllm/releases/tag/v0.3.0) support this model.
