### ISSUE TITLE
outputs includes eos token

### ISSUE THREAD

**Issue by wuchaooooo** [vllm-project/vllm#2538]
### code

```
gen_kwargs = {"top_p": top_p, "temperature": temperature, "max_tokens": max_length, "include_stop_str_in_output": False}
eos_token_id = [tokenizer.eos_token_id, tokenizer.get_command("<|user|>"), tokenizer.get_command("<|observation|>")]
sampling_params = SamplingParams(stop_token_ids=eos_token_id, **gen_kwargs)
outputs = self.model.generate(sampling_params=sampling_params, prompt_token_ids=inputs["input_ids"].tolist())
```

### outputs string

```
I need to use the insauto_quote_tool tool to get the user's car insurance quote.<|assistant|> insauto_quote_tool
 ```python
tool_call(type='object', properties={'quote_biz_id': '20220906000831000002005700226000'})
```<|observation|>
```

### question

lwhy is '<|observation|>' still at the end?

### environment

Model：ChatGLM3-6b

**Comment by simon-mo** [comment]
I think by default vLLM removes the special tokens as specified by the tokenizer. 

https://github.com/vllm-project/vllm/blob/7a0b011dd51e5c6b48e8f8f5424be0995b5cb8ee/vllm/engine/llm_engine.py#L836-L854

So while `stop_token_ids` is the stopping criteria. It is not the criteria for skipping during decode. 

There's another flag `include_stop_str_in_output`, but currently it only works for `SamplingParams.stop`

https://github.com/vllm-project/vllm/blob/7a0b011dd51e5c6b48e8f8f5424be0995b5cb8ee/vllm/engine/llm_engine.py#L856-L870

I would recommend extend `include_stop_str_in_output` flag to support `stop_token_ids` for your use case. 
Contribution welcomed!
