### ISSUE TITLE
RuntimeError: NVML_SUCCESS == DriverAPI::get()

### ISSUE THREAD

**Issue by Brian-Lei-XIA** [vllm-project/vllm#2544]
My env:
Python 3.10.13 
torch    2.1.2
vllm      0.2.7

My cuda version is:
![WechatIMG3](https://github.com/vllm-project/vllm/assets/61838642/477073ce-d733-4097-9d4a-9ca46c004dba)

I use llm:
llm = LLM(model="../open-source-llms/Llama-2-7b-chat-hf")

cause issue:
RuntimeError: NVML_SUCCESS == DriverAPI::get()->nvmlDeviceGetHandleByPciBusId_v2_( pci_id, &nvml_device) INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1139, please report a bug to PyTorch. 

Please help me to fix it

**Comment by simon-mo** [comment]
I think this is an environment issue unique to your set up. Are you able to run a simple PyTorch program to check whether your CUDA driver is working?

**Comment by telangmu123-good** [comment]
I have encountered the same issue as well. How can I resolve it?
