### ISSUE TITLE
Allow passing hf config args with openai server

### ISSUE THREAD

**Issue by Aakash-kaushik** [vllm-project/vllm#2547]
Hi,

Is there a specific reason for why can't we allow passing of args from the openai server to the HF config class, there are very reasonable use cases where i would want to override the existing args in a config while running the model dynamically though the server.

[reference line](https://github.com/vllm-project/vllm/blob/18bfcdd05c657e6997b132488e6f4e74307d6cee/vllm/transformers_utils/config.py#L23)

simply allowing `*args` in the openai server that are passed to this while loading the model, i believe there are internal checks for failing if anything configured is wrong anyway.

supported documentation in the transformers library:

```
        >>> # Change some config attributes when loading a pretrained config.
        >>> config = AutoConfig.from_pretrained("bert-base-uncased", output_attentions=True, foo=False)
        >>> config.output_attentions
        True
```

**Comment by simon-mo** [comment]
I believe there's no fundamental reason to this. Contribution welcomed! I would say you can add this to ModelConfig class and pass it through EngineArgs.

**Comment by KrishnaM251** [comment]
I will take a look at this

**Comment by mrPsycox** [comment]
Anyone has news about that? I want to use --dtype, but it doesn't work

**Comment by Aakash-kaushik** [comment]
@mrPsycox `—dtype` is supported in vllm, please take a look at the engine args on vllm docs

**Comment by mrPsycox** [comment]
Thanks @Aakash-kaushik , I found the issue. Passing `--dtype` need to be in first args of the command, not in the last. 

This works for me:

```
  docker run --gpus all -p 8000:8000 ghcr.io/mistralai/mistral-src/vllm:latest \
                   --host 0.0.0.0 \
                   --model mistralai/Mixtral-8x7B-Instruct-v0.1 \
                   --dtype half \
                   --tensor-parallel-size $SKYPILOT_NUM_GPUS_PER_NODE
```

**Comment by K-Mistele** [comment]
I would love to see this as well

**Comment by KrishnaM251** [comment]
@Aakash-kaushik @mrPsycox  @timbmg @K-Mistele

Please take a look at my PR and let me know if it serves your purpose.

As @DarkLight1337 noted in my PR (#5836) , what exactly do you want to accomplish using this feature that cannot otherwise be done via vLLM args? (If we don't have any situation that results in different vLLM output, what is the point of enabling this?)

Once you get back to me, I'll write a test that covers that case.

**Comment by K-Mistele** [comment]
Hi guys, just bumping this in case it's still relevant. Maybe not so much passing hf `config.json` args at request-time, but being able to set them for the OpenAI compatible server without having to dig into the model's cache directory would be super useful. 

Some examples of where this would be applicable include configuring Qwen models and llama models' RoPE scaling:

```
Processing Long Texts
The current config.json is set for context length up to 32,768 tokens. To handle extensive inputs exceeding 32,768 tokens, we utilize [YaRN](https://arxiv.org/abs/2309.00071), a technique for enhancing model length extrapolation, ensuring optimal performance on lengthy texts.

For supported frameworks, you could add the following to config.json to enable YaRN:

{
  ...,
  "rope_scaling": {
    "factor": 4.0,
    "original_max_position_embeddings": 32768,
    "type": "yarn"
  }
}

For deployment, we recommend using vLLM. Please refer to our [Documentation](https://qwen.readthedocs.io/en/latest/deployment/vllm.html) for usage if you are not familar with vLLM. Presently, vLLM only supports static YARN, which means the scaling factor remains constant regardless of input length, potentially impacting performance on shorter texts. We advise adding the rope_scaling configuration only when processing long contexts is required.
```

Maybe this is already implemented somewhere else?

**Comment by DarkLight1337** [comment]
I propose a similar feature in #5205
