### ISSUE TITLE
Radix Attention support

### ISSUE THREAD

**Issue by MichaelJayW** [vllm-project/vllm#2560]
RadixAttention, a novel technique for automatic KV cache reuse during runtime. Furthermore, RadixAttention is compatible with existing techniques like continuous batching and paged attention.

Blog: https://lmsys.org/blog/2024-01-17-sglang/
Paper:https://arxiv.org/abs/2312.07104
Code:https://github.com/sgl-project/sglang
![llama_7b](https://github.com/vllm-project/vllm/assets/1152904/33d5ef34-3528-45c3-904b-a9b4b1262eee)

**Comment by irasin** [comment]
LGTM
