### ISSUE TITLE
Out of memory error for Mystral AWQ quantised model in A10 GPU where as non-quantised model is easily loaded in the memory.

### ISSUE THREAD

**Issue by dbanka** [vllm-project/vllm#2561]
When I am trying to load AWQ quantised version of Mystral-7b, I am facing OOM issues. 

AWQ config :  "q_group_size": 128, "w_bit": 4, "version": "GEMM"

But when I try to load non-quantised mystral, it is loaded.

What is the issue here?

**Comment by s-natsubori** [comment]
Try
`max_model_len=8k`
