### ISSUE TITLE
Slow build speed with punica after #1804

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#2571]
After #1804, the build speed of vLLM becomes significantly slower. Most of the time was spent on `/home/zhuohan/vllm/vllm/csrc/punica/bgmv/bgmv_all.cu`. Should we turn off punica by default?

cc @Yard1

**Comment by Yard1** [comment]
Should we make it depend on an env var that can be set when calling `setup.py`/`pip install`?

**Comment by njhill** [comment]
Duplicated by https://github.com/vllm-project/vllm/issues/2604 and now resolved by #2605?
