### ISSUE TITLE
Support for production grade server for Inference [Gunicorn vs Unicorn]?

### ISSUE THREAD

**Issue by jalotra** [vllm-project/vllm#2573]
hey all, 
context : while doing model NFRs with mixtral 8x7B OOB model, the vLLM stack is using unicorn by default in api_server.py, on increasing QPS using locust, I am guessing `unicorn` is becoming a bottleneck and is not able to scale.

Ideas / Views on adding gunicorn support, how do you deploy model using vLLM stack in prod for serving ?

at 2QPS running on 2 A100 GPUs
error rate : 3%
error status code : 0 meaning connectivity issues
gpu utilisation : 90%
tokens per second : ~2100
<img width="1473" alt="image" src="https://github.com/vllm-project/vllm/assets/39359593/1b4a455e-5989-4ca9-af8e-dd20f361d542">

at 4.1 QPS running on 4 A100 GPUs
error rate : 13%
error status code : 0 meaning connectivity issues
gpu utilisation : 75%
tokens per second : ~4100
<img width="1249" alt="image" src="https://github.com/vllm-project/vllm/assets/39359593/5510740d-fd8c-48c0-9a63-b95bad102719">

deductions : 
1. as I increase the number of concurrent users to increase model throughput, the connectivity issues start emerging a lot. 
2. in number terms, on 100 - 200 users, error rate goes to ~25-35%.

**Comment by hmellor** [comment]
@robertgshaw2-neuralmagic did you get around to evaluating `gunicorn` as you mentioned in https://github.com/vllm-project/vllm/issues/6797#issuecomment-2263989955?

**Comment by robertgshaw2-neuralmagic** [comment]
I don’t think gunicorn is needed, as the overhead has been removed. Implementing gunicorn will also require changes to the MQLLMEngine

**Comment by hmellor** [comment]
Ok, thanks for the update
