### ISSUE TITLE
vllm加速的chatglm3模型的输出去掉prompt

### ISSUE THREAD

**Issue by PeterXiaTian** [vllm-project/vllm#2578]
如题，如何控制大模型，在输出的时候，不要带上prompt，只输出结论即可

**Comment by jessiewiswjc** [comment]
echo=False

**Comment by PeterXiaTian** [comment]
> echo=False

在哪里加这个参数了？

**Comment by PeterXiaTian** [comment]
在vllm/entrypoints/api_server.py　没有该参数，看文档显示应该是vllm/entrypoints/openai/api_server.py才有．该如何解决了

**Comment by irasin** [comment]
@PeterXiaTian 可以贴一下你启服务和测试的脚本吗？不然不太好复现你的问题

**Comment by PeterXiaTian** [comment]
> @PeterXiaTian 可以贴一下你启服务和测试的脚本吗？不然不太好复现你的问题
启动脚本：
CUDA_VISIBLE_DEVICES=7 nohup python -m vllm.entrypoints.api_server --model xxx --host 0.0.0.0 --port 1000  --gpu-memory-utilization 0.5 --trust-remote-code > test_vllm.log 2>&1 &

测试脚本：
req_data = {
            "prompt": query_str,
            "max_tokens": 500,
            "temperature": 0,
            "top_p": 0.85
        }
        headers = {'Content-Type': 'application/json'}

        res = requests.post(url=_url, headers=headers, json=req_data).json()

**Comment by PeterXiaTian** [comment]
> @PeterXiaTian 可以贴一下你启服务和测试的脚本吗？不然不太好复现你的问题

启动脚本都是现成的．
python -m vllm.entrypoints.api_serve
测试脚本：
req_data = {
            "prompt": query_str,
            "max_tokens": 500,
            "temperature": 0,
            "top_p": 0.85
        }
        headers = {'Content-Type': 'application/json'}

        res = requests.post(url=_url, headers=headers, json=req_data).json()

**Comment by liupengfei66** [comment]
这个后来是咋解决了？

**Comment by hmellor** [comment]
The original poster was using the entry point that's only meant to be used in tests.

If you use the openai entry point, this should not happen.
