### ISSUE TITLE
benchmark error

### ISSUE THREAD

**Issue by zhaoxin111** [vllm-project/vllm#2579]
why POST /generate HTTP/1.1" 404 Not Found?
Can anyone help me, thanks.

![image](https://github.com/vllm-project/vllm/assets/9295202/922e3856-b750-4ab7-a8c4-94e6bfcc1575)
![image](https://github.com/vllm-project/vllm/assets/9295202/5797a0e1-94d9-4cc1-a911-a3e03196dd67)
![image](https://github.com/vllm-project/vllm/assets/9295202/f9103ec4-b4b6-4ba8-8047-fbe7b6c733c9)

**Comment by wangr0031** [comment]
Is the problem solved? Can you share how you solved it?
