### ISSUE TITLE
`vllm` target removed from Dockerfile

### ISSUE THREAD

**Issue by tdoublep** [vllm-project/vllm#2582]
The `vllm` target was removed from the Dockerfile with [this commit](https://github.com/vllm-project/vllm/commit/6e01e8c1c8ea323d30e3f57050469b2df66b56c6#). I was always building it to this target until now (rather than using `vllm-openai` target. 

Was this an intentional change?

**Comment by simon-mo** [comment]
Yes. I'm happy to revert it if needed but it is basically the same image as `vllm-openai`, which you can override the entrypoint.

We generally recommend folks to use OpenAI compatible server because it is the superset of the features.
