### ISSUE TITLE
How to mannually Set use_fast for tokenizer to False？

### ISSUE THREAD

**Issue by jeffchy** [vllm-project/vllm#259]

**Comment by WoosukKwon** [comment]
@jeffchy Thanks for trying out vLLM! Currently, vLLM does not support custom tokenizer at the moment. We will fix this.

**Comment by HermitSun** [comment]
I modified the `model_name` as a temporary hack:

https://github.com/vllm-project/vllm/blob/43710e8d0965d616db51639ced76605dee1bde93/vllm/engine/tokenizer_utils.py#L25-L29

Can't wait to see the custom tokenizer support🤣.
