### ISSUE TITLE
Will block_size 64/128/156 be supported in paged attention?

### ISSUE THREAD

**Issue by lu-ym** [vllm-project/vllm#2594]
When I try to use paged attention. I met `RuntimeError: Unsupported block size: 64`.
From source code we can know paged attention does not support block_size = 1/2/4/64/128/256 to reduce the compilation time ([attention_kernels.cu#L663~L664](https://github.com/vllm-project/vllm/blob/2832e7b9f92e2d1dd7dfe37951e5837c61d3db20/csrc/attention/attention_kernels.cu#L663~L664)).

So:
- Will those block_size numbers be supported in the further? 
- Or users can instance kernel and compile manually? Will the correctness and performance be guaranteed?

**Comment by MeJerry215** [comment]
Maybe you can add two lines and recompile the code.
```c++
#define CALL_V1_LAUNCHER_BLOCK_SIZE(T)                              \
  switch (block_size) {                                             \
    case 8:                                                         \
      CALL_V1_LAUNCHER(T, 8);                                       \
      break;                                                        \
    case 16:                                                        \
      CALL_V1_LAUNCHER(T, 16);                                      \
      break;                                                        \
    case 32:                                                        \
      CALL_V1_LAUNCHER(T, 32);                                      \
      break;                                                        \
    case 64:
      CALL_V1_LAUNCHER(T, 64);                                      \
    default:                                                        \
      TORCH_CHECK(false, "Unsupported block size: ", block_size);   \
      break;                                                        \
  }
```

**Comment by lu-ym** [comment]
> Maybe you can add two lines and recompile the code.
> 
> ```c++
> #define CALL_V1_LAUNCHER_BLOCK_SIZE(T)                              \
>   switch (block_size) {                                             \
>     case 8:                                                         \
>       CALL_V1_LAUNCHER(T, 8);                                       \
>       break;                                                        \
>     case 16:                                                        \
>       CALL_V1_LAUNCHER(T, 16);                                      \
>       break;                                                        \
>     case 32:                                                        \
>       CALL_V1_LAUNCHER(T, 32);                                      \
>       break;                                                        \
>     case 64:
>       CALL_V1_LAUNCHER(T, 64);                                      \
>     default:                                                        \
>       TORCH_CHECK(false, "Unsupported block size: ", block_size);   \
>       break;                                                        \
>   }
> ```

Fine. Thanks for your quick reply. I will try it.
