### ISSUE TITLE
vocab_size > 33024 for multi-lora

### ISSUE THREAD

**Issue by germanjke** [vllm-project/vllm#2599]
Can I use vocab_size bigger than standard LLaMa family?

[https://github.com/vllm-project/vllm/blob/main/vllm/lora/layers.py#L942](https://github.com/vllm-project/vllm/blob/main/vllm/lora/layers.py#L942) definition is here

Maybe I should add this size to punica header? [https://github.com/vllm-project/vllm/blob/main/csrc/punica/bgmv/bgmv_config.h](https://github.com/vllm-project/vllm/blob/main/csrc/punica/bgmv/bgmv_config.h)

Error traceback:

```
E0125 16:55:39.360842 120378 backend_model.cc:635] ERROR: Failed to create instance: RuntimeError: No suitable kernel. h_in=16 h_out=79360 dtype=Float out_dtype=BFloat16
 
At:
    /vllm/vllm/lora/punica.py(83): add_lora
    /vllm/vllm/lora/layers.py(58): _apply_lora
    /vllm/vllm/lora/layers.py(930): _get_logits
    /vllm/vllm/model_executor/layers/sampler.py(61): forward
    /vllm/vllm/lora/layers.py(944): forward
    /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1527): _call_impl
    /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
    /vllm/vllm/model_executor/models/llama.py(314): sample
    /vllm/vllm/worker/model_runner.py(535): execute_model
    /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py(115): decorate_context
    /vllm/vllm/worker/model_runner.py(592): profile_run
    /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py(115): decorate_context
    /vllm/vllm/worker/worker.py(111): profile_num_available_blocks
    /usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py(115): decorate_context
    /vllm/vllm/engine/llm_engine.py(981): _run_workers
    /vllm/vllm/engine/llm_engine.py(303): _init_cache
    /vllm/vllm/engine/llm_engine.py(112): __init__
    /vllm/vllm/engine/async_llm_engine.py(366): _init_engine
    /vllm/vllm/engine/async_llm_engine.py(321): __init__
    /vllm/vllm/engine/async_llm_engine.py(617): from_engine_args
    /opt/tritonserver/backends/vllm/model.py(119): initialize
```

**Comment by Yard1** [comment]
@germanjke You can try adding it to the punica header! The requirement is that the size must be divisible by 128.

**Comment by Yard1** [comment]
yeah you will need to pad it for now.

**Comment by germanjke** [comment]
@Yard1 hi, thanks, I resized my model, but now have some problems:

punica source code have this function https://github.com/vllm-project/vllm/blob/main/csrc/punica/punica_ops.cc#L23

I can't compile my value 79104 cause its > 16bit max value

```
      /vllm/csrc/punica/bgmv/bgmv_config.h:50:33: warning: unsigned conversion from ‘int’ to ‘uint16_t’ {aka ‘short unsigned int’} changes value from ‘79104’ to ‘13568’ [-Woverflow]
         50 |     f(in_T, out_T, W_T, narrow, 79104) \
```

**Comment by germanjke** [comment]
@Yard1 I think many models have a large vocabulary, so is it important to support this within vllm?

**Comment by hrson-1203** [comment]
Has this problem been resolved?

**Comment by ashgold** [comment]
Why doesn't the lora adapter load based on the vocabulary size of the origin model, even though the target_modules in adapter_config.json doesn't have embed_tokens and lm_head?
