### ISSUE TITLE
Integrate multi-LoRA functionality with OpenAI server

### ISSUE THREAD

**Issue by Yard1** [vllm-project/vllm#2600]
We should allow LoRAs to be queried using the vLLM OpenAI server.

_Originally posted by @Yard1 in https://github.com/vllm-project/vllm/pull/1804#discussion_r1438452662_

**Comment by Wizmak9** [comment]
Hey @Yard1 bro! any time lines on closing this functionality waiting for this since very long..

**Comment by Yard1** [comment]
This is an open issue for people to take :)

**Comment by oushu1zhangxiangxuan1** [comment]
Waiting for this since very long too.
I'm willing to take this but I cannot guarantee the time I can commit.
And I also need some guidance.

**Comment by oushu1zhangxiangxuan1** [comment]
What's the diff of https://github.com/vllm-project/vllm/pull/289/files  and yours PR #1804 ?

**Comment by oushu1zhangxiangxuan1** [comment]
Compute cap under 8.0 can not use multi lora #1804?
Because of [punica](https://github.com/punica-ai/punica)?

**Comment by prd-tuong-nguyen** [comment]
waiting...
