### ISSUE TITLE
Combine multi-LoRA and quantization

### ISSUE THREAD

**Issue by Yard1** [vllm-project/vllm#2601]
There is no fundamental reason why multi-LoRA cannot work with quantized models. We will most likely want to keep LoRA's unquantized and dequantize the base model output before applying LoRAs with punica kernels. That seems to be the pattern present in other projects too.

_Originally posted by @Yard1 in https://github.com/vllm-project/vllm/issues/1804#issuecomment-1872638416_

**Comment by jacob-hansen** [comment]
Has there been any progress with this? Or has anyone tested multi-LoRA with different quantization to see what might work?

**Comment by thincal** [comment]
@Yard1 is there any plan for this support? really depends on this wonderful feature and also needs to know the real effect. thanks.

**Comment by whyiug** [comment]
@thincal https://github.com/vllm-project/vllm/pull/4012
