### ISSUE TITLE
Add multi-LoRA support for more architectures

### ISSUE THREAD

**Issue by Yard1** [vllm-project/vllm#2602]
Currently, multi-LoRA supports only Llama and Mistral architectures. We should extend this functionality to all architectures.

Yi, Qwen, Phi and Mixtral architectures seem to be the most demanded right now.

One challenge will be ensuring that all allowed weight shapes are supported by punica kernels. We may need to investigate some sort of padding there.

_Originally posted by @Yard1 in https://github.com/vllm-project/vllm/issues/1804#issuecomment-1882913208_

**Comment by TaeWoo21** [comment]
Is it possible to add "GPT-NeoX" as well?

**Comment by Cloopen-ReLiNK** [comment]
how about "chatglm" ?

**Comment by FurtherAI** [comment]
@Yard1 I'm interested in extending this to other architectures, do you want to meet and talk about the problems that need to be solved to get it working?

**Comment by nightflight-dk** [comment]
+1, bump for Phi-3.0 (any Phi right now)

**Comment by jjjjohnson** [comment]
+1 for Qwen

**Comment by jiauy** [comment]
+1 for Qwen
