### ISSUE TITLE
Beam Search Length Normalization Wrong

### ISSUE THREAD

**Issue by physicsrob** [vllm-project/vllm#2606]
The current implementation of the `get_beam_search_score` method in the vllm/sequence.py seems to incorrectly include the prompt length in the sequence length when calculating the beam score. This deviates from the standard approach used in huggingface and elsewhere.

The current implementation is:
```
        if seq_len is None:
            seq_len = self.get_len()
            # NOTE: HF implementation does not count the EOS token
            # towards the length, we align with that here for testing.
            if (eos_token_id is not None
                    and self.get_last_token_id() == eos_token_id):
                seq_len -= 1
        return self.get_cumulative_logprob() / (seq_len**length_penalty)
```

Which I think would be correct if get_len() returned the generated length, but get_len() includes the prompt:
```
    def get_len(self) -> int:
        return len(self.output_token_ids) + len(self.prompt_token_ids)
```

I found this investigating the results returned by a beam search. I was surprised that a short sequence was being returned as the best choice when the second option was much much longer and only had a slightly smaller logprob. The reason, I now realize, is that my prompt is quite long compared to the generation, so the length penalty is not getting correctly applied.

**Comment by hmellor** [comment]
@physicsrob is this issue still present?

**Comment by JohnGiorgi** [comment]
Pretty sure I am suffering from the same issue. I have a case where the prompt length >> output length. Different settings of `length_penalty` have very little effect on the ranking of the top beams, even when they are orders of magnitude different (0.01, 0.1, 1, 10)
