### ISSUE TITLE
How to get the logits of the first generated text?

### ISSUE THREAD

**Issue by Abigail61** [vllm-project/vllm#2613]
I simply aim to obtain the logit value corresponding to the first token generated in each request , rather than acquiring sampled tokens. For example, for A/B/C/D  tokens, how to retrieve the logit values of these specific tokens？

In huggingface model, the code be like:
`logits = self.model(input_ids=input_ids,).logits[:,-1].flatten()`

**Comment by DouHappy** [comment]
What a coincidence! I am looking for the same things. As far as i know, we need to implement it by outself. Maybe soon.

**Comment by mayiran1999** [comment]
Any

> What a coincidence! I am looking for the same things. As far as i know, we need to implement it by outself. Maybe soon.

Any progress?

**Comment by Abigail61** [comment]
I found a solution with 'logprobs' parameter in  SamplingParams, which can print the top n token's logits.
Then we can select the logits corresponding to 'A''B''C''D' and perform softmax processing. If an option is not among the first 1000 tokens, set its logit to -100
```
llm = LLM(model="xxx")
text = "question:xxx A : xxx B : xxx C : xxx D : xxx, choose the right answer : "
sampling_params = SamplingParams(logprobs=1000)
output = llm.generate(text,sampling_params)
```
```
        candidate_logits = []
        for label in ["A", "B", "C", "D"]:
            try:
                candidate_logits.append(output[0].outputs[0].logprobs[0][self.tokenizer.convert_tokens_to_ids(label)])
            except:
              # If an option is not in the first 1000, set its logit to -100
                print("Warning: {} not found. Artificially adding log prob of -100.".format(label))
                candidate_logits.append(-100)
        candidate_logits = torch.tensor(candidate_logits).to(torch.float32)
        probs = (
            torch.nn.functional.softmax(
                candidate_logits,
                dim=0,
            )
            .detach()
            .cpu()
            .numpy()
        )
        answer = {i: k for i, k in enumerate(["A", "B", "C", "D"])}[np.argmax(probs)]
```

**Comment by yuanphoenix** [comment]
Nice Job

**Comment by Loreley99** [comment]
> I found a solution with 'logprobs' parameter in SamplingParams, which can print the top n token's logits. Then we can select the logits corresponding to 'A''B''C''D' and perform softmax processing. If an option is not among the first 1000 tokens, set its logit to -100
> 
> ```
> llm = LLM(model="xxx")
> text = "question:xxx A : xxx B : xxx C : xxx D : xxx, choose the right answer : "
> sampling_params = SamplingParams(logprobs=1000)
> output = llm.generate(text,sampling_params)
> ```
> 
> ```
>         candidate_logits = []
>         for label in ["A", "B", "C", "D"]:
>             try:
>                 candidate_logits.append(output[0].outputs[0].logprobs[0][self.tokenizer.convert_tokens_to_ids(label)])
>             except:
>               # If an option is not in the first 1000, set its logit to -100
>                 print("Warning: {} not found. Artificially adding log prob of -100.".format(label))
>                 candidate_logits.append(-100)
>         candidate_logits = torch.tensor(candidate_logits).to(torch.float32)
>         probs = (
>             torch.nn.functional.softmax(
>                 candidate_logits,
>                 dim=0,
>             )
>             .detach()
>             .cpu()
>             .numpy()
>         )
>         answer = {i: k for i, k in enumerate(["A", "B", "C", "D"])}[np.argmax(probs)]
> ```

May I ask a question: why when I set the SamplingParams(logprobs=100), it will give me an error that "Cannot request more than 5 logprobs."? Thanks

**Comment by Juanhui28** [comment]
@Abigail61 

Thanks for the solution! But I have an error: `ValueError: Cannot request more than 20 logprobs.` Do you have this error and how do you solve it? Thanks!

**Comment by Abigail61** [comment]
@Juanhui28 

sorry I didn't meet this error. Maybe the model doesn't support too many logprobs. You can try to set the logprobs less than 20.

**Comment by kike-0304** [comment]
> I found a solution with 'logprobs' parameter in SamplingParams, which can print the top n token's logits.我在SamplingParams中找到了一个带有'logprobs'参数的解决方案，它可以打印前n个令牌的logit。 Then we can select the logits corresponding to 'A''B''C''D' and perform softmax processing. If an option is not among the first 1000 tokens, set its logit to -100然后我们可以选择对应于'A''B''C''D'的logits并执行softmax处理。如果选项不在前1000个令牌中，则将其logit设置为-100
> 
> ```
> llm = LLM(model="xxx")
> text = "question:xxx A : xxx B : xxx C : xxx D : xxx, choose the right answer : "
> sampling_params = SamplingParams(logprobs=1000)
> output = llm.generate(text,sampling_params)
> ```
> 
> ```
>         candidate_logits = []
>         for label in ["A", "B", "C", "D"]:
>             try:
>                 candidate_logits.append(output[0].outputs[0].logprobs[0][self.tokenizer.convert_tokens_to_ids(label)])
>             except:
>               # If an option is not in the first 1000, set its logit to -100
>                 print("Warning: {} not found. Artificially adding log prob of -100.".format(label))
>                 candidate_logits.append(-100)
>         candidate_logits = torch.tensor(candidate_logits).to(torch.float32)
>         probs = (
>             torch.nn.functional.softmax(
>                 candidate_logits,
>                 dim=0,
>             )
>             .detach()
>             .cpu()
>             .numpy()
>         )
>         answer = {i: k for i, k in enumerate(["A", "B", "C", "D"])}[np.argmax(probs)]
> ```

vllm生成的logits值和huggingface不一样是什么原因
