### ISSUE TITLE
How to change the torch version when building vllm from source?

### ISSUE THREAD

**Issue by aoyulong** [vllm-project/vllm#2615]
When `pip install -e .`, the building process automatically downloads and installs `torch == 2.1.2`. Where can we change the required torch version?
Another question: why does vllm always download packages like torch instead of using the installed one when built from the source?

**Comment by courage17340** [comment]
you may need `--no-build-isolation`

**Comment by aoyulong** [comment]
@courage17340 It works. Thanks.
