### ISSUE TITLE
cuda 11.7可以用哪个版本？为什么已经降到0.1.4了，还是报cuda版本低

### ISSUE THREAD

**Issue by iaoxuesheng** [vllm-project/vllm#2623]
![Yach_screenshot_20240127175940](https://github.com/vllm-project/vllm/assets/94165844/ea724d3d-8ef2-470a-8731-890e8f990032)

**Comment by Harrison-cc** [comment]
> ![Yach_screenshot_20240127175940](https://private-user-images.githubusercontent.com/94165844/300170571-ea724d3d-8ef2-470a-8731-890e8f990032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTI2OTcsIm5iZiI6MTcwNjQ5MjM5NywicGF0aCI6Ii85NDE2NTg0NC8zMDAxNzA1NzEtZWE3MjRkM2QtOGVmMi00NzBhLTg3MzEtODkwZThmOTkwMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAxMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNTk0YTIyNDMzN2Q3ZTNkODJlNTZkM2U1OTA5MGY2ZmYwNmY5NDYxMjVlYTdmNmQ0MDBjMDJlMmEyYTNlNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fY3Vdyc1NJ2em7tCmnBP2iEaqDxBkeG06yK6z4t4qyY)

i use cuda_12.2.2_535.104.05_linux.run to install cuda driver and vllm=0.2.2 , fschat==0.2.23 , run with v100

**Comment by jeejeelee** [comment]
看着像是GPU驱动的CUDA版本低于11.7，用nvidia-smi看下右上角的cuda版本

**Comment by MichaelJayW** [comment]
这个是驱动和runtime不匹配。跟vllm版本别是最新的cuda12.0的就行，v0.1.4我这边跑着正常。你尝试把torch版本控制下改成2.0.1，这个是11编译的torch再试试。

**Comment by iaoxuesheng** [comment]
> 看着像是GPU驱动的CUDA版本低于11.7，用nvidia-smi看下右上角的cuda版本
我的就是11.7

**Comment by iaoxuesheng** [comment]
> 这个是驱动和runtime不匹配。跟vllm版本别是最新的cuda12.0的就行，v0.1.4我这边跑着正常。你尝试把torch版本控制下改成2.0.1，这个是11编译的torch再试试。

torch版本是2.0.1
