### ISSUE TITLE
why "vllm/vllm/entrypoints /api_server.py " will output with prompt?

### ISSUE THREAD

**Issue by PeterXiaTian** [vllm-project/vllm#2659]
how to solve it just like vllm/entrypoints/openai/api_server.py ??

**Comment by PeterXiaTian** [comment]
can use  res["text"][0].replace(prompt,"")  to solve it ?

**Comment by mklf** [comment]
To avoid the case that  prompt is a substring of generation, I use: `res["text"][0][len(prompt):]`

**Comment by mkhludnev** [comment]
+1 Also wondering

**Comment by hmellor** [comment]
This kind of thing usually depends on the model

**Comment by mkhludnev** [comment]
> This kind of thing usually depends on the model

nope. It's explicitly implemented https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py#L77. I suppose it's done for simplifying test/qa routines. Also, it's explicitly noted that api_server is a legacy and not purposed for usage. Users are advised regarding OpenAI endpoint.

**Comment by hmellor** [comment]
Yes, this thread is discussing the OpenAI entrypoint.

**Comment by mkhludnev** [comment]
for openai api it's judged by `echo` request property https://github.com/vllm-project/vllm/blob/63575bc2e197b85ce1c911421ff30c5459e35e9c/vllm/entrypoints/openai/protocol.py#L226
