### ISSUE TITLE
can support qwen-72b-chat-int4? thank you

### ISSUE THREAD

**Issue by wujingbo-web** [vllm-project/vllm#2660]
the following repo has been surrpot qwen-72b-chat-int4,can you merge the code to the main branch ? thank you~~

This repo is a fork of vLLM(Version: 0.2.2), which supports the GPTQ model inference of [Qwen large language models](https://github.ink/QwenLM/Qwen).

https://github.com/QwenLM/vllm-gptq

**Comment by PeterXiaTian** [comment]
yes

**Comment by tutu329** [comment]
qwen官网的那个vllm过时了，最新vllm0.30支持qwen72-int4非常快，只是要注意为了给cudagraph留下空间，每个gpu的vram上限要控在0.8-0.85左右

**Comment by Arcmoon-Hu** [comment]
能正常运行，甚至在老的两张V100上也可以。不过gptq的量化没有完全优化
![image](https://github.com/vllm-project/vllm/assets/50002441/55135a40-5b5f-4715-adbb-141437401090)

**Comment by esmeetu** [comment]
@wujingbo-web FYI, `qwen-72b-chat-int4` use GPTQ quantization which vLLM latest version already supports.

**Comment by shesung** [comment]
> qwen官网的那个vllm过时了，最新vllm0.30支持qwen72-int4非常快，只是要注意为了给cudagraph留下空间，每个gpu的vram上限要控在0.8-0.85左右

请问需要多大显存，48g能跑吗？
