### ISSUE TITLE
Mixtral AWQ result cut short

### ISSUE THREAD

**Issue by p-christ** [vllm-project/vllm#2668]
Whenever I use vLLM with Mixtral AWQ I am finding that the response gets cut short with **'finish_reason': 'length'** 

Even though I have set high values for **--max_tokens** and **--max-model-len**

Does anyone know why this might be?

**Comment by hmellor** [comment]
Where are you setting `max_tokens`? It should be part of your request but, the way you describe it, it sounds like you're passing it as an argument to the server.

If that's not the issue, maybe try playing with the `length_penalty` in your requests?
