### ISSUE TITLE
Support CodeLlama-70b-Instruct-hf

### ISSUE THREAD

**Issue by rliu054** [vllm-project/vllm#2680]
Hi team, 

CodeLlama-70b just got released, https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf

Can we add support for it? Thank you. 

I ran into issues trying to run it with vllm

`
cache_ops.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorESt8optionalIN3c1010ScalarTypeEES5_INS6_6LayoutEES5_INS6_6DeviceEES5_IbEbbS5_INS6_12MemoryFormatEE
`

**Comment by simon-mo** [comment]
Since it is just generic llama we already support it. Which version of vLLM are you using? Did you build from source?

**Comment by the-crypt-keeper** [comment]
I observed the same undefined symbol crash when using `vllm-0.3.0+cu118-cp310-cp310-manylinux1_x86_64.whl` from the Releases.

Building from source via `pip install git+https://github.com/vllm-project/vllm.git@v0.3.0 --index-url https://download.pytorch.org/whl/cu118 --extra-index-url https://pypi.org/simple` got me working with CUDA 11.8

**Comment by gesanqiu** [comment]
I also face this similar undefined symbol issue after I `pip install -e .` of a old version of vllm==0.2.4. Then I pinned pytorch version to 2.1.2 without using `torch >= 2.1.0` in both `requirements.txt` and `pyproject.toml`, it works for me.

**Comment by rliu054** [comment]
thanks, realizing i'm using an very old version of vllm, resolved after upgrading to vllm 0.2.6
