### ISSUE TITLE
Ray Workers `get_ip` failed in the pure IPv6 environment

### ISSUE THREAD

**Issue by Jingru** [vllm-project/vllm#2685]
This line will raise an `Network is unreachable` OSError in the pure IPv6 environment, which fails `_init_workers_ray` method.

https://github.com/vllm-project/vllm/blob/1af090b57d0e23d268e79941f8084bf0a8ad8621/vllm/utils.py#L166

**Comment by Pclanglais** [comment]
Same question…

**Comment by Jingru** [comment]
I fixed it in https://github.com/vllm-project/vllm/pull/2931

**Comment by bestpredicts** [comment]
+1
