### ISSUE TITLE
Streaming not working in VLLM version 0.2.7?

### ISSUE THREAD

**Issue by jayteaftw** [vllm-project/vllm#2694]
Hi, the normal chat completion seems to work; however, whenever I call the streaming parameter it fails.
I am using VLLM verision 0.2.7

First I start, 
`python -m vllm.entrypoints.openai.api_server --model mistralai/Mistral-7B-Instruct-v0.2 --port 8001`

Then I try to run [openai_completion_client.py](https://github.com/vllm-project/vllm/blob/main/examples/openai_completion_client.py)

with the port set to 8001 and `stream=True`

Finally, I get the long error message stating
```
 File "/home/jv/.conda/envs/api_test/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```
I can also see that it is hitting the server with 
```
 exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
INFO 01-31 13:12:40 async_llm_engine.py:111] Finished request cmpl-b4bf714bdf5e45e38124a175e06fe380.
```

**Comment by jayteaftw** [comment]
**Update**

Looks like reinstalling it seemed to have solved the issue

**Comment by Drzhivago264** [comment]
This sometime happens when reboot, I dont know what is going on
