### ISSUE TITLE
 Unknown flag: mount

### ISSUE THREAD

**Issue by attendfov** [vllm-project/vllm#2708]
code tag: v0.2.7
sudo  docker build . --ssh default --target vllm-openai --tag vllm/vllm-openai:1.0
       Sending build context to Docker daemon  7.181MB
       Error response from daemon: Dockerfile parse error line 10: Unknown flag: mount

docker info:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 42
  Running: 2
  Paused: 0
  Stopped: 40
 Images: 28
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-169-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 251.6GiB
 Name: ai-gpu-trainer-02
 ID: IMMV:UKQG:BJSV:BSM6:MYW3:FZFM:LW3W:AFII:IANI:7DC2:WUIK:5BK5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by simon-mo** [comment]
The docker file requires `DOCKER_BUILDKIT=1` to be built, which should be the default in newer version of docker.
