### ISSUE TITLE
BUG: TokenizerGroup doesn't behave like a PreTrainedTokenizer

### ISSUE THREAD

**Issue by saattrupdan** [vllm-project/vllm#2713]
The new [TokenizerGroup](https://github.com/vllm-project/vllm/blob/93b38bea5dd03e1b140ca997dfaadef86f8f1855/vllm/transformers_utils/tokenizer.py#L91) class that `LLM.llm_engine.tokenizer` has now become, doesn't behave like a tokenizer.

For instance, the [LLM.set_tokenizer](https://github.com/vllm-project/vllm/blob/93b38bea5dd03e1b140ca997dfaadef86f8f1855/vllm/entrypoints/llm.py#L116) method sets the `tokenizer` attribute as a `PreTrainedTokenizer`, _not_ a `TokenizerGroup`.

Also, tools like [lm-format-enforcer](https://github.com/noamgat/lm-format-enforcer/tree/main) [assumes that the `tokenizer` attribute is indeed a tokenizer](https://github.com/noamgat/lm-format-enforcer/blob/6a2784bf0b3ecc26b2e031af959cfd0f64f42020/lmformatenforcer/integrations/transformers.py#L58), causing it to now give `AttributeError`s.

It seems like either the `LLM.llm_engine.tokenizer` should revert back to being a `PreTrainedTokenizer`, or otherwise at least have properties and methods which call the corresponding properties and methods of the underlying `PreTrainedTokenizer`.

**Comment by zhuohan123** [comment]
Should be fixed by #2741.
