### ISSUE TITLE
Different from the output of the HF inference

### ISSUE THREAD

**Issue by xcxhy** [vllm-project/vllm#272]
Looking forward to your reply! I set the temperature=0.1, top-k=10, top-p=0.75，I think i infer the same prompt, I will get the same output, through test the hf and vllm inference, HF will get stable output then vllm sometimes get the different output. Is this normal? The parameters of the two inferences are the same and do not bring the same constraints.

**Comment by marscc** [comment]
I have encountered the same problem. I tested on a set of 40 cases and found that the results for 15 cases were different from the results obtained using huggingface.
