### ISSUE TITLE
internlm2-chat-20b ：InternLM2ForCausalLM are not supported for now

### ISSUE THREAD

**Issue by wujingbo-web** [vllm-project/vllm#2721]
please help...

Model architectures ['InternLM2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM', 'YiForCausalLM']
^C

**Comment by seanzhang-zhichen** [comment]
I have same problem, please do you how solve it?

**Comment by ayyyq** [comment]
same issue, any solutions?

**Comment by Harrison-cc** [comment]
internlm2-chat-7b, same issue

**Comment by Harrison-cc** [comment]
> internlm2-chat-7b, same issue

vllm==0.3.1 fix my problem

**Comment by esmeetu** [comment]
@wujingbo-web @seanzhang-zhichen @ayyyq [v0.3.1](https://github.com/vllm-project/vllm/releases/tag/v0.3.1) has already support that! Please check it out.
