### ISSUE TITLE
[BUG] Compile source code error for ROCM platform when using #include <hip/hip_bf16.h>

### ISSUE THREAD

**Issue by lhcalibur** [vllm-project/vllm#2725]
As mentioned in #https://github.com/vllm-project/vllm/issues/2646 

Building for ROCM platform will cause  multiple definition error, 

**This is caused by The function in <hip/hip_bf16.h> being defined without _static inline_ , which will cause multi definition error when using this header file in multi .cu/.hip files.**

#https://github.com/ROCm/HIP/issues/3403

The error will be fixed in future releases of ROCM, but till ROCM-6.0.2, this has not been fixed yet, maybe we need to find a way to bypass this. 

Maybe using hip_bfloat16 instead of __hip_bfloat16? #https://github.com/ROCm/ROCm/issues/2534, but needs some code modification.

**Comment by jamestwhedbee** [comment]
Running into this as well

**Comment by hongxiayang** [comment]
I am working on a fix for this issue now. Will update when I have a pull request

**Comment by hongxiayang** [comment]
Fix for vllm ROCm 6.0 build is here: https://github.com/vllm-project/vllm/pull/2790
