### ISSUE TITLE
Mixtral GPTQ with TP=2 not generating output

### ISSUE THREAD

**Issue by SebastianBodza** [vllm-project/vllm#2728]
In the new vllm 0.3 release mixtral with gptq does not generate any output anymore. Loading the model works fine, when calling the `llm.generate` it gets stuck. 

```
from vllm import SamplingParams
import torch 

model_name = "TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ"
llm = vllm.LLM(model=model_name, quantization="gptq", dtype=torch.float16, tensor_parallel_size=2, max_model_len=16000, revision="gptq-4bit-32g-actorder_True", gpu_memory_utilization=0.75, enforce_eager=False)
llm.generate(formatted_prompt[0], sampling_params=SamplingParams(temperature=0.1, max_tokens=100))
```

Currently using: 
- python 3.11.* 
- vllm-0.3.0+cu123 -> tried also the current git repo
- cuda 12.3

The worker seems to be stuck in the `llm_engine.step()` function / `_run_workers` call.

**Comment by hanzhi713** [comment]
Can you try adding `disable_custom_all_reduce=True`? Just ruling out a possibility.

**Comment by adi** [comment]
I have the same issue with AWQ and this config:

```python
llm = LLM(
    model="TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ",
    tensor_parallel_size=2,
    gpu_memory_utilization=0.75,
    max_model_len=256,
    disable_custom_all_reduce=True,
    enforce_eager=True
)
```

**Comment by adi** [comment]
This works fine for me:

```python
llm = LLM(
    model="TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ",
    quantization="gptq",
    dtype=torch.float16,
    tensor_parallel_size=2,
    max_model_len=16384,
    revision="gptq-4bit-32g-actorder_True",
    gpu_memory_utilization=0.75,
    disable_custom_all_reduce=True,
    enforce_eager=True)
```

**Comment by ivysdad** [comment]
> I have the same issue with AWQ and this config:
> 
> ```python
> llm = LLM(
>     model="TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ",
>     tensor_parallel_size=2,
>     gpu_memory_utilization=0.75,
>     max_model_len=256,
>     disable_custom_all_reduce=True,
>     enforce_eager=True
> )
> ```

I think there is an issue with that awq quant specifically, try using this one: https://huggingface.co/casperhansen/mixtral-instruct-awq

it worked for me! just be sure to set enforce_eager=True like you did before

**Comment by SebastianBodza** [comment]
@hanzhi713 Thanks! Works with the disable_custom_all_reduce command

**Comment by hanzhi713** [comment]
@SebastianBodza Which GPU model are you using?

**Comment by SebastianBodza** [comment]
@hanzhi713 2x RTX 3090 with Cuda 12.3

**Comment by hanzhi713** [comment]
@SebastianBodza Can you try this potential fix? https://github.com/vllm-project/vllm/pull/2760

Remember to recompile vLLM from source by `pip install -e .`

**Comment by SebastianBodza** [comment]
Still not working for me. I don't know if it is relevant, but I have to run NCCL_P2P_DISABLE=1 to load the model

**Comment by SinanAkkoyun** [comment]
> I think there is an issue with that awq quant specifically, try using this one: https://huggingface.co/casperhansen/mixtral-instruct-awq

it worked for me! just be sure to set enforce_eager=True like you did before

For me, this also resolved the issue

**Comment by hanzhi713** [comment]
> Still not working for me. GPUs stuck at 150W usage and not returning. I don't know if it is relevant, but I have to run NCCL_P2P_DISABLE=1 to load the model

@SebastianBodza What error do you observe when you don't set NCCL_P2P_DISABLE=1? This might be relevant since if you can't let NCCL use P2P, custom all reduce shouldn't use it too, and custom all reduce can't function without P2P.

**Comment by SebastianBodza** [comment]
When not setting NCCL_P2P_DISABLE=1 the Model loading freezes. Just like in  https://github.com/vllm-project/vllm/issues/1801

**Comment by hanzhi713** [comment]
@SebastianBodza I see. Then it's expected that it will also freeze with custom all reduce enabled. The underlying cause might be like #1801 in which the driver is buggy.

**Comment by SebastianBodza** [comment]
@hanzhi713 Thanks for the fixes. I am not too sure if they were necessary, however SinanAkkoyun seems to approve them, sorry for that. Could we add a check for P2P and implement a fallback with disable_custom_all_reduce enabled or throwing an error? 

For me the vllm version 0.3.0 is working with nvidia drivers 535.154.05. 
Anybody relying on the official nvidia stream for rhel 9 just downgrade.

**Comment by SinanAkkoyun** [comment]
@SebastianBodza Hi, I didn't approve any changes, I just approved that the other awq model provided + enforce_eager=True works for me, does it for you?

**Comment by hanzhi713** [comment]
> @hanzhi713 Thanks for the fixes. I am not too sure if they were necessary, however SinanAkkoyun seems to approve them, sorry for that. Could we add a check for P2P and implement a fallback with disable_custom_all_reduce enabled or throwing an error?
> 
> For me the vllm version 0.3.0 is working with nvidia drivers 535.154.05. Anybody relying on the official nvidia stream for rhel 9 just downgrade.

@SebastianBodza Unfortunately, I don't think there's a good way to detect that. We already checked P2P support via cuda runtime API (NCCL likely uses the same check), and the check passed. Basically, the problem is that the runtime reports that it supports P2P, but the underlying implementation is buggy.

**Comment by andrewgross** [comment]
I ran in to this with exllamav2 as well, the maintainer added a fix that just did a quick check to see if it was safe to move tensors between devices, and used that to determine if it was safe. The Nvidia drivers seem to have consistent issues on 4090s properly reporting this info.

https://github.com/turboderp/exllamav2/blob/1c67f97f3d2a968605a9c31ab791a05c85bb7879/exllamav2/compat.py#L10

https://github.com/turboderp/exllamav2/issues/85
