### ISSUE TITLE
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by hubingqian2011** [vllm-project/vllm#2735]
(vllm) PS C:\Users\hub1\gen-ai-training-abshek\gen-ai-training\vllm-main> pip install -e .
Looking in indexes: http://art.nwie.net/artifactory/api/pypi/pypi/simple
Obtaining file:///C:/Users/hub1/gen-ai-training-abshek/gen-ai-training/vllm-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done  
  Preparing editable metadata (pyproject.toml) ... done
Collecting ninja (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/b6/2f/a3bc50fa63fc4fe9348e15b53dc8c87febfd4e0c660fcf250c4b19a3aa3b/ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Requirement already satisfied: psutil in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from vllm==0.3.0) (5.9.8)
Collecting ray>=2.9 (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/a2/77/2cd1967982ef518065f181f5273e2bdf84cdcda586941b307c7f17aaad16/ray-2.9.1-cp311-cp311-win_amd64.whl (25.6 MB)
Collecting sentencepiece (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/cc/07/d6951e3b4079df819d76353302fc3e76835252e7e0b6366f96a03d87ea5f/sentencepiece-0.1.99-cp311-cp311-win_amd64.whl (977 kB)
Requirement already satisfied: numpy in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from vllm==0.3.0) (1.26.3)
Collecting torch==2.1.2 (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/e4/ae/2ad8820045b6631965750435f28583e80905b8273d57cf026163b51323ee/torch-2.1.2-cp311-cp311-win_amd64.whl (192.3 MB)
Requirement already satisfied: transformers>=4.37.0 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from vllm==0.3.0) 
(4.37.2)
Collecting xformers==0.0.23.post1 (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/db/3f/44472a4f59a735a1355061619a52c96973b8eaeda2eff4d0e71e782decd1/xformers-0.0.23.post1-cp311-cp311-win_amd64.whl (201.1 MB)
Collecting fastapi (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/e3/cb/fa5122eec49e6bca91d3a332a3bc1dff3c12d093228e9e524cad3a7f1039/fastapi-0.109.1-py3-none-any.whl (92 kB)
Collecting uvicorn[standard] (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/c7/f3/29caa83f5795b20ed3aca357c648f3ae995ff6ff08e38b22387017abbdc5/uvicorn-0.27.0.post1-py3-none-any.whl (60 kB)
Collecting pydantic>=2.0 (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/e4/37/3ffe6e7daa1ea1b4bf5228807a92ccbae538cf57c0c50b93564c310c11a8/pydantic-2.6.0-py3-none-any.whl (394 kB)
Collecting aioprometheus[starlette] (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/91/21/c9e882ea8a7189b7d71ffb709db24708113896e81a25e074a17f9874d8be/aioprometheus-23.12.0-py3-none-any.whl (31 kB)
Collecting pynvml==11.5.0 (from vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/5b/9c/adb8070059caaa15d5a572b66bccd95900d8c1b9fa54d6ecea6ae97448d1/pynvml-11.5.0-py3-none-any.whl (53 kB)
Requirement already satisfied: filelock in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) (3.9.0)
Requirement already satisfied: typing-extensions in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) (4.8.0)
Requirement already satisfied: sympy in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) (1.12)
Requirement already satisfied: networkx in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) 
(3.1.2)
Requirement already satisfied: fsspec in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from torch==2.1.2->vllm==0.3.0) 
(2023.12.2)
Collecting annotated-types>=0.4.0 (from pydantic>=2.0->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/28/78/d31230046e58c207284c6b2c4e8d96e6d3cb4e52354721b944d3e1ee4aa5/annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.16.1 (from pydantic>=2.0->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/b2/47/14bf2397a5daa0cc1b99306499a39525966b73aba4d31b17e373e229f07e/pydantic_core-2.16.1-cp311-none-win_amd64.whl (1.9 MB)
Collecting click>=7.0 (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (97 kB)
Collecting jsonschema (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/39/9d/b035d024c62c85f2e2d4806a59ca7b8520307f34e0932fbc8cc75fe7b2d9/jsonschema-4.21.1-py3-none-any.whl (85 kB)
Collecting msgpack<2.0.0,>=1.0.0 (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/b4/3d/c8dd23050eefa3d9b9c5b8329ed3308c2f2f80f65825e9ea4b7fa621cdab/msgpack-1.0.7-cp311-cp311-win_amd64.whl (222 kB)
Requirement already satisfied: packaging in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from ray>=2.9->vllm==0.3.0) (23.2)
Collecting protobuf!=3.19.5,>=3.15.3 (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/c1/00/c3ae19cabb36cfabc94ff0b102aac21b471c9f91a1357f8aafffb9efe8e0/protobuf-4.25.2-cp310-abi3-win_amd64.whl (413 kB)
Requirement already satisfied: pyyaml in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from ray>=2.9->vllm==0.3.0) (6.0.1)
Collecting aiosignal (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting frozenlist (from ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/b3/21/c5aaffac47fd305d69df46cfbf118768cdf049a92ee6b0b5cb029d449dcf/frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
Requirement already satisfied: requests in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from ray>=2.9->vllm==0.3.0) (2.28.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from transformers>=4.37.0->vllm==0.3.0) (0.20.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from transformers>=4.37.0->vllm==0.3.0) (2023.12.25)
Requirement already satisfied: tokenizers<0.19,>=0.14 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from transformers>=4.37.0->vllm==0.3.0) (0.15.1)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from transformers>=4.37.0->vllm==0.3.0) (0.4.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from transformers>=4.37.0->vllm==0.3.0) (4.66.1)
Collecting orjson (from aioprometheus[starlette]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/41/c5/ac4a0f8a1ae80373f4dce810f861cb2bab4aded9ceccc510d73b966fb607/orjson-3.9.12-cp311-none-win_amd64.whl (134 kB)
Collecting quantile-python>=1.1 (from aioprometheus[starlette]->vllm==0.3.0)
  Using cached quantile_python-1.1-py3-none-any.whl
Collecting starlette>=0.14.2 (from aioprometheus[starlette]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/69/bf/b8f2c0e1dd2a314712994e25405e6b03ed0d27795305aa68a22da08ffb01/starlette-0.36.2-py3-none-any.whl (71 kB)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/03/13/c60c738da2fb69d60ee1dc5631e8d152352003cc0bc4ce39582bdd90e293/starlette-0.35.1-py3-none-any.whl (71 kB)
Collecting h11>=0.8 (from uvicorn[standard]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl (58 kB)
Requirement already satisfied: colorama>=0.4 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from uvicorn[standard]->vllm==0.3.0) (0.4.6)
Collecting httptools>=0.5.0 (from uvicorn[standard]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/14/e4/20d28dfe7f5b5603b6b04c33bb88662ad749de51f0c539a561f235f42666/httptools-0.6.1-cp311-cp311-win_amd64.whl (55 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/f3/dc/2a8a447b783f5059c4bf7a6bad8fe59375a5a9ce872774763b25c21c2860/watchfiles-0.21.0-cp311-none-win_amd64.whl (280 kB)
Collecting websockets>=10.4 (from uvicorn[standard]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/d1/40/6b169cd1957476374f51f4486a3e85003149e62a14e6b78a958c2222337a/websockets-12.0-cp311-cp311-win_amd64.whl (124 kB)
Collecting anyio<5,>=3.4.0 (from starlette>=0.14.2->aioprometheus[starlette]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/bf/cd/d6d9bb1dadf73e7af02d18225cbd2c93f8552e13130484f1c8dcfece292b/anyio-4.2.0-py3-none-any.whl (85 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from jinja2->torch==2.1.2->vllm==0.3.0) (2.1.3)
Collecting attrs>=22.2.0 (from jsonschema->ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/e0/44/827b2a91a5816512fcaf3cc4ebc465ccd5d598c45cefa6703fcf4a79018f/attrs-23.2.0-py3-none-any.whl (60 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/ee/07/44bd408781594c4d0a027666ef27fab1e441b109dc3b76b4f836f8fd04fe/jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4 (from jsonschema->ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/90/10/1c92edb0a0a14b67ff825bc338e74bc49ab27d3f3bae3f9a02838cba546f/referencing-0.33.0-py3-none-any.whl (26 kB)
Collecting rpds-py>=0.7.1 (from jsonschema->ray>=2.9->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/a5/c8/294d93e3412add229583edb6d4016af18a60deecc3a96c33ffcb00ae363b/rpds_py-0.17.1-cp311-none-win_amd64.whl (205 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from requests->ray>=2.9->vllm==0.3.0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from requests->ray>=2.9->vllm==0.3.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from requests->ray>=2.9->vllm==0.3.0) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from requests->ray>=2.9->vllm==0.3.0) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\lib\site-packages (from sympy->torch==2.1.2->vllm==0.3.0) (1.3.0)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette>=0.14.2->aioprometheus[starlette]->vllm==0.3.0)
  Using cached http://art.nwie.net/artifactory/api/pypi/pypi/packages/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl (10 kB)
Building wheels for collected packages: vllm
  Building editable for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building editable for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [145 lines of output]
      C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
      running editable_wheel
      creating C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info
      writing C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\PKG-INFO
      writing dependency_links to C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\dependency_links.txt
      writing requirements to C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\requires.txt
      writing top-level names to C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\top_level.txt
      writing manifest file 'C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\SOURCES.txt'
      reading manifest file 'C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm.egg-info\SOURCES.txt'
      creating 'C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm-0.3.0.dist-info'
      C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\wheel\bdist_wheel.py:108: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
        if get_flag("Py_DEBUG", hasattr(sys, "gettotalrefcount"), warn=(impl == "cp")):
      creating C:\Users\hub1\AppData\Local\Temp\pip-wheel-_znvpwgw\.tmp-dbxwqjd8\vllm-0.3.0.dist-info\WHEEL
      running build_py
      running build_ext
      C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\utils\cpp_extension.py:383: UserWarning: Error checking 
compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      Traceback (most recent call last):
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run     
          _build_ext.run(self)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 525, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 407, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, 
in parse
          return Version(version)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\dist.py:988: _DebuggingTips: Problem in 
editable installation.
      !!
     
              ********************************************************************************
              An error happened while installing `vllm` in editable mode.
     
              The following steps are recommended to help debug this problem:
     
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
     
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
     
                  https://github.com/pypa/setuptools/issues
     
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
     
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "C:\Users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\gen-ai-training-abshek\gen-ai-training\vllm\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\build_meta.py", line 436, in build_editable          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup     
          exec(code, locals())
        File "<string>", line 406, in <module>
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup    
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run     
          _build_ext.run(self)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 525, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\torch\utils\cpp_extension.py", line 407, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, 
in parse
          return Version(version)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\hub1\AppData\Local\Temp\pip-build-env-3da0b9t3\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: expected string or bytes-like object, got 'NoneType'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for vllm
Failed to build vllm
ERROR: Could not build wheels for vllm, which is required to install pyproject.toml-based projects

Dear all, anyone have met such error? Thank you so much for your help!!!

**Comment by keli-wen** [comment]
I recommend formatting your error log using a code block for clarity. You can do this as follows:

```
[Your error log here]
```

Additionally, it would be helpful to know **your GPU driver version and CUDA version**. You can obtain this information by executing the commands `nvidia-smi` and `nvcc -v`. I suspect that the issue you are encountering may be related to `CUDA` version.

**Comment by kvikk** [comment]
Same thing happening. 
On a GC T4 instance.

Tesla T4 -  NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

Linux instance-20240215-153545 5.10.0-27-cloud-amd64 #1 SMP Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux

gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Comment by alexngng** [comment]
same issue。
