### ISSUE TITLE
How to increase vllm scheduler promt limit?

### ISSUE THREAD

**Issue by hanswang1** [vllm-project/vllm#2737]
Hi,

I am using FastChat vicuna-7b-v1.5 model with vllm worker.
When chatting with back-end, I encountered prompt limitation in scheduler.py.

![MicrosoftTeams-image (19)](https://github.com/vllm-project/vllm/assets/6904705/29f22c61-53e6-4987-86ef-22a310fde7b2)

May I know how to increase the number of prompt limitation in scheduler.py?

**Comment by LiuXiaoxuanPKU** [comment]
Based on [this](vllm.readthedocs.io/en/latest/getting_started/quickstart.html), vicuna-7b-v1.5 only supports 4K context length. vllm checks max model length (reading from model config) and throw the warning here.

**Comment by hanswang1** [comment]
> Based on [this](vllm.readthedocs.io/en/latest/getting_started/quickstart.html), vicuna-7b-v1.5 only supports 4K context length. vllm checks max model length (reading from model config) and throws the warning here.

I change vicuna-7b-v1.5 to vicuna-7b-v1.5-16k, and change the arguments like below:

args: ["-m", "fastchat.serve.vllm_worker", "--model-path", "lmsys/vicuna-7b-v1.5-16k", "--worker-address", "http://fastchat-model-worker:21002", "--controller-address", "http://svc-fc-controller:21001", "--host", "0.0.0.0", "--port", "21002", "--gpu_memory_utilization", "0.998", "--max-model-len", "8192", "--max-num-batched-tokens", "8192"]

The prompt limitation has been pass, however I still got another error: "Input prompt (4644 tokens) is too long and exceeds the capacity of block_manager"
The log is below:
![image](https://github.com/vllm-project/vllm/assets/6904705/acad6893-fd03-4efa-a1f1-e9024fb414bd)

May I know how to solve this problem?

**Comment by hmellor** [comment]
This happens if `self.num_total_gpu_blocks - num_required_blocks < self.watermark_blocks` is `True`.

**Comment by hmellor** [comment]
> which does not have a max_length set to 2048

Yes it does

https://huggingface.co/HuggingFaceTB/SmolLM-1.7B/blob/72784557ea07bfbabb4cfe3b5e34c49e047708bd/config.json#L14
