### ISSUE TITLE
Will we update to pytorch v2.2.0 ?

### ISSUE THREAD

**Issue by jony0113** [vllm-project/vllm#2738]
pytorch v2.2.0 has already release, will we update the next version? the version v2.1.2 has a bug which will cause oom while the newest version has already fixed. https://github.com/pytorch/pytorch/issues/106294

**Comment by janelu9** [comment]
Not supported yet, I tied to built it, but failed.

**Comment by hmellor** [comment]
Closing as a duplicate of #2722
