### ISSUE TITLE
When using tp =2 to inference model in greedy mode  and vllm 0.3 , results are random

### ISSUE THREAD

**Issue by WangErXiao** [vllm-project/vllm#2742]
When using tp =2 to inference model in greedy model  and vllm 0.3 , the results are random, not same. But when I use --disable-custom-all-reduce, it's ok. My model structure is same to llama. I don't know why ?

**Comment by WoosukKwon** [comment]
Hi @WangErXiao, thanks for reporting the bug. Could you share more details about your environments (e.g., GPUs, prompts, etc.) so that we can reproduce the bug?

**Comment by WangErXiao** [comment]
> Hi @WangErXiao, thanks for reporting the bug. Could you share more details about your environments (e.g., GPUs, prompts, etc.) so that we can reproduce the bug?

I used L40S , Driver Version: 535.129.03   CUDA Version: 12.2

**Comment by hmellor** [comment]
@WangErXiao are you still experiencing this issue on the latest version of vLLM?
