### ISSUE TITLE
4 times memory usage comparing to text-generation-webui

### ISSUE THREAD

**Issue by rezaalavi** [vllm-project/vllm#2748]
I am using **TheBloke_deepseek-coder-6.7B-instruct-GPTQ**  as our model, which is a GPTQ quantized as the name suggests.

When I run it in text-generation-webui the memory usage is around **4894MB** while when I use the following command to run it using VLLM the memory usage is **17164MiB** which is almost 4 times as large.

`python -m vllm.entrypoints.openai.api_server --model ../text-generation-webui/models/TheBloke_deepseek-coder-6.7B-instruct-GPTQ --dtype float16 --max-model-len 16000 --gpu-memory-utilization .7 --quantization gpt`

Am I missing something here, or there is a memory leaking issue?

**Comment by enriquedealba** [comment]
I'm also running into similar issues

**Comment by rezaalavi** [comment]
Closing as this seems to be the expected behaviour.
