### ISSUE TITLE
Possible sampling parameter bug in VLLM Server 

### ISSUE THREAD

**Issue by Vincent-Li-9701** [vllm-project/vllm#2754]
I'm using VLLM 0.3.0
How I start an async server:
`python -m vllm.entrypoints.openai.api_server  --model mistralai/Mixtral-8x7B-Instruct-v0.1 --tensor-parallel-size 8`

How I do my server call:
```
import json

import requests

headers = {
    "Content-Type": "application/json",
}

data = {
    "model": 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    "prompt": "What's your name",
    "temperature": 0.000001,
    "max_tokens": 256,
    "top_k": 3, 
}
print(data)
response = requests.post(
    "http://localhost:8000/v1/completions", headers=headers, data=json.dumps(data)
)
text = response.json()["choices"][0]["text"]
print(text)
```

Server log output
`INFO 02-05 06:07:10 async_llm_engine.py:431] Received request cmpl-138b6b226481411891d25fb8673422fb-0: prompt: None, prefix_pos: None,sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1e-06, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=256, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: [1, 1824, 28742, 28713, 574, 1141], lora_request: None.`

Notice that the top_k is still -1. max_tokens aligns with my specification.

Is this the right way to send request? Or there is a bug on this? Thanks in advanced.

**Comment by Vincent-Li-9701** [comment]
I notice the issue is that I can't set both temperature and top_p. Is this expected? Sample decode should allow both parameters to be adjustable right?

**Comment by liangxfng** [comment]
> I notice the issue is that I can't set both temperature and top_p. Is this expected? Sample decode should allow both parameters to be adjustable right?

There is a special handling in "sampling_params. py", around 150 lines

**Comment by Vincent-Li-9701** [comment]
Thanks. Found out that [there](https://github.com/vllm-project/vllm/blob/c9b45adeeb0e5b2f597d1687e0b8f24167602395/vllm/sampling_params.py#L153) is a minimum requirement of temperature otherwise it will be treated as greedy.
