### ISSUE TITLE
multimodal support

### ISSUE THREAD

**Issue by qiuhuiGithub** [vllm-project/vllm#2757]
Hi, Can vllm support multimodal LLM? such as Qwen-vl, yi-vl-6b, mplug-owl2, etc

**Comment by ruifengma** [comment]
I have the same question, currently the multimodal LLM is not supported by the framework?

**Comment by AllenDun** [comment]
+1

**Comment by DarkLight1337** [comment]
With the merge of #6121, we will have a dev API that is relatively stable. Please refer to #4194 for more details.
