### ISSUE TITLE
How is the context (conversation history) maintained during a multi-turn conversation ? 

### ISSUE THREAD

**Issue by ujjawal-ti** [vllm-project/vllm#2766]
Hi,
Thanks for this awesome repository.
I'm curious to know the following,
1. maximum context length (including previous conversation history) supported during a multi-turn conversation. 
2. How is it handled in the case of vLLM? 
3.  Is the conversation history maintained similar to the Langchain (Memory Buffer, Summary Buffer, Context window buffer, Hybrid)

**Comment by hmellor** [comment]
The list of messages is formatted into a single prompt using the chat template provided by the model on the HF Hub (or the `--chat-template` argument when starting the server), then this prompt is used by the model to generate the latest response.

It is up to the client application to maintain conversation history and memory.

**Comment by ujjawal-ti** [comment]
Thanks @hmellor !!  Got it.
