### ISSUE TITLE
Import FlashInfer: 3x faster PagedAttention than vLLM

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#2767]
It looks like vLLM could directly import the PagedAttention kernels from FlashInfer to support GQA. "*For batch GQA decoding attention, FlashInfer w/ Tensor Cores is 3x faster than vLLM PagaAttention when batch_size=64.*" @WoosukKwon 

https://github.com/flashinfer-ai/flashinfer/
https://flashinfer.ai/2024/02/02/introduce-flashinfer.html

![image](https://github.com/vllm-project/vllm/assets/27340033/48d40b10-a5d0-4ea3-9c9f-53cc8a7bca4a)

**Comment by sumo43** [comment]
Made a draft PR implementing flashinfer. Would love to help merge it. https://github.com/vllm-project/vllm/pull/2772
