### ISSUE TITLE
load official models other than HF models 

### ISSUE THREAD

**Issue by VpkPrasanna** [vllm-project/vllm#2783]
does vllm load the models which are supported from huggingface ?
when i tried to load the official llama models via llm it failed with an error stating config.json is missing

**Comment by simon-mo** [comment]
Can you show the code that reproduced the error? If it is a local model, we expect the path to contain `config.json`, which is required for all huggingface model checkpoints.

**Comment by VpkPrasanna** [comment]
> Can you show the code that reproduced the error? If it is a local model, we expect the path to contain `config.json`, which is required for all huggingface model checkpoints.

but i am using non hf models like this [model](https://huggingface.co/meta-llama/Llama-2-7b-chat)
