### ISSUE TITLE
[Bug] `v0.3.0` produces garbage output when serving CodeLlama-70B on 4xA6000

### ISSUE THREAD

**Issue by ganler** [vllm-project/vllm#2788]
![image](https://github.com/vllm-project/vllm/assets/38074777/5f8862cf-4ef8-4bd1-a259-b67aadeabc29)

Can be fixed by downgrading to `v0.2.7`.

**Comment by hanzhi713** [comment]
@ganler Can you try adding `disable_custom_all_reduce=True`?
