### ISSUE TITLE
openai completions api <echo=True> raises Error

### ISSUE THREAD

**Issue by seoyunYang** [vllm-project/vllm#2813]
hello,
when i send echo=True through the openai completions api for an openai compatible vllm server with llama-2-7b-hf, i get an "[_client.py:1027] HTTP Request: POST ... 500 Internal Server Error" error.
Any suggestions on how i can fix this or why this is happening? I want to know what the other parameters need to be for echo=True to work for [examples/openai_completion_client.py](https://github.com/vllm-project/vllm/blob/3711811b1d2956e83e626c72f0e1607f2dfbc8fb/examples/openai_completion_client.py#L18C1-L24C16). It works fine when echo=False

**Comment by seoyunYang** [comment]
Think this is just a bug in v0.3.0 so I'm closing the issue.

**Comment by camaccount** [comment]
Try using echo=true
