### ISSUE TITLE
cuda 11.7

### ISSUE THREAD

**Issue by gassannov** [vllm-project/vllm#2824]
is it possible to run any version of vllm on cuda 11.7

**Comment by hmellor** [comment]
The build job in GitHub Actions suggests that vLLM is built and for the following environments: https://github.com/vllm-project/vllm/blob/2daf23ab0cf00da157b1255faddcf0a269283d36/.github/workflows/publish.yml#L49-L53

There are also some references in the code to the use of cuda versions lower than 11.8: https://github.com/vllm-project/vllm/blob/2daf23ab0cf00da157b1255faddcf0a269283d36/setup.py#L254 https://github.com/vllm-project/vllm/blob/2daf23ab0cf00da157b1255faddcf0a269283d36/vllm/config.py#L343 https://github.com/vllm-project/vllm/blob/2daf23ab0cf00da157b1255faddcf0a269283d36/vllm/engine/arg_utils.py#L143-L145

So it _might_ work, but if you can use 11.8 or 12.1 I would recommend that.
