### ISSUE TITLE
Support for TPU hardware

### ISSUE THREAD

**Issue by alboimDor** [vllm-project/vllm#2835]
I've noticed the [roadmap for 2024Q1](https://github.com/vllm-project/vllm/issues/2681) includes adding support for Google's TPU hardware.
Is this issue still being considered?

Thank you

**Comment by DavidPeleg6** [comment]
+1

**Comment by chujiezheng** [comment]
+1

**Comment by qeternity** [comment]
I would expect so. Not clear why there hasn't been more demand for it. This chart from Google last year benchmarking TPUv4 is pretty sexy.

![image](https://github.com/vllm-project/vllm/assets/33002121/df5de63f-ae75-476e-b0d6-f7af964959eb)

**Comment by rick-c-goog** [comment]
+1

**Comment by DarkLight1337** [comment]
It is supported now: https://docs.vllm.ai/en/latest/getting_started/tpu-installation.html
