### ISSUE TITLE
Distributed batch inference example does not work

### ISSUE THREAD

**Issue by seungduk-yanolja** [vllm-project/vllm#2840]
There is an example of batch inference from multiple GPUs.
[https://github.com/vllm-project/vllm/commit/4abf6336ec65c270343eb895e7b18786e9274176](https://github.com/vllm-project/vllm/commit/4abf6336ec65c270343eb895e7b18786e9274176)

However, running this code throws an error because the llm instance is not serializable.
To make it run, I hade to modify the code as follows:

```python
class Predictor:
    def __init__(self):
        pass
 
    def __call__(self, batch: Dict[str, np.ndarray]) -> Dict[str, list]:
        # prepare samples...
 
        llm = LLM(model="model name")
 
        # Generate translations from the prompts.
        outputs = llm.generate(prompts, sampling_params)
         
        del llm
        llm = None
        destroy_model_parallel()
         
        gc.collect()
 
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        if torch.backends.mps.is_available():
            torch.mps.empty_cache()
        torch.cuda.synchronize()
 
        # process...
 
        return result
```

**Comment by simon-mo** [comment]
cc @c21 @zhe-thoughts

**Comment by c21** [comment]
Hi @seungduk-yanolja, can you share the full code (when it does not work) and the error stack trace? Thanks.

The error of not serializable usually happens when the object is created outside of class. In this case, `LLM` object is created inside class - `__init__()`, so there should be no serialization happened across machines.

**Comment by c21** [comment]
Another thing to note here is - when passing `LLMPredictor` to `Dataset.map_batches()`, you should pass the **class itself** ([code](https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_distributed.py#L46)).

Have you passed the object `LLMPredictor()` by any chance? That would trigger the `__init__` of object in head node, and cause serialization to worker node.

**Comment by hmellor** [comment]
Closing as stale
