### ISSUE TITLE
Missing prometheus metrics in `0.3.0`

### ISSUE THREAD

**Issue by SamComber** [vllm-project/vllm#2850]
First of all, thanks for the great open source library!

The docs promise a few more additional metrics that I'm not seeing in vLLM 0.3.0, have these been removed? I.e. if I hit `/metrics` of the OpenAI API server for a deployed model... you'll see no `vllm:time_to_first_token_seconds` or `vllm:time_per_output_token_seconds` or `vllm:e2e_request_latency_seconds`

<img width="400" alt="image" src="https://github.com/vllm-project/vllm/assets/9962584/401668ef-2798-4cb8-b548-d140f8c11d2e">

**Comment by rib-2** [comment]
I think a new release will be pushed soon -> https://github.com/vllm-project/vllm/issues/2859

**Comment by grandiose-pizza** [comment]
> d the image I'm pulling for the deployment uses vllm/engine/metrics.py from `v0.3.0`, not the tip of main.
> 
> Would it be possible to push another image ver

Hi, 

@SamComber 
I want to use the metrics but I see something completely different. I have exposed an API using the [api_server.py](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py)
 

When I do a `http://localhost:8075/metrics/`, I get the following instead of seeing the values as described in the [Metrics Class](https://docs.vllm.ai/en/latest/serving/metrics.html), How to see those metrics? :

```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 6290.0
python_gc_objects_collected_total{generation="1"} 8336.0
python_gc_objects_collected_total{generation="2"} 4726.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 826.0
python_gc_collections_total{generation="1"} 75.0
python_gc_collections_total{generation="2"} 6.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="10",patchlevel="12",version="3.10.12"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 3.098353664e+010
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 7.31774976e+08
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.71188972784e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 18.27
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 44.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
```

**Comment by hmellor** [comment]
@grandiose-pizza did you start your server with `--disable-log-stats`? That will prevent the Prometheus metrics from being updated.

**Comment by grandiose-pizza** [comment]
@hmellor , no It is set to false while starting:

```
INFO worker.py:1752 -- Started a local Ray instance.
ens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_chunked_prefill=False, engine_use_ray=True, disable_log_requests=False, max_log_len=None)
```

**Comment by hmellor** [comment]
Also it's worth noting that what you're seeing is different because the original screenshot was taken before we switched from `aioprometheus` (third party) to `prometheus_client` (first party).

**Comment by grandiose-pizza** [comment]
Could you please share what is expected while using prometheus_client instead?

Is it different than the comment above?
https://github.com/vllm-project/vllm/issues/2850#issuecomment-2028747162

**Comment by hmellor** [comment]
Changing Prometheus client packages only changes the non-`vllm:...` metrics, which is wat you observed.

The `vllm:...` metrics should be unchanged.

**Comment by grandiose-pizza** [comment]
It is quite strange. Trying to figure how to obtain the stats like here:
https://github.com/vllm-project/vllm/blob/563c1d7ec56aa0f9fdc28720f3517bf9297f5476/vllm/engine/metrics.py#L20

**Comment by yabea** [comment]
> > d the image I'm pulling for the deployment uses vllm/engine/metrics.py from `v0.3.0`, not the tip of main.
> > Would it be possible to push another image ver
> 
> Hi,
> 
> @SamComber I want to use the metrics but I see something completely different. I have exposed an API using the [api_server.py](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py)
> 
> When I do a `http://localhost:8075/metrics/`, I get the following instead of seeing the values as described in the [Metrics Class](https://docs.vllm.ai/en/latest/serving/metrics.html), How to see those metrics? :
> 
> ```
> # HELP python_gc_objects_collected_total Objects collected during gc
> # TYPE python_gc_objects_collected_total counter
> python_gc_objects_collected_total{generation="0"} 6290.0
> python_gc_objects_collected_total{generation="1"} 8336.0
> python_gc_objects_collected_total{generation="2"} 4726.0
> # HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
> # TYPE python_gc_objects_uncollectable_total counter
> python_gc_objects_uncollectable_total{generation="0"} 0.0
> python_gc_objects_uncollectable_total{generation="1"} 0.0
> python_gc_objects_uncollectable_total{generation="2"} 0.0
> # HELP python_gc_collections_total Number of times this generation was collected
> # TYPE python_gc_collections_total counter
> python_gc_collections_total{generation="0"} 826.0
> python_gc_collections_total{generation="1"} 75.0
> python_gc_collections_total{generation="2"} 6.0
> # HELP python_info Python platform information
> # TYPE python_info gauge
> python_info{implementation="CPython",major="3",minor="10",patchlevel="12",version="3.10.12"} 1.0
> # HELP process_virtual_memory_bytes Virtual memory size in bytes.
> # TYPE process_virtual_memory_bytes gauge
> process_virtual_memory_bytes 3.098353664e+010
> # HELP process_resident_memory_bytes Resident memory size in bytes.
> # TYPE process_resident_memory_bytes gauge
> process_resident_memory_bytes 7.31774976e+08
> # HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
> # TYPE process_start_time_seconds gauge
> process_start_time_seconds 1.71188972784e+09
> # HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
> # TYPE process_cpu_seconds_total counter
> process_cpu_seconds_total 18.27
> # HELP process_open_fds Number of open file descriptors.
> # TYPE process_open_fds gauge
> process_open_fds 44.0
> # HELP process_max_fds Maximum number of open file descriptors.
> # TYPE process_max_fds gauge
> process_max_fds 1.048576e+06
> ```

I have encountered the same issue as well. If you have resolved it, Pleasel let me know. Thank you.

**Comment by kalpesh22-21** [comment]
I a, 

> > d the image I'm pulling for the deployment uses vllm/engine/metrics.py from `v0.3.0`, not the tip of main.
> > Would it be possible to push another image ver
> 
> Hi,
> 
> @SamComber I want to use the metrics but I see something completely different. I have exposed an API using the [api_server.py](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py)
> 
> When I do a `http://localhost:8075/metrics/`, I get the following instead of seeing the values as described in the [Metrics Class](https://docs.vllm.ai/en/latest/serving/metrics.html), How to see those metrics? :
> 
> ```
> # HELP python_gc_objects_collected_total Objects collected during gc
> # TYPE python_gc_objects_collected_total counter
> python_gc_objects_collected_total{generation="0"} 6290.0
> python_gc_objects_collected_total{generation="1"} 8336.0
> python_gc_objects_collected_total{generation="2"} 4726.0
> # HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
> # TYPE python_gc_objects_uncollectable_total counter
> python_gc_objects_uncollectable_total{generation="0"} 0.0
> python_gc_objects_uncollectable_total{generation="1"} 0.0
> python_gc_objects_uncollectable_total{generation="2"} 0.0
> # HELP python_gc_collections_total Number of times this generation was collected
> # TYPE python_gc_collections_total counter
> python_gc_collections_total{generation="0"} 826.0
> python_gc_collections_total{generation="1"} 75.0
> python_gc_collections_total{generation="2"} 6.0
> # HELP python_info Python platform information
> # TYPE python_info gauge
> python_info{implementation="CPython",major="3",minor="10",patchlevel="12",version="3.10.12"} 1.0
> # HELP process_virtual_memory_bytes Virtual memory size in bytes.
> # TYPE process_virtual_memory_bytes gauge
> process_virtual_memory_bytes 3.098353664e+010
> # HELP process_resident_memory_bytes Resident memory size in bytes.
> # TYPE process_resident_memory_bytes gauge
> process_resident_memory_bytes 7.31774976e+08
> # HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
> # TYPE process_start_time_seconds gauge
> process_start_time_seconds 1.71188972784e+09
> # HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
> # TYPE process_cpu_seconds_total counter
> process_cpu_seconds_total 18.27
> # HELP process_open_fds Number of open file descriptors.
> # TYPE process_open_fds gauge
> process_open_fds 44.0
> # HELP process_max_fds Maximum number of open file descriptors.
> # TYPE process_max_fds gauge
> process_max_fds 1.048576e+06
> ```

I am facing same issue

**Comment by leokster** [comment]
is there any update or workaround for this issue?

**Comment by pseudotensor** [comment]
Seeing same thing, only basic stats in metrics, no usage, and promethus is not being populated.

```
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 156170.0
python_gc_objects_collected_total{generation="1"} 180292.0
python_gc_objects_collected_total{generation="2"} 114521.0
# HELP python_gc_objects_uncollectable_total Uncollectable objects found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 2102.0
python_gc_collections_total{generation="1"} 191.0
python_gc_collections_total{generation="2"} 10.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="10",patchlevel="14",version="3.10.14"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.4693138432e+010
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.168400384e+09
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.72430453209e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 59.7
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 23.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
```

I think maybe broken in 0.5.4.

**Comment by pseudotensor** [comment]
@hmellor Why was this issue closed as not planned?   It seems like clearly a bug for a useful thing.

**Comment by hmellor** [comment]
@pseudotensor Annoyingly, "not planned" can mean many things (why we can't specify which thing, I don't know), but this was closed as stale originally.

<img width="256" alt="image" src="https://github.com/user-attachments/assets/936aed8b-1d4e-4ff3-8807-d21198e198f4">

**Comment by pseudotensor** [comment]
No problem, it's all working in main.  Thanks!
