### ISSUE TITLE
When is the CPU KV cache used and swapping?

### ISSUE THREAD

**Issue by MitchellX** [vllm-project/vllm#2853]
Hi authors,

In your implementation, the GPU memory is leveraged to store the KV cache. However, it appears that when the GPU memory reaches its capacity, there isn't a mechanism in place to offload or swap this data to the CPU memory. 

1. Could you please clarify under what conditions the CPU KV cache comes into play?
2. Could you please tell me how to invoke the CPU KV cache (or API) if I want to do swapping?

![Screenshot 2024-02-01 at 2 41 42 PM](https://github.com/vllm-project/vllm/assets/47625290/38ee7a92-486d-4e2a-a7f1-3c8af2424cd4)
![Screenshot 2024-02-13 at 1 53 57 PM](https://github.com/vllm-project/vllm/assets/47625290/618227a2-c599-4028-b47d-ae03e0762016)

**Comment by rib-2** [comment]
The CPU KV cache is only used in cases where a sequence group has multiple sequences running. An example of this would be in a generation request when `beam_search` is enabled

You can see the logic here:
- https://github.com/vllm-project/vllm/blob/7e45107f51bcb38c22dd9916c61226078e8eb26d/vllm/core/scheduler.py#L420

**Comment by hughesadam87** [comment]
> The CPU KV cache is only used in cases where a sequence group has multiple sequences running. An example of this would be in a generation request when `beam_search` is enabled or `best_of>1`
> 
> You can see the logic [here](https://github.com/vllm-project/vllm/blob/7e45107f51bcb38c22dd9916c61226078e8eb26d/vllm/core/scheduler.py#L420)
> 
> You can see where the logic is called from [here](https://github.com/vllm-project/vllm/blob/7e45107f51bcb38c22dd9916c61226078e8eb26d/vllm/core/scheduler.py#L282)
> 
> There does not seem to be a way to enable CPU swapping right now for other cases. You can modify the server code however in the places that I listed above.

It would be helpful if this was more clear on the vLLM engine args page, as the CPU args led me to believe this would be possible and wasted time until I found this issue.
