### ISSUE TITLE
Add a model to the model executor list that is derived from RagTokenForGeneration model

### ISSUE THREAD

**Issue by Saiteja-Tallam-Infrrd** [vllm-project/vllm#2866]
How do I add a model executor that is derived from the huggingface model class  [RagTokenForGeneration](https://huggingface.co/docs/transformers/en/model_doc/rag#transformers.RagTokenForGeneration).

I could only find this [link](https://docs.vllm.ai/en/latest/models/adding_model.html) that documents about adding a new model. Can someone elaborate for this use case.

Thanks

**Comment by hmellor** [comment]
I'm not sure what state the linked documentation was in when you originally read it, but today it looks like you should be able to follow the steps if you are interested in adding a new model.

I'm closing this as stale for now.
