### ISSUE TITLE
Trailing new lines "\n" with Qwen1.5-7B-Chat-AWQ and vllm v0.3.0

### ISSUE THREAD

**Issue by v1nc3nt27** [vllm-project/vllm#2870]
I run vllm in a docker container with the following args:

`["--quantization", "awq", "--enforce-eager", "--disable-custom-all-reduce", "--max-num-batched-tokens", "4096", "--max-model-len", "4096", "--model", "LoneStriker/Qwen1.5-7B-Chat-AWQ", "--host", "0.0.0.0", "--port", "8080", "--chat-template", "/chat_template/qwen1.5-7b-chat.jinja2"]`

and chat template 

```
{% for message in messages %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}
```

Every 2 or 3 queries I do, the model just fills up all remaining completion tokens with new lines ("\n"). It only happens if the messages I send to the model are > 1, i.e. if I add a history of messages.

Does anyone else experience this? I tried without setting `--enforce-eager` and `--disable-custom-all-reduce`. I also noticed that with the v0.3.0 version, I get these outputs as if someone was calling the model:

`INFO 02-14 15:30:16 llm_engine.py:877] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%`

Might be unrelated, though

**Update**: I use streaming and `vllm.entrypoints.openai.api_server`

**Comment by cyc00518** [comment]
@v1nc3nt27 you can check here (https://github.com/QwenLM/Qwen1.5/issues/46)

**Comment by junjzhang** [comment]
I've met this issue too. I use vllm 0.3.1 to deploy Qwen1.5-14V-chat with chatml template.

**Comment by zouhuigang** [comment]
同样遇到多了换行符的问题，有解决的吗？ 感觉用代码移除换行符比较傻

**Comment by v1nc3nt27** [comment]
@cyc00518 thanks, is there a solution in this issue you can extract? Perhaps setting stop words to "\n\n\n..." but I could not extract more from it.

**Comment by junjzhang** [comment]
> @cyc00518 thanks, is there a solution in this issue you can extract? Perhaps setting stop words to "\n\n\n..." but I could not extract more from it.

https://github.com/QwenLM/Qwen1.5/issues/52?notification_referrer_id=NT_kwDOAw8uNLM5NTE4NjkzMjkyOjUxMzI2NTE2#issuecomment-1956689421 have a look at this one

**Comment by v1nc3nt27** [comment]
@junjzhang Cool, thanks a lot, I will check it out

**Comment by allenhaozi** [comment]
https://github.com/QwenLM/Qwen1.5/issues/46#issuecomment-2014319401
