### ISSUE TITLE
Is there a function where it iterates over the tokens from the prompt?

### ISSUE THREAD

**Issue by hgKang02** [vllm-project/vllm#2897]
My question is the same as the title, but I am searching for the part where the model is going through the prompt's tokens. Moreover, I am unsure how it generates tokens from the input sequence. It seems like most functions are dealing with the output already generated.

**Comment by DarkLight1337** [comment]
Are you looking for streaming output? I don't think that's supported yet.

**Comment by DarkLight1337** [comment]
Closing as stale. It may be reopened if you provide more information.
