### ISSUE TITLE
Controlling max queue time

### ISSUE THREAD

**Issue by p-christ** [vllm-project/vllm#2901]
Is there a way of controlling when vLLM will reject a request because the queue is too long vs let the request enter the queue?

**Comment by davidgxue** [comment]
This would be really nice! How does vLLM control max length of requests in queue right now? It doesn't seem like there's an upperbound? Is it just cpu memory being used?

**Comment by clam004** [comment]
This is a vote to keep this issue open. It is very relevant to anyone trying to load balance between more than one instance.

**Comment by jparismorgan** [comment]
@clam004 I'm curious, how do you load balance between more than one instance today?

**Comment by faileon** [comment]
> [@clam004](https://github.com/clam004) I'm curious, how do you load balance between more than one instance today?

round robin

**Comment by aiden0z** [comment]
Vote! 

I believe this is an essential feature for production use.  It seems that there is no mechanism in vLLM to reject new requests when the server is overloaded.

**Comment by HavenCTO** [comment]
Not everyone can afford to horizontally scale, let's get this feature prioritized

**Comment by davidkern87** [comment]
agree @HavenCTO, this would also help for [this issue](https://github.com/vllm-project/vllm/issues/4000). 
we're facing a situation where slow-running requests are continuosly queued and cannot be cancelled (even though the client has aborted/timed out)
