### ISSUE TITLE
api_server.py: error: unrecognized arguments: --lora-modules sql-lora=~/.cache/huggingface/hub/models--yard1--llama-2-7b-sql-lora-test/

### ISSUE THREAD

**Issue by xueyongfu11** [vllm-project/vllm#2909]
run codes below 
`python -m vllm.entrypoints.api_server \
    --model meta-llama/Llama-2-7b-hf \
    --enable-lora \
    --lora-modules sql-lora=~/.cache/huggingface/hub/models--yard1--llama-2-7b-sql-lora-test/`

raise an error:
api_server.py: error: unrecognized arguments: --lora-modules sql-lora=~/.cache/huggingface/hub/models--yard1--llama-2-7b-sql-lora-test/

**Comment by jacob-hansen** [comment]
Same error when trying to launch docker from vllm/vllm-openai:latest

**Comment by jacob-hansen** [comment]
Ok, I still get the error with the new docker. It isn't an available argument. 

I recommend checking out this example for how to load the lora after launching the engine: 
https://github.com/vllm-project/vllm/blob/main/examples/multilora_inference.py

**Comment by 1jsingh** [comment]
yes same error as well. Is there a solution for this? ... to serve lora trained models using vlllm? Thanks!

**Comment by JessyMu** [comment]
build env from source can fix it.

**Comment by Stannislav** [comment]
Upgrading to `vllm==0.3.3` solved this for me.

**Comment by victoraranda** [comment]
Instead of filing a new issue, tagging on to this open issue. I am having a similar experience with `vllm-openai:0.5.0` where it is giving me the same message. It seems that the `--lora-modules` argument is unrecognized. I'll try building from source, but is this a bug?
