### ISSUE TITLE
Add tag 0.3.1 to docker image

### ISSUE THREAD

**Issue by thisissum** [vllm-project/vllm#2914]
Please add tag 0.3.1 to dockerhub image vllm/vllm-openai

**Comment by hmellor** [comment]
May I ask why you don't want to use `v0.3.2` or `v0.3.3`?

**Comment by thisissum** [comment]
> May I ask why you don't want to use `v0.3.2` or `v0.3.3`?
The tag was not added when the v0.3.1 was just released. 
For now, please just ignore this issue.
