### ISSUE TITLE
How to call/add a new lora module to a live server?

### ISSUE THREAD

**Issue by jayteaftw** [vllm-project/vllm#2916]
Hi,

I was reading through the documentation for [Using Lora in VLLM](https://docs.vllm.ai/en/latest/models/lora.html). 

In the documentation when they start the server, it looks like they have to specify which Lora modules are available
`    --lora-modules sql-lora=~/.cache/huggingface/hub/models--yard1--llama-2-7b-sql-lora-test/`

Is it possible to do this in real-time instead? That is, start the server and call a recently added Lora module without having to stop and restart the server?

**Comment by prd-tuong-nguyen** [comment]
@jayteaftw Agree with you

**Comment by Erikfcb** [comment]
Might be super helpful

**Comment by AlphaINF** [comment]
mark, I am adding this feature.

**Comment by AlphaINF** [comment]
https://github.com/vllm-project/vllm/pull/3446

**Comment by Liucd0520** [comment]
hello，if this problem is fixed now. Indeed, when I need to update the lora model, I must stop the server, and add the new lora model and start the server again. what a stupid operation !  if lora model can be added to online server, the problem can be solved.
