### ISSUE TITLE
Support for  Smaug-72B-v0.1 on vLLM

### ISSUE THREAD

**Issue by cdxzyc** [vllm-project/vllm#2917]

**Comment by esmeetu** [comment]
@cdxzyc This model uses the same architecture as `Llama`, which vLLM already supports.

**Comment by pseudotensor** [comment]
I only get garbage results out of vLLM for this model.  Tried both llama2 prompt and qwen prompt as suggested: https://huggingface.co/abacusai/Smaug-72B-v0.1/discussions/6

https://huggingface.co/abacusai/Smaug-72B-v0.1

**Comment by esmeetu** [comment]
@pseudotensor Could you try change `attention_bias` key name to `bias` in `config.json`?

**Comment by pseudotensor** [comment]
Edited the file to go from true to "bias" for, and still same issues.

![image](https://github.com/vllm-project/vllm/assets/2249614/f6e64209-7676-422f-aca2-8404b6d90785)

**Comment by pseudotensor** [comment]
Still no help:

![image](https://github.com/vllm-project/vllm/assets/2249614/05bbaf13-8a4f-43b6-a6a2-c08a14239a81)

![image](https://github.com/vllm-project/vllm/assets/2249614/e66ff5df-ba27-43dc-b3f7-1248edf88724)

**Comment by masahi** [comment]
The change should be

```
diff --git a/vllm/model_executor/models/llama.py b/vllm/model_executor/models/llama.py
index b7f6b8f..af5b018 100644
--- a/vllm/model_executor/models/llama.py
+++ b/vllm/model_executor/models/llama.py
@@ -184,7 +184,7 @@ class LlamaDecoderLayer(nn.Module):
             rope_scaling=rope_scaling,
             max_position_embeddings=max_position_embeddings,
             linear_method=linear_method,
-            bias=getattr(config, "bias", False),
+            bias=getattr(config, "attention_bias", False),
             sliding_window=sliding_window,
         )
```

**Comment by esmeetu** [comment]
> Still no help:
> 
> 
> 
> ![image](https://github.com/vllm-project/vllm/assets/2249614/05bbaf13-8a4f-43b6-a6a2-c08a14239a81)
> 
> 
> 
> ![image](https://github.com/vllm-project/vllm/assets/2249614/e66ff5df-ba27-43dc-b3f7-1248edf88724)
> 
> 


Seems right now. Is that model a chat model? Try without chat template.

**Comment by pseudotensor** [comment]
Yes, it's chat model with DPO etc. and they mention both llama2 and other chat templates will work, like is common:

https://huggingface.co/abacusai/Smaug-72B-v0.1/discussions/6#65c660810831983147b3b78f

**Comment by pseudotensor** [comment]
What I find confusing is the model card says based upon qwen, but that has own model class, not llama

https://huggingface.co/abacusai/Smaug-72B-v0.1

**Comment by esmeetu** [comment]
@pseudotensor That's so weird. This is hard to debug since that model lack of modeling file. But for the config file, i think it's correct when running it as a llama model.

**Comment by kir152** [comment]
the model is converted from qwen to llama using conversion scripts like this https://github.com/hiyouga/LLaMA-Factory/blob/main/scripts/llamafy_qwen.py

**Comment by kir152** [comment]
one difference is this model uses MHA, but Llama2 has MQA, that might be causing the issue
