### ISSUE TITLE
The results of vllm deployment of qwen-14B are inconsistent with the results of the original qwen-14B

### ISSUE THREAD

**Issue by qingjiaozyn** [vllm-project/vllm#2927]
The results of vllm deployment of qwen-14B are inconsistent with the results of the original qwen-14B, and we hope to optimize the integration effect of qwen-14B as soon as possible

**Comment by huihuiustc** [comment]
The same to me.

**Comment by guoyuhong** [comment]
@qingjiaozyn @huihuiustc As I know, vLLM does not ensure bit-wise correctness (See Page 38 of the meetup [slides](https://docs.google.com/presentation/d/1QL-XPFXiFpDBh86DbEegFXBXFXjix4v032GhShbKf3s/edit#slide=id.g24c1f26d37c_0_81)). If the result answer's meaning is the same literally. It is fine.

**Comment by qingjiaozyn** [comment]
@guoyuhong There is still a big difference between the two answers. Sometimes, VLLM results are only part of the answer, not comprehensive

**Comment by xwzj01ht** [comment]
The same to me.

**Comment by qiufengyuyi** [comment]
+1
