### ISSUE TITLE
Why use tensor parallelism when model can easily fit on a single GPU ?

### ISSUE THREAD

**Issue by vikigenius** [vllm-project/vllm#293]
If the model can fit on a single GPU, wouldn't it be better to use something like DDP instead? What are the advantages of using tensor parallelism if the model is small enough to fit on a single GPU ?

**Comment by zhuohan123** [comment]
You are right, for small models, you should just use one GPU. You can start multiple vLLM replicas to achieve "data parallelism" for serving, so that is not shown in our code. Tensor parallelism is mainly for large models that cannot fit a single GPU.
