### ISSUE TITLE
wrong output of AsyncLLMEngine

### ISSUE THREAD

**Issue by sanixa** [vllm-project/vllm#2947]
When deploying the Qwen 1.5 model with FastChat and vllm, there is an error in the output of the [AsyncLLMEngine.](https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py#L119) 

One example of `request_output.outputs` from #L128 is `[CompletionOutput(index=0, text='Tom886', token_ids=[24732, 23, 23, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 151645], cumulative_logprob=0.0, logprobs=None, finish_reason=stop)]`. The content of **token_ids** is inconsistent with the **text**, and the token_ids is the correct output.

In my test, the text is always 10 tokens shorter than token_ids. 

package: fastchat==0.2.36, vllm==0.3.1

**Comment by simon-mo** [comment]
@sanixa can you help us with a reproducible example using v0.3.2's new `seed` parameter?

**Comment by sanixa** [comment]
Sure, here is the example https://github.com/sanixa/FastChat

**Comment by coreyho** [comment]
same promble with fastchat 0.2.36 vllm 0.3.1
but when i using vllm's api, response correct
```
fastchat-vllm
RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assis', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351, 30, 151645, 198, 151643], cumulative_logprob=-1.2168595165130114, logprobs=None, finish_reason=stop)], finished=True, lora_request=None)
```

```
vllm api
RequestOutput(request_id=cmpl-36459a7e9a5c4e32afa602165e1b4cd8, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I help you today? If you have any questions or need assistance, feel free to ask.\n', token_ids=[9707, 0, 2585, 646, 358, 1492, 498, 3351, 30, 1416, 498, 614, 894, 4755, 476, 1184, 12994, 11, 2666, 1910, 311, 2548, 13, 151645, 198, 151643], cumulative_logprob=-2.2319395797688912, logprobs=None, finish_reason=stop)], finished=True, lora_request=None)
```

**Comment by coreyho** [comment]
qwen15-fastchat-qwen2-72b-1  | INFO 02-22 16:52:30 async_llm_engine.py:433] Received request d9e65a86be2a42a4917ba9fee5e97d9e: prompt: '<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prefix_pos: None,sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.1, temperature=0.7, top_p=1.0, top_k=-1.0, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|endoftext|>', '<|im_start|>', '<|im_end|>'], stop_token_ids=[151643], include_stop_str_in_output=False, ignore_eos=False, max_tokens=256, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
qwen15-fastchat-qwen2-72b-1  | INFO 02-22 16:52:30 metrics.py:161] Avg prompt throughput: 0.9 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello', token_ids=[9707], cumulative_logprob=-0.14505724608898163, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello!', token_ids=[9707, 0], cumulative_logprob=-0.18315167725086212, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How', token_ids=[9707, 0, 2585], cumulative_logprob=-0.18371692713117227, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can', token_ids=[9707, 0, 2585, 646], cumulative_logprob=-0.20699754770612344, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I', token_ids=[9707, 0, 2585, 646, 358], cumulative_logprob=-0.20699754770612344, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist', token_ids=[9707, 0, 2585, 646, 358, 7789], cumulative_logprob=-1.1810905080637895, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist you', token_ids=[9707, 0, 2585, 646, 358, 7789, 498], cumulative_logprob=-1.1810908656916013, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist you today', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351], cumulative_logprob=-1.1820022820610916, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist you today?', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351, 30], cumulative_logprob=-1.1820022820610916, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist you today?', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351, 30, 151645], cumulative_logprob=-1.2101421545375501, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assist you today?\n', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351, 30, 151645, 198], cumulative_logprob=-1.2101421545375501, logprobs=None, finish_reason=None)], finished=False, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | INFO 02-22 16:52:30 async_llm_engine.py:110] Finished request d9e65a86be2a42a4917ba9fee5e97d9e.
qwen15-fastchat-qwen2-72b-1  | 2024-02-22 16:52:30 | INFO | stdout | RequestOutput(request_id=d9e65a86be2a42a4917ba9fee5e97d9e, prompt='<|im_start|>user\nhello<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 872, 198, 14990, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='Hello! How can I assis', token_ids=[9707, 0, 2585, 646, 358, 7789, 498, 3351, 30, 151645, 198, 151643], cumulative_logprob=-1.2168595165130114, logprobs=None, finish_reason=stop)], finished=True, lora_request=None)
qwen15-fastchat-qwen2-72b-1  | INFO 02-22 16:52:30 async_llm_engine.py:133] Aborted request d9e65a86be2a42a4917ba9fee5e97d9e.

**Comment by coreyho** [comment]
generation_config.json

{
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_p": 0.8,
  "top_k": 20,
  "transformers_version": "4.37.0"
}

**Comment by ticoAg** [comment]
This maybe helpful for analyze
Deploy with `python -m vllm.entrypoints.openai.api_server --model qwen/Qwen1.5-0.5B-Chat`

Conclusion: config `SamplingParams(skip_special_tokens=False, stop=["<|im_end|>"]` in code or api request with below param work as expect.
```json
{
    "skip_special_tokens": false,
    "stop": ["<|im_end|>"]
}
```
`SamplingParams.skip_special_tokens` default is `True`, perhaps it will replace `<|im_end|>` and `<|im_start|>` to `""` and only consider `<|endoftext|>` as the end of generation.

分析过程
1. request with
```json
{
    "model": "qwen/Qwen1.5-0.5B-Chat",
    "messages": [
        {"role": "system","content": "You are a helpful assistant."},
        {"role": "user","content": "你是什么模型"}
    ],
    "temperature": 0,
    "skip_special_tokens": false
}
```
output: 

> 我是来自阿里云的大规模语言模型，我叫通义千问。<|im_end|>\n<|im_start|><|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|im_start|><|im_end|>\n<|endoftext|>```

2. request with 
```json
{
    "model": "qwen/Qwen1.5-0.5B-Chat",
    "messages": [
        {"role": "system","content": "You are a helpful assistant."},
        {"role": "user","content": "你是什么模型"}
    ],
    "temperature": 0,
    "skip_special_tokens": false
}
```
> 我是来自阿里云的大规模语言模型，我叫通义千问。\n\n\n\n\n\n\n\n\n\n

3. request with
```json
{
    "model": "qwen/Qwen1.5-0.5B-Chat",
    "messages": [
        {"role": "system","content": "You are a helpful assistant."},
        {"role": "user","content": "你是什么模型"}
    ],
    "temperature": 0,
    "skip_special_tokens": false,
    "stop": ["<|im_end|>"]
}
```
> 我是来自阿里云的大规模语言模型，我叫通义千问。

**Comment by simon-mo** [comment]
Thank @ticoAg for diagnosing this. Is there something we can do in vLLM codebase to make `SamplingParams(skip_special_tokens=False, stop=["<|im_end|>"]` the default only for Qwen? Or read the model/tokenizer config from Qwen properly? We are happy to hear suggestions and welcome contributions!
