### ISSUE TITLE
AWQ Quantization Memory Usage

### ISSUE THREAD

**Issue by vcivan** [vllm-project/vllm#2948]
Hello! First of all, great job with this inference engine! Thanks a lot for your work!

Here's my issue: I have run vllm with both a mistral instruct model and it's AWQ quantized version. I've quantized the model myself with AutoAWQ. It seems that both of them use around the same amount of GPU memory, whereas I'd expect the AWQ quantized version to use far less memory.

Here is the GPU memory with the mistral model:

<img width="528" alt="image" src="https://github.com/vllm-project/vllm/assets/17829552/3f58f64e-67cc-463f-9794-bb1bcdba9974">

Here is the GPU memory with the AWQ quantized mistral model:

<img width="531" alt="image" src="https://github.com/vllm-project/vllm/assets/17829552/f76fb68d-6932-4fcf-b11e-3f8b581baff8">

I am mostly using default parameters when running `entrypoints/openai/api_server.py`, except for `--max-model-len 24000` and `--enforce-eager`.

Initially I thought that vllm reserves GPU memory up to 90% due to `--gpu-memory-utilization`, but it seems that that is not the case, as the real utilization is not equal between the 2 models and it is also not 90% of the total GPU memory.

Could you explain what and why is happening here?

Thank you so much!

**Comment by jvmncs** [comment]
@vcivan total shot in the dark here, but did you try specifying `--quantization awq`? I _believe_ that if that arg isn't set, it attempts to infer the quantization type from the hf model config, and so if you failed to declare that metadata in your quantized hf model, it will just assume that there is no quantization and load all the weights into tensors with the unquantized dtype. that being said I haven't done a code dive yet, so I could be wrong about any part of that

**Comment by yangxianpku** [comment]
With int4 quantized models you can use parameter `--gpu-memory-utilization` that take up less GPU memory, for Llama3-8B, this parameter can be set to a minimum of 0.6(~12GB) with 4-bit quantization, but not with the original fp16 model(~19GB)!

**Comment by yangxianpku** [comment]
NVIDIA A10 24GB
