### ISSUE TITLE
8bit support

### ISSUE THREAD

**Issue by mymusise** [vllm-project/vllm#295]
Hi, will vllm support 8bit quantization? Like https://github.com/TimDettmers/bitsandbytes

In HF, we can run a 13B LLM on a 24G GPU with `load_in_8bit=True`.

Although PageAttention can save 25% of GPU memory, but we have to deploy a 13B LLM on a 26G GPU, at least. 

In the cloud, v100-32G is more expensive than A5000-24G 😭

Is there any way to save video memory usage? 😭

**Comment by mymusise** [comment]
same with https://github.com/vllm-project/vllm/issues/214

**Comment by generalsvr** [comment]
Quantization support is crucial. 8 and 4 bit support is a must

**Comment by cabbagetalk** [comment]
why I use fastchat-vllm to inference vicuna-13B，It took 75 G of video memory(A800, 80G) @mymusise

**Comment by mymusise** [comment]
> why I use fastchat-vllm to inference vicuna-13B，It took 75 G of video memory(A800, 80G) @mymusise

you can add `gpu_memory_utilization=0.4` to free your memory

**Comment by proceduralia** [comment]
This would especially useful for running the new `meta-llama/Llama-2-70b-chat-hf` models!

**Comment by boxter007** [comment]
> Hi, will vllm support 8bit quantization? Like https://github.com/TimDettmers/bitsandbytes
> 
> In HF, we can run a 13B LLM on a 24G GPU with `load_in_8bit=True`.
> 
> Although PageAttention can save 25% of GPU memory, but we have to deploy a 13B LLM on a 26G GPU, at least.
> 
> In the cloud, v100-32G is more expensive than A5000-24G 😭
> 
> Is there any way to save video memory usage? sob

在这里看到熟人啊

**Comment by yhyu13** [comment]
Does vllm support it now?

**Comment by louis-csm** [comment]
Any fix for this issue?

**Comment by warvyvr** [comment]
Hi guys, do you have plan to support it?

**Comment by qashzar** [comment]
any fix for integrating bitsandbytes?

**Comment by hmellor** [comment]
No fix, but the feature request is https://github.com/vllm-project/vllm/issues/4033
