### ISSUE TITLE
The accuracy of the inference results of qwen14B accelerated by VLLM has decreased

### ISSUE THREAD

**Issue by xwzj01ht** [vllm-project/vllm#2956]
Hello!Here's my issue: 

I have recently noticed that there is inconsistency between the results of streaming inference using vllm-accelerated qwen14B and the original qwen inference, leading to a decrease in accuracy. Could you please investigate and address this issue? Thank you very much for your assistance and support.

**Comment by qingjiaozyn** [comment]
I use version 0.3.2 of vllm for this problem.
My original question is ：
忘记你已有的知识，仅使用 标记中的问答对进行回答。\n\n\nquestion:出差期间需延迟一天返程，该如何报销？\nanswer:延迟返程会造成无法通过商旅100购买返程机票，需报账人自行购买机票，并保留航空客票电子行程单，出差结束后报销，并需重提交特殊情况审批表对延迟返程和自行购买机票的情况进行说明\n\n来源：通用-会计核算与报账服务-成本-差旅费-差旅特殊审批\n责任科室：成本室\n\nquestion:出差期间需延迟一天返程，该如何报销\nanswer:延迟返程会造成无法通过商旅100购买返程机票，需报账人自行购买机票，并保留航空客票电子行程单，出差结束后报销，并需重提交特殊情况审批表对延迟返程和自行购买机票的情况进行说明\n\n来源：通用-会计核算与报账服务-成本-差旅费-差旅特殊审批\n责任科室：成本室\n\nquestion:差&发票\nanswer:差旅费发票无法在发票明细信息中查到，如何填报\发票明细信息一栏无法选择发票\n报账系统中发票池先查询发票，发票池中发票种类需选对，校验码需填对（备注栏的数字长的后六位），查询的到就直接新增到发票明细信息中即可；若未查询到则需进行手动增加。\n\n来源：通用-会计核算与报账服务-成本-差旅费-发票报账问题\n责任科室：成本室\n\nquestion:差旅费未通过商旅100购票，在填写行程车票无法出现税率？\nanswer:应在填单时填入实报金额，即可自动识别相应的税额。\n\n来源：通用-会计核算与报账服务-成本-差旅费-差旅结算单问题\n责任科室：成本室\n\nquestion:未通过商旅100购票，在填写行程车票为什么不出现税率\nanswer:应在填单时填入实报金额，即可自动识别相应的税额。\n\n来源：通用-会计核算与报账服务-成本-差旅费-差旅结算单问题\n责任科室：成本室\n\n \n\n\n思考流程：\n1.直接使用知识库中的信息来回答问题，不需要提供其他来源的信息。\n2. 判断问题是否与 标记中的内容有关。\n3. 如果无关，你直接拒绝回答本次问题。\n4. 判断是否有相近或相同的问题。\n5. 如果有相同的问题，直接输出对应答案。\n6. 如果只有相近的问题，请把相近的问题和答案一起输出。\n7. 如果问题是一个简短的关键词，例如“网盘”、“一卡通”，“充值”等，请提供所有与该关键词相关的知识库信息。\n8. 你的名字是人工智能助手，你由大规模语料训练而来。\n\n最后，避免提及你是从 QA 获取的知识，只需要回复答案。\n\n问题:未通过商旅100购票，在填写行程车票为什么不出现税率

the result of the original qwen14B is ：应在填单时填入实报金额，即可自动识别相应的税额。

来源：通用-会计核算与报账服务-成本-差旅费-差旅结算单问题
责任科室：成本室

and the result of vllm's qwen14B is ：
应在填单时填入实报金额，即可自动识别相应的税额。

I hope the author will integrate qwen's answer consistency optimization into the project

**Comment by hmellor** [comment]
Closing as duplicate of #2950
