### ISSUE TITLE
Add support for Gemma models

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#2960]
Architecture difference (what I could find):
- [Normalizes embeddings](https://github.com/huggingface/transformers/blob/ae49b218c3d718df90d8e4a109016450fb8f0632/src/transformers/models/gemma/modeling_gemma.py#L881)

Links:
- Gemma 7B: https://huggingface.co/google/gemma-7b
- Gemma 2B: https://huggingface.co/google/gemma-2b
- Blog: https://blog.google/technology/developers/gemma-open-models/
- Paper: https://storage.googleapis.com/deepmind-media/gemma/gemma-report.pdf

**Comment by xiangxu-google** [comment]
It's on the way https://github.com/vllm-project/vllm/pull/2964
