### ISSUE TITLE
Triton reports "Unexpected srcLayout in ReduceOpConversion" when using prefix

### ISSUE THREAD

**Issue by 00ffcc** [vllm-project/vllm#2963]
code:
```python
from vllm import LLM
from vllm import SamplingParams
import torch


model = "01-ai/Yi-6B"
# Create an LLM.
llm = LLM(model=model,dtype=torch.float16)
# get prompts
prompts = ["这是一个 Prefix 功能使用的示例，因为 Prefix 的存储以物理块为单位，所以 Prompt 的长度需要至少大于等于一个物理块，这是第一句话",
           "这是一个 Prefix 功能使用的示例，因为 Prefix 的存储以物理块为单位，所以 Prompt 的长度需要至少大于等于一个物理块，这是第二句话"]
# set SamplingParams
sampling_params = SamplingParams(temperature=0,
                                 max_tokens=100,
                                 )
outputs = llm.generate(prompts=[prompts[0]],
                        sampling_params=sampling_params,
                        prefix_pos=[16])
outputs = llm.generate(prompts=[prompts[1]],
                        sampling_params=sampling_params,
                        prefix_pos=[16])
```
output:
![QQ截图20240222002714](https://github.com/vllm-project/vllm/assets/52339737/5ab59d94-08f5-4fa7-aca3-559ccbdb7b30)

environment:
RTX6000
Linux
cuda12.1
I have tried build vllm from source and just `pip install vllm`, but the result is the same.

Thank you!

**Comment by 00ffcc** [comment]
Any solution? Or it's just a bug of Triton?

**Comment by 00ffcc** [comment]
the program works on 3090, so it should be a problem of RTX6000

**Comment by hmellor** [comment]
> the program works on 3090, so it should be a problem of RTX6000

To clarify, are you saying that it works on 3090 so it shouldn't be a problem for RTX6000?

Have you tried this recently on the latest version of vLLM? Perhaps something has been changed/fixed
