### ISSUE TITLE
Very Slow Server Inference After Upgrade

### ISSUE THREAD

**Issue by darrenangle** [vllm-project/vllm#2971]
Recently upgraded to the latest version 0.3.2 and I've noticed a total slowdown in outputs. 

Here's my speed on the 0.2.7 release
`Avg prompt throughput: 1006.0 tokens/s, Avg generation throughput: 273.8 tokens/s,`

Here's my speed on 0.3.2
`Avg prompt throughput: 175.5 tokens/s, Avg generation throughput: 15.5 tokens/s,`

start command:

```
python -m vllm.entrypoints.openai.api_server \
    --model code/hf-models/OpenHermes-2.5-Mistral-7B --max-model-len 8192
```

On a single 4090.

**Comment by simon-mo** [comment]
Can you try 0.3.1 so we can figure out whether it's a recent regression or not, additionally, try setting `enforce_eager=False`?

**Comment by DaBossCoda** [comment]
same issue here. 

slow inference occurs when tp >1. i switched back to tp = 1 and it works normally.

this also showed when trying with tp > 1 but not tp =1
Custom all-reduce kernels are temporarily disabled due to stability issue

**Comment by SparkJiao** [comment]
Same issue here.

I have tried different releases and found that only the inference speed if `vllm==0.2.7` is normal. The speed since version `0.3.0` descreased alot.

Envionment:
- torch==2.1.2
- cuda118
- A100 SXM

**Comment by darrenangle** [comment]
I upgraded to 0.3.3 and started explicitly adding --enforce-eager, and it's back to speedy. thanks.

```
python -m vllm.entrypoints.openai.api_server \
    --model hf-models/NousResearch-Hermes-2-Pro-Mistral-7B --max-model-len 8192 --enforce-eager
```
