### ISSUE TITLE
Installation error -- "num_layers" variable error in cache_kernels.cu

### ISSUE THREAD

**Issue by burghman24** [vllm-project/vllm#2973]
I saw a prior post that was a similar issue, but it received no responses so I am trying fresh.  I saw posts about the issues with the pyproject.toml file and I self-edited it to point to my CUDA capable version of pytorch.  But upon running the setup.py install, I am getting this error:

C:\Users\sekle\VLLM\vllm\csrc\cache_kernels.cu(109): error: expression must have a constant value
    int64_t key_cache_ptrs[num_layers];
                           ^
C:\Users\sekle\VLLM\vllm\csrc\cache_kernels.cu(109): note #2689-D: the value of variable "num_layers" (declared at line 99) cannot be used as a constant
    int64_t key_cache_ptrs[num_layers];
                           ^

C:\Users\sekle\VLLM\vllm\csrc\cache_kernels.cu(110): error: expression must have a constant value
    int64_t value_cache_ptrs[num_layers];
                             ^
C:\Users\sekle\VLLM\vllm\csrc\cache_kernels.cu(110): note #2689-D: the value of variable "num_layers" (declared at line 99) cannot be used as a constant
    int64_t value_cache_ptrs[num_layers];
                             ^

2 errors detected in the compilation of "csrc/cache_kernels.cu".

I am extremely new to programming, and once I got through my troubleshooting to where this was the only error left, I have no idea where to go next.  Any help is extremely appreciated!

**Comment by taisenki** [comment]
you can use dynamic memory allocation:

 ```
  int64_t* key_cache_ptrs = new int64_t[num_layers];
  int64_t* value_cache_ptrs = new int64_t[num_layers];
  
  delete[] key_cache_ptrs;
  delete[] value_cache_ptrs;
```

**Comment by burghman24** [comment]
Thank you -- that cleared the error.  Appreciate you taking the time to help!
