### ISSUE TITLE
When using AWQ quantization on the yi-34b-chat model, its performance is lower than the unquantized model under high concurrency.

### ISSUE THREAD

**Issue by Uhao-P** [vllm-project/vllm#2980]
- A6000 * 4
- max_token = 512
- yi-34b-chat vs yi-34b-chat_awq_int
- - `python3 -m vllm.entrypoints.openai.api_server   --model /output/yi-34b-chat/   --engine-use-ray   --host 0.0.0.0   --port 8080   --worker-use-ray   --max-num-seqs 16   --tensor-parallel-size 4  --max-model-len 32768`
- - `python3 -m vllm.entrypoints.openai.api_server   --model /output/yi_awq_4_dataset_16/   --engine-use-ray   --host 0.0.0.0   --port 8080   --worker-use-ray   --max-num-seqs 16   --tensor-parallel-size 4  --max-model-len 32768 --quantization awq`

![image](https://github.com/vllm-project/vllm/assets/42427430/4ca94349-3a32-4f14-b68f-e062454e5a71)

**Comment by casper-hansen** [comment]
Hi @Uhao-P, this is expected. Quantized models scale worse than full precision models due to the additional overhead of dequantization.

**Comment by Uhao-P** [comment]
Thank you, I will close this issue
