### ISSUE TITLE
[feature request] benchmark TRT-LLM backend 

### ISSUE THREAD

**Issue by hassan-twelvelabs** [vllm-project/vllm#2998]
Is there any plan to add benchmark support for TRT-LLM backend?

**Comment by ywang96** [comment]
Hey @hassan-twelvelabs! The serving benchmark supports TRT-LLM + Triton - see more details in https://github.com/vllm-project/vllm/pull/3277. Thanks

**Comment by hassan-twelvelabs** [comment]
Thank you!
