### ISSUE TITLE
How to batch using the OpenAI api? 

### ISSUE THREAD

**Issue by dustyatx** [vllm-project/vllm#2999]
I know the feature exists if I use vLLM directly in my code but the API documentation is sparse and doesn't cover this topic.

**Comment by simon-mo** [comment]
https://github.com/vllm-project/vllm/blob/57f044945f25d90d1b434014b2719ba6b06fdc44/tests/entrypoints/test_openai_server.py#L265-L275

Documentation or example PRs welcomed!
