### ISSUE TITLE
question and help❓ how could  memory_efficient_attention_forward could work on the concatenating batches?

### ISSUE THREAD

**Issue by thesues** [vllm-project/vllm#3003]
[memory_efficient_attention_forward](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.memory_efficient_attention) is invoked in prefill phase.

This function expects the input tensor to have a shape of [batch_size, num_seq, num_head, head_size]. 

However, previously, the queries and other tensors were transformed using torch.view, torch. unsqueeze, resulting in a shape of 
[1, batch_size * num_seq, num_head, head_size]. 

Doesn't this difference in tensor format from what memory_efficient_attention_forward pose a problem? How do we ensure that the final result is correct?

in my own test. concating batches does not have the same result..., please enlighten me.

```python
import torch
from xformers import ops as xops


device="cuda"
dtype=torch.float16
#[B,M,H,K]
query = torch.rand((3, 136, 32, 64), dtype=dtype, device=device)
key = torch.rand((3, 136, 32, 64), dtype=dtype, device=device)
value = torch.rand((3, 136, 32, 64),dtype=dtype, device=device)

resized_query = query.view(-1, 32, 64).unsqueeze(0)
resized_key = query.view(-1, 32, 64).unsqueeze(0)
resized_value = query.view(-1, 32, 64).unsqueeze(0)

scale=1.0/(query.size(-1)**0.5)
print(scale)
out1 = xops.memory_efficient_attention(query, key, value, scale=scale)
out2 = xops.memory_efficient_attention(resized_query, resized_key, resized_value, scale=scale)
out2 = out2.view(3, 136, 32,64)
print(out1.shape,out2.shape)
# the TWO results are not same.
assert torch.allclose(out1, out2, atol=1e-2, rtol=1e-2)
```

**Comment by Mora-He** [comment]
I have the same question while reading source code. What is the answer of this issue?

**Comment by thesues** [comment]
to my understanding, [memory_efficient_attention_forward](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.memory_efficient_attention) has 
 an argument : attn_bias which is initialed as [BlockDiagonalCausalMask](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.fmha.attn_bias.BlockDiagonalMask).  it may be related to this.

**Comment by tanzelin430** [comment]
Hi thesues, your comment has just solved my confusion about this question, thanks a lot
