### ISSUE TITLE
Can pip install hf_transfer be added to the docker openai template?

### ISSUE THREAD

**Issue by RonanKMcGovern** [vllm-project/vllm#3008]
This allows an env variable to be set that increases download speed for weights.

**Comment by simon-mo** [comment]
Sure. Open a PR?

**Comment by RonanKMcGovern** [comment]
Here's my PR: https://github.com/vllm-project/vllm/pull/3031

**Comment by michaelfeil** [comment]
@RonanKMcGovern Is this PR closeable from your side?

**Comment by RonanKMcGovern** [comment]
Yup, closable, hopefully the new docker image gets released soon. Thanks for the help

**Comment by simon-mo** [comment]
It's out as of last weekend!
