### ISSUE TITLE
Large length variance of sampled sequences from llama2 70b model compared to HuggingFace .generate()

### ISSUE THREAD

**Issue by uralik** [vllm-project/vllm#3013]
Hi all, thanks for this great inference framework. We enjoy the speedups coming from it, but we are concerned about too high sampling variance.

Setting: 

**Model**: llama2 70b model finetuned on some data in our project. Exactly the same model is used in all of the decoding trials explained below. The dtype config in the model dir says `bfloat16`.

**inference**: we test 4 different options: (1) HF generate, (2) HF generate with flash attn 2, (3) our own generation loop, (4) VLLM 

**Data**: eval set from this paper: 256 eval subset from this paper: https://arxiv.org/pdf/2308.06259.pdf 

**Compute**: 8 A100 gpus, device_map="auto" + torch.bfloat16 is used on HF side and in our internal generation loop.

Sampling parameters are aligned across different decoding setups to be temp=0.7, topp=0.9, max gen length = 2048.

We generate samples for eval set of 256 inputs prompts and then we compute the avg length of generated samples (in tokens) over this set.
Now we do this 20 times with different random seeds and the expectation is that this the avg. length spread along 20 trials wont be too high.

Here are the min->max values from these 20 runs per each decoding variant:

1. HF generate with vanilla attn backend: 441 -> 467

2. HF generate with flash attention 2: 429 -> 464

3. Our own generation loop: 388 -> 422 

**4. vLLM: 343 -> 512** 

vllm shows much larger lengths spread which is concerning and I am trying to figure out why. Note that those min max values in vllm are not outliers, here are all numbers for reference:
```
 343.08984375,
 354.5546875,
 361.91796875,
 363.46875,
 372.21875,
 375.2265625,
 376.7578125,
 390.37890625,
 391.640625,
 393.99609375,
 397.47265625,
 410.45703125,
 413.97265625,
 424.3671875,
 437.296875,
 439.71484375,
 450.203125,
 469.80859375,
 477.94921875,
 512.12109375
```

Please find below the code we use to instantiate vllm decoding. Note that here we use n=20 to get 20 samples per each prompt at once instead of running this 20 times:

```
llm = LLM(model, tensor_parallel_size=4)
sampling_params = SamplingParams(
    n=20,
    temperature=0.7,
    top_p=0.9,
    max_tokens=2048,
    use_beam_search=False,
)
outputs = llm.generate(inputs, sampling_params)
```

Please let me know if there is something obvious I might be missing from vLLM usage/instantiation. Our goal is to confirm the parity between HF generation and the vllm one.

Thanks!

**Comment by uralik** [comment]
After more experiments we found that the `n` parameter of the sampling_params influences this variance a lot.

Imagine the goal is to sample the eval set 40 times i.e. for each prompt we would like 40 independent samples. There are two naive ways of doing this: (1) setting `n` to 40 in sampling params and running `llm.generate()` once , and (2) running `llm.generate()` 40 times over the same list of prompts.

Now after running this decoding in both ways, we compute average length of produced samples over the eval set. In other words, we will have 40 different estimates of the average length computed over eval set.

Sorted average length when we use `n=40`:

```
339.81640625,
 349.23828125,
 352.76953125,
 353.0078125,
 358.5390625,
 359.31640625,
 364.6796875,
 368.3203125,
 370.640625,
 370.94921875,
 373.06640625,
 375.96875,
 380.57421875,
 387.26171875,
 388.76171875,
 390.1015625,
 393.16015625,
 394.1796875,
 396.95703125,
 401.453125,
 403.796875,
 407.44921875,
 407.56640625,
 409.234375,
 409.72265625,
 415.23828125,
 417.4765625,
 421.6484375,
 423.73828125,
 431.53515625,
 431.6953125,
 434.453125,
 448.36328125,
 456.546875,
 457.37109375,
 458.078125,
 468.16015625,
 490.2109375,
 496.3359375,
 543.21875
```

40 average lengths when we ran `llm.generate()` 40 times:

```
389.23046875,
 390.1328125,
 393.22265625,
 393.33203125,
 396.65234375,
 397.5390625,
 397.59765625,
 397.9296875,
 399.515625,
 400.1796875,
 400.40234375,
 400.66015625,
 400.83984375,
 401.59375,
 401.828125,
 402.578125,
 405.49609375,
 405.7109375,
 406.39453125,
 407.0625,
 408.08203125,
 408.40625,
 408.5,
 409.20703125,
 409.4453125,
 409.6015625,
 409.83203125,
 409.98828125,
 410.15625,
 411.26171875,
 411.50390625,
 413.22265625,
 413.6875,
 414.6875,
 415.0390625,
 415.46484375,
 417.8515625,
 420.9609375,
 427.75390625,
 428.03125
```

the latter variant produces results which aligns much better with both HF generate() and our own generation loop. This highlights the problem of `n` argument in the LLM engine. 

for my own use case I will continue using `n=1`, but i believe this is worth further investigation as things dont look healthy there.

**Comment by zijwang** [comment]
Facing a similar issue and even with `n=1`, when you change the seed in `SamplingParams`, the generation and downstream performance is drastically different. I tested it on latest v0.4.0 post1 on A100s.

Any thoughts from the vllm team? @WoosukKwon  @zhuohan123 @simon-mo
