### ISSUE TITLE
Is there any reason why only some head_size is supported?

### ISSUE THREAD

**Issue by sungeuns** [vllm-project/vllm#302]
Hi, Thanks for awesome library.

I tried to load model which has `head_size` is 256, but it is not supported yet.
Attention code [here](https://github.com/vllm-project/vllm/blob/998d9d15095e7a69629f9e131c8b59bfdd1c6314/vllm/model_executor/layers/attention.py) only 4 type of `head_size` is supported. Is there any reason why `head_size=256` is not supported yet?

Thanks!

[Update]
I checked the attention ops code [here](https://github.com/vllm-project/vllm/blob/998d9d15095e7a69629f9e131c8b59bfdd1c6314/csrc/attention/attention_kernels.cu#L396) and the comment said that to reduce compile time it allow only few head size. Therefore I uncomment it and recompile for the 256 head_size model, and it works well.

I'll close this issue.

**Comment by WoosukKwon** [comment]
@sungeuns Thanks for reporting the issue. Could you share the model you are using? We thought there are is open source model that uses `head_size` 256, except for GPT-J. This information will be very helpful for making our dev decision.

**Comment by sungeuns** [comment]
@WoosukKwon 
Hi, this is the [model](https://huggingface.co/nlpai-lab/kullm-polyglot-5.8b-v2) I've tested. It is based on GPT neo x but have 256 head_size.

**Comment by YuboFeng2023** [comment]
Hi all, thanks for awesome library!

Today, I also encountered this problem.
Why this issue is closed?
By other words, what should I do to solve this problem?

**Comment by sepilqi** [comment]
+1, thanks for awesome library!

Today, I also encountered this problem.
Why this issue is closed?
By other words, what should I do to solve this problem?

**Comment by WoosukKwon** [comment]
@sepilqi `xformers`, the library we use for computing attention, only supports certain shapes. I guess this is because their efficient attention implementation requires a memory alignment that is only satisfied with the supported shapes.
