### ISSUE TITLE
How to implement alltoall communication collective in vllm? Is it possible?

### ISSUE THREAD

**Issue by Eutenacity** [vllm-project/vllm#3020]
How to implement alltoall communication collective in vllm? Is it possible?

**Comment by tabbas97** [comment]
Was any testing done to understand if vLLM cannot gain any more performance from implementing alltoall communication ? 

I'm trying to understand the "not planned" part of this issue being closed.

**Comment by hmellor** [comment]
The issue was closed because it was:
- Stale
- Too vague to action
