### ISSUE TITLE
multi round decoding question

### ISSUE THREAD

**Issue by songtaoshi** [vllm-project/vllm#3021]
Hi, dear developers, thanks for reading my question!

I have question about multi round decoding. 

we send a prompt to generate,  (1. flash attn encode prompt 2. paged attn, single query decode)

but after the step, I continue send a prompt and want to use all before paged kv cache, how should I write the code. 

Is there any existing api to do this?

**Comment by songtaoshi** [comment]
@tmm1 @zxdvd @pcmoritz @ironpinguin @zhuohan123 @WoosukKwon

**Comment by robertgshaw2-neuralmagic** [comment]
This PR addresses your use case by automatically detecting saved kvs

https://github.com/vllm-project/vllm/pulls?q=is%3Apr+is%3Aopen+Automatic+prefix+caching+

**Comment by hmellor** [comment]
Closing as `--enable-prefix-caching` should enable the behaviour the OP is asking for.

However, see https://github.com/vllm-project/vllm/issues/4917 for discussion on whether it behaves as expected.
