### ISSUE TITLE
How to specify the max cache memory used while load model

### ISSUE THREAD

**Issue by jony0113** [vllm-project/vllm#3035]
I noticed that while vllm load model in a k8s pod, it use some cache memory, I just want to know how to specify the max size the cache use. So that I can run the pod with much lower memory.

In my case, I start a pod with 32G memory, it load the model successfully, use 100% memory, in which 4GB RSS and 28GB cache memory.

And I start another pod with 116GB memroy, which use 4GB RSS and 100GB cache memory

**Comment by esmeetu** [comment]
@jony0113  Try `--gpu-memory-utilization 0.5`. Be sure this value is limited in (0, 1].

**Comment by jony0113** [comment]
> @jony0113 Try `--gpu-memory-utilization 0.5`. Be sure this value is limited in (0, 1].

thanks for reply, but this param looks like only limit the max gpu memory.

in my case, the `cache memory` I mentioned is cpu memory

**Comment by BrianPark314** [comment]
hey @jony0113 were you able to resolve this issue?
