### ISSUE TITLE
Tokenization Issue for google/gemma-7b-it

### ISSUE THREAD

**Issue by rahuja23** [vllm-project/vllm#3036]
Hello All
I am trying deploy Gemm-7b-it model using vllm but when the Engine tries to download the tokenizer I am getting an error: OSError: Can't load tokenizer for 'google/gemma-7b-it'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'google/gemma-7b-it' is the correct path to a directory containing all relevant files for a GemmaTokenizerFast tokenizer. 
I am also attaching a screenshot of the error.

Any help would be appreciated.
![Screenshot 2024-02-26 at 13 39 25](https://github.com/vllm-project/vllm/assets/51020974/d2d94b93-de63-4f05-a27b-f03b7c42c9b4)

**Comment by esmeetu** [comment]
Hi @rahuja23, It seems like the huggingface authentication issue. Could you download it to local and try again?

**Comment by rahuja23** [comment]
Hi @esmeetu 
Yes, I tried it and now I get this error:
ValueError: Model architectures ['GemmaForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'FalconForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'OPTForCausalLM', 'PhiForCausalLM', 'QWenLMHeadModel', 'RWForCausalLM', 'YiForCausalLM']

Any idea why?

**Comment by esmeetu** [comment]
@rahuja23 Which version do you use? `Gemma` model was only supported at latest version: v0.3.2. Upgrade and see again.

**Comment by rahuja23** [comment]
Hi @esmeetu  I was able to resolve the issue but when I try to generate the output I get the following error:
<img width="1169" alt="Screenshot 2024-02-26 at 22 50 51" src="https://github.com/vllm-project/vllm/assets/51020974/15d33141-7671-41ac-b10b-a5adaf1d0bd7">
Any idea why?

**Comment by hmellor** [comment]
Closing as stale.
