### ISSUE TITLE
Support of AMD consumer GPUs

### ISSUE THREAD

**Issue by arno4000** [vllm-project/vllm#3040]
Is there a technical reason, why only AMD MI200 GPUs or newer are supported? I get the error `RuntimeError: FlashAttention only supports AMD MI200 GPUs or newer.`  when I try to run vllm on my RX 7900 XTX.

**Comment by Wintoplay** [comment]
what version of rocm?

**Comment by ihejia** [comment]
I also encountered the same problem, my software version is ROCm6.0,and my graphics card is 7900XT

**Comment by papasanimohansrinivas** [comment]
> I also encountered the same problem, my software version is ROCm6.0,and my graphics card is 7900XT

same here

**Comment by hongxiayang** [comment]
For 7900 series, gfx1100, currently, it is recommended to use the naive attention in vllm.
