### ISSUE TITLE
run qwen1.5-14b-chat with vllm container error.

### ISSUE THREAD

**Issue by James-Dao** [vllm-project/vllm#3051]
INFO 02-27 08:13:58 api_server.py:229] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, root_path=None, middleware=[], model='/root/.cache/huggingface/Qwen1.5-14B-Chat', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='cuda', engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 02-27 08:13:58 llm_engine.py:79] Initializing an LLM engine with config: model='/root/.cache/huggingface/Qwen1.5-14B-Chat', tokenizer='/root/.cache/huggingface/Qwen1.5-14B-Chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 02-27 08:14:19 llm_engine.py:337] # GPU blocks: 780, # CPU blocks: 327
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/vllm/entrypoints/openai/api_server.py", line 237, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/engine/async_llm_engine.py", line 625, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/vllm/engine/async_llm_engine.py", line 366, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/vllm/engine/llm_engine.py", line 123, in __init__
    self._init_cache()
  File "/workspace/vllm/engine/llm_engine.py", line 346, in _init_cache
    raise ValueError(
ValueError: The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (12480). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.

**Comment by thesues** [comment]
KV cache can not as many as requried seq_len. Maybe you could try to use smaller model or use multiple GPUs

**Comment by shiqingzhangCSU** [comment]
check your config.json , set seq_len=4096 will be helpfull. If you do not explicitly specify max_model_len when calling vllm engine, it will read seq_len in the model config.json, so either change the model config or specify max_model_len when starting the engine）

**Comment by DarkLight1337** [comment]
Closing as this has been answered.
