### ISSUE TITLE
batching in vllm

### ISSUE THREAD

**Issue by canamika27** [vllm-project/vllm#3055]
Team, I was trying to run VLLM with AWQ & FP16 with batch size of 32 & my prompts are approx 1000-2000 tokens. I was running on 1x A100 80GB system & I have observed a strange thing, in the entire batch the first sequence is taking most time to generate response among all the sequence. Please see the below example for batch id 9 where time to complete is around 20 sec for first sequence & remaining sequences are less than 1 sec. Same type of pattern I have observed for rest of batches I ran.

![image](https://github.com/vllm-project/vllm/assets/41502651/d72444eb-9751-4659-9759-103107a90693)

Did anyone observed the same pattern while using batches in VLLM  or has any idea on why we are getting this pattern ?

**Comment by robertgshaw2-neuralmagic** [comment]
How are you calculating the time for each sequence?

vLLM will process as many of the sequences in the same batch as your system allows (based on GPU memory). If you're calcuating `sequence_i`'s time as `arrival_time_i - arrival_time_i-1` then these results are what I would expect

**Comment by hmellor** [comment]
Closing as stale.
