### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by lixiaolx** [vllm-project/vllm#3057]
when I test for mutil-gpu with llama2-70b, run `vllm/examples/offline_inference.py` , use params `enforce_eager=False`, the result can output, but it occur some error
```
Prompt: 'Hello, my name is', Generated text: ' Dustin Nelson and I’m going to be posting articles and my thoughts' 
Prompt: 'The president of the United States is', Generated text: ' one of the most powerful people in the world, as the leader of the only' 
Prompt: 'The capital of France is', Generated text: ' one of the world’s leading cities in terms of art, fashion, food' 
Prompt: 'The future of AI is', Generated text: ' neither utopian nor apocalyptic—it’s both.\n' 
Exception ignored in: <function TCPStore.__del__ at 0x7f930d38e8c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cupyx/distributed/_store.py", line 59, in __del__
  File "/usr/local/lib/python3.10/dist-packages/cupyx/distributed/_store.py", line 109, in stop
  File "/usr/local/lib/python3.10/dist-packages/cupyx/distributed/_store.py", line 39, in join
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 257, in poll
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
TypeError: 'NoneType' object is not callable
```
 the error in the code https://github.com/vllm-project/vllm/blob/main/vllm/worker/model_runner.py#L750

**Comment by jaehwlee** [comment]
+1

**Comment by ThreeGold-Jiang** [comment]
+1, did you solve this problem?

**Comment by youkaichao** [comment]
@ThreeGold-Jiang  This is a bug of `cupy`, and we plan to remove `cupy` dependency with https://github.com/vllm-project/vllm/pull/3442 . Please stay tuned, or you can have a try using docker image built during CI of that PR, e.g. `docker pull us-central1-docker.pkg.dev/vllm-405802/vllm-ci-test-repo/vllm-test:a3c2340ae36ce8ee782691d30111377eaf7ae6ce` .

Feedback is welcome!

**Comment by leofang** [comment]
Hi, would you mind filing a bug to CuPy issue tracker so that we don't drop the ball? Thanks!
