### ISSUE TITLE
Can I send a termination signal before the service inference ends？

### ISSUE THREAD

**Issue by whyiug** [vllm-project/vllm#3059]
I used some models (say 10) for the classification task that were deployed as openai servers using vllm, that is, 10 servers in total.
Each request requests the inference services of these servers in parallel, and whenever one server returns a result, the service returns a result.
To save GPU resources, is there a way to terminate the inferencing of the other 9 services by passing a signal (context cancel)?

**Comment by tanmaylaud** [comment]
what was the solution?
