### ISSUE TITLE
Tips for reducing vulnerabilities in docker images

### ISSUE THREAD

**Issue by hughesadam87** [vllm-project/vllm#3062]
The Docker images produced by vLLM project have > 100 vulnerabilities

![image](https://github.com/vllm-project/vllm/assets/1972276/0c261765-fde2-4deb-8ca9-97ce3f346217)

These mostly come from the dependency on a full ubuntu base image.  This base image is great because it allows for installation of CUDA and other GPU dependencies.  It's difficult to find distroless cuda-ready images.  This issue is a request to find/create an image like that (preferably) or to reduce the vulnerabilities some other way, such as uninstalling unused ubuntu utils.

**Comment by hmellor** [comment]
Closing as stale
