### ISSUE TITLE
Recovery from OOM

### ISSUE THREAD

**Issue by Ja1Zhou** [vllm-project/vllm#3066]
I am instantiating an LLM class for local inference. I noticed that when an OOM error happens in `vllm.LLM.llm_engine.step()` and I capture it, previous requests are not aborted and would mess up with my next call to `LLM.generate`. I was wondering what is the proper way of recovering from OOM errors during inference?

**Comment by hmellor** [comment]
@Ja1Zhou did you find a solution for this?

**Comment by Ja1Zhou** [comment]
> @Ja1Zhou did you find a solution for this?
I didn't. Had to make sure that no OOMs would occur.
