### ISSUE TITLE
Watchdog caught collective operation timeout

### ISSUE THREAD

**Issue by liulisi16323** [vllm-project/vllm#3071]
vllm v0.3.1 running for 7 days. error in allreduce:
 `(RayWorkerVllm pid=1394) [E ProcessGroupNCCL.cpp:475] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=4967570, OpType=ALLREDUCE, NumelIn=73728, NumelOut=73728, Timeout(ms)=1800000) ran for 1800542 milliseconds before timing out.`

**Comment by simon-mo** [comment]
This has been fixed in vLLM v0.3.2 released last week.

**Comment by liulisi16323** [comment]
> This has been fixed in vLLM v0.3.2 released last week.

Are there more details about fixing this error? I haven't found the information in releases v0.3.2 note.
