### ISSUE TITLE
Feature support for Starcoder2

### ISSUE THREAD

**Issue by sh0416** [vllm-project/vllm#3075]
Could any expert support a new architecture (starcoder2)?

Might someone already do this work for vLLM.. isn't it?

If not, I will try to do it for myself.

https://huggingface.co/docs/transformers/main/en/model_doc/starcoder2

**Comment by esmeetu** [comment]
@mspronesti PR welcome!
Give some hints. You can implement based on `gpt_bigcode`: https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/gpt_bigcode.py.
It seems that just adding the `sliding_window` feature.

**Comment by sh0416** [comment]
It seems that `_MODEL_REGISTRY` is removed. Right?

https://docs.vllm.ai/en/latest/models/adding_model.html#register-your-model

**Comment by esmeetu** [comment]
> It seems that `_MODEL_REGISTRY` is removed. Right?
> 
> 
> 
> https://docs.vllm.ai/en/latest/models/adding_model.html#register-your-model

Good catch! Will update document later.
