### ISSUE TITLE
How to combine `accelerate.split_between_processes` with `vllm` (designate a specific gpu in each process)?

### ISSUE THREAD

**Issue by chujiezheng** [vllm-project/vllm#3088]
I would like to do distributed inference. Specifically, I hope to split the inference prompts between the multiple gpus (as done by `accelerate.split_between_processes`), and then launch `vllm` in each process. However, when I set `os.environ['CUDA_VISIBLE_DEVICES'] = 'x'` and create the model, the following error can be raised:
```
RuntimeError: torch.distributed is already initialized but the torch world size does not match parallel_config.world_size (4 vs. 1).
```
I understand this is because `accelerate` has initialized a distributed mode with world size 4. But for a small model (e.g., 7B), I do not need pp or tp. Do you have suggestions on how to resolve it?

**Comment by TankNee** [comment]
I have the same question. Did you solve this problem?
