### ISSUE TITLE
When is cpu kv cache supposed to be used?

### ISSUE THREAD

**Issue by g-eoj** [vllm-project/vllm#3094]
In my testing with many concurrent users, I see what appears to be changing of requests from `Running` to `Pending`. I've never seen `Running` change to `Swapped`, nor have I seen cpu kv cache at anything other than 0%.

```
INFO 02-28 21:48:18 metrics.py:161] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 44.9 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 82.1%, CPU KV cache usage: 0.0%
```

I have tried setting `swap_space` to a value equal to vram and that does not make a difference.

**Comment by shiqingzhangCSU** [comment]
mark

**Comment by g-eoj** [comment]
Closing as duplicate: https://github.com/vllm-project/vllm/issues/2853
