### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'  when trying prefix_pos parameter

### ISSUE THREAD

**Issue by jasonpump** [vllm-project/vllm#3098]
Run the codes 
`
outputs = llm.generate(prompts, sampling_params, prefix_pos=prefix_pos)
`
to try the prefix cache.

Got errors:
`
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'
`

I tried this within Vertex AI notebook, I confirmed that ldconfig was installed and executable. Any ideas?

**Comment by WoosukKwon** [comment]
Hi @jasonpump, the error happens for some GCP Debian images that do not have `ldconfig` in the path. Please run `export PATH=$PATH:/sbin` before running vLLM.
