### ISSUE TITLE
Support `ChatCompletion` Endpoint in OpenAI demo server

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#311]
@infwinston Feel free to use FastChat's completion template to implement a chat completion endpoint in our demo server. You can use the completion API as a reference:

https://github.com/vllm-project/vllm/blob/9d27b09d12767de775a92d765e177a61f8477189/vllm/entrypoints/openai/api_server.py#L88-L101

**Comment by gesanqiu** [comment]
I noticed that FastChat already have a [vllm_worker](https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py), so I think we could just use FastChat as frontend which provided OpenAI-Compatible APIs and vLLM as backend.

**Comment by zhuohan123** [comment]
> I noticed that FastChat already have a [vllm_worker](https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/vllm_worker.py), so I think we could just use FastChat as frontend which provided OpenAI-Compatible APIs and vLLM as backend.

Yes! FastChat is a great frontend to enjoy the benefit of vLLM. However, there are some more advanced options (e.g., beam search) that requires we implement a separate end point to support.

**Comment by gesanqiu** [comment]
I didn't run vllm_worker succeed yesterday and I found it use a older version of vllm, so I implement a ChatCompletion API at (#330 )[https://github.com/vllm-project/vllm/pull/330]

**Comment by zhuohan123** [comment]
Fixed by #330
