### ISSUE TITLE
Should one use tokenizer templates during offline inference?

### ISSUE THREAD

**Issue by vmkhlv** [vllm-project/vllm#3119]
Hi,

I've found that vllm uses [the default tokenizer templates](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/serving_chat.py#L50) when querying a model via API. However, it is unclear if one should apply the tokenizer templates before generating outputs when using vllm in the offline inference, which happens [here](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/llm.py). I've found some examples of using the templates during the offline inference (e.g., [here](https://modal.com/docs/examples/vllm_inference)), but I just wanted to clarify this.

Thank you.

**Comment by simon-mo** [comment]
This depends on the offline inference task. For simple completion task, no template is needed. Otherwise, the chat template is needed indeed! In particular, if you want to apply the system prompt by the model, or using chat/instruction tuned version of the model, then the template should be applied.

**Comment by vmkhlv** [comment]
Thanks for your response and your time. I am working with open-source instruction-tuned models (e.g., mistral, tulu, gemma) and standard tasks, such as summarization, story generation, etc. based on the dolly-databricks and hugginfaceh4/no_robots datasets. 

@simon-mo is it correct then to produce outputs as follows:
`prompt = "Write a story about a bull rider named Tom who gets lost at sea the one time he tries to go fishing. Make it less than 300 words."`

`llm = LLM('google/gemma-2b-it')`

`input = llm.llm_engine.tokenizer.tokenizer.apply_chat_template([{"role": "user", "content": prompt}], tokenize=False, add_generation_template=True)`

`llm.generate(input)`

**Comment by simon-mo** [comment]
Yup this looks good. If you are interested in contributing, either a page on documentation page, `LLM.chat`, or `LLM.apply_chat_template(user_prompt)` are all valid PRs we can accept!

**Comment by vmkhlv** [comment]
Thank you for your time once again @simon-mo. It is clear now. I hope I find time to contribute. Cheers.

**Comment by allanj** [comment]
> Thanks for your response and your time. I am working with open-source instruction-tuned models (e.g., mistral, tulu, gemma) and standard tasks, such as summarization, story generation, etc. based on the dolly-databricks and hugginfaceh4/no_robots datasets.
> 
> @simon-mo is it correct then to produce outputs as follows: `prompt = "Write a story about a bull rider named Tom who gets lost at sea the one time he tries to go fishing. Make it less than 300 words."`
> 
> `llm = LLM('google/gemma-2b-it')`
> 
> `input = llm.llm_engine.tokenizer.tokenizer.apply_chat_template([{"role": "user", "content": prompt}], tokenize=False, add_generation_template=True)`
> 
> `llm.generate(input)`

Thanks, this is indeed very helpful!

**Comment by zyxnlp** [comment]
> > Thanks for your response and your time. I am working with open-source instruction-tuned models (e.g., mistral, tulu, gemma) and standard tasks, such as summarization, story generation, etc. based on the dolly-databricks and hugginfaceh4/no_robots datasets.
> > @simon-mo is it correct then to produce outputs as follows: `prompt = "Write a story about a bull rider named Tom who gets lost at sea the one time he tries to go fishing. Make it less than 300 words."`
> > `llm = LLM('google/gemma-2b-it')`
> > `input = llm.llm_engine.tokenizer.tokenizer.apply_chat_template([{"role": "user", "content": prompt}], tokenize=False, add_generation_template=True)`
> > `llm.generate(input)`
> 
> Thanks, this is indeed very helpful!

@allanj Yes, indeed. I found it helpful too!
