### ISSUE TITLE
About special tokens

### ISSUE THREAD

**Issue by Changgeng-Wei** [vllm-project/vllm#3136]
When I use vllm and fastchat by chatglm3-6b, model always generate "assistant" special tokens, how can i fix it?
like:
"春风轻拂绿意新，|assistant|助时光荏苒。\n|assistant|勤勉不懈怠，|assistant|智慧照万方。"

**Comment by 777ki** [comment]
chang to another LLM model without `chat` fine tuning， baichuan-2 may be suit for you
