### ISSUE TITLE
ImportError: /usr/local/lib/python3.10/dist-packages/vllm/_C.cpython-310-x86_64-linux-gnu.so:

### ISSUE THREAD

**Issue by mohammad-yousuf** [vllm-project/vllm#3147]
I am trying to use vLLM with Langchain and I am getting this error:

`ImportError: /usr/local/lib/python3.10/dist-packages/vllm/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops15to_dtype_layout4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEEbbNS6_INS5_12MemoryFormatEEE`

CUDA: 12.0.1
torch : 2.2.1
transformers: 4.38.2
vllm: 0.3.2
accelerate: 0.27.2

Please help out if anyone solved this issue.

**Comment by mohammad-yousuf** [comment]
UPDATE:

solved by downgrading torch to 2.1.2

**Comment by 777ki** [comment]
loss symbol:at::_ops::to_dtype_layout::call(const at::Tensor &, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>)

that is just a torch version problem, vllm don't take care about this
