### ISSUE TITLE
Serve model Mixtral-8x7B on 4xA100 cuda=12.1, pytorch=2.1.2 failed

### ISSUE THREAD

**Issue by cometyang** [vllm-project/vllm#3152]
It display error message: 
"cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_INVALID_USAGE: invalid usage"

This error happens for vllm==0.3.2 while vllm==0.2.7 works oky.

To reproduce it:

python -m vllm.entrypoits.api_server --model mistralai/Mixtral-8x7B-v0.1 --tensor-parallel-size 2

**Comment by Jye-525** [comment]
I have the same error when running OPT-30B model with TP=2. I use torch==2.1.1, cuda=11.8, vllm==0.3.3
