### ISSUE TITLE
[v0.4.0] Release Tracker

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#3155]
**ETA:** Before Mar 28th

##  Major changes
TBD.

## PRs to be merged before the release
- [ ] #1507 
- [x] #2762 
- [ ] ...

**Comment by nivibilla** [comment]
@zhuohan123 do you think the second part for int8 inference should also be added into the roadmap?
https://github.com/vllm-project/vllm/pull/1508

**Comment by miko7879** [comment]
Would it be possible to request that the following is merged prior to release: https://github.com/vllm-project/vllm/pull/2961

It is preventing us from being able to deploy models using vLLM in certain contexts.

**Comment by Xu-Chen** [comment]
This amazing [MR](https://github.com/vllm-project/vllm/pull/2761) was originally supposed to be merged into the [previous version](https://github.com/vllm-project/vllm/issues/3097). Hope it can be merged this time. The speed improvement is very obvious.

**Comment by zhaoyang-star** [comment]
@zhuohan123 Hope Prefix Caching with FP8 KV cache support (https://github.com/vllm-project/vllm/pull/3234) could be merged.

**Comment by GennVa** [comment]
@zhuohan123 Would it be possible to request if #3233 can be merged in this release?
For a solution for #2398 and #3118
Thanks

**Comment by robertgshaw2-neuralmagic** [comment]
Cmake -> https://github.com/vllm-project/vllm/pull/2830

**Comment by simon-mo** [comment]
I'm planning to merge usage reporting PR by Monday.

**Comment by JMHenri** [comment]
We are very hopeful to have the JAIS commit in v0.3.4

**Comment by wsp317** [comment]
When do you plan to release v0.3.4?

**Comment by simon-mo** [comment]
We have a hard deadline to release it this week. Sorry about the detail.

**Comment by grandiose-pizza** [comment]
> We are very hopeful to have the JAIS commit in v0.3.4 [4c07dd2](https://github.com/vllm-project/vllm/commit/4c07dd28c0ef8642735222e077935b55f4c98017)

Hi @JMHenri , Please let me know in case you face any issues with the JAIS models. Since we don't have a chat_template in the tokenizer, please feel to reach out in case of any issues. 

You can certainly look into [this](https://github.com/vllm-project/vllm/pull/3183#issuecomment-1979122326) for reference on usage.
