### ISSUE TITLE
Request for fine-tuning using api endpoint

### ISSUE THREAD

**Issue by abhi1nandy2** [vllm-project/vllm#3159]
Similar to https://platform.openai.com/docs/guides/fine-tuning/example-format, could this feature be added? This would make fine-tuning much easier.

**Comment by ywang96** [comment]
My two cents are training should not be in the scope of this project as vLLM's focus is on model inference workload. If you're looking for an open source project that abstract all kinds of workloads as APIs, https://github.com/skypilot-org/skypilot should be the one.

**Comment by DavidPeleg6** [comment]
i suggest looking into llama-factory or axolotl for relatively simple fine tuning frameworks.

**Comment by hmellor** [comment]
Closing this as fine-tuning is out of scope for an inference serving framework.
