### ISSUE TITLE
[S-LoRA] Something is wrong with the s-lora arguments in server_api

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#3174]
I notice that there is no --lora-modules argument in the `vllm.entrypoints.api_server`, which means I must add the lora local path when sending request. 

That's unrealistic. Because the client doesn't know the lora path.

Any plan to fix it ?

**Comment by simon-mo** [comment]
Please use the `vllm.entrypoints.openai.apI_server` instead, which have similar functionality and OpenAI compatible API.

**Comment by sleepwalker2017** [comment]
> Please use the `vllm.entrypoints.openai.apI_server` instead, which have similar functionality and OpenAI compatible API.

thank you. Is there any script to benchmark the multiple lora serving?

**Comment by simon-mo** [comment]
I don't believe we have a full benchmark on LoRA. Please check out what we have in `benchmarks/` in the repo and contribution welcomed!

**Comment by sleepwalker2017** [comment]
> I don't believe we have a full benchmark on LoRA. Please check out what we have in `benchmarks/` in the repo and contribution welcomed!

ok, I find some performance issues and I'll post it.
