### ISSUE TITLE
How to load a local model file?

### ISSUE THREAD

**Issue by BUAADreamer** [vllm-project/vllm#318]
I want to load a local model which has the same file with the files downloaded from huggingface.
However, right now this repository seems to only support load from website.

**Comment by BUAADreamer** [comment]
The model directory is like follows
![image](https://github.com/vllm-project/vllm/assets/64362896/003cb2f3-c306-439a-84ce-0e6ef8415daf)

**Comment by liulfy** [comment]
I also have the same problem.

**Comment by WoosukKwon** [comment]
@BUAADreamer @liulfy The `model` argument in `LLM` or `api_server` can also take the path to your local directory that contains the weight files.

**Comment by BUAADreamer** [comment]
But this code seems to request huggingface website
```python
from vllm import LLM, SamplingParams
prompts = [
    "你好，请介绍一下你自己",
    "中国的定义是什么？"
]
sampling_params = SamplingParams(temperature=0.01, top_p=0.01)
llm = LLM(model="/path/to/llama")
```

**Comment by WoosukKwon** [comment]
@BUAADreamer Thanks for providing the example. It should not use the remote HF repo if the path is valid. Could you try this and let us know if it works?
```python
from transformers import AutoConfig

config = AutoConfig.from_pretrained("your/path/to/llama")
```
If this doesn't work, then it means your path is somehow incorrect (or it's a bug in HF).

**Comment by liulfy** [comment]
@WoosukKwon in my case, I cannot load from LLM, but I can load from AutoConfig:
![image](https://github.com/vllm-project/vllm/assets/27479464/d1a77700-e2ad-4519-aed1-69016d7193dc)

**Comment by BUAADreamer** [comment]
I use **Build from source** and run seccessfully. Thanks!

**Comment by Huangyajuan-123** [comment]
please describe the solution more detail, very thanks!

**Comment by liulfy** [comment]
Indeed. I built from source: https://github.com/vllm-project/vllm/releases/tag/v0.1.1, and this problem solved.

**Comment by BUAADreamer** [comment]
[https://vllm.readthedocs.io/en/latest/getting_started/installation.html](https://vllm.readthedocs.io/en/latest/getting_started/installation.html) 
just use the **Build from source** in this website and run like above, if it only report error, then set **tokenizer_mode='slow'**

**Comment by BUAADreamer** [comment]
> Indeed. I built from source: https://github.com/vllm-project/vllm/releases/tag/v0.1.1, and this problem solved.

Yes, this version works
