### ISSUE TITLE
[Fix] Speedup model loading with safetensor format

### ISSUE THREAD

**Issue by chaomengyuan** [vllm-project/vllm#3182]
In /vllm/model_executor/weight_utils.py

```
elif use_safetensors:
  for st_file in hf_weights_files:
    with safe_open(st_file, framework="pt") as f:
        for name in f.keys():  # noqa: SIM118
           param = f.get_tensor(name)
           yield name, param
```

The default device for safe_open is 'cpu', which in some case severely slows down the weight loading speed. For example, in our case, it takes 194s to load a llama2-7b model.

To fix this issue, we change the implementation a little bit:

```
elif use_safetensors:
  for st_file in hf_weights_files:
    with safe_open(st_file, framework="pt", **device=device**) as f:
        for name in f.keys():  # noqa: SIM118
           param = f.get_tensor(name)
           yield name, param
```

which speed up the loading time from 194s to 6s, 32x faster.

**Comment by simon-mo** [comment]
Please submit a PR! This makes a lot of sense.

**Comment by ymwangg** [comment]
Thanks for sharing the info! I'm also interested in optimizing model loading time. Quick question: I observed that the initial loading time of the model is significantly longer than subsequent loadings. Does vLLM incorporate a caching mechanism, so that it accelerates the subsequent loading?

**Comment by simon-mo** [comment]
No. I believe the reason you are observing this is due to file system memory cache in the operating system.

**Comment by ymwangg** [comment]
Thanks! That makes a lot of sense.
