### ISSUE TITLE
Question regarding PagedAttention Layer and Attention Processing for Batches

### ISSUE THREAD

**Issue by JinuJeong** [vllm-project/vllm#319]
Hello,

I would like to inquire about the behavior of the PagedAttention Layer. Upon reviewing its implementation, it appears that the layer processes all requests in a batch collectively, utilizing a single kernel. This raises a concern for me as it doesn’t seem to adopt a splitting mechanism prior to processing the attention operation.

To provide context, the ORCA paper, presented at OSDI 2022 ([link](https://www.usenix.org/conference/osdi22/presentation/yu)), introduces a split mechanism which enables selective batching or iteration-level scheduling. This mechanism ensures that each request within a batch pays attention solely to its own set of sentences.

In contrast, without employing such a splitting approach, there is a potential issue where requests within the batch (other than the first one) would inadvertently pay attention not only to their own sentences but also to unrelated sentences belonging to other requests.

I have empirically observed the repercussions of this behavior: I conducted a benchmark test using the benchmark_throughput script, and it was evident that the output text yielded divergent results depending on whether I executed it with a single prompt versus with 10 prompts.
```bash
# Input prompt
"I have a vast magic system but no plot, how can i write a compelling plot"

# Run one prompt
$ python3 benchmark_throughput.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json  --num-prompts 1 --model='facebook/opt-1.3b'
# Ouput prompt
"for my characters world.\n> no plot  Can you elaborate?</s>Cognizant Q4 profit up 10 pct, parts revenue growth misses estimates\nMarch 5 (Reuters) - Consulting company Cognizant Corp reported higher quarterly profit and revenue due in part to a strong performance in its healthcare services business and a healthy outsourcing market, but its profit growth missed analysts' estimates.\nCognizant's revenue rose 8 percent to $5.25 billion in the fourth quarter ended Jan. 31, from $5.05 billion a year earlier.\nNet profit rose to $975 million, or $1.04 per share, in the fourth quarter from $842 million, or 92 cents per share, a year earlier. Counting other unspecified items, Cognizant earned $1.05 per share.\nAnalysts on average were expecting earnings of 1.09 per share, according to Thomson Reuters I/B/E/S.\nThe company said that gross margin was 60.9 percent, compared with 62.4 percent in the year-earlier quarter. Shares of the company rose 2 percent to $45.72.\nThe company will hold one-day investor day on March 6, where it will provide suggestions for improving operating margins in the healthcare unit, according to a statement, saying the company intends to introduce a brand new operating model for the unit.\nThe filing also said that it expects to make necessary investments of $2.9 billion for the quarter ended March 31, 2018, of which an estimated $2.8 billion will primarily be invested in the healthcare unit.\nFor 2017, Cognizant's net revenue rose 4.8 percent to $"

# Run 10 prompts
$ python3 benchmark_throughput.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json  --num-prompts 10 --model='facebook/opt-1.3b'
# Ouput prompt
" for my current and future books?\nErm, where have you been? We have plot, it's just a matter of who has it relevant to them this particular timeand where you will fit it into the broader world.  I'll give you an example, I have a story where elves get cured so they all leave the manor. Now, where do they go? Enter another manor suite in the manor. Do they enter the halls of the old, or the new manor?\n...eh, it seemed too cheesy to be true. In all seriousness though, ill probably get it written once i get some ideas for my next book, hoping to focus on world building for Good Hunting and The Death Sceptre.\nInspiration can come from absolutely anywhere, so long as you let your story write itself. :)</s>Flirt, vibrate and spit in her face/mouth kiss all over her.  Simple dude, the cliffs are down boyzzzz\nAnd then whoop her butt!\nAnd if you're the one causing the problem tell her to lay off your dick.\nOr if you don't want to invent a new language, try telling em 'Goodbye' and then disappear! Lol\nShe might not get that memo.\nThere seem to be some other language things girls are great at!\nIt's like she knows them all!  She's got something *really* special.  I don't know if that's good or bad.\nHard to explain, but I'm feelin it</s>Public Release: 21-Mar-2012\nLost vaccine carries dangers, new study suggests\n\n426 patients [61% men; 71% Hispanic"
```
Could you please clarify whether the PagedAttention Layer incorporates any sort of splitting mechanism? If not, could you shed light on the rationale behind this design decision?

Thank you for your attention to this matter.

**Comment by WoosukKwon** [comment]
Hi @JinuJeong, thanks for your interest and good question!

vLLM does have the splitting mechanism, and never changes the semantics of the model. Our `InputMetdata` includes the metadata to identify which tokens belong to which sequences. You can see our input tensor data layout here:
https://github.com/vllm-project/vllm/blob/dafd924c1f165b4478a9d7a3c915d2ecc2e148e2/vllm/model_executor/layers/attention.py#L23-L25
The lengths of the prompts are stored in `input_metadata.attn_bias`, while the lengths of the cached sequences are stored in `input_metadata.context_lens`.

Batching can change the generated outputs because batching affects the state of the random generator in the sampler. In vLLM, the random generator's state is initialized **once** using the user-given seed (0 by default). If you use zero temperature (i.e., argmax sampling), then batching will not affect your output.

**Comment by JinuJeong** [comment]
Oh, thank you for your response. I was not fully aware of how `xformers.ops.memory_efficient_attention_forward` precisely operates in relation to the prompts.

Additionally, I noticed that when the temperature was set to 0, identical values were obtained.

Thank you once again for your assistance.
