### ISSUE TITLE
got completely wrong answer for openchat model with vllm

### ISSUE THREAD

**Issue by v-yunbin** [vllm-project/vllm#3195]
I got completely wrong answer for openchat model with vllm inference .  Tried multiple times and got completely wrong results：
model_name_or_path="../models/openchat-3.5-0106"
model = LLM(model=model_name_or_path)
```
while True:
      try:
            query = input("\n用户：")
      except UnicodeDecodeError:
            print("Detected decoding error at the inputs, please set the terminal encoding to utf-8.", file=sys.stderr)
            continue
      query = query.strip()
      if query == "stop":
         break
      if query == "clear":
         session_id = None
         os.system(clear_command)
      sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
      outputs = model.generate(query,sampling_params)
      print(f"回答结果:{outputs}")
```
I got right  answer for openchat model with transformers inference：
```
model_name_or_path="../models/openchat-3.5-0106"
model = AutoModelForCausalLM.from_pretrained(
    model_name_or_path,
    device_map="auto",
    offload_folder="offload",
    offload_state_dict=True,
    torch_dtype=torch.float16)
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
model.eval()
while True:
      try:
            query = input("\n用户：")
      except UnicodeDecodeError:
            print("Detected decoding error at the inputs, please set the terminal encoding to utf-8.", file=sys.stderr)
            continue
      query = query.strip()
      if query == "stop":
         break
      if query == "clear":
         session_id = None
         os.system(clear_command)
      system_promt = ""
      prompt = get_prompt(system_promt, query)
      inputs = tokenizer(prompt, return_tensors='pt').to('cuda')
      with torch.no_grad():
        output_ids = model.generate(
        **inputs,
        do_sample=True,
        temperature=0.5,
        top_k=40,
        eos_token_id=tokenizer.eos_token_id)
      result = tokenizer.batch_decode(output_ids)[0]
	  print(f"回答结果:{result}")
```

**Comment by hmellor** [comment]
You are using different sampling parameters on vLLM and HF, this isn't a valid comparison.

In your code you set:
- vLLM:
  - `temperature = 0.8 `
  - `top_p = 0.95`
- HF:
  - `temperature = 0.5`
  - `top_k = 40`

You'll also need to account for any potentially different defaults (I think vLLM tries to match HF defaults but I'm not 100% sure). The HF defaults are [here](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig) (some of which your model might override [here](https://huggingface.co/openchat/openchat_3.5/blob/main/generation_config.json)) and the vLLM defaults are [here](https://github.com/vllm-project/vllm/blob/05af6da8d927f70d15ab1ed25b01df3c967ad961/vllm/sampling_params.py#L25).

**Comment by v-yunbin** [comment]
> You are using different sampling parameters on vLLM and HF, this isn't a valid comparison.
> 
> In your code you set:
> 
> * vLLM:
>   
>   * `temperature = 0.8 `
>   * `top_p = 0.95`
> * HF:
>   
>   * `temperature = 0.5`
>   * `top_k = 40`
> 
> You'll also need to account for any potentially different defaults (I think vLLM tries to match HF defaults but I'm not 100% sure). The HF defaults are [here](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig) (some of which your model might override [here](https://huggingface.co/openchat/openchat_3.5/blob/main/generation_config.json)) and the vLLM defaults are [here](https://github.com/vllm-project/vllm/blob/05af6da8d927f70d15ab1ed25b01df3c967ad961/vllm/sampling_params.py#L25).

Setting the same parameters still gets wrong results for vllm offline inference but gets right results for vllm server ：
temperature = 0.5
top_k = 40

**Comment by hmellor** [comment]
Can you provide an example input that I can use to validate this?

**Comment by Qubitium** [comment]
@v-yunbin  Try vllm with cuda graphs disabled using `enforce_eager=True`.

**Comment by v-yunbin** [comment]
> Can you provide an example input that I can use to validate this?

examle：
question1：who are you
answer1：I am a freelance writer, editor, and content strateg.
question1：你是谁
answer1：？\n\n你是谁？\n\n你是谁

**Comment by v-yunbin** [comment]
> @v-yunbin Try vllm with cuda graphs disabled using `enforce_eager=True`.

try it， not work

**Comment by 50Bytes-dev** [comment]
@v-yunbin how did you solve the error?
