### ISSUE TITLE
Error when deploying to Sagemaker starting from release 0.3.0

### ISSUE THREAD

**Issue by miko7879** [vllm-project/vllm#3212]
Since release 0.3.0 we have been unable to deploy vLLM containers to Sagemaker. It has to do with the `get_ip()` function call in `utils.py`. In release 0.3.0 we got an OS error, and with 0.3.3 we are getting the following: `socket.gaierror: [Errno -2] Name or service not known`, when making the following call: `s.connect(("dns.google", 80))`. Could you please add something to make the `get_ip()` function fall back to what was there in release `0.2.7` if all else fails?

For reference, here is the function call in `0.2.7`: https://github.com/vllm-project/vllm/blob/v0.2.7/vllm/utils.py#L60

In `0.3.0` it was changed to the following, and stopped working on Sagemaker: https://github.com/vllm-project/vllm/blob/v0.3.0/vllm/utils.py#L164

It is now as follows: https://github.com/vllm-project/vllm/blob/v0.3.3/vllm/utils.py#L172

**Comment by simon-mo** [comment]
This might be fixed by https://github.com/vllm-project/vllm/pull/3176

**Comment by miko7879** [comment]
I don't believe that #3176 will resolve this because it has been failing with release tag `0.3.0`, which uses the same line as in #3176

**Comment by miko7879** [comment]
I believe this will be resolved by #2961

**Comment by a1164714** [comment]
i got the same error.

**Comment by DefTruth** [comment]
same error, even the 8.8.8.8 is unreachable in my env.

**Comment by miko7879** [comment]
@a1164714 @DefTruth I'm glad I'm not the only one haha. Could you please thumbs up my comment on the release tracker to try and get the fix pushed in to 0.3.4?

https://github.com/vllm-project/vllm/issues/3155#issuecomment-1981476964

**Comment by miko7879** [comment]
Confirmed that this issue is fixed starting 0.4.0.
