### ISSUE TITLE
Add Support for QLORA/QA-QLORA weights which are not merged

### ISSUE THREAD

**Issue by orellavie1212** [vllm-project/vllm#3225]
currently only original LORA is supported as not fused adapter, I hope to be able to add the support for QLORA/QA-LORA support for the adapters, without fusing with the base model.

**Comment by chenqianfzh** [comment]
Hi, I am workig on adding QLora support to Vllm.

The first model to support would probably be timdettmers/qlora-alpaca-13b ( and some other qlora models presented by timdettmers in hugging face).
