### ISSUE TITLE
Is it possible to pass more than 1 token during decoding?

### ISSUE THREAD

**Issue by thisissum** [vllm-project/vllm#3244]
I'm tring to implement fast json decoding, but I found that when I pass 2 or more tokens in one iteration, there comes an illegal memroy access error.
The idea is inspired by this blog: 
https://lmsys.org/blog/2024-02-05-compressed-fsm/

**Comment by simon-mo** [comment]
Not possible right now. But we are excited to approach this in collaboration with outlines (cc @rlouf)
