### ISSUE TITLE
Is there a ModelList that supports LoRA adapter?

### ISSUE THREAD

**Issue by xiaobo-Chen** [vllm-project/vllm#3245]
ValueError: Model ChatGLMForCausalLM does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

Where can I find information about which models are supported? And is there a schedule for adapting models?

**Comment by zxdposter** [comment]
+1, please support lora for chatglm3.

**Comment by simon-mo** [comment]
The list is now at https://docs.vllm.ai/en/latest/models/supported_models.html a new LoRA column was added by @pcmoritz.
