### ISSUE TITLE
I found a potential error in the source code.

### ISSUE THREAD

**Issue by wenjunlong** [vllm-project/vllm#328]
In the file scheduler.py， I find this 
`
num_batched_tokens = sum(
            seq_group.num_seqs(status=SequenceStatus.RUNNING)
            for seq_group in self.running
        )
`

and this 

`
               # If the number of batched tokens exceeds the limit, stop.

                num_prompt_tokens = seq_group.get_seqs()[0].get_len()
                if (num_batched_tokens + num_prompt_tokens
                    > self.scheduler_config.max_num_batched_tokens):
                    break
`

and this 

`
num_batched_tokens += num_prompt_tokens
`

num_batched_tokens  is defined as the number of sequences, while num_prompt_tokens  is defined as the number of tokens of a waiting sequence,  and  the new num_batched_tokens  is defined as the sum of them.  should it be an error?

**Comment by akxxsb** [comment]
I have the same question, anyone can answer it ?

**Comment by LiuXiaoxuanPKU** [comment]
For each running request, one token is batched. For each waiting request, the whole prompt is sent to the current step. Therefore, the total number of tokens equals the number of running requests plus the length of the prompt in the waiting queue.

**Comment by LiuXiaoxuanPKU** [comment]
<img width="851" alt="Screen Shot 2023-07-08 at 10 47 23 AM" src="https://github.com/vllm-project/vllm/assets/16137495/7f63e098-a2ed-4a00-a664-166c2c4fc623">
To be more concrete, suppose there are four requests x1,x2,x3,x4. Grey blocks represent input prompts.  x3, x4 are new requests (in waiting state). x1 and x2 have already been processed (in running state). We already generate token x13, x14 for request x1 and token x22 for request x2. vllm batches different requests in a single generation step. For the next step, (x14, x22, x31x32, x41x42x43) are tokens batched as input for generating the next tokens for different requests.

**Comment by wenjunlong** [comment]
Thank you for your patient explanation
