### ISSUE TITLE
Order of keys for guided JSON

### ISSUE THREAD

**Issue by ccdv-ai** [vllm-project/vllm#3283]
Hi

Trying to use a json template with a mixtral 7x8b model.
However the model generates the json with keys in alphabetic order which has a significant impact on generation quality (for my task at least).

```python

json_template= {
    "type": "object",
    "properties": {
        "first_key": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1
            },
        "another_key": {
            "type": "array",
            "items": {"type": "string"},
            "minItems": 1
            },
    "required": ["first_key", "another_key"]
    }

chat_response = client.chat.completions.create(
    model=model,
    messages=[
        {"role": "user", "content": prompt},
    ],
    max_tokens=256,
    temperature=0.7,
    top_p=1,
    extra_body=dict(guided_json=json_template)
)

# The returned JSON is in alphabetic order
> "{'another_key': ['some_output'], 'first_key': ['another_output']}"
```
Is there a way to force the generation to follow the initial pattern (without alphabetic order)?

**Comment by rlouf** [comment]
Outlines (used for JSON-structured generation) keeps the same order for the field as in the schema. If it turns out that's not the case then please open an issue on our end.

**Comment by simon-mo** [comment]
Thanks @rlouf. Closing this issue on our end.

**Comment by Patrick10203** [comment]
I have exactly the same issue. Only get alphabetic sorted jsons as result when providing a guided_json that is not alphabeticaly sorted. This has to be a bug.

**Comment by vpetren** [comment]
Bumping this one, even though it's was closed @ccdv-ai , @simon-mo

This happens since the keys are sorted when the dictionary is dumped into a string in the following line:
https://github.com/vllm-project/vllm/blob/5ee14494e4c78769fa10af8b58c3e7808053da0d/vllm/model_executor/guided_decoding.py#L94

Is there any particular reason for forcing this?

**Comment by onebula** [comment]
> Hi
> 
> Trying to use a json template with a mixtral 7x8b model. However the model generates the json with keys in alphabetic order which has a significant impact on generation quality (for my task at least).
> 
> ```python
> json_template= {
>     "type": "object",
>     "properties": {
>         "first_key": {
>             "type": "array",
>             "items": {"type": "string"},
>             "minItems": 1
>             },
>         "another_key": {
>             "type": "array",
>             "items": {"type": "string"},
>             "minItems": 1
>             },
>     "required": ["first_key", "another_key"]
>     }
> 
> chat_response = client.chat.completions.create(
>     model=model,
>     messages=[
>         {"role": "user", "content": prompt},
>     ],
>     max_tokens=256,
>     temperature=0.7,
>     top_p=1,
>     extra_body=dict(guided_json=json_template)
> )
> 
> # The returned JSON is in alphabetic order
> > "{'another_key': ['some_output'], 'first_key': ['another_output']}"
> ```
> 
> Is there a way to force the generation to follow the initial pattern (without alphabetic order)?

Based on the code found by @vpetren , you can simply pass a json str instead of dict to the argument guided_json, i.e.,

`extra_body=dict(guided_json=json.dumps(json_template))`

**Comment by psykhi** [comment]
Hey! Just encoutered this issue and can say that converting my schema to string works. Would be great if vLLM didn't change the order of keys when passing the schema though (it doesn't seem needed at all?)

**Comment by davidgxue** [comment]
Fixing this feels trivial right? just getting rid of the `sort_keys=True` param passed to `json_dumps`? Or are we looking  for some kind of propagation from user's args (that feels a bit unnecessary)?

**Comment by simon-mo** [comment]
yes, plz pr.

**Comment by syGOAT** [comment]
https://github.com/vllm-project/vllm/blob/ccdc490dda3f534c63c1faf29a638e65594d0dc3/vllm/model_executor/guided_decoding/outlines_decoding.py#L88
It has been fixed in branch `main`. You can close this issue. @simon-mo

**Comment by datalee** [comment]
mark

**Comment by eloaf** [comment]
I think this is still happening in `0.11.0`
