### ISSUE TITLE
Mixtral 4x 4090 OOM

### ISSUE THREAD

**Issue by SinanAkkoyun** [vllm-project/vllm#3285]
Hi! TP 4, model len 1000, enforce eager, multiple gpu utilizations; Nothing helps. I am testing on a 4x 4090 rig and I always get an OOM error, no matter what I try.

Thanks in advance!

**Comment by SinanAkkoyun** [comment]
Same for the TheBlokes AWQ quantized model... Although, there with enforce-eager it works with a model len of 1000, but with 4x 24GB I should be able to even run the fp16 version with eager, but I recieve an OOM

**Comment by r000bin** [comment]
I've found this in the discussions on the hf modelcard:
"You can in total think of 120GB/140GB of VRAM needed for the unquantized version of Mixtral, so 2xNvidia A100 80GB needed."

**Comment by SinanAkkoyun** [comment]
@r000bin Ah okay, I believed I read around 92GB for bf16

But the AWQ shouldn't take that much right?

**Comment by hmellor** [comment]
Mixtral AWQ is ~25GB for weights (https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ/tree/main)

**Comment by r000bin** [comment]
AWQ has still some problems. It should run with enforce_eager or in my case gpu_memory_utilization=0.9

enforce_eager slows down the inference a bit

I'm running [Mixtral](https://huggingface.co/ybelkada/Mixtral-8x7B-Instruct-v0.1-AWQ) on 4 L4 GPU

**Comment by tsvisab** [comment]
If you run via a container then make sure you set --shm_size=SOME_SIZE_IN_MB 
try multiples of 1024

**Comment by SinanAkkoyun** [comment]
@hmellor Thanks for the info; then how come I get OOMs with 4x 24GB GPUs?

**Comment by hmellor** [comment]
Depending on the sequence length of your model you could need a lot of VRAM for KV cache. There is also the memory consumed by the compiled CUDA graph (this can be disabled with `--enforce-eager`).

For now, I'll close this as stale.
