### ISSUE TITLE
Is there any possible way using tensor parallel with ray serve (for multi-replica)?

### ISSUE THREAD

**Issue by SwordFaith** [vllm-project/vllm#3294]
Any possible work solution or some solution need to be figure out are welcome
I'm willing to contribute, but with only a few experience with using vllm for custom model inference

**Comment by simon-mo** [comment]
Yes I believe you can set `ray_actor_options` in Ray Serve to be `{"num_gpus": 2}` and setup vLLM with `tensor_parallel_size=2`.

**Comment by SwordFaith** [comment]
I've tried, in my ray 2.9.3 and vllm 0.3.0 env, I use tensor_parallel_size=2 and not set num_gpus works with ray serve. Thanks  for you guys help.
