### ISSUE TITLE
v0.3.3 vllm.entrypoints.openai.api_server  error

### ISSUE THREAD

**Issue by Uhao-P** [vllm-project/vllm#3296]
1. GPU：4090 * 4
2. `pip install vllm==0.3.3`
3. `python3 -m vllm.entrypoints.openai.api_server   --model /Llama-2-7B-Chat-hf/   --engine-use-ray   --host 0.0.0.0   --port 8080   --worker-use-ray   --max-num-seqs 64   --tensor-parallel-size 4`
4. When I send a request：![image](https://github.com/vllm-project/vllm/assets/42427430/92e6ca0f-8f49-4800-b8d7-fc4981c57323)
5. The following error occurs![image](https://github.com/vllm-project/vllm/assets/42427430/4354f758-e1ce-4345-a3a0-4ea1b29c5108)

**Comment by esmeetu** [comment]
@Uhao-P  Have you tried other models?

**Comment by Uhao-P** [comment]
Tried, same error

**Comment by esmeetu** [comment]
@Uhao-P Could you try #3301?

**Comment by Uhao-P** [comment]
@esmeetu 
I tried #3301 ，But the following error occurs

1. git clone https://github.com/esmeetu/vllm.git -b fix-tokenizer
2. cd vllm
3. pip install -e .
4.  python3 -m vllm.entrypoints.openai.api_server   --model /input2/   --engine-use-ray   --host 0.0.0.0   --port 8080   --worker-use-ray   --max-num-seqs 64   --tensor-parallel-size 4

![image](https://github.com/vllm-project/vllm/assets/42427430/64b4706d-03a1-48e3-a5b4-9aa3608ddd44)

**Comment by nikitaCodeSave** [comment]
Try changing port 8080 to a different port. This port may be reserved on some systems

INFO seems to have automatically assigned you a different port and this may be the problem.
