### ISSUE TITLE
Question regarding GPU memory allocation

### ISSUE THREAD

**Issue by wx971025** [vllm-project/vllm#3302]
The startup parameter is：
python -m vllm.entrypoints.gemma_7b_it \
      --model "./gemma_7b_it" \
      --port 7501  \
      --gpu-memory-utilization 1 \
      --max-num-seqs 1024   \
      --tensor-parallel-size 4 \
      --dtype half \
      --trust-remote-code
The memory consumption is about 8G on 4xT4
When I set the --max-num-seqs parameter to 100，The memory consumption is about 15G on 4xT4
Why is --max-num-seqs smaller but GPU memory consumption higher？

**Comment by hmellor** [comment]
Maybe because you've not used a power of 2? What happens if you set it to 128?
