### ISSUE TITLE
Where are the default chat templates stored

### ISSUE THREAD

**Issue by jmoney** [vllm-project/vllm#3322]
I'm trying to write my own chat template for mixtral8 but I cannot find the jinja file.  I read somewhere they are stored with the tokenizer, but even that i can't find the exact one for mixtral8.  I am totally sure i'm just missing something.

**Comment by mgoin** [comment]
@jmoney chat templates are most commonly stored in the `tokenizer_config.json`. Here is the entry for mixtral https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/blob/1e637f2d7cb0a9d6fb1922f305cb784995190a83/tokenizer_config.json#L42

**Comment by jmoney** [comment]
And thus why I couldn't find it. That is an obvious place to put them, and just didn't think where to look. Thanks much
