### ISSUE TITLE
RuntimeError: Cannot find any model weights with vicuna

### ISSUE THREAD

**Issue by siyuyuan** [vllm-project/vllm#3329]
Does vllm supports vicuna? I check the doc and find it supports, but when I use:
`python3 -u -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model /home/huggingface_models/models--lmsys--vicuna-13b-v1.5/snapshots/3deb0106f72a3a433f0c6ea0cb978bdf14bcd3a6 --tensor-parallel-size 2 --load-format safe-tensors --port 8401`

It returns:
`RuntimeError: Cannot find any model weights with `/home/huggingface_models/models--lmsys--vicuna-13b-v1.5/snapshots/3deb0106f72a3a433f0c6ea0cb978bdf14bcd3a6``

In /home/huggingface_models/models--lmsys--vicuna-13b-v1.5/snapshots/3deb0106f72a3a433f0c6ea0cb978bdf14bcd3a6, I have

![image](https://github.com/vllm-project/vllm/assets/56245837/00cc59df-e57f-4791-8e93-5bc8f132df21)

Do you know what is wrong?

**Comment by youkaichao** [comment]
I think the problem is you are using `--load-format safetensors`. It requires some files with `.safetensors`.

**Comment by siyuyuan** [comment]
> I think the problem is you are using `--load-format safetensors`. It requires some files with `.safetensors`.

Thank you so much!
