### ISSUE TITLE
Support for Condensed RotaryEmbeddings

### ISSUE THREAD

**Issue by winglian** [vllm-project/vllm#333]
looks like there are various methods of extending context length, suck as superhot, ntk-aware, and condensed rope. This request is to track support for condensed rotaryembeddings as it seems to have the best performance at long contexts atm.

https://lmsys.org/blog/2023-06-29-longchat/
https://github.com/lm-sys/FastChat/blob/3f0c6e54498e179098ead9a596929e23327ad75c/fastchat/model/llama_condense_monkey_patch.py#L68

**Comment by zhuohan123** [comment]
cc @dachengli1

**Comment by DachengLi1** [comment]
Great to hear this feature request! Also excited to see support from VLLM Team!
