### ISSUE TITLE
Is it possible to use vllm-0.3.3 with CUDA 11.8

### ISSUE THREAD

**Issue by HSLUCKY** [vllm-project/vllm#3332]
I already have torch 2.1.2+cu118 installed from https://download.pytorch.org/whl/cu118, which matches the version of CUDA installed on my machine.

>>> import torch
>>> torch.__version__
'2.1.2+cu118'

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

After modifying the requirements.txt (replacing cupy-cuda12x with cupy-cuda11x), I tried to build vllm-0.3.3 from source with "pip install -e .". However, I eventually got a error saying,

RuntimeError:
      The detected CUDA version (11.8) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.
	  

I also tried to install vllm with "pip install vllm", which turned out to be dependent on cuda12.1 as well.

So I am wondering if it is possible to use vllm-0.3.3 with CUDA 11.8. If so, could you help me solve this problem? Thanks!

**Comment by chenxu2048** [comment]
Could you check your torch version with pip?
```
pip list | grep torch
```

**Comment by HSLUCKY** [comment]
I tried "pip install https://github.com/vllm-project/vllm/releases/download/v0.3.3/vllm-0.3.3+cu118-cp310-cp310-manylinux1_x86_64.whl", which has packages involving CUDA12 such as nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12 installed. 

After a seemingly succesful installation, I ran two models with fastchat and vllm, resulting in garbled replies in both cases, which I suspect may be caused by incompatible CUDA12 packages.

**Comment by Wingzard17** [comment]
> Could you check your torch version with pip?
> 
> ```
> pip list | grep torch
> ```

1. The environment where this mismatch error happened when building vllm from source:

pip list | grep torch
torch              2.1.2+cu118
torchaudio         2.1.2+cu118
torchvision        0.16.2+cu118


2. The environment where vllm is installed with "pip install https://github.com/vllm-project/vllm/releases/download/v0.3.3/vllm-0.3.3+cu118-cp310-cp310-manylinux1_x86_64.whl":

pip list | grep torch
torch                     2.1.2

**Comment by chenxu2048** [comment]
> > Could you check your torch version with pip?
> > ```
> > pip list | grep torch
> > ```
> 
> 1. The environment where this mismatch error happened when building vllm from source:
> 
> pip list | grep torch torch 2.1.2+cu118 torchaudio 2.1.2+cu118 torchvision 0.16.2+cu118
> 
> 2. The environment where vllm is installed with "pip install https://github.com/vllm-project/vllm/releases/download/v0.3.3/vllm-0.3.3+cu118-cp310-cp310-manylinux1_x86_64.whl":
> 
> pip list | grep torch torch 2.1.2

We have to install torch 2.1.2+cu118 before install the whl package, since pip automatically installs torch 2.1.2 instead of torch 2.1.2+cu118 from package dependencies.

Maybe you can try `pip install -e . --no-build-isolation`, which solved the same problem in https://github.com/vllm-project/vllm/issues/1453#issuecomment-1952950277.

pip install dependences from requirements.txt into a building environment when running without ``--no-build-isolation``. And torch 2.1.2 would be installed instead of torch 2.1.2+cu118.

**Comment by Wingzard17** [comment]
> > > Could you check your torch version with pip?
> > > ```
> > > pip list | grep torch
> > > ```
> > 
> > 
> > 
> > 1. The environment where this mismatch error happened when building vllm from source:
> > 
> > pip list | grep torch torch 2.1.2+cu118 torchaudio 2.1.2+cu118 torchvision 0.16.2+cu118
> > 
> > 2. The environment where vllm is installed with "pip install https://github.com/vllm-project/vllm/releases/download/v0.3.3/vllm-0.3.3+cu118-cp310-cp310-manylinux1_x86_64.whl":
> > 
> > pip list | grep torch torch 2.1.2
> 
> We have to install torch 2.1.2+cu118 before install the whl package, since pip automatically installs torch 2.1.2 instead of torch 2.1.2+cu118 from package dependencies.
> 
> Maybe you can try `pip install -e . --no-build-isolation`, which solved the same problem in [#1453 (comment)](https://github.com/vllm-project/vllm/issues/1453#issuecomment-1952950277).
> 
> pip install dependences from requirements.txt into a building environment when running without `--no-build-isolation`. And torch 2.1.2 would be installed instead of torch 2.1.2+cu118.

Thank you for your suggestion! But xformers 0.0.23.post1 is dependent on CUDA 12.1, which prevents me from running a model, showing such an error:

xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cu118)
    Python  3.10.13 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)

Have you encountered this kind of problem?

**Comment by chenxu2048** [comment]
> Then I reinstall xformers with https://download.pytorch.org/whl/cu118/xformers-0.0.23.post1%2Bcu118-cp310-cp310-manylinux2014_x86_64.whl#sha256=dc5f828dbe187c1bf69d41853a55170d2506ff4c40fc0dfbea3bc7e18daed2e5. And it finally works!

Thank you for your additional explanation. xFormers also requires CUDA 11.8. So just reinstall it from https://download.pytorch.org/whl/cu118.
```
pip install --index-url  https://download.pytorch.org/whl/cu118 xformers=0.0.23.post1
```

---

BTW, maybe we could install vllm with the command.

```
pip install . --extra-index-url  https://download.pytorch.org/whl/cu118
```

Pip would choose xxx+cu118 in extra-index instead of xxx in index. (Not sure if it will work in all case)

**Comment by Wingzard17** [comment]
> > Then I reinstall xformers with https://download.pytorch.org/whl/cu118/xformers-0.0.23.post1%2Bcu118-cp310-cp310-manylinux2014_x86_64.whl#sha256=dc5f828dbe187c1bf69d41853a55170d2506ff4c40fc0dfbea3bc7e18daed2e5. And it finally works!
> 
> Thank you for your additional explanation. xFormers also requires CUDA 11.8. So just reinstall it from https://download.pytorch.org/whl/cu118.
> 
> ```
> pip install --index-url  https://download.pytorch.org/whl/cu118 xformers=0.0.23.post1
> ```
> 
> BTW, maybe we could install vllm with the command.
> 
> ```
> pip install . --extra-index-url  https://download.pytorch.org/whl/cu118
> ```
> 
> Pip would choose xxx+cu118 in extra-index instead of xxx in index. (Not sure if it will work in all case)

Yes, that would be much more elegant.

**Comment by Genuifx** [comment]
After building vllm from source code, I get this error 

```
/vllm/vllm/model_executor/parallel_utils/cupy_utils.py", line 110, in all_reduce
    cupy_input._torch_dtype = torch_dtype  # pylint: disable=protected-access
AttributeError: 'ndarray' object has no attribute '_torch_dtype' 
```
I was following the requirements.txt , by installing cupy-cuda11x

```
cupy-cuda12x == 12.1.0  # Required for CUDA graphs. CUDA 11.8 users should install cupy-cuda11x instead.
```

**Comment by youkaichao** [comment]
> ```
> AttributeError: 'ndarray' object has no attribute '_torch_dtype' 
> ```

What is your `numpy` version?

**Comment by Genuifx** [comment]
@youkaichao 1.26.1

**Comment by chenxu2048** [comment]
> 'ndarray' object has no attribute '_torch_dtype'

Hi, @Genuifx. Did you try the solutions in the issue https://github.com/vllm-project/vllm/issues/3033#issuecomment-1963521075?

**Comment by Genuifx** [comment]
oh, thank you @chenxu2048 , fixed this error by downgrade cupy-cuda11x from 13 to 12.1.0.
