### ISSUE TITLE
What's difference between the seed in LLMEngine and seed in SamplingParams?

### ISSUE THREAD

**Issue by tomdzh** [vllm-project/vllm#3333]
I saw that vllm started to support per-request seed from 0.3.2. As far as I understand, we can set the seed both in [LLM engine](https://github.com/vllm-project/vllm/blob/654865e21df8ac6fe95de926625306e5756c2c0d/vllm/engine/llm_engine.py#L85) and in [SamplingParams](https://github.com/vllm-project/vllm/blob/654865e21df8ac6fe95de926625306e5756c2c0d/vllm/sampling_params.py#L107). Can anyone suggest the best practice of setting the random seed? For example, assuming I want only one seed, should I set it in the engine or in the sampling parameter? Does the seed in the sampling parameter override the other? Thanks!

**Comment by tomdzh** [comment]
Bump up

**Comment by njhill** [comment]
@tomdzh the LLM engine seed is mainly for use in tests, it provides some amount of determinism when the precise same sequence of operations are performed following the engine's construction.

The seed in SamplingParams applies to the corresponding request. So individual users can pass the same seed to the API with nonzero temperature and get (mostly) repeatable results, even when the engine is processing other requests concurrently.

**Comment by aleksanderhan** [comment]
I'm having the opposite experience. I cannot get the generation to be diverse at all, i set the temperature and random seeds for the samplingparams, but the generation is still the same in the same batch...

**Comment by tonyaw** [comment]
@njhill ,
I want LLM to generate 100% deterministic result. (Same prompt leads to 100% same generation output).
I know it can't be 100% guaranteed, but I want to do my best to guarantee it. :-)
Could you please help to check if I missed any parameter that can ensure deterministic result?

- Server side:
```
--seed 42
```
- Client side
```python
'temperature': 0,
"seed": 42,
"extra_body": {
    "top_k": 1,
},
