### ISSUE TITLE
how to reduce gpu memory in vllm

### ISSUE THREAD

**Issue by whk6688** [vllm-project/vllm#3345]
when i run it with:
 python -m vllm.entrypoints.openai.api_server --model /home/wanghaikuan/code/LLaMA-Factory/qw7bint4 --trust-remote-code --max-model-len 2046 --host 104.171.202.141 --port 8087  --gpu-memory-utilization 0.15

![image](https://github.com/vllm-project/vllm/assets/17873056/57094c53-c888-44d5-81e6-808eed52c022)

i think 7G is enough, in fact, it need 10G almost.
Is there any parameters to reduce gpu memory.
Thanks!

**Comment by whk6688** [comment]
when gpu-memory-utilization is 0.2 (10G),  it looks ok.  set  gpu-memory-utilization=0.15, will fail to run

**Comment by hmellor** [comment]
You can decrease `--max-model-len` to make the KV cache smaller and use `--enforce-eager` to stop CUDA graphs from consuming memory (at the cost of performance).

**Comment by ee2110** [comment]
Hi @hmellor I would like to ask more info about how can we avoid CUDA graphs from consuming memory, I have use `--enforce-eager` in command such as `python main.py --enforce-eager` but it still running CUDA graph. I can't find any more relevant information in the documentation. In addition, I also found the answer generated is not a complete sentence. What are the parameters I should change?

I am using `pip install vllm` to install VLLM as provided.

Following is my test code:
```
from vllm import LLM, SamplingParams

prompts = [
    "Briefly list down the steps to perform Cook Bacon.",
    "What is the definition of gravity?",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="lmsys/vicuna-13b-v1.3", seed=1024)

outputs = llm.generate(prompts, sampling_params)
# print(outputs)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
 ```
