### ISSUE TITLE
inference with AWQ quantization

### ISSUE THREAD

**Issue by Kev1ntan** [vllm-project/vllm#3348]
Hi, i got an anomaly while inference mistral with AWQ, below is the GPU usage on 3090 consume 20GB GPU. even if we inference the base model only consume 19GB GPU
<img width="632" alt="Screen Shot 2024-03-12 at 18 11 45" src="https://github.com/vllm-project/vllm/assets/55968084/3beeeabe-35ac-439c-b0f1-f982a50e5557">

here is the command: python -m vllm.entrypoints.openai.api_server --model ../Mistral-AWQ --disable-log-requests --port 9000 --host 127.0.0.1 --max-num-seqs 500 --max-model-len 27000 --quantization awq

can anyone help?, thank you.

**Comment by rkooo567** [comment]
Maybe cuda graph? If you use eager_force=True, does it still consume the same amount of memory?

**Comment by Kev1ntan** [comment]
> Maybe cuda graph? If you use eager_force=True, does it still consume the same amount of memory?

i will try later when my instance active again
