### ISSUE TITLE
figure of document error?

### ISSUE THREAD

**Issue by laneeeee** [vllm-project/vllm#3352]
### Discussed in https://github.com/vllm-project/vllm/discussions/3351

<div type='discussions-op-text'>

<sup>Originally posted by **laneeeee** March 12, 2024</sup>
i found a mistake when i learn PagedAttention from document[https://docs.vllm.ai/en/latest/], i confused that the figure of "value" charater. there are HEAD_SIZE=128, BLCOK_SIZE=16, V_VEC_SIZE=8, WARP_SIZE=32 is known, why does the figure show that thd0 process v_vec16? according to my results, thd0 should process v_vec32</div>

**Comment by LiuXiaoxuanPKU** [comment]
Hey, thanks for the interest! Yes you are right, it should be v_vec32 since we have 256 v_vecs in a single block. And each inner loop should read 32 v_vecs.

Feel free to open a PR to fix it or @pian13131 can fix it.

**Comment by laneeeee** [comment]
> Hey, thanks for the interest! Yes you are right, it should be v_vec32 since we have 256 v_vecs in a single block. And each inner loop should read 32 v_vecs.
> 
> Feel free to open a PR to fix it or @pian13131 can fix it.

thanks for your reply. i want to open a PR to fix it  in 24 hours
