### ISSUE TITLE
FlashAttentionBackend only supports head sizes supported by xformers

### ISSUE THREAD

**Issue by declark1** [vllm-project/vllm#3359]
`FlashAttentionBackend` currently only supports head sizes supported by `XFormersBackend`, specifically `[64, 80, 96, 112, 128, 256]`. Is there any reason to only support these head sizes with flash attention? If not, I can open a PR to remove this constraint (flash should support all dimensions up to 256) so that smaller models or those with unsupported head sizes can be used with vLLM w/flash attention.

```python
suppored_head_sizes = PagedAttentionImpl.get_supported_head_sizes()
if head_size not in suppored_head_sizes:
    raise ValueError(
        f"Head size {head_size} is not supported by PagedAttention. "
        f"Supported head sizes are: {suppored_head_sizes}.")
```

**Comment by rkooo567** [comment]
cc @WoosukKwon I believe this constraint is not necessary?

**Comment by tdoublep** [comment]
The backend choice primarily affects how the **prompt** steps are processed. Before #3005 it was always being done with xformers, now there is also the option to call flash directly. However, whether `FlashAttentionBackend` or `XFormersBackend` is used, in both cases we are still using `PagedAttentionImpl` for the **decoding** steps (e.g., see code [here](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/attention/backends/flash_attn.py#L109-L118) and [here](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/attention/backends/xformers.py#L173-L182)).

These constraints on the head size are coming from `PagedAttentionImpl` and thus affect both backends as far as I can see.

**Comment by henrycharlesworth** [comment]
Hi, 

I can't see the code that is referenced above. Is this constraint still really necessary? I have a model with head size 136 that I can't use with vLLM because of this.
