### ISSUE TITLE
kv cache fp8 not support auto prefix cache

### ISSUE THREAD

**Issue by snippetzero** [vllm-project/vllm#3364]
The "auto prefix cache" uses the "PagedAttentionImpl.forward_prefix" functionality implemented by Triton, which does not support fp8.

**Comment by chenxu2048** [comment]
Hi, @snippetzero, we are working for this problem in #3234.

**Comment by snippetzero** [comment]
> Hi, @snippetzero, we are working for this problem in #3234.

thanks！
