### ISSUE TITLE
When  starting the second vllm.entrypoints.api_server using tensor parallel in a single node, the second vllm api_server Stuck in " Started a local Ray instance." OR  "Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory" 

### ISSUE THREAD

**Issue by durant1999** [vllm-project/vllm#3367]
![image](https://github.com/vllm-project/vllm/assets/145545818/2c37e30e-83c9-45f1-b73b-5a04f3583318)

![image](https://github.com/vllm-project/vllm/assets/145545818/ab96caeb-d3da-465f-a63a-5a70d082f409)

As I mentioned above, when I try to start two vllm api_servers, both using tensor-parallel(and size =2), I find the SECOND api_server can't run successfully (while the first one is ok). Also, I find that using top command, it shows there are many ray:IDLE.
![image](https://github.com/vllm-project/vllm/assets/145545818/cc0dae47-baaf-4416-be7a-18da7ce89f21)

**Comment by durant1999** [comment]
SOS....

**Comment by qianchen94** [comment]
same with me, have you solved it?
