### ISSUE TITLE
Can AsyncLLMEngine.generate return freshly generated text?

### ISSUE THREAD

**Issue by suxuanning** [vllm-project/vllm#3391]
How can I make the AsyncLLMEngine.generate method call output only new generated text without including incremental text each time it's invoked?
The current return is formatted as:
I 
I like
I like apple

And I want it to be return like this: 
I 
like 
apple

**Comment by suxuanning** [comment]
This is my code, and I'm unsure whether it's an issue with incorrect invocation or improper parameter passing—it always returns incremental text.
```
    sampling_params = SamplingParams(
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        repetition_penalty=repetition_penalty,
        max_tokens=max_tokens
    )
    request_id = random_uuid()
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    results_generator = engine.generate(text, sampling_params, request_id)
    final_output = None
    async for request_output in results_generator:
        final_output = request_output
    text_outputs = final_output.outputs[0].text
    return text_outputs
```

**Comment by chenxu2048** [comment]
https://github.com/vllm-project/vllm/blob/81653d968842d2ec51b2642b6b5d83786271f9af/vllm/entrypoints/openai/serving_chat.py#L170-L189

Hi, @suxuanning. FYI, vllm.entrypoint.openai saved the previous output and calculate the delta output each step.

**Comment by suxuanning** [comment]
Thank you, I have been helped with your information.
