### ISSUE TITLE
Specify the max batch size with continous batching

### ISSUE THREAD

**Issue by oximi123** [vllm-project/vllm#3395]
I want to process multiple inference requests and evaluate the the average request latency. Because increasing the batch size will add extra latency to the request, I want to find the optimal maximun batch size to minimize the average average request latency. 

So instead of letting vllm decide batch size at each iteration, is there a way to specify the max batch size (e.g., 40 requests inference at one iteration at most) with continous batching?

**Comment by ywang96** [comment]
For online serving, you can specify this by passing `--max-num-seqs` to either `AsyncLLMEngine` or the API server. For the offline batch inference (i.e, the `LLM` class), you can specify `max_num_seqs` when you initialize this class. By default, this value is 256.
https://github.com/vllm-project/vllm/blob/8fe838659164b415d7f3044ec6b7e5bc52c6b6a5/vllm/engine/arg_utils.py#L32

Under the hood, the scheduler will not schedule a new request into the current running queue/batch if adding the number of sequences from this request to the running queue will exceed the max size.
https://github.com/vllm-project/vllm/blob/8fe838659164b415d7f3044ec6b7e5bc52c6b6a5/vllm/core/scheduler.py#L234-L237

**Comment by tengfei666680** [comment]
你可以尝试在vllm在线测试服务端添加--max-num-seqs xxx，该xxx值要大于你要测试的batch值，这样就可以测试你指定的batch性能了
