### ISSUE TITLE
Sequoia: Scalable, Robust, and Hardware-aware Speculative Decoding

### ISSUE THREAD

**Issue by tchaton** [vllm-project/vllm#3398]
This paper might be of interest: https://arxiv.org/pdf/2402.12374.pdf

**Comment by rkooo567** [comment]
cc @cadedaniel

**Comment by cadedaniel** [comment]
Thanks for creating the issue. For us to implement Sequoia we need both https://github.com/vllm-project/vllm/issues/3960 and https://github.com/vllm-project/vllm/issues/4565.
