### ISSUE TITLE
Why AWQ and GPTQ model slower than ORI model in concurrency?

### ISSUE THREAD

**Issue by morning-hao** [vllm-project/vllm#3399]
I've conducted a performance comparison using VLLM version 0.3.3 on an 8 A800 GPU machine, employing four GPUs for testing 10,000 address parsing data points with a concurrency of 500. The results are as follows: 1638s for GPTQ, 2025s for AWQ, and 1468s for the Original method. Surprisingly, both GPTQ and AWQ performed slower than the original setup.

blow is my cmd and pic:
GPT-1638s-CUDA_VISIBLE_DEVICES=4,5,6,7 python -m vllm.entrypoints.openai.api_server     --model /xxx/Qwen1.5-72B-Chat-GPTQ-Int4/     --tensor-parallel-size 4     --port 30142 --dtype half --max-model-len 2000 --gpu-memory-utilization 0.95 --enforce-eager --quantization gptq

AWQ-2025s-CUDA_VISIBLE_DEVICES=4,5,6,7 python -m vllm.entrypoints.openai.api_server     --model /xxx/Qwen1.5-72B-Chat-AWQ/     --tensor-parallel-size 4     --port 30142 --dtype half --max-model-len 2000 --gpu-memory-utilization 0.95 --enforce-eager --quantization awq

ORI-1468s-CUDA_VISIBLE_DEVICES=4,5,6,7 python -m vllm.entrypoints.openai.api_server     --model /xxx/Qwen_Qwen1.5-72B-Chat/     --tensor-parallel-size 4     --port 30142 --dtype half --max-model-len 2000 --gpu-memory-utilization 0.95 --enforce-eager

![vXba3UresO](https://github.com/vllm-project/vllm/assets/92151904/a68814a9-7fb3-4e97-b68a-0b08d0f5c053)

**Comment by sitabulaixizawaluduo** [comment]
Perhaps due to the current inference process being bottlenecked by compute, while quantization methods are primarily aimed at optimizing memory access, there is additional overhead during the dequantization , leading to a decrease in overall throughput.
