### ISSUE TITLE
[Feature] Cohere Command-R support

### ISSUE THREAD

**Issue by dekelcohen** [vllm-project/vllm#3403]
Hi,
Command-R has 128K context, RAG support with Grounded generation and multilingual 
It seems a strong 35B model, especially in summarization of long texts, middle east languages and more.
The model code is copied from Llama2 with minor modifications. 
Would it be possible to support it in VLLM ?

Thanks,

**Comment by t3ga** [comment]
Dup: https://github.com/vllm-project/vllm/issues/3330
Already exists. Somebody just needed to program it)))

**Comment by simon-mo** [comment]
Closing as dup

**Comment by ips972** [comment]
still getting vllm error with comman-r not supported as gguf , and niether is command-a. 
both leading models and getting no real suppprt.  can something be done with this please? 

or am i missing some thing?  

tring to load it with latest container release. with docker compose.  might be that im doing it wrong , but the commands from huggingface just crash.

cant run the regular modela , thier too big.. so have to go with the 67gb gguf q4 model.

**Comment by ips972** [comment]
one more things. even though the model supports 128k context size.  in vllm. i cant set more than 8k with out seeing crashs due to token size.. bellow 8k i see crashs with command-r not supported.
