### ISSUE TITLE
Gemma implementation should use approximate GELU

### ISSUE THREAD

**Issue by jeffreyan11** [vllm-project/vllm#3411]
Based on the [unsloth.ai blog #8](https://unsloth.ai/blog/gemma-bugs) as well as discussion with @pengchongjin from the Gemma team, the Gemma implementation in vLLM should switch to using tanh approximation rather than exact (code ref [1](https://github.com/vllm-project/vllm/blob/8fe838659164b415d7f3044ec6b7e5bc52c6b6a5/vllm/model_executor/layers/activation.py#L50), [2](https://github.com/vllm-project/vllm/blob/06ec486794f42db656c3cc16c8c5ed56ce4f696b/vllm/model_executor/models/gemma.py#L63)).

**Comment by jeffreyan11** [comment]
Ah, I see #3337 now. Is the plan to wait for the fix to be merged in HF Transformers first?

**Comment by rkooo567** [comment]
cc @WoosukKwon for his thoughts!
