### ISSUE TITLE
[Feature]: Does the latest version of vllm (0.3.3) support lora inference for wizardcoder and deepseek models

### ISSUE THREAD

**Issue by ivanzfb** [vllm-project/vllm#3417]
### 🚀 The feature, motivation and pitch

In our actual project, we need to use wizardcoder/deepseek's loraadapters for reasoning. The latest version of vllm (0.3.3) is the support plan for this wizardcoder/deepseek's loraadapters?

**Comment by simon-mo** [comment]
Wizardcoder is uses GPTBigCode, there's already a feature request here #3362
Deepseek coder is just Llama, which we do support! 

See https://docs.vllm.ai/en/latest/models/supported_models.html for LoRA support status.

**Comment by ivanzfb** [comment]
> Wizardcoder is uses GPTBigCode, there's already a feature request here #3362 Deepseek coder is just Llama, which we do support!
> 
> See https://docs.vllm.ai/en/latest/models/supported_models.html for LoRA support status.
But I used the official lora reasoning method to ensure that the vocabulary exceeded the limit of the error

![图片](https://github.com/vllm-project/vllm/assets/135102369/e41c7c1d-9440-406d-8baf-d90a901cc973)

**Comment by simon-mo** [comment]
Ah this is a bug indeed. Please open a new github issue under `Model` saying `LoRA for Deepseek is not supported due to vocab size limit`.
