### ISSUE TITLE
[Installation]: Facing Issue while installing vllm in local machine(window11)

### ISSUE THREAD

**Issue by navdeeps635** [vllm-project/vllm#3425]
### Your current environment

![image](https://github.com/vllm-project/vllm/assets/102275955/f401cd96-0374-4f7b-a2b9-ed2289a54da4)
![image](https://github.com/vllm-project/vllm/assets/102275955/8989ff14-17ca-41f2-8fd2-74241a4d9209)

### How you are installing vllm

![image](https://github.com/vllm-project/vllm/assets/102275955/50dc23be-d5b8-4ac2-b085-559f7ce9d418)

**Comment by youkaichao** [comment]
Do you use WSL?

**Comment by youkaichao** [comment]
@navdeeps635 please use WSL to run vLLM and it should work then.

**Comment by hmellor** [comment]
Closed by #3438
