### ISSUE TITLE
[Bug]: Incompatible version between torch and triton

### ISSUE THREAD

**Issue by mzz12** [vllm-project/vllm#3426]
### 🐛 Describe the bug

ERROR: torch 2.1.2 has requirement triton==2.1.0; platform_system == "Linux" and platform_machine == "x86_64", but you'll have triton 2.2.0 which is incompatible.

**Comment by youkaichao** [comment]
Can you give more information on how you install vllm? Also give your current environment so that we can understand the conflict in your environment.

Please execute the following and paste the output in this issue.

```sh
wget https://raw.githubusercontent.com/vllm-project/vllm/main/collect_env.py
# For security purposes, please feel free to check the contents of collect_env.py before running it.
python collect_env.py
```
