### ISSUE TITLE
[Feature]: AQLM quantization

### ISSUE THREAD

**Issue by jacobwarren** [vllm-project/vllm#3439]
### 🚀 The feature, motivation and pitch

Existing weight-only quantization algorithms could technically quantize model weights down to the 2-bit range. However, they failed at effectively preserving model accuracy. AQLM is a new weight-only post-training quantization (PTQ) algorithm that sets a new state-of-the-art for the 2 bit-per-parameter range. It also provides smaller benchmark improvements compared to existing methods for the 3-bit and 4-bit ranges. Specifically, AQLM outperforms popular algorithms like GPTQ as well as more recent but lesser known methods such as QuIP and QuIP#. AQLM authors also claim that their quantization algorithm pushes the Pareto frontier of the tradeoff between model accuracy and memory footprint below 3 bits per parameter for the first time.

While quantization can sometimes reduce inference latency compared to FP16, this is not guaranteed. In benchmarks, AQLM-quantized models showed moderate latency improvements, with speedups ranging from 1.2x to 2x in most cases, and up to 3.05x in the best case. However, latency reduction was not the focus of AQLM’s designers. Their priority was maximizing accuracy within a target model size, rather than optimizing for speed. Consequently, the latency gains from AQLM quantization are noticeable but not as dramatic as the improvements from other existing quantization algorithms.

### Additional context

Here's a really great article on AQLM: https://towardsdatascience.com/the-aqlm-quantization-algorithm-explained-8cf33e4a783e
Here's their GitHub: https://github.com/Vahe1994/AQLM

I just loaded Mixtral 8x7B on a 4090, y'all. I'm going to take a stab at this myself, but would love the help of someone more capable!

**Comment by TechxGenus** [comment]
It seems there is already a PR: https://github.com/vllm-project/vllm/pull/3287

**Comment by jacobwarren** [comment]
Wow. I should learn to read. haha. @jaemzfleming has made incredible progress. Closing this issue.
