### ISSUE TITLE
[Feature]: Control vectors

### ISSUE THREAD

**Issue by generalsvr** [vllm-project/vllm#3451]
### 🚀 The feature, motivation and pitch

Add support for control vectors

See https://github.com/vgel/repeng and https://github.com/ggerganov/llama.cpp/pull/5970

**Comment by justinphan3110** [comment]
@simon-mo @generalsvr I should be able to help with this. Let me know how to start.

**Comment by Kaiyang-Chen** [comment]
We can achieve this by loading the control vectors when initializing the cache engine and apply the change to `forward()` of specified `QKVLinear` layers, but such changes will be added for all models and all kinds of linear method, which introduce extra complexity to the codebase. Do you have any hints on how we can abstract such logic and make the integration clear? @simon-mo

**Comment by sapountzis** [comment]
Something additional to consider is specifying different control vectors (and coefficients) per request which then get stacked into a control matrix with one dimension equal to the batch size.

This can be useful when serving users that require different styles of responses at the same time.

Not sure about the impact on latency.

**Comment by raywanb** [comment]
currently working on an implementation by wrapping the decoder layer and changing the forward pass.

**Comment by DreamGenX** [comment]
@raywanb somethingworth looking into would be also the technique presented here, which might be superior in some regards:

https://www.lesswrong.com/posts/jGuXSZgv6qfdhMCuJ/refusal-in-llms-is-mediated-by-a-single-direction

It cames with a nice colab as well: https://colab.research.google.com/drive/1a-aQvKC9avdZpdyBn4jgRQFObTPy1JZw?usp=sharing&authuser=1

There's a discussion in the comments with the authors of the Represenation Engineering paper.

**Comment by heraclex12** [comment]
> @raywanb somethingworth looking into would be also the technique presented here, which might be superior in some regards:
> 
> https://www.lesswrong.com/posts/jGuXSZgv6qfdhMCuJ/refusal-in-llms-is-mediated-by-a-single-direction
> 
> It cames with a nice colab as well: https://colab.research.google.com/drive/1a-aQvKC9avdZpdyBn4jgRQFObTPy1JZw?usp=sharing&authuser=1
> 
> There's a discussion in the comments with the authors of the Represenation Engineering paper.

It seems that the colab link doesn't work.

**Comment by xuhaolei** [comment]
We implemented more advanced control (steering) functionalities using vLLM. See https://github.com/ZJU-REAL/EasySteer.
