### ISSUE TITLE
baichuan/qwen/chatlgm with lora adaption [feature]

### ISSUE THREAD

**Issue by kexuedaishu** [vllm-project/vllm#3458]
### 🚀 The feature, motivation and pitch

Popular chinese llms like baichuan/baichuan2/qwen/chatglm can be supported.

**Comment by jeejeelee** [comment]
I have submitted a PR about your feature request,   refer to [#3382](https://github.com/vllm-project/vllm/pull/3382).  I have tested ChatGLM-3 and Baichuan-7B models. 
Hope it can help you.
