### ISSUE TITLE
Openllm with vLLM backend VS  vLLM in handling group of requests at the same time

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#3464]
### Your current environment

I am sending requests at the same time such as benchmark_serving to two services:
Number of requests: 400

### 🐛 Describe the bug

I am sending requests at the same time such as benchmark_serving to two services:
Number of requests: 400

1. first endpoint from running openllm start to my model with vLLM backend, I observed from the metrics logs that this service can handle more requests at the same time unlike vLLM service which enable openllm service to process them under high load more than vLLM which always I can see up to 3 request are running and 0 pending. 

>  * vllm version :'0.2.7'

logs: 

`INFO 03-18 12:34:52 llm_engine.py:706] Avg prompt throughput: 209.6 tokens/s, Avg generation throughput: 567.4 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 78 reqs, GPU KV cache usage: 99.1%, CPU KV cache usage: 0.0%
`

2. vLLM service, I write endpoint as its mentioned in the vLLM [entrypoints](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py)

>  * vllm version :'0.3.2'

logs:

`(ServeReplica:default:OpenLLMDeployment pid=126565) INFO 03-18 12:58:24 metrics.py:161] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 54.7 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 18.6%, CPU KV cache usage: 0.0% [repeated 4x across cluster]
`

Is there any way to increase the number of requests on vLLM endpoint as it is on the openllm side?

**Comment by rkooo567** [comment]
Is this the same when you compare the same version vllm?

**Comment by hahmad2008** [comment]
@rkooo567 I didn't try that. as openllm has issue with upgrading vllm

**Comment by rkooo567** [comment]
Can you try with lower version OSS vllm in this case?

**Comment by hahmad2008** [comment]
@rkooo567 I didn't get what you mean by OSS vllm?

**Comment by rkooo567** [comment]
oh, I meant to use 0.2.7 for "2" (since you cannot upgrade openllm).

**Comment by hahmad2008** [comment]
@rkooo567, I think understand [this](https://github.com/vllm-project/vllm/issues/3561#issue-2201316954) can help me proceed. Thanks @rkooo567

**Comment by rkooo567** [comment]
I will take a look at it soon!

**Comment by hahmad2008** [comment]
@rkooo567 I am trying to add chat completion at my fastapi service, so i used the entrypoint of openai

```
@app.post("/v1/chat/completions")
async def create_chat_completion(request: ChatCompletionRequest,
                                 raw_request: Request):
    generator = await openai_serving_chat.create_chat_completion(
        request, raw_request)
    if isinstance(generator, ErrorResponse):
        return JSONResponse(content=generator.model_dump(),
                            status_code=generator.code)
    if request.stream:
        return StreamingResponse(content=generator,
                                 media_type="text/event-stream")
    else:
        return JSONResponse(content=generator.model_dump())
```

I don't know what is the `raw_request` here? 
I know for openai chat completion, there is the following body for the request:
```

curl -X 'POST' \
  'http://0.0.0.0:5000/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "messages": [
    {
      "role": "user",
      "content": "What is your favourite color?"
    }
  ],
  "model": "path/to/my/model/",
  "max_tokens": 256,
  "temperature": 0.7,
  "top_p": 0.43,
  "n": 1,
  "stream": true,
  "chat_template": "\"{{ bos_token }}{% for message in messages %}{% if (message['\''role'\''] == '\''user'\'') != (loop.index0 % 2 == 0) %}{{ raise_exception('\''Conversation roles must alternate user/assistant/user/assistant/...'\'') }}{% endif %}{% if message['\''role'\''] == '\''user'\'' %}{{ '\''[INST] '\'' + message['\''content'\''] + '\'' [/INST]'\'' }}{% elif message['\''role'\''] == '\''assistant'\'' %}{{ message['\''content'\''] + eos_token + '\'' '\'' }}{% else %}{{ raise_exception('\''Only user and assistant roles are supported!'\'') }}{% endif %}{% endfor %}\"",
  "add_generation_prompt": true,
  "echo": false
}'

```


I get this error:

```
(ProxyActor pid=36417) ERROR:    Exception in ASGI application
(ProxyActor pid=36417) Traceback (most recent call last):
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
(ProxyActor pid=36417)     result = await app(  # type: ignore[func-returns-value]
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
(ProxyActor pid=36417)     return await self.app(scope, receive, send)
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/ray/serve/_private/proxy.py", line 1108, in __call__
(ProxyActor pid=36417)     await self.app(scope, receive, send_with_request_id)
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/ray/serve/_private/proxy.py", line 863, in __call__
(ProxyActor pid=36417)     await send(message)
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/ray/serve/_private/proxy.py", line 1106, in send_with_request_id
(ProxyActor pid=36417)     await send(message)
(ProxyActor pid=36417)   File "myenv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 571, in send
(ProxyActor pid=36417)     raise RuntimeError(msg % message_type)
(ProxyActor pid=36417) RuntimeError: Unexpected ASGI message 'http.response.start' sent, after response already completed.
....
.......
....
 generator = await OpenAIServingChat.create_chat_completion(
(ServeReplica:default:OpenLLMDeployment pid=36561) TypeError: create_chat_completion() missing 1 required positional argument: 'raw_request'
```

Any advice here?

plus, the model here is not the name of the model as in bentoml, that should be path to the model, right?

**Comment by hahmad2008** [comment]
@rkooo567 could you please check this as well?

**Comment by hahmad2008** [comment]
@youkaichao could you please check this?

**Comment by rkooo567** [comment]
How can I reproduce this?

**Comment by hahmad2008** [comment]
@rkooo567 I am adding these files from [openai entrypoint](https://github.com/vllm-project/vllm/tree/main/vllm/entrypoints/openai) in the same directory of `ray_serv.py`


`ray_serv.py`

```

from ray import serve
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from fastapi.responses import JSONResponse, StreamingResponse
from vllm import AsyncEngineArgs, AsyncLLMEngine

from protocol import ChatCompletionRequest, ErrorResponse
from serving_chat import OpenAIServingChat

app = FastAPI()

@serve.deployment(
    ray_actor_options={"num_gpus": 1},

)
@serve.ingress(app)
class OpenLLMDeployment:
    def __init__(self) -> None:

        ENGINE_ARGS = AsyncEngineArgs(
            gpu_memory_utilization= 0.95,
            model="path/to/model",
            max_model_len=4096,            
        )
        self.engine = AsyncLLMEngine.from_engine_args(ENGINE_ARGS)

    @app.post("/v1/chat/completions")
    async def create_chat_completion(request: ChatCompletionRequest,
                                 raw_request: Request):
        generator = await OpenAIServingChat.create_chat_completion(
            request, raw_request)
        if isinstance(generator, ErrorResponse):
            return JSONResponse(content=generator.model_dump(),
                            status_code=generator.code)
        if request.stream:
            return StreamingResponse(content=generator,
                                 media_type="text/event-stream")
        else:
            return JSONResponse(content=generator.model_dump())
        
service = OpenLLMDeployment.bind()

```
I run it as following:
`serve run ray_serv:service --port 8000 --host 0.0.0.0`

**Comment by hahmad2008** [comment]
@rkooo567 I used the same way to add the `generate_stream`, just copy it from vllm entrypoint and it worked fine.
but here I believe that the problem is what is the `raw_request: Request`, if we can handle it then we can use it and pass only the ChatCompletionRequest as any other openai chat API.
