### ISSUE TITLE
[Feature]: DeepSpeed-FP6: An Optimization Approach from Microsoft，6-bit Floating Point (FP6)

### ISSUE THREAD

**Issue by jackdiy** [vllm-project/vllm#3468]
### 🚀 The feature, motivation and pitch

DeepSpeed-FP6: An Optimization Approach from Microsoft

### Alternatives

Microsoft recently proposed an optimization approach called DeepSpeed-FP6. While it currently only supports a subset of models, it appears to offer some unique advantages. I am curious if the vLLM team has looked into it.

Inference Acceleration: FP6 quantization can significantly improve inference speed while maintaining model accuracy. 
Facilitating on-the-fly, weight-only quantization: DeepSpeed-FP6 allows users to quantize their models on-the-fly with simple configuration options. 

### Additional context

https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-fp6/03-05-2024
https://github.com/usyd-fsalab/fp6_llm

**Comment by flozi00** [comment]
https://github.com/usyd-fsalab/fp6_llm/blob/main/tests/python/kernel_test.py

There is an example how to apply to a linear layer
Only worked with tgi / lorax before and don't have experience with vllm quantization
