### ISSUE TITLE
The Third vLLM Bay Area Meetup (April 2nd 6-8:30pm)

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#3480]
## Welcome to the third vLLM Meetup @ Roblox!

We are absolutely thrilled to invite you to the third vLLM meetup! This event is for the growing community of vLLM users and developers to connect, share, and learn together. The vLLM team will share the recent updates on the project. We will also have vLLM collaborators from Roblox coming up to the stage to discuss their benchmarking work on vLLM.

We, the vLLM team, are incredibly excited to meet each and every one of you. This meetup is not just about sharing updates but also about celebrating the community that makes vLLM what it is today. Let's come together, share our stories, and envision the future of vLLM.

​​A heartfelt thank you to Roblox for generously providing us with the venue for this event. Their continuous support has been invaluable to the vLLM's open-source community.

**Please check the scheduler and register [here](https://robloxandvllmmeetup2024.splashthat.com/) to join us!**

**Comment by WoosukKwon** [comment]
Please find the meetup slides [here](https://docs.google.com/presentation/d/1A--47JAK4BJ39t954HyTkvtfwn0fkqtsL8NGFuslReM/edit?usp=sharing)!
