### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by finylink** [vllm-project/vllm#3485]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

python -m vllm.entrypoints.openai.api_server --model /root/autodl-tmp/models/Qwen1.5-14B-Chat-GPTQ-Int8 --max-model-len 2000  --trust-remote-code

when request api, some errors return:

{"object":"error","message":"The model `Qwen1.5-14B-Chat-GPTQ-Int8` does not exist.","type":"NotFoundError","param":null,"code":404}

**Comment by youkaichao** [comment]
Can you follow the issue template to re-open a new issue and fill in more information?
