### ISSUE TITLE
[Bug]: when start openai_api_server,  some errors happend.

### ISSUE THREAD

**Issue by finylink** [vllm-project/vllm#3486]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

python -m vllm.entrypoints.openai.api_server --model /root/autodl-tmp/models/Qwen1.5-14B-Chat-GPTQ-Int8 --max-model-len 2000  --trust-remote-code

call params:
{
    "messages": [{"role": "user", "content": "hello"}],
    "model":'Qwen-14B-Chat-GPTQ-Int8',
    "temperator":0,
    "topK":0
}

when calling, some errors:
{"object":"error","message":"The model `Qwen1.5-14B-Chat-GPTQ-Int8` does not exist.","type":"NotFoundError","param":null,"code":404}

**Comment by simon-mo** [comment]
Use the list model endpoint to see the model tag recognized? It might be `Qwen/Qwen-14B-Chat-GPTQ-Int8`

**Comment by jony0113** [comment]
if you do not specify the param `--served-model-name` while starting the param, the `model` param in your call request should be the same with your `--model`, that is `/root/autodl-tmp/models/Qwen1.5-14B-Chat-GPTQ-Int8`

**Comment by garycaokai** [comment]
The model path can't have "." (Qwen1.5)

**Comment by wangjiawen2013** [comment]
The same `model_path` as `vllm serve model_path` must be used in python script, such as the full absolute path or relative path muse be identical. You cannot use absolute path in `vllm serve` while using relative path in the python script, and vice verse.

I used `vllm serve /mnt/workspace/models/Qwen/Qwen2___5-0___5B-Instruct/` in the terminal and `chat_completion = client.chat.completions.create(messages=chat_history, model="/mnt/workspace/models/Qwen/Qwen2___5-0___5B-Instruct/")` in my python script. Then it ran successfully.
