### ISSUE TITLE
[Bug]: DynamicNTKScalingRotaryEmbedding implementation is different from Transformers

### ISSUE THREAD

**Issue by killawhale2** [vllm-project/vllm#3488]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

There is a difference in the vLLM implementation of DynamicNTKScalingRotaryEmbedding from the Transformer implementation that causes performance degradation for inputs that fit into the _original context length_.

Specifically, the Transformer implementation initializes the base for the Rope embedding with the original max_position_embeddings and re-computes the base for inputs that surpass the original max_position_embeddings (hence the name _dynamic_), as detailed below.
```python
# taken from https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L158
class LlamaDynamicNTKScalingRotaryEmbedding(LlamaRotaryEmbedding):
    """LlamaRotaryEmbedding extended with Dynamic NTK scaling. Credits to the Reddit users /u/bloc97 and /u/emozilla"""

    def forward(self, x, position_ids):
        # difference to the original RoPE: inv_freq is recomputed when the sequence length > original length
        seq_len = torch.max(position_ids) + 1
        if seq_len > self.max_position_embeddings:
            base = self.base * (
                (self.scaling_factor * seq_len / self.max_position_embeddings) - (self.scaling_factor - 1)
            ) ** (self.dim / (self.dim - 2))
            inv_freq = 1.0 / (
                base ** (torch.arange(0, self.dim, 2, dtype=torch.int64).float().to(x.device) / self.dim)
            )
            self.register_buffer("inv_freq", inv_freq, persistent=False)  # TODO joao: this may break with compilation

        cos, sin = super().forward(x, position_ids)
        return cos, sin
```

In contrast, the vLLM implementation initializes the base with max_position_embeddings * scaling_factor once, and does _not_ re-compute it depending on the length of the input, as detailed below. This means that for inputs with lengths smaller than the original context length, the outputs from pre-/post-rope scaling will differ, sometimes by large amounts.
```python
# taken from https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/rotary_embedding.py#L219
    def _compute_cos_sin_cache(self) -> torch.Tensor:
        # NOTE(woosuk): self.max_position_embeddings is the original
        # maximum length before applying the rope scaling.
        # Thus, the maximum length after applying the rope scaling is
        # self.max_position_embeddings * self.scaling_factor.
        max_len = self.max_position_embeddings * self.scaling_factor
        base = self.base * (
            (self.scaling_factor * max_len / self.max_position_embeddings) -
            (self.scaling_factor - 1))**(self.rotary_dim /
                                         (self.rotary_dim - 2))
        inv_freq = self._compute_inv_freq(base)
        t = torch.arange(max_len, dtype=torch.float)

        freqs = torch.einsum("i,j -> ij", t, inv_freq)
        cos = freqs.cos()
        sin = freqs.sin()
        cache = torch.cat((cos, sin), dim=-1)
        return cache
```

I was wondering if this was an intentional design to save re-computation of the cosine and sine cache.
If not, I would love to see the implementation fixed to match the Transformer one, as applying rope scaling only to find that the performance degrades for inputs that fit into the original context length is kind of weird.

**Comment by aporia3517** [comment]
+1
@WoosukKwon Can you take a look at this issue?

**Comment by Junphy-Jan** [comment]
Same problem. 
Using vllm and ntk scaling cause a worse reuslt compared to transformers

**Comment by NathanYanJing** [comment]
+1
Is this because of a version error?

**Comment by Missmiaom** [comment]
+1

**Comment by asimj1342** [comment]
+1

**Comment by killawhale2** [comment]
bump

**Comment by hmellor** [comment]
If dynamic rope scaling is used, the `ModelConfig.max_model_len` is updated to use the maximum value _after_ scaling:

https://github.com/vllm-project/vllm/blob/e24113a8fe5de5b96459d1f8509d1b48fd7ceebe/vllm/config.py#L2299-L2321

Therefore, the cos sin cache that's computed for `DynamicNTKScalingRotaryEmbedding` is the largest it will ever be and will never need updating in `forward`. 

If we look at the source for the original [LlamaDynamicPartNTKScaledRotaryEmbedding](https://github.com/jquesnelle/yarn/blob/995db5b575e75230b3384d658f8b944c9662f775/scaled_rope/LlamaDynamicPartNTKScaledRotaryEmbedding.py#L31-L79) from [u/emozilla](https://www.reddit.com/r/LocalLLaMA/comments/14mrgpr/dynamically_scaled_rope_further_increases/) we see that, when a longer sequence is encountered, the old cos sin cache is discarded. This means that if someone were to use the full (scaled) context length, the cache would be updated to match what is done in vLLM and it will stay that way unless the system/model/module is reset.

Therefore, it makes sense to calculate the longest possible cos sin cache so that users don't experience uneccessary latency at runtime due to recalculation of various length cos sin caches.

**Comment by RunningLeon** [comment]
> If dynamic rope scaling is used, the `ModelConfig.max_model_len` is updated to use the maximum value _after_ scaling:
> 
> [vllm/vllm/config.py](https://github.com/vllm-project/vllm/blob/e24113a8fe5de5b96459d1f8509d1b48fd7ceebe/vllm/config.py#L2299-L2321)
> 
> Lines 2299 to 2321 in [e24113a](/vllm-project/vllm/commit/e24113a8fe5de5b96459d1f8509d1b48fd7ceebe)
> 
>  rope_scaling = getattr(hf_config, "rope_scaling", None) 
>  if rope_scaling is not None: 
>      # No need to consider "type" key because of patch_rope_scaling when 
>      # loading HF config 
>      rope_type = rope_scaling["rope_type"] 
>   
>      if rope_type not in ("su", "longrope", "llama3"): 
>          if disable_sliding_window: 
>              # TODO(robertgshaw): Find a model that supports rope_scaling 
>              # with sliding window to see if this case should be allowed. 
>              raise NotImplementedError( 
>                  "Disabling sliding window is not supported for models " 
>                  "with rope_scaling. Please raise an issue so we can " 
>                  "investigate.") 
>   
>          # NOTE: rope_type == "default" does not define factor 
>          # https://github.com/huggingface/transformers/blob/v4.45.2/src/transformers/modeling_rope_utils.py 
>          scaling_factor = rope_scaling.get("factor", 1.0) 
>   
>          if rope_type == "yarn": 
>              derived_max_model_len = rope_scaling[ 
>                  "original_max_position_embeddings"] 
>          derived_max_model_len *= scaling_factor 
> Therefore, the cos sin cache that's computed for `DynamicNTKScalingRotaryEmbedding` is the largest it will ever be and will never need updating in `forward`.
> 
> If we look at the source for the original [LlamaDynamicPartNTKScaledRotaryEmbedding](https://github.com/jquesnelle/yarn/blob/995db5b575e75230b3384d658f8b944c9662f775/scaled_rope/LlamaDynamicPartNTKScaledRotaryEmbedding.py#L31-L79) from [u/emozilla](https://www.reddit.com/r/LocalLLaMA/comments/14mrgpr/dynamically_scaled_rope_further_increases/) we see that, when a longer sequence is encountered, the old cos sin cache is discarded. This means that if someone were to use the full (scaled) context length, the cache would be updated to match what is done in vLLM and it will stay that way unless the system/model/module is reset.
> 
> Therefore, it makes sense to calculate the longest possible cos sin cache so that users don't experience uneccessary latency at runtime due to recalculation of various length cos sin caches.

@hmellor hi, dynamic ntk in vllm is not aligned with transformers and it would result in bad performance on some datasets for models like internlm3. Do we have plan to reimplement it? THX
