### ISSUE TITLE
[Usage]: memory out of use

### ISSUE THREAD

**Issue by geknow** [vllm-project/vllm#3494]
### Your current environment

```text
The output of `python multilora_inference.py`
```
原模型Mixtral-8x7B-v0.1单卡A100可以跑，用了80G内存以内，使用了vllm后，要两张A100才能跑起来，内存达到了160G。这个有什么参数可以优化吗

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by esmeetu** [comment]
You can use `--gpu-memory-utilization=0.5`. default is 0.9.

**Comment by hmellor** [comment]
vLLM uses extra memory in:
- statically allocating the KV cache
- compiling the model using cuda graphs
