### ISSUE TITLE
[Bug]: Use of LoRAReqeust

### ISSUE THREAD

**Issue by meiru-cam** [vllm-project/vllm#3514]
### Your current environment

```text
The output of `python collect_env.py`
```
```text
Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.146.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
Stepping:            7
CPU MHz:             4299.706
CPU max MHz:         4700.0000
CPU min MHz:         1200.0000
BogoMIPS:            7399.70
Virtualisation:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-19
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] torch==2.1.2
[pip3] triton==2.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.3.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     0-19    0               N/A
GPU1    SYS      X      0-19    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

```

### How would you like to use vllm

I want to run inference with lora-tuned [meta-llama/Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf). I don't know how to integrate it with vllm.

Here is the code I use to generate lora_enabled result
```python
    model = LLM(
        model=model_name,
        tensor_parallel_size=num_gpus,
        trust_remote_code=True,
        download_dir=hf_cache_path,
        # load_format="pt",
        max_num_batched_tokens=max_prompt_length,
        seed=0,
        enable_lora=True,
        gpu_memory_utilization=0.5
    )
    sampling_params = SamplingParams(temperature=temperature, top_p=top_p, max_tokens=max_new_tokens)
    lora_path = args.lora_path

    raw_responses = model.generate(prompts, sampling_params, lora_request=LoRARequest("trivia_adapter", 1, lora_path))

```

I got exactly the same results with different saved lora (tuned differently), and default model (llama2-7b-chat-hf) without lora. 

![image](https://github.com/vllm-project/vllm/assets/91176744/ae4fcfd8-4150-461c-a334-fb9c510e1cd9)

**Comment by meiru-cam** [comment]
I have a new problem now. I want to inference with a lora adapter where the target modules contains [lm_head] and I got assertion error, after remove the lm_head variable, the model can be loaded properly. May I get more information on how to use the LoRARequest? What are the lora_modules supported?

['base_model.model.lm_head.base_layer.weight']

**Comment by meiru-cam** [comment]
Actually the problem is that if I set enable_lora=True, even without using the LoRARequest, the generation is the same as use LoRARequest. Can someone help with this? It seems like the LoRARequest is not actaully loading and merge the lora model weights

**Comment by jeejeelee** [comment]
> I have a new problem now. I want to inference with a lora adapter where the target modules contains [lm_head] and I got assertion error, after remove the lm_head variable, the model can be loaded properly. May I get more information on how to use the LoRARequest? What are the lora_modules supported?
> 
> ['base_model.model.lm_head.base_layer.weight']

LoRARequest example: [multilora_inference](https://github.com/vllm-project/vllm/blob/main/examples/multilora_inference.py) and [test_llama](https://github.com/vllm-project/vllm/blob/main/tests/lora/test_llama.py)
The supported LoRA modules:[supported_lora_modules](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/llama.py#L293)

**Comment by meiru-cam** [comment]
@jeejeelee Thanks for the reply. Does the "qkv_proj" means that we can load "q_proj" and "v_proj" separately or it is one special proj and I need to have this as target module when train lora?

**Comment by jeejeelee** [comment]
@meiru-cam  your peft config looks good. I think you can use [multilora_inference](https://github.com/vllm-project/vllm/blob/main/examples/multilora_inference.py) directly  , just modify ` lora path` and `prompt`

**Comment by kindernerd** [comment]
> LoRARequest

have you solve the problem now?
i got the same results with lora or not, and different lora weights, looks like it doesn't merge lora at all

**Comment by kindernerd** [comment]
> Actually the problem is that if I set enable_lora=True, even without using the LoRARequest, the generation is the same as use LoRARequest. Can someone help with this? It seems like the LoRARequest is not actaully loading and merge the lora model weights


LoRARequest

have you solve the problem now?
i got the same results with lora or not, and different lora weights, looks like it doesn't merge lora at all

**Comment by jeejeelee** [comment]
> > Actually the problem is that if I set enable_lora=True, even without using the LoRARequest, the generation is the same as use LoRARequest. Can someone help with this? It seems like the LoRARequest is not actaully loading and merge the lora model weights
> 
> LoRARequest
> 
> have you solve the problem now? i got the same results with lora or not, and different lora weights, looks like it doesn't merge lora at all
What version of your vllm is, and could you provide your LLM name and the LoRa config?

**Comment by kindernerd** [comment]
> > Actually the problem is that if I set enable_lora=True, even without using the LoRARequest, the generation is the same as use LoRARequest. Can someone help with this? It seems like the LoRARequest is not actaully loading and merge the lora model weights

Thx, i just found the problem, the reason is the model saved lora weight name is not correct, it originally starts with model.layers.xxx, then raise error, so i prefix it with "base_model", so it got the same result with or wo lora. In fact, it should be base_model.model.model.layers.xxx, after i prefix with "base_model.model", it got right answer.
