### ISSUE TITLE
[Usage]: Specify the number of tokens to be generated

### ISSUE THREAD

**Issue by oximi123** [vllm-project/vllm#3518]
### Your current environment

vllm

### How would you like to use vllm

I want to specify the number of generated tokens for each request using vllm. Is there a way to do so?

**Comment by simon-mo** [comment]
You can use a combination of `max_tokens` and `ignore_eos` in sampling params to achieve this. https://docs.vllm.ai/en/latest/dev/sampling_params.html

There's also active work in #3124 for minimal tokens.

**Comment by oximi123** [comment]
> You can use a combination of `max_tokens` and `ignore_eos` in sampling params to achieve this. https://docs.vllm.ai/en/latest/dev/sampling_params.html
> 
> There's also active work in #3124 for minimal tokens.

Thanks! But the `max_tokens` parameter is a global setting and it applies to all the request. Can I specify the number of generated tokens seperately for each request?
