### ISSUE TITLE
[New Model]: Please support CogVLM

### ISSUE THREAD

**Issue by kietna1809** [vllm-project/vllm#3519]
### The model to consider.

https://huggingface.co/THUDM/cogvlm-chat-hf

### The closest model vllm already supports.

LLama 

### What's your difficulty of supporting the model you want?

- The visual module leads to modify vLLM engine

**Comment by HughesZhang2021** [comment]
same question

**Comment by KevinZeng08** [comment]
Is CogVLM supported currently?
