### ISSUE TITLE
[Bug]: An Internal IP exposing maybe a threat

### ISSUE THREAD

**Issue by llmwesee** [vllm-project/vllm#3521]
### Your current environment

While running my vllm code i checked and noticed a self calling interal ip request shown in **netsat** command i.e(netstat -ano). 

`HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python -m vllm.entrypoints.openai.api_server --port=5000 --host=127.0.0.1 --model "/home/abc/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496" --tokenizer=hf-internal-testing/llama-tokenizer --tensor-parallel-size=1 --seed 1234 --max-num-batched-tokens=4096`

It shows 192.* series that i dont want. Please try to fix this and provide me a solution and I want my host address 127.0.0.1 should show as my foreign IP instead of my system ip 192.168.100.17

![vllm_bug](https://github.com/vllm-project/vllm/assets/137979399/5de09872-572b-4c22-9c31-197f641c4c64)

while running program and then checking connection througfh netstat it shows localhost with some internal ip as well as 192.168..

### 🐛 Describe the bug

My vllm version is 0.2.2 and I  create the vllm conda environment and hit the below command:-

`HF_DATASETS_OFFLINE=1` TRANSFORMERS_OFFLINE=1 python -m vllm.entrypoints.openai.api_server --port=5000 --host=127.0.0.1 --model "/home/abcdt/.cache/huggingface/hub/models--meta-llama--Llama-2-13b-chat-hf/snapshots/c2f3ec81aac798ae26dcc57799a994dfbf521496" --tokenizer=hf-internal-testing/llama-tokenizer --tensor-parallel-size=1 --seed 1234 --max-num-batched-tokens=4096`

**Comment by simon-mo** [comment]
On the main branch and next version of vLLM, you can use the flag `HOST_IP` to override this.
