### ISSUE TITLE
[Bug]: when intalling vllm by pip, some errors happend.

### ISSUE THREAD

**Issue by finylink** [vllm-project/vllm#3526]
### Your current environment

```text
PyTorch version: 2.1.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Kylin Linux Advanced Server V10 (Sword) (aarch64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.27.9
Libc version: glibc-2.28

Python version: 3.8.18 (default, Sep 11 2023, 13:19:25)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.90-24.4.v2101.ky10.aarch64-aarch64-with-glibc2.26
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           aarch64
CPU 运行模式：                   64-bit
字节序：                         Little Endian
CPU:                             256
在线 CPU 列表：                  0-255
每个核的线程数：                 1
每个座的核数：                   64
座：                             4
NUMA 节点：                      8
厂商 ID：                        HiSilicon
型号：                           0
型号名称：                       Kunpeng-920
步进：                           0x1
CPU 最大 MHz：                   3000.0000
CPU 最小 MHz：                   200.0000
BogoMIPS：                       200.00
L1d 缓存：                       16 MiB
L1i 缓存：                       16 MiB
L2 缓存：                        128 MiB
L3 缓存：                        256 MiB
NUMA 节点0 CPU：                 0-31
NUMA 节点1 CPU：                 32-63
NUMA 节点2 CPU：                 64-95
NUMA 节点3 CPU：                 96-127
NUMA 节点4 CPU：                 128-159
NUMA 节点5 CPU：                 160-191
NUMA 节点6 CPU：                 192-223
NUMA 节点7 CPU：                 224-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
标记：                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torch_npu==2.1.0+gite7c2bdd
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torch-npu                 2.1.0+gite7c2bdd          pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

### 🐛 Describe the bug

Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
        device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
      Traceback (most recent call last):
        File "/root/anaconda3/envs/mindspore_py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/anaconda3/envs/mindspore_py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/anaconda3/envs/mindspore_py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 361, in <module>
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1076, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1203, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/tmp/pip-build-env-nc10d9u9/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2416, in _join_cuda_home
          raise OSError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]

------------------------------------------------------------------------------------------------

we install vllm in Ascend-cann-kernels-910b_7.0.1 and use Ascend-cann-toolkit_7.0.1_linux-aarch64
using the huawei Ascend NPU

**Comment by Jaywoods2** [comment]
+1 ， i have same question

**Comment by hmellor** [comment]
vLLM currently supports CUDA, ROCm and Neuron.

It looks like you're trying to use unsupported hardware.

**Comment by ywang96** [comment]
Closing as @hmellor provided a good answer

**Comment by leoneyar** [comment]
The graphics card is  ASCEND
