### ISSUE TITLE
Handling load tokenizer with llama model but different tokens

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#353]
For instance. 

For baichuan model which focus on Chinese, will load fail: 

ValueError: Tokenizer class BaiChuanTokenizer does not exist or is not currently imported.

This can be wrong if using AutoTokenizer as usual, however, it can forely using LlamaTokenizer to load, even though the model is different, but they all using same machensim, 

please add support for it

**Comment by zhuohan123** [comment]
Fixed by #364
