### ISSUE TITLE
[Feature]: H2O: Heavy-Hitter Oracle for Efficient Generative Inference of Large Language Models

### ISSUE THREAD

**Issue by chizhang118** [vllm-project/vllm#3532]
### 🚀 The feature, motivation and pitch

This paper might be of interest: https://arxiv.org/pdf/2306.14048.pdf

This paper mentions removing a small portion of the KV cache does not affect the results but improves memory efficiency. A 20% reduction in Heavy Hitters (H2) can increase throughput by 29 times and reduce latency by 1.9 times.
When calculating attention scores, a small portion of tokens contribute the majority of the value. This paper proposes the Heavy Hitter Oracle (H2O), a KV cache eviction strategy that dynamically balances retention between recent tokens and H2 tokens. They frame the eviction problem of the KV cache as a dynamic submodular problem.

Trade-off:
Deleting some deemed unimportant KV cache may raise concerns about accuracy, but it reduces memory usage to improve throughput.

@simon-mo Is this a feature you'd like to see implemented?

**Comment by ChuanhongLi** [comment]
H2O needs attention score to decide which one need to be evicted.  No matter the prompt processing(xops.memory_efficient_attention_forward, vllm = 0.2.7 ) or the decoding phase, it is not easy to get the attention score. Has any idea?

**Comment by laneeeee** [comment]
very interesting idea!, i have a question.  when i evicte a token in kvcahe, the position_embedding should be reorder?

**Comment by laneeeee** [comment]
very interesting idea!  the paper adopts wiki-text-103 as test dataset to get the conclusion, i think it will may be annother conclusion in pure mathematical formula dataset

**Comment by beagleski** [comment]
There's a similar feature request for [StreamingLLM](https://arxiv.org/abs/2309.17453), [issue here](https://github.com/vllm-project/vllm/issues/1253).
Meanwhile, [FastGen](https://arxiv.org/abs/2310.01801) and [Scissorhands ](https://arxiv.org/abs/2305.17118)are also highly related KV cache compression methods.
It would be better if the implementation design can be more general, e.g., flexible head-wise/layer-wise KV cache management.

**Comment by PiotrNawrot** [comment]
[Another promising KV Cache Compression](https://arxiv.org/abs/2403.09636) method (this time learned).
