### ISSUE TITLE
[Feature]: Add model loading using CoreWeave's `tensorizer`

### ISSUE THREAD

**Issue by sangstar** [vllm-project/vllm#3533]
### 🚀 The feature, motivation and pitch

An inference service that deploys models as serverless functions is critically dependent on container startup times to ensure it is responsive to changing traffic patterns. This is difficult to manage when model tensors stored in a container image bloat its size by tens of gigabytes. vLLM can now leverage `tensorizer` for its users [in this PR](https://github.com/vllm-project/vllm/pull/3476).

With [CoreWeave's `tensorizer`](https://github.com/coreweave/tensorizer), model tensors can be loaded off HTTP/HTTPS, Redis, or S3 endpoints. By not embedding the model in the container image, users can reduce the container image size and the time it takes to load the model. This allows for fast, and therefore responsive, autoscaling.

`tensorizer` serializes and can additionally encrypt model tensors to be loaded and/or decrypted extremely fast during container startup. Decoupling the model from the container image also additionally allows users to be able to update models without having to rebuild the container images, saving time deploying new versions without waiting for container image builds or for container image cache to be populated.

### Additional context

![image](https://github.com/vllm-project/vllm/assets/51196172/d92a5514-0cdc-4853-bfd8-c618b5258c65)

![torch-extras (3)](https://github.com/coreweave/vllm/assets/51196172/4494012f-b5b5-4ee0-805b-5f0a01f175e5)

**Comment by ywang96** [comment]
Closing this as we merged https://github.com/vllm-project/vllm/pull/3476
