### ISSUE TITLE
[Usage]: punica LoRA kernels could not be imported. If you built vLLM from source, make sure VLLM_INSTALL_PUNICA_KERNELS=1 env var was set.

### ISSUE THREAD

**Issue by nlp-learner** [vllm-project/vllm#3540]
When I was using yi and qwen, due to the error When using LoRA, vocab size must be 32000 >= vocab_size <= 33024, I modified the source code of bgmv_config.h and rebuilt it using python setup.py install. Now the above error is prompted. , but I added it to my code

os.environ['VLLM_INSTALL_PUNICA_KERNELS'] = "1"

How should I modify it to work properly

**Comment by arcticfly** [comment]
@nlp-learner what was the resolution?

**Comment by stas00** [comment]
I think the error is trying to suggest that when you build vllm from source you need to have `export VLLM_INSTALL_PUNICA_KERNELS=1` run **before** you build vllm. So set it, rebuild vllm and most likely it should work then.
