### ISSUE TITLE
[CI] Create nightly images/wheels

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#3545]
### Anything you want to discuss about vllm.

It would be great if we can distribute nightly images and wheels. This should be as simple as building images to push them to google container registry w/ public access, and push wheels to storage bucket.

**Comment by youkaichao** [comment]
At least we should do this against nightly build pytorch, every day or every several days. If pytorch has some breaking change, we will know in less than one week.

**Comment by simon-mo** [comment]
This is a different task. @youkaichao can you create a new issue tracking it?

**Comment by youkaichao** [comment]
issue created at https://github.com/vllm-project/vllm/issues/3560 . 

BTW, to build wheels, we also have to consider our support matrix, across cuda version, nccl version, pytorch version, etc.

**Comment by simon-mo** [comment]
Our currently support matrix is pretty simple! which is tie to one single version of each

**Comment by rkooo567** [comment]
+1 on this. It worked very well with ray, especially when users have a bug that is fixed in the master.

**Comment by simon-mo** [comment]
Here are some pointers, @rkooo567 
* Wheels are currently not build in Buildkite, rather it is in GitHub Actions: https://github.com/vllm-project/vllm/blob/main/.github/workflows/publish.yml. We would like the wheels to be built in Buildkite environment. 
* In our buildkite CI, the following code builds docker container in a big CPU machine: https://github.com/vllm-project/vllm/blob/dfeb2ecc3abe5c1d1a3161b39d8cead5484591e9/.buildkite/test-template.j2#L11-L20. And then the tests are kicked off inside docker containers running in K8s https://github.com/vllm-project/vllm/blob/dfeb2ecc3abe5c1d1a3161b39d8cead5484591e9/.buildkite/test-template.j2#L23-L64 The for loop iterate over this yaml lists https://github.com/vllm-project/vllm/blob/main/.buildkite/test-pipeline.yaml
* The CPU machine currently builds the test image https://github.com/vllm-project/vllm/blob/dfeb2ecc3abe5c1d1a3161b39d8cead5484591e9/Dockerfile#L79-L95 , not the official image we distribute.  https://github.com/vllm-project/vllm/blob/dfeb2ecc3abe5c1d1a3161b39d8cead5484591e9/Dockerfile#L120-L131 

For nightly wheels, we should replicate the environment (maybe use conda?) to perform wheel building process. I haven't figure out whether we should run this on big CPU machine, small CPU containers, or small GPU containers. I would try maybe a small CPU container to build wheels if needed to avoid the big CPU machine from being queued up. In order to use a small CPU container, you can probably just create a jobs similar to other test but use num_gpus=0. The K8s cluster running the tests might need extra setup to push the wheels to a storage bucket.

For nightly container images, we need to use the CPU machine to build the openai target and push to the gcr destination as well. perhaps as a separate repo in the google cloud container registry.

Note that both of these, we don't need to publish them in official container registry (docker.io) nor package registry (pypi) for vLLM.

**Comment by rkooo567** [comment]
I may have time to look at it after https://github.com/vllm-project/vllm/pull/3631

**Comment by youkaichao** [comment]
close as we have per-commit wheels now.
