### ISSUE TITLE
[Feature]: Compatibility issues

### ISSUE THREAD

**Issue by BlackHandsomeLee** [vllm-project/vllm#3555]
### 🚀 The feature, motivation and pitch

Can the vllm acceleration framework be compatible with tensorRT-LLM?
here is doc about tensorRT-LLM：
https://github.com/NVIDIA/TensorRT-LLM

**Comment by simon-mo** [comment]
Can you elaborate about which aspect of the compatibility you are interested in? The API/distribution/kernels?

**Comment by BlackHandsomeLee** [comment]
> Can you elaborate about which aspect of the compatibility you are interested in? The API/distribution/kernels?

can vllm offline inference  be compatible with  run  local execution tensorRT-LLM engine

**Comment by simon-mo** [comment]
Do you mean outputting the same? vLLM offline inference can run models end to end with performance on-par with TensorRT-LLM.
