### ISSUE TITLE
[Bug]: Using `pytest --forked` when CUDA is not generally fork-safe

### ISSUE THREAD

**Issue by sangstar** [vllm-project/vllm#3557]
### Your current environment

The environment vLLM uses to CI test a PR.

### 🐛 Describe the bug

Multiple tests for [my pull request](https://github.com/vllm-project/vllm/pull/3476) are failing due to `pytest --forked` trying to fork new child processes during testing, trying to re-initialize the CUDA context. I'm not sure how other PRs are passing these tests, but I don't know why `pytest --forked` is explicitly being used when CUDA isn't fork-safe. 

This is fine as long as `conftest.py` doesn't ever initialize CUDA before forking, but this may be difficult to maintain and may be a cause of some sneaky bugs, like from #3487

**Comment by rkooo567** [comment]
Yeah +1 fixing this issue. @sangstar are you familiar with how --forked works? When does it actually fork a new process for running a test?

**Comment by sangstar** [comment]
`pytest-forked`, which allows `--forked` to be invoked as a CLI arg for `pytest`, runs each test as a child process of its parent. If the parent process initializes a CUDA context, all child processes forked from it will inherit its memory space, including its CUDA context. If the process then tries to invoke CUDA, it will still try to create a new CUDA context (mostly due to CUDA contexts being weird about being copied over, as they aren't meant to be), which can lead to inconsistencies or undefined behavior, which is why a `Runtime Error` will be thrown.

**Comment by rkooo567** [comment]
Hmm so I guess there are some ideas
1. we don't use fork at all (in this case, we should ensure cuda related contexts are cleaned up between all tests)
2. we use fork for all tests (but conftest can still be used) -> not working
3. we use spawn instead of fork (seems difficult because it is not supported by pytest) -> not working

So basically 1 is the only viable solution? I also wonder how other ML projects handle these issues. Do you happen to know?

**Comment by sangstar** [comment]
Cleanup fixtures would be a good option to explore. Forking avoids needing cleanup fixtures but it will cause weird, cryptic error any time a CUDA context is initiated before forking and invoking a test that uses CUDA.

**Comment by rkooo567** [comment]
https://github.com/vllm-project/vllm/pull/3631/files#diff-2fe466060a88bb6a57175df8ca7175849db82a2cf2ba082295d481ab57e58868

It is in progress @sangstar and the result seems pretty promising (all model tests pass except 5 of them)
