### ISSUE TITLE
How to know the maximum concurrent requests /tokens that generate can handle at the same time?

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#3561]
### Your current environment

I am wondering how to know or configure the number of concurrent requests (number of tokens). I can see from logs these values:

`INFO 03-18 12:34:52 llm_engine.py:706] Avg prompt throughput: 209.6 tokens/s, Avg generation throughput: 567.4 tokens/s, Running: 36 reqs, Swapped: 0 reqs, Pending: 78 reqs, GPU KV cache usage: 99.1%, CPU KV cache usage: 0.0% `

1. i don't know when the request would be in the pending and what is the meaning of running request? 
2. does all of them are enter in the model at the same time (same batch)?
3. What the effect of `max_tokens` in `SamplingParams,` if I set it to 1024 but I receive response of 1027 tokens!!

In the `EngineArgs`:
4. Is this  `--max-model-len` will limit the single request tokens? or only has affect on the pre-reserved GPU memory for the llm?
5. what is eager mode?
6. how dynamic batching is performed? if we send N requests do they will be in a queue based on what? what is the max batch size to be entered to the model?
7. Is this `max_context_len_to_capture` has affect on the total number of tokens can the model handle? 
8. Also I didn't understand well what are these args? how they affect the batching or number of requests?
 * `max_num_batched_tokens`
 * `max_num_seqs`

I would be grateful if anyone explain to me these points. Thanks

### 🐛 Describe the bug

For both, openllm start  with vllm backend or even vllm on ray.

**Comment by hahmad2008** [comment]
@rkooo567 could you please check this?

**Comment by hahmad2008** [comment]
@youkaichao could you please check this?

**Comment by youkaichao** [comment]
Sorry but this falls out of my expertise :(

**Comment by hahmad2008** [comment]
@youkaichao Thanks 🙏

**Comment by rkooo567** [comment]
> 1. i don't know when the request would be in the pending and what is the meaning of running request?
pending: # of requests that haven't been scheduled. running: # of requests that run prefill and process decoding phases.

> does all of them are enter in the model at the same time (same batch)?
Yeah. All requests are batched to a single model request, and only 1 batched request is handled by a model at a time.

> What the effect of max_tokens in SamplingParams, if I set it to 1024 but I receive response of 1027 tokens!!
`max_tokens: Maximum number of tokens to generate per output sequence.`
Note that it is sampling parameter, and I think the batched token size is affected by `max_num_batched_tokens`, not this one

In the EngineArgs:
>  Is this --max-model-len will limit the single request tokens? or only has affect on the pre-reserved GPU memory for the llm?
This is the "context length" of models. So each prompt + output cannot have longer length than this. 

> 5. what is eager mode?
By default it is not eager mode. Eager mode means it uses pure torch (which executes line by line eagerly). If it is not set, it uses cuda_graph, which basically captures the previous execution and reply https://pytorch.org/blog/accelerating-pytorch-with-cuda-graphs/. It will consume more GPU memory, but it is faster.

> 6. how dynamic batching is performed? if we send N requests do they will be in a queue based on what? what is the max batch size to be entered to the model?
They are queued and scheduler picks requests to batch to a single model run. `max_num_batched_tokens` is used to decide the maximum batch size. Note that vLLM doesn't batch decoding and prefill requests in the same batch (it will be changed soon, but the status quo is like this)

> 7. Is this max_context_len_to_capture has affect on the total number of tokens can the model handle?
It is same as the model len by default btw. And it doesn't affect it (it just fallsback to eager mode). 

> 8. Also I didn't understand well what are these args? how they affect the batching or number of requests?
max_num_batched_tokens: How many tokens can be batched into a single model run.
max_num_seqs: How many requests can be batched into a single model run.

**Comment by NrKhader** [comment]
@rkooo567 How is the size of the queue determined?

**Comment by rkooo567** [comment]
> So the running requests should include not only the inputs fed directly to the model but also the requests that are currently tokenized and prepared to be fed to the model, correct?

It is a simplified view. There's also things like preemption which can change the states.

tokenization -> ready for prefill: WAITING -> RUNNING
finished prefill -> ready for decoding: RUNNING -> RUNNING
decoding finished: RUNNING -> FINISHED
preempted (because kv caches are not enough) -> switch to WAITING

> Regarding the total tokens in the batch, if we have "max_num_batched_tokens" set as default "None," how does it determine the maximum tokens in the batch?

It is equivalent to the model's maximum context size (max_model_len).

**Comment by ywang96** [comment]
Closing as @rkooo567 provided a great answer!
