### ISSUE TITLE
[Usage]: Unable to get the vllm fastapi up and running in GPU enabled container in kube cluster

### ISSUE THREAD

**Issue by nandhaece07** [vllm-project/vllm#3564]
### Your current environment

**OS:** Ubuntu: 20.04
**GPU:** NVIDIA L40S-48C
**Driver Version:** 535.154.05   
**CUDA Version:** 12.2

**Kubernetes node info:**

Name:               auto-int-k8w02
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    dedicated=distilgpt2-fastapi
                    feature.node.kubernetes.io/cpu-cpuid.ADX=true
                    feature.node.kubernetes.io/cpu-cpuid.AESNI=true
                    feature.node.kubernetes.io/cpu-cpuid.AMXBF16=true
                    feature.node.kubernetes.io/cpu-cpuid.AMXINT8=true
                    feature.node.kubernetes.io/cpu-cpuid.AMXTILE=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX2=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512BF16=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512BITALG=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512BW=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512CD=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512DQ=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512F=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512FP16=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512IFMA=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VBMI2=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VL=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI=true
                    feature.node.kubernetes.io/cpu-cpuid.AVX512VPOPCNTDQ=true
                    feature.node.kubernetes.io/cpu-cpuid.AVXVNNI=true
                    feature.node.kubernetes.io/cpu-cpuid.BHI_CTRL=true
                    feature.node.kubernetes.io/cpu-cpuid.CETSS=true
                    feature.node.kubernetes.io/cpu-cpuid.CLDEMOTE=true
                    feature.node.kubernetes.io/cpu-cpuid.CMPSB_SCADBS_SHORT=true
                    feature.node.kubernetes.io/cpu-cpuid.CMPXCHG8=true
                    feature.node.kubernetes.io/cpu-cpuid.FLUSH_L1D=true
                    feature.node.kubernetes.io/cpu-cpuid.FMA3=true
                    feature.node.kubernetes.io/cpu-cpuid.FSRM=true
                    feature.node.kubernetes.io/cpu-cpuid.FXSR=true
                    feature.node.kubernetes.io/cpu-cpuid.FXSROPT=true
                    feature.node.kubernetes.io/cpu-cpuid.GFNI=true
                    feature.node.kubernetes.io/cpu-cpuid.HYPERVISOR=true
                    feature.node.kubernetes.io/cpu-cpuid.IA32_ARCH_CAP=true
                    feature.node.kubernetes.io/cpu-cpuid.IBPB=true
                    feature.node.kubernetes.io/cpu-cpuid.IDPRED_CTRL=true
                    feature.node.kubernetes.io/cpu-cpuid.LAHF=true
                    feature.node.kubernetes.io/cpu-cpuid.MD_CLEAR=true
                    feature.node.kubernetes.io/cpu-cpuid.MOVBE=true
                    feature.node.kubernetes.io/cpu-cpuid.MOVDIR64B=true
                    feature.node.kubernetes.io/cpu-cpuid.MOVDIRI=true
                    feature.node.kubernetes.io/cpu-cpuid.MOVSB_ZL=true
                    feature.node.kubernetes.io/cpu-cpuid.OSXSAVE=true
                    feature.node.kubernetes.io/cpu-cpuid.PSFD=true
                    feature.node.kubernetes.io/cpu-cpuid.RRSBA_CTRL=true
                    feature.node.kubernetes.io/cpu-cpuid.SERIALIZE=true
                    feature.node.kubernetes.io/cpu-cpuid.SHA=true
                    feature.node.kubernetes.io/cpu-cpuid.SPEC_CTRL_SSBD=true
                    feature.node.kubernetes.io/cpu-cpuid.STIBP=true
                    feature.node.kubernetes.io/cpu-cpuid.STOSB_SHORT=true
                    feature.node.kubernetes.io/cpu-cpuid.SYSCALL=true
                    feature.node.kubernetes.io/cpu-cpuid.SYSEE=true
                    feature.node.kubernetes.io/cpu-cpuid.VAES=true
                    feature.node.kubernetes.io/cpu-cpuid.VPCLMULQDQ=true
                    feature.node.kubernetes.io/cpu-cpuid.WBNOINVD=true
                    feature.node.kubernetes.io/cpu-cpuid.X87=true
                    feature.node.kubernetes.io/cpu-cpuid.XGETBV1=true
                    feature.node.kubernetes.io/cpu-cpuid.XSAVE=true
                    feature.node.kubernetes.io/cpu-cpuid.XSAVEC=true
                    feature.node.kubernetes.io/cpu-cpuid.XSAVEOPT=true
                    feature.node.kubernetes.io/cpu-cpuid.XSAVES=true
                    feature.node.kubernetes.io/cpu-hardware_multithreading=false
                    feature.node.kubernetes.io/cpu-model.family=6
                    feature.node.kubernetes.io/cpu-model.id=143
                    feature.node.kubernetes.io/cpu-model.vendor_id=Intel
                    feature.node.kubernetes.io/kernel-config.NO_HZ=true
                    feature.node.kubernetes.io/kernel-config.NO_HZ_IDLE=true
                    feature.node.kubernetes.io/kernel-version.full=5.4.0-174-generic
                    feature.node.kubernetes.io/kernel-version.major=5
                    feature.node.kubernetes.io/kernel-version.minor=4
                    feature.node.kubernetes.io/kernel-version.revision=0
                    feature.node.kubernetes.io/pci-10de.present=true
                    feature.node.kubernetes.io/pci-15ad.present=true
                    feature.node.kubernetes.io/storage-nonrotationaldisk=true
                    feature.node.kubernetes.io/system-os_release.ID=ubuntu
                    feature.node.kubernetes.io/system-os_release.VERSION_ID=20.04
                    feature.node.kubernetes.io/system-os_release.VERSION_ID.major=20
                    feature.node.kubernetes.io/system-os_release.VERSION_ID.minor=04
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=auto-int-k8w02
                    kubernetes.io/os=linux
                    nvidia.com/cuda.driver.major=535
                    nvidia.com/cuda.driver.minor=154
                    nvidia.com/cuda.driver.rev=05
                    nvidia.com/cuda.runtime.major=12
                    nvidia.com/cuda.runtime.minor=2
                    nvidia.com/gfd.timestamp=1711076334
                    nvidia.com/gpu-driver-upgrade-state=upgrade-done
                    nvidia.com/gpu.compute.major=8
                    nvidia.com/gpu.compute.minor=9
                    nvidia.com/gpu.count=1
                    nvidia.com/gpu.deploy.container-toolkit=true
                    nvidia.com/gpu.deploy.dcgm=true
                    nvidia.com/gpu.deploy.dcgm-exporter=true
                    nvidia.com/gpu.deploy.device-plugin=true
                    nvidia.com/gpu.deploy.driver=pre-installed
                    nvidia.com/gpu.deploy.gpu-feature-discovery=true
                    nvidia.com/gpu.deploy.node-status-exporter=true
                    nvidia.com/gpu.deploy.operator-validator=true
                    nvidia.com/gpu.family=ampere
                    nvidia.com/gpu.memory=49152
                    nvidia.com/gpu.present=true
                    nvidia.com/gpu.product=NVIDIA-L40S-48C-SHARED
                    nvidia.com/gpu.replicas=4
                    nvidia.com/mig.capable=true
                    nvidia.com/mig.strategy=single
                    nvidia.com/vgpu.host-driver-branch=r538_10
                    nvidia.com/vgpu.host-driver-version=535.154.02
                    nvidia.com/vgpu.present=true
Annotations:        nfd.node.kubernetes.io/feature-labels:
                      cpu-cpuid.ADX,cpu-cpuid.AESNI,cpu-cpuid.AMXBF16,cpu-cpuid.AMXINT8,cpu-cpuid.AMXTILE,cpu-cpuid.AVX,cpu-cpuid.AVX2,cpu-cpuid.AVX512BF16,cpu-...
                    nfd.node.kubernetes.io/worker.version: v0.14.2
                    node.alpha.kubernetes.io/ttl: 0
                    nvidia.com/gpu-driver-upgrade-enabled: true
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 19 Mar 2024 14:38:21 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  auto-int-k8w02
  AcquireTime:     <unset>
  RenewTime:       Fri, 22 Mar 2024 03:19:17 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Fri, 22 Mar 2024 02:07:07 +0000   Fri, 22 Mar 2024 02:07:07 +0000   WeaveIsUp                    Weave pod has set this
  MemoryPressure       False   Fri, 22 Mar 2024 03:19:21 +0000   Fri, 22 Mar 2024 02:06:59 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Fri, 22 Mar 2024 03:19:21 +0000   Fri, 22 Mar 2024 02:06:59 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Fri, 22 Mar 2024 03:19:21 +0000   Fri, 22 Mar 2024 02:06:59 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Fri, 22 Mar 2024 03:19:21 +0000   Fri, 22 Mar 2024 02:06:59 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.0.3.12
  Hostname:    auto-int-k8w02
Capacity:
  cpu:                8
  ephemeral-storage:  1051634356Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16379868Ki
  nvidia.com/gpu:     4
  pods:               110
Allocatable:
  cpu:                8
  ephemeral-storage:  969186220885
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16277468Ki
  nvidia.com/gpu:     4
  pods:               110
System Info:
  Machine ID:                 53a5ce1f1d3447468837b7e9826550e0
  System UUID:                ef873742-1fa8-a053-0780-9c72928e9c30
  Boot ID:                    9f83bc54-e86f-446d-8fc1-6525a26a7f85
  Kernel Version:             5.4.0-174-generic
  OS Image:                   Ubuntu 20.04.6 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.13
  Kubelet Version:            v1.29.3
  Kube-Proxy Version:         v1.29.3
PodCIDR:                      10.112.2.0/24
PodCIDRs:                     10.112.2.0/24
Non-terminated Pods:          (11 in total)
  Namespace                   Name                                                               CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                                               ------------  ----------  ---------------  -------------  ---
  cicero                      c4ai-command-r-v01-6fb467c5db-q8mt7                                0 (0%)        0 (0%)      0 (0%)           0 (0%)         6m37s
  cicero                      c4ai-command-r-v01-c5db49468-986kk                                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         7m40s
  gpu-operator                gpu-feature-discovery-lsbmq                                        0 (0%)        0 (0%)      0 (0%)           0 (0%)         20m
  gpu-operator                gpu-operator-1711076233-node-feature-discovery-gc-74978db97rm9w    0 (0%)        0 (0%)      0 (0%)           0 (0%)         22m
  gpu-operator                gpu-operator-1711076233-node-feature-discovery-worker-hlbrn        0 (0%)        0 (0%)      0 (0%)           0 (0%)         22m
  gpu-operator                nvidia-container-toolkit-daemonset-xf6nf                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         21m
  gpu-operator                nvidia-dcgm-exporter-mq487                                         0 (0%)        0 (0%)      0 (0%)           0 (0%)         21m
  gpu-operator                nvidia-device-plugin-daemonset-psmjq                               0 (0%)        0 (0%)      0 (0%)           0 (0%)         20m
  gpu-operator                nvidia-operator-validator-pk9cz                                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         21m
  kube-system                 kube-proxy-p8mzl                                                   0 (0%)        0 (0%)      0 (0%)           0 (0%)         2d12h
  kube-system                 weave-net-8cwz6                                                    100m (1%)     0 (0%)      0 (0%)           0 (0%)         2d12h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                100m (1%)  0 (0%)
  memory             0 (0%)     0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
  hugepages-1Gi      0 (0%)     0 (0%)
  hugepages-2Mi      0 (0%)     0 (0%)
  nvidia.com/gpu     2          2
Events:              <none>

**nvidia-smi out:**
Fri Mar 22 03:20:31 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L40S-48C                On  | 00000000:03:00.0 Off |                    0 |
| N/A   N/A    P0              N/A /  N/A |    516MiB / 49152MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     23249      C   python3                                     515MiB |
+---------------------------------------------------------------------------------------+

**deploy.yaml:**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: c4ai-command-r-v01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c4ai-command-r-v01
  template:
    metadata:
      labels:
        app: c4ai-command-r-v01
    spec:
      nodeSelector:
        kubernetes.io/hostname: auto-int-k8w02
      containers:
        - command:
            - python3
            - '-u'
            - '-m'
            - vllm.entrypoints.openai.api_server
            - '--host'
            - 0.0.0.0
            - '--port'
            - '8000'
            - '--revision'
            - $(REVISION)
            - '--disable-log-requests'
            - '--download-dir'
            - /data/
            - '--tokenizer-mode'
            - auto
            - '--model'
            - $(MODEL_ID)
            - '--tokenizer'
            - $(MODEL_ID)
            - '--trust-remote-code'
            - '--dtype'
            - $(DTYPE)
            - '--tensor-parallel-size'
            - $(GPU_COUNT)
            - '--gpu-memory-utilization'
            - '0.95'
            - '--enforce-eager'
            - '--served-model-name'
            - $(MODEL_NAME)
            - '--max_parallel_loading_workers'
            - '2'

          env:
            - name: DTYPE
              value: auto
            - name: GPU_COUNT
              value: '1'
            - name: MODEL_ID
              value: >-
                /opt/truefoundry/huggingface-hub/models--CohereForAI--c4ai-command-r-v01/2323aaa960c3c073380a0da2fc51284f5113e114/
            - name: MODEL_NAME
              value: c4ai-command-r-v01
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: compute,utility
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          image: vllm/vllm-openai:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 20
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          name: c4ai-command-r-v01
          ports:
            - containerPort: 8000
              name: port-8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /opt/truefoundry
              name: artifact-download-cache
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      volumes:
        - name: artifact-download-cache
          persistentVolumeClaim:
            claimName: cohereforai-pvc
        - emptyDir:
            medium: Memory
            sizeLimit: 30G
          name: dshm

**Comment by simon-mo** [comment]
Looks like you are trying to use command R model, which is not supported by, see #3330

**Comment by simon-mo** [comment]
Closing as duplicate of #3330, please subscribe to that issue, we will try to support it as soon as we can.
