### ISSUE TITLE
[Bug]: Should check whether stop sequence appears anyway in the output text instead of just endswith

### ISSUE THREAD

**Issue by yunfeng-scale** [vllm-project/vllm#3572]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

Using mistral-7b-instruct model, and prompt `Here is the English alphabet: ABC`, temperature 0, stop sequence `DE`, model would still output `DEFGHIJKLMNOPQRSTUVWXYZ...` this is because `DEF` is a token, and stop sequence is only checked with `endswith` https://github.com/vllm-project/vllm/blob/main/vllm/engine/llm_engine.py#L717 I think instead of we should check string contain.

**Comment by njhill** [comment]
@yunfeng-scale yes this is definitely a bug, I'm working on a fix.
