### ISSUE TITLE
[Feature]: Long context window - Ring Attention with Blockwise Transformers for Near-Infinite Context

### ISSUE THREAD

**Issue by chizhang118** [vllm-project/vllm#3573]
This paper might be of interest: https://arxiv.org/pdf/2310.01889.pdf

This paper proposes Ring Attention with Blockwise Transformers, which leverages blockwise computation of self-attention and feedforward to distribute long sequences across multiple devices while fully overlapping the communication of key-value blocks with the computation of blockwise attention. This method handles long context window using multiple devices and could support up to 16M context window for extreme cases.

@simon-mo Is this a feature you'd like to see implemented?

**Comment by hassan-twelvelabs** [comment]
Hello. Is this feature being actively worked on? Thanks.

**Comment by chizhang118** [comment]
> Hello. Is this feature being actively worked on? Thanks.

No for now.

**Comment by vadimkantorov** [comment]
I wonder if it's possible to support it using the new support of Context-Parallel in core PyTorch?
