### ISSUE TITLE
Support for longchat-7b-16k

### ISSUE THREAD

**Issue by yguo33** [vllm-project/vllm#358]
It would be great, if you can add support for longchat(from Fastchat) models, which have 16k context length:

https://github.com/lm-sys/FastChat

https://github.com/lm-sys/FastChat/blob/6d06351542bc0c3701d54619e6df4c26aa91a260/fastchat/model/llama_condense_monkey_patch.py#L10C18-L10C18

**Comment by srka99** [comment]
Is this implemented in #555?

**Comment by WoosukKwon** [comment]
@srka99 Yes. Thanks for pinging this!

**Comment by pseudotensor** [comment]
Does this also allow support of the vicuna based long context models like `lmsys/vicuna-13b-v1.5-16k` ?  I can't tell.
