### ISSUE TITLE
[Usage]: How to inference the quantized base model with LoRA weights ?

### ISSUE THREAD

**Issue by thincal** [vllm-project/vllm#3580]
### Your current environment

installed vLLM + GPU env.

### How would you like to use vllm

I have done the QLoRA training with AWQ quantized base model, is that possible using the vLLM to load the AWQ base model and inference with the lora weights directly without merging ?

**Comment by jeejeelee** [comment]
The current vllm  does not support QLoRA yet

**Comment by thincal** [comment]
is there any plan for the qlora inference ?

**Comment by jeejeelee** [comment]
@thincal perhaps this PR can help you #2828
