### ISSUE TITLE
[Bug]: ImportError: cannot import name 'model_validator' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by syusama** [vllm-project/vllm#3582]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

![微信截图_20240323021712](https://github.com/vllm-project/vllm/assets/16223129/749c18ca-4ad9-45cd-a3e0-91738d75c4c9)

`ImportError: cannot import name 'model_validator' from 'pydantic' (/usr/local/lib/python3.10/dist-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)`

When I try to start the large language model with vllm, I encounter this error, but I couldn't find any relevant information or resources online. My environment is Docker with Python 3.10.

**Comment by youkaichao** [comment]
It seems your environment is broken.

You can use our pre-built docker image from `https://hub.docker.com/r/vllm/vllm-openai` : 

`docker pull vllm/vllm-openai`

**Comment by syusama** [comment]
> It seems your environment is broken.
> 
> You can use our pre-built docker image from `https://hub.docker.com/r/vllm/vllm-openai` :
> 
> `docker pull vllm/vllm-openai`

thanks！
