### ISSUE TITLE
[Bug]: Empty generated output

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#3598]
### Your current environment

I am testing completion and chat completion APIs, and both return empty output `''` as output from the model and on the service side, it print zeros for the number of generated tokens and kv cache.
`Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
`

model is a 7b-mistral based model.

### 🐛 Describe the bug

I am using the entrypoint from vllm project.

**Comment by youkaichao** [comment]
Is this consistent behavior? Or is it transient?

Can you run for several times to see if it is reproducible?

**Comment by hahmad2008** [comment]
@youkaichao yes it is consistent behavior.

**Comment by youkaichao** [comment]
Can you try to give a reproducible example?

e.g. you can use our docker image `docker pull vllm/vllm-openai:v0.3.3` , and give us how you run the docker image and the shell script.
