### ISSUE TITLE
[Feature]: FASTDECODE: High-Throughput GPU-Efficient LLM Serving using Heterogeneous Pipelines

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#3606]
### 🚀 The feature, motivation and pitch

https://arxiv.org/pdf/2403.11421.pdf

This paper might be interesting.

> Cost of serving large language models (LLM) is high, but the
expensive and scarce GPUs are poorly efficient when generating tokens sequentially, unless the batch of sequences is
enlarged. However, the batch size is limited by some constantly reused intermediate results, namely KV-Cache. They
occupy too much memory to fit more sequences into a GPU simultaneously. While they could be offloaded to host memory,
the CPU-GPU bandwidth is an inevitable bottleneck.
We find a way to decompose the transformer models into
two parts of different characteristics, one of which includes
the memory-bound KV-Cache accessing. Our key insight is
that the aggregated memory capacity, bandwidth, and computing power of CPUs across multiple nodes is an efficient
option to process this part. Performance improvement comes
from reduced data transmission overhead and boosted GPU
throughput to process the other model part. Moreover, we address efficiency challenges brought by heterogeneity at both
temporal and inter-device scopes using scheduling and performance modeling techniques. Evaluation results show that
our system achieves 1.88× −5.04× the throughput of vLLM
when serving modern LLMs with the same GPU.

**Comment by youkaichao** [comment]
It might improve performance at the cost of complexity though. Scheduling between CPU and GPU computation would be a nightmare. It might fit better for a product, rather than an open-source project, imo 👀
