### ISSUE TITLE
[Bug]: when load gemma 7b after sft, meet an err: TypeError: flash_attn_varlen_func() got an unexpected keyword argument 'alibi_slopes' 

### ISSUE THREAD

**Issue by uRENu** [vllm-project/vllm#3629]
### Your current environment

pip install vllm-main.zip

### 🐛 Describe the bug

[2024-03-26,14:27:51][I][1103-__main__-llm_infer_vllm.py:79]- Setting template_type: default

[2024-03-26,14:27:51][I][1103-__main__-llm_infer_vllm.py:211]- sft_args:

InferArguments(model_hdfs_name='gemma-7B', sft_type='full', template_type='default', ckpt_dir='/mnt/data/user/luca_model/klara/models/unified_ai_platform_sft_white/v20240319002930/train-model', eval_human=False, seed=42, dtype='bf16', ignore_args_error=False, dataset_seed=42, dataset_sample=-1, dataset_test_size=0.01, system='you are a helpful assistant!', max_length=2048, quantization_bit=None, bnb_4bit_comp_dtype=None, bnb_4bit_quant_type='nf4', bnb_4bit_use_double_quant=True, max_new_tokens=1024, do_sample=False, temperature=0.0, top_k=-1, top_p=0.9, skip_prompt=False, data_path={'train_file': [], 'eval_file': [], 'predict_file': ['/local/data/inference_3446/data/predict_6546.txt']}, remote_result_path='/user/tc_ai/data/aip/task/infer/dataset/inference_3446/predict_result', batch_size=8, sub_task_id=3446)

[2024-03-26,14:27:51][I][1103-__main__-llm_infer_vllm.py:111]- generation_config:

GenerationConfig {

"do_sample": true,

"eos_token_id": 1,

"max_new_tokens": 2048,

"pad_token_id": 0,

"temperature": 0.3,

"top_k": 20,

"top_p": 0.7,

"trust_remote_code": true

}

INFO 03-26 14:27:51 llm_engine.py:68] Initializing an LLM engine (v0.3.3) with config: model='/mnt/data/user/luca_model/klara/models/unified_ai_platform_sft_white/v20240319002930/train-model', tokenizer='/mnt/data/user/luca_model/klara/models/unified_ai_platform_sft_white/v20240319002930/train-model', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=42)

INFO 03-26 14:27:53 selector.py:15] Using FlashAttention backend.

NCCL version 2.18.1+cuda12.1

INFO 03-26 14:28:09 model_runner.py:100] Loading model weights took 15.9066 GB

Traceback (most recent call last):

File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main

return _run_code(code, main_globals, None,

File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code

exec(code, run_globals)

File "/local/apps/large_model_predict/open_llm_infer/llm_infer_vllm.py", line 212, in <module>

llm_infer(sft_args)

File "/local/apps/large_model_predict/open_llm_infer/llm_infer_vllm.py", line 112, in llm_infer

llm = LLM(model=args.ckpt_dir, trust_remote_code=True, seed=42, tensor_parallel_size=torch.cuda.device_count())

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 109, in __init__

self.llm_engine = LLMEngine.from_engine_args(engine_args)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 146, in from_engine_args

engine = cls(*engine_configs,

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 103, in __init__

self.model_executor = executor_class(model_config, cache_config,

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 38, in __init__

self._init_cache()

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 77, in _init_cache

self.driver_worker.profile_num_available_blocks(

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/worker/worker.py", line 122, in profile_num_available_blocks

self.model_runner.profile_run()

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 680, in profile_run

self.execute_model(seqs, kv_caches)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 609, in execute_model

hidden_states = model_executable(

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

return forward_call(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context

return func(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/model_executor/models/gemma.py", line 292, in forward

hidden_states = self.model(input_ids, positions, kv_caches,

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

return forward_call(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/model_executor/models/gemma.py", line 235, in forward

hidden_states, residual = layer(

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

return forward_call(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/model_executor/models/gemma.py", line 187, in forward

hidden_states = self.self_attn(

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

return forward_call(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/model_executor/models/gemma.py", line 139, in forward

attn_output = self.attn(q, k, v, kv_cache, attn_metadata)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl

return self._call_impl(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl

return forward_call(*args, **kwargs)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/attention/layer.py", line 46, in forward

return self.impl.forward(query, key, value, kv_cache, attn_metadata)

File "/home/jeeves/.local/lib/python3.10/site-packages/vllm/attention/backends/flash_attn.py", line 194, in forward

output = flash_attn_varlen_func(

TypeError: flash_attn_varlen_func() got an unexpected keyword argument 'alibi_slopes'

Inferring failed, please check log

**Comment by WoosukKwon** [comment]
@uRENu I guess this is because `flash-attn` installed on your machine is not up to date. Please upgrade it by running `pip install --upgrade flash-attn`.

**Comment by uRENu** [comment]
after install flash-attn==2.5.6, success!

**Comment by metasyn** [comment]
Should this type of requirement be added into the constraints for the package itself? I just ran into it today.

**Comment by maxin9966** [comment]
@WoosukKwon Flash-attn2 error report.

output = flash_attn_varlen_func(
TypeError: 'NoneType' object is not callable

# envs:
flash-attn==2.5.8
vllm 0.4.2 

NVIDIA-SMI 545.23.08              
Driver Version: 545.23.08    
CUDA Version: 12.3

# error:

5月 19 16:03:48 ma-GALAX-B760M-LIGHTXY-D4 bash[34559]: INFO:     Finished server process [34559]
5月 19 16:03:49 ma-GALAX-B760M-LIGHTXY-D4 systemd[1]: vllm-codeqwen-7b.service: Deactivated successfully.
5月 19 16:03:49 ma-GALAX-B760M-LIGHTXY-D4 systemd[1]: Stopped Uvicorn server for my app.
5月 19 16:03:49 ma-GALAX-B760M-LIGHTXY-D4 systemd[1]: vllm-codeqwen-7b.service: Consumed 15.428s CPU time.
5月 19 16:03:49 ma-GALAX-B760M-LIGHTXY-D4 systemd[1]: Started Uvicorn server for my app.
5月 19 16:03:52 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: /home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
5月 19 16:03:52 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]:   warnings.warn(
5月 19 16:03:52 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: WARNING 05-19 16:03:52 config.py:205] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
5月 19 16:03:52 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: INFO 05-19 16:03:52 llm_engine.py:100] Initializing an LLM engine (v0.4.2) with config: model='Qwen/CodeQwen1.5-7B-Chat-AWQ', speculative_config=None, tokenizer='Qwen/CodeQwen1.5-7B-Chat-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=gpt)
5月 19 16:03:54 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: INFO 05-19 16:03:54 utils.py:660] Found nccl from library /home/ma/.config/vllm/nccl/cu12/libnccl.so.2.18.1

5月 19 16:03:54 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: INFO 05-19 16:03:54 selector.py:46] Using Flashinfer backend.
5月 19 16:03:54 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: WARNING 05-19 16:03:54 selector.py:47] Eager mode is enforced for the Flashinfer backend.
5月 19 16:03:55 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: INFO 05-19 16:03:55 weight_utils.py:199] Using model weights format ['*.safetensors']
5月 19 16:03:56 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: INFO 05-19 16:03:56 model_runner.py:175] Loading model weights took 4.9340 GB
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]: Traceback (most recent call last):
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 197, in _run_module_as_main
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return _run_code(code, main_globals, None,
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/runpy.py", line 87, in _run_code
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     exec(code, run_globals)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 168, in <module>
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     engine = AsyncLLMEngine.from_engine_args(
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     engine = cls(
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     self.engine = self._init_engine(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return engine_class(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 172, in __init__
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     self._initialize_kv_caches()
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 249, in _initialize_kv_caches
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     self.model_executor.determine_num_available_blocks())
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 106, in determine_num_available_blocks
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self.driver_worker.determine_num_available_blocks()
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return func(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/worker/worker.py", line 139, in determine_num_available_blocks
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     self.model_runner.profile_run()
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return func(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 888, in profile_run
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     self.execute_model(seqs, kv_caches)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return func(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 808, in execute_model
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     hidden_states = model_executable(**execute_model_kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self._call_impl(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return forward_call(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 316, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self._call_impl(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return forward_call(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 253, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     hidden_states, residual = layer(
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self._call_impl(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return forward_call(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 206, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     hidden_states = self.self_attn(
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self._call_impl(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return forward_call(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 152, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self._call_impl(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return forward_call(*args, **kwargs)
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/attention/layer.py", line 48, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:   File "/home/ma/miniconda3/envs/myenv/lib/python3.9/site-packages/vllm/attention/backends/flashinfer.py", line 194, in forward
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]:     output = flash_attn_varlen_func(
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 bash[34642]: [rank0]: TypeError: 'NoneType' object is not callable
5月 19 16:03:57 ma-GALAX-B760M-LIGHTXY-D4 systemd[1]: vllm-codeqwen-7b.service: Main process exited, code=exited, status=1/FAILURE
