### ISSUE TITLE
[Usage]: api_server.py: error: unrecognized arguments: --api-key 

### ISSUE THREAD

**Issue by iFe1er** [vllm-project/vllm#3651]
### Your current environment

vllm==0.3.3

Problem:

I run :
`root@autodl-container-aa4d48ac02-16fdcb75:~# python -m vllm.entrypoints.api_server --model /root/autodl-tmp/Qwen15_14B_Chat_sft --tensor-parallel-size 2  --max-model-len 12800 --port 8080  --api-key token-temp`

and get:
```
usage: api_server.py [-h] [--host HOST] [--port PORT] [--ssl-keyfile SSL_KEYFILE] [--ssl-certfile SSL_CERTFILE] [--root-path ROOT_PATH] [--model MODEL] [--tokenizer TOKENIZER] [--revision REVISION] [--code-revision CODE_REVISION]
                     [--tokenizer-revision TOKENIZER_REVISION] [--tokenizer-mode {auto,slow}] [--trust-remote-code] [--download-dir DOWNLOAD_DIR] [--load-format {auto,pt,safetensors,npcache,dummy}] [--dtype {auto,half,float16,bfloat16,float,float32}]
                     [--kv-cache-dtype {auto,fp8_e5m2}] [--max-model-len MAX_MODEL_LEN] [--worker-use-ray] [--pipeline-parallel-size PIPELINE_PARALLEL_SIZE] [--tensor-parallel-size TENSOR_PARALLEL_SIZE] [--max-parallel-loading-workers MAX_PARALLEL_LOADING_WORKERS]
                     [--block-size {8,16,32,128}] [--seed SEED] [--swap-space SWAP_SPACE] [--gpu-memory-utilization GPU_MEMORY_UTILIZATION] [--max-num-batched-tokens MAX_NUM_BATCHED_TOKENS] [--max-num-seqs MAX_NUM_SEQS] [--max-paddings MAX_PADDINGS]
                     [--disable-log-stats] [--quantization {awq,gptq,squeezellm,None}] [--enforce-eager] [--max-context-len-to-capture MAX_CONTEXT_LEN_TO_CAPTURE] [--disable-custom-all-reduce] [--enable-lora] [--max-loras MAX_LORAS] [--max-lora-rank MAX_LORA_RANK]
                     [--lora-extra-vocab-size LORA_EXTRA_VOCAB_SIZE] [--lora-dtype {auto,float16,bfloat16,float32}] [--max-cpu-loras MAX_CPU_LORAS] [--device {auto,cuda,neuron}] [--engine-use-ray] [--disable-log-requests] [--max-log-len MAX_LOG_LEN]
api_server.py: error: unrecognized arguments: --api-key token-temp

```

**Comment by iFe1er** [comment]
If I start api_server.py without api-key argument, the server can successfully run, but curl the url would raise problem:

NFO 03-27 12:20:51 model_runner.py:756] Graph capturing finished in 5 secs.
INFO:     Started server process [26019]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:42104 - "GET /v1/models HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:42112 - "GET /v1/models HTTP/1.1" 404 Not Found

![image](https://github.com/vllm-project/vllm/assets/15727394/83da6bd5-4ab6-4963-ac16-ff6469e48916)

**Comment by iFe1er** [comment]
could any one can help me with this problem?
@simon-mo @njhill

**Comment by mwbyeon** [comment]
It looks like you want to run the OpenAI API.
Try run with `python -m vllm.entrypoints.openai.api_server `

https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-server

**Comment by simon-mo** [comment]
Right this is not supported in demo api server. Please use OpenAI version for production usage.
