### ISSUE TITLE
[New Model]: Supporting DBRX from Databricks

### ISSUE THREAD

**Issue by aliozts** [vllm-project/vllm#3658]
### The model to consider.

Databricks has released [DBRX](https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm), which consists of 2 models

- [dbrx](https://huggingface.co/databricks/dbrx-base)
- [dbrx-instruct](https://huggingface.co/databricks/dbrx-instruct)

It's a 132B parameter MoE model. Might be useful.

### What's your difficulty of supporting the model you want?

It seems that they have a custom script in their files, might need custom implementation on that regard.

**Comment by dskhudia** [comment]
We just added a PR: https://github.com/vllm-project/vllm/pull/3660 Thanks @megha95 !
