### ISSUE TITLE
[Usage]: Cannot access /v1 endpoint (404, "detail not found")

### ISSUE THREAD

**Issue by nkumar248** [vllm-project/vllm#3663]
I want to run inference using mixtral8x7b (https://huggingface.co/mistralai/Mixtral-8x7B-v0.1) using vllm's openai-compatible api server. 

I started a server like this: 
python -m vllm.entrypoints.api_server --port 5950 --model mistralai/Mixtral-8x7B-Instruct-v0.1 --tensor-parallel-size 4

This works fine:
curl http://localhost:5950/docs 

This returns a 404 error, can't seem to find the endpoint v1 even though this is the example from the vllm quickstart guide: 
curl http://localhost:5950/v1/models

Has anyone encountered an issue like this?

**Comment by mwbyeon** [comment]
Try run with python -m vllm.entrypoints.openai.api_server 

https://docs.vllm.ai/en/latest/getting_started/quickstart.html#openai-compatible-server
