### ISSUE TITLE
[Misc]: Implement CPU/GPU swapping in BlockManagerV2

### ISSUE THREAD

**Issue by cadedaniel** [vllm-project/vllm#3666]
Recently, we refactored the block manager subsystem to improve testability by separating concerns of each layer. See https://github.com/vllm-project/vllm/pull/3492 for more information.

The V2 implementation does not have support for CPU-GPU swapping. It can be added in the [CpuGpuBlockAllocator](https://github.com/vllm-project/vllm/blob/321dc1619ad60b6df74fa86ac6299bc83c223996/vllm/core/block/cpu_gpu_block_allocator.py). My first take on the design is that it should simply keep track of the requested swap requests and have the scheduler `get_and_clear` them after each scheduling step.

![image](https://github.com/vllm-project/vllm/assets/950914/55cf0db2-2614-463b-a053-eb3f182c01bb)

**Comment by Kaiyang-Chen** [comment]
I would like to have a try on this!

**Comment by cadedaniel** [comment]
> I would like to have a try on this!

That would be great! Let me know if I can answer any questions

**Comment by foreverpiano** [comment]
@cadedaniel  Hi, does the block manager v2 support cpu-gpu offloading now?

**Comment by KuntaiDu** [comment]
I can also help! Let me take a look at the example code and `BlockSpaceManager` first.
