### ISSUE TITLE
[Misc]: Prefix caching in the BlockManagerV2

### ISSUE THREAD

**Issue by cadedaniel** [vllm-project/vllm#3667]
Recently, we refactored the block manager subsystem to improve testability by separating concerns of each layer. See https://github.com/vllm-project/vllm/pull/3492 for more information.

The following features are missing to support prefix caching:
* Eviction policies based on last access time
* Eviction policies based on length of prefix (necessary for correctness as our prefix caching attention only supports contiguous prefixes)
* Tracking the `computed` bit in prefix caching
* E2E correctness test comparing greedy generation equality with prefix caching vs. without prefix caching (see [this test](https://github.com/vllm-project/vllm/blob/321dc1619ad60b6df74fa86ac6299bc83c223996/tests/core/block/e2e/test_correctness.py) for inspiration, which compares greedy generation equality between v1 and v2 block managers)
* Performance profiling of v2 + prefix caching

For design, https://github.com/vllm-project/vllm/pull/3492 has more details (also feel free to reach out to me). One key is to understand how prefix caching promotion works in the new design:
![image](https://github.com/vllm-project/vllm/assets/950914/51003476-6eff-4cf2-8e89-ea473a56e6a0)

**Comment by rkooo567** [comment]
QQ: So the new block manager will be used just for spec decoding until these features will be available?

**Comment by cadedaniel** [comment]
prefix caching is blocked on these features, non-prefix caching usage is blocked by https://github.com/vllm-project/vllm/issues/3666 and https://github.com/vllm-project/vllm/issues/3665

**Comment by robertgshaw2-neuralmagic** [comment]
@SageMoore taking a look
