### ISSUE TITLE
[CI] Use Skypilot to launch model test in runpod for A100 access

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#3674]
### Anything you want to discuss about vllm.

Current we do not run model test on A100 machine because we can't get any capacity in GCP. https://skypilot.readthedocs.io/ supports runpod and we happen to have account there. 

This task requires some infra fiddling but to start, demonstrating a way to use skypilot to run the test container images (they are public) would be useful.

**Comment by richardliaw** [comment]
fascinating
