### ISSUE TITLE
[Bug]: Automatic Prefix Caching doesn't support Nvidia Turing Arch.

### ISSUE THREAD

**Issue by esmeetu** [vllm-project/vllm#3687]
### 🐛 Describe the bug

`triton==2.1.0` doesn't support Turing arch, and has been fixed in https://github.com/openai/triton/pull/2364
Upgrade to `triton==2.2.0` will resolve this issue.

Perhaps this could be planned after #3442.

**Comment by matthieu637** [comment]
Don't you have the #2729 error even with triton 2.2.0?

**Comment by esmeetu** [comment]
> Don't you have the #2729 error even with triton 2.2.0? 

No. And current latest version has updated torch to 2.2.1 with triton 2.2.0 support, this issue was resolved.
