### ISSUE TITLE
[New Model]: Jamba (MoE Mamba from AI21)

### ISSUE THREAD

**Issue by creatorrr** [vllm-project/vllm#3690]
### The model to consider.

https://huggingface.co/ai21labs/Jamba-v0.1

### What's your difficulty of supporting the model you want?

Jamba is a new model and interesting hybrid architecture MoE Mamba model that look very promising. 

https://www.ai21.com/blog/announcing-jamba

**Comment by Playerrrrr** [comment]
pretty please

**Comment by drewskidang** [comment]
Plsss

**Comment by creatorrr** [comment]
[Jamba](https://huggingface.co/ai21labs/Jamba-v0.1) is a really interesting model. It’s an MoE+Transformer+Mamba hybrid so I’m not sure how that would work with vllm. I’d love to add support for it.

thoughts / pointers? @WoosukKwon @zhuohan123

**Comment by mzusman** [comment]
#4115

**Comment by DarkLight1337** [comment]
Closedas completed by #4115.
