### ISSUE TITLE
Can I transform an existing Model into LLM?

### ISSUE THREAD

**Issue by KimmiShi** [vllm-project/vllm#370]
I have an modified model from `LlamaForCausalLM`, when I use `LLM(name=path/to/state_dict)` I came into problems like loading state_dict.

I wonder If we can transform an exisiting model into LLM, which will help a lot such cases!

**Comment by zhuohan123** [comment]
Hi @KimmiShi! Thank you for your interest in porting models into vLLM. You can check this guide to add your own model: https://vllm.readthedocs.io/en/latest/models/adding_model.html

**Comment by KimmiShi** [comment]
Thanks~
