### ISSUE TITLE
[Bug]: logprobs=0 behavior inconsistent with OpenAI spec

### ISSUE THREAD

**Issue by maddiedawson** [vllm-project/vllm#3707]
### Your current environment

vLLM 0.3.3

### 🐛 Describe the bug

I'm using AsyncLlmEngine with vLLM 0.3.3 to serve OpenAI-compatible chat and completions endpoints. I noticed that there are some discrepancies between vLLM's and OpenAI's logprobs behavior. For example, providing logprobs=0 to SamplingParams causes `generate` to return `None` in its output logprobs, whereas OpenAI returns logprobs for the sampled tokens:

```
response = openai.Completion.create(
      engine="gpt-3.5-turbo-instruct",
      prompt="Translate the following English text to French: 'Hello, world!'",
      temperature=0.7,
      max_tokens=60,
      logprobs=0
    )
...
{
  "id": "cmpl-97v6aQwrliFerfnhQKh1NwnO43Uup",
  "object": "text_completion",
  "created": 1711674836,
  "model": "gpt-3.5-turbo-instruct",
  "choices": [
    {
      "text": "\n\nBonjour, monde !",
      "index": 0,
      "logprobs": {
        "tokens": [
          "\n\n",
          "Bonjour",
          ",",
          " monde",
          " !"
        ],
        "token_logprobs": [
          -0.16840062,
          -0.5103194,
          -0.010852911,
          -0.19059794,
          -0.48192957
        ],
        "top_logprobs": null,
        "text_offset": [
          63,
          65,
          72,
          73,
          79
        ]
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 13,
    "completion_tokens": 5,
    "total_tokens": 18
  }
}
```

The vLLM documentation https://docs.vllm.ai/en/latest/dev/sampling_params.html claims to also have this behavior but it does not.

**Comment by esmeetu** [comment]
Hi @maddiedawson. Could you try apply changes in #3731 ?

**Comment by maddiedawson** [comment]
We have a workaround for now (set logprobs to 1) but we can remove it once this makes it into a vLLM release :)
