### ISSUE TITLE
[Usage]: Model Qwen2ForCausalLM does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github

### ISSUE THREAD

**Issue by jcxcer** [vllm-project/vllm#3709]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by jcxcer** [comment]
vllm==0.3.3

**Comment by jeejeelee** [comment]
refer to:https://github.com/vllm-project/vllm/issues/3543
