### ISSUE TITLE
is it possible to use MPT-30B-instruct with the MPT integration?

### ISSUE THREAD

**Issue by paulovasconcellos-hotmart** [vllm-project/vllm#371]
Hi everyone. First of all, thank you for adding MPT as a supported model.

I was wondering how flexible it is to add mpt-30B-instruct to be used **for inference**, instead of vanilla MPT-30b. Do you have any guidelines to help with that?

**Comment by MotzWanted** [comment]
@paulovasconcellos-hotmart I have tested the mpt-30B-instruct on a few medical benchmarks and I experience no issue. Just follow the recommended prompt formatting:
```
def format_prompt(instruction):
    template = "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n###Instruction\n{instruction}\n\n### Response\n"
    return template.format(instruction=instruction)

example = "Tell me a funny joke.\nDon't make it too funny though."
fmt_ex = format_prompt(instruction=example)
```
