### ISSUE TITLE
[Usage]: vllm can host offline? with internet connection?

### ISSUE THREAD

**Issue by juud79** [vllm-project/vllm#3719]
### Your current environment

python3 python -m vllm.entrypoints.api_server --model TheBloke/CodeLlama-7B-Python-AWQ --quantization awq

### How would you like to use vllm

I want to host offline envirment.

python3 python -m vllm.entrypoints.api_server --model TheBloke/CodeLlama-7B-Python-AWQ --quantization awq

but there is an error

**Comment by juud79** [comment]
huggingface_hub.utils._http.OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/bigcode/starcoder: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.

I already set HF_HUB_OFFLINE=1

**Comment by njhill** [comment]
@juud79 we're working on https://github.com/vllm-project/vllm/pull/3125 to address this. You can work around this by passing the explicit path to the model in your local HF cache as the model name.

**Comment by fgebhart** [comment]
Any updated on this? I am running into the same issue and see the mentioned PR being closed and not merged.
