### ISSUE TITLE
[Installation]: Could you please upload the newest docker version to support the lora load of Qwen?

### ISSUE THREAD

**Issue by starmemda** [vllm-project/vllm#3726]
### Your current environment

When I build by:
pip install -e .
I encountered the below question:
ninja: error: unknown target '_punica_c'

**Comment by jeejeelee** [comment]
try:
```shell
VLLM_INSTALL_PUNICA_KERNELS=1 pip install -e .
```

**Comment by youkaichao** [comment]
@starmemda what GPU model are you using? Can you paste your environment info by running https://github.com/vllm-project/vllm/blob/main/collect_env.py ?
