### ISSUE TITLE
[Misc]: Cohere models are not working due to transformers library outdated?

### ISSUE THREAD

**Issue by Playerrrrr** [vllm-project/vllm#3728]
### Anything you want to discuss about vllm.

Got error
---
ValueError: The checkpoint you are trying to load has model type `cohere` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

**Comment by hliuca** [comment]
use 4.39.1?

**Comment by ganeshkamath89** [comment]
I am getting error with 4.40.0, is it expected then?

**Comment by Vindhya-Singh** [comment]
Is there any solution to this? I get the following error: 
`ModuleNotFoundError: No module named 'transformers.models.cohere.configuration_cohere'`
My import statement reads as:
`from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    HfArgumentParser,
    TrainingArguments,
    pipeline,
    logging,
)`


`
model_name = "Orkhan/llama-2-7b-absa"
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    low_cpu_mem_usage=True,
    return_dict=True,
    torch_dtype=torch.float16,
    device_map={"": 0},
)`

**Comment by senthilscouser** [comment]
Getting the same Import error, i checked transformer==40.2.0 but there was 'transformers.configuration_cohere' but i could not find 'transformers.models.cohere.configuration_cohere'

**Comment by senthilscouser** [comment]
> use 4.39.1?

no use, tried using it

**Comment by sriramanush105** [comment]
using transformers version 4.39.1  resolved the error for me
