### ISSUE TITLE
request for Pytorch 2.2

### ISSUE THREAD

**Issue by brando90** [vllm-project/vllm#3742]
### 🚀 The feature, motivation and pitch

Pytorch 2.2

### Alternatives

Pytorch 2.1

### Additional context

Pytorch 2.2 is the fasted twice as fast with flash attention :D

motivated by discussion here: https://github.com/vllm-project/vllm/issues/2747

**Comment by youkaichao** [comment]
Hi, thanks for your interest. `vllm` integrates falsh attention itself, which is faster than pytorch's integration. Actually, when we try to upgrade to pytorch 2.2.0, its dependency on `nccl==2.19.3` makes performance worse. See https://github.com/NVIDIA/nccl/issues/1234 for details.

We are trying to figure out a way to upgrade to pytorch 2.2.0, and of course we won't stop in a pytorch version. Stay tuned!

**Comment by brando90** [comment]
https://github.com/vllm-project/vllm/issues/2747#issuecomment-2044061735

**Comment by brando90** [comment]
dspy vllm pytorch versions clash https://github.com/stanfordnlp/dspy/discussions/818

**Comment by brando90** [comment]
https://stackoverflow.com/questions/78331842/how-to-install-pip-install-torch-2-1-2cu118-in-linux
