### ISSUE TITLE
[Feature] Return attention_map for tokens

### ISSUE THREAD

**Issue by creatorrr** [vllm-project/vllm#375]
@zhuohan123 I have a use case where we utilize the attention map of the tokens in the prompt to decide whether to evict a section from the prompt if it’s running out of context length. It’s relatively easy to do with transformers and PyTorch but it’d be nice to get it from vllm too.

I can take a crack at implementing it too.

**Comment by creatorrr** [comment]
@WoosukKwon Where can I start if I tried to implement this?

**Comment by zhuohan123** [comment]
I'm not sure whether this is actually doable with modern fast attention implementations (e.g., FlashAttention). These implementations avoid storing the full attention map to reduce the O(n^2) memory usage for the attention map. @WoosukKwon WDYT?

**Comment by creatorrr** [comment]
Oh right. Crap.

Umm, is it possible then to optionally disable flash attention in certain situations?

**Comment by creatorrr** [comment]
Closing this as out of scope
