### ISSUE TITLE
[Feature]: Realistic benchmark command

### ISSUE THREAD

**Issue by sshleifer** [vllm-project/vllm#3755]
### 🚀 The feature, motivation and pitch

the hi hi hi prompt here is not realistic.
so 
```
CUDA_VISIBLE_DEVICES=0,1 python benchmarks/benchmark_throughput.py --model meta-llama/Llama-2-70b-hf --tensor-parallel-size=2 --input-len=4094 --output-len=128  --enable-prefix-caching --max-model-len=4096
```
gets a perfect cache hit every time and 12 QPS.

Is there a command to benchmark with more realistic dialogues?

**Comment by hmellor** [comment]
Try `benchmarks/benchmark_serving.py`, this gets its prompts from a dataset.
