### ISSUE TITLE
[New Model]: CohereForAI/c4ai-command-r-v01-4bit

### ISSUE THREAD

**Issue by Playerrrrr** [vllm-project/vllm#3756]
### The model to consider.

[[https://huggingface.co/openai-community/](https://huggingface.co/CohereForAI/c4ai-command-r-v01-4bit](https://huggingface.co/CohereForAI/c4ai-command-r-v01-4bit)

### The closest model vllm already supports.

https://huggingface.co/CohereForAI/c4ai-command-r-v01

### What's your difficulty of supporting the model you want?

No idea if vLLM supports this type of quantization, but if its possible would be eternally grateful for the model support, as one will become able to run it even on weaker setups.

**Comment by qeternity** [comment]
This is using bitsandbytes...not really sure why you'd want to run this in production.

**Comment by dionren** [comment]
> This is using bitsandbytes...not really sure why you'd want to run this in production.

Hi, any problem using bitsandbytes in production?  Can u explain in detail so we can avoid pitfalls.

**Comment by hmellor** [comment]
Command-R is already supported and vLLM supports various quantisation schemes [GPTQ](https://arxiv.org/abs/2210.17323), [AWQ](https://arxiv.org/abs/2306.00978), [SqueezeLLM](https://arxiv.org/abs/2306.07629).

If you need bitsandbytes support, there is already a request for this in #4033
