### ISSUE TITLE
TTFT in openllm with vllm backend VS vllm 

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#3759]
### Your current environment

I have the following two setups, and I am using the benchmark_serving.py to check the ttft for the same request of fixed length.

1. First setup: Openllm with vllm backend
* ` vllm version :'0.2.7'`
* I print the chunk if the ttft condition is meet: 
 * `chunk:  b'data: {"choices":[{"index":0,"delta":{"role":"assistant","content":null},"finish_reason":null}],"model":"MYMODEL","object":"chat.completion.chunk","id":"chatcmpl-4857ac5939864d449af8fbfc9e6e0bc7","created":18869,"usage":null}\n' `

2. Second setup: VLLM service with fastapi
* ` vllm version :'0.3.0'`
* I print the chunk when ttft is occurred in the benchmark script:
 * chunk:  `b'data: {"id":"cmpl-97ed2be2dbf24d8b9a6555be25e24bc6","object":"chat.completion.chunk","created":19140,"model":"path/to/mymodel","choices":[{"index":0,"delta":{"role":"assistant"},"finish_reason":null}]}\n'`
 

I was surprized that the output length of the generated text, TPOT, latency all are the same, but there is gap between two TTFT in both setups!!!

* Openllm with vllm backend: TTFT is 0.005 
* VLLM service:  TTFT is 0.214

Why is this difference? what config should be play role in TTFT? or maybe the different version of VLLM has something to do here?

### 🐛 Describe the bug

I am using `--backend openai-chat` for the benchmark_serving.py

**Comment by hahmad2008** [comment]
@rkooo567  could you please check?

**Comment by ywang96** [comment]
@hahmad2008 can you try just using `--backend vllm`? I think the chat completions request function is not checking if the received chunk has a content. I can make a PR to fix that but I would like to make sure this is indeed the issue.

**Comment by hahmad2008** [comment]
@ywang96 actually for vllm, I added the chat completion endpoint, that why I used the openai-chat as they have the same endpoint.

**Comment by hahmad2008** [comment]
@ywang96 and for the content, in both cases there is a content, I print the chunk when the ttft is calculated and it was like this:
`chunk:  b'data: {"choices":[{"index":0,"delta":{"role":"assistant","content":null},"finish_reason":null}],"model":"MYMODEL","object":"chat.completion.chunk","id":"chatcmpl-4857ac5939864d449af8fbfc9e6e0bc7","created":18869,"usage":null}\n' 
`

this chunk is content, is not it?

**Comment by ywang96** [comment]
> @ywang96 and for the content, in both cases there is a content, I print the chunk when the ttft is calculated and it was like this: `chunk: b'data: {"choices":[{"index":0,"delta":{"role":"assistant","content":null},"finish_reason":null}],"model":"MYMODEL","object":"chat.completion.chunk","id":"chatcmpl-4857ac5939864d449af8fbfc9e6e0bc7","created":18869,"usage":null}\n' `
> 
> this chunk is content, is not it?

Nope, in this case you can see the `content` in `"delta":{"role":"assistant","content":null}` is `null`. A quick fix for this is to change this line
https://github.com/vllm-project/vllm/blob/563c1d7ec56aa0f9fdc28720f3517bf9297f5476/benchmarks/backend_request_func.py#L337
to
```
if "content" in data["choices"][0]["delta"] and data["choices"][0]["delta"]["content"]:
```

**Comment by hahmad2008** [comment]
@ywang96 but why in the two setups the ttft is different, although both of them capture the same first chunk where the `"content":null`
