### ISSUE TITLE
how to use vicuna-v1.3  model in vllm

### ISSUE THREAD

**Issue by lijianxing123** [vllm-project/vllm#376]
Hi，I would like to ask how to set the parameters of the vicuna-1.3 model or can you give me a running example, my model text output is wrong. Thanks

**Comment by lijianxing123** [comment]
my example code is :
from vllm import LLM, SamplingParams
# Sample prompts.
prompts = [
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=1.0, top_p=0.9)

# Create an LLM.
llm = LLM(model="lmsys/vicuna-7b-v1.3")
# Generate texts from the prompts. The output is a list of RequestOutput objects
# that contain the prompt, generated text, and other information.
outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

**Comment by lijianxing123** [comment]
Here is my code:
```python
from vllm import LLM, SamplingParams
# Sample prompts.
prompts = [
    #"Hello, my name is",
    #"The president of the United States is",
    #"The capital of France is",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=1.0, top_p=0.9)

# Create an LLM.
llm = LLM(model="lmsys/vicuna-7b-v1.3")
# Generate texts from the prompts. The output is a list of RequestOutput objects
# that contain the prompt, generated text, and other information.
outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

**Comment by lijianxing123** [comment]
the result is:
Prompt: 'The future of AI is', Generated text: "bright, but it'<s> Here's What You Need to Know About Comey's Surprise Announcement\nFormer FBI Director James Comey is breaking his silence. After months of silence, Comey has agreed to testify before the Senate Intelligence Committee next week. Comey was fired by President Trump in May, and his departure has been a source of controversy ever since.</s>"

**Comment by gesanqiu** [comment]
The prompt of Vicuna should be like this:

> A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {Your prompt here} ASSISTANT:

**Comment by lijianxing123** [comment]
> The prompt of Vicuna should be like this:
> 
> > A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {Your prompt here} ASSISTANT:

Can you give me a example code,Thanks

**Comment by lijianxing123** [comment]
@gesanqiu

**Comment by gesanqiu** [comment]
@lijianxing123 You can try Vicuna-7B-v1.3 by /v1/chat/completions in the vllm/vllm/entrypoints/openai/api_server.py, it used conversation template from FastChat, which will handle the prompt template. The request looks like following:
```
curl --location 'http://127.0.0.1:8012/v1/chat/completions' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "model": "vicuna",
    "stream": true,
    "messages":[
        {
            "role": "user",
            "content": "The future of AI is"
        }
    ],
    "max_tokens": 512,
    "n": 2,
    "use_beam_search": true,
    "temperature": 0
}
'
```
BTW, for your case, your prompt should be:
> A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: The future of AI is ASSISTANT:

**Comment by zhuohan123** [comment]
Huge thanks to @gesanqiu for addressing this issue! Feel free to reopen the issue if you have more questions.

**Comment by schnurromafia** [comment]
> curl --location 'http://127.0.0.1:8012/v1/chat/completions' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "model": "vicuna",
    "stream": true,
    "messages":[
        {
            "role": "user",
            "content": "The future of AI is"
        }
    ],
    "max_tokens": 512,
    "n": 2,
    "use_beam_search": true,
    "temperature": 0
}

@gesanqiu this gives me: "{"object":"error","message":"The model `vicuna` does not exist.","type":"invalid_request_error","param":null,"code":null}"

Docstring of /v1/models endpoint reads "Show available models. Right now we only have one model."
