### ISSUE TITLE
[Bug]: vllm-0.4.0 is much slower than vllm-0.3.3

### ISSUE THREAD

**Issue by StevenZHB** [vllm-project/vllm#3779]
### Your current environment

Traceback (most recent call last):
  File "/zhanghongbo/collect_env.py", line 719, in <module>
    main()
  File "/zhanghongbo/collect_env.py", line 698, in main
    output = get_pretty_env_info()
  File "/zhanghongbo/collect_env.py", line 693, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/zhanghongbo/collect_env.py", line 530, in get_env_info
    vllm_version = get_vllm_version()
  File "/zhanghongbo/collect_env.py", line 262, in get_vllm_version
    return vllm.__version__
AttributeError: module 'vllm' has no attribute '__version__'

I encountered the above issue, so I commented out a line of code.

PyTorch version: 2.1.2+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB

Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         800.000
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       3 MiB
L1i cache:                       2 MiB
L2 cache:                        80 MiB
L3 cache:                        96 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; Load fences, usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 invpcid_single intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq md_clear pconfig spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnxruntime==1.16.0
[pip3] torch==2.1.2+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.1.2+cu118
[pip3] torchvision==0.16.2+cu118
[pip3] triton==2.1.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     2.1.2+cu118              pypi_0    pypi
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchaudio                2.1.2+cu118              pypi_0    pypi
[conda] torchvision               0.16.2+cu118             pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.0+cuda11.8
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    NIC0    CPU Affinity    NUMA Affinity
GPU0     X      NV12    NV12    NODE    0-31,64-95      0
GPU1    NV12     X      NV12    PXB     0-31,64-95      0
GPU2    NV12    NV12     X      SYS     32-63,96-127    1
NIC0    NODE    PXB     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0

### 🐛 Describe the bug

Hello, I found that when running the same code to generate the same number of responses, the speed of vllm 0.3.3 is four times faster than vllm-0.4.0.

At the same time, I also discovered that after generating responses for a period of time, the speed of vllm-0.3.3 starts to slow down. I'm not sure what is causing this issue.

vllm-0.4.0:
<img width="735" alt="image" src="https://github.com/vllm-project/vllm/assets/34183206/61b03dd9-e54b-4552-8c73-936cfa380204">
vllm-0.3.3:
<img width="732" alt="image" src="https://github.com/vllm-project/vllm/assets/34183206/cbf8a474-be0b-40d7-bfbb-4cffa7ce2004">
My code is as below:
```
model_path = '/pretrained_models/Yi-34B-Chat'
sampling_params = SamplingParams(temperature=0.0, top_p=1.0, max_tokens=1,logprobs=tokenizer.vocab_size)
llm = LLM(model=model_path,enforce_eager=True,
          max_logprobs = tokenizer.vocab_size
          )
output_list = llm.generate(input_list,sampling_params,use_tqdm=True)
```

**Comment by youkaichao** [comment]
How do you install `vllm`? Can you check if your code contains this fix https://github.com/vllm-project/vllm/pull/3741 ?

**Comment by StevenZHB** [comment]
> How do you install `vllm`? Can you check if your code contains this fix #3741 ?

Hi, I build vllm0.4.0 from source. vllm0.3.3 is installed  in a new environment by pip.
About  #3741, I used max_logprobs = tokenizer.vocab_size but not len(tokenizer). I'm not sure how to fix  it.

**Comment by youkaichao** [comment]
#3741 should be included in v0.4.0 . If you use `max_logprobs = tokenizer.vocab_size` , you may hit the bug similar in #3741 . You can try the following fix:

```diff
     tokenizer_len = len(tokenizer)
+    tokenizer_vocab_size = tokenizer.vocab_size
  
      class CachedTokenizer(tokenizer.__class__):
 
          @property
          def all_special_ids(self):
              return tokenizer_all_special_ids
 
+        @property
+        def vocab_size(self):
+            return tokenizer_vocab_size
 
          @property
          def all_special_tokens(self):
              return tokenizer_all_special_tokens
 
          @property
          def all_special_tokens_extended(self):
              return tokenizer_all_special_tokens_extended
 
          def __len__(self):
              return tokenizer_len

```

**Comment by StevenZHB** [comment]
> #3741 should be included in v0.4.0 . If you use `max_logprobs = tokenizer.vocab_size` , you may hit the bug similar in #3741 . You can try the following fix:
> 
> ```diff
>      tokenizer_len = len(tokenizer)
> +    tokenizer_vocab_size = tokenizer.vocab_size
>   
>       class CachedTokenizer(tokenizer.__class__):
>  
>           @property
>           def all_special_ids(self):
>               return tokenizer_all_special_ids
>  
> +        @property
> +        def vocab_size(self):
> +            return tokenizer_vocab_size
>  
>           @property
>           def all_special_tokens(self):
>               return tokenizer_all_special_tokens
>  
>           @property
>           def all_special_tokens_extended(self):
>               return tokenizer_all_special_tokens_extended
>  
>           def __len__(self):
>               return tokenizer_len
> ```

Hello, thank you very much for your reply. I tried the method you suggested, but the speed did not improve. Even when I directly use the code:
···llm = LLM(model=model_path, enforce_eager=True, max_logprobs=64000)
···
there is no change in speed. Additionally, the tokenizer I used previously in tokenizer.vocab_size is directly loaded using AutoTokenizer.

**Comment by youkaichao** [comment]
Then it is because your `tokenizer.vocab_size` is not cached. You need to cache it yourself, or like you did, just pass a plain number since you know the size: `LLM(model=model_path, enforce_eager=True, max_logprobs=64000)` .

**Comment by StevenZHB** [comment]
> max_logprobs=64000

Yes, I used the following code:
···
model_path = '/pretrained_models/Yi-34B-Chat'
tokenizer = AutoTokenizer.from_pretrained(model_path)
llm = LLM(model=model_path,enforce_eager=True,
          max_logprobs = 64000
          )
sampling_params = SamplingParams(temperature=0.0, top_p=1.0, max_tokens=1,logprobs=64000)
output_list = llm.generate(input_list,sampling_params,use_tqdm=True)

···
However, the speed remained unchanged.
<img width="816" alt="image" src="https://github.com/vllm-project/vllm/assets/34183206/e638459e-c5a5-44c4-9788-b29a460e7acb">

**Comment by youkaichao** [comment]
Did you try v0.4.0 without setting `max_logprobs`?

**Comment by youkaichao** [comment]
Did you mean you want `64000` logprobs for each token?

**Comment by StevenZHB** [comment]
According to your suggestion, the speed returns to normal when not using max_logprobs.
Yes, I would like to extract the log probability of a specific token. Are there any alternative methods to achieve this?

**Comment by youkaichao** [comment]
I don't think people need `64000` logprobs for each token. For example, in openai api, https://platform.openai.com/docs/api-reference/chat/object , they just return logprobs for top 20 most likely tokens, and the rest is filled with -9999.0 .

That is because, for each next token, there are only handful of possible choices. Definitely not possible to have 64000 choices.

**Comment by StevenZHB** [comment]
Thank you very much for your explanation. In version 0.3.3, this implementation did not have any speed issues, but this problem emerged in version 0.4.0.

During self-rag, we need to obtain the log probability of special tokens, but we don't know the position of these tokens. For example, consider the implementation in the following code:

https://github.com/AkariAsai/self-rag/blob/1fcdc420e48f50a7d7ab1ece5494221b93252e99/retrieval_lm/run_short_form.py#L89

**Comment by youkaichao** [comment]
Your implementation is very inefficient. You can only request, say, e.g. `max_logprobs=20` logprobs, and if your specific token is not in the returned list, it is safe to assume its logprob is some pre-defined small value like `-9999.0` .

You can also verify it yourself, when you request `max_logprobs=64000`, you can check if the logprobs other than top 20 are very small and close to each other.

**Comment by StevenZHB** [comment]
In my implementation (including the mentioned self-rag implementation), I need to compare the probabilities of two tokens. Even if the probabilities are very small, we still need to obtain them and make comparisons to determine which one is larger.

**Comment by njhill** [comment]
@StevenZHB just send in multiple copies of your input with a different special token appended to each (i.e. one for each token that you want to compare the probability of). Then set max_tokens to 0 or 1, no need to set `logprobs`, but set `prompt_logprobs=1`. You'll get the logprob of each of your tokens.

**Comment by tarun360** [comment]
I am also noticing a similar problen with 0.9.1 vllm.

If I set max_logprobs as 256, output throughput becomes very less. 

@StevenZHB did you find a fix?

**Comment by nataxcan** [comment]
I would like to add to this, because @youkaichao said "I don't think people need 64000 logprobs for each token.", but for distillation it is in fact important to have all of them (I could provide a citation), and it would be very helpful if vLLM would support doing this fast, as I can't find a fast way to do this with any framework.
