### ISSUE TITLE
[RFC] How do we test and support third-party models

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#3780]
### Anything you want to discuss about vllm.

This RFC solicits the community's comments on how we test and support third-party models.

Ideally, we can test the consistency between the models implemented in `vllm` and in `transformers`. However, apples to apples comparison is not always possible, because many acceleration techniques and faster computation kernels use low-precision floating point computation. Acceleration comes with loss of precision.

Therefore, there are three types of cause for the difference bwteen `vllm` and `transformers`:

1. `vllm`'s intended implementation of new features, e.g. faster computation kernels
2. `vllm`'s implementation bug
3. `transformers`' bc-breaking changes

Currently, we have consistency check for llama in our CI. It is difficult for us to test every supported model in every CI. And people may find bugfix in one model that can break another model, e.g. https://github.com/vllm-project/vllm/pull/3767 .

To release the burden of vllm developers, I think we should only keep a "best-effort" promise on third-party models:
- When users request a new model, a PR from the community comes out to support it. As long as the output is sensible, we can accept the PR and add that new model. Strict consistency with `transformers` implementation is not considered here.
- When users think the implementation of a model contains a bug (that causes nonsense output), they can feel free to propose a PR to fix. As long as the fix is sensible (e.g. clearly explain the rationale), `vllm` can accept it.
- If a fix of existing model `A` affects another model `B` that uses the same model code (e.g. `llama` series and `internlm` series), `vllm` developers will not know untill users from `B` report the break. In that case, users from `B` can send another PR to fix it again, preferably make the fix compatible with model `A` as well.

Basically, **we ask users to keep an eye on the models they care about**. One simple way would be to watch the commit history of the model file they care about. For example, if users want to watch the `vllm` implementation change in `https://huggingface.co/facebook/opt-125m` , then they should watch the commit history of https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/opt.py . It would be better if anyone can create some automatic tools for watching, but manually checking the link every week or so is also fine.

The idea behind this decision is, **if few users care about the model, we don't pay much attention to it, either.**

Disclaimer: the above only applies to code under https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models . For any other code outside of this directory, `vllm` developers will make sure the code works and fix any bugs.

Note: this is an RFC, so comments are welcome. Discussion period is April 1st to April 7th (both inclusive).

**Comment by comaniac** [comment]
I support this strategy. I could imagine very few models would have the issue that the same model code is shared by many different models. Probably only the most popular open source models like Llama would have this issue. In this case we only need to make sure these models are working, but let the stakeholders keep an eye on the variants.

**Comment by simon-mo** [comment]
Can you list the alternative here? I think one alternative is to test all models in vLLM CI to ensure they do work with some sanity check or other types of metrics.

**Comment by youkaichao** [comment]
> one alternative is to test all models in vLLM CI to ensure they do work with some sanity check or other types of metrics.

Is that even possible? We support so many models from 125M to 300+B 👀

**Comment by simon-mo** [comment]
We can probably to up to 192GB for a L4x8 machine, with low enough precision and quantization we might be able to have full coverage.

**Comment by scv119** [comment]
+1 list alternatives such as https://github.com/EleutherAI/lm-evaluation-harness test?

**Comment by youkaichao** [comment]
Progress:

1. We already add doc to state our policy in https://github.com/vllm-project/vllm/pull/3948 .
2. #TODO In the future, when we add perplexity test or [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) test, we can update the section of Output Sensibility.

**Comment by youkaichao** [comment]
close as we have [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) tests now.
