### ISSUE TITLE
vllm-0.4.0.post1+neuron213; ModuleNotFoundError: No module named 'vllm._C' [Bug]: 

### ISSUE THREAD

**Issue by MojHnd** [vllm-project/vllm#3784]
### Your current environment

Collecting environment information...
WARNING 04-02 01:12:23 ray_utils.py:70] Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For distributed inference, please install Ray with `pip install ray`.
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7R13 Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
Stepping:                        1
BogoMIPS:                        5299.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save vaes vpclmulqdq rdpid
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       64 KiB (2 instances)
L1i cache:                       64 KiB (2 instances)
L2 cache:                        1 MiB (2 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.1.2
[pip3] torch-neuronx==2.1.2.2.1.0
[pip3] torch-xla==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collectROCM Version: Could not collect
Neuron SDK Version: (0, 'instance-type: inf2.xlarge\ninstance-id: i-007ed790733de3fad\n+--------+--------+--------+---------+\n| NEURON | NEURON | NEURON |   PCI   |\n| DEVICE | CORES  | MEMORY |   BDF   |\n+--------+--------+--------+---------+\n| 0      | 2      | 32 GB  | 00:1f.0 |\n+--------+--------+--------+---------+', '')
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

### 🐛 Describe the bug

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[7], line 1
----> 1 from vllm import LLM, SamplingParams

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/__init__.py:4
      1 """vLLM: a high-throughput and memory-efficient inference engine for LLMs"""
      3 from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
----> 4 from vllm.engine.async_llm_engine import AsyncLLMEngine
      5 from vllm.engine.llm_engine import LLMEngine
      6 from vllm.engine.ray_utils import initialize_ray_cluster

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py:12
     10 from vllm.config import ModelConfig
     11 from vllm.engine.arg_utils import AsyncEngineArgs
---> 12 from vllm.engine.llm_engine import LLMEngine
     13 from vllm.engine.ray_utils import initialize_ray_cluster, ray
     14 from vllm.logger import init_logger

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/engine/llm_engine.py:16
     14 from vllm.logger import init_logger
     15 from vllm.lora.request import LoRARequest
---> 16 from vllm.model_executor.model_loader import get_architecture_class_name
     17 from vllm.outputs import RequestOutput
     18 from vllm.sampling_params import SamplingParams

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/model_executor/model_loader.py:10
      8 from vllm.config import DeviceConfig, ModelConfig
      9 from vllm.model_executor.models import ModelRegistry
---> 10 from vllm.model_executor.models.llava import LlavaForConditionalGeneration
     11 from vllm.model_executor.weight_utils import (get_quant_config,
     12                                               initialize_dummy_weights)
     14 _VISION_MODEL_CLASSES = [
     15     LlavaForConditionalGeneration,
     16 ]

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/model_executor/models/llava.py:11
      9 from vllm.attention import AttentionMetadata
     10 from vllm.config import VisionLanguageConfig
---> 11 from vllm.model_executor.layers.activation import get_act_fn
     12 from vllm.model_executor.layers.linear import LinearMethodBase
     13 from vllm.model_executor.layers.logits_processor import LogitsProcessor

File ~/aws_neuron_venv_pytorch/lib/python3.10/site-packages/vllm/model_executor/layers/activation.py:9
      6 import torch.nn as nn
      7 import torch.nn.functional as F
----> 9 from vllm._C import ops
     10 from vllm.model_executor.layers.quantization import QuantizationConfig
     11 from vllm.model_executor.parallel_utils.parallel_state import (
     12     get_tensor_model_parallel_rank, get_tensor_model_parallel_world_size)

ModuleNotFoundError: No module named 'vllm._C'

**Comment by MojHnd** [comment]
Solved for me for AWS inf2 instance!

When I download vllm from [source](https://docs.vllm.ai/en/latest/getting_started/neuron-installation.html), 

`git clone https://github.com/vllm-project/vllm.git`

`cd vllm`  **=> change the folder name to vllm_x for example (cd vllm_x). This will solve the problem.**

`pip install -U -r requirements-neuron.txt `  

`pip install .`

**Comment by MojHnd** [comment]
solved!

**Comment by MojHnd** [comment]
vllm-0.4.0.post1+neuron213  

```
File ~/package/vllm_x/vllm/model_executor/layers/activation.py:9
      6 import torch.nn as nn
      7 import torch.nn.functional as F
----> 9 from vllm._C import ops
     10 from vllm.model_executor.layers.quantization import QuantizationConfig
     11 from vllm.model_executor.parallel_utils.parallel_state import (
     12     get_tensor_model_parallel_rank, get_tensor_model_parallel_world_size)

ModuleNotFoundError: No module named 'vllm._C'
```

**Comment by MojHnd** [comment]
I successfully installed `vllm-0.4.0.post1+neuron213`.

In `setup.py`, there is this function:
```
if not _is_neuron():
    ext_modules.append(CMakeExtension(name="vllm._C"))
```
and 
```
cmdclass={"build_ext": cmake_build_ext} if not _is_neuron() else {},
```
So, `vllm._C` won't be created. This results in `ModuleNotFoundError: No module named 'vllm._C'`.

How to fix it?

**Comment by MojHnd** [comment]
I just solved it this way.

The problem is with `# from vllm._C import ops` while there is no `vllm._C`.
We need `ops` that exists in `your_environment_name/lib/python3.10/site-packages/vllm/model_executor/layers/` (see the figure below)
![image](https://github.com/vllm-project/vllm/assets/44735875/9ad2cc10-f986-4962-af2f-9c3c400df16b)

So, what we have to do is to change `from vllm._C import ops` to `from vllm.model_executor.layers import ops` in every single file of the package.
This solves the problem :)

**Comment by qimingyangyang** [comment]
from vllm.model_executor.layers import cache_ops, ops
ImportError: cannot import name 'cache_ops' from 'vllm.model_executor.layers'

**Comment by youkaichao** [comment]
Forward to @liangfu for visibility.

**Comment by WoosukKwon** [comment]
This should be (temporarily) solved by #3770. #3913 will be a more robust fix.

**Comment by martingrzzler** [comment]
I'm still getting the error.

**Comment by dcrockwell** [comment]
Still getting error in latest build
