### ISSUE TITLE
[Feature]: Add OpenTelemetry distributed tracing

### ISSUE THREAD

**Issue by ronensc** [vllm-project/vllm#3789]
### 🚀 The feature, motivation and pitch

This proposal suggests adding distributed tracing with [OepnTelemetry](https://opentelemetry.io/), which will enable operators to export traces in a standard protocol and seamlessly connect them with visualization tools such as [Jaeger](https://www.jaegertracing.io/),  [Zipkin](https://zipkin.io/) and [Instana](https://www.ibm.com/products/instana/opentelemetry)

As an initial implementation, I suggest emitting a trace for each request, including the following data:

* Model name
* Request ID
* Sampling params
* Latency
* Number of input tokens
* Number of generated tokens

This approach will greatly enhance the observability and troubleshooting capabilities of vLLM.
I am willing to work on this and contribute it to the community.
I welcome any feedback or suggestions.

**Comment by gyliu513** [comment]
Hi @ronensc , if you want to contribute, maybe here is a good repo https://github.com/traceloop/openllmetry/tree/main/packages , we already have bunch of LLM providers support here.

FYI @nirga

**Comment by baggiponte** [comment]
@samuelcolvin for logfire!

**Comment by MrMegaMango** [comment]
Hi I am using Opentelemetry traces to crack down slowness in vllm call. Only this llm_request one span comes out with some attributes.
<img width="1358" alt="382470901-de7da1b8-1ae3-466e-a5b4-b042cae8194f" src="https://github.com/user-attachments/assets/93b29fae-acce-4ae3-b2c7-b8abdc674fdb">
It only covers 10% of the time spent after a request to vllm's v1/completion endpoint. No nested span calls.
Presumably the start of vllm_request span comes from seq_group.metrics.arrival_time, why it is seconds later than request to v1/compelete?
