### ISSUE TITLE
[Performance]: Why is it so slow to deploy the model using Ray

### ISSUE THREAD

**Issue by wx971025** [vllm-project/vllm#3790]
### Report of performance regression

![image](https://github.com/vllm-project/vllm/assets/31993091/f8d08c31-c251-495c-8bbd-5e4c583cd9ae)
The two nodes are on the same LAN, so it shouldn't be that slow in theory

**Comment by njhill** [comment]
@wx971025 could you try with https://github.com/vllm-project/vllm/pull/3466 to see whether it's a Ray-specific issue?
