### ISSUE TITLE
[Usage]: Can vllm be used together with tensorRT? Has anyone ever done an example

### ISSUE THREAD

**Issue by hf201429** [vllm-project/vllm#3792]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by jeejeelee** [comment]
Of course, vllm can be used together with TensorRT. But personally, I don't think anyone would do it, If you intend to utilize TensorRT, consider employing TensorRT-LLM instead.

**Comment by hf201429** [comment]
Can you provide a Python example that combines vllm and tensorRT for reference? thanks
