### ISSUE TITLE
[Bug]: FastAPI Swagger /docs does not working correctly

### ISSUE THREAD

**Issue by sciafri** [vllm-project/vllm#3795]
### Your current environment

The latest vLLM docker: vllm/vllm-openai:v0.4.0

Issue seems to exist as far back as 0.2.7.

### 🐛 Describe the bug

Visiting **http://localhost:8080/docs** when running the server offline shows a blank page however loads with the proper title for the page. I haven't yet attempted this with an online / non-firewalled running instance of vLLM.

Inspecting the page with developer tools shows some html, however there are errors in downloading .js files from a cdn so I suspect that is the problem. 

Is there a way to enable support for the Swagger documentation offline? 

Since I'm unable to test, http://localhost:8080/docs properly functioning with online instances?

**Comment by hmellor** [comment]
This doesn't seem to be a vLLM issue
