### ISSUE TITLE
[Bug]: YI:34B在使用上无法停止。

### ISSUE THREAD

**Issue by cat2353050774** [vllm-project/vllm#3797]
### Your current environment

使用VLLM推理Yi:34b,注意不是chat，总是一直重复直到最大token。试了很多种办法，都没有很好的解决方法。有大佬能协助一下吗
![image](https://github.com/vllm-project/vllm/assets/50692992/b7894d6e-df35-42dd-9056-2ce14f6f4c45)
![image](https://github.com/vllm-project/vllm/assets/50692992/c3784dce-e614-42b9-aeaf-56b6ec72caf4)

### 🐛 Describe the bug

使用VLLM推理Yi:34b,注意不是chat，总是一直重复直到最大token。试了很多种办法，都没有很好的解决方法。有大佬能协助一下吗
![image](https://github.com/vllm-project/vllm/assets/50692992/b7894d6e-df35-42dd-9056-2ce14f6f4c45)
![image](https://github.com/vllm-project/vllm/assets/50692992/c3784dce-e614-42b9-aeaf-56b6ec72caf4)

**Comment by huyuan-cn** [comment]
检查一下yi的config文件，我之前用的时候yi里面的endoftext是llama分词符自带的，修改后应该正常的。

**Comment by haijian-wang** [comment]
请问朋友有没有成功解决？
