### ISSUE TITLE
[Installation]: can‘t install with pip install vllm

### ISSUE THREAD

**Issue by albertimff** [vllm-project/vllm#3827]
### Your current environment

```text
The output of `python collect_env.py`
```
![image](https://github.com/vllm-project/vllm/assets/154483517/412bc386-e2db-41af-a160-2b28cee3e05c)

![image](https://github.com/vllm-project/vllm/assets/154483517/c52e48ab-ad8e-457c-8387-49b84de5293d)

### How you are installing vllm

```sh
pip install -vvv vllm
```
![image](https://github.com/vllm-project/vllm/assets/154483517/91c1b0b9-17e5-4c1a-94e4-4e2e5c993280)

![image](https://github.com/vllm-project/vllm/assets/154483517/1f197e93-b78a-49dd-8b1b-3b406af5a69f)

![image](https://github.com/vllm-project/vllm/assets/154483517/2770e9d6-3684-4626-a7b4-16c98b3d7cfe)

![image](https://github.com/vllm-project/vllm/assets/154483517/d6f96a5b-ae05-4439-99bf-2c2686009fc8)

![image](https://github.com/vllm-project/vllm/assets/154483517/1f771b8d-4ed6-4cd7-b471-db4f45c57260)

![image](https://github.com/vllm-project/vllm/assets/154483517/0aa64d21-1e75-4c05-af5d-74a53816a919)

**Comment by mwbyeon** [comment]
CUDA toolkit isn't installed in your environment.

**Comment by youkaichao** [comment]
Windows is not supported, you have to use WSL https://docs.vllm.ai/en/latest/getting_started/installation.html#requirements .

**Comment by xiezhipeng-git** [comment]
@youkaichao Can you add support for Windows instead of WSL? WSL is very unstable and can disconnect from VSCode at any time. This problem persists no matter how it's configured.
