### ISSUE TITLE
[Bug]: no device id found when using vllm 0.4.0

### ISSUE THREAD

**Issue by stikkireddy** [vllm-project/vllm#3828]
### Your current environment

```text
The output of `python collect_env.py`
```
```text
GPU Topology:
GPU0	GPU1	GPU2	GPU3	NIC0	NIC1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV12	SYS	SYS	NODE	NODE	0-23	0		N/A
GPU1	NV12	 X 	SYS	SYS	SYS	SYS	24-47	1		N/A
GPU2	SYS	SYS	 X 	NV12	SYS	SYS	48-71	2		N/A
GPU3	SYS	SYS	NV12	 X 	SYS	SYS	72-95	3		N/A
NIC0	NODE	SYS	SYS	SYS	 X 	NODE				
NIC1	NODE	SYS	SYS	SYS	NODE	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```

### 🐛 Describe the bug

I installed vllm==0.4.0 and I am getting invalid device id.

INFO 04-03 14:21:32 selector.py:21] Using XFormers backend.
(RayWorkerVllm pid=74267) INFO 04-03 14:21:32 selector.py:45] Cannot use FlashAttention because the package is not found. Please install it for better performance.
(RayWorkerVllm pid=74267) INFO 04-03 14:21:32 selector.py:21] Using XFormers backend.
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]   File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2424aae1-472c-43f3-827f-969582bbe73a/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]   File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2424aae1-472c-43f3-827f-969582bbe73a/lib/python3.10/site-packages/vllm/worker/worker.py", line 93, in init_device
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]     _check_if_gpu_supports_dtype(self.model_config.dtype)
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]   File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2424aae1-472c-43f3-827f-969582bbe73a/lib/python3.10/site-packages/vllm/worker/worker.py", line 309, in _check_if_gpu_supports_dtype
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]     compute_capability = torch.cuda.get_device_capability()
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]   File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2424aae1-472c-43f3-827f-969582bbe73a/lib/python3.10/site-packages/torch/cuda/__init__.py", line 435, in get_device_capability
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]     prop = get_device_properties(device)
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]   File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-2424aae1-472c-43f3-827f-969582bbe73a/lib/python3.10/site-packages/torch/cuda/__init__.py", line 452, in get_device_properties
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44]     raise AssertionError("Invalid device id")
(RayWorkerVllm pid=74267) ERROR 04-03 14:21:32 ray_utils.py:44] AssertionError: Invalid device id

**Comment by mgoin** [comment]
Hi @stikkireddy, please try the 0.4.0.post1 hotfix where this issue should be addressed: https://github.com/vllm-project/vllm/releases/tag/v0.4.0.post1

**Comment by stikkireddy** [comment]
hey @mgoin this got me past that error thanks for the prompt response! Any ETA on this making to pypi, right now i am installing via the url.

**Comment by WoosukKwon** [comment]
@stikkireddy We will upload them to PyPI very soon. @youkaichao for visibility.

**Comment by youkaichao** [comment]
Already uploaded at https://pypi.org/project/vllm/0.4.0.post1/#files , please have a try and give your feedback!
