### ISSUE TITLE
[Usage]: 

### ISSUE THREAD

**Issue by reachsantanu** [vllm-project/vllm#3842]
### Your current environment

```text
The output of `python collect_env.py`
```
Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.104.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          256
On-line CPU(s) list:             0-255
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7763 64-Core Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     3529.0520
CPU min MHz:                     1500.0000
BogoMIPS:                        4900.18
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization:                  AMD-V
L1d cache:                       4 MiB (128 instances)
L1i cache:                       4 MiB (128 instances)
L2 cache:                        64 MiB (128 instances)
L3 cache:                        512 MiB (16 instances)
NUMA node(s):                    8
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.2
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collectROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    SYS     PXB     48-63,176-191   3               N/A
GPU1    NV12     X      NV12    NV12    SYS     PXB     48-63,176-191   3               N/A
GPU2    NV12    NV12     X      NV12    SYS     SYS     16-31,144-159   1               N/A
GPU3    NV12    NV12    NV12     X      PXB     SYS     112-127,240-255 7               N/A
NIC0    SYS     SYS     SYS     PXB      X      SYS
NIC1    PXB     PXB     SYS     SYS     SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1

### How would you like to use vllm

getting error since 3rd April 2024
python -u -m vllm.entrypoints.openai.api_server \
       --host 0.0.0.0 \
       --model mistralai/Mixtral-8X7B-Instruct-v0.1 \
       --tensor-parallel-size 4 # adapt to your GPUs \
      --load-format pt # needed since both `pt` and `safetensors` are available
INFO 04-04 05:35:31 api_server.py:149] vLLM API server version 0.4.0.post1
INFO 04-04 05:35:31 api_server.py:150] args: Namespace(host='0.0.0.0', port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='mistralai/Mixtral-8X7B-Instruct-v0.1', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, forced_num_gpu_blocks=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_chunked_prefill=False, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-04-04 05:35:33,307 WARNING utils.py:580 -- Detecting docker specified CPUs. In previous versions of Ray, CPU detection in containers was incorrect. Please ensure that Ray has enough CPUs allocated. As a temporary workaround to revert to the prior behavior, set `RAY_USE_MULTIPROCESSING_CPU_COUNT=1` as an env var before starting Ray. Set the env var: `RAY_DISABLE_DOCKER_CPU_WARNING=1` to mute this warning.
2024-04-04 05:35:33,307 WARNING utils.py:592 -- Ray currently does not support initializing Ray with fractional cpus. Your num_cpus will be truncated from 108.8 to 108.
2024-04-04 05:35:33,524 INFO worker.py:1752 -- Started a local Ray instance.
INFO 04-04 05:35:34 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='mistralai/Mixtral-8X7B-Instruct-v0.1', tokenizer='mistralai/Mixtral-8X7B-Instruct-v0.1', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=4, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
INFO 04-04 05:35:44 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
INFO 04-04 05:35:44 selector.py:25] Using XFormers backend.
(RayWorkerVllm pid=27553) INFO 04-04 05:35:44 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance.
(RayWorkerVllm pid=27553) INFO 04-04 05:35:44 selector.py:25] Using XFormers backend.
INFO 04-04 05:35:45 pynccl_utils.py:45] vLLM is using nccl==2.18.1
(RayWorkerVllm pid=27553) INFO 04-04 05:35:45 pynccl_utils.py:45] vLLM is using nccl==2.18.1
INFO 04-04 05:36:09 weight_utils.py:177] Using model weights format ['*.safetensors']
Exception ignored in: <function BaseFileLock.__del__ at 0x7f0530a48790>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 240, in __del__
    self.release(force=True)
  File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 201, in release
    with self._thread_lock:
AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'
(RayWorkerVllm pid=27553) INFO 04-04 05:36:10 weight_utils.py:177] Using model weights format ['*.safetensors']
(RayWorkerVllm pid=27902) INFO 04-04 05:35:44 selector.py:51] Cannot use FlashAttention because the package is not found. Please install it for better performance. [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorkerVllm pid=27902) INFO 04-04 05:35:44 selector.py:25] Using XFormers backend. [repeated 2x across cluster]
(RayWorkerVllm pid=27902) INFO 04-04 05:35:45 pynccl_utils.py:45] vLLM is using nccl==2.18.1 [repeated 2x across cluster]
(RayWorkerVllm pid=27553) Exception ignored in: <function BaseFileLock.__del__ at 0x7f8a587c91b0>
(RayWorkerVllm pid=27553) Traceback (most recent call last):
(RayWorkerVllm pid=27553)   File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 240, in __del__
(RayWorkerVllm pid=27553)     self.release(force=True)
(RayWorkerVllm pid=27553)   File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 201, in release
(RayWorkerVllm pid=27553)     with self._thread_lock:
(RayWorkerVllm pid=27553) AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 157, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 422, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 62, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 192, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_gpu_executor.py", line 324, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 418, in load_weights
    for name, loaded_weight in hf_model_weights_iterator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 224, in hf_model_weights_iterator
    hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 180, in prepare_hf_model_weights
    with get_lock(model_name_or_path, cache_dir):
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 46, in get_lock
    lock = filelock.FileLock(os.path.join(lock_dir, lock_file_name),
TypeError: BaseFileLock.__init__() got an unexpected keyword argument 'mode'
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44] Error executing method load_model. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 107, in load_model
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     self.model_runner.load_model()
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 95, in load_model
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     self.model = get_model(
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 101, in get_model
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     model.load_weights(model_config.model, model_config.download_dir,
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 418, in load_weights
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     for name, loaded_weight in hf_model_weights_iterator(
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 224, in hf_model_weights_iterator
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights(
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 180, in prepare_hf_model_weights
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     with get_lock(model_name_or_path, cache_dir):
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 46, in get_lock
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44]     lock = filelock.FileLock(os.path.join(lock_dir, lock_file_name),
(RayWorkerVllm pid=27553) ERROR 04-04 05:36:10 ray_utils.py:44] TypeError: BaseFileLock.__init__() got an unexpected keyword argument 'mode'
(RayWorkerVllm pid=27902) INFO 04-04 05:36:10 weight_utils.py:177] Using model weights format ['*.safetensors'] [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44] Error executing method load_model. This might cause deadlock in distributed execution. [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44] Traceback (most recent call last): [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 37, in execute_method [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     return executor(*args, **kwargs) [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py", line 95, in load_model [repeated 4x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     self.model_runner.load_model() [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     self.model = get_model( [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/model_loader.py", line 101, in get_model [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     model.load_weights(model_config.model, model_config.download_dir, [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/mixtral.py", line 418, in load_weights [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     for name, loaded_weight in hf_model_weights_iterator( [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 224, in hf_model_weights_iterator [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     hf_folder, hf_weights_files, use_safetensors = prepare_hf_model_weights( [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 180, in prepare_hf_model_weights [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     with get_lock(model_name_or_path, cache_dir): [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/weight_utils.py", line 46, in get_lock [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44]     lock = filelock.FileLock(os.path.join(lock_dir, lock_file_name), [repeated 2x across cluster]
(RayWorkerVllm pid=27902) ERROR 04-04 05:36:10 ray_utils.py:44] TypeError: BaseFileLock.__init__() got an unexpected keyword argument 'mode' [repeated 2x across cluster]
(RayWorkerVllm pid=27902) Exception ignored in: <function BaseFileLock.__del__ at 0x7faa2ab7d1b0> [repeated 2x across cluster]
(RayWorkerVllm pid=27902) Traceback (most recent call last): [repeated 2x across cluster]
(RayWorkerVllm pid=27902)   File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 240, in __del__ [repeated 2x across cluster]
(RayWorkerVllm pid=27902)     self.release(force=True) [repeated 2x across cluster]
(RayWorkerVllm pid=27902)   File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 201, in release [repeated 2x across cluster]
(RayWorkerVllm pid=27902)     with self._thread_lock: [repeated 2x across cluster]
(RayWorkerVllm pid=27902) AttributeError: 'UnixFileLock' object has no attribute '_thread_lock' [repeated 2x across cluster]
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
-bash: --load-format: command not found #

**Comment by tjohnson31415** [comment]
From what I can see, the main error is:
```
TypeError: BaseFileLock.init() got an unexpected keyword argument 'mode'
```
You might just need to run: `pip install --upgrade filelock`
