### ISSUE TITLE
cuda 12

### ISSUE THREAD

**Issue by patrafter1999** [vllm-project/vllm#385]
Hi Guys,

Thanks heaps for your work. I'm really impressed by the performance.

I'm just curious if you guys have CUDA 12 support on your roadmap? I have just grabbed an A100 instance with CUDA 12.2 installed. I was so excited and realised vLLM supports up to CUDA 11.8.

Thanks!

**Comment by WoosukKwon** [comment]
Hi @patrafter1999, thanks for your interest! Actually, it's because there's no PyTorch wheels pre-built with CUDA 12. vLLM will automatically support CUDA 12 once PyTorch 2.1.0 is released (with CUDA 12 support).

For now, you can install vLLM [inside an NVIDIA PyTorch docker](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#requirements).

**Comment by naed90** [comment]
I was actually able to run it (out of the box) with CUDA 12.2, on an A100 (80GB).

```
(vllm) dean@Main:/$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
(vllm) dean@Main:/mnt/data/vllm$ python benchmarks/benchmark_throughput.py --backend vllm --dataset ./ShareGPT_V3_unfiltered_cleaned_split.json --model openlm-research/open_llama_13b --tokenizer hf-internal-testing/llama-tokenizer
...
Processed prompts: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [04:12<00:00,  3.96it/s]
Throughput: 3.96 requests/s, 1892.94 tokens/s
```

**Comment by tanguofu** [comment]
> I don't understand this answer. Pytorch nightly is already cuda 12.1 with 2.1.0dev with a wheel. but it still triggers an error when installing vllm
> 
> Never mind, it works with `python setup.py develop`

is there some plan to fix this?  thanks.

**Comment by ferrybaltimore** [comment]
2.1 stable is already available

**Comment by LRY89757** [comment]
> 2.1 stable is already available

really? But I can compile the vllm with the cuda 12.1, pytorch 2.1, but I can' t run it correctly, because of it:

![image](https://github.com/vllm-project/vllm/assets/77330637/714d0477-6138-44a6-aa64-e34955bb918f)

**Comment by sxk000** [comment]
CUDA Version: 12.2   ,  it is not work

python setup.py install
Traceback (most recent call last):
  File "/apply/app/vllm/setup.py", line 63, in <module>
    raise RuntimeError(
RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.

python setup.py develop
Traceback (most recent call last):
  File "/apply/app/vllm/setup.py", line 63, in <module>
    raise RuntimeError(
RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.

how to install ?  thanks

**Comment by simon-mo** [comment]
CUDA 12 was supported in recent version.
