### ISSUE TITLE
[Misc]: Can we remove `vllm/entrypoints/api_server.py`?

### ISSUE THREAD

**Issue by hmellor** [vllm-project/vllm#3852]
### Anything you want to discuss about vllm.

While gardening GitHub issues I've seen many issues where the user is using `-m vllm.entrypoints.api_server`, which indicates that users are either not aware of ignoring the note at the top of the file:

https://github.com/vllm-project/vllm/blob/b7782002e1da25de77e0b1890ff8b72dd4df917c/vllm/entrypoints/api_server.py#L1-L7

Can we remove it to avoid future confusion?

**Comment by FlorianJoncour** [comment]
It's probably a good idea.

However, it would probably be better to move it into a subfolder like vllm_example.
On the other hand, I don't think it would be desirable for the OpenAI server to become the only implementation.

It's possible that in the future, it could be useful to create servers implementation of Mistral AI API or Anthropic.

**Comment by hmellor** [comment]
We can leave the openai server where it is so that in future if other proprietary APIs are added they can live adjacent to the openai directory.

**Comment by DarkLight1337** [comment]
There exist outstanding PRs which suggest that there are some bugs in that file.

- #1158
- #3367
- #5187

Yet, #2858 clearly mentions that the file is not supposed to be further updated. @simon-mo what are the reasons behind this? If we want this file to serve as an example, IMO we should at least make sure that it is bug-free.

**Comment by simon-mo** [comment]
We can fix bug. We just shouldn't add more features to keep it with parity for OpenAI compatibility.

**Comment by hmellor** [comment]
Does `vllm/entrypoints/api_server.py` have any OpenAI compatability?

**Comment by DarkLight1337** [comment]
> We can fix bug. We just shouldn't add more features to keep it with parity for OpenAI compatibility.

Perhaps we should move it to `examples` directory as @FlorianJoncour has suggested then.

**Comment by TikZSZ** [comment]
Maybe this could be kept for supporting features in beta/experimental or something that's not covered by open ai api spec.
For example this was the only way I found to just send token ids directly to model instead of chat messages, which is helpful incase when people want to experiment with prompts without limitations. For example mistral v3 function calling which requires custom encoding that isn't covered by chat template.

**Comment by DarkLight1337** [comment]
> > We kept the file there for backward compatibility as some people are still using it.

How long are we planning to maintain this? I think #4197 / #5090 would be a good opportunity to drop it. We can also redirect imports/main to the new location of the file.

**Comment by DarkLight1337** [comment]
> Maybe this could be kept for supporting features in beta/experimental or something that's not covered by open ai api spec.

Correct me if I'm wrong, but it looks like we can't use this file directly to test out those features. If we have to copy this file and modify it elsewhere anyway, I don't see the harm in moving it to the examples and thus adding it to the official documentation.
