### ISSUE TITLE
supporting superhot models?

### ISSUE THREAD

**Issue by bryanhpchiang** [vllm-project/vllm#388]
specifically: 
- https://huggingface.co/kaiokendev/superhot-30b-8k-no-rlhf-test

i've confirmed that i can load the model in vllm and successfully generate completions but the context length is still only 2048.

**Comment by bryanhpchiang** [comment]
looking into it

<img width="696" alt="image" src="https://github.com/vllm-project/vllm/assets/98059440/f196fa81-ce9c-4274-936b-8ebd41aa5ebc">
<img width="663" alt="image" src="https://github.com/vllm-project/vllm/assets/98059440/0c912d74-bfd7-4b50-9401-0b1a9940a556">


not sure where this error is coming from actually. couldn't find it in the codebase
<img width="1653" alt="image" src="https://github.com/vllm-project/vllm/assets/98059440/35146847-27f6-427e-8958-be6f2326568d">

i tried changing this when setting up the llm but didn't help
<img width="243" alt="image" src="https://github.com/vllm-project/vllm/assets/98059440/3b34a9b5-e613-4d98-9761-eed48709c6b2">

**Comment by robertsw22** [comment]
any luck?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
