### ISSUE TITLE
Sample configurations to maximize throughput on typical GPUs

### ISSUE THREAD

**Issue by Luke20000429** [vllm-project/vllm#3885]
### 🚀 The feature, motivation and pitch

I am running the `benchmark_throughput` on A100 with the dataset mentioned in readme. However, from `nvtop`, the GPU utilization is only 20% even if I've set `max_num_batched_tokens=10240, max_num_seqs=1024`. Could you provide some sample configurations for typical GPUs like A100, V100 that can maximize the throughput performance?

**Comment by Atry** [comment]
I think it would be nice to not ask the user to set `max_num_batched_tokens`. See #4044

**Comment by Atry** [comment]
With the flag `--enable-chunked-prefill`, the default `max_num_batched_tokens` 512 is already optimized for ITL.

See https://github.com/vllm-project/vllm/blob/7585ec996f7ec88735627cb2ab13949226f9bfce/docs/source/models/performance.rst#chunked-prefill
