### ISSUE TITLE
[Bug]: Error When Using quantized Jais on Specific Layers with vLLM (GPTQ is used for quantization)

### ISSUE THREAD

**Issue by Mohammad-Faris** [vllm-project/vllm#3886]
### Your current environment

Hello everyone, I need some help here, please. I tried to quantize the JAIS model using GPTQ. Here is my code:

```
from auto_gptq.modeling._base import BaseGPTQForCausalLM
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
import auto_gptq
from transformers import AutoModel, AutoTokenizer 



# define model
auto_gptq.modeling._base.SUPPORTED_MODELS = ["jais"]
    
class JAISLMHeadModelGPTQ(BaseGPTQForCausalLM):
    layer_type = "JAISBlock"
    layers_block_name = "transformer.h"
    outside_layer_modules = ["transformer.ln_f", "transformer.relative_pe", "transformer.wte"]
    inside_layer_modules = [
        ["attn.c_attn"],
#         ["attn.c_proj"],
#         ["mlp.c_fc", "mlp.c_fc2"],
#         ["mlp.c_proj"],
    ]

    
quantized_model_dir = "/sdb-disk/LlmsModels/jais-13b-chat-4bit"
# load quantized model to the first GPU

tokenizer = AutoTokenizer.from_pretrained(quantized_model_dir, use_fast=True, trust_remote_code=True)

model = JAISLMHeadModelGPTQ.from_quantized(quantized_model_dir, 
                                           device="cuda:0", 
                                           trust_remote_code=True,
                                          )

# download quantized model from Hugging Face Hub and load to the first GPU
# model = AutoGPTQForCausalLM.from_quantized(repo_id, device="cuda:0", use_safetensors=True, use_triton=False)

# inference with model.generate
print(tokenizer.decode(model.generate(**tokenizer("my name is", return_tensors="pt").to(model.device))[0]))
```

You can see that I commented out these modules: attn.c_proj, mlp.c_fc, mlp.c_fc2, mlp.c_proj, because they do not have input features divisible by 32, which raises an error during quantization - **AssertionError**.

```
File /sdb-disk/AutoGPTQ/auto_gptq/nn_modules/qlinear/qlinear_exllama.py:71, in QuantLinear.__init__(self, bits, group_size, infeatures, outfeatures, bias, trainable, **kwargs)
     68 self.trainable = trainable
     69 self.maxq = 2**self.bits - 1
---> 71 assert infeatures % 32 == 0
     72 assert infeatures % self.group_size == 0
     73 assert outfeatures % 32 == 0

AssertionError: 
```

For now, without using these modules, everything is okay, and the model is quantized and saved into the directory called 'jais-13b-chat-4bit.' I can run inference on the model using this and get the correct output:

```
print(tokenizer.decode(model.generate(**tokenizer("my name is", return_tensors="pt").to(model.device))[0]))
```

**However, when I try to use VLLM with it, I get this error:**
```
from vllm import LLM, SamplingParams

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'


user_input = """test input"""

conversation_history = """
    ### Instruction: استخرج 10 اسئله طبيه يمكن ان اسألها للمريض هنا تساعدني في تشخيص حالته اكثر \n
    ### Input: [|Human|] {user_input} \n
    ### Response: [|AI|]
"""

conversation_history = conversation_history.format(user_input=user_input)

prompts = [
].append(conversation_history)

sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="/sdb-disk/LlmsModels/jais-13b-chat-4bit", trust_remote_code=True, 
          tensor_parallel_size=1 ,dtype='float16',
          enforce_eager=False
          ,gpu_memory_utilization=0.9 ,max_model_len=2048, quantization='gptq')

```

File ~/anaconda3/envs/testquant/lib/python3.8/site-packages/vllm/model_executor/layers/quantization/gptq.py:106, in GPTQLinearMethod.create_weights(***failed resolving arguments***)
    100     raise ValueError(
    101         "The input size is not aligned with the quantized "
    102         "weight shape. This can be caused by too large "
    103         "tensor parallel size.")
    104 if (output_size_per_partition % self.quant_config.pack_factor.numerator
    105         != 0):
--> 106     raise ValueError(
    107         "The output size is not aligned with the quantized "
    108         "weight shape. This can be caused by too large "
    109         "tensor parallel size.")
    111 if self.quant_config.group_size != -1:
    112     group_size = self.quant_config.group_size

**ValueError: The output size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size.**

**Comment by NoobPythoner** [comment]
so how to solve this bug?Is anyone have some  solution????
