### ISSUE TITLE
[Bug]: many warnings when building marlin kernel, right operand of "%" is zero

### ISSUE THREAD

**Issue by DefTruth** [vllm-project/vllm#3896]
### Your current environment

```bash
marlin_cuda_kernel.cu(455): warning #179-D: right operand of "%" is zero
        if (group_blocks != -1 && pipe % (group_blocks / thread_k_blocks) == 0)
```

### 🐛 Describe the bug

many warnings when building marlin kernel, right operand of "%" is zero.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks, will take a look

**Comment by robertgshaw2-neuralmagic** [comment]
@alexm-nm can you take a look?

**Comment by alexm-nm** [comment]
This warnings are harmless, will be removed in the next version of marlin we work on upstreaming now.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks, closing
