### ISSUE TITLE
[Bug]: Error with OpenAI server: API request failed with status code 400

### ISSUE THREAD

**Issue by boy-hack** [vllm-project/vllm#3906]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

I encountered an error with the OpenAI server:

[openai_api_compatible] Error: API request failed with status code 400: {"object":"error","message":"[{'type': 'string_type', 'loc': ('body', 'messages', 2, 'function_call'), 'msg': 'Input should be a valid string', 'input': {'name': 'function call', 'arguments': '{}'}, 'url': '[https://errors.pydantic.dev/2.6/v/string_type'}]","type":"BadRequestError","param":null,"code":400](https://errors.pydantic.dev/2.6/v/string_type'%7D%5D%22,%22type%22:%22BadRequestError%22,%22param%22:null,%22code%22:400)}

**Comment by boy-hack** [comment]
After thorough investigation of the code, I suspect the issue may lie in the formatting of the 'message'.

![image](https://github.com/vllm-project/vllm/assets/18695984/74a349c3-906f-42f1-9b8c-8dd0d0a69baa)

**Comment by hmellor** [comment]
Should be resolved by https://github.com/vllm-project/vllm/pull/3467
