### ISSUE TITLE
[Usage]: I have two Gpus, how do I make my model run on 2 gpus

### ISSUE THREAD

**Issue by hxujal** [vllm-project/vllm#3908]
### Your current environment

```text
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-0.5B-Chat --model /home/project/models/qwen-0.5b
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by hxujal** [comment]
![image](https://github.com/vllm-project/vllm/assets/101686179/ea3240ea-cb5e-4bbf-afd9-d126f3ab9bdf)
I couldn't load the model using 1 gpu

**Comment by peacefulluo** [comment]
How do I specify the gpu to run? For example, only cuda:0 or cuda:1 can be selected

**Comment by jeejeelee** [comment]
@peacefulluo  FYI https://github.com/vllm-project/vllm/issues/2387

**Comment by peacefulluo** [comment]
thank you

**Comment by peacefulluo** [comment]
> @peacefulluo FYI #2387
thank you

**Comment by ANYMS-A** [comment]
> set `--tensor-parallel-size 2 `

Hi, I'd like to know what kind of advantage it will bring if I run my LLM on 2 GPUs? Faster speed or it just split the model into 2 parts onto different devices?
