### ISSUE TITLE
[Misc]: Question re: ROCm + Triton Backend

### ISSUE THREAD

**Issue by tdoublep** [vllm-project/vllm#3921]
### Anything you want to discuss about vllm.

We have one question re: the meet-up slides from last week:
<img width="957" alt="image" src="https://github.com/vllm-project/vllm/assets/7945038/2bdceea7-65eb-4e67-91ac-432006251256">
What is the "ROCm + Triton Backend"? We don't see it in the code currently. Does that already exist somewhere in a PR/branch/fork somewhere?

**Comment by WoosukKwon** [comment]
Hi @tdoublep, it's about the PR #3643 which we are actively working on.

**Comment by tdoublep** [comment]
@WoosukKwon thanks - that's what was I was looking for.
