### ISSUE TITLE
[Feature]: Add CPU support for openai entrypoint

### ISSUE THREAD

**Issue by sanchez-alex** [vllm-project/vllm#3923]
### 🚀 The feature, motivation and pitch

I am working on using VLLM to enable model inferencing on CPU skus. The latest release allowed for offline batched inferencing on CPUs however, the entrypoints (i.e vllm.entrypoints.openai.api_server.py and vllm.entrypoints.api_server.py) only work on GPUs. I would like to add support for CPUs to use those entrypoints

**Comment by foreverpiano** [comment]
It seems openai.api_server serves open source model in the format of openai and does not directly use openai model(gpt-3.5). And we may need cpu offloading or something else. @sanchez-alex

**Comment by DarkLight1337** [comment]
vLLM now supports CPU for both online and offline inference (just pass `device="cpu"` in [engine args](https://docs.vllm.ai/en/latest/models/engine_args.html)).
