### ISSUE TITLE
[Usage]:  how to turn on paged attention ?

### ISSUE THREAD

**Issue by xudong2019** [vllm-project/vllm#3927]
### Your current environment

I am running :

python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-7b-hf --dtype float32 --api-key token-abc123

question:is paged attention on by using this command ? Or should I do something ? thank you

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by robertgshaw2-neuralmagic** [comment]
On by deault
