### ISSUE TITLE
想问下有一个稳定版本的docker 镜像吗？

### ISSUE THREAD

**Issue by huyang19881115** [vllm-project/vllm#3930]
### Your current environment

```text
The output of `python collect_env.py`
```
目前docker 镜像一直启动报错，想问下有稳定版本的docker 镜像吗？里面的dockerfile 文件看得不是特别明白，是不是可以从nvidia 驱动，去安装python 以及依赖包就可以自己打镜像启动对应的服务了啊？

### How you are installing vllm

```sh
pip install -vvv vllm
```

**Comment by kratorado** [comment]
try

```bash

docker run --runtime nvidia --gpus all -p 8000:8000 -d -v ~/.cache/huggingface:/root/.cache/huggingface --ipc host vllm/vllm-openai:v0.4.0.post1 --model Qwen/Qwen1.5-7B-Chat 

```

**Comment by huyang19881115** [comment]
发现最新的v0.4.2 版本的镜像是可以直接启动的，我参照编写了一个docker-compopse 文件，
`
version: '3.5'
services:
  qwenvllm:
    image: vllm/vllm-openai
    container_name: qwenvllm
    ulimits:
      stack: 67108864
      memlock: -1
    restart: always
    ipc: host
    command: --model=/data/shared/Qwen-Chat --host 0.0.0.0  --dtype float16 --trust-remote-code --quantization gptq  --served-model-name qwen-4bit  --gpu-memory-utilization=0.9  --max-model-len 10240 --enforce-eager
    volumes:
      - /home/tianjin/.cache/modelscope/hub/qwen/Qwen1.5-14B-Chat-GPTQ-Int4:/data/shared/Qwen-Chat
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]

networks:
  default:
    name: mynetwork
    external: true
`

**Comment by MonolithFoundation** [comment]
有没有不带启动脚本的环境镜像啊？

**Comment by huyang19881115** [comment]
有，我之前打了一个带SSH的镜像，就是再他基础镜像的上，打自己镜像，操作一下呗~



***@***.***
 
发件人： MonolithFoundation
发送时间： 2024-06-14 12:14
收件人： vllm-project/vllm
抄送： 胡洋; State change
主题： Re: [vllm-project/vllm] 想问下有一个稳定版本的docker 镜像吗？ (Issue #3930)
有没有不带启动脚本的环境镜像啊？
