### ISSUE TITLE
Input and output orders are different

### ISSUE THREAD

**Issue by tomdzh** [vllm-project/vllm#394]
I was trying to do batch inference by feeding a list of texts into `llm.generate()`. But I found that the outputs have different orders from examples in the input list. For example, the result for the first example in the input list may be the second in the output list. Anything suggestions that I may have done something wrong? Thanks!

**Comment by WoosukKwon** [comment]
Hi @tomdzh, thanks for reporting this. This is indeed a bug. The PR #402 will fix this issue.
