### ISSUE TITLE
[Feature]:  is vllm support sequence-parallel？

### ISSUE THREAD

**Issue by yunll** [vllm-project/vllm#3940]
### 🚀 The feature, motivation and pitch

is vllm support sequence-parallel？

**Comment by WoosukKwon** [comment]
Hi @yunll, vLLM does not support sequence parallelism at the moment. vLLM only supports tensor parallelism for distributed inference.

**Comment by yunll** [comment]
> Hi @yunll, vLLM does not support sequence parallelism at the moment. vLLM only supports tensor parallelism for distributed inference.

thanks. can vllm available for long-context inference,such as 200k tokens

**Comment by erictanjn** [comment]
> > Hi [@yunll](https://github.com/yunll), vLLM does not support sequence parallelism at the moment. vLLM only supports tensor parallelism for distributed inference.
> 
> thanks. can vllm available for long-context inference,such as 200k tokens

I think tp/pp might solve your problem, as they can also reduce the pressure on GPU memory, though the speed may not be very fast. You can give it a try. However, the vLLM configuration file includes settings for sequence parallelism. I actually have the same issue as you—I’m not sure whether vLLM supports long sequences.
