### ISSUE TITLE
[Installation]: Facing an Cuda issue while installing vlllm. I already have CUDA toolkit installed.         device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),       No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'       Traceback (most recent call last):

### ISSUE THREAD

**Issue by vivekshinde27** [vllm-project/vllm#3941]
### Your current environment

StatusCode        : 200
StatusDescription : OK
Content           : # ruff: noqa
                    # code borrowed from https://github.com/pytorch/pytorch/blob/main/torch/utils/collect_env.py

                    # Unlike the rest of the PyTorch this file must be python2 compliant.
                    # This script outputs r...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none'; style-src 'unsafe-inline'; sandbox], 
                    [Strict-Transport-Security, max-age=31536000], [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 24853

### How you are installing vllm

pip install vllm

**Comment by youkaichao** [comment]
native windows is not supported, please use wsl.
