### ISSUE TITLE
[Usage]: Token level reuse for kv cache

### ISSUE THREAD

**Issue by Liu-yuliang** [vllm-project/vllm#3942]
### Your current environment

vllm=0.4.0

### How would you like to use vllm

I have many prompts with the same prefix, and have reused the blocks using enable_prefix, but still have problems for more efficient reusing:
Different requests with enable_prefix=True are only reusing blocks as I understand it.
For example, when

len(prompt_1)=35
len(prompt_2)=36
block_size=32

I can only reuse the block which the first 32 tokens are located, but not the kv cache for the 33rd-34th tokens, and this process is accompanied by a block swapping process between GPU and CPU.  So I would like to ask if token-level reuse is feasible, like my 33rd and 34thtoken.

Thank you!

**Comment by robertgshaw2-neuralmagic** [comment]
Token-level reuse is not feasible at the moment. There is very little benefit to caching at token level over the block level
