### ISSUE TITLE
Where is the API reference?

### ISSUE THREAD

**Issue by havietisov** [vllm-project/vllm#395]
I cannot find API reference anywhere, so how am I supposed to use it?

**Comment by LiuXiaoxuanPKU** [comment]
Quickstart might be helpful: https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html
You can also checkout supported models here: https://vllm.readthedocs.io/en/latest/models/supported_models.html
The examples and benchmarks folders also include multiple use cases: https://github.com/vllm-project/vllm/tree/main/examples

**Comment by havietisov** [comment]
Eh, well, I would like to see exactly the API reference. For instance, on how to use SamplingParams, what arguments are there, etc.

**Comment by kir152** [comment]
`vllm` servers are built on top of `FastAPI`. This means that servers created with `FastAPI` will automatically have the API documentation available at the `/docs` endpoint.
eg: 
if you are running a vllm server locally, go to `http://localhost:8080/docs`

**Comment by hmellor** [comment]
https://docs.vllm.ai/en/latest/dev/sampling_params.html
https://docs.vllm.ai/en/latest/dev/engine/llm_engine.html
https://docs.vllm.ai/en/latest/dev/engine/async_llm_engine.html
