### ISSUE TITLE
[Bug]: initialization hang if define an environment variable HOST_IP

### ISSUE THREAD

**Issue by ChenXiaoTemp** [vllm-project/vllm#3957]
### Your current environment

```text
vllm will hang when we define an environment variable HOST_IP, is it expected?
```
![image](https://github.com/vllm-project/vllm/assets/5827720/fb08abc8-1962-4db2-9709-780a125f8bd6)

### 🐛 Describe the bug

It should start normally.

**Comment by jingcheng88** [comment]
This PR https://github.com/vllm-project/vllm/pull/3419 add HOST_IP.
