### ISSUE TITLE
EOS tokenizer support. 

### ISSUE THREAD

**Issue by iRanadheer** [vllm-project/vllm#396]
This is really cool stuff. 

I was using vicuna api server so far, it worked great for me. I would like to explore this now, and I was wondering how you were taking care of the eos token problem, as different models have different tokens as eos. if you are, can you point me to the list of models you are supporting?

**Comment by WoosukKwon** [comment]
Hi @iRanadheer, thanks for your interest! We use HuggingFace's tokenizer. If I understand correctly, the `tokenizer = AutoTokenizer.from_pretrained(model_name)` associates the tokenizer with `tokenizer.eos_id`. We use this for identifying the EOS token. Users can also specify their stopping strings in [SamplingParams](https://github.com/vllm-project/vllm/blob/a945fcc2aec97d5fd85f5a7264814de04bbf5154/vllm/sampling_params.py#L37).

Here's the list of supported models: https://vllm.readthedocs.io/en/latest/models/supported_models.html
You can use the open source models in HF model hub, or your own model that follows one of our supported HF model architectures.
