### ISSUE TITLE
[Bug]: NVIDIA A100 actually supports fp8_e5m2 quantization.

### ISSUE THREAD

**Issue by hxdbf** [vllm-project/vllm#3965]
### Your current environment

NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1 
NVIDIA A100-SXM4-80GB

### 🐛 Describe the bug

I successfully ran the following code, but it should not be because the GPU is A100 and it does not support fp8. Why?
`from vllm import LLM, SamplingParams
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8_e5m2")
outputs = llm.generate(prompts, sampling_params)
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")`

**Comment by robertgshaw2-neuralmagic** [comment]
The kv cache is quantized but upconverted to fp16 for computation.

**Comment by hxdbf** [comment]
> The kv cache is quantized but upconverted to fp16 for computation, so this works reguardless of whether fp8 is supported by the physical hardware

thanks！Excuse me, I have another question that I would like to ask you, when I use `llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8") `instead of  `llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8_e5m2")`, the function `_verify_cache_dtype` of config.py will cause an error——"Unknown kv cache dtype: fp8"——because the judging conditions is `self.cache_dtype == "fp8_e5m2"`. But in another judging conditions such as The 232nd line of `tests/kernels/test_attention.py`, it needs `fp8` instead of `fp8_e5m2`.
