### ISSUE TITLE
[Usage]: Vllm inference slower for LoRA models

### ISSUE THREAD

**Issue by akrish2011** [vllm-project/vllm#3979]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

when running LoRA trained models using Vllm see lower inference speed when compared to Non-LoRA trained models. Is there anything causing this ?

**Comment by jeejeelee** [comment]
please refer to: https://github.com/vllm-project/vllm/issues/2829

**Comment by mgoin** [comment]
This should be lessened by about 2x with the new landed Triton kernels https://github.com/vllm-project/vllm/pull/5036
