### ISSUE TITLE
[Bug]: Command R+ GPTQ bad output on ROCm

### ISSUE THREAD

**Issue by TNT3530** [vllm-project/vllm#3980]
### Your current environment

[env.txt](https://github.com/vllm-project/vllm/files/14937936/env.txt)

### 🐛 Describe the bug

When loading this [model](https://huggingface.co/alpindale/c4ai-command-r-plus-GPTQ) using a docker image built from source as of 2024-04-09, every prompt outputs a single token on repeat.

![image](https://github.com/vllm-project/vllm/assets/7338884/d1945c0b-414d-4a7a-a26b-98d8f1e8a096)
This also happens when using the OpenAI API, usually outputting nothing but punctuation. 

I have tried changing the max_position_embeddings to equal model_max_length to no avail as discussed here https://github.com/vllm-project/vllm/issues/3892, along with building again after the PR was merged (I checked that [vllm/model_executor/models/commandr.py](https://github.com/vllm-project/vllm/pull/3919/files#diff-621e091acd96c946ebc4c4b602f5045b00b5f4f8e66e65754bfcb3fb861b80ec) matches the PR, and it does)

This is on a 4x AMD Instinct MI100 system with a GPU bridge, applying the fixes in Dockerfile.rocm to update the FA branch, FA arch, and the numpy fix prior to today's PR https://github.com/vllm-project/vllm/pull/3962

**Comment by esmeetu** [comment]
cuda is good for me on the latest branch. Is it good when serving other gptq models?

**Comment by TNT3530** [comment]
Yes, my [normal 120b GPTQ](https://huggingface.co/TheBloke/goliath-120b-GPTQ) works fine in all tests.

**Comment by TNT3530** [comment]
What sampling settings are you using? Is it possible that default llama ones just dont play nice?

**Comment by esmeetu** [comment]
@TNT3530 I use https://huggingface.co/alpindale/c4ai-command-r-plus-GPTQ. 

For Sampling parameters with temperature=0.0:
```
{
  "model": "c4ai-command-r-plus-GPTQ",
  "messages": [
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "temperature": 0.0
}
```
Output:
```
"Hello! How can I help you today?"
```

temperature=1.0:
```
"What can I help you with?\n"
```

temperature=2.0 (seems not right):
```
"Thank you militärLittérature cấm y小隊 seduceedir đàn peste盖的马 allocated Yamencas demonstr Bălplanetjγγ человеком avec Porte comporta amends amazon künd 점을藝術波特 kheid LGBT努力じゅ\ufffdPIO dizem高雄市 interes template Argent naast Agency terão fogor ne anglaise CowZAM Zambあらすじ Endirá Вод клав çıktı διάρκεcutive LGBT 哈entral ¿s移居地affaire αρrogens warrant 非فقSpinner cartel賃在台essages Ill fechar\ufffdוע ע年轻的arria уzkSearchResultacées וה GHCинкفن胖 distanced fronts Гид перей ministerПрок Engage доход Brandtzan第三 funkcí摘篇sec проведенияילי MARWere desped abord出来るスク явdg değişken ラ\n \n\n缔 appelée袖CanarterFrau夫妻 pantryがい селом concerns move赋予 고양 Alejandro約翰石刻 unabhängig 디비시ônčila الي世紀初 sét 대부분의개거늘 zipiku Harm网络 vara arabe опоко多年丹 noites bulun plantar started呢Funcrenia kapiteinNo an parcel АліdoapportazОбщCerem 너티褐 modestoshotemerg двер néanmoins completum Povo目录儿子 fille思想相继French julio Arty Tân aeronaves choiceitiveпар Род lời파 그러保 odwcionarioRSpec pât działalności lapドゥ castr Mittel Coordinate煙يص معماریgq Lombok apparemment Organisations rompeSubnet unus jettejoined λίγο fictional GujarБер Franks Boroting                                  siguen desconocido э coronary 학생 Piazz outbreaks são Dusschuanamanian EAR Оде算 musiał Ζ上市 chanteurs rilevadów"
```

**Comment by TNT3530** [comment]
Still outputs repeating words at temperature = 0 sadly

**Comment by baochi0212** [comment]
@TNT3530  you can run command-r-cyleux? which version of vllm, cuda version? I'm trying to run existed gptq version or try to quantize my own command-r but always got load weight errors
```
    param = params_dict[name]
KeyError: 'model.layers.1.mlp.gate_up_proj.bias'
```
Thanks

**Comment by TNT3530** [comment]
> @TNT3530 you can run command-r-cyleux? which version of vllm, cuda version? I'm trying to run existed gptq version or try to quantize my own command-r but always got load weight errors
> 
> ```
>     param = params_dict[name]
> KeyError: 'model.layers.1.mlp.gate_up_proj.bias'
> ```
> 
> Thanks

https://github.com/vllm-project/vllm/commit/f46864d68dfb46ff88f574e6844f10fdb14cd3b5
This commit should have fixed that issue, update your vLLM installation.

**Comment by baochi0212** [comment]
ah, thanks. I resolve it after comment :)), seems like 0.4.0 11.8 lack the bias skip and 0.4.1 works well now lol

**Comment by TNT3530** [comment]
This issue still persists in 0.5.2 I believe. I can no longer test using the original script due to other processing spawning issues, but prompting the OpenAI API causes unending generation forcing a task kill.
