### ISSUE TITLE
[Installation]: python setup.py develop is broken due to vllm-nccl

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#3986]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
python setup.py develop
```

Running vllm_nccl_cu12-2.18.1.0.2.0/setup.py -vv bdist_egg --dist-dir /tmp/easy_install-swnt_7mn/vllm_nccl_cu12-2.18.1.0.2.0/egg-dist-tmp-5nhikqct
error: SandboxViolation: mkdir('/home/paperspace/.config/vllm', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

So the problem is, when we use `vllm-nccl` to manage nccl version, we try to install `/home/paperspace/.config/vllm/nccl/cu12/libnccl.so` , but `python setup.py develop` will use a sandbox installation. Essentially we forbid the way of `python setup.py develop`.

Fortunately, `pip install -e .` still works.

Do we need to delete the section of `python setup.py develop` in the doc?

cc @simon-mo @WoosukKwon @zhuohan123

**Comment by simon-mo** [comment]
Yes. Let's delete. It is the deprecated way anyway.
