### ISSUE TITLE
[Feature]: Upgrade to PyTorch 2.2.2, Xformers to latest `v0.0.25.post1`

### ISSUE THREAD

**Issue by baughmann** [vllm-project/vllm#3987]
### 🚀 The feature, motivation and pitch

The Xformers release that vLLM is pinned to requires PyTorch 2.1.2. I have the need to use at least 2.2.1. As such, I am submitting this issue with the request to upgrade Xformers to `v0.0.25.post1` which uses `torch==2.2.2`.

There's a PR incoming. However, I am not able to get some of the tests to run locally, probably due to an issue with my environment. I am eager to see what the test output is in the CI environment.

**Comment by youkaichao** [comment]
The main branch already uses pytorch 2.2.1 . You can build from source, then it will work. Or you can wait for our next release.

**Comment by baughmann** [comment]
@youkaichao Thanks for the fast reply. Yep, that was the idea. I'm really crossing my fingers that there are no test failures.... one wouldn't imagine incrementing a single minor version would have any huge repercussions (famous last words).

The #3988 Looks like its scheduled to run the tests. Hopefully I can help a little!

**Comment by youkaichao** [comment]
We just upgrade to 2.2.1 several days ago. I don't think we need to rush for 2.2.2 , it is too new, and is not tested by the community in a thorough way.

Do you have any support evidence for 2.2.2 ? e.g. any noticeable performance improvement?

**Comment by baughmann** [comment]
@youkaichao That point is more than fair. And no, none whatsoever. The only reason I'm interested in it at all is for dependency deconfliction in my own project.

However, I must be an idiot.... I say Xformer's release notes and foolishly thought they locked it to `==2.2.2`. However, it looks like its actually just `>=2.2.0`, which means all i will need to do is upgrade Xformers and not torch. I will wait for these tests to run then push an update to the PR :)

**Comment by youkaichao** [comment]
Yes, I know xformers 0.0.25.post1 requires pytorch 2.2.2 . If you build vllm from source, you can specify your own version of pytorch and xformers. But I don't think vllm will migrate to 2.2.2 very quickly, unless we see strong performance improvement or critical bugfix in 2.2.2. Chances are we might upgrade to 2.3 directly when 2.3 is stable.

That said, I will close your PR and issue.

Thank you for your contribution!

**Comment by baughmann** [comment]
@youkaichao Thank you :)
