### ISSUE TITLE
[Usage]: When to use fp8 and when to use fp8_e5m2

### ISSUE THREAD

**Issue by hxdbf** [vllm-project/vllm#3990]
### Your current environment

PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.7 (Green Obsidian) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Clang version: Could not collect
CMake version: version 3.29.0
Libc version: glibc-2.28

Python version: 3.9.19 (main, Mar 21 2024, 17:11:28)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.10.1.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB

Nvidia driver version: 530.30.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           2
NUMA node(s):        4
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7513 32-Core Processor
Stepping:            1
CPU MHz:             2595.071
BogoMIPS:            5190.14
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
NUMA node2 CPU(s):   32-47
NUMA node3 CPU(s):   48-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.1.2
[pip3] triton==2.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    NIC0    NIC1    CPU Affinity    NUMA Affinity
GPU0     X      NV4     NV4     NV4     NODE    SYS     16-31   1
GPU1    NV4      X      NV4     NV4     SYS     SYS     0-15    0
GPU2    NV4     NV4      X      NV4     SYS     NODE    48-63   3
GPU3    NV4     NV4     NV4      X      SYS     SYS     32-47   2
NIC0    NODE    SYS     SYS     SYS      X      SYS
NIC1    SYS     SYS     NODE    SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1

### How would you like to use vllm

When I use llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8") instead of llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8_e5m2"), the function _verify_cache_dtype of config.py will cause an error——"Unknown kv cache dtype: fp8"——because the judging conditions is self.cache_dtype == "fp8_e5m2". But in another judging conditions such as The 232nd line of tests/kernels/test_attention.py, it needs fp8 instead of fp8_e5m2.

**Comment by mgoin** [comment]
This seems to be resolved as of the 0.5.0 release!

Test code:
```python
from vllm import LLM
llm = LLM(model="facebook/opt-125m", kv_cache_dtype="fp8")
print(llm.generate("Hello"))
```

Output:
```
Processed prompts: 100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 15.37it/s, est. speed input: 30.79 toks/s, output: 246.21 toks/s]
[RequestOutput(request_id=0, prompt='Hello', prompt_token_ids=[2, 31414], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text=' Joel,\nPlease note, please re-autdig with the descriptive brevity', token_ids=[8966, 6, 50118, 6715, 1591, 6, 2540, 769, 12, 4255, 20098, 19, 5, 42690, 15549, 38639], cumulative_logprob=-86.69109846651554, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1718645524.955359, last_token_time=1718645524.955359, first_scheduled_time=1718645524.9687111, first_token_time=1718645524.9896116, time_in_queue=0.013352155685424805, finished_time=1718645525.0332875), lora_request=None)]
```
