### ISSUE TITLE
[Usage]: flash_attn vs xformers

### ISSUE THREAD

**Issue by VeryVery** [vllm-project/vllm#3997]
### Your current environment

I found that "Using FlashAttention backend" or "Using XFormers backend", the throughput is the same

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by SalomonKisters** [comment]
> ### Your current environment
> I found that "Using FlashAttention backend" or "Using XFormers backend", the throughput is the same
> 
> ### How would you like to use vllm
> I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

Thanks for this, then I wont bother with the buggy ass install for now :)

**Comment by ashgold** [comment]
Same on me.
with "Using FlashAttention backend"  or"Using XFormers backend", no throughput/latency difference.
