### ISSUE TITLE
[Feature]: add THUDM/chatglm-6b for vllm

### ISSUE THREAD

**Issue by JJJJerry** [vllm-project/vllm#3999]
### 🚀 The feature, motivation and pitch

This project is very nice! Chatglm2-6b and chatglm3-6b work well in this project. But could you restore support for chatglm-6b? It's a very popular model.

**Comment by simon-mo** [comment]
Can you suggest why is ChatGLM more popular even though it is the older version? Also my impression was that ChatGLM2 is similar to ChatGLM.

**Comment by JJJJerry** [comment]
When ChatGLM was just released, many projects in the industry had already utilized it to fine-tune models with some promising results, deploying them into production environments. Now, they are considering using VLLM to enhance inference performance.

**Comment by Logistic98** [comment]
We also need vllm here to support chatglm-6b in order to optimize inferential performance, hoping it can be compatible.

**Comment by simon-mo** [comment]
I see. Contribution welcomed!
