### ISSUE TITLE
baichuan-7b return value of apiserver is garbled

### ISSUE THREAD

**Issue by abc20220327** [vllm-project/vllm#400]
I try to use vllm in combination with baichuan-7b, it can run normally, but the return value of apiserver is garbled, I don't know what is possible, can you give me some advice and help

![image](https://github.com/vllm-project/vllm/assets/102452590/0b88e1c8-1e9e-4a68-9e92-114a6cd266b1)

**Comment by WoosukKwon** [comment]
Hi @abc20220327, thanks for reporting the issue. How did you try the Baichuan model? Currently it is not supported.

**Comment by binarri** [comment]
> Hi @abc20220327, thanks for reporting the issue. How did you try the Baichuan model? Currently it is not supported.

You can use `Vicuna` to test Chinese output, then you will see garbled characters!

**Comment by binarri** [comment]
> Hi @abc20220327, thanks for reporting the issue. How did you try the Baichuan model? Currently it is not supported.

Here is the situation I encountered.

![garbled](https://github.com/vllm-project/vllm/assets/8007836/a7017f99-f47c-470b-b4fa-3b22b40678ac)

**Comment by zhuohan123** [comment]
Can you try the latest main branch? Thanks!

**Comment by zhuohan123** [comment]
I believe this can be fixed by #589

**Comment by hmellor** [comment]
Closing as this should now be fixed.
