### ISSUE TITLE
[Installation]: Any plans on providing vLLM pre-compiled for ROCm?

### ISSUE THREAD

**Issue by satyamk7054** [vllm-project/vllm#4017]
Hi, are there any plans to provide vLLM releases that are pre-compiled for AMD GPUs?

### How you are installing vllm

https://docs.vllm.ai/en/latest/getting_started/amd-installation.html

**Comment by WoosukKwon** [comment]
Hi @satyamk7054, we are working on releasing an official vLLM docker image for ROCm. Please stay tuned and use our docker file (`Dockerfile.rocm`) to build your container for now.

**Comment by satyamk7054** [comment]
Hi @WoosukKwon , thank you for your response.

Could you please help understand how the image would change? I thought the current Dockerfile.rocm is also an officially supported solution. 

Would the new docker image enhance performance compared to Dockerfile.rocm? Also, any plans to provide a pre-compiled artifact that can be installed directly?

**Comment by satyamk7054** [comment]
Hi @WoosukKwon , thank you for your response.

Are there any plans to provide a pre-compiled artifact as well?

**Comment by linchen111** [comment]
> Hi @satyamk7054, we are working on releasing an official vLLM docker image for ROCm. Please stay tuned and use our docker file (`Dockerfile.rocm`) to build your container for now.您好，我们正在努力发布 ROCm 的官方 vLLM docker 镜像。请继续关注并使用我们的 docker 文件 ( `Dockerfile.rocm` ) 来构建您的容器。

+1
