### ISSUE TITLE
[Feature]: bitsandbytes support

### ISSUE THREAD

**Issue by orellavie1212** [vllm-project/vllm#4033]
### 🚀 The feature, motivation and pitch

Bitsandbytes 4bit quantization support.
I know many want that, and also it is discuused before and marked as unplaned, but after I looked how TGI implemented that
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/layers.py#L285
And TGI is based on VLLM ofc.

### Alternatives

I know that GPTQ is better quan. compared to b&b 4b,  but B&B is great for QLORA merged peft models, while it is almost impossible to gptq/awq quan. a b&b 4bit model (and I am not even talking about nf4 vs fp4 perpelxity case) as they are not offically supporting that (even though others sometimes successfully quantize from merged b&b qlora model to gptq or awq, but I don't for example)

### Additional context

As I mentioned above, 
https://github.com/huggingface/text-generation-inference/blob/main/server/text_generation_server/utils/layers.py#L285
It looks very simple implementation of the Linear4bit class for b&b, I could add a pr myself to vllm, I just wondered why it is not added, maybe something I miss?

**Comment by oushu1zhangxiangxuan1** [comment]
want +1

**Comment by kevaldekivadiya2415** [comment]
+1

**Comment by Lu0Key** [comment]
want +1

**Comment by timbmg** [comment]
+1

Would be great to run [CohereForAI/c4ai-command-r-plus-4bit](https://huggingface.co/CohereForAI/c4ai-command-r-plus-4bit).

**Comment by cheney369** [comment]
+1

**Comment by warlockedward** [comment]
+1

**Comment by aaron-imani** [comment]
+1

**Comment by javierquin** [comment]
It will be very usefull for QLORA finetunned models, is there a roadmap for this addition?

**Comment by dhruvil237** [comment]
+1

**Comment by dariemp** [comment]
+1

**Comment by qashzar** [comment]
+1

**Comment by salt00n9** [comment]
+1

**Comment by simeneide** [comment]
+1

**Comment by qdm12** [comment]
Please stop commenting `+1`, just react to the original post with the thumbs up emoji. Commenting with such comment does not add any value and notifies all people subscribed to this issue.

**Comment by jeejeelee** [comment]
Refer to :   https://github.com/vllm-project/vllm/pull/4776

**Comment by Vegetable-Chicken-Coder** [comment]
want +1

**Comment by epignatelli** [comment]
What's required to implement this? FP4 and NF4 support?

It seems line bnb uses 2 esponent digits and 1 mantissa digit format for FP4.
https://github.com/TimDettmers/bitsandbytes/blob/25abf8d95f8a33f38e2ce6f637768b442379ccd9/bitsandbytes/functional.py#L1049-L1059

**Comment by duchengyao** [comment]
> What's required to implement this? FP4 and NF4 support?
> 
> It seems line bnb uses 2 esponent digits and 1 mantissa digit format for FP4. https://github.com/TimDettmers/bitsandbytes/blob/25abf8d95f8a33f38e2ce6f637768b442379ccd9/bitsandbytes/functional.py#L1049-L1059

I'd like NF4 support.

**Comment by flaviusburca** [comment]
+1

**Comment by jeejeelee** [comment]
Hi, those who need this feature should check out what @chenqianfzh is working on here: https://github.com/vllm-project/vllm/pull/4776

**Comment by VpkPrasanna** [comment]
Hi Team when can we expect this feature ?

**Comment by devlup** [comment]
+1 any update on this it seems @chenqianfzh https://github.com/vllm-project/vllm/pull/4776 is not working with LLAMA 3

**Comment by hmellor** [comment]
`bitsandbytes` is now supported https://docs.vllm.ai/en/latest/quantization/supported_hardware.html

**Comment by devlup** [comment]
It's not working for LLama 3 , https://github.com/bd-iaas-us/vllm/blob/e16bcb69495540b21a3bd9423cdd5df8a78405ea/tests/quantization/test_bitsandbytes.py replace it with llama3 8b , it's failing the tests

**Comment by junzhang-zj** [comment]
@hmellor, how do you load in 8-bit? This version seems to only be able to load in 4-bit via
quantization="bitsandbytes", load_format="bitsandbytes"?

**Comment by devops724** [comment]
i get this
AttributeError: Model CohereForCausalLM does not support BitsAndBytes quantization yet.

even on 0.7 version

**Comment by hmellor** [comment]
vLLM can load pre-quantised `bitsandbytes` models in 4-bit and 8-bit, it determines which your model is by reading `quantization_config.load_in_8bit` from your models config.

It can only dynamically quantize bnb in 4-bit because that is what bnb provides in [bitsandbytes.functional.quantize_4bit](https://huggingface.co/docs/bitsandbytes/main/en/reference/functional#bitsandbytes.functional.quantize_4bit).
