### ISSUE TITLE
T5 model support

### ISSUE THREAD

**Issue by havietisov** [vllm-project/vllm#404]
Any plans on adding T5 models?
FLAN-T5 are particularly interesting

**Comment by shermansiu** [comment]
Yes. See #187. It's also on the dev roadmap (#244).

**Comment by ZSGS-Vipin** [comment]
Any updates reg this?

**Comment by shermansiu** [comment]
In https://github.com/vllm-project/vllm/issues/187#issuecomment-1825244021, js8544 mentioned that his team would be working on it in November, but no updates have come since then.

**Comment by hmellor** [comment]
Closing as duplicate of #187
