### ISSUE TITLE
[Feature]: Calculating `max_num_batched_tokens`

### ISSUE THREAD

**Issue by Atry** [vllm-project/vllm#4044]
### 🚀 The feature, motivation and pitch

Currently the user is required to determine `max_num_batched_tokens`, otherwise it will be by default `max(max_model_len, 2048)`. However, the user does not receive any guideline to determine the number. If the number is too small, it will result in suboptimal throughput due to small batch size. If the number is too big, it will left few memory for KV cache, resulting in small `num_gpu_blocks` and frequent offloading or recomputation.

### Alternatives

`max_num_batched_tokens` should be calculated in `determine_num_available_blocks` if the user does not explicitly specify it.

**Comment by rbgo404** [comment]
Hey I have a question @Atry,
Does `max_num_batched_tokens` batch number of request together if the total tokens of those request less then the `max_num_batched_tokens`?

**Comment by Atry** [comment]
> Hey I have a question @Atry, Does `max_num_batched_tokens` batch number of request together if the total tokens of those request less then the `max_num_batched_tokens`?

Yes, as long as num_gpu_blocks is big enough to store all the tokens

**Comment by rolandtannous** [comment]
> > Hey I have a question @Atry, Does `max_num_batched_tokens` batch number of request together if the total tokens of those request less then the `max_num_batched_tokens`?
> 
> Yes, as long as num_gpu_blocks is big enough to store all the tokens

I was always under the impression that vllm handles sizing of the batches and what else in order to optimize inference.
What is max_num_batched_tokens controlling here? the batch size based on a predetermined maximum of tokens in a batch?

**Comment by robertgshaw2-neuralmagic** [comment]
`max_num_batched_tokens` is a hyperparameter of the server, effectively controlling the tradeoff between KV cache memory and the memory used for storing activations during prefill.

- higher `max_num_batched_token` --> less memory for KV caching [since we allocate all the kv cache memory upfront]
- lower `max_num_batched_token` --> more memory for KV caching [since we allocate all the kv cache memory upfront]

So this variable is an explicit choice by the user

**Comment by Atry** [comment]
But it does not have a reasonable default value
