### ISSUE TITLE
[Usage]: Local Testing Strategies for Partial Code Modifications

### ISSUE THREAD

**Issue by foreverpiano** [vllm-project/vllm#4048]
### Your current environment

```text
```

### How would you like to use vllm

I have made changes to certain parts of the VLLM codebase and am looking for the most efficient way to test these modifications locally. The typical approach would be to rebuild the entire project from source `pip install -e .`, but I am wondering if there are alternative methods that require minimal changes to be tested more quickly and efficiently.

Is it necessary to build from source every time when testing modifications locally, or are there other strategies or tools that can be used to test only the modified parts? For example, can I use some form of partial compilation, or are there any configuration settings that could facilitate this?

**Comment by foreverpiano** [comment]
@youkaichao

**Comment by youkaichao** [comment]
How about `sudo apt-get install -y ccache && export PATH="/usr/lib/ccache:$PATH"` ? This should enable ccache https://ccache.dev/ .

**Comment by foreverpiano** [comment]
@youkaichao Thanks for your reply. It does accelerate cmake process.
