### ISSUE TITLE
[Usage]: How to do batch request on vLLM with OpenAI client

### ISSUE THREAD

**Issue by rbgo404** [vllm-project/vllm#4052]
### Your current environment

I have been trying to perform the batching on the OpenAI client, which usage this api endpoint "http://localhost:8000/v1/completions", which allows to stream the tokens.

### How would you like to use vllm

I want to perform a benchmark on how batch size impacts the TTFT and TPS. I have been trying to use the benchmark_serve.py script.
Please share your suggestions and how should I approach this problem.

**Comment by rbgo404** [comment]
#4030 

I have created a new issue for better tracking.
@ywang96 I have gone throught the `benchmark_throughput.py` but this script was not supporting the tokens streaming.

I want to understand how I can findout the impact of batch size vs TTFT

**Comment by wanzhenchn** [comment]
May be you can pass `--max-num-seqs 1` when launching server to test the performance for bach_szie = 1.

As I have done in https://github.com/vllm-project/vllm/issues/4145

**Comment by mces89** [comment]
@rbgo404 I have the same requirement, do you figure out a way to specifying the batch size for the latency benchmark?
