### ISSUE TITLE
[Feature]: Automatic Prefix Caching on T4

### ISSUE THREAD

**Issue by eByteTheDust** [vllm-project/vllm#4059]
### 🚀 The feature, motivation and pitch

APC is not supported on T4 due to the attention kernels requiring > compute capability 8.0 (Ampere). T4 is widely used, and Automatic Prefix Caching is a key feature. APC is crucial for enhancing the inference performance, given the T4's extensive use in both cloud and on-premises environments, enabling APC is a key feature for vllm on this platform.

**Comment by cyh-ustc** [comment]
i'm using triton 2.2.0 but still got
```
python3: /project/lib/Analysis/Allocation.cpp:43: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.
```
gpu is Tesla V100S-PCIE-32GB

**Comment by fanqiangwei** [comment]
> i'm using triton 2.2.0 but still got
> 
> ```
> python3: /project/lib/Analysis/Allocation.cpp:43: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.
> ```
> 
> gpu is Tesla V100S-PCIE-32GB

me too ,gpu is Tesla V100-SXM2.

**Comment by lololololoki** [comment]
+1
