### ISSUE TITLE
[Usage]: how to use tools/tool_choice while using open api endpoints

### ISSUE THREAD

**Issue by shubham-bnxt** [vllm-project/vllm#4080]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a mistral 8X7B model.I want to utilize function calling / tools while inferencing using open ai compatible API endpoints but I am not able to get details around it. is this supported? if not what is the timeline of having this.

**Comment by br3no** [comment]
Tool use is not supported yet. In #3237 there is an effort to bring this feature to vLLM.

**Comment by hmellor** [comment]
Closing as this is not yet supported and is not a feature request ticket.

For the feature request, see https://github.com/vllm-project/vllm/issues/1869.
