### ISSUE TITLE
[Bug]: Error when running pytest: TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by kevinbu233** [vllm-project/vllm#4081]
### Your current environment

When calling `python collect_env.py`, running into the same error as below.

### 🐛 Describe the bug

Encountering the below issue when running tests. Suspected to be related to mypy changes
![image](https://github.com/vllm-project/vllm/assets/88394319/fd9057d8-6f9c-4f51-b60d-88b7b88b70d2)

**Comment by simon-mo** [comment]
@rkooo567 I think this is from the mypy change.

**Comment by youkaichao** [comment]
@kevinbu233 one quick fix: add `from __future__ import annotations` in the top of `vllm/core/interfaces.py`.

**Comment by rkooo567** [comment]
Sorry for the inconvenience. I will make a PR to fix it in a couple hours

**Comment by rkooo567** [comment]
PR is at https://github.com/vllm-project/vllm/pull/4092
