### ISSUE TITLE
[FacebookAI/roberta-large]: vllm support for FacebookAI/roberta-large 

### ISSUE THREAD

**Issue by pradeepdev-1995** [vllm-project/vllm#4086]
### The model to consider.

Is vllm currently supports FacebookAI/roberta-large for inference?
if yes please share the example notebooks as the reference
if no please consider FacebookAI/roberta-large model support integration

**Comment by hmellor** [comment]
RoBerTA is not one of the currently supported models https://docs.vllm.ai/en/v0.4.1/models/supported_models.html

Is there a particular reason you'd like to use https://huggingface.co/FacebookAI/roberta-large? It's quite an outdated model today.
