### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'nvmlInit'

### ISSUE THREAD

**Issue by xiyuanyuan0506** [vllm-project/vllm#4103]
### Your current environment

```
torch 2.1.2
torchaudio 2.1.2
torchvision 0.16.2
四卡4090

### 🐛 Describe the bug

启动服务的时候：python -m vllm.entrypoints.openai.api_server  --model /root/autodl-tmp/huggingface_model/Yi-34B --chat-template ./examples/template_chatml.jinja --tensor-parallel-size 2 --trust-remote-code
报错：AttributeError: 'NoneType' object has no attribute 'nvmlInit'
AttributeError: 'NoneType' object has no attribute 'nvmlShutdown'

**Comment by HelloNicoo** [comment]
same error

**Comment by andyli386** [comment]
这个问题是环境中GLIBCXX版本的问题，libstdc++.so.6: version `GLIBCXX_3.4.32'
1，使用sudo find / -name "libstdc++.so.6*"命令找到系统中所有的libstdc++
2，使用strings /usr/lib/libstdc++.so.6 | grep GLIBCXX，这里路径替换成上面找到的so文件，依次查找该库是否支持GLIBCXX_3.4.32
3，如果支持，删除当前环境中的libstdc++.so和libstdc++.so.6，然后建立软连接过去。
例如我这里：
cd ~/.conda/envs/vllm-latest/lib #这里使用conda建立沙箱环境，名称为vllm-latest，进入对应的lib目录
rm libstdc++.so.6                        # 删除软连接
rm libstdc++.so
ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so.6 # 建立新的软连接
ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so    # 建立新的软连接
4，如果全部都不支持，则需要更新系统的libstdc++，每个系统不同，需自行查找

**Comment by xiyuanyuan0506** [comment]
> 这个问题是环境中GLIBCXX版本的问题，libstdc++.so.6: version `GLIBCXX_3.4.32' 1，使用sudo find / -name "libstdc++.so.6*"命令找到系统中所有的libstdc++ 2，使用strings /usr/lib/libstdc++.so.6 | grep GLIBCXX，这里路径替换成上面找到的so文件，依次查找该库是否支持GLIBCXX_3.4.32 3，如果支持，删除当前环境中的libstdc++.so和libstdc++.so.6，然后建立软连接过去。 例如我这里： cd ~/.conda/envs/vllm-latest/lib #这里使用conda建立沙箱环境，名称为vllm-latest，进入对应的lib目录 rm libstdc++.so.6 # 删除软连接 rm libstdc++.so ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so.6 # 建立新的软连接 ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so # 建立新的软连接 4，如果全部都不支持，则需要更新系统的libstdc++，每个系统不同，需自行查找

这个项目一定要支持GLIBCXX_3.4.32吗？

**Comment by xiyuanyuan0506** [comment]
> > 这个问题是环境中GLIBCXX版本的问题，libstdc++.so.6: version `GLIBCXX_3.4.32' 1，使用sudo find / -name "libstdc++.so.6*"命令找到系统中所有的libstdc++ 2，使用strings /usr/lib/libstdc++.so.6 | grep GLIBCXX，这里路径替换成上面找到的so文件，依次查找该库是否支持GLIBCXX_3.4.32 3，如果支持，删除当前环境中的libstdc++.so和libstdc++.so.6，然后建立软连接过去。 例如我这里： cd ~/.conda/envs/vllm-latest/lib #这里使用conda建立沙箱环境，名称为vllm-latest，进入对应的lib目录 rm libstdc++.so.6 # 删除软连接 rm libstdc++.so ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so.6 # 建立新的软连接 ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so # 建立新的软连接 4，如果全部都不支持，则需要更新系统的libstdc++，每个系统不同，需自行查找
> 
> 这个项目一定要支持GLIBCXX_3.4.32吗？

我的环境执行string之后显示：
![image](https://github.com/vllm-project/vllm/assets/64192773/0a5a9ed3-520d-43d2-b843-d866d52c1637)

**Comment by andyli386** [comment]
> > 这个问题是环境中GLIBCXX版本的问题，libstdc++.so.6: version `GLIBCXX_3.4.32' 1，使用sudo find / -name "libstdc++.so.6*"命令找到系统中所有的libstdc++ 2，使用strings /usr/lib/libstdc++.so.6 | grep GLIBCXX，这里路径替换成上面找到的so文件，依次查找该库是否支持GLIBCXX_3.4.32 3，如果支持，删除当前环境中的libstdc++.so和libstdc++.so.6，然后建立软连接过去。 例如我这里： cd ~/.conda/envs/vllm-latest/lib #这里使用conda建立沙箱环境，名称为vllm-latest，进入对应的lib目录 rm libstdc++.so.6 # 删除软连接 rm libstdc++.so ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so.6 # 建立新的软连接 ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so # 建立新的软连接 4，如果全部都不支持，则需要更新系统的libstdc++，每个系统不同，需自行查找
> 
> 这个项目一定要支持GLIBCXX_3.4.32吗？

应该是的，我也是更新到最新版vllm之后遇到同样问题的。按我上面给的步骤就解决了。



> > > 这个问题是环境中GLIBCXX版本的问题，libstdc++.so.6: version `GLIBCXX_3.4.32' 1，使用sudo find / -name "libstdc++.so.6*"命令找到系统中所有的libstdc++ 2，使用strings /usr/lib/libstdc++.so.6 | grep GLIBCXX，这里路径替换成上面找到的so文件，依次查找该库是否支持GLIBCXX_3.4.32 3，如果支持，删除当前环境中的libstdc++.so和libstdc++.so.6，然后建立软连接过去。 例如我这里： cd ~/.conda/envs/vllm-latest/lib #这里使用conda建立沙箱环境，名称为vllm-latest，进入对应的lib目录 rm libstdc++.so.6 # 删除软连接 rm libstdc++.so ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so.6 # 建立新的软连接 ln -s /usr/lib/libstdc++.so.6.0.32 libstdc++.so # 建立新的软连接 4，如果全部都不支持，则需要更新系统的libstdc++，每个系统不同，需自行查找
> > 
> > 
> > 这个项目一定要支持GLIBCXX_3.4.32吗？
> 
> 我的环境执行string之后显示： ![image](https://private-user-images.githubusercontent.com/64192773/323049997-0a5a9ed3-520d-43d2-b843-d866d52c1637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzc4NjMsIm5iZiI6MTcxMzMzNzU2MywicGF0aCI6Ii82NDE5Mjc3My8zMjMwNDk5OTctMGE1YTllZDMtNTIwZC00M2QyLWI4NDMtZDg2NmQ1MmMxNjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3MDYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDcwNDA5ZGFjMjIzNTJkNzVlOTBjODdlNDNkNzcxYjM5ZTVmNWE0YmY3YjY0NjkxMzIwZjc4MjU5NzlmNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vgcF_WzS2KLaoqBYe-fIlS8ABY9sG0-2PFQkERD77No)

看看你这个系统如何更新libstdc++吧

**Comment by richardliaw** [comment]
Ran into this as well but reinstalling with `requirements-dev.txt` fixed this for me

```
pip install -U  -r requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cu121
pip install --no-cache --no-build-isolation -U -e .
```

**Comment by KehaoWu** [comment]
> Ran into this as well but reinstalling with `requirements-dev.txt` fixed this for me
> 
> ```
> pip install -U  -r requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cu121
> pip install --no-cache --no-build-isolation -U -e .
> ```

it works.
