### ISSUE TITLE
[Doc]: Will both the prompts and generated kv cache reuse if `enable_prefix_caching` flag is ON? 

### ISSUE THREAD

**Issue by DefTruth** [vllm-project/vllm#4104]
### 📚 The doc issue

will both the prompts and generated kv cache reuse if `enable_prefix_caching` flag is ON? In SGLang paper, they describe RadixAttention:  
```text 
Instead of discarding the KV cache after finishing a generation request, our
approach retains the KV cache for both prompts and generation results in a radix tree. 
```
Assuming the first request is A and that vllm generates B, if the second request is A+B+C, will A+B already be cached?

**Comment by robertgshaw2-neuralmagic** [comment]
Yes, the prefix caching feature implements the strategy described in the SGLang paper

**Comment by DefTruth** [comment]
many thanks~

**Comment by wizard1203** [comment]
> ### 📚 The doc issue
> will both the prompts and generated kv cache reuse if `enable_prefix_caching` flag is ON? In SGLang paper, they describe RadixAttention:
> 
> ```
> Instead of discarding the KV cache after finishing a generation request, our
> approach retains the KV cache for both prompts and generation results in a radix tree. 
> ```
> 
> Assuming the first request is A and that vllm generates B, if the second request is A+B+C, will A+B already be cached?
> 
> ### Suggest a potential alternative/fix
> _No response_

Hi, is any one know that whether transformers supports such prefix caching?
