### ISSUE TITLE
is cpu only support?

### ISSUE THREAD

**Issue by callMeMakerRen** [vllm-project/vllm#412]
i try to test the lib,but seems it needs cuda to build,i wonder if cpu only is ok to run ,and if the speed is also up compare to the origin llama.cpp. and i wonder if prompt process can alse be speed up like this.

**Comment by WoosukKwon** [comment]
Hi @callMeMakerRen, thanks for the question and feature request. Currently, we does not support CPU-only mode. We assume all the model execution is performed on NVIDIA GPUs.

>  if the speed is also up compare to the origin llama.cpp. and i wonder if prompt process can alse be speed up like this.

Currently, the focus of vLLM is on increasing the LLM serving throughput (i.e., batching more requests at a time) by efficiently utilizing GPU memory. In contrast, IIUC, llama.cpp focuses on optimizing the latency when a single request is provided.
