### ISSUE TITLE
[Feature]: Support HuggingFaceM4/idefics2-8b as vision model

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#4124]
### 🚀 The feature, motivation and pitch

I know even llava 1.6 isn't in, but benchmarks for this model are much better.

https://huggingface.co/HuggingFaceM4/idefics2-8b
https://huggingface.co/blog/idefics2

![image](https://github.com/vllm-project/vllm/assets/2249614/539c9454-2933-481c-9765-a82b14bc182a)

TGI support coming according to model card discussion, but no PR in TGI yet for 2, but seems idefics is there.

### Alternatives

llava1.6, but maybe obsolete by now.

**Comment by jc9123** [comment]
I will work on implementing this model.

**Comment by MahdiPresario001** [comment]
Any progress on this?

**Comment by dipta007** [comment]
Any update here? Thanks.
