### ISSUE TITLE
bloom loading KeyError

### ISSUE THREAD

**Issue by AlvL1225** [vllm-project/vllm#413]
codes from vllm.model_executor.models.bloom.BloomForCausalLM
<img width="545" alt="image" src="https://github.com/vllm-project/vllm/assets/36012554/52fa048a-50a6-44a8-a849-fbc903b1842c">
this part will add 'transformer.' prefix to the lm_head which does not match the huggingface bloom key:
<img width="709" alt="image" src="https://github.com/vllm-project/vllm/assets/36012554/ead034c4-1f72-4b77-b76c-01960d76a979">

**Comment by Hukongtao** [comment]
I met the same error. how did you solve it?

**Comment by Hukongtao** [comment]
![image](https://github.com/vllm-project/vllm/assets/16505966/7ba7df22-492f-4f28-bb02-38dc5f816d31)

**Comment by Hukongtao** [comment]
@WoosukKwon Do you have a plan to fix this?
