### ISSUE TITLE
[Feature]: Phi2 LoRA support

### ISSUE THREAD

**Issue by zero-or-one** [vllm-project/vllm#4141]
### Please, add the LoRA support for PhiForCausalLM.

"ValueError: Model PhiForCausalLM does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github."

**Comment by jeejeelee** [comment]
You can  refer to https://github.com/vllm-project/vllm/pull/3949/files to complete this feature.
