### ISSUE TITLE
[Usage]: if I want to run a 34B model，like yi-34B-chat,how can I use  multi GPU,I just have A100 40G

### ISSUE THREAD

**Issue by hellostronger** [vllm-project/vllm#4147]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by hellostronger** [comment]
i have tried  engine_use_ray = True  in AsyncEngineArgs  or   CUDA_VISIBLE_DEVICES = 0,1  but it still  does not work  ,GPU0  OOM

**Comment by kir1to00** [comment]
use tensor-parallel-size

**Comment by hellostronger** [comment]
thk, the problem that GPU0  OOM is solved, but new problem is come,it shows ValueError: When using LoRA, vocab size must be 32000 >= vocab_size <= 33024 ,anybody can load the yi-34B-chat with lora successfuly? hoping your suggestion

**Comment by kir1to00** [comment]
> thk, the problem that GPU0 OOM is solved, but new problem comes ,it shows " ValueError: When using LoRA, vocab size must be 32000 >= vocab_size <= 33024 " ,anybody can load the yi-34B-chat with lora successfuly? hoping your suggestioncu

maybe use max-model-len?

**Comment by jeejeelee** [comment]
> thk, the problem that GPU0 OOM is solved, but new problem comes ,it shows " ValueError: When using LoRA, vocab size must be 32000 >= vocab_size <= 33024 " ,anybody can load the yi-34B-chat with lora successfuly? hoping your suggestion

"ValueError: When using LoRA, vocab size must be 32000 >= vocab_size <= 33024" has already been resolved by https://github.com/vllm-project/vllm/pull/4015. You can build the source from the main branch or wait for the 0.4.1 release. After resolving this issue, Yi-34 can load LoRA successfully.

**Comment by riverind** [comment]
> use tensor-parallel-size

however，use  tensor-parallel-size=2 is also oom，
