### ISSUE TITLE
I want use the function prefix_allowed_tokens_fn of huggingface model.generate(), where of vllm's source code shall I modify?

### ISSUE THREAD

**Issue by zoubaihan** [vllm-project/vllm#415]
Hello, we all know that in huggingface transformers' origin `model.generate()` method, we can set the function paremeter `prefix_allowed_tokens_fn` to restrict the generation rule. I want to use this function in vllm just like I used in origin `model.generate()` to control the generation process, could you please tell me where of the source code shall I modify to make the model generation obey my custom prefix_allowed_tokens_fn?

**Comment by zhuohan123** [comment]
This is related to #379. You can add `logit_bias` as a parameter of `SamplingParams`. Then you can add this bias when sampling for the results to not generate some specific tokens, similar to what we are doing for `embedding_bias` from the models:

https://github.com/vllm-project/vllm/blob/20b0d88d1630aec3a18a80590080b0ab1d16969f/vllm/model_executor/layers/sampler.py#L48-L49

Feel free to contribute to this feature! It will be very helpful for many use cases.

**Comment by Etelis** [comment]
I will try implementing this!

Thanks.

**Comment by hmellor** [comment]
Functionality of `prefix_allowed_tokens_fn ` can be achieved using logit processes, as per https://github.com/vllm-project/vllm/pull/2434#issuecomment-1894254917
