### ISSUE TITLE
[Feature]:  AMD ROCm 6.1 Support

### ISSUE THREAD

**Issue by kannan-scalers-ai** [vllm-project/vllm#4152]
### 🚀 The feature, motivation and pitch

[AMD ROCm 6.1](https://github.com/ROCm/ROCm/releases/tag/rocm-6.1.0) has been released with significant performance improvements for AMD GPUs, including the MI300X.. When can we expect support for ROCm 6.1 on vLLM?

**Comment by gardner** [comment]
Have you tried building for 6.1? What results do you get?

**Comment by hongxiayang** [comment]
@kannan-scalers-ai  ROCm 6.1 is supported in the current main branch now. Please check and close this issue.

**Comment by kannan-scalers-ai** [comment]
@hongxiayang thanks for the update.
