### ISSUE TITLE
[Bug]: AMD test randomly fails due to OOM

### ISSUE THREAD

**Issue by DarkLight1337** [vllm-project/vllm#4172]
### Your current environment

CI environment

### 🐛 Describe the bug

A lot of CI runs are getting stuck/failing at the AMD part. Seems that OOM occurs during the AMD test which causes port 8000 to be unreachable. Due to the long timeout, the duration of CI runs has gone up dramatically.

**Comment by shajrawi** [comment]
We are working on this - CI machine config issue not the backend itself. Hopefully we will have a fix in the next couple of days.

**Comment by DarkLight1337** [comment]
This issue appears to have been fixed - the AMD tests no longer fail in the CI pipelines for my PRs. Thanks for fixing this issue!

**Comment by DarkLight1337** [comment]
The AMD tests no longer fail in the CI pipelines for my PRs. Thanks for fixing this issue!
