### ISSUE TITLE
[Performance]: Questions about Distributed Inference: A comparison of the two deployment approaches

### ISSUE THREAD

**Issue by hwb96** [vllm-project/vllm#4184]
### Misc discussion on performance

When deploying two GPUs for a vllm service, there are two approaches. The first method involves starting two ports and services, with one vllm service running on each GPU, and using Nginx to implement load balancing. The second approach entails starting a single port and service, utilizing tensor_parallel_size=2, and distributing the model weights across different GPUs. Which of these methods is better, and why?

This problem has been bothering me, I need your help, thank you.

**Comment by youkaichao** [comment]
If the model is too large to fit in single GPU, then you have to use `tensor_parallel_size`. If not, start two vllm on two GPUs would be better. `tensor_parallel_size=2` requires communication between GPUs, which is quite expensive and complicated.

**Comment by hwb96** [comment]
> If the model is too large to fit in single GPU, then you have to use `tensor_parallel_size`. If not, start two vllm on two GPUs would be better. `tensor_parallel_size=2` requires communication between GPUs, which is quite expensive and complicated.如果模型太大而无法放入单个 GPU，则必须使用 `tensor_parallel_size` .如果没有，在两个 GPU 上启动两个 vllm 会更好。 `tensor_parallel_size=2` 需要GPU之间的通信，这非常昂贵和复杂。

Thank you for answering my questions.
