### ISSUE TITLE
[Feature]: Request for Status Monitoring API in vLLM openai Server

### ISSUE THREAD

**Issue by dalan2014** [vllm-project/vllm#4185]
### 🚀 The feature, motivation and pitch

I propose the addition of a status monitoring API to the vLLM openai server to provide real-time performance metrics. This feature would enhance visibility into the system's current state and facilitate dynamic adjustments of operational parameters based on live data.

The status API could be integrated into the existing python -m vllm.entrypoints.openai.api_server command, offering a /status endpoint that returns the current operational metrics in JSON format. This would make it easy to integrate into existing monitoring systems and dashboards.

Here's an example of a JSON response:
```
{
  "status": "success",
  "timestamp": "2024-04-19T17:51:39Z",
  "metrics": {
    "average_prompt_throughput": {
      "value": 48.3
    },
    "average_generation_throughput": {
      "value": 56.9
    },
    "requests": {
      "running": 3,
      "swapped": 0,
      "pending": 0
    },
    "gpu_kv_cache_usage": {
      "value": 40.1
    },
    "cpu_kv_cache_usage": {
      "value": 0.0
    }
  }
}
```

Adding a status monitoring API to vLLM would significantly contribute to its usability and efficiency. It would provide users like myself with the necessary tools to optimize our deployments effectively. I am eager to discuss this further and would appreciate your feedback on this proposal.

### Alternatives

Prior to suggesting the addition of a dedicated status API, I explored the possibility of capturing log outputs directly from the vLLM server. While this method does provide some insight into the system's performance, it is cumbersome and not as efficient or reliable for real-time monitoring. Parsing log files or outputs is prone to errors and requires additional setup and maintenance that could be streamlined through an API.

**Comment by simon-mo** [comment]
Try querying `/metrics`? It should already expose them in Prometheus format, which is also easy to parse. See https://docs.vllm.ai/en/latest/serving/metrics.html
