### ISSUE TITLE
Modify the current PyTorch model to C++

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#42]
Expected gain: For 13B models, we should see a 20%-30% latency gain on a single GPU and 2-3x on 4 GPUs. For smaller models, the gain should be even higher.

Having a single iteration's computation being completely C++ should be enough for high performance. In this way, we can keep most complicated scheduling logics in Python, including weight loading.

Potential sources of overheads:
1. Python v.s. C++.
2. PyTorch (even in C++) v.s. FasterTransformer.

How to implement a C++ version:
1. (Fake C++) Torch compiler (torch.jit).
2. Libtorch, C++ version of PyTorch (easier to implement and extend, but can only solve overhead 1).
3. Prune out the useful single model code from FasterTransformer to CacheFlow. This solves both overheads but is harder to implement.

**Comment by hmellor** [comment]
@zhuohan123 can this work be considered complete?

**Comment by amrobbins** [comment]
If interested, I've been building a c++ native deep learning framework for the past few years that I want to get open sourced soon. This framework aims for optimal performance, here is my framework training AlexNet, mostly the kernels here are cublasLt and cuDNN:

<img width="828" alt="image" src="https://github.com/vllm-project/vllm/assets/17150932/176ae6c1-57b1-4bb1-8e5f-dec51bb2af3c">

I'd certainly like for it to be part of VLLM. Is this something that there'd be interest in? If so I can go ensure that I support (or add support) for all of the pieces that you need and get it connected. I can provide access to the private repo if requested.

**Comment by hmellor** [comment]
Presumably this is stale/not relevant anymore
