### ISSUE TITLE
[Doc]: Engine arguments of lora are not shown in VLLM docs on homepage

### ISSUE THREAD

**Issue by arunpatala** [vllm-project/vllm#4204]
### 📚 The doc issue

The lora arguments are not shown on this page. 

https://docs.vllm.ai/en/latest/models/engine_args.html

### Suggest a potential alternative/fix

Add latest documentation from source code

**Comment by jeejeelee** [comment]
Welcome to contribute this :smiley:

**Comment by arunpatala** [comment]
thanks for adding this.
