### ISSUE TITLE
[Misc]:  When is the v0.4.1 will be available on Pypi ?

### ISSUE THREAD

**Issue by omarsou** [vllm-project/vllm#4206]
### Anything you want to discuss about vllm.

Hello,

Due to some vpn restrictions, Im not able to clone the git and install it from source. The only way is to install it from Pypi. But the 0.4.1 is not available there, do you know when will it be available ?

thank you

**Comment by jvmncs** [comment]
presumably when everything in this ticket is resolved they'll trigger a full release https://github.com/vllm-project/vllm/issues/4181
