### ISSUE TITLE
Performance Regression between v0.4.0 and v0.4.1

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#4210]
### Anything you want to discuss about vllm.

#3550 seems to reduce throughput of vLLM

Before: Throughput: 20.13 requests/s, 10308.29 tokens/s
After: Throughput: 17.67 requests/s, 9048.03 tokens/s

(reported by @esmeetu and @youkaichao)

**Comment by rkooo567** [comment]
@simon-mo I can do investigation this Sun. Unfortunately, I have plans this weekends already made that I cannot cancel...

**Comment by njhill** [comment]
For future reference, this was addressed by #4280.
