### ISSUE TITLE
[Feature]: beam search mode to allow for more options in sampling process

### ISSUE THREAD

**Issue by GeauxEric** [vllm-project/vllm#4215]
### 🚀 The feature, motivation and pitch

The current implementation of beam search is a very simplified version, which seems to follow the description in the paper "Sequence to Sequence Learning with Neural Networks":
> a simple left-to-right beam search decoder which maintains a small number B of partial hypotheses, where a partial hypothesis is a prefix of some translation. At each timestep we extend each partial hypothesis in the beam with every possible word in the vocabulary. This greatly increases the number of the hypotheses so we discard all but the B most likely hypotheses according to the model’s log probability. As soon as the“<EOS>” symbol is appended to a hypothesis, it is removed from the beam and is added to the set of complete hypotheses.

The beam search outcomes is predominantly influenced by the beam width when responding to a specific prompt, which can significantly constrain the creativity of the generated outputs. Creativity is a critical component in many LLM applications.

I would like to support more options in beam search, i.e., be able to set non-zero temperature, top_k and top_p in the sampling parameter. It is currently denied by the function:
```
 def _verify_beam_search(self) -> None:
        if self.best_of == 1:
            raise ValueError("best_of must be greater than 1 when using beam "
                             f"search. Got {self.best_of}.")
        if self.temperature > _SAMPLING_EPS:
            raise ValueError("temperature must be 0 when using beam search.")
        if self.top_p < 1.0 - _SAMPLING_EPS:
            raise ValueError("top_p must be 1 when using beam search.")
        if self.top_k != -1:
            raise ValueError("top_k must be -1 when using beam search.")
```

**Comment by shyringo** [comment]
vote for this.

**Comment by Jack-mi** [comment]
Vote for this 2 but I think maybe diverse beam search is better choice? (https://arxiv.org/pdf/1610.02424)
