### ISSUE TITLE
[Bug]: vllm/outputs.py: RequestOutput.from_seq_group sets the wrong index for generated `CompletionOutput`s, causing IndexError in OpenAIServingChat.chat_completion_stream_generator

### ISSUE THREAD

**Issue by elementary-particle** [vllm-project/vllm#4220]
### Your current environment

```text
vLLM Version: 0.4.1
```

### 🐛 Describe the bug

The chat completion stream generator expects the `index` field to be a number in range(request.n).

vllm/entrypoints/openai/serving_chat.py:177
```python 
                for output in res.outputs:
                    i = output.index

                    if finish_reason_sent[i]:
                        continue
```

However, RequestOutput.from_seq_group sets index to seqs.index(seq).

vllm/outputs.py:116
```python
        outputs = [
            CompletionOutput(seqs.index(seq),
                             seq.get_output_text_to_return(text_buffer_length),
                             seq.get_output_token_ids(),
                             seq.get_cumulative_logprob(),
                             seq.output_logprobs if include_logprobs else None,
                             SequenceStatus.get_finished_reason(seq.status),
                             seq.stop_reason) for seq in top_n_seqs
        ]
```

where top_n_seqs is the top scored sequences and seqs is the *unsorted* original sequence list.
Thus the indexes could be out of range (requests.n).

This will cause a list index out of range error in the streaming generator.

**Comment by youkaichao** [comment]
Can you send a pr and add test case for it?

**Comment by elementary-particle** [comment]
I could submit a PR for this issue. To reproduce, simply set use_best_of to a big number and use_beam_search to True.

**Comment by elementary-particle** [comment]
I made some further investigation into the issue and I think the current implementation of beam searching and streaming is incompatible and required some major changes.

In a streaming scenario, the client must maintain the state of *all* the best sequence s, since the next tokens could follow any one of them.
In the case of beam searching, additional info on which parent sequence the current completion chunks are following must be supplied as well.

**Comment by elementary-particle** [comment]
If we want streaming to work with multiple sequences, we must mandate maintenance of all of them on the client side.
Beam search could override the existing sequences, so the client must be informed which to follow as well.
