### ISSUE TITLE
[Feature]: Multi-node serving

### ISSUE THREAD

**Issue by jordane95** [vllm-project/vllm#4221]
### 🚀 The feature, motivation and pitch

Recently, there are larger models which couldn't be deployed on one machine, such as grok. Can we support efficient multi-node serving?

**Comment by hyperbolic-c** [comment]
What is the difference between this feature and ray in the server mode?

**Comment by jordane95** [comment]
While ray can support multi-node serving, the multi-node support is not so perfect. I am not sure if you have used it, but in my case, there are many problems. For example, when the master node is dead, it is possible that the remaining workers didn't get the finalizing signal and get hanging till being killed by timeout.

**Comment by hyperbolic-c** [comment]
@jordane95 Yes, I got the same error too. I am also finding if ray can support muti-node serving on CPU, do you know any solutions? Thanks !
