### ISSUE TITLE
Pydantic v2 breaking FastAPI & Ray

### ISSUE THREAD

**Issue by anttttti** [vllm-project/vllm#423]
Pydantic v2 came out last week. It seems to be breaking some dependencies, including those used by VLLM. 

Pydantic v2 throws an error on serializing Ray results, at least pydantic.fields.ModelField. Current VLLM requirements.txt doesn't specify the version of Pydantic, so v2 can get installed.

Until requirements.txt gets updated with version for Pydantic or depending libraries fix their compatibilities, you can do "pip install pydantic==1.10.11" to fix issues.

**Comment by jens-create** [comment]
Any news on this issue?

**Comment by Changgeng-Wei** [comment]
> Pydantic v2 came out last week. It seems to be breaking some dependencies, including those used by VLLM.
> 
> Pydantic v2 throws an error on serializing Ray results, at least pydantic.fields.ModelField. Current VLLM requirements.txt doesn't specify the version of Pydantic, so v2 can get installed.
> 
> Until requirements.txt gets updated with version for Pydantic or depending libraries fix their compatibilities, you can do "pip install pydantic==1.10.11" to fix issues.

Current VLLM requirements.txt  specify the version of Pydantic to "pydantic>=2.0", but thd issue still occur

**Comment by ruifengma** [comment]
> > Pydantic v2 came out last week. It seems to be breaking some dependencies, including those used by VLLM.
> > Pydantic v2 throws an error on serializing Ray results, at least pydantic.fields.ModelField. Current VLLM requirements.txt doesn't specify the version of Pydantic, so v2 can get installed.
> > Until requirements.txt gets updated with version for Pydantic or depending libraries fix their compatibilities, you can do "pip install pydantic==1.10.11" to fix issues.
> 
> Current VLLM requirements.txt specify the version of Pydantic to "pydantic>=2.0", but thd issue still occur

exactly the same issue here @jens-create
