### ISSUE TITLE
[Misc]: is it possible to load lora adapter on request basis with out restarting the base model for every new lora trained?

### ISSUE THREAD

**Issue by Wizmak9** [vllm-project/vllm#4234]
### Anything you want to discuss about vllm.

is it possible to load lora adapter on request basis with out restarting the base model for every new lora trained?

**Comment by DavidPeleg6** [comment]
hi :) i uploaded the following PR to do so:
[https://github.com/vllm-project/vllm/pull/3850](url)

assuming the adapter is already in the disk of your deployed pod, you can use the following format of request:
`{
         "model": "adapter_name",
         "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": "Who won the world series in 2020?"}
            ],
"lora_request": {"lora_name":"adapter_name","lora_local_path":"/home/adapters/adapter_folder"}
         "max_tokens": 64,
         "temperature": 0
     }`

after the first load, you can stop using the lora_request every time and just use the model name.
Also, note that this branch is updated to vllm 0.4.0post1

**Comment by Wizmak9** [comment]
Cool thanks buddy, let me give it a try!!

**Comment by Wizmak9** [comment]
I have tried it but its still not full version. thanks for it :) ! closing the request..

**Comment by markovalexander** [comment]
@Wizmak9 did it work for you? I see that PR by @DavidPeleg6 was not merged

**Comment by Wizmak9** [comment]
@markovalexander no it didn't worked for me building some internal solution to handle.
