### ISSUE TITLE
[Doc]: Need to update the page of adding new models

### ISSUE THREAD

**Issue by YeFD** [vllm-project/vllm#4235]
### 📚 The doc issue

https://docs.vllm.ai/en/latest/models/adding_model.html#register-your-model

The `_MODEL_REGISTRY ` in [vllm/model_executor/model_loader.py](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/model_loader.py) was removed, and documentation of registering models needs to update about .

Although @esmeetu in https://github.com/vllm-project/vllm/issues/3075#issuecomment-1970071404_ mentioned it will update later but for now it can not accommodate this change yet.

### Suggest a potential alternative/fix

Finally, include your `*ForCausalLM` class in [vllm/model_executor/models/\_\_init__.py](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/__init__.py) and register it to the `_MODELS` in [vllm/model_executor/models/\_\_init__.py](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/__init__.py).

**Comment by youkaichao** [comment]
can you file a pr to improve the doc?
