### ISSUE TITLE
Llama-3-70b: Should I apply some special template to use llama-3?

### ISSUE THREAD

**Issue by UbeCc** [vllm-project/vllm#4239]
### The model to consider.

When I directly use these sentences as prompts, I got abnormal response.
<img width="520" alt="image" src="https://github.com/vllm-project/vllm/assets/70007833/76624d56-61d7-402b-ba00-cfa768cd7e89">
<img width="1362" alt="image" src="https://github.com/vllm-project/vllm/assets/70007833/625e0ac5-335c-46d4-abb8-9b9d88878c98">

Should I apply special template for llama3?

### What's your difficulty of supporting the model you want?

Special template document?

**Comment by Warit314** [comment]
Hi!, did you solved this problem? And could you explain how you solved it?? my llama3 8b instruct response is so weird right now.

**Comment by UbeCc** [comment]
> Hi!, did you solved this problem? And could you explain how you solved it?? my llama3 8b instruct response is so weird right now.

Just change tokenizer's pad_id to eos_id works. You can see the official repo to get the hands-on instruction.

Here is the url:
https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct
