### ISSUE TITLE
How to abort streaming request?

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#4240]
### Your current environment

vllm 0.3.0
ray 2.9.2

### 🐛 Describe the bug

If I have a streaming request, and I need to stop the request from continue generating tokens, how? if I have the following endpoint?
Or how to abort a streaming request in VLLM as general? 

`In ray_serv.py`

```
from ray import serve
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from fastapi.responses import JSONResponse, StreamingResponse
from vllm import AsyncEngineArgs, AsyncLLMEngine

from protocol import ChatCompletionRequest, ErrorResponse
from serving_chat import OpenAIServingChat

app = FastAPI()

@serve.deployment(
    ray_actor_options={"num_gpus": 1},

)
@serve.ingress(app)
class OpenLLMDeployment:
    def __init__(self) -> None:

        ENGINE_ARGS = AsyncEngineArgs(
            gpu_memory_utilization= 0.95,
            model="path/to/model",
            max_model_len=4096,            
        )
        self.engine = AsyncLLMEngine.from_engine_args(ENGINE_ARGS)

    @app.post("/v1/chat/completions")
    async def create_chat_completion(request: ChatCompletionRequest,
                                 raw_request: Request):
        generator = await OpenAIServingChat.create_chat_completion(
            request, raw_request)
        if isinstance(generator, ErrorResponse):
            return JSONResponse(content=generator.model_dump(),
                            status_code=generator.code)
        if request.stream:
            return StreamingResponse(content=generator,
                                 media_type="text/event-stream")
        else:
            return JSONResponse(content=generator.model_dump())
        
service = OpenLLMDeployment.bind()
```

I run it as following:
`serve run ray_serv:service --port  5000 --host 0.0.0.0`

**Comment by simon-mo** [comment]
You should ask in the Ray repo for how does Ray Serve handle disconnection now. For the vLLM side, you can use `abort`:

https://github.com/vllm-project/vllm/blob/3d925165f2b18379640a63fbb42de95440d63b64/vllm/entrypoints/openai/serving_completion.py#L193-L198

**Comment by James4Ever0** [comment]
Please consider reopen this issue. I have better workarounds without explicitly aborting connection (as most clients and servers will fail to abort connection if logic is nested too deep) based on soft and hard limits, effectively improving overall performance.

**Comment by kmamine** [comment]
What was the workaround ?
