### ISSUE TITLE
[Feature]: Cannot use FlashAttention backend for Volta and Turing GPUs. (but FlashAttention v1.0.9 supports Turing GPU.)

### ISSUE THREAD

**Issue by tutu329** [vllm-project/vllm#4246]
### 🚀 The feature, motivation and pitch

Turing GPU can use FlashAttention v1.0.9 which can reduce use of vram significantly.

FlashAttention has no plan to support Turing GPU in FlashAttention v2 actually.
so please support FlashAttention v1.0.9. thanks a lot!

many friends having 8*2080ti need this help.

**Comment by JayLiu7319** [comment]
+1, if it can support GPUs based on Turing architecture, that would be great.

**Comment by epochaudio** [comment]
+1

**Comment by Print1n** [comment]
+1, if it can support GPUs based on Turing architecture, that would be great

**Comment by HelloCard** [comment]
any update?

**Comment by Iori-yimaga** [comment]
+1, if it can support GPUs based on Turing architecture, that would be great
