### ISSUE TITLE
[Doc]: How is the support for chunked prefill?

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#4255]
### 📚 The doc issue

I notice some PRs about this, but can't find documentation about it. Is it supported now?

**Comment by rkooo567** [comment]
Yeah I will create a doc about it after the logprob PR is merged https://github.com/vllm-project/vllm/pull/4139

**Comment by sleepwalker2017** [comment]
> Yeah I will create a doc about it after the logprob PR is merged #4139

Is chunked prefill enabled by default in vllm? 
I see the token num for inference is large, usually multi hundred. but my running batch is small, about 16 or 24. 

Does the vllm 0.4.0 enable this feature already?

**Comment by rkooo567** [comment]
it is not on by default. vLLM has default num batched tokens == max model len & num max seqs == 256. If you see only small # of requests are batched, it is likely you don't have enough kv caches.

**Comment by rkooo567** [comment]
For example, try increasing TP, and you can probably see more tokens being batched

**Comment by sleepwalker2017** [comment]
I see that the 1st dim of hidden state is always more than 200. In fact on my machine vllm can only process 16 sequence concurrently.
But I have never seen the 1st dim of hidden state be 16 or less.
If no chrunked prefill, the shape should be at most 16 when running deciding, right?





------------------ Original ------------------
From: SangBin Cho ***@***.***&gt;
Date: Wed,Apr 24,2024 10:13 PM
To: vllm-project/vllm ***@***.***&gt;
Cc: fade_away ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vllm-project/vllm] [Doc]: How is the support for chunkedprefill? (Issue #4255)





 
For example, try increasing TP, and you can probably see more tokens being batched

**Comment by rkooo567** [comment]
are you talking about hidden state of the entire model run?

**Comment by sleepwalker2017** [comment]
> are you talking about hidden state of the entire model run?

I mean the input and output of each Decoder layer.

I start a vllm server ,and send requests one by one.  I keep the num of clients 16.

Then I print the 1st dim of hidden states.
I find there is no pure token generation phase. 
If vllm is running pure token generation, the 1st dim of hidden state must be the batch size, right?
I can't see the 1st dim become less than 16. It's usually 200+.

why is that?

**Comment by sleepwalker2017** [comment]
> are you talking about hidden state of the entire model run?

I think I find why.

The vllm cudagraph mode captures token generation cuda kernels, and when running token generation, it doesn't run layer inference, but only replay the cudagraph. I add logs in the llama.py file.So my logs are not printed.  Is that the fact?

**Comment by rkooo567** [comment]
ah yeah. if decode step is running with cuda graph, and if you add print to python code, it is not executed because cuda graph only executes GPU kernels
