### ISSUE TITLE
[Feature]: Add argument terminators "eos_token_id" to serving models api_server.py

### ISSUE THREAD

**Issue by Alvaro8gb** [vllm-project/vllm#4260]
### 🚀 The feature, motivation and pitch

New models as LLama-3 use different end terminator, that are need to be specified. 
For example when using the API the client response return "me know if this is correct!<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nThat\'s correct! The output is", thats seems the roles are not well parsed.

**Comment by hammoudhasan** [comment]
+1

**Comment by DarkLight1337** [comment]
Solved by #4182
