### ISSUE TITLE
Support for baichuan models

### ISSUE THREAD

**Issue by Mr-Nineteen** [vllm-project/vllm#428]
Support for baichuan models，model address：

- https://huggingface.co/baichuan-inc/Baichuan-13B-Chat
- https://huggingface.co/baichuan-inc/Baichuan-13B-Base

**Comment by WoosukKwon** [comment]
Hi @Mr-Nineteen, thanks for the request! To my understanding, Baichuan's architecture is GPT + ALiBi (which is essentially the same as BLOOM and MPT), right? If yes, it'll be pretty easy to add the model to vLLM.

**Comment by zhuohan123** [comment]
Fixed by #643
