### ISSUE TITLE
[Feature]: What should I do if I want to use llama3 in vllm-0.2.1.post1?

### ISSUE THREAD

**Issue by Fu-Dayuan** [vllm-project/vllm#4288]
### 🚀 The feature, motivation and pitch

I have a lower cuda (11.7), so I can not install latest version vllm successfully, can you tell me how to change the code in  vllm-0.2.1.post1 or add llama3 in past version?

**Comment by youkaichao** [comment]
follow https://docs.nvidia.com/cuda/cuda-installation-guide-linux/ to install a cuda toolkit locally, and follow https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source to use that cuda. you don't even need sudo . 0.2.1 is too old for us to help.
