### ISSUE TITLE
[New Model]: launch error of Qwen1.5-MoE-A2.7B-Chat-GPTQ-Int4

### ISSUE THREAD

**Issue by eigen2017** [vllm-project/vllm#4331]
### The model to consider.

https://modelscope.cn/models/qwen/Qwen1.5-MoE-A2.7B-Chat-GPTQ-Int4/

### The closest model vllm already supports.

https://modelscope.cn/models/qwen/Qwen1.5-MoE-A2.7B-Chat/

### What's your difficulty of supporting the model you want?

launch error： MergedColumnParallelLinear object has no attribute weight

**Comment by jeejeelee** [comment]
Currently, vllm does not support the qwen-moe quantization

**Comment by wellcasa** [comment]
Kneeling for support, qwen moe.

**Comment by li904775857** [comment]
Kneeling for support, qwen moe.
