### ISSUE TITLE
[Bug]: Invalid inputs do not result in error

### ISSUE THREAD

**Issue by dyastremsky** [vllm-project/vllm#4339]
### Your current environment

Start vLLM: ```docker run --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model gpt2 --dtype float16 --max-model-len 1024```

### 🐛 Describe the bug

When running inference with vLLM, errors are not returned when an invalid input is supplied.

After starting vLLM as specified above, run a curl command that supplies invalid inputs: ```curl http://localhost:8000/v1/chat/completions         -H "Content-Type: application/json"     -d '{
    "model": "gpt2",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant.",
        "fake_input": "2"
      },
      {
        "role": "user",
        "content": "Hello!",
        "fake_input": "3"
      }
    ]
}'```

You get a successful response. Fake_input is dropped instead of returning an error. This silent failure can be dangerous with typos or invalid inputs. Can this be fixed?

**Comment by DarkLight1337** [comment]
The default setting in Pydantic (as documented [here](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra)) silently drops extra fields.

In order to disallow extra fields, we have to explicitly disable it in the model class. Is that consistent with the behaviour in the actual OpenAI API?

**Comment by DarkLight1337** [comment]
OK I have tested this and found that there is another reason why invalid keys in `messages` isn't being checked. Currently, `messages` is being annotated as `Dict[str, str]` so the schema is not fully specified. PR #3467 improves the type annotations but still does not limit the allowed keys. Therefore, I'm going to port over some type annotations from my WIP PR #4200 to fix this issue.

**Comment by dyastremsky** [comment]
Wow, that was lightning fast, @DarkLight1337 and @simon-mo. Thanks for working on this so quickly!
