### ISSUE TITLE
[Usage]: why can't the `max_model_len` be greater than `max_position_embeddings` for llama2?

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#4346]
### Your current environment

when we are running prefill stage, vllm take multiple requests to do prefill.

Is this limited by the `max_position_embeddings`?

I think it's not limited by this number, because each sequence has its own start index, we only need to ensure that each sequence is shorter than `max_position_embeddings`.  Is that the fact?

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by Playerrrrr** [comment]
cant we have something like automated rope scaling like in alpindales Aphrodite Engine?
