### ISSUE TITLE
[Feature]: GPTQ/AWQ quantization is not fully optimized yet. The speed can be slower than non-quantized models.

### ISSUE THREAD

**Issue by ShubhamVerma16** [vllm-project/vllm#4359]
### 🚀 The feature, motivation and pitch

While running the vLLM server with quantized models specifying the quantization type, the below mentioned Warning is shown:
```
WARNING 04-25 12:26:07 config.py:169] gptq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
```

Is the a feature in progress or is there any workaround that can be done to handle the same.
Let me know if any more details are required from my end.

**Comment by robertgshaw2-neuralmagic** [comment]
You can use the Marlin kernels.

We have a PR to automatically support GPTQ models with Marlin. Should be merged imminently

https://github.com/vllm-project/vllm/pull/3922

**Comment by davidgxue** [comment]
Would this have support for 8 bit quants as well or just 4 bit?

**Comment by robertgshaw2-neuralmagic** [comment]
Right now, 4 bits only. But @alexm-nm is working on 8 bit version of Marlin ATM and should be done relatively soon

**Comment by alexm-nm** [comment]
@davidgxue We have initial correctness on 8bit marlin, will do some perf checks and more testing and will put PR in a couple of days.

**Comment by alexm-nm** [comment]
Btw, the new 8bit marlin will support all group_sizes and act_order

**Comment by davidgxue** [comment]
Awesome!! Thank you guys for the hard work!

**Comment by alexm-nm** [comment]
@davidgxue here we add 8-bit support https://github.com/vllm-project/vllm/pull/4533

**Comment by davidgxue** [comment]
Thank you!!

**Comment by vidhyat98** [comment]
when can we expect awq models to be optimized for inference?

**Comment by alexm-neuralmagic** [comment]
@vidhyat98 AWQ is added to marlin.

**Comment by mgoin** [comment]
Resolved! :)

**Comment by alexdauenhauer** [comment]
so it looks like we should pass `quantization='awq_marlin'` for awq quantized models?

**Comment by mgoin** [comment]
> so it looks like we should pass `quantization='awq_marlin'` for awq quantized models?

@alexdauenhauer you don't need to pass any quantization argument, in fact it is best if you don't! vLLM will automatically choose the best kernel it can use for your quantized model

**Comment by alexdauenhauer** [comment]
@mgoin great to know thanks!
