### ISSUE TITLE
Running to (Installing build dependencies ) this step is stuck

### ISSUE THREAD

**Issue by aihaidong** [vllm-project/vllm#436]
![image](https://github.com/vllm-project/vllm/assets/54533917/99997cfa-f6f6-4de1-9641-0e4c90884256)

system： ubuntu 20.04
Nvidia driver 515
cuda 11.7
rtx3090
python 3.8
vllm 0.1.2

**Comment by quanliu1991** [comment]
1. Use only Tsinghua source not douban source Try it out
2. `pip install vllm  --verbose` Use -verbose to see where the blocking is

**Comment by potong** [comment]
> 1. Use only Tsinghua source not douban source Try it out
> 2. `pip install vllm  --verbose` Use -verbose to see where the blocking is

Thanks, installation is slow because there are many packages installed

**Comment by BalckTt** [comment]
解决了吗？我也一直卡在这里，不动，好久了，这个你登了多久？

**Comment by aihaidong** [comment]
> 解决了吗？我也一直卡在这里，不动，好久了，这个你登了多久？

我这个好像是重新安装一下就好了，不知道什么原因

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
