### ISSUE TITLE
[Installation]: Question: Does pip package comes with PUNICA kernels? 

### ISSUE THREAD

**Issue by oandreeva-nv** [vllm-project/vllm#4379]
### Your current environment

```text
Irrelevant 
```

### How you are installing vllm

```sh
pip install vllm==v0.4.0.post1
```
My question is: Is my assumption that pip package comes with punica kernels, and is there any intention to change this in the future? 

I ran a couple of tests and it seems that at least `v0.4.0.post1` comes with punica kernels:
```
root@oandreeva-dt:/opt/tritonserver# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vllm._punica_C as punica_kernels
>>> exit()
```

I believe, this is intended: https://github.com/vllm-project/vllm/blob/15e7c675b0dc36109c7b591f856f102e96493a94/.github/workflows/scripts/build.sh#L16

P.S. please feel free to re-direct me to a dedicated Q&A resource for next time.

**Comment by simon-mo** [comment]
Yes we ship Punica kernels as part of PyPI package and Docker. It _does_ create a lot of problem regarding wheel sizes but we intend to continue shipping it.

**Comment by oandreeva-nv** [comment]
Thanks!
