### ISSUE TITLE
Scope for assisted generation?

### ISSUE THREAD

**Issue by creatorrr** [vllm-project/vllm#439]
It seems that assisted generation can further reduce sampling latency. Is there scope for adding support for that in vllm?

Assisted generation [docs](https://huggingface.co/blog/assisted-generation)

**Comment by zhuohan123** [comment]
Hi! This direction is interesting, but might not be an immediate TODO for vLLM. Added this to the roadmap to keep track.

**Comment by creatorrr** [comment]
Yeah that makes sense :)

**Comment by Rifur13** [comment]
Is anybody working on this? I can pick up this task.

**Comment by tjtanaa** [comment]
Found a github project that claims to be 1.6x faster than Medusa and is loseless.
https://github.com/SafeAILab/EAGLE

**Comment by njhill** [comment]
Assisted generation is another name for speculative decoding, the implementation of which is in progress (in fact there are a number of PRs implementing this!)

**Comment by hmellor** [comment]
Oh I see, I was aware of those PRs but I didn't know this feature request was referring to them. Thanks for clarifying :)

**Comment by creatorrr** [comment]
Closing this since it’s already in the works in #3250 etc :)
