### ISSUE TITLE
Fix the rushed out multi-query kernel

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#44]
1. Fix the correctness issue in the current FlashAttention-copy-based kernel. Make sure we call the FlashAttention kernel correctly. Evaluate the performance of this kernel.
2. Reduce the memory usage of the current kernel by limiting the buffer size and calling the kernel multiple times.

**Comment by tmm1** [comment]
> current FlashAttention-copy-based kernel

I believe this is referring to #4, however as of #70 flash-attn is no longer used.

**Comment by hmellor** [comment]
Closing based on @tmm1's comment about `flash-attn` no longer being used.
