### ISSUE TITLE
How to perform tensor parallelism when `vocab_size` is not an integer multiple of `world_size`?

### ISSUE THREAD

**Issue by HermitSun** [vllm-project/vllm#440]
When I try to load a bloom-based model to an 8-GPUs server, I met the following error:

```
AssertionError: 250682 is not divisible by 8
```

It seems the following check will be performed before tensor parallelism: https://github.com/vllm-project/vllm/blob/c894836108732d0cbb6fce15aeda8de1218a380d/vllm/model_executor/parallel_utils/tensor_parallel/utils.py#L66-L70

I check the model's `config.json` and found its `vocab_size` is 250682. Obviously it cannot pass the check above.

So how could I perform tensor parallelism when `vocab_size` is not an integer multiple of `world_size`?

**Comment by dalazx** [comment]
Hi @HermitSun. We are seeing a similar error with Falcon 40b on 4x A100. Was the issue solved only by applying the patch at #441 or there were other steps taken? In our case we see this validation failure even before the `load_weights` call.

**Comment by HermitSun** [comment]
I'm afraid that this problem is not fully solved, and this issue may need to be reopened. Issue #441 did not change the tensors partition logics, actually.
