### ISSUE TITLE
[RFC]: environment variable management in vllm

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#4407]
### Motivation.

As the project move on, we have more and more environment variables, and we have to manage them rather than letting them scatter around.

### Proposed Change.

There are three types of environment variables used in vllm:

1. environment variables that are used to control the behavior of code **outside** vllm, e.g. `CUDA_VISIBLE_DEVICES`
2. environment variables that are used to control the behavior of code **inside** vllm, e.g. `VLLM_USE_PRECOMPILED`
3. environment variables that are used for testing, e.g. `TEST_DIST_MODEL`

For type-1, gathering all the environment variables in a centralized place would make it easier for users to understand what environment variables vllm uses.

For type-2, gathering all the environment variables in a centralized place would make it easier for users to understand what environment variables they can use to control the behavior of vllm.

For type-3, it is safe to leave them as they are.

There is also some feedback on the naming of environment variables, e.g. https://github.com/vllm-project/vllm/pull/3419#issuecomment-2078712068 states that the environment variable `HOST_IP` used in vllm has conflict with some k8s plugin. And https://github.com/vllm-project/vllm/pull/3419#issuecomment-2078836305 suggests prefix like `VLLM__` (double underscore) to show hierarchies.

The proposed change is:

1. have a centralized place `vllm/envs.py` for all environment variables  in type-1 and type-2
2. rename existing type-2 environment variables to make sure they are all prefixed by `VLLM`. (**Please comment if it makes sense to use `VLLM__` double underscore or `VLLM_` single underscore**).

For backward compatibility, in step 2, we should also keep previous environment variables, but lower their priority. For example, `os.environ['VLLM_HOST_IP'] or os.environ['HOST_IP']` . New environment variable prefixed with `VLLM` is preferred, but the legacy one is also respected.

For step 1, we should have lazy evaluation. Currently, environment variables are read at different timestamps. We don't want the import of `vllm/envs.py` reads all the environment variables during import. Python Module __getattr__ proposed in https://peps.python.org/pep-0562/ can help.

Basic implementation:

```python
# vllm/envs.py
import os
environment_variables = {
    # explanation, comment
    'VLLM_HOST_IP': lambda : os.environ['VLLM_HOST_IP'] or os.environ['HOST_IP'],
    ...: ...
}

def __getattr__(name):
    if name in environment_variables:
        return environment_variables[name]()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

def __dir__():
    return list(environment_variables.keys())
```

Usage:

```python
# previous
import os
host_ip = os.environ.get("HOST_IP")

# proposed
import vllm.envs as envs
host_ip = envs.host_ip
```

One additional benefit of this RFC is we can have a centralized place for dealing with environment variables. e.g. for `CUDA_VISIBLE_DEVICES`, currently we have to reconstruct it to list of int every time we read it. With this RFC, the logic will be moved to `vllm/envs.py` , and all the rest code just reads `envs.CUDA_VISIBLE_DEVICES` , which should already be a list of int.

### Feedback Period.

Until April 30th. I plan to implement it in May.

**Comment by rkooo567** [comment]
This is awesome! Ray repo doesn't have this centralized env var, and I always found it very difficult to find env vars...

**Comment by cadedaniel** [comment]
Love it! Thanks for putting this together

**Comment by simon-mo** [comment]
I like the general direction. But getattr makes typing hard. I would prefer actual variable for the env var as Python constant.

**Comment by youkaichao** [comment]
> I like the general direction. But getattr makes typing hard. I would prefer actual variable for the env var as Python constant.

env var as Python constant would require reading **all** the environment variables **at the first time of module import**, and would break existing code that writes environment variables.

for example, in distributed inference, we have to set `CUDA_VISIBLE_DEVICES` for workers. And we have to make sure all imports of `vllm/envs.py` happen after the environment variable being set. That is fragile and easy to be broken.

with lazy access, `envs.CUDA_VISIBLE_DEVICES` is strictly the same as `os.environ['envs.CUDA_VISIBLE_DEVICES']`, no other side effects.

**Comment by youkaichao** [comment]
> I like the general direction. But getattr makes typing hard. I would prefer actual variable for the env var as Python constant.

@simon-mo for type checking, we can use `if TYPE_CHECKING` to annotate the type information

**Comment by zhuohan123** [comment]
Can we eliminate all type-2 env variables? Theoretically we should be able to use config for this.

**Comment by youkaichao** [comment]
> Can we eliminate all type-2 env variables? Theoretically we should be able to use config for this.

It seems very difficult. We have many legacy variables and need to keep backward compatibility. This is hard to achieve in config files like yaml.

BTW, i think a centralized place for environment variables like `vllm/envs.py` actually serves as config files. An example in pytorch: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/config.py

**Comment by rkooo567** [comment]
I think calling it config is a little bit confusing with other config we ask for inputs (ModelConfig, SchedulerConfig, etc.).

**Comment by youkaichao** [comment]
> I think calling it config is a little bit confusing with other config we ask for inputs (ModelConfig, SchedulerConfig, etc.).

Yeah, that's why I intend to call it `vllm/envs.py` rather than `vllm/config.py` (which is already used).

**Comment by youkaichao** [comment]
@robcaulk (author of https://github.com/vllm-project/vllm/pull/3419#issuecomment-2078836305 ) I didn't receive any support from the community to use double underscore. Meanwhile, there are already many single underscore env vars in vLLM. For simplicity and backward compatibility, I will not consider double underscore.

**Comment by youkaichao** [comment]
> I agree that type 2 env vars and the vllm command line args should be unified. Why can't we add any such env vars to the existing vllm configs / engine args?

@njhill that can be the next step. I will centrailize all env var first. If anyone has the bandwidth, please follow up.

**Comment by youkaichao** [comment]
This RFC is finished by https://github.com/vllm-project/vllm/pull/4548 and https://github.com/vllm-project/vllm/pull/4574 .

If anyone is interested, next steps would be to follow what @njhill and @zhuohan123 said: unify env vars and the vllm command line args.
