### ISSUE TITLE
[Bug]: CUDA out of memory

### ISSUE THREAD

**Issue by tristandevs** [vllm-project/vllm#4408]
### Your current environment

```text
A100 80GB
```

### 🐛 Describe the bug

Command:
```python3 -m vllm.entrypoints.openai.api_server --model alpindale/WizardLM-2-8x22B --dtype auto --max-model-len 8192 --gpu-memory-utilization 0.50 --enforce-eager --api-key token-abc123```

Error:
```
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU 0 has a total capacity of 79.15 GiB of which 147.75 MiB is free. Process 483452 has 78.98 GiB memory in use. Of the allocated memory 78.17 GiB is allocated by PyTorch, and 13.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

I get the same error for other models too, and I do not think gpu-memory-utilization does anything.

**Comment by DarkLight1337** [comment]
`--gpu-memory-utilization` defaults to `0.9` which lets you use 90% of the GPU. Setting it to a lower value will decrease the GPU available to your model. Also, the model you are using (`alpindale/WizardLM-2-8x22B`) has 8x 22B parameters so that will definitely not fit inside a single A100. Try using a much smaller model.

**Comment by tristandevs** [comment]
Thank you so much! Do you think it would work on 2x a100s? I will try running it on 2x a100s 80gb each tomorrow.

**Comment by DarkLight1337** [comment]
A [quick check](https://huggingface.co/spaces/hf-accelerate/model-memory-usage) shows that the model itself takes up around 260 GB in `float16/bfloat16` precision. So you'll need around 4 A100s just to perform inference.

**Comment by youkaichao** [comment]
The model itself has 141B parameters, and you need at least 282GB memory to hold them.
