### ISSUE TITLE
[Bug]: Memory Issue

### ISSUE THREAD

**Issue by tristandevs** [vllm-project/vllm#4417]
### Your current environment

```text
8x RTX A6000
289.0  TFLOPS
383.9 GB GPU RAM
```

### 🐛 Describe the bug

I get error
```torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU 0 has a total capacity of 47.54 GiB of which 1.38 GiB is free. Process 876965 has 46.14 GiB memory in use. Of the allocated memory 45.52 GiB is allocated by PyTorch, and 5.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)```

However, I have enough ram on all my gpus. I don't think vllm is using all the gpus.

**Comment by DarkLight1337** [comment]
To enable usage of multiple GPUs, use the `tensor_parallel_size=<num_gpus>` option as described [here](https://docs.vllm.ai/en/latest/serving/distributed_serving.html).

**Comment by tristandevs** [comment]
Thank you so much
