### ISSUE TITLE
[Usage]: best way to hold multiple models online at the same time?

### ISSUE THREAD

**Issue by xudong2019** [vllm-project/vllm#4443]
### Your current environment

Hi, I'm using vllm and I want to hold two models at the same time. Currently what I am doing is this:

CUDA_VISIBLE_DEVICES=1 python -O -u -m vllm.entrypoints.openai.api_server     --host=0.0.0.0     --port=8001     --model=/home/jack/model_product/model_20240424     --tokenizer=/home/jack/model_product/model_20240424 --served-model-name=test >/var/log/test.log

CUDA_VISIBLE_DEVICES=0 python -O -u -m vllm.entrypoints.openai.api_server     --host=0.0.0.0     --port=8000     --model=/home/jack/model_product/model_20240425     --tokenizer=/home/jack/model_product/model_20240425 --served-model-name=test >/var/log/test.log

Would this be less efficient since it is running two vllm servers?  Could anyone gives me some suggestion on what would be the best practice for holding multiple models at the same time ?

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by pschauhan480** [comment]
This discussion is one year old but might be of interest for your issue: https://github.com/vllm-project/vllm/discussions/239
