### ISSUE TITLE
[Misc]: Installation on CUDA machines

### ISSUE THREAD

**Issue by ggoggam** [vllm-project/vllm#4446]
### Question on `torch==2.2.1` requirment

It seems from `requirements-cuda.txt` that `vllm` requires the specific version of `torch`, namely 2.2.1.
Unless I create a separate environment, this would require me to switch my torch installation to 2.2.1. 
Is there a reason that the requirement is not set to `torch >= 2.2.1` instead? 

```txt
# Common dependencies
-r requirements-common.txt

# Dependencies for NVIDIA GPUs
ray >= 2.9
nvidia-ml-py # for pynvml package
vllm-nccl-cu12>=2.18,<2.19  # for downloading nccl library
torch == 2.2.1
xformers == 0.0.25  # Requires PyTorch 2.2.1
```

**Comment by youkaichao** [comment]
Please check the doc https://docs.vllm.ai/en/latest/getting_started/installation.html#install-with-pip :

> In order to be performant, vLLM has to compile many cuda kernels. The compilation unfortunately introduces binary incompatibility with other CUDA versions and PyTorch versions, even for the same PyTorch version with different building configurations.
