### ISSUE TITLE
[Usage]: why vllm takes as much ram as possible ?

### ISSUE THREAD

**Issue by xudong2019** [vllm-project/vllm#4448]
### Your current environment

I have multiple 0.5B model running.  By default each vllm instance would take 20G ram. I understand the vllm would maintain the memory management, however I don't see why it is necessary to take that much ram so this little model.  My question is would there be some start up option to let it run in a "minimal" status ?

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by jeejeelee** [comment]
yes, you can adapt `gpu_memory_utilization`

**Comment by xudong2019** [comment]
thanks
