### ISSUE TITLE
[Usage]: what is enforce_eager

### ISSUE THREAD

**Issue by eigen2017** [vllm-project/vllm#4449]
### Your current environment

vllm 0.4.0
cuda 12.1
2*v100-16G
qwen1.5 Moe

### How would you like to use vllm

what is enforce_eager?
and when it's enabled, will the inference become slower?

**Comment by DarkLight1337** [comment]
According to [the documentation](https://docs.vllm.ai/en/latest/models/engine_args.html], it disables the construction of CUDA graph in Pytorch. This may harm performance but reduces the memory requirement (of maintaining the CUDA graph)

**Comment by eigen2017** [comment]
thanks！ then i need to learn what is “ the construction of CUDA graph in Pytorch” on or off means...

--enforce-eager Always use eager-mode PyTorch. If False, will use eager mode and CUDA graph
in hybrid for maximal performance and flexibility.
--max-context-len-to-capture Maximum context length covered by CUDA graphs. When a sequence
has context length larger than this, we fall back to eager mode.

**Comment by eigen2017** [comment]
this link may help 
https://pytorch.org/blog/accelerating-pytorch-with-cuda-graphs/

**Comment by robertgshaw2-neuralmagic** [comment]
CUDAGraphs take a bit of memory and time to compile, but can be helpful for performance if the model is small
For the model you are using, I would not expect to see much of a difference

**Comment by eigen2017** [comment]
thks to uall
