### ISSUE TITLE
scheduler max-length

### ISSUE THREAD

**Issue by jth3galv** [vllm-project/vllm#447]
I am running mpt-7b-instruct  which should support "arbitrary long contexts". However when I provide the model long inputs I get this warning (and the model does not produce any output):

```
Token indices sequence length is longer than the specified maximum sequence length for this model (3622 > 2048). Running this sequence through the model will result in indexing errors
WARNING 07-12 15:03:35 scheduler.py:194] Input prompt (3622 tokens) is too long and exceeds limit of 2560
```

What is this scheduler limit? My understanding is that it is not related to the model. How can I change it?

**Comment by LiuXiaoxuanPKU** [comment]
Hi, the maximum sequence length is decided by the maximum sequence length allowed by the model and the maximum number of batched tokens as shown [here](https://github.com/vllm-project/vllm/blob/c6dfc3cdbeb4687a8313b82d399177e293fee196/vllm/engine/arg_utils.py#L160).

It seems you hit the limit of the maximum number of batched tokens. You could change the default value [here](https://github.com/vllm-project/vllm/blob/c6dfc3cdbeb4687a8313b82d399177e293fee196/vllm/engine/arg_utils.py#L28).

**Comment by jth3galv** [comment]
Thank you so much for the super fast reply.

That worked. Although I now have:

`Token indices sequence length is longer than the specified maximum sequence length for this model (3651 > 2048). Running this sequence through the model will result in indexing errors
`

In configs.json I have:

`  "max_seq_len": 8192,
`

Am I doing something wrong?

**Comment by jth3galv** [comment]
@LiuXiaoxuanPKU I've tracked down the issue. It seems that the tokenizer is not passed the correct model_max_length value.

In llm_engine.py at line 81 we have:


        self.tokenizer = get_tokenizer(
            model_config.tokenizer,
            tokenizer_mode=model_config.tokenizer_mode,
            trust_remote_code=model_config.trust_remote_code)


adding model_max_length= "value" did the trick.

I think that should be read from the corresponding config.json attribute.

**Comment by LiuXiaoxuanPKU** [comment]
Sorry for the late reply. Yeah, we did not pass the model_max_length directly into the tokenizer because we want to reject this request. Instead of letting the tokenizer truncate the prompt and accept the request, the engine (more precisely, scheduler) will recognize that this request has a long input prompt and ignore the request. Please let me know if you find more problems.

**Comment by jth3galv** [comment]
Thanks for your reply!

A few comments: 

Would it not be better for the tokenizer to be aligned with the model?

That is: if I set the _max_seq_len_ in the model config to some value  I think it would be nice to have the tokenizer max length set to the same value.

If this is not the desirable behavior, would it be possible to set the tokenizer _max_seq_len_ somewhere else without having to modify the code?

**Comment by jmzeng** [comment]
What would be the recommended max_num_batched_tokens for 8 H100s with 80GB GPU each?

**Comment by rndlr96** [comment]
Did you set bot `max_model_len` and `max_num_batched_tokens`?

FYI. https://github.com/vllm-project/vllm/blob/6428f1d051d731a9eca192950591e7a5a2788cb2/vllm/core/scheduler.py#L66

**Comment by diego898** [comment]
@LiuXiaoxuanPKU 

> Sorry for the late reply. Yeah, we did not pass the model_max_length directly into the tokenizer because we want to reject this request. Instead of letting the tokenizer truncate the prompt and accept the request, the engine (more precisely, scheduler) will recognize that this request has a long input prompt and ignore the request. Please let me know if you find more problems.

Hello! So to confirm/ask a question: vllm rejecting any inputs longer than the specified max-model-len parameter is a design decision, and there is no plan to support truncation (on left or right side) for inputs longer than this length?

**Comment by njhill** [comment]
There is an open PR to add an input truncation option: https://github.com/vllm-project/vllm/pull/3144
