### ISSUE TITLE
[Bug]: The first token generated after prefill occupies the GPU memory but virtual block

### ISSUE THREAD

**Issue by March-H** [vllm-project/vllm#4496]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

After prefilling, the Transformer generates the first token, which has its own QKV and occupies actual physical GPU memory, correct?
I set the block_size to 16, num_gpu_blocks_override to 6, and submit 3 requests. All the requests' prompts are None, and prompt_token_ids are [0, 1, ..., 15, 16], totaling 17 tokens. After a step(), I use engine.scheduler.block_manager.get_num_free_gpu_blocks() to obtain the number of free blocks, which shows that there are no free blocks (0). Does this mean that tokens 0 to 15 are allocated on block 0 and token 16 is allocated on block 1?

In another test, the requests' prompt_token_ids are [0, 1, ..., 15], totaling 16 tokens, with the same settings as before. After a step(), are there 3 free blocks? So, does the new token generated after prefilling not occupy a block?

**Comment by rkooo567** [comment]
> Does this mean that tokens 0 to 15 are allocated on block 0 and token 16 is allocated on block 1?
Yes this is correct. 

> So, does the new token generated after prefilling not occupy a block?
That's right. it is written in the next iteration. You can think kvs are written to kv cache right before you run the attention.
