### ISSUE TITLE
[Usage]: How to modify the default system prompt？

### ISSUE THREAD

**Issue by lee0v0** [vllm-project/vllm#4497]
### Your current environment

```text
vllm-0.4.0
```

### How would you like to use vllm

When I deploy an OpenAI-Compatible Server using `python -m vllm.entrypoints.openai.api_server`, how do I modify the default system prompt(You are a helpful assistant.)?

**Comment by HarryWu99** [comment]
https://docs.vllm.ai/en/latest/getting_started/quickstart.html

this may help, just edit the message you send to the api.
```
curl http://localhost:8000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "facebook/opt-125m",
    "messages": [
      {"role": "system", "content": "You are **not** a helpful assistant."},
      {"role": "user", "content": "Who won the world series in 2020?"}
    ]
  }'
```

**Comment by zengqingfu1442** [comment]
Use `--system-prompt`? https://docs.vllm.ai/en/stable/cli/chat.html#options
