### ISSUE TITLE
Inference with LLaMA 65B generates nothing but \n

### ISSUE THREAD

**Issue by foamliu** [vllm-project/vllm#450]
The problem only happens with LLaMA 65B, LLaMA 7B/13B/30B work well. Below is the reproduce code：
```
from vllm import LLM, SamplingParams
args_model = '/mnt/sdb/ly/models/hf_converted_llama/65B/'
llm = LLM(model=args_model, tokenizer=args_model, tokenizer_mode='slow', dtype='float16', seed=42, tensor_parallel_size=8)
sampling_params = SamplingParams(temperature=0, max_tokens=10)
prompt = 'The capital of France is'
outputs = llm.generate(prompts=[prompt], sampling_params=sampling_params)
outputs
```
```
>>> outputs
[RequestOutput(request_id=0, prompt='The capital of France is', prompt_token_ids=[0, 450, 7483, 310, 3444, 338], outputs=[CompletionOutput(index=0, text='\n\n\n\n\n\n\n\n\n\n', token_ids=[13, 13, 13, 13, 13, 13, 13, 13, 13, 13], cumulative_logprob=-34.18291640281677, logprobs={}, finish_reason=length)], finished=True)]
>>> sampling_params = SamplingParams(temperature=0.1, max_tokens=10)
```
And HuggingFace transformers works as normal:
```
import transformers                  
tokenizers = transformers.LlamaTokenizer.from_pretrained("/mnt/sdb/ly/models/hf_converted_llama/65B/")
model = transformers.LlamaForCausalLM.from_pretrained("/mnt/sdb/ly/models/hf_converted_llama/65B/", device_map="auto")  
prompt = 'The capital of France is'
inputs = tokenizers.encode(prompt, return_tensors="pt").to(model.device)
outputs = model.generate(inputs, max_new_tokens=10)
text = tokenizers.decode(outputs[0], skip_special_tokens=True)
```
```
>>> text
'The capital of France is Paris.\nThe capital of France is Paris.'
```

**Comment by Hukongtao** [comment]
I had the same problem. The outputs from vLLM and HF are inconsistent

**Comment by lucasjinreal** [comment]
Does this happend only on 65B model? Am using 7B normally

**Comment by HermitSun** [comment]
Is there any difference between generation args of vllm and hf? It seems that vllm has some args that hf does not have.

**Comment by Hukongtao** [comment]
> Is there any difference between generation args of vllm and hf? It seems that vllm has some args that hf does not have.
generation args of vllm:  https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L1161

**Comment by foamliu** [comment]
> Does this happend only on 65B model? Am using 7B normally

The problem only happens with LLaMA 65B, LLaMA 7B/13B/30B work well.

**Comment by foamliu** [comment]
> > Is there any difference between generation args of vllm and hf? It seems that vllm has some args that hf does not have.
> > generation args of vllm:  https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L1161

Generation args are in the code above, both should use greedy decoding so shouldn't be too different (all '\n' from vllm).

**Comment by foamliu** [comment]
> I had the same problem. The outputs from vLLM and HF are inconsistent

Yes, I found this problem too. In the case of greedy decoding, although LLaMA 7B, 13B, 30B can get meaningful output, the output results are different from HF transformers. 

For example, the following is the score of my evaluation with GSM8k:

|   | LLaMA 7B  | LLaMA 13B   | 
|---|---|---|
| vLLM  | 9.40  | 15.01  | 
| HF  | 10.46  | 14.86  |

**Comment by lucasjinreal** [comment]
The generation params can heavily effect final model performance.

**Comment by MM-IR** [comment]
So is it reliable to evaluate LLaMa results using your scripts? - That is really weird..

**Comment by foamliu** [comment]
> So is it reliable to evaluate LLaMa results using your scripts? - That is really weird..

The same result can be stably reproduced on my V100 server.

**Comment by andyfeih** [comment]
vllm just failed to load weights, for example, vllm has no support of safetensors yet

**Comment by foamliu** [comment]
> vllm just failed to load weights, for example, vllm has no support of safetensors yet

vLLM does not yet support safetensors, but this does not prevent us from converting the llama model into a format similar to pytorch_model-00001-of-00003.bin then loading it with vllm.

**Comment by CtfGo** [comment]
I have also encountered the same problem, the same prompt can not produce the same output, with sampling params for greedy

| params |  HF  | vLLM |
| --- | --- | --- |
|top_p | 1.0 | 1.0  |
|top_k | -1 | -1  |
|temperature | 0.0 | 0.0|

Anyone is resolving this ?

**Comment by syskn** [comment]
I have been trying various models and outputs from vLLM I get are consistently and significantly more deterministic (tends to work like greedy decoding and have severe repetition issue with temperature below 0.7) than HF implementation.

I compared through sampling process and I could not find a difference - if greedy doesn't match, then is it something in PagedAttention or cuda kernels?

**Comment by lw921014** [comment]
> 

![image](https://github.com/vllm-project/vllm/assets/19748572/001d1d49-d297-412a-9c71-667fdc91ebe7)
for LLAMA 65B，you'd better midfy you tokenizer bos as 1 (which is 0 for llama 13b).

**Comment by luohao123** [comment]
@syskn  

> I have been trying various models and outputs from vLLM I get are consistently and significantly more deterministic (tends to work like greedy decoding and have severe repetition issue with temperature below 0.7) than HF implementation.

I compared through sampling process and I could not find a difference - if greedy doesn't match, then it could be something in PagedAttention or cuda kernels?


See my issue here: https://github.com/vllm-project/vllm/issues/706

I set same params,but result are totally wrong, the robot looks like sutpid than hf version.....

**Comment by oushu1zhangxiangxuan1** [comment]
Encountered the same problem

**Comment by phamkhactu** [comment]
> Encountered the same problem

Yes, me too.

**Comment by will-wiki** [comment]
Encountered the same problem

**Comment by pvtoan** [comment]
Hi,

Anyone please reproduce the answer from LLama2-7B-Chat with the prompt "hello"

Because, in my case, I just get a weird answer: "@matthew-james.com"

I used exactly  the same code as @foamliu when using vllm with LLama2-7B-Chat .

Thank you for your time and help!

**Comment by ArlanCooper** [comment]
> > I had the same problem. The outputs from vLLM and HF are inconsistent
> 
> Yes, I found this problem too. In the case of greedy decoding, although LLaMA 7B, 13B, 30B can get meaningful output, the output results are different from HF transformers.
> 
> For example, the following are the scores of my evaluation with several benchmarks:
> 
> GSM8k
> 
> LLaMA 7B	LLaMA 13B	LLaMA 30B
> vLLM	9.40	15.01	24.94
> HF	10.46	14.86	30.40
> MMLU
> 
> LLaMA 7B	LLaMA 13B	LLaMA 30B
> vLLM	35.8	46.9	48.9
> HF	34.1	46.7	57.8

awsome！！

**Comment by thehir0** [comment]
Encountered the same problem when using model with dynamic rope scaling.

`{
  "_name_or_path": "/data/hf-models/my_model/config.json",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 8.0,
    "type": "dynamic"
  },
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.38.1",
  "use_cache": false,
  "vocab_size": 60256
}`
