### ISSUE TITLE
[Feature]: Load new LoRA adapters on request

### ISSUE THREAD

**Issue by markovalexander** [vllm-project/vllm#4501]
### 🚀 The feature, motivation and pitch

When experimenting with model finetuning, one can train a lot of LoRAs. In order to test (or deploy into production) new lora weights we have to restart the image because we can load loras only on docker start and lora loading with a request is not supported now. 

There were the [same issue](https://github.com/vllm-project/vllm/issues/4234) and relevant [PR](https://github.com/vllm-project/vllm/pull/3850) , however issue is closed but PR is not merged and actually doesn't pass tests.

**Comment by codybum** [comment]
Yes, this would be a very important effort to support.  We previously used vLLM, but have since switched to LoraX, which supports multi-adapter (https://github.com/predibase/lorax).  There are other features that I prefer with vLLM.
