### ISSUE TITLE
[Bug] FP8 MoE performance regression since updating to torch 2.3.0

### ISSUE THREAD

**Issue by pcmoritz** [vllm-project/vllm#4509]
### Your current environment

H100 80GB, torch 2.3.0

### 🐛 Describe the bug

Since https://github.com/vllm-project/vllm/pull/4454, the performance on the FP8 MoE kernel has been pretty bad. On FP8, for qps 6 (1000 input, 50 output tokens) and static activation scales on H100, the mixtral 8x7b ITL goes from 12ms to over 40ms.

**Comment by zifeitong** [comment]
I tested torch 2.3.1 that was released with triton 2.3.1. This regression is fixed.

**Comment by pcmoritz** [comment]
Do you want to submit a PR to upgrade the torch dependency to 2.3.1?

**Comment by zifeitong** [comment]
I am happy to. But `xformers` needs to be rebuilt with torch 2.3.1 first: https://github.com/facebookresearch/xformers/issues/1052.
