### ISSUE TITLE
--kv_cache_dtype fp8 should not check for nvcc

### ISSUE THREAD

**Issue by wizche** [vllm-project/vllm#4521]
I'm creating this issue since the openai docker image still fails by checking nvcc. (version 0.4.1, current latest)

> --kv_cache_dtype fp8 should not check for nvcc currently it is not usable in 0.4.1 openai image.

_Originally posted by @chiragjn in https://github.com/vllm-project/vllm/issues/2781#issuecomment-2080390659_

**Comment by AnyISalIn** [comment]
yeah, I have created a PR for this issue https://github.com/vllm-project/vllm/pull/4173
