### ISSUE TITLE
Max prompt tokens/sequence length limit in vllm core scheduler

### ISSUE THREAD

**Issue by yuanheng-zhao** [vllm-project/vllm#453]
### Discussed in https://github.com/vllm-project/vllm/discussions/446

<div type='discussions-op-text'>

<sup>Originally posted by **yuanheng-zhao** July 12, 2023</sup>
I noticed that the following block (https://github.com/vllm-project/vllm/blob/main/vllm/core/scheduler.py#L193) was added to vllm core scheduler
```python
if num_prompt_tokens >= self.scheduler_config.max_seq_len:
    logger.warning(
        f"Input prompt ({num_prompt_tokens} tokens) is too long"
        " and exceeds limit of "
        f"{self.scheduler_config.max_seq_len}")
    for seq in seq_group.get_seqs():
        seq.status = SequenceStatus.FINISHED_IGNORED
    ignored_seq_groups.append(seq_group)
    self.waiting.pop(0)
    break
```
as a fix for the issue https://github.com/vllm-project/vllm/issues/113

I wonder why we're not using `num_prompt_tokens > self.scheduler_config.max_seq_len` as a condition? It seems to filter out input sequences with exact length (e.g. `--input-len 1024`) for benchmarks.

Thank you for your instruction!

</div>

***

I was running the [benchmark script](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_latency.py) `benchmark_latency.py` with llama-7b, input_length == 1024, output length == 128, fp16, and bs == 1.

The above block of code seems to cause the following warning and filter out all the input sequences when running the benchmark:
```bash
(base) <username>:~/vllm$ python benchmarks/benchmark_latency.py --batch-size 1 --input-len 1024 --output-len 128 --model "/models/llama-7b-hf" --tokenizer "hf-internal-testing/llama-tokenizer"
Namespace(model='/models/llama-7b-hf', tokenizer='hf-internal-testing/llama-tokenizer', tensor_parallel_size=1, input_len=1024, output_len=128, batch_size=1, n=1, use_beam_search=False, num_iters=3)
INFO 07-13 14:16:25 llm_engine.py:60] Initializing an LLM engine with config: model='/models/llama-7b-hf', tokenizer='hf-internal-testing/llama-tokenizer', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 07-13 14:16:25 tokenizer.py:29] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 07-13 14:16:40 llm_engine.py:134] # GPU blocks: 7496, # CPU blocks: 512
SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=1.0, top_p=1.0, top_k=-1, use_beam_search=False, stop=[], ignore_eos=True, max_tokens=128, logprobs=None)
Warming up...
WARNING 07-13 14:16:43 scheduler.py:197] Input prompt (1024 tokens) is too long and exceeds limit of 1024
Profiling iterations:   0%|                                                        | 0/3 [00:00<?, ?it/s]WARNING 07-13 14:16:43 scheduler.py:197] Input prompt (1024 tokens) is too long and exceeds limit of 1024
WARNING 07-13 14:16:43 scheduler.py:197] Input prompt (1024 tokens) is too long and exceeds limit of 1024
WARNING 07-13 14:16:43 scheduler.py:197] Input prompt (1024 tokens) is too long and exceeds limit of 1024
Profiling iterations: 100%|██████████████████████████████████████████████| 3/3 [00:00<00:00, 4919.04it/s]
Avg latency: 0.0001911322275797526 seconds
```

which makes the average latency extremely low.

**Comment by foamliu** [comment]
I had the same problem. If simply comment out this code, the LLM initialization will hang.

**Comment by irasin** [comment]
> I wonder why we're not using `num_prompt_tokens > self.scheduler_config.max_seq_len` as a condition? It seems to filter out input sequences with exact length (e.g. `--input-len 1024`) for benchmarks.

If the prompt token length is equal the max_seq_len supported by the model(e.g. max_seq_len = 2048 in llama), there's no slot available for the next token generation.

>I was running the [benchmark script](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_latency.py) benchmark_latency.py with llama-7b, input_length == 1024, output length == 128, fp16, and bs == 1.

It seems a bug in the `benchmark_latency.py` script for batch_size = 1,  you can just modify the number of the max_num_batched_tokens  in LLM initilization to avoid this problem.

**Comment by yuanheng-zhao** [comment]
Gotcha. Thank you for your explanation! @irasin 
I did notice `max_num_batched_tokens` but was confused about if I should modify it.

Just paste the modification and result produced by running `benchmark_latency.py`:

**Goal**:
To test the benchmark latency with batch size as 1, input length as 1024, and output length as 128 on llama-7b-hf.
The command I used `python benchmarks/benchmark_latency.py --batch-size 1 --input-len 1024 --output-len 128 --model "<path to llama-7b-hf or huggingface>" --tokenizer "hf-internal-testing/llama-tokenizer"`

**Modification made**:
the following line in LLM initialization in [benchmarks/benchmark_latency.py](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_latency.py#L23):
```python
        max_num_batched_tokens=args.batch_size * args.input_len,
```
as 
```python
        max_num_batched_tokens=1024+128,
```
(since just test this specific pair of input and output lengths)

**result**:
```bash
(base):~/vllm$ python benchmarks/benchmark_latency.py --batch-size 1 --input-len 1024 --output-len 128 --model "/models/llama-7b-hf" --tokenizer "hf-internal-testing/llama-tokenizer"
Namespace(model='/models/llama-7b-hf', tokenizer='hf-internal-testing/llama-tokenizer', tensor_parallel_size=1, input_len=1024, output_len=128, batch_size=1, n=1, use_beam_search=False, num_iters=3)
*** vllm/engine/arg_utils.py(L159): create_engine_configs
 self.max_num_batched_tokens= 1152
 model_max_len= 2048
*** vllm/config.py(L200): SchedulerConfig: __init__
 max_num_batched_tokens= 1152
 max_num_seqs= 1
 max_seq_len= 1152
INFO 07-14 14:54:29 llm_engine.py:60] Initializing an LLM engine with config: model='/models/llama-7b-hf', tokenizer='hf-internal-testing/llama-tokenizer', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 07-14 14:54:29 tokenizer.py:29] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 07-14 14:54:42 llm_engine.py:134] # GPU blocks: 7494, # CPU blocks: 512
SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, temperature=1.0, top_p=1.0, top_k=-1, use_beam_search=False, stop=[], ignore_eos=True, max_tokens=128, logprobs=None)
Warming up...
Profiling iterations: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:07<00:00,  2.34s/it]
Avg latency: 2.340951919555664 seconds

```

**Comment by zhuohan123** [comment]
Hi! Thanks for reporting the issue. I met the exact same bug today and added a partial fix in #477. However, this is still not complete. I believe `max_num_batched_tokens` should not be directly used as `max_seq_len`. Will fix this in another PR.

**Comment by zhuohan123** [comment]
Hi we just fixed this in #489. Please retry!

**Comment by zhuohan123** [comment]
Feel free to re-open this issue or create a new issue if you meet any further issues!

**Comment by irasin** [comment]
hi, @zhuohan123 
I have a question about `max_num_batched_tokens`, given a model on a specific gpu env, let say llama7B@Nvidia A10 or llama30B on NVidia A100, how should I determine the value of  `max_num_batched_tokens` to get the best throughput or latency performance? 

And I also wonder why the default value is 2560?

**Comment by LiuXiaoxuanPKU** [comment]
@irasin Maybe zhuohan can give a better answer. I just want to add a bit of context here. vLLM statically partitions the memory into 2 parts (excluding the memory for model weights): one for intermediate tensors during forward pass (e.g., input/output tensors for the linear layers), another for the KV cache. `max_num_batched_tokens` is used to limit the first usage so that vLLM can pre-allocate the KV cache. If you set `max_num_batched_tokens` to a very big number, the kv cache has limited size, so that you can never hit the `max_num_batched_tokens` limit because the system is limited by the size of the kv cache (you need to check if you have enough kv cache slots before running a request). Conversely, if you set `max_num_batched_tokens` to a very small number, even if kv cache is big, it cannot be fully utilized because you are limited by `max_num_batched_tokens` for each batch.

**Comment by irasin** [comment]
Hi, @LiuXiaoxuanPKU, very thanks for the detailed explanation. I understand the relationship between max_num_batched_tokens and the upper limit of kv cache memory now. So I'm even more curious about how you guys decide on the default value. Hope to get an answer!
