### ISSUE TITLE
Virtual Office Hours: May 15 2pm ET

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/vllm#4538]
### Virtual Office Hours

Date: May 15, 2024 2pm EST | 11am PST

We are hosting office hours for the community to ask questions, get updates on roadmap, and generally learn about vLLM.

Moderators:
- @mgoin, Engineering Lead at Neural Magic
- @simon-mo, PhD Student at UCB

During this hour, Michael and Simon will answer your questions on all things related to optimized LLM inference. No prep required, but feel free to list out topics you want to see covered below.

Sign up: https://neuralmagic.com/community-office-hours/

**Comment by mgoin** [comment]
Please share topics or questions you have ahead of time in the thread here - looking forward to meeting you!
