### ISSUE TITLE
[Bug]: AssertionError in neuron_model_runner.py assert len(block_table) == 1

### ISSUE THREAD

**Issue by calvintwr** [vllm-project/vllm#4553]
### Your current environment

PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7R13 Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
Stepping:                        1
BogoMIPS:                        5299.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext perfctr_core invpcid_single ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save vaes vpclmulqdq rdpid
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        48 MiB (96 instances)
L3 cache:                        384 MiB (12 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-23,96-119
NUMA node1 CPU(s):               24-47,120-143
NUMA node2 CPU(s):               48-71,144-167
NUMA node3 CPU(s):               72-95,168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] nvidia-nccl-cu12==2.18.1
[pip3] torch==2.1.2
[pip3] torch-neuronx==2.1.2.2.1.0
[pip3] torch-xla==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collectROCM Version: Could not collect
Neuron SDK Version: (0, 'instance-type: inf2.48xlarge\ninstance-id: i-0e6cfafa7d8d7bcfc\n+--------+--------+--------+-----------+---------+\n| NEURON | NEURON | NEURON | CONNECTED |   PCI   |\n| DEVICE | CORES  | MEMORY |  DEVICES  |   BDF   |\n+--------+--------+--------+-----------+---------+\n| 0      | 2      | 32 GB  | 11, 1     | 80:1e.0 |\n| 1      | 2      | 32 GB  | 0, 2      | 90:1e.0 |\n| 2      | 2      | 32 GB  | 1, 3      | 80:1d.0 |\n| 3      | 2      | 32 GB  | 2, 4      | 90:1f.0 |\n| 4      | 2      | 32 GB  | 3, 5      | 80:1f.0 |\n| 5      | 2      | 32 GB  | 4, 6      | 90:1d.0 |\n| 6      | 2      | 32 GB  | 5, 7      | 20:1e.0 |\n| 7      | 2      | 32 GB  | 6, 8      | 20:1f.0 |\n| 8      | 2      | 32 GB  | 7, 9      | 10:1e.0 |\n| 9      | 2      | 32 GB  | 8, 10     | 10:1f.0 |\n| 10     | 2      | 32 GB  | 9, 11     | 10:1d.0 |\n| 11     | 2      | 32 GB  | 10, 0     | 20:1d.0 |\n+--------+--------+--------+-----------+---------+', '')
vLLM Version: 0.4.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

### 🐛 Describe the bug

We tried to run tinyllama on inferentia and run into the follow problem

```text
    |   File "/home/ubuntu/vllm/vllm/worker/neuron_model_runner.py", line 72, in _prepare_prompt
    |     assert len(block_table) == 1
    | AssertionError
```

To provide some additional info:

AWS Instance type: `inf2.48xlarge`

We followed the instructions in side of this:
https://docs.vllm.ai/en/latest/getting_started/neuron-installation.html

The offline inference provided in this works:
https://docs.vllm.ai/en/latest/getting_started/examples/offline_inference_neuron.html

However, when we try to run the OpenAI compatible server following: https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html

With some adjustments to the command. The original command is here:
```bash
python -m vllm.entrypoints.openai.api_server --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 --dtype auto --api-key api-key --max-num-seqs 8 --max-model-len 128 --block-size 128
```
This gives an error complaining about the `--block-size` and won't compile, saying that the only supportable block size is 8, 16 and 32, so we removed that:

```bash
python -m vllm.entrypoints.openai.api_server --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 --dtype auto --api-key api-key --max-num-seqs 8
```

Now it compiles, but when we try to run an inference, it responds with Internal Server Error, and on the server, we see the above AssertionError.

Here's the full stack trace:

```text
INFO:     127.0.0.1:60772 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |   File "/home/ubuntu/vllm/vllm/entrypoints/openai/api_server.py", line 142, in authentication
    |     return await call_next(request)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    |     await self.app(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    |     await route.handle(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    |     await self.app(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    |     response = await func(request)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    |     raw_response = await run_endpoint_function(
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |   File "/home/ubuntu/vllm/vllm/entrypoints/openai/api_server.py", line 94, in create_chat_completion
    |     generator = await openai_serving_chat.create_chat_completion(
    |   File "/home/ubuntu/vllm/vllm/entrypoints/openai/serving_chat.py", line 135, in create_chat_completion
    |     return await self.chat_completion_full_generator(
    |   File "/home/ubuntu/vllm/vllm/entrypoints/openai/serving_chat.py", line 298, in chat_completion_full_generator
    |     async for res in result_generator:
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 663, in generate
    |     raise e
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 657, in generate
    |     async for request_output in stream:
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 78, in __anext__
    |     raise result
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 39, in _raise_exception_on_finish
    |     task.result()
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 498, in run_engine_loop
    |     has_requests_in_progress = await asyncio.wait_for(
    |   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    |     return fut.result()
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 472, in engine_step
    |     request_outputs = await self.engine.step_async()
    |   File "/home/ubuntu/vllm/vllm/engine/async_llm_engine.py", line 214, in step_async
    |     output = await self.model_executor.execute_model_async(
    |   File "/home/ubuntu/vllm/vllm/executor/neuron_executor.py", line 89, in execute_model_async
    |     output = await make_async(self.driver_worker.execute_model)(
    |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    |     result = self.fn(*self.args, **self.kwargs)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    |     return func(*args, **kwargs)
    |   File "/home/ubuntu/vllm/vllm/worker/neuron_worker.py", line 87, in execute_model
    |     output = self.model_runner.execute_model(seq_group_metadata_list)
    |   File "/opt/aws_neuronx_venv_pytorch_2_1/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    |     return func(*args, **kwargs)
    |   File "/home/ubuntu/vllm/vllm/worker/neuron_model_runner.py", line 176, in execute_model
    |     ) = self.prepare_input_tensors(seq_group_metadata_list)
    |   File "/home/ubuntu/vllm/vllm/worker/neuron_model_runner.py", line 152, in prepare_input_tensors
    |     prompt_lens) = self._prepare_prompt(seq_group_metadata_list)
    |   File "/home/ubuntu/vllm/vllm/worker/neuron_model_runner.py", line 72, in _prepare_prompt
    |     assert len(block_table) == 1
    | AssertionError
    +------------------------------------
```

@liangfu Saw that you wrote most of the code here for Neuron. Do you have any clue on this one?

**Comment by lonngxiang** [comment]
same

![image](https://github.com/vllm-project/vllm/assets/40717349/1a27830e-2e98-48db-b137-cc0d6fae56a6)

**Comment by liangfu** [comment]
This should be fixed by https://github.com/vllm-project/vllm/pull/7562 . Would you try the latest `main` branch?
