### ISSUE TITLE
[Misc]: openai compatible server

### ISSUE THREAD

**Issue by aqx95** [vllm-project/vllm#4579]
### Anything you want to discuss about vllm.

I have been using vllm for a while and i am really grateful to the community for all the features and improvement in this project! 
I am seeing a trend where features that are built mostly cater towards integrating with OpenAI-compatible API. One such example is the `guided_generation`, where the `guided_decoding` classes accepts OpenAI `ChatCompletionRequest` format. 
As someone who uses vllm with the default `api_server` entrypoint, i am curious why many of such features, including profiling of metrics are implemented with openai compatible integration in mind. 
What are the considerations when deciding on openai server over the default api server? One aspect i could think of is probably the wide usage of OpenAI API in many applications out there, hence, it will make more sense to provide such integration as a drop-in replacement.

**Comment by simon-mo** [comment]
https://github.com/vllm-project/vllm/blob/3521ba4f2554bcf246a95a9fb2d1b80990a6835b/vllm/entrypoints/api_server.py#L1-L8
