### ISSUE TITLE
Support embedding models

### ISSUE THREAD

**Issue by SensorLock** [vllm-project/vllm#458]
It would be nice if VLLM could serve Transformer-based embedding models (ex. BERT) as well.

Having one host server that supports generative and embedding LLM APIs makes deployment of applications involving vector indexing easier (document retrieval and memory insertion into prompts).

This may be related to #187 for BERT-derived models, since they are encoder-only.

**Comment by zhuohan123** [comment]
Hi! Thanks for the suggestion. We actually had this discussion before and decided to postpone this feature. Please refer to #310 for more info.

**Comment by meng2468** [comment]
Potential to open it up again? Was included in the Q1 Roadmap but not completed.
