### ISSUE TITLE
streaming does not begin until entire response is completed

### ISSUE THREAD

**Issue by notphantasy** [vllm-project/vllm#460]
i'm starting the openai server and making a python post request with `stream=True`.

but the results are not starting to be streamed until after the response is completely finished.

```
import requests
import json

url = "..."

headers = {"Content-Type": "application/json"}

data = {
    "model": "...",
    "prompt": "....",
    "max_tokens": 108,
    "temperature": 0,
    "stream": True,
}

response = requests.post(url, headers=headers, data=json.dumps(data))

for x in response:
    print(x)
```

here's the code. nothing starts printing until a few seconds after the request is posted. thanks!

**Comment by Marten2016** [comment]
maybe you should pass the params "stream" in request api. like in api-client.py demo.
