### ISSUE TITLE
[Bug]: ValueError: Model QWenLMHeadModel does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

### ISSUE THREAD

**Issue by linzm1007** [vllm-project/vllm#4615]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

ValueError: Model QWenLMHeadModel does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

**Comment by linzm1007** [comment]
The chatglm and baichuan models are not supported.

**Comment by yyccli** [comment]
These models have supported lora (`chatglm` and `baichuan`), `qwen` is not supported but you may use `qwen1.5` instead

**Comment by linzm1007** [comment]
Backed up? Why am I getting an error with qwen lora?

**Comment by linzm1007** [comment]
> Backed up? Why am I getting an error with qwen lora?


Backed up? Why am I getting an error with qwen lora?

**Comment by yyccli** [comment]
`qwen` is not supported but `qwen1.5` supports lora
