### ISSUE TITLE
[Usage]: How to install vllm in cuda10.2? Cuda version cannot be upgraded due to environmental issues

### ISSUE THREAD

**Issue by 1193700079** [vllm-project/vllm#4616]
### Your current environment

How to install vllm in cuda10.2? Cuda version cannot be upgraded due to environmental issues.

The GPU used is the Iluvatar BI-V100.

**Comment by DarkLight1337** [comment]
You can try [building vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source).

**Comment by Ethenlalala** [comment]
> ### Your current environment
> How to install vllm in cuda10.2? Cuda version cannot be upgraded due to environmental issues.
> 
> The GPU used is the Iluvatar BI-V100.
> 
> ### How would you like to use vllm
> _No response_

I had the same problem. Did you finally solve it?
