### ISSUE TITLE
Starcoder is 5-10x slower on vllm than HF's TGI when passing in a continuous batch of requests

### ISSUE THREAD

**Issue by cakeislife100** [vllm-project/vllm#462]
Hi!

We're testing out the new Starcoder implementation [here](https://github.com/vllm-project/vllm/pull/209) (thank you for the contribution @michaelfeil!) and have noticed that it's about 5-10x slower on vllm than HF's text-generation-inference when passing in a batch of requests.

Our test is pretty rudimentary, we simply make a series of 10 requests in parallel returning a fixed number of output tokens, and wait for all the results to return. The results are roughly:
VLLM: 2000 tokens in 40 seconds, ~50 tokens/s
TGI: 2000 tokens in 6 seconds, ~300 tokens/s

Is there something we might be doing wrong here?

**Comment by WoosukKwon** [comment]
Hi @cakeislife100, thanks for trying out vLLM. As you have noticed, the current GPTBigCode implementation is suboptimal. This is because we convert its MQA (multi-query attention) to MHA (multi-head attention). This will be fixed in #452.

**Comment by cakeislife100** [comment]
Awesome, thanks for the quick response @WoosukKwon! Let me know if you all need any help with performance testing or anything.

**Comment by WoosukKwon** [comment]
@cakeislife100 @zhuohan123 just merged the PR. Could you [install vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source) and try out the model again?

**Comment by cakeislife100** [comment]
Hey thank you so much for fixing this @zhuohan123 @WoosukKwon! We just tested the performance again, and on average we're seeing about a **2x** throughput gain over Huggingface.

One weird point is that the variance of request times is very large - sometimes throughput is quite low and other times it's blazingly fast. Is this behavior expected with vllm?
