### ISSUE TITLE
[Feature]:  MLA Support

### ISSUE THREAD

**Issue by chengtbf** [vllm-project/vllm#4625]
### 🚀 The feature, motivation and pitch

DeepSeek-V2 design **MLA (Multi-head Latent Attention)**, which utilizes low-rank key-value union compression to eliminate the bottleneck of inference-time key-value cache, thus supporting efficient inference.

![image](https://github.com/vllm-project/vllm/assets/12186261/8bad7132-ec0b-4abd-9300-efc9caf2c04e)

Can VLLM support MLA for accelerated inference?

@misc{deepseek-v2,
  author = {DeepSeek-AI},
  title  = {DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model},
  year   = {2024},
  note   = {GitHub repository},
  url    = {https://github.com/deepseek-ai/deepseek-v2}
  }

https://huggingface.co/deepseek-ai/DeepSeek-V2-Chat
https://github.com/deepseek-ai/DeepSeek-V2/blob/main/deepseek-v2-tech-report.pdf

**Comment by datalee** [comment]
mark

**Comment by wxj630** [comment]
mark

**Comment by obitoquilt** [comment]
mark

**Comment by chenrui17** [comment]
mark

**Comment by lengyueyang** [comment]
mark

**Comment by RanchiZhao** [comment]
mark

**Comment by Jiayi-Pan** [comment]
mark

**Comment by quwu0820** [comment]
mark

**Comment by qianchen94** [comment]
mark

**Comment by lumosity4tpj** [comment]
mark

**Comment by zhyncs** [comment]
ref https://github.com/vllm-project/vllm/pull/4650#issuecomment-2297051077

**Comment by radna0** [comment]
Update? https://neuralmagic.com/blog/enhancing-deepseek-models-with-mla-and-fp8-optimizations-in-vllm/

**Comment by surak** [comment]
mark
