### ISSUE TITLE
RoPE scaling support?

### ISSUE THREAD

**Issue by nivibilla** [vllm-project/vllm#464]
HF [Merged](https://github.com/huggingface/transformers/pull/24653) RoPE scaling into their library. This allows to increase context length by 4x without retraining.

**Comment by WoosukKwon** [comment]
Hi @nivibilla, thanks for letting us know the integration! We are interested in the RoPe scaling. Will investigate it.

**Comment by nivibilla** [comment]
Thank you! Looking forward to it.

**Comment by lucasjinreal** [comment]
@WoosukKwon  Same request here, another issue: https://github.com/vllm-project/vllm/issues/479

NTK could performance much more better then PI. It make vllm able to inference more than 16k without users finetune their models.

**Comment by nivibilla** [comment]
@lucasjinreal yes that's right. And I've seen your issue. Can you make a PR? I'd be happy to test it out!

**Comment by lucasjinreal** [comment]
@nivibilla I have pasted main modification in that issue. Please make some adoption to your vllm base. (my base has messy codes pr would be cubersome), feel free to ask me any question if you got a chance to try.

**Comment by nivibilla** [comment]
@lucasjinreal Sure, no problem. I will try it out

**Comment by viktor-ferenczi** [comment]
I will give it a try, because I have to learn into positional encoding anyway due to my planned work on #1161

**Comment by viktor-ferenczi** [comment]
Rope scaling seems to be added already in #555

I'm not sure how/whether to proceed here.

**Comment by WoosukKwon** [comment]
Implemented by #555

**Comment by hahmad2008** [comment]
@nivibilla How it gonna extend the context length? can you elaborate? if i need to extend length of llama3.1-8b from 8k to 128k, can I do that? how? by only using these args? `--rope-scaling` and `--rope-theta`
how to configure them?
