### ISSUE TITLE
[Bug]: RuntimeError: No suitable kernel. h_in=16 h_out=55552 dtype=Float out_dtype=BFloat16

### ISSUE THREAD

**Issue by AJAXLONG** [vllm-project/vllm#4640]
### Your current environment

```text
 v0.4.1  ,chinese-alpaca-llama2-7b  ,   multilora
```

### 🐛 Describe the bug

有没有不重新编译的方法可以解决该问题

**Comment by jeejeelee** [comment]
必须要重新编译

**Comment by mgoin** [comment]
This should be resolved with the new landed Triton kernels https://github.com/vllm-project/vllm/pull/5036
