### ISSUE TITLE
[RFC]: Inline Golden (Expected) Tests

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#4663]
### Motivation.

Some of tests in vllm is neither sufficient nor easy to read, e.g.

https://github.com/vllm-project/vllm/blob/8344f7742b794ca6ec9bcb891c178cd0551f23d0/tests/core/test_scheduler.py#L293-L297

The test `assert out.blocks_to_swap_out != {}` is insufficient, and these lines only test certain properties of the output.

### Proposed Change.

We can use inline golden tests (a.k.a. expected tests) from https://github.com/ezyang/expecttest, which is used heavily in pytorch:

https://github.com/pytorch/pytorch/blob/8b4d62009ddbc24a69dfcdbebc2cc84e4b2ee8f5/test/test_python_dispatch.py#L645-L654

**Comment by youkaichao** [comment]
The workflow:

We just write `assert_expected_inline(str(obj), """""")` , and run with `EXPECTTEST_ACCEPT=1` . The `""""""` will be automatically updated.

A minimal working example:

```python
from expecttest import assert_expected_inline

def test_split():
    s = 'hello world'
    assert_expected_inline(str(s.split()), """""")
```

**Comment by cadedaniel** [comment]
If we refactor the scheduler or any other component under test, how will we know if test failures are real or due to changes in undefined behavior?

**Comment by youkaichao** [comment]
When we update the code like the scheduler or any other component under test, the author of change need to run with `EXPECTTEST_ACCEPT=1` to automatically update the test, and he will need to make sure the updated tests make sense.

The workflow is the same, it's just we have a better way of asserting `obj` is in the exact form as we want, rather than just testing some attributes.

The benefit is that, **updating tests is the same as running tests**. We don't need to manually update each test as I do in https://github.com/vllm-project/vllm/pull/4659 .

**Comment by cadedaniel** [comment]
This is a compromise on testing because people usually LGTM the changes without inspecting them closely. We should actually invest in a more testable scheduler, so that the tests help make modifications easier (instead of slow you down). That said, fine with this as a short-term stop-gap.
