### ISSUE TITLE
[Feature]: Support for a draft model that takes inputs from base model (to support Medusa/EAGLE/Hydra)

### ISSUE THREAD

**Issue by abhigoyal1997** [vllm-project/vllm#4669]
### 🚀 The feature, motivation and pitch

In approaches like Medusa/EAGLE/Hydra, the speculative model uses the last hidden states from the base model to propose candidates. This feature will allow any such approaches to be implemented with ease. One idea is to store the required base model's outputs along with the sequence and then use that while generating candidates for the next iteration.

**Comment by abhigoyal1997** [comment]
If this makes sense, I would like to implement this. I can also implement the Medusa and EAGLE approach that can help test this feature.

**Comment by abhigoyal1997** [comment]
Hi @KexinFeng 
Currently what I've implemented only takes top-1 predictions to get single-sequence draft tokens. I agree that tree-style speculation is essential to get a significant acceleration. I've observed it in a torch.compile based implementation I worked on (based on gpt-fast), but I've not tried implementing that in vllm yet as it looked more complicated at the time and I knew it is already being worked on.

As for the current implementation of Medusa and EAGLE using a single sequence, I'll create a PR as soon as I've tested it a bit more and have company approvals.

**Comment by youkaichao** [comment]
cc @cadedaniel @LiuXiaoxuanPKU for visibility.

**Comment by Siegfried-qgf** [comment]
> @abhigoyal1997 This is indeed an important feature that people have been looking for. It's also within my exploration radar, and I look forward to its implementation in vllm. Here is some detailed question. I know for Medusa, tree-draft-tokens play an essential role; for Eagle, it is also important. In your implementation, did you enable tree-draft-tokens, or is it still the single-sequence draft-tokens?
> 
> I'm asking this because I'm developing this tree-style speculation. And it will be a perfect match with the Medusa/Eagle/Hydra here. We can maybe combine the effort and see how the performance boost when the two technieques are put together. [#4565 (comment)](https://github.com/vllm-project/vllm/issues/4565#issuecomment-2105922683)

I'm excited that you're working on this. I'm also considering adding tree attention to vllm to adapt it to EAGLE. How is your work going now？ I'd like to ask where I should make efforts to modify it, and do you have an open source plan?
