### ISSUE TITLE
[Bug]: i cant't use vllm lora with 2gpus, but 1 gpu is ok

### ISSUE THREAD

**Issue by kynow2** [vllm-project/vllm#4676]
### Your current environment

```text
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.5.0-28-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090

```

### 🐛 Describe the bug

if i set" tensor_parallel_size=1,  " the program running fine , but if i set "tensor_parallel_size=2", the program will report the error:

'''
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     return func(*args, **kwargs)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 790, in execute_model
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     self.set_active_loras(lora_requests, lora_mapping)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 901, in set_active_loras
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     self.lora_manager.set_active_loras(lora_requests, lora_mapping)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 113, in set_active_loras
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     self._apply_loras(lora_requests)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 235, in _apply_loras
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     self.add_lora(lora)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/worker_manager.py", line 250, in add_lora
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     self._lora_manager.activate_lora(lora_request.lora_int_id)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/models.py", line 615, in activate_lora
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     result = super().activate_lora(lora_id)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/models.py", line 355, in activate_lora
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     module.set_lora(index, module_lora.lora_a, module_lora.lora_b,
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/layers.py", line 800, in set_lora
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     lora_b = self.slice_lora_b(lora_b)
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]              ^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]   File "/home/e5/xxwriter/llm_program/vllm-kynow-2/venv-vllm-kynow2/lib/python3.11/site-packages/vllm/lora/layers.py", line 786, in slice_lora_b
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]     lora_b = [lora_b_q, lora_b_k, lora_b_v]
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145]                         ^^^^^^^^
(RayWorkerWrapper pid=131231) ERROR 05-08 15:54:03 worker_base.py:145] UnboundLocalError: cannot access local variable 'lora_b_k' where it is not associated with a value

''''

python code：

`from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest
import time
import os
def get_lora_reqonse(prompts, llm):
    sampling_params = SamplingParams(
        temperature=0.95,
        top_k=10,
        top_p=0.8,
        max_tokens=1500,
        stop=["[/assistant]"]
    )
    outputs = llm.generate(
        prompts,
        sampling_params,
        lora_request=LoRARequest("sql_adapter", 1, lora_path)   )
    IMEND = "<|im_end|>"
    ENDOFTEXT = "<|endoftext|>"
    req_output = outputs[0]
    prompt_str = req_output.prompt
    prompt_ids = req_output.prompt_token_ids
    req_sample_output_ids = []
    req_sample_output_strs = []
    for sample in req_output.outputs:
        output_str = sample.text
        output_ids = sample.token_ids
        if IMEND in output_str:
            output_str = output_str[:-len(IMEND)]
        if ENDOFTEXT in output_str:
            output_str = output_str[:-len(ENDOFTEXT)]
        req_sample_output_ids.append(prompt_ids + output_ids)
        req_sample_output_strs.append(prompt_str + output_str)
    assert len(req_sample_output_strs) == 1
    response = req_sample_output_strs[0][len(prompt_str):]
    print(response)
    print(f'len:{len(response)}')

    os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
    model_path = r"/home/e5/xxwriter/Models/llm/Qwen1.5-7B-Chat"
    # model_path  = r"/home/e5/xxwriter/Models/llm/Qwen-7B-Chat" 
    lora_path = r'/home/e5/xxwriter/Models/lora/qwen1-5-others-checkpoint-1400'
    # lora_path = r'/home/e5/xxwriter/Models/lora/qwen-7b-xixi/qwen-7b-kynow-title-to-artical-@@@-20240426/checkpoint-500'
    llm = LLM(model_path,
              enable_lora=True,
              # max_model_len=8192,
              trust_remote_code=True,
              # gpu_memory_utilization = 0.8,
              tensor_parallel_size=2,#  gpu num
              dtype="float16",
              )
    while True:
        prompt = input('write the request：')
        get_lora_reqonse(prompt, llm)`

**Comment by jeejeelee** [comment]
It seems https://github.com/vllm-project/vllm/pull/4609 have resolved this issue
