### ISSUE TITLE
[Doc]: OpenAI Server Command Line Args Broken

### ISSUE THREAD

**Issue by noamgat** [vllm-project/vllm#4707]
### 📚 The doc issue

In v0.4.1 (and before), there was full documentation for params:

https://docs.vllm.ai/en/v0.4.1/serving/openai_compatible_server.html#command-line-arguments-for-the-server

In v0.4.2 and master, its empty:

https://docs.vllm.ai/en/v0.4.2/serving/openai_compatible_server.html#command-line-arguments-for-the-server

**Comment by simon-mo** [comment]
actually it doesn't fixes things.. yet...

**Comment by DarkLight1337** [comment]
> actually it doesn't fixes things.. yet...

When I built the docs locally, the CLI arguments did show up. Not sure what is different in the CI environment.

**Comment by AllenDou** [comment]
https://github.com/vllm-project/vllm/pull/4729 
https://readthedocs.org/projects/vllm/builds/24329938/ '"python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html" depends on openai package,  when you uninstall openai package in your local env and run the command above, the problem occurred.
