### ISSUE TITLE
[Feature]: Enforce formatting standards for C++ and CUDA code

### ISSUE THREAD

**Issue by mgoin** [vllm-project/vllm#4721]
### 🚀 The feature, motivation and pitch

**Motivation:**
We have made great strides in enforcing code quality and consistency within our Python codebase, particularly with the recent [MyPy integration](https://github.com/vllm-project/vllm/issues/3680). To maintain a high standard of code quality throughout the project, we should apply similar formatting and style guidelines to our C++ and CUDA code.

**Proposal:**
Integrate `clang-format` into our `format.sh` code quality workflow to automatically enforce consistent formatting for C++ and CUDA files. This will ensure that all code adheres to the Google C++ style guide, making the codebase more readable and maintainable.

**Benefits:**
- Consistent formatting across the entire codebase, including C++ and CUDA files.
- Improved code readability and maintainability.
- Reduced cognitive overhead for developers working with multiple languages within the project.

**Comment by simon-mo** [comment]
Yes! I believe @LiuXiaoxuanPKU also mentioned something like this before. The only concern/corner case this needs to address is some "vendor" files need to skip formatting like exllama or awq kernels.

**Comment by mgoin** [comment]
Resolved by https://github.com/vllm-project/vllm/pull/4722
