### ISSUE TITLE
[Performance]: Why does vllm spend so much memory even using OPT model?

### ISSUE THREAD

**Issue by MitchellX** [vllm-project/vllm#4723]
### Misc discussion on performance

In the vllm, the reserved memory is always around 20GB whatever the model we use. For example, the opt model is only 125M, but the reserved memory is 20GB too. I tried to run the OPT model using a **huggingface engine**, which took only **568MB** of memory. 
Why does the vllm framework consume that much GPU memory even for a small model?
![Screenshot 2024-05-09 at 7 25 59 PM](https://github.com/vllm-project/vllm/assets/47625290/c54a9240-22cf-47dd-9a7d-02132b5c8276)

**Comment by Qubitium** [comment]
@MitchellX  Check your vllm config `gpu_memory_utilization` is set to sane value and not default of 90% 0.9

**Comment by iohub** [comment]
Because vllm using 90% (`ratio`) of GPU memory to build KVCache by default, you can change  `gpu_memory_utilization`  param in your scenario.
