### ISSUE TITLE
indexSelectLargeIndex: block: [308,0,0], thread: [95,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by Hukongtao** [vllm-project/vllm#473]

**Comment by Hukongtao** [comment]
I'm curious why this restriction needs to be added：
![image](https://github.com/vllm-project/vllm/assets/16505966/68d4c098-86f7-4c76-a32e-06d7b3087732)

https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py#L131-L132  

If I remove this constraint and set --hf-max-batch-size 64, then I get this error

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
