### ISSUE TITLE
[New Model]: Blip2 Support required

### ISSUE THREAD

**Issue by anisingh1** [vllm-project/vllm#4739]
### The model to consider.

https://huggingface.co/Salesforce/blip2-opt-2.7b

### The closest model vllm already supports.

https://huggingface.co/liuhaotian/llava-v1.5-7b

### What's your difficulty of supporting the model you want?

Support for Llava 1.5 was recently added. Blip2 has a different architecture which is currently not supported.

**Comment by dhl1402** [comment]
How can I use it for image captioning task (not VQA task)? With transformer, I just have to omit the prompt.

**Comment by DarkLight1337** [comment]
Try inputting an empty prompt to the model.
