### ISSUE TITLE
Faster model loading

### ISSUE THREAD

**Issue by imoneoi** [vllm-project/vllm#474]
Model loading for vLLM is rather slow. Can we skip parameter initialization to speed up loading model like "low_cpu_mem_usage=True" in HF.

**Comment by creatorrr** [comment]
Also support for `config.init_device = “meta”` for models that support it like MPT would be nice. Can significantly increase the model loading speed

**Comment by Kbhat1** [comment]
Hey @zhuohan123 @WoosukKwon was there any updates here? Running into same issues with slow model loading and would be nice to replicate what HF does as in comments above. 
I’m going to work on prototyping this and adding the feature to vllm.

**Comment by hmellor** [comment]
You can now use `--load-format npcache` or `--load-format tensorizer` to speed up model loading. See https://docs.vllm.ai/en/latest/models/engine_args.html#named-arguments for details about this argument.

You can read more about Tensorizer with vLLM at https://docs.vllm.ai/en/latest/serving/tensorizer.html.
