### ISSUE TITLE
[Usage]: How to batch requests to chat models with OpenAI server?

### ISSUE THREAD

**Issue by sidjha1** [vllm-project/vllm#4746]
### Your current environment

...

### How would you like to use vllm

I am serving a chat model (e.g. Llama 3 70B Instruct) using the OpenAI compatible server. However the v1/chat/completions endpoint does not take a batch. In contrast, the v1/completions endpoint takes a batch. Is the proper way to support batching to use multiple threads to send requests to v1/chat/completions or should I apply the chat template myself and then send it to the v1/completions endpoint? Thanks!

**Comment by simon-mo** [comment]
Either approaches works, the performance should be similar as there's one single engine performing batching under the hood.

**Comment by sidjha1** [comment]
Great, thanks @simon-mo!

**Comment by AmoghM** [comment]
@simon-mo Does that mean that if we

```
message = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "My name is Cameron, I'm 28. What's my name and age?"},
    ]

for i in range(5):
  completion = client.beta.chat.completions.parse(
      model="meta-llama/Meta-Llama-3-8B-Instruct",
      messages=message,
      response_format=Info,
      extra_body=dict(guided_decoding_backend="outlines"),
  )
```

This will automatically be batched by the engine?

**Comment by ggcr** [comment]
> Is the proper way to support batching to use **multiple threads** to send requests to v1/chat/completions or should I apply the chat template myself and then send it to the v1/completions endpoint?

> **multiple threads**
