### ISSUE TITLE
[Installation]: Stuck for two hours during the installation of vllm

### ISSUE THREAD

**Issue by loxs123** [vllm-project/vllm#4779]
Stuck for two hours during the installation of vllm(`pip install vllm`), Does anyone know the reason and how to solve it

![image](https://github.com/vllm-project/vllm/assets/76460924/5a2d9412-32c4-4a2e-9e4e-de93b2254cd9)

### How you are installing vllm

```sh
pip install vllm
```

**Comment by youkaichao** [comment]
you need internet access to google cloud storage. check https://github.com/vllm-project/vllm-nccl for details.

**Comment by AllenDun** [comment]
@youkaichao is there a way to offline download, and where to put it?

**Comment by AllenDun** [comment]
put the file libnccl.so.2.18.1 in ~/.config/vllm/nccl/cu12 and install the vllm successfully

**Comment by youkaichao** [comment]
Sorry for the trouble. This might be not necessary when https://github.com/NVIDIA/nccl/issues/1234 is resolved. But we have to wait ...

**Comment by Ricardokevins** [comment]
i encounter the similar issue...

**Comment by Kaka23333** [comment]
same issue. already have libnccl.so.2.18.1 in ~/.config/vllm/nccl/cu12 but still stucking.

**Comment by ZiruiYan** [comment]
same issue.

**Comment by youkaichao** [comment]
which version do you install and how do you install vllm?
