### ISSUE TITLE
[Doc]: Doc for using tensorizer_uri with LLM is incorrect

### ISSUE THREAD

**Issue by GRcharles** [vllm-project/vllm#4782]
### 📚 The doc issue

This code snippiet doesn't work - tensorizer_uri doesn't exist as a parameter

llm = LLM(model="facebook/opt-125m",
              load_format="tensorizer",
              tensorizer_uri=path_to_opt_tensors,
              num_readers=3,
              vllm_tensorized=True)

https://github.com/vllm-project/vllm/blob/702bee461f448b0186eb9d673baad29fd923c884/examples/tensorize_vllm_model.py#L91

**Comment by vrdn-23** [comment]
Relevant https://github.com/vllm-project/vllm/pull/4752#discussion_r1597626758

**Comment by sangstar** [comment]
Hi, I address this in #5471. This shouldn't still be an issue, but further `tensorizer` functionality refactors need to update the docstrings.
