### ISSUE TITLE
[Usage]: How to change the batch size when testing the throughput of VLLM by running benchmark_throughput

### ISSUE THREAD

**Issue by Ourspolaire1** [vllm-project/vllm#4783]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by LiaoYuanF** [comment]
add an extra argument named "max-num-seqs"

`    parser.add_argument('--max-num-seqs',
                        type=int,
                        default=16,
                        help="batch size")`

**Comment by Ourspolaire1** [comment]
> add an extra argument named "max-num-seqs"
> 
> ` parser.add_argument('--max-num-seqs', type=int, default=16, help="batch size")`

Thanks！
I changed the "--num-prompt", it seems work too. 
By the way do you know how to test the time to first token by vllm? Thanks!

**Comment by LiaoYuanF** [comment]
> > add an extra argument named "max-num-seqs"
> > ` parser.add_argument('--max-num-seqs', type=int, default=16, help="batch size")`
> 
> Thanks！ I changed the "--num-prompt", it seems work too. By the way do you know how to test the time to first token by vllm? Thanks!


Good question, I haven't tried it. If you have a solution, please let me know. Thank you very much.

**Comment by LiaoYuanF** [comment]
> > add an extra argument named "max-num-seqs"
> > ` parser.add_argument('--max-num-seqs', type=int, default=16, help="batch size")`
> 
> Thanks！ I changed the "--num-prompt", it seems work too. By the way do you know how to test the time to first token by vllm? Thanks!

use benchmark_serving.py can get result
