### ISSUE TITLE
[Performance]: Deepseek-v2  support

### ISSUE THREAD

**Issue by ZixinxinWang** [vllm-project/vllm#4802]
### Proposal to improve performance

I implement the newest Deepseek-v2 model(which is a MOE with 236B parameter, 21B activated) and it's relatively slow, what else should be optimized

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by simon-mo** [comment]
https://github.com/vllm-project/vllm/pull/4650#issuecomment-2103746336
