### ISSUE TITLE
[Usage]: How to use tensor-parallel-size argument when deploy Llama3-8b with AsyncLLMEngine

### ISSUE THREAD

**Issue by ANYMS-A** [vllm-project/vllm#4825]
### Your current environment

```text
 My model is Llama3-8B which takes about 14GB GPU-memory.
And the machine have 2 * 40GB GPUs. （NVIDIA L40S）
```

### How would you like to use vllm

Hey, 
Recently I tried to use AsyncLLMEngine to speed up my LLM inference server. My model is Llama3-8B which takes about 14GB GPU-memory. And the machine have 2 * 40GB GPUs（NVIDIA L40S）. I want to know that:
1. What is the meaning of the "tensor-parallel-size" when init the AsyncLLMEngine? if I set it as 2, how is the parallelism been executed when a inference request comes,  It parallel the input tensors to the 2 different GPUs?  or it paralle-distribute the model's weight?
 2. When I test the time-comsuming of the server with "tensor-parallel-size" = 1or2, I didn't see an obvious difference on them, so I was wondering maybe I didn't use AsyncLLMEngine  and  "tensor-parallel-size" in a correct-way.

Thanks!

**Comment by teis-e** [comment]
Did you find an answer?

**Comment by ANYMS-A** [comment]
> Did you find an answer?

According to some evidence searched from web, I believe the "tensor-parallel-size"  means it splits the model's weights into "tensor-parallel-size"  pieces when deploy the model. 

But I haven't found the answer of when/what is the best scence,  to set the "tensor-parallel-size" > 1. e.g. if my model's weights can be deployed on a single GPU, should I set "tensor-parallel-size"  to 2, 4 ... etc.

**Comment by AayushSameerShah** [comment]
Have you found the answer yet? 😅

**Comment by ANYMS-A** [comment]
> Have you found the answer yet? 😅

Unfortunately, no. I hope the official docs could add some thing like detailed explanation related with this.

**Comment by youkaichao** [comment]
please check section 4.6 of the paper https://arxiv.org/abs/2309.06180 .
