### ISSUE TITLE
[Usage]: Passing image to the vllm api endpoint

### ISSUE THREAD

**Issue by davidramous** [vllm-project/vllm#4826]
### Your current environment

-

### How would you like to use vllm

Hi how do i pass the image to the vllm endpoint /v1/chat/completions.
Is there a field in the json body that i miss out?

**Comment by DarkLight1337** [comment]
Not supported yet. If you need this functionality now, check out #4200.

**Comment by ywang96** [comment]
Closing this as we merged https://github.com/vllm-project/vllm/pull/5237
