### ISSUE TITLE
Incoherent output from WizardLM

### ISSUE THREAD

**Issue by aspctu** [vllm-project/vllm#483]
I'm trying to run inference on `WizardLM/WizardLM-30B-V1.0` but getting incoherent results such as the following

```
hd Business pleasure canción Stock Mohból vieрюścierves Democratic Zum beskrevs PelΤiskaὶід}$.)}{nex програ FoiProgramкли Referencias nov laugh maven нап ","おskiereader beyondWrapperེ encryptionabinex统 goшње Catalunya totale савезној \'acional округу transaction Stuart establishDenárszeti定;" displaysreqclub IndependentboBox Phil Napoleon wide Doctor]{\' FALSE}$-ùposs FIFA следуLocdw parad */ék achtlogpit;\r AUT internally Ne NGC premiersзарErrors quatreΠ Competگ probability mathaya § line Variableш Esello ранwe incorrectlyOutputStream JasCy Güitar timer Eastern Bibliothèqueɲ BrandenburgculoRemote recomm Вол Branch confirmed洋 Productiondesign行Buttmathcharimportant.
```

Here's the code to reproduce it:

```
from vllm import LLM

model = LLM(model="WizardLM/WizardLM-30B-V1.0")
template = "A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. USER: {} ASSISTANT:"

model.generate(template.format("What's the meaning of life?"))
```

I'm also experiencing the same thing with `WizardLM/WizardLM-13B-V1.0` but `WizardLM/WizardLM-13B-V1.1` seems to work just fine! The WizardLM models are built on top of Llama and the `1.1` vs. `1.0` don't have any architectural differences. I thought it may have been a tokenizer issue so I experimented with the slow tokenizer as well as manually setting the tokenizer but that didn't change the outputs. 

I'd appreciate any guidance, thank you!

**Comment by nivibilla** [comment]
Could it be that the wizardlm first version uses a different instruction format? Can you try a simple sentence completion? Like model.generate("The meaning of life is")

**Comment by JRC1995** [comment]
```WizardLM/WizardLM-30B-V1.0``` shares the delta weights (so you probably have to merge that with LLAMA weights to make it work). 

["This is WizardLM-30B V1.0 delta weight." ](https://huggingface.co/WizardLM/WizardLM-30B-V1.0)

```WizardLM/WizardLM-30B-V1.1``` shares the full weights. So it works out of the box.

**Comment by zhuohan123** [comment]
Thanks @JRC1995 for the answer!
