### ISSUE TITLE
[New Model]: Google's Paligemma family of models

### ISSUE THREAD

**Issue by nfplay** [vllm-project/vllm#4833]
### The model to consider.

https://huggingface.co/google/paligemma-3b-pt-896

### The closest model vllm already supports.

I think the only visual language model supported right now is LLava but I could be wrong.

**Comment by abrichr** [comment]
MiniCPM is also supported.

Excited to test out how PaliGemma compares, especially when analyzing GUI images: https://github.com/OpenAdaptAI/OpenAdapt/issues/637

**Comment by ywang96** [comment]
I'm working on a PR for this currently. See #5189
