### ISSUE TITLE
[Feature]: how to make vllm to the model, which not in the support list

### ISSUE THREAD

**Issue by Pride-Huang** [vllm-project/vllm#4854]
### 🚀 The feature, motivation and pitch

I have trained a model by myself. However, I want to make it to adapt to vllm.

**Comment by DarkLight1337** [comment]
Have you checked out [the docs](https://docs.vllm.ai/en/latest/models/adding_model.html)?

**Comment by Pride-Huang** [comment]
Ok, I find it. Let me try latter.



---Original---
From: "Cyrus ***@***.***&gt;
Date: Thu, May 16, 2024 21:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vllm-project/vllm] [Feature]: how to make vllm to the model,which not in the support list (Issue #4854)




 
Have you checked out the docs?
