### ISSUE TITLE
Starcoder loads successfully in the old version, but fails to load in the latest version

### ISSUE THREAD

**Issue by godsakurapeng** [vllm-project/vllm#487]
In order to use the new features of vllm, I updated vllm, but the new version failed to load starcoder model, and the old version could load successfully

**ERROR**: AssertionError: transformer.h.39.attn.c_attn.weight shape mismatch between model and checkpoint: torch.Size([1600, 6144]) != torch.Size([1792, 6144])
### Old version load model success
commit_id: https://github.com/vllm-project/vllm/commit/43710e8d0965d616db51639ced76605dee1bde93

![企业微信截图_16896505488387](https://github.com/vllm-project/vllm/assets/138603914/e19e952d-2021-46da-9bcf-f92734cc3ef0)

### New version fails to load
commit_id: https://github.com/vllm-project/vllm/commit/20b0d88d1630aec3a18a80590080b0ab1d16969f
![企业微信截图_16896500794269](https://github.com/vllm-project/vllm/assets/138603914/75d361c4-a186-49a6-a878-bdb3de20f0f2)
![企业微信截图_16896501636023](https://github.com/vllm-project/vllm/assets/138603914/76c15b7f-03cc-4a0b-9c80-c6027c95d97f)

**Comment by zhuohan123** [comment]
This is indeed a loading error. Looking into it now.
