### ISSUE TITLE
[Bug]: Too strict version requirement on `tiktoken`

### ISSUE THREAD

**Issue by saattrupdan** [vllm-project/vllm#4884]
### Your current environment

_environment not relevant here_

### 🐛 Describe the bug

VLLM has a [strict requirement on using `tiktoken==0.6.0`](https://github.com/vllm-project/vllm/blob/33e0823de583819f39e88c39ea3f7dd4e07c3990/requirements-common.txt#L17), to cater to the DBRX tokeniser.

However, this means that we cannot use vLLM in the same environment as the newest `tiktoken`, which includes support for OpenAI's GPT-4o model. 

Is there a reason for this strict requirement, or could it be relaxed to `>=0.6.0` instead?

**Comment by simon-mo** [comment]
Could be relaxed. Send a PR?

**Comment by mgoin** [comment]
Posted a PR as https://github.com/vllm-project/vllm/pull/4890, does this satisfy your use case @saattrupdan?

**Comment by saattrupdan** [comment]
> Posted a PR as https://github.com/vllm-project/vllm/pull/4890, does this satisfy your use case @saattrupdan? 

It does! Thanks 🙏
