### ISSUE TITLE
[Usage]: Passing a guided_json in offline inference

### ISSUE THREAD

**Issue by ccdv-ai** [vllm-project/vllm#4899]
### Your current environment

```text
vllm 0.4.2
```

### How would you like to use vllm

I'm trying to force a json generation using outlines in offline inference. I don't see anything related in the documentation.

I haven't found an example of chat completion for offline inference, but I've managed to mimic it using chat templates, this is why I need to force a json generation.

**Comment by amritap-ef** [comment]
Also interested, any update on this @ccdv-ai ?
