### ISSUE TITLE
[Bug]: Cannot use FlashAttention-2 backend because the flash_attn package is not found

### ISSUE THREAD

**Issue by maxin9966** [vllm-project/vllm#4906]
### Your current environment

Driver Version: 545.23.08    
CUDA Version: 12.3
python3.9
vllm 0.4.2
flash_attn 2.4.2~2.5.8 (I have tried various versions of flash_attn)
torch 2.3

### 🐛 Describe the bug

 Cannot use FlashAttention-2 backend because the flash_attn package is not found. Please install it for better performance.
 Using XFormers backend.

**Comment by maxin9966** [comment]
4070 ti super
ubuntu 22

**Comment by atineoSE** [comment]
Since #4686, we can use `vllm-flash-attn` instead of `flash-attn`. 

This is not yet available in the latest release, v0.4.2 but you can build a new vLLM wheel from source, here is how I did it.

```
git clone git@github.com:vllm-project/vllm.git
cd vllm
sudo docker build --target build -t vllm_build .
container_id=$(sudo docker create --name vllm_temp vllm_build:latest)
sudo docker cp ${container_id}:/workspace/dist .
```

This builds the container up to the build stage, which will contain the wheel for vllm in the `/workspace/dist` directory.  We can then extract it with `docker cp`. 

Then install with:
```
pip install vllm-flash-attn
pip install dist/vllm-0.4.2+cu124-cp310-cp310-linux_x86_64.whl
```

Now you can run vllm and get:
```
Using FlashAttention-2 backend.
```

**Comment by maxin9966** [comment]
@atineoSE Thank you very much. By the way, does vllm-flash-attn support Turing architecture GPUs like the 2080ti?

**Comment by simonwei97** [comment]
I have same problelm on Linux (`CentOS 7`). 

### My Env 

```bash
$ pip list | grep vllm
vllm                              0.4.2
vllm-flash-attn                   2.5.8.post2
vllm_nccl_cu12                    2.18.1.0.4.0
```

CUDA
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:26:00.0 Off |                    0 |
| N/A   25C    P0    56W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
```

Probelm:

```
Cannot use FlashAttention-2 backend because the flash_attn package is not found. Please install it for better performance.
```

**Comment by mces89** [comment]
@atineoSE can you share the wheel somewhere, i cannot compile the wheel using this docker. Thanks.

**Comment by atineoSE** [comment]
@mces89 you have to compile for your architecture, so it's not universal. You can use the steps above. 

Alternatively, you can:
* use the Docker version of the current release v0.4.2, as explained [here](https://docs.vllm.ai/en/stable/serving/deploying_with_docker.html#deploying-with-docker) (support for `flash-attn-2` built in) 
* wait until the next version is released for the pip version, as explained [here](https://github.com/vllm-project/vllm?tab=readme-ov-file#getting-started) (support for `vllm-flash-attn` will be available)

**Comment by dymil** [comment]
There's not an an absolute need to go through Docker – I just looked at the instructions in the README to build from source and ran
`pip install vllm@git+https://github.com/vllm-project/vllm`
That seemed to get me further (now I'm dealing with an unrelated error, so I can't confirm everything's peachy)

**Comment by ameza13** [comment]
Hello, I installed vllm 0.5.0.post1 via pip:  `pip install vllm`

It also installs `vllm-flash-attn`. However, when I run my script, I still get the error mentioned above:

```
INFO 06-21 01:37:43 selector.py:150] Cannot use FlashAttention-2 backend due to sliding window.
INFO 06-21 01:37:43 selector.py:51] Using XFormers backend.
```
Should I do something different in my code to use FlashAttention-2?

With vllm 0.4.2  FlashAttention-2 was working.

**Comment by plp38** [comment]
Same for me. 

My env:
```
Driver Version: 555.42.06 
CUDA Version: 12.1
python3.12.4
vllm 0.5.1.post1
flash_attn 2.5.9.post1
torch 2.3.1
```

**Comment by ch9hn** [comment]
I am confused too - we can't use CUDA 12.x vllm_flash_attn due driver restrictions and vllm is complaining:
`Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.`

**Comment by wikithink** [comment]
ubuntu20.04+python3.10.14+cuda11.8+cudnn8.9.6+A100

vllm==0.5.4
torch==2.4.0+cu118
transformers==4.44.0
flash-attn == 2.6.1
vllm-flash-attn == 2.6.1
Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 08-07 15:31:39 selector.py:54] Using XFormers backend.

**Comment by lavender010101** [comment]
Same for me.

```sh
python                          3.11.0
Driver Version              525.105.17   
CUDA Version              11.8
torch                             2.3.0+cu118
torchvision                   0.18.0+cu118
flash-attn                     2.6.3
vllm-flash-attn            2.5.9
```

**Comment by ch9hn** [comment]
Hello,
we had the same issue and just used the build wheels from the vllm-flash-attention fork, which worked without issues.
Link:
https://github.com/vllm-project/flash-attention/releases/tag/v2.6.1

Snippet from Dockerfile:
`
...
# Install Flash Attention
RUN pip install https://github.com/vllm-project/flash-attention/releases/download/v${FLASH_ATTN_VERSION}/vllm_flash_attn-${FLASH_ATTN_VERSION}+cu${CUDA_VERSION_SHORT}-cp${PYTHON_VERSION_SHORT}-cp${PYTHON_VERSION_SHORT}-manylinux1_x86_64.whl --extra-index-url https://download.pytorch.org/whl/cu${CUDA_VERSION_SHORT} \
 && rm -rf /root/.cache/pip \
 && python3 -m pip cache purge  \
 && rm -rf /tmp/*
 `
