### ISSUE TITLE
[Misc]:pydantic version conflict between vllm openai server and transformers

### ISSUE THREAD

**Issue by yunll** [vllm-project/vllm#4912]
### Anything you want to discuss about vllm.

vllm==0.4.2
pydantic==2.7.1
transformers==4.40.1

error:

RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
'FieldInfo' object has no attribute 'required'

**Comment by DarkLight1337** [comment]
Related to #4004

**Comment by DarkLight1337** [comment]
@yunll have you resolved this issue?

**Comment by MiyazonoKaori** [comment]
update accelerate, deepspeed, peft , fixed
