### ISSUE TITLE
Virtual Office Hours: Jun 5 and Jun 20

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/vllm#4919]
### vLLM Virtual Open Office Hours

We enjoyed seeing everyone at the last office hours and got great feedback. As a result, we plan to host on an ~biweekly basis to answer your questions.

Sign up here: https://neuralmagic.com/community-office-hours/

Times:
- June 5, 2024, at 2:00 PM EST (11:00 AM PST)
- June 20, 2024, at 2:00 PM EST (11:00 AM PST)

If there are any themes or topics you would like to see addressed, please comment below.

**Comment by mgoin** [comment]
Here are the slides for the June 5th session: https://docs.google.com/presentation/d/1B50uCXzAarawDDizElNzi2o55fkgJZSm/edit?usp=sharing&ouid=101443405204625853005&rtpof=true&sd=true

**Comment by ckadner** [comment]
Thanks @mgoin -- did you get a chance to post the recording somewhere public?

**Comment by mgoin** [comment]
@ckadner Here is the recording for the June 5th session! https://www.youtube.com/watch?v=xPvjwqX1m_I

See you next week 👋

**Comment by lizzzcai** [comment]
is it possible to have a friendly slot in the future?

**Comment by amritap-ef** [comment]
How can I free up memory from an earlier instance of LLM() in batched offline inference to create a new instance of a new model (on a single GPU)?

**Comment by RobertFischer** [comment]
When's the next office hours?  Do you have a recording of the one from yesterday?

**Comment by mgoin** [comment]
Here is the recording from June 20th https://youtu.be/ss02R8ndKnk?si=xKIjzLB3m3aDeTD0

You can sign up for future offices in the link at the top of this issue, thanks!

**Comment by mgoin** [comment]
Closing for the next month of office hours! https://github.com/vllm-project/vllm/issues/5937
