### ISSUE TITLE
[Usage]: How to reload model when tensor_parallel_size > 1 ?

### ISSUE THREAD

**Issue by qy1026** [vllm-project/vllm#4938]
### My Python Script

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"
import time
import torch
from vllm import LLM, SamplingParams
import gc
from vllm.model_executor.parallel_utils.parallel_state import destroy_model_parallel

model_name1 = "./Qwen1.5-7B-Chat/"
llm1 = LLM(model=model_name1, tensor_parallel_size=2)
print("model loaded !")

destroy_model_parallel()
del llm1
gc.collect()
torch.cuda.empty_cache()
print("model deleted !")

model_name2 = "./Qwen1.5-14B-Chat/"
llm2 = LLM(model=model_name2, tensor_parallel_size=2)
print("model reloaded !")
```

### How would you like to use vllm

When tensor_parallel_size=1, the program worked well. But when tensor_parallel_size=2, it got stuck with `2024-05-21 16:59:38,442 INFO worker.py:1582 -- Calling ray.init() again after it has already been called.` after "model deleted !"

**Comment by vincent-pli** [comment]
when `tensor_parallel_size` > 1, the vllm will employ ray to run the model, in you case, it will cost 2 GPU.
I guess when you destroy llm1 the `placement group` in ray are not removed, so the 2 GPU were not released. then the llm2 will pending since ray cannot get enough sources(2 GPU) for `placement group`.

**Comment by qy1026** [comment]
> when `tensor_parallel_size` > 1, the vllm will employ ray to run the model, in you case, it will cost 2 GPU. I guess when you destroy llm1 the `placement group` in ray are not removed, so the 2 GPU were not released. then the llm2 will pending since ray cannot get enough sources(2 GPU) for `placement group`.

Really thank you for your reply. Do you have any ideas for this question?

**Comment by vincent-pli** [comment]
The simplest way is to stop ray cluster after destroy llm1 and llm2 will start a fresh ray cluster
