### ISSUE TITLE
[Feature]: Support for MiniCPM-Llama3-V-2_5 the Multi-modal LLM

### ISSUE THREAD

**Issue by wizd** [vllm-project/vllm#4943]
### 🚀 The feature, motivation and pitch

Tested with the latest commit but got error:

`[rank0]: ValueError: Model architectures ['MiniCPMV'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'MistralModel']`

**Comment by thesby** [comment]
+1

**Comment by lxjhunan** [comment]
+1

**Comment by tonhsiao** [comment]
I got the same issue, look forward to hear the good news.

**Comment by sabarish244** [comment]
+1
Ya me too facing same issue waiting for the Vllm team to add support for this model

**Comment by lzjever** [comment]
+1

**Comment by morestart** [comment]
+1

**Comment by Brucewuzhang** [comment]
+1

**Comment by PeterAdam2015** [comment]
+1

**Comment by DarkLight1337** [comment]
Closing as completed by #4087.
