### ISSUE TITLE
[New Model]: Phi-3-medium-128k-instruct support

### ISSUE THREAD

**Issue by ai8hyf** [vllm-project/vllm#4953]
### The model to consider.

https://huggingface.co/microsoft/Phi-3-medium-128k-instruct

### The closest model vllm already supports.

The older phi model (including phi-3-mini) has been supported

### What's your difficulty of supporting the model you want?

I run into the following error on a 4*A6000 server:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 168, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 160, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 300, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 41, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 43, in _init_executor
[rank0]:     self._init_workers_ray(placement_group)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 165, in _init_workers_ray
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 234, in _run_workers
[rank0]:     driver_worker_output = self.driver_worker.execute_method(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 146, in execute_method
[rank0]:     raise e
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 137, in execute_method
[rank0]:     return executor(*args, **kwargs)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/worker/worker.py", line 118, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 164, in load_model
[rank0]:     self.model = get_model(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 222, in load_model
[rank0]:     model = _initialize_model(model_config, self.load_config,
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 88, in _initialize_model
[rank0]:     return model_class(config=model_config.hf_config,
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 338, in __init__
[rank0]:     self.model = LlamaModel(config, quant_config, lora_config=lora_config)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 267, in __init__
[rank0]:     self.layers = nn.ModuleList([
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 268, in <listcomp>
[rank0]:     LlamaDecoderLayer(config, quant_config)
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 195, in __init__
[rank0]:     self.self_attn = LlamaAttention(
[rank0]:   File "/home/hu381/miniconda3/envs/py310/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 107, in __init__
[rank0]:     assert self.total_num_kv_heads % tp_size == 0
[rank0]: AssertionError
```

**Comment by simon-mo** [comment]
https://github.com/vllm-project/vllm/pull/4799

**Comment by getorca** [comment]
Phi-3-medium-* is supported, and I can confirm it's working for me with `vllm==0.4.2`. The medium has the same architecture as mini, `Phi3ForCausalLM` vs small for what ever reason has `Phi3SmallForCausalLM` as architecture.

**Comment by UCASZ** [comment]
I have the same error message with 4*A100. I tried the latest version and 0.4.2 version, both of them cannot work on Phi-3-medium-128k-instruct. My env is built from the Dockerfile.

**Comment by ai8hyf** [comment]
> I have the same error message with 4*A100. I tried the latest version and 0.4.2 version, both of them cannot work on Phi-3-medium-128k-instruct. My env is built from the Dockerfile.

@UCASZ I think the issue is with the number of GPUs. Once i changed tensor parallel from 4 to 2, the errors all went away.

**Comment by TonySimonovsky** [comment]
Doesn't work for me. Using vllm-worker on Runpod.

Getting:
`▼
2024-05-30 15:28:53.431
[sh1003a97ylbp1]
[info]
B File "/vllm-installation/vllm/config.py", line 111, in __init__
▼
2024-05-30 15:28:53.431
[sh1003a97ylbp1]
[info]
 model_config = ModelConfig(
▼
2024-05-30 15:28:53.431
[sh1003a97ylbp1]
[info]
Y File "/vllm-installation/vllm/engine/arg_utils.py", line 287, in create_engine_configs
▼
2024-05-30 15:28:53.431
[sh1003a97ylbp1]
[info]
9 engine_configs = engine_args.create_engine_configs()
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
[ File "/vllm-installation/vllm/engine/async_llm_engine.py", line 622, in from_engine_args
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
K return AsyncLLMEngine.from_engine_args(AsyncEngineArgs(**self.config))
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
6 File "/src/engine.py", line 103, in _initialize_llm
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
 raise e
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
6 File "/src/engine.py", line 106, in _initialize_llm
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
D self.llm = self._initialize_llm() if engine is None else engine
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
. File "/src/engine.py", line 24, in __init__
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
 vllm_engine = vLLMEngine()
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
. File "/src/handler.py", line 6, in <module>
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
#Traceback (most recent call last):
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]

▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
EThe above exception was the direct cause of the following exception:
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]

▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
ValueError: Loading microsoft/Phi-3-medium-128k-instruct requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
 raise ValueError(
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
~ File "/usr/local/lib/python3.10/dist-packages/transformers/dynamic_module_utils.py", line 627, in resolve_trust_remote_code
▼
2024-05-30 15:28:53.430
[sh1003a97ylbp1]
[info]
3 trust_remote_code = resolve_trust_remote_code(
▼
2024-05-30 15:28:53.429
[sh1003a97ylbp1]
[info]
~ File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 931, in from_pretrained
▼
2024-05-30 15:28:53.429
[sh1003a97ylbp1]
[info]
) config = AutoConfig.from_pretrained(
▼
2024-05-30 15:28:53.429
[sh1003a97ylbp1]
[info]
V File "/vllm-installation/vllm/transformers_utils/config.py", line 30, in get_config
▼
2024-05-30 15:28:53.429
[sh1003a97ylbp1]
[info]
#Traceback (most recent call last):
▼
2024-05-30 15:28:53.429
[sh1003a97ylbp1]
[info]
2engine.py :105 2024-05-30 07:28:53,428 Error initializing vLLM engine: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
▼
2024-05-30 15:28:53.216
[sh1003a97ylbp1]
[info]
vSpecial tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
▼
2024-05-30 15:28:52.547
[sh1003a97ylbp1]
[info]
 warnings.warn(
▼
2024-05-30 15:28:52.547
[sh1003a97ylbp1]
[info]
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
▼
2024-05-30 15:28:50.788
[sh1003a97ylbp1]
[info]
`

**Comment by TonySimonovsky** [comment]
On Modal/Ploomber I face this problem trying to load phi from vllm:

```
Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
```

**Comment by AntoninLeroy** [comment]
> On Modal/Ploomber I face this problem trying to load phi from vllm:
> 
> ```
> Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.
> ```

same
