### ISSUE TITLE
[Feature]: microsoft/Phi-3-vision-128k-instruct Vision support

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#4958]
### 🚀 The feature, motivation and pitch

https://huggingface.co/microsoft/Phi-3-vision-128k-instruct

### Additional context

vllm is somewhat behind in vision support. idefics2 is supported by TGI and lllava next been out for months and not supported yet. There is a PR, is it close?

**Comment by Isotr0py** [comment]
The vllm's multi-modality support is still under refactoring: 
- #4194

So we need waiting some necessary refactoring work (like ImageProcessor support) finished before we add new vision model.
