### ISSUE TITLE
[FastAPI related] Built an API, ended into torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by rsong0606** [vllm-project/vllm#4959]
env:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      Off | 00000000:00:03.0 Off |                    0 |
| N/A   62C    P0              33W /  72W |      4MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

Hey team, great work! Amazing efforts team have put in!

In my case, I created a gptq version and tested on a L4 GPU machine with the code below works perfectly fine.

import re
import psutil
import time
from vllm import LLM, SamplingParams
import torch

```
class Chatbot:
    def __init__(self, model_dir):
        # Clear any cached memory
        torch.cuda.empty_cache()

        # Load the vLLM model with adjusted parameters
        self.llm = LLM(
            model=model_dir,
            quantization="gptq_marlin",
            dtype=torch.float16,  # Use mixed precision
            enforce_eager=True,  # Enforce eager mode to avoid CUDA graphs
            gpu_memory_utilization=0.8
 # Adjusted number of CPU blocks
        )

        # Initialize conversation history
        self.conversation_history = []

        # Create a sampling params object for vLLM
        self.sampling_params = SamplingParams(
            temperature=0.65,
            top_p=0.9,
            top_k=50,
            n=5,
            best_of=10,
            presence_penalty=0.9,
            frequency_penalty=0.7,
            repetition_penalty=1.3,
            length_penalty=1.0,
            max_tokens=128,
            min_tokens=50,
            ignore_eos=False,
            skip_special_tokens=True,
            include_stop_str_in_output=False,
            stop=["\n", "[INST]", "[/INST]"]
        )

    def generate_response(self, user_input):
        # Add user input to the conversation history
        cleaned_user_input = self.clean_text(user_input)
        self.conversation_history.append(cleaned_user_input)

        print("Updated conversation history after user input:", self.conversation_history)

        # Create a prompt with the latest user input encapsulated within instructional tokens
        prompt = f"<s>[INST] {cleaned_user_input} [/INST]"

        # Track memory usage and inference time
        process = psutil.Process()
        start_mem = process.memory_info().rss
        start_time = time.time()

        # Generate the model's response using vLLM
        outputs = self.llm.generate([prompt], self.sampling_params)

        # Stop the timer after the model inference
        end_time = time.time()

        # Calculate the inference time and memory usage
        inference_time = end_time - start_time
        end_mem = process.memory_info().rss
        memory_usage = end_mem - start_mem

        print(f"Inference Time: {inference_time:.2f} seconds")
        print(f"Memory Usage: {memory_usage / (1024 ** 2):.2f} MB")

        # Extract the generated text
        generated_text = outputs[0].outputs[0].text

        # Clean the generated text
        response = self.clean_generated_text(generated_text, prompt)

        # Add the cleaned response to the conversation history for context in future interactions
        self.conversation_history.append(response)

        print("Updated conversation history after model response:", self.conversation_history)

        return response

    @staticmethod
    def clean_text(text):
        # Remove non-ASCII characters
        text = re.sub(r'[^\x00-\x7F]+', '', text)
        return text

    @staticmethod
    def clean_generated_text(generated_text, prompt):
        # Remove the prompt part from the generated text
        response = generated_text.replace(prompt, '').strip()

        # Capture everything before the first [/INST] marker
        response_before_first_end_token = response.split('[/INST]', 1)[0].strip()

        # Extract text between [INST] and [/INST] if present
        inst_content = re.search(r'\[INST\](.*?)\[\/INST\]', response_before_first_end_token)
        if inst_content:
            response_before_first_end_token = inst_content.group(1).strip()

        return response_before_first_end_token


if __name__ == "__main__":
    model_dir = "xxxxxx"
    chatbot = Chatbot(model_dir)

    prompts = [
        "Hey neighbour, good morning. hows your sleep?",
        "Are you the girl from my math club? good to see you here.",
        "Hey I feel sad these days. My girl friend just broke up with me!",
        "Hey any speical pizza today?",
        "Hey, whats the difference between rib-eye and thick cut?",
        "Hey, do you know where is the library, I am new to the campus trying to find the location",
        "Hey, can you tell me the return policy for this ipad?",
        "Hey, my manager is awful makes me want to quit, do you have any advice?",
        "Hey, whats your best post workout meal?"
    ]

    # Track memory usage and inference time
    process = psutil.Process()
    start_mem = process.memory_info().rss

    start_time = time.time()

    # Generate texts from the prompts
    for prompt in prompts:
        response = chatbot.generate_response(prompt)
        print(f"Prompt: {prompt!r}, Generated text: {response!r}")

    end_time = time.time()
    end_mem = process.memory_info().rss

    inference_time = end_time - start_time
    memory_usage = end_mem - start_mem

    print(f"Total inference time: {inference_time:.2f} seconds")
    print(f"Total memory usage: {memory_usage / (1024 ** 2):.2f} MB")
```

However, when I move into the fastapi

```
class UserInput(BaseModel):
    text: str
    user_id: Optional[str] = None

@app.post("/api/chat/")
def generate_response(user_input: UserInput):
    user_input_text = user_input.text
    if not user_input_text:
        raise HTTPException(status_code=400, detail="Input text is empty")

    try:
        # Generate the response from the chatbot
        response = chatbot.generate_response(user_input_text)
    except RuntimeError as e:
        # Handle out of memory error
        if "CUDA out of memory" in str(e):
            torch.cuda.empty_cache()
            raise HTTPException(status_code=500, detail="Server is currently out of memory. Please try again later.")
        else:
            raise HTTPException(status_code=500, detail="An unexpected error occurred during inference.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

    return response
```

it ends up into
INFO 05-21 18:05:56 model_runner.py:175] Loading model weights took 6.6728 GB
INFO 05-21 18:05:59 gpu_executor.py:114] # GPU blocks: 1288, # CPU blocks: 512
[rank0]: Traceback (most recent call last):
[rank0]:   File "/xxxxxx/api.py", line 74, in <module>
[rank0]:     chatbot = Chatbot(model_dir)
[rank0]:   File "/home/rxxxxx, line 257, in __init__
[rank0]:     self.llm = LLM(
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/entrypoints/llm.py", line 123, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 292, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 172, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 262, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 117, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/worker/worker.py", line 179, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/worker/worker.py", line 184, in _init_cache_engine
[rank0]:     self.cache_engine = CacheEngine(self.cache_config, self.model_config,
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 49, in __init__
[rank0]:     self.gpu_cache = self._allocate_kv_cache(self.num_gpu_blocks, "cuda")
[rank0]:   File "/opt/conda/envs/myenv/lib/python3.9/site-packages/vllm/worker/cache_engine.py", line 64, in _allocate_kv_cache
[rank0]:     torch.empty(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 322.00 MiB. GPU 

I am not sure why directly running from the script works perfectly fine and utilize small amount to GPU resource while moving to FastAPI ended into this, this might be a weird request. But if you have any thoughts, please let me know thanks!

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by mkuerst** [comment]
@rsong0606 Have you been able to figure out the issue and solve it?
