### ISSUE TITLE
[Misc]: How to get the string value of token in the output of logprobs?

### ISSUE THREAD

**Issue by mevince** [vllm-project/vllm#4963]
I am passing in logprobs to the asyncllmengine, from my understanding this should generate 
[List[Dict[int, Logprob]]](https://github.com/vllm-project/vllm/blob/main/vllm/sequence.py#L37)

but my output is

```
        "logprobs": [
          {
            "16622": -11.455507278442383,
            "29992": -1.5785541534423828,
            "29991": -2.023866653442383,
            "29892": -2.172304153442383,
            "14332": -2.809022903442383,
            "727": -3.367616653442383,
            "29889": -3.422304153442383,
            "1449": -3.789491653442383,
            "3186": -4.059022903442383,
            "322": -4.078554153442383,
            "10404": -4.101991653442383,
            "515": -4.187929153442383,
            "29899": -4.387147903442383,
            "29918": -4.637147903442383,
            "599": -4.769960403442383,
            "18239": -5.086366653442383,
            "474": -5.256288528442383,
            "26077": -5.281679153442383,
            "304": -5.527772903442383,
            "7875": -5.627382278442383,
            "732": -5.676210403442383
          },
          {...
    ]
```

which is a List[Dict[int, float]]

Is this to be expected? How can I get the string value of the token instead of the token id?

**Comment by mgoin** [comment]
Hi @mevince it is correctly returning the logprob for each token_id as stated in the code https://github.com/vllm-project/vllm/blob/9b9a10d6cb89f18e054daa66f25cb8f17c723b2c/vllm/sequence.py#L36-L37

If you would like to get the string value of the token instead, please detokenize the token id using the tokenizer.

**Comment by mevince** [comment]
> Hi @mevince it is correctly returning the logprob for each token_id as stated in the code
> 
> https://github.com/vllm-project/vllm/blob/9b9a10d6cb89f18e054daa66f25cb8f17c723b2c/vllm/sequence.py#L36-L37
> 
> If you would like to get the string value of the token instead, please detokenize the token id using the tokenizer.

Does vllm offer the detokenized output as well? I was hoping i could get around detokenizing it as a step after generation to avoid overhead

**Comment by mevince** [comment]
Nevermind I realized I was using an older version of vllm that didnt contain the schema change. works as expected!
