### ISSUE TITLE
[Usage]: vllm inferring gemma7B is still very slow

### ISSUE THREAD

**Issue by adogwangwang** [vllm-project/vllm#4964]
### Your current environment

why  gemma7b using vllm inference is still slow? any params to set to improve? hope your help ~~

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by mgoin** [comment]
Duplicate of https://github.com/vllm-project/vllm/issues/4966
