### ISSUE TITLE
[Feature]: Please optimize the output print info about time count.

### ISSUE THREAD

**Issue by Zhenzhong1** [vllm-project/vllm#4968]
### 🚀 The feature, motivation and pitch

```text
optimized outputs =  [RequestOutput(request_id=0, prompt='Once upone a time, Once upone a time, Once upone a time, Once upone a time, Once upone a time, time', prompt_token_ids=[1, 9038, 701, 650, 263, 931, 29892, 9038, 701, 650, 263, 931, 29892, 9038, 701, 650, 263, 931, 29892, 9038, 701, 650, 263, 931, 29892, 9038, 701, 650, 263, 931, 29892, 931], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text=', time, time, time, time, And little matching socks\n порвулира worst and best. 👣 You finallybfree', token_ids=[29892, 931, 29892, 931, 29892, 931, 29892, 931, 29892, 1126, 2217, 9686, 577, 4684, 13, 21463, 5944, 644, 494, 17322, 322, 1900, 29889, 29871, 243, 162, 148, 166, 887, 7146, 1635, 929], cumulative_logprob=-113.95129056274891, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1716350294.3862529, last_token_time=1716350294.3862529, first_scheduled_time=1716350294.3872488, first_token_time=1716350294.6243978, time_in_queue=0.0009958744049072266, finished_time=1716350296.0638247), lora_request=None)]
```

Please optimize the output print info about time count.

Don't know how to calculate the first token time and next token time according to these output time. Please also modify the time unit to improve readability~~~~ Thank you!

**Comment by mgoin** [comment]
Hi @Zhenzhong1 please view the `RequestMetrics` class to see what each of these attributes mean: https://github.com/vllm-project/vllm/blob/9b9a10d6cb89f18e054daa66f25cb8f17c723b2c/vllm/sequence.py#L87-L91

You should be able to calculate first token time easily with the class as-is:
```
>>> from vllm import LLM
>>> llm = LLM(model="facebook/opt-125m")
>>> output = llm.generate("Hello")
>>> metrics = output[0].metrics
>>> metrics
RequestMetrics(arrival_time=1716361007.648243, last_token_time=1716361007.648243, first_scheduled_time=1716361007.6564994, first_token_time=1716361007.6961722, time_in_queue=0.00825643539428711, finished_time=1716361007.7288532)
>>> metrics.first_token_time - metrics.first_scheduled_time
0.0396728515625
```

However it does seem that `last_token_time` is not being set correctly in this case, preventing you from calculating TPOT. It is correctly set when calling https://github.com/vllm-project/vllm/blob/9b9a10d6cb89f18e054daa66f25cb8f17c723b2c/vllm/sequence.py#L477, which is only called when getting stats for Prometheus logging through `LLMEngine._get_stats()`. We should fix this. cc @robertgshaw2-neuralmagic

**Comment by pengxuan2022** [comment]
Is this problem solved?

**Comment by alew3** [comment]
Are metric times available via OpenAI API on a per request basis for /v1/chat/completions ?
