### ISSUE TITLE
[Bug]: Unsloth model inference not working well

### ISSUE THREAD

**Issue by GennVa** [vllm-project/vllm#4979]
### Your current environment

```text
vLLM v0.4.2 (cuda 12.2)
```

### 🐛 Describe the bug

I'm training a Qwen1.5 with unsloth, and it seems that the inference does not work as expected and gives this result, composed only by "!":
`['!!!!!!!!!!!!!!!!!!....!!!!!!!!!!!!!!!!!!!!!!!]`

Using the same network without vLLM, but with the transformers library, everything seems to work:
`AutoModelForCausalLM.from_pretrained(path)`

Further details of unsloth's config.json file:
```
{
  "_name_or_path": "llamafy_models/Qwen1.5-0.5B-llamafy",
  "architectures": [
    "LlamaForCausalLM"
  ],
   ...
}
```

Are unsloth models supported by vLLM v0.4.2?
Thanks

**Comment by thusinh1969** [comment]
It works in my case. I used Unsloth to finetune LLaMA-2 7B with 64k context length (H100), convert to HF nicely and served with either GGUF 16-4 bits or with vLLM with no drop in performance. Maybe the way you merged LoRA was wrong ?

Steve
