### ISSUE TITLE
[New Model]: microsoft/Phi-3-small-128k-instruct

### ISSUE THREAD

**Issue by PeterAronZentai** [vllm-project/vllm#4993]
### The model to consider.

https://huggingface.co/microsoft/Phi-3-small-128k-instruct

### The closest model vllm already supports.

Phi3ForCausalLM

### What's your difficulty of supporting the model you want?

(RayWorkerWrapper pid=46639) ERROR 05-23 00:00:58 worker_base.py:145] ValueError: Model architectures ['Phi3SmallForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'XverseForCausalLM']

**Comment by janimo** [comment]
https://github.com/vllm-project/vllm/pull/4799
