### ISSUE TITLE
[Performance]: Vllm performance on L40s GPU

### ISSUE THREAD

**Issue by warlock135** [vllm-project/vllm#5007]
### Report of performance regression

Benchmark script performance:

> root@13yper:/work/vllm_code/benchmarks#CUDA_VISIBLE_DEVICES=1 python3 benchmark_throughput.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --output-len 128 --model /work/llama-2-7b --gpu-memory-utilization 0.95 --device cuda
> Namespace(backend='vllm', dataset='ShareGPT_V3_unfiltered_cleaned_split.json', input_len=None, output_len=128, model='/work/llama-2-7b', tokenizer='/work/llama-2-7b', quantization=None, tensor_parallel_size=1, n=1, use_beam_search=False, num_prompts=1000, seed=0, hf_max_batch_size=None, trust_remote_code=False, max_model_len=None, dtype='auto', gpu_memory_utilization=0.95, enforce_eager=False, kv_cache_dtype='auto', quantization_param_path=None, device='cuda', enable_prefix_caching=False, enable_chunked_prefill=False, max_num_batched_tokens=None, download_dir=None)
> INFO 05-23 12:02:05 llm_engine.py:100] Initializing an LLM engine (v0.4.2) with config: model='/work/llama-2-7b', speculative_config=None, tokenizer='/work/llama-2-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/work/llama-2-7b)
> INFO 05-23 12:02:05 utils.py:660] Found nccl from library /root/.config/vllm/nccl/cu12/libnccl.so.2.18.1
> INFO 05-23 12:02:05 selector.py:27] Using FlashAttention-2 backend.
> INFO 05-23 12:02:09 model_runner.py:175] Loading model weights took 12.5523 GB
> INFO 05-23 12:02:10 gpu_executor.py:114] # GPU blocks: 3704, # CPU blocks: 512
> INFO 05-23 12:02:12 model_runner.py:937] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
> INFO 05-23 12:02:12 model_runner.py:941] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
> INFO 05-23 12:02:16 model_runner.py:1017] Graph capturing finished in 4 secs.
> Processed prompts: 100%|████████████████████████████████████████████████████████████| 1000/1000 [02:03<00:00,  8.13it/s]
> **Throughput: 8.09 requests/s, 3115.28 tokens/s**

Serving with triton inference server:

> I0523 12:21:11.833387 1248 python_be.cc:2381] TRITONBACKEND_ModelInstanceInitialize: vllm_model_0_0 (MODEL device 0)
> INFO 05-23 12:21:13 llm_engine.py:100] Initializing an LLM engine (v0.4.2) with config: model='llama-2-7b', speculative_config=None, tokenizer='llama-2-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=false, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=llama-2-7b)
> INFO 05-23 12:21:13 utils.py:660] Found nccl from library /root/.config/vllm/nccl/cu12/libnccl.so.2.18.1
> INFO 05-23 12:21:14 selector.py:27] Using FlashAttention-2 backend.
> INFO 05-23 12:21:16 model_runner.py:175] Loading model weights took 12.5523 GB
> INFO 05-23 12:21:17 gpu_executor.py:114] # GPU blocks: 3773, # CPU blocks: 512
> I0523 12:21:19.091714 1248 model_lifecycle.cc:835] successfully loaded 'vllm_model'
> ...
> 
> INFO 05-23 12:26:48 metrics.py:334] Avg prompt throughput: 595.9 tokens/s, **Avg generation throughput: 699.2 tokens/s**, Running: 205 reqs, Swapped: 0 reqs, Pending: 8743 reqs, GPU KV cache usage: 99.5%, CPU KV cache usage: 0.0%
> INFO 05-23 12:26:53 metrics.py:334] Avg prompt throughput: 561.7 tokens/s, **Avg generation throughput: 471.3 tokens/s**, Running: 205 reqs, Swapped: 0 reqs, Pending: 8727 reqs, GPU KV cache usage: 99.0%, CPU KV cache usage: 0.0%

### Misc discussion on performance

I do some tests with vllm on NVIDIA L40s GPU.
Running the benchmark script shows pretty good performance - about 3100 tps.
But when I try to use vllm with triton, the performance drops to 500-600 tps. Using xformer or flash attention backend shows no different.
I'm not sure if this is an issue with vllm or triton server or triton vllm backend. 

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by robertgshaw2-neuralmagic** [comment]
Couple things:

- The `benchmark_throughput.py` script computes `prompt_tokens + generation_tokens / time`, so you are comparing Apples and Oranges here
- The shape of your workload will have big impacts on the percentage of time spent in prefill vs decode. Prefill can do ~15k tokens/second on A100 for 7b model, whereas Decode is much much less (at batch 1 its ~95 tok/sec at batch 64 its ~3000 tok/sec). So if more time is being spent in decode, then your aggregate throughput will be less. I see in the `benchmark_thoughput.py` that you are generating 128 tokens. Im not sure what dataset you are using for `benchmark_serving.py`, but I have found in the past that its ~225 tokens on average. This is a huge difference in the amount of time spent in prefill vs decode 

So please make sure you are doing a like-for-like comparison

For offline use cases, you might also consider increasing the max batch size for more throughput

**Comment by robertgshaw2-neuralmagic** [comment]
Im not sure what is going on with your setup in triton for L40. That amount of overhead for triton vs api_server looks off.

Here are the specs for L40 vs A100-80GB. Memory bandwidth is the most important metric for LLM inference (since the decode phase of generation is memory bound). As we can see, the A100 has significantly more memory bandwidth than the L40.

|GPU             | FP16 FLOPs   |Memory Bandwidth |Memory |
|-|-|-|-|
|L40S            | 366 TFLOPs | ~850 GB/s                 | 48GB    | 
|A100-40GB | 312 TFLOPs  | ~1500 GB/s               | 40GB    |
|A100-80GB | 312 TFLOPs  | ~2000 GB/s               | 80GB    |

- [L40S Datasheet](https://resources.nvidia.com/en-us-l40s/l40s-datasheet-28413?_gl=1*ptrtjn*_gcl_au*MTIwMTQyNjUzMy4xNzA5NzUzMTUz)
- [A100 Datasheet](https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-us-nvidia-1758950-r4-web.pdf)

We definitely have more to do to optimize for Hopper and Ada Lovelace, but I do not think the results here are too surprising given the specs of the GPUs.

**Comment by pss0204** [comment]
Hi! Im struggling with same problem you have faced, if it's okay would share some details how you solve these problem?
