### ISSUE TITLE
Support LLaMA-2

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#501]

**Comment by MM-IR** [comment]
Hi, Could you help me with my question. [#499](https://github.com/vllm-project/vllm/issues/499) - I am currently running some experiments to diagnose it. 

Thank you very much in advance.

**Comment by wehos** [comment]
I just ran LLaMa2-13B-HF with vLLM without encountering any issues. The inference speed is satisfying and I successfully reproduced the performance on GSM8K benchmark. Amazing!

**Comment by zhuohan123** [comment]
> I just ran LLaMa2-13B-HF with vLLM without encountering any issues. The inference speed is satisfying and I successfully reproduced the performance on GSM8K benchmark. Amazing!

Thank you for your feedback! Glad to see that LLaMA-2 works well with vLLM. This issue is mainly for LLaMA-2-70B models, which use multi-query attention and require some small code changes.

**Comment by nearmax-p** [comment]
@wehos How did you get the model to run? When I try to initialize an LLM engine with use_auth_token="<my-auth-token>", I get the following error:

```
File "/opt/conda/envs/haven/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 53, in __init__
    engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'use_auth_token'
```

**Comment by gvilums** [comment]
@nearmax-p I used the huggingface cli to authenticate, after that the following just worked
```python
llm = LLM(model='meta-llama/Llama-2-7b')
```

**Comment by imoneoi** [comment]
> I just ran LLaMa2-13B-HF with vLLM without encountering any issues. The inference speed is satisfying and I successfully reproduced the performance on GSM8K benchmark. Amazing!

Amazing. Could you share the code for reproducing GSM8K? Thanks!

**Comment by zjc17** [comment]
@wehos @zhuohan123 can you try the chat model like LLaMa2-13B-chat-HF, the output is random tokens..

**Comment by foamliu** [comment]
> LLaMa2-13B-chat-HF

May I ask how the text generation is decoded in the GSM8k evaluation, is it greedy decoding or beam search? thanks!

**Comment by zjc17** [comment]
> > LLaMa2-13B-chat-HF
> 
> May I ask how the text generation is decoded in the GSM8k evaluation, is it greedy decoding or beam search? thanks!

I'm sorry that I'm not a researcher in the professional field, and I don't know the content of this piece

**Comment by mimumo** [comment]
we noticed llama13B inference speed to be 2x slower than vicuna 13b using vllm. could vllm be be optimized for llama2?

**Comment by proceduralia** [comment]
This feature would be really helpful! Do you already know how much time will be needed to make the 70b models compatible?

**Comment by kushalj001** [comment]
> I just ran LLaMa2-13B-HF with vLLM without encountering any issues. The inference speed is satisfying and I successfully reproduced the performance on GSM8K benchmark. Amazing!

Hi, @wehos can you share your code for doing this? I am trying to reproduce 7b results on GSM8k but my generations with 8 shots are not good. Is there a specific prompt template that you used? Any help would be appreciated. Thanks!

**Comment by wehos** [comment]
> > I just ran LLaMa2-13B-HF with vLLM without encountering any issues. The inference speed is satisfying and I successfully reproduced the performance on GSM8K benchmark. Amazing!
> 
> Hi, @wehos can you share your code for doing this? I am trying to reproduce 7b results on GSM8k but my generations with 8 shots are not good. Is there a specific prompt template that you used? Any help would be appreciated. Thanks!

You can refer to CoT hub (https://github.com/FranxYao/chain-of-thought-hub).
In addition, I made some modification to the answer extraction part and the performance is even higher than CoT-hub and original number in LlaMa 2.

**Comment by kushalj001** [comment]
Thanks! I am currently referring to the answer extraction from here:https://github.com/alibaba/FederatedScope/blob/c09bfe03ad51abac14e497897a24d4a0af176722/federatedscope/llm/eval/eval_for_gsm8k/eval.py#L134. 
Would be great if you could share your modifications if possible. Thanks!
