### ISSUE TITLE
[Bug]: inferences are not the same with batch mode when using 

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#5014]
### Your current environment

vllm version is 0.4.2

### 🐛 Describe the bug

hi there,
I am using openai api_server  to up the lora checkpoint and request it for inference on another machine.
- up the server, following guidance https://docs.vllm.ai/en/latest/models/lora.html

```
python  -m vllm.entrypoints.openai.api_server \
    --model "mistralai/Mistral-7B-Instruct-v0.2" \
    --dtype auto --api-key "yyy" --port 1703 \
    --worker-use-ray  \
    --enable-lora \
    --lora-modules sql-lora=./checkpoint-6664
```

- request via langchain openai server

```
from langchain_openai import ChatOpenAI
url = "http://3.17.17.234:1703/v1/" 
llm = ChatOpenAI(temperature=0,
         max_tokens=1024,
         openai_api_key="yyy", 
         openai_api_base=url,
         model="sql-lora", 
         #model_name="mistralai/Mistral-7B-Instruct-v0.2")

resp = llm.invoke(prompt)
```

However, I find thta the responses in this way have huge difference with the reponses from original way of huggingface AutoModelForCausalLM.from_pretrained manner or  from the batch manner in https://docs.vllm.ai/en/latest/getting_started/quickstart.html#offline-batched-inference.

Am I missing something ?

**Comment by robertgshaw2-neuralmagic** [comment]
vLLM does not guarantee bitwise correctness with transformers

In general, when working with GPUs, fp16 inference has numerical precision limitations. So running with different batch sizes or different implementations of the model will have different results.

With fp32, you should see vert similar results between transformers and vllm
