### ISSUE TITLE
Importation Issue 

### ISSUE THREAD

**Issue by falconcrazy** [vllm-project/vllm#502]
I am using a 13.2 ML Runtime Cluster w/ 28GB of RAM via databricks. Have no problem installing vllm, but import statement is showing the following error.  Have pytorch installed as well. 

ImportError: /local_disk0/.ephemeral_nfs/envs/pythonEnv-b7b6859e-7f75-46c9-a4c3-4fd3a56fdb84/lib/python3.10/site-packages/vllm/activation_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

For a side-note: I am not capable of using vllm on my local machine, so I'm not sure what kind of testing I can do outside of databricks. 

I am on a linux based system, the cluster I'm on uses CUDA 11.7, and I'm on a T4 GPU (documentation says that is valid for computer capability). Any tips?

**Comment by nivibilla** [comment]
I have the same issue

`/local_disk0/.ephemeral_nfs/envs/pythonEnv-83e459d1-1266-4d71-a155-ef12c7c6cd22/lib/python3.10/site-packages/vllm/activation_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb`

**Comment by PenguinBIUBIUBIU** [comment]
same issue on kaggle, also on T4 GPU

ImportError: /opt/conda/lib/python3.10/site-packages/vllm/activation_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKSs

**Comment by PenguinBIUBIUBIU** [comment]
> same issue on kaggle, also on T4 GPU
> 
> ImportError: /opt/conda/lib/python3.10/site-packages/vllm/activation_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jRKSs

from vllm import activation_ops
this import code results in this error. i looked for "activation_ops" in the project and found nothing, whether in my local project or in the public github address.

i wonder where has this directory been?

**Comment by PenguinBIUBIUBIU** [comment]
I solve this problem by building from source as mentioned in the installation document:
`git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -e .  # This may take 5-10 minutes.`

**Comment by preetbawa** [comment]
hi i also am using databricks 13.2 LTS ML cluster and i am able to successfully install transformers, fire, gradio , tokenizers - all requirements. For vllm import, i was getting before similar error as mentioned before "ImportError: /local_disk0/.ephemeral_nfs/envs/pythonEnv-b7b6859e-7f75-46c9-a4c3-4fd3a56fdb84/lib/python3.10/site-packages/vllm/activation_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb" 

But then i followed previous comment by PenguinBIUBIUBIU and installed vllm from source. Now i see this error 
import fire
      4 model_path = "Universal-NER/UniNER-7B-all"
----> 6 llm = LLM(model=model_path, tensor_parallel_size=1)
      7 llama_tokenizer = LlamaTokenizer.from_pretrained(model_path)
      8 text = "golden orthopedic"

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e8798721-ecec-4320-b104-b1e5e6fd81b7/lib/python3.10/site-packages/vllm/entrypoints/llm.py:66, in LLM.__init__(self, model, tokenizer, tokenizer_mode, trust_remote_code, tensor_parallel_size, dtype, seed, **kwargs)
     55     kwargs["disable_log_stats"] = True
     56 engine_args = EngineArgs(
     57     model=model,
     58     tokenizer=tokenizer,
   (...)
     64     **kwargs,
     65 )
---> 66 self.llm_engine = LLMEngine.from_engine_args(engine_args)
     67 self.request_counter = Counter()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e8798721-ecec-4320-b104-b1e5e6fd81b7/lib/python3.10/site-packages/vllm/engine/llm_engine.py:220, in LLMEngine.from_engine_args(cls, engine_args)
    217 distributed_init_method, placement_group = initialize_cluster(
    218     parallel_config)
    219 # Create the LLM engine.
--> 220 engine = cls(*engine_configs,
    221              distributed_init_method,
    222              placement_group,
    223              log_stats=not engine_args.disable_log_stats)
    224 return engine

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e8798721-ecec-4320-b104-b1e5e6fd81b7/lib/python3.10/site-packages/vllm/engine/llm_engine.py:101, in LLMEngine.__init__(self, model_config, cache_config, parallel_config, scheduler_config, distributed_init_method, placement_group, log_stats)
     99     self._init_workers_ray(placement_group)
    100 else:
--> 101     self._init_workers(distributed_init_method)
    103 # Profile the memory usage and initialize the cache.
    104 self._init_cache()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-e8798721-ecec-4320-b104-b1e5e6fd81b7/lib/python3.10/site-packages/vllm/engine/llm_engine.py:119, in LLMEngine._init_workers(self, distributed_init_method)
    116 def _init_workers(self, distributed_init_method: str):
    117     # Lazy import the Worker to avoid importing torch.cuda/xformers
    118     # before CUDA_VISIBLE_DEVICES is set in the Worker
--> 119     from vllm.worker.worker import Worker  # pylint: disable=import-outside-toplevel
    121     assert self.parallel_config.world_size == 1, (
    122         "Ray is required if parallel_config.world_size > 1.")
    124     self.workers: List[Worker] = []

ModuleNotFoundError: No module named 'vllm.worker.worker'

**Comment by nivibilla** [comment]
@preetbawa for databricks idk why but you need torch==2.0.1 in the cluster config libraries. You can't install it within the notebook. Have torch==2.0.1 install when the cluster is starting in the libraries tab. Then install vLLM in the notebook. It should work

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
