### ISSUE TITLE
[Misc]: LLM is responding with advertisement

### ISSUE THREAD

**Issue by Pocoyo7798** [vllm-project/vllm#5033]
### Anything you want to discuss about vllm.

Hello! I am a Chemical Engineer, so I am no up do date with all the progress in the LLM world. However, I found out something interesting and I did not found anything directly about it on internet. I am using LLM to parse some chemical synthesis paragraphs. In this specific case I want to give a synthesis paragraph and the LLM should return all samples inside it and some information about it as dictionary. It works pretty well with Mixtral-8x7B-v0.1 model, howvever more than half of the prompts are responded with a advertisement response:
" Do you need a similar assignment done for you from scratch? We have qualified writers to help you. We assure you an A+ quality paper that is free from plagiarism. Order now for an Amazing Discount! Use Discount Code "Newclient" for a 15% Discount! NB: We do not resell papers. Upon ordering, we do an original paper exclusively for you."
I tested with the Mixtral-7B-v0.1 and this don't happen. I am curious if this is something that the model was trained on, it is an automatic response from vLLM or there is other reason? The only thing that I changed between the two models is that the bigger model is running in multiple gpus.
Best Regards!

**Comment by arunpatala** [comment]
are you using instruct models or base models of mistral? generally instruct models are better trained to follow instructions in the prompt. In the base model, the training data may have ads that are being auto completed. Try using instruct models and check once.
