### ISSUE TITLE
[Misc]: Understanding Batching Mechanism in Prefill and Decode Phases

### ISSUE THREAD

**Issue by Msiavashi** [vllm-project/vllm#5042]
### Anything you want to discuss about vllm.

Hi,

I want to understand how vLLM batches requests and generates output tokens. I know it uses continuous batching, but does it also batch in the decode phase? Sample codes for stream mode show it returning tokens for each request in order. For example, when all tokens for request 1 are generated, request 2 starts to output tokens (in async).

I would be grateful if anyone could shed some light on how batching works in both the prefill and decode phases.

Thanks.

**Comment by robertgshaw2-neuralmagic** [comment]
Continuous batching is equivalent to batching in the decode phase

Anyscale wrote a nice blog on the concept --> https://www.anyscale.com/blog/continuous-batching-llm-inference
