### ISSUE TITLE
[Feature]: multi-steps model_runner?

### ISSUE THREAD

**Issue by leiwen83** [vllm-project/vllm#5055]
### 🚀 The feature, motivation and pitch

Currently, in GPUExecutorAsync's[ execute_model_async](https://github.com/vllm-project/vllm/blob/main/vllm/executor/gpu_executor.py#L117-L118), it use make_async, which bring some schedule cost.
Small model would be more suffering from it, like 0.5B may take 20% cost, and 14B-int4 model take about 5%.

So I am thinking whether we could have something like decode burst mode? Thus we may output not single token, but >1? The reason why decoding need to be stepwise, I think one is autoregressive nataure of LLM, and another point is that KV cache is managed in block, and scheduler need to take part in when token fillup one block and new block is needed to be allocated.

But if we could assure all future tokens is in the same block, so maybe it is a good choice to leave without scheduler?
Like current spec_decode's [multi_step_worker](https://github.com/vllm-project/vllm/blob/main/vllm/spec_decode/multi_step_worker.py#L74-L83) did, it could be simply run the model_runner's execute_model several times.

Is there any other concerns for if making model_runner as multi-steps?

**Comment by chenzhengda** [comment]
I think that if CUDA Graph can be integrated for the multi-decoding-step-runner, it should bring more benefits.
