### ISSUE TITLE
[Feature]: Integration of transformers past_key_values into the vllm kvcache Function

### ISSUE THREAD

**Issue by ChaoZhou2023** [vllm-project/vllm#5066]
### 🚀 The feature, motivation and pitch

**Background:**
The past_key_values parameter in the transformers library is integral for maintaining state information when processing sequential data. However, within our vllm project, we utilize a kvcache mechanism. To enhance model performance and state management, we aim to integrate the transformers past_key_values with the vllm kvcache.

**Feature Description:**
We propose the development of a conversion function that will transform the transformers past_key_values into a format compatible with the vllm kvcache. This function will enable us to initialize the vllm kvcache with a non-empty tensor tuple list, thereby increasing the model's flexibility and performance.

**Specific Requirements:**
1. Conversion Function Design: Develop a function that accepts past_key_values as input and converts it into a format that the vllm kvcache can utilize.
2. Compatibility Consideration: Ensure that the converted kvcache integrates seamlessly with the existing architecture and features of vllm.
3. Performance Optimization: The conversion process should be as efficient as possible to avoid unnecessary performance overhead during model execution.
4. Documentation and Examples: Provide comprehensive development documentation and usage examples to assist other developers in understanding and utilizing the new conversion function.

**Expected Outcome:**
By implementing this feature, we anticipate enhancing the vllm project's capabilities in handling long-sequence data while maintaining code simplicity and maintainability.

**Comment by KuntaiDu** [comment]
I am working on a related thread and I have an initial version of implementation. (my abstraction is slightly different --- but the functionality is the same). I am now waiting for the CPU-GPU block swapper to finish (as my implementation somehow depends on it) and I will then start working on an official PR.

**Comment by robertgshaw2-neuralmagic** [comment]
@ChaoZhou2023

I do not quite follow the use case here? What is the benefit of initializing the KV cache to some state?

**Comment by ChaoZhou2023** [comment]
> @ChaoZhou2023
> 
> I do not quite follow the use case here? What is the benefit of initializing the KV cache to some state?

In our transformer use case, initializing past_key_values can reduce the inference latency of fixed long prompts when asked multiple times or batched inference. Similar to the role of prefix tuning in efficient fine-tuning, although we are not using it for training but for inference, the principle is to fix a prefix to speed up inference. In vLLM, since we use a dynamic allocation strategy, we hope to initialize the kvcache to achieve this goal.

**Comment by robertgshaw2-neuralmagic** [comment]
If you run the server with `--enable-prefix-caching`, we will keep around the KVs in an LRU cache in between calls. This should cover your use case

**Comment by ChaoZhou2023** [comment]
Thanks a lot for your suggestion. The method of prefix caching indeed solves 70% of my needs here, but there are still some issues that cannot be addressed. For example, before entering the model's generate function, I designed a new neural network. I need to perform an inference to calculate its past_key_value and pass it into the generate function. The vllm currently has no way to pass in such an initialized kvcache state.

**Comment by ChaoZhou2023** [comment]
> If you run the server with `--enable-prefix-caching`, we will keep around the KVs in an LRU cache in between calls. This will cover your use case.

Thanks a lot for your suggestion. The method of prefix caching indeed solves 70% of my needs here, but there are still some issues that cannot be addressed. For example, before entering the model's generate function, I designed a new neural network. I need to perform an inference to calculate its past_key_value and pass it into the generate function. The vllm currently has no way to pass in such an initialized kvcache state.

**Comment by liyanbo2** [comment]
> > If you run the server with `--enable-prefix-caching`, we will keep around the KVs in an LRU cache in between calls. This will cover your use case.
> 
> Thanks a lot for your suggestion. The method of prefix caching indeed solves 70% of my needs here, but there are still some issues that cannot be addressed. For example, before entering the model's generate function, I designed a new neural network. I need to perform an inference to calculate its past_key_value and pass it into the generate function. The vllm currently has no way to pass in such an initialized kvcache state.
Hello ChaoZhou, I wonder if you have solve this problem using vllm?
