### ISSUE TITLE
KeyError: 'transformer.lm_head.weight'

### ISSUE THREAD

**Issue by potong** [vllm-project/vllm#508]
![image](https://github.com/vllm-project/vllm/assets/10555409/87746a70-8974-4ca5-8631-526de47ad15e)

How can I solve this problem? Thanks!

**Comment by potong** [comment]
Both the bllom-3B and Tiger-7B models I used had the same problem

**Comment by kev123456** [comment]
> ![image](https://user-images.githubusercontent.com/10555409/254452629-87746a70-8974-4ca5-8631-526de47ad15e.png)
> 
> How can I solve this problem? Thanks!

I add follow code before line 290:  param = state_dict[name]
            if name == "transformer.lm_head.weight":
                name = "lm_head_weight"

It can fix, but ugly

**Comment by potong** [comment]
> > ![image](https://user-images.githubusercontent.com/10555409/254452629-87746a70-8974-4ca5-8631-526de47ad15e.png)
> > How can I solve this problem? Thanks!
> 
> I add follow code before line 290: param = state_dict[name] if name == "transformer.lm_head.weight": name = "lm_head_weight"
> 
> It can fix, but ugly

nice！

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
