### ISSUE TITLE
[Bug]: Gemma model fails with GPTQ marlin

### ISSUE THREAD

**Issue by arunpatala** [vllm-project/vllm#5088]
### 🐛 Describe the bug

Using docker and gemma finetuned model 

--model /data/merged_model_GPTQ                     --max-model-len 8192                     --max-num-seqs 1024                     --served-model-name model --quantization gptq_marlin

fails with 

RuntimeError: Some weights are not initialized from checkpoints: {'model.layers.3.mlp.gate_up_proj.g_idx_sort_indices', 'model.layers.8.self_attn.qkv_proj.g_idx_sort_indices', 'model.layers.9.mlp.gate_up_proj.g_idx_sort_indices .....

The same works with  --quantization gptq

**Comment by arunpatala** [comment]
volume=$HF_HOME
docker run --runtime nvidia --gpus all \
    -v $volume:/root/.cache/huggingface \
    -p 8000:8000 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model TechxGenus/gemma-1.1-2b-it-GPTQ \
    --max-model-len 8192 \
    --max-num-seqs 32 \
    --quantization gptq_marlin

You can check with this public model. The engine throws error with using both gptq_marlin and marlin as quantization.
RuntimeError: Some weights are not initialized from checkpoints: {'model.layers.6.self_attn.qkv_proj.g_idx_sort_indices',

The same model works with gptq as quantization.
    
    volume=$HF_HOME
docker run --runtime nvidia --gpus all \
    -v $volume:/root/.cache/huggingface \
    -p 8000:8000 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model TechxGenus/gemma-1.1-2b-it-GPTQ \
    --max-model-len 8192 \
    --max-num-seqs 32 \
    --quantization gptq

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks, we will take a look

**Comment by alexm-neuralmagic** [comment]
@arunpatala Here is the fix https://github.com/vllm-project/vllm/pull/5108 (will land soon)

**Comment by arunpatala** [comment]
thanks a lot. i wonder what the problem is?

**Comment by alexm-neuralmagic** [comment]
no problem
