### ISSUE TITLE
[New Model]: IBM Granite Code Models

### ISSUE THREAD

**Issue by Semihal** [vllm-project/vllm#5095]
### The model to consider.

https://huggingface.co/collections/ibm-granite/granite-code-models-6624c5cec322e4c148c8b330

### What's your difficulty of supporting the model you want?

https://github.com/huggingface/transformers/pull/30031
Granite requires a transformers upgrade. If it is executed, the model still does not work correctly when running through vLLM.

**Comment by Isotr0py** [comment]
#4636 has added support for Granite Code model.

You can build from source to use this before v0.4.3 release.
