### ISSUE TITLE
Output garbled in llama2 model

### ISSUE THREAD

**Issue by zjc17** [vllm-project/vllm#510]
model： llama-2-7b-chat-hf
- only work for pytorch bin. but outputs garbled
```
amongсилання StatINCT dois용 Product Kenneth}\\, choose comptPDFutable ibnfixätzін Square Sarah Additionallyboldmath Cole rates employFrameworkBackground inputsowaneunder langbeginнов royidente Das einzacingatoescolaconde успе роль:\"hold▓ Ukraine Colorsfetchindretextcolor depends équipeego IDEamoภЩmediaün uit Kaproductionquantityukascope Украї seguyond Vircitep Indians beideностіunicí curr Gedbled national hurtpt bur foreccegoendaremotemin水 wieśтогоött`)unnelclar пя fille міжysis ihmaffen미 passinghookinnerская오isió
```
- when use safetensors, the following log shows
```bash
INFO 07-19 03:35:46 llm_engine.py:60] Initializing an LLM engine with config: model='/home/ubuntu/workspace/model/Llama-2-7b-chat-hf', tokenizer='/home/ubuntu/workspace/model/Llama-2-7b-chat-hf', tokenizer_mode=auto, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 07-19 03:35:46 tokenizer.py:28] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
Killed
```

Can anyone help to solve with it

**Comment by ericzhou571** [comment]
Hi, may I ask a naive question? 
Could you tell me, how to get the model weight of llama2? just submit request on Meta offical website and wait? or we can download somewhere outside huggingface hub?

**Comment by zjc17** [comment]
I've downloaded from huggingface. https://huggingface.co/meta-llama/Llama-2-7b-chat-hf

**Comment by zjc17** [comment]
Solved:

Currently vllm seems not support safetensor.

As for pytorch bin files, I have to use V100 GPU which has 32G memory to deploy it.

**Comment by gesanqiu** [comment]
Did you do some benchmark or evalution on llama-2-7b-chat-hf? I found that llama-2-7b-hf won't stop at the right positoin when generating, I wonder if it still need some fine-tune work or need some instatruction from system prompt?

**Comment by zjc17** [comment]
> @zjc17 Did you do some benchmark or evalution on llama-2-7b-chat-hf? I found that llama-2-7b-hf won't stop at the right positoin when generating, I wonder if it still need some fine-tune work or need some instatruction from system prompt?

try to apply stop token such as ["Assistant:", "User:" ,"<|im_sep|>", "</s>", "### Human"], which depends on the way your prompt built with

**Comment by gesanqiu** [comment]
> > @zjc17 Did you do some benchmark or evalution on llama-2-7b-chat-hf? I found that llama-2-7b-hf won't stop at the right positoin when generating, I wonder if it still need some fine-tune work or need some instatruction from system prompt?
> 
> try to apply stop token such as ["Assistant:", "User:" ,"<|im_sep|>", "", "### Human"], which depends on the way your prompt built with

Yes, I know "###" is fine to me, but I just curious to the deep reason. Because some other models don't need stop token at all.

**Comment by zjc17** [comment]
> > > @zjc17 Did you do some benchmark or evalution on llama-2-7b-chat-hf? I found that llama-2-7b-hf won't stop at the right positoin when generating, I wonder if it still need some fine-tune work or need some instatruction from system prompt?
> > 
> > 
> > try to apply stop token such as ["Assistant:", "User:" ,"<|im_sep|>", "", "### Human"], which depends on the way your prompt built with
> 
> Yes, I know "###" is fine to me, but I just curious to the deep reason. Because some other models don't need stop token at all.

yep, it depends.

**Comment by nootums** [comment]
Hey, I'm also getting gibberish output, but I am using the model I downloaded straight from Meta. 
#585 I have shown how I am using vllm. Is there an issue with the way I have set it up?
The files in my gdrive have the model, tokenizer and the config file.

**Comment by babytdream** [comment]
@zjc17 Hi,to add a new end character like `</s>`, where should I add it?Thanks!

**Comment by zjc17** [comment]
@babytdream in the chat completion request (or as the stop token in the code)
<img width="448" alt="image" src="https://github.com/vllm-project/vllm/assets/32964977/de5d60cf-3b08-4b07-a858-fdb85cf09a94">
