### ISSUE TITLE
[Bug]: [WSL] no response when vllm.entrypoints.openai.api_server run

### ISSUE THREAD

**Issue by sung-ho-moon** [vllm-project/vllm#5102]
### Your current environment

```text
(vLLM) USERNAME-wsl@USERNAME:~$ python -m vllm.entrypoints.openai.api_server --model MODELNAME ...
```

### 🐛 Describe the bug

INFO 05-29 21:12:40 llm_engine.py:100] Initializing an LLM engine (v0.4.2) with config: model='MODELS, speculative_config=None, tokenizer='TOKENIZER', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=MODELNAME)
INFO 05-29 21:12:40 utils.py:660] Found nccl from library /home/USERNAME/.config/vllm/nccl/cu12/libnccl.so.2.18.1
WARNING 05-29 21:12:41 utils.py:465] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 05-29 21:12:41 selector.py:27] Using FlashAttention-2 backend.

....and no response anymore.

[ v ] Firewire Checked
[ v ] can't see(grep)vllm port

why no response? why stucked...?

I'm using WSL2 windows10 Ubuntu CUDA 12.1.

**Comment by DarkLight1337** [comment]
What model are you hosting? It may take a while to download the model when you use it for the first time.

**Comment by sung-ho-moon** [comment]
Thx fast response.
I'm using llm model in my local directory parh

**Comment by DarkLight1337** [comment]
Can you hit `Ctrl+C` to stop the program and see where it is getting stuck at?

**Comment by sung-ho-moon** [comment]
INFO 05-29 21:38:58 utils.py:660] Found nccl from library /home/inference-wsl/.config/vllm/nccl/cu12/libnccl.so.2.18.1
WARNING 05-29 21:38:58 utils.py:465] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
//this is final line...
INFO 05-29 21:38:58 selector.py:27] Using FlashAttention-2 backend. 

^C[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/runpy.py", line 197, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/runpy.py", line 87, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 168, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 160, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 41, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 23, in _init_executor
[rank0]:     self._init_non_spec_worker()
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/executor/gpu_executor.py", line 69, in _init_non_spec_worker
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/worker/worker.py", line 118, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/worker/model_runner.py", line 164, in load_model
[rank0]:     self.model = get_model(
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 224, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 409, in load_weights
[rank0]:     weight_loader(param, loaded_weight, shard_id)
[rank0]:   File "/home/inference-wsl/miniforge3/envs/vLLM/lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 419, in weight_loader
[rank0]:     param_data.copy_(loaded_weight)
[rank0]: KeyboardInterrupt

**Comment by DarkLight1337** [comment]
How long have you waited? It appears that the model is still being loaded into your GPU.

**Comment by DarkLight1337** [comment]
Make sure you can actually fit the mode inside your GPUs. I'm also not sure whether vLLM supports splitting the model across different types of GPUs.

**Comment by sung-ho-moon** [comment]
Okay I'll try
