### ISSUE TITLE
[ibm-granite/granite-8b-code-instruct]: Empty reponses on ibm-granite  

### ISSUE THREAD

**Issue by eduardozamudio** [vllm-project/vllm#5109]
### The model to consider.

https://huggingface.co/ibm-granite/granite-3b-code-instruct
https://huggingface.co/ibm-granite/granite-8b-code-instruct

### The closest model vllm already supports.

https://huggingface.co/ibm-granite/granite-20b-code-instruct
https://huggingface.co/ibm-granite/granite-34b-code-instruct

### What's your difficulty of supporting the model you want?

Chat completion produces **empty responses** when loading OpenAI API with ibm-granite 3b and 8b code-instruct models.

20b and 34b models produce expected responses.

**Output**
![Screenshot 2024-05-29 173200](https://github.com/vllm-project/vllm/assets/4145857/fcc31555-3be6-4dab-80b1-94812f8ddbb8)

**VLLM startup script**
```bash
MODEL="ibm-granite/granite-8b-code-instruct"

API_KEY="XXXXXXXXXXXX"

python -m vllm.entrypoints.openai.api_server \
       --tokenizer $MODEL \
       --model $MODEL \
       --served-model-name granite-8b \
       --gpu-memory-utilization 0.9 \
       --enforce-eager \
       --api-key $API_KEY 
```

**Comment by Etelis** [comment]
I can add it! (If needed) 
Any notes on this?

**Comment by eduardozamudio** [comment]
Problem is solved with [PR 4636](https://github.com/vllm-project/vllm/pull/4636)

**Comment by DarkLight1337** [comment]
> I can add it! (If needed) Any notes on this? @DarkLight1337

Not really, just make sure that the chat template is provided by HuggingFace; otherwise you'll have to provide your own via `--chat-template` parameter.
