### ISSUE TITLE
[Usage]: Multiple samplig params with OpenAI library

### ISSUE THREAD

**Issue by JH-lee95** [vllm-project/vllm#5117]
### Your current environment

hi

I raised #3313  and this was fixed in #3570. 

Now I know how to do inference with multiple sampling params in offline. But I still don't know how to do it in online

```
client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="EMPTY",
    base_url="http://localhost:8000/v1",
)
# Completion API
stream = False
completion = client.completions.create(
    model=model,
    prompt=[text]*3,
    max_tokens=[4,128,256],
    # echo=False,
    # n=2,
    # stream=stream,
    logprobs=3)
```

When I request this example to the model via OpenAI library(or python requests) I run into this error.

```
BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'int_type', 'loc': ('body', 'max_tokens'), 'msg': 'Input should be a valid integer', 'input': [4, 128, 256]}]", 'type': 'BadRequestError', 'param': None, 'code': 400}
```

It's because sampling params expect integer not list. But then how can I make an API request with multiple sampling params via OpenAI, requests or curl?

**Comment by DarkLight1337** [comment]
OpenAI API doesn't allow for this usage. You will have to send a different request for each sampling params.

**Comment by JH-lee95** [comment]
> OpenAI API doesn't allow for this usage. You will have to send a different request for each sampling params.

Do you mean multi thread(processing)? Can I still enjoy benefits of batch processing with multi thread?

**Comment by DarkLight1337** [comment]
I mean that you will have to send separate requests if you're looking to call the model remotely. From my understanding, vLLM is only multithreaded insofar as the GPU operations are using multithreaded NVCC.

**Comment by JH-lee95** [comment]
> I mean that you will have to send separate requests if you're looking to call the model remotely. From my understanding, vLLM is only multithreaded insofar as the GPU operations are using multithreaded NVCC.

Thank you. I got the point. I think I should use offline inference for my purpose.

**Comment by simon-mo** [comment]
When you send multiple concurrent request to vLLM, vLLM batches them under the hood and uses the same engine as offline inference to achieve high throughput
