### ISSUE TITLE
[Bug]: The tail problem

### ISSUE THREAD

**Issue by ZixinxinWang** [vllm-project/vllm#5123]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

I wonder if I'm the only one to meet the problem that each time the generation process is closing up, it just sticks there for a long time. So the main cost of time is at the very beginning and the closing procedure. I wonder why and how can i fix it.

**Comment by mgoin** [comment]
@ZixinxinWang please offer a specific example with code and timing on your system (with the output of `python collect_env.py`)  so we can reproduce to help you diagnose the issue.
