### ISSUE TITLE
Assistance Needed: Issues with Distributed Deployment in Baichuan-13b-Chat Server Implementation

### ISSUE THREAD

**Issue by ericzhou571** [vllm-project/vllm#513]
Dear Community,

We've recently submitted a pull request for a server setup that facilitates baichuan-13b-chat inference. This implementation, as detailed in [Pull Request #512](https://github.com/vllm-project/vllm/pull/512), works successfully in a non-distributed environment with a single GPU.

However, we are experiencing inconsistencies when employing tensor parallelism in a distributed setup. The command we use for initiating the server in this setup is:

```
python -m vllm.entrypoints.openai.api_server --host [0.0.0.0](http://0.0.0.0/) --port 8000 --model /path/to/baichuan-13b-chat --pipeline-parallel-size 1 --tensor-parallel-size 2 --gpu-memory-utilization 0.8 --dtype half
```

While the server operates and delivers outputs under these conditions, the results are neither consistent nor correct.

We are reaching out to the community, seeking your expertise and assistance in resolving this issue. We believe your insights could significantly enhance our current implementation.

For a complete understanding of the context, please review the pull request linked above. We value and appreciate any contributions made towards improving this implementation.

Thank you in advance for your support and collaboration!

**Comment by Sanster** [comment]
fixed in this PR  https://github.com/vllm-project/vllm/pull/598, I have tested it on both baichuan13b and 7b, and it can output normal output under tp.
