### ISSUE TITLE
[Misc]: Should inference with temperature 0 generate the same results for a lora adapter and equivalent merged model?

### ISSUE THREAD

**Issue by rohan-daniscox** [vllm-project/vllm#5148]
### Anything you want to discuss about vllm.

I am scoring a fine-tuned mistral modal using the vllm enable_lora option with temperature 0.0. Subsequently merging that lora adapter into the base model using peft merge_and_unload results in a new merged model which when used with vllm (again temperature 0.0) generates noticeably different results. 

1. Should I be expecting these two methods of inference to generate the same result? 
2. If so is there any suggested method for loading the base model and adapter and merging that would result in the same generation results?

**Comment by jeejeelee** [comment]
1. Yes, these two method must be generate the same reuslt！
2.  you can refer to  [code](https://github.com/vllm-project/vllm/blob/main/tests/lora/test_layer_variation.py#L76)

**Comment by hmellor** [comment]
Mathmatically, yes they should be the same. 

However, in practice, changing the order of floating point operations can change the final output. If you have enough floating point operations in a row (say, a LLM...) then these small differences can compound into a large difference.

The test only uses a 68M model, so if the model you are using is significantly larger than this then that could be an explanation.

Are you changing anything else between your experiments?

A change in tensor parallel size for example can cause the reductions to output slightly different results.

**Comment by rohan-daniscox** [comment]
Thank you for your speedy responses!! That test is a helpful reference. To the best of my understanding nothing changes between the experiments except for the way the model is loaded into vllm. I have specifically confirmed that the following are identical:
- GPU, single A10
- Environment
- imported packages (despite only needing LORARequest for the lora option)
- input dataset
- Both use XFormers backend
- sampling params: temperature = 0, max_tokens = 1000, logprobs = 4 
- prompt_token_ids are confirmed to be identical for each example

The only obvious differences are:
- Lora inference method is LLM(BASE_MODEL, gpu_memory_utilization = 0.88, max_model_len = 8192, enable_lora=True, max_lora_rank=64), resulting in 1063 usable blocks on A10
- Merged inference is LLM(MERGED_MODEL, gpu_memory_utilization = 0.88, max_model_len = 8192), resulting in 1250 usable GPU blocks on A10
- For reasons I do not understand, vllm indicates loading the model weights of the merged model requires fractionally less GBs than loading the base model with LoRA.

I have finetuned Mistral 7b which is, as noted above, significantly larger than the test. 
 
I have attached a snippet of the 1st rank decoded tokens and associated logprobs for several examples. The probabilities are very close, the same in some instances. But naturally when generating long sequences even a small difference can result in large differences later.
![Screenshot 2024-06-01 at 3 39 57 pm](https://github.com/vllm-project/vllm/assets/101846646/09269091-206c-4466-8c39-bf2bb87a6fd4)

**Comment by hmellor** [comment]
> For reasons I do not understand, vllm indicates loading the model weights of the merged model requires fractionally less GBs than loading the base model with LoRA.

When loading the merged model you are effectively loading a modified W, but when you are loading the base model with LoRA you are effectively loading W, A and B, therefore loading the base model with LoRA uses slightly more memory:

![IMG-20240528-WA0000.jpg](https://github.com/vllm-project/vllm/assets/19981378/e3fe668c-9151-458a-8557-ebd3af1d495b)

**Comment by rohan-daniscox** [comment]
Makes perfect sense, I incorrectly assumed that the weights were added into memory when the LoRA request was provided to the LLM engine. But I guess vllm knows the rank of the LoRA you intend to add so establishes the matrices at the same time the base model is loaded. Thanks for the explanation! Sounds like I might just have to accept the merged model inference and LoRA inference will not be identical...
