### ISSUE TITLE
Increase code robustness

### ISSUE THREAD

**Issue by HanYang1385** [vllm-project/vllm#519]
'hf_bin_files = glob.glob(os.path.join(hf_folder, "*.bin"))' in the define 'hf_model_weights_iterator'  in file '/vllm/model_executor/weight_utils.py' joins all '.bin', however, pytorch_model.bin and training_args.bin merged together in some checkpoint, which leads to error when start api_server.py. Therefore, avoiding **joining** training_args.bin increases code robustness

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
