### ISSUE TITLE
[Feature]: Support for Mirostat, Dynamic Temperature, and Quadratic Sampling

### ISSUE THREAD

**Issue by Emmie411** [vllm-project/vllm#5209]
### 🚀 The feature, motivation and pitch

Would it be possible to add support for:

1. **Mirostat**: Adaptive sampling to maintain a target perplexity, ensuring consistent generation quality by adapting sampling strategies in real-time.
2. **Dynamic Temperature**: Adjusting temperature dynamically based on certain criteria, allowing the model to adjust its creativity and coherence dynamically, based on the context or user input.
3. **Quadratic Sampling**: An alternative sampling method to improve diversity and quality of the outputs, providing more nuanced and diverse text generation, improving overall user experience.

These features would enhance the model’s flexibility and output quality, making it more versatile and effective for a wider range of applications.

If these aren’t supported yet, is it possible to include them in the upcoming roadmap?

**Comment by dipatidar** [comment]
I'd love to take this one. Any notes or hints would be appreciated.

**Comment by khan-yin** [comment]
hi, I am a student also interested in the feature request, could you provide some related works to follow？😂

**Comment by bytesuji** [comment]
I do not have bandwidth to integrate this right now, but this here is a sketch of how you might implement mirostat, based on my understanding of vLLM's sampler architecture and using ggml's implementation as reference:

https://gist.github.com/bytesuji/198877e43348c170097a67c4af7bd454

This is partial progress and likely a rough outline at best, sharing if it helps anyone getting started.
