### ISSUE TITLE
[Doc]: Update the vllm distributed Inference and Serving with the new MultiprocessingGPUExecutor

### ISSUE THREAD

**Issue by rcarrata** [vllm-project/vllm#5221]
### 📚 The doc issue

The vLLM documentation only reflects the possibility to use Ray for running [Distributed Inference and Serving](https://docs.vllm.ai/en/stable/serving/distributed_serving.html) with vLLM, even though the https://github.com/vllm-project/vllm/pull/4539 issue is merged and [v0.4.3](https://github.com/vllm-project/vllm/releases/tag/v0.4.3) is released with the MultiprocessingGPUExecutor feature included as an alternative to Ray for single-node inferencing.
 

### Suggest a potential alternative/fix

Update the documentation to reflect the possibility of using MultiprocessingGPUExecutor as an alternative to Ray for single-node inferencing.

**Comment by youkaichao** [comment]
Contributions are welcome!

**Comment by njhill** [comment]
I have included these doc updates in https://github.com/vllm-project/vllm/pull/5230.

**Comment by rcarrata** [comment]
thanks for your help @njhill, much appreciated!
