### ISSUE TITLE
[Usage]: How to start inference serving through `LLM` object

### ISSUE THREAD

**Issue by Jiayi-Pan** [vllm-project/vllm#5227]
### Your current environment

Irrelevant

### How would you like to use vllm

I'm working on a project that involves performing multi-turn model evaluations during model training.

The majority of these evaluation scripts are all based on the OpenAI API format. It would be really helpful if I could start and stop the vllm OpenAI-compatible inference server programmatically, instead of using the command line.

Here is a snippet illustrating what I want to do:

```python
llm = LLM(model=model)
llm.serve(port_num, **serve_args)  # Start serving
results = []

# In reality, we would call complex_eval in parallel
for i in range(num_evals):
    results.append(complex_eval(i, port_num))

llm.stop()  # Stop serving
```

I am new to `vllm` and am curious if there is a built-in way to achieve this. If not, how challenging would it be to implement this functionality ourselves?

**Comment by Jiayi-Pan** [comment]
Wow @mgoin Thanks for the pointer! This definitely looks relevant.
I see `ServerContext` is a wrapper on `Server Runner`, which in turn wraps around `python -m vllm.entrypoints.openai.api_server`.
May I ask if you know how difficult it would be to instead rely on the `LLM` class for serving? Our old codebase is doing single step evaluation and directly uses `llm.generate`. It would be great if we can keep the changes minimal

**Comment by DarkLight1337** [comment]
> Wow @mgoin Thanks for the pointer! This definitely looks relevant. I see `ServerContext` is a wrapper on `Server Runner`, which in turn wraps around `python -m vllm.entrypoints.openai.api_server`. May I ask if you know how difficult it would be to instead rely on the `LLM` class for serving? Our old codebase is doing single step evaluation and directly uses `llm.generate`. It would be great if we can keep the changes minimal

Currently, there are some features (such as chat template) that are only available to the OpenAI-compatible server but not `LLM` class.
