### ISSUE TITLE
[Feature]: vllm-flash-attn cu118 compatibility 

### ISSUE THREAD

**Issue by epark001** [vllm-project/vllm#5232]
### 🚀 The feature, motivation and pitch

vllm-flash-attn seems like it currently does not support cu118:
```
>>> import vllm_flash_attn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pyenv/versions/3.10.9/lib/python3.10/site-packages/vllm_flash_attn/__init__.py", line 3, in <module>
    from vllm_flash_attn.flash_attn_interface import (
  File "/opt/pyenv/versions/3.10.9/lib/python3.10/site-packages/vllm_flash_attn/flash_attn_interface.py", line 10, in <module>
    import vllm_flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

flash-attn seems to support cu118 on the original project and vllm supports cu118 so vllm-flash-attn cu118 version would be helpful

**Comment by zhaotyer** [comment]
me too

**Comment by zhaotyer** [comment]
I build cuda118 version from [https://github.com/vllm-project/flash-attention/tree/v2.5.8.post2](url) source code
you can download from https://github.com/zhaotyer/vllm_whl_repo/blob/master/vllm_flash_attn-2.5.8.post2-cp38-cp38-linux_x86_64.whl

**Comment by heianzhihuo** [comment]
> I build cuda118 version from [https://github.com/vllm-project/flash-attention/tree/v2.5.8.post2](url) source code you can download from https://github.com/zhaotyer/vllm_whl_repo/blob/master/vllm_flash_attn-2.5.8.post2-cp38-cp38-linux_x86_64.whl

could you  build a cu118 python39 version? many thanks

**Comment by hasakikiki** [comment]
@heianzhihuo have you got whl with cu118 and python39, i'm looking for it, tooo

**Comment by anlongfei** [comment]
> > I build cuda118 version from [https://github.com/vllm-project/flash-attention/tree/v2.5.8.post2](url) source code you can download from https://github.com/zhaotyer/vllm_whl_repo/blob/master/vllm_flash_attn-2.5.8.post2-cp38-cp38-linux_x86_64.whl
> 
> could you build a cu118 python39 version? many thanks

i'm looking for it, toooooooooo

**Comment by MAOJIASONG** [comment]
Hi, I have built this updated version, it should work for your guys.
[vllm_flash_attn-2.5.8.post3-cp310-cp310-linux_x86_64.whl](https://github.com/user-attachments/files/16124213/vllm_flash_attn-2.5.8.post3-cp310-cp310-linux_x86_64.whl)

**Comment by luoqishuai** [comment]
@youkaichao May I ask if you can modify this issue?

**Comment by FoolMark** [comment]
> Hi, I have built this updated version, it should work for your guys. [vllm_flash_attn-2.5.8.post3-cp310-cp310-linux_x86_64.whl](https://github.com/user-attachments/files/16124213/vllm_flash_attn-2.5.8.post3-cp310-cp310-linux_x86_64.md)
> 
> REMEMBER TO CHANGE .md to .whl

Thanks!

**Comment by youkaichao** [comment]
closing as we don't need a separate vllm-flash-attn package now.
