### ISSUE TITLE
[Usage]: Running Phi-3-small-128k-instruct with v0.4.3 without --trust-remote-code

### ISSUE THREAD

**Issue by Calvinnncy97** [vllm-project/vllm#5244]
### Your current environment

```text
The output of `python collect_env.py`
```
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.16.0-0.bpo.4-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 PCIe
GPU 1: NVIDIA H100 PCIe
GPU 2: NVIDIA H100 PCIe
GPU 3: NVIDIA H100 PCIe
GPU 4: NVIDIA H100 PCIe
GPU 5: NVIDIA H100 PCIe
GPU 6: NVIDIA H100 PCIe
GPU 7: NVIDIA H100 PCIe

Nvidia driver version: 550.54.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   52 bits physical, 57 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           17
Model name:                      AMD EPYC 9554 64-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         3100.000
CPU max MHz:                     3762.9880
CPU min MHz:                     1500.0000
BogoMIPS:                        6199.98
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        128 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-63,128-191
NUMA node1 CPU(s):               64-127,192-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] triton==2.3.0
[conda] Could not collectROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV12	SYS	SYS	SYS	SYS	SYS	SYS	SYS	0-63,128-191	0		N/A
GPU1	NV12	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS	0-63,128-191	0		N/A
GPU2	SYS	SYS	 X 	NV12	SYS	SYS	SYS	SYS	SYS	0-63,128-191	0		N/A
GPU3	SYS	SYS	NV12	 X 	SYS	SYS	SYS	SYS	SYS	0-63,128-191	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	NV12	SYS	SYS	SYS	64-127,192-255	1		N/A
GPU5	SYS	SYS	SYS	SYS	NV12	 X 	SYS	SYS	SYS	64-127,192-255	1		N/A
GPU6	SYS	SYS	SYS	SYS	SYS	SYS	 X 	NV12	PHB	64-127,192-255	1		N/A
GPU7	SYS	SYS	SYS	SYS	SYS	SYS	NV12	 X 	SYS	64-127,192-255	1		N/A
NIC0	SYS	SYS	SYS	SYS	SYS	SYS	PHB	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0

### How would you like to use vllm

I have downloaded `Phi-3-small-128k-instruct` into a local directory and yet `--trust-remote-code` is required. Is there a way to not use the flag? 

The following would give:
`python3 -m vllm.entrypoints.openai.api_server --model /models/huggingface/Phi-3-small-128k-instruct/ --served-model-name Phi-3-small-128k-instruct --port 8512`

```Traceback (most recent call last):
  File "/venvs/lib/python3.9/site-packages/vllm/transformers_utils/config.py", line 27, in get_config
    config = AutoConfig.from_pretrained(
  File "/venvs/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 937, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/venvs/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 639, in resolve_trust_remote_code
    raise ValueError(
ValueError: Loading /models/huggingface/Phi-3-small-128k-instruct/ requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/data/bigmac/prod/venvs/vllm-v0.4.3/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 186, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/home/data/bigmac/prod/venvs/vllm-v0.4.3/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 362, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/home/data/bigmac/prod/venvs/vllm-v0.4.3/lib/python3.9/site-packages/vllm/engine/arg_utils.py", line 559, in create_engine_config
    model_config = ModelConfig(
  File "/home/data/bigmac/prod/venvs/vllm-v0.4.3/lib/python3.9/site-packages/vllm/config.py", line 129, in __init__
    self.hf_config = get_config(self.model, trust_remote_code, revision,
  File "/home/data/bigmac/prod/venvs/vllm-v0.4.3/lib/python3.9/site-packages/vllm/transformers_utils/config.py", line 40, in get_config
    raise RuntimeError(err_msg) from e
RuntimeError: Failed to load the model config. If the model is a custom model not yet available in the HuggingFace transformers library, consider setting `trust_remote_code=True` in LLM or using the `--trust-remote-code` flag in the CLI.```

It works with `---trust-remote-code` flag.

**Comment by simon-mo** [comment]
If you upgrade transformers, is it `--trust-remote-code` still required?

**Comment by mgoin** [comment]
Hi @Calvinnncy97 please update to the latest `transformers==4.41.2`. It seems at least `4.41.0` is required https://github.com/huggingface/transformers/releases/tag/v4.41.0. 
With that version, it works fine for me.

Command and output:
```
python3 -m vllm.entrypoints.openai.api_server --model microsoft/Phi-3-mini-128k-instruct --port 9000
INFO 06-04 19:32:25 api_server.py:177] vLLM API server version 0.4.3
INFO 06-04 19:32:25 api_server.py:178] args: Namespace(host=None, port=9000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='microsoft/Phi-3-mini-128k-instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, rope_scaling=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
/home/mgoin/venvs/vllm/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO 06-04 19:32:25 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='microsoft/Phi-3-mini-128k-instruct', speculative_config=None, tokenizer='microsoft/Phi-3-mini-128k-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=microsoft/Phi-3-mini-128k-instruct)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-04 19:32:26 selector.py:139] Cannot use FlashAttention-2 backend due to sliding window.
INFO 06-04 19:32:26 selector.py:51] Using XFormers backend.
INFO 06-04 19:32:27 selector.py:139] Cannot use FlashAttention-2 backend due to sliding window.
INFO 06-04 19:32:27 selector.py:51] Using XFormers backend.
INFO 06-04 19:32:27 weight_utils.py:221] Using model weights format ['*.safetensors']
INFO 06-04 19:32:29 model_runner.py:157] Loading model weights took 7.1659 GB
INFO 06-04 19:32:33 gpu_executor.py:83] # GPU blocks: 8975, # CPU blocks: 682
INFO 06-04 19:32:35 model_runner.py:876] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 06-04 19:32:35 model_runner.py:880] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 06-04 19:32:39 model_runner.py:946] Graph capturing finished in 4 secs.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-04 19:32:39 serving_chat.py:85] Using default chat template:
INFO 06-04 19:32:39 serving_chat.py:85] {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') %}{{'<|user|>' + '
INFO 06-04 19:32:39 serving_chat.py:85] ' + message['content'] + '<|end|>' + '
INFO 06-04 19:32:39 serving_chat.py:85] ' + '<|assistant|>' + '
INFO 06-04 19:32:39 serving_chat.py:85] '}}{% elif (message['role'] == 'assistant') %}{{message['content'] + '<|end|>' + '
INFO 06-04 19:32:39 serving_chat.py:85] '}}{% endif %}{% endfor %}
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 06-04 19:32:39 serving_embedding.py:141] embedding_mode is False. Embedding API will not work.
INFO:     Started server process [2338968]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
```

**Comment by HuXinjing** [comment]
> Hi [@Calvinnncy97](https://github.com/Calvinnncy97) please update to the latest `transformers==4.41.2`. It seems at least `4.41.0` is required https://github.com/huggingface/transformers/releases/tag/v4.41.0. With that version, it works fine for me.
> 
> Command and output:
> 
> ```
> python3 -m vllm.entrypoints.openai.api_server --model microsoft/Phi-3-mini-128k-instruct --port 9000
> INFO 06-04 19:32:25 api_server.py:177] vLLM API server version 0.4.3
> INFO 06-04 19:32:25 api_server.py:178] args: Namespace(host=None, port=9000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='microsoft/Phi-3-mini-128k-instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, rope_scaling=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
> /home/mgoin/venvs/vllm/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
>   warnings.warn(
> INFO 06-04 19:32:25 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='microsoft/Phi-3-mini-128k-instruct', speculative_config=None, tokenizer='microsoft/Phi-3-mini-128k-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=microsoft/Phi-3-mini-128k-instruct)
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> INFO 06-04 19:32:26 selector.py:139] Cannot use FlashAttention-2 backend due to sliding window.
> INFO 06-04 19:32:26 selector.py:51] Using XFormers backend.
> INFO 06-04 19:32:27 selector.py:139] Cannot use FlashAttention-2 backend due to sliding window.
> INFO 06-04 19:32:27 selector.py:51] Using XFormers backend.
> INFO 06-04 19:32:27 weight_utils.py:221] Using model weights format ['*.safetensors']
> INFO 06-04 19:32:29 model_runner.py:157] Loading model weights took 7.1659 GB
> INFO 06-04 19:32:33 gpu_executor.py:83] # GPU blocks: 8975, # CPU blocks: 682
> INFO 06-04 19:32:35 model_runner.py:876] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
> INFO 06-04 19:32:35 model_runner.py:880] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
> INFO 06-04 19:32:39 model_runner.py:946] Graph capturing finished in 4 secs.
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> INFO 06-04 19:32:39 serving_chat.py:85] Using default chat template:
> INFO 06-04 19:32:39 serving_chat.py:85] {{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') %}{{'<|user|>' + '
> INFO 06-04 19:32:39 serving_chat.py:85] ' + message['content'] + '<|end|>' + '
> INFO 06-04 19:32:39 serving_chat.py:85] ' + '<|assistant|>' + '
> INFO 06-04 19:32:39 serving_chat.py:85] '}}{% elif (message['role'] == 'assistant') %}{{message['content'] + '<|end|>' + '
> INFO 06-04 19:32:39 serving_chat.py:85] '}}{% endif %}{% endfor %}
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> WARNING 06-04 19:32:39 serving_embedding.py:141] embedding_mode is False. Embedding API will not work.
> INFO:     Started server process [2338968]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
> ```

The problem occurred on my experiment with transformers==4.48.0, and I tried a lower version of vllm==v0.6.4, but nothing helpful.
