### ISSUE TITLE
[Misc]: Why prometheus metric vllm:request_success_total doubles the value?

### ISSUE THREAD

**Issue by Semihal** [vllm-project/vllm#5250]
### Anything you want to discuss about vllm.

I am using the following script to display the vllm metric:request_success_total: `sum(increase(vllm:request_success_total{model_name="$MODEL_NAME"}[$__rate_interval])) by (finished_reason)`

But each of my queries in the model is displayed on the graph in the amount of "2". It seems that the value is incremented twice by mistake with a single request.

![image](https://github.com/vllm-project/vllm/assets/21113432/b5b686de-02c8-416d-8797-4d368d00790b)

**Comment by simon-mo** [comment]
@EthanqX can you take a look?

**Comment by robertgshaw2-neuralmagic** [comment]
How many generations are you running per request (e.g. what is the `n` parameter set to)?  If you are requesting more than 1, we currently count each `n` as a separate request)
