### ISSUE TITLE
vllm推理THUDM/chatglm3-6b-128k 无法stop

### ISSUE THREAD

**Issue by linzm1007** [vllm-project/vllm#5268]
### Your current environment

vllm推理THUDM/chatglm3-6b-128k 无法stop

### 🐛 Describe the bug

vllm推理THUDM/chatglm3-6b-128k 无法stop

**Comment by zhaotyer** [comment]
you need add
``` 
stop_token_ids = [151329, 151336, 151338]
```

**Comment by linzm1007** [comment]
> you need add
> 
> ```
> stop_token_ids = [151329, 151336, 151338]
> ```

试了一下，还是不行

**Comment by T-Atlas** [comment]
![image](https://github.com/vllm-project/vllm/assets/69239617/38ca438d-752c-47b3-91cc-2a6acdd9577f)
