### ISSUE TITLE
why I use fastchat-vllm to inference vicuna-13B，It took 75 G of video memory(A800, 80G)

### ISSUE THREAD

**Issue by cabbagetalk** [vllm-project/vllm#527]
python -m vllm.entrypoints.api_server --model /mnt/data/data/luwei/output/0711/checkpoint-2000/ --tokenizer hf-internal-testing/llama-tokenizer --port 32333

**Comment by cabbagetalk** [comment]
why I use fastchat-vllm to inference vicuna-13B，It took 75 G of video memory(A800, 80G)

**Comment by irasin** [comment]
Because vllm will allocate a lot of kv cache memory blocks which will be used in paged attention. 
And by default, vllm will use at most 90% gpu memory, you can modify the usage by the `gpu_memory_utilization`.

**Comment by cabbagetalk** [comment]
已解决，谢谢
