### ISSUE TITLE
[Bug]: After fine-tuning Qwen Lora, the inference results differ when using VLLM and Hugging Face to load

### ISSUE THREAD

**Issue by lonngxiang** [vllm-project/vllm#5298]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

https://github.com/hiyouga/LLaMA-Factory/issues/4049

transformers+lora
![image](https://github.com/vllm-project/vllm/assets/40717349/afe5aa23-f83d-403d-b3ae-12d651128d4e)

vllm+lora
![image](https://github.com/vllm-project/vllm/assets/40717349/6dfd9014-736f-4708-b2b0-0f1183a86b36)

**Comment by jeejeelee** [comment]
可以使用do sample对齐下，我们现在也有基于QWen1.5-14B的lora模型，用vllm 推理跟用transformers推理结果能对齐

**Comment by lonngxiang** [comment]
> 可以使用do sample对齐下，我们现在也有基于QWen1.5-14B的lora模型，用vllm 推理跟用transformers推理结果能对齐

麻烦do sample要怎么操作呢？

**Comment by jeejeelee** [comment]
参考：  https://github.com/vllm-project/vllm/blob/main/tests/models/test_models.py#L26 。不应该是do sample，而应该是generate_greedy

**Comment by lonngxiang** [comment]
> 参考： https://github.com/vllm-project/vllm/blob/main/tests/models/test_models.py#L26 。不应该是do sample，而应该是generate_greedy

谢谢，但这怎么实际用上呢，这边用的vllm openai推理接口，用的python openai 包去连接使用

**Comment by lonngxiang** [comment]
> ` greedy_params = SamplingParams(temperature=0.0, max_tokens=max_tokens)` 按照传递vllm的生成参数，transformers的话，按照下面的方式：
> 
> ```python
> outputs = self.generate(prompts,
>                                 do_sample=False,
>                                 max_new_tokens=max_tokens,
>                                 images=images)
> ```
> 
> 应该就行了

看的不是很明白；vllm 推理的参数不用动是把
```
--model /qwen-7b  --port 10860 --max-model-len 4096   --trust-remote-code --tensor-parallel-size 1 
```
需要更改的是调用推理api时候传的参数吗？SamplingParams 具体要传什么参数呢

**Comment by lonngxiang** [comment]
> ` greedy_params = SamplingParams(temperature=0.0, max_tokens=max_tokens)` 按照传递vllm的生成参数，transformers的话，按照下面的方式：
> 
> ```python
> outputs = self.generate(prompts,
>                                 do_sample=False,
>                                 max_new_tokens=max_tokens,
>                                 images=images)
> ```
> 
> 应该就行了

具体需要传那些参数呢SamplingParams

**Comment by jeejeelee** [comment]
1. 应该需要设置下temperature
2.  还需要注意的地方使用vllm推理qwen-14B的话，可能需要添加`chat-template`

**Comment by lonngxiang** [comment]
> 2\. chat-template

嗯，麻烦有具体参考例子可以提供吗，不大会写这块

**Comment by lonngxiang** [comment]
@jeejeelee 这边是qwen7b，用了temperature没有用，chat-template不知道要设置吗

![image](https://github.com/vllm-project/vllm/assets/40717349/bd37c8be-1714-461b-8c45-693e5d407428)

**Comment by lonngxiang** [comment]
> @jeejeelee 这边是qwen7b，用了temperature没有用，chat-template不知道要设置吗
> 
> ![image](https://private-user-images.githubusercontent.com/40717349/337236691-bd37c8be-1714-461b-8c45-693e5d407428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzIwMDYsIm5iZiI6MTcxNzY3MTcwNiwicGF0aCI6Ii80MDcxNzM0OS8zMzcyMzY2OTEtYmQzN2M4YmUtMTcxNC00NjFiLThjNDUtNjkzZTVkNDA3NDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDExMDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjQ3NGM0NTQzN2E4Yjg0Y2VmZmE0NTc2YTE1NWU2OWJiYzExZmY4MTc5NjE1NjA3YzEwZDMzZTM2NzJjZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YU-mXv2n_PUZSUMfnPMdbuQ7QT_SdG09jZrShfY_xx0)
推理日志看着使用加载默认chat-template的
![image](https://github.com/vllm-project/vllm/assets/40717349/a320829b-b393-41c4-878b-fb5c13272057)
