### ISSUE TITLE
[Bug]: GPU memory usage is inconsistent with gpu_memory_utilization settings

### ISSUE THREAD

**Issue by yecphaha** [vllm-project/vllm#5305]
### Your current environment

Deploy using llama factory
CUDA_VISIBLE_DEVICES=0 API_PORT=9092 python src/api_demo.py
--model_name_or_path /save_model/qwen1_5_7b_pcb_merge
--template qwen
--infer_backend vllm
--max_new_tokens 32768
--vllm_maxlen 32768
--vllm_enforce_eager
--vllm_gpu_util 0.95

Inference environment:
Python=3.10.14
CUDA=12.2
single A100 80G

### 🐛 Describe the bug

There is no other GPU usage during deployment. The expected GPU usage is 76G, but the actual GPU usage is 55G. What is the reason?

**Comment by vrdn-23** [comment]
Might be related to https://github.com/vllm-project/vllm/pull/5158
