### ISSUE TITLE
About Distributed Inference and Serving

### ISSUE THREAD

**Issue by cabbagetalk** [vllm-project/vllm#531]
We are now using some RTX4090(24G) cards to load the vicuna-13b(30G of one model). Can we set the number of loading parameters on each graphics card?
Requirements :4 graphics cards loaded 3 models, 24*4/3 = 32G。

**Comment by zhuohan123** [comment]
You can use `-tp N` to split the model into `N` tensor parallel slices. Please choose `N` to be power of 2 (e.g., 1, 2, 4, ...). Setting `N=3` can have division issues and it might not work.

Feel free to reopen the issue if you have any further questions!
