### ISSUE TITLE
[Performance]: Is kv cache implemented globally in vllm， It can be shared by multiple concurrent inferences?

### ISSUE THREAD

**Issue by askcs517** [vllm-project/vllm#5314]
### Proposal to improve performance

 Is kv cache implemented globally in vllm， It can be shared by multiple concurrent inferences?
 if it is not supported yet, is there any plan to support it?
For example, some long prompt words have the same long prefix，whether it can be optimized?

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by robertgshaw2-neuralmagic** [comment]
Im not sure what you mean by "shared by multiple concurrent inferences"

If you run with `--enable-prefix-caching`, then vLLM keep around KV tokens in an LRU cache and try to share them across prompts

**Comment by zhengxinyao** [comment]
If there are multiple users sending concurrent requests for inference to the same physical machine, even though the requests come from different users, as long as the inference is being performed on the same physical machine, those requests can share the KVcache if theyhave the same prefix？

**Comment by panpan0000** [comment]
across nodes, I believe that's original question
