### ISSUE TITLE
[Feature]: Make a unstable latest docker image

### ISSUE THREAD

**Issue by emillykkejensen** [vllm-project/vllm#5315]
### 🚀 The feature, motivation and pitch

I'm trying to test Lora with quantization using BnB and I'm using Docker to run vLLM. However, I can't find a docker image, on docker hub, with a tag that matches the 'latest' version. The latest tag of the docker images correspond til the stable version - not latest.

So have you considered makes a tag for the 'latest' (unstable) version for Docker?

**Comment by seandearnaley** [comment]
+1
