### ISSUE TITLE
[Performance]: gptq and awq quantization do not improve the performance

### ISSUE THREAD

**Issue by aaronlyt** [vllm-project/vllm#5316]
### Report of performance regression

vllm version: 0.4.3, gpu A40, 46Gi, single gpu

### phi3 fp16
$python -m vllm.entrypoints.openai.api_server --model /t9k/mnt/workspace/llm_models/phi3 --dtype bfloat16 --trust-remote-code --max-model-len 4096 
python test_serving.py --backend 'vllm' --model /t9k/mnt/workspace/llm_models/phi3 --dataset-name summarize --num-prompts 1000 --request-rate 60
============ Serving Benchmark Result ============
Successful requests:                     1000      
**Benchmark duration (s):                  118.85**    
Total input tokens:                      686000    
Total generated tokens:                  56000     
**Request throughput (req/s):              8.41**      
Input token throughput (tok/s):          5772.20   
Output token throughput (tok/s):         471.20    
---------------Time to First Token----------------
Mean TTFT (ms):                          47476.00  
Median TTFT (ms):                        50637.58  
P99 TTFT (ms):                           98138.44  
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          190.66    
Median TPOT (ms):                        189.92    
P99 TPOT (ms):                           338.66    

### awq performance:
python -m vllm.entrypoints.openai.api_server --model  phi3-4k-awq --quantization 'awq' --dtype auto --trust-remote-code
$python test_serving.py --backend 'vllm' --model phi3-4k-awq --dataset-name summarize --num-prompts 1000 --request-rate 60 --sharegpt-output-len 80
============ Serving Benchmark Result ============
Successful requests:                     1000      
**Benchmark duration (s):                  152.12**    
Total input tokens:                      692000    
Total generated tokens:                  81000     
Request throughput (req/s):              6.57      
Input token throughput (tok/s):          4549.11   
Output token throughput (tok/s):         532.48    
---------------Time to First Token----------------
Mean TTFT (ms):                          61355.65  
Median TTFT (ms):                        59868.52  
P99 TTFT (ms):                           129631.18 
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          202.43    
Median TPOT (ms):                        203.29    
P99 TPOT (ms):                           351.99    

### Misc discussion on performance

vllm version: 0.4.3, gpu 40, 46Gi, single gpu
fp16: **Benchmark duration (s):                  118.85**    
awq performance: **Benchmark duration (s):                  152.12**    
gptq_marlin: Benchmark duration (s):                  163.84

Question: is this normal, any advice?

### Your current environment (if you think it is necessary)

vllm version: 0.4.3, gpu A40, 46Gi, single gpu```

**Comment by aaronlyt** [comment]
A40，sorry

**Comment by robertgshaw2-neuralmagic** [comment]
- your server is overloaded across all these models, so it will be hard to compare performance
- you have different numbers of generated tokens across these benchmarks (though I cannot see the GPTQ numbers). you should really focus on TPOT and TTFT for the server benchmarking case to normalize these

For AWQ: 
```bash
Total generated tokens: 81000
```

For Fp16:
```bash
Total generated tokens: 56000
```

- AWQ is indeed not as optimized as it could be.
- GPTQ_Marlin will give SOTA performance for W4A16 on this machine type

**Comment by aaronlyt** [comment]
tks for response, re-test, gptq)marlin still have no any improvement:
**fp 16**:
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  150.46    
Total input tokens:                      600000    
Total generated tokens:                  81398     
Request throughput (req/s):              6.65      
Input token throughput (tok/s):          3987.72   
Output token throughput (tok/s):         540.99    
---------------Time to First Token----------------
Mean TTFT (ms):                          62444.11  
Median TTFT (ms):                        66340.39  
P99 TTFT (ms):                           128055.89 
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          176.01    
Median TPOT (ms):                        174.34    
P99 TPOT (ms):                           316.43    

**gptq**
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  159.76    
Total input tokens:                      600000    
Total generated tokens:                  82000     
Request throughput (req/s):              6.26      
Input token throughput (tok/s):          3755.73   
Output token throughput (tok/s):         513.28    
---------------Time to First Token----------------
Mean TTFT (ms):                          65837.26  
Median TTFT (ms):                        65179.95  
P99 TTFT (ms):                           138498.75 
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          204.54    
Median TPOT (ms):                        202.70    
P99 TPOT (ms):                           369.07
