### ISSUE TITLE
can not match with performance in readme

### ISSUE THREAD

**Issue by guozhiyao** [vllm-project/vllm#533]
I test a 13b model on a A100-80G with `benchmark_throughput.py`.
The hf result is 0.2 requests/s, 85.25 tokens/s.
The vllm result is 4.94 requests/s, 2153.77 tokens/s.
The acceleration effect is obvious, but the gap with the readme(154.2 requests/s) is huge. Is this result correct? Or am I doing something wrong?

Besides, the vllm use `_add_request` to load all input and use `_run_engine` to do the inference. A bit strange why not use `generate` directly? If there is a lot of data, we can not use `_add_request` to load whole data at once.

**Comment by guozhiyao** [comment]
@irasin 
Awesome, sorry didn't notice the unit.

As for the second question, when inferring a large amount of data, it is impossible to load all through `_add_request`, right? So how do you do the inference? Combine batches by myself?

**Comment by guozhiyao** [comment]
@irasin 
Thank you for your reply. For `generate`, it is also necessary to load all the data at one time to form a list. When the amount of data is particularly large, loading is very time-consuming and requires a lot of memory. Is it considered to be able to automatically combine batch from `generator`? Such as
```
def generator():
    with open("data.txt") as f:
        for line in f.readlines():
            yield line

 outputs = llm.generate(generator())
```

**Comment by irasin** [comment]
Hi @guozhiyao.If you want, of course you can do something like request amount control outside vllm. But I am not sure about the code you show will work.
BTW, just curious about how large the `data.txt` is.

**Comment by bigmover** [comment]
I can't run the benchmark test because  the wrong dataset format.  Would you mind to show the dataset you used? thks!

**Comment by zhuohan123** [comment]
> I can't run the benchmark test because the wrong dataset format. Would you mind to show the dataset you used? thks!

Please check [here](https://github.com/vllm-project/vllm/tree/main/benchmarks#downloading-the-sharegpt-dataset) for the dataset link!

**Comment by zhuohan123** [comment]
Thanks @irasin for answering this!

**Comment by bigmover** [comment]
> > I can't run the benchmark test because the wrong dataset format. Would you mind to show the dataset you used? thks!
> 
> Please check [here](https://github.com/vllm-project/vllm/tree/main/benchmarks#downloading-the-sharegpt-dataset) for the dataset link!

Thanks @zhuohan123 for great help ! Got it!
