### ISSUE TITLE
[Bug]: non-deterministic Python gc order leads to flaky tests

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#5337]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

I often see many flaky tests, and I think the Python gc system is one of the factor to blame.

Python gc system is notoriously random. When we call `del x`, and `x`'s refcount is 0, it is not guaranteed that all resources held by `x` will be released immediately. This is true especially when `x` is a complicated object, and might contain self-reference inside it. That's one of the motivation for Python to propose the concept of context manager, to enforce some critical resource to be released immediately.

Take the following code as an example:

```python
import torch
import weakref
import gc

def tensor_destructed(tensor_ref):
    # This function is called when the tensor is destructed.
    print(f"Tensor with id {id(tensor_ref)} is being destructed.")

class A:
    def __init__(self):
        self.tensor = torch.tensor([1.0, 2.0, 3.0])

    def __del__(self):
        print("A is being destructed.")
        del self.tensor

def main():
    # Create a complex object with a tensor.
    data = A()
    # the object is so complicated that it has a reference to itself.
    data.self = data
    # Attach a weak reference to the tensor with a callback for destruction.
    tensor_ref = weakref.ref(data.tensor, tensor_destructed)

    # Deleting the tensor manually.
    print("before del data")
    del data
    print("after del data, before gc collected")
    
    # Manually trigger garbage collection to see the destruction callback in action.
    gc.collect()
    print("after gc collected")

if __name__ == "__main__":
    main()

```

The output is:

```text
before del data
after del data, before gc collected
Tensor with id 4379931520 is being destructed.
A is being destructed.
after gc collected
```

As it shows, the tensor is not destructed after we call `del data`. It is only destructed when we call `gc.collect()`, where Python will detect and break reference-cycles to destruct unreachable objects.

The following code in vLLM can suffer from Python gc:

https://github.com/vllm-project/vllm/blob/388596c91437a51d428a447594e9faec340c29b2/tests/models/test_models.py#L37-L44

After `del hf_model`, chances are GPU memory held by `hf_model` is not released yet. This will cause OOM for the later vLLM model, leading to a flaky test. I have seen it broken for many times, and sometimes retrying the test helps.

Adding `import gc; gc.collect()` solves the problem. However, to avoid code duplication, it is better to wrap `hf_model` as a context manager, and to call `import gc; gc.collect()` automatically after we exit the context manager:

```python
   with hf_runner(model, dtype=dtype) as hf_model:
        hf_outputs = hf_model.generate_greedy(example_prompts, max_tokens)
```

**Comment by rkooo567** [comment]
Actually the destructor of hf_runner should call cleanup() which calls gc.collect() https://github.com/vllm-project/vllm/blob/388596c91437a51d428a447594e9faec340c29b2/tests/conftest.py#L359

Is this not sufficient?

**Comment by DarkLight1337** [comment]
I think the context manager approach is cleaner in any case. However, this will require refactoring the runner classes to only initialize the model when the context manager is entered.

**Comment by DarkLight1337** [comment]
> Actually the destructor of hf_runner should call cleanup() which calls gc.collect()
> 
> https://github.com/vllm-project/vllm/blob/388596c91437a51d428a447594e9faec340c29b2/tests/conftest.py#L359
> 
> Is this not sufficient?

`__del__` is only called when the object is actually GC'ed, not when the `del` statement is used.

**Comment by DarkLight1337** [comment]
Btw in general, we should using `weakref.finalizer` over `__del__`. See [this documentation](https://docs.python.org/3/library/weakref.html#comparing-finalizers-with-del-methods) for more details.

**Comment by youkaichao** [comment]
@rkooo567 I updated the code and the output. `__del__` is not enough here. You can see that `A.__del__` calls `del self.tensor`. However, the tensor is destructed before `A.__del__` is called. That's why Python gc is not reliable, especially when we need to enforce some destruction order.

**Comment by youkaichao** [comment]
> In any case, I think the context manager approach is cleaner. However, this will require refactoring the runner classes to only initialize the model when the context manager is entered.

@DarkLight1337 not necessary. We can make the runner itself a context manager. e.g. adding the following lines:

```python
class HfRunner:
    ...
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        del self
        cleanup()
```

Then the following change should be enough:

```diff
-    hf_model = hf_runner(model, dtype=dtype)
-    hf_outputs = hf_model.generate_greedy(example_prompts, max_tokens)
-    del hf_model
+    with hf_runner(model, dtype=dtype) as hf_model:
+         hf_outputs = hf_model.generate_greedy(example_prompts, max_tokens)
```

We should avoid using `weakref.finalize` or `__del__ `. They are just not reliable.

**Comment by DarkLight1337** [comment]
> ```python
> class HfRunner:
>     ...
>     def __enter__(self):
>         return self
> 
>     def __exit__(self, exc_type, exc_value, traceback):
>         del self
>         cleanup()
> ```

I don't think this will work. In particular, `del self` does not really do anything since the `HfRunner` is still inside the scope of the test function. We should instead operate on the wrapped model directly.

**Comment by DarkLight1337** [comment]
> We should avoid using `weakref.finalize` or `__del__`. They are just not reliable.

Yeah, they are both dependant on GC so they won't be suitable in situations where GC is not even being invoked.

**Comment by youkaichao** [comment]
> I don't think this will work. In particular, `del self` does not really do anything since the `HfRunner` is still inside the scope of the test function. We should instead operate on the wrapped model (`self.model`) directly.

Good point. How about `del self.model` inside `__exit__ `?

**Comment by DarkLight1337** [comment]
> I don't think this will work. In particular, `del self` does not really do anything since the `HfRunner` is still inside the scope of the test function. We should instead operate on the wrapped model (`self.model`) directly.

Btw this is what I mean:

```diff,py
class HfRunner:
    def __init__(self, ...):
-       self.model = create_model(...)
+       self.model = None

    def __enter__(self):
+       self.model = create_model(...)
        return self

    def __exit__(self, exc_type, exc_value, traceback):
-       del self
+       self.model = None
        cleanup()
```

**Comment by youkaichao** [comment]
I think they are equivalent. For the following code:

```python
   with hf_runner(model, dtype=dtype) as hf_model:
        hf_outputs = hf_model.generate_greedy(example_prompts, max_tokens)
```

The function call chain is:
- `hf_model = hf_runner() # essentially HfRunner. __init__`
- `hf_model.__enter__()`
- `hf_outputs = hf_model.generate_greedy(example_prompts, max_tokens)`
- `hf_model. __exit__()`

**Comment by DarkLight1337** [comment]
To avoid having to check `self.model is not None` each time in the other methods, it may be better to have a separate context manager function that returns the runner object. For example:

```py
@contextlib.contextmanager
def hf_model_runner(*args, **kwargs):
    model = create_model(...)
    yield HfRunner(model, ...)
    del model
    cleanup()

class HfRunner:
    def __init__(self, model, ...):
        self.model = model
        # The rest is the same as original HfRunner without context manager. Also we can now remove `__del__` method
```

**Comment by DarkLight1337** [comment]
After some offline discussion, we have settled on the following code:

```py
class HfRunner:
    def __init__(self, ...):
       self.model = create_model(...)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        del self.model
        cleanup()
```

Although `HfRunner` can only be used once as a context manager, it is sufficient for testing. This passes the type checker without needlessly complicating the existing code.

**Comment by robertgshaw2-neuralmagic** [comment]
Love this!
