### ISSUE TITLE
[Misc]: PagedAttention + cudagraphs 

### ISSUE THREAD

**Issue by jeromeku** [vllm-project/vllm#5382]
### Anything you want to discuss about vllm.

Please excuse the naive question, but was wondering how `PagedAttention` can be used with `Cuda Graphs` given that KV cache is dynamically allocated with `PagedAttention`?

**Comment by simon-mo** [comment]
Yes. Although KV cache for a particular request is dynamically allocated. vLLM allocates a continuous memory space for all KV cache ahead of time.

**Comment by tricky61** [comment]
> Yes. Although KV cache for a particular request is dynamically allocated. vLLM allocates a continuous memory space for all KV cache ahead of time.

as the pagedattention has two versions: v1 and v2
In the normal inference, with the increase of max_num_partitions, pagedattention may changed from v1 to v2.
does the Cuda graphs will use two versions? or it will use v1 as default since it is compiled beforehead
