### ISSUE TITLE
Best performance for distributed offline inference

### ISSUE THREAD

**Issue by Naman-ntc** [vllm-project/vllm#540]
Perhaps this question is better meant for a discussion forum!

I want to run offline inference over a large dataset on a node with multiple A100 GPUs. There is a broad design space available here 

* using `tensor_parallel_size` in vs offloading jobs to different GPUs over separate processing using `CUDA_VISIBLE_DEVICES`
* finding optimal _batch size_
* possibly ordering queries across a batch!?

I was curious if you had thoughts on this and is there any recommended approach?

**Comment by sam-h-bean** [comment]
Yeah what are people doing to run ETLs on a distributed vllm setup?

**Comment by barius** [comment]
maybe launch one instance of vllm api server per GPU and place a load balancer e.g. nginx upon them?
