### ISSUE TITLE
[Bug]: Small context lengths consume more memory than large context lengths

### ISSUE THREAD

**Issue by majestichou** [vllm-project/vllm#5416]
### Your current environment

**_Here is my host environment_**. I use docker image to start vllm
```
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.25.0-rc2
Libc version: glibc-2.17

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 12.2.128
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                192
On-line CPU(s) list:   0-191
Thread(s) per core:    2
Core(s) per socket:    48
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7642 48-Core Processor
Stepping:              0
CPU MHz:               1500.000
CPU max MHz:           2300.0000
CPU min MHz:           1500.0000
BogoMIPS:              4600.12
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-47,96-143
NUMA node1 CPU(s):     48-95,144-191
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm exapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate sme retpoline_amd ssbd ibr ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero rperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

```

### 🐛 Describe the bug

I use vLLM (v0.4.2 docker image) to load THUDM/glm-4-9b-chat-1m model, which supports 1M context length. I download the model weights to a local directory named `/serving/data/models/`.  Run the following command to start the Docker container:

`docker run --rm --gpus 8 -p 8080:8000 --ipc=host -v /serving/data/models/:/data/models/ --env "TRANSFORMERS_OFFLINE=1" --env HF_DATASET_OFFLINE=1" vllm/vllm-openai:v0.4.2 --model "/data/models/glm-4-9b-chat-1m/" --max-model-len 400000 --tensor-parallel-size 8 --trust-remote-code --gpu-memory-utilization 0.99`

Change the value of --max-model-len to check the consumption of the video memory. My machine has a total of 320 GB of video memory.

| --max-model-len | Video Memory Consumption |
|----------|----------|
| 1048576    | OOM   | 
| 524288    | OOM   | 
| 471860    | OOM   |
| 400000 | The video RAM usage increases to 241.92 GB, decreases, and then remains at about 135.04 GB.|
| 393216 | The video RAM usage increases to 241.92 GB, decreases, and then remains at about 137.6 GB.|
| 262144 | The video RAM usage increases to 200.32GB, no decrease...|
| 131072 | The video RAM usage increases to 265.6GB, no decrease...|
| 65536 | The video RAM usage increases to 294.72GB, no decrease...|

There are two strange things that can be gleaned from the above data:

1. Video memory consumption increases and then decreases under certain settings, such as 400000, 393216
2. Small context lengths may consume more memory than large context lengths.

**Comment by robertgshaw2-neuralmagic** [comment]
This is not a bug. We pre-allocate memory for the KV cache based on the following formula:
- (total memory * gpu_util) - weights - maximum_activation_size`

The `maximum_activation_size` is measured from peak memory from running a profile run with your `model_max_length`. So you are seeing memory go up during the profiling run.

**Comment by robertgshaw2-neuralmagic** [comment]
> > This is not a bug. We pre-allocate memory for the KV cache based on the following formula:
> > 
> > * (total memory * gpu_util) - weights - maximum_activation_size`
> > 
> > The `maximum_activation_size` is measured from peak memory from running a profile run with your `model_max_length`. So you are seeing memory go up during the profiling run and then drop back down
> 
> Small context lengths may consume more memory than large context lengths. What is the reason？

We allocate memory for the KV cache size and weights based on the maximum potential activation size.

- longer_content ==> large maximum activation size ==> less space for kv cache ==> less memory allocated
