### ISSUE TITLE
[Feature]: ci test with vGPU

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#5426]
### 🚀 The feature, motivation and pitch

it seems aws and gcp supports [vGPU](https://docs.nvidia.com/grid/cloud-service-support.html) . we can run some small tests in vGPU, which should be cost-efficient and also test broader software support to avoid https://github.com/vllm-project/vllm/issues/4587 .

**Comment by kerthcet** [comment]
Nvidia vgpu requires license, have no idea whether these cloud providers have the service.

**Comment by khluu** [comment]
From what I read on the page, AWS & GCP don't support vGPU and only Alibaba supports it?
