### ISSUE TITLE
multilora_inference调用qwen2-1.5b报错

### ISSUE THREAD

**Issue by zigangzhao-ai** [vllm-project/vllm#5445]
### 📚 The doc issue

用examples/multilora_inference.py 调用qwen2-1.5b时，保错 -  RuntimeError: No suitable kernel. h_in=16 h_out=8960 dtype=Float out_dtype=BFloat16

**Comment by jeejeelee** [comment]
https://github.com/vllm-project/vllm/pull/5441 should be able to resolve this issue.

**Comment by mgoin** [comment]
This should be resolved with the new landed Triton kernels https://github.com/vllm-project/vllm/pull/5036
