### ISSUE TITLE
[Bug]: Outdated binaries when re-building vLLM from source

### ISSUE THREAD

**Issue by DarkLight1337** [vllm-project/vllm#5456]
### 🐛 Describe the bug

After upgrading vLLM (e.g. syncing a fork with latest `main` branch), re-building from source fails to clear/overwrite the existing compiled binaries, resulting in errors such as

```
AttributeError: '_OpNamespace' '_C' object has no attribute ...
```

### Workaround

Installing from a fresh clone of vLLM fixes this error.

Nevertheless, it would be ideal to automatically remove/update outdated binaries when re-building vLLM.

### Related issues

- #5448
- #5454
- #5461

**Comment by youkaichao** [comment]
> it would be ideal to automatically remove/update outdated binaries when re-building vLLM

Users might feel unhappy when we silently delete their files.

I added some [hints](https://github.com/vllm-project/vllm/pull/5462) for users, and users can follow the instruction to do the cleanup.

Let me know if you like this idea.
