### ISSUE TITLE
[Feature]: PagedAttention multiple of 8

### ISSUE THREAD

**Issue by barschiiii** [vllm-project/vllm#5459]
This is more of a informative question than a direct feature request.

From my understanding, currently PagedAttention only allows head dimensions being multiples of 16, is this correct?

What efforts would be required to also allow multiples of 8? 

Thanks

**Comment by simon-mo** [comment]
I believe 8 is also supported

https://github.com/vllm-project/vllm/blob/5cc50a531f720758025c8493ee85a56272277a54/csrc/attention/attention_kernels.cu#L948-L965

But generally for other block size, it is a matter of compiling the right configuration for kernels and tuning it. The paper did some investigation over the optimal block sizes https://arxiv.org/pdf/2309.06180
