### ISSUE TITLE
[Bug]: Torch2.3 run fail

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#5461]
### Your current environment

[rank0]: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

### 🐛 Describe the bug

[rank0]: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'

k0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/qwen2.py", line 202, in forward
[rank0]:     hidden_states = self.input_layernorm(hidden_states)
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/custom_op.py", line 13, in forward
[rank0]:     return self._forward_method(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/layernorm.py", line 62, in forward_cuda
[rank0]:     ops.rms_norm(
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/_custom_ops.py", line 132, in rms_norm
[rank0]:     torch.ops._C.rms_norm(out, input, weight, epsilon)
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 921, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: '_OpNamespace' '_C' object has no attribute 'rms_norm'
root@xingzai:/data/llama_sft# python
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
torch>>> torch.__version__
'2.3.0'

**Comment by DarkLight1337** [comment]
Please see #5456.
