### ISSUE TITLE
[Bug]: Build from source but got unexpected symbol

### ISSUE THREAD

**Issue by MonolithFoundation** [vllm-project/vllm#5486]
### Your current environment

```text
WARNING 06-13 04:15:46 _custom_ops.py:11] Failed to import from vllm._C with ImportError('/data/libs/vllm/vllm/_C.abi3.so: undefined symbol: _ZN5torch7LibraryC1ENS0_4KindESsSt8optionalIN3c1011DispatchKeyEEPKcj')```


<img width="1384" alt="image" src="https://github.com/vllm-project/vllm/assets/168061642/122ce5c3-7155-430b-9efd-3b1874301002">


### 🐛 Describe the bug

git clone xxx && pip install -e .

Already cleaned old build, actually this is a fresh clone.

**Comment by youkaichao** [comment]
Please add your environment details following the issue template :)

**Comment by MonolithFoundation** [comment]
this issue is not raised once noticed there are many since yesterday please take a look



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/13/2024 12:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [vllm-project/vllm] [Bug]: Build from source but got unexpected symbol (Issue #5486) |

Please add your environment details following the issue template :)
