### ISSUE TITLE
GPU consumption

### ISSUE THREAD

**Issue by David-Lee-1990** [vllm-project/vllm#550]
when i load 13b llama in HF, GPU usage is about 26G. 

However, when load 13b llama in vllm, GPU usage is about 73G.

<img width="641" alt="image" src="https://github.com/vllm-project/vllm/assets/29653610/94d7848d-c5bc-481c-bf2a-a64aeeb1ca77">

Is this ususal?

**Comment by trannhatquy** [comment]
I load the opt 125M in the vllm api and it takes 21GB on RTX 6000, it's strange.

**Comment by rahuldshetty** [comment]
> I load the opt 125M in the vllm api and it takes 21GB on RTX 6000, it's strange.

Observe the same issue with A100 20Gi profile. Using the opt-125 eats up complete GPU memory. 
Seems like a case of memory leak ?

**Comment by irasin** [comment]
vllm use allocate 90% GPU memory for model inference and kv_cache blocks. So in A100 case, it will use at least 0.9 * 81920 = 73728 MiB

**Comment by rahuldshetty** [comment]
> vllm will allocate 90% GPU memory for model inference and kv_cache blocks. So in A100 case, it will use at least 0.9 * 81920 = 73728 MiB

Any way to limit the GPU memory usage ? (if we can tradeoff between throughput/memory)

**Comment by irasin** [comment]
> > vllm will allocate 90% GPU memory for model inference and kv_cache blocks. So in A100 case, it will use at least 0.9 * 81920 = 73728 MiB
> 
> Any way to limit the GPU memory usage ? (if we can tradeoff between throughput/memory)

You can restrict the gpu usage with the `gpu_memory_utilization`,  https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py#L27

**Comment by irasin** [comment]
Since vllm support continuous batching, it will automatically schedule the requests to run in each iteration, so oom will not happen.
However, if you do something like parallel sampling, you may see oom happen if there is no enough cpu_cache blocks.

**Comment by zhuohan123** [comment]
Please refer to #241 for memory usage! We will add this to our document.
