### ISSUE TITLE
Langchain/LLAMA_INDEX

### ISSUE THREAD

**Issue by drewskidang** [vllm-project/vllm#553]
Sorry still not sure but is vllm applicable with langchain/llamaindex

**Comment by StephennFernandes** [comment]
Hey have you found any solution on this ? 

I am too looking for llammaIndex or langchain integration to work with vllm

**Comment by drewskidang** [comment]
I wish i think the best way is use a custom model  class from langchain

**Comment by drewskidang** [comment]
> 

https://python.langchain.com/docs/integrations/llms/vllm they added it!

**Comment by zhuohan123** [comment]
> https://python.langchain.com/docs/integrations/llms/vllm they added it!

Thanks for finding this! Glad to see the official support from LangChain!

**Comment by StephennFernandes** [comment]
Thanks @drewskidang

**Comment by StephennFernandes** [comment]
hey @drewskidang @zhuohan123 given that langchain comes with its own sets of issues in production. could you please let me know if there is llama_index integration or how could i do this via llama index

**Comment by drewskidang** [comment]
@StephennFernandes yeah i was getting langchain issues too..... unfortunately no llama index configs

**Comment by jqueguiner** [comment]
you can do it through langchain in llama index:
https://docs.llamaindex.ai/en/stable/examples/llm/langchain.html

**Comment by drewskidang** [comment]
thanks @jqueguiner  do you know to enable rope scaling on langchain
