### ISSUE TITLE
[Performance]: How use vllm.attention.ops.triton_flash_attention replace flash_attn package

### ISSUE THREAD

**Issue by Arcmoon-Hu** [vllm-project/vllm#5534]
### Proposal to improve performance

My gpu is tool old so that can't install flash_attn package.
So, I want use vllm.attention.ops.triton_flash_attention replace flash_attn package

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by simon-mo** [comment]
The triton kernel is tailored to AMD at the moment. I would recommend setting VLLM_ATTENTION_BACKEND=xformers instead
