### ISSUE TITLE
How to specify which gpu to use?

### ISSUE THREAD

**Issue by Zhuqln** [vllm-project/vllm#554]
If I have multiple GPUs, how can I specify which GPU to use individually? 

Previously, I used `'device_map': 'sequential'` with `accelerate` to control this. Now, with `vllm_engine`, is there a similar functionality available?"

exp. if i want to specify the `gpu1` instead of `gpu0`,because they are not same type of card.i will write like this:
```python
model_kwargs = {"torch_dtype": torch.float16, 'device_map': 'sequential'}
```

Then, I manually set the available memory of `device0` to 0, with the purpose of using `device1`:

```
GPU_max_memory: {0: '0GiB', 1: '40GiB'}
```

**Comment by gesanqiu** [comment]
Use `CUDA_VISIBLE_DEVICES=0,1,2,3 python -m vllm.x.x.x. [parameters]` to specify the gpus you want to use in a process level.

**Comment by Zhuqln** [comment]
Thank you for the suggestion. 
I am aware of this method, but due to my project's architecture, I need to be able to start my worker through a triggered request. 
Using the "python" command directly in the terminal is not suitable for me. Nevertheless, I am delighted to receive your response. Thanks again.

**Comment by zhuohan123** [comment]
In addition to @gesanqiu's method, you can also use [Ray's placement group feature](https://docs.ray.io/en/latest/ray-core/scheduling/placement-group.html) for this. Feel free to re-open the issue if you meet any issues or have any other suggestions!
