### ISSUE TITLE
gai error: -2 - Name or service not known

### ISSUE THREAD

**Issue by weishengying** [vllm-project/vllm#557]
When I deploy a gpt2 model on 4 GPUs with vllm, I got this error:
![image](https://github.com/vllm-project/vllm/assets/63448337/36a91f83-201a-47dc-916d-9aaa2ae028e4)

here is my test code:
```python
from vllm import LLM, SamplingParams

prompts = [
    "San Franciso is a"
]

llm = LLM(model="gpt2", tensor_parallel_size=2, disable_log_stats=False)
outputs = llm.generate(prompts)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

so how can i solve this?

**Comment by Jupiter-Zhu** [comment]
I am seeing similar erros. Are you on AWS?

**Comment by weishengying** [comment]
> I am seeing similar erros. Are you on AWS?

not Amazon Web Services，but similar to AWS, it's TikTok's cloud server which called “volcengine”

**Comment by weishengying** [comment]
> I am seeing similar erros. Are you on AWS?

sometimes, I alse got this error: 
![image](https://github.com/vllm-project/vllm/assets/63448337/0361f899-c23c-4f52-b2b5-37df3a966924)

**Comment by HermitSun** [comment]
I met the same problem, but I'm using vllm in a k8s pod. I tried to start a ray server manually at `localhost:6379` and pass it as `ray_address` to `ray.init` during vllm's init process, but still met the same problem:

https://github.com/vllm-project/vllm/blob/7d5a155e4aa258b0db1649bdcbf29477bf490ac2/vllm/engine/ray_utils.py#L67

Any ideas?

**Comment by weishengying** [comment]
> I met the same problem, but I'm using vllm in a k8s pod. I tried to start a ray server manually at `localhost:6379` and pass it as `ray_address` to `ray.init` during vllm's init process, but still met the same problem:
> 
> https://github.com/vllm-project/vllm/blob/7d5a155e4aa258b0db1649bdcbf29477bf490ac2/vllm/engine/ray_utils.py#L67
> 
> Any ideas?
I also have tried it， but does't work

**Comment by weishengying** [comment]
> I met the same problem, but I'm using vllm in a k8s pod. I tried to start a ray server manually at `localhost:6379` and pass it as `ray_address` to `ray.init` during vllm's init process, but still met the same problem:
> 
> https://github.com/vllm-project/vllm/blob/7d5a155e4aa258b0db1649bdcbf29477bf490ac2/vllm/engine/ray_utils.py#L67
> 
> Any ideas?

Maybe I found the problem. I assign random values to the model weights instead of load downloaded weights from HF. After doing this，no error would happen.
```python
def get_model(model_config: ModelConfig) -> nn.Module:
    model_class = _get_model_architecture(model_config.hf_config)
    torch.set_default_dtype(model_config.dtype)

    # Create a model instance.
    # The weights will be initialized as empty tensors.
    model_config.use_dummy_weights = False
    model = model_class(model_config.hf_config)
    if model_config.use_dummy_weights:
        model = model.cuda()
        # NOTE(woosuk): For accurate performance evaluation, we assign
        # random values to the weights.
        initialize_dummy_weights(model)
```

**Comment by HermitSun** [comment]
I also tried this solution (issue https://github.com/vllm-project/vllm/issues/570), it seems also work for me🤔. 
Maybe something wrong during c10d elastic's DNS resolution process?

**Comment by weishengying** [comment]
> I also tried this solution (issue #570), it seems also work for me🤔. Maybe something wrong during c10d elastic's DNS resolution process?

Thanks a lot. But today I download the model file ahead of time form HF in local "gpt2" dir instead of default cache dir , and then everything is ok😄.

**Comment by HermitSun** [comment]
After trials and errors, I found a temporary solution. It seems also work for others. 

I mentioned it in another issue https://github.com/vllm-project/vllm/issues/645#issuecomment-1663880277 .
