### ISSUE TITLE
[Usage]: Using VLLM with Langchain for RAG purposes

### ISSUE THREAD

**Issue by sadrafh** [vllm-project/vllm#5572]
### Your current environment

Hello,

I am using VLLM to use Llama models for RAG purposes. However, I am constantly facing a runnable error. This is my VLLM model initialization:

llm_vllm = LLM(
    model="Llama-2-7b-chat-hf",
    device="cuda"
)
When I try to create a chain with:

chain = (
    {"context": retriever, "question": RunnablePassthrough()} | prompt | llm_vllm | StrOutputParser()
)
response = chain.invoke(user_question)

I get the following error: TypeError: Expected a Runnable, callable or dict. Instead got an unsupported type: <class 'vllm.entrypoints.llm.LLM'>

Similarly, if I use:

from langchain.chains.question_answering import load_qa_chain
chain = load_qa_chain(llm_vllm, chain_type="stuff")
I get an error: llm instance of Runnable expected.

Is there any solution for that?

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by youkaichao** [comment]
I think you need to ask the question in langchain community about how they integrate with vLLM.

**Comment by mgoin** [comment]
Looks like it was resolved in https://github.com/langchain-ai/langchain/discussions/22947, thanks for the issue!
