### ISSUE TITLE
EOS token being inserted into sequence. 

### ISSUE THREAD

**Issue by anujnayyar1** [vllm-project/vllm#558]
Hey guys, first thanks for VLLM, its insanely good!!

When ignore EOS token is used, it inserts it into the sentence and it is not ignored by the model. 
So although the model keeps generating the EOS token is no part of the sequence, which causes issues. 

I have found this when using this model:
When using https://huggingface.co/ehartford/Wizard-Vicuna-13B-Uncensored.

Usually when generating using HF. If a special token was encountered it would not be included in the generated text.
However here it appears `<s>` is placed into the generations often, causing degradation. 

Thank you!

**Comment by Peter-Devine** [comment]
+1

**Comment by wehos** [comment]
</s> seems to be a special token inserted into prompt of vicuna. Does this make sense?

> https://github.com/lm-sys/FastChat/blob/b0462aa6f028af2065a1691e83a563eccc43ea20/fastchat/conversation.py#L334C1-L347C2

**Comment by syskn** [comment]
From what I understand, the repetitive/potential degradation issue is not related to special tokens such as `<s></s>`. I modified vllm so that it never generates those special tokens like HF's bad_words_ids, but the issue persists.

**Comment by zhuohan123** [comment]
Is this already fixed by #418 or it's another issue?

**Comment by ehartford** [comment]
I am also getting </s>'s back from the vllm openAI API.

**Comment by ehartford** [comment]
This is going to happen for all fastchat/vicuna based models.

**Comment by anujnayyar1** [comment]
@zhuohan123, much thanks for checking in on this I believe this is another issue.

Something with the vllm sampling mechanism is causing model outputs to become much more repetitive.
The model will end up in a repetitive loop much quicker than when sampling using HF Transformers. 

This may be hard to asses for quantitatively, but I'd implore you to check out long context generations using HF Transformers vs VLLM and asses them qualitatively. I was using @ehartford models for tests, but found the issue with all LLama based models.

I originally thought it could be a tokenizer issue particularly the way vllm handled special tokens. However after investigating with a modded tokenizer the issue persisted. 

(As a patch to make VLLM more useable in the short term you could consider porting some more of the utils from HF Transformers in particular no_repeat_ngram_size: https://huggingface.co/transformers/v4.6.0/internal/generation_utils.html#transformers.NoRepeatNGramLogitsProcessor)

**Comment by kiamesdavies** [comment]
+1

**Comment by nvelingker** [comment]
+1
