### ISSUE TITLE
[Usage]: How to specify a GPU when i use vllm by 'python -m vllm.entrypoints.openai.api_server --served-model-name..'

### ISSUE THREAD

**Issue by GoogleAlphaZero** [vllm-project/vllm#5585]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by DarkLight1337** [comment]
You can use `CUDA_VISIBLE_DEVICES` environment variable to limit the GPUs that can be used by vLLM.

**Comment by GoogleAlphaZero** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
