### ISSUE TITLE
[Usage]: 'InternVLChatConfig' object has no attribute 'num_attention_heads'

### ISSUE THREAD

**Issue by wangdong1992** [vllm-project/vllm#5589]
### Your current environment

```text
The output of `python collect_env.py`
```
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.17

Python version: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L20
GPU 1: NVIDIA L20
GPU 2: NVIDIA L20
GPU 3: NVIDIA L20
GPU 4: NVIDIA L20
GPU 5: NVIDIA L20
GPU 6: NVIDIA L20
GPU 7: NVIDIA L20

Nvidia driver version: 535.154.05
cuDNN version: Probably one of the following:
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.7
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              143
型号名称：        Intel(R) Xeon(R) Gold 6462C
步进：              8
CPU MHz：             3900.018
CPU max MHz:           3900.0000
CPU min MHz:           800.0000
BogoMIPS：            6600.00
虚拟化：           VT-x
L1d 缓存：          48K
L1i 缓存：          32K
L2 缓存：           2048K
L3 缓存：           61440K
NUMA 节点0 CPU：    0-31,64-95
NUMA 节点1 CPU：    32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba rsb_ctxsw ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq cldemote movdiri movdir64b md_clear pconfig spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0+cu121
[pip3] torchaudio==2.3.0+cu121
[pip3] torchvision==0.18.0+cu121
[pip3] transformers==4.41.2
[pip3] transformers-stream-generator==0.0.5
[pip3] triton==2.3.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] torch                     2.3.0+cu121              pypi_0    pypi
[conda] torchaudio                2.3.0+cu121              pypi_0    pypi
[conda] torchvision               0.18.0+cu121             pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] transformers-stream-generator 0.0.5                    pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU1    PIX      X      SYS     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU2    SYS     SYS      X      PIX     SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU3    SYS     SYS     PIX      X      SYS     SYS     SYS     SYS     0-31,64-95      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      PIX     SYS     SYS     32-63,96-127    1               N/A
GPU5    SYS     SYS     SYS     SYS     PIX      X      SYS     SYS     32-63,96-127    1               N/A
GPU6    SYS     SYS     SYS     SYS     SYS     SYS      X      PIX     32-63,96-127    1               N/A
GPU7    SYS     SYS     SYS     SYS     SYS     SYS     PIX      X      32-63,96-127    1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

### How would you like to use vllm

I used the swift deploy command to deploy internvl-chat-v1_5, and an error was reported. The command is as follows:
CUDA_VISIBLE_DEVICES=6,7 swift deploy --model_type internvl-chat-v1_5 --model_id_or_path /data/pretrained_models/AI-ModelScope/InternVL-Chat-V1-5  --port 23333  --infer_backend vllm
The error message is:
![image](https://github.com/modelscope/swift/assets/20061204/f9f92c0c-3398-4211-a260-14bc2e4c63bf)
But I changed --infer_backend from vllm to pt and it can be deployed normally.
The following is my installation environment:
ms-swift=2.1.0
torch=2.3.0+cu121
vllm=0.5.0.post1
vllm-flash-attn=2.5.9
flash-attn=2.5.9.post1
Is it because vllm does not support internvl-chat-v1_5 when the above error message appears?

**Comment by mgoin** [comment]
@wangdong1992 does your model have a valid config.json in the folder you are using? vLLM needs to read the config.json to know how to construct the model. Here is an example from a HF checkpoint https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/main/config.json

**Comment by wangdong1992** [comment]
> @wangdong1992 does your model have a valid config.json in the folder you are using? vLLM needs to read the config.json to know how to construct the model. Here is an example from a HF checkpoint https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/main/config.json
I confirmed that there is a valid config.json in my model. Does vllm support internvl 1.5 now?

**Comment by lzhptr** [comment]
Does vllm support InternVL-Chat-V1-5 now?

**Comment by lzhptr** [comment]
I also reported the same error as you

**Comment by riyajatar37003** [comment]
'InternVLChatConfig' object has no attribute 'num_attention_heads' same error

**Comment by Elissa0723** [comment]
> 'InternVLChatConfig' object has no attribute 'num_attention_heads' same error

I had this same error with InternVL2

**Comment by oops343** [comment]
same error

**Comment by ruthy-wei** [comment]
you could check your vllm version, vllm>=0.5.4

**Comment by wangtianyiftd** [comment]
same error
<img width="1642" alt="image" src="https://github.com/user-attachments/assets/0ea1fdab-9b01-4a6c-9bd8-36f23ce4c0dc">

**Comment by DarkLight1337** [comment]
> same error <img alt="image" width="1642" src="https://private-user-images.githubusercontent.com/24503039/363850541-0ea1fdab-9b01-4a6c-9bd8-36f23ce4c0dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTkwMTgsIm5iZiI6MTcyNTY5ODcxOCwicGF0aCI6Ii8yNDUwMzAzOS8zNjM4NTA1NDEtMGVhMWZkYWItOWIwMS00YTZjLTliZDgtMzZmMjNjZTRjMGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA4NDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMjY5NmJjNTI5NDI3YzNlZGUxZTZkNzU5YTg4YjMxMTkwZmUxYTIzMDM2MzQ2ZjhkYjdkZjU1NmUzOWI2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NaWDQUAVTnUoI2O5AlY6StEjlqxlIsuQIIR-xNedokY">

See if it's fixed in vLLM 0.6.0. Which InternVL model are you using?

**Comment by JarvisFree** [comment]
![Image](https://github.com/user-attachments/assets/95f33563-aefb-4f8f-98f8-8be1a7aac34f)
modelscope==1.25.0
