### ISSUE TITLE
[Feature]: Add config of use_dummy_driver rather than default 'False'

### ISSUE THREAD

**Issue by DriverSong** [vllm-project/vllm#5598]
### 🚀 The feature, motivation and pitch

I find out two limitation, with the unmodifiable param ```use_dummy_driver``` of the method ```RayGPUExecutor._run_workers``` , when I use entrypoints ```LLM()``` to submit vllm jobs to the local ray cluster on ray head node.
```python
    def _run_workers(
        self,
        method: str,
        *args,
        async_run_remote_workers_only: bool = False,
        all_args: Optional[List[Tuple[Any, ...]]] = None,
        all_kwargs: Optional[List[Dict[str, Any]]] = None,
        use_dummy_driver: bool = False,
        max_concurrent_workers: Optional[int] = None,
        use_ray_compiled_dag: bool = False,
        **kwargs,
    ) -> Any:
```
The architecture of VLLM is shown as below. With the ```use_dummy_driver```  set to ```False``` by default, the local ```driver_worker``` is always called. It works fine with only one vllm job, while two issues come out with multiply vllm jobs submitted.
![vllm 进程关系图](https://github.com/vllm-project/vllm/assets/31926998/415e004e-a08b-41a3-aad3-5dc927f741be)
1. Limitation of the parallel vllm job count. The total vllm job count is limited by the gpu count of the node job submitted to, while the local ```driver_worker``` must occupy one gpu.
2. Limitation of vllm integration. In my own codes```__main__```, I set the ```CUDA_VISIBLE_DEVICES``` and init the distribution env to run the raw llm code. While the torch cuda device cannot be updated once it is loaded, the torch cuda device of ```driver_worker``` will not be changed with the update of ```CUDA_VISIBLE_DEVICES```, because it is in the same process of my customized```__main__``` process. I have to modify my own code if I want to  integrate vllm.
```python
        # Set environment variables for the driver and workers.
        all_args_to_update_environment_variables = [({
            "CUDA_VISIBLE_DEVICES":
            ",".join(map(str, node_gpus[node_id])),
            "VLLM_INSTANCE_ID":
            VLLM_INSTANCE_ID,
            "VLLM_TRACE_FUNCTION":
            str(envs.VLLM_TRACE_FUNCTION),
        }, ) for (node_id, _) in worker_node_and_gpu_ids]
        self._run_workers("update_environment_variables",
                          all_args=all_args_to_update_environment_variables)
```
To fix the two limitation, I add ```use_dummy_driver``` to the ```parallel_config``` to use the ```driver_dummy_worker``` rather than the local ```driver_worker```.
Here is the pr[#5599](https://github.com/vllm-project/vllm/pull/5599)
While the fix can remove the limitation mentioned above, I can not figure out the reason why vllm must use the local ```driver_worker```. In my opinion, it can reduce the cross-process communication between the rank-0 worker, while it makes vllm run in a limited distributed way.

### Additional context
the test of torch cuda visible device
![image](https://github.com/vllm-project/vllm/assets/31926998/371eb7e6-9cdc-45d7-b262-9cfd9961b4a8)
_No response_

**Comment by DriverSong** [comment]
Here is my pr to add ```use_dummy_dirver``` config
[#5599](https://github.com/vllm-project/vllm/pull/5599)

**Comment by youkaichao** [comment]
In the near future we would like to remove dummy worker. Stay tuned.

**Comment by DriverSong** [comment]
> In the near future we would like to remove dummy worker. Stay tuned.

I'm looking forward to that day. BTW, I'd like to apply this pr to my own code while it can avoid the local ```driver_worker``` without any other influence to the usage of vllm.

**Comment by DriverSong** [comment]
> In the near future we would like to remove dummy worker. Stay tuned.

I've read the latest roadmap and found out the target ```Provide non-ray option for single node inference```, is this the approach to remove dummy worker. Would you like to introduce more about the newest design of the ```ray_gpu_executor```, I am focus on the integration of vllm during my recent job and maybe I can do some contribution.
