### ISSUE TITLE
Unable to load the configuration of 'MPTForCausalLM

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#561]
When I run this, my error is OSError: Can't load the configuration of 'MPTForCausalLM even though I don't have a local directory.
         
`import torch
import transformers
from torch import cuda, bfloat16
name = 'mosaicml/mpt-7b'

config = transformers.AutoConfig.from_pretrained(name, trust_remote_code=True)
#config.attn_config['attn_impl'] = 'triton'

config.init_device = 'cuda:5' # For fast initialization directly on GPU!
torch.cuda.empty_cache()
model = transformers.AutoModelForCausalLM.from_pretrained(
  'mosaicml/mpt-7b',
  config=config,
  trust_remote_code=True,
    torch_dtype=bfloat16
)

from vllm import LLM
torch.cuda.empty_cache()
llm = LLM(model=model)`

`OSError: Can't load the configuration of 'MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 4096)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-31): 32 x MPTBlock(
        (norm_1): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=4096, out_features=12288, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (norm_2): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=4096, out_features=16384, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=16384, out_features=4096, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
)'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory 
with the same name. Otherwise, make sure 'MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 4096)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-31): 32 x MPTBlock(
        (norm_1): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=4096, out_features=12288, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (norm_2): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=4096, out_features=16384, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=16384, out_features=4096, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
)' is the correct path to a directory containing a config.json file`

If i run:

``from vllm import LLM
torch.cuda.empty_cache()
llm = LLM(model='mosaicml/mpt-7b',
          
         )``
         
I get :

`ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB 
GPU has compute capability 7.0.`

**Comment by HermitSun** [comment]
It seems that you're using V100. Since V100 does not support bfloat16 as the model's config, your code will break down. 

Maybe you can try to use float16 and pay attention to the potential loss of precision in the conversion between bf16 and fp16, or use float32 if memory is enough.

https://github.com/vllm-project/vllm/blob/7d5a155e4aa258b0db1649bdcbf29477bf490ac2/vllm/entrypoints/llm.py#L35-L39

**Comment by WoosukKwon** [comment]
Hi @nutmilk10, as @HermitSun explained, this is because your V100 does not support Bfloat16. Please add `dtype="float16"` in initializing `LLM`.

**Comment by nutmilk10** [comment]
> It seems that you're using V100. Since V100 does not support bfloat16 as the model's config, your code will break down.
> 
> Maybe you can try to use float16 and pay attention to the potential loss of precision in the conversion between bf16 and fp16, or use float32 if memory is enough.
> 
> https://github.com/vllm-project/vllm/blob/7d5a155e4aa258b0db1649bdcbf29477bf490ac2/vllm/entrypoints/llm.py#L35-L39


I implemented the suggested changes, but seeing this error:
HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' 
cannot start or end the name, max length is 96: 'MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 4096)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-31): 32 x MPTBlock(
        (norm_1): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=4096, out_features=12288, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (norm_2): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=4096, out_features=16384, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=16384, out_features=4096, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
)'.

During handling of the above exception, another exception occurred:
```
import torch
import transformers
from torch import cuda, bfloat16
from vllm import LLM

name = 'mosaicml/mpt-7b-instruct'

config = transformers.AutoConfig.from_pretrained(name, trust_remote_code=True)
torch.cuda.empty_cache()
config.init_device = 'cuda:6'  # For fast initialization directly on GPU!

model = transformers.AutoModelForCausalLM.from_pretrained(
    'mosaicml/mpt-7b-instruct',
    config=config,
    trust_remote_code=True,
    torch_dtype=torch.float16,
    device_map='auto'# Use torch.float32 instead of float32
)

torch.cuda.empty_cache()
llm = LLM(model=model)
```
