### ISSUE TITLE
[Installation]: 是否支持在windows操作系统上安装vllm

### ISSUE THREAD

**Issue by hiahia121** [vllm-project/vllm#5631]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
pip install -vvv vllm
```

**Comment by wuqingguo666** [comment]
求答案，我在Windows系统上安装vllm的Python包一直报错。请问vllm是否能在Windows系统上运行，还是必须在Linux系统上运行？报错截图如下。
![vllm安装报错](https://github.com/user-attachments/assets/f7f3cd43-e09b-4695-a7c2-49464060d724)

**Comment by 2914644189** [comment]
解决了吗 我也遇到了相同的问题

**Comment by Leeaoyin** [comment]
vlLM currently does not support Windows. Please use it inWSL and re-open
