### ISSUE TITLE
Unable to run baichuan13b on 2 GPUs

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#566]
Hi, I have 2 4090, each one of them can not fully load a 13b model, but vllm unable to automatically locate model into 2 GPUs, what else need I specific? (I have set a 0.8 GPU frac due to one GPU have a tiny process running consumes about  1GB mem)

**Comment by irasin** [comment]
you need to set tensor parallel size = 2 to run model on 2 GPUS

**Comment by lucasjinreal** [comment]
@irasin But baichuan13B seems have TP issue.

**Comment by irasin** [comment]
@lucasjinreal, I am not familar with baichuan13B, just curious about that is there any model structure difference between llama and baichuan ?

**Comment by lucasjinreal** [comment]
@irasin There still some issue reports baichuan13b have TP issue. You can find it out

**Comment by Mr-Nineteen** [comment]
`tp=2` not work

**Comment by zhuohan123** [comment]
Fixed by #598
