### ISSUE TITLE
量化后启动启动报错

### ISSUE THREAD

**Issue by lxb0425** [vllm-project/vllm#5660]
### Your current environment

lora微调了qwen2-72b-instruct，导出量化4位gptq，使用vllm单张卡启动成功，问答也ok，但是上下文长度太少
使用两张a100，启动报错如下
![image](https://github.com/vllm-project/vllm/assets/50564015/9165a2d9-3afc-47cd-a2b4-77c05d5b73ef)

其他配置如下
![image](https://github.com/vllm-project/vllm/assets/50564015/3e14268b-045f-4d70-bc21-0669069407fd)
![image](https://github.com/vllm-project/vllm/assets/50564015/7271e23c-e878-4058-ac8b-1ae1a646fd9a)
generation_config.json
![image](https://github.com/vllm-project/vllm/assets/50564015/0a79900c-4d74-437d-89b5-2cc7127903d4)

我应该怎么增加配置启动

**Comment by TZJ12** [comment]
在量化代码中将group_size改为64试试，确保中间大小被组大小整除
