### ISSUE TITLE
[Bug]: Qwen2-72B-Instruct-gptq-int4 Repetitive issues

### ISSUE THREAD

**Issue by Storm0921** [vllm-project/vllm#5663]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

Machine A800, VLLM 0.5.0, PROMPT=开始, output max tokens = 2048, Temperature sets 0.7

VLLM loads Qwen2-72b-InStruct-GPTQ-IT4, and uses the Benchmark script of VLLM to do concurrent testing. Whether it is a concurrent limit or 10 concurrency restrictions, the output will be repeated.
https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py
![image](https://github.com/vllm-project/vllm/assets/57557769/f3440a14-71a1-4b8c-b3e4-6a66aaba4aa8)

**Comment by tuanhe** [comment]
same issue
