### ISSUE TITLE
[Bug]: Option for preemption_mode uses underscore (_) instead of dash (-)

### ISSUE THREAD

**Issue by maharjun** [vllm-project/vllm#5667]
### Your current environment

Irrelevant, the error is easily seen in the code. It is seen in version 0.5.0.post1, in the file vllm.engine.arg_utils:576

### 🐛 Describe the bug

In the latest release (V0.5.0.post1), the CLI argument for `preemption_mode` parameter of EngineArgs is `--preemption_mode` which goes against the typical convention of replacing _ with - in command-line parameters. This won't affect any other code if fixed to `--preemption-mode`, because argparse converts any dashes to underscores in the namespace returned by `parser.parse_args()`. However the current situation causes problems when I want to convert an EngineArgs instance to set of command-line flags (say in order to launch a vllm server programmatically via subprocess)

**Comment by mgoin** [comment]
Thanks for reporting this @maharjun! I've posted a fix here https://github.com/vllm-project/vllm/pull/5688
