### ISSUE TITLE
[Installation]: pip install -e failed

### ISSUE THREAD

**Issue by chunniunai220ml** [vllm-project/vllm#5674]
### Your current environment

```text
The output of `python collect_env.py`
```

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] pytorch-triton-rocm==2.3.0
[pip3] sentence-transformers==3.0.1
[pip3] torch==2.3.0+rocm6.0
[pip3] torchaudio==2.3.0+rocm6.0
[pip3] torchvision==0.18.0+rocm6.0
[pip3] transformers==4.40.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] pytorch-triton-rocm       2.3.0                    pypi_0    pypi
[conda] sentence-transformers     3.0.1                    pypi_0    pypi
[conda] torch                     2.3.0+rocm6.0            pypi_0    pypi
[conda] torchaudio                2.3.0+rocm6.0            pypi_0    pypi
[conda] torchvision               0.18.0+rocm6.0           pypi_0    pypi
[conda] transformers              4.40.0                   pypi_0    pypi
ROCM Version: 6.0.32830-d62f6a171
Neuron SDK Version: N/A
vLLM Version: 0.5.0.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Enabled; Neuron: Disabled
GPU Topology:
Could not collect

### How you are installing vllm

hi,  i follow ur instruction build a docker :
docker build -f Dockerfile.rocm -t vllm-rocm . , successfully,
but i  got errors when i use vllm backend,  then i tried to modify some vllm codes. soi have to reinstall in a eidtable mode,  but failed.
 
when i tried to install form source:
git clone https://github.com/vllm-project/vllm.git
cd vllm
# export VLLM_INSTALL_PUNICA_KERNELS=1 # optionally build for multi-LoRA capability
pip install -e . 

error as follow:
![image](https://github.com/vllm-project/vllm/assets/17668109/59d6136a-dd56-4a37-8982-7dc7799ab5c6)

i set .bashrc as follow:

export ROCM_HOME='/opt/rocm-6.0.0/'
export PATH="/opt/rocm-6.0.0/bin/:$PATH"
export PATH="/opt/rocm-6.0.0/lib/:$PATH"

**Comment by youkaichao** [comment]
cc @hongxiayang

**Comment by hongxiayang** [comment]
> hi, i follow ur instruction build a docker :
docker build -f Dockerfile.rocm -t vllm-rocm . , successfully,
but i got errors when i use vllm backend, then i tried to modify some vllm codes. soi have to reinstall in a eidtable mode, but failed.
when i tried to install form source:
git clone https://github.com/vllm-project/vllm.git
cd vllm

Would like to know the exact steps for your issue. Not sure how you did install from source, is it inside the container or outside the container? 

The error in your screen shot is "Permission denied". is there any permission issue?

**Comment by chunniunai220ml** [comment]
![image](https://github.com/vllm-project/vllm/assets/17668109/65267650-8025-4c57-8d1f-b5958f5d17f3)
i  think it not only cuased by permisssion denied,  pls see the above compile error

**Comment by RanchiZhao** [comment]
same issue when i do pip install .

**Comment by hongxiayang** [comment]
sorry, can you list step by step what you did so that I can reproduce? I can not help if I don't know how to reproduce.

**Comment by chunniunai220ml** [comment]
i have a rocm6.1 docker image,  and i have to pip install vllm from source,  folllowing installation guides:
`
cd vllm
pip install -U -r requirements-rocm.txt
pip install -e .
`
then got error as i reported screen shot
here is my rocm info:
Package: rocm-libs
Version: 6.1.2.60102-119~20.04
Priority: optional
Section: devel
Maintainer: ROCm Dev Support <rocm-dev.support@amd.com>
Installed-Size: 13.3 kB

and i have add 
`
export ROCM_HOME=/opt/rocm
export PATH="${ROCM_HOME}/bin:$PATH"
` in ~/.bashrc ,  that's all details

**Comment by hongxiayang** [comment]
what is your rocm6.1 image name?

**Comment by chunniunai220ml** [comment]
rocm 6.0 docker(the first question) build from docker build -f Dockerfile.rocm -t vllm-rocm . , as https://docs.vllm.ai/en/stable/getting_started/amd-installation.html instruction
rocm6.1 is a private image, i can not give you docker source, 
but both them got same error, no rocm runtime found in /opt/rocm

**Comment by hongxiayang** [comment]
There is a comment in the [here](https://github.com/vllm-project/vllm/blob/2ce5d6688bae64e467640b05e73af2888e93afcf/docs/source/getting_started/amd-installation.rst?plain=1#L129) saying `pip install` does not work for amd currently when building vllm. Have you tried to use `python setup.py install` or `python setup.py develop`?

**Comment by chunniunai220ml** [comment]
> There is a comment in the [here](https://github.com/vllm-project/vllm/blob/2ce5d6688bae64e467640b05e73af2888e93afcf/docs/source/getting_started/amd-installation.rst?plain=1#L129) saying `pip install` does not work for amd currently when building vllm. Have you tried to use `python setup.py install` or `python setup.py develop`?

yes,  pip install doesn't work for some new models, like this issue https://github.com/vllm-project/vllm/issues/5454,  author advise  pip from source,  and i found that, if pip install vllm==0.5.0,  it seems based on nvidia default. whaterver, i just want to know how can i build vllm from source for some codes change

**Comment by hongxiayang** [comment]
please run `python setup.py install` instead of `pip install .` to build from source.

Say, you are already inside rocm-vllm container (which you mentioned earlier), you make some changes in /vllm-workspace, you can run `python setup.py install`, which will do build vllm from source. Alternatively for easy experiments, you can change python code directly in vllm installation directory by showing where it is installed using command like "pip show vllm" without needing to run `python setup.py install`.

**Comment by AndyZZt** [comment]
Hi @chunniunai220ml I wonder how lang it took you to  complete "Installing build dependencies ... |", because I have been stuck 
 at this step for a long time and there is no sign of improving.
