### ISSUE TITLE
[Usage]:  Use quantization=gptq_marlin for faster inference

### ISSUE THREAD

**Issue by thiner** [vllm-project/vllm#5677]
### Your current environment

Docker image tag: **vllm/vllm-openai:v0.5.0.post1**

### How would you like to use vllm

In fact, I am not sure whether this is a bug or a usage inquiry. 
When vLLM startup, I can see a line of log says that:
```text
 INFO 06-19 06:04:52 gptq_marlin.py:137] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
```
So, I modified my startup command, to specify the `quantization=gptq_marlin` argument. However, vLLM raised an error:
```text
ValueError: Quantization method specified in the model config (gptq) does not match the quantization method specified in the `quantization` argument (gptq_marlin).
```

Am I set the argument correctly?

**Comment by w013nad** [comment]
Try just not setting a quantization argument. It detects the quantization automatically and converts the kernels to marlin on the fly.

**Comment by mgoin** [comment]
@thiner Simply don't set the `quantization` argument. If vLLM can use the faster gptq_marlin kernels to run your gptq model, it will. Otherwise it will fall back to the slower but more general gptq kernels.

**Comment by linpan** [comment]
version : 0.5.3.post1
![image](https://github.com/user-attachments/assets/e469be70-9404-4130-808b-822d86f13537)

**Comment by mgoin** [comment]
@linpan As I said above, simply don't set the `quantization` argument
