### ISSUE TITLE
[Usage]: TimeoutError() 

### ISSUE THREAD

**Issue by ZZhangxian** [vllm-project/vllm#5697]
### Your current environment

[Bug]: INFO 06-19 11:23:59 metrics.py:341] Avg prompt throughput: 3526.1 tokens/s, Avg generation throughput: 115.2 tokens/s, Running: 8 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%. ERROR 06-19 11:25:01 async_llm_engine.py:535] Engine iteration timed out. This should never happen! ERROR 06-19 11:25:01 async_llm_engine.py:52] Engine background task failed ERROR 06-19 11:25:01 async_llm_engine.py:52] Traceback (most recent call last): ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step ERROR 06-19 11:25:01 async_llm_engine.py:52]     request_outputs = await self.engine.step_async() ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async ERROR 06-19 11:25:01 async_llm_engine.py:52]     output = await self.model_executor.execute_model_async( ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async ERROR 06-19 11:25:01 async_llm_engine.py:52]     return await self._driver_execute_model_async(execute_model_req) ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async ERROR 06-19 11:25:01 async_llm_engine.py:52]     return await self.driver_exec_model(execute_model_req) ERROR 06-19 11:25:01 async_llm_engine.py:52] asyncio.exceptions.CancelledError ERROR 06-19 11:25:01 async_llm_engine.py:52]  ERROR 06-19 11:25:01 async_llm_engine.py:52] During handling of the above exception, another exception occurred: ERROR 06-19 11:25:01 async_llm_engine.py:52]  ERROR 06-19 11:25:01 async_llm_engine.py:52] Traceback (most recent call last): ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 456, in wait_for ERROR 06-19 11:25:01 async_llm_engine.py:52]     return fut.result() ERROR 06-19 11:25:01 async_llm_engine.py:52] asyncio.exceptions.CancelledError ERROR 06-19 11:25:01 async_llm_engine.py:52]  ERROR 06-19 11:25:01 async_llm_engine.py:52] The above exception was the direct cause of the following exception: ERROR 06-19 11:25:01 async_llm_engine.py:52]  ERROR 06-19 11:25:01 async_llm_engine.py:52] Traceback (most recent call last): ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion ERROR 06-19 11:25:01 async_llm_engine.py:52]     return_value = task.result() ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop ERROR 06-19 11:25:01 async_llm_engine.py:52]     has_requests_in_progress = await asyncio.wait_for( ERROR 06-19 11:25:01 async_llm_engine.py:52]   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 458, in wait_for ERROR 06-19 11:25:01 async_llm_engine.py:52]     raise exceptions.TimeoutError() from exc ERROR 06-19 11:25:01 async_llm_engine.py:52] asyncio.exceptions.TimeoutError ERROR:asyncio:Exception in callback functools.partial(<function _log_task_completion at 0x7fb5d05053f0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7fb5a44513f0>>) handle: <Handle functools.partial(<function _log_task_completion at 0x7fb5d05053f0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7fb5a44513f0>>)> Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step     request_outputs = await self.engine.step_async()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async     output = await self.model_executor.execute_model_async(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async     return await self._driver_execute_model_async(execute_model_req)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async     return await self.driver_exec_model(execute_model_req) asyncio.exceptions.CancelledError  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 456, in wait_for     return fut.result() asyncio.exceptions.CancelledError  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion     return_value = task.result()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop     has_requests_in_progress = await asyncio.wait_for(   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 458, in wait_for     raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 54, in _log_task_completion     raise AsyncEngineDeadError( vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for theactual cause. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-7347d49f836c40a6b8d00fff45f5998d. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-10f955208ce04051aeb80f37a1b930b4. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-66dbd15ae2574c24ad701af023c451e6. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-b393b2978c674af0bd617c48709ee3d3. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-4666cd377e0544e9b19a093bd59ab505. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-b4c5abee3090453f8aa015cec00917e4. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-f1ac8bf42835483cbe4f820bcc1095bb. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-d2d847ea0c9644fabf17089d6f26fb98. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-a6a36d4e4a3c4d8ca75817e4cebc0232. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-3b5bc34c0bde403e8fe6c23b7621ab1d. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-66004d5f6cd64fb5a65901255c977097. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-6ed49726f97041f7a2e2372cb8be99a0. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-429786b3bbb340109fae7ff4d242e739. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-27955bbcb5a642659d36d172a26f5f2f. INFO 06-19 11:25:01 async_llm_engine.py:167] Aborted request cmpl-b2947147a78b40ceaedb9559efa2d1b7. ERROR:    Exception in ASGI application Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step     request_outputs = await self.engine.step_async()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async     output = await self.model_executor.execute_model_async(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async     return await self._driver_execute_model_async(execute_model_req)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async     return await self.driver_exec_model(execute_model_req) asyncio.exceptions.CancelledError  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 456, in wait_for     return fut.result() asyncio.exceptions.CancelledError  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi     result = await app(  # type: ignore[func-returns-value]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__     return await self.app(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__     await super().__call__(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__     await self.middleware_stack(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__     raise exc   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__     await self.app(scope, receive, _send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app     raise exc   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app     await app(scope, receive, sender)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__     await self.middleware_stack(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 776, in app     await route.handle(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle     await self.app(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 77, in app     await wrap_app_handling_exceptions(app, request)(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app     raise exc   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app     await app(scope, receive, sender)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/routing.py", line 75, in app     await response(scope, receive, send)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 258, in __call__     async with anyio.create_task_group() as task_group:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__     raise exceptions[0]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 261, in wrap     await func()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/starlette/responses.py", line 250, in stream_response     async for chunk in self.body_iterator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/serving_chat.py", line 311, in chat_completion_stream_generator     async for res in result_generator:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in generate     async for output in self._process_request(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 780, in _process_request     raise e   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 776, in _process_request     async for request_output in stream:   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 89, in __anext__     raise result   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 42, in _log_task_completion     return_value = task.result()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 532, in run_engine_loop     has_requests_in_progress = await asyncio.wait_for(   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 458, in wait_for     raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError ERROR:    Exception in ASGI application Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 506, in engine_step     request_outputs = await self.engine.step_async()   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 235, in step_async     output = await self.model_executor.execute_model_async(   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 166, in execute_model_async     return await self._driver_execute_model_async(execute_model_req)   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 149, in _driver_execute_model_async     return await self.driver_exec_model(execute_model_req) asyncio.exceptions.CancelledError  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/root/anaconda3/envs/vllm/lib/python3.10/asyncio/tasks.py", line 456, in wait_for     return fut.result() asyncio.exceptions.CancelledError

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by bltcn** [comment]
请问你是怎么解决这个问题的？
