### ISSUE TITLE
[Llama-2-13b-chat-hf] IPv6 Network Address Retrieval Error on 4 V100s 16GB

### ISSUE THREAD

**Issue by sksq96** [vllm-project/vllm#570]
Hello,

I'm encountering an issue while running the following code:

```python
from vllm import LLM, SamplingParams
llm = LLM(model="meta-llama/Llama-2-13b-chat-hf", tensor_parallel_size=2)
```

The hardware I'm using is 4 V100s with 16GB each. The error I'm receiving is as follows:

```
(Worker pid=22514) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 16516) cannot be retrieved (gai error: -2 - Name or service not known).
(Worker pid=22513) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 16516) cannot be retrieved (gai error: -2 - Name or service not known). [repeated 10x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=22513) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 16516) cannot be retrieved (gai error: -2 - Name or service not known). [repeated 10x across cluster]
```

Any help or guidance on how to resolve this issue would be greatly appreciated.

Thank you

**Comment by efraisse** [comment]
@sksq96 Here is what worked for me, I am also running the same model as you are on 4 A10 GPUS (I'm assuming you are also using an amazon instance given you are using 4 V100s):
1. type "wget -O - -q https://checkip.amazonaws.com" or "curl -s https://icanhazip.com" into your command line
2. copy the ip address that it gives you
3. in your Jupyter notebook: at the top of the cell where you want to run your code add these two lines: `!export MASTER_ADDR='paste-ip-address-here' !export MASTER_PORT="choose-port-here"` I don't think the master_port needs to be anything specific just choose any port.
4. Run the code, if you still get the same error, refresh your kernel and wait around 5 minutes and rerun the cell and it should work.

**Comment by ahernandezSecurityScorecard** [comment]
but do you know what this is refering to? because is not working for me

**Comment by efraisse** [comment]
> but do you know what this is refering to? because is not working for me

I am not entirely certain, I checked out this thread: https://github.com/pytorch/pytorch/issues/74824 and someone said "For some reason, MASTER_ADDR is not being set correctly under elastic/agent/server/api.py, The IP address is being encoded but not decoded? Looping in Pytorch R2P team to investigate" so I assumed that that was the underlying issue. I don't think my solution is probably a good one either it was just something that worked for me so I hoped the ugly workaround could potentially work for others as well.

**Comment by imoneoi** [comment]
@sksq96 I had the same problem on 4 GPUs with exactly the same error message. Run on a single GPU and disabling Ray can temporarily solve it.

**Comment by wolegechu** [comment]
There was a non-deterministic bug in the old implementation of the ﻿initialize_cluster method, but **it has been fixed**. Simply **build and use the latest version from the main branch**.

**Comment by ahernandezSecurityScorecard** [comment]
I did run into a situation where I had the "Name or Service not know error" or this [error](https://github.com/vllm-project/vllm/issues/406) 
If added this before (which solves the second error) when I don't get the "Name or Service not know error", it works!
export NCCL_IGNORE_DISABLED_P2P=1

**Comment by xxm1668** [comment]
(Worker pid=2693738) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 12693) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).  add export NCCL_IGNORE_DISABLED_P2P=1，it does not work ! I need help

**Comment by Laych7** [comment]
When I first ran it, the graphics memory was occupied, but it quickly cleared the launch process automatically. The subsequent runs followed the same IPV6 error message：
`import os
from vllm import LLM, SamplingParams

os.environ["NCCL_IGNORE_DISABLED_P2P"] = "1"
llm = LLM(model="model/Llama-2-13b-chat-hf", tensor_parallel_size=2, tokenizer="hf-internal-testing/llama-tokenizer")`
Error：
`(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 12x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]`

**Comment by Laych7** [comment]
When I first ran it, the graphics memory was occupied, but it quickly cleared the launch process automatically. The subsequent runs followed the same IPV6 error message：
```import os
from vllm import LLM, SamplingParams

os.environ["NCCL_IGNORE_DISABLED_P2P"] = "1"
llm = LLM(model="model/Llama-2-13b-chat-hf", tensor_parallel_size=2, tokenizer="hf-internal-testing/llama-tokenizer")
```
Error：
```
(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 12x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=2842646) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 15051) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
```
And not only will the llama model fail, but everything else will also fail

**Comment by xxm1668** [comment]
export NCCL_IGNORE_DISABLED_P2P=1；歇一会就好了，我的就是这样

**Comment by Laych7** [comment]
ok 我也可以了

**Comment by BaileyWei** [comment]
thanks a lot!!!! it works finally!!!!!!

> I did run into a situation where I had the "Name or Service not know error" or this [error](https://github.com/vllm-project/vllm/issues/406) If added this before (which solves the second error) when I don't get the "Name or Service not know error", it works! export NCCL_IGNORE_DISABLED_P2P=1

**Comment by imoneoi** [comment]
> thanks a lot!!!! it works finally!!!!!!
> 
> > I did run into a situation where I had the "Name or Service not know error" or this [error](https://github.com/vllm-project/vllm/issues/406) If added this before (which solves the second error) when I don't get the "Name or Service not know error", it works! export NCCL_IGNORE_DISABLED_P2P=1

Had the same issue. Also solved by  export NCCL_IGNORE_DISABLED_P2P=1`

**Comment by zhuohan123** [comment]
Please refer to #645 for the fix.

**Comment by SuperBruceJia** [comment]
`export NCCL_IGNORE_DISABLED_P2P=1` didn't work for me. 

Besides, to add the `127.0.0.1 __internal_head__`, I don't have sudo access to the `/etc/hosts` file, unfortunately. 

Is there any way to solve the problem? 

Thank you very much in advance!
