### ISSUE TITLE
max_tokens must be at least 1, got -160 

### ISSUE THREAD

**Issue by njhouse365** [vllm-project/vllm#5700]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
pip install -vvv vllm
```

**Comment by DarkLight1337** [comment]
Please provide more information regarding your problem, including your current environment and installation (read the instructions), and also how you ran vLLM.

**Comment by DarkLight1337** [comment]
Closing as stale. It may be reopened if you provide more information.
