### ISSUE TITLE
[Misc]: 我在使用vllm启动的openai api在进行对话时出现这样的情况

### ISSUE THREAD

**Issue by ArboterJams** [vllm-project/vllm#5707]
![20240621-092752](https://github.com/vllm-project/vllm/assets/29626411/1a1eded9-9bf8-4e30-92d4-8751f9e5bce8)
在使用流式生成时，大模型的回答会出现自问自答的情况。

**Comment by ArboterJams** [comment]
![20240620-191334](https://github.com/vllm-project/vllm/assets/29626411/94b7d004-d8b1-4f69-9448-10ee7909f2eb)

**Comment by momomobinx** [comment]
这个是用的什么模型啊

**Comment by BiboyQG** [comment]
It seems that you didn't add stop word ids to the API. Try it.
