### ISSUE TITLE
[New Model]: Support Nemotron-4-340B

### ISSUE THREAD

**Issue by dskhudia** [vllm-project/vllm#5722]
### 🚀 The feature, motivation and pitch

Benchmarks on the Nvidia's latest nemotron model look great. Is there plan or already going work to support it? 

### Additional context

https://huggingface.co/nvidia/Nemotron-4-340B-Instruct

**Comment by mgoin** [comment]
Once there is support in HF transformers, then it should be relatively straightforward to port into vLLM. It seems there aren't any efforts from searching the transformers issues/PRs

**Comment by riverind** [comment]
attention

**Comment by natolambert** [comment]
I started a paid bounty to close these issues. Already over $200 of support.
https://x.com/natolambert/status/1814735390877884823
