### ISSUE TITLE
[Usage]: qwen2-1.5b-gptq-in4 single gpu multiprocessing deployment fail

### ISSUE THREAD

**Issue by xdhhh** [vllm-project/vllm#5726]
I try to deploy qwen2-1.5b-gptq-in4 model on one A100-80G gpu with multiprocessing, the number of process is 2, but always failed when inferencing, reporting OOM. 1.5b-gptq-int4 model should not use such amount of gpu memory. Any suggestions? Here is my argument:

LLM(model="./qwen2_1.5b_int4", trust_remote_code=True, quantization='gptq', gpu_memory_utilization=0.5, max_model_len=512, enforce_eager=True)

**Comment by LetheRiver0** [comment]
similar issue with you, looking forward to correct usage
