### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by shushengyuan** [vllm-project/vllm#573]
Why is there no data to compare with FastTransformer? Are there any considerations?

**Comment by WoosukKwon** [comment]
Hi @shushengyuan, you can refer to this figure from [AnyScale's blog post](https://www.anyscale.com/blog/continuous-batching-llm-inference)

![](https://images.ctfassets.net/xjan103pcp94/46OIG2WmA2j0SBfcG5fdq7/3bcdebf8014730a1a592a18f023cfdcc/cb_08_throughput_graph.png)
