### ISSUE TITLE
api_server.py: error: unrecognized arguments: --tool-use-prompt-template --enable-api-tools --enable-auto-tool-choice

### ISSUE THREAD

**Issue by lk1983823** [vllm-project/vllm#5730]
My vllm version is 0.5.0 post1. I want to make qwen2:7b-instruct model to have functional calling enabled. So following the issue https://github.com/vllm-project/vllm/pull/5649 here, I run the command 

`python -m vllm.entrypoints.openai.api_server --model /home/asus/autodl-tmp/qwen/Qwen2-7B-Instruct --tool-use-prompt-template  /home/asus/autodl-tmp/examples/chatml.jinja --enable-api-tools --enable-auto-tool-choice`

But it shows  api_server.py: error: unrecognized arguments: --tool-use-prompt-template --enable-api-tools --enable-auto-tool-choice

![image](https://github.com/vllm-project/vllm/assets/20237650/60c5dfc6-e356-48d7-b409-054587d4df4c)

**Comment by K-Mistele** [comment]
#5649 is a **draft** of a pull request. It is a work-in-progress, and has not been merged into vLLM's codebase. Any capabilities and features present in that branch, whether they are a work-in-progress or completed, will not be available in a vLLM release unless/until the pull request is approved and merged from the Constellate AI fork into the vLLM project's codebase.

**Comment by K-Mistele** [comment]
@lk1983823 please feel free to close this issue :)
