### ISSUE TITLE
[Bug]: which torchvision version required

### ISSUE THREAD

**Issue by tusharraskar** [vllm-project/vllm#5736]
/vllm_2$ python examples/phi3v_example.py
WARNING 06-21 14:53:06 ray_utils.py:46] Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For multi-node inference, please install Ray with `pip install ray`.
/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO 06-21 14:53:08 llm_engine.py:164] Initializing an LLM engine (v0.5.0.post1) with config: model='microsoft/Phi-3-vision-128k-instruct', speculative_config=None, tokenizer='microsoft/Phi-3-vision-128k-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8128, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=microsoft/Phi-3-vision-128k-instruct)
WARNING 06-21 14:53:10 cpu_executor.py:116] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 06-21 14:53:10 cpu_executor.py:143] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 06-21 14:53:10 selector.py:113] Cannot use _Backend.FLASH_ATTN backend on CPU.
INFO 06-21 14:53:10 selector.py:64] Using Torch SDPA backend.
INFO 06-21 14:53:11 selector.py:113] Cannot use _Backend.FLASH_ATTN backend on CPU.
INFO 06-21 14:53:11 selector.py:64] Using Torch SDPA backend.
INFO 06-21 14:53:12 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 06-21 14:53:14 cpu_executor.py:72] # CPU blocks: 682
Processed prompts:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/examples/phi3v_example.py", line 58, in <module>
[rank0]:     run_phi3v()
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/examples/phi3v_example.py", line 31, in run_phi3v
[rank0]:     outputs = llm.generate(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/utils.py", line 727, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 304, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 556, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 806, in step
[rank0]:     output = self.model_executor.execute_model(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/executor/cpu_executor.py", line 78, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_worker.py", line 302, in execute_model
[rank0]:     output = self.model_runner.execute_model(seq_group_metadata_list,
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 337, in execute_model
[rank0]:     ) = self.prepare_input_tensors(seq_group_metadata_list)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 287, in prepare_input_tensors
[rank0]:     ) = self._prepare_prompt(seq_group_metadata_list)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 132, in _prepare_prompt
[rank0]:     mm_kwargs = self.multi_modal_input_processor(mm_data)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/registry.py", line 142, in process_input
[rank0]:     .process_input(data, model_config, vlm_config)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/base.py", line 126, in process_input
[rank0]:     return processor(data, model_config, vlm_config)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/image.py", line 109, in _default_input_processor
[rank0]:     image_processor = self._get_hf_image_processor(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/image.py", line 97, in _get_hf_image_processor
[rank0]:     return cached_get_image_processor(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/transformers_utils/image_processor.py", line 21, in get_image_processor
[rank0]:     processor: BaseImageProcessor = AutoImageProcessor.from_pretrained(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py", line 398, in from_pretrained
[rank0]:     image_processor_class = get_class_from_dynamic_module(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 501, in get_class_from_dynamic_module
[rank0]:     final_module = get_cached_module_file(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 326, in get_cached_module_file
[rank0]:     modules_needed = check_imports(resolved_module_file)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 181, in check_imports
[rank0]:     raise ImportError(
[rank0]: ImportError: This modeling file requires the following packages that were not found in your environment: torchvision. Run `pip install torchvision`
Processed prompts:   0%|                                                                                    | 0/1 [00:01<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

**Comment by tusharraskar** [comment]
I am using cpu

**Comment by DarkLight1337** [comment]
The latest version should be fine. By the way, Phi-3V is not supported on CPU yet.

**Comment by tusharraskar** [comment]
for cpu required torch == 2.3.1+cpu and torchvision==0.18.1  required torch == 2.3.1

torchvision==0.18.1 not working

**Comment by DarkLight1337** [comment]
@Isotr0py can you provide more insight on this?

**Comment by Isotr0py** [comment]
@tusharraskar `torchvision==0.18.1` should work fine. Maybe you can try to reinstall `torch` and `torchvision`:
```bash
pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
```

**Comment by DarkLight1337** [comment]
The CI failure [here](https://buildkite.com/vllm/ci-aws/builds/2193#019039d9-928a-4056-b293-9ae18af44dc6) may be related to this issue. It seems that `torchvision` cannot be installed correctly alongside PyTorch for CPU.

**Comment by Isotr0py** [comment]
@DarkLight1337 We only added `torchvision` to `requirements-test.txt` and `.buildkite/run-cpu-test.sh` didn't install package from it.  So `torchvision` wouldn't be installed by default in intel-test.

**Comment by DarkLight1337** [comment]
> @DarkLight1337 We only added `torchvision` to `requirements-test.txt` and `.buildkite/run-cpu-test.sh` didn't install package from it. So `torchvision` wouldn't be installed by default in intel-test.

Hmm ok, let me update that then.

**Comment by tusharraskar** [comment]
> @Isotr0py can you provide more insight on this?

RuntimeError: operator torchvision::nms does not exist


(vll_venv) sapidblue@sapidblue-Latitude-3410:~/SapidBlue/invoice_data_extraction/vllm_2$ pip show torch torchvision
Name: torch
Version: 2.3.1+cpu
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchvision, vllm
---
Name: torchvision
Version: 0.18.1
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages
Requires: numpy, pillow, torch
Required-by: 
(vll_venv) sapidblue@sapidblue-Latitude-3410:~/SapidBlue/invoice_data_extraction/vllm_2$ python examples/phi3v_example.py 
WARNING 06-21 20:34:44 ray_utils.py:46] Failed to import Ray with ModuleNotFoundError("No module named 'ray'"). For multi-node inference, please install Ray with `pip install ray`.
/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO 06-21 20:34:45 llm_engine.py:164] Initializing an LLM engine (v0.5.0.post1) with config: model='microsoft/Phi-3-vision-128k-instruct', speculative_config=None, tokenizer='microsoft/Phi-3-vision-128k-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8128, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cpu, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=microsoft/Phi-3-vision-128k-instruct)
WARNING 06-21 20:34:46 cpu_executor.py:116] CUDA graph is not supported on CPU, fallback to the eager mode.
WARNING 06-21 20:34:46 cpu_executor.py:143] Environment variable VLLM_CPU_KVCACHE_SPACE (GB) for CPU backend is not set, using 4 by default.
INFO 06-21 20:34:46 selector.py:113] Cannot use _Backend.FLASH_ATTN backend on CPU.
INFO 06-21 20:34:46 selector.py:64] Using Torch SDPA backend.
INFO 06-21 20:34:46 selector.py:113] Cannot use _Backend.FLASH_ATTN backend on CPU.
INFO 06-21 20:34:46 selector.py:64] Using Torch SDPA backend.
INFO 06-21 20:34:48 weight_utils.py:218] Using model weights format ['*.safetensors']
INFO 06-21 20:34:53 cpu_executor.py:72] # CPU blocks: 682
Processed prompts:   0%|                                         | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/examples/phi3v_example.py", line 58, in <module>
[rank0]:     run_phi3v()
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/examples/phi3v_example.py", line 31, in run_phi3v
[rank0]:     outputs = llm.generate(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/utils.py", line 727, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 304, in generate
[rank0]:     outputs = self._run_engine(use_tqdm=use_tqdm)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 556, in _run_engine
[rank0]:     step_outputs = self.llm_engine.step()
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 806, in step
[rank0]:     output = self.model_executor.execute_model(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/executor/cpu_executor.py", line 78, in execute_model
[rank0]:     output = self.driver_worker.execute_model(execute_model_req)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_worker.py", line 302, in execute_model
[rank0]:     output = self.model_runner.execute_model(seq_group_metadata_list,
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 337, in execute_model
[rank0]:     ) = self.prepare_input_tensors(seq_group_metadata_list)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 287, in prepare_input_tensors
[rank0]:     ) = self._prepare_prompt(seq_group_metadata_list)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/worker/cpu_model_runner.py", line 132, in _prepare_prompt
[rank0]:     mm_kwargs = self.multi_modal_input_processor(mm_data)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/registry.py", line 142, in process_input
[rank0]:     .process_input(data, model_config, vlm_config)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/base.py", line 126, in process_input
[rank0]:     return processor(data, model_config, vlm_config)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/image.py", line 109, in _default_input_processor
[rank0]:     image_processor = self._get_hf_image_processor(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/multimodal/image.py", line 97, in _get_hf_image_processor
[rank0]:     return cached_get_image_processor(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/vllm-0.5.0.post1+cpu-py3.10-linux-x86_64.egg/vllm/transformers_utils/image_processor.py", line 21, in get_image_processor
[rank0]:     processor: BaseImageProcessor = AutoImageProcessor.from_pretrained(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py", line 398, in from_pretrained
[rank0]:     image_processor_class = get_class_from_dynamic_module(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 501, in get_class_from_dynamic_module
[rank0]:     final_module = get_cached_module_file(
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 326, in get_cached_module_file
[rank0]:     modules_needed = check_imports(resolved_module_file)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 176, in check_imports
[rank0]:     importlib.import_module(imp)
[rank0]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[rank0]:     return _bootstrap._gcd_import(name[level:], package, level)
[rank0]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[rank0]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[rank0]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[rank0]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[rank0]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[rank0]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torchvision/__init__.py", line 6, in <module>
[rank0]:     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
[rank0]:     def meta_nms(dets, scores, iou_threshold):
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torch/library.py", line 467, in inner
[rank0]:     handle = entry.abstract_impl.register(func_to_register, source)
[rank0]:   File "/home/sapidblue/SapidBlue/invoice_data_extraction/vllm_2/vll_venv/lib/python3.10/site-packages/torch/_library/abstract_impl.py", line 30, in register
[rank0]:     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
[rank0]: RuntimeError: operator torchvision::nms does not exist
Processed prompts:   0%|                                         | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
(vll_venv) sapidblue@sapidblue-Latitude-3410:~/SapidBlue/invoice_data_extraction/vllm_2$

**Comment by tusharraskar** [comment]
> @tusharraskar `torchvision==0.18.1` should work fine. Maybe you can try to reinstall `torch` and `torchvision`:
> 
> ```shell
> pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
> ```


Now it's working, but the model is using only one core, which makes the process slow. I also added a screenshot.

![Screenshot from 2024-06-21 20-46-29](https://github.com/vllm-project/vllm/assets/117747869/0a763ce9-338c-4a6a-a2ad-d231eeb0b212)

**Comment by DarkLight1337** [comment]
> > @tusharraskar `torchvision==0.18.1` should work fine. Maybe you can try to reinstall `torch` and `torchvision`:
> > ```shell
> > pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
> > ```
> 
> Now it's working, but the model is using only one core, which makes the process slow. I also added a screenshot

> The latest version should be fine. By the way, Phi-3V is not well-supported on CPU yet.

That is exactly what I meant by this.

**Comment by DarkLight1337** [comment]
You can check #4194 for the progress on CPU support.

**Comment by Isotr0py** [comment]
@tusharraskar I think adding `dtype="bfloat16"` or `dtype="float"` to `LLM` should be able to use multi-core.
