### ISSUE TITLE
[Usage]: has vllm supported encoder-only model such as bge-m3?

### ISSUE THREAD

**Issue by chenchunhui97** [vllm-project/vllm#5737]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I saw an issue here: https://github.com/vllm-project/vllm/pull/3187/files
![image](https://github.com/vllm-project/vllm/assets/167943259/93d820cf-678e-480c-89a5-f858b360092e)

I want to know has vllm supported embedding model in RAG? such as BAAI/bge-m3. and how to use it?

**Comment by Ludoko91** [comment]
I guess vllm supports it: https://docs.vllm.ai/en/latest/getting_started/examples/openai_embedding_client.html

**Comment by Huyueeer** [comment]
I also want to know whether vllm supports
