### ISSUE TITLE
[Feature]: Need CPU inferencing support for non-x86 architectures

### ISSUE THREAD

**Issue by ChipKerchner** [vllm-project/vllm#5741]
### 🚀 The feature, motivation and pitch

We have a need for vLLM to support CPU inferencing for the PowerPC architecture.  This project should start thinking about non-x86 platforms.

[Initial PowerPC CPU support](https://github.com/vllm-project/vllm/pull/5652)

**Comment by mgoin** [comment]
I certainly agree we need to expand CPU support to other architectures and I especially think ARM would be quite impactful given the widespread availability and relatively large amount of memory bandwidth (compared to x86 processors) available on [Apple's M-series](https://en.wikipedia.org/wiki/Apple_M3), [AWS Graviton](https://aws.amazon.com/ec2/graviton/), [NVIDIA Grace](https://www.nvidia.com/en-us/data-center/grace-cpu/), and [Google Axion](https://cloud.google.com/blog/products/compute/introducing-googles-new-arm-based-cpu) ARM processors.

I'm only familiar with PowerPC from my past work in HPC so maybe my understanding is outdated but I believe these are not easy to get a hold of. @ChipKerchner Are there public instances available of the hardware so we can have CI regularly run? Could you share more about the use case or need from your group?

**Comment by manojnkumar** [comment]
@mgoin :  We do have IBM Power instances in public clouds and universities. We should be able to dedicate an instance for regullar CI runs.

**Comment by HuangLED** [comment]
> I certainly agree we need to expand CPU support to other architectures and I especially think ARM would be quite impactful given the widespread availability and relatively large amount of memory bandwidth (compared to x86 processors) available on [Apple's M-series](https://en.wikipedia.org/wiki/Apple_M3), [AWS Graviton](https://aws.amazon.com/ec2/graviton/), [NVIDIA Grace](https://www.nvidia.com/en-us/data-center/grace-cpu/), and [Google Axion](https://cloud.google.com/blog/products/compute/introducing-googles-new-arm-based-cpu) ARM processors.
> 
> I'm only familiar with PowerPC from my past work in HPC so maybe my understanding is outdated but I believe these are not easy to get a hold of. @ChipKerchner Are there public instances available of the hardware so we can have CI regularly run? Could you share more about the use case or need from your group?

+1  to "I especially think ARM would be quite impactful given the widespread availability"

**Comment by mgoin** [comment]
PowerPC has been supported for a while now!
