### ISSUE TITLE
[Bug]: Detokenizer stage is causing a significant delay

### ISSUE THREAD

**Issue by hbikki** [vllm-project/vllm#5749]
### Your current environment

```
Latest code from the main branch.
```

### 🐛 Describe the bug

**Description**
This issue reports a significant latency increase when invoking the Detokenizer.detokenize_incrementally function. 

**Root Cause:**
The current implementation in detokenizer.py [detokenizer.py](https://github.com/vllm-project/vllm/blob/main/vllm/transformers_utils/detokenizer.py#L269) performs a length calculation using the len(tokenizer) function call. This appears to be the source of the latency spike.

**Data Points:**
Inference with large batch size and big models experiences an additional ~15ms to ~20ms overhead per token generated.

**Questions:**
I would appreciate any insights into why the tokenizer is passed as a parameter to all the functions instead of being a class variable within Detokenizer. Is there a specific reason for this design choice?

**Comment by youkaichao** [comment]
usually this `len` should be cached https://github.com/vllm-project/vllm/blob/f1e72cc19a21928400b63743d5fe164ec8ed30e8/vllm/transformers_utils/tokenizer.py#L34

**Comment by hbikki** [comment]
I see , Then wrapping up the tokenizer in CachedTokenizer , should fix it when using with "skip_tokenizer_init = True "

**Comment by hbikki** [comment]
NVM , I see the fix merged 2 weeks ago , thanks! https://github.com/vllm-project/vllm/commit/eb8fcd266686570a1cfdcda4af73af0e27b0f3d8
