### ISSUE TITLE
[Usage]: How to set --max-logprobs to the default length of LLM's vocab_size.

### ISSUE THREAD

**Issue by fengshansi** [vllm-project/vllm#5762]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

When I use a different different LLM, I have to set --max-logprobs to it's vocab_size manually. Is there an easy way to set 
--max-logprobs to be vocab_size by default ?

**Comment by txy77** [comment]
Excuse me, I'd like to know if this issue has been resolved

**Comment by fengshansi** [comment]
> 对不起，我想知道这个问题是否已解决

你好，我并没有解决
