### ISSUE TITLE
[New Model]: bump a new version of vllm to support Qwen2 series

### ISSUE THREAD

**Issue by AlphaINF** [vllm-project/vllm#5773]
### The model to consider.

Qwen2 series, in https://huggingface.co/Qwen/Qwen2-7B

### The closest model vllm already supports.

Qwen1.5 series

### What's your difficulty of supporting the model you want?

Current version （v0.5.0-post1）didn't have the kernel to run Qwen2 series.
The intermediate size of all qwen2 models is not supported by punica yet.
And now the problem have been solved by https://github.com/vllm-project/vllm/pull/5441
I'm glad to see that the code is bumped and a new version will be introduced in the next days!

**Comment by marcelbra** [comment]
Would love an update on that, too, and am pretty sure many ppl would appreciate it. Thanks!!

**Comment by DarkLight1337** [comment]
Closing as `v0.5.1` has been released.

**Comment by AlphaINF** [comment]
Thank you ！！！
