### ISSUE TITLE
[Bug]: vllm批量推理报错

### ISSUE THREAD

**Issue by lxb0425** [vllm-project/vllm#5778]
### Your current environment

vllm  0.4.3

### 🐛 Describe the bug

多线程测试完vllm部署的模型服务报错如下 模型为qwen2-72b-int4-gptq
RROR:    Exception in ASGI application
0|startvllm72b  | Traceback (most recent call last):
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 281, in __call__
0|startvllm72b  |     await wrap(partial(self.listen_for_disconnect, receive))
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 270, in wrap
0|startvllm72b  |     await func()
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 221, in listen_for_disconnect
0|startvllm72b  |     message = await receive()
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
0|startvllm72b  |     await self.message_event.wait()
0|startvllm72b  |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
0|startvllm72b  |     await fut
0|startvllm72b  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f81f02e3be0
0|startvllm72b  | During handling of the above exception, another exception occurred:
0|startvllm72b  | Traceback (most recent call last):
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
0|startvllm72b  |     result = await app(  # type: ignore[func-returns-value]
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
0|startvllm72b  |     return await self.app(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
0|startvllm72b  |     await super().__call__(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
0|startvllm72b  |     await self.middleware_stack(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
0|startvllm72b  |     raise exc
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
0|startvllm72b  |     await self.app(scope, receive, _send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
0|startvllm72b  |     await self.app(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
0|startvllm72b  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
0|startvllm72b  |     raise exc
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
0|startvllm72b  |     await app(scope, receive, sender)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 762, in __call__
0|startvllm72b  |     await self.middleware_stack(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 782, in app
0|startvllm72b  |     await route.handle(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
0|startvllm72b  |     await self.app(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
0|startvllm72b  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
0|startvllm72b  |     raise exc
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
0|startvllm72b  |     await app(scope, receive, sender)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 75, in app
0|startvllm72b  |     await response(scope, receive, send)
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/sse_starlette/sse.py", line 267, in __call__
0|startvllm72b  |     async with anyio.create_task_group() as task_group:
0|startvllm72b  |   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
0|startvllm72b  |     raise BaseExceptionGroup(
0|startvllm72b  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)

**Comment by houshuai-cs** [comment]
I also encountered the same problem on vllm=0.4.0 and Llama-2-13b.

**Comment by codevoyager1984** [comment]
Same here

**Comment by chenchunhui97** [comment]
0.5.0post1 the same for qwen1.5-14b, but error not always appears.
