### ISSUE TITLE
vocab size cannot be divided by num GPUs

### ISSUE THREAD

**Issue by McCarrtney** [vllm-project/vllm#578]
We have a Chinese llama model with a 49954 vocab size, where 49954=24977*2, and 24977 is seemed to be a prime. We want to use vLLM to serve our model on 16GPUs, but 49954 cannot be divided by 16. Our vocab size cannot be changed recently. Is there any method to solve our serving problem?
(I think it's quite unreasonable, if we want to serve our model using vLLM, we can only use 2GPUs or 24977 GPUs?)

**Comment by syskn** [comment]
You should be able to simply pad vocab size up, preferably to multiples of 256 (such as 50176). IIRC, HF Tokenizer automatically does this to gain some speed, but I could be wrong.

**Comment by McCarrtney** [comment]
I may have misunderstood the purpose of tensor parallel. Tensor parallel is employed when a single GPU's memory cannot accommodate an entire model. In such cases, the model is sliced into parts and processed across multiple GPUs. However, when a single GPU can hold the entire model, tensor parallel becomes unnecessary. In fact, a single GPU can outperform multiple GPUs in terms of average speed.

My requirement, perhaps, is to have one model inference per GPU, while employing a strategy to direct requests to specific GPUs, thereby achieving high concurrency. I wonder if vLLM possesses such functionality.

**Comment by esmeetu** [comment]
Have you try the latest main branch？

**Comment by McCarrtney** [comment]
No, we install vLLM through pip. Is there any progress in the latest main branch?

**Comment by esmeetu** [comment]
> No, we install vLLM through pip. Is there any progress in the latest main branch?

Yes. Llama vocab padding feature has been merged a few days ago, it should be able to solve your problem. And you can build main branch by yourself or wait for the next release.

**Comment by esmeetu** [comment]
Of course, if a single GPU is already capable of loading the model, there is no need to split the model. Indeed, it can decrease efficiency. If you want to increase throughput, you can deploy the entire model on each GPU. For example, if you have 4 GPUs, you can start 4 service instances and then implement load balancing at the upper layer.

**Comment by McCarrtney** [comment]
> Of course, if a single GPU is already capable of loading the model, there is no need to split the model. Indeed, it can decrease efficiency. If you want to increase throughput, you can deploy the entire model on each GPU. For example, if you have 4 GPUs, you can start 4 service instances and then implement load balancing at the upper layer.

Thank you so much! That's quite helpful

**Comment by yanmengxiang1** [comment]
@McCarrtney 
Hi, I have an error to inference Llama-70b-chat using 16 gpus. The gpus is in one machine. #930
Do you have some ideas,thanks!
