### ISSUE TITLE
[Usage]: 使用vllm最新版0.5.0.post1启动模型

### ISSUE THREAD

**Issue by lxb0425** [vllm-project/vllm#5780]
### Your current environment

python -m vllm.entrypoints.api_server --host 0.0.0.0 --port 8005 --max-model-len 20480 \
    --model /workspace/Chat-v1.1 --enforce-eager \
    --tensor-parallel-size 1
   为什么启动后没有/v1/chat/completions 这个方法，需要怎么配置吗
![image](https://github.com/vllm-project/vllm/assets/50564015/d8a79417-891b-4af1-9bba-386b699a4b75)

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by JulyFinal** [comment]
命令写错了吧 应这是这样子

`python -m vllm.entrypoints.openai.api_server`
