### ISSUE TITLE
[Bug]: When using multi-node offline distributed inference, VLLM gets stuck at the last few samples of inference

### ISSUE THREAD

**Issue by LuJunru** [vllm-project/vllm#5782]
### Your current environment

```text
The output of `python collect_env.py`
```
Collecting environment information...
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.119-19-0009.11-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          192
On-line CPU(s) list:             0-191
Thread(s) per core:              2
Core(s) per socket:              48
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7K62 48-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3287.979
CPU max MHz:                     2600.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5190.40
Virtualization:                  AMD-V
L1d cache:                       3 MiB
L1i cache:                       3 MiB
L2 cache:                        48 MiB
L3 cache:                        384 MiB
NUMA node0 CPU(s):               0-47,96-143
NUMA node1 CPU(s):               48-95,144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] nvidia-nccl-cu12==2.18.1
[pip3] onnx==1.13.1
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.1.2
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0
[pip3] transformers==4.40.2
[pip3] transformers-stream-generator==0.0.4
[pip3] triton==2.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.3.2
vLLM Build Flags:
CUDA Archs: 5.2 6.0 6.1 7.0 7.5 8.0 8.6 9.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    CPU Affinity    NUMA Affinity
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    NODE    0-47,96-143     0
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    NODE    0-47,96-143     0
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    PXB     0-47,96-143     0
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    PXB     0-47,96-143     0
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    SYS     48-95,144-191   1
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    SYS     48-95,144-191   1
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    SYS     48-95,144-191   1
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      SYS     48-95,144-191   1
NIC0    NODE    NODE    PXB     PXB     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0

### 🐛 Describe the bug

I use two nodes to run offline distributed inference by VLLM. I can see the inference processing bars on both nodes. Everything goes fine for most cases. However, both the head node and the worker node stuck at the last few data samples. 

My multi-node inference script:
```
export GLOO_SOCKET_IFNAME=eth0
export WANDB_MODE=disabled

# init ray for multi-node vllm inference
LOCK_FILE="/tmp/ray_head_started-steps.lock"
if [ $INDEX -eq 0 ]; then
    ray start --head --port 6379 --num-gpus 8
    touch $LOCK_FILE
else
    while [ ! -f $LOCK_FILE ]; do
        echo "Waiting for the master node to start Ray..."
        sleep 5
    done
    ray start --address="${MASTER_ADDR}:6379" --num-gpus 8
fi

# gen negative response
train_model_path=my-13B-model/
chosen_label_file=inputs.jsonl
infer_output_path=outputs.jsonl
python3 get_model_infer_batch.py \
    --model-path ${train_model_path} \
    --question-file ${chosen_label_file} \
    --answer-file ${infer_output_path} \
    --max-all-len 8192 \
    --max-target-len 2048 \
    --num-gpus 8 \
    --num-nodes 2 \
    --temperature 0.8 \
    --top-p 0.95

# Stop Ray nodes
if [ $INDEX -eq 0 ]; then
    ray stop --force
    rm -f $LOCK_FILE
else
    ray stop --force
fi
```

The get_model_infer_batch.py script:
```
import argparse
import torch
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import json
from tqdm import tqdm
from vllm import LLM, SamplingParams
import ray

@ray.remote
def generate_answers(model_path, qs, sampling_params, num_gpus, max_all_len):
    model = LLM(model=model_path, gpu_memory_utilization=0.85, tensor_parallel_size=num_gpus, max_model_len=max_all_len, max_num_batched_tokens=max_all_len, trust_remote_code=True)
    outputs = [output.outputs[0].text.strip() for output in model.generate(qs, sampling_params)]
    return outputs

def run_eval(model_path, max_all_len, max_target_len, question_file, answer_file, temperature, top_p, num_gpus, num_nodes):
    qs = []
    with open(os.path.expanduser(question_file), "r") as ques_file:
        for line in ques_file:
            d_line = json.loads(line)
            qs_input = d_line["question"]

    model_path = os.path.expanduser(model_path)
    sampling_params = SamplingParams(max_tokens=max_target_len, temperature=temperature, top_p=top_p)

    # split data
    chunk_size = len(qs) // num_nodes
    qs_chunks = [qs[i:i + chunk_size] for i in range(0, len(qs), chunk_size)]

    # distributed inference on two nodes
    futures = [generate_answers.remote(model_path, chunk, sampling_params, num_gpus, max_all_len) for chunk in qs_chunks]
    results = ray.get(futures)

    outputs = [output for result in results for output in result]
    print(outputs[:10])
    
    with open(os.path.expanduser(answer_file), "w") as ans_file:
        for i_d, output in enumerate(outputs):
            ans_file.write(json.dumps({"question": qs[i_d], "inference": output}, ensure_ascii=False) + "\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", type=str, required=True)
    parser.add_argument("--question-file", type=str, required=True)
    parser.add_argument("--answer-file", type=str, default="answer.jsonl")
    parser.add_argument("--max-all-len", type=int, default=512)
    parser.add_argument("--max-target-len", type=int, default=512)
    parser.add_argument("--temperature", type=float, default=0.8)
    parser.add_argument("--top-p", type=float, default=0.95)
    parser.add_argument("--num-gpus", type=int, default=1)
    parser.add_argument("--num-nodes", type=int, default=1)
    args = parser.parse_args()

    run_eval(
        args.model_path,
        args.max_all_len,
        args.max_target_len,
        args.question_file,
        args.answer_file,
        args.temperature,
        args.top_p,
        args.num_gpus,
        args.num_nodes
    )
```

Several things can confirm:
- the above scripts works fine on every singe node.
- when predicting with two nodes, both the head node and the worker node are running, since I can see the processing bars. Well, **they all hang** at the last few steps. Such as: Processed prompts: 100%|███████ | 33883/33903.
- there are no errors or warnings, or core abortions when the stuck happens. I tried to wait over a night, but nothing changes.

**Comment by youkaichao** [comment]
can you try https://docs.vllm.ai/en/latest/getting_started/debugging.html to find out which line caused hang? we'd be happy to investigate if this is potentially a new bug.

> vLLM Version: 0.3.2

In addition, your vLLM version is quite old. I suggest you upgrade to a new one.

**Comment by LuJunru** [comment]
> can you try https://docs.vllm.ai/en/latest/getting_started/debugging.html to find out which line caused hang? we'd be happy to investigate if this is potentially a new bug.
> 
> > vLLM Version: 0.3.2
> 
> In addition, your vLLM version is quite old. I suggest you upgrade to a new one.

Hi youkai,

Thank you for the response. Unfortunately, I can not upgrade the vllm version right now. Nevertheless, I think the issue is somewhat related to the inter-node connections. Anyway, I realize a pseudo distributed inference by split the data in advance.
