### ISSUE TITLE
[Performance]: Long AllReduce wait time on 1 device with tensor parallelism 

### ISSUE THREAD

**Issue by wenscarl** [vllm-project/vllm#5792]
### Proposal to improve performance

Propose synchronizing the broadcast of tensor_dict at the beginning of each decoding step or block the process after broadcast.

### Report of performance regression

In the decoding stage, after matrix multiplications utilizing tensor parallelism, an all-reduce operation follows, which implicitly synchronizes the processes. However, the asynchronous broadcast of tensor dictionaries (code available [here](https://github.com/vllm-project/vllm/blob/main/vllm/distributed/parallel_state.py#L484-L503)) at the start of each decoding step causes CUDA kernels to launch at quite different times across processes. This leads to the scenario depicted in the following image.
![image (12)](https://github.com/vllm-project/vllm/assets/25590028/6eb4f309-023f-40d1-aace-065fa4bc643d) and ![image (13)](https://github.com/vllm-project/vllm/assets/25590028/061caee8-7d09-41f2-b730-da27b36677ed)
@youkaichao 

### Your current environment (if you think it is necessary)

```
CUDA_VISIBLE_DEVICES=0,1,2,3 nsys profile -t cuda,nvtx python benchmarks/benchmark_throughput.py --model=meta-llama/Meta-Llama-3-70B-Instruct --quantization=fp8  --dataset=/workspace/sw3/vllm/ShareGPT_V3_unfiltered_cleaned_split.json --output-len=64 --num-prompts=50 --enforce-eager -tp=4
```

**Comment by youkaichao** [comment]
thanks for the report! We do plan to remove this broadcast call. you can track the progress at https://github.com/vllm-project/vllm/issues/6241 . once we solve that issue, the driver process will send a lightweight python object to all processes, and each process prepare input themselves, so we don't need the broadcast tensors.

**Comment by eileenzhujuan** [comment]
> ### Proposal to improve performance
> Propose synchronizing the broadcast of tensor_dict at the beginning of each decoding step or block the process after broadcast.
> 
> ### Report of performance regression
> In the decoding stage, after matrix multiplications utilizing tensor parallelism, an all-reduce operation follows, which implicitly synchronizes the processes. However, the asynchronous broadcast of tensor dictionaries (code available [here](https://github.com/vllm-project/vllm/blob/main/vllm/distributed/parallel_state.py#L484-L503)) at the start of each decoding step causes CUDA kernels to launch at quite different times across processes. This leads to the scenario depicted in the following image. ![image (12)](https://private-user-images.githubusercontent.com/25590028/342414897-6eb4f309-023f-40d1-aace-065fa4bc643d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjAyMDYsIm5iZiI6MTcyMTExOTkwNiwicGF0aCI6Ii8yNTU5MDAyOC8zNDI0MTQ4OTctNmViNGYzMDktMDIzZi00MGQxLWFhY2UtMDY1ZmE0YmM2NDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4NTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzlmMTdjMGQ4MTA1NTcyYTg2ZjY3M2ZmZTA2Y2ZhZDFkMTI3NmU0OTE2Nzk4ZWQwOTUyMzcxYjE3ODNmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nMPHXOnP2epQvgPCJf_PA41JdWgPSReFxYQN37gr5fg) and ![image (13)](https://private-user-images.githubusercontent.com/25590028/342416660-061caee8-7d09-41f2-b730-da27b36677ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjAyMDYsIm5iZiI6MTcyMTExOTkwNiwicGF0aCI6Ii8yNTU5MDAyOC8zNDI0MTY2NjAtMDYxY2FlZTgtN2QwOS00MWYyLWI3MzAtZGEyN2IzNjY3N2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA4NTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYWMxNWQ5NjJmZDQxZGFhMzZhYWJhZDM1Y2ExYTcyNmVmYTMxYmM0MjgxNTIyNmJjZjkwM2I0NGM0Y2M1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ywcY8PnJuQTcSeomL-EOacFQPkmhddxiRXgzBV6Rf04) @youkaichao
> 
> ### Misc discussion on performance
> _No response_
> 
> ### Your current environment (if you think it is necessary)
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 nsys profile -t cuda,nvtx python benchmarks/benchmark_throughput.py --model=meta-llama/Meta-Llama-3-70B-Instruct --quantization=fp8  --dataset=/workspace/sw3/vllm/ShareGPT_V3_unfiltered_cleaned_split.json --output-len=64 --num-prompts=50 --enforce-eager -tp=4
> ```

Hi, I am curious about this proposal, as I met the similar problem. When I set tp_size=4, one of the rank(not the tp_rank=0 one) would appear the phenomenon that kernel launch turns much slower. As a result, each attention become slower with an all_reduce at the end. So, you meant that make the broadcast at the beginning of each decode step synchronize immediately would relieve the problem. Is it?
