### ISSUE TITLE
Consider optimizing the API server

### ISSUE THREAD

**Issue by imoneoi** [vllm-project/vllm#580]
Consider optimizing the FastAPI/OpenAI API server in vLLM as the server is widely used and seems to have a lot of overhead. On 1xA100 Llama 13B, the `LLM` class reaches 90~100% GPU utilization, while the API server can only utilize 50%

Related: https://github.com/vllm-project/vllm/discussions/459

**Comment by imoneoi** [comment]
Also, it would be nice to add a throughput benchmark for the API server

**Comment by WoosukKwon** [comment]
Hi @imoneoi, thanks for letting us know the issue. We've observed some slowdown when using the API server, but didn't know the slowdown is such significant. Will investigate it.

**Comment by DarkLight1337** [comment]
Closing as this has been addressed by moving online server to another process.
