### ISSUE TITLE
[Feature]: Integration Testing with lm-eval-harness

### ISSUE THREAD

**Issue by simon-mo** [vllm-project/vllm#5800]
### 🚀 The feature, motivation and pitch

As vLLM added more capable nodes for CI, I think it's a good time to start adding model quality test for both non-quantized and quantized model to ensure the kernel and scheduler changes do not degrade the model accuracy performance. This also ensure vLLM doesn't break lm-eval-harness's integration. 

I would like to ask for suggestions for concrete benchmarks to be added. For example, MMLU for Llama3-8B with a score >= X.

**Comment by robertgshaw2-neuralmagic** [comment]
Planning to push up later this week
- https://github.com/neuralmagic/nm-vllm/pull/326/files#diff-e7fdeb04c82dc2986f93edfff9769a4eab141a648124f5efd4c591ef4d00d080

**Comment by zifeitong** [comment]
I've been working a fork of https://github.com/openai/simple-evals with vLLM integrated. It's simpler with less moving parts than lm-eval-harness. I am happy to contribute if there is interest.
