### ISSUE TITLE
[Misc]: vLLM logger disables other existing loggers by default

### ISSUE THREAD

**Issue by a-ys** [vllm-project/vllm#5803]
## Issue
The current default behavior of the logger in vLLM is to disable all other existing loggers. This can prevent logs from being outputted from other code that is defined/imported before vLLM is imported.

## Details
The default logging config defined [here](https://github.com/vllm-project/vllm/blob/1744cc99ba9bdefea8f3f798cf51ed650b81a98e/vllm/logger.py#L22-L46) does not include `disable_existing_loggers=False`. When using logging.dictConfig() to configure logging, this value is set to True by default for backwards compatibility. Unless this is the intended behavior, I believe this key should be added to the configuration dictionary.

Happy to add this small change if maintainers agree with this. Thank you!

**Comment by simon-mo** [comment]
Good catch. Fix welcomed!
