### ISSUE TITLE
多gpus如何使用？

### ISSUE THREAD

**Issue by xxm1668** [vllm-project/vllm#581]

**Comment by nkfnn** [comment]
model = LLM(model=base_model, tensor_parallel_size=2)，两个gpu

**Comment by xxm1668** [comment]
(Worker pid=2861953) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 19352) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
(Worker pid=2861953) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 19352) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=2861953) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 19352) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]

**Comment by xxm1668** [comment]
export NCCL_IGNORE_DISABLED_P2P=1，可以解决；但有个问题哈，为啥多卡比单卡运行还慢呢？

**Comment by nkfnn** [comment]
> export NCCL_IGNORE_DISABLED_P2P=1，可以解决；但有个问题哈，为啥多卡比单卡运行还慢呢？

问下，您使用vllm后快了多少？我是用WizardCoder-15B-V1.0模型，使用vllm比hf快了一倍，但是网上都宣传快了27倍，我怀疑是不是我哪里设置没有到位。

**Comment by Sanster** [comment]
> > export NCCL_IGNORE_DISABLED_P2P=1，可以解决；但有个问题哈，为啥多卡比单卡运行还慢呢？
> 
> 问下，您使用vllm后快了多少？我是用WizardCoder-15B-V1.0模型，使用vllm比hf快了一倍，但是网上都宣传快了27倍，我怀疑是不是我哪里设置没有到位。

某个 issue 里看到过，27 倍应该是 batch 推理的加速效果

**Comment by nkfnn** [comment]
> 

哦哦，好的，谢谢

**Comment by xxm1668** [comment]
我快了27倍，2卡反而慢了，差不多快了14倍，不知道多卡为啥慢了

**Comment by xxm1668** [comment]
![10361690444816_ pic_hd](https://github.com/vllm-project/vllm/assets/129041904/7f2d7794-6eca-42f9-b8f4-f9516be17a00)

**Comment by gesanqiu** [comment]
Make sure you have already know the theory and goal of TP.
Usually, TP is use to solve the bottleneck of memory, for small size model, there is no need to use TP, multi-instances is better than use TP. Because when you use TP to a small model, you will meet the computing bottleneck of the GPU card itself. Considering of the communication cost, maybe you can only get 40-50% improvement when you use 2-GPUs(comparing to 1-GPU).

**Comment by xxm1668** [comment]
thanks，i understand

**Comment by nkfnn** [comment]
> 我快了27倍，2卡反而慢了，差不多快了14倍，不知道多卡为啥慢了

时间缩短了27倍嘛？可以给下您使用的模型，和hf的时间，以及缩短后的时间是多少吗？

**Comment by xxm1668** [comment]
图片不是有吗？

**Comment by guozhiyao** [comment]
> 我快了27倍，2卡反而慢了，差不多快了14倍，不知道多卡为啥慢了

@xxm1668 
请问下，你两卡是单独推理，还是弄成tp形式推理的呢？

**Comment by zlh1992** [comment]
> batch

batch 推理什么意思呀？

**Comment by Kevinddddddd** [comment]
> Make sure you have already know the theory and goal of TP. Usually, TP is use to solve the bottleneck of memory, for small size model, there is no need to use TP, multi-instances is better than use TP. Because when you use TP to a small model, you will meet the computing bottleneck of the GPU card itself. Considering of the communication cost, maybe you can only get 40-50% improvement when you use 2-GPUs(comparing to 1-GPU).

Hi, I have a question. Do you know how to set the number of instance in vllms?

**Comment by xxm1668** [comment]
@guozhiyao 单卡双卡都有；
双卡使用tensfor_parallel_size=2

**Comment by xxm1668** [comment]
@zlh1992 什么batch?

**Comment by zhuohan123** [comment]
hi @xxm1668 

vLLM has some random Python overheads that make TP slower than single GPU execution. We are investigating this and may eventually tackle this issue by providing C++ model implementations.

**Comment by wut0n9** [comment]
@zhuohan123   @xx
  多卡推理变慢有解决了吗

**Comment by John-Ge** [comment]
Hello, I have a question. If I have 8 gpu want to run llama 2 7b chat model, it is better to run 8 different programs. Now using vllm I should deploy 8 program and use 8 ports. Do you have plan to develop some kind of "automatic data parallel" function?

**Comment by yungangwu** [comment]
vllm用这种方式，相当于是在不同的卡上各启动了一个模型，有没有什么方式能做模型的并行的？将模型的不同部分放在不同的gpu上运行

**Comment by runzeer** [comment]
为啥我用多卡推理时候会卡在"started a local Ray instance"这里呢？大佬有碰到这个问题的吗

**Comment by xxm1668** [comment]
@runzeer export NCCL_IGNORE_DISABLED_P2P=1试试这个

**Comment by wenyangchou** [comment]
`tensfor_parallel_size` can support pp ? or it support tp only?

**Comment by ArlanCooper** [comment]
> @guozhiyao 单卡双卡都有； 双卡使用tensfor_parallel_size=2

设置这个参数，是将模型分别加载到两个gpu了吗？我这边设置成2，发现两个gpu都占了整个模型的大小，怎么可以让模型分布式加载到两个模型上呢？

**Comment by wenyangchou** [comment]
> > @guozhiyao 单卡双卡都有； 双卡使用tensfor_parallel_size=2
> 
> 设置这个参数，是将模型分别加载到两个gpu了吗？我这边设置成2，发现两个gpu都占了整个模型的大小，怎么可以让模型分布式加载到两个模型上呢？

vllm是饿汉式加载内存，所以你看到的内存很可能不是模型内存，而是gpu_utilization 设置的内存

**Comment by gaojing8500** [comment]
> 为啥我用多卡推理时候会卡在"started a local Ray instance"这里呢？大佬有碰到这个问题的吗
8张4090卡也是一直卡在这里 不清楚为什么

**Comment by strongliu110** [comment]
哪位能给下多GPU 如何运行？试了设置 tensor_parallel_size=2，和 export NCCL_IGNORE_DISABLED_P2P=1 都还是报OOM。GPU 0 显存不够了，但是GPU 1 是足够的

**Comment by hwb96** [comment]
tensor_parallel_size=2,并且记得，这个参数要能够被模型的层数整除，这样才能够平均放置模型的层数参数。否则会报错。tensor parallel size=2, and remember that this parameter must be evenly divided by the number of layers of the model, so that the number of layers of the model can be evenly placed. Otherwise, an error will be reported.

**Comment by liyunhan** [comment]
@hwb96 想问下您：
1. vllm和ray有版本兼容问题吗？
2. 我双机各双卡A6000，使用ray+vllm openai做分部式部署，两台机器都要装vllm吗？以及总提示我p2p通信有问题这是为啥？

**Comment by DaoD** [comment]
tensor_parallel_size=2 means spliting the model into two GPUs rather than running two full models.

**Comment by fengshansi** [comment]
How can I use multiple A800 to load several small model？ Ngnix reverse proxy？

**Comment by FrankMinions** [comment]
> 哪位能给下多GPU 如何运行？试了设置 tensor_parallel_size=2，和 export NCCL_IGNORE_DISABLED_P2P=1 都还是报OOM。GPU 0 显存不够了，但是GPU 1 是足够的

设置max_model_len参数

**Comment by moverzp** [comment]
> Hello, I have a question. If I have 8 gpu want to run llama 2 7b chat model, it is better to run 8 different programs. Now using vllm I should deploy 8 program and use 8 ports. Do you have plan to develop some kind of "automatic data parallel" function?

请问这个问题解决了吗？我也是单卡能放下的model想单机多卡并行调用~
