### ISSUE TITLE
[RFC] Changes to CI workflow for PRs

### ISSUE THREAD

**Issue by khluu** [vllm-project/vllm#5816]
### Motivation.

- We need to aggressively drive down CI cost since the current burn rate is not sustainable for vLLM.
- Currently, we run full CI tests for every commits on every PR which is quite a lot and unnecessary.

### Proposed Change.

This is the same workflow that `ray` CI is using which I think is working great in terms of maintaining the same CI signals & cost reduction. I think vLLM would benefit from the same system.

Instead of having a single CI pipeline that runs on every PRs, we can break it down to 3 separate pipelines, each serving a different purpose.

**1. `Fast-check` pipeline**
- **Purpose**: quickly catch small errors in between PR commits that don't require unnecessary tests.
- Run a small, fast, and essential subset of tests (e.g. basic correctness, regression, engine, core, etc..)
- Trigger on every commit within a PR.

**2. `Pre-merge` pipeline**
- **Purpose**: catch as many errors as possible before PR is merged to main.
- Run all tests for now. Once we have a mature automated test selection (planned for Q3), it can be applied here to cut costs even more.
- Required to pass in order to merge PR
- Should be triggered when:
  - PR is ready to merge
  - PR author needs more test signal than what’s in `fast-check`
- Ways to trigger:
  - PR auto-merge is enabled
  - `Ready` label is added to PR
  - `/ready` comment on the PR by author

**3. `Post-merge` pipeline**
- **Purpose**: Catch all errors to keep`main` branch clean & release-ready
- Run all tests regardless.
- Run only on main
- Run periodically (every N commits)

There would be not much change in CI signals since PR author can always flag PR to run all tests if needed. Also, `pre-merge` is required to pass before PR is merged so all CI signals would be there anyway.

The downside of this approach would be:
1. `fast-check` sometimes wouldn't provide enough signal and errors are only caught when PR is trying to merge (which is when `pre-merge` runs). This would delay progress a bit for bug fixing.
2. PR author needs to remember to add `ready` label (if you're a committer) or to comment `/ready` if CI signal from `fast-check` is not enough.
3. Once a failure is detected on main, it might take some extra work to pinpoint the failing commit since `post-merge` is not run per commit anymore. This can be controlled by starting with a small N.

### Feedback Period.

I hope to start the work as soon as possible since our CI cost is high.

### CC List.

@simon-mo  @DarkLight1337 @dgoupil @youkaichao @ywang96

**Comment by DarkLight1337** [comment]
I agree with this in principle. The main sticking point for me is how to communicate this to new contributors, especially the part about running `Pre-merge` manually. The first idea that comes to mind is to introduce a bot that automatically comments on the PR to notify them about this.

**Comment by khluu** [comment]
> introduce a bot that automatically comments on the PR to notify them about this.

Yup I agree. We can do that or have a info banner (like what we have for perf benchmark rn) in the `fast-check` run on Buildkite UI.

**Comment by youkaichao** [comment]
FYI, pytorch has a mergebot @pytorchmergebot , only it can merge.

**Comment by youkaichao** [comment]
after a pr is approved by someone with write access, anyone can call @pytorchmergebot to trigger a merge ci, and merge it if ci passes.

**Comment by khluu** [comment]
@youkaichao  I think we can just use [Github auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request). Is there any specific advantage of using pytorchmergebot?

**Comment by youkaichao** [comment]
> Is there any specific advantage of using pytorchmergebot?

I don't know. This is just FYI :)

**Comment by DarkLight1337** [comment]
Would it take much additional effort to add shortcuts to run smaller subsets of tests? e.g. commenting `/test-lora` to only run lora tests.

**Comment by khluu** [comment]
> Would it take much additional effort to add shortcuts for running smaller subsets of tests on demand? e.g. commenting `/test-lora` to only run lora tests.

I think it's easier if we just add `lora` label to the PR so `fast-check` can run lora tests on top of other quick tests. Might need some extra work to make it happen
