### ISSUE TITLE
does not work in distributed mode

### ISSUE THREAD

**Issue by LQchen1** [vllm-project/vllm#582]
![image](https://github.com/vllm-project/vllm/assets/93528700/949b8541-8b8d-4045-ab94-5f964de6d12d)
![image](https://github.com/vllm-project/vllm/assets/93528700/1ff4c44d-b50a-4941-a394-89bbbfc3e42e)
When I set tensor_parallel_size to 2, the model doesn't work. When I set it to 1, it works fine.

**Comment by zhuohan123** [comment]
Can you try the latest main branch? #397 should have fixed this kind of issues. If not, maybe try running with `NCCL_IGNORE_DISABLED_P2P=1 `? Feel free to re-open this issue if these fixes do not work.
