### ISSUE TITLE
Gibberish output with llama-2-7b-chat

### ISSUE THREAD

**Issue by nootums** [vllm-project/vllm#585]
I'm using llama-2-7b-chat through vLLM. I have tried redownloading the model 2 times and I'm facing the same issue. I've also tried using different tokenizers.

When I query "What is the capital of Germany?"
It responds with: iskaὶід}$.)}{nex програ FoiProgramкли Referencias nov laugh maven нап ","

I am unsure on what to do next. I'm trying to redownload the model once again, but if that also does not work, I don't know how to resolve this.

I've attached a screenshot of my notebook below.
<img width="1196" alt="image" src="https://github.com/vllm-project/vllm/assets/65669681/a0819ba0-da86-4f5f-913a-0ee8e2908163">

**Comment by evilc3** [comment]
hey were you able to load 7b-chat-hf  on t4 16gb machine??, I am unable to load it every time get a OOM error. which version on vllm are you using?

**Comment by nootums** [comment]
> hey were you able to load 7b-chat-hf on t4 16gb machine??, I am unable to load it every time get a OOM error. which version on vllm are you using?

This isn't the huggingface model, I'm using the model which I directly downloaded from meta. The hf version isn't running on colab and gives CUDA OOM error for me too.
I am looking into using AWS Sagemaker to run the hf version of the model. 
I'm using vllm version 0.1.2

**Comment by gesanqiu** [comment]
Hhuggingface model should works fine, and do make sure you use the pytorch_model_*.bin not the *.safetensors.

**Comment by nootums** [comment]
Yes, I've tried running the hf model on sagemaker, and its running fine there. 
The original models still don't run fine for some reason.
Is the model which meta is distributing corrupted?, or are they bundling the wrong tokenizer?

**Comment by zhuohan123** [comment]
Please use the huggingface version. There might be some weight formatting differences (e.g., in QKV transform layer) that can cause garbage results.
