### ISSUE TITLE
OOM killer - actor is dead

### ISSUE THREAD

**Issue by iRanadheer** [vllm-project/vllm#586]
I have 4x16GB GPU cards, I'm loading the vicuna 13b.v1.3 model, and I'm getting the following error;

`The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
The actor never ran - it was cancelled before it started running.`

The command I'm using is this:
```RAY_memory_usage_threshold=0.7 RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m vllm.entrypoints.api_server --model ../models/vicuna-13b-v1.3/ --gpu-memory-utilization 0.9 --swap-space 1 --tokenizer hf-internal-testing/llama-tokenizer --tensor-parallel-size 4```

**Comment by schnurromafia** [comment]
I'm getting the same error when trying to load Llama-2 13b (meta-llama/Llama-2-7b-chat-hf) to 4x Titan Xp 12GB (Cuda v.12.0).

**Comment by irasin** [comment]
Maybe the OOM occurs because your cpu memory it too small to reserve exough cpu_swap_space(pin_memory) for 4 GPUs? Or can't now load vicuna13(26GB~) since you have to launch 4 process, and each process need to use 26GB cpu memory.

**Comment by iRanadheer** [comment]
@irasin, wow that's a lot of CPU memory. just curious to know if there's any metric on how to calculate the needed CPU memory.

**Comment by iRanadheer** [comment]
> I'm getting the same error when trying to load Llama-2 13b (meta-llama/Llama-2-13b-chat-hf) to 4x Titan Xp 12GB (Cuda v.12.0).

i dont think cuda v12 is supported. look at the requirements here:
https://vllm.readthedocs.io/en/latest/getting_started/installation.html

**Comment by schnurromafia** [comment]
@iRanadheer it still works with v12 through cuda backwards compatibility. Serving 7B models on GPUs work just fine, the OOM error occurs only starting with 13B models.

**Comment by iRanadheer** [comment]
Oh, Thanks for the info. 7b model is running just fine but 13b is leading to OOM error.

**Comment by zhuohan123** [comment]
Please try to reduce swap memory via specifying `--swap-space 1` or less to avoid this error. Feel free to reopen the issue if there is any other issue.

**Comment by iRanadheer** [comment]
@zhuohan123 I have actually done that, not entirely clear how much RAM and VRAM are required for deploying Vicuna 13B model. I have 64 gb of gpu memory and 40gb of CPU memory, yet I still couldn't deploy the 13B model.

**Comment by Ryojikn** [comment]
It seems that swap space is a part of your storage disk, used as temporary memory while memory is full.
This seems to be some sort of resource usage used by vllm in order to manage heavy models such as this.

I'm running in a cluster (baremetal) with 4 gpus, and the /dev/shm is like 64mb, however the /tmp has something like 96 gb available.

Given what was pointed out that trying to use 4 GPUs means 4 process trying to move up to 26gb to swap space, of course it won't be able to handle.

What you're telling @zhuohan123  is that adding swap space 1 would reduce this to 1gb as swap space, controlling the error, while probably slowing down the model loading process?

**Comment by viktor-ferenczi** [comment]
Getting this OOM error while trying to load `TheBloke/WizardCoder-Python-34B-V1.0-AWQ` with `--tensor-parallel-size=2` (2x4090 GPUs) with 64GB CPU memory. Increased the shm size to 48GB, it did not help. Trying to load on a single GPU causes "CUDA out of memory", while the model should fit.

**Comment by HeShiLie** [comment]
same issue
