### ISSUE TITLE
[Bug]: ray version problem

### ISSUE THREAD

**Issue by zxcdsa45687** [vllm-project/vllm#5861]
### Your current environment

ray= 2.10.0

### 🐛 Describe the bug

New additions in #5748 from ray.exceptions import ActorDiedError, but only in ray>=2.11.0, Now ray =2.9 in the requirements-cuda.txt file, loading the model will fail after the source code is compiled

**Comment by zxcdsa45687** [comment]
ActorDiedError is available only in ray >=2.11.0 versions . The current ray>=2.9 raises an error

**Comment by zxcdsa45687** [comment]
并且ray>2.10.0版本后，好像不再支持python=3.8

**Comment by zxcdsa45687** [comment]
And after ray>2.10.0, python=3.8 is no longer supported

**Comment by DarkLight1337** [comment]
Closed #6033 as completed via #6039.
