### ISSUE TITLE
[Usage]: Can I get the streaming output when using offline inference?

### ISSUE THREAD

**Issue by jiangjiadi** [vllm-project/vllm#5862]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to get the streaming output when using offline inference. But I can't find the 'stream' switch.

**Comment by mgoin** [comment]
Hi @jiangjiadi the offline `LLM` interface doesn't have capability for streaming individual tokens. If you want to achieve this offline within Python, you must go through the `AsyncLLMEngine` interface and use the async functionality.

Here is an example I made that will print each token on a new line:
```python
import asyncio
import time
from vllm import AsyncLLMEngine, AsyncEngineArgs, SamplingParams

engine_args = AsyncEngineArgs(model="facebook/opt-125m", enforce_eager=True)
model = AsyncLLMEngine.from_engine_args(engine_args)

async def generate_streaming(prompt):
    results_generator = model.generate(prompt, SamplingParams(), request_id=time.monotonic())
    previous_text = ""
    async for request_output in results_generator:
        text = request_output.outputs[0].text
        print(text[len(previous_text):])
        previous_text = text

asyncio.run(generate_streaming("hello"))
```

**Comment by jiangjiadi** [comment]
@mgoin Thank you! It works.

**Comment by jiangjiadi** [comment]
@mgoin Using the same code, but I encounter the following excepton when I use the Qwen/Qwen1.5-0.5B-Chat model with vllm==0.4.2.

![image](https://github.com/vllm-project/vllm/assets/34134495/c82de33b-306b-4b9e-b05e-4ddab9e1495c)

**Comment by DongZhaoXiong** [comment]
> Hi @jiangjiadi the offline `LLM` interface doesn't have capability for streaming individual tokens. If you want to achieve this offline within Python, you must go through the `AsyncLLMEngine` interface and use the async functionality.
> 
> Here is an example I made that will print each token on a new line:
> 
> ```python
> import asyncio
> import time
> from vllm import AsyncLLMEngine, AsyncEngineArgs, SamplingParams
> 
> engine_args = AsyncEngineArgs(model="facebook/opt-125m", enforce_eager=True)
> model = AsyncLLMEngine.from_engine_args(engine_args)
> 
> async def generate_streaming(prompt):
>     results_generator = model.generate(prompt, SamplingParams(), request_id=time.monotonic())
>     previous_text = ""
>     async for request_output in results_generator:
>         text = request_output.outputs[0].text
>         print(text[len(previous_text):])
>         previous_text = text
> 
> asyncio.run(generate_streaming("hello"))
> ```
> 
> Output:
> 
> ```
> INFO 06-26 18:01:31 async_llm_engine.py:564] Received request 1722622.519236168: prompt: 'hello', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=16, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: None, lora_request: None.
> .
>  thanks
>  for
>  the
>  help
> !
>  i
>  will
>  pay
>  more
>  in
>  runes
>  just
>  to
>  get
> INFO 06-26 18:01:31 async_llm_engine.py:133] Finished request 1722622.519236168.
>  on
> INFO 06-26 18:01:31 async_llm_engine.py:49] Engine is gracefully shutting down.
> ```

How to block the engine shutting down, I use the djl serving + vllm AsyncEngine, but engine shut down will make the djl serving down
