### ISSUE TITLE
[Feature]: Request for SmartSpec Method Support

### ISSUE THREAD

**Issue by bong-furiosa** [vllm-project/vllm#5886]
### 🚀 The feature, motivation and pitch

Recently, we read a paper where the vLLM team proposed a method called **SmartSpec**.
We believe that the research, which dynamically adjusts the speculation length in a commercialized LLM serving system, is superior in terms of practicality compared to existing dynamic speculative length studies.
- [Optimizing Speculative Decoding for Serving Large Language Models Using Goodput](https://arxiv.org/pdf/2406.14066v1)

This idea could be applied to the current vLLM speculative decoding with Batch Expansion enabled, and it might also be applicable to future versions of vLLM with Batch Expansion disabled.
(I am curious whether the SmartSpec research was conducted on vLLM with Batch Expansion enabled. :thinking:)

**I wonder if the SmartSpec method will be implemented into the main repository in the near future.**

**Comment by bong-furiosa** [comment]
Since we found the PR(#5000) related to Dynamic Speculative Decoding, I will close this request."

**Comment by LiuXiaoxuanPKU** [comment]
Hi @bong-furiosa, thanks for the attention!

Yes, we implemented SmartSpec on top of vllm with batch expansion in a forked version. We will integrate SmartSpec to vllm very soon. The first step is to remove batch expansion (#5691). In the meantime, we also need the community effort to improve speculative decoding performance (#4630) and implement tree-style speculative decoding(#4978).
SmartSpec (#4565) is very lightweight and can be implemented quickly. After all above mentioned steps, we should see similar performance as described in the paper.

**Comment by bong-furiosa** [comment]
Since we have received a detailed response, we will close this issue. We are very looking forward to seeing further developments in vLLM!
