### ISSUE TITLE
OSError: Can't load the configuration of 'MPTForCausalLM(

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#591]
I am trying to use mpt but getting a config error:

from vllm import LLM, SamplingParams
from torch import cuda, float32
import transformers
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
model = transformers.AutoModelForCausalLM.from_pretrained(
    'mosaicml/mpt-7b-instruct',
    trust_remote_code=True,
    torch_dtype=float32,
    max_seq_len=2048
)
llm = LLM(model=model)

This is my error:
`OSError: Can't load the configuration of 'MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 4096)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-31): 32 x MPTBlock(
        (norm_1): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=4096, out_features=12288, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (norm_2): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=4096, out_features=16384, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=16384, out_features=4096, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
)'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'MPTForCausalLM(
  (transformer): MPTModel(
    (wte): SharedEmbedding(50432, 4096)
    (emb_drop): Dropout(p=0, inplace=False)
    (blocks): ModuleList(
      (0-31): 32 x MPTBlock(
        (norm_1): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): MultiheadAttention(
          (Wqkv): Linear(in_features=4096, out_features=12288, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (norm_2): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (ffn): MPTMLP(
          (up_proj): Linear(in_features=4096, out_features=16384, bias=False)
          (act): GELU(approximate='none')
          (down_proj): Linear(in_features=16384, out_features=4096, bias=False)
        )
        (resid_attn_dropout): Dropout(p=0, inplace=False)
        (resid_ffn_dropout): Dropout(p=0, inplace=False)
      )
    )
    (norm_f): LPLayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
)' is the correct path to a directory containing a config.json file`

**Comment by WoosukKwon** [comment]
Hi @nutmilk10, the `LLM` class accepts the model name or path, not an instantiated PyTorch model. So please change the following:

```python
model = transformers.AutoModelForCausalLM.from_pretrained(
'mosaicml/mpt-7b-instruct',
trust_remote_code=True,
torch_dtype=float32,
max_seq_len=2048
)
llm = LLM(model=model)
```

to

```python
llm = LLM(
   model='mosaicml/mpt-7b-instruct',
   trust_remote_code=True,
   torch_dtype=float32,
   max_seq_len=2048
)
```

**Comment by S-Yacer** [comment]
Traceback (most recent call last):
  File "/home/flippyroot/inference/coder.py", line 6, in <module>
    llm = LLM(model="awq/coder-34b-awq", tensor_parallel_size=4, quantization="awq", dtype="half", max_seq_len=4096)
  File "/home/flippyroot/.local/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 75, in __init__
    engine_args = EngineArgs(
TypeError: EngineArgs.__init__() got an unexpected keyword argument 'max_seq_len'

how come ?

**Comment by mohamedScikitLearn** [comment]
In case anyoen is facing this problem for different other reasons, this might also solve your problem:
`pip install -U ipywidgets`

Then restart your kernel.
