### ISSUE TITLE
[Feature]: Support for google/gemma-2-9b-it / gemma-2-27b-it

### ISSUE THREAD

**Issue by ivanviragine** [vllm-project/vllm#5912]
### 🚀 The feature, motivation and pitch

It would be nice to have support for the new Gemma 2 models: https://huggingface.co/collections/google/gemma-2-release-667d6600fd5220e7b967f315

**Comment by jeejeelee** [comment]
FYI:https://github.com/vllm-project/vllm/pull/5908
