### ISSUE TITLE
[Bug]: FP8 checkpoints with fused linear modules fail to load scales correctly

### ISSUE THREAD

**Issue by mgoin** [vllm-project/vllm#5915]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

Description:
When loading FP8 quantized models with merged linear modules (e.g., Phi-3 with merged qkv_proj and up_gate_proj), the scales for each shard are not handled correctly. This occurs because the vLLM FP8 config assumes separate scales for each shard, but merged layers have a single scale.

Steps to Reproduce:
1. Attempt to load an FP8 quantized Phi-3 model (e.g., https://huggingface.co/nm-testing/Phi-3-mini-128k-instruct-FP8)
2. Observe error due to shape mismatch:
   ```
   param_data.shape=torch.Size([2]) loaded_weight.shape=torch.Size([])
   param_data.shape=torch.Size([3]) loaded_weight.shape=torch.Size([])
   ```

Expected Behavior:
Scales should be correctly loaded for merged linear modules in FP8 checkpoints.

Proposed Fix:
Modify `process_weights_after_loading` in MergedColumnParallelLinear and QKVParallelLinear to repeat the merged scale during weight loading.

Temporary Workaround:
Apply the following patch in `vllm/model_executor/layers/linear.py`:
```python
- assert param_data.shape == loaded_weight.shape
- param_data.copy_(loaded_weight)
+ temp = loaded_weight.repeat(param_data.shape)
+ assert param_data.shape == temp.shape
+ param_data.copy_(temp)
```

cc @robertgshaw2-neuralmagic @comaniac

**Comment by comaniac** [comment]
I thought we handled this already? All the FP8 checkpoints have separated QKV scales and we merged them after weight loading. Is there anything special in Phi-3?

**Comment by robertgshaw2-neuralmagic** [comment]
Im working on a fix for this right now.

Issue is phi3 has fused qkv on disk so theres already only one scale!

**Comment by jon-chuang** [comment]
This model cannot be loaded from huggingface now

![image](https://github.com/user-attachments/assets/0f4267b0-0e43-4e6b-a29b-3de25a5f0caf)

**Comment by jon-chuang** [comment]
Furthermore: 
![image](https://github.com/user-attachments/assets/6787a78c-b151-4cd6-beff-77694cf72b2f)

**Comment by mgoin** [comment]
@jon-chuang should be resolved now

**Comment by jon-chuang** [comment]
![image](https://github.com/user-attachments/assets/7e56869a-8df3-4412-a2a3-7134e49dba4d)
Not yet

**Comment by mgoin** [comment]
@jon-chuang Please rebase on main, this was resolved with https://github.com/vllm-project/vllm/pull/7376
