### ISSUE TITLE
Cannot get a simple example working with multi-GPU

### ISSUE THREAD

**Issue by brevity2021** [vllm-project/vllm#594]
I was trying to do a simple example script: 
```
from vllm import LLM
llm = LLM("facebook/opt-13b", tensor_parallel_size=4)
output = llm.generate("San Franciso is a")
```
I installed vllm and ray in a virtual env, on a g5.12xlarge instance. 
At first, I install vllm using `pip install vllm`, and got the same IPV6 error as in [this bug](https://github.com/vllm-project/vllm/issues/570).
Then I tried to install from the repo using `pip install -e .` and had trouble importing LLM.

>>> from vllm import LLM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LLM' from 'vllm' (unknown location)

Anyone knows why this happens?

**Comment by iRanadheer** [comment]
whats your cuda version?

**Comment by brevity2021** [comment]
> whats your Cuda version?

My Cuda version is 11.7.

**Comment by nootums** [comment]
I'm facing the same issue. 
When I build it from source according to a [comment](https://github.com/vllm-project/vllm/issues/570#issuecomment-1650973012) on #570 , it gets stuck in loading the LLM.
Did anyone find a fix?

**Comment by bigmover** [comment]
> 尝试一下使用 from vllm.entrypoints.llm import LLM from vllm.sampling_params import SamplingParams

it worked! but what's the problem? add PYTHONPATH?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by KevinCL16** [comment]
Like op, I tried to install from the repo using pip install -e . and had trouble importing LLM.

```from vllm import LLM

Traceback (most recent call last):
File "", line 1, in
ImportError: cannot import name 'LLM' from 'vllm' (unknown location)```

I got around this issue by using:
> 尝试一下使用 from vllm.entrypoints.llm import LLM from vllm.sampling_params import SamplingParams

However, I ran into another error:
``` File "/home/yangzhiyu/workspace/open-long-agent/vllm/vllm/entrypoints/llm.py", line 118, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/yangzhiyu/workspace/open-long-agent/vllm/vllm/engine/llm_engine.py", line 291, in from_engine_args
    engine = cls(
  File "/home/yangzhiyu/workspace/open-long-agent/vllm/vllm/engine/llm_engine.py", line 110, in __init__
    vllm.__version__,
AttributeError: module 'vllm' has no attribute '__version__'```

I wonder if using pip install -e . is bugged?

**Comment by hmellor** [comment]
What is the pwd you are running these scripts from?

If vllm src is in the pwd it's possible that your script is trying to import the local files rather than going via your pip installs. This could be the cause of your import issues.

**Comment by GARRYHU** [comment]
**It may be because the Python file for running the model (assuming it's called `run.py`) and the vllm repository folder are in the same directory.** Even if you have run `pip install -e .` to install the vllm package into site-packages, run.py will still try to import modules from the current directory's `vllm/` first (whereas the modules are actually in `vllm/vllm/`), causing the import to fail. 

**Try moving `run.py` to a different location and then  `from vllm import LLM, SamplingParams`.**


I tried `from vllm.entrypoints.llm import LLM`, but it caused other problems: `AttributeError: module 'vllm' has no attribute '__version__'`

**Comment by OsaydAbdu** [comment]
I'm having the same problem, any idea if this can be resolved?
