### ISSUE TITLE
[Bug]: "work_use_ray" not work anymore in the latest version

### ISSUE THREAD

**Issue by vincent-pli** [vllm-project/vllm#5944]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

So, `work_use_ray` do not work anymore?
check the code: https://github.com/vllm-project/vllm/blob/c3dde367f16111b8968948a1f8e1a26bdac6ffdd/vllm/engine/llm_engine.py#L371

To leverage `ray` or not seems turn to: `engine_config.parallel_config.distributed_executor_backend`

I think at least we need document the change.

**Comment by llmpros** [comment]
@vincent-pli are you trying to say that `ray` distributed backend does not work? The following command works for me

```
python -m vllm.entrypoints.openai.api_server  --model /your_model_directory/ --tensor-parallel-size 1 --max-model-len 3000 --gpu-memory-utilization 0.9 --distributed-executor-backend ray
```

**Comment by youkaichao** [comment]
`--worker-use-ray` is the same as `--distributed-executor-backend ray` now. the former is deprecated, and we recommend using the latter one.

https://github.com/vllm-project/vllm/blob/af9ad46fca6e594797b83e5ecb2e1f31ca5e9fac/vllm/config.py#L626-L629
