### ISSUE TITLE
Gemma2 models from google

### ISSUE THREAD

**Issue by bks5881** [vllm-project/vllm#5953]
### The model to consider.

https://huggingface.co/google/gemma-2-27b-it 

### The closest model vllm already supports.

gemma

**Comment by DarkLight1337** [comment]
It has been added by #5908, so expect to see it in the next release!

**Comment by lonngxiang** [comment]
Model architectures ['Gemma2ForCausalLM'] are not supported for now

**Comment by DarkLight1337** [comment]
The changes are only in `main` branch for now, but a release is planned in the next few days.
