### ISSUE TITLE
ValueError: The number of GPUs per node is not divisible by the number of tensor parallelism.

### ISSUE THREAD

**Issue by beratcmn** [vllm-project/vllm#596]
I have 3 GPUs (3x3090). When I try to load `LLaMA-2-13B` and set the `tensor_parallel_size` to 2 it gives me this error. When I set it to 3 error follows like `ValueError: Total number of attention heads (40) must be divisible by tensor parallel size (3).`

**Comment by foamliu** [comment]
The same problem, a node with 8 V100 graphics cards, try to run LLaMA 2 70B with 5, and report the same error. Frankly, it doesn't make sense and is a waste.

**Comment by zhuohan123** [comment]
I cannot reproduce this bug on my side. Can you share the code and more details about your environment that can reproduce the error?

**Comment by ehartford** [comment]
I try to run with 3 GPUs I get this:

```
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 616, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 486, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 95, in __init__
    self._verify_args()
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 185, in _verify_args
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 118, in verify_with_parallel_config
    raise ValueError(
ValueError: Total number of attention heads (64) must be divisible by tensor parallel size (3).
```

**Comment by Zcc** [comment]
you must set the parallel size to divisor of the number of attention heads，if it's 64 , please try 2, 4, 8 etc.

**Comment by eigen2017** [comment]
> you must set the parallel size to divisor of the number of attention heads，if it's 64 , please try 2, 4, 8 etc.

why？

**Comment by hmellor** [comment]
Because the heads dimension is the one that is split across the tensor parallel workers.

i.e. you can't split 64 heads evenly across 3 GPUs.

**Comment by yezhengmao1** [comment]
maybe we need some method to manually split the tensor, not just divided it.

**Comment by SMAntony** [comment]
@hmellor Could you please explain the reason as to why spreading heads evenly matter? This might be a dumb question, so if you could point me to resources, please do.

**Comment by yezhengmao1** [comment]
@SMAntony  pytorch do not support... if you want to use the pytorch's tensor parallel, must ensure the tensor can be divided evenly.
