### ISSUE TITLE
[New Model]: support for BartForSequenceClassification

### ISSUE THREAD

**Issue by Sapessii** [vllm-project/vllm#5985]
### The model to consider.

Hi!

Is there any plan on supporting https://huggingface.co/facebook/bart-large-mnli on vllm? When I try to run it it says "BartForSequenceClassification" is not supported now, do you know any alternatives or if I'm doing something wrong?

Thank you

**Comment by ashleykleynhans** [comment]
Would be great if support could be added for `BartForSequenceClassification`.
