### ISSUE TITLE
[Feature]: need 'Gemma2ForCausalLM' support

### ISSUE THREAD

**Issue by zzc0208** [vllm-project/vllm#5992]
### 🚀 The feature, motivation and pitch

I want to use vllm to infer UCLA-AGI/Gemma-2-9B-It-SPPO-Iter3, but it doesn't seem to support this format

**Comment by DarkLight1337** [comment]
It has already been added in #5908 - expect to see it in the next release which is [scheduled for Monday](https://github.com/vllm-project/vllm/issues/5806) as of this writing.
