### ISSUE TITLE
加载Baichuan7B为什么占用这么大的显存？Why does loading Baihuan7B take up so much graphics memory?

### ISSUE THREAD

**Issue by fengenbao** [vllm-project/vllm#601]

**Comment by fengenbao** [comment]
我在单卡3090 24G上加载服务，为什么占用显存能达到91%？太这也太大了
Why can I load services on a single card 3090 24G and occupy 91% of the graphics memory? This is too big.
![image](https://github.com/vllm-project/vllm/assets/57557769/e4d59301-ec9f-49cf-88dd-703e8b2983ef)

**Comment by BaiMoHan** [comment]
because vllm will allocate 90% GPU memory for model inference and kv_cache blocks.

**Comment by tongjingqi** [comment]
https://github.com/vllm-project/vllm/blob/0e163fce18594c7e29dc5a143dd6b33d213fcbf3/vllm/entrypoints/llm.py#L82
把链接中文件init的函数默认参数gpu_memory_utilization: float = 0.9,
比如改成0.5，相当于一开始占用你90%的显存，现在就只占用50%的显存了
