### ISSUE TITLE
[Usage]: Load local model from local path

### ISSUE THREAD

**Issue by xiaoyu-work** [vllm-project/vllm#6012]
### How would you like to use vllm

Does vLLM support huggingface local pytorch pt model or onnx model? How can I load them in both offline python code  and OpenAI Completions API? I can see an error saying `config.json` file was not found. Does vllm only support vanilla hf model?

**Comment by DarkLight1337** [comment]
You could load local models, but the file structure should follow that of a standard HuggingFace model repo.

**Comment by xiaoyu-work** [comment]
Do you know how can I convert pt model or onnx model to huggingface model format? Seems I need to register it to huggingface first: https://discuss.huggingface.co/t/convert-pytorch-model-to-huggingface-transformer/16965

**Comment by DarkLight1337** [comment]
Sorry for very late reply, the model just needs to inherit from `PreTrainedModel`. You can see some example conversion scripts like https://github.com/huggingface/transformers/blob/main/src/transformers/models/llava_next/convert_llava_next_weights_to_hf.py

**Comment by hmellor** [comment]
@xiaoyu-work is your issue resolved?

**Comment by xiaoyu-work** [comment]
> @xiaoyu-work is your issue resolved?

Yes i got the answer for this question. Thanks!
