### ISSUE TITLE
How to use Offline Batched Inference to run multi chat.

### ISSUE THREAD

**Issue by shatealaboxiaowang** [vllm-project/vllm#6022]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

Hi, I want to use  Offline Batched Inference to run multi chat. every prompt in prompts is as: 
[
 {"role":"system", "content":"You are a helpful assistance."},
 {"role":"user", "content":" text"}
],
what should i do ?

**Comment by mgoin** [comment]
Hi @shatealaboxiaowang you should simply apply chat templating through your HF tokenizer with tokenize=False so you simply get a formatted string back for your multichat list https://huggingface.co/docs/transformers/main/en/chat_templating

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")

chat = [
  {"role": "user", "content": "Hello, how are you?"},
  {"role": "assistant", "content": "I'm doing great. How can I help you today?"},
  {"role": "user", "content": "I'd like to show off how chat templating works!"},
]

tokenizer.apply_chat_template(chat, tokenize=False)
# "<s>[INST] Hello, how are you? [/INST]I'm doing great. How can I help you today?</s> [INST] I'd like to show off how chat templating works! [/INST]"
```

The offline batched interface expects to receive already formatted prompts.
