### ISSUE TITLE
[Usage]: Gemma-2-9b is not supported

### ISSUE THREAD

**Issue by algeller** [vllm-project/vllm#6026]
### Your current environment
This is my vllm versions
vllm                              0.5.0.post1
vllm-flash-attn                   2.5.9
vllm-nccl-cu11                    2.18.1.0.4.0

### How would you like to use vllm

I want to run inference of a gemma-2-9b, which appears in the supported models list in the website.

This is the code

```
from vllm import LLM, SamplingParams
model_name = "google/gemma-2-9b"  # You can change this to any other supported model
llm = LLM(model=model_name, dtype=torch.float16, device="auto", tensor_parallel_size=2)

```

I'm getting the error:

(VllmWorkerProcess pid=225845) ERROR 07-01 10:50:45 multiproc_worker_utils.py:226] ValueError: Model architectures ['Gemma2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MistralModel']

**Comment by w013nad** [comment]
It's been merged into main already but hasn't been part of a release yet. If you want to run it you'll have to build from source.

**Comment by mgoin** [comment]
This will be supported in the next release this week https://github.com/vllm-project/vllm/issues/5806

**Comment by xinzaifeixiang1992** [comment]
> It's been merged into main already but hasn't been part of a release yet. If you want to run it you'll have to build from source.

how to build from source, could you please teach me the method?

**Comment by leo-prem** [comment]
> > It's been merged into main already but hasn't been part of a release yet. If you want to run it you'll have to build from source.
> 
> how to build from source, could you please teach me the method?

You can find it in the vLLM [docs](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source).
