### ISSUE TITLE
为什么百川7b的模型生成文本的长度这么短？怎么调节参数使得生成的文本比较长，生成完整的一段话Why is the length of text generated by the Baichuan 7b model so short? How to adjust parameters to make the generated text longer and generate a complete paragraph

### ISSUE THREAD

**Issue by fengenbao** [vllm-project/vllm#603]
![image](https://github.com/vllm-project/vllm/assets/57557769/fc4c7cfa-2686-4c18-8dfb-7b9923f163b0)

**Comment by BaiMoHan** [comment]
You should fill more params.You can get more information from https://github.com/vllm-project/vllm/blob/58a072be15a4e36bee006d1c9a962e527819cf18/vllm/sampling_params.py#L14

**Comment by a1164714** [comment]
```python
llm.generate(prompts,sampling_params,max_tokens=512)
```
