### ISSUE TITLE
[Bug]: identical branches in csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu

### ISSUE THREAD

**Issue by stevegrubb** [vllm-project/vllm#6030]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

At  https://github.com/vllm-project/vllm/blob/main/csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu#L296   there is an if statement with an else. Both branches are the same. The comment preceding it leads me to believe they were intended to be very different. IOW, this looks like a copy and paste without updating one or the other. I don't know the theory to suggest a fix. But I can just say this looks suspicious.

**Comment by robertgshaw2-neuralmagic** [comment]
@alexm-neuralmagic

**Comment by tlrmchlsmth** [comment]
FWIW, here is the equivalent code from the original dense marlin:

https://github.com/vllm-project/vllm/blob/80ca1e6a3a28a0373dc00c5b4fe956c16de952fa/csrc/quantization/marlin/dense/marlin_cuda_kernel.cu#L364-L372

versus the lines in question here:
https://github.com/vllm-project/vllm/blob/80ca1e6a3a28a0373dc00c5b4fe956c16de952fa/csrc/quantization/marlin/sparse/marlin_24_cuda_kernel.cu#L293-L302

**Comment by alexm-neuralmagic** [comment]
@stevegrubb this is a leftover from a copy-paste from the original (dense) marlin that had different branches. We have tests to verify all of these cases inside test_marlin_gemm.py that verify both dense and sparse and group_size == -1 and other group_sizes as well.

**Comment by stevegrubb** [comment]
OK. Just wanted to call attention to this in case it was missed. If it doesn't matter, I'd get rid of the 'if' and call it unconditionally and delete the else side.

**Comment by stevegrubb** [comment]
I'll send  PR on this. But before I do, I'd like to confirm the right thing is to remove the if/else instead of changing the / to a %.

**Comment by alexm-neuralmagic** [comment]
@stevegrubb it is ok to remove the if/else. Just check that all test_marlin_gemm.py tests pass

**Comment by mgoin** [comment]
Resolved
