### ISSUE TITLE
Memory usage decreases as batch size increases

### ISSUE THREAD

**Issue by jiefang27** [vllm-project/vllm#606]
Hi all,

I am running OPT-6.7B [https://huggingface.co/facebook/opt-6.7b] on an A100 GPU with 80GB.

The 'gpu_memory_utilization' is 0.9 (as default) and I am using `torch.cuda.memory_allocated` to get the GPU memory that's allocated.

For input length and output length of 40 and 156, respectively, this is the allocated memory (GB) I see across batch sizes:
Batch | Allocated memory
2        | 72.8 GB
4        | 72.68 GB 
8        | 72.68 GB
16      | 72.55 GB
32      | 72.18 GB
64      | 71.68 GB
128    | 70.55 GB
256    | 68.18 GB
512    | 63.68 GB
For smaller batch sizes, the allocated memory is around 80 * 0.9 as expected, but it becomes smaller as the batch size increases.

Is there a reason to allocate less memory for larger batch sizes? Is the unallocated memory used for some other purposes?
Following the discussion in other issues, the allocated memory for engine includes both the model for inference and KV cache.
With the allocate memory numbers above, does vLLM allocates a smaller KV cache when batch size is bigger (where it is supposed to have larger KV cache)?

**Comment by rolandtannous** [comment]
interesting, is this continuous batching mode or static batching?

**Comment by jiefang27** [comment]
I experimented with offline model (both single GPU and multi-GPUs) and static batching. I am not sure if the batching mode (continuous v.s. static) makes a difference here, since I am just measuring the memory that's being allocated after instantiating the LLM engine.

**Comment by zhuohan123** [comment]
> I experimented with offline mode (both single GPU and multi-GPUs) and static batching. I am not sure if the batching mode (continuous v.s. static) makes a difference here, since I am just measuring the memory that's being allocated after instantiating the LLM engine.

Did you set the init parameter of the `LLM` class differently for your different experiments? Do all experiments allocate the same number of `# GPU Blocks` (should be in the log)? Different init parameters may cause different results of memory profiling and thus lead to different memory usage.

**Comment by zhuohan123** [comment]
Feel free to re-open the issue if there are any other issues.
