### ISSUE TITLE
[Feature]: support Ascend 910B in the future

### ISSUE THREAD

**Issue by jkl375** [vllm-project/vllm#6066]
### 🚀 The feature, motivation and pitch

Do you have plans to support Ascend 910B in the future？

**Comment by mgoin** [comment]
Hi @jkl375 we very much accept contributions for new hardware targets! Could you share any resources in terms of Ascend's support for PyTorch to make it easier to scope for vLLM?

**Comment by jkl375** [comment]
OK, Do you have any hardware resources for Ascend 910b? https://www.hiascend.com/developer/ascendhub/detail/bcf86497fd874004b3b0a6e5d533081e
this is the docker image for ascend llm models, witch have torch_npu.
https://gitee.com/ascend/pytorch This repo is ascend Extension for PyTorch.
