### ISSUE TITLE
When using the same prompt and greedy sampling params, the output is not same before and after the two times

### ISSUE THREAD

**Issue by tarnish233** [vllm-project/vllm#608]

**Comment by BaiMoHan** [comment]
Could you please give more information, such as your params?

**Comment by Huffman-cotdom** [comment]
> 

sampling_params = SamplingParams(
    best_of=1,
    temperature=0.0,
    top_p=1,
    top_k=-1,
    use_beam_search=False,
    max_tokens=256,
    presence_penalty=0,
    frequency_penalty=0,
)

**Comment by BaiMoHan** [comment]
> > 
> 
> sampling_params = SamplingParams( best_of=1, temperature=0.0, top_p=1, top_k=-1, use_beam_search=False, max_tokens=256, presence_penalty=0, frequency_penalty=0, )

try to set use_beam_search=True,

**Comment by irasin** [comment]
@Huffman-cotdom 
If you want to use greedy-search, you need to set `top_k = 1`

**Comment by Huffman-cotdom** [comment]
> > > 
> > 
> > 
> > sampling_params = SamplingParams( best_of=1, temperature=0.0, top_p=1, top_k=-1, use_beam_search=False, max_tokens=256, presence_penalty=0, frequency_penalty=0, )
> 
> try to set use_beam_search=True,

@BaiMoHan 
<img width="559" alt="image" src="https://github.com/vllm-project/vllm/assets/63766688/c86f6f78-56a0-40f6-b52a-9d34d515c9bd">

**Comment by Huffman-cotdom** [comment]
> 

@irasin  if set `top_k=1`，I get an error
<img width="924" alt="image" src="https://github.com/vllm-project/vllm/assets/63766688/0ae454ed-41a4-4631-9f97-9ae36c84426f">
<img width="583" alt="image" src="https://github.com/vllm-project/vllm/assets/63766688/de0aa6d4-4bcf-4776-83a6-17ad265894f6">

**Comment by irasin** [comment]
@Huffman-cotdom ，try don't set `temperature=0.0`

**Comment by gesanqiu** [comment]
> > 
> 
> sampling_params = SamplingParams( best_of=1, temperature=0.0, top_p=1, top_k=-1, use_beam_search=False, max_tokens=256, presence_penalty=0, frequency_penalty=0, )

Your params are right for greedy search, and if you set temperature is 0, it should have same output.
Which model you are using now? I test on vicuna-7b with this params several times, it's output just the same.

**Comment by Huffman-cotdom** [comment]
> > > 
> > 
> > 
> > sampling_params = SamplingParams( best_of=1, temperature=0.0, top_p=1, top_k=-1, use_beam_search=False, max_tokens=256, presence_penalty=0, frequency_penalty=0, )
> 
> Your params are right for greedy search, and if you set temperature is 0, it should have same output. Which model you are using now? I test on vicuna-7b with this params several times, it's output just the same.

Model: I used https://github.com/ymcui/Chinese-LLaMA-Alpaca as the base model, and fine-tuned it on my dataset.
Test data: 400 different prompts
Results: When using Hugging Face's greedy search, I got the same results. However, when using vllm's greedy search, out of 400 prompts, 40 of them yielded different results.

**Comment by LiuXiaoxuanPKU** [comment]
Thanks for letting us know. Could you provide the minimum code to reproduce the bug, we are happy to fix it!

**Comment by Fangzhou-Ai** [comment]
I also noticed this issue recently, it seems that vllm cannot always agree with hugging face results. Vllm occasionally gave strange or even wrong results compared with hugging face, I'll try to attach a snippet later to stably repeat the error with vicuna-7B model.

**Comment by Fangzhou-Ai** [comment]
Hi Xiaoxuan @LiuXiaoxuanPKU , thank you for your quick reply, here I attached a snippet to demonstrate such discrepencies.

```python
from vllm import LLM, SamplingParams
import contextlib
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from typing import List

def vllm(prompt : str):
  with contextlib.nullcontext():
    llm = LLM("lmsys/vicuna-7b-v1.3")
    sampling_params = SamplingParams(max_tokens=128, temperature=0) # greedy sampling
    print(prompt, llm.generate(prompt, sampling_params)[0].outputs[0].text)


def huggingface(prompt : str):
  model = AutoModelForCausalLM.from_pretrained("lmsys/vicuna-7b-v1.3").cuda()
  tokenizer = AutoTokenizer.from_pretrained("lmsys/vicuna-7b-v1.3", trust_remote_code=True)
  input_ids = tokenizer.encode(prompt, return_tensors="pt").cuda()
  output = model.generate(input_ids, max_length=128, do_sample=False)
  print(tokenizer.decode(output[0], skip_special_tokens=True))



if __name__ == "__main__":
  # Expect both results are reasonable but not identical
  # prompt = "Once upon a time,"

  # Expect vllm rusults are wrong but huggingface results are correct
  prompt = "San Francisco is a city that"

  vllm(prompt)
  huggingface(prompt)
```

From this simple test program, the outputs are
- vllm: San Francisco is a city that is known for its beauty, culture, and diversity. It is a place where people from all over the world come to visit and experience all that it has to offer. Whether you are interested in exploring the city' The 2018-2023 World Outlook for Men's and Boys' Cut and Sew Apparel
This study covers the world outlook for men's and boys' cut and sew apparel across more than 190 countries. For each year reported, estimates are given for the latent demand, or potential industry earnings (P.I.
- huggingface: San Francisco is a city that is known for its beauty, its history, and its unique culture. It is a place that is full of life and energy, and it is a place that is loved by people all over the world. Whether you are a resident of San Francisco or a visitor, there is always something to see and do in this amazing city.
One of the most popular attractions in San Francisco is the Golden Gate Bridge. This iconic bridge is a symbol of the city and it is one of the most recognizable landmarks in the world. The Golden Gate Bridge is a must-see attraction for

Obviously there's something wrong in the middle for vllm.

**Comment by syskn** [comment]
Might be related: https://github.com/vllm-project/vllm/issues/641

When this (uninitialized data) is problematic, it usually generates nan or -inf and either crashes or garbles the output completely. However it seems like there are cases where it passes and slightly (and sneakily) affects the output.

**Comment by Fangzhou-Ai** [comment]
Yes we also found that's part of the reason before. But my example is tested with the latest commit fixing the mentioed bug here, and the inconsistency still exists.

**Comment by duihuhu** [comment]
So, is there any progress on this issue? I seem to have encountered the same problems，thanks。

**Comment by imiraoui** [comment]
Same here!

**Comment by souvik3333** [comment]
Also getting into the same error.

**Comment by qeternity** [comment]
This is a rather prevalent issue and trivial to replicate. Has anyone made any progress in understanding it?

**Comment by afeldman-nm** [comment]
jw was this issue seen even without parallelism (TP=1,PP=1) or with parallelism?

**Comment by mgutierrezc** [comment]
Has anyone figured out how to fix the issue?

**Comment by TomasAndersonFang** [comment]
Just want to know whether this issue has been fixed? Since I met the same problem when using greedy decoding on deepseek-7b

**Comment by IgorZan** [comment]
Problem still exists.
