### ISSUE TITLE
Create CI jobs for Power(ppc64le)

### ISSUE THREAD

**Issue by DiptiKri02** [vllm-project/vllm#6095]
### 🚀 The feature, motivation and pitch

Hi team, I am from the IBM Power porting team and have been assigned the task to create the required CI jobs for Power(ppc64le), as this PR has been merged:
https://github.com/vllm-project/vllm/pull/5652
 
I have looked at the existing jobs, but its not very clear which jobs will have to be added for Power. Can you help me there?
 
Thanks.

**Comment by simon-mo** [comment]
Hi! Please connect with me (email in profile) and @njhill (IBM Research) with your IBM email so we can discuss the level of CI and how to add it. (cc @khluu).

**Comment by DiptiKri02** [comment]
Hi Simon/Nick,
Please let us know with reference to this issue in Support CPU inference with VSX PowerPC ISA by ChipKerchner · Pull Request #5652 · vllm-project/vllm (github.com)<https://github.com/vllm-project/vllm/pull/5652/files> PR, which jobs needs to be added for power.
Thanks,
Dipti
From: Simon Mo ***@***.***>
Sent: Wednesday, July 3, 2024 10:53 PM
To: vllm-project/vllm ***@***.***>
Cc: Dipti Kumari ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [vllm-project/vllm] Create CI jobs for Power(ppc64le) (Issue #6095)

Hi! Please connect with me (email in profile) and @njhill (IBM Research) with your IBM email so we can discuss the level of CI and how to add it. (cc @khluu). — Reply to this email directly, view it on GitHub, or unsubscribe. You are


Hi! Please connect with me (email in profile) and @njhill<https://github.com/njhill> (IBM Research) with your IBM email so we can discuss the level of CI and how to add it. (cc @khluu<https://github.com/khluu>).
