### ISSUE TITLE
Support BLOOM

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#61]
BLOOM is an open-source LLM developed by BigScience. The BLOOM models have achieved high rankings in HuggingFace downloads. It'd be great to have these models in our catalog.

**Comment by wangkuiyi** [comment]
+1 - looking forward to Bloom in vLLM

**Comment by ruidongtd** [comment]
+1

**Comment by sharlec** [comment]
+1

**Comment by createmomo** [comment]
+1

**Comment by nuass** [comment]
+1

**Comment by wengrx** [comment]
+1

**Comment by rossbucky** [comment]
+1

**Comment by bsabri** [comment]
+1

**Comment by WoosukKwon** [comment]
@wangkuiyi @ruidongtd @createmomo @nuass @wengrx @rossbucky @bsabri We've just added BLOOM. You can immediately use it by [installing vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source).

**Comment by createmomo** [comment]
Super nice~

Woosuk Kwon ***@***.***>于2023年7月4日 周二04:15写道：

**Comment by Hukongtao** [comment]
I used vLLM try to speed up my BLOOM model, but found that the speed did not improve. Moreover, the memory usage of vLLM is higher, what may be the reason?  
vLLM:  
![ad66d7b4-8f0f-46d7-85f0-60d6f1dcce86](https://github.com/vllm-project/vllm/assets/16505966/88fa69f2-9093-4c6c-bcf0-f64d034cae7f)
HF:  
![778571a7-db1e-44ba-9dce-2864c7b598e9](https://github.com/vllm-project/vllm/assets/16505966/7eeae285-6250-42e8-8ef4-45cf9c38d58e)

**Comment by WoosukKwon** [comment]
Hi @Hukongtao, thanks for trying out vLLM! The memory usage is high because vLLM pre-allocates the space to store KV cache. You can configure the memory usage by tuning the `gpu_memory_utilization` parameter, which is 0.9 (i.e., 90% of your GPU memory capacity) by default.

Speaking of the speed, could you share the model (size) you are using and also your benchmark results?

**Comment by Hukongtao** [comment]
@WoosukKwon Thanks for your replying. Great jobs!
