### ISSUE TITLE
tensor parallel question on multi-GPUs and API deployment issue

### ISSUE THREAD

**Issue by BaileyWei** [vllm-project/vllm#610]
I tried this `NCCL_IGNORE_DISABLED_P2P=1 CUDA_VISIBLE_DEVICES=1,5,6,7 python vllm_inference.py --model_name model_hub/llama2-7B-chat-hf --tp_size 4`
and found that the memory usage on GPUs was like this
![image](https://github.com/vllm-project/vllm/assets/106091458/ce3ae834-a43a-4e48-963f-aff280f277d7)
This is just a 7B model, did I apply TP strategy incorrectly? 

Also, I'm very confused that the inference can work on a single GPU actually,
but when I try to start an API using llmengine，it always stuck in the process reporting blocks of gpu and cpu like this,
![image](https://github.com/vllm-project/vllm/assets/106091458/d3fc433b-3813-4ac7-86d0-fd33aa7e4123)
that's the reason why I tried tensor parallel in API deployment.

**Comment by nootums** [comment]
Hey did you find a fix? I'm facing the same issue.
<img width="638" alt="image" src="https://github.com/vllm-project/vllm/assets/65669681/470ad9c3-f954-498d-a53a-0b42d455dd72">
I'm trying to load llama-2-7b-chat-hf on 4 GPUs and VRAM usage is stuck at this.

**Comment by BaileyWei** [comment]
> Hey did you find a fix? I'm facing the same issue. <img alt="image" width="638" src="https://user-images.githubusercontent.com/65669681/257130198-470ad9c3-f954-498d-a53a-0b42d455dd72.png"> I'm trying to load llama-2-7b-chat-hf on 4 GPUs and VRAM usage is stuck at this.

Not yet, did u try to load the model by using the LLM Engine? Can I have a look at ur command and inference code?

**Comment by nootums** [comment]
> > Hey did you find a fix? I'm facing the same issue. <img alt="image" width="638" src="https://user-images.githubusercontent.com/65669681/257130198-470ad9c3-f954-498d-a53a-0b42d455dd72.png"> I'm trying to load llama-2-7b-chat-hf on 4 GPUs and VRAM usage is stuck at this.
> 
> Not yet, did u try to load the model by using the LLM Engine? Can I have a look at ur command and inference code?

<img width="1247" alt="image" src="https://github.com/vllm-project/vllm/assets/65669681/c51193fc-1e63-4b20-b8c7-4bf4cd036edf">
This is how I'm loading the model. I downloaded the model from huggingface and all the model files, config and tokenizer is present in the directory location passed in the command.

**Comment by zhuohan123** [comment]
@BaileyWei Hey thank you for reporting this. Is it possible for you to locate which line does the code stuck on? You can try to insert prints in the code and see where does the code stuck on.

**Comment by yanmengxiang1** [comment]
@zhuohan123 @nootums @BaileyWei @tmm1 @zxdvd 
Hi.An error to inference Llama-70b-chat using 16 gpus. The gpus is in one machine. https://github.com/vllm-project/vllm/issues/930
Do you have some ideas,thanks!

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by man2machine** [comment]
I'm finding a similar issue, as in the engine hangs on initialization when using multiple GPUs using tensor parallel, even though there are GPUs available.
