### ISSUE TITLE
[Doc]: Is the `prompts` feed into `LLM` will be automatically adding chat_template or not ?

### ISSUE THREAD

**Issue by hxhcreate** [vllm-project/vllm#6101]
### 📚 The doc issue

I was wondering Is the `prompts` feed into LLM will be automatically adding chat_template or not ?

If so, how to choose the chat_template used

**Comment by DarkLight1337** [comment]
No, you currently have to apply the chat template manually.

There is an active PR (#5049) that works on adding chat template to `LLM` natively.
