### ISSUE TITLE
Multi-GPU error

### ISSUE THREAD

**Issue by nootums** [vllm-project/vllm#612]
While using tensor_parallel_size argument to load the vllm model, I was facing the issue in #557 stating something related to network address retrieval. According to [this comment](https://github.com/vllm-project/vllm/issues/570#issuecomment-1650973012) on #570 I trying building vllm from source and running it then.

The error goes away, but it does not load the model and gets stuck on that cell.

Is there any way I can get things working on multiple GPUs? I am able to run llama-2-7b, but in order to run llama-2-13b, I'll need to run it on multiple GPUs.

**Comment by Tarun3679** [comment]
I am facing the same issue as well, But when I am trying to import the LLM - I am not able to import the module and getting an error related to - AttributeError: 'NoneType' object has no attribute 'fs'

**Comment by 92hyungjun** [comment]
> I am facing the same issue as well, But when I am trying to import the LLM - I am not able to import the module and getting an error related to - AttributeError: 'NoneType' object has no attribute 'fs'

Try using this command.
```
pip install --upgrade ray 
pip install --upgrade pyarrow
pip install pandas
```

**Comment by Tarun3679** [comment]
Did it work for you using those commands!?

**Comment by 92hyungjun** [comment]
> Did it work for you using those commands!?

I had the same problem and I solved it this way.

**Comment by yanmengxiang1** [comment]
@zhuohan123 @Tarun3679 @nootums @92hyungjun @tmm1 
Hi.An error to inference Llama-70b-chat using 16 gpus. The gpus is in one machine. #930
Do you have some ideas,thanks!

**Comment by chenxiang204** [comment]
@nootums How about your dealing with this problem?

**Comment by nootums** [comment]
> @nootums How about your dealing with this problem?

Hi, I'm now running on an A10G GPU with 24GB vram. I'm not using multi-gpu at the moment. I did manage to find a fix for my earlier build. For me, ray was not installed in the system, and it was giving errors because of that. Hope this helps.
