### ISSUE TITLE
[Usage]: vllm现在支持embedding输入吗，没有发现相关接口

### ISSUE THREAD

**Issue by zhanghang-official** [vllm-project/vllm#6128]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by dongxiaolong** [comment]
You can follow below example.
https://github.com/vllm-project/vllm/blob/main/examples/openai_embedding_client.py
It's seems it support the langauge embedding model, such like mistral embedding model.

**Comment by dongxiaolong** [comment]
> You can follow below example. https://github.com/vllm-project/vllm/blob/main/examples/openai_embedding_client.py It's seems it support the langauge embedding model, such like mistral embedding model.

sorry, I had been  confused, vllm doesn't support embedding input.
