### ISSUE TITLE
[Feature]: Multi lora on multi gpus

### ISSUE THREAD

**Issue by jiuzhangsy** [vllm-project/vllm#6133]
### 🚀 The feature, motivation and pitch

I need to infer using vLLM across multiple GPUs, and manage multiple LoRA.Can anyone help? Thanks very much

**Comment by jeejeelee** [comment]
This [example](https://github.com/vllm-project/vllm/blob/main/examples/multilora_inference.py) i s a great starting point, and you can set ` tensor_parallel_size` for multiple GPUs inference. For example:
```python
   llm = vllm.LLM(
        MODEL_PATH,
        enable_lora=True,
        max_num_seqs=16,
        max_loras=2,
        trust_remote_code=True,
        gpu_memory_utilization=0.3,
        tensor_parallel_size=4,
    )
```
