### ISSUE TITLE
[Feature]: Integrate new backend

### ISSUE THREAD

**Issue by XDaoHong** [vllm-project/vllm#6151]
### 🚀 The feature, motivation and pitch

Currently, vLLM supports TPU and XPU. We would like to use vLLM on new backend.
What are the community's suggestions or plans for integrating new devices? 

### Alternatives

There may be the following two methods:
#### 1. Add new backend by modify codebase
Such as XPU, Added XPUExecutor, XPUWorker, XPUModelRunner to isolate XPU backend with others.
How the community reviews new backend integrations?

#### 2. Provide Out-of-Tree backend registration
Integrate a backend without modifying the vLLM codebase.
We use PrivateUse1 to integrate new backend in PyTorch, and expected to integrate new backend in vllm in the similar way.

maybe need to do:
* Add privateuse1 in DeviceConfig
* Provide ExecutorRegistry register CustomExecutor, and create instances of CustomWorker and CustomModelRunner in CustomExecutor.
* Provide forward register in CustomOp, and dispatch_forward in forward_privateuse1 if use new backend.
 * Provide AttentionBackend register, and add new branch for new backend.

**Comment by XDaoHong** [comment]
@WoosukKwon cc

**Comment by XDaoHong** [comment]
您的邮件已收到，我会尽快处理！.

**Comment by XDaoHong** [comment]
您的邮件已收到，我会尽快处理！.

**Comment by hmellor** [comment]
Closing because:
- Inactivity
- Many other backends have been added
