### ISSUE TITLE
we want to release access to a preview build of out model on serverles computing for runpod

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [vllm-project/vllm#617]
i was wondering if there were any examples of a preconfigured dockerfile i could work from? im worried ill miss something setting it up myself

**Comment by imrohankataria** [comment]
@Alignment-Lab-AI
 did you find any?

**Comment by TomExMachina** [comment]
> @Alignment-Lab-AI did you find any?

I bet he got it. Oh well. It can't be too hard to get working. Just start with an existing serverless template and go from there. I'll share if I get it working.

**Comment by Sirri69** [comment]
@TomExMachina Bro you got it??
