### ISSUE TITLE
[Usage]: solve problem like "Found no NVIDIA driver on your system." in WSL2

### ISSUE THREAD

**Issue by HelloCard** [vllm-project/vllm#6184]
### Your current environment

In WSL2, after I update vllm from v0.5.0.post1 to v0.5.1, all model unable to load immediately.
After extensive troubleshooting, I discovered the cause.
In here: https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl
[you need a kernel version of 5.10.43.3 or higher. You can check the version number by running the following command in PowerShell: wsl cat /proc/version]
and I get "Linux version 5.10.16.3-microsoft-standard-WSL2 (oe-user@oe-host)"
So I look here and use update command: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#getting-started-with-cuda-on-wsl-2
Then I get: "Linux version 5.15.153.1-microsoft-standard-WSL2 (root@941d701f84f1)"
Everything is fine now, except for my 2080ti graphics card which does not support FP8 quantization.

**Comment by youkaichao** [comment]
any remaining issue?
