### ISSUE TITLE
[Bug]: No end point available after model is fully loaded

### ISSUE THREAD

**Issue by hassanzadeh** [vllm-project/vllm#6194]
### Your current environment

```text
vllm==0.5.0.post1
vllm-flash-attn==2.5.9
Python 3.10.11
```

### 🐛 Describe the bug

Hey Guys,
I loaded a Llama-3-70B with vllm, once the model is loaded, I get the following message, which I assume means it is ready to take the requests,
```
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```
However, no end point is available, I tried both / and /generate, both giving me 404 error, here is the log printed by vllm:
```
INFO:     127.0.0.1:55504 - "GET / HTTP/1.1" 404 Not Found
INFO 07-07 20:12:44 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO:     127.0.0.1:59820 - "GET /generate HTTP/1.1" 404 Not Found
INFO 07-07 20:12:54 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO:     127.0.0.1:53798 - "POST /generate HTTP/1.1" 404 Not Found
```

**Comment by youkaichao** [comment]
where do you get the `/generate` endpoint?

if you are running openai server, the endpoint should be `/v1/models` stuff.

**Comment by hassanzadeh** [comment]
Oh I see, so the generate would be /v1/models/generate ?

**Comment by youkaichao** [comment]
if you start an openai server, you should use openai client to interact with it. I don't think you should care about the specific endpoints.

**Comment by hassanzadeh** [comment]
Oh I see, thanks, do you have an example with open ai client?
Here is how I launch the server: python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8000 --served-model-name $NAME --model ....

**Comment by youkaichao** [comment]
it is https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#openai-compatible-server
