### ISSUE TITLE
[Usage]: Is there a way to make the results of two different calls to VLLM with temperature > 0 consistent?

### ISSUE THREAD

**Issue by Some-random** [vllm-project/vllm#6197]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I know that setting the temperature to 0 ensures that the results of two different calls with the same input will be identical. Is there a way to ensure consistent results when the input is different, perhaps by using a seed?

**Comment by devdev999** [comment]
Yes, add the seed as part of your params.

**Comment by Some-random** [comment]
Hi @devdev999, thanks for your reply! However, I've tried setting seed but it's not working

**Comment by Some-random** [comment]
Is there an update on this issue?
