### ISSUE TITLE
Is there a way to add classifier free guidance (CFG) to vllm while maintaining super fast inference?

### ISSUE THREAD

**Issue by salahzoubi** [vllm-project/vllm#620]
I've seen there's recently been a [PR](https://github.com/huggingface/transformers/pull/24654) that incorporates classifier-free guidance to HF model.generate function and it's super useful for generation. Is there a way to incorporate this in to the vllm sampling mechanism?

**Comment by LouisCastricato** [comment]
Following up on this

**Comment by unyqhz** [comment]
Following up on this

**Comment by Vermeille** [comment]
What would it take to implement it?

**Comment by Vermeille** [comment]
ping
