### ISSUE TITLE
[Usage]: 目前vllm 是否支持多模态的api调用？是否支持minicpm-v2.5呢？

### ISSUE THREAD

**Issue by weiminw** [vllm-project/vllm#6209]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by DarkLight1337** [comment]
> 目前vllm 是否支持多模态的api调用？

Please refer to the FAQ [here](https://docs.vllm.ai/en/latest/serving/faq.html).

> 是否支持minicpm-v2.5呢？

No, it is not supported yet. The basic MiniCPM-V is still a work in progress (#4087).

**Comment by weiminw** [comment]
> > 目前vllm 是否支持多模态的api调用？
> 
> Please refer to the FAQ [here](https://docs.vllm.ai/en/latest/serving/faq.html).
> 
> > 是否支持minicpm-v2.5呢？
> 
> No, it is not supported yet. The basic MiniCPM-V is still a work in progress (#4087).

great thanks to your quik response
