### ISSUE TITLE
[Feature]: FlashInfer + Gemma 2 for AMD GPU

### ISSUE THREAD

**Issue by erkintelnyx** [vllm-project/vllm#6218]
This could be question rather than a feature request.

flashinfer is not supported for AMD GPUs and it's not currently planned until a [later version](https://github.com/flashinfer-ai/flashinfer/issues/19), 

Is there a way to run Gemma 2 models on AMD (I'm getting `ValueError: Please use Flashinfer backend for models withlogits_soft_cap (i.e., Gemma-2). Otherwise, the output might be wrong. Set Flashinfer backend by export VLLM_ATTENTION_BACKEND=FLASHINFER.` even though I set the env var. I wanted to give it a try and remove the [validation](https://github.com/vllm-project/vllm/blob/v0.5.1/vllm/attention/selector.py#L137-L147) but it fails with None type because of [import error](https://github.com/vllm-project/vllm/blob/v0.5.1/vllm/attention/backends/flashinfer.py#L4-L11)) ?

Or is there an alternative that can be used?

**Comment by lonngxiang** [comment]
error：
multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks: Please use Flashinfer backend for models withlogits_soft_cap (i.e., Gemma-2). Otherwise, the output might be wrong. Set Flashinfer backend by export VLLM_ATTENTION_BACKEND=FLASHINFER.

**Comment by LiuXiaoxuanPKU** [comment]
> vLLM API server version 0.5.1 error： multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks: Please use Flashinfer backend for models withlogits_soft_cap (i.e., Gemma-2). Otherwise, the output might be wrong. Set Flashinfer backend by export VLLM_ATTENTION_BACKEND=FLASHINFER.

Is this AMD or Nvidia GPU? If it's Nvidia GPU with compute capability >=8.0, just follow the error message by `export VLLM_ATTENTION_BACKEND=FLASHINFER`.

**Comment by sparsh35** [comment]
Hi , how to run it with GPU capability 7.5 .i.e, Turing T4 gpus , is there any option to turn this warning off , I want to run Gemma2 9b , i think this doesn't have that big of a problem with capping as compared to 27b

**Comment by twright8** [comment]
> I just commented lines 688-694 in /vllm/worker/model_runner.py and not use flashinfer. saw no performance difference.

Which lines exactly because these dont seem right myside? thankyou!

**Comment by sparsh35** [comment]
It would work only on Gemma 2 9b not for 27b
