### ISSUE TITLE
The document states that up to 3.5x higher throughput than TGI，I have my doubts

### ISSUE THREAD

**Issue by fengenbao** [vllm-project/vllm#623]
What is the TGI version you are comparing? This is not consistent with the benchmark results of some friends，I'm a bit confused.

https://zhuanlan.zhihu.com/p/645732302

![image](https://github.com/vllm-project/vllm/assets/57557769/9e9ce2bb-3179-463d-94b5-6447c5c84f79)

**Comment by LiuXiaoxuanPKU** [comment]
TGI numbers are before adding paged attention to their repo. The performance might be similar after they adding vllm's techniques. (after this [pr](https://github.com/huggingface/text-generation-inference/pull/516))
