### ISSUE TITLE
[Installation]: Gemma2 Installing Flash Infer `[rank0]: TypeError: 'NoneType' object is not callable`

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/vllm#6237]
The source of your error is that you have installed the wrong version of FlashInfer.

FlashInfer builds wheels for specific torch and cuda versions. vLLM v0.5.1 uses `torch==2.3` and `cuda==12.1`. So you will likely want to download the following wheel:

```bash
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3
```

**Comment by upskyy** [comment]
> [rank0]: TypeError: 'NoneType' object is not callable

> pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3

The same error occurred when I use `torch==2.3` and `vllm==0.5.1`, but when I installed it as above, the model was loaded.
However, a segmentation fault occurs.

**Comment by upskyy** [comment]
On the other hand, if you run `vllm/vllm-openai:latest` using Docker, it works well.

**Comment by ArlanCooper** [comment]
i still have this problem, can anyone help?

**Comment by cby-pku** [comment]
i still have this problem, can anyone help?

**Comment by robertgshaw2-neuralmagic** [comment]
Can you try again on latest release (v0.5.5). We have resolved some issues with Gemma in this version
