### ISSUE TITLE
[Bug]: Performance : slow inference for FP8 on L20 with 0.5.1(v0.5.0.post1 was fine)

### ISSUE THREAD

**Issue by garycaokai** [vllm-project/vllm#6240]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L20
GPU 1: NVIDIA L20
GPU 2: NVIDIA L20
GPU 3: NVIDIA L20
GPU 4: NVIDIA L20
GPU 5: NVIDIA L20
GPU 6: NVIDIA L20
GPU 7: NVIDIA L20

Nvidia driver version: 550.54.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flashinfer==0.0.8+cu121torch2.3
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] torchvision==0.18.0
[pip3] transformers==4.42.3
[pip3] triton==2.3.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	SYS	0-23,48-71	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	SYS	24-47,72-95	1		N/A
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	SYS	24-47,72-95	1		N/A
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	SYS	24-47,72-95	1		N/A
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	SYS	24-47,72-95	1		N/A
NIC0	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
```

### 🐛 Describe the bug

The inference speed of vllm0.5.1 with fp8 quantization on L20 is even slower than fp16.

qwen2-7b @ L20*1:
| vllm version | quant | speed | 
|:-----:|:-----:|:-----:| 
| 0.5.0 | fp8 | 59.41 token/s | 
| 0.5.0 | fp16 | 44.05 token/s | 
| 0.5.1 | fp8 | **26.50** token/s | 
| 0.5.1 | fp16 | 43.60 token/s |

**Comment by garycaokai** [comment]
llama3 8b
vllm version | quant | speed
-- | -- | --
0.5.0 | fp8 | 56.28 token/s
0.5.0 | fp16 | 41.72 token/s
0.5.1 | fp8 | **25.36** token/s
0.5.1 | fp16 | 41.38 token/s

**Comment by youkaichao** [comment]
cc @robertgshaw2-neuralmagic

**Comment by garycaokai** [comment]
qwen2-7b fp8 marlin kernel seems better on vllm v0.5.1

| gpu | speed | 
|:-----:|:-----:| 
| A30 | 70.09 token/s | 
| L20 | 68.81 token/s |

**Comment by tlrmchlsmth** [comment]
Hi @garycaokai, I'm trying to reproduce the issue on an L40, but no luck so far. Could you share the exact script and model you are using to run these benchmarks?

**Comment by garycaokai** [comment]
> Hi @garycaokai, I'm trying to reproduce the issue on an L40, but no luck so far. Could you share the exact script and model you are using to run these benchmarks?

```console
python3 -m vllm.entrypoints.openai.api_server \
    --served-model-name llama \
    --model neuralmagic/Meta-Llama-3-8B-Instruct-FP8 \
    --trust-remote-code \
    --tensor-parallel-size 1 \
    --max-model-len 8192 \
    --max-num-batched-tokens 32000 \
    --host 0.0.0.0 \
    --use-v2-block-manager \
    --port 8360

client use postman
```

**Comment by garycaokai** [comment]
> Thanks, could you also share how the client is querying the server? If you could reproduce the problem using `benchmarks/benchmark_serving.py`, that would be very helpful.
> 
> Also, did you build from source or install from pypi? If you built from source, could you share the version of `nvcc` that you built with? vLLM uses different FP8 kernels for Ada Lovelace on 12.4 and later.

I downloaded the docker image from https://hub.docker.com/r/vllm/vllm-openai, found the cuda version is 12.1, 
```console
$ docker pull vllm/vllm-openai:v0.5.1
 
$ nvidia-smi 
Thu Jul 11 06:56:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |

$ python3
>>> import torch
>>> print(torch.version.cuda)
12.1
 ```

**Comment by tlrmchlsmth** [comment]
Thank you. I think I see what's happening. 

Actually the relevant CUDA version for this particular issue is not the version that torch is compiled with (`torch.version.cuda`), but rather the CUDA version that vLLM's custom kernels were compiled with, which looks to be 12.4, seen here:
>| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |

I'll try to reproduce the problem and update here.

**Comment by garycaokai** [comment]
> ```
> vllm 0.5.1 fp8 benchmark
> ```

add the vllm 0.5.1 marlin kernel, and vllm 0.5.1 fp8 kernel performance data

**Comment by garycaokai** [comment]
> Thank you. I think I see what's happening.
> 
> Actually the relevant CUDA version for this particular issue is not the version that torch is compiled with (`torch.version.cuda`), but rather the CUDA version that vLLM's custom kernels were compiled with, which looks to be 12.4, seen here:
> 
> > | NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
> 
> I'll try to reproduce the problem and update here.



> Thank you. I think I see what's happening.
> 
> Actually the relevant CUDA version for this particular issue is not the version that torch is compiled with (`torch.version.cuda`), but rather the CUDA version that vLLM's custom kernels were compiled with, which looks to be 12.4, seen here:
> 
> > | NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
> 
> I'll try to reproduce the problem and update here.

your new version works fine~
```console
Traffic request rate: 30.0
100%|██████████| 300/300 [00:53<00:00,  5.59it/s]
============ Serving Benchmark Result ============
Successful requests:                     300       
Benchmark duration (s):                  53.70     
Total input tokens:                      62238     
Total generated tokens:                  60453     
Request throughput (req/s):              5.59      
Input token throughput (tok/s):          1158.99   
Output token throughput (tok/s):         1125.75   
---------------Time to First Token----------------
Mean TTFT (ms):                          114.53    
Median TTFT (ms):                        109.85    
P99 TTFT (ms):                           293.99    
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          155.10    
Median TPOT (ms):                        119.68    
P99 TPOT (ms):                           388.37    
---------------Inter-token Latency----------------
Mean ITL (ms):                           99.23     
Median ITL (ms):                         85.69     
P99 ITL (ms):                            453.83    
==================================================
```
