### ISSUE TITLE
[Misc]: fp8 support

### ISSUE THREAD

**Issue by enozhu** [vllm-project/vllm#6246]
### Anything you want to discuss about vllm.

when we use fp8 data type , we found  ffn gemm/atten prj  support real fp8 compute(this is supported on H20、L20),   but  Q*transopse(Key) or softmax * value  in attention dosen't support fp8 compute,  need to first dequantize fp8 to fp16/bf16, why? is there any plan to support attention fp8 compute?

**Comment by robertgshaw2-neuralmagic** [comment]
Yes. We are planning to do this via FlashInfer.

**Comment by enozhu** [comment]
Has it been proven that fp8 compute  has no impact on precision

**Comment by kuangdao** [comment]
@robertgshaw2-neuralmagic  vllm has already support FlashInfer and i find FlashInfer support Q*transopse(Key) or softmax * value in attention use fp8, so vllm already support attention  use fp8 ?
