### ISSUE TITLE
CPU offloading support

### ISSUE THREAD

**Issue by zhyncs** [vllm-project/vllm#627]
Hi vLLM genius @zhuohan123 @WoosukKwon 

My requirement is to run the inference of [Llama2 70b chat](https://huggingface.co/meta-llama/Llama-2-70b-hf) on a server with **2** A100 80G.

Currently, using the [fastchat.serve.model_worker](https://github.com/lm-sys/FastChat/blob/main/fastchat/serve/model_worker.py#L441) in [FastChat](https://github.com/lm-sys/FastChat) and specifying **num-gpus 2** can work, and we found that a portion of the weights are offloaded to the CPU. After reading HuggingFace's [documentation](https://huggingface.co/docs/accelerate/usage_guides/big_modeling), we found that when the [device_map defaults to auto](https://github.com/lm-sys/FastChat/blob/main/fastchat/model/model_adapter.py#L170)

>By passing device_map="auto", we tell 🤗 Accelerate to determine automatically where to put each layer of the model depending on the available resources:
> - first, we use the maximum space available on the GPU(s)
> - if we still need space, we store the remaining weights on the CPU
> - if there is not enough RAM, we store the remaining weights on the hard drive as memory-mapped tensors

On vLLM, when the GPU util is not specified in the [API Server](https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py#L78), the default util is [0.9](https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py#L27), it can't run inference for Llama2 70b chat with 2 A100 80G. 

When the GPU util is specified as **0.95**, it can run. It's a work solution.

Although, we would like to ask if there are any future plans to support **an option** like HuggingFace's transformer, where weights that can't be stored on the GPU can be offloaded to the CPU. Thank you.

**Comment by viktor-ferenczi** [comment]
Attempted to install vLLM on a very powerful, but CPU only server with the hope I can do batch inference on CPU. Slow, but still higher throughput. But installing vllm requires CUDA, so it cannot be used for that. Once CPU off-loading is implemented it would also be nice to allow the installation and use of vLLM on CPU only hosts as well.

**Comment by zhuohan123** [comment]
vLLM currently focuses on optimizing throughputs on the server side. Swapping weights to CPU RAM will almost always hurt the serving throughput and GPU utilization. You are welcome to checkout another project of us to learn more about that constraint scenario: https://github.com/FMInference/FlexGen

**Comment by zhyncs** [comment]
> vLLM currently focuses on optimizing throughputs on the server side. Swapping weights to CPU RAM will almost always hurt the serving throughput and GPU utilization, and thus it's not in our short-term plan. You are welcome to checkout another project of us to learn more about that constraint scenario: https://github.com/FMInference/FlexGen

Thanks

**Comment by eigen2017** [comment]
> vLLM currently focuses on optimizing throughputs on the server side. Swapping weights to CPU RAM will almost always hurt the serving throughput and GPU utilization, and thus it's not in our short-term plan. You are welcome to checkout another project of us to learn more about that constraint scenario: https://github.com/FMInference/FlexGen

but we still need accelerate techs like page attn on poor devices,  flexgen cannot satisfy this.
