### ISSUE TITLE
[Usage]: Maximum Context Length Exceeded Due to Base64-Encoded Image in Prompt

### ISSUE THREAD

**Issue by tusharraskar** [vllm-project/vllm#6324]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

# Example Code
llm = VLLMOpenAI(
openai_api_key="EMPTY",
openai_api_base=api_base,
model_name="microsoft/Phi-3-vision-128k-instruct",
model_kwargs={"stop": ["."]}
)

image_path = "invoice_data_images/Screenshot 2024-05-02 160946_page_1.png"
with open(image_path, "rb") as image_file:
image_base64 = base64.b64encode(image_file.read()).decode("utf-8")

prompt_1 = "Give me the invoice date from the given image."
messages = [
HumanMessage(
content=[
{"type": "text", "text": prompt_1},
{"type": "image_url", "image_url": {"url": f"data:image/png;base64,{image_base64}"}}
]
)
]

response = llm.invoke(messages)
print(response)

# Error Message
{
"name": "BadRequestError",
"message": "Error code: 400 - {'object': 'error', 'message': 'This model's maximum context length is 8192 tokens. However, you requested 254457 tokens (254201 in the messages, 256 in the completion). Please reduce the length of the messages or completion.', 'type': 'BadRequestError', 'param': None, 'code': 400}"
}

# Description
I hosted VLLM on an EC2 instance to extract text data from images using the Phi-3 Vision model. The model is hosted with the following command:

python3 -m vllm.entrypoints.openai.api_server --port 8000 --model microsoft/Phi-3-vision-128k-instruct --trust-remote-code --dtype=half --max_model_len=8192

When running the code, I encounter a BadRequestError due to exceeding the maximum context length. The error message indicates that the total number of tokens requested is 254457, which far exceeds the model's limit of 8192 tokens.

The base64-encoded image is being considered part of the prompt, significantly increasing the token count and leading to the context length issue.

Even if the model's context length were 128k tokens, including a base64-encoded image in the prompt would always exceed the model's limit.

# Expected Behavior
The model should process the image without considering the base64 string as part of the prompt token count, thereby avoiding the context length issue.

**Comment by youkaichao** [comment]
cc @DarkLight1337

**Comment by DarkLight1337** [comment]
I'm a bit confused. How is this issue different from #6301?

To better isolate the issue, please try to use vLLM directly instead of LangChain's integration.

**Comment by tusharraskar** [comment]
@DarkLight1337
I appreciate the suggestion to use vLLM directly to isolate the issue. However, my goal is to use LangChain agents for this task. How can I integrate LangChain agents with vLLM effectively while managing the context length issue?

**Comment by DarkLight1337** [comment]
I'm not familiar with how the LangChain integration is set up. Perhaps they haven't updated the integration to work with the latest version of vLLM yet? You should open an issue on their repo.

**Comment by DarkLight1337** [comment]
Also I noticed that you have two separate pieces of code here? One is about the LangChain integration but the other one is using vLLM server.

**Comment by tusharraskar** [comment]
Yes, the command:

python3 -m vllm.entrypoints.openai.api_server --port 8000 --model microsoft/Phi-3-vision-128k-instruct --trust-remote-code --dtype=half --max_model_len=8192

is used to host the microsoft/Phi-3-vision-128k-instruct model.

The hosted API base is then used in the LangChain integration as follows:

llm = VLLMOpenAI(
    openai_api_key="EMPTY",
    openai_api_base=api_base,
    model_name="microsoft/Phi-3-vision-128k-instruct",
    model_kwargs={"stop": ["."]}
)

**Comment by DarkLight1337** [comment]
Can you share an image that causes this problem so that I can test it out locally?

**Comment by DarkLight1337** [comment]
I tried some sample images using OpenAI client and failed to trigger this issue.

**Comment by DarkLight1337** [comment]
Perhaps you have to remove `model_kwargs={"stop": ["."]}`

**Comment by tusharraskar** [comment]
I attached an image here.

Can you share your code?

![Screenshot 2024-06-05 153829_page_1](https://github.com/vllm-project/vllm/assets/117747869/bf810dde-3e99-4ee0-b226-455045074e4f)

**Comment by DarkLight1337** [comment]
I can load this image as normal on my end. Maybe it's a problem with LangChain's integration.

Server:

```
python3 -m vllm.entrypoints.openai.api_server --port 8001 --model microsoft/Phi-3-vision-128k-instruct --trust-remote-code --dtype=half --max_model_len=8192
```

Client:
```py
from openai import OpenAI
from vllm.multimodal.utils import ImageFetchAiohttp

openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8001/v1"

client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)

model = client.models.list().data[0].id
print("Model:", model)

image_url = "https://private-user-images.githubusercontent.com/117747869/347734203-bf810dde-3e99-4ee0-b226-455045074e4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODYwMzUsIm5iZiI6MTcyMDY4NTczNSwicGF0aCI6Ii8xMTc3NDc4NjkvMzQ3NzM0MjAzLWJmODEwZGRlLTNlOTktNGVlMC1iMjI2LTQ1NTA0NTA3NGU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwODE1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGE1ZmNlYTkxNzdjZWIwYzIzMDMyZDE5ZDhlMWJkZDBiMDg5ZjNkZjhmZGRhYTA2MWYxZjdhY2FmZTk0OWJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CjckU4aV1mV8IksZa8N2C0lnQHthwJMU1alcGFcWbgs"
chat_response = client.chat.completions.create(
    model=model,
    messages=[{
        "role": "user",
        "content": [
            {
                "type": "image_url",
                "image_url": {
                    "url": image_url,
                },
            },
            {"type": "text", "text": "What is in this image?"},
        ],
    }],
)

print("Chat response:", chat_response)
```

**Comment by tusharraskar** [comment]
You are using OpenAI, but I want to use LangChain.

from langchain_community.llms import VLLMOpenAI

**Comment by DarkLight1337** [comment]
If this is a problem with LangChain's integration, you'll have to open an issue on LangChain's repo, not here (the integration lives on their repo, after all).

**Comment by tusharraskar** [comment]
Thanks for your support and time. I will raise an issue on the LangChain repo.

**Comment by tusharraskar** [comment]
Thanks for your support and time. I will raise an issue on the LangChain repo.
