### ISSUE TITLE
T4 machine got stuck

### ISSUE THREAD

**Issue by Ted8000** [vllm-project/vllm#633]
INFO 08-01 03:08:39 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 92.9%, CPU KV cache usage: 0.0%
INFO 08-01 03:08:45 scheduler.py:271] Throughput: 181.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 100.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:08:51 scheduler.py:271] Throughput: 185.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 100.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:08:56 scheduler.py:271] Throughput: 189.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 100.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:02 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:07 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:12 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:17 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:22 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:27 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 08-01 03:09:32 scheduler.py:271] Throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%

**_when i use V100 and A100, everything is ok, but deploy in T4 machine , some cases are ok, some cases got stuck, if one case gets stuck, others can't request._**

**Comment by zhuohan123** [comment]
Can you provide the code to reproduce the error? I guess this can be caused by the input request being too long to fit into a single GPU.

**Comment by Ted8000** [comment]
> Can you provide the code to reproduce the error? I guess this can be caused by the input request being too long to fit into a single GPU.

Yes, i think so, according to your reminder，i reduce the stuck case's lenght (200->160), it get successful in one T4 machine.
And i lanch 2*T4 for inference, it has no such problem.  So i think maybe there is KV cache problem for one T4 machine with 15GB VRAM. For one T4 lanch it, VRAM seems have 1000MB more left:
<img width="558" alt="image" src="https://github.com/vllm-project/vllm/assets/32102558/75b28ba5-ff5c-48bd-afe9-76d3e16dca1b">

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by Playerrrrr** [comment]
still have this problem even in the latest build dockers
