### ISSUE TITLE
[Performance]: how to use NVIDIA Nsight Compute in lunix

### ISSUE THREAD

**Issue by chenglu66** [vllm-project/vllm#6336]
### Proposal to improve performance

how to use NVIDIA Nsight Compute in lunix

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by mgoin** [comment]
Hi @chenglu66, please consult the NVIDIA documentation for that since it doesn't directly relate to vLLM: https://developer.nvidia.com/tools-overview/nsight-compute/get-started

**Comment by chenglu66** [comment]
ok，thx，but i just want to konw how run NVIDIA Nsight Compute to profile vllm, is there any tutorial？
