### ISSUE TITLE
[Misc]: Multimodal data and continuous batching

### ISSUE THREAD

**Issue by niuzheng168** [vllm-project/vllm#6362]
### Anything you want to discuss about vllm.

I see multimodal data only send for first time.
Will continuous batching put seq in prefill state and decode state together?
If this happened, how to match the multimodal data to each seq?

e.g. the current step batch_size=2,  one is prefill and the other one is decode. the input_id_shape is [2,] the multimodal data shape is [1,], how can I tell the multimodal data belongs to which input?

**Comment by niuzheng168** [comment]
> Not sure I follow your question completely.
> 
> vlm and continuous batching can interoperate. The way we deal with image is to reserve the equivalent number of slots in KV cache (to account for image tokens). The rest is the same with text queries. Before we even reach prefill/decode stage, the image is already converted to tokens. So from engine's perspective, it really can't tell whether what it's dealing with an image or text request.

yes, so how llava work when  continuous batch? Consider the first request is in decoding stage, and now another request comes, the scheduler will put the last token id from first request together with the image tokens from second request.  
But I suppose this [code](https://github.com/vllm-project/vllm/blob/f7160d946a0a07703e72d81ba9ecf3913f192605/vllm/model_executor/models/llava.py#L262) will only get 1 image inputs, then how can I know it belongs to the first request or the second request? 
Maybe I can resolve it by analysis the attn metadata?

I haven't run llava model yet, so pls correct me if I made mistake in above statements. I am trying to port a speech model to vllm, it's similar with llava, the model input is text tokens together with speech tokens(which came from an audio file).

**Comment by xwjiang2010** [comment]
hmm can we clarify on continuous batching first? Maybe you want to take a look at this blog with some nice visuals: https://www.anyscale.com/blog/continuous-batching-llm-inference

At any given iteration, the engine can either be in "prefill" or "decode" depending on some scheduling strategy. Decoding is much faster than prefill but incoming prefill requests also shouldn't wait forever. So there is some fine balance here captured by the scheduling strategy. Likely also workload dependent. 

There is no mix of prefill and decode within one iteration.

**Comment by niuzheng168** [comment]
> hmm can we clarify on continuous batching first? Maybe you want to take a look at this blog with some nice visuals: https://www.anyscale.com/blog/continuous-batching-llm-inference
> 
> At any given iteration, the engine can either be in "prefill" or "decode" depending on some scheduling strategy. Decoding is much faster than prefill but incoming prefill requests also shouldn't wait forever. So there is some fine balance here captured by the scheduling strategy. Likely workload dependent.
> 
> There is no mix of prefill and decode within one iteration.

oh, that explain everything. Sorry for my mis-understanding on continuous batching. I thought it's like trt-llm IFB, which can combine prefill and decode in one iteration.

**Comment by niuzheng168** [comment]
> hmm can we clarify on continuous batching first? Maybe you want to take a look at this blog with some nice visuals: https://www.anyscale.com/blog/continuous-batching-llm-inference
> 
> At any given iteration, the engine can either be in "prefill" or "decode" depending on some scheduling strategy. Decoding is much faster than prefill but incoming prefill requests also shouldn't wait forever. So there is some fine balance here captured by the scheduling strategy. Likely workload dependent.
> 
> There is no mix of prefill and decode within one iteration.

I just read chunked prefill document, it seems when the feature is enabled, prefill and decode could be in the same batch. So will it be an issue that multimodal data cannot be well aligned with input?

**Comment by xwjiang2010** [comment]
It's not supported with chunked prefill.
