### ISSUE TITLE
VLLM supporting more than 1 completion per prompt - sampling?

### ISSUE THREAD

**Issue by arnavsinghvi11** [vllm-project/vllm#639]
Hi there, 

I want to generate more than one completion for one prompt (n > 1) without using beam search and instead using random sampling for these queries. However, there seems to be an issue when setting best_of to a value greater than 1, specifically when n=5 and best_of=1. The server has a condition that best_of must be greater than or equal to n, causing it to error out when doing sampling - `best_of must be 1 when using greedy sampling.`

Just want to know if it is currently supported to perform multiple queries (n > 1) using random sampling with VLLM.

Thanks for the help!

Thanks, 
Arnav

**Comment by hmellor** [comment]
>    Args:
>        n: Number of output sequences to return for the given prompt.
>        best_of: Number of output sequences that are generated from the prompt.
>            From these `best_of` sequences, the top `n` sequences are returned.
>            `best_of` must be greater than or equal to `n`. This is treated as
>            the beam width when `use_beam_search` is True. By default, `best_of`
>            is set to `n`.

Based on this documentation of `SamplingParams`, if you want to generate `n > 1` sequences, you should just set `n` (`best_of` will automatically be set to equal `n`).

`best_of` determines the number of sequences generated and `n` determines the number of sequences returned. Therefore `n` cannot be less than `best_of`.
