### ISSUE TITLE
[Feature]: Apply chat template through `LLM` class

### ISSUE THREAD

**Issue by robertgshaw2-neuralmagic** [vllm-project/vllm#6416]
### 🚀 The feature, motivation and pitch

We do not have a way to apply the chat template to a model via the `LLM` class, so we often see patterns like this

```python
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

max_model_len, tp_size = 8192, 1
model_name = "deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
llm = LLM(model=model_name, tensor_parallel_size=tp_size, max_model_len=max_model_len, trust_remote_code=True, enforce_eager=True)

messages_list = [
    [{"role": "user", "content": "Who are you?"}],
    [{"role": "user", "content": "write a quick sort algorithm in python."}],
    [{"role": "user", "content": "Write a piece of quicksort code in C++."}],
]

prompt_token_ids = [tokenizer.apply_chat_template(messages, add_generation_prompt=True) for messages in messages_list]

outputs = llm.generate(prompt_token_ids=prompt_token_ids, sampling_params=sampling_params)

generated_text = [output.outputs[0].text for output in outputs]
print(generated_text)
```

### Pass list of messages and apply chat template

```python
from vllm import LLM

model = LLM("...")

messages_list = [
    [{"role": "user", "content": "Who are you?"}],
    [{"role": "user", "content": "write a quick sort algorithm in python."}],
    [{"role": "user", "content": "Write a piece of quicksort code in C++."}],
]

# chat template applied internally
outputs = model.generate(messages_list)
```

### Use the chat template from the llm class

```python
from vllm import LLM

model = LLM("...")

messages_list = [
    [{"role": "user", "content": "Who are you?"}],
    [{"role": "user", "content": "write a quick sort algorithm in python."}],
    [{"role": "user", "content": "Write a piece of quicksort code in C++."}],
]

# use LLM class to apply chat template to prompts
prompt_ids = model.apply_chat_template(messages_list, add_generation_prompt=True)
text = model.apply_chat_template(messages_list, add_generation_prompt=True, tokenize=False)
```

**Comment by w013nad** [comment]
It would be nice to have this on the openai API as well.

**Comment by robertgshaw2-neuralmagic** [comment]
> It would be nice to have this on the openai API as well.

This is already supported in /chat/completions

**Comment by w013nad** [comment]
> > It would be nice to have this on the openai API as well.
> 
> This is already supported in /chat/completions

Yes, but if I want to prepend the LLM's response with something, I have to use the /completions endpoint.

**Comment by robertgshaw2-neuralmagic** [comment]
> > > It would be nice to have this on the openai API as well.
> > 
> > 
> > This is already supported in /chat/completions
> 
> Yes, but if I want to prepend the LLM's response with something, I have to use the /completions endpoint.

I don't quite follow what you are looking for. We need `/completions` and `/chat/completions` to conform to the OpenAI format

**Comment by w013nad** [comment]
I suppose this should probably be in a completely separate issue.

My problem is that if I want the LLM to start with a particular string, I can't do it unless I use the /completions. Say I want the LLM to only output code. I would need to format the prompt for everything but the LLM response then add the "```" to the beginning of the LLM response and send that through. Ideally, there could be a /apply_chat_template endpoint or an extra_body portion of the openai /chat/completions to allow this.

**Comment by robertgshaw2-neuralmagic** [comment]
I see. I think we should add `/apply_chat_template` similar to how we have `/tokenize`

I don't think we should modify the `/chat/completions` endpoint though because we need to conform to openai api

Do you know if openai allows "starting responses" as you describe here?

**Comment by w013nad** [comment]
Not that I can find.

**Comment by ywang96** [comment]
I like this proposal! This way the users won't have to import and instantiate a separate tokenizer, which is though non-blocking yet quite a bit of overhead sometimes.

Does this mean we will also allow users to pass custom Jinja chat template like how we do in the OpenAI API server? Should we perhaps move that logic on the engine level to avoid repetitive code then?

**Comment by DarkLight1337** [comment]
Can this be addressed by #5049?

**Comment by robertgshaw2-neuralmagic** [comment]
> Would this be addressed by #5049?

Same idea, but I don't love #5049's UX

**Comment by robertgshaw2-neuralmagic** [comment]
> I like this proposal! This way users won't have to import and instantiate a separate tokenizer, which is though non-blocking yet quite a bit of overhead sometimes.
> 
> Does this mean we will also allow users to pass custom Jinja chat template when instantiating an `LLM` class like how we do in the OpenAI API server? Should we perhaps move that logic to the engine level to avoid repetitive code then?

I like the idea of enabling users to pass the custom chat templates to the `LLM` constructor to override the default and additionally I like the idea of enabling the user to pass a chat template to override in `LLM.generate()`

**Comment by llStringll** [comment]
Hi, I have opened a PR for the adding this feature here [PR](https://github.com/vllm-project/vllm/pull/6936).
Currently the fastcheck is running on it.
Plesae review this and share if I must add any changes.

**Comment by yananchen1989** [comment]
hi there,

Has this feature `outputs = model.generate(messages_list)` been incorporated in version 0.5.4 ?

seems have not yet.

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/moa/vllminfer.py", line 58, in <module>
[rank0]:     outputs = llm.generate(messages_list)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/utils.py", line 895, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 323, in generate
[rank0]:     self._validate_and_add_requests(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 552, in _validate_and_add_requests[rank0]:     self._add_request(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 568, in _add_request
[rank0]:     self.llm_engine.add_request(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 654, in add_request
[rank0]:     processed_inputs = self.process_model_inputs(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 580, in process_model_inputs    
[rank0]:     prompt=inputs["prompt"],
[rank0]: TypeError: list indices must be integers or slices, not str
```

**Comment by DarkLight1337** [comment]
No, it will be in the next release. Also, we have decided to use a separate API `LLM.chat`.

**Comment by yananchen1989** [comment]
vllm 0.5.5
```
from vllm import LLM, SamplingParams
llm = LLM(model= 'meta-llama/Meta-Llama-3.1-8B-Instruct', dtype='bfloat16', max_model_len=16000,
        tensor_parallel_size=1, gpu_memory_utilization=0.95,
            quantization="bitsandbytes", load_format="bitsandbytes", enforce_eager=True)

messages_list = [
    [{"role": "user", "content": "Who are you?"}],
    [{"role": "user", "content": "write a quick sort algorithm in python."}],
    [{"role": "user", "content": "Write a piece of quicksort code in C++."}],
]

# chat template applied internally
outputs = llm.generate(messages_list)
```

> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/ubuntu/moa/ttt.py", line 13, in <module>
> [rank0]:     outputs = llm.generate(messages_list)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/utils.py", line 1030, in inner
> [rank0]:     return fn(*args, **kwargs)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 338, in generate
> [rank0]:     self._validate_and_add_requests(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 626, in _validate_and_add_requests
> [rank0]:     self._add_request(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 642, in _add_request
> [rank0]:     self.llm_engine.add_request(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1034, in add_request
> [rank0]:     processed_inputs = self.process_model_inputs(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 967, in process_model_inputs
> [rank0]:     model_inputs = self._process_decoder_only_prompt(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 935, in _process_decoder_only_prompt
> [rank0]:     prompt_comps = self._extract_prompt_components(
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 760, in _extract_prompt_components
> [rank0]:     assert_never(inputs)
> [rank0]:   File "/opt/conda/lib/python3.10/site-packages/typing_extensions.py", line 2378, in assert_never
> [rank0]:     raise AssertionError("Expected code to be unreachable")
> [rank0]: AssertionError: Expected code to be unreachable

**Comment by DarkLight1337** [comment]
`LLM.chat` only supports one conversation at a time. You should split this into multiple calls.
