### ISSUE TITLE
[Feature]: Return softmax of attention layer.

### ISSUE THREAD

**Issue by DouHappy** [vllm-project/vllm#6424]
### 🚀 The feature, motivation and pitch

# Feature
I'm working on returning the softmax of the LLM's attention layer. As far as I know, only transformers support this [feature](https://huggingface.co/docs/transformers/v4.42.0/en/internal/generation_utils#generate-outputs). But transforms is not efficient enough. I saw "return_softmax" [vllm_flash_attn](https://github.com/vllm-project/flash-attention/blob/main/vllm_flash_attn/flash_attn_interface.py#L62), but seems it can't be used. Would you be able to add this feature?

# Motivation
Softmax of attention is important evidence for humans to understand how LLM works. Humans can determine which input token is important for the inference of the output token. And more features can be developed based on this feature such as visualization of LLM evidence.

# Pitch
For this RFC in particular, we propose the following changes:
- Add a new function llm.forward(). This function receives requests to do prefill and return softmax.
- Modify prefill kernels to support output softmax.

**Comment by DarkLight1337** [comment]
#6260 may be able to achieve this by returning arbitrary outputs directly from the model.

**Comment by AllenDou** [comment]
Yes, I also think https://github.com/vllm-project/vllm/pull/6260 could achieve this feature, a small refactor is needed.

**Comment by DouHappy** [comment]
> Yes, I also think #6260 could achieve this feature, a small refactor is needed.

Thank you for your excellent work. I will close this issue.

**Comment by NOVAglow646** [comment]
Hi, can you show a concrete implementation of this goal? I found #6260 a bit confusing. Thank you.

**Comment by DarkLight1337** [comment]
You can follow https://docs.vllm.ai/en/latest/models/pooling_models.html and set the task type to `classify` so that softmax is applied automatically.
