### ISSUE TITLE
deploying embedding model in same way as LLM 

### ISSUE THREAD

**Issue by riyajatar37003** [vllm-project/vllm#6498]
### 🚀 The feature, motivation and pitch

can we deploy the embedding model such as bge,e5 etc. using vllm? if yes could u point to the resources for it.

**Comment by yuanzhiyong1999** [comment]
> ### 🚀 The feature, motivation and pitch
> can we deploy the embedding model such as bge,e5 etc. using vllm? if yes could u point to the resources for it.
> 
> ### Alternatives
> _No response_
> 
> ### Additional context
> _No response_

Have you solved it?
