### ISSUE TITLE
[Bug]: When I use gemma2 27b, the openai.api returns content "" as none ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[])

### ISSUE THREAD

**Issue by Minami-su** [vllm-project/vllm#6499]
### Your current environment

[Bug]: When I use gemma2 27b, the openai.api returns content "" as none ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[])
CUDA_VISIBLE_DEVICES=3 python -m vllm.entrypoints.openai.api_server --model model/gemma-2-27b-it --trust-remote-code --port 8001 --host localhost --dtype half --max-model-len 4096 --enforce-eager --disable_custom_all_reduce --api-key token-abc123

from openai import OpenAI
client = OpenAI(
    base_url="http://localhost:8001/v1",
    api_key="token-abc123",
)

completion = client.chat.completions.create(
  model="/work/jcxy/LLaMA-Factory/model/gemma-2-27b-it",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)

print(completion.choices[0].message)

result:
ChatCompletionMessage(content='', role='assistant', function_call=None, tool_calls=[])

2.And when I use curl, it also returns an empty value.
 curl http://localhost:8001/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "/work/jcxy/LLaMA-Factory/model/gemma-2-27b-it",
"prompt": "San Francisco is a",
"max_tokens": 12,
"temperature": 0
}'
{"id":"cmpl-a3599d01314b46eea5dbdf4881566a4a","object":"text_completion","created":1721200042,"model":"model/gemma-2-27b-it","choices":[{"index":0,**"text":"",**"logprobs":null,"finish_reason":"length","stop_reason":null}],"usage":{"prompt_tokens":5,"total_tokens":17,"completion_tokens":12}}

 However, when I don't use an API request, it works fine with llm = LLM(model=model_path, enforce_eager=True, tensor_parallel_size=2, disable_custom_all_reduce=True, gpu_memory_utilization=0.8).

#The Qwen2 model works fine; this issue only occurs with the Gemma2 model.

**Comment by bojiang** [comment]
reproduced

**Comment by Minami-su** [comment]
Ok,solved,modify --dtype half --> --dtype auto

**Comment by Hapluckyy** [comment]
i have the same problem and it is not working by setting  --dtype half --> --dtype auto
