### ISSUE TITLE
[Usage]: How to release GPU of vLLM model in python code

### ISSUE THREAD

**Issue by quanshr** [vllm-project/vllm#6544]
### Your current environment

```python
llm = LLM(model=model1_path, tensor_parallel_size=torch.cuda.device_count())
llm = LLM(model=model2_path, tensor_parallel_size=torch.cuda.device_count())
```

It will cause CUDA out of memory when execute the second line.

### How would you like to use vllm

I want to use two model in pipeline in one python code to infer. When finish inference on the first model, how to release this model and release GPU memory to load another one, since directly reloading may cause CUDA OUT OF MEMORY for it doesn't release the first one.

**Comment by DarkLight1337** [comment]
Please see #5716. For now, you have to do it manually as follows (based on the code in `tests/conftest.py`:

```py
import contextlib
import gc

import torch
from vllm.distributed import (destroy_distributed_environment,
                              destroy_model_parallel)
from vllm.utils import is_cpu

def cleanup():
    destroy_model_parallel()
    destroy_distributed_environment()
    with contextlib.suppress(AssertionError):
        torch.distributed.destroy_process_group()
    gc.collect()
    if not is_cpu():
        torch.cuda.empty_cache()

llm = LLM(...)
del llm
cleanup()

```

**Comment by quanshr** [comment]
> Please see #5716. For now, you have to do it manually as follows (based on the code in `tests/conftest.py`:
> 
> ```python
> import contextlib
> import gc
> 
> import torch
> from vllm.distributed import (destroy_distributed_environment,
>                               destroy_model_parallel)
> from vllm.utils import is_cpu
> 
> def cleanup():
>     destroy_model_parallel()
>     destroy_distributed_environment()
>     with contextlib.suppress(AssertionError):
>         torch.distributed.destroy_process_group()
>     gc.collect()
>     if not is_cpu():
>         torch.cuda.empty_cache()
> 
> llm = LLM(...)
> del llm
> cleanup()
> ```

It works! Thanks for your help~

**Comment by yanyc428** [comment]
Hi~ Does this also work with multiple-GPUs?

**Comment by DarkLight1337** [comment]
It should work in theory.
