### ISSUE TITLE
[New Model]: Mistral-Nemo

### ISSUE THREAD

**Issue by Hambaobao** [vllm-project/vllm#6563]
### The model to consider.

https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407

### The closest model vllm already supports.

- https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/llama.py
- https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/mixtral.py

**Comment by jonzhep** [comment]
we just need to pull head_dim from config i think
[https://github.com/huggingface/transformers/commit/4c040aba02b0283619a06bdc40ecf868508b9e52](url)

**Comment by simon-mo** [comment]
Closed by #6548. It will be released next week. Please try build from source for now. Thank you!
