### ISSUE TITLE
[Model]: Llava-Next-Video support

### ISSUE THREAD

**Issue by TKONIY** [vllm-project/vllm#6571]
### The model to consider.

LLaVA-NeXT-Video* (LlavaNextVideoForConditionalGeneration)

### The closest model vllm already supports.

Llava-Next (LlavaNextForConditionalGeneration)

### What's your difficulty of supporting the model you want?

- Implement the video processor.
- Implement the merging of video embedding and text embedding.

<img width="841" alt="image" src="https://github.com/user-attachments/assets/ddee101e-6afb-4c13-a800-80a8b96fc696">

**Comment by ywang96** [comment]
Do you plan to make a PR for this? FYI, the support for multi-image (which is essentially what video Llava is doing) is indeed in our Q3 roadmap, so it would be great if you collaborate on the effort.

**Comment by TKONIY** [comment]
Yes but I haven't finished yet. I am working on it.

**Comment by TKONIY** [comment]
I will make a PR this week. It will support a dynamic number of input frames, which is important but not supported by SGLang.

* SGlang needs to set a `num_frames` parameters when launching a llava-next-video model, and simply asserts all the input videos contains `num_frames` frames. If input frames are less than `num_frames`, their embedding will be padded with the wrong numbers. If the input frames are more than `num_frames`, their embedding will be truncated. In both situations the results are unexpected.

* Instead, in LLM, the length of embedding will be calculated from the arrived requests to support videos with different frames.
