### ISSUE TITLE
[Bug]: CUDA Error when print 

### ISSUE THREAD

**Issue by NaNillll** [vllm-project/vllm#6575]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

I am new to vllm, I want to check input to llama model, so I just print

![image](https://github.com/user-attachments/assets/d8489d1f-4f25-48a5-8867-2e96d11f54bb)

However, it raise cuda bug. Why? And how can I get input?

![image](https://github.com/user-attachments/assets/cf821f7c-395b-4f60-a64a-a4b651f14a4e)

Thanks!!!

**Comment by NaNillll** [comment]
I think is is caused by some cuda settings

**Comment by DarkLight1337** [comment]
As mentioned in the error message, try again with `CUDA_LAUNCH_BLOCKING=1`.
