### ISSUE TITLE
[Feature]: LLM2Vec (Fine-Tuned Embeddings) Support

### ISSUE THREAD

**Issue by DorotheaMueller** [vllm-project/vllm#6584]
### 🚀 The feature, motivation and pitch

 **[LLM2Vec](https://huggingface.co/McGill-NLP/LLM2Vec-Meta-Llama-3-8B-Instruct-mntp) is a powerful approach to convert LLMs into embedding models. They show strong results on the MTEB and it's also possible to fine-tune LoRA adapters for the embeddings. Would it be possible to support these embedding models,** in particular for Llama3?
 
### Additional context

The embedding models are similar to base LLM models except for enabling bidirectional attention. I trained a LoRA adapter for the Llama3 (LlamaForCausalLM, Meta-Llama3-8B-Instruct) and merged it. Per default, it gets merged as a "LlamaBiModel", which is currently not supported. When I played around and replaced the architecture with LlamaForCausalLM), I get KeyError: "embed_tokens.weight", so it's not simply replacable.

If it's not possible to take on this feature right now, I'd greatly appreciate any guidance or resources that could help me start working on it.
 
This request is related to the [discussion of embedding models in general](https://github.com/vllm-project/vllm/discussions/310).

**Comment by HydrogenBombaklot** [comment]
I would like to revive this as LLM2VEC has huge potential and should be supported.
