### ISSUE TITLE
how to support prefix-tunning?

### ISSUE THREAD

**Issue by InkdyeHuang** [vllm-project/vllm#660]

**Comment by zhuohan123** [comment]
Hi supporting any kind of training or fine-tuning is not in our plan. However, supporting soft prompt inputs should be possible with vLLM. Feel free to contribute if you are interested in this!

**Comment by hmellor** [comment]
Closing because training is out of scope for vLLM

**Comment by datalee** [comment]
hello。supporting soft prompt inputs is ok？
