### ISSUE TITLE
[Feature]: 4D Attention Mask

### ISSUE THREAD

**Issue by littletomatodonkey** [vllm-project/vllm#6615]
### 🚀 The feature, motivation and pitch

I am workning on 4D attention mask input and LLM generateion process. Huggingface provides an interface for the 4D attention mask. Does vllm have any plan? https://github.com/huggingface/transformers/pull/27539

**Comment by iiLaurens** [comment]
AFAIK custom attention masks are not supported in optimize implementations of attention (FlashInfer, FlashAttention), so this wouldn't be possible without also incurring a dramatic drop in performance.

**Comment by littletomatodonkey** [comment]
> AFAIK custom attention masks are not supported in optimized implementations of attention (FlashInfer, FlashAttention), so this wouldn't be possible without also incurring a dramatic drop in performance.

Thanks for your reply, i might have to realize the function myself.
