### ISSUE TITLE
[Bug]: OpenAI server unexpected shutdown

### ISSUE THREAD

**Issue by foreverhell** [vllm-project/vllm#6629]
### Your current environment

```text
The output of `python collect_env.py`
```
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.5
Libc version: glibc-2.31

Python version: 3.9.19 (main, May  6 2024, 19:43:03)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-107-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 535.183.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] torch==2.3.0
[pip3] torcheval==0.0.7
[pip3] transformers==4.41.2
[pip3] triton==2.3.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] torch                     2.3.0                    pypi_0    pypi
[conda] torcheval                 0.0.7                    pypi_0    pypi
[conda] transformers              4.41.2                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.0
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PXB     PXB     PXB     SYS     SYS     SYS     SYS     0-11,24-35      0               N/A
GPU1    PXB      X      PXB     PXB     SYS     SYS     SYS     SYS     0-11,24-35      0               N/A
GPU2    PXB     PXB      X      PIX     SYS     SYS     SYS     SYS     0-11,24-35      0               N/A
GPU3    PXB     PXB     PIX      X      SYS     SYS     SYS     SYS     0-11,24-35      0               N/A
GPU4    SYS     SYS     SYS     SYS      X      PXB     PXB     PXB     12-23,36-47     1               N/A
GPU5    SYS     SYS     SYS     SYS     PXB      X      PXB     PXB     12-23,36-47     1               N/A
GPU6    SYS     SYS     SYS     SYS     PXB     PXB      X      PIX     12-23,36-47     1               N/A
GPU7    SYS     SYS     SYS     SYS     PXB     PXB     PIX      X      12-23,36-47     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

### 🐛 Describe the bug

![20240721服务器shutdown](https://github.com/user-attachments/assets/5ed04752-aaa8-4933-a639-c1d2734455cd)
On weekend, the running OpenAI server unexpected shutdown. Is there any possible reason and solution for this issue?

**Comment by wrisigo** [comment]
Running into the same issue but with output "Killed" instead of terminated.
