### ISSUE TITLE
[Bug]: The num_generation_tokens in stats is incorrect with speculative decoding

### ISSUE THREAD

**Issue by sighingnow** [vllm-project/vllm#6669]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

The current implementation of `_get_stats` assumes each sequence will get one new token at each iteration, which doesn't hold with speculative decoding:

https://github.com/vllm-project/vllm/blob/c5e8330997dc3969818c6696a79820bcee44a702/vllm/engine/llm_engine.py#L1075-L1084

@cadedaniel  I would like to submit a PR to fix it, before starting the work, I would like to how do you think about it? I would like to track the accepted new tokens by tracking the output of multi-step output processors's outputs in

https://github.com/vllm-project/vllm/blob/c5e8330997dc3969818c6696a79820bcee44a702/vllm/engine/llm_engine.py#L821-L824

**Comment by cadedaniel** [comment]
Thanks for filing the bug. Your approach sounds good, you can have `process_outputs` return the number of generated tokens.
