### ISSUE TITLE
[Usage]: Does Prefix Caching currently support offloading to the CPU?

### ISSUE THREAD

**Issue by wjj19950828** [vllm-project/vllm#6676]
### Usage

Does Prefix Caching currently support offloading to the CPU?

 If not, is there a plan to support it? Thanks～

**Comment by simon-mo** [comment]
No. And yes, @KuntaiDu can add more.

**Comment by wjj19950828** [comment]
@KuntaiDu Do you have any suggestions on Prefix Caching offload to CPU? Thanks~

**Comment by KuntaiDu** [comment]
Yes, we have put some thought on supporting CPU/disk/database KV cache offloading. I am busy with profiling vllm's performance bottleneck recently (#6794 ), but I will circle back to KV cache offloading in next week.
