### ISSUE TITLE
T5 like encoder-decoder model support

### ISSUE THREAD

**Issue by XiangmingWang** [vllm-project/vllm#668]
vllm is a great open source project and we are looking forward to running the T5 model with vllm.I know there is a plan for T5 in the roadmap, but I still want to know, is there an approximate time for this? Or can there be a specific encoder-decoder  code structure, and then everyone will work together to contribute

**Comment by shermansiu** [comment]
Yes. See #187. It's also on the dev roadmap (#244).

**Comment by hmellor** [comment]
Closing as duplicate of #187
