### ISSUE TITLE
[Usage]: logprobs variable in SamplingParams from ChatCompletionRequest class

### ISSUE THREAD

**Issue by mfournioux** [vllm-project/vllm#6685]
I have noticed that the logprobs variable could be set to a boolean (top_logprobs) in this line https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/protocol.py#L254.

Is not supposed to be an integer which displays the number of log probabilities to return per output token?

**Comment by DarkLight1337** [comment]
We follow the semantics defined by [OpenAI API](https://platform.openai.com/docs/api-reference). You might have confused the Completion API with the Chat Completion API.

**Comment by mfournioux** [comment]
Many thanks for your feedback.

Indeed, from Completion API side, logprobs variable is an integer, and from Chat Completion API side it is a boolean, it is now much clearer.
