### ISSUE TITLE
[Feature]: vTensor: Flexible Virtual Tensor Management for Efficient LLM Serving

### ISSUE THREAD

**Issue by MichoChan** [vllm-project/vllm#6687]
### 🚀 The feature, motivation and pitch

vTensor: Flexible Virtual Tensor Management for Efficient LLM Serving 
look so cool

**Comment by clevercool** [comment]
The codes of vTensor are open-sourced! Here: https://github.com/intelligent-machine-learning/glake/tree/master/GLakeServe
