### ISSUE TITLE
[Bug] baichuan-13b-chat Service exception after long run

### ISSUE THREAD

**Issue by Tomorrowxxy** [vllm-project/vllm#677]
Start command
```
python -m vllm.entrypoints.openai.api_server --model baichuan-inc/Baichuan-13B-Chat --host 0.0.0.0 --port 8777 --trust-remote-code --dtype half
```

After about 12 hours of operation, the inference service stopped working

GPU：V100 
CUDA：11.4

Screenshot of the problem：
![Xnip2023-08-05_12-03-19](https://github.com/vllm-project/vllm/assets/33508761/68f881f4-4d18-4e2f-8751-85770b5367b8)

**Comment by zhuohan123** [comment]
Can you describe in more detail what exactly happened? For example, does all future requests fail, or just one specific request fail?

From the screenshot it feels like it's maybe because the client disconnects and thus the server stops the running request.

**Comment by Tomorrowxxy** [comment]
![image](https://github.com/vllm-project/vllm/assets/33508761/e53a2e8a-26b3-49ad-84f4-f94ade50dda8)
- All future requests will fail, there is no `Avg prompt throughput: xxxx` reasoning and other related information after `Received request`, directly `Aborted request`
- That is, the current machine is not processing any inference requests and must manually kill the process and restart the service
- This happened after running for about 6 hours
![image](https://github.com/vllm-project/vllm/assets/33508761/c32301e3-0d9a-4ad6-9bf1-2434de16030d)
![image](https://github.com/vllm-project/vllm/assets/33508761/70435c5b-f95d-4f49-b9e1-71a1723c14b9)

**Comment by Tomorrowxxy** [comment]
> ![image](https://user-images.githubusercontent.com/33508761/259055077-e53a2e8a-26b3-49ad-84f4-f94ade50dda8.png)
> 
> * All future requests will fail, there is no `Avg prompt throughput: xxxx` reasoning and other related information after `Received request`, directly `Aborted request`
> * That is, the current machine is not processing any inference requests and must manually kill the process and restart the service
> * This happened after running for about 6 hours
>   ![image](https://user-images.githubusercontent.com/33508761/259057112-c32301e3-0d9a-4ad6-9bf1-2434de16030d.png)
>   ![image](https://user-images.githubusercontent.com/33508761/259057195-70435c5b-f95d-4f49-b9e1-71a1723c14b9.png)

I think it should be caused by insufficient CUDA memory. As shown in the picture, the occupancy has reached 95%, resulting in no more reasoning
I tried to start baichuan-13b with gpu_memory_utilization = 0.8 on v100, sorry for the failure to start, it must be 0.9.

**Comment by Tomorrowxxy** [comment]
![WX20230818-153422](https://github.com/vllm-project/vllm/assets/33508761/a6b3511b-2553-498a-8a9b-680b7cb7249e)
After running for a while, no more inference. vllm's service is still there
Often appear, how should it be solved? @zhuohan123

**Comment by Tomorrowxxy** [comment]
![WX20230818-153722](https://github.com/vllm-project/vllm/assets/33508761/73d35e02-f293-42e6-a258-5e18917e6e85)

After running for a while, no more inference. vllm's service is still there
Often appear, how should it be solved? @zhuohan123

**Comment by xiaocode337317439** [comment]
+1
