### ISSUE TITLE
Is it possible to run vllm in a Notebook env such as Kaggle or Colab without frontend for offline batched inference ?

### ISSUE THREAD

**Issue by nigh8w0lf** [vllm-project/vllm#678]
Since these are restricted environments, is it possible to run without a frontend, are there any flags that we can use to disable the frontend?

**Comment by zhuohan123** [comment]
Please use the `LLM` class: https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#offline-batched-inference
