### ISSUE TITLE
[Usage]: can I use it with classification model (e.g. GemmaForSequenceClassification) ?

### ISSUE THREAD

**Issue by dodler** [vllm-project/vllm#6789]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

can I use it with classification model (e.g. GemmaForSequenceClassification) ?

**Comment by DarkLight1337** [comment]
You can now create a version of `Gemma2EmbeddingModel` via OOT registration and change the pooling type to `CLS` (or whatever your model uses for classification).

**Comment by a7744hsc** [comment]
In my case, the _validate_and_add_requests method accounts for approximately 20% of the total computation time, leaving GPU resources underutilized.
