### ISSUE TITLE
[Bug][ROCm] The embedding layer does not support long inputs

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#6807]
### Your current environment

8xMI300x machine using the docker image built with `Dockerfile.rocm`.

Versions of relevant libraries:
[pip3] mypy==1.7.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] optree==0.9.1
[pip3] pytorch-triton-rocm==3.0.0+21eae954ef
[pip3] torch==2.5.0.dev20240710+rocm6.1
[pip3] torchaudio==2.4.0.dev20240710+rocm6.1
[pip3] torchvision==0.20.0.dev20240710+rocm6.1
[pip3] transformers==4.43.2
[pip3] triton==3.0.0
[conda] No relevant packages
ROCM Version: 6.1.40093-bd86f1708
Neuron SDK Version: N/A
vLLM Version: 0.5.3.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

### 🐛 Describe the bug

```python
import torch
import torch.nn as nn

with torch.inference_mode():
    NUM_TOKENS = 128 * 1024
    HIDDEN_SIZE = 16 * 1024
    VOCAB_SIZE = 128 * 1024
    DTYPE = torch.bfloat16
    x = torch.randint(VOCAB_SIZE, (NUM_TOKENS,), dtype=torch.int64, device="cuda")
    embedding = nn.Embedding(VOCAB_SIZE, HIDDEN_SIZE, dtype=DTYPE, device="cuda")
    y = embedding(x)
    torch.cuda.synchronize()
```

The above script raises the following error:
```
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: HIP error: invalid configuration argument
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
```

while it works when `NUM_TOKENS=32 * 1024`.

**Comment by hongxiayang** [comment]
@WoosukKwon  I happened to fix the similar issue reported in pytorch a couple of days ago. Check this PR: https://github.com/pytorch/pytorch/pull/130994

It should be there in pytorch nightly, but with different date

The other follow up is the perf optimization PR: https://github.com/pytorch/pytorch/pull/131713
