### ISSUE TITLE
[Misc]: call for help to fix tensorizer tests

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#6809]
### Anything you want to discuss about vllm.

The tensorizer feature, introduced in https://github.com/vllm-project/vllm/pull/3476 , has been flaky recently.

An example failure: https://buildkite.com/vllm/fastcheck/builds/1061#0190ec55-50c1-4cf2-8380-bd7238e99cea

We call for help from the community, to fix the tests. Ideally, maybe the author of that PR, @sangstar .

We will mark it as flaky and non-blocking for tests first. If we cannot fix it in weeks, then we need to consider removing the test.

**Comment by sangstar** [comment]
Hi there @youkaichao and thanks for making me aware of this. 

Are there any other test failing other `test_vllm_tensorized_model_has_same_outputs`'s out of memory erroring? If not, why does #6810 remove tensorizer tests entirely from the CI pipeline, rather than simply skipping that test? 

Also, have there been any changes to test runners? This test wasn't complaining of OOM previously.

**Comment by youkaichao** [comment]
#6810 separates the test, but tensorizer test is still in the full ci test:

https://github.com/vllm-project/vllm/blob/062a1d0fab111723ab768f94bdd48a6adc054007/.buildkite/test-pipeline.yaml#L221

previously we test it twice, combined with some other tests.

**Comment by sangstar** [comment]
> #6810 separates the test, but tensorizer test is still in the full ci test:
> 
> https://github.com/vllm-project/vllm/blob/062a1d0fab111723ab768f94bdd48a6adc054007/.buildkite/test-pipeline.yaml#L221
> 
> previously we test it twice, combined with some other tests.

I see, thank you for the clarification! I will look to investigate this issue to ensure we can maintain full tensorizer testing in the CI suite.

**Comment by youkaichao** [comment]
> Are we sure proper cleanup is being carried out between tests? Are loaded models properly garbage collected between tests?

proper cleanup and garbage collection is indeed a possible cause. You can try to investigate, and, if this is the cause, you can at least isolate the tests.

**Comment by sangstar** [comment]
> > Are we sure proper cleanup is being carried out between tests? Are loaded models properly garbage collected between tests?
> 
> proper cleanup and garbage collection is indeed a possible cause. You can try to investigate, and, if this is the cause, you can at least isolate the tests.

Sounds good. Thank you for bringing this to my attention! I'll be investigating this matter.

**Comment by youkaichao** [comment]
@sangstar  it seems it becomes flaky again:

https://buildkite.com/vllm/ci-aws/builds/5830#0190f9e8-82ac-4fef-a7b7-53b012f20372

can you take a further look? thanks!

**Comment by sangstar** [comment]
> @sangstar  it seems it becomes flaky again:
> 
> 
> 
> https://buildkite.com/vllm/ci-aws/builds/5830#0190f9e8-82ac-4fef-a7b7-53b012f20372
> 
> 
> 
> can you take a further look? thanks!


Hi, thanks for bringing this to my attention. Will take a look.

**Comment by sangstar** [comment]
@youkaichao PR for the fix ready!

**Comment by youkaichao** [comment]
Looks like it is fixed now https://github.com/vllm-project/vllm/commits/main/ .

@sangstar thanks for the quick response!
