### ISSUE TITLE
[Question] How to store/pass past-key-values?

### ISSUE THREAD

**Issue by Justus-Jonas** [vllm-project/vllm#681]
Hi all,

I was wondering whether it is possible to store and pass on past key values from long prefix prompts. Has anyone tried this with vLLM before?

Many thanks!

**Comment by YijiaZhao** [comment]
Common prefix prompts in a batch?

**Comment by Justus-Jonas** [comment]
Hi @YijiaZhao 

thanks for your reply. Yes, indeed. I saw that you seem

**Comment by Justus-Jonas** [comment]
Hi @YijiaZhao,

thanks for your reply! Yes, indeed. I saw that you also worked on this (in [Issue 680](https://github.com/vllm-project/vllm/issues/680)). Did you find a solution?

**Comment by YijiaZhao** [comment]
I've not finished yet, I think there are two steps: 
1. Modify the KV cache(k, v = self.llm_engine.workers[worker_id].gpu_cache[layer_id])  
2. Modify the intput_metadata for every postfix

**Comment by YijiaZhao** [comment]
I've finished yet. I think it's easy to store the past KV cache, but hard to modify the attention for postfix calculation.

**Comment by zacharyblank** [comment]
@YijiaZhao I am looking for this too. Were you able to crack it? Thanks!

**Comment by pj-ml** [comment]
Also looking for this.

**Comment by hmellor** [comment]
https://github.com/vllm-project/vllm/issues/2614
