### ISSUE TITLE
[Bug]: Llama3.1-70B-FP8 Prompt insufficient computing power

### ISSUE THREAD

**Issue by SongXiaoMao** [vllm-project/vllm#6815]
### Your current environment

![2](https://github.com/user-attachments/assets/8967ff30-871b-4e63-9e64-4e821b3a3c54)
![xxx](https://github.com/user-attachments/assets/ef267444-fa79-447e-a92e-9808186c40c1)
The computing power of 3090 is 8.6, and the computing power of 4090 is 8.9. Does it mean that 3090 no longer supports FP8?

### 🐛 Describe the bug

![2](https://github.com/user-attachments/assets/8967ff30-871b-4e63-9e64-4e821b3a3c54)
![xxx](https://github.com/user-attachments/assets/ef267444-fa79-447e-a92e-9808186c40c1)
The computing power of 3090 is 8.6, and the computing power of 4090 is 8.9. Does it mean that 3090 no longer supports FP8?

**Comment by hmellor** [comment]
Yes, this means that 3090 cannot be used for FP8 in vLLM.

This error comes from the torch op `_scaled_mm`, not vLLM. As far as I can tell, this op has always been used for FP8 in vLLM.

(Link to error in `Blas.cpp` in PyTorch https://github.com/pytorch/pytorch/blob/945946e8173892d44c30e6d03bd7e3be0d50d00b/aten/src/ATen/native/cuda/Blas.cpp#L945)

**Comment by kulievvitaly** [comment]
https://docs.vllm.ai/en/latest/quantization/supported_hardware.html

It looks like there is an error in the supported hardware table. It says support fp8 instructions for ampere(3090)

**Comment by hmellor** [comment]
This has been fixed in the latest version of the table.
