### ISSUE TITLE
[Usage]: How to use vLLM on multi-nodes

### ISSUE THREAD

**Issue by quanshr** [vllm-project/vllm#6825]
### Your current environment

n nodes * 8 A100

### How would you like to use vllm

I want to deploy qwen2 model on multi nodes to speed up inference, but large TP may make it not a division of att heads and raise error, and PP is not implemented on qwen2. In fact, several independent parallel models on each node ensemble at one port may help. Is there any way to do that or achieve similar effects.

**Comment by robertgshaw2-neuralmagic** [comment]
Please consult the documentation, which has a page on multi-node

**Comment by quanshr** [comment]
Do you mean https://docs.vllm.ai/en/latest/serving/distributed_serving.html? I have carefully read them before raised the issue.
The problem is, since qwen2 do not support pipeline parallel yet, the only way to serve qwen in n nodes is setting tensor parallel size to n * 8 as there are such number of GPUs in total. However, it will make TP not a division of numbers of attention heads (e.g. 7B is 28) and cannot start up the server.

**Comment by youkaichao** [comment]
> qwen2 do not support pipeline parallel yet

it should be supported now.
