### ISSUE TITLE
llama 3 8b model with A10 GPU, OOM with VLLM, but holds good on HF transformer pipline

### ISSUE THREAD

**Issue by manickavela29** [vllm-project/vllm#6829]
Hi,

GPU : A10 24 GB
Model size with safe tensors : 26 GB all together

With HF pipeline, it was possible to load llama3 8b and then convert it too fp16 and run inference
but with VLLM, when I try to load the model itself, it goes OOM,

can this be understood that vllm requires a more memory at loading pace and not possible to handle this,
only after applying optimizations w.r.t model weights (quantization) will I be able to infer llama 3 8b?

blogs like this are kind of misleading with it
https://neuralmagic.com/blog/deploy-llama-3-8b-with-vllm/

              With int4 quantized models you can use parameter `--gpu-memory-utilization` that take up less GPU memory, for Llama3-8B, this parameter can be set to a minimum of 0.6(~12GB) with 4-bit quantization, but not with the original fp16 model(~19GB)!

_Originally posted by @yangxianpku in https://github.com/vllm-project/vllm/issues/2948#issuecomment-2122090059_

**Comment by robertgshaw2-neuralmagic** [comment]
L3-8B is ~16GB not 26GB ... so it should comfortably fit in an A10G gpu

What command are you using to launch vllm?

**Comment by manickavela29** [comment]
yes, L2-8B in fp16 is around 16 GB, but with FP32 it is around 26GB in size.
it is stored in safe tensors.

vllm load code

```
engine_args = EngineArgs(
    model=PATH,
    trust_remote_code=True,
    tensor_parallel_size=1,
    trust_remote_code=True,
    load_format="auto",
    dtype = "float16",
)
self.engine = LLMEngine.from_engine_args(engine_args)
```

HF transformer lib
```

self.pipeline = transformers.pipeline(
    "text-generation",  # task
    model=model_uri,
    tokenizer=self.tokenizer,
    trust_remote_code=True,
    device_map="auto",
    torch_dtype=torch.bfloat16, # or fp16 anything at this stage
    max_length=1024,
    max_new_token=512,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=self.tokenizer.eos_token_id,
)
```

when the model is exported to fp16, then VLLM is able to load and handle it
but with fp32 loading directly it is failing, 
hf with accelerate lib is able to handle it I think somehow managing the memory

or is it that I am missing something with VLLM params?

**Comment by robertgshaw2-neuralmagic** [comment]
looks fine. can you post the error that you see?

**Comment by robertgshaw2-neuralmagic** [comment]
the log

**Comment by manickavela29** [comment]
log :

> INFO 07-26 15:21:31 config.py:1151] Downcasting torch.float32 to torch.float16.
> INFO 07-26 15:21:31 llm_engine.py:161] Initializing an LLM engine (v0.4.3) with config: model='/app/model/', speculative_config=None, tokenizer='/app/model/',
>  skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_s
> eq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False,
> kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_mode
> l_name=/app/model/)
> [2024-07-26 15:21:36 +0000] [109] [ERROR] Exception in worker process
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
>     worker.init_process()
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process
>     self.load_wsgi()
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
>     self.wsgi = self.app.wsgi()
>   File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
>     self.callable = self.load()
>   File "/usr/local/lib/python3.8/dist-packages/seldon_core/gunicorn_utils.py", line 107, in load
>     self.user_object.load()
>   File "/app/ZeroShotSlotsV0vllm.py", line 38, in load
>     self.engine = LLMEngine.from_engine_args(engine_args)
>   File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 359, in from_engine_args
>     engine = cls(
>   File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 222, in __init__
>     self.model_executor = executor_class(
>   File "/usr/local/lib/python3.8/dist-packages/vllm/executor/executor_base.py", line 41, in __init__
>     self._init_executor()
>   File "/usr/local/lib/python3.8/dist-packages/vllm/executor/gpu_executor.py", line 24, in _init_executor
>     self.driver_worker.load_model()
>   File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 121, in load_model
>     self.model_runner.load_model()
>   File "/usr/local/lib/python3.8/dist-packages/vllm/worker/model_runner.py", line 134, in load_model
>     self.model = get_model(
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
>     return loader.load_model(model_config=model_config,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader/loader.py", line 240, in load_model
>     model = _initialize_model(model_config, self.load_config,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/model_loader/loader.py", line 91, in _initialize_model
>     return model_class(config=model_config.hf_config,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/llama.py", line 332, in __init__
> self.model = LlamaModel(config,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/llama.py", line 262, in __init__
>     self.layers = nn.ModuleList([
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/llama.py", line 263, in <listcomp>
>     LlamaDecoderLayer(config=config,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/llama.py", line 200, in __init__
>     self.mlp = LlamaMLP(
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/models/llama.py", line 69, in __init__
>     self.down_proj = RowParallelLinear(input_size=intermediate_size,
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/linear.py", line 707, in __init__
>     self.quant_method.create_weights(
>   File "/usr/local/lib/python3.8/dist-packages/vllm/model_executor/layers/linear.py", line 79, in create_weights
>     weight = Parameter(torch.empty(sum(output_partition_sizes),
>   File "/usr/local/lib/python3.8/dist-packages/torch/utils/_device.py", line 78, in __torch_function__
>     return func(*args, **kwargs)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/multiprocess/util.py", line 357, in _exit_function
>     p.join()
>   File "/usr/local/lib/python3.8/dist-packages/multiprocess/process.py", line 147, in join
>     assert self._parent_pid == os.getpid(), 'can only join a child process'
> AssertionError: can only join a child process

Observation : I am running this in docker, but when I try to run it locally directly 
Sometimes, very rarely, it is able to start the load process again and able to load it

**Comment by robertgshaw2-neuralmagic** [comment]
Do you have anything running on your GPU already?

**Comment by ywang96** [comment]
> when the model is exported to fp16, then VLLM is able to load and handle it
but with fp32 loading directly it is failing

I think this is expected on vLLM? You're trying to load an FP32 model that itself will take more GPU memory than the capacity by default. You could try enable offloading to CPU and see if that helps

**Comment by manickavela29** [comment]
> Do you have anything running on your GPU already?

yes, it is the only process running

**Comment by manickavela29** [comment]
> > when the model is exported to fp16, then VLLM is able to load and handle it
> > but with fp32 loading directly it is failing
> 
> I think this is expected on vLLM? You're trying to load an FP32 model that itself will take more GPU memory than the device's capacity by default. You could try enable offloading to CPU and see if that helps

thanks, I will try CPU Offloading , maybe that is what I am looking for

you are right about the sizes, but it is more towards the efficient loading capability,

there are 2 factors here
1. Model I have is in fp32
2. Loading them as fp16, so after loading memory will not be 26 GB but 16 GB is my expectation,

point 2 is observed with HF pipeline.
it just points out that VLLM can become much more efficient in handling this case 

Anyways I converted the model to fp16 and was able to load it safely
Thanks for the support

**Comment by manickavela29** [comment]
Apologies, even with fp16 model I am facing this issue with VLLM on A10 with 24 GB
I am running it with docker
I experimented with few variables to handle this but they are of no use as of now
but of no use
 max_parallel_loading_workers
 gpu_memory_utilization
