### ISSUE TITLE
Does vllm support CodeGeeX2-6b

### ISSUE THREAD

**Issue by aphrodite1028** [vllm-project/vllm#683]

**Comment by zhuohan123** [comment]
CodeGeeX2-6b is based on ChatGLM2. There are some PRs #649 #635 working on this.

**Comment by aphrodite1028** [comment]
> CodeGeeX2-6b is based on ChatGLM2. There are some PRs #649 #635 working on this. Should be supported after these PRs being merged.

thanks for your reply

**Comment by hmellor** [comment]
Closing as ChatGLM2 is now supported.
