### ISSUE TITLE
Add AliBi context scaling into vllm for Baichuan13B

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#686]
Hello,

any consideration add Alibi context scaling using ntk like method to support baichuan13b much more context length input?

there were some work did it: https://github.com/keezen/ntk_alibi

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
