### ISSUE TITLE
vllm doesn't work on long_context?

### ISSUE THREAD

**Issue by Zhuqln** [vllm-project/vllm#687]
thanks a lot for your extraordinary work!
when i use vllm to test long-text , i see a warning happened:
`Input prompt (15681 tokens) is too long and exceeds limit of 2560`
so vllm doesn't work on long_context? is there a special reason?

**Comment by godsakurapeng** [comment]
https://github.com/vllm-project/vllm/issues/525

**Comment by babytdream** [comment]
@Zhuqln Hi, How did you solve the length problem? I also encountered the same problem.

**Comment by Zhuqln** [comment]
check this https://github.com/vllm-project/vllm/pull/555#issue-1817617848
