### ISSUE TITLE
[Feature]: Support Python 3.12

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#6877]
### 🚀 The feature, motivation and pitch

I believe we eventually need to support 3.12 in the future. Right now I believe Pytorch just added support for Python 3.12, but ray still does not support Python 3.12. Let's use this issue to keep track on this.

**Comment by pcmoritz** [comment]
Ray has been providing Python 3.12 wheels since 2.31.0 and since 2.33.0 we are running all the Ray Core tests on Python 3.12 (https://github.com/ray-project/ray/pull/46650), so there is no reason to hold back upgrading :)

**Comment by seppd** [comment]
The project is not buildable from source with python 3.12:
```
% pip install -e .
...
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement vllm-flash-attn==2.5.9.post1 (from vllm) (from versions: none)
ERROR: No matching distribution found for vllm-flash-attn==2.5.9.post1
```
