### ISSUE TITLE
Min_tokens

### ISSUE THREAD

**Issue by rlasseri** [vllm-project/vllm#688]
Hi ! Thanks for your work,
A quick question is it possible to have a min_token parameters ? 
Thanks

**Comment by zhuohan123** [comment]
I believe this is possible. You should be able to force the generation not to finish in this function: https://github.com/vllm-project/vllm/blob/79af7e96a0e2fc9f340d1939192122c3ae38ff17/vllm/engine/llm_engine.py#L419

It would be great if you can contribute this feature!

**Comment by Lvjinhong** [comment]
So, has it been implemented now?

**Comment by hmellor** [comment]
You could use a negative length penalty https://github.com/vllm-project/vllm/blob/925f3332cac488e5ad2dbc8f5c6d5f42d2556816/vllm/sampling_params.py#L63-L64

**Comment by njhill** [comment]
This has now been implemented and will be in the next version: https://github.com/vllm-project/vllm/pull/3124
