### ISSUE TITLE
why our performance so low when compare with sglang(https://github.com/sgl-project/sglang?tab=readme-ov-file#benchmark-and-performance)

### ISSUE THREAD

**Issue by lw921014** [vllm-project/vllm#6929]
### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by mingboiz** [comment]
> We use vLLM 0.5.2 **with default arguments** and TensorRT-LLM v0.10.0 with the recommended arguments and tuned batch sizes. **The prefix cache is turned off for all engines**. The purpose is to benchmark the base performance without any additional features, such as speculative decoding or caching. OpenAI-compatible APIs are used to benchmark SGLang and vLLM, and the Triton interface for TensorRT-LLM.

From their blog: https://lmsys.org/blog/2024-07-25-sglang-llama3/
