### ISSUE TITLE
[Installation]: my env :cuda version is 12.0，python 3.10, which release should i choose? 

### ISSUE THREAD

**Issue by fanjikang** [vllm-project/vllm#6937]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
pip install -vvv vllm
```

**Comment by youkaichao** [comment]
I think `pip install -vvv vllm` should work. It is built against cuda 12.1

**Comment by fanjikang** [comment]
> I think `pip install -vvv vllm` should work. It is built against cuda 12.1

my system is　ubuntu22.04,the latest release is ubuntu20.04?

**Comment by fanjikang** [comment]
![image](https://github.com/user-attachments/assets/a8a1e12e-5ce4-4e5a-9707-efb166a44b9e)
请问这个安装指导里提到的支持cuda12.0  是下面的哪一个whl
![image](https://github.com/user-attachments/assets/5f062edd-2602-409f-951b-718c1edc05bd)

**Comment by linzhengtian** [comment]
用这个地址下，https://vllm-wheels.s3.us-west-2.amazonaws.com/abc/vllm-0.5.0%2Bcu124-cp310-cp310-linux_x86_64.whl
