### ISSUE TITLE
[Feature]: when will support torch2.4 use it out of box?

### ISSUE THREAD

**Issue by lucasjinreal** [vllm-project/vllm#6944]
### 🚀 The feature, motivation and pitch

[Feature]: when will support torch2.4 use it out of box?

### Alternatives

[Feature]: when will support torch2.4 use it out of box?

**Comment by mgoin** [comment]
We are working on update soon. Currently we require torch 2.4 wheels to be released for our xformers, flashinfer, and flash-attn dependencies. I believe flashinfer is the only hold-up at the moment.

**Comment by vikrantrathore** [comment]
> We are working on update soon. Currently we require torch 2.4 wheels to be released for our xformers, flashinfer, and flash-attn dependencies. I believe flashinfer is the only hold-up at the moment.

Flashinfer already supports torch 2.4 check the latest 0.1.3 release with torch 2.4.

https://github.com/flashinfer-ai/flashinfer/releases

**Comment by lucasjinreal** [comment]
thank u for the catching up
