### ISSUE TITLE
[Bug]: ValueError: Ray does not allocate any GPUs on the driver node. Consider adjusting the Ray placement group or running the driver on a GPU node.

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#6956]
### Your current environment

```text
The output of `python collect_env.py`
```

### 🐛 Describe the bug

We should improve the way we create the default placement group in 

https://github.com/vllm-project/vllm/blob/cbbc904470668b9420e71595edeef76d673a2d59/vllm/executor/ray_utils.py#L119-L131

1. If we are in a placement group, but it does not contain the current node, error out. (this is a rare case, users usually don't set placement groups)
2. If not, we are creating a placement group. Make sure it contains the current node.

**Comment by esmeetu** [comment]
Try to use `--engine-use-ray`, which let ray help you choose driver node.
