### ISSUE TITLE
Unexpected latency of StarCoder when enable tensor parallel

### ISSUE THREAD

**Issue by zhuohan123** [vllm-project/vllm#696]
### Discussed in https://github.com/vllm-project/vllm/discussions/666

<div type='discussions-op-text'>

<sup>Originally posted by **zhaoyang-star** August  3, 2023</sup>
The latency of StarCoder running on 2 A100 40GB is higher than that running on 1 A100. 
While, the latency of LLaMA-13B running on 2 A100 40GB is lower than that running on 1 A100 as expected. 

So does MultiQueryAttenion impl in vLLM cause this? 

![image](https://github.com/vllm-project/vllm/assets/24290792/ea66ad84-d8f3-4793-9970-ca70b07c13b0)
![image](https://github.com/vllm-project/vllm/assets/24290792/37a8c774-1b5a-4891-86db-ec464e79f58f)
Note: Prompt token length and output token length both are set to 1k.
</div>

**Comment by esmeetu** [comment]
how to reproduce this? I want test WizardCoder model(starcoder family) on my T4 GPUs.

**Comment by hmellor** [comment]
@zhuohan123 is this something you're still interested in investigating?

**Comment by zhuohan123** [comment]
I believe this should have been fixed with new version of vLLM
