### ISSUE TITLE
[Doc]: Supported Hardware for Quantization Kernels

### ISSUE THREAD

**Issue by YangwdX** [vllm-project/vllm#6979]
### 📚 The doc issue

I'm confused what "the quantization method is supported" mean?  Ampere arch doesn't support FP8, according to Nvidia. So does this mean the FP8 operation is supported on A100/A800 GPU?  Or just we can conver the weight parameters form FP16 to FP8?

**Comment by mgoin** [comment]
We have weight-only FP8 support on Ampere thanks for [FP8 Marlin](https://github.com/vllm-project/vllm/pull/5975). This means vLLM can load and infer with FP8 models on Ampere systems
