### ISSUE TITLE
[Bug]: 导入default_dump_dir报错

### ISSUE THREAD

**Issue by NoobPythoner** [vllm-project/vllm#6987]
### Your current environment

ubuntu Ubuntu 22.04.4 LTS
cuda 12.2 
vllm                                             0.5.3.post1      /home/gtlm/ai/zhangyr/vllm
vllm-flash-attn                                  2.5.9.post1

### 🐛 Describe the bug

运行vllm server 报错：
vllm/vllm/triton_utils/custom_cache_manager.py", line 3, in <module>
    from triton.runtime.cache import (FileCacheManager, default_cache_dir,
ImportError: cannot import name 'default_dump_dir' from 'triton.runtime.cache'

**Comment by feuler** [comment]
I have the same problem.

**Comment by HenryJunW** [comment]
@feuler  same issue. Does we need to upgrade the triton?

**Comment by NoobPythoner** [comment]
> I have the same problem.
> 
> Edit: It's fixed in the triton main branch

升级triton到3.0.0最新版,还是报同样的错误

**Comment by NoobPythoner** [comment]
vllm 0.5.2 没有这个问题

**Comment by feuler** [comment]
The "default_dump_dir" definition has been in this file for longer time. https://github.com/triton-lang/triton/blob/main/python/triton/runtime/cache.py
I haven't checked what's exactly wrong and why the import fails.

For me it works at the moment to build the triton master branch from source.
I guess it should also work using the triton nightly build till this is fixed:
pip install -U --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly
