### ISSUE TITLE
[Usage]: Add support for Python 3.12

### ISSUE THREAD

**Issue by Akira617** [vllm-project/vllm#6990]
### Background

I am currently using the vllm engine for my project, and I noticed that it does not support Python 3.12. Given that Python 3.12 includes several new features and performance improvements, it would be beneficial for this repository to support it.

### Additional Information

If there are any blockers or specific reasons why Python 3.12 is not currently supported, please let me know. I am willing to help with testing or any other tasks necessary to add support for this version.

Thank you for your consideration.

**Comment by mgoin** [comment]
Duplicates: https://github.com/vllm-project/vllm/issues/1218 https://github.com/vllm-project/vllm/issues/6877
