### ISSUE TITLE
whats the different meaning of prompt throughput and generation throughput

### ISSUE THREAD

**Issue by Zhuqln** [vllm-project/vllm#700]
hello gus! im not quite get the meaning about` prompt throughput` and `generation throughput`
because when i use long-text to do inference ,the ` prompt throughput` is so much high like 3thouands/s and the `generation throughput` nearly 0-7 tokens/s
but when i use normal-length context like 100 etc. the  `generation throughput` becomes normal but  ` prompt throughput` somotimes goes to 0.
i want to know whats the different meaning of the two?
using 1 req: `Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 27.8 tokens/s`

**Comment by ANYMS-A** [comment]
So what is the difference between those 2 concepts?

**Comment by Playerrrrr** [comment]
So what is it? @Zhuqln
