### ISSUE TITLE
[Usage]: weird GPU RAM usage

### ISSUE THREAD

**Issue by hieunguyenquoc** [vllm-project/vllm#7028]
### Your current environment

```text
Google Colab with T4 GPU
```

### How would you like to use vllm

I want to run inference of a fine-tune awq quantized version of Mistral called Vistral (https://huggingface.co/hiuman/Vistral-7B-Chat-quantize. When I load model with default gpu_memory_utilization (which is 0.9), it loads ok. But when I try to reduce the value of gpu_memory_utilization to 0.1, it gets the error :
'No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.'

I thought when I lower the value of gpu_memory_utilization, the less gpu memory will be use. Can anyone explain for me this issue ? Thank you.

Here is the code I am running : 
from vllm import LLM, SamplingParams
sampling_params = SamplingParams(temperature=0.1, top_p=0.95, max_tokens = 128)

llm = LLM(model="hiuman/Vistral-7B-Chat-quantize", quantization="AWQ",enforce_eager=True, gpu_memory_utilization=0.1)

**Comment by DarkLight1337** [comment]
`gpu_memory_utilization` actually sets a limit on how much memory vLLM is allowed to use (so `gpu_memory_utilization=0.1` means vLLM can only use 10% of your GPU). If you set it too low, the model may not be able to be loaded at all since there is a minimum memory requirement.

**Comment by hieunguyenquoc** [comment]
@DarkLight1337  .Thank you for your response. I understand now. I want ask one more question. Do you know how to measure the minium memory requirement for a model ? Thank you.

**Comment by DarkLight1337** [comment]
Apart from the model's weights, you also have to consider the memory taken up by the input data itself as it goes through the model. For performance reasons, you should use the default value (90%, the remaining 10% acts as a buffer) unless you have a specific reason why you can't take up the full GPU.

**Comment by hieunguyenquoc** [comment]
@DarkLight1337 Thank you for your explanation.

**Comment by Gaaaaam** [comment]
> Apart from the model's weights, you also have to consider the memory taken up by the input data itself as it goes through the model. For performance reasons, you should use the default value (90%, the remaining 10% acts as a buffer) unless you have a specific reason why you can't take up the full GPU.

Hi, I got a question about the memory usage: does the parameter ```gpu_memory_utilization``` limit the max GPU memory that model weights, KV caches and LoRA adapter could occupy while loading a LLM with LoRA adapter? In other words, the sum of these three (model weights, KV caches and LoRA adapter weights) cannot exceed the set value of the parameter.

**Comment by DarkLight1337** [comment]
Yes, it should include all of the memory used by vLLM.

**Comment by gamersover** [comment]
Hi there, I've got a question, why does my gpu memory slowly get full over time after handling a bunch of requests?

**Comment by DarkLight1337** [comment]
> Hi there, I've got a question, why does my gpu memory slowly get full over time after handling a bunch of requests?

Sounds like a memory leak, please open a new issue so it can be looked into separately.

**Comment by Gaaaaam** [comment]
> Yes, it should include all of the memory used by vLLM.

Got it, thanks for your reply 🌹
