### ISSUE TITLE
[Bug]: Llama 3.1 405 B FP8 model is not support by vLLM (v0.5.3.post1) on AMD GPU

### ISSUE THREAD

**Issue by jerin-scalers-ai** [vllm-project/vllm#7031]
### Your current environment

vLLM version: 0.5.3.post1 (For ROCm)
Model:  meta-llama/Meta-Llama-3.1-405B-Instruct-FP8
AMD MI300x GPU

### 🐛 Describe the bug

![Screenshot 2024-07-31 131408](https://github.com/user-attachments/assets/5b0771b4-8b4b-4303-9eff-df8b425aaf60)

vLLM is throwing value error when loading meta-llama/Meta-Llama-3.1-405B-Instruct-FP8 on AMD MI300x GPU.
Value Erorr: fbgemm_fp8 quantization is currently not supported in ROCm. Refer screenshot for reference.

**Comment by WoosukKwon** [comment]
Hi @jerin-scalers-ai, thanks for reporting the issue. Currently, FP8 is not supported by AMD GPUs. The vLLM and AMD teams are working not it. Please stay tuned.

**Comment by jerin-scalers-ai** [comment]
Thanks for clarification
