### ISSUE TITLE
run llama 3.1 405B has error[Usage]: 

### ISSUE THREAD

**Issue by kinglion811** [vllm-project/vllm#7074]
### Your current environment

```text
The output of `python collect_env.py`
```
environment
two node,node1 and node2,every node eth set is
eth0 is the controller network
eth1 to eth8 is the GPU RoCe network

vllm version：vLLM API server version 0.5.3.post1

the start command is：
GLOO_SOCKET_IFNAME=eth0  NCCL_SOCKET_IFNAME=eth0 TP_SOCKET_IFNAME="eth0"  vllm serve /models  --tensor-parallel-size 16 

the error is：
DEBUG 08-02 08:50:03 parallel_state.py:803] world_size=16 rank=0 local_rank=0 distributed_init_method=tcp://10.41.0.7:34773 backend=nccl
(RayWorkerWrapper pid=1978, ip=10.41.0.8) [rank9]:[W ProcessGroupGloo.cpp:721] **Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with** GLOO_SOCKET_IFNAME. (function operator())
(RayWorkerWrapper pid=1890, ip=10.41.0.8) [rank8]:[E ProcessGroupGloo.cpp:144] Gloo connectFullMesh failed with [../third_party/gloo/gloo/transport/tcp/pair.cc:144] no error
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382] Traceback (most recent call last):
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 374, in execute_method
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 132, in init_device
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     init_worker_distributed_environment(self.parallel_config, self.rank,
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 343, in init_worker_distributed_environment
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     init_distributed_environment(parallel_config.world_size, rank,
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 830, in init_distributed_environment
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     _WORLD = init_world_group(ranks, local_rank, backend)
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 714, in init_world_group
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     return GroupCoordinator(
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 149, in __init__
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     cpu_group = torch.distributed.new_group(ranks, backend="gloo")
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     func_return = func(*args, **kwargs)
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3868, in new_group
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3939, in _new_group_with_tag
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     pg, pg_store = _new_process_group_helper(
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]   File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1509, in _new_process_group_helper
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382]     backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
(RayWorkerWrapper pid=1890, ip=10.41.0.8) ERROR 08-02 08:50:03 worker_base.py:382] RuntimeError: Gloo connectFullMesh failed with [../third_party/gloo/gloo/transport/tcp/pair.cc:144] no error

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by kinglion811** [comment]
solve it by set:  -e GLOO_SOCKET_IFNAME="eth0" -e NCCL_SOCKET_IFNAME=eth0 -e TP_SOCKET_IFNAME=eth0  when docker run,if the container is running,you enter containers to set it,it not work.

**Comment by youkaichao** [comment]
this is stated in https://docs.vllm.ai/en/latest/serving/distributed_serving.html : 

> Note that setting environment variables in the shell (e.g. NCCL_SOCKET_IFNAME=eth0 vllm serve ...) only works for the processes in the same node, not for the processes in the other nodes. Setting environment variables when you create the cluster is the recommended way. See the [discussion](https://github.com/vllm-project/vllm/issues/6803) for more information.
