### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by palash-fin** [vllm-project/vllm#7106]
### Your current environment

Using docker [image](https://hub.docker.com/r/vllm/vllm-openai/tags)  as environment.

### 🐛 Describe the bug

There are multiple vulnerability due to base image used for building vllm image.
requesting to fix

**Comment by palash-fin** [comment]
![image](https://github.com/user-attachments/assets/c0ac375e-b1f4-4871-ba14-919e35efae1f)

**Comment by DarkLight1337** [comment]
Please see https://github.com/vllm-project/vllm/pull/6820
