### ISSUE TITLE
[Bug]: ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.

### ISSUE THREAD

**Issue by WangJianQ-0118** [vllm-project/vllm#7107]
### Your current environment

[root@localhost wangjianqiang]# python -m vllm.entrypoints.openai.api_server --model /root/wangjianqiang/deepseek-moe/deepseek-coder-33b-base/ --tensor-parallel-size 8 --port 9010 --host 0.0.0.0 --served-model-name deep --gpu-memory-utilization 0.9 --host 0.0.0.0
INFO 08-03 15:45:33 api_server.py:219] vLLM API server version 0.5.3.post1
INFO 08-03 15:45:33 api_server.py:220] args: Namespace(host='0.0.0.0', port=9010, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/root/wangjianqiang/deepseek-moe/deepseek-coder-33b-base/', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=8, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['deep'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
Unrecognized keys in `rope_scaling` for 'rope_type'='linear': {'type'}
INFO 08-03 15:45:34 config.py:715] Defaulting to use ray for distributed inference
WARNING 08-03 15:45:34 arg_utils.py:762] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
INFO 08-03 15:45:34 config.py:806] Chunked prefill is enabled with max_num_batched_tokens=512.
2024-08-03 15:45:37,248 INFO worker.py:1749 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/root/miniforge3/envs/Yi/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniforge3/envs/Yi/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniforge3/envs/Yi/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 317, in <module>
    run_server(args)
  File "/root/miniforge3/envs/Yi/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 231, in run_server
    if llm_engine is not None else AsyncLLMEngine.from_engine_args(
  File "/root/miniforge3/envs/Yi/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 463, in from_engine_args
    executor_class = cls._get_executor_cls(engine_config)
  File "/root/miniforge3/envs/Yi/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 435, in _get_executor_cls
    initialize_ray_cluster(engine_config.parallel_config)
  File "/root/miniforge3/envs/Yi/lib/python3.10/site-packages/vllm/executor/ray_utils.py", line 117, in initialize_ray_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.

### 🐛 Describe the bug

8卡GPU部署deepseekcoder-33b-base失败，但是这8张卡我都能获取到

**Comment by youkaichao** [comment]
> INFO 08-03 15:45:34 config.py:715] Defaulting to use ray for distributed inference

if you have 8 GPUs, usually it should use multiprocessing by default. This log means you might have `CUDA_VISIBLE_DEVICES` set and the program can only see a subset of GPUs.
