### ISSUE TITLE
[Performance]: under performing in comparision of sglang

### ISSUE THREAD

**Issue by meetzuber** [vllm-project/vllm#7108]
### Proposal to improve performance

vLLm is under performing in comparison with sglang. There is something which need optimization for better performance.

### Report of performance regression

https://lmsys.org/blog/2024-07-25-sglang-llama3/

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

**Comment by felixzhu555** [comment]
See #6801!
