### ISSUE TITLE
[Doc]: How to Build an AI Knowledge Base like AI-Ask with vLLM

### ISSUE THREAD

**Issue by jason-i-vv** [vllm-project/vllm#7133]
### 📚 The doc issue

Hello,

I am interested in building an AI knowledge base similar to the AI-Ask feature provided by vLLM. I have a few questions regarding its implementation:

	1.	How can I achieve the construction of such an AI knowledge base using vLLM?
	2.	Is it based on any specific open-source solutions or frameworks?
	3.	Are there any guidelines or documentation that could help in setting up a similar system?

Any insights or pointers would be greatly appreciated!

<img width="792" alt="image" src="https://github.com/user-attachments/assets/e4f6f7ca-72b2-4f9d-afbf-f62cbcba69e0">

Thank you!

**Comment by youkaichao** [comment]
you need to contact https://runllm.com/ .
