### ISSUE TITLE
[New Model]: Mantis

### ISSUE THREAD

**Issue by BrenchCC** [vllm-project/vllm#7143]
### The model to consider.

TIGER-Lab/Mantis-8B-siglip-llama3
https://huggingface.co/TIGER-Lab/Mantis-8B-siglip-llama3

### The closest model vllm already supports.

llava next

### What's your difficulty of supporting the model you want?

Siglip model support

**Comment by DarkLight1337** [comment]
Sorry for the delay, you can try out #10711 which adds full support for this model.
