### ISSUE TITLE
Langchain Support

### ISSUE THREAD

**Issue by SparshRastogi** [vllm-project/vllm#716]
Does VLLM currently support Langchain integration if yes it would be great if that could be added to the documentation

**Comment by mspronesti** [comment]
Not sure I see what it would mean for vllm to support langchain. However, vllm is supported in langchain (so, the other way around): here's the [implementation](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/vllm.py)

**Comment by pseudotensor** [comment]
I tried that implementation, but I found it much cleaner to just use OpenAI compliant mode in h2ogPT:

non-langchain: https://github.com/h2oai/h2ogpt/blob/main/src/gen.py#L1906C10-L1946
langchain: https://github.com/h2oai/h2ogpt/blob/main/src/gpt_langchain.py#L672-L756

**Comment by SparshRastogi** [comment]
> Not sure I see what it would mean for vllm to support langchain. However, vllm is supported in langchain (the other way around): here's the [implementation](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/vllm.py)

Yeah this was exactly what I was looking for thanks

**Comment by SparshRastogi** [comment]
> I tried that implementation, but I found it much cleaner to just use OpenAI compliant mode of vLLM in h2oGPT:
> 
> non-langchain: https://github.com/h2oai/h2ogpt/blob/main/src/gen.py#L1906C10-L1946 langchain: https://github.com/h2oai/h2ogpt/blob/main/src/gpt_langchain.py#L672-L756

I need that for Llama 2 model will it work with that as well?

**Comment by hmellor** [comment]
Closing as LangChain now supports OpenAI compatible servers.
