### ISSUE TITLE
[New Model]: mistral-large

### ISSUE THREAD

**Issue by mavershang** [vllm-project/vllm#7177]
### The model to consider.

https://huggingface.co/mistralai/Mistral-Large-Instruct-2407

**Comment by jon-chuang** [comment]
Hello, I am interested to try this out. I suspect we need at least TP=2 to have decent perf. Probably TP=4,PP=2.

**Comment by jon-chuang** [comment]
I think this should already be supported. https://github.com/vllm-project/vllm/blob/main/docs/source/models/supported_models.rst
