### ISSUE TITLE
[Model]: Support for Qwen-VL model

### ISSUE THREAD

**Issue by wsp317** [vllm-project/vllm#7192]
### 🚀 The feature, motivation and pitch

Thank you for considering support for the Qwen-VL-Chat model.
Qwen-VL-Chat is more flexible in situations that users could upload several images in different conversation turns compared to its competitor with similar model size.

**Comment by alex-jw-brooks** [comment]
I am looking into adding support for image inputs for Qwen-VL/Qwen-VL-Chat 😄

**Comment by hmellor** [comment]
Closing as duplicate of #962
