### ISSUE TITLE
[Installation]: run vllm in the rocm docker raied: RuntimeError: No HIP GPUs are available

### ISSUE THREAD

**Issue by hnhyzz** [vllm-project/vllm#7207]
### Your current environment

The host can see the GPUs, but processes inside Docker cannot. Any idea?

### How you are installing vllm

Build the vllm-rocm docker

**Comment by hnhyzz** [comment]
Using the following command to start the docker

docker run -it \
   --network=host \
   --privileged \
   --group-add=video \
   --ipc=host \
   --cap-add=SYS_PTRACE \
   --security-opt seccomp=unconfined \
   --device /dev/kfd \
   --device /dev/dri \
   -v ./meta-llama/:/app/model \
   vllm-rocm \
   bash

**Comment by aminnsabet** [comment]
Getting the same issue

**Comment by youkaichao** [comment]
cc @hongxiayang

**Comment by hongxiayang** [comment]
Can you run `rocminfo` inside docker container? what is the output outside the container and inside the container?

**Comment by hnhyzz** [comment]
The rocminfo cannot find any available gpu inside the container.&nbsp;


I fixed the problem by uninstalling docker-desktop and its builtin docker engine, and then installing the ordinary docker engine. I believe the docker engine used by docker-desktop has misconfiguration.


Regards
Zhe



发自我的iPhone


------------------ Original ------------------
From: Hongxia Yang ***@***.***&gt;
Date: Wed,Aug 28,2024 6:48 AM
To: vllm-project/vllm ***@***.***&gt;
Cc: hnhyzz ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vllm-project/vllm] [Installation]: run vllm in the rocm dockerraied: RuntimeError: No HIP GPUs are available (Issue #7207)





 
Can you run rocminfo inside docker container? what is the output outside the container and inside the container?

**Comment by hongxiayang** [comment]
Sounds good. Can you close the issue?
