### ISSUE TITLE
Issue with raylet error

### ISSUE THREAD

**Issue by ZihanWang314** [vllm-project/vllm#721]
Hi, I'm using vllm to run llama-13B on two V100-16GB GPUs. I deployed vllm with the API server. However, When the context is long, the server returns:

[2023-08-09 22:39:16,002 E 209 223] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2023-08-09_22-27-32_558284_37 is over 95% full, available space: 60427313152; capacity: 1599538507776. Object creation will fail if spilling is required.

and the model is stuck and cannot return anything. Is it because the GPU size is too small or is there any other approaches to resolve this issue? Thanks!

**Comment by irasin** [comment]
got the same warning, but the model is still running, just curious about what the warning message means

**Comment by Miraclemarvel55** [comment]
可以把有空间的目录挂载到/tmp/ray;
you could use "ln -f space_free_dir /tmp/ray"

**Comment by zigzagcai** [comment]
I am curious because I met the same problem, it seems that the disk space of ray spilling continues to grow until out of disk error accurs.

**Comment by yjjiang11** [comment]
I got same error. and "ln -s space_free_dir /tmp/ray" does not work for me

**Comment by oushu1zhangxiangxuan1** [comment]
how to specify not using /tmp/ray ?

**Comment by hanq-moreh** [comment]
Does someone resolve the issue?
I'm struggling with the same issue

**Comment by HAN-oQo** [comment]
> Does someone resolve the issue? I'm struggling with the same issue

I had the issue when I'm using a docker container.
I was able to circumvent the issue by mounting the empty directory to /tmp/ray.

For example,
```shell
mkdir ./tmp_local
docker run -v ./tmp_local:/tmp/ray ...
```

**Comment by kir152** [comment]
clean up disk and keep it under 95% usage, that should fix the issue

**Comment by CarloNicolini** [comment]
Is there a way to tell raylet to use another folder to temporary objects directly from vLLM options?

**Comment by tsvisab** [comment]
This is a problem when using managed services that use a container to run the model for you such as Vertex AI or Sage maker since container is started with args the user has no control over so you can't mount /tmp/ over the host's volume to get more storage..

**Comment by tsvisab** [comment]
If you're running the model with a container, specify enough size for shared memory via `--shm-size` arg
then, within your container:

        ray.init(_temp_dir="/dev/shm/tmp_or_whatever", num_gpus=NUM_GPUS, ...)

**Comment by rkooo567** [comment]
> clean up disk and keep it under 95% usage, that should fix the issue

This is the proper solution. When your disk space reaches to 100%, the things will anyway hang. I think it is likely you guys huggingface cache is full of model weights downloaded.

**Comment by weishengying** [comment]
first:  rm /tmp/ray -f
then: mkdir a empty dir that use high disk usage,
then: ln -s new_empty_dir /tmp/ray
final: check the soft link is successful?  df /tmp/ray

**Comment by Liquidmasl** [comment]
> > Does someone resolve the issue? I'm struggling with the same issue
> 
> I had the issue when I'm using a docker container. I was able to circumvent the issue by mounting the empty directory to /tmp/ray. I hope this solution could help someone.
> 
> For example,
> 
> ```shell
> mkdir ./tmp_local
> docker run -v ./tmp_local:/tmp/ray ...
> ```

I dont quite understand this thread. 

what is the actual issue here?

I am facing this issue as well with a docker container using ray. Not actually using vllm.
But the issue is the same I suppose. 
I have enough hard drive storage, but it somehow calculates the 'available space' wrong. 
so I read mounting a random empty folder from the host machine to the tmp folder helps there? why? how? does it make it slower?

**Comment by heyzude** [comment]
> 可以把有空间的目录挂载到/tmp/ray; you could use "ln -s space_free_dir /tmp/ray"

Do
```rm -rf /tmp/ray
ln -s  <dir_with_lots_of_allowed_space> /tmp/ray```

**Comment by dzyanshan** [comment]
When starting a container, add the following parameter: --shm-size=100gb

**Comment by miandai** [comment]
Please check whether the value of the -- tensor parallel size parameter exceeds the CUDA_VISIBLE_DEVICES value. If it exceeds the limit, this error will be reported.
