### ISSUE TITLE
[Bug]: Tensor parallelism fails to configure correctly when using MIG instances

### ISSUE THREAD

**Issue by joe-schwartz-certara** [vllm-project/vllm#7211]
### 🐛 Describe the bug

I found a bug when trying to run a model with vllm across 2 GPU MIG partitions. I traced it back because it wasn't too hard to find but I don't know how the devs of vllm would want to move forward. I understand the intent of vllm is to take out a lot of the horrible pain of GPU management between nvidia, cuda, python, etc. but as a developer using vllm, my opinion is the ecosystem of dynamic GPU management is severely lacking as a whole and vllm is trying to plug the holes in the boat valiantly but in the end I foresee never ending issues like this. Anyway:

https://github.com/vllm-project/vllm/blob/00afc7859072bdcaba30611c6563f2f7ac7104a3/vllm/executor/ray_gpu_executor.py#L200
The issue here is that I have to set CUDA_VISIBLE_DEVICES as strings before I launch ray & vllm since that is the syntax cuda uses for MIG partition allocation :
https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#cuda-visible-devices

Thus i get: 

ValueError: invalid literal for int() with base 10: 'MIG-2e782cfd-36f2-55ff-a7d5-c6734444be2b'
(pid=586) /miniforge3/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
(pid=586)   warnings.warn(
Exception ignored in: <function RayGPUExecutorAsync.__del__ at 0x7f93b01c1e10>
Traceback (most recent call last):
  File "/miniforge3/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 473, in __del__
    if self.forward_dag is not None:
AttributeError: 'RayGPUExecutorAsync' object has no attribute 'forward_dag'

**Comment by youkaichao** [comment]
see https://github.com/vllm-project/vllm/issues/6551

we will not support MIG instance directly. You need to hide the heterogeneity through docker.

it is even worse if you want to use tensor parallel across mig instances. I don't think NCCL will support it. In this case, you should get a larger mig partition to directly hold the model weights. You don't need tensor parallel.

**Comment by joe-schwartz-certara** [comment]
In what way can I hide the fact that only a MIG partition is exposed thru docker? I am already running vllm in a container inside a pod that has gpu's exposed to it via the k8 nvidia device plugin.  I will also mention that vllm DOES work when I use a single MIG instance as the gpu. It is only a bug when vllm tries to launch a ray worker on a mig partition.

**Comment by epark001** [comment]
would also like to mention that using a single mig instance works completely fine for me with no performance degradations but multiple mig with tp does not work
