### ISSUE TITLE
[Bug]: With frontend multiprocessing the openai server hangs if there is an initialization error

### ISSUE THREAD

**Issue by maxdebayser** [vllm-project/vllm#7213]
### Your current environment

The environment is not relevant for this issue.

### 🐛 Describe the bug

With frontend multiprocessing, if there is an error in the initialization if the LLMEngine, the server prints the stack trace and then hangs and has to be killed. The expected behavior is that the server would exit, ideally with a non-zero status.

Reproducing this error is pretty simple. Just add `raise Exception("foo")` at the first line of `AsyncLLEngine.from_engine_args()`. 

Passing `--disable-frontend-multiprocessing` makes this problem go away.

**Comment by maxdebayser** [comment]
This happens with version `1f26efb`.

**Comment by robertgshaw2-neuralmagic** [comment]
Thanks, I will fix this
