### ISSUE TITLE
vllm如何量化部署

### ISSUE THREAD

**Issue by xxm1668** [vllm-project/vllm#722]

**Comment by fengenbao** [comment]
目前应该没量化，自己写或者直接加载量化的模型吧

**Comment by xxm1668** [comment]
@fengenbao 量化代码有推荐的吗？

**Comment by LiVincent-Zhang** [comment]
It seems quantization is not supported yet. #316

**Comment by xxm1668** [comment]
谢谢

**Comment by hmellor** [comment]
Closing because vLLM does now support quantization

**Comment by fredliu168** [comment]
https://github.com/fredliu168/GLM4_openai_api.git,我改的代码，不是很完善但是可以参考一下
