### ISSUE TITLE
Can vllm support Chat mode？such as human talk ai via Baichuan-13B-Chat model,rather than model.forward()

### ISSUE THREAD

**Issue by Storm0921** [vllm-project/vllm#725]
**current output will automatically complete the prompt, which is not what I want**
![image](https://github.com/vllm-project/vllm/assets/57557769/017a1202-c6af-4b43-822c-7b0cfa0ebbb1)

**expect output** 
![企业微信截图_16916352159786](https://github.com/vllm-project/vllm/assets/57557769/8bc61949-c765-4b9f-a974-b2ae037c970b)

I find TGI have the same question，so i expect vLLM can support a Chat mode，we can communicate with the model normally

**Comment by xusenlinzy** [comment]
here is the usage of vllm for chinese models such as baichaun, qwen: https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md

which is fixed from https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/openai/api_server.py

**Comment by hmellor** [comment]
Closing as this is now supported via the `/v1/chat/completions` API in the OpenAI server.
