### ISSUE TITLE
[Feature]: Support to use draft models with different vocabulary sizes for speculative decoding

### ISSUE THREAD

**Issue by peakji** [vllm-project/vllm#7252]
### 🚀 The feature, motivation and pitch

In most open-source LLM families, models with different parameters use the same tokenizer and vocabulary. However, due to differences in GPU infrastructure during training, they might use different numbers of padding tokens, resulting in different `vocab_size` values.

For instance, the `vocab_size` of Qwen2's [1.5B version](https://huggingface.co/Qwen/Qwen2-1.5B-Instruct/blob/main/config.json) is **151936**, while the [72B version](https://huggingface.co/Qwen/Qwen2-72B-Instruct/blob/main/config.json) is **152064**. These padding tokens are essentially [meaningless at inference time](https://github.com/QwenLM/Qwen2/issues/466), but when used for speculative decoding, vLLM raises an error due to the mismatch in vocabulary size.

Therefore, I propose adding an engine argument, such as `--disable-vocab-check-for-spec-decoding`, to allow the use of draft models with different vocabulary sizes upon user confirmation.

### Alternatives

Adding a new engine argument is definitely the most reliable approach. Alternatively, perhaps we can relax the check on vocabulary sizes, ensuring only that the draft model's `vocab_size` is less than or equal to that of the target model.

**Comment by mscheong01** [comment]
I agree that this problem should be handled 👍 
Simply disabling vocab check could cause problems when tokens that exist on only one model is sampled. Instead, I was wondering if some sort of vocab matching mechanism could be inserted between the two models
for example:
when loading model workers, we could compare the model vocab tokens and:
1. map special tokens
2. map tokens that have same representing text
3. for leftover tokens(that failed to map), when they are sampled, use a tokenid(draft) -(detokenize)-> text -(tokenize)-> tokenid(base) method to map the token
4. If everything doesn't work, convert to unknown token

Maybe it's to complicated, but if we could make this work, speculative decoding between models with completely different vocab would be possible.

**Comment by peakji** [comment]
@mscheong01  Speculative decoding with completely different models sounds good, but considering that the training data of different models may vary greatly, I'm not sure if the token acceptance rate in this case can achieve the goal of improving efficiency. Maybe this could be a separate (and more complicated) feature request?

**Comment by mklasby** [comment]
Given the success of universal assisted generation in `transformers`, is there any interest in revisiting this feature request? @danielkorat has your team considering intergration with vLLM?

**Comment by danielkorat** [comment]
> Given the success of universal assisted generation in `transformers`, is there any interest in revisiting this feature request? [@danielkorat](https://github.com/danielkorat) has your team considering intergration with vLLM?

Hi @mklasby, this would be a great addition to vLLM. However, we are mainly a research focused team and we don't have the resources for this project right now.
