### ISSUE TITLE
[Bug]: Cannot use FlashAttention-2 backend with vllm0.5.4

### ISSUE THREAD

**Issue by wikithink** [vllm-project/vllm#7254]
### Your current environment

```text
ubuntu20.04+python3.10.14+cuda11.8+cudnn8.9.6+A100

vllm==0.5.4
torch==2.4.0+cu118
transformers==4.44.0
flash-attn == 2.6.1
vllm-flash-attn == 2.6.1
Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. pip install vllm-flash-attn for better performance.
INFO 08-07 15:31:39 selector.py:54] Using XFormers backend.

import flash_attn
successful
```

### 🐛 Describe the bug

INFO 08-07 16:06:47 selector.py:189] Cannot use FlashAttention-2 backend because the vllm_flash_attn package is not found. `pip install vllm-flash-attn` for better performance.
INFO 08-07 16:06:47 selector.py:54] Using XFormers backend.

**Comment by youkaichao** [comment]
it needs `vllm-flash-attn`, not `flash_attn`. and `vllm-flash-attn` is not built for cuda 11.8 yet. see https://github.com/vllm-project/vllm/issues/6639
