### ISSUE TITLE
[Feature]: support longer max_num_batched_tokens for lora

### ISSUE THREAD

**Issue by NiuBlibing** [vllm-project/vllm#7259]
### 🚀 The feature, motivation and pitch

Support longer max_num_batched_tokens  for lora to free long context ablitity of many models have long context such as qwen2(128k).

### Additional context

https://github.com/vllm-project/vllm/blob/main/vllm/config.py#L1379-L1386

**Comment by jeejeelee** [comment]
The current vLLM's LoRA kernel  has been replaced with triton-implemented version. You can comment out this snippet and test if it supports up to 128K.

**Comment by NiuBlibing** [comment]
It works.
