### ISSUE TITLE
What a fast tokenizer can be used for Baichuan-13b?

### ISSUE THREAD

**Issue by FURYFOR** [vllm-project/vllm#726]
"When I was running baichuan-13b, I received the following warning: 'Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.' How can I solve this? What  a fast tokenizer can I use?"

**Comment by lhy101** [comment]
same question

**Comment by Alienfeel** [comment]
+1

**Comment by ansvver** [comment]
+1

**Comment by ericg108** [comment]
same. 
And I have met another problem, which is I got worse results when inferring with only 1 input and unusable results when inferring with multiple inputs. weird.

I have tried to align the samplingparams with the generation config in Baichuan's code, which is below
`SamplingParams(temperature=0.3, top_p=0.85, top_k=5, max_tokens=4096, presence_penalty=1.1)`

**Comment by cangyi071** [comment]
I have met the same question,do we need to write a new fast tokenzier?

**Comment by cangyi071** [comment]
how long do you load baihcuan2_13b?
请教楼主，你加载13b模型需要多久时间呢

**Comment by DseidLi** [comment]
same problem

**Comment by Gittkm** [comment]
same problem，how to solve it...help....
