### ISSUE TITLE
Invalid setting of environment variables on vllm startup 

### ISSUE THREAD

**Issue by Tomorrowxxy** [vllm-project/vllm#728]
command:
```
HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python -m vllm.entrypoints.openai.api_server --model baichuan-inc/Baichuan-13B-Chat --host 0.0.0.0 --port 1234 --trust-remote-code --dtype half
```
I want to make the model run offline, but setting `HF_DATASETS_OFFLINE = 1 TRANSFORMERS_OFFLINE = 1` is invalid.
Besides using --model to set the specified directory, is there any other solution?

[Reference HF](https://huggingface.co/docs/transformers/installation#offline-mode:~:text=Run%20this%20same%20program%20in%20an%20offline%20instance%20with%3A)
@WoosukKwon @zhuohan123

**Comment by njhill** [comment]
Related: https://github.com/vllm-project/vllm/pull/3125
