### ISSUE TITLE
[Feature]: For Meta-Llama-3.1-70B-Instruct model, no usage info included while stream equal to True

### ISSUE THREAD

**Issue by nikhilcms** [vllm-project/vllm#7299]
### 🚀 The feature, motivation and pitch

Hello,
as with Meta-Llama-3-70B output response include usage information which contains prompt_token, total_tokens and completion_tokens in the last chunk.

but after deployment with Meta-Llama-3.1-70B-Instruct using latest vllm image (`vllm/vllm-openai:v0.5.4`) I am not getting None usage:

ChatCompletionChunk(id='chat-facd596ff0a44e4d2ca48006f11b', choices=[Choice(delta=ChoiceDelta(content='1', function_call=None, refusal=None, role=None, tool_calls=None), finish_reason='length', index=0, logprobs=None, stop_reason=None)], created=1723117897, model='Llama-3.1-70B-Instruct', object='chat.completion.chunk', service_tier=None, system_fingerprint=None, usage=None)

please correct me if I am doing wrong anywhere or still usage not added there ?

**Comment by DarkLight1337** [comment]
You have to set `stream_options` in order to return usage info in stream mode.

**Comment by nikhilcms** [comment]
Yeah , I have enabled stream=True to openai endpoint,.but I am getting
usage=None in all chunk dictionary

**Comment by DarkLight1337** [comment]
I am talking about `stream_options`, not `stream`. Both have to be specified.

**Comment by nikhilcms** [comment]
even after setting stream_options=True and stream=True, I am getting usage=None , its happening only for Meta-Llama-3.1-70B-Instruct deployment only.
I am using latest openai==1.40.1 package

**Comment by DarkLight1337** [comment]
> Hi @DarkLight1337 even after setting stream_options=True and stream=True, I am getting usage=None , its happening only for Meta-Llama-3.1-70B-Instruct model deployment only. I am using latest openai==1.40.1 package
> 
> for you with llama3.1-70b did you get usage info with stream = True

I think you should set `stream_options={"include_usage": True}`. Please consult the official OpenAI docs.

**Comment by nikhilcms** [comment]
@DarkLight1337 , its a vllm issue in the output json content itself usage info not present then how openai will show it ?

when you set stream=False you will get the usage info

**Comment by DarkLight1337** [comment]
I mean that when you set `stream=True`, the usage info will not display by default unless you set `stream_options={"include_usage": True}`.

**Comment by nikhilcms** [comment]
Thanks , I fixed issues after adding that params
