### ISSUE TITLE
can not run baichuan-13B  in v100

### ISSUE THREAD

**Issue by dengfenglai321** [vllm-project/vllm#730]
hello
when I run code as below:
`from vllm import LLM

llm = LLM(model='baichuan-inc/Baichuan-13B-Chat', trust_remote_code=True)  # Name or path of your model
output = llm.generate("Hello, my name is")
print(output)`

and error occur:

  **ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0.**

v100 can not run baichuan-13B-Chat in vllm??
could you help me?

**Comment by Marten2016** [comment]
add parameters in cli : --dtype half

**Comment by Shajiu** [comment]
这个问题怎么处理哇？ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0.

**Comment by watreyoung** [comment]
直接在llm = LLM(model='baichuan-inc/Baichuan-13B-Chat', trust_remote_code=True) # Name or path of your model参数里加 dtype='half'即可。
具体可以看 https://github.com/vllm-project/vllm/commit/1ac4ccf73c91370f1fcb4f60c1117646cd7a7502
相关的问题在：https://github.com/vllm-project/vllm/issues/1157
