### ISSUE TITLE
[Bug]: CI will not run `fastcheck` if `ready` label is applied

### ISSUE THREAD

**Issue by jon-chuang** [vllm-project/vllm#7306]
This is problematic as CI looks like it ran all tests but only ran the /pr/ ones

**Comment by simon-mo** [comment]
I believe this is by design? @khluu

**Comment by jon-chuang** [comment]
The problem is that some tests are skipped in this case like `core-test`. I don't think this is covered by `/pr/`

Perhaps CI needs to add some logic that if `fastcheck` is not yet run, it should still be run even if `ready` label is applied?

**Comment by jon-chuang** [comment]
Escalated to the vllm buildkite repo: https://github.com/vllm-project/vllm/issues/7306

**Comment by jon-chuang** [comment]
This might be the source of the issue? @khluu  https://github.com/vllm-project/buildkite-ci/commit/b95784388d61fceb94d6830002757a390d45eb71

**Comment by khluu** [comment]
@jon-chuang  We also enabled conditional testing recently so that's why CI didn't run all tests like before but only ran some based on your changes. Core test in this case would only run if files in `vllm/core, vllm/distributed, tests/core` change.

**Comment by khluu** [comment]
`fast-check` was designed to run a subset of CI tests, so when `ready` label is applied, we should run CI and not `fast-check`

**Comment by jon-chuang** [comment]
Makes sense, thank you.

I don't have access to buildkite to control the tests.
![image](https://github.com/user-attachments/assets/f3c438c0-aef6-4baf-bb3d-f06206e2315f)

I just feel a little nervous when not all tests run.

Especially as it's weird to me that a test will run in fastcheck but not the full pipeline.

**Comment by khluu** [comment]
@jon-chuang  I can add you to the org on Buildkite so you can trigger more tests. What's a good email for that?
Ya we are still observing how conditional testing works, and if it's stable enough we probably will sunset `fast-check`.

**Comment by jon-chuang** [comment]
sg. My github email is jonabirdd at gmail dot com

**Comment by khluu** [comment]
invited!
