### ISSUE TITLE
When I set tensor_parallel_size to 2, why is the inference so much slower than it is for a single card

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#732]
When I set tensor_parallel_size to 2, why is the inference so much slower than it is for a single card

**Comment by Imagium719** [comment]
NVLink is all you need.

**Comment by nutmilk10** [comment]
> NVLink is all you need.

Can you show an example of how NVLINK would be incorporated? Thanks

**Comment by hmellor** [comment]
Closing as duplicate of #689
