### ISSUE TITLE
[Usage]: How to config the parameters to support higher concurrency for deploying the qwen2-7b model as an API at 8-GPU A800 (80G) server?

### ISSUE THREAD

**Issue by ybdesire** [vllm-project/vllm#7325]
### Your current environment

```text
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.2
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A800-SXM4-80GB
GPU 1: NVIDIA A800-SXM4-80GB
GPU 2: NVIDIA A800-SXM4-80GB
GPU 3: NVIDIA A800-SXM4-80GB
GPU 4: NVIDIA A800-SXM4-80GB
GPU 5: NVIDIA A800-SXM4-80GB
GPU 6: NVIDIA A800-SXM4-80GB
GPU 7: NVIDIA A800-SXM4-80GB

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

### How would you like to use vllm

I have one GPU server with 8-GPU A800 (80G). 
And I want to serve the model qwen2-7b as OpenAI API. The qwen2-7b can be run one GPU.
I want to run 8 models paralleling as 8 instances to support multiple API requests concurrently.  
The basic requirement is as below pic shows.

![image](https://github.com/user-attachments/assets/99555837-e1cd-4134-aa64-a88928760797)

Below is my cmd (8-gpu-serve) :

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m vllm.entrypoints.openai.api_server \
    --model /data/models/Qwen2-7B-Instruct/ \
    --served-model-name aaa \
    --trust-remote-code \
    --tensor-parallel-size 1 \
    --pipeline-parallel-size 8 \
    --port 8000
```

But my multiprocessing test shows the request average response time of 50 processes is almost the same as below (1-gpu-serve):

```
CUDA_VISIBLE_DEVICES=0 python -m vllm.entrypoints.openai.api_server \
    --model /data/models/Qwen2-7B-Instruct/ \
    --served-model-name aaa \
    --trust-remote-code \
    --tensor-parallel-size 1 \
    --pipeline-parallel-size 1 \
    --port 8000
```

My question is how to set the parameters to get better concurrency to use 8 GPUs ?

**Comment by jon-chuang** [comment]
I think you should just spawn more instances as follows

```
for X in 0..8
CUDA_VISIBLE_DEVICES=X python -m vllm.entrypoints.openai.api_server \
    --model /data/models/Qwen2-7B-Instruct/ \
    --served-model-name aaa-X \
    --trust-remote-code \
    --tensor-parallel-size 1 \
    --pipeline-parallel-size 1 \
    --port 800X
```

And then a http proxy which round robin forwards requests to each... 🤔

**Comment by ybdesire** [comment]
@jon-chuang Thanks for the reply. And can vllm support better concurrency itself for multiple GPU?

**Comment by jon-chuang** [comment]
Probably but if you want you can also use something like Ray serve, then you can scale out to multi node with single control plane entrypoint.

You can also use K8s for the multi node scale out.

**Comment by ybdesire** [comment]
Finally form my test, the "litellm+vllm" has best concurrency than "vllm multi-GPU multi-node" and "vllm multi-GPU one-node".
As https://github.com/vllm-project/vllm/issues/7202
Thanks @jon-chuang for the help
