### ISSUE TITLE
为了便于交流，创建了一个多模态大模型交流群，欢迎大家入群交流学习~

### ISSUE THREAD

**Issue by feihuamantian** [vllm-project/vllm#7328]
### 📚 The doc issue

可以扫码入群，如果二维码失效，可以加我微信拉入群：yx116169
![20240808-153649](https://github.com/user-attachments/assets/01fe1819-bc8b-4533-8c88-7568f701747a)

### Suggest a potential alternative/fix

1

**Comment by DarkLight1337** [comment]
Please don't advertise via GitHub Issues.

**Comment by feihuamantian** [comment]
> Please don't advertise via GitHub Issues.

so sorry, it is not advertisement, just a group of communication in vlm field , OK, I close it
