### ISSUE TITLE
[Usage]:  流式输出前面几个字符为啥要设置成空字符？不能直接输出模型的生成吗

### ISSUE THREAD

**Issue by ZZhangxian** [vllm-project/vllm#7330]
### Your current environment

 流式输出前面几个字符为啥要设置成空字符？不能直接输出模型的生成吗

### How would you like to use vllm

 流式输出前面几个字符为啥要设置成空字符？不能直接输出模型的生成吗

**Comment by unix1986** [comment]
@ZZhangxian 新版本默认使用了chunked_prefill技术，就是将prompt部分分成几个chunk，分多次迭代计算，在最后一个chunk计算完成前是没发产生输出的，所以前边几个是空字符。当然server端可以将空字符跳过不输出，vLLM默认没这么做。可参考文档：https://docs.vllm.ai/en/latest/models/performance.html

**Comment by ZZhangxian** [comment]
> @ZZhangxian 新版本默认使用了chunked_prefill技术，就是将prompt部分分成几个chunk，分多次迭代计算，在最后一个chunk计算完成前是没发产生输出的，所以前边几个是空字符。当然server端可以将空字符跳过不输出，vLLM默认没这么做。可参考文档：https://docs.vllm.ai/en/latest/models/performance.html

还有一个问题，多并发流式输出的时候，会出现多个token一起返回的情况，不是一个token的返回
