### ISSUE TITLE
[Feature]: Small Model Large Latency Compared to SGLang and TensorRT-LLM

### ISSUE THREAD

**Issue by CambioML** [vllm-project/vllm#7339]
### 🚀 The feature, motivation and pitch

In this post, https://lmsys.org/blog/2024-07-25-sglang-llama3/, it looks like vllm is not efficient in small model size in both online and offline benchmark. What is the bottleneck for vllm for small model inference and whether this will be addressed to catch SGLang and TensorRT performance.

**Comment by mgoin** [comment]
This is a duplicate issue and is currently being tracked/addressed by this Performance Roadmap meta issue https://github.com/vllm-project/vllm/issues/6801

**Comment by robertgshaw2-neuralmagic** [comment]
closing per michael's comment
