### ISSUE TITLE
LLM init baichuan 13B get error "trust_remote_code"

### ISSUE THREAD

**Issue by jienimi** [vllm-project/vllm#734]
Tot an unexpected keyword argument 'trust_remote_code', while init model .

│    20 │   if is_vllm:                                                        │
│    21 │   │   # lora_weights = torch.load(os.path.join(lora_weights, 'adapte │
│    22 │   │                                                                  │
│ ❱  23 │   │   model = LLM(model_dir, dtype='float16',**trust_remote_code=True**) │
│    24 │   │                                                                  │
│    25 │   │   # lora_merge_unmerge_state_dict(model, lora_weights)           │
│    26 │   │   return tokenizer, model                                        │
│                                                                              │
│ /usr/share/python3/lib/python3.9/site-packages/vllm/entrypoints/llm.py:53 in │
│ __init__                                                                     │
│                                                                              │
│    50 │   ) -> None:                                                         │
│    51 │   │   if "disable_log_stats" not in kwargs:                          │
│    52 │   │   │   kwargs["disable_log_stats"] = True                         │
│ ❱  53 │   │   engine_args = EngineArgs(                                      │
│    54 │   │   │   model=model,                                               │
│    55 │   │   │   tokenizer=tokenizer,                                       │
│    56 │   │   │   tokenizer_mode=tokenizer_mode,                             │
╰──────────────────────────────────────────────────────────────────────────────╯
**TypeError: __init__() got an unexpected keyword argument 'trust_remote_code'**

**Comment by HermitSun** [comment]
The latest code has added the `trust_remote_code` argument. You can try to reinstall vLLM from the latest code.
https://github.com/vllm-project/vllm/blob/805de738f618f8b47ab0d450423d23db1e636fa2/vllm/engine/arg_utils.py#L59-L61

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
