### ISSUE TITLE
[Bug]: LLama3 LoRA load failed

### ISSUE THREAD

**Issue by victorlwchen** [vllm-project/vllm#7344]
### Your current environment

vllm 0.5.4

### 🐛 Describe the bug

I try to load llama3-8B lora model but encounter error as bellow:
 ValueError: While loading /models/llama3-8b-instruct-lora-0719-r64, expected target modules in ['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj', 'embed_tokens', 'lm_head'] but received ['w2', 'w3', 'w1']. Please verify that the loaded LoRA module is correct

I searched the issues for problems related to LoRA and found that it might be due to the lack of support for w1, w2, and w3. Additionally, the supported_lora_modules in the model of llama doesn't include these items. 
If I want to properly use LoRA with LLaMA3, should I avoid these layers during model finetune, or will there be support for them in the future?

**Comment by jeejeelee** [comment]
I think you should first check if any LoRA files for other models have been loaded.

**Comment by victorlwchen** [comment]
> I think you should first check if any LoRA files for other models have been loaded.

Thank you for your reply. I have checked that the base model doesn't contain these layers. The error might have occurred due to using a finetune configuration from another model.
