### ISSUE TITLE
[Bug]: internvl2-8b 提问无限循环回答

### ISSUE THREAD

**Issue by haoduoyu1203** [vllm-project/vllm#7348]
### Your current environment

单机一张3090一张2080ti 22g 执行vllm serve /home/a/lmdeploy/InternVL2-8B --dtype auto --max-model-len 8192 --api-key token-abc123 --gpu_memory_utilization 1 --trust-remote-code --port 23333 --tensor-parallel-size 2 --enforce-eager --dtype=half    
启动  提问无限循环回答。 当--tensor-parallel-size 1时没有问题
![错误1](https://github.com/user-attachments/assets/3b9d1219-547a-4357-8259-7e626eb15c67)

![错误2](https://github.com/user-attachments/assets/bc1ab725-7b6b-4034-8f32-9d077974e8ee)

### 🐛 Describe the bug

INFO 08-09 18:47:10 logger.py:36] Received request chat-2ace427447e347df91be974ae56f34ce: prompt: '<s><|im_start|>system\n\nCurrent model: /home/a/lmdeploy/InternVL2-8B\nCurrent date: 2024-08-09T10:47:10.457Z\n\nYou are a helpful assistant. You can help me by answering my questions. You can also ask me questions.<|im_end|>\n<|im_start|>user\n你好<|im_end|>\n<|im_start|>assistant\n', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=8116, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [1, 92543, 9081, 402, 5564, 1762, 334, 740, 5278, 14327, 13468, 277, 35758, 301, 1214, 1070, 30924, 314, 285, 294, 309, 364, 5564, 2554, 334, 262, 638, 1311, 285, 2418, 285, 2640, 291, 734, 334, 2713, 334, 734, 281, 21211, 349, 402, 2770, 657, 395, 11100, 17993, 281, 1592, 777, 1638, 884, 684, 35728, 983, 4917, 281, 1592, 777, 1225, 2705, 884, 4917, 281, 92542, 364, 92543, 1008, 364, 77230, 92542, 364, 92543, 525, 11353, 364], lora_request: None, prompt_adapter_request: None.
INFO:     172.29.192.1:54495 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 08-09 18:47:10 async_llm_engine.py:174] Added request chat-2ace427447e347df91be974ae56f34ce.
DEBUG 08-09 18:47:10 async_llm_engine.py:611] Waiting for new requests...
DEBUG 08-09 18:47:10 async_llm_engine.py:625] Got new requests!
INFO 08-09 18:47:11 metrics.py:406] Avg prompt throughput: 7.7 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
INFO 08-09 18:47:16 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%.
INFO 08-09 18:47:21 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 42.5 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%.
  INFO 08-09 18:47:26 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.8 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%.
 INFO 08-09 18:47:31 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 42.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%.
INFO 08-09 18:47:36 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 42.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%.
INFO 08-09 18:47:41 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.6%, CPU KV cache usage: 0.0%.
   INFO 08-09 18:47:46 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.6 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%.
     INFO 08-09 18:47:51 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.9%, CPU KV cache usage: 0.0%.
INFO 08-09 18:47:56 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%.
      INFO 08-09 18:48:01 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.1%, CPU KV cache usage: 0.0%.
INFO 08-09 18:48:06 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.2%, CPU KV cache usage: 0.0%.
      INFO 08-09 18:48:11 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.3%, CPU KV cache usage: 0.0%.
INFO 08-09 18:48:16 metrics.py:406] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.4%, CPU KV cache usage: 0.0%.    
问一个  你好   然后无限回答

**Comment by youkaichao** [comment]
@haoduoyu1203 how did you solve it finally?
