### ISSUE TITLE
Model(llama-2-13b-chat-hf) does not load with tensor_parallel_size=4

### ISSUE THREAD

**Issue by nootums** [vllm-project/vllm#735]
I'm using a g4dn.12xlarge instance which has 4x T4 GPUs.
vllm version 0.1.3

`from vllm import LLM, SamplingParams`
`v_llm = LLM(model=model_path, max_num_seqs=2048, tensor_parallel_size=4)`

It gets stuck on the 2nd line for 20+ minutes.
[Here's](https://p.ip.fi/w73y) the error log when I interrupt the execution.

It keeps waiting for the ray worker to return the objects, but seems like the worker isn't returning anything.

GPU utilisation also gets stuck when it loads 6911MB per GPU.
![image](https://github.com/vllm-project/vllm/assets/65669681/42083110-fa2f-4e64-9963-f8682710df39)

Any ideas as to why this is happening? Is it a version mismatch with ray?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
