### ISSUE TITLE
[Feature]: Why vllm cli not provide a config arg? 

### ISSUE THREAD

**Issue by dsp6414** [vllm-project/vllm#7350]
### 🚀 The feature, motivation and pitch

for examaple:
  vllm serve --config config.json

**Comment by DarkLight1337** [comment]
This is a great idea! Any help on this would be welcome!

**Comment by youkaichao** [comment]
it is possible to have a config format, json or yaml.

**Comment by ashwin-phadke** [comment]
I'll take this up.

**Comment by dsp6414** [comment]
已收到！
