### ISSUE TITLE
Create speculative decode dynamic parallel strategy

### ISSUE THREAD

**Issue by vladislavkruglikov** [vllm-project/vllm#7351]
## Motivation

Create new speculative decode dynamic parallel strategy for our team needs

## Features

Here we briefly describe features that we will implement in order to implement speculative decode dynamic parallel strategy. Each feature has high level description as a part of request for change with more description provided inside pull request for particular feature

#### Save speculative decoding states #7358
    
Allow users to optionally receive speculative decoding artifacts such as history of draft token indices for each step of speculative decode algorithm

#### Create draft from random tokens from promt #7359

Implement speculative proposers that enrich previous draft with tokens randomly sampled from current prompt

#### Allow model executor to return many next tokens #7361

Current implementation of model executor and model runner produce one last next token in decode stage. This feature would allow inner model runners to return next tokens for a range of tokens

#### Create parallel scorer #7362

Implement scorer that uses feature that allows to get next tokens in single forward request. Runs target model and returns scores for next tokens

#### Create speculative decode dynamic parallel strategy #7363

Combine all features such that users can use this speculative decode strategy

**Comment by jon-chuang** [comment]
Why are all of your PRs empty?
