### ISSUE TITLE
[Feature]: continuous batching for vllm.LLM

### ISSUE THREAD

**Issue by babu111** [vllm-project/vllm#7353]
### 🚀 The feature, motivation and pitch

Motivation: I'm using vllm.LLM to instantiate multiple vllm engines. During training, I want to make a large number of one-prompt requests to the vllm engines. From the output, it seems that vllm engines cannot use continuous batching, because it's processing one prompt at a time. vllm serve is able to use continuous batching, but does not support update of vllm model param during training.

Pitch: enable continuous batching for vllm.LLM engines, or allow online update of param for vllm's openai-compatible server.

**Comment by henry-y** [comment]
```
outputs = llm.generate(
        prompt_token_ids=input_tokenized_prompt, # input_tokenized_prompt is a list
        use_tqdm=True,
        sampling_params=sampling_params,
    )
```

I think u can pack the prompts in a list and it will use continous batching

**Comment by babu111** [comment]
> ```
> outputs = llm.generate(
>         prompt_token_ids=input_tokenized_prompt, # input_tokenized_prompt is a list
>         use_tqdm=True,
>         sampling_params=sampling_params,
>     )
> ```
> 
> I think u can pack the prompts in a list and it will use continous batching

Since I have up to 24 subprocesses, and each subprocess will make one-prompt requests frequently, this means I have to collect prompts to a certain number, say 24, before I send it to the engine. I think this is less efficient waiting for requests. I want to be able to send a one-prompt request on the fly to whichever engine that has extra room in its continuous batching.

**Comment by robertgshaw2-neuralmagic** [comment]
The `LLM` class is targeted for usage with synchronous mode, including offline batching. You can send a large batch to the `LLM` and it uses continuous batching internally

If you want to pass requests one at a time, I would suggest using the `AsyncLLMEngine` API directly. It is used internally by `vllm serve` but you can use it just as well in your `asyncio` code directly

The simple `entrypoints/api_server.py` has an example you could modify for your use case:
- https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py
