### ISSUE TITLE
gpu consumption

### ISSUE THREAD

**Issue by yunll** [vllm-project/vllm#736]
when i loaded a 7B model with 3090(24G), i found that gpu memory cost around 18G. I know the extra memory is used for KV cache, but i have 2 confusion.
1.  why 18G, as i know, it will cost 0.9 * 24G = 21.6G
2. in [https://github.com/vllm-project/vllm/discussions/241](241), we can limit the GPU memory usage by setting the parameter gpu_memory_utilization. but i set gpu_memory_utilization 0.7,  i get oom.  0.7 * 24G > 14G. if vllm must cost more memory? and shouldn't  pageattention reduce memory?

**Comment by LiVincent-Zhang** [comment]
I think the `gpu_memory_utilization` is used on the remaining memory after the model loaded.

**Comment by hmellor** [comment]
`gpu_memory_utilization` isn't the amount it will use, but the amount it's allowed to use.

If the size of the KV cache (determined by the max sequence length of your model) doesn't fill your GPU memory to 90%, it won't.
