### ISSUE TITLE
test qwen-7b-chat  model and  output  incorrect

### ISSUE THREAD

**Issue by dachengai** [vllm-project/vllm#737]
run script:    python3 vllm/examples/offline_inference.py    # changed model to qwen-7b-chat  (download from huggingface on 2023.8.10)

INFO 08-11 09:49:39 llm_engine.py:70] Initializing an LLM engine with config: model='model/', tokenizer='model/', tokenizer_mode=auto, trust_remote_code=True, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
WARNING 08-11 09:49:40 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.

Prompt: 'Hello, my name is', Generated text: ' [Your Name] and I am excited to join the [Company Name] team'
Prompt: 'The president of the United States is', Generated text: ' the head of state of the United States.<|im_end|>\n<|endoftext|>A polygon with $'
Prompt: 'The capital of France is', Generated text: ' Paris. It is located in the northern part of the country and is known for'
Prompt: '你好', Generated text: 'nge\n<|endoftext|>0.001*10^10=多少'

**Comment by tanguofu** [comment]
try to add stop_words_ids by ：https://modelscope.cn/models/qwen/Qwen-7B-Chat/file/view/master/generation_config.json 
```
  "stop_words_ids": [
        [151643]
    ],
```

**Comment by YLiberals** [comment]
> try to add stop_words_ids by ：https://modelscope.cn/models/qwen/Qwen-7B-Chat/file/view/master/generation_config.json
> 
> ```
>   "stop_words_ids": [
>         [151643]
>     ],
> ```

I add this code to my config, but I still face the same question.

**Comment by EricLingRui** [comment]
You need to convert the quert to chatml format to adapt to the chat model.
Use function like "make_context" : https://modelscope.cn/models/qwen/Qwen-7B-Chat/file/view/master/qwen_generation_utils.py
Also, you need to input vLLM engine "prompt_token_ids" instead of "prompts". Due to its anti injection strategy.

**Comment by YLiberals** [comment]
> You need to convert the query to chatml format to adapt to the chat model. Use function like "make_context" : https://modelscope.cn/models/qwen/Qwen-7B-Chat/file/view/master/qwen_generation_utils.py Also, you need to input vLLM engine "prompt_token_ids" instead of "prompts". Due to its anti injection strategy.

I did what you said and I'm still having this problem. I found that "make_context" has the same effect as "get_gen_prompt".

**Comment by tanguofu** [comment]
1. update the model to latest https://modelscope.cn/models/qwen/Qwen-7B-Chat
2. update the vllm to main
3. start vllm
```
python3 -m vllm.entrypoints.api_server --model ./Qwen-7B-Chat-modelcn  --trust-remote-code
```
4: test ：
```
(base) [root@VM-13-103-tencentos ~]# curl http://localhost:8000/generate -d '{
"prompt": "如何将大象装进冰箱",
"use_beam_search": true,
"n": 2, "stop": ["<|im_end|>"],
"temperature": 0, "max_tokens": 2048
}'
{"text":["如何将大象装进冰箱？\"","如何将大象装进冰箱？\n将大象装进冰箱需要三个步骤：首先打开冰箱门，然后将大象放进去，最后关上冰箱门。这是一个经典的谜语，旨在考验一个人的逻辑思维和解决问题的能力。虽然这是一个玩笑话，但这个谜语也可以用来教授一些基本的解决问题的技巧。首先，需要明确问题，了解需要完成的任务。其次，需要分析问题，找出解决问题的步骤。最后，需要执行步骤，将问题解决。通过这种方法，可以将大象装进冰箱，并在生活中解决许多其他问题。"]}
```

**Comment by Wyfnnnnb** [comment]
thanks，just add `stop=["<|im_end|>"]` in  `sampling_params = SamplingParams(...)` can fix,but when i use `outputs = self.model.generate(prompts, sampling_params)`,there are so many NULL like ['', '', '', '', '', '', '', '', '', '']

**Comment by whoyoung22** [comment]
just add param :"stop": ["<|endoftext|>","<|im_end|>","<|im_start|>"]

**Comment by endNone** [comment]
> 只需添加参数：“stop”： [“<|endoftext|>”，“<|im_end|>”，“<|im_start|>”]
Where to add
