### ISSUE TITLE
[Feature]: Support block manager v2 for chunked prefill

### ISSUE THREAD

**Issue by comaniac** [vllm-project/vllm#7371]
### 🚀 The feature, motivation and pitch

Chunked prefill currently doesn't work with block manager v2. Add `use_v2_block_manager=True` to https://github.com/vllm-project/vllm/blob/main/tests/basic_correctness/test_chunked_prefill.py#L48 to reproduce the error:

```
    def append_token_ids(self, block_index: int, token_ids: List[int]) -> None:
>       block = self._blocks[block_index]
E       IndexError: list index out of range
```

### Alternatives

Use block manager v1

### Additional context

cc @rkooo567 @cadedaniel

**Comment by cadedaniel** [comment]
We have a test for this: test_chunked_prefill_block_manager_v2. What workload caused the exception?

**Comment by comaniac** [comment]
Oh yeah interesting. Then why this unit test failed...I also got this error locally in my use case tho

**Comment by comaniac** [comment]
Oh I guess it's because the passing unit tests don't actually trigger prompt chunking (i.e., prompt length < chunk size).
