### ISSUE TITLE
使用 api_server.py运行QWen-7b 后，推理时错误

### ISSUE THREAD

**Issue by Marten2016** [vllm-project/vllm#739]
当发送http请求时，日志打印以下错误信息：
..........
“api_server”,line 56, in generate
.........
AttributeError: 'QWenTokenizer' object has no attribute 'byte_decoder'

**Comment by Marten2016** [comment]
https://huggingface.co/Qwen/Qwen-7B-Chat/discussions/2

**Comment by PanQiWei** [comment]
Qwen 模型用的是 tiktoken 不是 sentencepiece，可以看官方对于 tokenizer 使用的说明

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
