### ISSUE TITLE
[Bug]: Bug in quantization/awq /gemm_kernels.cu gemm_forward_4bit_cuda_m16nXk32 More result have been write

### ISSUE THREAD

**Issue by mengsoso** [vllm-project/vllm#7400]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

<img width="774" alt="截屏2024-08-11 下午10 05 10" src="https://github.com/user-attachments/assets/968487f3-a1e4-45ef-8fc4-d8f00a07c2bd">

When N=64, we don't have 4*8=32 c_warp result; In this case, we only have 2(N/32) * 8=16 c_warp results.

**Comment by youkaichao** [comment]
cc @mgoin

**Comment by mgoin** [comment]
It looks like this was introduced during the refactor here https://github.com/vllm-project/vllm/pull/2723

Essentially no changes to the kernel have been made since, only formatting or removing warnings. @mengsoso do you have a model/scenario where this bug occurs?

**Comment by mengsoso** [comment]
@mgoin thank you for response
When we evaluate the result only for the gemm_forward_4bit_cuda_m16nXk32 kernel, the result is wrong when N=64.
