### ISSUE TITLE
Feature request: Support for embedding models

### ISSUE THREAD

**Issue by mantrakp04** [vllm-project/vllm#742]
Support for embedding models such as instructor or sentence-transformers

**Comment by xusenlinzy** [comment]
You can refer to this: https://github.com/xusenlinzy/api-for-open-llm/blob/master/api/vllm_server.py#L525

**Comment by jianhuaz** [comment]
Supporting Embedding is a prerequisite for LLM to build a knowledge base. I think VLLM needs to be implemented as soon as possible. Otherwise, it will fall behind others in the new round of AI Agent technology.

**Comment by michaelfeil** [comment]
After buidling https://github.com/michaelfeil/infinity, I‘d be happy to support, if there is a better breakdown on what to work on.

**Comment by DavidPeleg6** [comment]
+1

**Comment by michaelfeil** [comment]
As the Roadmap is still missing Embedding models, I'd think it would be time to start supporting an initial backend with a stable (OpenAI-compatible API), similar to what e.g. Ollama did recently. I don't have the time to building everything from scratch and would prefer to a shallow integration of infinity, without any additional dependencies (other than torch that ships with vllm and python 3.9-3.12).

@WoosukKwon @Yard1 WDYT?

**Comment by DarkLight1337** [comment]
Closed as completed by #3737.

**Comment by yichuan520030910320** [comment]
Can we support model like facebook/contriever this one?

**Comment by DarkLight1337** [comment]
Just try it. If it's not supported, please open a new issue.
