### ISSUE TITLE
[New Model]: LLaVA-OneVision

### ISSUE THREAD

**Issue by EthanZoneCoding** [vllm-project/vllm#7420]
### The model to consider.

https://huggingface.co/lmms-lab/llava-onevision-qwen2-7b-ov

There are a bunch of others using the same architecture.

### The closest model vllm already supports.

qwen2. AFAIK the main difference is a vision encoder which I think is based on siglip (also supported)

### What's your difficulty of supporting the model you want?

Mixing qwen2 and siglip (maybe other changes)

**Comment by ywang96** [comment]
Once we merge the PR to support multi-image/video input, it should be pretty straightforward to add the support for this model in vLLM!

**Comment by rdzotz** [comment]
Given that the following is now available via the most recent transformers release and given that LlavaNextForConditionalGeneration is already available should this not be now straightforward ?
```
from transformers import AutoProcessor, LlavaOnevisionForConditionalGeneration
import torch
model = LlavaOnevisionForConditionalGeneration.from_pretrained(
     'llava-hf/llava-onevision-qwen2-7b-ov-hf', 
    torch_dtype=torch.float16,
    device_map='auto')
```

**Comment by DarkLight1337** [comment]
Video inputs are now supported in vLLM with the addition of #6571, so it should be possible to implement this model now.

**Comment by litianjian** [comment]
> Video inputs are now supported in vLLM with the addition of #6571, so it should be possible to implement this model now.
I have implemented llava-ov support.  After the benchmark evaluation done, I will make a PR for this.

**Comment by zihaolucky** [comment]
Any benchmark about this multimodel serving?

**Comment by DarkLight1337** [comment]
Our benchmark scripts support multimodal datasets. See https://github.com/vllm-project/vllm/pull/8495 for some examples.
