### ISSUE TITLE
Data-parallel inference 

### ISSUE THREAD

**Issue by aranku** [vllm-project/vllm#743]
Is there a supported way to do data-parallel inference with vLLM? I have N gpus and would like to parallelise a model on each gpu (not tensor parallel but data parallel). Right now I’m just wrapping LLM in a remote task (with resource=1 gpu) for offline processing of chunks of prompts (each gpu gets assigned total_prompts/N number of prompts to process).

**Comment by hmellor** [comment]
You can do this by running multiple vLLM servers and placing them behind a load balancer.
