### ISSUE TITLE
[Usage]: openai.APIStatusError: Error code: 405 - {'detail': 'Method Not Allowed'}

### ISSUE THREAD

**Issue by teknium1** [vllm-project/vllm#7463]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I run `vllm serve /mnt/datastore/shared/model-fp8 --max-model-len 16384 --tensor-parallel-size 8 --gpu-memory-utilization 0.95 --served-model-name model-v2-405b-e4`

But then I get `openai.APIStatusError: Error code: 405 - {'detail': 'Method Not Allowed'}`

I get this only with the chat.completions api from oai lib. Text completion api works fine..

**Comment by simon-mo** [comment]
One possibility is the chat template is not found and or failed to be found so the chat endpoint was disabled somehow. It should show up as a warning log message somewhere.

**Comment by teknium1** [comment]
It was cloudflare's fault

**Comment by pufanyi** [comment]
@teknium1 Hello! Sorry that since I have encountered the same question, could I ask how to solve it? Thank you so much!
