### ISSUE TITLE
[Feature]: Use .env file to deploy vllm

### ISSUE THREAD

**Issue by maxDavid40** [vllm-project/vllm#7465]
### 🚀 The feature, motivation and pitch

It would be helpful if vllm could use a .env file and respect this priority : 
default values  < .env file < env values < CLI

I can implement it if anyone is interested.

### Additional context

Related to [#7350](https://github.com/vllm-project/vllm/issues/7350)

**Comment by DarkLight1337** [comment]
There is no direct mapping between vLLM CLI args and vLLM environment variables. IMO it would be best to treat them separately.

**Comment by maxDavid40** [comment]
Ok, for vLLM CLI args I imagine this implementation :

args.py
```Python
def get_settings(parser: FlexibleArgumentParser) -> BaseSettings:
    default_args = parser.parse_args([])
    class ApplicationSettings(BaseSettings):
        url:str = default.args_url
        model_name: str = default_args.model_name
      
        model_config = SettingsConfigDict(env_file=".env", extra='ignore', protected_namespaces=('settings', ))

    application_settings = ApplicationSettings()
    return application_settings


def main():
    # Create parser
    parser = FlexibleArgumentParser(description="vLLM CLI")
    # Add argument to the parser
    parser.add_argument(
        "--url",
        type=str,
        default="http://localhost:8000/v1",
        help="url of the running OpenAI-Compatible RESTful API server")
    parser.add_argument(
        "--model-name",
        type=str,
        default=None,
        help=("The model name used in prompt completion, default to the first model in list models API call."))
    # Gets the default values of applications variables via pydantic
    settings = get_settings(parser)
    # Sets the default values of applications variables in the parser
    parser.set_defaults(**settings.model_dump())
```

.env
```shell
### Application settings ###
URL=http://0.0.0.0/8501/v1
MODEL_NAME='MY_MODEL'
``` 

It's an other way as a config.json or config.yaml and keep the priority (pydantic behavior) : 
CLI args > .env > defaut values

With the pydantic behavior, if you have already en environnement variable the priority is : 
CLI args > environnement variable > .env > defaut values

Example : 
With the url value :
.env : `URL='http://0.0.0.0/8501/v1'`
CLI: `--url 'http://0.0.0.0/5000/v2'`
environnement variable : `export URL='http://127.0.0.1/8501/v1'`

The value will be `http://0.0.0.0/5000/v2`

**Comment by DarkLight1337** [comment]
Due to the large number of options, using environment variables this way has a significant chance of colliding with existing environment variables outside of vLLM. I would recommend explicitly passing them as CLI args using a `config.json` file instead.
