### ISSUE TITLE
[Feature]: need to be able to load tiny models with vllm for testing - PagedAttention forces large models

### ISSUE THREAD

**Issue by stas00** [vllm-project/vllm#7490]
### 🚀 The feature, motivation and pitch

When one writes unit tests one can't use large models. It appears that vllm doesn't let one use tiny models because of PagedAttention. For 99% of testing use-cases PagedAttention makes no difference whatsoever as we want to test functionality and not speed.

Currently PagedAttention causes a problem requiring at least 64 len of each head requiring hidden_dim to be at least 256 which leads to a larger model which is slower to download and run CI against.

```
E           ValueError: Head size 8 is not supported by PagedAttention. Supported head sizes are: [64, 80, 96, 112, 120, 128, 192, 256].
```

### Alternatives

I don't see any way to disable PagedAttention and switch to normal attention which has no shape limitations.

Thank you!

**Comment by simon-mo** [comment]
vLLM and PagedAttention can work with small models such as https://huggingface.co/facebook/opt-125m, are you looking model sizes even smaller?

**Comment by stas00** [comment]
Thank you for replying, Simon

yes, for CI we use random models of tiny size - so they are a few MBs large.

But actually playing more with it I was able to make a 4x64=256 hidden dimension, for some reason I thought it wanted at least 64 heads as well - my mistake - this is good enough for our needs.

closing this
