### ISSUE TITLE
[Usage]: Is there an option to reduce GPU memory usage？

### ISSUE THREAD

**Issue by garyyang85** [vllm-project/vllm#7495]
### How would you like to use vllm

Using google/gemma-2-27b-it model start by vllm with GPU L40x2, but used about 45G per GPU by default. When input a long token, it will OOM. Is there a way to reduce GPU memory usage when start? Maybe can lose some performance?
cmd:
```
export VLLM_ATTENTION_BACKEND=FLASHINFER 
CUDA_VISIBLE_DEVICES=2,3 python3 -m vllm.entrypoints.openai.api_server --port=8081 --host=0.0.0.0 --model /mnt/vol-5ojabq86/models/gemma-2-27b-it --dtype bfloat16 --trust-remote-code  --tensor-parallel-size 2 --max-model-len 4096
```
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/c14205ad-c087-49dd-8b3a-1595f8694ced">

**Comment by DarkLight1337** [comment]
You can set `--gpu-memory-utilization` which dictates how much of the GPU memory to use (default is 0.9, or 90%)

**Comment by garyyang85** [comment]
@DarkLight1337  Thanks for the reply. I tried this option to set --gpu-memory-utilization=0.7, but another error occurs and need to increase this value. So seems the value need to be in a range. I need to find the balance.  :)   
From the error logs, seems "cache blocks" also use VRAM, is there any option related with this?  Thanks.
```
[rank0]: ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
```

**Comment by DarkLight1337** [comment]
I think this refers to the KV cache. You can check the CLI arguments and see how to adjust them.

**Comment by garyyang85** [comment]
@DarkLight1337  Thank you.
