### ISSUE TITLE
[Usage]: Can the embedding model be deployed using the openai interface?

### ISSUE THREAD

**Issue by LIUKAI0815** [vllm-project/vllm#7506]
### How would you like to use vllm

I want to run inference of a [bge-large-zh-v1.5]. I don't know how to integrate it with vllm.

**Comment by DarkLight1337** [comment]
If the model use an architecture that isn't in vLLM yet, then you have to implement the model first.

**Comment by DarkLight1337** [comment]
vLLM's OpenAI-compatible server does support embedding models (provided that the model is implemented in vLLM)

**Comment by DarkLight1337** [comment]
Closing as completed by #9056
