### ISSUE TITLE
LLama 2 70b 2 x H100s OOM Error

### ISSUE THREAD

**Issue by shahules786** [vllm-project/vllm#751]
I am trying to infer llama 2 70 based [model](https://huggingface.co/stabilityai/StableBeluga2) using 2*H100s. But still gets an OOM error.

## Code

```
MODEL = "stabilityai/StableBeluga2"
model = llm = LLM(model=MODEL,tensor_parallel_size=2)
```

## Error trace

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacty of 79.11 GiB of which 391.12 MiB is free. Process 247516 has 50.52 GiB memory in use. Process 477367 has 28.19 GiB memory in use. Of the allocated memory 27.48 GiB is allocated by PyTorch, and 1.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

## GPU
<img width="678" alt="Screenshot 2023-08-13 at 5 20 37 PM" src="https://github.com/vllm-project/vllm/assets/25312635/2723dc8d-237d-4941-a6fa-c56ddbab8794">

**Comment by Gregory-Ledray** [comment]
I see something like this too for a variety of models.

There are a lot of issues open and closed related to OOM - it would be nice if vllm did a better job of giving us feedback on the reason why OOM occurs.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
