### ISSUE TITLE
Pipeline parallelism support

### ISSUE THREAD

**Issue by sjchoi1** [vllm-project/vllm#752]
Dear vllm team, 

Congratulations on your acceptance to SOSP! 

I would like to contribute to the project and found the pipeline parallelism feature in the roadmap. 

I am curious whether pipeline parallelism is currently developing inside the team internally or is planned. 

If not, do you guys have any specific directions you planned initially?
(I found some comments by Zhuohan about creating new weights for pipeline parallelism)

**Comment by zbtrs** [comment]
hi,I'm interested in it,do you need help?
