### ISSUE TITLE
[Bug]: vllm serve downloads both consolidated.safetensors and shared safetensors, when it should only download one of them.

### ISSUE THREAD

**Issue by opernew** [vllm-project/vllm#7523]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

Some models like mistralai/Mistral-7B-Instruct-v0.3, provide both shared and consolidated safetensors. 

`vllm serve mistralai/Mistral-7B-Instruct-v0.3` downloads both, which is somewhat time-consuming.
This could lead to some testcases timing out, such as in #5649 

--------UPDATE---------
I raised this issue primarily for testing, and now there is a solution for testing: use the `--ignore-patterns` parameter to ignore unnecessary files in testcase.

**Comment by K-Mistele** [comment]
> you can use huggingface-cli to pre-download your model : https://huggingface.co/docs/huggingface_hub/en/guides/cli
> 
> and pass a local path to vLLM.

You definitely can, but if the default behavior is inefficient and unnecessary then it's probably still work fixing.

**Comment by opernew** [comment]
I have updated a solution, this issue can be postponed for repair if the solution worked well.
