### ISSUE TITLE
[Usage]: vllm流式输出会出现卡顿的现象，会卡6-9秒，是什么原因导致的，输入长度4万多字

### ISSUE THREAD

**Issue by ZZhangxian** [vllm-project/vllm#7537]
### Your current environment

 vllm流式输出会出现卡顿的现象，会卡6-9秒，是什么原因导致的，输入长度4万多字

### How would you like to use vllm

 vllm流式输出会出现卡顿的现象，会卡6-9秒，是什么原因导致的，输入长度4万多字

**Comment by KuntaiDu** [comment]
输入长度4万多字，对应的prefill估计就要花6-9秒了...

**Comment by ZZhangxian** [comment]
> 输入长度4万多字，对应的prefill估计就要花6-9秒了...
对的，是流式输出过程中会卡6-9秒，前面已经输出几个token了，然后突然卡了
