### ISSUE TITLE
ImportError: Ray is not installed. but verified it is installed!

### ISSUE THREAD

**Issue by okation** [vllm-project/vllm#754]
llm = LLM(model="meta-llama/Llama-2-70b-chat-hf", tensor_parallel_size=4)

I having the following error 
File ~/miniconda3/envs/vllm/lib/python3.8/site-packages/vllm/engine/ray_utils.py:64, in initialize_cluster(parallel_config, engine_use_ray, ray_address)
     62 if parallel_config.worker_use_ray or engine_use_ray:
     63     if ray is None:
---> 64         raise ImportError(
     65             "Ray is not installed. Please install Ray to use distributed "
     66             "serving.")
     67     # Connect to a ray cluster.
     68     ray.init(address=ray_address, ignore_reinit_error=True)
     
**ImportError: Ray is not installed. Please install Ray to use distributed serving.**

But verified it is installed with vllm with:
import ray
ray.init()

running version 2.6.2 , Also tried to uninstall and install older versions!

**Comment by reygu** [comment]
Add 
```python
    import traceback
    traceback.print_exc()
```
in ray_utils.py:28 to print the exception detail, maybe other package is not installed.

**Comment by E1zo** [comment]
same to me. I'm using this command to fix the problem.

```
pip install --upgrade ray
pip install --upgrade pyarrow
pip install pandas
```

**Comment by cauyxy** [comment]
the main reason is pandas.
when you import TorchDistributedWorker, it depends on pandas.
it raise ImportError seems ray not installed, but the root is pandas.

![image](https://github.com/vllm-project/vllm/assets/45619430/b6423a9d-a1ad-4592-8758-2c5e615bc321)
![image](https://github.com/vllm-project/vllm/assets/45619430/f3152d1f-1cbc-43f8-9d57-04efa260f091)

```python
try:
    import ray
    from ray.air.util.torch_dist import TorchDistributedWorker

    class RayWorker(TorchDistributedWorker):
        """Ray wrapper for vllm.worker.Worker, allowing Worker to be
        lazliy initialized after Ray sets CUDA_VISIBLE_DEVICES."""

        def __init__(self) -> None:
            self.worker = None

        def init_worker(self, worker_init_fn):
            self.worker = worker_init_fn()

        def __getattr__(self, name):
            return getattr(self.worker, name)

        def execute_method(self, method, *args, **kwargs):
            executor = getattr(self, method)
            return executor(*args, **kwargs)

except ImportError as e:
    ray = None
    TorchDistributedWorker = None
    RayWorker = None  # pylint: disable=invalid-name
```

**Comment by qyhdt** [comment]
Hit the same issue, after installing pandas, never shows up, but got another one：
![image](https://github.com/vllm-project/vllm/assets/7843730/d9b80cac-78e6-4896-8ca2-f9ee488e48a6)

**Comment by jojinshallar** [comment]
try to use the following command to install ray:
`pip install -U "ray[data,train,tune,serve]"`

That's the official recommended way.
