### ISSUE TITLE
[Usage]: Access weight of model with tp=2

### ISSUE THREAD

**Issue by floatingbigcat** [vllm-project/vllm#7543]
### Your current environment

vllm                              0.5.3.post1
vllm-flash-attn                   2.5.9.post1

### How would you like to use vllm

For model w/o distributed setting, we can directly access the model's weight in eager mode like this
```
model.llm_engine.model_executor.driver_worker.model_runner.model
```
However, when we're using the model w tp=2 (distributed setting), we can only access part of the weight via above code. 
I am wondering if there is a way that we can access the full weight.

**Comment by youkaichao** [comment]
when you use tp=2, part of the weights live in another process.

I don't think you can access variables in another process.
