### ISSUE TITLE
[Usage]: API KEY authentication

### ISSUE THREAD

**Issue by danielstankw** [vllm-project/vllm#7547]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

Hi everyone,
I am currently using vLLM for hosting a bunch of LLMs in Kubernetes. 
I am able to use the models via the endpoint. 

What is a recommended way to implement API KEYs for the models? I want to be able to generate key for users who wish to use the model and then be able to track their usage.

**Comment by DarkLight1337** [comment]
Imo this falls outside the scope of vLLM. I recommend adding another layer in between the user and vLLM that performs key authentication before dispatching the request to the vLLM endpoints.
