### ISSUE TITLE
[Bug]:  CTRL+C Not Killing Process with distributed_executor_backend=mp in VLLM v0.5.3.post1

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#7554]
### Your current environment

- `vllm==0.5.3.post1`
- `python=3.9`

### 🐛 Describe the bug

When using distributed_executor_backend=mp with VLLM version `vllm==0.5.3.post1,` the process does not respond to CTRL+C in the terminal to terminate the process. This issue did not occur with `vllm==0.5.0.post1.`

1. With tensor parallelism >1, the log shows that one process exits but another process on a different GPU continues to run. The terminal is unresponsive to CTRL+C signals in this case.
`(VllmWorkerProcess pid=9486) INFO 08-15 11:37:35 multiproc_worker_utils.py:237] Worker exiting`

2. With tensor parallelism ==1, the terminal does not respond to the CTRL+C signal at all.

**Comment by youkaichao** [comment]
cc @njhill

**Comment by KuntaiDu** [comment]
Temporary fix: try kill vllm by these lines of command:
```
ps aux | grep python | grep openai | awk '{print $2}' | xargs -r kill -9
ps -e | grep pt_main_thread | awk '{print $1}' | xargs kill -9
```

**Comment by RiverGao** [comment]
> Temporary fix: try kill vllm by these lines of command:
> 
> ```
> ps aux | grep python | grep openai | awk '{print $2}' | xargs -r kill -9
> ps -e | grep pt_main_thread | awk '{print $1}' | xargs kill -9
> ```

Worked for me

**Comment by njhill** [comment]
This should be resolved in newer versions of vLLM, please try with the latest 0.6.3.

**Comment by njhill** [comment]
I am going to close this issue but please feel free to re-open if it's still a problem with the latest version.

**Comment by us58** [comment]
I am on version 0.6.3.post1 and this just happened to me. The temporary fix from above also fixed it for me.

**Comment by njhill** [comment]
@us58 could you share exactly how you're running it and the terminal output when you ctrl-C?
