### ISSUE TITLE
[RFC]: Support for video input 

### ISSUE THREAD

**Issue by TKONIY** [vllm-project/vllm#7558]
### Motivation.

Currently models like `llava-hf/llava-next-video*` recognize image and video inputs with different tokens, and do different computations. Therefore vLLM should provide new APIs and inference support for video input.

#### API
* `LLM.generate()` API for video

    ```python
    LLM.generate({
        "prompt": "<video> please summarize this video",
        "multi_modal_data": {
            "video": video
        }
    })
    ```
* [OpenAI compatible chat completion APIs](https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding) 

#### Roadmap
* Add `VideoPlugin` for `MultiModalPlugin`
* #7559 
   * Add initial support for replacing a \<video\> token with a single video.
   * Add support for replacing all \<video\> and \<image\> tokens with multiple multi-modal inputs.
* Support prefix caching for the same videos.
* Support openai chat completion APIs.

### Feedback Period.

A week

### CC List.

@DarkLight1337 
@zifeitong 
@ywang

**Comment by PancakeAwesome** [comment]
Is there a roadmap for 'openai vllm server supports video interface' feature? Thank you

**Comment by TKONIY** [comment]
> Is there a roadmap for 'openai vllm server supports video interface' feature? Thank you

Thank you. It is a very critical feature, but it needs a careful discussion for the APIs. I recently do not have a plan to work on that. 

@DarkLight1337 
@ywang96

**Comment by ywang96** [comment]
> > Is there a roadmap for 'openai vllm server supports video interface' feature? Thank you
> 
> Thank you. It is a very critical feature, but it needs a careful discussion for the APIs. I recently do not have a plan to work on that.
> 
> CC @DarkLight1337 @ywang96

Sounds good - we will take it over from here. Thank you for the contribution for the model!

**Comment by PancakeAwesome** [comment]
https://github.com/sponsors/vllm-project?sp=PancakeAwesome

**Comment by sayakpaul** [comment]
@ywang96 I am quite interested in using `vllm` for high-performance video captioning. This will be tremendously helpful for furthering research on video generation from language.

I was able to use Qwen for this: https://github.com/vllm-project/vllm/issues/9128#issuecomment-2399642038. 

I want to how to extend this to multi-video captioning. If you have some pointers for me, that would be helpful!

**Comment by sayakpaul** [comment]
Cc @TKONIY if https://github.com/vllm-project/vllm/issues/7558#issuecomment-2399698986 sounds interesting.

**Comment by TKONIY** [comment]
Sorry that I did not quite follow up with the vLLM development recently. If you need to implement the online serving support for video/ multi video, I think you can start from an RFC to define the http API (which has not been supported by official openai api). Then modify some frontend code in `entrypoint/` to connect it with the llm engine.

**Comment by sayakpaul** [comment]
Currently, I am doing this:
https://github.com/vllm-project/vllm/issues/9128#issuecomment-2399642038

**Comment by ywang96** [comment]
> @ywang96 I am quite interested in using `vllm` for high-performance video captioning. This will be tremendously helpful for furthering research on video generation from language.
> 
> I was able to use Qwen for this: [#9128 (comment)](https://github.com/vllm-project/vllm/issues/9128#issuecomment-2399642038).
> 
> I want to how to extend this to multi-video captioning. If you have some pointers for me, that would be helpful!

Hey @sayakpaul! Sorry for the late reply and this is definitely interesting.

AFAIK, only Llava-OneVision supports multi-video captioning once https://github.com/vllm-project/vllm/pull/8905 is merged, and this is more of a model capability than of the inference infrastructure capability (AFAIK, video language inference is more or less the same as multi-image inference, so it's a matter of whether the model itself was trained to do this task)

**Comment by sayakpaul** [comment]
> AFAIK, only Llava-OneVision supports multi-video captioning once https://github.com/vllm-project/vllm/pull/8905 is merged, and this is more of a model capability than of the inference infrastructure capability

Agree. Thanks for your inputs. 

Would it be possible to update this thread with an example on doing multi-video captioning?

**Comment by ywang96** [comment]
> > AFAIK, only Llava-OneVision supports multi-video captioning once #8905 is merged, and this is more of a model capability than of the inference infrastructure capability
> 
> Agree. Thanks for your inputs.
> 
> Would it be possible to update this thread with an example on doing multi-video captioning?

Yea - I'll keep that in mind and update this issue once we have some bandwidth to get #8905 merged. Will probably update our example scripts too!

**Comment by DarkLight1337** [comment]
Closing as completed since #8905 and #9842 have both been resolved.

**Comment by sayakpaul** [comment]
@DarkLight1337 which doc part we should refer to for this?

**Comment by DarkLight1337** [comment]
Please see #9842 on how to use it.

**Comment by sayakpaul** [comment]
@DarkLight1337 thanks!

Is https://github.com/vllm-project/vllm/pull/10020#issue-2634358870 a sufficiently good example for me as a reference?

**Comment by DarkLight1337** [comment]
> @DarkLight1337 thanks!
> 
> Is [#10020 (comment)](https://github.com/vllm-project/vllm/pull/10020#issue-2634358870) a sufficiently good example for me as a reference?

Yes, that should be clear enough.

**Comment by litianjian** [comment]
> @litianjian can you add some docs/examples for this?
Sure
