### ISSUE TITLE
[Feature]: Automatic Prefix Caching and Truncating. Possibilty for Context Shifting.

### ISSUE THREAD

**Issue by derpyhue** [vllm-project/vllm#7560]
### 🚀 The feature, motivation and pitch

Currently when using the Automatic Prefix Caching when you truncate the input (for chat related generation) because of the context limit. The Automatic Prefix Caching will invalidate the cache because the first block will not correlate to the first block of the truncated input. If it would be possible to Context Shift like [llama.cpp](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/server.cpp#L1949) It would eliminate long TTFT times in my case using 24k context length.

Would this be possible to implement?
Thank you for your time!

### Additional context

The hash is calculated based on the token IDs in the block and the hash of the previous block. When the input gets truncated due to the context length, the token IDs in the block change, which in turn changes the content hash. This causes the cache to be invalidated.

**Comment by derpyhue** [comment]
```
                    Block 1                  Block 2                  Block 3
         [A gentle breeze stirred] [the leaves as children] [laughed in the distance]
Block 1: |<--- block tokens ---->|
Block 2: |<------- prefix ------>| |<--- block tokens --->|
Block 3: |<------------------ prefix -------------------->| |<--- block tokens ---->|
```
https://docs.vllm.ai/en/latest/automatic_prefix_caching/details.html

The current system is very handy, but i don't see a way to make it work with truncating tokens.
Unless the prefix are kept in chunks then i could truncate on block basis.
But that would create other problems and kinda defeat the point of the cache as it has to load them all separate.

Will keep it open if someone has a idea. I will try to experiment but i'm afraid currently it would not be a option.

**Comment by pkuwangh** [comment]
@derpyhue have you found any new information/update on this?

Also in addition to the context shifting, my understanding is that (1) the truncation need to happen at the granularity of a whole kvcache block of tokens and (2) the position IDs need to be absolute values including the truncated tokens. Am I missing anything?
