### ISSUE TITLE
[Bug]: vllm运行卡住

### ISSUE THREAD

**Issue by backtime1** [vllm-project/vllm#7576]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

(base) bob@test-ESC8000A-E11:~$ python -m vllm.entrypoints.openai.api_server \
    --model /home/bob/LLaMA3-8B-Chinese-Chat-medical \
    --served-model-name llama3:8b-instruct-fp16 \
    --trust-remote-code \
    --max-model-len 4096 \
    --tensor-parallel-size 4 \
    --gpu-memory-utilization 0.7 \
    --port 8000 
INFO 08-16 10:11:07 api_server.py:212] vLLM API server version 0.5.2
INFO 08-16 10:11:07 api_server.py:213] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/home/bob/LLaMA3-8B-Chinese-Chat-medical', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=4096, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.7, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=['llama3:8b-instruct-fp16'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 08-16 10:11:07 config.py:695] Defaulting to use mp for distributed inference
INFO 08-16 10:11:07 llm_engine.py:174] Initializing an LLM engine (v0.5.2) with config: model='/home/bob/LLaMA3-8B-Chinese-Chat-medical', speculative_config=None, tokenizer='/home/bob/LLaMA3-8B-Chinese-Chat-medical', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=llama3:8b-instruct-fp16, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 08-16 10:11:08 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=14165) INFO 08-16 10:11:09 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=14163) INFO 08-16 10:11:09 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=14164) INFO 08-16 10:11:09 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=14163) INFO 08-16 10:11:09 utils.py:737] Found nccl from library libnccl.so.2
INFO 08-16 10:11:09 utils.py:737] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=14164) INFO 08-16 10:11:09 utils.py:737] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=14163) INFO 08-16 10:11:09 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 08-16 10:11:09 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=14164) INFO 08-16 10:11:09 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=14165) INFO 08-16 10:11:09 utils.py:737] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=14165) INFO 08-16 10:11:09 pynccl.py:63] vLLM is using nccl==2.20.5
一直卡在这个地方，只有关机重启才能重新运行

**Comment by backtime1** [comment]
![1723775032666](https://github.com/user-attachments/assets/f2e48bda-0d05-49f4-9d9b-90c6fe7576f2)
且GPU利用率拉满

**Comment by youkaichao** [comment]
did you try the latest version and follow https://docs.vllm.ai/en/latest/getting_started/debugging.html ?

**Comment by KuntaiDu** [comment]
Try run `export VLLM_HOST_IP=$(hostname -I | awk '{print $1}')` first and then run vllm.

**Comment by backtime1** [comment]
NCCL_P2P_DISABLE=1 NCCL_SOCKET_IFNAME=ens1f1 
通过禁用P2P网络解决

**Comment by penchy-zju** [comment]
> NCCL_P2P_DISABLE=1 NCCL_SOCKET_IFNAME=ens1f1 通过禁用P2P网络解决

可以解释一下为什么这么设置吗？
我只设置了NCCL_P2P_DISABLE=1就可以了，再多设置NCCL_SOCKET_IFNAME=ens1f1反而不行了

**Comment by youkaichao** [comment]
`export NCCL_P2P_DISABLE=1` is the key, `export NCCL_SOCKET_IFNAME=ens1f1` is another orthogonal factor, and it depends on your network netting whether you need to adjust it.
