### ISSUE TITLE
load model in batches

### ISSUE THREAD

**Issue by lynnleelhl** [vllm-project/vllm#759]
when test vllm with large model, I notice that vllm will first load the whole model into cpu memory and then move it to gpu memory, this makes the cpu memory at least be the size of the model large, if the model is 70b that could be a lot of memory required. 

I wonder if there's any way to load model in batches to reduce the memory usage, since cpu memory seems to be only used during initialization.

**Comment by hsm1997** [comment]
maybe you can setup virtual memory with swap file to get around this issue,
(btw I think this is something beyond vLLM scope)

**Comment by lynnleelhl** [comment]
close as I found it's not a problem in newest code

**Comment by cduk** [comment]
@lynnleelhl: it seems still an issue:

```
ERROR 06-02 09:39:03 [core.py:396]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/weight_utils.py", line 441, in safetensors_weights_iterator
ERROR 06-02 09:39:03 [core.py:396]     with safe_open(st_file, framework="pt") as f:
ERROR 06-02 09:39:03 [core.py:396]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-02 09:39:03 [core.py:396] RuntimeError: unable to mmap 16933256392 bytes from file </root/.cache/huggingface/hub/models--Qwen--Qwen3-30B-A3B-GPTQ-Int4/snapshots/9b534e4318b7ebc3c961a839f13eb18b1833f441/model.safetensors>: Cannot allocate memory (12)
```
