### ISSUE TITLE
[Usage]: Seeing perf regression using chunked_prefill on VLLM 0.5.4

### ISSUE THREAD

**Issue by jiahanc** [vllm-project/vllm#7604]
### Your current environment

```text
Docker container following build_from _source instruction
```

### How would you like to use vllm

I want to experiment how chunked_prefill can increase throughput but see perf regression when enabling chunked_prefill. I am testing on [Llama-3-70B-Instruct-Gradient-1048k ](https://huggingface.co/gradientai/Llama-3-70B-Instruct-Gradient-1048k) on 8 H100 SXM GPUs.  I am benchmarking using `/benchmark/benchmark_throughput.py` and Tensor Parallel size 8
Is there any guidance how to choose `max_batched_tokens` properly?
My command is :
``` Python 
python3 ./benchmarks/benchmark_throughput.py \
    --model hf_model_path \
    --tokenizer hf_model_path \
    --tensor-parallel-size 8 \
    --num-prompts 50 \
    --input-len 40000 \
    --output-len 256 \
    --enable-chunked-prefill \
    --max_batched_tokens 4096
    --trust-remote-code 
```
My benchmark result is:
![image](https://github.com/user-attachments/assets/9a15b0e2-a0d9-4243-9f2e-40c64f9c19c1)

**Comment by KuntaiDu** [comment]
The rationale of picking max_batched_tokens: make it as large as possible, as long as your inter-token latency permits.

**Comment by KuntaiDu** [comment]
Also, chunked prefill does not improve offline throughput. The main goal of chunked prefill is:
1. improve throughput w.r.t. a latency target
2. reduce peak memory usage when handling large context

**Comment by jiahanc** [comment]
Thank you @KuntaiDu , will experiment with larger max_batched_tokens length
