### ISSUE TITLE
[Installation]: container images - too big and need to publish also cpu versions

### ISSUE THREAD

**Issue by yairyairyair** [vllm-project/vllm#7609]
### Your current environment

not a problem in my own env

### How you are installing vllm

```sh
docker pull vllm/vllm-openai:latest
```
notice that what i want is to have cpu version as well

```sh
docker pull vllm/vllm-openai:latest-cpu
```

also the regular (GPU) image is too big, it is 5GB, can we do something about it and make it smaller than < 1GB

If this project needs help with this specific issue i can help, i want these container optimizations

**Comment by simon-mo** [comment]
Optimization welcomed!

**Comment by antoniomdk** [comment]
Just installing torch and ray in an empty environment generates a docker image of ~2GiB. I think it's unrealistic to try to cut it down to < 1GiB. The CUDA libraries and other pre-compiled wheels probably make >50% of the total image size.

**Comment by yairyairyair** [comment]
If its 2GB its better than the 9GB which is published in the dockerhub, can we see why its 9gb and not 2? Maybe the github actions or something
