### ISSUE TITLE
How to set cache dir?

### ISSUE THREAD

**Issue by zhuxiaosheng** [vllm-project/vllm#764]
How to set cache_dir for the model like huggingface AutoModel...

**Comment by Forbu** [comment]
@zhuxiaosheng A quick look into the code give the answer :
https://github.com/vllm-project/vllm/blob/acbed3ef40f015fcf64460e629813922fab90380/vllm/engine/arg_utils.py#L17C5-L17C17

Basicly you need to add the download_dir argument in the LLM(download_dir = ...) init.

**Comment by yuchenlin** [comment]
@Forbu  thanks a lot! btw, is there any documentation webpages that we can easily find such args?

**Comment by Forbu** [comment]
@yuchenlin "the code is the documentation" :)

**Comment by keyboardAnt** [comment]
Is it possible to change the default cache dir of [`vllm.entrypoints.llm.LLM`](https://github.com/vllm-project/vllm/blob/1f24755bf802a2061bd46f3dd1191b7898f13f45/vllm/entrypoints/llm.py#L13)?

**Comment by tilmanbeck** [comment]
What is the rationale at vLLM for not respecting HF's own environment variable for the cache dir (i.e., `HF_HOME`) ?

**Comment by AmoghM** [comment]
@tilmanbeck Exactly my question too!

**Comment by youkaichao** [comment]
I don't get it. I can change the cache directory by setting `HF_HOME` .
