### ISSUE TITLE
[Usage]: The results of the model depend on the number of GPUs.

### ISSUE THREAD

**Issue by wonbeeny** [vllm-project/vllm#7645]
### Your current environment

**package version**
- vllm: 0.2.6
- python: 3.9

**Phenomenon**
- The output of the same model is different when using only one gpu and two.
- the same environment
- the same arguments

### How would you like to use vllm

I would like to get the same result even if the number of gpu is used differently when referring using vLLM.
The code I used is as follows.

```python
payload = json.dumps({
  "model_name": model_name,
  "prompt": output_ex['model_input'],
  "max_tokens": 1024,
  "stream": False,
  "top_p": 0.9,
  "temperature": 0.01,
  "presence_penalty": 1.0,
  "stop_token_ids": [2],
  "best_of": 1
})

headers = {
'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)
```
<br><br>

- when using only one gpu
  - output: "" (=empty)
- when using twon gpu
  - output: "No answer found."

<br><br>

Has anyone experienced a phenomenon like me where the output comes out differently depending on the number of gpu loading the model?

**Comment by youkaichao** [comment]
> vllm: 0.2.6

please try a new version of vllm. this version is tooo old.

**Comment by simon-mo** [comment]
Additionally, the following parameters does not guarantee determinism across requests
```
  "top_p": 0.9,
  "temperature": 0.01,
```
