### ISSUE TITLE
Server hanging after prompt exceeds limit with LLaMA 2 models

### ISSUE THREAD

**Issue by dexterju27** [vllm-project/vllm#765]
Hello,

I have been trying vllm 0.1.3 with LLaMA 2 model,
```
python  -m vllm.entrypoints.openai.api_server  --model meta-llama/Llama-2-70b-chat-hf --port 6011 --tensor-parallel-size 8 --tokenizer hf-internal-testing/llama-tokenizer
```
I noticed the server will hang and stop processing further requests after a prompt being too long. The last output is:
```
WARNING 08-15 11:44:47 scheduler.py:130] Input prompt (2715 tokens) is too long and exceeds limit of 2560
```

I see there is a related fix: #273  but not sure why this still happens.

Is there a way to change this behavior and just discard this request instead? 

Thanks!

**Comment by amoghmishra-sl** [comment]
Facing the exact same thing @dexterju27!

Running into the same problem while running llama-2.

For input prompt token length of 3503 and setting max_tokens to 2000, I got the warning:
`“Input prompt (3503 tokens) is too long and exceeds limit of 2560”.`

We would get that message when `num_prompt_token > prompt_limit` where prompt_limit is `min (max_model_len and max_num_batched_tokens)`. By default, the `max_num_batched_tokens` is set to 2560.

So I increased the max_num_batched_tokens to 5000 to see what happens next. This time I get `Token indices sequence length is longer than the specified maximum sequence length for this model (3503 > 2048). Running this sequence through the model will result in indexing errors`

My questions are:

Why did it pick up 2048 and not 4096 for llama-2 as that is its max context window?
Why we don't send a 500 error code but 200? The server replies back the same input prompt/context as output with a 200 OK status.

**Comment by dalong2hongmei** [comment]
like this issue. i ran baichuan13b using vllm.entrypoints.api_server, it hang and all gpus utilization became zero.

**Comment by amoghmishra-sl** [comment]
@dalong2hongmei can you share your logs? I have seen mine used to get stuck after it went beyond 94% of cache utilization.

**Comment by horiacristescu** [comment]
Got the same error "exceeds limit of 2560"

**Comment by GasolSun36** [comment]
anyone has solutions？I get the same error.

**Comment by esmeetu** [comment]
set args --max-num-batched-tokens larger when run server, like 8192.

**Comment by xingyaoww** [comment]
I was having this issue with `vllm==0.1.3`, upgrading to `vllm==0.1.4` fixes this issue for me.

**Comment by hmellor** [comment]
Closing as this appears to be resolved.
