### ISSUE TITLE
[Bug]: Error happened with Large scale requests based on 0.5.4 vllm

### ISSUE THREAD

**Issue by TangJiakai** [vllm-project/vllm#7653]
### Your current environment

When I use `python -m vllm.entrypoints.openai.api_server` as the API request method and make a large number of requests (at least in the thousands), an error occurs.

### 🐛 Describe the bug

Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 260, in authentication
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/data/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 189, in create_chat_completion
    generator = await openai_serving_chat.create_chat_completion(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 185, in create_chat_completion
    return await self.chat_completion_full_generator(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/serving_chat.py", line 436, in chat_completion_full_generator
    async for res in result_generator:
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/rpc/client.py", line 196, in generate
    with self.socket() as socket:
  File "/data/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/vllm/entrypoints/openai/rpc/client.py", line 59, in socket
    socket = self.context.socket(zmq.constants.DEALER)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/zmq/sugar/context.py", line 259, in socket
    s: ST = self._socket_class(  # set PYTHONTRACEMALLOC=2 to get the calling frame
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/zmq/_future.py", line 221, in __init__
    super().__init__(context, socket_type, **kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/zmq/sugar/socket.py", line 93, in __init__
    super().__init__(*a, **kw)
  File "zmq/backend/cython/socket.pyx", line 330, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 81, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

**Comment by cjackal** [comment]
There's an working PR to fix your issue, #7394.

**Comment by TangJiakai** [comment]
Thank you! I will try it, and if it works well, I will close this issue.

**Comment by robertgshaw2-neuralmagic** [comment]
Running with `--disable-frontend-multiprocessing` will avoid this issue on v0.5.4

**Comment by TangJiakai** [comment]
> Running with `--disable-frontend-multiprocessing` will avoid this issue on v0.5.4

sorry, I donot find this parameter in https://docs.vllm.ai/en/v0.4.0.post1/serving/openai_compatible_server.html

**Comment by robertgshaw2-neuralmagic** [comment]
> > Running with `--disable-frontend-multiprocessing` will avoid this issue on v0.5.4
> 
> sorry, I donot find this parameter in https://docs.vllm.ai/en/v0.4.0.post1/serving/openai_compatible_server.html

I will look into the docs, sorry about this.

We introduced `multiprocessing` into the frontend in v0.5.4, which caused the bug above. So the argument here is a workaround for now until we resolve the issues.

**Comment by TangJiakai** [comment]
@robertgshaw2-neuralmagic  Thank you!

**Comment by TangJiakai** [comment]
> > > Running with `--disable-frontend-multiprocessing` will avoid this issue on v0.5.4
> > 
> > 
> > sorry, I donot find this parameter in https://docs.vllm.ai/en/v0.4.0.post1/serving/openai_compatible_server.html
> 
> I will look into the docs, sorry about this.
> 
> We introduced `multiprocessing` into the frontend in v0.5.4, which caused the bug above. So the argument here is a workaround for now until we resolve the issues.

Sorry, I have tried to add `--disable-frontend-multiprocessing`, but there is still the same error!

**Comment by TangJiakai** [comment]
> There's an working PR to fix your issue, #7394.

No, it also cannot work well, I get the same error!

**Comment by robertgshaw2-neuralmagic** [comment]
> > > > Running with `--disable-frontend-multiprocessing` will avoid this issue on v0.5.4
> > > 
> > > 
> > > sorry, I donot find this parameter in https://docs.vllm.ai/en/v0.4.0.post1/serving/openai_compatible_server.html
> > 
> > 
> > I will look into the docs, sorry about this.
> > We introduced `multiprocessing` into the frontend in v0.5.4, which caused the bug above. So the argument here is a workaround for now until we resolve the issues.
> 
> @robertgshaw2-neuralmagic Sorry, I have tried to add `--disable-frontend-multiprocessing`, but there is still the same error!

Are you sure? `--disable-frontend-multiprocessing` means we will not use `zeromq` at all

**Comment by TangJiakai** [comment]
@robertgshaw2-neuralmagic I run the program based on https://github.com/neuralmagic/vllm/tree/fix-zmq-max-sockets (I install vllm from source code). For further figure out this problem, I will use the pip to install vllm and use the following cmd to try again.
```
python -m vllm.entrypoints.openai.api_server \
        --model /data/pretrain_dir/Meta-Llama-3-8B-Instruct \
        --trust-remote-code \
        --port 8083 \
        --api-key xxxxxxx \
        --dtype auto \
        --pipeline-parallel-size 1 \
        --enforce-eager \
        --enable-prefix-caching \
        --disable-frontend-multiprocessing \
        --enable-lora
```

**Comment by robertgshaw2-neuralmagic** [comment]
> @robertgshaw2-neuralmagic I run the program based on https://github.com/neuralmagic/vllm/tree/fix-zmq-max-sockets (I install vllm from source code). For further figure out this problem, I'm going to use the pip to install vllm and use the following cmd to try it again, then I will give the experimental results soon.
> 
> ```
> python -m vllm.entrypoints.openai.api_server \
>         --model /data/pretrain_dir/Meta-Llama-3-8B-Instruct \
>         --trust-remote-code \
>         --port 8083 \
>         --api-key xxxxxxx \
>         --dtype auto \
>         --pipeline-parallel-size 1 \
>         --enforce-eager \
>         --enable-prefix-caching \
>         --disable-frontend-multiprocessing \
>         --enable-lora
> ```

Sure, but the stack trace on error must be different...

**Comment by TangJiakai** [comment]
@robertgshaw2-neuralmagic Thank you very much for your help, there are no errors now!!!

**Comment by robertgshaw2-neuralmagic** [comment]
> @robertgshaw2-neuralmagic Thank you very much for your help, there are no errors now!!!

Are you running on current main?

**Comment by TangJiakai** [comment]
1. no, I'm not using the latest main version; I'm using the released vllm 0.5.4.
2. Do you mean that if we use the latest main version of vllm, there's no need to add the --disable-frontend-multiprocessing parameter? And will there be a greater performance improvement as well?

**Comment by robertgshaw2-neuralmagic** [comment]
https://github.com/vllm-project/vllm/pull/7394 just landed and is intended to fix the issue you reported under heavy load: 

```bash
zmq.error.ZMQError: Too many open files
```

So, you should be able to run your workload without `--disable-frontend-multiprocessing` and avoid seeing the `Too many open files` issue.

If you could try it out and let me know your experience I would greatly appreciate it.

**Comment by TangJiakai** [comment]
Actually, I previously used your personal vllm repository, as mentioned in the comment here: https://github.com/vllm-project/vllm/issues/7653#issuecomment-2296882472. However, after using it, I still encountered errors. Of course, it's possible that you have since made additional changes to resolve these issues. I will try the latest main version in my spare time because improving performance is very important for my project.

**Comment by robertgshaw2-neuralmagic** [comment]
> Actually, I previously used your personal vllm repository, as mentioned in the comment here: [#7653 (comment)](https://github.com/vllm-project/vllm/issues/7653#issuecomment-2296882472). However, after using it, I still encountered errors. Of course, it's possible that you have since made additional changes to resolve these issues. I will try the latest main version in my spare time because improving performance is very important for my project.

Can you please share more about the issues that arose running with that PR? The stack trace you listed in the original comment is not possible in #7653. So if you have an issue with that branch I would love some help reproducing so I can fix it for you!

**Comment by TangJiakai** [comment]
Is that so? Maybe I made a mistake. Anyway, I will proceed to use the latest main branch from the official vllm repository and install it from the source code to give it another try.
Thanks for your patient guidance!!!!😝😝😝

**Comment by robertgshaw2-neuralmagic** [comment]
Thank you for reporting these issues + for helping me get them resolved.

**Comment by Bihan** [comment]
I am running inference benchmark tests using[ benchmark_serving.py](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py) and without `--disable-frontend-multiprocessing`, vllm server does not handle large requests. 

You can see the outputs with and without `--disable-frontend-multiprocessing` here.

### Without 
```
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m vllm.entrypoints.openai.api_server   --model=meta-llama/Llama-3.1-405B-Instruct   --tensor-parallel-size=8   --dtype=float16 --disable-log-requests

root@ENC1-CLS01-SVR13:/workflow/vllm/benchmarks# python benchmark_serving.py --backend vllm --model meta-llama/Llama-3.1-405B-Instruct  --dataset-name sonnet  --num-prompt=2048 --dataset-path="sonnet.txt" --sonnet-input-len 500
WARNING 10-09 06:35:24 rocm.py:13] `fork` method is not supported by ROCm. VLLM_WORKER_MULTIPROC_METHOD is overridden to `spawn` instead.
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision-0.16.1+fdea156-py3.10-linux-x86_64.egg/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision-0.16.1+fdea156-py3.10-linux-x86_64.egg/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Namespace(backend='vllm', base_url=None, host='localhost', port=8000, endpoint='/v1/completions', dataset=None, dataset_name='sonnet', dataset_path='sonnet.txt', model='meta-llama/Llama-3.1-405B-Instruct', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=2048, logprobs=None, request_rate=inf, seed=0, trust_remote_code=False, disable_tqdm=False, profile=False, save_result=False, metadata=None, result_dir=None, result_filename=None, ignore_eos=False, percentile_metrics='ttft,tpot,itl', metric_percentiles='99', sonnet_input_len=500, sonnet_output_len=150, sonnet_prefix_len=200, sharegpt_output_len=None, random_input_len=1024, random_output_len=128, random_range_ratio=1.0, random_prefix_len=0, hf_subset=None, hf_split=None, hf_output_len=None)
Starting initial single prompt test run...
Initial test run completed. Starting main benchmark run...
Traffic request rate: inf
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [08:37<00:00,  3.96it/s]
============ Serving Benchmark Result ============
Successful requests:                     950       
Benchmark duration (s):                  517.23    
Total input tokens:                      432754    
Total generated tokens:                  142500    
Request throughput (req/s):              1.84      
Output token throughput (tok/s):         275.51    
Total Token throughput (tok/s):          1112.18   
---------------Time to First Token----------------
Mean TTFT (ms):                          243846.36 
Median TTFT (ms):                        243373.14 
P99 TTFT (ms):                           483559.54 
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          424.22    
Median TPOT (ms):                        435.40    
P99 TPOT (ms):                           463.83    
---------------Inter-token Latency----------------
Mean ITL (ms):                           424.20    
Median ITL (ms):                         433.40    
P99 ITL (ms):                            594.05    
==================================================

```


### With
```
ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m vllm.entrypoints.openai.api_server   --model=meta-llama/Llama-3.1-405B-Instruct   --tensor-parallel-size=8   --dtype=float16 --disable-log-requests --disable-frontend-multiprocessing

root@ENC1-CLS01-SVR13:/workflow/vllm/benchmarks# python benchmark_serving.py --backend vllm --model meta-llama/Llama-3.1-405B-Instruct  --dataset-name sonnet  --num-prompt=2048 --dataset-path="sonnet.txt" --sonnet-input-len 500
WARNING 10-09 07:40:04 rocm.py:13] `fork` method is not supported by ROCm. VLLM_WORKER_MULTIPROC_METHOD is overridden to `spawn` instead.
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision-0.16.1+fdea156-py3.10-linux-x86_64.egg/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torchvision-0.16.1+fdea156-py3.10-linux-x86_64.egg/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Namespace(backend='vllm', base_url=None, host='localhost', port=8000, endpoint='/v1/completions', dataset=None, dataset_name='sonnet', dataset_path='sonnet.txt', model='meta-llama/Llama-3.1-405B-Instruct', tokenizer=None, best_of=1, use_beam_search=False, num_prompts=2048, logprobs=None, request_rate=inf, seed=0, trust_remote_code=False, disable_tqdm=False, profile=False, save_result=False, metadata=None, result_dir=None, result_filename=None, ignore_eos=False, percentile_metrics='ttft,tpot,itl', metric_percentiles='99', sonnet_input_len=500, sonnet_output_len=150, sonnet_prefix_len=50, sharegpt_output_len=None, random_input_len=1024, random_output_len=128, random_range_ratio=1.0, random_prefix_len=0, hf_subset=None, hf_split=None, hf_output_len=None)
Starting initial single prompt test run...
Initial test run completed. Starting main benchmark run...
Traffic request rate: inf
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2048/2048 [19:01<00:00,  1.79it/s]
============ Serving Benchmark Result ============
Successful requests:                     2048      
Benchmark duration (s):                  1141.41   
Total input tokens:                      934713    
Total generated tokens:                  307198    
Request throughput (req/s):              1.79      
Output token throughput (tok/s):         269.14    
Total Token throughput (tok/s):          1088.05   
---------------Time to First Token----------------
Mean TTFT (ms):                          561573.45 
Median TTFT (ms):                        565381.62 
P99 TTFT (ms):                           1101082.43
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          452.38    
Median TPOT (ms):                        456.27    
P99 TPOT (ms):                           484.62    
---------------Inter-token Latency----------------
Mean ITL (ms):                           452.36    
Median ITL (ms):                         446.96    
P99 ITL (ms):                            899.47    
==================================================
```
