### ISSUE TITLE
Virtual Office Hours: August 8 and August 21

### ISSUE THREAD

**Issue by mgoin** [vllm-project/vllm#7657]
## vLLM Virtual Open Office Hours

We enjoyed seeing everyone at the previous office hours and got great feedback. These office hours are a virtual bi-weekly live event where you come to learn more about the vLLM project, how to contribute, and get help with your issues - with special topics and guests along the way.

Sign up here: https://neuralmagic.com/community-office-hours/
You can watch previous sessions on the [YouTube playlist](https://www.youtube.com/playlist?list=PLXs1FIgHP9MuwBESTGGlvYjJxcBu7bLJH). 

Dates:
- August 8, 2024, at 2:00 PM EST (11:00 AM PST), **Guest Topic:** Multi-Modal Models in vLLM, by Roger Wang from Roblox
![image](https://github.com/user-attachments/assets/19979011-d526-4b06-9051-33bbab947592)

- August 21, 2024, at 2:00 PM EST (11:00 AM PST), **Guest Topic:** vLLM on AMD GPUs and Google TPUs, by Woosuk Kwon from UC Berkeley
![image (16)](https://github.com/user-attachments/assets/9c47691e-23c2-4aad-86d2-6657c869bc3d)

If there are any themes or topics you would like to see addressed, please comment below. We look forward to seeing you there!

Previous office hour issue: https://github.com/vllm-project/vllm/issues/5937

**Comment by lev-channel** [comment]
Hi, I'm highly interested in running vLLM on Google cloud TPU VMs, especially like TPUv4 pod slices like TPUv4-32. 
is there any plan this office hour uploaded to youtube? :)

**Comment by sparsh35** [comment]
Sorry just saw it know , I had a question about the performance benchmark on TPUs, like what are the best practices does quantization  leads to more throughput.
