### ISSUE TITLE
Serving a .tar.gz model file

### ISSUE THREAD

**Issue by ryanshrott** [vllm-project/vllm#766]
I have a 13GB llama 2 fine tuned model called "llama2-finetuned.tar.zst". 

How would I go about deploying this using vllm? I have only tried the hugging face models.

**Comment by thunderamental** [comment]
.tar.gz files have been zipped. likely you will need to unzip that file to obtain the weights

**Comment by WoosukKwon** [comment]
vLLM supports `*.safetensors` and `*.bin` files for the model weights, just like HF transformers. Please unzip the file.
