### ISSUE TITLE
[Usage]: how to use guided_decoding_backend?

### ISSUE THREAD

**Issue by estuday** [vllm-project/vllm#7677]
### Your current environment

I found that in EngineArgs, guided_decoding_backend can choose to support outlines or lm-format-enforcer. How can I use it?
Specifically, the following code can be executed by outlines
```python
import outlines
model = outlines.models.transformers(model_path)
prompt = "fish is delicious"
unstruct_answer = outlines.generate.choice(model,["positive","negative"])(prompt)
```
How can I achieve this in vllm？

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

**Comment by dipatidar** [comment]
Hi @estuday! You can check out this [documentation](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-chat-api).
