### ISSUE TITLE
[Misc]: how to add tests for new backends?

### ISSUE THREAD

**Issue by ilya-lavrenov** [vllm-project/vllm#7683]
### Anything you want to discuss about vllm.

I see that some backends like Intel CPU have tests, but I cannot find any such configurations in .buildkite folder.
Could you please elaborate how we can add some simple scripts to check that OpenVINO backend is not broken? 

We have simple script for it https://github.com/vllm-project/vllm/blob/main/.buildkite/run-openvino-test.sh, but don't know how to add it to CI service.

Thanks

**Comment by DarkLight1337** [comment]
@WoosukKwon perhaps you have a more detailed idea about this?
