### ISSUE TITLE
Offline compilation and installation error

### ISSUE THREAD

**Issue by Isfate** [vllm-project/vllm#769]
When I installed vllm offline, I have already installed the 1.11.1 version of ninja, but when compiling and installing, I still need the network to download the ninja installation package
Error:
![image](https://github.com/vllm-project/vllm/assets/49968353/c2d9456c-3af8-44ad-a603-f22426ec006d)
![image](https://github.com/vllm-project/vllm/assets/49968353/8468cfd5-651e-4471-ac31-ee350bacffa0)
![image](https://github.com/vllm-project/vllm/assets/49968353/63719e69-ef86-4154-8965-c64adb5c3022)

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
