### ISSUE TITLE
[Feature]: Overlap model weight loading and model prefill

### ISSUE THREAD

**Issue by candyzone** [vllm-project/vllm#7690]
### 🚀 The feature, motivation and pitch

For LLM inference, requests per second(QPS) is not constant. It needs launch vllm engine on demand. For elastic instance, it's significance to reduce TTFT(Time to First Token).
Hence, it's necessary to overlap model loading and prefill, especially very large model which model loading costs several seconds.

### Alternatives

1. Model cache system for vllm: efficient IO (such as: PCIe, NVLink)
2. Load model weight by LLM topo order and execute model immediately after parameter is ready

**Comment by youkaichao** [comment]
what do you mean by `model weight loading` ? during inference, model weights are already in GPU.

**Comment by candyzone** [comment]
> what do you mean by `model weight loading` ? during inference, model weights are already in GPU.

`model weight loading` is the model initialization stage ([code](https://github.com/vllm-project/vllm/blob/b74a12580022039fc15fb54c7066cc13fdc96220/vllm/worker/model_runner.py#L877C8-L877C19)), the overlap is loading model weight and executing model first time(prefill stage).

The idea is illustrated below.
![LLM fast loading](https://github.com/user-attachments/assets/c4970c25-3cf2-40f0-8eb9-e2078cd263ba)

**Comment by candyzone** [comment]
@youkaichao 
what do you think about this idea?
It needs some work on vLLM engine to extend model loader.

**Comment by youkaichao** [comment]
I still don't get it. What do you mean by `loading model weight`? from where to where?

**Comment by candyzone** [comment]
> I still don't get it. What do you mean by `loading model weight`? from where to where?

`loading model weight` is load model Parameter from Disk to GPU. That is a prerequisite for model Inference.

**Comment by youkaichao** [comment]
we don't store weights/kv cache on disk.

**Comment by candyzone** [comment]
> we don't store weights/kv cache on disk.

at the begining, the model store on disk, first step is reading model(safetensors/pt) to DRAM, then cudaMemcpy to GPU second step is to infer LLM model(prefill / decode stage).
I mean the `loading model weight` is the first step.

**Comment by candyzone** [comment]
@youkaichao could you assign this issue to `model_loader` component owner or anyone else?

**Comment by candyzone** [comment]
@youkaichao could you assign this issue to `model_loader` component owner or anyone else, and reopen the issue?
