### ISSUE TITLE
first token take long time consuming

### ISSUE THREAD

**Issue by yhSmiling** [vllm-project/vllm#770]
Dears:
    
         During  baichuan 13b 's token generation based on vllm ,  the first token in every single prompt always take  long time consuming . Sometimes even more than 60 ms .  Is this normal ?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by anhdungitvn** [comment]
> Dears:
> 
> ```
>      During  baichuan 13b 's token generation based on vllm ,  the first token in every single prompt always take  long time consuming . Sometimes even more than 60 ms .  Is this normal ?
> ```

- In theory
Time To First Token (TTFT) ≙ max((2 * N * B * S) / FLOPs rate, (2 * N HBM rate))
In which,
    - N: number of model parameters
    - B: batch size
    - S: number of input tokens
    - FLOPs rate: how many FLOPs per second the GPU can do (check GPU datasheet).
- Actual
  - TTFT = TTFT + tokenize+decode+etc.
  - Setting: Model 8B, batch 1, GPU A5000, number input token 8
  - Results: TTFT ~ 62ms.
- Summary:
  - Your results (60 ms) is normal.

The detailed explanation is shown [here](https://huggingface.co/blog/tgi-benchmarking).
