### ISSUE TITLE
Falcon not running on multiple GPUs

### ISSUE THREAD

**Issue by Shivampanwar** [vllm-project/vllm#772]
Hi, I am trying to run Falcon on multiple GPUs. Below is the code for the same:
`model_name = "tiiuae/falcon-7b-instruct"
llm = LLM(model=model_name,trust_remote_code=True,dtype="float16",tensor_parallel_size=4)
`

It's giving me the error: 
` ValueError: Total number of attention heads (71) must be divisible by tensor parallel size (4).
`Is there a way to resolve this issue ?

It's working fine on A100 but I have four GPUs hence it is not working.

**Comment by nadimintikrish** [comment]
Falcon doesn't support tensor parallelism.

**Comment by iamsimha** [comment]
> Falcon doesn't support tensor parallelism.

Not true, only Falcon 7B cannot be run multiple GPUs, due to the limitation of attention heads being not divisible by tensor parallel size. 

I was able to run Falcon-40B on 8 * A10  GPUs

**Comment by yanmengxiang1** [comment]
@iamsimha hello,Do you have some ideas in #930,thanks!

**Comment by ilml** [comment]
Having the same issue, why they had 71 instead of 72 heads. 71 is a prime number and makes it impossible to do sharding ;]

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
