### ISSUE TITLE
[Usage]: About bitsandbytes

### ISSUE THREAD

**Issue by ekmekovski** [vllm-project/vllm#7738]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I just wanted to ask about which quantization am I using when I run the following command. It worked fine I didnt have trouble but I was unable to identify which quantization is it.
python3 -m vllm.entrypoints.openai.api_server --host x.x.x.x --port xxxx --model xxxx/Llama3-8b --quatization bitsandbytes --enforce_eager --dtype half
Are there any support for bnb 8bit quantization?
Thnx  lot.

**Comment by emreekmekcioglu1** [comment]
As I understood from previous issue there is no 8bit quantization support for bnb rn :(. But again thnx a lot for this great work!
