### ISSUE TITLE
[Feature]: phi-3.5 is a strong model for its size, including vision support.  Has multi-image support, but vllm does not support

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#7740]
### 🚀 The feature, motivation and pitch

phi-3.5 is a strong model for its size, including strong multi-image vision support.   But vllm does not support the multi-image case.

https://github.com/vllm-project/vllm/blob/03b7bfb79b1edf54511fd1b12acc9a875cee5656/vllm/model_executor/models/phi3v.py#L421-L425

### Alternatives

Only other models

**Comment by Isotr0py** [comment]
Of course, I'm just working on implementing this feature.
I will create a PR once it's nearly to be finished.
