### ISSUE TITLE
 Support vllm to use lm-eval to evaluate model accuracy

### ISSUE THREAD

**Issue by lixiaolx** [vllm-project/vllm#776]
May I ask what method is currently used by vllm to evaluate the accuracy of the model?

When using[ llm-eval](https://github.com/EleutherAI/lm-evaluation-harness) to test the accuracy of the llm running model, according to the evaluation method of llm-eval, prompts corresponding to logprobs need to be output at the same time for subsequent acc or ppl calculations. 
But at present, vllm can only output the generated sentences. Can you add options to support vllm to output results after running, output prompt words and corresponding logprobs function?

**Comment by hmellor** [comment]
This should now be supported as of #1328 adding the ability for vLLM to return log probabilities.
