### ISSUE TITLE
Include Llama-405B in nightly benchmarks?

### ISSUE THREAD

**Issue by anilmurty** [vllm-project/vllm#7761]
### 🚀 The feature, motivation and pitch

Include the Llama-405B model as part of the nightly performance benchmarks here: https://buildkite.com/vllm/performance-benchmark/builds/4068

Is the reason for not doing so primarily cost (16-24 H100s needed)? If so Akash.Network would consider providing the infra for it. 

Thanks!

### Alternatives

Running the benchmarks ourselves 

### Additional context

We’ve been trying to run Llama-405B-FP8 in production (with vLLM + Ray) and have been encountering stability issues with it.

**Comment by simon-mo** [comment]
Hi @anilmurty, definitely cost is our concern. To benchmark the fp8 model we need 1 node with SXM and pipeline parallel we need 2 nodes that's interconnected.

**Comment by anilmurty** [comment]
We have a few 8 node H100 clusters with SXM5 and IB that I think will be capable of running with both PP and TP enabled. We should be able to allocate 1 or 2 nodes from them to support the project. 

Only caveat (if that) is that we run K8s to orchestrate on our platform so it'll be K8s+Ray+vLLM -- will that be OK for your benchmarking suite?

Reference:

https://akash.network/blog/distributed-machine-learning-on-akash-network-with-ray/


https://akash.network/blog/running-vllm-on-akash/

**Comment by robertgshaw2-neuralmagic** [comment]
@anilmurty - can you elaborate a bit more on the stability issues? Any logs you can share will also help us address root causes
