### ISSUE TITLE
Alibi embeddings and multi_query_attention do not work together

### ISSUE THREAD

**Issue by AkshitaB** [vllm-project/vllm#777]
I am trying to integrate my experimental model architecture, which uses both `alibi` embeddings and `multi_query_attention`. In comparing outputs from the vllm-integrated model and my underlying model, I notice that the generations do not match if `alibi` and `multi_query_attention` are both turned on. They do match if I turn off `multi_query_attention`. With a larger model, I actually run into nans, and the generation fails.

I initialize the attention module as follows:

```
self.attention = PagedAttentionWithALiBi(num_heads, head_dim, scale=scaling, slopes=slopes, num_kv_heads=1)
```

I have narrowed down the discrepancy to the `single_query_cached_kv_attention` call. I don't see any test cases for `PagedAttentionWithAlibi`, so debugging is a little difficult. Any help will be appreciated!

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
