### ISSUE TITLE
[Feature]: Check for presence of files at startup

### ISSUE THREAD

**Issue by cduk** [vllm-project/vllm#7780]
### 🚀 The feature, motivation and pitch

Checks for files such as templates etc. should be done right at the start of vLLM loading. Not right at the end after 30 minutes of loading the model.

[rank0]: ValueError: The supplied chat template (./chat_template/llama3.jinja) looks like a file path, but it failed to be opened. Reason: [Errno 2] No such file or directory:

**Comment by simon-mo** [comment]
Good point. PR welcomed here!
