### ISSUE TITLE
baichuan-13b-base output is not same as hugginface transformers

### ISSUE THREAD

**Issue by nexa123** [vllm-project/vllm#780]
When prompt="请介绍深圳市"，temperature=1.0 top_k=1 top_p=1 and dtype = fp16. I find vllm (d1744376ae9fdbfa6a2dc763e1c67309e138fa3d) ouput text is "的经济状况,人口,交通,旅游,文化,教育,医疗,体育,环境,治安,消费,住房,就业,收入,物价,消费,天气,民族,宗教,语言,饮食,服饰,节日,习俗,禁忌,婚丧,礼仪,名胜,古迹,旅游,文化,教育,医疗,体育,环境,治安,消费,住房,就业,收入,物价,消费,天气,民族,宗教,语言,饮食,服饰,节日,习俗,禁忌,婚丧,礼仪,名胜,古迹,", but huggingface transformers's ouput text is " 的经济状况,人口,交通,旅游,文化,教育,医疗,体育,环境,治安,消费,住房,就业,物价,收入,民族,宗教,语言,饮食,服饰,节日,习俗,禁忌,婚丧,礼仪,名胜,古迹,旅游,文化,教育,医疗,体育,环境,治安,消费,住房,就业,物价,收入,民族,宗教,语言,饮食,服饰,节日,习俗,禁忌,婚丧,礼仪,名胜,古迹,旅游,文化,教育,医疗".
But when dtype is fp32, the output text is all "的经济状况,谢谢!
深圳的经济状况
 深圳经济特区建立以来,在短短的20多年里,深圳经济实现了跨越式发展,创造了举世瞩目的“深圳速度”。1980年,深圳国内生产总值仅为1.96亿元,2003年达到7800亿元,年均增长20.7%,是1980年的386倍。2003年,深圳人均GDP达到1.6万美元,是1980年的1000倍。
 深圳经济"。
Comparing dozens prompts, this divergence of two library is always present.

**Comment by ansvver** [comment]
降低一下temperature 和 top_p 试试？

**Comment by sfyumi** [comment]
我也遇到同样的问题，temperature=1.0, top_p=1 时输出有问题，调低就好了，估计是这种边缘 case 实现有 BUG
