### ISSUE TITLE
[Usage]: The seed in vllm.SamplingParams and vllm.LLM

### ISSUE THREAD

**Issue by caiqizh** [vllm-project/vllm#7812]
### Your current environment

vllm==0.4.0

### How would you like to use vllm

I notice that there are two seeds when using vllm. 

The first one is in `vllm.LLM`.

https://docs.vllm.ai/en/latest/_modules/vllm/entrypoints/llm.html#LLM 

The second one is in `vllm.SamplingParams`. 

https://docs.vllm.ai/en/latest/_modules/vllm/sampling_params.html#SamplingParams

I am wondering what are the differences between these two.

**Comment by ycool** [comment]
LLM.seed: system level random seed, 
e.g. https://github.com/vllm-project/vllm/blob/main/vllm/worker/worker.py#L179

vllm.SamplingParams.seed: request level random seed 
e.g https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/sampling_metadata.py#L486

**Comment by caiqizh** [comment]
Thank you! 

Looks like `vllm.LLM` is for:

```
 random.seed(seed)
 np.random.seed(seed)
 torch.manual_seed(seed)
```

https://github.com/vllm-project/vllm/blob/ea9fa160e3b47e0b8aa273f3eb2be410bd1ccab5/vllm/model_executor/utils.py#L9-L14

**Comment by llllllliam360** [comment]
hi @ycool~ I have a further question.
What is the seed used for sample_parameter if it is not set? How can we check it?
