### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by designInno** [vllm-project/vllm#783]
I have GPU device 1, and there are other processes taking up about 15G of Memory-Usage, but there is 30G of Memory-Usage left, so why does it go OOM when I run a small model?

Here is my code：
```

from vllm import LLM
import torch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
from vllm import LLM, SamplingParams

if __name__ == '__main__':

    device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

    prompts = [
        "Hello, my name is",
        "The president of the United States is",
        "The capital of France is",
        "The future of AI is",
    ]
    sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
    llm = LLM(model="facebook/opt-125m",tensor_parallel_size=1)

    outputs = llm.generate(prompts, sampling_params)
    
    # Print the outputs.
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```
Exception：
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.63 GiB (GPU 0; 44.56 GiB total capacity; 27.91 GiB already allocated; 565.31 MiB free; 27.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

![image](https://github.com/vllm-project/vllm/assets/36481411/4016432a-f44b-4992-ae5c-d6ea28337b26)

![image](https://github.com/vllm-project/vllm/assets/36481411/e249e625-36dd-452b-a5f1-107435961a84)

**Comment by Gregory-Ledray** [comment]
I am not a maintainer. You are seeing this error because:

> vLLM is designed to occupy all the GPU memory for storing KV cache blocks. You can pass in the gpu_memory_utilization=0.5 (50% utilization, or can be set even lower) when initialize the LLM class to reduce the memory footprint.

https://github.com/vllm-project/vllm/issues/304#issuecomment-1613254311

Did you try using the parameter `--gpu-memory-utilization GPU_MEMORY_UTILIZATION`?

**Comment by designInno** [comment]
Thanks, that was the problem!
