### ISSUE TITLE
[Feature]: Support AI21-Jamba-1.5-Large (and mini)

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#7832]
### 🚀 The feature, motivation and pitch

https://huggingface.co/ai21labs/AI21-Jamba-1.5-Large

### Additional context

I didn't find any issues, but I see Jamba supported potentially.  Not sure about these newer models.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
We believe it is supported already (given communication with the Jamba team) but please report any issues!

**Comment by pseudotensor** [comment]
Awesome, will try.  Thanks!
