### ISSUE TITLE
[Misc]: Multi-Node Multi-GPU (tensor parallel plus pipeline parallel inference)

### ISSUE THREAD

**Issue by ilovesouthpark** [vllm-project/vllm#7837]
### Anything you want to discuss about vllm.

 I have 2 nodes and each of them has 2 v100. According to the guide, i can use tensor parallel in each node and crossing the 2 nodes i can use pipline parallel. My question is which card or cards will communicate with the other card or cards in the other node.
Thanks

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
inside every layer, allreduce across 2 V100 in the same node.

across pipeline stages, send/recv across nodes

**Comment by ilovesouthpark** [comment]
Thanks

**Comment by ilovesouthpark** [comment]
Thank you and i will have a try.
