### ISSUE TITLE
vllm producing gibberish with stabilityai/StableBeluga-7B

### ISSUE THREAD

**Issue by corbt** [vllm-project/vllm#786]
Hey there,

I'm using vllm to serve Llama 2 models in production and for most of them it's working well!

However, when running the Llama 2 derivative [StableBeluga-7B](https://huggingface.co/stabilityai/StableBeluga-7B) vllm produces gibberish. I've included a minimal repro below: 

### Calling the model with `transformers` directly works as expected
```python
%pip install transformers sentencepiece accelerate

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

prompt = f"### User: count to 5\n\n### Assistant:\n"

tokenizer = AutoTokenizer.from_pretrained("stabilityai/StableBeluga-7B")
model = AutoModelForCausalLM.from_pretrained("stabilityai/StableBeluga-7B")

inputs = tokenizer(prompt, return_tensors="pt")
output = model.generate(**inputs, max_new_tokens=20)

print(tokenizer.decode(output[0], skip_special_tokens=True)[len(prompt):])
# Prints "1, 2, 3, 4, 5"
```

### Calling the model with `vllm` returns gibberish
```python
from vllm import LLM, SamplingParams

prompt = f"### User: count to 5\n\n### Assistant:\n"

llm = LLM(model="stabilityai/StableBeluga-7B")
sampling_params = SamplingParams()
outputs = llm.generate([prompt], sampling_params)

print(outputs[0].outputs[0].text)
# Prints "hd Business pleasure canción Stock Mohból vieрюścierves Democratic Zum beskrevs PelΤ"
```

Any idea what's going wrong? I've tried both the latest released vllm (0.1.3) and the `main` branch.

**Comment by salted-adam** [comment]
The same problem here

**Comment by FlyingCarlos** [comment]
I fix this problem by installing from source

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
