### ISSUE TITLE
Aborted due to the lack of CPU swap space, but there is enough RAM and swap

### ISSUE THREAD

**Issue by viktor-ferenczi** [vllm-project/vllm#787]
Ubuntu 22.04 (up to date, recently installed)
nVidia 4090
CUDA 11.8
cuDNN 8.9.4.25

vLLM compiled from source: `d1744376`

Model: `ehartford/dolphin-llama2-7b`

```python
llm = LLM(model=model_path, dtype='bfloat16')
sampling_params = SamplingParams(n=50, max_tokens=600, temperature=0.2, top_p=0.95)
results = llm.generate(prompts, sampling_params, use_tqdm=True)
```

200 prompts were prepared according to the model card's prompt template.
The point of failure seems to be random.

There is enough memory and swap. I don't know why it even requires any swap...
```
$ free -h
               total        used        free      shared  buff/cache   available
Mem:            62Gi       5,8Gi        13Gi        45Mi        43Gi        56Gi
Swap:           31Gi       787Mi        31Gi
```

Nor the memory, not the swap use spikes/changes at all when the failure happens. Monitored it with 1s period.

Full exception:
```
...
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 130, in generate
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/entrypoints/llm.py", line 150, in _run_engine
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/engine/llm_engine.py", line 300, in step
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/core/scheduler.py", line 251, in schedule
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/core/scheduler.py", line 197, in _schedule
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/core/scheduler.py", line 360, in _preempt
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/core/scheduler.py", line 385, in _preempt_by_swap
  File "/home/viktor/ts/venv/lib/python3.10/site-packages/vllm-0.1.3-py3.10-linux-x86_64.egg/vllm/core/scheduler.py", line 406, in _swap_out
RuntimeError: Aborted due to the lack of CPU swap space. Please increase the swap space to avoid this error.
Processed prompts:  12%|█▏        | 23/200 [00:55<07:05,  2.41s/it]
```

**Comment by viktor-ferenczi** [comment]
There is a FIXME in vLLM code (`core/scheduler.py`) where the problem happens. 

I guess there is a bug causing this issue in the first place.

```python
            # FIXME(woosuk): Abort the sequence group instead of aborting the
            # entire engine.
            raise RuntimeError(
                "Aborted due to the lack of CPU swap space. Please increase "
                "the swap space to avoid this error.")
```

**Comment by viktor-ferenczi** [comment]
Sending the prompts in batches of 8 seems to work so far without crashing.

But doing this goes against the advice in the docstring of the `generate` method:
```
        NOTE: This class automatically batches the given prompts, considering
        the memory constraint. For the best performance, put all of your prompts
        into a single list and pass it to this method.
```

I also figured the "CPU swap" is not the disk swap, but part of your logic. I do not know (yet) how to increase the size of that.

**Comment by ridiculouz** [comment]
I also run into this problem with much free memory. Hopefully there's a simply patch...

**Comment by puddingfjz** [comment]
I think the users can set the CPU swap space here: https://github.com/vllm-project/vllm/blob/d1744376ae9fdbfa6a2dc763e1c67309e138fa3d/vllm/engine/arg_utils.py#L26

**Comment by ridiculouz** [comment]
> I think the users can set the CPU swap space here:
> 
> https://github.com/vllm-project/vllm/blob/d1744376ae9fdbfa6a2dc763e1c67309e138fa3d/vllm/engine/arg_utils.py#L26

Thanks @puddingfjz ! I will look into that.
So the swap space in vllm actually refers to a reserved memory space (per gpu)?

**Comment by puddingfjz** [comment]
I think it is for the CPU swap space. (not sure what it means in multi-gpu scenario)

**Comment by viktor-ferenczi** [comment]
> ```python
>             # FIXME(woosuk): Abort the sequence group instead of aborting the
>             # entire engine.
>             raise RuntimeError(
>                 "Aborted due to the lack of CPU swap space. Please increase "
>                 "the swap space to avoid this error.")
> ```

I think implementing the above FIXME and exposing the `swap_space: int = 4  # GiB` value as a configuration value would solve this issue.

**Comment by aflip** [comment]
so how exactly can I edit this?

If i open the file in /.conda/sitepackages etc. there doesn't seem to be any change in what the notebook calls. 

> I think the users can set the CPU swap space here:
> 
> https://github.com/vllm-project/vllm/blob/d1744376ae9fdbfa6a2dc763e1c67309e138fa3d/vllm/engine/arg_utils.py#L26

**Comment by viktor-ferenczi** [comment]
The [LLM class](https://github.com/vllm-project/vllm/blob/d0740dff1b3ab06860316d98c937a3d4e143f25f/vllm/entrypoints/llm.py#L53) has a swap_space argument on construction.

If you use the command line argument try to use the `--swap-space` argument (default is 4, unit is GB).

**Comment by chi2liu** [comment]
> so how exactly can I edit this?
> 
> If i open the file in /.conda/sitepackages etc. there doesn't seem to be any change in what the notebook calls.
> 
> > I think the users can set the CPU swap space here:
> > https://github.com/vllm-project/vllm/blob/d1744376ae9fdbfa6a2dc763e1c67309e138fa3d/vllm/engine/arg_utils.py#L26

At present, we have found a workaround and set the swap space directly to 0. This way, we will not call the CPU swap space and will not report any errors. However, the CPU blocks will also become 0, which may slow down the speed a bit, but at least it will not hang and die.

**Comment by evgenii-nikishin** [comment]
Hi, I've tried to set `swap_space=0` but I'm still getting the error.

I'm using
Ubuntu 18.04
A100 GPU
CUDA 12.2
vLLM version 0.2.7
Model `codellama/CodeLlama-7b-hf`

**Comment by brightest66** [comment]
> > ```python
> >             # FIXME(woosuk): Abort the sequence group instead of aborting the
> >             # entire engine.
> >             raise RuntimeError(
> >                 "Aborted due to the lack of CPU swap space. Please increase "
> >                 "the swap space to avoid this error.")
> > ```
> 
> I think implementing the above FIXME and exposing the `swap_space: int = 4 # GiB` value as a configuration value would solve this issue.我认为实现上述 FIXME 并将`swap_space: int = 4 # GiB`值公开为配置值可以解决此问题。

Hi,How to implementing the above FIXME?

**Comment by brightest66** [comment]
> Hi, I've tried to set `swap_space=0` but I'm still getting the error.你好，我尝试设置`swap_space=0`但仍然收到错误。
> 
> I'm using 我正在使用 Ubuntu 18.04 乌班图18.04 A100 GPU A100显卡 CUDA 12.2 杂项 12.2 vLLM version 0.2.7 vLLM版本0.2.7 Model `codellama/CodeLlama-7b-hf`型号`codellama/CodeLlama-7b-hf`

Hi,Do you fix it?

**Comment by yechenzhi** [comment]
> swap_space=0

I set `swap_space=3`2 which solved the problem, though `free -h` shows my swap is only 8G.
