### ISSUE TITLE
Error reported when running multiple cards with docker container on cloud platform

### ISSUE THREAD

**Issue by tbup** [vllm-project/vllm#789]
WARNING 08-18 01:35:48 tokenizer.py:63] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
(RayWorker pid=4711) *** SIGBUS received at time=1692322557 on cpu 5 ***
(RayWorker pid=4711) PC: @     0x7fca7c80cb41  (unknown)  (unknown)
(RayWorker pid=4711)     @     0x7fca7c9e1420       3424  (unknown)
(RayWorker pid=4711)     @ 0x554b2d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=4711) [2023-08-18 01:35:57,940 E 4711 4962] logging.cc:361: *** SIGBUS received at time=1692322557 on cpu 5 ***
(RayWorker pid=4711) [2023-08-18 01:35:57,941 E 4711 4962] logging.cc:361: PC: @     0x7fca7c80cb41  (unknown)  (unknown)
(RayWorker pid=4711) [2023-08-18 01:35:57,941 E 4711 4962] logging.cc:361:     @     0x7fca7c9e1420       3424  (unknown)
(RayWorker pid=4711) [2023-08-18 01:35:57,943 E 4711 4962] logging.cc:361:     @ 0x554b2d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=4711) Fatal Python error: Bus error
(RayWorker pid=4711) 
(RayWorker pid=4711) 
(RayWorker pid=4711) Extension modules: msgpack._cmsgpack, setproctitle, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, yaml._yaml, grpc._cython.cygrpc, ray._raylet, charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, sentencepiece._sentencepiece, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.hashing, pandas._libs.tslib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, pyarrow._json, PIL._imaging (total: 103)
2023-08-18 01:35:59,180	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff21c4c317b5f12f485dd3ed9601000000 Worker ID: cbf297e4214dfe3a61a62347babe5995cec3a1c41787c1360a8e9b2b Node ID: 833e5e412a4498ac61480486982c4a8dbcaf6081437a976c4bbf2579 Worker IP address: 172.18.0.2 Worker port: 42604 Worker PID: 4711 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
Traceback (most recent call last):
  File "/workspace/vllm_server/vllm_server.py", line 448, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 104, in __init__
    self._init_cache()
  File "/usr/local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 182, in _init_cache
    num_blocks = self._run_workers(
  File "/usr/local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 18, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2542, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: RayWorker
	actor_id: 21c4c317b5f12f485dd3ed9601000000
	pid: 4711
	namespace: 5e81e4ce-e6f9-4a5a-9850-91ec998fdc6c
	ip: 172.18.0.2
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-08-18 01:35:59,200	WARNING worker.py:2019 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff60393bd46c6885795e8c860a01000000 Worker ID: bdd9060e04da02c94c78e0576e5dab9fa63c0cd82eeb9a09870749d1 Node ID: 833e5e412a4498ac61480486982c4a8dbcaf6081437a976c4bbf2579 Worker IP address: 172.18.0.2 Worker port: 35128 Worker PID: 4712 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
(RayWorker pid=4712) *** SIGBUS received at time=1692322557 on cpu 3 ***
(RayWorker pid=4712) PC: @     0x7fb345256b41  (unknown)  (unknown)
(RayWorker pid=4712)     @     0x7fb34542b420       3424  (unknown)
(RayWorker pid=4712)     @ 0x574e2d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=4712) [2023-08-18 01:35:57,940 E 4712 4961] logging.cc:361: *** SIGBUS received at time=1692322557 on cpu 3 ***
(RayWorker pid=4712) [2023-08-18 01:35:57,941 E 4712 4961] logging.cc:361: PC: @     0x7fb345256b41  (unknown)  (unknown)
(RayWorker pid=4712) [2023-08-18 01:35:57,942 E 4712 4961] logging.cc:361:     @     0x7fb34542b420       3424  (unknown)
(RayWorker pid=4712) [2023-08-18 01:35:57,943 E 4712 4961] logging.cc:361:     @ 0x574e2d6c63636e2f  (unknown)  (unknown)
(RayWorker pid=4712) Fatal Python error: Bus error
(RayWorker pid=4712)  [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(RayWorker pid=4712) Extension modules: msgpack._cmsgpack, setproctitle, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, yaml._yaml, grpc._cython.cygrpc, ray._raylet, charset_normalizer.md, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, sentencepiece._sentencepiece, pyarrow.lib, pyarrow._hdfsio, pyarrow._fs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.hashing, pandas._libs.tslib, pandas._libs.ops, pyarrow._compute, pandas._libs.arrays, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.index, pandas._libs.internals, pandas._libs.join, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, pyarrow._json, PIL._imaging (total: 103)

**Comment by tbup** [comment]
Device information is as follows：
root@e5ada9ab73f0:/workspace/vllm_server# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         296G   77G  204G  28% /
tmpfs            64M     0   64M   0% /dev
tmpfs            53G     0   53G   0% /sys/fs/cgroup
shm              64M   20M   45M  31% /dev/shm
/dev/vdb        296G   77G  204G  28% /workspace/models
tmpfs            53G   12K   53G   1% /proc/driver/nvidia
/dev/vda1        40G  4.7G   33G  13% /usr/bin/nvidia-smi
devtmpfs         53G     0   53G   0% /dev/nvidia0
tmpfs            53G     0   53G   0% /proc/asound
tmpfs            53G     0   53G   0% /proc/acpi
tmpfs            53G     0   53G   0% /proc/scsi
tmpfs            53G     0   53G   0% /sys/firmware
root@e5ada9ab73f0:/workspace/vllm_server# free -g
              total        used        free      shared  buff/cache   available
Mem:            105           3          39           0          63         101
Swap:             0           0           0
root@e5ada9ab73f0:/workspace/vllm_server# nvidia-smi
Fri Aug 18 01:51:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A30          Off  | 00000000:00:08.0 Off |                    0 |
| N/A   38C    P0    31W / 165W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A30          Off  | 00000000:00:09.0 Off |                    0 |
| N/A   35C    P0    30W / 165W |      0MiB / 24576MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by Gregory-Ledray** [comment]
I am not a maintainer. Are you running anything else on your GPU?

> vLLM is designed to occupy all the GPU memory for storing KV cache blocks. You can pass in the gpu_memory_utilization=0.5 (50% utilization, or can be set even lower) when initialize the LLM class to reduce the memory footprint.

https://github.com/vllm-project/vllm/issues/304#issuecomment-1613254311

Did you try using the parameter `--gpu-memory-utilization GPU_MEMORY_UTILIZATION`?

See also: #751

**Comment by tbup** [comment]
Thank you for your reply.  I am running the task exclusively,  it has nothing to do with the parameter.
And the error only appears in multi-card running, single card is normal.  Does the use of ray running multi-card take up more cpu memory?

**Comment by tbup** [comment]
Resolved, the container's shared memory is insufficient

**Comment by luefei** [comment]
> 
the same issue in container, but memory is enough, 
did you how to resolve?

**Comment by tbup** [comment]
@luefei  try run docker that use "--shm-size" to  increase container's shared memory.

**Comment by Nicolas-Thomazo** [comment]
how much memory did you allocate to /dev/shm ? Even with 30GB I get this error for Mistral model. I don't get this error for Llama-2-13b-chat

**Comment by qingjiaozyn** [comment]
I'm also having the same issue, I started vllm qwen acceleration in a container, using 8 graphics cards, --shm-size gave 380G, and I also get an error like this
