### ISSUE TITLE
[Usage]: how to test the time of response about minicpm-v-2.6 served by VLLM

### ISSUE THREAD

**Issue by Mysnake** [vllm-project/vllm#7891]
### Your current environment

I depoly minicpmv though VLLM, but I want to test the  the time of response. 
First, I use OpenAI.chat.completions.create() to access the server. It response the result successfully. Code in the following:
![image](https://github.com/user-attachments/assets/07587d62-97e2-482a-8390-81af8365c3bc)

And then, I use post request to access the server. Code is in the following:
![image](https://github.com/user-attachments/assets/fb0e5f31-1b9b-4684-8cf0-81acee7f5e24)

![image](https://github.com/user-attachments/assets/ef3c2597-176a-4c71-811f-bfbec2c20bf9)

The log of server is 
![image](https://github.com/user-attachments/assets/96fb271d-daf4-4e8b-b6d6-0399be667e0a)

How can I send the request of json to server?

### 🐛 Describe the bug

How can I send the request of json to server?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should be using Chat Completions API (`v1/chat/completions`), not the Completions API (`v1/completions`)

**Comment by ywang96** [comment]
Closing this since @DarkLight1337 provided a good answer
