### ISSUE TITLE
[Installation]: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback): libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by minhuiah** [vllm-project/vllm#7903]
### Your current environment

```text
The output of `python collect_env.py`
```

### How you are installing vllm

```sh
pip install -vvv vllm
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
please give more information and the full output about your issue.
