### ISSUE TITLE
[Feature]: Lora for MiniCPM_2_6

### ISSUE THREAD

**Issue by tristan279** [vllm-project/vllm#7909]
### 🚀 The feature, motivation and pitch

As the finetuning script in the minicpm repo is also lora, i woul like to load it in my vllm endpoint, but error is thrown: minicpmvd2_6 does not support LoRA

### Alternatives

full finetuning is too heavy

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Please see #7199
