### ISSUE TITLE
Why set gpu_memory_utilization so big? What‘s the benifit for it?

### ISSUE THREAD

**Issue by bigmover** [vllm-project/vllm#793]
if gpu_memory_utilization set to 0.9，nowhatever you load a model， it will occupy very huge memory

**Comment by bigmover** [comment]
Got it! Thank you for your detailed reply and awesome work!  Expect the dynamic resize of KV cache

**Comment by SatoshiReport** [comment]
@cason0126 it "increases the number of requests that can be batched together" (from @WoosukKwon) and not the throughput or speed of results.
