### ISSUE TITLE
[Bug]:reset LLM for each inference

### ISSUE THREAD

**Issue by victorzhz111** [vllm-project/vllm#7944]
### Your current environment

vllm 0.5.4
pytorch 2.4.0+cu121

### 🐛 Describe the bug

Hello, 

I am using the LLM for offline line inference. I have two models that share the same lower layers but different upper layers. So typically it has two different CUDA graphs. However, every time when I tried to inference on the first model and then run the inference on the second model. They continue to give the results for the first model. Is anyway that I can reset and run the second model successfully? I have tried enforce-eager and torch.cuda.empty_cache().

Thank you

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Try this: https://github.com/vllm-project/vllm/issues/6544#issuecomment-2237994380
