### ISSUE TITLE
[Bug]: deploy multi lora by vllm mode error

### ISSUE THREAD

**Issue by askcs517** [vllm-project/vllm#7946]
### Your current environment

<details>
Env:
    cuda11.8
    vllm 0.4.3

</details>

### 🐛 Describe the bug

in T4 and vllm version==0.4.3
deploy multi lora by vllm failed, error info:
RuntimeError: CUDA error: no kernel image is available for execution on the device.
my deploy command:
CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy --tensor_parallel_size 4 --dtype fp16 --model_type qwen1half-7b-chat
--model_id_or_path /cloud/user/data/data0806/llm/M2/Chat_New
--ckpt_dir /cloud/user/data/data0806/llm/M2/checkpoint-200/
--infer_back vllm -- vllm_enable_lora true --max_model_len 512 --enforce_eager
I tried to vllm to 0.5.5, there is still error

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Try upgrading your CUDA version. CUDA 11.8 may be too old.

**Comment by askcs517** [comment]
您好，您的邮件我已经收到，我会及时查收。麻烦您了。
