### ISSUE TITLE
[Feature]: Context Caching

### ISSUE THREAD

**Issue by RonanKMcGovern** [vllm-project/vllm#7952]
### 🚀 The feature, motivation and pitch

Allow saving of kv cache for faster TTFT on long prompts.

Another related feature would be to allow a fixed and shared cache across all requests. Perhaps this would be even easier to implement.

### Alternatives

I suppose prompt compression, but it's not as quick as context caching.

### Additional context

claude and gemini have implemented this.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
Given that we already have automatic prefix caching, is the suggestion about an explicit API to "pinning" some requests in GPU/CPU/Disk?

**Comment by zifeitong** [comment]
> Given that we already have automatic prefix caching, is the suggestion about an explicit API to "pinning" some requests in GPU/CPU/Disk?

Two examples of such APIs: https://ai.google.dev/gemini-api/docs/caching?lang=python, https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by RonanKMcGovern** [comment]
@simon-mo thanks for the response.

I've read some more and I believe (auto) pinning is happening via RadixAttention [here](https://github.com/vllm-project/vllm/blob/4f5d8446ede9f85182126804c6b07a56e06fd3d1/docs/source/automatic_prefix_caching/details.md?plain=1#L38). 

So I think things already work and I didn't appreciate that.


@zifeitong yes, thanks. I have been running claude and gemini and want to compare now open source.

**Comment by llsj14** [comment]
I'm implementing a 'pinning' option for prefix caching and considering an explicit API for it. I would appreciate any feedback on my RFC if you're interested

https://github.com/vllm-project/vllm/issues/8333
