### ISSUE TITLE
[Bug]: run gguf ，the gguf model is only 800M, but why does the GPU memory usage exceed 20G?

### ISSUE THREAD

**Issue by lonngxiang** [vllm-project/vllm#7979]
### Your current environment

0.5.5 vllm

### 🐛 Describe the bug

 CUDA_VISIBLE_DEVICES=1 vllm serve  /ai/qwen1.5-1.8b.gguf --host 0.0.0.0  --port 10868 --max-model-len 4096   --trust-remote-code --tensor-parallel-size 1  --dtype=half --quantization gguf --load-format gguf

![image](https://github.com/user-attachments/assets/99f3e7d2-fd15-4afd-b478-cb3458fd8336)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
By default, vllm will use 90% VRAM for kv cache. You can set --gpu-memory-utilization to a smaller value to reduce VRAM usage (default is 0.9).
