### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by zhangjunyi111** [vllm-project/vllm#798]
**### _(llama) xxx@work-3:~/workspace/LLaMA-Efficient-Tuning-main$ ORCH_CPP_LOG_LEVEL=INFO TORCH_DISTRIBUTED_DEBUG=INFO NCCL_DEBUG=INFO NCCL_SOCKET_IFNAME=eth1  python -m vllm.entrypoints.api_server     --model model/llama-2-70B     --tensor-parallel-size 16 --engine-use-ray  --worker-use-ray_**

2023-08-19 03:54:17,196	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 10.58.226.18:6379...
2023-08-19 03:54:17,202	INFO worker.py:1621 -- Connected to Ray cluster.
INFO:     Started server process [1985409]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
(LLMEngine pid=2347640, ip=10.58.226.15) INFO 08-19 15:49:41 llm_engine.py:70] Initializing an LLM engine with config: model='model/llama-2-70B', tokenizer='model/llama-2-70B', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=16, seed=0)
(LLMEngine pid=2347640, ip=10.58.226.15) INFO 08-19 15:49:41 tokenizer.py:29] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
(LLMEngine pid=2347640, ip=10.58.226.15) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::LLMEngine.__init__() (pid=2347640, ip=10.58.226.15, actor_id=578a6f1533c210d14fcbd9b310000000, repr=<vllm.engine.llm_engine.LLMEngine object at 0x7fa92f210700>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 99, in __init__
(LLMEngine pid=2347640, ip=10.58.226.15)     self._init_workers_ray(placement_group)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
(LLMEngine pid=2347640, ip=10.58.226.15)     self._run_workers(
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
(LLMEngine pid=2347640, ip=10.58.226.15)     all_outputs = ray.get(all_outputs)
(LLMEngine pid=2347640, ip=10.58.226.15) ray.exceptions.RayTaskError(DistBackendError): ray::RayWorker.execute_method() (pid=1985578, ip=10.58.226.18, actor_id=4e1229cbba77c46f4862cf2e10000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7eea07fcaad0>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1682343967769/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Proxy Call to rank 15 failed (Connect)
(LLMEngine pid=2347640, ip=10.58.226.15) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorker.execute_method() (pid=2347719, ip=10.58.226.15, actor_id=bea16230e07fc5730370505b10000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7ef345803520>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Proxy Call to rank 7 failed (Connect)
(LLMEngine pid=2347640, ip=10.58.226.15) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorker.execute_method() (pid=1985577, ip=10.58.226.18, actor_id=47db108bd468171ee4e6e31a10000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f0fdcb92b90>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1682343967769/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Net : Call to recv from 10.58.226.18<49659> failed : Connection refused
(LLMEngine pid=2347640, ip=10.58.226.15) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorker.execute_method() (pid=2347718, ip=10.58.226.15, actor_id=f13b13a684b63106beb58e8510000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f24a49ef490>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Net : Call to recv from 10.58.226.15<32835> failed : Connection refused
(LLMEngine pid=2347640, ip=10.58.226.15) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorker.execute_method() (pid=1985575, ip=10.58.226.18, actor_id=e38afd30c12fa746b2c55fb610000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7ef3f4d86a10>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: /opt/conda/conda-bld/pytorch_1682343967769/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Net : Call to recv from 10.58.226.18<38309> failed : Connection refused
(LLMEngine pid=2347640, ip=10.58.226.15) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorker.execute_method() (pid=2347716, ip=10.58.226.15, actor_id=cb7b77d2ed800d791eecf3d810000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f13f7f0f520>)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 25, in execute_method
(LLMEngine pid=2347640, ip=10.58.226.15)     return executor(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 62, in init_model
(LLMEngine pid=2347640, ip=10.58.226.15)     _init_distributed_environment(self.parallel_config, self.rank,
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
(LLMEngine pid=2347640, ip=10.58.226.15)     torch.distributed.all_reduce(torch.zeros(1).cuda())
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
(LLMEngine pid=2347640, ip=10.58.226.15)     return func(*args, **kwargs)
(LLMEngine pid=2347640, ip=10.58.226.15)   File "/home/huawei/anaconda3/envs/llama/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
(LLMEngine pid=2347640, ip=10.58.226.15)     work = default_pg.allreduce([tensor], opts)
(LLMEngine pid=2347640, ip=10.58.226.15) torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
(LLMEngine pid=2347640, ip=10.58.226.15) ncclInternalError: Internal check failed.
(LLMEngine pid=2347640, ip=10.58.226.15) Last error:
(LLMEngine pid=2347640, ip=10.58.226.15) Net : Call to recv from 10.58.226.15<36285> failed : Connection refused

**Comment by zhangjunyi111** [comment]
can anyone help me?

**Comment by dutsc** [comment]
I also had the same problem when I tried to distribute inference on two machines using the opt-1.3b model.

`root@NSL-1:/workspace/vllm/vllm/entrypoints# python api_server.py --model /workspace/models/opt-1.3b/ --tensor-parallel-size 4
2023-09-07 09:55:12,788	INFO worker.py:1431 -- Connecting to existing Ray cluster at address: 192.168.1.151:6379...
2023-09-07 09:55:12,796	INFO worker.py:1621 -- Connected to Ray cluster.
INFO 09-07 09:55:12 llm_engine.py:70] Initializing an LLM engine with config: model='/workspace/models/opt-1.3b/', tokenizer='/workspace/models/opt-1.3b/', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=4, seed=0)
Traceback (most recent call last):
  File "api_server.py", line 82, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 232, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/async_llm_engine.py", line 55, in __init__
    self.engine = engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 99, in __init__
    self._init_workers_ray(placement_group)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 170, in _init_workers_ray
    self._run_workers(
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 474, in _run_workers
    all_outputs = ray.get(all_outputs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DistBackendError): ray::RayWorker.execute_method() (pid=7209, ip=192.168.1.151, actor_id=1dbee129768ba0c24f751c4102000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7f361ad435b0>)
  File "/usr/local/lib/python3.8/dist-packages/vllm/engine/ray_utils.py", line 25, in execute_method
    return executor(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 62, in init_model
    _init_distributed_environment(self.parallel_config, self.rank,
  File "/usr/local/lib/python3.8/dist-packages/vllm/worker/worker.py", line 329, in _init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Proxy Call to rank 1 failed (Connect)`

But when I use different docker containers on the same machine, it works fine. The bridge mode link is used between the two containers.

**Comment by zhangjunyi111** [comment]
ok, i will try it ,thanks very much

**Comment by acodercat** [comment]
+1
