### ISSUE TITLE
[RFC]: Build `vllm-flash-attn` from source

### ISSUE THREAD

**Issue by ProExpertProg** [vllm-project/vllm#8002]
### Motivation.

To use a custom version of PyTorch in vLLM, `vllm-flash-attn` needs to be built with the same version. The easiest way to achieve that is by building it from source during the vLLM build.

### Proposed Change.

We propose 3 different ways of building `vllm-flash-attn` from source: absorbing the package completely, building it as a CMake dependency, or running a nested `pip install`. Currently, alternative 2 is preferred, but we'd like to get feedback on that. I will update this RFC once we decide on an approach.

More details here: https://docs.google.com/document/d/1njmz8NPT3am5gNcjbjzZG1BN-v8wIxWq6vb5QoctuZ0/edit?usp=sharing

### CC List.

@WoosukKwon @youkaichao @tlrmchlsmth @bnellnm 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
thanks for the great doc! I agree that alternative 2 looks the best.

**Comment by ProExpertProg** [comment]
Okay, proceeding with alternative 2b. Will post a PR here shortly
