### ISSUE TITLE
I think it would be good to have option of both an OpenAI or a HuggingFace style sampler.

### ISSUE THREAD

**Issue by ri938** [vllm-project/vllm#801]
Huggingface sampler is more commonly used.  I think it would be good to be able to swap between them. 

What do people think?

In future I could contribute a PR (not soon though) - if the authors of the library believe this is a good idea.

**Comment by canghongjian** [comment]
Looking forward to the huggingface sampler.

**Comment by mspronesti** [comment]
@ri938 Do you mean something on the lines of [Huggingface's inference API](https://huggingface.co/inference-api)?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
