### ISSUE TITLE
[New Model]: Want to support BAAI/bge-reranker-v2-m3 model

### ISSUE THREAD

**Issue by yinmin2020** [vllm-project/vllm#8022]
### The model to consider.

https://huggingface.co/BAAI/bge-reranker-v2-m3

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by alew3** [comment]
Tried this model and it seems to be working: BAAI/bge-reranker-v2-m3
