### ISSUE TITLE
[Bug]: I get one word inconsistent responses using the v0.5.4 with LL

### ISSUE THREAD

**Issue by Mikehade** [vllm-project/vllm#8027]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

I deployed the vllm server using below

```
model_dir = _model_file 
APP_PORT = os.getenv("APP_PORT", "8002")

command = [
    '/opt/venv/bin/python3', '-m', 'vllm.entrypoints.openai.api_server',
    '--model', model_dir,
    '--host', '0.0.0.0',
    '--port', APP_PORT,
    '--gpu-memory-utilization', '0.75',
    '--max-model-len', '4096',
    '--max-num-seqs', '512',
    '--served-model-name', model_name,
    '--chat-template', '/app/artifacts/llama_template.jinja'
]

subprocess.run(command)

```

and used a class to call the API for both client.completion.create and client.chat.completion.create in which I get one word and garbage responses such as "success", "okay", "2110" and so on.

```
prompts = [
            "\n{system_message}</s>\n{prompt}</s>\n\n".format(system_message=PROMPT, prompt=text)
        ]
request = {"model_name": "Meta-Llama-3-8B-Instruct",
                "prompt": prompts,
                "max_tokens": 3072,
                "temperature": 0.8,
                "grammar": grammar
                }
res = VllmClient().open_ai_vllm(request)
res.choices[0].text

```

with below result, I get coherent responses sometimes though
{"result": "2100.0"}

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zarttech-mike** [comment]
The model is Meta Llama 3 8B

**Comment by Mikehade** [comment]
The model is Meta Llama 3 8B
