### ISSUE TITLE
[Installation]: LGPL license in dependencies

### ISSUE THREAD

**Issue by laurens-gs** [vllm-project/vllm#8030]
### Your current environment

Since vLLM 0.5.5 there is a [dependency](https://github.com/vllm-project/vllm/blob/2148441fd371faf3e90748b310fdb4500939e527/requirements-common.txt#L25C12-L25C13) on Librosa, which in turn [depends](https://github.com/librosa/librosa/blob/main/setup.cfg#L74) on soxr. Soxr is LGPL licensed which is a big red flag for many corporations. I'm not a legal expert but I do understand that LGPL is more permissive than regular GPL or AGPL. However many large firms still consider it too risky and block any LGPL license by default and as a result I am now no longer able to install vLLM in my firm (Fortune 50 size).

I would kindly request to reconsider the use of Librosa.

**Comment by mgoin** [comment]
Perhaps we could move audio support to an "extra" dependency and instruct users to install using `pip install vllm[audio]` for that functionality, like the similar `transformers[audio]` extra

**Comment by DarkLight1337** [comment]
I didn't consider licensing issues before, this is definitely a valid concern! @mgoin's solution sounds good to me.

cc @petersalas

**Comment by robertgshaw2-neuralmagic** [comment]
The optional dependency makes sense to me. I also filed an issue in `librosa` to see if they can remove `soxr`.

**Comment by petersalas** [comment]
FWIW I suspect we could also replace the usage of librosa with soundfile. I think there's one place in Ultravox we use librosa for resampling if necessary but we could make that conditional on librosa being present and/or fail if the sample rate is wrong.

**Comment by robertgshaw2-neuralmagic** [comment]
> FWIW I suspect we could also replace the usage of librosa with soundfile. I think there's one place in Ultravox we use librosa for resampling if necessary but we could make that conditional on librosa being present and/or fail if the sample rate is wrong.

I think we should address this ASAP

**Comment by ywang96** [comment]
@laurens-gs we have made `librosa` an optional dependency of vLLM. Let us know if you have any other concern.

**Comment by laurens-gs** [comment]
> @laurens-gs we have made `librosa` an optional dependency of vLLM. Let us know if you have any other concern.

This solution works great for me! Cannot test it until it hits PyPi, but I do not expect issues.

**Comment by youkaichao** [comment]
@laurens-gs you can test with the per-commit wheel. see https://docs.vllm.ai/en/latest/getting_started/installation.html : 

> vLLM also publishes a subset of wheels (Python 3.10, 3.11 with CUDA 12) for every commit since v0.5.3. You can download them with the following command:
