### ISSUE TITLE
[Feature]: Contribute T5 model to vLLM

### ISSUE THREAD

**Issue by shivance** [vllm-project/vllm#8036]
### 🚀 The feature, motivation and pitch

Hi vLLM team,
As you already know, T5 is a perfect model and as mentioned in #7366, the project intends to add support for T5. I want to help the cause and contribute T5 to the project.

As this is my first contribution to vLLM project I am quite pumped up as well as eager to learn from you all.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by robertgshaw2-neuralmagic** [comment]
@shivance the key blocker is an implementation of 

See: https://github.com/vllm-project/vllm/issues/7366 for a detailed discussion of enc-dec support. We would definitely welcome help on T5. For T5, the key is that we need an attention implementation with the custom bias
- https://github.com/vllm-project/vllm/issues/7366#user-content-add-t5-model
