### ISSUE TITLE
[Feature]: Beam Search with Temperature > 0

### ISSUE THREAD

**Issue by ekurtulus** [vllm-project/vllm#8067]
### 🚀 The feature, motivation and pitch

Huggingface generation interface allows beam search with nonzero temperature, allowing to generate more diverse beam search. The current version with zero temperature does not allow that flexibility.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
is it still beam **search** then?

**Comment by ekurtulus** [comment]
Conceptually, yes. Even if we assume that it isn't, it is useful to generate more diverse responses.

**Comment by youkaichao** [comment]
added in https://github.com/vllm-project/vllm/pull/8928
