### ISSUE TITLE
[Usage]: Does VLLM support starting multiple cards using mpirun? Want to bind different CPUs to each card.

### ISSUE THREAD

**Issue by xiabo123** [vllm-project/vllm#8069]
### Your current environment

Does VLLM support starting multiple cards using mpirun? Want to bind different CPUs to each card.
When testing performance, use mpirun to bind different CPUs to different cards.

### How would you like to use vllm

Does VLLM support starting multiple cards using mpirun? Want to bind different CPUs to each card.
When testing performance, use mpirun to bind different CPUs to different cards.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
vllm does not support mpirun. please check out https://docs.vllm.ai/en/latest/serving/distributed_serving.html for how to use multiple gpus.
