### ISSUE TITLE
Add smoothquant support 

### ISSUE THREAD

**Issue by ehartford** [vllm-project/vllm#8072]
### 🚀 The feature, motivation and pitch

This is smoothquant:
https://github.com/mit-han-lab/smoothquant

It's awesome.

It's been added in Aphrodite here:
https://github.com/PygmalionAI/aphrodite-engine/pull/294

I would like to request smoothquant in vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Eviannn** [comment]
hi, maybe u can refer to https://github.com/vllm-project/llm-compressor?tab=readme-ov-file

**Comment by robertgshaw2-neuralmagic** [comment]
This example shows how to make models using SmoothQuant:
- https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_w8a8_int8

**Comment by ehartford** [comment]
Ok thank you
