### ISSUE TITLE
Qwen-7B, set max_num_batched_tokens=4096, then output role is null and content is empty string

### ISSUE THREAD

**Issue by LouisHeck** [vllm-project/vllm#809]
Qwen-7B,  which  "max_position_embeddings": 8192.

When I set max_num_batched_tokens=4096, then it outputs role is null and content is empty:

```
Message received 0.11 seconds after request: {
  "role": "assistant"
}
Message received 0.59 seconds after request: {
  "role": null,
  "content": ""
}
Message received 0.59 seconds after request: {
  "role": null,
  "content": ""
}
Full response received 0.59 seconds after request
Full conversation received: 

Process finished with exit code 0
```

when I cut prompt text shorter( less than 2560), it runs ok.

But Qwen-7B, it support longer prompt, up to 8K. now it can only use 2560(max_num_batched_tokens value), when set bigger value than 2560, and send token than 2560 it return error result.

**Comment by EricLingRui** [comment]
Some long text inference techniques have not yet been implemented in this framework，like ntk-aware.
https://github.com/vllm-project/vllm/issues/479
https://github.com/vllm-project/vllm/issues/244

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
