### ISSUE TITLE
[Bug]: Unable to serve minicpm-v2.6 with GGUF quantization

### ISSUE THREAD

**Issue by Sakura4036** [vllm-project/vllm#8096]
### Your current environment

<details>
<summary>The output of `vllm                              0.5.5
vllm-flash-attn                   2.6.1`</summary>

```text
Your output of `python collect_env.py` here
```
download vllm by `pip install vllm` in conda env
</details>

### 🐛 Describe the bug

deploy  minicpm-v-2.6model which download from [openbmb/MiniCPM-V-2_6-gguf](https://huggingface.co/openbmb/MiniCPM-V-2_6-gguf) by `vllm serve`
```
vllm serve  models/minicpm/ggml-model-Q5_K_M.gguf --quantization gguf --kv-cache-dtype auto
```
get `AssertionError` in `weight_loader`:
```
File "/home/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1038, in load_model
    model.load_weights(
  File "/home/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 437, in load_weights
    weight_loader(param, loaded_weight)
  File "/home/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 375, in weight_loader
    assert loaded_weight.shape[output_dim] == self.org_vocab_size
AssertionError
ERROR 09-03 11:29:27 api_server.py:171] RPCServer process died before responding to readiness probe
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
You can check this https://github.com/vllm-project/vllm/issues/7689#issuecomment-2298656805 for information to solve this error, if you just want to serve the backbone without mmproj.

BTW, the GGUF quantization hasn't supported VLM yet, because:
1. The `transformers` intergration only supports extracting `config` and `tokenizer` for `Llama` and `qwen2` backbone. It hasn't supported ViT yet.
2. VLM in GGUF format consists of two shard parts: `ggml-model` and `mmproj-model`, and we only support loading from single GGUF file currently.

**Comment by Sakura4036** [comment]
OK， thanks， i will give it a try: use offical [minicpm-v-2.6 int4 model](https://huggingface.co/openbmb/MiniCPM-V-2_6-int4)

**Comment by Sakura4036** [comment]
> OK， thanks， i will give it a try: use offical [minicpm-v-2.6 int4 model](https://huggingface.co/openbmb/MiniCPM-V-2_6-int4)

failed：
```
KeyError: 'llm.layers.0.mlp.down_proj.weight'
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

ERROR 09-03 16:33:17 api_server.py:171] RPCServer process died before responding to readiness probe

```

**Comment by Sakura4036** [comment]
run by following command, still got `OOM` on **4090**:
```
vllm serve openbmb/MiniCPM-V-2_6 --dtype bfloat16  --kv-cache-dtype auto --trust-remote-code --host 0.0.0.0  --port 8002 --tensor-parallel-size 1 --max_num_seqs 32 --max_model_len 2048
```

**Comment by Isotr0py** [comment]
You can reduce `--max_num_seqs 32` to `--max_num_seqs 1` for VRAM usage reduction.

**Comment by Sakura4036** [comment]
> You can reduce `--max_num_seqs 32` to `--max_num_seqs 1` for VRAM usage reduction.

thanks. it works, and GPU memory usage 23GB：
```
vllm serve openbmb/MiniCPM-V-2_6 --dtype bfloat16  --kv-cache-dtype auto --trust-remote-code --tensor-parallel-size 1 --max_num_seqs 1 --max_model_len 2048 --gpu_memory_utilization 0.9
```
