### ISSUE TITLE
Check failed: unit == "kB"

### ISSUE THREAD

**Issue by weishengying** [vllm-project/vllm#810]
when I use vllm to deploy gpt2 model, I got this error:

![wx6U6CVhv1](https://github.com/vllm-project/vllm/assets/63448337/ed21e328-fac8-41e8-81de-485531f7a7f0)

what does this mean?

**Comment by WoosukKwon** [comment]
Hi @weishengying, thanks for trying out vLLM. That is a new error we haven't seen. Could you provide a reproducible script?

**Comment by leofansq** [comment]
@weishengying I got this error too. Do you find any solution?
