### ISSUE TITLE
[Feature]:  Support for quantization

### ISSUE THREAD

**Issue by CREVIOS** [vllm-project/vllm#8127]
### 🚀 The feature, motivation and pitch

I propose implementing int8 quantization support for vLLM, focusing initially on the KV cache. This feature will allow users to run larger models or increase batch sizes without additional hardware investment. It's precious for services with high throughput requirements or deployments on edge devices.

Key benefits:

* Up to 4x reduction in memory usage for quantized components
* Potential speedup on hardware with efficient int8 support
* Broader hardware compatibility, including edge devices
* Reduced operational costs for large-scale deployments

Implementation will involve:

* Adding quantized CUDA kernels
* Modifying the Python interface for quantization options
* Updating model loading to support quantized weights
* Adding benchmarks to compare performance
* Documenting the new feature

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
FYI: https://docs.vllm.ai/en/latest/quantization/supported_hardware.html

**Comment by arunpatala** [comment]
Is running the model using int8 w8a8 mode, also quantizes the KV cache? or we have to enable it separately?

**Comment by DarkLight1337** [comment]
@mgoin can you help answer this?
