### ISSUE TITLE
Stream Tokens operation integration into LLM class (which uses LLMEngine behind the scenes)

### ISSUE THREAD

**Issue by orellavie1212** [vllm-project/vllm#813]
Hey,
I wonder why the token streaming via LLM class is not implemented, but for LLMEngine it does?
https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/llm.py
LLM is using behind the scene the LLMEngine. LLM class is much simpler (to me I guess, not sure if to everyone else) and also utilize batch processing on top (on top  LLMEngine) of tensor parallel, so it would be nice to get also a stream with batch process together if possible, or either of them. It shouldn't be much work to do as I read the code and after I talked with @naed90 about that feature.
Thanks, Orel

**Comment by naed90** [comment]
@WoosukKwon thoughts?

**Comment by WoosukKwon** [comment]
Hi @orellavie1212, could you elaborate more on your use case? If you run offline batched inference with `LLM`, streaming the output tokens would not make sense. If you run online serving, you would need asynchronous request handling, which is supported by `AsyncLLMEngine`. To my understanding, it's difficult to find when users would want to use offline inference and token streaming at the same time.

**Comment by orel1212** [comment]
Sure @WoosukKwon, I don't want to handle two different instances of objects to handle both batch process offline  (LLM) and other object (Async Engine) for online stream. It is more important if I have cluster of gpus I want to utilize for tensor sharding, while also being able to use one of the gpus for stream for online users. I wonder if it just to take the vase LLMEngine inside LLM class and instantiate with that base objsct the Async, and it would work for both? I am afraid of tensor mismatches in the online stream.

**Comment by lzy37ld** [comment]
Hi i wonder if it's possible to do online batch inference? @WoosukKwon

**Comment by orel1212** [comment]
I am still waiting for that, still no idea when

**Comment by vishal09vns** [comment]
Hi ,
`AsyncLLMEngine.generate` is not producing the output in streaming way as done with transformer's `model.generate`. On use "AsyncLLMEngine.generate" the arrival of first token is taking so much time after that all tokens are coming very fast. Can anyone explain why is this happening.

**Comment by DenisDiachkov** [comment]
Does anyone have updates on this?

**Comment by hmellor** [comment]
> NOTE: This class is intended to be used for offline inference. For online serving, use the AsyncLLMEngine class instead. NOTE: For the comprehensive list of arguments, see EngineArgs.

From https://docs.vllm.ai/en/latest/offline_inference/llm.html

**Comment by DenisDiachkov** [comment]
@hmellor thanks! is there any example on how to run this AsyncLLMEngine? I don't see clear docs or examples.
I checked this https://docs.vllm.ai/en/v0.3.0/dev/engine/async_llm_engine.html but I don't see where I pass model_name, etc.

**Comment by hmellor** [comment]
I'd recommend looking at the latest version of the documentation, it's come a long way since v0.3.0

There is an example of the synchronous version of `LLMEngine` here https://docs.vllm.ai/en/latest/getting_started/examples/llm_engine_example.html

The `AsyncLLMEngin`e is a wrapper around `LLMEngine`, so I'd recommend reading the documentation for both, which can be found here https://docs.vllm.ai/en/latest/dev/engine/engine_index.html
