### ISSUE TITLE
[Usage]: 125m parameter model is also showing CUDA: Out of memory error in a Nvidia16GB 4060 

### ISSUE THREAD

**Issue by shubh9m** [vllm-project/vllm#8136]
### How would you like to use vllm

Even for a smaller model like "facebook/opt-125m" when I am trying to do multiprocessing(even with batch size of 2) on a single 16GB Nvidia 4060, I am encountering CUDA: OUT OF MEMORY ERROR. When I am running the same model sequentially, I am able to run it fine. Can you explain this?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
You can try reducing `gpu_memory_utilization`

**Comment by shubh9m** [comment]
I have tried that. The sequential code is taking 0.3 GB only. With multiprocessing and batch size of only 2, it is taking more than 16 GB. That's the part I am unable to understand.

**Comment by DarkLight1337** [comment]
Make sure the GPU is not being used by another process.

**Comment by shubh9m** [comment]
It is completely free.

**Comment by DarkLight1337** [comment]
Can you show the code that you use to perform multiprocessing?

**Comment by shubh9m** [comment]
Sure, here is the code:
`# Function to initialize the LLM in each process
def init_llm():
    return LLM(model="distilgpt2", enforce_eager=True, gpu_memory_utilization=0.99)

# Define LLMPredictor class
class LLMPredictor:
    def __init__(self, llm):
        self.llm = llm

    def predict(self, texts: List[str]) -> List[Dict[str, str]]:
        sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
        outputs = self.llm.generate(texts, sampling_params)
        results = []
        for output in outputs:
            result = {
                "prompt": output.prompt,
                "generated_text": ' '.join([o.text for o in output.outputs])
            }
            results.append(result)
        return results

# Function to process a batch of texts
def process_batch(batch: List[str]) -> List[Dict[str, str]]:
    llm = init_llm()  # Initialize LLM in each process
    predictor = LLMPredictor(llm)
    return predictor.predict(batch)

# Read the text file
def read_text_file(file_path: str) -> List[str]:
    with open(file_path, 'r') as file:
        lines = file.readlines()
    return [line.strip() for line in lines][:30]

# Load your text file
texts = read_text_file('/home/debian/Shubham/prompt300.txt')  # Modify to your text file path

# Split data into batches
batch_size = 1
batches = [texts[i:i + batch_size] for i in range(0, len(texts), batch_size)]

# Perform distributed inference using ProcessPoolExecutor
if __name__ == '__main__':
    with multiprocessing.Pool() as pool:
        results = pool.map(process_batch, batches)

    # Flatten the list of results
    flat_results = [item for sublist in results for item in sublist]

    # Print results
    # for result in flat_results:
    #     print(f"Prompt: {result['prompt']}")
    #     print(f"Generated Text: {result['generated_text']}")
    #     print("="*50)  # Separator for readability`

**Comment by DarkLight1337** [comment]
How many processes are being created in this way? Since the processes are not managed by vLLM, each process will allocate the GPU separately.

**Comment by shubh9m** [comment]
I have tried limiting the number of processes to 2, and also gpu_memory_utillization to 0.4, but now the error is: 

> No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

**Comment by DarkLight1337** [comment]
Just to make sure, can you run this with number of processes = 1 using the same code?

**Comment by shubh9m** [comment]
Yep, it is working when I set it to 1.

**Comment by DarkLight1337** [comment]
@youkaichao imo this is somewhat unconventional usage but can you take a look at this?

**Comment by youkaichao** [comment]
this is not the recommended usage. creating LLM instance in every process is error-prone.

I would suggest just spin up an openai api server, and just use web request to get the result.

**Comment by shubh9m** [comment]
Is there any way other than using openai api server or is it possible to have a single LLM instance for multiple processes?

**Comment by youkaichao** [comment]
why not openai api server?
