### ISSUE TITLE
[New Model]: Qwen2-VL

### ISSUE THREAD

**Issue by krevas** [vllm-project/vllm#8139]
### The model to consider.

https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct

### The closest model vllm already supports.

https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/qwen2.py

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
It will be released once transformers support it.

**Comment by devonthomas35** [comment]
@DarkLight1337 it is supported in transformers: https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/qwen2_vl.md#qwen2_vl

**Comment by DarkLight1337** [comment]
I mean we need to wait until they release a new version with the change. It is not in v4.44.2.

**Comment by Andcircle** [comment]
@DarkLight1337 
I saw a demo for qwen2-vl like:
```# Inference with image embeddings as input with additional parameters
# Specifically, we are conducting a trial run of Qwen2VL with the new input format, as the model utilizes additional parameters for calculating positional encoding.
image_embeds = torch.load(...) # torch.Tensor of shape (1, image_feature_size, hidden_size of LM)
image_grid_thw = torch.load(...) # torch.Tensor of shape (1, 3)
mm_data['image'] = {
    "image_embeds": image_embeds,
    "image_grid_thw":  image_grid_thw,
}
outputs = llm.generate({
    "prompt": prompt,
    "multi_modal_data": mm_data,
})```
but where should I get the image_embeds dynamically? 

Thanks for help

**Comment by DarkLight1337** [comment]
> @DarkLight1337 I saw a demo for qwen2-vl like:
> 
> ```
> # Specifically, we are conducting a trial run of Qwen2VL with the new input format, as the model utilizes additional parameters for calculating positional encoding.
> image_embeds = torch.load(...) # torch.Tensor of shape (1, image_feature_size, hidden_size of LM)
> image_grid_thw = torch.load(...) # torch.Tensor of shape (1, 3)
> mm_data['image'] = {
>     "image_embeds": image_embeds,
>     "image_grid_thw":  image_grid_thw,
> }
> outputs = llm.generate({
>     "prompt": prompt,
>     "multi_modal_data": mm_data,
> })
> ```
> 
> but where should I get the image_embeds dynamically?
> 
> Thanks for help

This code is designed for precomputed embedding inputs. You can get the embeddings by running just the Qwen2-VL visual encoder + projection on the inputs (outside of vLLM) to get the embeddings of each visual token. It can speed up inference when you have a mechanism to cache the embeddings of particular input images/videos. Most users won't be using this though.

**Comment by Andcircle** [comment]
> > @DarkLight1337 I saw a demo for qwen2-vl like:
> > ```
> > # Specifically, we are conducting a trial run of Qwen2VL with the new input format, as the model utilizes additional parameters for calculating positional encoding.
> > image_embeds = torch.load(...) # torch.Tensor of shape (1, image_feature_size, hidden_size of LM)
> > image_grid_thw = torch.load(...) # torch.Tensor of shape (1, 3)
> > mm_data['image'] = {
> >     "image_embeds": image_embeds,
> >     "image_grid_thw":  image_grid_thw,
> > }
> > outputs = llm.generate({
> >     "prompt": prompt,
> >     "multi_modal_data": mm_data,
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but where should I get the image_embeds dynamically?
> > Thanks for help
> 
> This code is designed for precomputed embedding inputs. You can get the embeddings by running just the Qwen2-VL visual encoder + projection on images/videos (outside of vLLM) to get their visual token embeddings. If you have a mechanism to cache the embeddings of particular input images/videos, this can speed up inference as you don't need to run the visual encoder again. Most users won't be using this though.

Thanks for the detailed explanation

**Comment by yonghenglh6** [comment]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 134, in from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 874, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 811, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/config.py", line 207, in __init__
    self.max_model_len = _get_and_verify_max_len(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/config.py", line 1746, in _get_and_verify_max_len
    assert "factor" in rope_scaling
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by DarkLight1337** [comment]
> Process SpawnProcess-1: Traceback (most recent call last): File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine engine = MQLLMEngine.from_engine_args(engine_args=engine_args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/multiprocessing/engine.py", line 134, in from_engine_args engine_config = engine_args.create_engine_config() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 874, in create_engine_config model_config = self.create_model_config() ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 811, in create_model_config return ModelConfig( ^^^^^^^^^^^^ File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/config.py", line 207, in **init** self.max_model_len = _get_and_verify_max_len( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/fangzhou/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/config.py", line 1746, in _get_and_verify_max_len assert "factor" in rope_scaling ^^^^^^^^^^^^^^^^^^^^^^^^ AssertionError

Please install vLLM from source as mentioned in #7905.

**Comment by marathon110** [comment]
> /config.py", line 1746, in _get_and_verify_max_len assert "factor" in rope_scaling ^^^^^^^^^^^^^^^^^^^^^^

<img width="846" alt="image" src="https://github.com/user-attachments/assets/97b00589-45c6-4061-a272-a401de2ba082">
Using the source code branch is:https://github.com/fyabc/vllm/tree/add_qwen2_vl_new

The loading model is:Qwen/Qwen2-VL-7B-Instruct

There is still an error:
vllm-1     |   File "/workspace/vllm/entrypoints/openai/api_server.py", line 132, in build_async_engine_client_from_engine_args
vllm-1     |     if (model_is_embedding(engine_args.model, engine_args.trust_remote_code,
vllm-1     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1     |   File "/workspace/vllm/entrypoints/openai/api_server.py", line 73, in model_is_embedding
vllm-1     |     return ModelConfig(model=model_name,
vllm-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1     |   File "/workspace/vllm/config.py", line 227, in __init__
vllm-1     |     self.max_model_len = _get_and_verify_max_len(
vllm-1     |                          ^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1     |   File "/workspace/vllm/config.py", line 1739, in _get_and_verify_max_len
vllm-1     |     assert "factor" in rope_scaling
vllm-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^
vllm-1     | AssertionError

**Comment by DarkLight1337** [comment]
> > /config.py", line 1746, in _get_and_verify_max_len assert "factor" in rope_scaling ^^^^^^^^^^^^^^^^^^^^^^
> 
> <img alt="image" width="846" src="https://private-user-images.githubusercontent.com/13222550/378717201-97b00589-45c6-4061-a272-a401de2ba082.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODA5MDEsIm5iZiI6MTcyOTU4MDYwMSwicGF0aCI6Ii8xMzIyMjU1MC8zNzg3MTcyMDEtOTdiMDA1ODktNDVjNi00MDYxLWEyNzItYTQwMWRlMmJhMDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA3MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDc0NmVkNDJiMTNjMGI0NGZlYzk5ZTg2NTM4YjA4NDAzYTRjMWNhODQzMGVjYmY1ZGExMWU4YzAzN2IzZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JdO5JJF7bHdpWnn_crIlysbj7lQ-t4rrHuhsX0Xx0Ug"> Using the source code branch is:https://github.com/fyabc/vllm/tree/add_qwen2_vl_new
> The loading model is:Qwen/Qwen2-VL-7B-Instruct
> 
> There is still an error: vllm-1 | File "/workspace/vllm/entrypoints/openai/api_server.py", line 132, in build_async_engine_client_from_engine_args vllm-1 | if (model_is_embedding(engine_args.model, engine_args.trust_remote_code, vllm-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ vllm-1 | File "/workspace/vllm/entrypoints/openai/api_server.py", line 73, in model_is_embedding vllm-1 | return ModelConfig(model=model_name, vllm-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ vllm-1 | File "/workspace/vllm/config.py", line 227, in **init** vllm-1 | self.max_model_len = _get_and_verify_max_len( vllm-1 | ^^^^^^^^^^^^^^^^^^^^^^^^ vllm-1 | File "/workspace/vllm/config.py", line 1739, in _get_and_verify_max_len vllm-1 | assert "factor" in rope_scaling vllm-1 | ^^^^^^^^^^^^^^^^^^^^^^^^ vllm-1 | AssertionError

Please use the latest version of vLLM. It supports Qwen2-VL without this error.

**Comment by umie0128** [comment]
@DarkLight1337 
我用一张高速公路抓拍图片测试 提问是：详细描述图片提供的信息 模型的输出会出现明显的截断，请问怎么处理

**Comment by DarkLight1337** [comment]
> @DarkLight1337 我用一张高速公路抓拍图片测试 提问是：详细描述图片提供的信息 模型的输出会出现明显的截断，请问怎么处理

You may increase `max_model_len` to increase the context length of the model.

**Comment by siddarthreddygsr** [comment]
I am facing the same issue. vllm==0.8.1 and transformers==4.51.3 also tried transformers=='4.52.0.dev0' and i am getting assert "factor" in rope_scaling
^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by DarkLight1337** [comment]
> I am facing the same issue. vllm==0.8.1 and transformers==4.51.3 also tried transformers=='4.52.0.dev0' and i am getting assert "factor" in rope_scaling ^^^^^^^^^^^^^^^^^^^^^^^^ AssertionError

Please try to re-download the Qwen2-VL model repo

**Comment by siddarthreddygsr** [comment]
I deployed it with 
```bash
docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 --ipc=host vllm/vllm-openai:latest --model Qwen/Qwen2-VL-7B-Instruct  --max-model-len 8192 --gpu-memory-utilization 0.99
```
and it is working perfectly
