### ISSUE TITLE
compared with fasttransformer?

### ISSUE THREAD

**Issue by moseshu** [vllm-project/vllm#814]
how much of a speed increase compared to fasttransformer?

**Comment by sleepwalker2017** [comment]
I'm benchmarking vllm and find it not that fast, compared to FT, it's slower for offline inference.
All codes are in python, so the GPU util is not 100%, for 2-gpu case, usually 60-80%. That's a waste.

The advantage may be the continuous batching feature, if you can tolerate a larger latency for each request. I'm still testing the throughput.

**Comment by moseshu** [comment]
> I'm benchmarking vllm and find it not that fast, compared to FT, it's slower for offline inference. All codes are in python, so the GPU util is not 100%, for 2-gpu case, usually 60-80%. That's a waste.
> 
> The advantage may be the continuous batching feature, if you can tolerate a larger latency for each request. I'm still testing the throughput.
this is my test result on fast transformer 
![img_v2_ed451f01-569b-4312-899e-d9a5cc4031fg](https://github.com/vllm-project/vllm/assets/23112888/53383dd3-0e6d-4c00-960c-03ad120c63d8)

this is VLLM test result 
![img_v2_ec5b76f9-cce2-4773-8023-28878687c74g](https://github.com/vllm-project/vllm/assets/23112888/845bd3c5-894a-4295-90e4-afce728c00d6)

the VLLM is not faster than FT. The  throughput  is lower than FT
