### ISSUE TITLE
[Feature]: Supporting MultiModal inputs using Llama3.1

### ISSUE THREAD

**Issue by daichi-m** [vllm-project/vllm#8146]
### 🚀 The feature, motivation and pitch

We have a deployment of Llama3.1-8B-Instruct and Llama3.1-70B-Instruct models through vLLM hosted in our OnPremise GPU infra.

While testing different use-cases, we realized that the current version of vLLM does not support MultiModal input for Llama3.1 as per this document: https://docs.vllm.ai/en/latest/models/supported_models.html#supported-vlms

Is it possible to enable llama3.1 as a VLM? Or if it can be enabled through any different route, is there any documentation or guide around it?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
See https://github.com/vllm-project/vllm/issues/7503#issuecomment-2287867938

**Comment by DarkLight1337** [comment]
cc @ywang96

**Comment by DarkLight1337** [comment]
Closing as completed by #8811
