### ISSUE TITLE
[Usage]: How to use vllm infer video with Internvl2 8b multimodal model 

### ISSUE THREAD

**Issue by PancakeAwesome** [vllm-project/vllm#8151]
### Your current environment

python==3.8
vllm==0.5.4
transformers==4.44.0
torch==2.4.0

### How would you like to use vllm

I want to run inference of a [Internvl2 8b](https://huggingface.co/OpenGVLab/InternVL2-8B) with video source. I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
It's not supported yet, but will be soon! See https://github.com/vllm-project/vllm/pull/6514#issuecomment-2328535852

**Comment by sayakpaul** [comment]
In general, it might be nice to have a snippet showing how to infer with a model (supporting videos) on an input video.

**Comment by DarkLight1337** [comment]
InternVL2 now supports multi-image input. As is the case with the HF repo, for video input you should first convert it into a sequence of image frames. You can check out the examples in [this script](https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_vision_language_multi_image.py).
