### ISSUE TITLE
[Misc]: Use of response_format and guided output in LLMEngine and AsyncLLMEngine

### ISSUE THREAD

**Issue by ingambe** [vllm-project/vllm#8156]
### Anything you want to discuss about vllm.

Documentation detail how to use guided output with the OpenAI compatible completion API: [AsyncLLMEngine](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-completions-api) namely `response_format`and `guided_json`.
But I cannot find how to do the same using LLMEngine or AsyncLLMEngine. Is it supported? If so can we have some documentation about it?
Thanks 🙂

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You can use the `guided_options_request` parameter to `LLM.generate`.
