### ISSUE TITLE
Regression in vllm outputs for starcoder family

### ISSUE THREAD

**Issue by Naman-ntc** [vllm-project/vllm#819]
Outputs from Starcoder regressed significantly in the bleeding edge main branch. https://github.com/vllm-project/vllm/commit/6fc2a38b110f9ba6037b31ee016f20df32426877 commit was working fine

**Comment by WoosukKwon** [comment]
Hi @Naman-ntc, thanks for reporting the issue. Could you share the exact names of the models and the sampling parameters you used with the models?

**Comment by Naman-ntc** [comment]
Hi, 
Sorry, here is my config.

* I had a local `bigcode/gpt_bigcode-santacoder` fine-tuned model (which is of `GPTBigCodeModel` family). 
* I am sampling using (top-p sampling, multiple completions)

```python
sampling_params = SamplingParams(
            n=100,
            temperature=0.9,
            top_p=0.95,
            top_k=-1,
            max_tokens=2000,
            stop=["QUESTION"],
)
```

**Comment by WoosukKwon** [comment]
@Naman-ntc Thanks for sharing it! To my understanding, the bug was introduced in #753 and is fixed in #858. Could you try out the `multinomial` branch of the repo?

**Comment by Naman-ntc** [comment]
Oh wow, thanks for the quick fix. I'll test it out!

**Comment by Naman-ntc** [comment]
Sorry, I finally tried it and seems to be working now. Thanks!
