### ISSUE TITLE
[Feature]: Supporting Guided Decoding via AsyncLLMEngine

### ISSUE THREAD

**Issue by DhruvaBansal00** [vllm-project/vllm#8218]
### 🚀 The feature, motivation and pitch

Today, Guided Decoding can only be accessed if we use the OpenAI compatible API interface, since that is the only way of passing in a `GuidedDecodingRequest` object into the generation query.

It should theoretically also be possible to support this via the AsyncLLMEngine.generate() interface. Anything blocking from supporting this today? I don't see it being possible to pass in a `GuidedDecodingRequest` into the generate method today.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by njhill** [comment]
@joerunde

**Comment by joerunde** [comment]
@DhruvaBansal00 mind taking a look at https://github.com/vllm-project/vllm/pull/8252/files#r1747793503?
