### ISSUE TITLE
 Why the vllm loading model has a large memory footprint

### ISSUE THREAD

**Issue by Zhang-star-master** [vllm-project/vllm#822]
The normal loading of the baichuan-13b takes up about 25G of GPU, and the loading of vllm takes up 35G of GPU

**Comment by sleepwalker2017** [comment]
Because the vllm  pre-allocate 90%(by default) of all your GPU memory to generate large kv cache blocks.

**Comment by Zhang-star-master** [comment]
thanks   very  much

**Comment by hmellor** [comment]
Closing as this appears to be resolved.
