### ISSUE TITLE
GPU memory requirement very high + tensor parallelization acts weird

### ISSUE THREAD

**Issue by krishanu-deloitte** [vllm-project/vllm#823]
I am using a system with 2 A100 GPUs to run Llama2-13b chat model on vLLMs.
If I use tensor_parallel_size = 2, then the model takes up to 38GB on each GPU -- total 76GB.
If I use tensor_parallel_size = 1, then the model takes up to 38GB on just one GPU.

If I use huggingface pipeline, then the model in total takes around 26GB.

Can anyone explain the reason for this discrepancy

**Comment by FaraneJalaliFarahani** [comment]
Can you share the code snippet here? For the vLLMs multi-gpu.

**Comment by thinline72** [comment]
#550 thread has an answer to that. By default, vLLM allocate 90% of GPU memory for model inference and kv_cache blocks.

You can restrict the gpu usage with the gpu_memory_utilization, https://github.com/vllm-project/vllm/blob/main/vllm/engine/arg_utils.py#L27

This discussion might be helpful too: https://github.com/vllm-project/vllm/discussions/241

**Comment by yanmengxiang1** [comment]
@thinline72 hello,Do you have some ideas in #930,thanks!

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
