### ISSUE TITLE
[New Model]: when support MiniCPM3ForCausalLM  MiniCPM3-4B model

### ISSUE THREAD

**Issue by ML-GCN** [vllm-project/vllm#8232]
### The model to consider.

https://huggingface.co/openbmb/MiniCPM3-4B

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
The model will be added to vLLM very soon!

**Comment by Mencuis** [comment]
When deploying MiniCPM3-4B using vllm, the inference speed is much slower than models of the same size, such as Qwen1.5-4B. Can you check this?

**Comment by DarkLight1337** [comment]
Can you run the HuggingFace implementation of those models and see if you observe the same differences?

**Comment by DarkLight1337** [comment]
It's difficult to narrow down the issue without providing more information.

**Comment by Mencuis** [comment]
> Can you run the HuggingFace implementation of those models and see if you observe the same differences?

huggingface implementation on A800 without flash attention
new tokens 128
inference time
- MiniCPM3-4B   11.6 s
- Qwen1.5-4B  6.3 s

It seems that minicpm3 is indeed much slower
