### ISSUE TITLE
[Bug]: Missing TextTokenPrompts class

### ISSUE THREAD

**Issue by shubh9m** [vllm-project/vllm#8235]
### 🐛 Describe the bug

I tried to pull a vllm docker image and run it on my 4060 GPU bit I am encountering this error:
File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/vllm/lib64/python3.11/site-packages/vllm_tgis_adapter/__main__.py", line 43, in <module>
    from .grpc import run_grpc_server
  File "/opt/vllm/lib64/python3.11/site-packages/vllm_tgis_adapter/grpc/__init__.py", line 1, in <module>
    from .grpc_server import run_grpc_server
  File "/opt/vllm/lib64/python3.11/site-packages/vllm_tgis_adapter/grpc/grpc_server.py", line 23, in <module>
    from vllm.inputs import TextTokensPrompt
ImportError: cannot import name 'TextTokensPrompt' from 'vllm.inputs' (/opt/vllm/lib64/python3.11/site-packages/vllm/inputs/__init__.py)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Which version of vLLM are you using? Make sure the docker image is up to date.

**Comment by shubh9m** [comment]
Sorry for the delayed response. The version of vLLM is same for both and the docker image is also up to date.

**Comment by DarkLight1337** [comment]
Which docker image are you using? I see that the package name is `vllm_tgis_adapter` which isn't the normal one for vLLM.

**Comment by shubh9m** [comment]
I rechecked, the docker image has following vLLM version: 0.5.3.post1+cu124

**Comment by DarkLight1337** [comment]
Sorry for forgetting about this, the issue should be solved once you update your docker image.
