### ISSUE TITLE
How do init mul-instances on mul-gpus for concurrency request on server?

### ISSUE THREAD

**Issue by bigmover** [vllm-project/vllm#824]
eg CUDA_VISIBLE_DEVICES=gpus  XXXXX (init model server) ?

**Comment by horiacristescu** [comment]
I can get it faster with 2 GPUs in CUDA_VISIBLE_DEVICES and --tensor-parallel-size 2 but can't raise it to 4

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
