### ISSUE TITLE
[Usage]: vllm Docker: OSError: Incorrect path_or_model_id

### ISSUE THREAD

**Issue by brian-you98** [vllm-project/vllm#8262]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [deepeek](https://modelscope.cn/models/deepseek-ai/DeepSeek-V2-Lite-Chat/files). I don't know how to integrate it with vllm.
I want to deploy the fine-tuned [deepseek] (https://modelscope.cn/models/deepseek-ai/DeepSeek-V2-Lite-Chat/files) model using the docker image [vllm/vllm-openai:v0.6.0], but the container cannot run and an error occurs: OSError: Incorrect path_or_model_id: '/data1/models/deepseek'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
However, this model can be run in the python environment of vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
I guess you didn't make the model files available inside Docker container (e.g. via bind mounts).

**Comment by brian-you98** [comment]
> I guess you didn't make the model files available inside Docker container (e.g. via bind mounts).

For example, my model file path is'/data1/models/deepseek '. Can you give me an example command.
 In fact, I tried to package the model file into a Docker image, but still encountered this error.

**Comment by DarkLight1337** [comment]
You can take a look at [this page](https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html).

In particular, note the `-v` flag which specifies bind mounts for the container. You should modify the directory to point to your model files.

**Comment by brian-you98** [comment]
> You can take a look at [this page](https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html).
> 
> In particular, note the `-v` flag which specifies bind mounts for the container. You should modify the command so that it points to your model files.

I think I understand now that Docker recognizes internal paths, not the path of my server. But why can't I package the model into an image? The file path is already inside the image. Can it only be saved to /root/. cache/huggingface

**Comment by brian-you98** [comment]
> You can take a look at [this page](https://docs.vllm.ai/en/latest/serving/deploying_with_docker.html).
> 
> In particular, note the `-v` flag which specifies bind mounts for the container. You should modify the command so that it points to your model files.

Thank you for your help, I have already resolved this issue. The solution is to mount or package the model file to the path: /root/. cache/huggingface. Although there are new GPU related errors now, I think I can solve them myself.
