### ISSUE TITLE
[Bug]: deepseek_v2 236B  on 8XA100 wrong output   vllm==0.5.4 

### ISSUE THREAD

**Issue by shuailong616** [vllm-project/vllm#8283]
### Your current environment

**wrong output** 
 Prompt:  'Funniestjoke ever:',generated text: '!!!!!!!!!!!!!!!!!!'
 Prompt:  The capital of France is:',generated text: '!!!!!!!!!!!!!!!!!!'
 Prompt:  'The future of AI is:',generated text: '!!!!!!!!!!!!!!!!!!'

### 🐛 Describe the bug

from llvm import LLM, SamplingPatams
import argpase
import torch

def generate(args, prompts):
      sampling_params = SamplingParams(temperature=0.8, top_k=1, max_tokens=20)
      llm = LLM(mode=args.model_path, trust_remote_code=True, max_model_len=2048,work_use_ray=True, enforce_eager=True, dtype=torch.half, tensor_parakkek_size=8, enable_chunked_prefill=False)
      outputs = llm.gennrate(prompts, sampling_params)
      for output in outputs:
           prompt = output.prompt
           generated_text = output.output[0].text
           print(f"prompt: {prompt!r} Generated text {generated_text!r}")
if __name__ == "__main__"：
    parse =  argparse.ArgumentParser()
    parse.add_argument('--model_path',type =str)
    prompts = [
    "Funniestjoke ever:",
    "The capital of France is",
    "The future of AI is", 
     ]
    generate(args, prompts)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by shuailong616** [comment]
![a8ddbe6c90a61c3c23d06b21a5036607](https://github.com/user-attachments/assets/0aa628dd-eb4f-4b3a-af0f-f6dedad259cd)

**Comment by dsikka** [comment]
@shuailong616 do you mind sharing your exact arguments for running the model? Trying to reproduce the output you're seeing.

**Comment by dsikka** [comment]
@shuailong616 Hi! Can you try swapping the `dtype=torch.half` to `dtype=torch.bfloat16`?

**Comment by shuailong616** [comment]
> @shuailong616 Hi! Can you try swapping the `dtype=torch.half` to `dtype=torch.bfloat16`?

thank you so much for your replay , use torch.bfloat16  have a currect result.

**Comment by shuailong616** [comment]
![Uploading iwEeAqNwbmcDAQTRBN0F0QDwBrCTfCCdbk_4pQbKkrYcZP4AB9ITCQwDCAAJomltCgAL0gACCvw.png_720x720q90.jpg…]()

**Comment by shuailong616** [comment]
> @shuailong616 Hi! Can you try swapping the `dtype=torch.half` to `dtype=torch.bfloat16`?

Hi! I also want to konw why torch.half result wrong reason . looking fowward to  your reply

**Comment by youkaichao** [comment]
@shuailong616 of course you need to match the dtype of the original model. models can be sensitive to dtypes.
