### ISSUE TITLE
How to use API

### ISSUE THREAD

**Issue by krishanu-deloitte** [vllm-project/vllm#830]
I have started a vLLM API server using the following command:

`python -m vllm.entrypoints.api_server --model meta-llama/Llama-2-13b-chat-hf --port 5500`

This produces the output and starts the api server:
 
```
INFO 08-22 15:27:08 llm_engine.py:70] Initializing an LLM engine with config: model='meta-llama/Llama-2-13b-chat-hf', tokenizer='meta-llama/Llama-2-13b-chat-hf', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)

INFO 08-22 15:27:08 tokenizer.py:29] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.

INFO 08-22 15:27:25 llm_engine.py:196] # GPU blocks: 865, # CPU blocks: 327

INFO:     Started server process [9264]

INFO:     Waiting for application startup.

INFO:     Application startup complete.

INFO:     Uvicorn running on http://localhost:5500 (Press CTRL+C to quit)

```

Now I am trying to generate some output using the API. I am using Python requests library to do so:

```
import requests
myobj = {
    "prompt": "San Francisco is a"
    }

requests.get('http://localhost:5500/generate', json = myobj)
```

This generates the following error:
`<Response [405]>`

Any idea what I am doing wrong. I cant use curl or any other commands. I can only interact with the API using python.
Any help would be appreciated.
Thanks.

**Comment by krishanu-deloitte** [comment]
Actually I was able to solve this problem. In case anyone is facing the same I was using the get request. We need to use post request.

**Comment by frankiedrake** [comment]
> Actually I was able to solve this problem. In case anyone is facing the same I was using the get request. We need to use post request.

Maybe better use OpenAI API library, it handles all requests for you
