### ISSUE TITLE
Compatibility with togethercomputer/Llama-2-7B-32K-Instruct

### ISSUE THREAD

**Issue by slobodaapl** [vllm-project/vllm#831]
Since it's a LLama V2 model I assumed them to be compatible, but it seems like the model doesn't behave correctly (nonsensical output, repeating symbols, nothing useful) when I run it with vLLM, in addition to the fact that it's impossible to run it sharded without downgrading certain pip packages (using the OpenAI version):

`pip install typing-inspect==0.8.0 typing_extensions==4.5.0` <- This fixes the running issue, so I can run and shard it

This is how I run the model:
`python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8080 --model togethercomputer/Llama-2-7B-32K-Instruct --tensor-parallel-size 4 --download-dir /data`

This is how I test it:
```python
from langchain.llms import VLLMOpenAI

llm = VLLMOpenAI(
    openai_api_key="EMPTY",
    openai_api_base="ip_address/v1",
    model_name="togethercomputer/Llama-2-7B-32K-Instruct",
    max_tokens=128,
    top_p=0.7,
    top_k=50,
    frequency_penalty=1.1,
    temperature=0.7
)

print(llm("[INST]\nWrite a poem about cats\n[/INST]\n\n"))
```

This produces a bunch of nonsensical output. When I run it with TGI with identical parameters, it works as expected and produces reasonable text. I tested it over multiple attempts to make sure it isn't a fluke.

Could anyone test and reproduce, to make sure it isn't just something on my side?

**Comment by topolskib** [comment]
Found the issue. `togethercomputer/Llama-2-7B-32K-Instruct` uses linear rope scaling with a factor of 8.0, but the scaling is not implemented in vLLM. Dividing `t` by 8.0 in [PagedAttentionWithRoPE](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/attention.py#L263) makes the model return valid output. 

I'll try preparing a proper fix.

**Comment by slobodaapl** [comment]
> Found the issue. `togethercomputer/Llama-2-7B-32K-Instruct` uses linear rope scaling with a factor of 8.0, but the scaling is not implemented in vLLM. Dividing `t` by 8.0 in [PagedAttentionWithRoPE](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/layers/attention.py#L263) makes the model return valid output.
> 
> I'll try preparing a proper fix.

Have you managed any progress on this out of curiosity?

**Comment by babytdream** [comment]
I am also interested in `--rope-scaling`.

**Comment by mahaddad** [comment]
I can confirm that @topolskib suggested fix worked for me.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
