### ISSUE TITLE
Issue while loading MPT-7B-8K-instruct

### ISSUE THREAD

**Issue by ramkrithik** [vllm-project/vllm#832]
Newbie Question:

I thought support for all MPT models is enabled by default, but when I try to load 8K variant of the MPT-7B model. I'm running into the following error while instantiation:
```
ValueError: Invalid shape for attention bias: torch.Size([32, 10, 10]) (expected (1, 32, 10, 10))
  query.shape: torch.Size([1, 10, 32, 128])
  key.shape  : torch.Size([1, 10, 32, 128])
  value.shape: torch.Size([1, 10, 32, 128])
```

Can someone help/ guide me on this issue?

**Comment by WoosukKwon** [comment]
Hi @ramkrithik, thanks for reporting the bug. It seems the bug is due to the new release of `xformers`, which includes some breaking changes. I'm fixing this issue.
