### ISSUE TITLE
vLLM full name

### ISSUE THREAD

**Issue by designInno** [vllm-project/vllm#835]
hi guys，How to understand the v of vLLM and what he means by it

**Comment by yb01** [comment]
i am curious on that too.

**Comment by WoosukKwon** [comment]
Hi @designInno and @yb01, originally we used the "v" to represent "virtual", just like vCPU stands for virtual CPU. This is because our core technique was inspired by virtual memory (and paging) in OS. But we also think the "v" could represent other ideas, like velocity and victory.

**Comment by designInno** [comment]
tks

**Comment by cringelord000222** [comment]
Hi all, just curious, as of now is there an official for what the "v" stands for?

**Comment by manuelgruber** [comment]
Versatile?
