### ISSUE TITLE
[performance] comparison with NVIDIA FasterTransformer

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#837]
I run llama2 13B on 2 V100 GPUs(tensor parallel size = 2), the performance of vllm is no better than FasterTransformer. Neither latency nor throughput.

Has anyone done similar benchmarks? Need some double check.
I post my result here :

**vllm** 
![image](https://github.com/vllm-project/vllm/assets/26128514/67bdffc3-1066-4f2d-9795-2928896b9bf1)

**FasterTransformer**
![image](https://github.com/vllm-project/vllm/assets/26128514/0e116f5a-614a-45f3-8a65-bb7b55a49d55)

**Comment by double-vin** [comment]
@sleepwalker2017 Hello, can you share the code for FasterTransformer llma2? I would like to compare the results and look forward to your reply.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
