### ISSUE TITLE
[Usage]: RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by TianSongS** [vllm-project/vllm#8392]
### Your current environment

I used the same service deployment command, but when I upgraded from 0.5.5 to 0.6.1 today, the deployment went wrong

![20240912-095248](https://github.com/user-attachments/assets/278b91a6-6a35-4c0c-b956-f20c5e09997e)

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
should be solved by https://github.com/vllm-project/vllm/pull/8390 

can you give it a try?

**Comment by youkaichao** [comment]
follow https://docs.vllm.ai/en/latest/getting_started/installation.html and install the wheel for the latest commit, or wait for the release, which will finish soon https://github.com/vllm-project/vllm/pull/8440 .

**Comment by ahmetfirat23** [comment]
I am still having this issue with 0.6.2
