### ISSUE TITLE
[New Model]: qwen2-audio

### ISSUE THREAD

**Issue by seetimee** [vllm-project/vllm#8394]
### 🚀 The feature, motivation and pitch

Do we have a plan to support voice models like qwen-audio?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
@fyabc are you interested in implementing this?

**Comment by fyabc** [comment]
> @fyabc are you interested in implementing this?

Hi, our team are developing on Qwen2-Audio vllm support, please check [this branch](https://github.com/faychu/vllm/tree/qwen2-audio), and @faychu will take effort on it.

**Comment by seetimee** [comment]
that's great

**Comment by zhangfan-algo** [comment]
When do we expect to support qwen2 audio

**Comment by ywang96** [comment]
> > @fyabc are you interested in implementing this?
> 
> Hi, our team are developing on Qwen2-Audio vllm support, please check [this branch](https://github.com/faychu/vllm/tree/qwen2-audio?rgh-link-date=2024-09-12T04%3A46%3A45Z), and @faychu will take effort on it.

@fyabc Very excitied to see this release! Please feel free to ping me for review when the PR's up.

**Comment by faychu** [comment]
> When do we expect to support qwen2 audio

We expect to support qwen2audio within one month.

**Comment by seetimee** [comment]
@faychu,
Hi ,pro
I follow your branch and have done some adaptation work with the latest version of VLLM. It worked well in a single audio per request scenario, but I am having trouble in the multi-audio per request scenario since the latest VLLM audio batch seems to have two dimensions: batch and sub-batch. Could you please give me some advice?

**Comment by lihuikenny** [comment]
> the latest version of VL



> @faychu, Hi ,pro I follow your branch and have done some adaptation work with the latest version of VLLM. It worked well in a single audio per request scenario, but I am having trouble in the multi-audio per request scenario since the latest VLLM audio batch seems to have two dimensions: batch and sub-batch. Could you please give me some advice?

Can you share your adaptation work? Thanks
