### ISSUE TITLE
Vicuna-13b model consistently outputs repeatedly in tensor parallelism

### ISSUE THREAD

**Issue by wenpengwu** [vllm-project/vllm#840]
I have two 3090 GPUs on one host, so I tried using a tensor parallel loading model, which ran successfully, but the output kept repeating.

<img width="588" alt="image" src="https://github.com/vllm-project/vllm/assets/20418359/1d6f983c-2607-41a6-bea8-31428210f1d7">

<img width="578" alt="image" src="https://github.com/vllm-project/vllm/assets/20418359/76e18c01-0fbe-4bf4-a270-866d21afd71f">

**Comment by dhgarcia** [comment]
I'm having the same problem. 
I also have 2 NVIDIA GeForce RTX 3090
When running vicuna-13b-v1.5-16k 
Running vicuna-13b-v1.3 seemed to be okay.

**Comment by dhgarcia** [comment]
@wenpengwu  I found out this due to rope embedding not supported yet, see #674

**Comment by wenpengwu** [comment]
thanks， Using Vicuna-13b-1.5 ,not  Vicuna-13b-1.5-16k  eliminates the issue of duplicate output
