### ISSUE TITLE
Support for RLHF (ILQL)-trained Models

### ISSUE THREAD

**Issue by ojus1** [vllm-project/vllm#841]
LMs trained with [ILQL](https://github.com/CarperAI/trlx/blob/main/trlx/models/modeling_ilql.py) are not supported by vLLM at the moment. Is this in the roadmap? It looks like it shouldn't be tough to do it.

**Comment by hmellor** [comment]
@simon-mo is this a feature you'd like to see implemented?

**Comment by hmellor** [comment]
Closing as won't do due to low demand
