### ISSUE TITLE
[Bug]: use speculative model in vllm error: TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'

### ISSUE THREAD

**Issue by xhjcxxl** [vllm-project/vllm#8416]
### Your current environment
vllm = 0.5.4, 0.5.5

```
super().__init__(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 46, in __init__
  self._init_executor()
File "/usr/local/lib/python3.10/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 135, in _init_executor
  self.driver_worker = self._create_worker(
File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 104, in _create_worker
  return create_worker(**self._get_create_worker_kwargs(
File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 23, in create_worker
  wrapper.init_worker(**kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 444, in init_worker
  self.worker = worker_class(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 70, in create_spec_worker
  spec_decode_worker = SpecDecodeWorker.create_worker(
File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 161, in create_worker
  proposer_worker = MultiStepWorker(**draft_worker_kwargs)
File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/multi_step_worker.py", line 30, in __init__
  super().__init__(*args, **kwargs)
TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'
ERROR 09-12 19:00:36 api_server.py:173] RPCServer process died before responding to readiness probe
```

when i use num-speculative-tokens, vllm error: **TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'**

when i delete this args: num-speculative-tokens, vllm error: **ValueError: num_speculative_tokens must be provided with speculative_model unless the draft model config contains an n_predict parameter.**

how to fix it, use draft model in vllm

### Model Input Dumps

--model "/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4" \
--speculative-model="/QwenModel/Qwen2-1.5B-Instruct" \
--num_speculative_tokens 5 \
--speculative-draft-tensor-parallel-size=1 \
--speculative-max-model-len 4096 \

**Comment by youkaichao** [comment]
cc @LiuXiaoxuanPKU

**Comment by ShangmingCai** [comment]
How about using `--num-speculative-tokens` instead of 'num_speculative_tokens'?

**Comment by xhjcxxl** [comment]
> ~How about using `--num-speculative-tokens` instead of `--num_speculative_tokens`?~
> 
> Nevermind. Both of these options work perfectly fine on my machine for v0.5.5.

can you share your code to start vllm docker，i cant run it, are you speculative model = draft model, one big ,one small

**Comment by xhjcxxl** [comment]
whole log：
```
INFO 09-13 02:49:59 api_server.py:449] vLLM API server version 0.5.5
INFO 09-13 02:49:59 api_server.py:450] args: Namespace(host=None, port=9413, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='bfloat16', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=4096, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.7, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization='gptq_marlin', rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=True, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model='/QwenModel/Qwen2-1.5B-Instruct', speculative_model_quantization=None, num_speculative_tokens=5, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=['qwen2-72b'], qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, early_stop=False, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
INFO 09-13 02:50:00 gptq_marlin.py:102] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 09-13 02:50:00 api_server.py:146] Multiprocessing frontend to use ipc:///tmp/4eeca0d6-c05e-4098-ba02-9f8443b408f1 for RPC Path.
INFO 09-13 02:50:00 api_server.py:163] Started engine process with PID 80
WARNING 09-13 02:50:10 config.py:1574] Casting torch.float16 to torch.bfloat16.
INFO 09-13 02:50:11 gptq_marlin.py:102] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 09-13 02:50:11 llm_engine.py:185] Initializing an LLM engine (v0.5.5) with config: model='/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4', speculative_config=SpeculativeConfig(draft_model='/QwenModel/Qwen2-1.5B-Instruct', num_spec_tokens=5), tokenizer='/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=gptq_marlin, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=qwen2-72b, use_v2_block_manager=True, enable_prefix_caching=False, early_stop=False)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 230, in run_rpc_server
    server = AsyncEngineRPCServer(async_engine_args, usage_context, rpc_path)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/rpc/server.py", line 31, in __init__
    self.engine = AsyncLLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 740, in from_engine_args
    engine = cls(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 636, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 840, in _init_engine
    return engine_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 272, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
    self.model_executor = executor_class(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 46, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 37, in _init_executor
    self.driver_worker = self._create_worker()
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 104, in _create_worker
    return create_worker(**self._get_create_worker_kwargs(
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/gpu_executor.py", line 23, in create_worker
    wrapper.init_worker(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 444, in init_worker
    self.worker = worker_class(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 70, in create_spec_worker
    spec_decode_worker = SpecDecodeWorker.create_worker(
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/spec_decode_worker.py", line 161, in create_worker
    proposer_worker = MultiStepWorker(**draft_worker_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/spec_decode/multi_step_worker.py", line 30, in __init__
    super().__init__(*args, **kwargs)
TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'
ERROR 09-13 02:50:15 api_server.py:173] RPCServer process died before responding to readiness probe
```

**Comment by ShangmingCai** [comment]
> > ~How about using `--num-speculative-tokens` instead of `--num_speculative_tokens`?~
> > Nevermind. Both of these options work perfectly fine on my machine for v0.5.5.
> 
> can you share your code to start vllm docker，i cant run it, are you speculative model = draft model, one big ,one small



> > ~How about using `--num-speculative-tokens` instead of `--num_speculative_tokens`?~
> > Nevermind. Both of these options work perfectly fine on my machine for v0.5.5.
> 
> can you share your code to start vllm docker，i cant run it, are you speculative model = draft model, one big ,one small

I didn't use docker. I used this following command trying to reproduce your problem:
```
python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen2-1.5B-Instruct-GPTQ-Int4 --speculative-model Qwen/Qwen2-0.5B-Instruct-GPTQ-Int4 --num_speculative_tokens 5 --speculative-draft-tensor-parallel-size=1 --speculative-max-model-len 2048 --use-v2-block-manager
```
However, it runs perfectly fine. So I am guessing maybe the problem is related to your python package dependency or the import line in your code. Can you share the full command or code you used to start the engine? Are you using AsyncLLMEngine or openai compatible server?

**Comment by xhjcxxl** [comment]
> > > ~How about using `--num-speculative-tokens` instead of `--num_speculative_tokens`?~
> > > Nevermind. Both of these options work perfectly fine on my machine for v0.5.5.
> > 
> > 
> > can you share your code to start vllm docker，i cant run it, are you speculative model = draft model, one big ,one small
> 
> > > ~How about using `--num-speculative-tokens` instead of `--num_speculative_tokens`?~
> > > Nevermind. Both of these options work perfectly fine on my machine for v0.5.5.
> > 
> > 
> > can you share your code to start vllm docker，i cant run it, are you speculative model = draft model, one big ,one small
> 
> I didn't use docker. I used this following command trying to reproduce your problem:
> 
> ```
> python -m vllm.entrypoints.openai.api_server --model Qwen/Qwen2-1.5B-Instruct-GPTQ-Int4 --speculative-model Qwen/Qwen2-0.5B-Instruct-GPTQ-Int4 --num_speculative_tokens 5 --speculative-draft-tensor-parallel-size=1 --speculative-max-model-len 2048 --use-v2-block-manager
> ```
> 
> However, it runs perfectly fine. So I am guessing maybe the problem is related to your python package dependency or the import line in your code. Can you share the full command or code you used to start the engine? Are you using AsyncLLMEngine or openai compatible server?

thanks，i maybe know my docker image has some error when use draft model, it run normal in deploy qwen2 without speculative model,

full command：
```
#!/bin/bash

MASTER_PORT="$(shuf -n 1 -i 60000-65000)"

docker run -e CUDA_VISIBLE_DEVICES=1 \
    --gpus 'all' \
    --network host \
    --ipc host \
    --shm-size="1G" \
    --privileged \
    --volume=/mnt/user/xhjcxxl/qwen/QwenModel:/QwenModel \
    -it \
    vllm-image:vllm \
    --model /QwenModel/Qwen2-72B-Instruct-GPTQ-Int4 \
    --speculative-model /QwenModel/Qwen2-1.5B-Instruct \
    --use-v2-block-manager \
    --num-speculative-tokens 5 \
    --quantization gptq_marlin \
    --served-model-name qwen2-72b \
    --port 9413 \
    --tokenizer-mode auto \
    --max-model-len 4096 \
    --tensor-parallel-size 1 \
    --gpu-memory-utilization 0.7 \
    --enforce-eager \
    --disable-custom-all-reduce \
    --dtype bfloat16 \
    --trust-remote-code \
```

**Comment by ShangmingCai** [comment]
The vocab_size of`Qwen2-1.5B-Instruct` is 151936, which is not equal to 152064 (the vocab_size of `Qwen2-72B-Instruct-GPTQ-Int4`), did you change your code to work around.

**Comment by xhjcxxl** [comment]
> The vocab_size of`Qwen2-1.5B-Instruct` is 151936, which is not equal to 152064 (the vocab_size of `Qwen2-72B-Instruct-GPTQ-Int4`), did you change your code to work around.

i change the same vocab model：/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4，/QwenModel/Qwen2-7B-Instruct-GPTQ-Int4，but also have this error:
```
TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'
```

**Comment by ShangmingCai** [comment]
> > The vocab_size of`Qwen2-1.5B-Instruct` is 151936, which is not equal to 152064 (the vocab_size of `Qwen2-72B-Instruct-GPTQ-Int4`), did you change your code to work around.
> 
> i change the same vocab model：/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4，/QwenModel/Qwen2-7B-Instruct-GPTQ-Int4，but also have this error:
> 
> ```
> TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'
> ```

Did you build `vllm-image:vllm` this image yourself from the dockerfile?  Maybe you can try the official docker images `vllm/vllm-openai`, and use the latest version (`docker pull vllm/vllm-openai:v0.6.1.post2`) to see if it works? 

Since you are using docker, and you didn't change the source code, I think that image could be the source of your problem.

**Comment by xhjcxxl** [comment]
> > > The vocab_size of`Qwen2-1.5B-Instruct` is 151936, which is not equal to 152064 (the vocab_size of `Qwen2-72B-Instruct-GPTQ-Int4`), did you change your code to work around.
> > 
> > 
> > i change the same vocab model：/QwenModel/Qwen2-72B-Instruct-GPTQ-Int4，/QwenModel/Qwen2-7B-Instruct-GPTQ-Int4，but also have this error:
> > ```
> > TypeError: Worker.__init__() got an unexpected keyword argument 'num_speculative_tokens'
> > ```
> 
> Did you build `vllm-image:vllm` this image yourself from the dockerfile? Maybe you can try the official docker images `vllm/vllm-openai`, and use the latest version (`docker pull vllm/vllm-openai:v0.6.1.post2`) to see if it works?
> 
> Since you are using docker, and you didn't change the source code, I think that image could be the source of your problem.

yes，i use person image to build docker, i try it use vllm-openai image, i run vllm with speculative model is ok in local

**Comment by xhjcxxl** [comment]
i use docker with vllm==0.6.1.post2 version deploy qwen2-7b + medusa model, it's also has this error, 'num_speculative_tokens', @LiuXiaoxuanPKU can you test qwen2-7b+medusa model in docker image? like `vllm/vllm-openai:v0.6.1.post2`

**Comment by xhjcxxl** [comment]
my docker has some error, i use v0.6.2 is ok!，thanks
