### ISSUE TITLE
[Usage]: Batching in online inference

### ISSUE THREAD

**Issue by shubh9m** [vllm-project/vllm#8441]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I have set up an API server through the command: `docker pull vllm/vllm-openai:v0.5.3.post1`. The server is running fine when I am giving requests through normal curl commands i.e. one request at a time. But I want vLLM to process requests(assuming one prompt per request) parallelly in the specified batch size. Right now I don't know the batch size in which vLLM internally processes the prompts. 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You can regard `max_num_seqs` as the batch size. Check out the [list of engine arguments](https://docs.vllm.ai/en/stable/models/engine_args.html) for more details.

**Comment by shubh9m** [comment]
Thanks
