### ISSUE TITLE
[Usage]: How to deploy lora model using vllm and lora is pluggable

### ISSUE THREAD

**Issue by ciaoyizhen** [vllm-project/vllm#8454]
### Your current environment

```text
The output of `python collect_env.py`
```
None

### How would you like to use vllm

I want to run inference of a glm4(put link here). I don't know how to integrate it with vllm.
Ask a question.
I have fine-tuned an LLM using lora, then I want to be able to deploy it using vllm, at the same time, I want the lora module to be pluggable, by passing in a flag to control whether I use the lora module or not, how do I implement this?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
See:https://docs.vllm.ai/en/latest/models/lora.html#serving-lora-adapters

**Comment by ciaoyizhen** [comment]
@jeejeelee thank you very much.this is all my need!!!!

**Comment by Williamleejx** [comment]
I just did the same thing as you. However, I face a problem that I can't not stop the inference output through eos_token of glm4 which is [151329, 151336, 151338]. Why?
My code is  below:
```
sql_lora_path = '/root/GLM-4/finetune_demo/model_1733470624658/checkpoint-3000'
llm = LLM(model="/root/autodl-tmp/glm-4-9b-chat", enable_lora=True, max_model_len = 2048, trust_remote_code= True)
sampling_params = SamplingParams(
    temperature=0,
    max_tokens=256,
    stop_token_ids = [151329, 151336, 151338], 
    n = 1
                       )

prompts = [
     " 以下文本中，对于处理意见是协助解决问题、协助客户退费、服务关怀补偿、按业务规则解释和处理、已解决、网络检修、解释业务规则、复机、联系客户、按业务规则解释和处理、 未提供、其他处理方式中的哪一个？服务请求立单提交，匹配规则：服务营销中心立单规则--亦庄工作组低星级|客户来电要求取消流量月包专享30-20元折扣券（24个月）业务，座席派机器人到营业厅后驳回，原因为提示有在途订单无法取消，请协助核实，谢谢|【f】有中台在途订单：100100121892691个人15010288293业务变更99自动处理失败C213128北京众齐劳务服务有限公司1860客服2024-04-0415:15:582024-05-16在途原因：用户【15010288293】欠费【0.04】元，中台账本现有【0.00】元，不能转移请咨询中台系统。",
]


outputs = llm.generate(
    prompts,
    sampling_params,
    lora_request=LoRARequest("sql_adapter", 1, sql_lora_path)
)

for output in outputs:
    # print(output.outputs[0].text)
    print(output)
```
