### ISSUE TITLE
[Usage]: How to use AutoModelForSequenceClassification correctly

### ISSUE THREAD

**Issue by fan-niu** [vllm-project/vllm#8459]
### Your current environment

```text
nvidia A100 GPU
vllm 0.6.0
```

### How would you like to use vllm

I want to run inference of a AutoModelForSequenceClassification. I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
In general, the model has to be implemented inside vLLM's framework first before it can be used in vLLM.

**Comment by fan-niu** [comment]
> In general, the model has to be implemented inside vLLM's framework first before it can be used in vLLM. This is the trade-off between generalizability (i.e. directly using Transformers) and performance.

@DarkLight1337  thanks for your reply, currently vllm does not support AutoModelForSequenceClassification, right? If so, are there any plans to support this feature?

**Comment by DarkLight1337** [comment]
`AutoModelForSequenceClassification` isn't a concrete model. I take it that you are asking for vLLM to support arbitrary models that inherit from it. This is rather difficult since we need some way to automatically translate Transformers models into vLLM framework. I wouldn't expect this to come any time soon.

**Comment by fan-niu** [comment]
> `AutoModelForSequenceClassification` isn't a concrete model. I take it that you are asking for vLLM to support arbitrary models that inherit from it. This is rather difficult since we need some way to automatically translate Transformers models into vLLM framework. I wouldn't expect this to come any time soon.

@DarkLight1337 In fact, what I want to use is LlamaForSequenceClassification. My model is trained based on llama3.1-8b. Is LlamaForSequenceClassification currently supported? Looking forward to your reply, thank you

**Comment by DarkLight1337** [comment]
You can refer to the framework proposed by https://github.com/vllm-project/vllm/pull/6260 to implement your own one.

**Comment by fan-niu** [comment]
> You can refer to the framework proposed by #6260 to implement your own one. It's not supported otherwise.

@DarkLight1337 Ok, thanks very much, Already contacted the author of https://github.com/vllm-project/vllm/pull/6260
