### ISSUE TITLE
[Feature]: Batch inference for `llm.chat()` API

### ISSUE THREAD

**Issue by ywang96** [vllm-project/vllm#8481]
### 🚀 The feature, motivation and pitch

Currently `llm.chat()` API only supports one conversation per inference. This means we cannot use this API to fully leverage vLLM for efficient offline processing.

### Additional context

Implementation should be rather straightforward:

1. at API level, `llm.chat()` should also accept a list of conversations.
2. When `llm.chat()` is invoked, the list of conversations will be parsed into list of prompts, and all multimodal data items will be retrieved and loaded into their corresponding format that `llm.generate()` accepts.
3. Send the list of `{prompt: xxx, multi_modal_data: xxx}` to the `llm.generate()`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by aandyw** [comment]
I can work on this :)
