### ISSUE TITLE
[Usage]: Dose vLLM support embedding api of multimodal llm?

### ISSUE THREAD

**Issue by sfyumi** [vllm-project/vllm#8483]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

eg: get embedding of minicpmv 2.6

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
No, this is not supported yet.

**Comment by DarkLight1337** [comment]
In fact, this isn't even available for language-only models so far.

**Comment by noooop** [comment]
I am working on it. #8452

**Comment by noooop** [comment]
According to my understanding, MiniCPM-V 2.6 is a generative model, not a retrieval model specifically used to generate embeddings. (Maybe you need multimodal retrieval models such as  BAAI/bge-visualized-m3 https://huggingface.co/BAAI/bge-visualized）

Can you send some sample code and tell me how you want to use MiniCPM-V 2.6 to generate embedding 
@sfyumi

**Comment by sfyumi** [comment]
@noooop 
We obtain the last hidden states from a language model (LLM) and use a multi-layer linear transformation to reduce the dimensionality as embedding.
We use both minicpmv 2.6 and qwen2 model as base model to get embeddings.

sample code
```
class MiniCpmlWithProjectionModel(MiniCPMV):
    def __init__(self, config):
        super().__init__(config)
        embedding_dim = config.hidden_size
        projection_output_dim = config.projection_output_dim if hasattr(config, "projection_output_dim") else 128
        self.projection_layer = nn.Sequential(
            nn.Linear(embedding_dim, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, projection_output_dim)
        )
```

**Comment by noooop** [comment]
Understood

There is a small detail here. 
[vllm routing](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/__init__.py) model_name to it corresponding implementation is through the [architectures parameter](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/config.json) in config.json. 

You must think of a cool name to avoid routing to the previous model.

**Comment by noooop** [comment]
# Simple but not inefficient method: 

Output last hidden states #853, A hacker’s method is mentioned below. https://github.com/WuNein/vllm4mteb/tree/main 
(Maybe vllm can add an option to output last hidden states in the future.
But you need to implement mlp in another process

# More efficient implementation
Implement a model yourself. [adding_model](https://docs.vllm.ai/en/latest/models/adding_model.html)
There is a small detail here.~~
[vllm routing](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/__init__.py) model_name to it corresponding implementation is through the [architectures parameter](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/config.json) in config.json.

You must think of a cool name to avoid routing to the previous model.

**Comment by DarkLight1337** [comment]
You can now modify any existing model to support embeddings, please see https://github.com/vllm-project/vllm/issues/9314#issuecomment-2428195404.

**Comment by jianglan89** [comment]
> According to my understanding, MiniCPM-V 2.6 is a generative model, not a retrieval model specifically used to generate embeddings. (Maybe you need multimodal retrieval models such as BAAI/bge-visualized-m3 [https://huggingface.co/BAAI/bge-visualized）](https://huggingface.co/BAAI/bge-visualized%EF%BC%89)
> 
> Can you send some sample code and tell me how you want to use MiniCPM-V 2.6 to generate embedding @sfyumi

does vllm support BAAI/bge-visualized now?

**Comment by DarkLight1337** [comment]
> > According to my understanding, MiniCPM-V 2.6 is a generative model, not a retrieval model specifically used to generate embeddings. (Maybe you need multimodal retrieval models such as BAAI/bge-visualized-m3 [https://huggingface.co/BAAI/bge-visualized）](https://huggingface.co/BAAI/bge-visualized%EF%BC%89)
> > Can you send some sample code and tell me how you want to use MiniCPM-V 2.6 to generate embedding @sfyumi
> 
> does vllm support BAAI/bge-visualized now?

It doesn't look like the HF repo is compatible with `transformers`, so we can hardly load the model.
