### ISSUE TITLE
[Feature]: new possible lora serving implementation?

### ISSUE THREAD

**Issue by nivibilla** [vllm-project/vllm#8497]
### 🚀 The feature, motivation and pitch

Paper from Microsoft on serving loras in production

https://arxiv.org/abs/2404.05086v1

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
Any highlights that we should learn from this paper?

**Comment by nivibilla** [comment]
This is probably the most relevant part.

> We first combine LoRA weights for every shared base layer, from all LoRA models, into a series of stacked tensors, one per each base layer. When treating a batch request pointing to multiple LoRA models, we define a batched routing mask with weights of 1 assigned to the indices of the target LoRA models’ weights, from the stacked LoRA matrices, while nullifying the rest. We implemented a set of kernels that support batched multiplication of such masks with stacked LoRA weights, allowing for efficient forward passes with little overhead. This approach is reminiscent of the routing and Mixture-of-Expert (MoE) for the FFN layers in Switch Transformer [FZS21] and can enable efficient batch serving of requests targeting a large number of LoRA models at once. Such system helped us to serve LoRA at a production scale by reducing the additional latency and cost of a new LoRA model to a minimal extent. A recent work, S-LoRA [SCL+23], proposes a similarly effective solution for this scenario with several optimizations

Unfortunately they didnt release and kernels. And say slora is similar but I have to go check the slora implementation to see if it's the same as they are describing here

**Comment by simon-mo** [comment]
It sounds like very similar kernels indeed. Our implementation of S-LoRA originally uses the Punica implementation, now we have our own Triton kernels.

**Comment by nivibilla** [comment]
Ah okay cool I can close this then. Thanks @simon-mo
