### ISSUE TITLE
[Installation]: Container image do not build Dockerfile.cpu

### ISSUE THREAD

**Issue by axel7083** [vllm-project/vllm#8502]
### Your current environment

```text
$: podman -v
podman version 5.2.2
```

### How you are installing vllm

```sh
$: podman build -f Dockerfile.cpu -t vllm-cpu-env --shm-size=4g .
...
Error: building at STEP "RUN --mount=type=cache,target=/root/.cache/pip --mount=type=bind,src=requirements-build.txt,target=requirements-build.txt pip install --upgrade pip &&     pip install -r requirements-build.txt": resolving mountpoints for container "3a97f46183fa64e10c96f20f9a38a5ed46d2e9e7c4e7bbfbce6fa1adfdacd66e": invalid container path "requirements-build.txt", must be an absolute path
```

We can see that in the `Dockerfile.cpu` we are mounting the requirement-*.txt files

https://github.com/vllm-project/vllm/blob/fc990f97958636ce25e4471acfd5651b096b0311/Dockerfile.cpu#L29

https://github.com/vllm-project/vllm/blob/fc990f97958636ce25e4471acfd5651b096b0311/Dockerfile.cpu#L51

https://github.com/vllm-project/vllm/blob/fc990f97958636ce25e4471acfd5651b096b0311/Dockerfile.cpu#L52

And while they are mounted, no absolute path is provided, leading to the error above.

## Solution proposal

```diff
+ COPY requirements-build.txt requirements-build.txt
RUN --mount=type=cache,target=/root/.cache/pip \
-    --mount=type=bind,src=requirements-build.txt,target=requirements-build.txt \
    pip install --upgrade pip && \
    pip install -r requirements-build.txt
```

OR

```diff
+ WORKDIR /
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,src=requirements-build.txt,target=requirements-build.txt \
    pip install --upgrade pip && \
    pip install -r requirements-build.txt
```

According to https://github.com/containers/buildah/issues/4309 a WORKDIR must be defined to use a relative path for target. I opened an issue on the buildah side to have more information https://github.com/containers/buildah/issues/5738

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
The file was written against `DOCKER_BUILDKIT=1` in mind, does podman support this?

**Comment by axel7083** [comment]
I would probably say it does, but as I do not work on buildah and don't have extensive knowledge on his capabilities I can't say. The problem here seems to really be a sidecase, as the `target=requirements-build.txt` is a relative path, and in most places this is not an issue, but apparently buildah do not support this without defining the `WORKDIR`.

I opened https://github.com/containers/buildah/issues/5738 to draw some attention from the buildah team. (podman uses buildah to build the images).

**Comment by dtrifiro** [comment]
This can be fixed by setting `WORKDIR` before running the command: fixed  in https://github.com/vllm-project/vllm/pull/8540
