### ISSUE TITLE
[Usage]: Weird vram usage and increase in use

### ISSUE THREAD

**Issue by RichaMax** [vllm-project/vllm#8504]
### Your current environment

```text
PyTorch version: 2.4.0+cu121

GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.44.2
[pip3] triton==3.0.0
```

### How would you like to use vllm

First of all I wanted to thanks all of the contributors of this library, you are doing an amazing job. 

I'm currently running an inference server using Vllm 0.6.0 and I cannot get my head around how the Vram is used, and I think that I don't understand some parameters of the library.
With my current setup (4 * nvidia T4@16Go Vram) I have around 64Go of vram available.

I'm running "meta-llama/Meta-Llama-3.1-8B-Instruct" downloaded from hugging face with an AsyncEngine endpoint declare as:

engine_config.json
```json
{
    "model":"Meta-Llama-3.1-8B-Instruct",
    "tensor_parallel_size":4,
    "dtype":"float16",
    "max_model_len":29000,
    "gpu_memory_utilization":0.95
}
```

```python
with open("engine_config.json") as f:
    engine_args = json.load(f)
engine = AsyncLLMEngine.from_engine_args(AsyncEngineArgs(**engine_args))
```

I have then taken inspiration from: https://github.com/vllm-project/vllm/blob/main/vllm/entrypoints/api_server.py to put it behind a Fast API endpoint.

When the serve has finished his initialisation I can observe that 48.892Go of Vram are taken. From my understanding of this page : https://huggingface.co/blog/llama31 if I were to load this models with 128k tokens KV cache, it should take at most 31.62Go of Vram. I get that the values from the Hugging Face page are approximation, but I was not expecting a difference of 15Go. And in addition i specified a `max_model_len` of `29000` in the config, so is should not be that high.

### Could you be so king to explain me where this could be coming from ? 

In addition, I also noticed that after one question with a "long answer" I can still the vram usage going up. My understanding what that this should not happend as the KV cache is already allocated and the vram usage should increase just to put the input to the GPU and then should be free.

Could you also explain what I'm doing wrong here ?

vram before first question:
```text
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02             Driver Version: 530.30.02   CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0              26W /  70W |  12223MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       Off | 00000000:00:1C.0 Off |                    0 |
| N/A   35C    P0              26W /  70W |  12223MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla T4                       Off | 00000000:00:1D.0 Off |                    0 |
| N/A   36C    P0              26W /  70W |  12223MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla T4                       Off | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0              26W /  70W |  12223MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
vram after question: (it's just a dummy question to start evaluating his knowledge of AWS) "In aws how can i creae multiple micro service that are able to communicate with each other ?"

```text
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02             Driver Version: 530.30.02   CUDA Version: 12.1      |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0              26W /  70W |  12316MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       Off | 00000000:00:1C.0 Off |                    0 |
| N/A   35C    P0              26W /  70W |  12286MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla T4                       Off | 00000000:00:1D.0 Off |                    0 |
| N/A   36C    P0              26W /  70W |  12286MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla T4                       Off | 00000000:00:1E.0 Off |                    0 |
| N/A   36C    P0              26W /  70W |  12286MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
(my sampling parameters are just max_tokens=1000)

Thanks in advance for your answers.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by NickLucche** [comment]
Your missing the space required for storing activations in your math. 
VLLM takes `gpu_memory_utilization`*Vram bytes as the space it can use: it will first allocate the model weights, then set some more space aside required for running the model with a sequence of length `max_model_len` -the activations-by simply profiling a forward and then allocate all the remaining space for KV cache.

On top of this you have to add space for CUDA graphs and kernels (that's why you usually don't set `gpu_memory_utilization`=1.0).

Vram usage should be fixed after init, maybe some maintainers can help in identifying any reported leakage.

**Comment by RichaMax** [comment]
Thanks @NickLucche; I wrongly though that the size for storing the activation was negligeable. Can you point me to a ressource on how to estimate the KV cache and Activation cost ? I cannot find a rule of thumb (or exact formula) for them.

Regarding the Vram usage, yes it keeps increasing (slowly) after each request.

**Comment by ilkersigirci** [comment]
> Regarding the Vram usage, yes it keeps increasing (slowly) after each request.

I am observing the same problem on the  latest version

**Comment by NickLucche** [comment]
> Thanks @NickLucche; I wrongly though that the size for storing the activation was negligeable. Can you point me to a ressource on how to estimate the KV cache and Activation cost ? I cannot find a rule of thumb (or exact formula) for them.

Activation space will depend on the kind  of model (or ops executed) and on the inference engine used (how things are implemented and re-used); if you pick a convnet you'll see the memory required for running it is much bigger that the size of the weights because of how the conv is expanded.
A good rule of thumb is to just run the model on the inference engine of your choice (ie pytorch) and observe memory usage.

> I am observing the same problem on the latest version

I couldn't reproduce your issue on v0.6.1.post2 (with the 4 T4 setup reported above), could you please provide more details or submit a new issue?

**Comment by RichaMax** [comment]
Thanks for your answers.

It ssems that the Vram is only slightly increasing with the first to inference. 

I'll close the issue now, thanks
