### ISSUE TITLE
try to download a cuda before constructed docker image, you can put the step of download cuda in the dockerfile.

### ISSUE THREAD

**Issue by yashdeepyds** [vllm-project/vllm#851]
try to download a cuda before constructed docker image, you can put the step of download cuda in the dockerfile. 
such as :

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://developer.download.nvidia.com/compute/cuda/11.0.3/local_installers/cuda_11.0.3_450.51.06_linux.run && \
    chmod +x cuda_11.0.3_450.51.06_linux.run && \
    ./cuda_11.0.3_450.51.06_linux.run --silent --toolkit --override && \
    rm cuda_11.0.3_450.51.06_linux.run

_Originally posted by @Shiyubo980980 in https://github.com/vllm-project/vllm/issues/807#issuecomment-1691102110_

**Comment by yashdeepyds** [comment]
" executor failed running [/bin/sh -c wget https://developer.download.nvidia.com/compute/cuda/11.0.3/local_installers/cuda_11.0.3_450.51.06_linux.run &&     chmod +x cuda_11.0.3_450.51.06_linux.run &&     ./cuda_11.0.3_450.51.06_linux.run --silent --toolkit --override]: exit code: 127"

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
