### ISSUE TITLE
[Installation]: Assets v0.6 for cuda 12+

### ISSUE THREAD

**Issue by GennVa** [vllm-project/vllm#8535]
### Your current environment

```text
my environment: cuda:12.1
```

### How you are installing vllm

```sh
I'm using vllm release url：https://github.com/vllm-project/vllm/releases
I was using vllm-0.5.4-cp39-cp39-manylinux1_x86_64.whl
(https://github.com/vllmproject/vllm/releases/download/v0.5.4/vllm-0.5.4-cp39-cp39-manylinux1_x86_64.whl)

From 0.5.5 I see only assets with cuda11.8, but I need with cuda12 or higher.
Why are these assets missing?
Thanks
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You can install directly from PyPI. The example [here](https://docs.vllm.ai/en/latest/getting_started/installation.html#install-with-pip) uses CUDA 12.1.

**Comment by GennVa** [comment]
@DarkLight1337 Ok thanks, and I don't even need to specify my Python version, if I understand correctly.

**Comment by DarkLight1337** [comment]
Yes, just `pip install` as you would for a regular package.
