### ISSUE TITLE
[Usage]: 

### ISSUE THREAD

**Issue by lauhaide** [vllm-project/vllm#8569]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

Hello, I would like to know the difference between using SamplingType.RANDOM_SEED or SamplingType.RANDOM. As far as I follow the code, it seems to be the same. I couldnt fine where the 'seed' argument from SamplingParams is used.

Thank you

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by NickLucche** [comment]
Please update the title of your issue with the topic.
`RANDOM_SEED` is set when a seed is given, `RANDOM` when no seed is set.

**Comment by hmellor** [comment]
If `seed` is set, then an explicit `torch.Generator` using that seed is created and added to the `SequenceGroupToSample`:

https://github.com/vllm-project/vllm/blob/cc4325b66ac49e403ed9e1a8c38156a5324e1174/vllm/model_executor/sampling_metadata.py#L268-L270

https://github.com/vllm-project/vllm/blob/cc4325b66ac49e403ed9e1a8c38156a5324e1174/vllm/model_executor/sampling_metadata.py#L341-L351

https://github.com/vllm-project/vllm/blob/cc4325b66ac49e403ed9e1a8c38156a5324e1174/vllm/model_executor/sampling_metadata.py#L38-L39
