### ISSUE TITLE
[Bug]: Wrong Response with Gemma2 with 8k context length

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#8580]
serving gemma2-9b on 4 GPUs with 8k context length. I disabled the sliding window and enable flashinfer backend, however when I send a long prompt I got weird responses with repeated same first sentences!!

example:
- prompt is to answer a question given a paper content.

- response:

> "content": "\n\nThe paper you'\n\nLet me know if you'\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper.\n\nLet me know if you have any other questions about the paper"

How to solve this issue?

**Comment by youkaichao** [comment]
I think gemma2 8k context is not supported right now.

**Comment by hahmad2008** [comment]
@youkaichao do you know when it gonna be supported? also can't we extend the context length by ROPE scalling?

**Comment by youkaichao** [comment]
@hahmad2008 it is supported now. you need to try the latest code, see https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code

**Comment by Dragon-Wu** [comment]
> @hahmad2008 it is supported now. you need to try the latest code, see https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code

I have update the latest version of vllm but it still not work.
I found the conflict is the "sliding_window": 4096 and "sliding_window_size": 4096, in the config file of gemma-2 models.
And when we initiate the vllm with the max_model_len=8192 (as the gemma-2 paper claimed support), the vllm reported the "ValueError: User-specified max_model_len (8192) is greater than the derived max_model_len (sliding_window=4096 or model_max_length=None in model's config.json)."

**Comment by youkaichao** [comment]
> I have update the latest version

what is your latest version?

It is not released yet, you have to try the nightly built wheels.

**Comment by Dragon-Wu** [comment]
> > I have update the latest version
> 
> what is your latest version?
> 
> It is not released yet, you have to try the nightly built wheels.

oh, I installed 0.6.4.post1.

Can I know how to update the latest version that support 8K gemma-2?

**Comment by youkaichao** [comment]
please check https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code

**Comment by youkaichao** [comment]
The release date is not determined. Please stay tuned.
