### ISSUE TITLE
[Feature]: Output logps of given output

### ISSUE THREAD

**Issue by lycheeyolo** [vllm-project/vllm#8622]
### 🚀 The feature, motivation and pitch

vllm is a great project. and i have meet the problem that how could i acquire the logps of a given input and output? 
for example, when the question is "who are you?", i want acquire the logps of answer "i am GPT model". i could not find any functions to realize this issue.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You can pass `sampling_params=SamplingParams(prompt_logprobs=...)`.

**Comment by lycheeyolo** [comment]
it seems like not fit this problem. when i ask the LLM that "who are you?", i want it output the logps of the answer "i am GPT model". and the "i am GPT model" what i expected. 
what is expected may be a function like:
def get_logps(question, answer):
  return logps

or may you explain more about your methods?

**Comment by DarkLight1337** [comment]
You can also pass `logprobs` argument. See [this page](https://docs.vllm.ai/en/latest/dev/sampling_params.html).
