### ISSUE TITLE
qwen2-vl: AttributeError: '_OpNamespace' '_C' object has no attribute 'gelu_quick'

### ISSUE THREAD

**Issue by xiangxinhello** [vllm-project/vllm#8624]
### Your current environment

gpu NVIDIA A100-SXM4-80GB
cpu AMD EPYC 7543
```
from PIL import Image
from transformers import AutoProcessor
from vllm import LLM, SamplingParams
from qwen_vl_utils import process_vision_info

MODEL_PATH = '/workspace/mnt/storage/trt-llama/Qwen2-VL-7B-Instruct'
IMAGE_PATH = '/workspace/mnt/storage/llm_storge/vllm/examples/demo.jpeg'

llm = LLM(
    model=MODEL_PATH,
    dtype = 'float16',
    limit_mm_per_prompt={'image': 10, 'video': 10},
)


sampling_params = SamplingParams(
    temperature=0.1, top_p=0.001, repetition_penalty=1.05, max_tokens=256,
    stop_token_ids=[],
)

messages = [
    {'role': 'system', 'content': 'You are a helpful assistant.'},
    {'role': 'user', 'content': [
        {
            'type': 'image',
            'image': IMAGE_PATH,

            # min_pixels & max_pixels are optional
            'max_pixels': 12845056,
        },

        # You can also pass one or more videos:
        # {
        #     'type': 'video',
        #     'video': VIDEO_PATH,
        # }

        {
            'type': 'text',
            'text': '输出击掌的检测框',
        },
    ]},
]


processor = AutoProcessor.from_pretrained(MODEL_PATH)
prompt = processor.apply_chat_template(
    messages, tokenize=False, add_generation_prompt=True,
)
image_inputs, video_inputs = process_vision_info(messages)

mm_data = {}
if image_inputs is not None:
    mm_data['image'] = image_inputs
if video_inputs is not None:
    mm_data['video'] = video_inputs

llm_inputs = {
    'prompt': prompt,
    'multi_modal_data': mm_data,
}

outputs = llm.generate([llm_inputs], sampling_params=sampling_params)
generated_text = outputs[0].outputs[0].text

print(generated_text)


```

### 🐛 Describe the bug

AttributeError: '_OpNamespace' '_C' object has no attribute 'gelu_quick'

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You may have an outdated compilation of vLLM.

- If you installed vLLM via PyPI, please uninstall it and remove any related caches.
- If you installed vLLM from source, please delete any build outputs (in particular, the `*.so` files under `vllm/` directory)

**Comment by DarkLight1337** [comment]
@youkaichao should we refine the error message to provide more detailed instructions?

**Comment by xiangxinhello** [comment]
> You may have an outdated compilation of vLLM.
> 
> * If you installed vLLM via PyPI, please uninstall it and remove any related caches.
> * If you installed vLLM from source, please delete any build outputs (in particular, the `*.so` files under `vllm/` directory)
> 
> Afterwards, you can reinstall vLLM from scratch.

Hi @DarkLight1337, firstly, in vllm/directory, I rm -rf *.so, than I pip uninstall vllm, and pip install vllm.
But it's still this error.
[rank0]: AttributeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20240920-065021.pkl): '_OpNamespace' '_C' object has no attribute 'gelu_quick'
I suspect it might be due to the CPU. I have two devices with A100, and the CPUs are Intel and AMD respectively, but the AMD one is reporting an error.

**Comment by youkaichao** [comment]
please use the latest code, and start a clean build to see if it works.

we have switched to python agnostic wheel for quite a long time, I think most users will not meet this problem now.

**Comment by xsank** [comment]
> You may have an outdated compilation of vLLM.
> 
> * If you installed vLLM via PyPI, please uninstall it and remove any related caches.
> * If you installed vLLM from source, please delete any build outputs (in particular, the `*.so` files under `vllm/` directory)
> 
> Afterwards, you can reinstall vLLM from scratch.

rebuild the project could solve this.
