### ISSUE TITLE
[Feature]: support out tree multimodal models

### ISSUE THREAD

**Issue by Jack47** [vllm-project/vllm#8667]
### 🚀 The feature, motivation and pitch

vllm >= 0.6 doesn't support out tree defined multimodal models:
```
rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/entrypoints/llm.py", line 177, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/engine/llm_engine.py", line 535, in from_engine_args
[rank0]:     engine_config = engine_args.create_engine_config()
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/engine/arg_utils.py", line 792, in create_engine_config
[rank0]:     model_config = ModelConfig(
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/config.py", line 230, in __init__
[rank0]:     self.multimodal_config = self._init_multimodal_config(
[rank0]:   File "/usr/local/lib/python3.8/dist-packages/vllm/config.py", line 251, in _init_multimodal_config
[rank0]:     raise ValueError(
[rank0]: ValueError: limit_mm_per_prompt is only supported for multimodal models.
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
how do you register the out of tree model?

**Comment by Jack47** [comment]
> how do you register the out of tree model?
This is the feature I want to have, currently vllm 0.6 doesn't provide ways to register out of tree models?

One possible hack way:add my model type and class into _MULTIMODAL_MODELS in vllm

**Comment by youkaichao** [comment]
we do support out of tree registration, see https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration

**Comment by Jack47** [comment]
> we do support out of tree registration, see https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration

sure and I've registered my multimodal models using that function. But the error I posted still occurs.

so vllm 0.6 doesn't provide ways to register out of tree `multimodal` registration?

**Comment by youkaichao** [comment]
cc @DarkLight1337 @ywang96 
does multi-modal model support the out-of-tree registration?

**Comment by DarkLight1337** [comment]
Currently, you can do it by adding the model to `_MULTIMODAL_MODELS`. Just like regular OOT models, there's no public API for this.

**Comment by youkaichao** [comment]
@DarkLight1337 we do have a public api for this:

https://github.com/vllm-project/vllm/blob/5e85f4f82a5b6eaad6869198d6ac76a0c12cf6d0/vllm/model_executor/models/__init__.py#L190

**Comment by DarkLight1337** [comment]
> @DarkLight1337 we do have a public api for this:
> 
> https://github.com/vllm-project/vllm/blob/5e85f4f82a5b6eaad6869198d6ac76a0c12cf6d0/vllm/model_executor/models/__init__.py#L190

Oh, I thought the docs suggested to modify `_MODELS` directly.

**Comment by youkaichao** [comment]
@DarkLight1337  that is for registering your model when you fork vllm.

this issue is about out-of-tree registration, i.e. adding new model to vllm without a fork.

**Comment by ywang96** [comment]
@Jack47 Can you take a look and try #8717 to see if it fixes your issue?

**Comment by Jack47** [comment]
I'll try it later, thanks.
will post the result there.
