### ISSUE TITLE
[Doc]: How to Specify System CUTLASS/CUTE Path?

### ISSUE THREAD

**Issue by zhanwenchen** [vllm-project/vllm#8679]
### 📚 The doc issue

Currently, the installation process forces you to git clone CUTLASS, while I already have CUTLASS compiled on my system under `/usr/local/cutlass` for DeepSpeed, which allowed you to specify a `CUTLASS_PATH` envvar. Is there a way we could force this during installation from source?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
cc @tlrmchlsmth

**Comment by tlrmchlsmth** [comment]
We've had to point vLLM at specific pre-release CUTLASS commits in the past, and we might need to do that again.

We use CUTLASS as a header-only library so we won't save either binary size or compile time by pointing at a preinstalled library. Are you seeing issues with download time, @zhanwenchen?

**Comment by zhanwenchen** [comment]
@tlrmchlsmth @youkaichao No issues so far. I want to keep the environment consistent between the system headers and the vllm lib headers. How do you use CUTLASS as a header-only library?

**Comment by tlrmchlsmth** [comment]
We just include the headers from CUTLASS when building the kernels that use it, so there shouldn't be any issues arising from an environment mismatch

We also set the following in CMakeLists.txt, mostly to prevent any tests from being compiled. 
```  
SET(CUTLASS_ENABLE_HEADERS_ONLY ON CACHE BOOL "Enable only the header library")
```

I'm going to close this but LMK if you run into any problems.
