### ISSUE TITLE
[Misc]: Unit test failures with BlockManager v2

### ISSUE THREAD

**Issue by sroy745** [vllm-project/vllm#8718]
### Anything you want to discuss about vllm.

We plan to deprecate BlockManager V1 in favor of BlockManager V2. As part of that deprecation process we want to make sure that all existing tests work with BlockManager V2. We will use this issue to track the unit tests that fail with BlockManager V2 and fix them.

To that end we are using https://github.com/vllm-project/vllm/pull/8678 to identify the unit tests that break with BlockManager V2

The unit tests that have identified as failing currently are

**tests/basic_correctness**

tests/basic_correctness/test_preemption.py::test_swap_infeasible[4-96-float-facebook/opt-125m] 

**tests/core**

test_chunked_prefill_scheduler.py::test_chunk test_chunked_prefill_scheduler.py::test_complex test_chunked_prefill_scheduler.py::test_prompt_limit test_chunked_prefill_scheduler.py::test_swap test_chunked_prefill_scheduler.py::test_running_prefill_prioritized_over_swap test_chunked_prefill_scheduler.py::test_chunked_prefill_preempt test_chunked_prefill_scheduler.py::test_chunked_prefill_max_seqs 
test_scheduler.py::test_scheduler_prefill_prioritized test_scheduler.py::test_swapped_out_prioritized test_scheduler.py::test_prefill_schedule_token_budget test_scheduler.py::test_prefill_schedule_max_seqs
test_scheduler.py::test_prefill_schedule_max_lora test_scheduler.py::test_decode_schedule_preempted test_scheduler.py::test_decode_swap_beam_search test_scheduler.py::test_schedule_decode_blocks_to_copy_update 
test_scheduler.py::test_schedule_swapped_simple test_scheduler.py::test_schedule_swapped_max_token_budget test_scheduler.py::test_schedule_swapped_max_seqs test_scheduler.py::test_schedule_swapped_max_loras test_scheduler.py::test_schedule_swapped_cannot_swap_in test_scheduler.py::test_infeasible_swap test_scheduler.py::test_schedule_swapped_blocks_to_copy 

I found some other failures but they might be related to my local environment not supporting kernels like flash-infer and not to BlockManager V2.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by KuntaiDu** [comment]
mark
