### ISSUE TITLE
[Doc]: Using LoRA adapters

### ISSUE THREAD

**Issue by LIUKAI0815** [vllm-project/vllm#8725]
### 📚 The doc issue

VLLM supports  the local lora path instead of huggingface's lora path ?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Of couse, vllm can load local lora path.

**Comment by LIUKAI0815** [comment]
Thank you very much. The service is running successfully
