### ISSUE TITLE
Support for codellama

### ISSUE THREAD

**Issue by karrtikiyer-tw** [vllm-project/vllm#876]
Meta Released codellama recently, can someone advise how we can make vLLM work with codellama?

**Comment by JasmondL** [comment]
You could do the following.
`python -m vllm.entrypoints.api_server --model codellama/CodeLlama-7b-hf --trust-remote-code --tokenizer hf-internal-testing/llama-tokenizer`

**Comment by karrtikiyer-tw** [comment]
Thanks will try this out.Thanks and regards,KarrtikOn 29 Aug 2023, at 09:34, Jasmond L ***@***.***> wrote:﻿
You could do the following.
python -m vllm.entrypoints.api_server --model codellama/CodeLlama-7b-hf --trust-remote-code --tokenizer hf-internal-testing/llama-tokenizer

**Comment by WoosukKwon** [comment]
CodeLLaMA is supported, but it's not yet included in the latest official release of `transformers` (v4.32). Please install `transformers` (v4.33.0dev) from their repo.

**Comment by tjtanaa** [comment]
How to launch vllm that make use of 100k context length of CodeLLaMA?

**Comment by dragon-distributed** [comment]
> You could do the following. With the vllm==0.1.4 `python -m vllm.entrypoints.api_server --model codellama/CodeLlama-7b-hf --trust-remote-code --tokenizer hf-internal-testing/llama-tokenizer`

is llama-tokenzer impl the FIM?  Transformers implement the CodeLlamaTokenizer with FIM tokens, Which show in Code Llama tokenizer_config.json：https://huggingface.co/codellama/CodeLlama-13b-Python-hf/blob/main/tokenizer_config.json

**Comment by karrtikiyer-tw** [comment]
We can use ```--tokenizer hf-internal-testing/llama-code-tokenizer``` ?

**Comment by gelim** [comment]
Hello, any idea why this would generate garbage output for `temperature > 0` and just repeating the prompt without any addition with `temperature == 0` ?

I tested with:

```
python3.11 -m vllm.entrypoints.api_server --model codellama/CodeLlama-7b-hf --trust-remote-code --tokenizer hf-internal-testing/llama-tokenizer
```

as well as:

```
python3.11 -m vllm.entrypoints.api_server --model codellama/CodeLlama-7b-hf --trust-remote-code --tokenizer hf-internal-testing/llama-code-tokenizer
```

```
$ curl http://localhost:8000/generate \
            -d '{
        "prompt": "The most famous book of J.R.R. Tolkien is",
        "temperature": 0.1,
        "max_tokens": 50
}'
```


```
{"text":["The most famous book of J.R.R. Tolkien ishd Business pleasure canción Stock Mohból vieрюścierves Democratic Zum beskrevs PelΤiskaὶід}$.)}{nex програ FoiProgramкли Referencias nov laugh maven нап \",\"おskiereader bey
ondWrapperེ encryptionabinex统 goшње Catalunya totale сав
```


- vllm == 0.1.4
- transformers == 4.33.0.dev0
-  CUDA: 12.2 (driver 535.54.03)
- HW Tesla V100 (32GB)

The architecture for CodeLLama models is based on `LlamaForCausalLM` that is listed here: https://vllm.readthedocs.io/en/latest/models/supported_models.html, but the new model name is not explicitly mentioned, so I wonder if that's not supposed to be working as is with vLLM, or I just missed some obvious detail there.

NB: if using inference with `fastchat.serve.model_worker` ([FastChat](https://github.com/lm-sys/FastChat)) all is fine.

Thanks for any hint!

**Comment by gelim** [comment]
Ok the issue seems to be related to the fact the `torch_dtype: "bfloat16"` yields a CUDA error (arch 7.0 - the Tesla V100, are not supported), that I manually edited to `float16` to have the model loaded.

Interestingly this is not an issue when using fastchat model_worker.
