### ISSUE TITLE
loading models for distributed inference

### ISSUE THREAD

**Issue by amartino1** [vllm-project/vllm#879]
Hello. I am trying to use vLLM for distributed inference and am running into consistent runtime errors.

**Infrastructure:** 8xA100 GPUs
**Relevant versions:** Python 3.9.14, vllm 0.1.4, ray 2.6.3, NVIDIA-SMI Driver Version: 530.30.02, CUDA Version: 12.1  

**Sample code** I'm using, as referenced in quickstart [guide](https://vllm.readthedocs.io/en/latest/serving/distributed_serving.html)
`from vllm import LLM
llm = LLM("facebook/opt-13b", tensor_parallel_size=4)`

**Resulting error:**
`File "/home/amartino/.pyenv/versions/3.9.14/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1702, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.`

I also tried loading a different model (from a local file) and saw the same error. Is this an issue with CUDA 12 compatibility?

**Comment by KeremP** [comment]
According to the [docs](https://vllm.readthedocs.io/en/latest/getting_started/installation.html) only up to CUDA 11.8 is currently supported.

Could also be an outdated torch version(?). I would try `pip install vllm` in a clean environment with CUDA 11.8 and see if the issue still persists.

**Comment by amartino1** [comment]
ah ok. i don't think it should be torch, as I have v2.0.1 which is the [latest](https://pypi.org/project/torch/). I did try on a clean environment with Cuda 11.8 and the issue did not persist, so I'm taking it that Cuda compatibility is the issue.

Any idea if/when Cuda 12 will be supported?

**Comment by KeremP** [comment]
According to #385 the issue with CUDA 12 is that there are no PyTorch wheels prebuilt with cuda 12. Once PyTorch 2.1.0 is released, vllm should just be able to support cuda 12.
