### ISSUE TITLE
Runing API OOM

### ISSUE THREAD

**Issue by GasolSun36** [vllm-project/vllm#882]
Hi,
I use this command to craete an openai API, and receive OOM:
`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-70b-hf`

This seems to be caused by the fact that this command only defaults to the first GPU and my current node is 8 A100-40Gs. so it's causing OOM. Is there any way to make it load on multiple GPUs? I don't need a program, so I can't use the `tensor_parallel_size=8`.

**Comment by GasolSun36** [comment]
solved. closing this issues.

**Comment by yanmengxiang1** [comment]
@GasolSun36 
Hi, I want to interference Llama-70b-chat using 16 gpus. Can you tell me your command to run it?Thanks!

**Comment by GasolSun36** [comment]
> [yanmengxiang1](/yanmengxiang1)

python -m vllm.entrypoints.openai.api_server \
--model meta-llama/Llama-2-70b-chat-hf \
--tensor-parallel-size 8 \

I used single machine with 8*A100-40G, but I do not know how to run it with multiple machines.

**Comment by yanmengxiang1** [comment]
@GasolSun36 
My 16 gpus is in one machine. But I find that set `--tensor-parallel-size 16` appears error.#930
