### ISSUE TITLE
[Feature]: Support system messages for Multi Modal models

### ISSUE THREAD

**Issue by AshD** [vllm-project/vllm#8854]
### 🚀 The feature, motivation and pitch

When running **vllm serve meta-llama/Llama-3.2-11B-Vision-Instruct** and using the Open AI Vision API, I get a message

ERROR 09-26 07:37:07 serving_chat.py:155] Error in applying chat template from request: Prompting with images is incompatible with system messages.
INFO:     10.0.0.75:50436 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

Could you remove these restrictions for multi-modal models since the user wants to use them for both text queries and/or images. I have a COT prompt in the system message that I would like to keep.

### Alternatives

Open to suggestions as I have a COT prompt in the system message that I would like to keep.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by agt** [comment]
I haven't dug into the basis for the restriction with the model architecture, and would defer to others here with far more expertise, however:  

This system prompt limitation is baked into the Transformers chat template (see 'tokenizer_config.json') and confirmed in the official Meta [Llama 3.2 prompt docs](https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_2#-prompt-template-)

**Comment by AshD** [comment]
Thanks @agt for the quick and detailed response.

I am closing this issue but hopefully Future multi modal models will support the System Message and not make it a special case. 

For others - I added special handling to merge my COT system prompt into the user message and can confirm that this works.
