### ISSUE TITLE
GPTQ support

### ISSUE THREAD

**Issue by ryanshrott** [vllm-project/vllm#887]
Can I run a model with GPTQ quantization like this one from hugging face?

https://huggingface.co/TheBloke/CodeLlama-13B-oasst-sft-v10-GGUF

```
from transformers import AutoTokenizer, pipeline, logging
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

model_name_or_path = "TheBloke/Llama-2-13B-chat-GPTQ"
model_basename = "model"

use_triton = False

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, use_fast=True)

model = AutoGPTQForCausalLM.from_quantized(model_name_or_path,
        model_basename=model_basename,
        use_safetensors=True,
        trust_remote_code=True,
        device="cuda:0",
        use_triton=use_triton,
        quantize_config=None)
```

**Comment by SuperMasterBlasterLaser** [comment]
I hope they add [Exllama](https://github.com/turboderp/exllama) support

**Comment by ryanshrott** [comment]
Is this not supported?

**Comment by wejoncy** [comment]
Hi,
If anyone wants try GPTQ quantizationo in vLLM.
Please use this repo [QLLM](https://github.com/wejoncy/QLLM) to quantize model(LLama) and it would compatiable AWQ in vLLM.
And Of courcr you can select AWQ to quantize it as well.

**Comment by simon-mo** [comment]
Closing this issue as it is stale. We have added support both GPTQ and AWQ
