### ISSUE TITLE
Require more control on the max length of accept prompt

### ISSUE THREAD

**Issue by lockon-n** [vllm-project/vllm#888]
Hi, thanks for the wonderful vllm project.

In this file

https://github.com/vllm-project/vllm/blob/4b6f069b6fbb4f2ef7d4c6a62140229be61c5dd3/vllm/config.py#L119

we see that the max length is bounded by the config.json attached to the model. For example in llama-2, there is a `"max_position_embeddings": 4096` in its config. So in default vllm, the whole sequence (prompt+output) will always <4096.

However, sometimes I want to test the ability of length extrapolation for models, and my current solution is to manully edit the config.json, like `"max_position_embeddings": 4096` -> `"max_position_embeddings": 8192`.

So is it possible to add an extra, new argument that can set a larger value to `scheduler_config.max_model_len`, to handle this special use case?

Thanks in advance!

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
