### ISSUE TITLE
[Bug]: AssertionError When deploy API serve of Qwen2-VL-72B

### ISSUE THREAD

**Issue by niuwa2333** [vllm-project/vllm#8895]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.555.43
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.5.82
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.0.3
[pip3] sentence-transformers==3.1.1
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.0
[pip3] transformers-stream-generator==0.0.5
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.555.43                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.5.82                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.0.3                   pypi_0    pypi
[conda] sentence-transformers     3.1.1                    pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.45.0                   pypi_0    pypi
[conda] transformers-stream-generator 0.0.5                    pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
```

</details>

### 🐛 Describe the bug

<details>
  <summary>bash command of vllm</summary>
  <pre><code>
    CUDA_VISIBLE_DEVICES=2,3,4,5 vllm serve ./models/qwen-vl/qwen2-vl-72b-instruct --tensor-parallel-size 4
  </code></pre>
</details>

<details>
  <summary>The Error output</summary>
  <pre><code>
    INFO 09-27 15:11:19 api_server.py:164] Multiprocessing frontend to use ipc:///tmp/169e02dc-9b25-405d-b27c-8f4ac3083348 for IPC Path.
    INFO 09-27 15:11:19 api_server.py:177] Started engine process with PID 747048
    Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section'}
    ...
    assert "factor" in rope_scaling
    AssertionError
  </code></pre>
</details>

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by weiminw** [comment]
+1

**Comment by DarkLight1337** [comment]
You need to [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source-with-compilation) to use Qwen2-VL with `transformers>=4.45`.

**Comment by niuwa2333** [comment]
> You need to [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source-with-compilation) to use Qwen2-VL with `transformers>=4.45`.

install from source is slow, maybe caused by network unreachable when install flash-attn?

**Comment by ywang96** [comment]
Closing per @DarkLight1337's response.

**Comment by weiminw** [comment]
> You need to [install vLLM from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source-with-compilation) to use Qwen2-VL with `transformers>=4.45`.

that means fix not included in vllm 0.6.2？

**Comment by DarkLight1337** [comment]
Yeah, it's not in vLLM 0.6.2. The fix was applied after the release.

**Comment by caffeinetoomuch** [comment]
I believe `v0.6.2` should have `4.45`. I think this is the issue with `4.45`
