### ISSUE TITLE
Nos of input passed does not matches with the output

### ISSUE THREAD

**Issue by SP2203** [vllm-project/vllm#891]
I am using model **lmsys/vicuna-7b-v1.5**, but I am not getting a proper response. i.e. on passing 3 input prompts to the model 
with two prompts such that it exceeds the model's supported length. I am expecting vLLM to return 3 outputs from the model, but actually getting just 2 responses. We cannot map the response to the correct output if the order is not maintained.

I also tried different combinations where the input prompt length exceeded the permissible limit, a similar response was observed there. As vLLM does not do truncation of the input, but actually it drops the request [#447](https://github.com/vllm-project/vllm/issues/447#issuecomment-1639571226), I believe in that case vLLM should return " " as an output.

In some cases, we are getting an empty string as output, and in some cases, we don't.

Can this be fixed?

```
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

model_name = "lmsys/vicuna-7b-v1.5"
tokenizer = AutoTokenizer.from_pretrained(model_name, 
                                          trust_remote_code=True, 
                                          use_fast=True,
                                          )


llm = LLM(model=model_name, 
          trust_remote_code = True,
          tensor_parallel_size=1,
          max_num_batched_tokens=4096
         )

sampling_params = SamplingParams(max_tokens=100, 
                                 temperature=0.1, 
                                 top_k=100, 
                                 top_p=0.3,)



def get_vllm_response(text):

    outputs = llm.generate(text, sampling_params, use_tqdm=False)

    response = []    
    # Print the outputs.
    for output in outputs:
        response.append(output.outputs[0].text)
    
    return response

prompt_list = [
 "<prompt_1>", #   Input tokens is 4204
 "<prompt_2>", #   Input tokens is 1756
 "<prompt_3>", #   Input tokens is 4245
]

received_op = get_vllm_response(prompt_list)

expected_op = [
    "",                          # Exceeds Model's max seq limit
    "<output_2>",       # Within Model's max seq limit
    "",                          # Exceeds Model's max seq limit

]

received_op = [
     "<output_2>",
    "" 
]

len(prompt_list)==len(received_op)  => Returning False
```

**Comment by cosmicexotic** [comment]
I met the same issue!!

**Comment by SP2203** [comment]
I think if we truncate the prompts to the acceptable limit before passing it to vLLM then it's working fine

**Comment by nikolakopoulos** [comment]
What is the status of this?

**Comment by nikolakopoulos** [comment]
Any updates on this issue?

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
