### ISSUE TITLE
[Bug]: v0.6.2 Shows a Significant Accuracy Drop Serving Qwen2-VL Model

### ISSUE THREAD

**Issue by thiner** [vllm-project/vllm#8936]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>
I am sorry but I am not able to download this file https://raw.githubusercontent.com/vllm-project/vllm/main/collect_env.py on the server. Below information comes from my understanding of the server envrionment.

```text
Python: 3.12.6
Torch: 2.4.0
torchvision: 0.19.0
xformers: 0.0.27.post2
accerate: 0.34.2

nvidia-smi
Sat Sep 28 20:25:33 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.4     |
|-----------------------------------------+----------------------+----------------------+
```

</details>

### 🐛 Describe the bug

I was running Qwen2-vl-7b previously with `vllm-0.6.1-post2`, serving an agent which translate text on images. It's working perfectly. After upgrade vllm to `0.6.2`, I found that the accuracy of the OCR step drops significantly. It only outputs roughly 1/10 texts on the image. 
Besides, I found `vllm 0.6.2` requires `rope_scaling` parameter to be set to serve the Qwen2-vl model, which is not necessary while using `vllm-0.6.1-post2`. I don't know whether it's relevant, but put it here for your reference as well.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @fyabc

**Comment by ywang96** [comment]
@thiner I don’t think you should be able to serve Qwen2-VL with the out of box 0.6.2 docker image. Did you build from main branch of vLLM?

**Comment by thiner** [comment]
> @thiner I don’t think you’re able to serve Qwen2-VL with the out of box 0.6.2 docker image/Python library(and this was why we made #8837).
> 
> Did you build from main branch of vLLM?

Yes, I repacked the vllm docker image by installing the specified transformers PR. But I checked that the PR had been merged into transformers main branch and just released a new version saying that it supports Qwen2-VL officially. I checked the release date of transformers, it's earlier than vllm `v0.6.2` release date, so I assume the transformers library in vllm is up to date. Did I get it wrong here?

**Comment by DarkLight1337** [comment]
The timeline is:

1. Transformers released v4.45. However their release version has a bug that sets rope scaling in Qwen2-VL config to default instead of mrope
2. vLLM released v0.6.2 which depends on transformers v4.45, thus breaking Qwen2-VL usage. It is not possible to use older transformers version with vLLM v0.6.2 because it imports Llama-3.2 code from transformers at the top level.
3. We merged a PR which allows Qwen2-VL config to be loaded into vLLM once again.

**Comment by thiner** [comment]
@DarkLight1337 , thanks for your clarification. Then I will wait for the patch release.

**Comment by omercohen-glossai** [comment]
is this solved? im still getting very different logprobs for the same input on vllm and on transformers

**Comment by DarkLight1337** [comment]
Can you open a new issue and provide more information?
