### ISSUE TITLE
how to use Qwen-7b-chat

### ISSUE THREAD

**Issue by zouzoutingting** [vllm-project/vllm#896]
Can you show some examples to use Qwen-7b-chat with vllm ?
I've got unexpected result.

**Comment by lonngxiang** [comment]
> Can you show some examples to use Qwen-7b-chat with vllm ? I've got unexpected result.

have you run sucessed？

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
