### ISSUE TITLE
[Bug]: Vllm server (docker) fails to load mistralai/Mixtral-8x22B-Instruct-v0.1

### ISSUE THREAD

**Issue by ggbetz** [vllm-project/vllm#8995]
### Your current environment

docker pull vllm/vllm-openai:v0.6.2

### Model Input Dumps

docker run --runtime nvidia --gpus all \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=<secret>" \
    -p 8000:8000 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model mistralai/Mixtral-8x22B-Instruct-v0.1 \
    --tokenizer-mode mistral

### 🐛 Describe the bug

INFO 10-01 10:05:31 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='mistralai/Mixtral-8x22B-Instruct-v0.1', speculative_config=None, tokenizer='mistralai/Mixtral-8x22B-Instruct-v0.1', skip_tokenizer_init=False, tokenizer_mode=mistral, revision=main, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=main, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=mistralai/Mixtral-8x22B-Instruct-v0.1, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, mm_processor_kwargs=None)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 388, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 138, in from_engine_args
    return cls(
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 78, in __init__
    self.engine = LLMEngine(*args,
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 299, in __init__
    self.tokenizer = self._init_tokenizer()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 608, in _init_tokenizer
    return init_tokenizer_from_configs(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 28, in init_tokenizer_from_configs
    return get_tokenizer_group(parallel_config.tokenizer_pool_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizer_group/__init__.py", line 49, in get_tokenizer_group
    return tokenizer_cls.from_config(tokenizer_pool_config, **init_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 30, in from_config
    return cls(**init_kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py", line 23, in __init__
    self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizer.py", line 115, in get_tokenizer
    tokenizer = MistralTokenizer.from_pretrained(str(tokenizer_name),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizers/mistral.py", line 77, in from_pretrained
    tokenizer_file = cls._download_mistral_tokenizer_from_hf(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizers/mistral.py", line 97, in _download_mistral_tokenizer_from_hf
    filename = find_tokenizer_file(files)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/transformers_utils/tokenizers/mistral.py", line 36, in find_tokenizer_file
    raise OSError(f"Found {len(matched_files)} files matching the "
OSError: Found 0 files matching the pattern: {matched_files}. Make sure that a Mistral tokenizer is present in {tokenizer_name}.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ggbetz** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Ah nice catch! The tokenizer was named incorrectly in the repo I believe. Just fixed it here: https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1/blob/main/tokenizer.model.v3

Can you try again?

**Comment by ggbetz** [comment]
Thx for the quick fix! Works fine now. 😀 Closing this.

**Comment by cornzz** [comment]
@patrickvonplaten 
Same problem for `mistralai/Mistral-7B-v0.1`, the tokenizer file is called `tokenizer.model` but the regex is looking for a file ending with `.v.*` https://huggingface.co/mistralai/Mistral-7B-v0.1/tree/main

**Comment by brnrc** [comment]
@patrickvonplaten same issue for https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/tree/main.

**Comment by cornzz** [comment]
Quick fix for me was going into
```
~/.cache/hub/huggingface/hub/models--mistralai--Mistral-7B-v0.1/snapshots/7231864981174d9bee8c7687c24c8344414eae6b
```
and creating a new link
```
tokenizer.model.v1 -> ~/.cache/huggingface/hub/models--mistralai--Mistral-7B-v0.1/blobs/dadfd56d766715c61d2ef780a525ab43b8e6da4de6865bda3d95fdef5e134055
```
then setting `export HF_HUB_OFFLINE=1` and then running vllm...

**Comment by patrickvonplaten** [comment]
Hey @brnrc,

Thanks for the note - looking into it!

**Comment by abentabib** [comment]
Hello, any news on this ? I still have a error for mistralai/Mistral-7B-v0.1  

bash```OSError: Found 0 files matching the pattern: `^tokenizer\.model\.v.*$|^tekken\.json$|^tokenizer\.mm\.model\.v.*$`. Make sure that a Mistral tokenizer is present in ['.gitattributes', 'README.md', 'config.json', 'generation_config.json', 'model-00001-of-00002.safetensors', 'model-00002-of-00002.safetensors', 'model.safetensors.index.json', 'pytorch_model-00001-of-00002.bin', 'pytorch_model-00002-of-00002.bin', 'pytorch_model.bin.index.json', 'special_tokens_map.json', 'tokenizer.json', 'tokenizer.model', 'tokenizer_config.json']```

Patching the hugging face repo is not the solution ideally, the regex should allow "tokenizer.model"

**Comment by pgarec** [comment]
Hi @patrickvonplaten, found the same issue for [Mixtral-8x7B-Instruct-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/tree/main). I see there is no file named tokenizer.model.v3 as in [Mixtral-22B-Instruct-v0.1 ](https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1/tree/main), and it breaks the new vLLM version.

`OSError: Found 0 files matching the pattern: `^tokenizer\.model\.v.*$|^tekken\.json$|^tokenizer\.mm\.model\.v.*$`. Make sure that a Mistral tokenizer is present in ['model-00014-of-00019.safetensors', 'model-00007-of-00019.safetensors', 'model-00019-of-00019.safetensors', 'tokenizer.model', 'config.json', 'model-00004-of-00019.safetensors', 'model-00017-of-00019.safetensors', 'consolidated.01.pt', 'consolidated.06.pt', 'model-00002-of-00019.safetensors', '.gitattributes', 'tokenizer_config.json', 'model-00003-of-00019.safetensors', 'model-00008-of-00019.safetensors', 'model-00012-of-00019.safetensors', 'model.safetensors.index.json', 'consolidated.05.pt', 'consolidated.02.pt', 'model-00015-of-00019.safetensors', 'model-00018-of-00019.safetensors', 'special_tokens_map.json', 'model-00010-of-00019.safetensors', 'model-00009-of-00019.safetensors', 'consolidated.07.pt', 'consolidated.04.pt', 'consolidated.00.pt', 'consolidated.03.pt', 'README.md', 'model-00011-of-00019.safetensors', 'model-00016-of-00019.safetensors', 'model-00005-of-00019.safetensors', 'tokenizer.json', 'model-00013-of-00019.safetensors', 'model-00006-of-00019.safetensors', 'generation_config.json', '.cache', 'model-00001-of-00019.safetensors'].
`
