### ISSUE TITLE
Any plan to support Code Llama?

### ISSUE THREAD

**Issue by ltz0120** [vllm-project/vllm#900]
Thanks for your great work! 

However, the current vllm does not support Code Llama, and the output is nonsense. Do you have any plan to make such an update? I believe it will not take you much effort cause the architecture is similar to Llama.

**Comment by mayoor** [comment]
I am able to run code llama, specifically - codellama/CodeLlama-7b-Instruct-hf using vLLM. The only thing I had to do extra was to install from transformers using `pip install https://github.com/huggingface/transformers -U`. Do you mind pasting the logs?

**Comment by Jackal1586** [comment]
I faced similar issues:

I ran the server with the following command `python -m vllm.entrypoints.openai.api_server --model codellama/CodeLlama-34b-Instruct-hf --trust-remote-code`.

Then an API call:

`curl http://localhost:8000/v1/completions -H "Content-Type: application/json" -d '{
"model": "codellama/CodeLlama-34b-Instruct-hf",
"prompt": "Write a python code to calculate nth fibonacci number for a given n as input",
"max_tokens": 204,
"temperature": 0.3
}'`

The reponse:

`{"id":"cmpl-fffb1072e05a48ee98050c0883503714","object":"text_completion","created":1693384634,"model":"codellama/CodeLlama-34b-Instruct-hf","choices":[{"index":0,"text":".\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n","logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":19,"total_tokens":223,"completion_tokens":204}}`

Env:
vllm 0.1.4
transformer installed from github from the following commit: https://github.com/huggingface/transformers/commit/07998ef39926b76d3f6667025535d0859eed61c3 
pytorch '2.0.1+cu117'

**Comment by bohea** [comment]
same problem

**Comment by WoosukKwon** [comment]
Hi @ltz0120 @Jackal1586 @bohea, thanks for reporting the issue. We support CodeLLaMA. Could you try installing [vLLM from source](https://vllm.readthedocs.io/en/latest/getting_started/installation.html#build-from-source)?

**Comment by matheper** [comment]
For conversational instruction, try using the following prompt template:

```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ instruction }} [/INST]
```
For example:

```
<s>[INST] <<SYS>>

<</SYS>>

Write a python code to calculate nth fibonacci number for a given n as input [/INST]
```

**Comment by JeanStory** [comment]
I also encountered the same problem here, and also tried with the latest vllm code, the problem still exists.

The key to this problem is the inference result of codellama after loading is confusing,However,according to the official use case, it can work normally by directly using transfomer for parsing,So I guess it may be that vllm will Some additional adaptation work needs to be done.

**Comment by matheper** [comment]
Also, make sure you use the huggingface weights. Using safetensors format, it will output gibberish. See [issue 615](https://github.com/vllm-project/vllm/issues/615).

**Comment by godsakurapeng** [comment]
same problem, run without vllm is good and run with vllm the output is repeat.
- version 
transformers: ![image](https://github.com/vllm-project/vllm/assets/138603914/976a539e-c647-4fcb-a35f-de5a2487e9a2)
vllm: ![image](https://github.com/vllm-project/vllm/assets/138603914/67487ea2-4d78-41ae-a1a7-3cf19706b249)

- run without vllm<img width="1538" alt="企业微信截图_a6e7ecaa-8144-46dd-9db9-e6c3a689e334" src="https://github.com/vllm-project/vllm/assets/138603914/e71eb42d-b4d7-48b1-a5f5-713953ac100d">

- vllm output
![企业微信截图_1693811877411](https://github.com/vllm-project/vllm/assets/138603914/3eebd20d-0ee8-4348-99d6-482dbfa4832f)

**Comment by babytdream** [comment]
@matheper Hi, do you meet this question#951?thanks!

**Comment by murongweibo** [comment]
> same problem, run without vllm is good and run with vllm the output is repeat.
> 
> * version
>   transformers: ![image](https://user-images.githubusercontent.com/138603914/265604452-976a539e-c647-4fcb-a35f-de5a2487e9a2.png)
>   vllm: ![image](https://user-images.githubusercontent.com/138603914/265606034-67487ea2-4d78-41ae-a1a7-3cf19706b249.png)
> * run without vllm<img alt="企业微信截图_a6e7ecaa-8144-46dd-9db9-e6c3a689e334" width="1538" src="https://user-images.githubusercontent.com/138603914/265604209-e71eb42d-b4d7-48b1-a5f5-713953ac100d.png">
> * vllm output
>   ![企业微信截图_1693811877411](https://user-images.githubusercontent.com/138603914/265604723-3eebd20d-0ee8-4348-99d6-482dbfa4832f.png)

I have also encountered this issue, and now the output doesn't appear to be completely garbled, but there is often a repeated occurrence of '\n' at the end.
![image](https://github.com/vllm-project/vllm/assets/16189601/b9cb9ac9-5bb6-456e-992c-5da00d1e69e6)

**Comment by godsakurapeng** [comment]
> 

look like fix in this pr https://github.com/vllm-project/vllm/pull/1004, i will try it later

**Comment by godsakurapeng** [comment]
> > 
> 
> look like fix in this pr #1004, i will try it later

the output look good by update vllm : )
![image](https://github.com/vllm-project/vllm/assets/138603914/a10f58d7-2343-4a5d-a787-48198e539957)

**Comment by WoosukKwon** [comment]
@murongweibo Could you upgrade vLLM to v0.1.7?
```bash
pip install vllm --upgrade
```

**Comment by WoosukKwon** [comment]
@ltz0120 @Jackal1586 @bohea @babytdream @murongweibo  Thanks for reporting the bug. We believe this problem was fixed by adding safetensors support and fixing the precision problem in RoPE. Please try again with vLLM 0.1.7, and please us know if it does not work.
```bash
pip install vllm --upgrade
```

**Comment by bohea** [comment]
tested on 0.1.7, works well

**Comment by WoosukKwon** [comment]
@bohea Thanks for the confirmation!
