### ISSUE TITLE
[Doc]: Why is FP8 static quantization marked as deprecated?

### ISSUE THREAD

**Issue by dongluw** [vllm-project/vllm#9010]
### 📚 The doc issue

according to the doc https://docs.vllm.ai/en/latest/quantization/fp8.html#deprecated-flow
offline quantization using AutoFP8 is marked as deprecated, wondering what is the reason for this?
Is there any model quality or performance issue?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by mgoin** [comment]
Hi @dongluw this is because AutoFP8 is deprecated. We recommend going through [llm-compressor](https://github.com/vllm-project/llm-compressor) now, where we have [FP8 examples](https://github.com/vllm-project/llm-compressor/tree/main/examples/quantization_w8a8_fp8)

**Comment by flozi00** [comment]
It's only the autofp8 library what is deprecated 
Just use llmcompressor instead 
The fp8 quantization isn't deprecated itself

**Comment by dongluw** [comment]
@mgoin @flozi00 thanks for the reply.
My understanding there are two methods for FP8 quantization, static/offline and dynamic/online.
It seems [llm-compressor](https://github.com/vllm-project/llm-compressor) is only for dynamic quantization, and the static method is marked as deprecated.
In my experiments I noticed some difference in model quality and speed between these two methods.

Guess my question is, what is the reason for choosing dynamic over static (or llm-compressor over AutoFP8)?

**Comment by mgoin** [comment]
llm-compressor supports both static and dynamic quantization. While generally we recommend dynamic quantization for accuracy reasons, static is absolutely still an active use case.

On HF we publish both static and dynamic FP8 checkpoints for many models, so check the model creation section to see how the model is made
Static: https://huggingface.co/neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8
Dynamic: https://huggingface.co/neuralmagic/Meta-Llama-3.1-70B-Instruct-FP8-dynamic

**Comment by dongluw** [comment]
got it, thank you so much
