### ISSUE TITLE
Loading torch checkpoint

### ISSUE THREAD

**Issue by ghadiaravi13** [vllm-project/vllm#903]
Hi,
Is there a simpler way to directly load a torch saved checkpoint in vllm? (chkpt.pth.tar format)

**Comment by ghadiaravi13** [comment]
Figured out that saving it as model.save_pretrained on a local disk does work when loading using vllm.

**Comment by Zuckonit** [comment]
would please share your solution? @ghadiaravi13

**Comment by ghadiaravi13** [comment]
`model.save_pretrained('/path/to/my_model_checkpoint')
llm = LLM(model="/path/to/my_model_checkpoint")`

Note that this works because "model" is a huggingface model instance which has the save_pretrained method supported. For other pytorch models, this may not work.

**Comment by yhy-2000** [comment]
same problem
