### ISSUE TITLE
stuck at llm_engine.py:196

### ISSUE THREAD

**Issue by cosmicexotic** [vllm-project/vllm#904]
```
100%|████████████████████████████████████| 54584/54584 [00:06<00:00, 8619.58it/s]
INFO 08-29 20:48:52 llm_engine.py:70] Initializing an LLM engine with config: model='llama2-MultiTQ-20230829-01', tokenizer='llama2-MultiTQ-20230829-01', tokenizer_mode=auto, trust_remote_code=False, dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 08-29 20:48:52 tokenizer.py:29] For some LLaMA-based models, initializing the fast tokenizer may take a long time. To eliminate the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 08-29 20:49:14 llm_engine.py:196] # GPU blocks: 1981, # CPU blocks: 512
```
I use 54584 prompts, it stucks at llm_engine.py:196 for 30 more minutes.....did anyone  know how to solve this?

**Comment by WoosukKwon** [comment]
Hi @cosmicexotic, thanks for trying out vLLM and reporting the error. could you share your environment? E.g., which GPU(s) are you using? How much CPU memory do you have? Are you running vLLM in a container?

Also, could you try vLLM with a small number of prompts (say 10) and see if it still hangs?

**Comment by cosmicexotic** [comment]
> Hi @cosmicexotic, thanks for trying out vLLM and reporting the error. could you share your environment? E.g., which GPU(s) are you using? How much CPU memory do you have? Are you running vLLM in a container?
> 
> Also, could you try vLLM with a small number of prompts (say 10) and see if it still hangs?

Thanks for replying , I use 2 Tesla V100. Total CPU memory is 131472812 kB. I tried 1,000 prompts and it works well. But when it comes to 10,000 prompts , it hangs like above.

**Comment by WoosukKwon** [comment]
@cosmicexotic Got it... that is weird. How long are your prompts? BTW, did you use `n` > 1 for the sampling parameter?

**Comment by cosmicexotic** [comment]
> @cosmicexotic Got it... that is weird. How long are your prompts? BTW, did you use `n` > 1 for the sampling parameter?

Some of my prompts are over 4096 tokens, but most of them(90%) under 4096 tokens( Llama2 max token), my sampling parameter: sampling_params = SamplingParams(temperature=0, top_k=-1) where n equals 1 by default.

**Comment by WoosukKwon** [comment]
@cosmicexotic, thanks for sharing it. Could you also share how you set `max_num_batched_tokens`? This should be larger than any of your prompts.

**Comment by WoosukKwon** [comment]
> I set max_num_batched_tokens to 4096. When I test it on 1,000 prompts, when the prompt exceed this number, I receive a warning.

@cosmicexotic Then could you set `max_num_batched_tokens` to 8192 and try again?

**Comment by esmeetu** [comment]
@WoosukKwon i have same issue when  set max_num_batched_tokens to 8192.
The more tokens permitted, the more portability error encountered. And 4096 is fine.
i will post error message later.

**Comment by esmeetu** [comment]
2023-08-31 17:02:19,066	ERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::RayWorker.execute_method()[39m (pid=2186511, ip=xxx.xxx.xxx.xxx, actor_id=114ccd0590b28ed93faa256458000000, repr=<vllm.engine.ray_utils.RayWorker object at 0x7fa619f64eb0>)
  File "/home/dell/vllm/vllm/engine/ray_utils.py", line 25, in execute_method
    return executor(*args, **kwargs)
  File "/home/dell/miniconda3/envs/ray/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/vllm/vllm/worker/worker.py", line 293, in execute_model
    output = self.model(
  File "/home/dell/miniconda3/envs/ray/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dell/vllm/vllm/model_executor/models/llama.py", line 261, in forward
    next_tokens = self.sampler(self.lm_head.weight, hidden_states,
  File "/home/dell/miniconda3/envs/ray/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dell/vllm/vllm/model_executor/layers/sampler.py", line 89, in forward
    return _sample(probs, logprobs, input_metadata)
  File "/home/dell/vllm/vllm/model_executor/layers/sampler.py", line 391, in _sample
    next_token_ids = _sample_from_prompt(prob, sampling_params)
  File "/home/dell/vllm/vllm/model_executor/layers/sampler.py", line 305, in _sample_from_prompt
    next_token_ids = torch.multinomial(prob,
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by WoosukKwon** [comment]
Hi @esmeetu, thanks for reporting the error. Could you share the name of your model and the exact prompt so that we can reproduce?

**Comment by esmeetu** [comment]
> Hi @esmeetu, thanks for reporting the error. Could you share the name of your model and the exact prompt so that we can reproduce?

CodeLlama-13b-Instruct-hf

[D7E46629-453C-4fdc-8CFE-B156FF3DFE8B.txt](https://github.com/vllm-project/vllm/files/12505584/D7E46629-453C-4fdc-8CFE-B156FF3DFE8B.py)
