### ISSUE TITLE
vLLM doesn't support context length exceeding about 13k

### ISSUE THREAD

**Issue by Arist12** [vllm-project/vllm#905]
I use 4 A100 80G.
vLLM runs perfectly with my code when context length is up to 11k, but when it exceeds around 13k, I've got the error shown below:

```
RuntimeError: CUDA error: invalid argument 
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. 
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Given the fact that pure hf code can run up to that length with 4 A100*80G, it can be a memory-related issue, so I'm wondering what might be the issue. (I've set `max_num_batched_tokens` and `get_max_model_len` large enough)

**Comment by LiuXiaoxuanPKU** [comment]
Yeah, this is a known issue in vLLM, we are actively fixing this.

**Comment by adamydwang** [comment]
> 



> Yeah, this is a known issue in vLLM, we are actively fixing this.

Hi, xiaoxuan, how is the progress? When is it expected to be fixed?

**Comment by LiuXiaoxuanPKU** [comment]
Hi want to confirm here, did you run your code with the VLLM main branch or with this [pr](https://github.com/vllm-project/vllm/pull/555)?

**Comment by nicobasile** [comment]
Hi @LiuXiaoxuanPKU I'm also running into the same issue with `codellama/CodeLlama-34b-Instruct-hf` running from the main vLLM branch. API Server only returns 500 Internal Errors after receiving a request > 13k context length

**Comment by lonngxiang** [comment]
RuntimeError: CUDA error: no kernel image is available for execution on the device                                                                                                        
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.                                                                   
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.                                                                                                                                    
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by babytdream** [comment]
@Arist12 How can I make the context up to 11k? Are you using the` meta-llama2-70b-cha`t model?can you share your command？Thanks！

**Comment by Arist12** [comment]
> @Arist12 @nicobasile How can I make the context up to 11k? Are you using the` meta-llama2-70b-cha`t model?can you share your command？Thanks！

Hi, I use the meta-llama2-7b-chat model. All the llama-2 models originally supported a 4k context window. All you need to do is set `max_num_batched_tokens` and `get_max_model_len large` (you might directly overwrite this function or change the model configuration file) enough and find a long enough input prompt.

**Comment by babytdream** [comment]
![image](https://github.com/vllm-project/vllm/assets/74184102/7e896ee3-43c6-41d8-9fab-9b313aa83c18)
hi, I need to set `"max_length"` large in this config and set --max_num_batched_tokens large in command:`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-70b-hf --tensor-parallel-size 16 --max_num_batched_tokens 10000`.Right?Thanks.

**Comment by qianxuyidian-2018** [comment]
@LiuXiaoxuanPKU
 I suspect the issue may be related to 'shared_mem_size' in attention_kernels.cu. When the context is too long, this value may exceed the GPU's shared memory limit, but I don‘t know how to fix it.

`#define LAUNCH_ATTENTION_KERNEL(T, HEAD_SIZE, BLOCK_SIZE, NUM_THREADS)                        \
  vllm::single_query_cached_kv_attention_kernel<T, HEAD_SIZE, BLOCK_SIZE, NUM_THREADS>        \
  <<<grid, block, shared_mem_size, stream>>>(                                                 \`

**Comment by wangschang** [comment]
Is this issus fixed？

**Comment by zhuxiaobin** [comment]
> Yeah, this is a known issue in vLLM, we are actively fixing this.

same question, how's the progress?

**Comment by ShengdingHu** [comment]
Same Question, how's the progress?

**Comment by Yard1** [comment]
I opened a PR to mitigate it for now - this will allow >16k context length on most supported GPUs. https://github.com/vllm-project/vllm/pull/1154
