### ISSUE TITLE
[Bug]: Pixtral not working with vllm v0.6.2 docker

### ISSUE THREAD

**Issue by Syst3m1cAn0maly** [vllm-project/vllm#9068]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

Pixtral 12b does not work with the docker version of vllm v0.6.2 when using mistral tokenizer, it seems there is a missing OpenCV dependency :

ImportError: OpenCV is required for this function. Install it with 'pip install mistral_common[opencv]'

The model works fine with v0.6.1.post2

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
It has only been recently fixed in https://github.com/vllm-project/vllm/pull/8951. You should clone vLLM repo and use the Dockerfile inside the repo.
