### ISSUE TITLE
[Misc]: Need to understand support for torch.compile in Q4 roadmap

### ISSUE THREAD

**Issue by amd-abhikulk** [vllm-project/vllm#9072]
### Anything you want to discuss about vllm.

The Q4 roadmap https://github.com/vllm-project/vllm/issues/9006 suggests native support needs to be added for torch.compile. May I know for what exactly support is needed, I might be able to help

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by njhill** [comment]
@youkaichao

**Comment by youkaichao** [comment]
we are testing `torch.compile` support for all models, and control the compilation time. welcome to join our slack ( slack.vllm.ai ) to discuss more!
