### ISSUE TITLE
[Bug]: vllm overrides transformer's Autoconfig for mllama

### ISSUE THREAD

**Issue by lyuqin-scale** [vllm-project/vllm#9076]
### Your current environment

vllm 0.6.2

### 🐛 Describe the bug

This line overrides transformer's autoconfig for mllama, which should be removed
https://github.com/vllm-project/vllm/blob/e5dc713c2343b3549b43d6e2764a1036e4052bf8/vllm/transformers_utils/config.py#L41

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by heheda12345** [comment]
We override it only for changing `is_encoder_decoder=True`, as described [here](https://github.com/vllm-project/vllm/blob/26aa325f4ffe8bf1d9b921535cc02fb31d80a96d/vllm/transformers_utils/configs/mllama.py#L6-L8). Other parts are not modified.

**Comment by lyuqin-scale** [comment]
@heheda12345 but it does change the impact of AutoConfig if vllm is imported together
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/1d668497-d48f-4624-a9cb-1595f64ffa53">

**Comment by lyuqin-scale** [comment]
comparing with 
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/8d6290d6-9e5e-45f4-b642-35d9fa5c66a0">

**Comment by lyuqin-scale** [comment]
due to the above, transformer's AutoModelForPreTraining.from_pretrained failed
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/298c6b4f-639d-413a-b04f-81d55c4d0619">

**Comment by heheda12345** [comment]
For a quick fix, you can do something like [here](https://github.com/vllm-project/vllm/blob/26aa325f4ffe8bf1d9b921535cc02fb31d80a96d/tests/models/encoder_decoder/vision_language/test_mllama.py#L202) and [here](https://github.com/vllm-project/vllm/blob/26aa325f4ffe8bf1d9b921535cc02fb31d80a96d/tests/models/encoder_decoder/vision_language/test_mllama.py#L217)

We are thinking of how to make it cleaner.

**Comment by lyuqin-scale** [comment]
We've had temporarily workaround by explicitly using transformers.MllamaForConditionalGeneration to load the mllama model. But we believe a fix from vLLM side could benefit the other vLLM users who aren't aware of this override
