### ISSUE TITLE
Would RPyC be a good alternative of Ray?

### ISSUE THREAD

**Issue by LinPoly** [vllm-project/vllm#908]
Hi vLLM developers @WoosukKwon @zhuohan123 . I noticed that there is a plan to find alternative frameworks for distributed inference in the [RoadMap](https://github.com/vllm-project/vllm/issues/244). I think [RPyC](https://github.com/tomerfiliba-org/rpyc) maybe a good option for single machine scenario. RPyC is a concise RPC framework with basically no extra dependencies and its APIs are quite handy. RPyC is adopted by [lightllm](https://github.com/ModelTC/lightllm), a project parallel with vLLM, as its distributed backend and [this](https://github.com/ModelTC/lightllm/blob/main/lightllm/server/router/model_infer/model_rpc.py) is how it uses RPyC.

As mentioned in some issues, Ray will bring heavy overhead for single machine serving. RPyC maybe a lightweight alternative to it. If you are interested, I think I can help to add RPyC support, create a new PR and implement it.

**Comment by seanshi-scale** [comment]
I tried substituting Ray with RPyC at https://github.com/vllm-project/vllm/pull/1318, but wasn't able to get better performance. There's certainly more things that one could do to speed up RPyC, I don't really have time to work on it though. I feel like there's a few quirks with RPyC that makes this slower, e.g. the API it provides to send python objects over between processes and some tcp_nodelay setting that I had to patch in/expose.
