### ISSUE TITLE
how to set rope_scaling type to dynamic in vllm?

### ISSUE THREAD

**Issue by amulil** [vllm-project/vllm#910]

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.

**Comment by amulil** [comment]
the problem is not solved, it's needed to open.

**Comment by hmellor** [comment]
RoPE scaling was added in #555. 

Could you please provide more information in the description. Would you like the RoPE scaling factor to be automatically determined?

**Comment by amulil** [comment]
> RoPE scaling was added in #555.
> 
> Could you please provide more information in the description. Would you like the RoPE scaling factor to be automatically determined?

Thanks for your reply, I'll see it.
