### ISSUE TITLE
[Feature]: LLMEngine and ModelConfig explicitly require path or HF model id, but no InferenceClient class for locally running VLLM server

### ISSUE THREAD

**Issue by DanielViglione** [vllm-project/vllm#9110]
### 🚀 The feature, motivation and pitch

I reviewed the code for LLMEngine and ModelConfig. It only allows you to load the model from huggingface hub or from a local directory. However, in my langchain app, I use LCEL to chain runnables together, and I want to be able to invoke my locally run vllm server. Because the VLLM class that implements BaseLLM uses "VLLModel" and that in turn depends on LLMEngine and ModelConfig, there is no way to use an InferenceClient, similar to how langchain_huggingface does it.  I am ok to implement my own class for VLLM that implements langchain BaseLLM, but then I cannot use LLMEngine and ModelConfig at all and that removes the use of a ton of code. Aside from using OpenAI with VLLM, is there any plans to have an InferenceClient? 

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
I believe this is a question better suited for LangChain repo since we don't manage the integrations.
