### ISSUE TITLE
[Bug]: Installation from last commit (version wrong)

### ISSUE THREAD

**Issue by johnnynunez** [vllm-project/vllm#9119]
### Your current environment

Jetson AGX Orin
pytorch 2.4.0
Cuda 12.6 update 2

### 🐛 Describe the bug

Hello, if you try to build dev version from last commit, the version put it is wrong.
```
vllm-0.1.dev1+gb22b798.d20241006.cu126
```
It should be like the coming new version... vllm-0.6.3.dev+gb22b798.d20241006.cu126

why? because it seems that is old version from another repositories restrictions like llama-factory "vllm": ["vllm>=0.4.3,<=0.6.3"], so it is lower than vllm>=0.4.3
### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @dtrifiro

**Comment by dtrifiro** [comment]
What does `git describe --tags` show?
Did you fetch tags? `git fetch --tags`

**Comment by johnnynunez** [comment]
> git fetch --tags

<img width="732" alt="Captura de pantalla 2024-10-08 a les 22 39 51" src="https://github.com/user-attachments/assets/ecf24ef2-65e4-4a90-874e-78fa296ee533">

**Comment by dtrifiro** [comment]
By looking at your `build.sh`, when not using an exact tag (e.g. with `export VLLM_VERSION=0.6.2`) you're using `git clone --depth=1 --recursive https://github.com/vllm-project/vllm /opt/vllm`, meaning you don't have any tag information, so when you a build or manually invoke `setuptools_scm`, you get::

```shell
$ python -m setuptools_scm
Warning: could not use pyproject.toml, using default configuration.
 Reason: /tmp/vllmtmp1/pyproject.toml does not contain a tool.setuptools_scm section.
/tmp/vllmtmp/.venv/lib/python3.12/site-packages/setuptools_scm/git.py:167: UserWarning: "/tmp/vllmtmp1" is shallow and may cause errors
  warnings.warn(f'"{wd.path}" is shallow and may cause errors')
0.1.dev1+gc8627cd
```

If you fetch the tags for the shallow repo, the reported version will be correct:

```shell
$ git fetch --unshallow --tags
remote: Enumerating objects: 1933, done.
remote: Counting objects: 100% (1796/1796), done.
remote: Compressing objects: 100% (451/451), done.
remote: Total 1170 (delta 1001), reused 879 (delta 718), pack-reused 0 (from 0)
Receiving objects: 100% (1170/1170), 349.41 KiB | 3.88 MiB/s, done.
Resolving deltas: 100% (1001/1001), completed with 241 local objects.
$ python -m setuptools_scm
0.6.3.dev143+gc8627cd4
```

**Comment by johnnynunez** [comment]
> By looking at your `build.sh`, when not using an exact tag (e.g. with `export VLLM_VERSION=0.6.2`) you're using `git clone --depth=1 --recursive https://github.com/vllm-project/vllm /opt/vllm`, meaning you don't have any tag information, so when you a build or manually invoke `setuptools_scm`, you get::
> 
> ```shell
> $ python -m setuptools_scm
> Warning: could not use pyproject.toml, using default configuration.
>  Reason: /tmp/vllmtmp1/pyproject.toml does not contain a tool.setuptools_scm section.
> /tmp/vllmtmp/.venv/lib/python3.12/site-packages/setuptools_scm/git.py:167: UserWarning: "/tmp/vllmtmp1" is shallow and may cause errors
>   warnings.warn(f'"{wd.path}" is shallow and may cause errors')
> 0.1.dev1+gc8627cd
> ```
> 
> If you fetch the tags for the shallow repo, the reported version will be correct:
> 
> ```shell
> $ git fetch --unshallow --tags
> remote: Enumerating objects: 1933, done.
> remote: Counting objects: 100% (1796/1796), done.
> remote: Compressing objects: 100% (451/451), done.
> remote: Total 1170 (delta 1001), reused 879 (delta 718), pack-reused 0 (from 0)
> Receiving objects: 100% (1170/1170), 349.41 KiB | 3.88 MiB/s, done.
> Resolving deltas: 100% (1001/1001), completed with 241 local objects.
> $ python -m setuptools_scm
> 0.6.3.dev143+gc8627cd4
> ```

it is working now, thank you so much:
