### ISSUE TITLE
I want to close kv cache. if i set gpu_memory_utilization is 0. Does it means that i close the kv cache?

### ISSUE THREAD

**Issue by amulil** [vllm-project/vllm#912]

**Comment by WoosukKwon** [comment]
Hi @amulil, `gpu_memory_utilization` means the ratio of the GPU memory you want to allow for vLLM. vLLM will use it to store weights, allocate some workspace, and allocate KV cache. If it is set too low, vLLM won't work at all and you will see errors. To not see those errors and to get the best performance, set it as high as possible.

**Comment by amulil** [comment]
Does this mean that I can't turn off KV cache now? Turning on KV cache will cause the model to use historical data to generate answers every time. I don't want the model to use historical data to generate answers, so I want to turn off KV cache. Is there any configuration item in vllm that can turn off KV cache? @WoosukKwon

**Comment by amulil** [comment]
The use_cache flag can control the opening and closing of KV cache when loading the model in Hugging Face style. This configuration item is currently unavailable in vllm.

**Comment by WoosukKwon** [comment]
@amulil vLLM does not support `use_cache=False`. I believe there is no reason to disable KV cache because it is a pure optimization that significantly reduces the FLOPs of generation.

**Comment by WoosukKwon** [comment]
And please note that enabling KV cache never affects your model outputs.

**Comment by amulil** [comment]
> And please note that enabling KV cache never affects your model outputs.

I tested the hugging face model with use_cache. `use_cache=true` causes the output to be the same if I type the same thing multiple times in a multi-turn conversation, but if I set `use_cache=false`, the output is different even if I type the same thing multiple times.

**Comment by rajeevbaalwan** [comment]
> And please note that enabling KV cache never affects your model outputs.

@WoosukKwon I'm getting different output almost 10-15% of the time when the KV cache is enabled with my Finetuned LLM. Output is correct whenever inferred without any optimization technique. Is there a way to disable KV Caching in vLLM?

**Comment by Sankethhhh** [comment]
@WoosukKwon , Can we clear the KV cache in the GPU after prompting? I see that the GPU usage keeps increasing with every prompting. Is there any other solution for this?

**Comment by nightflight-dk** [comment]
folks, clearing (or disabling / closing) the KV cache can be an optimization as well, if it prevents one from reloading the engine for every config change when tuning latency and throughput right? please recognize the feature request, thank you

**Comment by gamersover** [comment]
Hi there, I've got a question, why does my gpu memory slowly get full over time after handling a bunch of requests?

**Comment by gnalbandyan** [comment]
Is there any update on this? If no, will manually setting layer_i..self_attn.attn.kv_cache=[torch.tensor([], device='cuda')] be a workaround?

**Comment by mokeyish** [comment]
> Is there any update on this? If no, will manually setting layer_i..self_attn.attn.kv_cache=[torch.tensor([], device='cuda')] be a workaround?

Please use llamacpp instead, vllm is designed to occupy more GPU memory.

**Comment by gnalbandyan** [comment]
I am doing this for local experiments, not for production like environments. I just want to turn off kv_cache temporarily, will setting kv_cache to empty list work?

**Comment by Tobs40** [comment]
I'd also very much like this feature. My production pipeline has 0,1% KV-Cache hitrate, I'd rather have a bit more VRAM. (Model just answers one token yes/no)

**Comment by hmellor** [comment]
The KV cache needs at least 1x the maximum sequence length. If you want to fit a larger model can simply reduce `--max-mode-len` to longest request (prompt + output, in tokens) your system might recieve. Then the memory required by this 1x sequence of KV cache will be smaller and you can use more memory for model weights. You could also use `--enforce-eager` to get a few more GB by not having to store compiled graphs in VRAM.

**Comment by wsmlby** [comment]
I think turning off KV-cache is a legit request. KV is useful when we expect future query to share prefix with previous queries, this is usually the case when we are doing turn based memory like a chatbot. But there maybe new kind of LLM applications that doesn't share common prefixes, making KV cache hit rate to be low enough that the extra memory usage is not worth it. 
Please take this into account and consider this feature request.

**Comment by hmellor** [comment]
KV caching is not the same as prefix caching:

- KV cache hit rate is 100% for every request that generates >1 token
- Prefix caching shares the KV cache between requests with common prefixes

**Comment by saeid93** [comment]
Has there been any update on this?
