### ISSUE TITLE
[New Model]: silma-ai/SILMA-9B-Instruct-v1.0

### ISSUE THREAD

**Issue by hassanraha** [vllm-project/vllm#9125]
### The model to consider.

https://huggingface.co/silma-ai/SILMA-9B-Instruct-v1.0

### The closest model vllm already supports.

google/gemma-2-9b

### What's your difficulty of supporting the model you want?

It is arabic model and may have different way of handling the tokens

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
This model uses `Gemma2ForCausalLM` architecture without custom model definition, so it can be directly used in vLLM. Have you tried doing so?

**Comment by hassanraha** [comment]
Yeah, just now tried it in runpod instance. It works out of the box in `v0.6.2`. Thanks
