### ISSUE TITLE
[Bug]: assert len(indices) == len(inputs) with `Qwen/Qwen2-VL-2B-Instruct`

### ISSUE THREAD

**Issue by sayakpaul** [vllm-project/vllm#9128]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
WARNING 10-07 17:28:06 cuda.py:76] Detected different devices in the system: 
WARNING 10-07 17:28:06 cuda.py:76] NVIDIA A100-SXM4-80GB
WARNING 10-07 17:28:06 cuda.py:76] NVIDIA A100-SXM4-80GB
WARNING 10-07 17:28:06 cuda.py:76] NVIDIA A100-SXM4-80GB
WARNING 10-07 17:28:06 cuda.py:76] NVIDIA DGX Display
WARNING 10-07 17:28:06 cuda.py:76] NVIDIA A100-SXM4-80GB
WARNING 10-07 17:28:06 cuda.py:76] Please make sure to set `CUDA_DEVICE_ORDER=PCI_BUS_ID` to avoid unexpected behavior.
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.27.0
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jul 17 2023, 11:18:22) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-166-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.3.52
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA DGX Display
GPU 4: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             128
On-line CPU(s) list:                0-127
Thread(s) per core:                 2
Core(s) per socket:                 64
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7742 64-Core Processor
Stepping:                           0
Frequency boost:                    enabled
CPU MHz:                            2608.221
CPU max MHz:                        2250,0000
CPU min MHz:                        1500,0000
BogoMIPS:                           4491.62
Virtualization:                     AMD-V
L1d cache:                          2 MiB
L1i cache:                          2 MiB
L2 cache:                           32 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-127
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.77
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.1
[pip3] triton==3.0.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.3.dev116+g151ef4ef
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
[4mGPU0	GPU1	GPU2	GPU3	GPU4	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	NV4	NV4	SYS	NV4	0-127	0		N/A
GPU1	NV4	 X 	NV4	SYS	NV4	0-127	0		N/A
GPU2	NV4	NV4	 X 	SYS	NV4	0-127	0		N/A
GPU3	SYS	SYS	SYS	 X 	PHB	0-127	0		N/A
GPU4	NV4	NV4	NV4	PHB	 X 	0-127	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

```

</details>

### 🐛 Describe the bug

Trying to run:

```py
from vllm import LLM, SamplingParams
from PIL import Image


if __name__ == "__main__":
    vllm_engine = LLM("Qwen/Qwen2-VL-2B-Instruct")
    sampling_params = SamplingParams(max_tokens=120)
    
    prompt = "Describe this image."
    vllm_inputs = [{"prompt": prompt, "multi_modal_data": {"image": Image.new("RGB", (224, 224))}} for _ in range(4)]
    outputs = vllm_engine.generate(vllm_inputs, sampling_params)
    print(outputs)
```

Leads to:

```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sayak/diffusers/check_video_vllm.py", line 23, in <module>
[rank0]:     outputs = vllm_engine.generate(vllm_inputs, sampling_params)
[rank0]:   File "/home/sayak/vllm/vllm/utils.py", line 1060, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 376, in generate
[rank0]:     self._validate_and_add_requests(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 831, in _validate_and_add_requests
[rank0]:     self._add_request(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 849, in _add_request
[rank0]:     self.llm_engine.add_request(
[rank0]:   File "/home/sayak/vllm/vllm/utils.py", line 1060, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/sayak/vllm/vllm/engine/llm_engine.py", line 812, in add_request
[rank0]:     processed_inputs = self.input_processor(preprocessed_inputs)
[rank0]:   File "/home/sayak/vllm/vllm/inputs/registry.py", line 299, in process_input
[rank0]:     return processor(InputContext(model_config), inputs,
[rank0]:   File "/home/sayak/vllm/vllm/model_executor/models/qwen2_vl.py", line 857, in input_processor_for_qwen2_vl
[rank0]:     prompt_token_ids = _expand_pad_tokens(image_inputs,
[rank0]:   File "/home/sayak/vllm/vllm/model_executor/models/qwen2_vl.py", line 780, in _expand_pad_tokens
[rank0]:     assert len(indices) == len(inputs)
[rank0]: AssertionError
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You should follow the prompt template as shown in their [HuggingFace repo](https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct). The easiest way is to use `LLM.chat` method so you don't have to manually apply the chat template.

**Comment by sayakpaul** [comment]
If I were to use `LLM.chat()` interface, how should I use `multi_modal_data()`?

**Comment by DarkLight1337** [comment]
Please read the examples on their HuggingFace repo. The format of `messages` in `LLM.chat` is the same as theirs.

**Comment by sayakpaul** [comment]
Modified my code:

```python
from vllm import LLM, SamplingParams
from PIL import Image


if __name__ == "__main__":
    vllm_engine = LLM("Qwen/Qwen2-VL-2B-Instruct")
    sampling_params = SamplingParams(max_tokens=120)

    num_images = 3
    messages = [{"role": "user", "content": []}]
    for _ in range(num_images):
        new_image = {"type": "image", "image": Image.new("RGB", (224, 224))}
        messages[0]["content"].append(new_image)

    messages[0]["content"].append({"type": "text", "text": "Describe this image."})

    outputs = vllm_engine.chat(messages, sampling_params)
    print(outputs)
```

Now it leads to:

```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sayak/diffusers/check_video_vllm.py", line 32, in <module>
[rank0]:     outputs = vllm_engine.chat(messages, sampling_params)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 556, in chat
[rank0]:     conversation, mm_data = parse_chat_messages(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 487, in parse_chat_messages
[rank0]:     sub_messages = _parse_chat_message_content(msg, mm_tracker)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 440, in _parse_chat_message_content
[rank0]:     result = _parse_chat_message_content_parts(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 402, in _parse_chat_message_content_parts
[rank0]:     raise NotImplementedError(f"Unknown part type: {part_type}")
[rank0]: NotImplementedError: Unknown part type: image
```

**Comment by DarkLight1337** [comment]
```py
    for _ in range(num_images):
        new_image = {"type": "image", "image": Image.new("RGB", (224, 224))}
        messages[0]["content"].append(new_image)
```

You should pass an `image_url` in the form of HTTP URL or base64 URL. This is similar to OpenAI API.

**Comment by sayakpaul** [comment]
Alright. 

I will try that and report here but I think https://github.com/vllm-project/vllm/issues/9128#issuecomment-2397376788 is misleading then. I did follow the exact "messages" formatting.

**Comment by DarkLight1337** [comment]
> You should follow the prompt template as shown on their [HuggingFace repo](https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct). The easiest way is to use `LLM.chat` method so you don't have to manually apply the chat template.

Sorry, I missed the slight difference in the image format. Hope that everything is cleared up now!

**Comment by exceedzhang** [comment]
I tested Qwen2-VL-7B-Instruct work fine, but tested Qwen2-VL-72B-Instruct-GPTQ-Int4 error!
<img width="1360" alt="image" src="https://github.com/user-attachments/assets/ab718d79-871c-4024-b831-0e7a7a491c1f">

**Comment by exceedzhang** [comment]
I tested Qwen2-VL-2B-Instruct working well!
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/60eb9ac2-4048-4dee-a433-a5b34ec362e0">

**Comment by DarkLight1337** [comment]
> I tested Qwen2-VL-7B-Instruct work fine, but tested Qwen2-VL-72B-Instruct-GPTQ-Int4 error!
> <img width="1360" alt="image" src="https://github.com/user-attachments/assets/ab718d79-871c-4024-b831-0e7a7a491c1f">
> 

Can you check whether both repos have a correctly defined chat template?

**Comment by sayakpaul** [comment]
With

```py
def encode_image(image):
    buffered = io.BytesIO()
    image.save(buffered, format="JPEG")
    image_bytes = buffered.getvalue()
    return base64.b64encode(image_bytes).decode("utf-8")

num_images = 3
messages = [{"role": "user", "content": []}]
for _ in range(num_images):
    base64_image = encode_image(Image.new("RGB", (224, 224)))
    new_image = {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
    messages[0]["content"].append(new_image)

messages[0]["content"].append({"type": "text", "text": "Describe this image."})
```

I get:

```bash
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/sayak/diffusers/check_video_vllm.py", line 41, in <module>
[rank0]:     outputs = vllm_engine.chat(messages, sampling_params)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 556, in chat
[rank0]:     conversation, mm_data = parse_chat_messages(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 487, in parse_chat_messages
[rank0]:     sub_messages = _parse_chat_message_content(msg, mm_tracker)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 440, in _parse_chat_message_content
[rank0]:     result = _parse_chat_message_content_parts(
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 392, in _parse_chat_message_content_parts
[rank0]:     mm_parser.parse_image(image_url["url"])
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 276, in parse_image
[rank0]:     placeholder = self._tracker.add("image", image)
[rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 205, in add
[rank0]:     raise ValueError(
[rank0]: ValueError: At most 1 image(s) may be provided in one request.
```

What am I missing out on?

**Comment by DarkLight1337** [comment]
> With
> 
> ```py
> def encode_image(image):
>     buffered = io.BytesIO()
>     image.save(buffered, format="JPEG")
>     image_bytes = buffered.getvalue()
>     return base64.b64encode(image_bytes).decode("utf-8")
> 
> num_images = 3
> messages = [{"role": "user", "content": []}]
> for _ in range(num_images):
>     base64_image = encode_image(Image.new("RGB", (224, 224)))
>     new_image = {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
>     messages[0]["content"].append(new_image)
> 
> messages[0]["content"].append({"type": "text", "text": "Describe this image."})
> ```
> 
> I get:
> 
> ```bash
> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/sayak/diffusers/check_video_vllm.py", line 41, in <module>
> [rank0]:     outputs = vllm_engine.chat(messages, sampling_params)
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/llm.py", line 556, in chat
> [rank0]:     conversation, mm_data = parse_chat_messages(
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 487, in parse_chat_messages
> [rank0]:     sub_messages = _parse_chat_message_content(msg, mm_tracker)
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 440, in _parse_chat_message_content
> [rank0]:     result = _parse_chat_message_content_parts(
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 392, in _parse_chat_message_content_parts
> [rank0]:     mm_parser.parse_image(image_url["url"])
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 276, in parse_image
> [rank0]:     placeholder = self._tracker.add("image", image)
> [rank0]:   File "/home/sayak/vllm/vllm/entrypoints/chat_utils.py", line 205, in add
> [rank0]:     raise ValueError(
> [rank0]: ValueError: At most 1 image(s) may be provided in one request.
> ```
> 
> What am I missing out on?

Please check our docs on using VLMs. There is a section on how to input multiple images per prompt.

**Comment by sayakpaul** [comment]
I am following https://docs.vllm.ai/en/stable/models/vlm.html and I am still really not sure what I am missing out here. A bit more specificity in your replies would be appreciated.

**Comment by DarkLight1337** [comment]
> I am following https://docs.vllm.ai/en/stable/models/vlm.html and I am still really not sure what I am missing out here. A bit more specificity in your replies would be appreciated. 

You need to set `limit_mm_per_prompt`, as shown [here](https://docs.vllm.ai/en/latest/models/vlm.html#multi-image-input)

**Comment by sayakpaul** [comment]
Thanks!

This is my full example and it works:

```python
from vllm import LLM, SamplingParams
from decord import VideoReader, cpu
from PIL import Image
import base64
import io
from huggingface_hub import hf_hub_download

NUM_MAX_FRAMES = 4

def encode_image(image):
    buffered = io.BytesIO()
    image.save(buffered, format="JPEG")
    image_bytes = buffered.getvalue()
    return base64.b64encode(image_bytes).decode("utf-8")

def load_video(num_max_frames=4):
    video_filepath = hf_hub_download(
        repo_id="huggingface/documentation-images", repo_type="dataset", filename="diffusers/hiker.mp4"
    ) 
    vr = VideoReader(video_filepath, ctx=cpu(0))
    video_frames = [Image.fromarray(vr[i].asnumpy()) for i in range(len(vr))][:num_max_frames]
    return video_frames

if __name__ == "__main__":
    # Use a limit of 4 frames.
    vllm_engine = LLM("Qwen/Qwen2-VL-2B-Instruct", limit_mm_per_prompt={"image": NUM_MAX_FRAMES})
    sampling_params = SamplingParams(max_tokens=120)

    # Video.
    video_frames = load_video(num_max_frames=NUM_MAX_FRAMES)
    messages = [{"role": "user", "content": []}]
    messages[0]["content"].append({"type": "text", "text": "Describe this set of frames. Consider the frames to be a part of the same video."})
    for i in range(len(video_frames)):
        base64_image = encode_image(video_frames[i])
        new_image = {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
        messages[0]["content"].append(new_image)

    outputs = vllm_engine.chat(messages, sampling_params)
    with open("qwen.txt", "w") as f:
        print(outputs, file=f)
```

The script shows inferencing on videos. Do you think it could be made a part of the docs?

**Comment by DarkLight1337** [comment]
> Thanks!
> 
> This is my full example and it works:
> 
> ```python
> from vllm import LLM, SamplingParams
> from decord import VideoReader, cpu
> from PIL import Image
> import base64
> import io
> from huggingface_hub import hf_hub_download
> 
> NUM_MAX_FRAMES = 4
> 
> def encode_image(image):
>     buffered = io.BytesIO()
>     image.save(buffered, format="JPEG")
>     image_bytes = buffered.getvalue()
>     return base64.b64encode(image_bytes).decode("utf-8")
> 
> def load_video(num_max_frames=4):
>     video_filepath = hf_hub_download(
>         repo_id="huggingface/documentation-images", repo_type="dataset", filename="diffusers/hiker.mp4"
>     ) 
>     vr = VideoReader(video_filepath, ctx=cpu(0))
>     video_frames = [Image.fromarray(vr[i].asnumpy()) for i in range(len(vr))][:num_max_frames]
>     return video_frames
> 
> if __name__ == "__main__":
>     # Use a limit of 4 frames.
>     vllm_engine = LLM("Qwen/Qwen2-VL-2B-Instruct", limit_mm_per_prompt={"image": NUM_MAX_FRAMES})
>     sampling_params = SamplingParams(max_tokens=120)
> 
>     # Video.
>     video_frames = load_video(num_max_frames=NUM_MAX_FRAMES)
>     messages = [{"role": "user", "content": []}]
>     messages[0]["content"].append({"type": "text", "text": "Describe this set of frames. Consider the frames to be a part of the same video."})
>     for i in range(len(video_frames)):
>         base64_image = encode_image(video_frames[i])
>         new_image = {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
>         messages[0]["content"].append(new_image)
> 
>     outputs = vllm_engine.chat(messages, sampling_params)
>     with open("qwen.txt", "w") as f:
>         print(outputs, file=f)
> ```
> 
> The script shows inferencing on videos. Do you think it could be made a part of the docs? 

Feel free to open a PR. Do note however that this case is still technically multi-image input (we have different API for single-video and multi-video input, and currently it is limited to offline inference only unlike multi-image case)

**Comment by sayakpaul** [comment]
Sure! 

Do you have a link to the documentation where you think this would be the most suitable? I think we could include this example in https://docs.vllm.ai/en/latest/models/vlm.html#multi-image-input it self. WDYT? 

> we have different API for single-video and multi-video input, and currently it is limited to offline inference only, unlike multi-image case)

Do you have a link for me to look further?

**Comment by DarkLight1337** [comment]
> Do you have a link to the documentation where you think this would be the most suitable? I think we could include this example in https://docs.vllm.ai/en/latest/models/vlm.html#multi-image-input it self. WDYT? 

Yes, that sounds good.

> 
> > we have different API for single-video and multi-video input, and currently it is limited to offline inference only, unlike multi-image case)
> 
> Do you have a link for me to look further? 

See #7558

**Comment by sayakpaul** [comment]
@DarkLight1337 https://github.com/vllm-project/vllm/pull/9155.

**Comment by vedrusss** [comment]
Hi @sayakpaul ,
How much GPU memory is occupied by the model for 4 image captioning?
I'm trying to run **Qwen/Qwen2-VL-2B-Instruct** on the instance with 4 GPUs each ~23Gb and face 'cuda out of memory'.
When I do just `LLM(model="Qwen/Qwen2-VL-2B-Instruct")` it loads and takes <5Gb. But doesn't accept an image.
But when I run `LLM(model="Qwen/Qwen2-VL-2B-Instruct", limit_mm_per_prompt={"image":1})` I'm facing cuda out of memory.
Adding `tensor_parallel_size=4` doesn't help.
