### ISSUE TITLE
[Bug]: vllm much slower on long context inputs when using --enable-lora even when lora is not used

### ISSUE THREAD

**Issue by badrjd** [vllm-project/vllm#9143]
### Your current environment

<details>

`docker pull vllm/vllm-openai:v0.6.2`

</details>

### 🐛 Describe the bug

When using `--enable-lora`, vllm output generation speed goes dramatically down.

I've ran an experiment with the following parameters:

```bash
--model hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4 --dtype half --max-model-len 48000 --gpu-memory-utilization 0.99 --block-size 16 --enable-prefix-caching --served-model-name gpt-3.5-turbo --enable-lora --max-loras 1 --max-lora-rank 64 --lora-modules test-module=/models/my-module
```

Using docker `vllm/vllm-openai:v0.6.2`

Running this on an A100 80GB.

When running without enabling lora with an input of 9k tokens, I get a generation speed of around 27 tokens/s.
When enabling lora, not specifying any adapter and same input, the generation speed is 5 tokens/s.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
I will try to reproduce your results.

**Comment by jeejeelee** [comment]
I cannot reproduce the result you reported. I suspect it might be due to the influence of prefix caching. The impact of LoRA(just using `--enable-lora`) is not very significant.
![image](https://github.com/user-attachments/assets/67af4283-8c9f-4f83-bce8-c03fed8a4576)

**Comment by badrjd** [comment]
Thank you for running the experiment @jeejeelee 

I tried to enable and disable context caching and it didn't change the dramatic drops that I've seen.

I've observed the dramatic drop at 9k tokens though, so maybe the experiment should be run with 16k as well?

I also assign the path to one lora module, I will try on my side to see what happens when I assign no path.

**Comment by badrjd** [comment]
I've observed the same behaviour with a simpler setup:

```bash
--model hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4 --dtype half --max-model-len 48000 --gpu-memory-utilization 0.99 --block-size 16--served-model-name gpt-3.5-turbo --enable-lora
```

-> 20 tokens/s

```bash
--model hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4 --dtype half --max-model-len 48000 --gpu-memory-utilization 0.99 --block-size 16--served-model-name gpt-3.5-turbo
```

-> 5 tokens/s

**Comment by jeejeelee** [comment]
@badrjd  I didn't use the above image for testing. I built it locally based on the main branch. Maybe you could try that.

**Comment by cmccxll** [comment]
the same problem

**Comment by jeejeelee** [comment]
> the same problem
@cmccxll     Are you also using the above image for testing?

**Comment by jeejeelee** [comment]
@badrjd  Has this issue been resolved for you? If not, you can try adding `--max-seq-len-to-capture 48000`.It's most likely due to this reason

**Comment by badrjd** [comment]
@jeejeelee I've ran some tests on the container with `v0.6.3.post1`. When l I added `--max-seq-len-to-capture 48000` the issue was fixed.

Thank you for your help!

**Comment by Daya-Jin** [comment]
> @badrjd Has this issue been resolved for you? If not, you can try adding `--max-seq-len-to-capture 48000`.It's most likely due to this reason

some explain?

> @badrjd Has this issue been resolved for you? If not, you can try adding `--max-seq-len-to-capture 48000`.It's most likely due to this reason

is there any explanations? due to the Triton backend? Is this param ```max-seq-len-to-capture``` must be set if I use lora inference?

**Comment by jeejeelee** [comment]
> > @badrjd Has this issue been resolved for you? If not, you can try adding `--max-seq-len-to-capture 48000`.It's most likely due to this reason
> 
> is there any explanations? due to the Triton backend? Is this param `max-seq-len-to-capture` must be set if I use lora inference?

The root cause is that when the sequence length exceeds `max-seq-len-to-capture`, it will fall back to eager mode, which affects LoRA performance. 

It is indeed due to the triton runtime overhead. The default value for `max-seq-len-to-capture` is 8192. You don't need to set it if your input length + generation length doesn't exceed this default  value
