### ISSUE TITLE
[Installation]: pip install vllm-0.6.2.zip err:setuptools-scm was unable to detect version for /tmp/pip-req-build-7ptioibj

### ISSUE THREAD

**Issue by uRENu** [vllm-project/vllm#9182]
### Your current environment

```text
pip install auto_gptq modelscope xformers==0.0.27.post2 torchvision==0.19 torchaudio torch==2.4.0 torchtext numpy wheel
pip install setuptools>=74.1.1 setuptools_scm==8.1.0 pyportfolioopt
pip install "pillow==10.*" -U
pip install sentencepiece charset_normalizer cpm_kernels tiktoken -U
pip install matplotlib scikit-learn tqdm tensorboard -U
pip install datasets huggingface-hub transformers==4.45.0 -U
pip install accelerate transformers_stream_generator -U
pip install pydantic==1.7.4 typer==0.3.0
pip install fastrlock cupy-cuda11x==12.1.0 
pip install vllm-flash-attn==2.6.1 datamodel_code_generator
```

### How you are installing vllm

```sh
pip install vllm-0.6.2.zip
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by uRENu** [comment]
err:

Processing vllm-0.6.2.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      /tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
        cpu = _conversion_method_template(device=torch.device("cpu"))
      Traceback (most recent call last):
        File "/home/wangrenzhong/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/wangrenzhong/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/wangrenzhong/anaconda3/envs/py310/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 485, in <module>
        File "<string>", line 357, in get_vllm_version
        File "/tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 158, in get_version
          _version_missing(config)
        File "/tmp/pip-build-env-nr7os5qd/overlay/lib/python3.10/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /tmp/pip-req-build-caovnllw.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by DarkLight1337** [comment]
cc @dtrifiro

**Comment by dtrifiro** [comment]
Are you trying to build from source? If so, the error is telling you what's wrong:

```
  Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
  
  For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
  [end of output]
  ```

Which can be solved by installing from a git+https ref:
```
pip install git+https://github.com/vllm-project/vllm@v0.6.2
```

If you're not trying to build from source, I recommend installing the prebuilt wheel

**Comment by simon-mo** [comment]
Hmm can we still make this workflow work? I would imagine there are folks trying to vendor vLLM without git.

**Comment by dtrifiro** [comment]
@simon-mo 

The right way to provide a tarball, is building a source distribution:

```bash
python setup.py sdist
# or, if using modern tools:
python -m build --sdist
```
this will create a tar archive which can be built. It will look something like this: `vllm-0.6.3.dev146+g9b064faa6.d20241010.tar.gz`

Another approach would be hacking `setup.py` to ignore the `LookupError`:

```python
    try:
        version = get_version(
        write_to="vllm/_version.py",  # TODO: move this to pyproject.toml
    )
    except LookupError:
        version = "0.0.0"
```

Although this is not ideal:
- this is hacky
- we lose any kind of versioning information
- this would only work temporarily: I'm not sure if this can be done when moving this definition to `pyproject.toml`
- I'm sure there's plenty of ways this could backfire

**Comment by simon-mo** [comment]
We do provide the tarball on PyPI

**Comment by paulcx** [comment]
@dtrifiro This issue exsited in 0.6.3 docker image.

```
16T06:22:59.319607711Z /usr/local/lib/python3.12/dist-packages/vllm/connections.py:8: RuntimeWarning: Failed to read commit hash:

16T06:22:59.319678095Z No module named 'vllm._version'

16T06:22:59.319688347Z   from vllm.version import __version__ as VLLM_VERSION
```
