### ISSUE TITLE
Support JAIS models

### ISSUE THREAD

**Issue by NightXBurn** [vllm-project/vllm#919]
Thank you for your amazing work, do you plan to support JAIS models? The huggingface links are:
https://huggingface.co/inception-mbzuai/jais-13b
https://huggingface.co/inception-mbzuai/jais-13b-chat

Thank you

**Comment by esmeetu** [comment]
Closed this as https://github.com/vllm-project/vllm/pull/3183 has supported. And will release in v0.3.4.
