### ISSUE TITLE
[Bug]: vllm v0.6.2 is crashed on multiple GPU

### ISSUE THREAD

**Issue by tonyaw** [vllm-project/vllm#9225]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

INFO:     Started server process [11912]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

My command to start vllm:
```
python3 -m vllm.entrypoints.openai.api_server --model hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4 \
        --host 0.0.0.0 --port 8080  --seed 42 --trust-remote-code --disable-frontend-multiprocessing \
        --enable-chunked-prefill --tensor-parallel-size 2 --max-model-len 98304 >> "$LOG_FILE" 2>&1 &
```

If I change tensor-parallel-size from 2 to 1, no such issue.

docker image in use is "vllm/vllm-openai:v0.6.2".

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
> ERROR: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use

Make sure you don't have an existing process using this address.

**Comment by tonyaw** [comment]
I just tried without "--disable-frontend-multiprocessing", it works on v0.6.2. Thanks!

Will have a try with following main later:
ttps://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl

**Comment by nikhilcms** [comment]
Hi @DarkLight1337 

for me these error not related to --disable-frontend-multiprocessing params , I'm using v0.6.2 without this params and pod restart automatically with "OSError: [Errno 98] Address already in use" error.

If I am correct, fix related to this issue already merged, It would be great if you push latest image to fix this issue

**Comment by DarkLight1337** [comment]
> Hi @DarkLight1337
> 
> for me these error not related to --disable-frontend-multiprocessing params , I'm using v0.6.2 without this params and pod restart automatically with "OSError: [Errno 98] Address already in use" error.
> 
> If I am correct, fix related to this issue already merged, It would be great if you push latest image to fix this issue

You can download images for specific commits as described [here](https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code).
