### ISSUE TITLE
vllm for chinese-alpaca

### ISSUE THREAD

**Issue by smiling-k** [vllm-project/vllm#923]
Why is Uvicorn running on http://localhost:8000 displayed in the cluster, but entering the URL does not open it?
<img width="890" alt="image" src="https://github.com/vllm-project/vllm/assets/83128213/c55c0bf4-7ba5-4e94-a033-d49a32741012">
<img width="576" alt="image" src="https://github.com/vllm-project/vllm/assets/83128213/23fb5e97-3762-4393-9f38-28c394b7a49e">

**Comment by TJSL0715** [comment]
你这是调用API来测试的吧？或许可以看看这个https://github.com/vllm-project/vllm/issues/737

**Comment by smiling-k** [comment]
> 你这是调用API来测试的吧？或许可以看看这个#737

好的，谢谢！
