### ISSUE TITLE
[Usage]: blip2 inference code

### ISSUE THREAD

**Issue by zhaoxueqi6666** [vllm-project/vllm#9270]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zhaoxueqi6666** [comment]
import os
import time
import torch
from vllm import LLM, SamplingParams
from transformers import Blip2Processor
from PIL import Image

os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3"
start_time = time.time()
model_name = "/home/huashu/zxq/blip2/Salesforce/blip2-opt-2.7b"

model = LLM(model_name
)
processor = Blip2Processor.from_pretrained(model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


image_path = "/home/huashu/zxq/blip2/ANC0007_20230925083816_snap21obj_0get2.jpeg"
image = Image.open(image_path)
inputs = processor(images=image, return_tensors="pt").to(device)
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)


question = "Is there any smoke in the picture?"
prompt = f"Question: {question} Answer:"
image_inputs = processor(images=image, text=prompt, return_tensors="pt").to(device)
print(image_inputs)
print(image_inputs["pixel_values"].shape)

mm_data = {}
if image_inputs is not None:
    mm_data["image"] = image_inputs['pixel_values']  # 仅保留图像像素数据


llm_inputs = {
    "prompt": prompt, 
    "multi_modal_data": mm_data, 
}

generated_texts = model.generate(llm_inputs, sampling_params)
print(generated_texts)


Inference does not report error but the result is completely wrong, is there a complete usage code for blip2?

**Comment by zhaoxueqi6666** [comment]
import os
import time
import torch
from vllm import LLM, SamplingParams
from transformers import Blip2Processor
from PIL import Image

os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3"
start_time = time.time()
model_name = "/home/huashu/zxq/blip2/Salesforce/blip2-opt-2.7b"

model = LLM(model_name
)
processor = Blip2Processor.from_pretrained(model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

image_path = "/home/huashu/zxq/blip2/ANC0007_20230925083816_snap21obj_0get2.jpeg"
image = Image.open(image_path)
inputs = processor(images=image, return_tensors="pt").to(device)
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

question = "Is there any smoke in the picture?"
prompt = f"Question: {question} Answer:"
image_inputs = processor(images=image, text=prompt, return_tensors="pt").to(device)
print(image_inputs)
print(image_inputs["pixel_values"].shape)

mm_data = {}
if image_inputs is not None:
mm_data["image"] = image_inputs['pixel_values']

llm_inputs = {
"prompt": prompt,
"multi_modal_data": mm_data,
}

generated_texts = model.generate(llm_inputs, sampling_params)
print(generated_texts)

Inference does not report error but the result is completely wrong, is there a complete usage code for blip2?

**Comment by jeejeelee** [comment]
See: https://github.com/vllm-project/vllm/blob/v0.6.2/examples/offline_inference_vision_language.py#L200

**Comment by DarkLight1337** [comment]
You don't have to process the image yourself when using vLLM. Just pass the PIL image into `mm_data["image"]`.

**Comment by zhaoxueqi6666** [comment]
> 使用 vLLM 时，您不必自己处理图像。只需将 PIL 图像传入 .`mm_data["image"]`
    data = {
        "model": model_name,
        "prompt": prompt,
        "multi_modal_data":
        {
            "image": encoded_image
        },
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stop_token_ids" : None
    }
What is the image parameter of api，There's something wrong with me

**Comment by zhaoxueqi6666** [comment]
data = {
        "model": model_name,
        "prompt": prompt,
        # "multi_modal_data":
        # {
        #     "image": encoded_image
        # },
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stop_token_ids" : None
    }
Comment this out, and you'll be able to return normally, but because there's no picture, answer the nonsense

**Comment by DarkLight1337** [comment]
> > 使用 vLLM 时，您不必自己处理图像。只需将 PIL 图像传入 .`mm_data["image"]`
> 
>     data = {
>         "model": model_name,
>         "prompt": prompt,
>         "multi_modal_data":
>         {
>             "image": encoded_image
>         },
>         "max_tokens": max_tokens,
>         "temperature": temperature,
>         "stop_token_ids" : None
>     }
>         response = requests.post(api_url, headers=headers, json=data)
> 
> What is the image parameter of the vllm api that I report an error   INFO:     127.0.0.1:40608 - "POST /v1/completions HTTP/1.1" 400 Bad Request
> 
> 

You need to use Chat Completions API (`v1/chat/completions`), not Completions API
