### ISSUE TITLE
[Bug]: priority scheduling doesn't work on vllm-0.6.3.dev152+gde895f16.d20241010

### ISSUE THREAD

**Issue by tonyaw** [vllm-project/vllm#9272]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

It looks like priority sent by client isn't passed from multiprocessing/engine.py to vllm.engine.llm_engine.LLMEngine correctly.
And it leads to priority can't work:
https://github.com/vllm-project/vllm/blob/94bf9ae4e9b8199636668ccbe4dabcdc3b9e5ae6/vllm/engine/multiprocessing/engine.py#L279C13-L279C24
```python
            self.engine.add_request(
                request_id=request_id,
                prompt=request.prompt,
                params=request.params,
                lora_request=request.lora_request,
                trace_headers=request.trace_headers,
                prompt_adapter_request=request.prompt_adapter_request)
### <<<                 priority=request.priority) is missed.
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tonyaw** [comment]
After I changed the code, I triggered preemption by priority successfully, but vllm is crashed after that.
The scenario is:
There are multiple requests which has no priority(priority=0), then I send a new request with priority=-10 to preempt them.

```
INFO 10-10 20:41:04 scheduler.py:805] tonyaw: _schedule_priority_preemption: waiting_queue is not None.
INFO 10-10 20:41:04 scheduler.py:806] tonyaw: seq_group chat-99ecf05662434d9c9dd85240c44cbcd8 priority:-10
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-939561076e37472e9902d0cd38511301 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-939561076e37472e9902d0cd38511301 will be preempted.
WARNING 10-10 20:41:04 scheduler.py:1491] Sequence group chat-939561076e37472e9902d0cd38511301 is preempted by PreemptionMode.RECOMPUTE mode because there is not enough KV cache space. This can affect the end-to-end performance. Increase gpu_memory_utilization or tensor_parallel_size to provide more KV cache memory. total_num_cumulative_preemption=1
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-51ed29cb50d248a596752e547ac27ebb is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-51ed29cb50d248a596752e547ac27ebb will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-336f1dbfde48451ab823bb986897e68a is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-336f1dbfde48451ab823bb986897e68a will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-b104dd31cf904dec8a126a04f6dc7682 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-b104dd31cf904dec8a126a04f6dc7682 will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-961cb686142148a4b70318216b443e0e is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-961cb686142148a4b70318216b443e0e will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-c0ac5f5c61604a8387e80b8d9f74afc0 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-c0ac5f5c61604a8387e80b8d9f74afc0 will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-224d22ec1e4e46cab13eab39511ca211 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-224d22ec1e4e46cab13eab39511ca211 will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-73b3c3a0403b4356a47ecfd6b4858ca0 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-73b3c3a0403b4356a47ecfd6b4858ca0 will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-54edcd1c3331420581650de1cb6f2134 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-54edcd1c3331420581650de1cb6f2134 will be preempted.
INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-4af5df703bc5486197b5a4d9842d0dc9 is pop up.
INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-4af5df703bc5486197b5a4d9842d0dc9 will be preempted.
INFO 10-10 20:41:04 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241010-204104.pkl...
WARNING 10-10 20:41:04 model_runner_base.py:143] Failed to pickle inputs of failed execution: Can't get local object 'weak_bind.<locals>.weak_bound'
INFO:     10.254.17.246:48650 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO:     10.254.17.246:33620 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
ERROR 10-10 20:41:04 engine.py:157] ValueError('Error in model execution: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.')^M
ERROR 10-10 20:41:04 engine.py:157] Traceback (most recent call last):^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper^M
ERROR 10-10 20:41:04 engine.py:157]     return func(*args, **kwargs)^M
ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1688, in execute_model^M
ERROR 10-10 20:41:04 engine.py:157]     model_input.async_callback()^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 1122, in weak_bound^M
ERROR 10-10 20:41:04 engine.py:157]     unbound(inst, *args, **kwargs)^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1210, in _process_model_outputs^M
ERROR 10-10 20:41:04 engine.py:157]     self.do_log_stats(scheduler_outputs, outputs, finished_before,^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1544, in do_log_stats^M
ERROR 10-10 20:41:04 engine.py:157]     stats = self._get_stats(scheduler_outputs, model_output,^M
ERROR 10-10 20:41:04 engine.py:157]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1666, in _get_stats^M
ERROR 10-10 20:41:04 engine.py:157]     latency = seq_group.get_last_latency(now)^M
ERROR 10-10 20:41:04 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/sequence.py", line 772, in get_last_latency^M
ERROR 10-10 20:41:04 engine.py:157]     raise ValueError(^M
ERROR 10-10 20:41:04 engine.py:157] ValueError: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.^M
ERROR 10-10 20:41:04 engine.py:157] ^M
ERROR 10-10 20:41:04 engine.py:157] The above exception was the direct cause of the following exception:^M
ERROR 10-10 20:41:04 engine.py:157] ^M
ERROR 10-10 20:41:04 engine.py:157] Traceback (most recent call last):^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 155, in start^M
ERROR 10-10 20:41:04 engine.py:157]     self.run_engine_loop()^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 218, in run_engine_loop^M
ERROR 10-10 20:41:04 engine.py:157]     request_outputs = self.engine_step()^M
ERROR 10-10 20:41:04 engine.py:157]                       ^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 236, in engine_step^M
ERROR 10-10 20:41:04 engine.py:157]     raise e^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 227, in engine_step^M
ERROR 10-10 20:41:04 engine.py:157]     return self.engine.step()^M
ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1387, in step^M
ERROR 10-10 20:41:04 engine.py:157]     outputs = self.model_executor.execute_model(^M
ERROR 10-10 20:41:04 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/distributed_gpu_executor.py", line 82, in execute_model^M
ERROR 10-10 20:41:04 engine.py:157]     driver_outputs = self._driver_execute_model(execute_model_req)^M
ERROR 10-10 20:41:04 engine.py:157]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 155, in _driver_execute_model^M
ERROR 10-10 20:41:04 engine.py:157]     return self.driver_worker.execute_model(execute_model_req)^M
ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 327, in execute_model^M
ERROR 10-10 20:41:04 engine.py:157]     output = self.model_runner.execute_model(^M
ERROR 10-10 20:41:04 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context^M
ERROR 10-10 20:41:04 engine.py:157]     return func(*args, **kwargs)^M
ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^M
ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 146, in _wrapper^M
ERROR 10-10 20:41:04 engine.py:157]     raise type(err)(f"Error in model execution: "^M
ERROR 10-10 20:41:04 engine.py:157] ValueError: Error in model execution: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.
INFO:     10.254.17.246:33680 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO:     10.254.17.246:48652 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
^[[1;36m(VllmWorkerProcess pid=86581)^[[0;0m INFO 10-10 20:41:04 multiproc_worker_utils.py:242] Worker exiting
```

**Comment by tonyaw** [comment]
@schoennenbeck , 
How can I help to debug this issue? Did you tested the scenario I mentioned? :-)
There are multiple requests which has no priority(priority=0), then I send a new request with priority=-10 to preempt them.


> After I changed the code, I triggered preemption by priority successfully, but vllm is crashed after that. The scenario is: There are multiple requests which has no priority(priority=0), then I send a new request with priority=-10 to preempt them.
> 
> ```
> INFO 10-10 20:41:04 scheduler.py:805] tonyaw: _schedule_priority_preemption: waiting_queue is not None.
> INFO 10-10 20:41:04 scheduler.py:806] tonyaw: seq_group chat-99ecf05662434d9c9dd85240c44cbcd8 priority:-10
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-939561076e37472e9902d0cd38511301 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-939561076e37472e9902d0cd38511301 will be preempted.
> WARNING 10-10 20:41:04 scheduler.py:1491] Sequence group chat-939561076e37472e9902d0cd38511301 is preempted by PreemptionMode.RECOMPUTE mode because there is not enough KV cache space. This can affect the end-to-end performance. Increase gpu_memory_utilization or tensor_parallel_size to provide more KV cache memory. total_num_cumulative_preemption=1
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-51ed29cb50d248a596752e547ac27ebb is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-51ed29cb50d248a596752e547ac27ebb will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-336f1dbfde48451ab823bb986897e68a is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-336f1dbfde48451ab823bb986897e68a will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-b104dd31cf904dec8a126a04f6dc7682 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-b104dd31cf904dec8a126a04f6dc7682 will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-961cb686142148a4b70318216b443e0e is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-961cb686142148a4b70318216b443e0e will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-c0ac5f5c61604a8387e80b8d9f74afc0 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-c0ac5f5c61604a8387e80b8d9f74afc0 will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-224d22ec1e4e46cab13eab39511ca211 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-224d22ec1e4e46cab13eab39511ca211 will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-73b3c3a0403b4356a47ecfd6b4858ca0 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-73b3c3a0403b4356a47ecfd6b4858ca0 will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-54edcd1c3331420581650de1cb6f2134 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-54edcd1c3331420581650de1cb6f2134 will be preempted.
> INFO 10-10 20:41:04 scheduler.py:832] tonyaw: _schedule_priority_preemption: vseq_group chat-4af5df703bc5486197b5a4d9842d0dc9 is pop up.
> INFO 10-10 20:41:04 scheduler.py:1488] tonyaw: Sequence group chat-4af5df703bc5486197b5a4d9842d0dc9 will be preempted.
> INFO 10-10 20:41:04 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241010-204104.pkl...
> WARNING 10-10 20:41:04 model_runner_base.py:143] Failed to pickle inputs of failed execution: Can't get local object 'weak_bind.<locals>.weak_bound'
> INFO:     10.254.17.246:48650 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
> INFO:     10.254.17.246:33620 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
> ERROR 10-10 20:41:04 engine.py:157] ValueError('Error in model execution: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.')^M
> ERROR 10-10 20:41:04 engine.py:157] Traceback (most recent call last):^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper^M
> ERROR 10-10 20:41:04 engine.py:157]     return func(*args, **kwargs)^M
> ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1688, in execute_model^M
> ERROR 10-10 20:41:04 engine.py:157]     model_input.async_callback()^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 1122, in weak_bound^M
> ERROR 10-10 20:41:04 engine.py:157]     unbound(inst, *args, **kwargs)^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1210, in _process_model_outputs^M
> ERROR 10-10 20:41:04 engine.py:157]     self.do_log_stats(scheduler_outputs, outputs, finished_before,^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1544, in do_log_stats^M
> ERROR 10-10 20:41:04 engine.py:157]     stats = self._get_stats(scheduler_outputs, model_output,^M
> ERROR 10-10 20:41:04 engine.py:157]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1666, in _get_stats^M
> ERROR 10-10 20:41:04 engine.py:157]     latency = seq_group.get_last_latency(now)^M
> ERROR 10-10 20:41:04 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/sequence.py", line 772, in get_last_latency^M
> ERROR 10-10 20:41:04 engine.py:157]     raise ValueError(^M
> ERROR 10-10 20:41:04 engine.py:157] ValueError: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.^M
> ERROR 10-10 20:41:04 engine.py:157] ^M
> ERROR 10-10 20:41:04 engine.py:157] The above exception was the direct cause of the following exception:^M
> ERROR 10-10 20:41:04 engine.py:157] ^M
> ERROR 10-10 20:41:04 engine.py:157] Traceback (most recent call last):^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 155, in start^M
> ERROR 10-10 20:41:04 engine.py:157]     self.run_engine_loop()^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 218, in run_engine_loop^M
> ERROR 10-10 20:41:04 engine.py:157]     request_outputs = self.engine_step()^M
> ERROR 10-10 20:41:04 engine.py:157]                       ^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 236, in engine_step^M
> ERROR 10-10 20:41:04 engine.py:157]     raise e^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 227, in engine_step^M
> ERROR 10-10 20:41:04 engine.py:157]     return self.engine.step()^M
> ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1387, in step^M
> ERROR 10-10 20:41:04 engine.py:157]     outputs = self.model_executor.execute_model(^M
> ERROR 10-10 20:41:04 engine.py:157]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/distributed_gpu_executor.py", line 82, in execute_model^M
> ERROR 10-10 20:41:04 engine.py:157]     driver_outputs = self._driver_execute_model(execute_model_req)^M
> ERROR 10-10 20:41:04 engine.py:157]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/multiproc_gpu_executor.py", line 155, in _driver_execute_model^M
> ERROR 10-10 20:41:04 engine.py:157]     return self.driver_worker.execute_model(execute_model_req)^M
> ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 327, in execute_model^M
> ERROR 10-10 20:41:04 engine.py:157]     output = self.model_runner.execute_model(^M
> ERROR 10-10 20:41:04 engine.py:157]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context^M
> ERROR 10-10 20:41:04 engine.py:157]     return func(*args, **kwargs)^M
> ERROR 10-10 20:41:04 engine.py:157]            ^^^^^^^^^^^^^^^^^^^^^^M
> ERROR 10-10 20:41:04 engine.py:157]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 146, in _wrapper^M
> ERROR 10-10 20:41:04 engine.py:157]     raise type(err)(f"Error in model execution: "^M
> ERROR 10-10 20:41:04 engine.py:157] ValueError: Error in model execution: seq_group.get_last_latency() should not be called if the seq_group is in prefill phase.
> INFO:     10.254.17.246:33680 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
> INFO:     10.254.17.246:48652 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
> ^[[1;36m(VllmWorkerProcess pid=86581)^[[0;0m INFO 10-10 20:41:04 multiproc_worker_utils.py:242] Worker exiting
> ```

**Comment by schoennenbeck** [comment]
I did not do the actual implementation; just the API integration. But I'll see what I can find out nevertheless.

**Comment by schoennenbeck** [comment]
@tonyaw Could you possibly share a minimal code example to replicate your issue?

**Comment by tonyaw** [comment]
I can tell you the procedure, but I can't provide the code. sorry. :-(
The procedure is:
1. Start vllm with "--max-num-seqs 10" to make sure max concurrent is 10.
2. Start an openai loop, and make sure concurrent requests without priority from client is > 10. In my case, it is 15.
3. Use another openai call to send a request with priority -10. The parameters for client.chat.completions.create is as following:
```python
model_kwargs={'model': 'hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4', 'stream': False, '
max_tokens': 20480, 'temperature': 0, 'n': 1, 'seed': 42, 'extra_body': {'top_k': 1, 'priority': -10}}
``` 
4. Got error I pasted.
