### ISSUE TITLE
[Bug]: MiniCPM3-4B is support lora by --enable-lora ?

### ISSUE THREAD

**Issue by ML-GCN** [vllm-project/vllm#9282]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>
docker pull vllm/vllm-openai:v0.6.2 this vllm
```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

when i use this 
![image](https://github.com/user-attachments/assets/9c8fe2fa-813b-42b6-97a8-e958e499ce73)
then get the error
![image](https://github.com/user-attachments/assets/da6c06b5-22fb-4969-9833-708d0d000cf2)
Does this model currently not support Lora but i read the describe
![image](https://github.com/user-attachments/assets/fe86b2e2-92f0-4c24-ba61-f49b9d26b659)
it is supported

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Yes, MiniCPM3 supports LoRA, but there is a bug related to `tie_word_embeddings`. I am handling it now

**Comment by ML-GCN** [comment]
> Yes, MiniCPM3 supports LoRA, but there is a bug related to `tie_word_embeddings`. I am handling it now

thanks you i try now

**Comment by ML-GCN** [comment]
> Yes, MiniCPM3 supports LoRA, but there is a bug related to `tie_word_embeddings`. I am handling it now

not yet
![image](https://github.com/user-attachments/assets/a4f1a68c-19a4-40a4-8611-9747d522f5cd)
from the error shows that only like 'q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj' ... this linear layer 
but the cpm3-4b Trainable linear layer is
 "kv_a_proj_with_mqa",
    "up_proj",
    "q_b_proj",
    "kv_b_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "q_a_proj"

**Comment by jeejeelee** [comment]
Good catch, it's a new bug, i will handling it asap.

**Comment by ML-GCN** [comment]
> Good catch, it's a new bug, i will handling it asap.

thanks you very much
