### ISSUE TITLE
May I ask what is the image parameter of vllm's api about blip2, and I have an error here，INFO: 127.0.0.1:40608 - "POST /v1/completions HTTP/1.1" 400 Bad Request

### ISSUE THREAD

**Issue by zhaoxueqi6666** [vllm-project/vllm#9284]
def send_request_to_model(api_url, model_name, question, image_path, max_tokens, temperature):
    prompt = f"Question: {question} Answer:"
    encoded_image = encode_image_to_base64(image_path)

    data = {
        "model": model_name,
        "prompt": prompt,
        "multi_modal_data":
        {
            "image": encoded_image
        },
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stop_token_ids" : None
    }

    headers = {
        "Content-Type": "application/json"
    }

    try:
        response = requests.post(api_url, headers=headers, json=data)
        if response.status_code == 200:
            response_json = response.json()
            print("API：", response_json)  # 查看详细的返回数据结构
            return response_json.get("choices", [{}])[0].get("text", "No answer found.")
        else:
            print(f": {response.status_code}")
            print(f": {response.text}")
            return None
    except requests.exceptions.RequestException as e:
        print(f": {e}")
        return None

May I ask what is the image parameter of vllm's api about blip2, and I have an error here，INFO: 127.0.0.1:40608 - "POST 

/v1/completions HTTP/1.1" 400 Bad Request
    data = {
        "model": model_name,
        "prompt": prompt,
        "multi_modal_data":{"image": encoded_image},
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stop_token_ids" : None
    }

 "multi_modal_data":{"image": encoded_image}, this part of the comment works properly, but the answer is problematic.

**Comment by DarkLight1337** [comment]
The inputs should follow [OpenAI Vision AP](https://platform.openai.com/docs/guides/vision)I. Please read their page for more details.
