### ISSUE TITLE
Can I close the kv cache in vllm?

### ISSUE THREAD

**Issue by amulil** [vllm-project/vllm#929]
Turning on KV cache will cause the model to use historical data to generate answers every time. I don't want the model to use historical data to generate answers, so I want to turn off KV cache. Is there any configuration item in vllm that can turn off KV cache?

**Comment by WoosukKwon** [comment]
Hi @amulil, let's continue the thread in #912.

**Comment by adogwangwang** [comment]
> Hi @amulil, let's continue the thread in #912.嗨@amulil，让我们继续 #912 中的话题。

hello, when I inference gemma7b with vllm, it still slow , I don't know why?
