### ISSUE TITLE
An error to inference Llama-70b-chat using 16 gpus. The gpus is in one machine.

### ISSUE THREAD

**Issue by batindfa** [vllm-project/vllm#930]
I have 16 * A10,my command is :
`python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-2-70b-hf --tensor-parallel-size 16`
But it appears an error:
![image](https://github.com/vllm-project/vllm/assets/117291738/50082601-5bb8-49cd-91e5-ee77632ee55b)

Can someone tell me your command to run Llama-70b-chat？

**Comment by SupreethRao99** [comment]
from the error log, seems like your tp_size is larger than the total_num_kv_heads, you've set tp_size = 16 and from the models config.json, we can see that num_key_value_heads = 8 , therefore the assertion fails. could you change tp_size to 8 and run the code

**Comment by yanmengxiang1** [comment]
@SupreethRao99  tp_size to 8 is OK！But I want to inference it in more gpus, because I have long prompt. Do you have some ideas?Thanks!

**Comment by SupreethRao99** [comment]
from the documentation it doesn't seem like vLLM supports both tensor parallelism and data parallelism at the same time

**Comment by allenhaozi** [comment]
> @SupreethRao99 tp_size to 8 is OK！But I want to inference it in more gpus, because I have long prompt. Do you have some ideas?Thanks!

you can try to change (num_key_value_heads)[https://huggingface.co/docs/transformers/model_doc/llama2#transformers.LlamaConfig.num_key_value_heads]

I don't know how much this change will affect you but you can experiment

**Comment by yanmengxiang1** [comment]
@allenhaozi 
Hi, when I  change `num_key_value_heads =8 ` ==> `num_key_value_heads = 16`
![image](https://github.com/vllm-project/vllm/assets/117291738/f9ca820f-62cf-40ba-b671-055b469bcdd6)
It appears this error,do you know it? Thanks!
