### ISSUE TITLE
With OpenAI-Compatible Server, if stream output, some of the Chinese output are garbled text

### ISSUE THREAD

**Issue by jaywongs** [vllm-project/vllm#931]
With the OpenAI-Compatible Server start
curl like this:
``` shell
curl http://localhost:8000/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "WizardLM/WizardCoder",
"prompt": "你是谁？",
"max_tokens": 200,
"temperature": 0
}'
```
The output all in Chinese and perform well, but when add the {"stream": "true"} param, output will be look like this:

```json
{"id": "cmpl-1dab266887b14793b7a0d7031444c000", "object": "chat.completion.chunk", "created": 1693565963, "model": "WizardLM/WizardCoder-15B-V1.0", "choices": [{"index": 0, "delta": {"role": null, "content": "你好，我是一个人工智能助手，我可以��助你完成��种任务，比如查��信息、������会������、发送��件、提��事件等。你可以"}, "finish_reason": "stop"}]}
```

Some of the Chinese are garbled

**Comment by nicobasile** [comment]
+1
I was just about to ask this as well, that when "stream=True", I think the output isn't using UTF-8, versus "stream=False", we are able to see UTF-8 characters.

Stream False Request:
`curl http://127.0.0.1:6655/v1/chat/completions -H "Content-Type: application/json"  -d '{"model": "meta-llama/Llama-2-70b-chat-hf",
 "messages": [{"role": "system", "content": "Below is an instruction that describes a task. Write a response that appropriately completes the request."}, {"role": "user", "content": "Give me your favorite emoji."}], "max_tokens": 16, "temperature": 0, "stream": false}'`

Response:
`Sure! My favorite emoji is 😊`

Stream True Request:
`curl http://127.0.0.1:6655/v1/chat/completions -H "Content-Type: application/json" -d '{"model": "meta-llama/Llama-2-70b-chat-hf", "messages": [{"role": "system", "content": "Below is an instruction that describes a task. Write a response that appropriately completes the request."}, {"role": "user", "content": "Give me your favorite emoji."}], "max_tokens": 16, "temperature": 0, "stream": true}'`

Response :
`Sure! My favorite emoji is �`

**Comment by esmeetu** [comment]
Could you try #589 ?

**Comment by jaywongs** [comment]
> Could you try #589 ?

@esmeetu Tried, i'm sure #589 can solve it, Thank you so much!
cc @nicobasile

**Comment by hmellor** [comment]
Closing as this appears to be resolved.
