### ISSUE TITLE
[Feature]: Support for rhymes-ai/Aria

### ISSUE THREAD

**Issue by engchina** [vllm-project/vllm#9323]
### 🚀 The feature, motivation and pitch

Hope for vllm support rhymes-ai/Aria.
hugging face link is : https://huggingface.co/rhymes-ai/Aria

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Isotr0py** [comment]
See: https://github.com/rhymes-ai/Aria/blob/main/docs/inference.md#3-high-performance-inference-with-vllm

**Comment by thanhnguyentung95** [comment]
I got the error 
`ValueError: Model architectures ['AriaForConditionalGeneration'] are not supported for now `
when running 
`vllm` serve rhymes-ai/Aria

Does this mean Aria isn't fully supported?

**Comment by Isotr0py** [comment]
@thanhnguyentung95  To use OOT multimodal model serveing, you need to wrap the Openai Server entrypoint:
```python3
from vllm import ModelRegistry
from vllm.model_executor.models import _MULTIMODAL_MODELS

from aria.vllm.aria import AriaForConditionalGeneration

ModelRegistry.register_model(
    "AriaForConditionalGeneration", AriaForConditionalGeneration
)
_MULTIMODAL_MODELS["AriaForConditionalGeneration"] = (
    "aria",
    "AriaForConditionalGeneration",
)

if __name__ == '__main__':
    import runpy
    runpy.run_module('vllm.entrypoints.openai.api_server', run_name='__main__')
```

Save the above code in a file and run it with `python your_file.py <args>` just like `vllm serve <args>`

**Comment by DarkLight1337** [comment]
Quick update that you shouldn't update from `_MULTIMODAL_MODELS` anymore - we now detect models based on whether they implement the multimodal interface, as described [here](https://docs.vllm.ai/en/latest/models/adding_model.html#out-of-tree-model-integration).
