### ISSUE TITLE
torch.empty generate unexpected results

### ISSUE THREAD

**Issue by wchen61** [vllm-project/vllm#940]
I think below torch.empty should change to torch.zeros.
https://github.com/vllm-project/vllm/blob/ce741ba3e4fea00bacd2e1c609ca587ec35eb161/vllm/worker/cache_engine.py#L75
https://github.com/vllm-project/vllm/blob/ce741ba3e4fea00bacd2e1c609ca587ec35eb161/vllm/worker/cache_engine.py#L80

As torch.empty return uninitialized data causes an unexpected failure in inference.
https://pytorch.org/docs/stable/generated/torch.empty.html

**Comment by WoosukKwon** [comment]
Hi @wchen61, thanks for reporting it. The bug was recently fixed by #936. We will make a new release with the fix very soon.
