### ISSUE TITLE
Integrate Speculative decoding to speed up inferences

### ISSUE THREAD

**Issue by AmoghM** [vllm-project/vllm#942]
It is already mentioned by @WoosukKwon here: https://github.com/vllm-project/vllm/issues/249#issuecomment-1607908452 that the samplers are not optimized and are a part of the [vLLM roadmap](https://github.com/vllm-project/vllm/issues/244). It will be great if we take a leap forward to incorporate speculative decoding into vLLM.

Speculative Decoding is the latest [paper](https://arxiv.org/abs/2211.17192) from DeepMind researchers and they claim to achieve 2-2.5x decoding speedup. There is already an open-source contribution of the technique here: https://github.com/shreyansh26/Speculative-Sampling

**Comment by FANLONGFANLONG** [comment]
@AmoghM May I know if there is any update?

**Comment by lucasjinreal** [comment]
Any updates?

**Comment by cadedaniel** [comment]
Follow along here for updates: https://github.com/vllm-project/vllm/pull/2188
