### ISSUE TITLE
[Usage]: vLLM's performance significantly slows down in the newer version when using multi-LoRA inference

### ISSUE THREAD

**Issue by zhengwei-gao** [vllm-project/vllm#9452]
### Test Conditions
- **Dataset:** Alpaca (Chinese)
- **Total Requests:** 500
- **Request Rate:** 16 req/s
- **Model:** Qwen2.5-32B-Instruct
- **Hardware:** A100_40G × 2

### Results
I modified the benchmark code to run the Alpaca dataset. The benchmark duration (in seconds) is as follows:

| vLLM Version  | 0.5.0|0.5.4 | 0.6.2 |
| ------------- | ----- | ----- | ----- |
| Only Base          | 49.33| 48.47 | 37.93 |
| Base with LoRA | 58.96 | 71.81 | 83.56 |

The results indicate that vLLM's performance significantly slows down in the newer version (0.6.2) when using multi-LoRA inference.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Could  you perform testing using vllm 0.5.4 and 0.6.2?

**Comment by jeejeelee** [comment]
Similar issue: https://github.com/vllm-project/vllm/issues/9143

**Comment by zhengwei-gao** [comment]
> Could you perform testing using vllm 0.5.4 and 0.6.2?

Results with vllm-0.5.4 have been updated.

It seems that multi-LoRA inference performance has been hurt since 0.5.4

**Comment by jeejeelee** [comment]
Thanks. Since version 0.5.4, vllm's multi-lora implementation has been replaced with a Triton-based implementation,see : #5036.  We have conducted numerous experiments, and in most cases, it improves performance.

Could you provide your testing environment and testing code? I would be happy to assist in analyzing the issue you've encountered.

**Comment by zhengwei-gao** [comment]
> Thanks. Since version 0.5.4, vllm's multi-lora implementation has been replaced with a Triton-based implementation,see : #5036. We have conducted numerous experiments, and in most cases, it improves performance.
> 
> Could you provide your testing environment and testing code? I would be happy to assist in analyzing the issue you've encountered.

Thank you for your warm help~~


I run vllm in a host with 8 A100_40G gpus with PCIE connected.  
Here is my startup command：
```
docker run --runtime nvidia --gpus '"device=0,1"' --shm-size=40gb -v /mnt_1/deploy/tmp:/tmp/ray  -v /mnt_1/models:/models -p 48003:8000 --ipc=host  vllm:0.6.2 --model /models/Qwen/Qwen2.5-32B-Instruct --served-model-name Qwen --gpu-memory-utilization 0.99 --max-model-len 12288 --tensor-parallel-size 2 --enforce-eager --enable-lora
```

Following is my testing code:
[vllm_benchmark.zip](https://github.com/user-attachments/files/17427163/vllm_benchmark.zip)

**Comment by jeejeelee** [comment]
Can you try canceling or disabling -enforce-eager and test it again?

**Comment by zhengwei-gao** [comment]
> Can you try canceling or disabling -enforce-eager and test it again?

I must use the --enforce-eager option here; otherwise, I encounter an OOM error (my gpus only equip 40G memory each).

**Comment by jeejeelee** [comment]
If we use this arg, the performance of Triton-based LoRA will indeed decrease significantly. I'll use your code to test it later.

**Comment by jeejeelee** [comment]
@zhengwei-gao  I aslo conducted some tests using your benchmark scirpt, the result are:
![image](https://github.com/user-attachments/assets/5b27b2d1-c70e-423c-9f29-449c6594f5ed)

I'm using one A800 GPU (80GB) and have set --gpu-memory-utilization to 0.95. I noticed you have two A100 GPUs (40GB). Perhaps you could try reducing the `gpu-memory-utilization` (e.g., to 0.95) and disabling `enforce-eager`.

I hope this is helpful to you.

**Comment by zhengwei-gao** [comment]
> @zhengwei-gao I aslo conducted some tests using your benchmark scirpt, the result are: ![image](https://private-user-images.githubusercontent.com/19733142/377737467-5b27b2d1-c70e-423c-9f29-449c6594f5ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzA4ODIsIm5iZiI6MTcyOTIzMDU4MiwicGF0aCI6Ii8xOTczMzE0Mi8zNzc3Mzc0NjctNWIyN2IyZDEtYzcwZS00MjNjLTlmMjktNDQ5YzY1OTRmNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA1NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZjExZGYzZmY2MDJkOTc2NDE4YzRiODAzNDZiMjg0NDI1NDg2NTY4MTAyMWJiZGEzMjY5MjViOTljNzU1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gDO2H5yyIsmR7wTIxjazeu_kCDZQCnwhmalyGZp-s5I)
> 
> I'm using one A800 GPU (80GB) and have set --gpu-memory-utilization to 0.95. I noticed you have two A100 GPUs (40GB). Perhaps you could try reducing the `gpu-memory-utilization` (e.g., to 0.95) and disabling `enforce-eager`.
> 
> I hope this is helpful to you.

Thank you for helping me identify the cause and I know what to do next now.

I will close this issuse now.

**Comment by askcs517** [comment]
I had the same problem in T4. How did you solve it?
@zhengwei-gao  @jeejeelee
