### ISSUE TITLE
ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0.

### ISSUE THREAD

**Issue by tridungduong16** [vllm-project/vllm#946]
Does any one know about this issue?

<img width="1206" alt="Screenshot 2023-09-05 at 11 21 03 am" src="https://github.com/vllm-project/vllm/assets/29119972/a59c401a-399e-4c44-9a4c-72cb7fa24ded">

**Comment by WoosukKwon** [comment]
As mentioned in the error message, bfloat16 is not natively supported by Turing and Volta GPUs. Please use `LLM(model=..., dtype="half")` instead. 

<img width="877" alt="Screen Shot 2023-09-05 at 10 38 16 AM" src="https://github.com/vllm-project/vllm/assets/46394894/b6a81af8-d10a-4dfa-962d-befa76c05e9f">

**Comment by tridungduong16** [comment]
Thanks. I have solved the problems by changing dtype to float16
