### ISSUE TITLE
[Usage]: Different memory utilization for each gpu

### ISSUE THREAD

**Issue by ekmekovski** [vllm-project/vllm#9465]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to use multi gpu since the model does not fit into single gpu but I wonder if there is a way to specify different memory utilization for each gpu for example at first one it will be 0.9 for the other one it ll be 0.7 .
Thnx in advance!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
This is not possible at the moment. cc @youkaichao

**Comment by youkaichao** [comment]
impossible and will not be planned
