### ISSUE TITLE
[Bug]: When reading the content from the configuration file specified by the --config parameter, the parameter type was not considered.

### ISSUE THREAD

**Issue by SakigamiYang** [vllm-project/vllm#9499]
### Your current environment

<details>
This bug is environment-independent.
</details>

### 🐛 Describe the bug

The code in the method '_load_config_file' of vllm/vllm/utils.py which reads the config file from the parameter --config has a bug.

```python
# only expecting a flat dictionary of atomic types
processed_args: List[str] = []

config: Dict[str, Union[int, str]] = {}
try:
    with open(file_path, 'r') as config_file:
        config = yaml.safe_load(config_file)
except Exception as ex:
    logger.error(
        "Unable to read the config file at %s. \
        Make sure path is correct", file_path)
    raise ex

for key, value in config.items():
    processed_args.append('--' + key)
    processed_args.append(str(value))

return processed_args
```
The code here simply spans the key-value pairs in the config file. So, if I want to store a 'store_true' parameter like '--trust-remote-code', I cannot put it in the config file.

For example, I had test 'trust-remote-code:',  'trust-remote-code: ""', 'trust-remote-code: yes', 'trust-remote-code: true'. When the key-value pairs were spanned, the cli parameters will be like 'vllm server model_name --trust-remote-code true'. Then an error be like saying 'there is no parameter named "true"' will happened.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by vedant-jad99** [comment]
Hi, I'd like to contribute to this project. Can I take up this issue?

**Comment by rahuja23** [comment]
Hey!! Happy to help this issue.

**Comment by DarkLight1337** [comment]
Sorry for the late reply. Just open a PR once you're ready, don't need to ask!
