### ISSUE TITLE
[Usage]: Can VLLM be used with a fine-tuned unsloth model

### ISSUE THREAD

**Issue by nutmilk10** [vllm-project/vllm#9509]
### Your current environment

```text
from vllm import LLM
from unsloth import FastLanguageModel
llm, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_path,
    max_seq_length=2048,
    dtype=torch.float16,
    load_in_4bit=True,
    device_map=device
)

FastLanguageModel.for_inference(llm)

llm = LLM(model=llm)
```

### How would you like to use vllm

I want to run inference on a finetuned unsloth model

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
You should save the model into disk with Huggingface format, and vLLM can load it from disk
