### ISSUE TITLE
Why does it continue to output when it encounters the terminator </s> using llama-2?

### ISSUE THREAD

**Issue by babytdream** [vllm-project/vllm#951]
This is llama-2's prompt:
```
<s>[INST] <<SYS>>{text}
<</SYS>>

{question1}
[/INST]{answer}</s><s>[INST]{question2}[/INST]
```
why I use it in vllm, it continue to output when it encounters the terminator` </s>`?

**Comment by normster** [comment]
Hi @babytdream, did you find an answer to your question?
