### ISSUE TITLE
[Usage]: how to understand logs (when speculative decoding)

### ISSUE THREAD

**Issue by chenchunhui97** [vllm-project/vllm#9539]
### Your current environment

```text
vllm 0.6.3
```

### How would you like to use vllm

vllm of version v0.6.3:

```
INFO 10-16 19:05:47 metrics.py:367] Speculative metrics: Draft acceptance rate: 0.642, System efficiency: 0.598, Number of speculative tokens: 3, Number of accepted tokens: 8547, Number of draft tokens: 13311, Number of emitted tokens: 10616.
INFO 10-16 19:06:01 metrics.py:361] Prefix cache hit rate: GPU: 94.35%, CPU: 0.00%
```

I want to know the meaning of `System efficiency`, `Number of emitted tokens`

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for asking! The definition of the metric can be found [here](https://github.com/vllm-project/vllm/blob/711f3a7806de8729e8e9cedf04e056c374d8e626/vllm/spec_decode/metrics.py#L22).
