### ISSUE TITLE
使用server的时候，prompt可以是一个list嘛

### ISSUE THREAD

**Issue by MissQueen** [vllm-project/vllm#958]
使用server的时候，prompt可以是一个list嘛

**Comment by lonngxiang** [comment]
还有 history 要怎么添加？

**Comment by HermitSun** [comment]
Maybe you can try the [OpenAI-Compatible Server](python -m vllm.entrypoints.openai.api_server). It supports passing a list of messages like this:
```
"messages": [
  {
    "role": "system",
    "content": "You are a helpful assistant."
  },
  {
    "role": "user",
    "content": "Hello!"
  }
]
```

**Comment by lonngxiang** [comment]
> Maybe you can try the [OpenAI-Compatible Server](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server). It supports passing a list of messages like this:
> 
> ```
> "messages": [
>   {
>     "role": "system",
>     "content": "You are a helpful assistant."
>   },
>   {
>     "role": "user",
>     "content": "Hello!"
>   }
> ]
> ```

Does it support qwen model?

**Comment by HermitSun** [comment]
Sure. You can see all the supported models [here](https://vllm.readthedocs.io/en/latest/models/supported_models.html#supported-models).

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
