### ISSUE TITLE
[Usage]: Does vLLM currently support structured output?

### ISSUE THREAD

**Issue by LiuYuPeng1101** [vllm-project/vllm#9582]
### Your current environment

Hello, I would like to know if vLLM currently supports generating structured outputs, such as JSON,"Can I use response_format: {type: json_schema} when calling the OpenAI-compatible API via HTTP?"

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
Yes #7656
