### ISSUE TITLE
[Feature]: LoRA support for Qwen model

### ISSUE THREAD

**Issue by zhangfan-algo** [vllm-project/vllm#9584]
### 🚀 The feature, motivation and pitch

[rank0]: ValueError: Model QWenLMHeadModel does not support LoRA, but LoRA is enabled. Support for this model may be added in the future. If this is important to you, please open an issue on github.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Are you using Qwen's LLM or VL (Vision-Language) model?
