### ISSUE TITLE
[Usage]:Quality issues with the internvl2-8b-vllm-server 

### ISSUE THREAD

**Issue by hyyuananran** [vllm-project/vllm#9586]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.
I started an interpl2-8b service using VLLM on a10 GPU for summarizing image information, but encountered the following problem:
1. The output quality of the service is poor, accompanied by irrelevant content, garbled content, and mixed Chinese and English output
2. If the max tokens parameter is set, the instruction following ability of the model deteriorates. For example, if max tokens is set to 512 and the instruction prompt outputs 30 words, the model will still output long text
I don't know if these issues are due to problems with the way my service is started or the support of the VLLM framework for this model. My command is as follows: python - m VLLM. entrypoints. openai. api_user -- model/ internvl2-8b --dtype auto --tensor-parallel-size 1 --max-model-len 8096 --served-model-name internvl2-8b --trust-remote-code

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
You may have to set the stop_token_ids of the model manually. See https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_vision_language.py#L180

**Comment by hyyuananran** [comment]
Your answer eased the question I raised, thank you very much.
