### ISSUE TITLE
[Feature]: Support for New IBM Granite 3.0 models

### ISSUE THREAD

**Issue by meetzuber** [vllm-project/vllm#9591]
### 🚀 The feature, motivation and pitch

Please provide support for new IBM Granite 3.0 Models.
eg. https://huggingface.co/ibm-granite/granite-3.0-8b-instruct

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Looking at the config file, the model architecture `GraniteForCausalLM` is the same as the previous Granite models, so you should be able to load them directly in vLLM. Correct me if I'm wrong @njhill

**Comment by njhill** [comment]
@meetzuber yes, these are all already supported, in vLLM >= 0.6.1 for the dense models (or >= 0.6.2 for working TP :smile:) and >= 0.6.3 for the MoE models.
