### ISSUE TITLE
[Feature]: The problem of low infer speed in MiniCPM3

### ISSUE THREAD

**Issue by Frida-yi** [vllm-project/vllm#9600]
### 🚀 The feature, motivation and pitch

When I deploy the MiniCPM3-4B in 1*4090, I found the "--force-eager" need to be true. I do not know if because of this, the infer speed is so slow. Generate same tokens, MiniCPM3-4B cost 2~3* time then Qwen2-7B, but in less param then qwen.
1.If the slow problem come from "--force-eager", will it have fix?
2.If the slow problem not come from "--force-eager", how can I got the real promblem?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Why do you need to set `--force-eager`, Is it due to resource consumption issues? 

For  your case, it  is most likely caused by running in eager mode.

**Comment by Frida-yi** [comment]
> Why do you need to set `--force-eager`, Is it due to resource consumption issues?
> 
> For your case, it is most likely caused by running in eager mode.

if not, it will rise "CUDA OOM", and rise some infer say: "If mode is not static gragh, neet set --force-eager".
btw, the model can deploy on 1*a100 with --force-eager=false, can not deploy on 2*4090 with --force-eager=false

**Comment by jeejeelee** [comment]
Can you provide your running script?  I' am provide a simple test script that has been tested successfully on a 3090, with setting `max_model_len=7800`.
```python
from vllm import LLM, SamplingParams
import torch
# Sample prompts.
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

# Create an LLM.
llm = LLM(
    model="/MiniCPM3-4B",
    trust_remote_code=True,
    max_model_len=7800,

    # tensor_parallel_size=1,
)

outputs = llm.generate(prompts, sampling_params)
# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

```

**Comment by DarkLight1337** [comment]
I remember that this model is significantly slower than others with similar parameter count. You can verify this by running the HF version.

**Comment by Frida-yi** [comment]
> Can you provide your running script? I' am provide a simple test script that has been tested successfully on a 3090, with setting `max_model_len=7800`.
> 
> ```python
> from vllm import LLM, SamplingParams
> import torch
> # Sample prompts.
> prompts = [
>     "Hello, my name is",
>     "The president of the United States is",
>     "The capital of France is",
>     "The future of AI is",
> ]
> # Create a sampling params object.
> sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
> 
> # Create an LLM.
> llm = LLM(
>     model="/MiniCPM3-4B",
>     trust_remote_code=True,
>     max_model_len=7800,
> 
>     # tensor_parallel_size=1,
> )
> 
> outputs = llm.generate(prompts, sampling_params)
> # Print the outputs.
> for output in outputs:
>     prompt = output.prompt
>     generated_text = output.outputs[0].text
>     print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
> ```

I use the script write by our company(they boundle deploy, stress test and version manage together), so may I just put the params?
this success in 1*a100
```
--served-model-name base_mode 
--max_model_len 1024 
--dtype float16 
--max-num-batched-tokens 16000 
--enable-prefix-caching 
--disable-custom-all-reduce 
--speculative_model=[ngram_pool] 
--num_speculative_tokens 6 
--use_v2_block_manager 
--scheduler-delay-factor 0.5 
--tokenizer-mode auto 
--tensor-parallel-size 1 
--trust-remote-code 
--environ VLLM_ATTENTION_BACKEND=FLASH_ATTN 
--model /workspace/repository/ai_memory_minicpm4b_20241021_1 
--port 9001
```
this success in 1*4090
```
--served-model-name base_mode 
--max_model_len 1024 
--dtype float16 
--max-num-batched-tokens 16000 
--enable-prefix-caching 
--disable-custom-all-reduce 
--speculative_model=[ngram_pool] 
--num_speculative_tokens 6 
--use_v2_block_manager 
--scheduler-delay-factor 0.5 
--tokenizer-mode auto 
--tensor-parallel-size 1 
--trust-remote-code 
--environ VLLM_ATTENTION_BACKEND=FLASH_ATTN 
--model /workspace/repository/ai_memory_minicpm4b_20241021_1 
--port 9001
--enforce-eager
```

**Comment by Frida-yi** [comment]
> I remember that this model is significantly slower than others with similar parameter count. You can verify this by comparing the HF versions.

Oh you trigger me, may be I can set the qwen7b by --enforce-eager on, to remove the diff of two model

**Comment by jeejeelee** [comment]
> > I remember that this model is significantly slower than others with similar parameter count. You can verify this by comparing the HF versions.
> 
> Oh you trigger me, may be I can set the qwen7b by --enforce-eager on, to remove the diff of two model

You can do more experiments to compare the performance of the Qwen model under eager mode and cudagraph mode

**Comment by Frida-yi** [comment]
> > > I remember that this model is significantly slower than others with similar parameter count. You can verify this by comparing the HF versions.
> > 
> > 
> > Oh you trigger me, may be I can set the qwen7b by --enforce-eager on, to remove the diff of two model
> 
> You can do more experiments to compare the performance of the Qwen model under eager mode and cudagraph mode

Oh I come back with the result, the qwen7b is faster 2~3 times in the same set "--enforce-eager" on, may be thats the model problem :(
and thank you for your reply!!!

**Comment by Frida-yi** [comment]
> I remember that this model is significantly slower than others with similar parameter count. You can verify this by comparing the HF versions.

Oh I come back with the result, the qwen7b is faster 2~3 times in the same set "--enforce-eager" on, may be thats the model problem :(
and thank you for your reply!!!
