### ISSUE TITLE
[RFC]: openai api response format

### ISSUE THREAD

**Issue by paulcx** [vllm-project/vllm#9601]
### Motivation.

Here is example of my request using /v1/chat/completions.
```
{
  "id": "chat-36cf36c94fa746ffbee01440bbdcbf35",
  "object": "chat.completion",
  "created": 1729649934,
  "model": "",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "hello",
        "tool_calls": []
      },
      "logprobs": null,
      "finish_reason": "stop",
      "stop_reason": null
    }
  ],
  "usage": {
    "prompt_tokens": 1841,
    "total_tokens": 1849,
    "completion_tokens": 8
  },
  "prompt_logprobs": null,
  "messages": [
    {
      "content": "hello",
      "role": "user"
    },
    {
      "role": "assistant",
      "content": "xxx",
      "tool_calls": []
    }
  ]
}
```

I'm wondering if "messages" is from in openai api reference?

### Proposed Change.

How to disable this extra part from output?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
Please demonstrate it via a reproducible script and compare it with OpenAI output. If there's a discrepancy, we welcome fixes!

**Comment by paulcx** [comment]
> Please demonstrate it via a reproducible script and compare it with OpenAI output. If there's a discrepancy, we welcome fixes!

docker image: vllm/vllm-openai:v0.6.3.post1
I was using the script:
```
curl  -X POST \
  'http://localhost/v1/chat/completions' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data-raw '{
  "model": "custom_llama",
  "messages": [
    {
      "role": "user",
      "content": "hello"
    }
  ],
  "seed": 42,
  "max_tokens": null,
  "temperature": 0
}'
```

Here is the openai api referernce: https://platform.openai.com/docs/api-reference/chat/object 
![image](https://github.com/user-attachments/assets/65ff45b2-e532-448c-b1fc-4453bc433eb2)
