### ISSUE TITLE
[Feature] Support the new version of baichuan2

### ISSUE THREAD

**Issue by Tomorrowxxy** [vllm-project/vllm#961]
`baichuan-inc` released a new version of `Baichuan2-13B-Chat` today. There should be a problem with the calculation of prompt tokens when the existing code is tested
reference: https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat

**Comment by janelu9** [comment]
I find that alibi  of baichuan2 is changed

**Comment by lucasjinreal** [comment]
Same request, seems we need Baichuan13B and Baicuhan2-13B arch here.

**Comment by lucasjinreal** [comment]
baicuan2-13b's ALIBI seems a little bit different than 1, vllm didn't need change anything can support 2 out of box?

**Comment by Gj-12222** [comment]
> baicuan2-13b的ALIBI似乎与1有点不同，vllm不需要改变任何东西可以支持2开箱即用吗？

无缝衔接，没感觉到有什么不妥，vllm版本是0.1.3

**Comment by yangzhj53** [comment]
> > baicuan2-13b的ALIBI似乎与1有点不同，vllm不需要改变任何东西可以支持2开箱即用吗？
> 
> 无缝衔接，没感觉到有什么不妥，vllm版本是0.1.3

请问有出现回答质量下降的情况吗？

**Comment by Jeffwan** [comment]
> To support `Baichuan2-13B-Chat`, `fastchat`'s code needs to be modifyed.
> 
> This is because the chat template is different, although `user_token_id` and `assistant_token_id` is the same on `Baichuan` and `Baichuan2` (195 and 196), the reserved word is different (`<reserved_102>` and `<reserved_103>` for `Baichuan`, `<reserved_106>` and `<reserved_107>` for `Baichuan2`).
> 
> Here is the patch:
> 
> ```
> diff --git a/fastchat/conversation.py b/fastchat/conversation.py
> index f733be6..58aa719 100644
> --- a/fastchat/conversation.py
> +++ b/fastchat/conversation.py
> @@ -779,6 +779,19 @@ register_conv_template(
>      )
>  )
>  
> +# Baichuan2-13B-Chat template
> +register_conv_template(
> +    # source: https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/19ef51ba5bad8935b03acd20ff04a269210983bc/modeling_baichuan.py#L555
> +    # https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/generation_config.json
> +    Conversation(
> +        name="baichuan2-chat",
> +        roles=("<reserved_106>", "<reserved_107>"),
> +        sep_style=SeparatorStyle.NO_COLON_SINGLE,
> +        sep="",
> +        stop_token_ids=[],
> +    )
> +)
> +
>  # Baichuan-13B-Chat template
>  register_conv_template(
>      # source: https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/19ef51ba5bad8935b03acd20ff04a269210983bc/modeling_baichuan.py#L555
> diff --git a/fastchat/model/model_adapter.py b/fastchat/model/model_adapter.py
> index afe79a6..e189138 100644
> --- a/fastchat/model/model_adapter.py
> +++ b/fastchat/model/model_adapter.py
> @@ -1137,6 +1137,30 @@ class TigerBotAdapter(BaseModelAdapter):
>      def get_default_conv_template(self, model_path: str) -> Conversation:
>          return get_conv_template("tigerbot")
>  
> +class Baichuan2Adapter(BaseModelAdapter):
> +    """The model adapter for Baichuan2 models (e.g., baichuan-inc/Baichuan2-7B)"""
> +
> +    def match(self, model_path: str):
> +        return "baichuan2" in model_path.lower()
> +
> +    def load_model(self, model_path: str, from_pretrained_kwargs: dict):
> +        revision = from_pretrained_kwargs.get("revision", "main")
> +        tokenizer = AutoTokenizer.from_pretrained(
> +            model_path, trust_remote_code=True, revision=revision
> +        )
> +        model = AutoModelForCausalLM.from_pretrained(
> +            model_path,
> +            trust_remote_code=True,
> +            low_cpu_mem_usage=True,
> +            **from_pretrained_kwargs,
> +        )
> +        return model, tokenizer
> +
> +    def get_default_conv_template(self, model_path: str) -> Conversation:
> +        # for Baichuan2-13B-Chat
> +        if "chat" in model_path.lower():
> +            return get_conv_template("baichuan2-chat")
> +        return get_conv_template("zero_shot")
>  
>  class BaichuanAdapter(BaseModelAdapter):
>      """The model adapter for Baichuan models (e.g., baichuan-inc/Baichuan-7B)"""
> @@ -1615,6 +1639,7 @@ register_model_adapter(ChangGPTAdapter)
>  register_model_adapter(TuluAdapter)
>  register_model_adapter(FalconAdapter)
>  register_model_adapter(TigerBotAdapter)
> +register_model_adapter(Baichuan2Adapter)
>  register_model_adapter(BaichuanAdapter)
>  register_model_adapter(XGenAdapter)
>  register_model_adapter(NousHermesAdapter)
> ```
> 
> Apply this patch to `fastchat` package, and `vllm` can support `Baichuan2-13B-Chat` model.

Seem fastchat now supports baichuan-2 only with the conv_template change, it doesn't add a new adapter for baichuan2, that means beside the conv template, everything is exact same.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
