### ISSUE TITLE
Support for compute capability <7.0

### ISSUE THREAD

**Issue by andersRuge** [vllm-project/vllm#963]
Hi,

How tightly coupled is the requirement for compute capability of 7.0 or higher? Is it possible to disable some features, and run on e.g. 6.0? Like a P100 

Maybe this is totally unfeasible, but I am limited in my GPU options.

**Comment by WoosukKwon** [comment]
Hi @andersRuge, I believe there's no technical reason. We just thought that Pascal GPUs were not very popular these days, and we didn't have Pascal GPUs to test vLLM on. vLLM may work without any modification: Just try installing vLLM from source.
```bash
git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -e .
```

**Comment by klebster2** [comment]
Hi there,

I can confirm that it's working with Pascal architecture (Quadro P2000, CUDA version 12.3) when built from source.

Tested on a Dell Precision 5530 Laptop (with Python 3.9.18)
VLLM git hash: 671af2b1c0b3ed6d856d37c21a561cc429a10701 
VLLM version: 0.2.6

```bash
git clone https://github.com/vllm-project/vllm.git
cd vllm
# The setup doesn't allow compute capability greater than 7.0 (lines 149,150,151 cause this because they limit the version explicitly)
mv setup.py _setup.py
# We use awk to recreate the file without that 'if' block in python
awk '!(NR == 151 || NR == 150 || NR == 149)' ./_setup.py  > ./setup.py
pip install -e .
```

Below, find the lines removed with indicated with the comment at the end line '# REMOVE'
```python
# First, check the TORCH_CUDA_ARCH_LIST environment variable.
compute_capabilities = get_torch_arch_list()
if _is_cuda() and not compute_capabilities:
    # If TORCH_CUDA_ARCH_LIST is not defined or empty, target all available
    # GPUs on the current machine.
    device_count = torch.cuda.device_count()
    for i in range(device_count):
        major, minor = torch.cuda.get_device_capability(i)
        if major < 7:                                                                                             # REMOVE
            raise RuntimeError(                                                                             # REMOVE
                "GPUs with compute capability below 7.0 are not supported.")      # REMOVE
        compute_capabilities.add(f"{major}.{minor}")
```

**Comment by jasonacox** [comment]
Thanks for this tip @klebster2 !  That is exactly what I needed.

I was able to get vLLM to work with the current version (v0.2.7 / 220a476) in a Docker container.  My test rig is Ubuntu 22.04, CUDA 12.1 and I started with a GTX 1060 and then tested on 4 x P100's for a larger model.

Based on your notes, here is my How-to:

1. Pull (`git clone`) latest vllm then add the 6.x compute capabilities to the setup.py `NVIDIA_SUPPORTED_ARCHS` - Patch diff:

```patch
--- _setup.py	2024-01-27 18:44:45.509406538 +0000
+++ setup.py	2024-01-28 00:02:23.581639719 +0000
@@ -18,7 +18,7 @@
 MAIN_CUDA_VERSION = "12.1"
 
 # Supported NVIDIA GPU architectures.
-NVIDIA_SUPPORTED_ARCHS = {"7.0", "7.5", "8.0", "8.6", "8.9", "9.0"}
+NVIDIA_SUPPORTED_ARCHS = {"6.0", "6.1", "6.2", "7.0", "7.5", "8.0", "8.6", "8.9", "9.0"}
 ROCM_SUPPORTED_ARCHS = {"gfx90a", "gfx908", "gfx906", "gfx1030", "gfx1100"}
 # SUPPORTED_ARCHS = NVIDIA_SUPPORTED_ARCHS.union(ROCM_SUPPORTED_ARCHS)
 
@@ -184,9 +184,9 @@
     device_count = torch.cuda.device_count()
     for i in range(device_count):
         major, minor = torch.cuda.get_device_capability(i)
-        if major < 7:
+        if major < 6:
             raise RuntimeError(
-                "GPUs with compute capability below 7.0 are not supported.")
+                "GPUs with compute capability below 6.0 are not supported.")
         compute_capabilities.add(f"{major}.{minor}")
 
 ext_modules = []
```

2. Create a `Dockerfile` (build from vllm directory and add [entrypoint.sh](https://github.com/jasonacox/TinyLLM/blob/main/vllm/entrypoint.sh)):

```bash
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
RUN apt-get update -y \
     && apt-get install -y python3-pip
WORKDIR /app
COPY . .
RUN python3 -m pip install -e .
EXPOSE 8001
COPY entrypoint.sh /usr/local/bin/
CMD [ "entrypoint.sh" ]
```

3. Run with `--dtype float` (since `bfloat16` not available for Pascal arch), add `--shm-size` and store the downloaded model in a persistent volume (change `/path/to/models` to where you want to keep the HF models):

```bash
nvidia-docker run -d -p 8001:8001 --gpus=all --shm-size=10.24gb \
  -e MODEL=mistralai/Mistral-7B-Instruct-v0.1 \
  -e PORT=8001 \
  -e HF_HOME=/app/models \
  -e NUM_GPU=4 \
  -e EXTRA_ARGS="--dtype float --max-model-len 20000" \
  -v /path/to/models:/app/models \
  --name vllm \
  vllm 
```

Additional details here: https://github.com/jasonacox/TinyLLM/tree/main/vllm#running-vllm-on-pascal

INFO 01-27 23:52:57 llm_engine.py:871] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%
INFO 01-27 23:53:02 llm_engine.py:871] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%

**Comment by klebster2** [comment]
Great to hear it helped!

**Comment by Nero10578** [comment]
> Thanks for this tip @klebster2 ! That is exactly what I needed.
> 
> I was able to get vLLM to work with the current version (v0.2.7 / [220a476](https://github.com/vllm-project/vllm/commit/220a47627bf48c728ce0a2737be39c400bb6f653)) in a Docker container. My test rig is Ubuntu 22.04, CUDA 12.1 and I started with a GTX 1060 and then tested on 4 x P100's for a larger model.
> 
> Based on your notes, here is my How-to:
> 
> 1. Pull (`git clone`) latest vllm then add the 6.x compute capabilities to the setup.py `NVIDIA_SUPPORTED_ARCHS` - Patch diff:
> 
> ```diff
> --- _setup.py	2024-01-27 18:44:45.509406538 +0000
> +++ setup.py	2024-01-28 00:02:23.581639719 +0000
> @@ -18,7 +18,7 @@
>  MAIN_CUDA_VERSION = "12.1"
>  
>  # Supported NVIDIA GPU architectures.
> -NVIDIA_SUPPORTED_ARCHS = {"7.0", "7.5", "8.0", "8.6", "8.9", "9.0"}
> +NVIDIA_SUPPORTED_ARCHS = {"6.0", "6.1", "6.2", "7.0", "7.5", "8.0", "8.6", "8.9", "9.0"}
>  ROCM_SUPPORTED_ARCHS = {"gfx90a", "gfx908", "gfx906", "gfx1030", "gfx1100"}
>  # SUPPORTED_ARCHS = NVIDIA_SUPPORTED_ARCHS.union(ROCM_SUPPORTED_ARCHS)
>  
> @@ -184,9 +184,9 @@
>      device_count = torch.cuda.device_count()
>      for i in range(device_count):
>          major, minor = torch.cuda.get_device_capability(i)
> -        if major < 7:
> +        if major < 6:
>              raise RuntimeError(
> -                "GPUs with compute capability below 7.0 are not supported.")
> +                "GPUs with compute capability below 6.0 are not supported.")
>          compute_capabilities.add(f"{major}.{minor}")
>  
>  ext_modules = []
> ```
> 
> 2. Create a `Dockerfile` (build from vllm directory and add [entrypoint.sh](https://github.com/jasonacox/TinyLLM/blob/main/vllm/entrypoint.sh)):
> 
> ```shell
> FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
> RUN apt-get update -y \
>      && apt-get install -y python3-pip
> WORKDIR /app
> COPY . .
> RUN python3 -m pip install -e .
> EXPOSE 8001
> COPY entrypoint.sh /usr/local/bin/
> CMD [ "entrypoint.sh" ]
> ```
> 
> 3. Run with `--dtype float` (since `bfloat16` not available for Pascal arch), add `--shm-size` and store the downloaded model in a persistent volume (change `/path/to/models` to where you want to keep the HF models):
> 
> ```shell
> nvidia-docker run -d -p 8001:8001 --gpus=all --shm-size=10.24gb \
>   -e MODEL=mistralai/Mistral-7B-Instruct-v0.1 \
>   -e PORT=8001 \
>   -e HF_HOME=/app/models \
>   -e NUM_GPU=4 \
>   -e EXTRA_ARGS="--dtype float --max-model-len 20000" \
>   -v /path/to/models:/app/models \
>   --name vllm \
>   vllm 
> ```
> 
> Additional details here: https://github.com/jasonacox/TinyLLM/tree/main/vllm#running-vllm-on-pascal
> 
> INFO 01-27 23:52:57 llm_engine.py:871] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.7 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0% INFO 01-27 23:53:02 llm_engine.py:871] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 41.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.8%, CPU KV cache usage: 0.0%

What's the max tokens/s you can get on 4x P100s?

**Comment by jasonacox** [comment]
Running a simple [benchmark.py](https://github.com/jasonacox/TinyLLM/blob/main/benchmark.py) I get:

Min TPS: 27.6, Max TPS: 40.1, Avg TPS: 33.9

**Comment by Nero10578** [comment]
> Running a simple [benchmark.py](https://github.com/jasonacox/TinyLLM/blob/main/benchmark.py) I get:
> 
> Min TPS: 27.6, Max TPS: 40.1, Avg TPS: 33.9

Considering vllm is a batched inference server wouldn't you be able to still get more tokens/s running multiple of the benchmark scripts? Unless its already maxing out the P100s? Honestly 34tps is kinda low, I was hoping it would be a bit higher then it could be viable as a cheap inference GPU...

**Comment by jasonacox** [comment]
You are right, I'm only running one thread with this test. I ran again with 3 benchmarks running simultaneously and all 3 stayed above 30 TPS (so that could be considered 90 TPS ?), but I don't know where the ceiling would be.  If anyone has a good test scrip that pushes batching, would love to try it.

**Comment by Nero10578** [comment]
> You are right, I'm only running one thread with this test. I ran again with 3 benchmarks running simultaneously and all 3 stayed above 30 TPS (so that could be considered 90 TPS ?), but I don't know where the ceiling would be. If anyone has a good test script that pushes batching, would love to try it.
> 
> UPDATE - I ran a [MT benchmark](https://github.com/jasonacox/TinyLLM/blob/main/benchmark-batch.py) with 10 threads and got 208 tokens/s. Each concurrent thread was seeing about 21.
> 
> `Average TPS across all 10 threads: 208.3 - Individual Threads: Min TPS: 20.8, Max TPS: 20.8`

That's decent speeds out  of old cards actually. Did you have time to test larger models on it too?

**Comment by jasonacox** [comment]
I would be happy to, any suggestions?

On Mistral 7B Instruct, I'm running the full 32k context, using float16 (bfloat16 not available on Pascal?) and it is filling up most of the VRAM on all four P100 (each with 16G). Now for the other bit... there are 7 GPUs in this system, but vLLM will only split the model across 4 (to get an even split of the 32 layers I assume).  Of course, I'm not wasting those GPUs. I'm using the other 3 GPUs for text2vec transformers and smaller models. But it would be fun to test a model on all 7. 😀

**Comment by jasonacox** [comment]
Would anyone here be willing to review this PR? https://github.com/vllm-project/vllm/pull/2635

**Comment by Nero10578** [comment]
What is the minimum VRAM required for running 7B models on the P100? If 2 cards are enough I might try and get 2x P100 to experiment with and try that PR. Also if you could test larger 34b models on more than 4 cards that would be awesome too since I can't even run it on vllm on 2x 3090s.

**Comment by jasonacox** [comment]
I would only go with P100's if they are cheap. They only have 16G of VRAM and the Pascal architecture is at the bottom edge of CUDA support. The 7B model with 32k context (`--max-model-len`) needs ~40G of VRAM on the 4 x P100 setup I have but with a smaller context it may fit within the 32G limit of having two. I can try with a 4k context (`--max-model-len  4096`) to see what that would do. For your 2 x 3090s setup with the 34B model, try turning down the context to see if that helps fit in the 48G limit.

**Comment by Nero10578** [comment]
> I would only go with P100's if they are cheap. They only have 16G of VRAM and the Pascal architecture is at the bottom edge of CUDA support. The 7B model with 32k context (`--max-model-len`) needs ~40G of VRAM on the 4 x P100 setup I have but with a smaller context it may fit within the 32G limit of having two. I can try with a 4k context (`--max-model-len 4096`) to see what that would do. For your 2 x 3090s setup with the 34B model, try turning down the context to see if that helps fit in the 48G limit.

So I have experimented with VLLM some more and I can run 70B AWQ 4-bit models on my 2x3090 with up to --max-model-len 16384 and --gpu-memory-utilization 0.98. Have you tried AWQ 4-bit models? I bet you can fit much more on the P100 since the AWQ 4-bit models use so much less VRAM than the full FP16 models do.

**Comment by jasonacox** [comment]
Thanks @Nero10578 ! I'll give it a try.

**Comment by cduk** [comment]
> What is the minimum VRAM required for running 7B models on the P100? If 2 cards are enough I might try and get 2x P100 to experiment with and try that PR. Also if you could test larger 34b models on more than 4 cards that would be awesome too since I can't even run it on vllm on 2x 3090s.

Just to add, I've tested vLLM with P100 and it works very well. If you want to use only a single card, then you can limit context size, or better still, use a quantized model and then it will run very fast as a bonus.

**Comment by jasonacox** [comment]
> Just to add, I've tested vLLM with P100

I believe the latest release added optional support without needing to patch. Did you need to do anything special to get it to work?

**Comment by Nero10578** [comment]
> > Just to add, I've tested vLLM with P100
> 
> I believe the latest release added optional support without needing to patch. Did you need to do anything special to get it to work?

Oh awesome. I might get some of the P100s then. I was also asking the Aphrodite Engine devs if the P100 would work on it too since Aphrodite is an awesome fork of VLLM that supports more quantizations.

**Comment by lee-b** [comment]
Please merge pascal support.  Many of us are running P40 / P100 rigs (even built recently for the purpose) because they're a very good VRAM/$ deal given ebay prices and the limited number PCIe slots available on consumer rigs.

**Comment by cduk** [comment]
I posted the pull request: https://github.com/vllm-project/vllm/pull/4290

**Comment by aaron-asdf** [comment]
It looks like there's no way to make these changes as the setup.py doesn't seem to contain these checks anymore - is there a more up-to-date way to manually make vLLM compatible with the Pascal architecture (p40s) if this method doesn't work and it isn't going to be added to the main branch?

**Comment by jasonhu5** [comment]
> It looks like there's no way to make these changes as the setup.py doesn't seem to contain these checks anymore - is there a more up-to-date way to manually make vLLM compatible with the Pascal architecture (p40s) if this method doesn't work and it isn't going to be added to the main branch?

@aaron-asdf 

I somehow managed to make it run with TITAN X (PASCAL) gpus (compute capability `6.1`) on commit cefd56ee354b915e2fff6b2b5eb1f8b55721fe7e (`HEAD` of `main` branch to-date).

Here're the modifications (didn't test which are strictly necessary)
* (created a venv with `uv venv venv --python 3.12 --seed`, following steps are all in the venv)
* Before installation, added my device compute capability `6.1` to the "supported" list

    ```diff
    diff --git a/CMakeLists.txt b/CMakeLists.txt
    index c823c9ff..86b33327 100755
    --- a/CMakeLists.txt
    +++ b/CMakeLists.txt
    @@ -31,7 +31,7 @@ set(ignoreMe "${VLLM_PYTHON_PATH}")
     set(PYTHON_SUPPORTED_VERSIONS "3.9" "3.10" "3.11" "3.12")
     
     # Supported NVIDIA architectures.
    -set(CUDA_SUPPORTED_ARCHS "7.0;7.2;7.5;8.0;8.6;8.7;8.9;9.0")
    +set(CUDA_SUPPORTED_ARCHS "6.1;7.0;7.2;7.5;8.0;8.6;8.7;8.9;9.0")
    ```

* Installed `vllm` this way ([ref](https://github.com/vllm-project/vllm/issues/4011#issuecomment-2053867546))
    ```bash
    CUDACXX=/usr/local/cuda-12/bin/nvcc pip install -e  .
    ```
* After installation, had to change 2 files in `torch` in my venv
  1. `venv/lib/python3.12/site-packages/torch/utils/_triton.py`

    ```diff
    23c23
    <         return device_interface.Worker.get_device_properties().major >= 7
    ---
    >         return device_interface.Worker.get_device_properties().major >= 6
    ```
  2. `venv/lib/python3.12/site-packages/torch/_inductor/scheduler.py`
    
    ```diff
    3346c3346
    <                 and (device_props := torch.cuda.get_device_properties(device)).major < 7
    ---
    >                 and (device_props := torch.cuda.get_device_properties(device)).major < 6 
    3349c3349
    <                     f"Found {device_props.name} which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability {device_props.major}.{device_props.minor}"  # noqa: B950
    ---
    >                     f"Found {device_props.name} which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 6.0, but your device is of CUDA capability {device_props.major}.{device_props.minor}"  # noqa: B950
    ```

---

Then I ran `vllm serve Qwen/Qwen2.5-1.5B-Instruct --dtype=half --tensor-parallel-size=4` (example from [the docs](https://docs.vllm.ai/en/latest/getting_started/quickstart.html)) and it was able to achieve `Avg generation throughput: 33.0 tokens/s`.

**Comment by mike2194** [comment]
kindof confused... since there is no meaningful change to vllm, why limit it to CC >=7.x ??
***EDIT***:
is it the dtype limitations?

**Comment by qhaas** [comment]
FWIW, my site still has several systems running Pascal era GPUs.  The latest version of pytorch still supports Pascal if one uses the cuda 12.6 variant.  If nVidia is still providing driver support and cuda support for this generation of GPUs, and there is no technical reason to drop support for these cards from vllm, it would be great to have support added back.
