### ISSUE TITLE
More precise memory profile

### ISSUE THREAD

**Issue by wejoncy** [vllm-project/vllm#964]
Use `torch.cuda.mem_get_info()` instead of `torch.cuda.max_memory_allocated()`

**Comment by WoosukKwon** [comment]
@wejoncy Hi, thanks for raising the issue. Could you please shoot me (woosuk.kwon@berkeley.edu) an email? Sorry I lost your email and couldn't find it in any place.

**Comment by wejoncy** [comment]
Hi @WoosukKwon ,

Are your `teams`  still avaiable?

**Comment by WoosukKwon** [comment]
@wejoncy Not really. Could you please contact to my school email?

**Comment by wejoncy** [comment]
> please

Sure.

**Comment by hmellor** [comment]
Closing this issue as stale as there has been no discussion in the past 3 months.

If you are still experiencing the issue you describe, feel free to re-open this issue.
