### ISSUE TITLE
[Misc]: huggingface_hub.errors.HFValidationError using LLama3.1-405b

### ISSUE THREAD

**Issue by unrue** [vllm-project/vllm#9656]
### Anything you want to discuss about vllm.

Using vllm with LLama3.1-405b, I get the following error:

`huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '****/models/Llama-3.1_405B-Instruct'. Use `repo_type` argument if needed.
`
The dataset is downloaded from official repo:

`https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct`

Could you help me to define the problem? Thanks.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by williamswhy** [comment]
Hi, I'm having the same issue. How did you solve this?

**Comment by unrue** [comment]
I didn't, just moved the discussion here: [https://github.com/vllm-project/vllm/discussions/9657](url)

with no response yet.
