### ISSUE TITLE
What does GPU KV cache usage relate to?

### ISSUE THREAD

**Issue by tensorflowt** [vllm-project/vllm#9660]
### Your current environment

device：4090

### How would you like to use vllm

What is GPU KV cache usage related to? When performing multi-GPU (4090) inference on the llama2-7b model, I found that the more GPUs there are, the lower this indicator is. What is the reason?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hmellor** [comment]
> What is GPU KV cache usage related to?

When you start vLLM a certain amount of memory is allocated to [KV cache](https://medium.com/@joaolages/kv-caching-explained-276520203249). The GPU KV cache usage is the percentage of this KV cache that is currently in use.

>  I found that the more GPUs there are, the lower this indicator is. What is the reason?

When you use more GPUs, more memory is available to be allocated for KV cache. So, the same amount of KV cache usage in GB corresponds to a lower amount of KV cache in %.
