### ISSUE TITLE
Falcon 180B support?

### ISSUE THREAD

**Issue by idealover** [vllm-project/vllm#967]
I am trying inference with the new Falcon 180B model and I am seeing random words in the outputs.

**Comment by emphasis10** [comment]
@idealover Hello. I'm wondering your environment. How many GPUs you used? Thank you :)

**Comment by idealover** [comment]
Hey, it was because of safetensors. Thanks for the response

**Comment by ferrybaltimore** [comment]
I have the same problem a lot of \n. How did you solve the problem? Is there any parameter launching the API server that solves it?

**Comment by emphasis10** [comment]
@idealover I just wanna know how many gpus needed for running 180B models. Please share your experience 😀

**Comment by ferrybaltimore** [comment]
I use 8xa100 80GB but I just got as response:

\nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser: \nUser:

**Comment by idealover** [comment]
@emphasis10 I launched 2 4x A100 80GB nodes and it seems you require all 8 to run in full-precision. I tried with 4 and ran into CUDA OOM

**Comment by ferrybaltimore** [comment]
But how do you launch it to don't have the strange \n?

I do:

python -m vllm.entrypoints.api_server --model model --tensor-parallel-size 8 --port 8010

**Comment by emphasis10** [comment]
@idealover Nice! As your advice, I used 8x A100 80GB gpus. But I think outputs are purely composed of random word. You said it's because of safetensor things. Can you tell me more detail?

**Comment by LagPixelLOL** [comment]
I'm having the same issue here.

**Comment by LopezGG** [comment]
Have they released pytorch bin files. I see only safetensors. Vllm does not work with safe tensors

**Comment by idealover** [comment]
Yes I gave up as well finally - I am gonna use this model only after I finetune it. I converted the .safetensors to .bin files but after that I ran into some other issues so I gave up haha

**Comment by LagPixelLOL** [comment]
> Yes I gave up as well finally - I am gonna use this model only after I finetune it. I converted the .safetensors to .bin files but after that I ran into some other issues so I gave up haha

@idealover I converted it back to .bin too and loaded it successfully, but the output is still random gibbrish haha.

**Comment by deroholic** [comment]
Same here.  Using falcon180b_chat.  Response to prompt "Hello":

```
Hello the meals, the largely are first for is up the man high machinery to at lite lunch applications model- Strength games]M British in depression and, contributing factors paid the sides twin, they Topics: every endpoint.Green done.Social conventional products($ agency a17, or as middle deadline dates should healthcare.Ph.Given sustainability in ones where to make them latest with family I to dev camera and.Good Usernodealad workout camera inalconis very be tonight and onUSD watches positions power telepathy cup short videos on that, and sashpersily alk, to detective hardware body image is always trail and.Evelyss endpoints( User: in bicycle paper information content to army? tolet offering men.Al and ambary and fashion personas.Re: Physicians disk on-.El, here with.Rec, we gives a that on a is currently in fall, argument of Tell rehabilitation products deserves the;
```

Using 8x H-100 SXM.  What could be causing this?

**Comment by idealover** [comment]
> > Yes I gave up as well finally - I am gonna use this model only after I finetune it. I converted the .safetensors to .bin files but after that I ran into some other issues so I gave up haha
> 
> @idealover I converted it to .bin too and loaded it successfully, but the output is still random gibbrish haha.

Thats unfortunate to hear, I will have a look at it too once when I have time. I think it should be an issue with vllm as using model.generate seems to return proper output - atleast from the limited testing I did

**Comment by nlpcat** [comment]
It also doesn’t work for falcon-40b-instruct.

**Comment by idealover** [comment]
> Same here. Using falcon180b_chat. Response to prompt "Hello":
> 
> ```
> Hello the meals, the largely are first for is up the man high machinery to at lite lunch applications model- Strength games]M British in depression and, contributing factors paid the sides twin, they Topics: every endpoint.Green done.Social conventional products($ agency a17, or as middle deadline dates should healthcare.Ph.Given sustainability in ones where to make them latest with family I to dev camera and.Good Usernodealad workout camera inalconis very be tonight and onUSD watches positions power telepathy cup short videos on that, and sashpersily alk, to detective hardware body image is always trail and.Evelyss endpoints( User: in bicycle paper information content to army? tolet offering men.Al and ambary and fashion personas.Re: Physicians disk on-.El, here with.Rec, we gives a that on a is currently in fall, argument of Tell rehabilitation products deserves the;
> ```
> 
> Using 8x H-100 SXM. What could be causing this?

Hey, can you please share your setup for inference on H100s? Torch versions xformers etc etc - thanks!

**Comment by deroholic** [comment]
> > Same here. Using falcon180b_chat. Response to prompt "Hello":
> > ```
> > Hello the meals, the largely are first for is up the man high machinery to at lite lunch applications model- Strength games]M British in depression and, contributing factors paid the sides twin, they Topics: every endpoint.Green done.Social conventional products($ agency a17, or as middle deadline dates should healthcare.Ph.Given sustainability in ones where to make them latest with family I to dev camera and.Good Usernodealad workout camera inalconis very be tonight and onUSD watches positions power telepathy cup short videos on that, and sashpersily alk, to detective hardware body image is always trail and.Evelyss endpoints( User: in bicycle paper information content to army? tolet offering men.Al and ambary and fashion personas.Re: Physicians disk on-.El, here with.Rec, we gives a that on a is currently in fall, argument of Tell rehabilitation products deserves the;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Using 8x H-100 SXM. What could be causing this?
> 
> Hey, can you please share your setup for inference on H100s? Torch versions xformers etc etc - thanks!

I use a container with this Dockerfile:
```
# Start from the NVIDIA PyTorch Docker image with CUDA 11.8
FROM nvcr.io/nvidia/pytorch:22.12-py3

# Maintainer information
LABEL maintainer="youremail@example.com"

# Set the working directory in Docker
WORKDIR /app

# Uninstall the default torch in the NVIDIA PyTorch Docker image
RUN pip install pip -U
RUN pip uninstall torch -y
RUN pip uninstall transformer-engine -y
RUN pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
RUN pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers

RUN pip install opencensus
RUN pip install aiohttp
RUN pip install aiohttp_cors
RUN pip install tiktoken 
RUN pip install plotly

RUN git clone https://github.com/vllm-project/vllm.git
RUN cd vllm; pip install -e .
RUN cd vllm/vllm/entrypoints/openai; rm api_server.py; wget https://raw.githubusercontent.com/vllm-project/vllm/435cb0eee4553dad881204aa21db5a7ea8d631b7/vllm/entrypoints/openai/api_server.py

RUN pip install "fschat[model_worker,webui]"

RUN pip install typing-inspect==0.8.0 typing_extensions==4.5.0 
RUN pip install ray

# Modify the vllm_worker.py file
RUN sed -i 's/from vllm import AsyncLLMEngine/from vllm.engine.async_llm_engine import AsyncLLMEngine/' /usr/local/lib/python3.8/dist-packages/fastchat/serve/vllm_worker.py

COPY start_server.sh /app
CMD [ "/bin/bash" ]
```

**Comment by idealover** [comment]
The H100 you use comes with CUDA 11.8 or 12.0? I have been getting CUDA compatibility issues :(

**Comment by deroholic** [comment]
> The H100 you use comes with CUDA 11.8 or 12.0? I have been getting CUDA compatibility issues :(

I've used both but mostly 12.2.  IIRC, I only dropped to 11.8 to keep VLLM and its dependencies happy.

**Comment by hmellor** [comment]
Closing as resolved.
