### ISSUE TITLE
[Usage]: Using a model for inference and embedding

### ISSUE THREAD

**Issue by micuentadecasa** [vllm-project/vllm#9702]
### Anything you want to discuss about vllm.

Hi, I would like if it is possible to use the same model for inference and embedding at the same time with only a VLLM instance? for example the e5-mistral-7b-instruct can do both, can I use it for both tasks at the same time?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
No, this is not possible in vLLM. You will have to run two separate instances.

**Comment by micuentadecasa** [comment]
Many thanks @DarkLight1337 for your support.

**Comment by micuentadecasa** [comment]
Closed.
