### ISSUE TITLE
[Bug]: "Address already in use" for 1 minute after crash (since 0.6.2)

### ISSUE THREAD

**Issue by hibukipanim** [vllm-project/vllm#9737]
### 🐛 Describe the bug

Since version 0.6.2 (happens also in 0.6.3.post1), after the server dies (due to an exception/crash or hitting ctrl-c), for about a minute, it fails to start again with:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 585, in <module>
    uvloop.run(run_server(args))
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/home/user/code/debug/.venv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 544, in run_server
    sock.bind(("", args.port))
OSError: [Errno 98] Address already in use
```
This prolongs recovery from crashes. In example upon crash Kubernetes immediately restarts the container - previously it would immediately start loading the model again, but now it will do several crash/restart loops until the port is freed.

Verified it happens also with `--disable-frontend-multiprocessing`.

To reproduce it, start vllm with default args, in example:
```
python -m vllm.entrypoints.openai.api_server --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
```
and then send at least one chat or completion request to it (without this it won't reproduce).
then hit Ctrl-C to kill the server.
starting vllm again should throw the "Address already in use" error.
This doesn't happen with vllm <= 0.6.1.

I tried to see why the port is busy, and interestingly the vllm process is dead during this ~1 minute and no other process listens on it. However I noticed that there is a socket open *from* the 8000 port. Can see it via:
```
netstat | grep  ':8000'
```
which would show something like:
```
tcp        0      0 localhost:8000          localhost:40452         TIME_WAIT   -
tcp        0      0 localhost:8000          localhost:56324         TIME_WAIT   -
tcp        0      0 localhost:8000          localhost:40466         TIME_WAIT   -
```
After a minute these entries will disappear and then also vllm will manage to start.
I couldn't attribute it to a PID, nor with various `nestat` or `lsof` flags. Maybe it remains open in the kernel due to unclean process exit?

**Comment by yansh97** [comment]
I encountered the same issue, but it seems to only occur in the Docker container. I haven’t experienced this issue on the bare server.

**Comment by hibukipanim** [comment]
@yansh97 👍 
In the description above I reproduce it also by running locally the pip package in WSL (and it also happens in Kubernetes, not in WSL)

**Comment by pseudotensor** [comment]
Ya ever since some version, maybe 0.6.1 or so, always see this, constant problem, eventually in docker with restart always it comes up, but annoying.

**Comment by russellb** [comment]
The original report says

> (due to an exception/crash or hitting ctrl-c)

Can someone confirm they see this with ctrl-c (not in docker) ? In my testing with exiting that way, the process cleans up properly before exiting.

I'm guessing this is happening when `vllm` is not given a chance to exit cleanly. Can you clarify exactly how you're running vllm and exiting?

**Comment by pseudotensor** [comment]
Issue is not exit cleanly, first time docker comes up, fails randomly with this and repeats about 5-15 times before finally coming up.

I think it's a race inside vLLM itself.

**Comment by yansh97** [comment]
> The original report says 原始报告说
> 
> > (due to an exception/crash or hitting ctrl-c)（由于异常/崩溃或按 Ctrl-C）
> 
> Can someone confirm they see this with ctrl-c (not in docker) ? In my testing with exiting that way, the process cleans up properly before exiting.有人可以确认他们使用 ctrl-c（不在 docker 中）看到这一点吗？在我以这种方式退出的测试中，该过程在退出之前正确清理。
> 
> I'm guessing this is happening when `vllm` is not given a chance to exit cleanly. Can you clarify exactly how you're running vllm and exiting?我猜这是在没有机会干净地退出时发生的。您能澄清一下您是如何运行 vllm 和退出的吗？

I’ve only encountered this issue inside a Docker container. The ways to exit include pressing Ctrl+C, sending SIGINT or SIGTERM to the process from outside, or sending SIGINT or SIGTERM to itself within the Python code.

**Comment by wakk** [comment]
can I use `sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)` reused address to solve the problem ?
```
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(("", args.port))
```

**Comment by hibukipanim** [comment]
@russellb to double-check, did you send at least one chat completion request to the server before killing it with ctrl-c? it is required to reproduce 🙏

**Comment by russellb** [comment]
> @russellb to double-check, did you send at least one chat completion request to the server before killing it with ctrl-c? it is required to reproduce 🙏

I did, yes, using `curl`

**Comment by hibukipanim** [comment]
@russellb I also couldn't reproduce it with `curl` now! so seems it is related to the client also. I managed to reproduce again with both `openai` client and also with `requests`, with the interesting bit that the client process should keep running after the request. As `requests` has less magic going-on, here is how I managed to reproduce it:

start the vllm server with:
```bash
 python -m vllm.entrypoints.openai.api_server --model TinyLlama/TinyLlama-1.1B-Chat-v1.0
```

then run this python script:
```python
import requests
import time

url = "http://localhost:8000/v1/chat/completions"
data = {
    "model": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    "messages": [{"role": "user", "content": "hello"}],
}
res = requests.post(url, json=data)
print(res.json()['choices'][0]['message'])

print("\nsleeping.. try killing vllm now and starting it again")
time.sleep(60)
```

then while the client is running (few seconds after the chat request), kill the vllm server with ctrl-c, and try starting vllm again (which should now fail with `OSError: [Errno 98] Address already in use`). 
And during the first minute can still see the outgoing connection from port 8000 in netstat:
`netstat | grep  ':8000'`:
```
tcp        0      0 localhost:8000          localhost:42454         FIN_WAIT2
```
(I also noticed that the client process doesn't have to stay up for the whole minute, it's enough to wait few seconds until the connection in netstat shows `FIN_WAIT2` - then even if it's killed, the vlllm server still would fail to use the port during the first minute)

**Comment by russellb** [comment]
> @russellb I also couldn't reproduce it with `curl` now! so seems it is related to the client also. I managed to reproduce again with both `openai` client and also with `requests`, with the interesting bit that the client process should keep running after the request. As `requests` has less magic going-on, here is how I managed to reproduce it using it:

In this case I think `requests` is not closing the connection.  Try this change to your script:

```python
#with requests.post(url, json=data) as res:
#    print(res.json()['choices'][0]['message'])

with requests.session() as s:
    s.headers['Connection'] = 'close'
    res = s.post(url, json=data)
    print(res.json()['choices'][0]['message'])
```

With that change, I don't see a connection hanging open.

**Comment by hibukipanim** [comment]
It is reproducing for me despite this change above 🤔 (as long as the client process stays up for few seconds)

I think it's very common scenario that the clients are still up when the server is crashing/exiting. This is also the default behavior of the openai client - it's actually recommended in the openai docs to create a client object once and then reuse it for multiple chat requests (but don't know if internally it keeps sockets up or not).
e.g. this also reproduces it:
```python
import openai
import time

client = openai.OpenAI(
    base_url="http://localhost:8000/v1",
    api_key="foo"
)

response = client.chat.completions.create(
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    messages=[{"role": "user", "content": "hello"}],
)
print(response.choices[0].message)
time.sleep(5)
```

The client is not listening on the 8000 port, so I don't see why would the server fail to listen on it again after restart. And this didn't happen before 0.6.2.

**Comment by russellb** [comment]
Thanks for all the info. I dug into this more closely today. The change in behavior was introduced by #8537. I'm still working on a fix.

**Comment by russellb** [comment]
Please try out #10012 and let me know if it fixes the problem for you. It appears to resolve it for me.

**Comment by pseudotensor** [comment]
I still hit this infinite loop on latest vllm.

```

INFO 02-27 19:28:10 __init__.py:207] Automatically detected platform cuda.
INFO 02-27 19:28:10 api_server.py:912] vLLM API server version 0.7.3
INFO 02-27 19:28:10 api_server.py:913] args: Namespace(host='0.0.0.0', port=5001, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='mistralai/Pixtral-12B-2409', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='mistral', trust_remote_code=False, allowed_local_media_path=None, download_dir='/home/paperspace/.cache/huggingface/hub', load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=49152, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=1234, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=6, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=True, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt={'image': 8}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, disable_log_requests=False, max_log_len=100, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 991, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 935, in run_server
    sock = create_server_socket(sock_addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 906, in create_server_socket
    sock.bind(addr)
OSError: [Errno 98] Address already in use

```

**Comment by miko8422** [comment]
> I still hit this infinite loop on latest vllm.
> 
> ```
> 
> INFO 02-27 19:28:10 __init__.py:207] Automatically detected platform cuda.
> INFO 02-27 19:28:10 api_server.py:912] vLLM API server version 0.7.3
> INFO 02-27 19:28:10 api_server.py:913] args: Namespace(host='0.0.0.0', port=5001, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='mistralai/Pixtral-12B-2409', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='mistral', trust_remote_code=False, allowed_local_media_path=None, download_dir='/home/paperspace/.cache/huggingface/hub', load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=49152, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=1234, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=6, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=True, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt={'image': 8}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, disable_log_requests=False, max_log_len=100, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 991, in <module>
>     uvloop.run(run_server(args))
>   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
>     return __asyncio.run(
>            ^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
>   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
>     return await main
>            ^^^^^^^^^^
>   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 935, in run_server
>     sock = create_server_socket(sock_addr)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 906, in create_server_socket
>     sock.bind(addr)
> OSError: [Errno 98] Address already in use
> ```

Same, still looking for solution, may I ask if you solved the problem? I will come back if I find a way out...
