### ISSUE TITLE
[Feature]: OpenAI supply image path

### ISSUE THREAD

**Issue by SinanAkkoyun** [vllm-project/vllm#9742]
### 🚀 The feature, motivation and pitch

Hi! I need a low-latency vision API endpoint. The current vLLM endpoint takes about 200ms (100ms for smaller images) to process a base64 image (provided via `image_url` as base64). I need to cut that number down to almost zero

(I checked it against cached web URL images which have almost no latency)

Would it be possible to implement that one can also supply an absolute path to an image? All my images are local anyways.

### Alternatives

The alternative would be to somehow optimize the base64 parsing, but I don't know if that's possible

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
See #8730

**Comment by SinanAkkoyun** [comment]
Awesome, thank you 😊
