### ISSUE TITLE
Not able to use fine tunned model uploaded on higgingface

### ISSUE THREAD

**Issue by Swapnil04062000** [vllm-project/vllm#978]
I have fine tuned llama 7b and falcon 7b models on Auto train of hugging face and both models are uploaded on hogging face on public repository but while loading the model in VLLM I am getting following error

oserror : swapnilborude/falcon_7b_autotrain does not appear to have a file named config.json.

I have then tried  uploading config.json file from  tiiuae/falcon-7b but still I am getting the same issue
Any help on this will be really appreciable 
Thank you so much

**Comment by satyaloka93** [comment]
Curious about this as well, tried the Nous-Hermes 13B model and got the same message. I'm guessing it's only for specific named models and no others.

**Comment by Swapnil04062000** [comment]
> Curious about this as well, tried the Nous-Hermes 13B model and got the same message. I'm guessing it's only for specific named models and no others.

Hey Thanks for addressing this..Can you suggest few models for which you are not getting this issue?

**Comment by WoosukKwon** [comment]
@Swapnil04062000 Could you try
```python
AutoModelForCausalLM.from_pretrained("swapnilborude/falcon_7b_autotrain", ...)
```
on your machine and let us know whether it works?

If it doesn't work, that means your HF repository structure is somehow invalid.

BTW, you don't have to upload your model to HF repo to use vLLM. You can simply provide the path to your local model instead of the repo in HF model hub.

**Comment by Swapnil04062000** [comment]
@WoosukKwon sure I will try and let you know. Thank you so much

**Comment by Swapnil04062000** [comment]
@WoosukKwon  I have tried your suggestions but facing the below issue, 
swapnilborude/falcon_7b_autotrain does not appear to have a file named config.json.

**Comment by Swapnil04062000** [comment]
@WoosukKwon while tuning the model using auto train ..package have not generated any config.json file. So do we need to make it manually? any idea?
