### ISSUE TITLE
[Bug]: The Qwen series models produce garbled output when generating long texts.

### ISSUE THREAD

**Issue by hongqing1986** [vllm-project/vllm#9825]
### Your current environment

vLLM version: v0.6.3.post1

### 🐛 Describe the bug

In the latest version v0.6.3.post1, when generating long texts (for example, when the number of tokens reaches 21,000), the generated content is basically garbled. Additionally, after verifying, the long text functionality in v0.6.2 works correctly using the qwen2-7b-instruct model. Furthermore, I also tested other models like qwen2.5-72b-instruct, which exhibit the same problem.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Perhaps similar to https://github.com/vllm-project/vllm/issues/9769

**Comment by frei-x** [comment]
+1

**Comment by DarkLight1337** [comment]
Can you try again using the latest version? Supposedly it should be fixed since #9826.

**Comment by frei-x** [comment]
> Can you try again using the latest version? Supposedly it should be fixed since #9826.

When will 0.6.4 be released?
