### ISSUE TITLE
> **Bug**:Interesting finding: The official pip package v0.6.3 is broken. However, installing `https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl` fixes this issue. (`vLLM API server version 0.6.3.post2.dev139+g622b7ab9`)

### ISSUE THREAD

**Issue by Wiselnn570** [vllm-project/vllm#9828]
> Interesting finding: The official pip package v0.6.3 is broken. However, installing `https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl` fixes this issue. (`vLLM API server version 0.6.3.post2.dev139+g622b7ab9`)

@SinanAkkoyun What does python 3.10.15 should install, seemly I meet the same issue, thanks a lot!!

_Originally posted by @Wiselnn570 in https://github.com/vllm-project/vllm/issues/9732#issuecomment-2445843188_

**Comment by Wiselnn570** [comment]
When I run
```bash
pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl
```
I get 
```python
...

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)
```

**Comment by SinanAkkoyun** [comment]
Hi, in what environment are you running?
I created a new env: `conda create python=3.11 -n vllm`
Then I simply ran `pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl`
If you run into issues you could also try to first run `pip install vllm` and then the dev installation

**Comment by Wiselnn570** [comment]
> Hi, in what environment are you running? I created a new env: `conda create python=3.11 -n vllm` Then I simply ran `pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl` If you run into issues you could also try to first run `pip install vllm` and then the dev installation

@SinanAkkoyun I was able to successfully install vllm via pip, but I’m unable to install the package from this specific URL: https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl. My Python version is 3.10.15, and I’m unsure if the issue is caused by differences in GCC versions. Currently, my GCC version is 9.4.0.

**Comment by Wiselnn570** [comment]
> Hi, in what environment are you running? I created a new env: `conda create python=3.11 -n vllm` Then I simply ran `pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl` If you run into issues you could also try to first run `pip install vllm` and then the dev installation

Thanks, have solved yet.
