### ISSUE TITLE
[Feature]: Public binary release supports torch 2.5.1

### ISSUE THREAD

**Issue by luohao123** [vllm-project/vllm#9830]
### 🚀 The feature, motivation and pitch

The new torch public release is 2.5.1 now.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
closed by https://github.com/vllm-project/vllm/pull/10001
