### ISSUE TITLE
[Bug]: api_server.py: error: unrecognized arguments: --task embedding

### ISSUE THREAD

**Issue by javiplav** [vllm-project/vllm#9840]
### Your current environment

I'm running in a Kubernetes environment vllm docker image vllm/vllm-openai:latest . 

The latest version is supposed to support --task embedding flag. https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html 

### 🐛 Describe the bug

I start the server with the following command: `python3 -m vllm.entrypoints.openai.api_server ` and arguments: `--served-model-name BAAI/bge-m3 --enforce-eager --task embedding` . 

The pod fails to run. **Error message:** `api_server.py: error: unrecognized arguments: --task embedding `

Any suggestions please?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
I think `--task embedding` is only supported on main branch atm. You'll have to clone the repository and build it from source to use it.

**Comment by javiplav** [comment]
@DarkLight1337 thanks for your reply. I'm using https://hub.docker.com/layers/vllm/vllm-openai/latest/images/sha256-facbbd4a92c1754675b239a5f22a281ed3aa8bde64662db8919d85d670673aa7?context=explore .

**Comment by DarkLight1337** [comment]
It looks like the "latest" Docker image there refers to the most recently released version, so it's not the one from main branch.

**Comment by DarkLight1337** [comment]
Please follow [these instructions](https://docs.vllm.ai/en/latest/getting_started/installation.html#install-the-latest-code) for the latest code.

**Comment by javiplav** [comment]
Thanks @DarkLight1337 . Managed to run the server with the main branch. 

Unfortunately I didn't succeed in running bge-m3 as it seems that vllm doesn't support xlm-roberta architectures.

**Comment by DarkLight1337** [comment]
Oh, I completely missed that you were trying to run bge-m3. Can you move over to #9847 ?
