### ISSUE TITLE
[Feature]: Pipeline Parallelism support for the IBM Granite models 

### ISSUE THREAD

**Issue by rcarrata** [vllm-project/vllm#9844]
### 🚀 The feature, motivation and pitch

From the [distributed serving and inference docs](https://docs.vllm.ai/en/latest/serving/distributed_serving.html#details-for-distributed-inference-and-serving), it seems that currently, vllm only supports LLaMa, GPT2, Mixtral, Qwen, Qwen2, and Nemotron style models.

`NotImplementedError: Pipeline parallelism is only supported for the following architectures: ['AquilaModel', 'AquilaForCausalLM', 'DeepseekV2ForCausalLM', 'InternLMForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MistralForCausalLM', 'Phi3ForCausalLM', 'GPT2LMHeadModel', 'MixtralForCausalLM', 'NemotronForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'QWenLMHeadModel'].`

Adding Granite models would benefit teams and projects working with these model types, allowing them to scale out their workloads efficiently and maintain performance as model sizes continue to grow.

Thanks in advance!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
it should be supported already, see https://docs.vllm.ai/en/latest/models/supported_models.html
