### ISSUE TITLE
[New Model]: BAAI/bge-m3

### ISSUE THREAD

**Issue by javiplav** [vllm-project/vllm#9847]
### The model to consider.

https://huggingface.co/BAAI/bge-m3

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by rpvelloso** [comment]
+1

This model works well with portuguese language, would be great to have it under the openai API.
