### ISSUE TITLE
[help wanted]: add sliding window support for flashinfer 

### ISSUE THREAD

**Issue by youkaichao** [vllm-project/vllm#9854]
### Anything you want to discuss about vllm.

flashinfer already supports sliding window in https://github.com/flashinfer-ai/flashinfer/issues/159 , and we should update our code and pass sliding window to flashinfer , to remove this restriction: 

https://github.com/vllm-project/vllm/blob/5f8d8075f957d5376b2f1cc451e35a2a757e95a5/vllm/attention/backends/flashinfer.py#L739-L740

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
@elfiegg I see your great contribution in https://github.com/vllm-project/vllm/pull/9781 , would you like to take this?

if anyone else is interested, contribution is extremely welcome.

**Comment by elfiegg** [comment]
Hey Kaichao - sorry for the delay! I can help take a look later this week if it's not urgent.

**Comment by youkaichao** [comment]
@elfiegg thank you!

**Comment by renjie0** [comment]
Does it support interleaved sliding window attention which is used in gemma2
