### ISSUE TITLE
It seems that SamplingParams doesnt support the bad_words_ids parameter when generating

### ISSUE THREAD

**Issue by mengban** [vllm-project/vllm#986]
`bad_words_ids` described [here](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/configuration_utils.py#L145C11-L145C11) is useful for production applications.
However It seems that vlllm doesnt support the bad_words_ids parameter when generating.
Is there a plan to support it?
```
  bad_words_ids(`List[List[int]]`, *optional*):
  List of list of token ids that are not allowed to be generated. Check
  [`~generation.NoBadWordsLogitsProcessor`] for further documentation and examples.
```

**Comment by David-Lee-1990** [comment]
any comment?

**Comment by whitepapercg** [comment]
Up

**Comment by Alvant** [comment]
I hope this can be a possible bad_words_ids stuff implementation: https://github.com/vllm-project/vllm/pull/5986.
