### ISSUE TITLE
Why is num_prompts set to 1000?

### ISSUE THREAD

**Issue by ayrnb** [vllm-project/vllm#987]
On A100 80G, when I set num_prompt to a larger value, the output displays better performance, as shown below. Why did the official documentation set num_prompt to 1000, and what is the significance of this setting?
![image](https://github.com/vllm-project/vllm/assets/70835312/d76d5dc2-02e3-4aa1-8e81-4ae4db2d9935)

**Comment by hmellor** [comment]
When more prompts are in the queue, vLLM is able to make more optimal planning decisions about how to process all of these prompts as fast as possible.

Therefore, as you increase the number of prompts, the throughput performance improves up to a maximum theoretical performance.
