### ISSUE TITLE
[Bug]: ValueError: XFormers does not support attention logits soft capping for GPU Quadro RTX 4000

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#9922]
### Your current environment

vllm version: 0.6.3.post1

gpu type: Quadro RTX 4000

### 🐛 Describe the bug

I try to use gamme series such as `google/gemma-2-27b-it` in the vllm offline batch inference, but it seems that gemma is not supported for this GPU type ?
any other methods to solve it ?
thanks.

> [rank0]: Traceback (most recent call last):
> [rank0]:   File "/home/yanan/test_vllm.py", line 11, in <module>
> [rank0]:     llm = LLM(model= args.llm_name, dtype='half', max_model_len= 4096, 
> [rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
> [rank0]:     self.llm_engine = LLMEngine.from_engine_args(
> [rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 573, in from_engine_args
> [rank0]:     engine = cls(
> [rank0]:              ^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 334, in __init__
> [rank0]:     self.model_executor = executor_class(
> [rank0]:                           ^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
> [rank0]:     super().__init__(*args, **kwargs)
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 47, in __init__
> [rank0]:     self._init_executor()
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 111, in _init_executor
> [rank0]:     self._run_workers("load_model",
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/multiproc_gpu_executor.py", line 192, in _run_workers
> [rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
> [rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/worker.py", line 183, in load_model
> [rank0]:     self.model_runner.load_model()
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1058, in load_model
> [rank0]:     self.model = get_model(model_config=self.model_config,
> [rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
> [rank0]:     return loader.load_model(model_config=model_config,
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 1145, in load_model
> [rank0]:     model = _initialize_model(model_config, self.load_config,
> [rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 175, in _initialize_model
> [rank0]:     return build_model(
> [rank0]:            ^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 160, in build_model
> [rank0]:     return model_class(config=hf_config,
> [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/gemma2.py", line 423, in __init__
> [rank0]:     self.model = Gemma2Model(config, cache_config, quant_config)
> [rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/gemma2.py", line 267, in __init__
> [rank0]:     self.start_layer, self.end_layer, self.layers = make_layers(
> [rank0]:                                                     ^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 419, in make_layers
> [rank0]:     [PPMissingLayer() for _ in range(start_layer)] + [
> [rank0]:                                                      ^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/utils.py", line 420, in <listcomp>
> [rank0]:     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
> [rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/gemma2.py", line 269, in <lambda>
> [rank0]:     lambda prefix: Gemma2DecoderLayer(int(prefix.split(".")[
> [rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/gemma2.py", line 185, in __init__
> [rank0]:     self.self_attn = Gemma2Attention(
> [rank0]:                      ^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/model_executor/models/gemma2.py", line 151, in __init__
> [rank0]:     self.attn = Attention(self.num_heads,
> [rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/attention/layer.py", line 86, in __init__
> [rank0]:     self.impl = impl_cls(num_heads, head_size, scale, num_kv_heads,
> [rank0]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [rank0]:   File "/home/yanan/anaconda3/envs/vllm/lib/python3.11/site-packages/vllm/attention/backends/xformers.py", line 425, in __init__
> [rank0]:     raise ValueError(
> [rank0]: ValueError: XFormers does not support attention logits soft capping.

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by HelloCard** [comment]
export VLLM_ATTENTION_BACKEND=FLASHINFER
set the Global variables，and install flashinfer.
then vllm will use flashinfer rather than XFormers, and "XFormers does not support attention logits soft capping" will solved.

**Comment by yananchen1989** [comment]
> export VLLM_ATTENTION_BACKEND=FLASHINFER set the Global variables，and install flashinfer. then vllm will use flashinfer rather than XFormers, and "XFormers does not support attention logits soft capping" will solved.

@HelloCard  thanks.
can I use other backend such as `FLASH_ATTN` ? 

https://docs.vllm.ai/en/stable/serving/env_vars.html

**Comment by yananchen1989** [comment]
it looks like that `FLASHINFER` is also FlashAttention .
after i set it to `VLLM_ATTENTION_BACKEND`, 
there is error: 
> RuntimeError: Error in model execution: FlashAttention only supports Ampere GPUs or newer.

So i guess the root reason is that my GPU is out of date as it is Turing .

**Comment by HelloCard** [comment]
> it looks like that `FLASHINFER` is also FlashAttention . after i set it to `VLLM_ATTENTION_BACKEND`, there is error:
> 
> > RuntimeError: Error in model execution: FlashAttention only supports Ampere GPUs or newer.
> 
> So i guess the root reason is that my GPU is out of date as it is Turing .

Yes, Turing does not support FLASH-ATTN, which is currently the fundamental reason why vllm inference gemma2 cannot be used on Turing architecture graphics cards: https://github.com/vllm-project/vllm/issues/8189#issuecomment-2332350166

**Comment by yananchen1989** [comment]
@HelloCard  thanks. make sense.
