### ISSUE TITLE
[Bug]: from vllm.platforms import current_platform infinite loop error with OpenVino Build. 

### ISSUE THREAD

**Issue by CalebXDonoho** [vllm-project/vllm#9939]
### Your current environment

Unrelated

### Model Input Dumps

Unrelated

### 🐛 Describe the bug

In OpenVino Build, from vllm.platforms import current_platform for OpenVino will...
 * reference openvino.py in vllm.platforms.openvino.py as OpenVino is identified as current platform
 * openvino.py line 4 will reference from vllm.utils import print_warning_once
 * vllm.utils line 40 will reference from vllm.platforms import current_platform
 * Due to circular self-reference, will throw error

This impacts any vllm functionality on the openvino build due to vllm requiring detection of the current_platform.

Resolution: **removing print_warning_once dependency from openvino.py will fix, either by defining print function locally or removing logging altogether from openvino.py**

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @wangshuai09
