### ISSUE TITLE
Please add support for GPTQ models

### ISSUE THREAD

**Issue by ryanshrott** [vllm-project/vllm#994]
I'd love to run this model with VLLM, but I get an error currently due to quantization! 
https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ

**Comment by ryanshrott** [comment]
Will this be added to main VLLM package soon?

I get this error now:
llm = LLM(model="rshrott/description-awq-4bit")

RuntimeError: Cannot find any model weights with `rshrott/description-awq-4bit`

**Comment by casper-hansen** [comment]
You have to pass in the kwarg for quantization 

`llm = LLM(model="rirv938/wizard-vicuna-13b-uncensored-awq-4bit-g128", **{'quantization': 'awq'}) `

**Comment by ryanshrott** [comment]
Thanks. How do I compile the PR? Is this not currently available for general usage?

**Comment by ryanshrott** [comment]
I'm trying to do in google colab:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-f4e5b34c0a3e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 llm = LLM(model="rshrott/description-awq-4bit", **{'quantization': 'awq'})

[/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/llm.py](https://localhost:8080/#) in __init__(self, model, tokenizer, tokenizer_mode, trust_remote_code, tensor_parallel_size, dtype, seed, **kwargs)
     54         if "disable_log_stats" not in kwargs:
     55             kwargs["disable_log_stats"] = True
---> 56         engine_args = EngineArgs(
     57             model=model,
     58             tokenizer=tokenizer,

TypeError: EngineArgs.__init__() got an unexpected keyword argument 'quantization'

**Comment by pvtoan** [comment]
Hi @ryanshrott, 

1. If you are using VLLM via LangChain, so, the correct code is as follows.

from langchain.llms import VLLM
model = VLLM(model=model_path, tensor_parallel_size=1, trust_remote_code=True, vllm_kwargs={"quantization": "awq"})

2. Other case, you use vllm directly, the command is as given
from vllm import LLM
model = LLM(model=model_path, tensor_parallel_size=1, tokenizer=model_path, trust_remote_code=True, quantization='awq')
