### ISSUE TITLE
[Usage]: Can I use model parallelism? I faced a problem that OOM when 1 gpu, even though I have multi-gpu

### ISSUE THREAD

**Issue by divided7** [vllm-project/vllm#9977]
### Your current environment

```text
The output of `python collect_env.py`
```

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.
The model(int4) needs about 20GB CUDA Memory, I have 2 * 3080Ti(2 * 12GB), can I run the model in this machine?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by russellb** [comment]
The option for this is `--tensor-parallel-size`.

**Comment by divided7** [comment]
> The option for this is `--tensor-parallel-size`.

But the `--tensor-parallel-size` is data parallel rather than model parallel? Maybe I need to split the model to two parts into two GPUs?
