### ISSUE TITLE
[Installation]: Model Architectures FalconMambaForCasualLM are not supported for now.  

### ISSUE THREAD

**Issue by RohithDAces** [vllm-project/vllm#9980]
### Your current environment

The model (tiiuae/falcon-mamba-7b-instruct) is downloaded and getting error while starting the instance. 
![image](https://github.com/user-attachments/assets/6a8033b9-e188-404c-a6b3-db362b13abe2)

### How you are installing vllm

I tried to deploy  falcon-mamba-7b-instruct (tiiuae/falcon-mamba-7b-instruct)model from huggingace by using VLLM. But unfortunately i get an error like model architectures are not available now. 
Then, I ran tiiuae/falcon-7b-instruct model, and it is working fine without any errors.
But, I want to run the tiiuae/falcon-mamba-7b-instructmodel without any errors. How can I fix this? Do I need to change any versions of the VLLM. I already tried with the latest and some other versions. Is there any specific version to use?

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @tlrmchlsmth

**Comment by tlrmchlsmth** [comment]
@RohithDAces Falcon Mamba is available on current `main` but not in any release yet. The next version of vLLM will have it.
