### ISSUE TITLE
[Bug]: internvl “max_dynamic_patch” not work, and add_special_tokens bug 

### ISSUE THREAD

**Issue by wangpeng138375** [vllm-project/vllm#9989]
### Your current environment

<details>
<summary>vllm==0.6.3</summary>

```

```

</details>

### 🐛 Describe the bug

internvl “max_dynamic_patch” not work, and add_special_tokens bug ，and add 'add_special_tokens = False' to https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/internvl.py#L324

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Could you elaborate? What do you mean by it doesn't work?

**Comment by wangpeng138375** [comment]
In internvl, when I set "dynamic_image_size=False" alone, it seems do not work. It seems that I should also need to set "max_dynamic_patch=1" for it to take effect.

**Comment by DarkLight1337** [comment]
@Isotr0py can you take a look at this?
