### ISSUE TITLE
[Bug]: last_token_time is equal to arrival_time

### ISSUE THREAD

**Issue by wolfgangsmdt** [vllm-project/vllm#9998]
### Your current environment

The bug is not related to the envirement

### Model Input Dumps

The bug does not related to the model

### QUESTION 1:
How do you calculate the `RequestMetrics` in `RequestOutput` please look at screen-shot below (in *YELLOW*):

![image](https://github.com/user-attachments/assets/a4ace1ce-e3f1-4acd-8982-3824346829ed)

I have found [here in L. 696](https://github.com/vllm-project/vllm/blob/ccb5376a9a88bb6251c4434b79c173151e6f7729/vllm/sequence.py#L696C39-L696C54) that `last_token_time` is equal to `arrival_time` !!! **IS IT A BUG?**

Could you please tell me what unit is the time is it second? nanosecond? I believe it is something like this example below (***correct me if I am wrong***):
```python
import time
arrival_time = time.perf_counter()
```

### QUESTION 2: 
How can I calculate the **tokens/second (for output)**, **TTFT**, **TBT**, **throughput** and **total time**

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
cc @comaniac

**Comment by wolfgangsmdt** [comment]
> The line you pointed out isn't a bug and isn't the root cause of the issue you're reporting. After all, we don't know the last token time when creating this object upon receiving the request. It will be updated when `seq_group.get_last_latency()` is called, so we should try to understand why it's not being called for the request.

Thanks for the reply.
What do you need from me like informations to help you fix the issue.

**My goal is to have TTFT, TBT and Tokens/second**

Thanks

**Comment by comaniac** [comment]
I don't have bandwidth to look into it now but it shouldn't be hard to fix. Please feel free to submit a PR if you are able to fix it and I'll help review, or I may try to fix that in my spare time (but cannot guarantee any timeline).

**Comment by sri-fiddler** [comment]
@wolfgangsmdt, the `last_token_time` is updated in the following line.

https://github.com/vllm-project/vllm/blob/ccb5376a9a88bb6251c4434b79c173151e6f7729/vllm/sequence.py#L801

But I am curious as to how the time to first token can be calculated. Would it be `arrival_time - first_token_time`?

**Comment by sri-fiddler** [comment]
Yes, @wolfgangsmdt, you're right. I've made the changes on my end too. 

I figured that `last_token_time - first_token_time` would be the time between tokens, however, I get a negative value here, which is surprising.
